(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"300x250_bcd_phone_atlas_", frames: [[0,936,318,67],[0,0,854,934]]}
];


// symbols:



(lib.docBC = function() {
	this.initialize(ss["300x250_bcd_phone_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.volcanoman = function() {
	this.initialize(ss["300x250_bcd_phone_atlas_"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.docBC();
	this.instance.parent = this;
	this.instance.setTransform(-142,-30,0.9,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-142,-30,286.2,60.3);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAOIgFgDIgDgFIgBgGIABgFIADgEIAFgEIAFgCIAGACIAFAEIADAEIABAFIgBAGIgDAFIgFADIgGACg");
	this.shape.setTransform(68.85,120.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_1.setTransform(61.775,114.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXAfIAWhDIAYAKIgdA+g");
	this.shape_2.setTransform(53.65,107.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgHgHQgIgHgMAAQgHAAgIADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_3.setTransform(42.2,115.875);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_4.setTransform(28.375,115.975);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_5.setTransform(18.925,113.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgNAAQgIAAgIAEQgIADgHAGIAABGIARAAIAAAUIg3AAIAAgUIARAAIAAg3QAAgOgHgHQgIgHgMAAQgJAAgHADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIALgBQANAAAJAFQAJAFAGAKIAJgHIAKgHIALgEQAGgCAGAAQAKAAAIADQAIADAGAFQAFAGADAIQADAJgBALIAAA6IASAAIAAAUg");
	this.shape_6.setTransform(-2.3,115.875);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_7.setTransform(-21.075,116.025);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AASA9IAAgUIAGAAIgYgeIgWAeIAGAAIAAAUIgpAAIAAgUIAKAAIAlgqIgigmIgNAAIAAgVIApAAIAAAVIgFAAIAVAcIAXgcIgGAAIAAgVIAoAAIAAAVIgKAAIgiAnIAkApIAJAAIAAAUg");
	this.shape_8.setTransform(-33.775,115.975);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgUA8QgKgFgIgHQgHgJgEgMQgFgLAAgQQAAgNAEgLQADgMAIgJQAHgIALgFQALgFANAAQANAAAJAEQAJAFAHAGQAFAHADAJQADAJABAJIABAJIAAAIIhWAAIABAJIACAIQAEAMAKAGQAJAGALgBQAKABAJgDQAIgDAKgFIAJAPQgMAIgMAEQgMAEgNAAQgLAAgLgEgAAfgNIgCgNQgCgGgEgEQgDgEgGgCQgFgDgIAAQgHAAgGADQgFACgEADQgEAFgDAFQgCAGgBAIIA+AAg");
	this.shape_9.setTransform(-47.35,116);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_10.setTransform(141.925,87.175);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_11.setTransform(131.625,88.975);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_12.setTransform(122.175,86.075);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_13.setTransform(112.475,88.925);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_14.setTransform(102.525,87.175);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgTA8QgLgFgHgHQgIgJgFgMQgDgLAAgQQAAgNADgLQADgMAIgJQAHgIAKgFQALgFANAAQAOAAAKAEQAIAFAGAGQAGAHADAJQADAJACAJIAAAJIAAAIIhWAAIAAAJIADAIQAEAMAJAGQAKAGAMgBQAJABAJgDQAJgDAKgFIAJAPQgMAIgNAEQgMAEgNAAQgLAAgKgEgAAfgNIgCgNQgCgGgDgEQgEgEgFgCQgGgDgIAAQgHAAgFADQgGACgEADQgEAFgCAFQgDAHgBAHIA+AAg");
	this.shape_15.setTransform(90.85,89);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgOAAQgHAAgIAEQgIADgHAGIAABGIARAAIAAAUIg3AAIAAgUIARAAIAAg3QAAgOgHgHQgHgHgNAAQgIAAgIADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIALgBQANAAAKAFQAIAFAGAKIAJgHIAKgHIALgEQAGgCAGAAQAKAAAIADQAIADAGAFQAFAGADAIQACAJAAALIAAA6IASAAIAAAUg");
	this.shape_16.setTransform(72.3,88.875);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_17.setTransform(53.025,88.975);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_18.setTransform(41.525,87.175);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag/BaIAAgUIARAAIAAiHIgRAAIAAgVIAmAAIAAAKQAIgGAJgDQAIgEAKAAQAMAAAKAFQAKAEAHAIQAHAIAEAMQAEALAAAOQAAAOgEANQgFALgHAIQgIAJgLAFQgLAEgNAAQgIAAgIgBIgNgFIAAAnIATAAIAAAUgAgLhCQgIADgFAGIAABBQADAEAIADQAHADAKAAQAHAAAHgCQAHgDAFgGQAGgGADgIQADgIAAgLQAAgLgDgIQgDgIgFgFQgFgGgHgCQgHgDgIAAQgHAAgIADg");
	this.shape_19.setTransform(29.575,91.575);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_20.setTransform(15.175,88.975);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgHgHQgIgHgNAAQgGAAgIADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAFAGAEAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_21.setTransform(-5.15,88.875);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_22.setTransform(-19.925,89.025);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgSIAIAGIAKAEIALAEIALABQAIAAAGgCQAHgDAEgEQAFgFACgIQACgIAAgNIAAgBQgGAGgIADQgIAEgKAAQgLAAgLgEQgLgFgHgHQgIgJgFgMQgEgLAAgQQAAgNAEgMQAEgLAIgJQAIgIALgEQALgFAMAAQAJAAAIADQAHACAHAEIAAgGIAWAAIAAB0QAAAcgOAPQgOAPgcAAgAgJhBQgHACgFAGQgFAFgDAIQgDAIAAAKQAAALACAJQADAIAFAGQAFAFAHAEQAHACAIAAIAKgBIAIgCIAGgFIAFgEIAAhBQgGgGgIgCQgIgCgIgBQgHABgGADg");
	this.shape_23.setTransform(-38.875,91.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgHgHQgIgHgMAAQgIAAgHADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_24.setTransform(-53.55,88.875);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_25.setTransform(-65.225,86.075);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AApBbIgwg2IgQAAIAAAiIAKAAIAAAUIg0AAIAAgUIAUAAIAAiNIgVAAIAAgUIArAAIAAAUIAABaIAVAAIAbgdIgHAAIAAgUIAuAAIAAAUIgPAAIglAlIAoArIAPAAIAAAUg");
	this.shape_26.setTransform(-76.475,85.925);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_27.setTransform(-91.525,88.975);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_28.setTransform(-105.875,88.975);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhBBZIAAgUIAQAAIAAiJIgQAAIAAgUIBOABQALAAAKADQAJAFAHAHQAHAGAEAKQAEAKAAALQAAAKgGAKQgGAKgMAFQAGACAEAEQAFAEADAFQAEAFACAFIABALQAAALgEAKQgEAJgHAIQgHAHgJAEQgKAEgLAAgAgaBFIApAAQAFAAAFgDIAJgHQADgFACgGQACgFAAgGQAAgFgCgFQgCgFgDgEIgJgGQgFgCgFAAIgpAAgAgagJIAoAAQAFgBAFgCQAFgCAEgDQADgEACgFQACgFAAgFQAAgGgCgGQgCgFgDgFQgEgEgFgDQgFgDgFAAIgoAAg");
	this.shape_29.setTransform(-120.425,86.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(-130.8,70,279.3,60), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAOIgFgDIgDgFIgBgGIABgFIADgEIAFgEIAFgCIAGACIAFAEIADAEIABAFIgBAGIgDAFIgFADIgGACg");
	this.shape.setTransform(114,92.65);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgcBYQgLgEgIgIQgIgIgEgMQgEgNAAgPQAAgOAEgLQAEgLAIgIQAHgJALgEQALgFAOABQAHAAAIACQAHABAHAGIAAgvIgRAAIAAgVIAmAAIAACiIASAAIAAAUIgnAAIAAgKQgGAGgIADQgIAEgJAAQgMAAgKgFgAgSgLQgHACgFAGQgFAEgDAJQgDAHAAALQAAALADAJQADAIAFAGQAFAGAHADQAHADAIAAQAJAAAHgDQAGgDAGgGIAAhCQgGgFgIgDQgHgCgHAAQgIAAgHADg");
	this.shape_1.setTransform(104.025,85.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_2.setTransform(90.775,87.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_3.setTransform(78.475,88.025);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAMBbIAAgUIAQAAIAAg3QAAgOgHgGQgHgIgNAAQgHAAgHAEQgIADgHAFIAABHIASAAIAAAUIg6AAIAAgUIASAAIAAiNIgQAAIAAgUIAmAAIAABKIABAAIAHgGIAJgFIAKgDIAKgBQAJAAAIACQAIADAFAGQAGAFADAJQADAHAAAMIAAA6IASAAIAAAUg");
	this.shape_4.setTransform(64.375,84.925);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_5.setTransform(45.225,87.975);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_6.setTransform(35.775,85.075);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgSIAIAGIAKAEIALAEIALABQAIAAAGgDQAHgBAEgFQAFgFACgIQACgIAAgMIAAgCQgGAGgIAEQgIADgKAAQgLAAgLgEQgLgEgHgJQgIgIgFgMQgEgLAAgQQAAgNAEgMQAEgLAIgJQAIgIALgEQALgFAMAAQAJAAAIACQAHADAHAEIAAgGIAWAAIAABzQAAAegOAOQgOAPgcAAgAgJhBQgHACgFAGQgFAFgDAIQgDAIAAAKQAAALACAJQADAIAFAGQAFAFAHAEQAHACAIAAIAKgBIAIgCIAGgFIAFgEIAAhCQgGgFgIgCQgIgDgIAAQgHAAgGAEg");
	this.shape_7.setTransform(19.175,90.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgHgHQgIgHgMAAQgIAAgHADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_8.setTransform(4.5,87.875);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_9.setTransform(-7.175,85.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_10.setTransform(-15.575,86.175);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AALA+IAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgHAAgHADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJABALIAAA6IAQAAIAAAUg");
	this.shape_11.setTransform(-28.05,87.875);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTA8QgLgFgHgHQgIgJgFgMQgDgMAAgPQAAgNADgLQADgMAIgJQAHgIAKgFQALgFANAAQAOAAAKAEQAIAEAGAHQAGAHADAJQADAJACAJIAAAJIAAAIIhWAAIAAAJIADAIQAEAMAJAGQAKAFAMAAQAJABAJgDQAJgCAKgGIAJAPQgMAIgNAEQgMAEgNAAQgLAAgKgEgAAfgNIgCgNQgCgGgDgEQgEgEgFgDQgGgCgIAAQgHAAgFACQgGADgEADQgEAEgCAGQgDAHgBAHIA+AAg");
	this.shape_12.setTransform(-43.25,88);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_13.setTransform(-55.525,87.925);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_14.setTransform(-67.825,88.025);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag+BZIAAgUIAQAAIAAiJIgQAAIAAgUIBGAAQAMAAAKADQAKADAIAGQAHAGAEAJQAEAJAAAMQAAAKgEAJQgEAIgHAHQgHAGgLADQgKADgMAAIgfAAIAAA/IASAAIAAAUgAgXgMIAfAAQAHAAAGgBQAFgCAEgEQAEgDADgGQACgFAAgHQAAgNgIgHQgIgIgSAAIgcAAg");
	this.shape_15.setTransform(-81.025,85.175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(-91.1,69,209.89999999999998,33), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.volcanoman();
	this.instance.parent = this;
	this.instance.setTransform(-623,190,0.49,0.49);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-623,190,418.5,457.70000000000005), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgYA7QgIgCgFgGQgFgGgDgIQgDgJAAgLIAAg5IgQAAIAAgVIAnAAIAABLQAAAOAGAHQAHAHAMAAQAGAAAIgCQAIgDAHgFIAAhIIgQAAIAAgVIAnAAIAABlIANAAIAAAUIgjAAIAAgLQgIAGgKADQgKAEgKAAQgJAAgHgDg");
	this.shape.setTransform(197.525,49.075);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_1.setTransform(183.025,48.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AglBYIAAgUIAPAAIAMghIgohmIgKAAIAAgUIAuAAIAAAUIgOAAIAcBMIAdhMIgPAAIAAgUIAvAAIAAAUIgNAAIg1CHIAQAAIAAAUg");
	this.shape_2.setTransform(168.65,51.725);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgcBYQgLgEgIgIQgIgJgEgMQgEgMAAgPQAAgOAEgMQAEgKAIgIQAHgIALgFQALgFAOAAQAHAAAIADQAHACAHAEIAAguIgRAAIAAgUIAmAAIAAChIASAAIAAAUIgnAAIAAgKQgGAGgIADQgIADgJAAQgMAAgKgEgAgSgLQgHADgFAFQgFAFgDAHQgDAJAAAKQAAALADAIQADAJAFAGQAFAGAHADQAHACAIAAQAJAAAHgCQAGgDAGgGIAAhCQgGgGgIgCQgHgCgHAAQgIAAgHADg");
	this.shape_3.setTransform(149.625,46.05);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_4.setTransform(138.425,46.075);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgcBYQgLgEgIgIQgIgJgEgMQgEgMAAgPQAAgOAEgMQAEgKAIgIQAHgIALgFQALgFAOAAQAHAAAIADQAHACAHAEIAAguIgRAAIAAgUIAmAAIAAChIASAAIAAAUIgnAAIAAgKQgGAGgIADQgIADgJAAQgMAAgKgEgAgSgLQgHADgFAFQgFAFgDAHQgDAJAAAKQAAALADAIQADAJAFAGQAFAGAHADQAHACAIAAQAJAAAHgCQAGgDAGgGIAAhCQgGgGgIgCQgHgCgHAAQgIAAgHADg");
	this.shape_5.setTransform(127.125,46.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_6.setTransform(107.075,48.975);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgRIAIAFIAKAFIALACIALABQAIAAAGgCQAHgCAEgEQAFgFACgIQACgIAAgMIAAgCQgGAGgIAEQgIADgKAAQgLAAgLgEQgLgEgHgJQgIgIgFgMQgEgLAAgPQAAgOAEgMQAEgLAIgIQAIgJALgFQALgEAMAAQAJAAAIACQAHADAHAFIAAgHIAWAAIAABzQAAAdgOAQQgOAOgcAAgAgJhCQgHADgFAFQgFAGgDAIQgDAIAAALQAAALACAIQADAIAFAGQAFAFAHAEQAHACAIAAIAKgBIAIgDIAGgEIAFgEIAAhCQgGgFgIgDQgIgBgIgBQgHAAgGADg");
	this.shape_7.setTransform(92.625,51.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_8.setTransform(79.175,49.025);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgRIAIAFIAKAFIALACIALABQAIAAAGgCQAHgCAEgEQAFgFACgIQACgIAAgMIAAgCQgGAGgIAEQgIADgKAAQgLAAgLgEQgLgEgHgJQgIgIgFgMQgEgLAAgPQAAgPAEgLQAEgMAIgHQAIgJALgFQALgEAMAAQAJAAAIACQAHADAHAEIAAgGIAWAAIAABzQAAAdgOAPQgOAPgcAAgAgJhCQgHADgFAFQgFAGgDAIQgDAIAAALQAAALACAIQADAIAFAGQAFAFAHAEQAHACAIAAIAKgBIAIgCIAGgFIAFgEIAAhCQgGgFgIgDQgIgCgIAAQgHAAgGADg");
	this.shape_9.setTransform(205.725,25.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgHgHQgIgHgNAAQgGAAgIADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAFAGAEAIQACAJAAALIAAA6IASAAIAAAUg");
	this.shape_10.setTransform(191.05,22.875);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_11.setTransform(175.775,22.975);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcBbIAAgUIASAAIAAiNIgSAAIAAgUIAmAAIAAChIATAAIAAAUg");
	this.shape_12.setTransform(164.875,19.925);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAbA+IgbhgIgbBgIgUAAIghhmIgKAAIAAgVIAmAAIAAAVIgGAAIAWBMIAdhhIARAAIAcBhIAWhMIgHAAIAAgVIAmAAIAAAVIgKAAIghBmg");
	this.shape_13.setTransform(145.825,23.075);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_14.setTransform(129.175,22.975);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAMBbIAAgUIAQAAIAAg3QAAgOgHgGQgHgIgNAAQgHAAgHAEQgIADgHAFIAABHIASAAIAAAUIg6AAIAAgUIASAAIAAiNIgQAAIAAgUIAmAAIAABKIABAAIAHgGIAJgFIAKgDIAKgBQAJAAAIACQAIADAFAGQAGAFADAJQADAHAAAMIAAA6IASAAIAAAUg");
	this.shape_15.setTransform(114.325,19.925);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgXAeIAWhCIAYAKIgdA+g");
	this.shape_16.setTransform(96.95,29.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_17.setTransform(87.075,22.975);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgUBZQgLgDgGgGQgHgFgDgHQgEgGgDgHIgJAAIAAgVIAeAAQAAANADAGQACAFAGAEQAFADAGADQAHABAHAAQAIAAAGgBQAHgDAEgDQAFgDACgGQACgFAAgHQAAgGgDgFQgDgFgEgEQgFgEgFgCIgLgDIgZgIQgIgCgHgEQgHgEgFgFQgFgGgDgHQgCgIAAgKQAAgLADgIQAFgJAIgHQAHgGAMgEQALgEANAAQAKAAAIACQAHACAHAEQAGAFAFAFQAGAFACAIIAJAAIAAAUIgcAAQAAgLgEgFQgDgFgFgDQgEgDgGgBIgLgBQgIAAgGACQgHACgEADQgFADgCAFQgCAFAAAFQAAAIADAFQACAFAFADIAJAEIAKADIAWAIQALADAIAEQAIAEAFAGQAGAGADAIQADAHAAAKQAAAMgEAJQgFAJgJAHQgHAHgMAEQgLAEgNAAQgNAAgJgDg");
	this.shape_18.setTransform(73.15,20.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(63.8,4,151.39999999999998,59), null);


(lib.shaker = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgQBLIgFgCIgCgFIgBgFIABgFIADgDIAFgDIAEgBIAFABIADADIADAEIABAFIgBAFIgDAEIgEADIgFAAgAgUAqIACgRIADgNQACgGAEgEIAJgIIAKgHIAHgGQAEgDABgEQACgDAAgFQAAgFgCgEQgBgEgCgDIgHgFQgFgDgEAAQgHAAgGACQgFADgDAEQgEADgBAFIgBAHIgRgCQAAgIAEgHQADgIAGgFQAHgFAIgDQAIgDAJAAQAJABAIADQAHAEAFAFQAFAGADAHQABAHAAAIQAAAKgFAIQgFAIgLAHIgKAHQgHAFgCAHIgDANIgBAMg");
	this.shape.setTransform(173.7,38.9969);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAUA1IgUhRIgZBPIgRAAIgZhWIgIgBIAAgQIAgABIAAAQIgFAAIAPBAIAbhPIAPABIAUBRIAVg/IgGAAIAAgRIAgABIAAARIgJgBIgfBUg");
	this.shape_1.setTransform(159.975,41.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgBA1QgLAAgJgEQgKgEgGgIQgGgHgEgKQgDgKABgLQAAgMAEgKQAEgJAHgHQAHgHAJgDQAKgEAKAAQALABAJAEQAKAEAGAHQAHAHADAKQADAKAAAMQgBALgEAKQgEAKgHAHQgHAGgJAEQgIAEgKAAIgCgBgAgKgjQgFACgFAFQgFAFgCAGQgDAIAAAJQgBAHACAHQADAHAEAGQAEAFAGADQAFADAHAAQAGAAAFgCIALgHQAEgFADgHQADgIAAgIQAAgIgCgIQgCgHgEgFQgEgFgGgCQgGgDgHAAQgFAAgGACg");
	this.shape_2.setTransform(145.9964,40.5503);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgGBNQgKgBgJgDQgIgEgGgHQgHgHgDgKQgDgKAAgNQAAgMAEgKQAEgIAHgGQAHgHAJgDQAJgEALAAIAMACQAGACAGAEIABgmIgOgBIABgRIAgABIgFCGIAPABIgBARIghgBIABgJQgFAFgHADQgFACgGAAIgDAAgAgNgKQgGACgEAFQgFADgCAHQgDAGAAAJQAAAJABAIQADAHAEAFQAEAFAFACQAGADAHAAQAHABAGgDQAFgCAFgEIACg4QgEgFgHgBIgMgDQgGAAgGACg");
	this.shape_3.setTransform(133.9214,37.6792);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAJAyIABgRIAOABIABgtQABgLgFgHQgGgGgLAAQgGAAgGADQgHACgGAFIgCA5IAOABIAAARIgvgCIAAgRIAPABIAChCIgOgBIAAgQIAgABIAAALIAIgFIAHgEIAIgCIAJgBQAIAAAGACQAHADAEAFQAEAEADAHQACAIAAAKIgCAvIAOABIAAAQg");
	this.shape_4.setTransform(120.95,39.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXBKIAAgRIAPAAIAChCIgOgBIAAgQIAgABIgDBTIAPAAIAAARgAAAgyIgEgDIgCgEIgBgFIABgFIADgDIADgDIAFgBIAFABIAEADIACAEIABAFIgBAFIgDAEIgEADIgFAAg");
	this.shape_5.setTransform(111.175,36.925);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAUA1IgUhRIgZBPIgRAAIgZhWIgIgBIAAgQIAgABIAAAQIgFAAIAPBAIAbhPIAPABIAUBRIAVg/IgGAAIAAgRIAgABIAAARIgJgBIgfBUg");
	this.shape_6.setTransform(100.025,38.925);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AglAyIABgRIANAAIADhCIgOgBIABgQIAfABIAAAOIADgGIAFgEIAGgDQAEgCAEAAIAJABIAJABIAAAWIgTgBIAAgHQgEAAgDACQgDABgDACQgDACgCAEQgCAEgBAFIgCAwIAQAAIAAARg");
	this.shape_7.setTransform(83,38.275);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgZAyQgGgDgFgEQgEgEgCgFQgDgGABgGQAAgGACgFQACgFADgDQAEgDAEgDIAJgDIAJgCIAKAAIAKABIAJABIABgIQAAgFgCgEQgBgEgDgDQgDgDgEgBIgHgCIgJABIgIABIgHACIgFACIgGgMIAIgFIAKgCIAJgCIAJgBQAJAAAHADQAHACAFAEQAEAFADAHQACAHAAAJIgCAyIALAAIgBARIgdgBIAAgJQgGAFgHADQgGADgJAAQgHAAgGgDgAgMAFQgEABgEACQgDACgCAEQgCADAAAEIABAHIAEAFIAHAEIAIABIAHgBIAGgCIAGgDIAFgEIABgXIgVgBIgJABg");
	this.shape_8.setTransform(72.6458,37.975);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAAA2QgJgBgJgEQgJgEgGgHQgHgIgDgKQgDgKABgKQAAgMAEgKQAEgKAHgGQAHgIAJgDQAJgEAJAAQAKABAIADQAJAEAGAHIAKAAIgBARIgSAAQgEgIgGgEQgGgDgIgBQgGAAgFADQgGACgFAFQgEAEgCAHQgDAHAAAJQgBAHACAHQADAHAEAGQAEAEAFADQAGADAFAAQAJAAAHgEQAIgEAEgJIAPAIIgIALQgEAFgGADQgFADgHACQgFACgGAAIgDAAg");
	this.shape_9.setTransform(62.1464,37.5772);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAAA1QgJAAgJgEQgJgEgFgGQgHgIgDgKQgDgKABgMQAAgLADgKQAEgJAGgHQAGgHAJgEQAJgEALABQALAAAIAEQAIADAEAGQAFAGACAIQACAHABAIIAAAHIAAAHIhIgDIABAIIABAHQAEAJAHAGQAIAFAJAAQAIABAIgCQAHgCAJgFIAHANQgLAGgKADQgJADgJAAIgDAAgAAagKIgBgLIgEgIQgDgEgFgCQgEgCgHAAQgFgBgFACQgFACgDADQgEADgCAFIgDALIAzACg");
	this.shape_10.setTransform(46.2214,37.0753);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAJBMIABgRIAOAAIABgtQABgMgGgFQgGgGgLgBQgFAAgHADQgGACgGAFIgCA6IAPABIgBARIgwgCIABgRIAPABIAEh1IgOgBIABgRIAgABIgDA+IABAAIAHgFIAHgEIAHgCIAJgBQAIABAHACQAGADAFAEQAEAFADAHQABAHAAAKIgCAvIAQABIgBARg");
	this.shape_11.setTransform(34.175,34.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAJBEQgHAAgEgCQgFgCgDgEQgDgEgCgGQgBgHAAgJIACg3IgQgBIABgOIAQAAIABgYIARgHIgBAgIAYABIgBAOIgYAAIgCA5IABAKQABAEADABIAHACIAHgBIAHgCIAEAMIgKAEIgJABIgDAAg");
	this.shape_12.setTransform(23.875,34.8063);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAJBEQgHAAgEgCQgFgCgDgEQgDgEgCgGQgBgHAAgJIACg3IgQgBIABgOIAQAAIABgYIARgHIgBAgIAYABIgBAOIgYAAIgCA5IABAKQABAEADABIAHACIAHgBIAHgCIAEAMIgKAEIgJABIgDAAg");
	this.shape_13.setTransform(12.175,34.4063);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAXAzIABgJQgIAFgIADQgIADgIgBQgIAAgGgCQgGgDgEgFQgEgFgCgGQgCgIAAgKIACgwIgOAAIAAgQIAhABIgCA+QAAALAEAHQAFAFALABQAFABAGgDIANgFIACg9IgOAAIABgRIAhABIgDBTIALAAIAAARg");
	this.shape_14.setTransform(1.4,35.45);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgBA1QgLAAgJgEQgKgEgGgIQgGgHgEgKQgDgKABgLQAAgMAEgKQAEgKAHgGQAHgHAJgDQAKgEAKAAQALABAJAFQAKADAGAHQAHAHADAKQADAKAAAMQgBALgEAKQgEAKgHAHQgHAGgJAFQgIADgKAAIgCgBgAgKgjQgFADgFAEQgFAEgCAHQgDAIAAAJQgBAHACAIQADAGAEAGQAEAFAGADQAFADAHAAQAGABAFgDIALgHQAEgFADgHQADgIAAgIQAAgIgCgIQgCgHgEgFQgEgEgGgDQgGgDgHAAQgFAAgGACg");
	this.shape_15.setTransform(-10.6536,35.0503);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAAA1QgJAAgJgEQgJgEgFgGQgHgIgDgKQgDgKABgMQAAgLADgKQAEgJAGgHQAGgHAJgEQAJgEALABQALAAAIAEQAIADAEAGQAFAGACAIQACAHABAIIAAAHIAAAHIhIgDIABAIIABAHQAEAJAHAGQAIAFAJAAQAIABAIgCQAHgCAJgFIAHANQgLAGgKADQgJADgJAAIgDAAgAAagKIgBgLIgEgIQgDgEgFgCQgEgCgHAAQgFgBgFACQgFACgDADQgEADgCAFIgDALIAzACg");
	this.shape_16.setTransform(154.5714,20.6753);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAJAyIABgRIAOABIABgtQABgLgGgHQgFgGgLAAQgGAAgGADQgGACgHAFIgCA5IAOABIAAARIgvgBIABgSIANABIADhCIgOgBIAAgQIAhABIgBALIAIgFIAHgEIAHgCIAJgBQAJAAAGADQAHACAEAFQAFAEACAHQACAIAAAKIgCAvIAOAAIgBARg");
	this.shape_17.setTransform(142.35,20.25);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBA1QgLAAgJgEQgKgFgGgHQgGgHgEgKQgDgKABgLQAAgMAEgKQAEgKAHgGQAHgHAJgDQAKgEAKABQALAAAJAEQAKAEAGAHQAHAHADAKQADAKAAAMQgBALgEAKQgEAKgHAHQgHAGgJAEQgIAEgKAAIgCgBgAgKgjQgFACgFAFQgFAEgCAIQgDAHAAAJQgBAIACAGQADAIAEAFQAEAFAGADQAFADAHAAQAGAAAFgCIALgHQAEgFADgHQADgIAAgIQAAgIgCgIQgCgHgEgFQgEgFgGgCQgGgDgHAAQgFAAgGACg");
	this.shape_18.setTransform(129.7964,19.8003);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAJBMIABgRIAOAAIABguQABgLgGgFQgGgGgLAAQgFgBgHADIgMAHIgCA6IAPAAIgBARIgwgBIABgRIAPAAIAEh0IgOgBIABgRIAgABIgDA+IABAAIAHgFIAHgEIAHgCIAJgBQAIAAAHADQAGADAFAEQAEAFADAHQABAGAAAKIgCAwIAQABIgBARg");
	this.shape_19.setTransform(117.275,16.85);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag2BJIAAgRIAOAAIAEhwIgOgBIABgQIAgABIgBAJQAHgFAIgDQAGgDAIABQAKAAAJAEQAIAEAGAHQAGAHACAKQADAJAAALQAAANgFAJQgEAJgGAHQgHAHgKAEQgJADgKAAQgHAAgGgCIgMgEIgBAgIAQABIAAARgAgGg3QgHACgFAFIgCA2QADADAGADQAGADAIAAQAGABAGgDQAGgCAFgEQAEgFADgGQADgHAAgJQAAgJgCgHQgCgHgEgEQgEgFgGgDQgFgCgHgBQgGAAgGADg");
	this.shape_20.setTransform(104.325,21.0964);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgjBJIAAgRIAMAAIAMgbIgfhWIgIAAIAAgQIAnABIgBARIgLgBIAUBBIAbg/IgMAAIAAgRIAnABIgBARIgKAAIgwBuIANAAIgBARg");
	this.shape_21.setTransform(88.3,20.55);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAqA0IABgRIAOAAIACgtQABgLgGgGQgGgHgLAAQgGAAgIADQgGACgGAGIgBA5IANAAIAAARIgugBIAAgRIAPAAIABgtQAAgMgFgFQgGgHgLAAQgGAAgGACQgHADgGAEIgDA7IAPAAIAAARIgvgBIAAgRIAOAAIADhDIgOAAIAAgRIAgABIAAAMIAHgFIAIgEIAIgDIAJgBQALABAIAEQAHAFAEAIIAHgFIAJgGIAKgDQAFgCAFABQAIAAAHADQAGACAFAFQAEAFACAHQACAHAAAKIgCAvIAPAAIgBARg");
	this.shape_22.setTransform(72.65,17.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAUA1IgUhRIgZBPIgRAAIgZhWIgIgBIAAgQIAgABIAAAQIgFAAIAPBAIAbhPIAPABIAUBRIAVg/IgGAAIAAgRIAgABIAAARIgJgBIgfBUg");
	this.shape_23.setTransform(50.375,17.025);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgBA1QgLAAgJgEQgKgFgGgGQgGgIgEgKQgDgKABgLQAAgMAEgKQAEgKAHgGQAHgHAJgDQAKgEAKAAQALABAJAEQAKAEAGAHQAHAHADAKQADAKAAAMQgBALgEAKQgEAKgHAHQgHAHgJADQgIAEgKAAIgCgBgAgKgjQgFACgFAFQgFAEgCAHQgDAIAAAJQgBAHACAHQADAHAEAGQAEAFAGADQAFADAHAAQAGAAAFgCIALgHQAEgFADgHQADgIAAgIQAAgIgCgIQgCgHgEgFQgEgFgGgCQgGgDgHAAQgFAAgGACg");
	this.shape_24.setTransform(36.3964,16.5503);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AglAyIAAgRIAOAAIADhCIgOgBIABgQIAfABIAAAOIADgGIAFgEIAHgDQACgCAFAAIAJABIAJABIAAAWIgTgBIAAgHQgEAAgCACQgEABgDACQgDACgCAEQgCAEgBAFIgCAwIARAAIgBARg");
	this.shape_25.setTransform(25.75,16.125);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAJBMIABgRIAOAAIABguQABgLgGgFQgGgGgLAAQgFgBgHADIgMAHIgCA6IAPAAIgBARIgwgBIABgRIAPAAIAEh1IgOAAIABgRIAgABIgDA+IABAAIAHgFIAHgEIAHgCIAJgBQAIAAAHADQAGADAFAEQAEAFADAHQABAGAAAKIgCAwIAQABIgBARg");
	this.shape_26.setTransform(14.575,13.25);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgdBKIAAgRIAOABIAEhyIgigBIAAAWIgUgBIABgmICCAEIgBAnIgUAAIABgYIgngBIgEByIAPABIAAARg");
	this.shape_27.setTransform(1.3,12.85);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.shaker, new cjs.Rectangle(-27.7,-1.7,209.5,55.5), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgbAvQgGgCgEgDIgEgGIgDgIQgBgEAAgGIACgMIAJgmIgNAAIADgPIAgAAIgLAvQgFARAEAIQAEAIAMAAQAFAAAEgCIAHgEIAGgIIAMgzIgNAAIAEgPIAfAAIgSBOIAOAAIgEAQIggAAIACgKIgGAGIgGADIgHACIgGAAQgHAAgFgBg");
	this.shape.setTransform(181.925,24.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgXAvQgIgEgGgFQgGgGgDgIQgDgIAAgJQAAgIACgGQACgIAEgHQADgFAGgGQAFgFAFgEQAHgDAHgDQAHgCAGAAQAKABAIADQAIADAGAGQAGAGAEAIQADAIAAAJQAAAHgCAHQgCAHgEAHQgDAGgGAGQgFAFgGAEQgGADgHACQgIACgGAAQgJAAgJgDgAgHgfQgHAEgFAFQgFAFgDAIQgDAHAAAHQAAAHACAFQACAGADADQAEAEAFACQAEACAGAAQAGAAAHgDQAFgDAGgFQAEgGAEgHQADgHAAgIQgBgHgBgEQgCgGgEgDQgEgEgEgCQgFgCgGAAQgFAAgGACg");
	this.shape_1.setTransform(170.2,24.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag3BGIAEgRIAJAAIARgaIgKhQIgJAAIADgPIAjAAIgDAPIgIAAIAGA6IAlg6IgIAAIAEgPIAiAAIgDAPIgIAAIhEBqIAKAAIgEARg");
	this.shape_2.setTransform(159.325,26.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgoAwIAThOIgTAAIAFgQIAjAAIgDANIAFgGIAGgEIAHgDIAHgBIAGAAIAFAAIAHABIgFAaIgTAAIADgLQgKAAgGAEQgFAFgEAHIgLAvIAQAAIgEAQg");
	this.shape_3.setTransform(145.2,24.575);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbAvQgHgDgFgFQgFgGgDgHQgDgHAAgIQAAgNAFgLQAFgLAHgIQAJgIAKgEQALgFAMAAQAHAAAFACQAGACAFAEIABgFIASAAIgSBOIAOAAIgDAQIgiAAIACgGQgHAEgFACQgGACgGAAQgIAAgHgDgAgGgeQgHADgFAFQgGAGgDAIQgDAIAAAJQAAAGABAFQABAEADADQADAEAFABQAEACAFAAIAHgBIAGgCIAFgDIAGgDIALgzQgCgDgFgCQgFgCgIAAQgHAAgGADg");
	this.shape_4.setTransform(133.7,24.575);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUAwQgIgDgFgGQgHgGgCgIQgEgIAAgKQAAgLAEgLQAEgKAIgIQAHgIAKgEQALgFALAAQAIAAAIADQAHADAFAGQAFAFADAGQACAHAAAHIAAAJIgBAHIhJAAIAAACIAAACQAAAGACAFQACAFADAEQADADAFACQAEACAGAAQAGAAAHgDQAGgDAFgFIAOAKIgHAHIgKAGQgFACgGABIgMACQgIAAgIgDgAgEggQgEABgEAEQgEADgDAEQgDAEgCAFIA1AAQAAgFgBgFQgCgEgDgDQgDgDgFgCQgEgBgFAAQgGAAgEACg");
	this.shape_5.setTransform(122.6,24.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAOAxIANg6QADgLgEgGQgFgFgKAAQgHAAgFADQgHADgGAFIgQBFIgSAAIAShPIgSAAIAEgQIAkAAIgDAKQAHgGAHgDQAIgDAIAAQAIAAAGADQAFACAEAEQAEAFABAHQABAGgCAJIgKAtIANAAIgDAQg");
	this.shape_6.setTransform(110.525,24.525);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgUAwQgIgDgFgGQgHgGgCgIQgEgIAAgKQAAgLAFgLQAEgKAHgIQAHgIALgEQAJgFALAAQAJAAAIADQAHADAFAGQAFAFACAGQADAHAAAHIAAAJIgCAHIhIAAIgBACIAAACQAAAGACAFQADAFADAEQADADAFACQAFACAFAAQAHAAAGgDQAHgDAEgFIAOAKIgHAHIgKAGQgFACgHABIgKACQgKAAgHgDgAgDggQgFABgEAEQgEADgDAEQgEAEgBAFIA1AAQAAgFgBgFQgCgEgDgDQgDgDgFgCQgEgBgFAAQgGAAgDACg");
	this.shape_7.setTransform(94.85,24.625);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAOAxIANg6QADgLgEgGQgFgFgKAAQgHAAgFADQgHADgGAFIgQBFIgSAAIAShPIgSAAIAEgQIAkAAIgDAKQAHgGAHgDQAIgDAIAAQAIAAAGADQAFACAEAEQAEAFABAHQABAGgCAJIgKAtIANAAIgDAQg");
	this.shape_8.setTransform(82.775,24.525);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgXAvQgHgEgGgFQgHgGgDgIQgDgIAAgJQAAgIACgGQACgIADgHQAEgFAGgGQAEgFAGgEQAHgDAHgDQAHgCAGAAQAKABAIADQAIADAGAGQAGAGAEAIQADAIAAAJQAAAHgDAHQgCAHgDAHQgDAGgGAGQgFAFgGAEQgGADgHACQgIACgGAAQgJAAgJgDgAgHgfQgHAEgFAFQgFAFgDAIQgDAHAAAHQAAAHACAFQACAGADADQAEAEAEACQAFACAGAAQAGAAAHgDQAGgDAFgFQAFgGADgHQACgHAAgIQAAgHgBgEQgCgGgEgDQgDgEgFgCQgFgCgGAAQgFAAgGACg");
	this.shape_9.setTransform(70.85,24.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AggBFQgHgDgFgFQgFgGgDgHQgDgIAAgJQAAgMAEgLQAFgKAIgIQAHgIALgEQAKgFALAAQAHAAAHACIALAGIAIglIgQAAIAEgQIAiAAIgdB/IAQAAIgEAQIgiAAIABgGIgKAFQgGADgGAAQgIAAgIgEgAgNgIQgHADgFAFQgFAFgDAIQgDAHAAAKQAAAGACAFQABAFAEADQADAEAEACQAFACAFAAQAGAAAGgDQAFgDAFgFIAMgwQgDgEgGgCQgFgCgIAAQgGAAgHACg");
	this.shape_10.setTransform(55.275,22.325);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAOAxIANg6QADgLgEgGQgFgFgKAAQgHAAgFADQgHADgGAFIgQBFIgSAAIAShPIgSAAIAEgQIAkAAIgDAKQAHgGAHgDQAIgDAIAAQAIAAAGADQAFACAEAEQAEAFABAHQABAGgCAJIgKAtIANAAIgDAQg");
	this.shape_11.setTransform(42.675,24.525);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgXBHIAThPIgSAAIAFgQIAiAAIgSBPIAPAAIgDAQgAAGguIgDgDIgDgEIAAgFIAAgEIADgEIADgDIAGgBIAEABIAEADIACAEIABAEIgBAFIgCAEIgEADIgEABg");
	this.shape_12.setTransform(33.4,22.325);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgxBfIAdh7IgUAAIAEgPIATAAIAEgRQACgKAEgGQAEgGAEgEQAFgEAGgCQAGgCAIAAIAIABIAGABIAGACIAEACIgKAOIgGgCIgJgBQgIAAgFADQgFAFgCAKIgEAQIAaAAIgEAPIgZAAIgcB7g");
	this.shape_13.setTransform(27.525,24.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(1,1,1).p("A1DjFMAqHAAAIAAGLMgqHAAAg");
	this.shape_14.setTransform(103.5,22.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(-32.2,2.2,271.5,41.599999999999994), null);


(lib.doclogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Tween2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(142,30);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.doclogo, new cjs.Rectangle(0,0,286.2,60.3), null);


(lib.bywhen = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shaker();
	this.instance.parent = this;
	this.instance.setTransform(86.3,22.5,1,1,0,0,0,86.3,22.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bywhen, new cjs.Rectangle(-27.7,-1.7,209.5,55.5), null);


// stage content:
(lib._300x250_bcd_phone = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 8
	this.instance = new lib.cta();
	this.instance.parent = this;
	this.instance.setTransform(152.5,-33.5,1,1,0,0,0,105.5,22);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(311).to({_off:false},0).wait(1).to({regX:103.5,regY:22.9,x:150.5,y:-31.65},0).wait(1).to({y:-28.15},0).wait(1).to({y:-20.3},0).wait(1).to({y:-4.25},0).wait(1).to({y:24.65},0).wait(1).to({y:55.7},0).wait(1).to({y:78},0).wait(1).to({y:93.85},0).wait(1).to({y:105.75},0).wait(1).to({y:114.95},0).wait(1).to({y:122.3},0).wait(1).to({y:128.25},0).wait(1).to({y:133.15},0).wait(1).to({y:137.15},0).wait(1).to({y:140.4},0).wait(1).to({y:143.1},0).wait(1).to({y:145.25},0).wait(1).to({y:146.95},0).wait(1).to({y:148.25},0).wait(1).to({y:149.25},0).wait(1).to({y:149.9},0).wait(1).to({y:150.25},0).wait(1).to({regX:105.5,regY:22,x:152.5,y:149.5},0).wait(27));

	// Layer 6
	this.instance_1 = new lib.doclogo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(142.1,-95.3,1,1,0,0,0,143.1,30.2);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(311).to({_off:false},0).wait(1).to({regY:30.1,y:-94.45},0).wait(1).to({y:-90.95},0).wait(1).to({y:-83.05},0).wait(1).to({y:-66.9},0).wait(1).to({y:-37.75},0).wait(1).to({y:-6.6},0).wait(1).to({y:15.85},0).wait(1).to({y:31.75},0).wait(1).to({y:43.7},0).wait(1).to({y:52.95},0).wait(1).to({y:60.35},0).wait(1).to({y:66.35},0).wait(1).to({y:71.25},0).wait(1).to({y:75.25},0).wait(1).to({y:78.55},0).wait(1).to({y:81.25},0).wait(1).to({y:83.4},0).wait(1).to({y:85.15},0).wait(1).to({y:86.45},0).wait(1).to({y:87.4},0).wait(1).to({y:88.1},0).wait(1).to({y:88.45},0).wait(1).to({regY:30.2,y:88.7},0).wait(27));

	// Layer 5
	this.instance_2 = new lib.Symbol3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(364,68,1,1,0,0,0,221.8,32.4);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(182).to({_off:false},0).wait(37).to({y:67},0).wait(1).to({regX:14.1,regY:87.6,x:156.3,y:121.9},0).wait(1).to({y:120.7},0).wait(1).to({y:117.4},0).wait(1).to({y:111.9},0).wait(1).to({y:108.2},0).wait(1).to({y:106.05},0).wait(1).to({y:104.8},0).wait(1).to({y:104},0).wait(1).to({y:103.5},0).wait(1).to({y:103.25},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:48},0).wait(75).to({regX:14.1,regY:87.6,x:156.3,y:103.55},0).wait(1).to({y:104.75},0).wait(1).to({y:107.1},0).wait(1).to({y:110.95},0).wait(1).to({y:116.85},0).wait(1).to({y:126},0).wait(1).to({y:140.6},0).wait(1).to({y:164.95},0).wait(1).to({y:199.15},0).wait(1).to({y:226},0).wait(1).to({y:242.45},0).wait(1).to({y:252.95},0).wait(1).to({y:260},0).wait(1).to({y:264.7},0).wait(1).to({y:267.85},0).wait(1).to({y:269.8},0).wait(1).to({y:270.85},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:216},0).to({_off:true},1).wait(38));

	// Layer 4
	this.instance_3 = new lib.bywhen();
	this.instance_3.parent = this;
	this.instance_3.setTransform(653.45,72.6,4,4,5.998,0,0,86.5,22.7);
	this.instance_3._off = true;

	this.instance_4 = new lib.Symbol5();
	this.instance_4.parent = this;
	this.instance_4.setTransform(364,60.75,1,1,0,0,0,221.8,17.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(93).to({_off:false},0).wait(1).to({regX:81.1,regY:25.9,scaleX:3.936,scaleY:3.936,rotation:5.7234,x:619.65,y:82.35},0).wait(1).to({scaleX:3.7493,scaleY:3.7493,rotation:4.9235,x:587.6,y:80.05},0).wait(1).to({scaleX:3.4547,scaleY:3.4547,rotation:3.6615,x:537.1,y:76.45},0).wait(1).to({scaleX:3.0765,scaleY:3.0765,rotation:2.0409,x:472.2,y:71.65},0).wait(1).to({scaleX:2.6482,scaleY:2.6482,rotation:0.2061,x:398.6,y:66.05},0).wait(1).to({scaleX:2.2112,scaleY:2.2112,rotation:-1.6665,x:323.45,y:60.15},0).wait(1).to({scaleX:1.8097,scaleY:1.8097,rotation:-3.3868,x:254.35,y:54.65},0).wait(1).to({scaleX:1.4858,scaleY:1.4858,rotation:-4.7748,x:198.5,y:50.05},0).wait(1).to({scaleX:1.2743,scaleY:1.2743,rotation:-5.681,x:162.05,y:47.05},0).wait(1).to({regX:86.3,regY:22.6,scaleX:1.2,scaleY:1.2,rotation:-5.9991,x:155.3,y:41.6},0).to({_off:true},79).wait(179));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(219).to({_off:false},0).to({alpha:1},16).wait(70).to({regX:9.4,regY:99.6,x:151.6,y:143},0).wait(1).to({y:144.15},0).wait(1).to({y:146.35},0).wait(1).to({y:150},0).wait(1).to({y:155.65},0).wait(1).to({y:164.35},0).wait(1).to({y:178.25},0).wait(1).to({y:201.5},0).wait(1).to({y:234.05},0).wait(1).to({y:259.6},0).wait(1).to({y:275.3},0).wait(1).to({y:285.3},0).wait(1).to({y:291.95},0).wait(1).to({y:296.45},0).wait(1).to({y:299.45},0).wait(1).to({y:301.35},0).wait(1).to({y:302.3},0).wait(1).to({regX:221.8,regY:17.7,x:364,y:220.75},0).to({_off:true},1).wait(38));

	// Layer 2
	this.instance_5 = new lib.Symbol1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-140.65,45.75,1,1,0,0,0,136.3,32.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({regX:139.1,regY:35.7,x:-126.7,y:49.2},0).wait(1).to({x:-112.65,y:49.35},0).wait(1).to({x:-94.4,y:49.6},0).wait(1).to({x:-69.75,y:49.95},0).wait(1).to({x:-36.35,y:50.4},0).wait(1).to({x:1.85,y:50.95},0).wait(1).to({x:34.05,y:51.4},0).wait(1).to({x:57.75,y:51.7},0).wait(1).to({x:75.35,y:51.95},0).wait(1).to({x:88.95,y:52.15},0).wait(1).to({x:99.75,y:52.3},0).wait(1).to({x:108.6,y:52.4},0).wait(1).to({x:115.95,y:52.55},0).wait(1).to({x:122.1,y:52.6},0).wait(1).to({x:127.3,y:52.7},0).wait(1).to({x:131.75,y:52.75},0).wait(1).to({x:135.55,y:52.8},0).wait(1).to({x:138.8,y:52.85},0).wait(1).to({x:141.5,y:52.9},0).wait(1).to({x:143.85},0).wait(1).to({x:145.8,y:52.95},0).wait(1).to({x:147.45},0).wait(1).to({x:148.8,y:53},0).wait(1).to({x:149.9},0).wait(1).to({x:150.75},0).wait(1).to({x:151.35},0).wait(1).to({x:151.8},0).wait(1).to({x:152.05},0).wait(1).to({regX:136.3,regY:32.4,x:149.35,y:49.75},0).wait(63).to({regX:139.1,regY:35.7,scaleX:1.0055,scaleY:1.0055,x:150.1,y:53.2},0).wait(1).to({scaleX:1.0243,scaleY:1.0243,x:143.25,y:53.8},0).wait(1).to({scaleX:1.0603,scaleY:1.0603,x:130.15,y:55},0).wait(1).to({scaleX:1.1201,scaleY:1.1201,x:108.3,y:57},0).wait(1).to({scaleX:1.2133,scaleY:1.2133,x:74.2,y:60},0).wait(1).to({scaleX:1.3537,scaleY:1.3537,x:22.9,y:64.7},0).wait(1).to({scaleX:1.5527,scaleY:1.5527,x:-49.8,y:71.2},0).wait(1).to({scaleX:1.7895,scaleY:1.7895,x:-136.4,y:79},0).wait(1).to({scaleX:2.0058,scaleY:2.0058,x:-215.4,y:86.1},0).wait(1).to({scaleX:2.1715,scaleY:2.1715,x:-276,y:91.5},0).wait(1).to({scaleX:2.2921,scaleY:2.2921,x:-320.05,y:95.55},0).wait(1).to({scaleX:2.3793,scaleY:2.3793,x:-351.9,y:98.4},0).wait(1).to({scaleX:2.4421,scaleY:2.4421,x:-374.9,y:100.45},0).wait(1).to({scaleX:2.4869,scaleY:2.4869,x:-391.25,y:101.95},0).wait(1).to({scaleX:2.5176,scaleY:2.5176,x:-402.5,y:102.95},0).wait(1).to({scaleX:2.5373,scaleY:2.5373,x:-409.65,y:103.6},0).wait(1).to({scaleX:2.5481,scaleY:2.5481,x:-413.6,y:103.9},0).wait(1).to({regX:136.2,regY:32.4,scaleX:2.5514,scaleY:2.5514,x:-422.1,y:95.75},0).to({_off:true},163).wait(89));

	// Layer 3
	this.instance_6 = new lib.Symbol2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(784,51,0.6,0.6,0,0,0,112.1,112.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({regX:-413.8,regY:418.8,x:456.35,y:234.5},0).wait(1).to({x:441.05},0).wait(1).to({x:421.15},0).wait(1).to({x:394.3},0).wait(1).to({x:357.9},0).wait(1).to({x:316.3},0).wait(1).to({x:281.15},0).wait(1).to({x:255.35},0).wait(1).to({x:236.2},0).wait(1).to({x:221.4},0).wait(1).to({x:209.6},0).wait(1).to({x:199.95},0).wait(1).to({x:191.95},0).wait(1).to({x:185.25},0).wait(1).to({x:179.55},0).wait(1).to({x:174.7},0).wait(1).to({x:170.6},0).wait(1).to({x:167.05},0).wait(1).to({x:164.05},0).wait(1).to({x:161.5},0).wait(1).to({x:159.35},0).wait(1).to({x:157.6},0).wait(1).to({x:156.1},0).wait(1).to({x:154.9},0).wait(1).to({x:154},0).wait(1).to({x:153.3},0).wait(1).to({x:152.85},0).wait(1).to({x:152.55},0).wait(1).to({regX:112.1,regY:112.9,x:468,y:51},0).wait(63).to({regX:-413.8,regY:418.8,scaleX:0.6013,scaleY:0.6013,x:152.4,y:234.8},0).wait(1).to({scaleX:0.6059,scaleY:0.6059,y:235.6},0).wait(1).to({scaleX:0.6147,scaleY:0.6147,x:152.3,y:237.2},0).wait(1).to({scaleX:0.6294,scaleY:0.6294,x:152.15,y:239.85},0).wait(1).to({scaleX:0.6522,scaleY:0.6522,x:152,y:243.9},0).wait(1).to({scaleX:0.6866,scaleY:0.6866,x:151.65,y:250.1},0).wait(1).to({scaleX:0.7353,scaleY:0.7353,x:151.2,y:258.85},0).wait(1).to({scaleX:0.7932,scaleY:0.7932,x:150.65,y:269.3},0).wait(1).to({scaleX:0.8461,scaleY:0.8461,x:150.2,y:278.8},0).wait(1).to({scaleX:0.8867,scaleY:0.8867,x:149.85,y:286.1},0).wait(1).to({scaleX:0.9162,scaleY:0.9162,x:149.6,y:291.4},0).wait(1).to({scaleX:0.9375,scaleY:0.9375,x:149.4,y:295.25},0).wait(1).to({scaleX:0.9529,scaleY:0.9529,x:149.25,y:298},0).wait(1).to({scaleX:0.9639,scaleY:0.9639,x:149.15,y:299.95},0).wait(1).to({scaleX:0.9714,scaleY:0.9714,x:149.1,y:301.3},0).wait(1).to({scaleX:0.9762,scaleY:0.9762,x:149.05,y:302.2},0).wait(1).to({scaleX:0.9789,scaleY:0.9789,x:149,y:302.65},0).wait(1).to({regX:112.4,regY:112.8,scaleX:0.9797,scaleY:0.9797,x:664.25,y:3.15},0).wait(1).to({regX:-413.8,regY:418.8,x:148.75,y:302.95},0).wait(1).to({y:302.9},0).wait(1).to({x:148.8,y:302.85},0).wait(1).to({x:148.85,y:302.75},0).wait(1).to({x:148.95,y:302.55},0).wait(1).to({x:149.05,y:302.35},0).wait(1).to({x:149.2,y:302.05},0).wait(1).to({x:149.3,y:301.8},0).wait(1).to({x:149.45,y:301.5},0).wait(1).to({x:149.55,y:301.3},0).wait(1).to({x:149.65,y:301.15},0).wait(1).to({x:149.7,y:301.05},0).wait(1).to({y:301},0).wait(1).to({regX:112.4,regY:112.8,x:665.25,y:1.15},0).wait(1).to({regX:-413.8,regY:418.8,x:149.7,y:301},0).wait(3).to({x:149.65,y:301.05},0).wait(1).to({x:149.6,y:301.1},0).wait(1).to({x:149.55,y:301.15},0).wait(1).to({x:149.5,y:301.2},0).wait(1).to({x:149.4,y:301.3},0).wait(1).to({x:149.3,y:301.4},0).wait(1).to({x:149.2,y:301.5},0).wait(1).to({x:149.1,y:301.6},0).wait(1).to({x:149,y:301.7},0).wait(1).to({x:148.95,y:301.75},0).wait(1).to({x:148.85,y:301.85},0).wait(1).to({x:148.8,y:301.9},0).wait(1).to({x:148.75,y:301.95},0).wait(3).to({regX:112.4,regY:112.8,x:664.25,y:2.15},0).wait(1).to({regX:-413.8,regY:418.8,x:148.7,y:301.95},0).wait(2).to({y:301.9},0).wait(1).to({x:148.65,y:301.85},0).wait(1).to({x:148.6,y:301.75},0).wait(1).to({x:148.55,y:301.65},0).wait(1).to({x:148.5,y:301.55},0).wait(1).to({x:148.4,y:301.35},0).wait(1).to({x:148.3,y:301.15},0).wait(1).to({x:148.2,y:300.95},0).wait(1).to({x:148.1,y:300.75},0).wait(1).to({x:148,y:300.55},0).wait(1).to({x:147.95,y:300.4},0).wait(1).to({x:147.85,y:300.25},0).wait(1).to({x:147.8,y:300.15},0).wait(1).to({x:147.75,y:300.05},0).wait(1).to({y:300},0).wait(2).to({regX:112.4,regY:112.8,x:663.25,y:0.15},0).wait(1).to({regX:-413.8,regY:418.8,x:147.75,y:300},0).wait(2).to({x:147.8},0).wait(1).to({x:147.85,y:300.05},0).wait(1).to({x:147.9},0).wait(1).to({x:148,y:300.1},0).wait(1).to({x:148.1,y:300.15},0).wait(1).to({x:148.25,y:300.25},0).wait(1).to({x:148.45,y:300.35},0).wait(1).to({x:148.65,y:300.45},0).wait(1).to({x:148.85,y:300.55},0).wait(1).to({x:149.05,y:300.65},0).wait(1).to({x:149.2,y:300.7},0).wait(1).to({x:149.35,y:300.8},0).wait(1).to({x:149.5,y:300.85},0).wait(1).to({x:149.6,y:300.9},0).wait(1).to({x:149.65,y:300.95},0).wait(1).to({x:149.7},0).wait(2).to({regX:112.4,regY:112.8,x:665.25,y:1.15},0).to({_off:true},1).wait(179));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D93D43").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(361));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-456.8,-0.5,1499.3999999999999,538.3);
// library properties:
lib.properties = {
	id: 'DCCA7DDDDB474A279771A470BF7560D2',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/300x250_bcd_phone_atlas_.png", id:"300x250_bcd_phone_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['DCCA7DDDDB474A279771A470BF7560D2'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;