(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib._970x250_solar_bg = function() {
	this.initialize(img._970x250_solar_bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,970,259);


(lib.CEPA_Horizontal_Logo_RGBK = function() {
	this.initialize(img.CEPA_Horizontal_Logo_RGBK);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,393,157);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.white = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EhNpAU8MAAAgp3MCbTAAAMAAAAp3g");
	this.shape.setTransform(497,134);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.white, new cjs.Rectangle(0,0,994,268), null);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.CEPA_Horizontal_Logo_RGBK();
	this.instance.parent = this;
	this.instance.setTransform(64,29,0.63,0.63);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol6, new cjs.Rectangle(64,29,247.6,98.9), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Ag4BCQgLgKAAgQQAAgIACgHQADgGAEgGQAEgEAGgEIALgFIAbgIQAUgHAGgEIAAgOIgBgIQAAgFgDgFQgDgFgFgEQgEgFgKAAQgHAAgFADQgGACgDACIABAJIACALQAAAFgEAEQgFAFgJAAQgHAAgDgGQgDgFAAgHQAAgGAEgGQAFgGAIgFQAGgEAKgDQAIgDAKAAQALAAAJABQAKADAHAFQAHAFAEAKQAEAJAAAPIgBAkIAAAjQAAAGACADQACADAEADIAHABIAKAAIAAAKIgMAEIgMABQgMAAgGgFQgHgFgCgKIgBAAQgKAKgJAGQgLAFgQAAQgQAAgKgKgAgEAAQgJADgJAGQgHAEgEAHQgFAHAAAKQAAAMAHAGQAHAFAJAAQAKAAAIgFQAHgFAGgHIAAgxg");
	this.shape.setTransform(413.2,22.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgsA3QgSgVAAgiQABgPAFgNQAEgNAJgLQAJgLANgGQANgGAOAAQAVAAAOAKQANAKAAASQAAAHgDAGQgEAFgIAAQgJAAgFgEQgEgFAAgFIACgNIABgLQgCgEgFgCIgLgBQgHAAgGADQgGADgGAIQgGAHgDANQgDAMAAARQAAAbAMARQAMARATAAQANAAAKgHQAKgHAIgOIAJAHQgJARgQAKQgQAKgQAAQgfAAgSgVg");
	this.shape_1.setTransform(399,22.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgNAOQgGgFAAgJQAAgHAGgGQAGgGAHAAQAIAAAGAGQAGAGAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGg");
	this.shape_2.setTransform(387.7,27.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgZBGQgNgGgIgLQgJgKgEgOQgEgOAAgPQAAgOAEgOQAFgNAIgLQAJgLAMgGQAMgGAPAAQAQAAALAFQALAFAHAIQAHAJADALQAEALAAANIAAAJIhfAAQAAAOADALQACAMAGAJQAGAIAJAFQAIAFANAAQANAAAKgGQAJgGAJgQIAKAGQgJASgPAKQgPAKgUAAQgRAAgNgGgAAggQIgCgRQgBgKgDgGQgDgHgGgEQgGgEgJAAQgPAAgKANQgKAMgBAXIBCAAg");
	this.shape_3.setTransform(376.6,22.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("Ag1BKIAAgKIAGgBIAGAAQAFgCACgDQACgDAAgFIAAhYQAAgFgCgEQgDgFgEgCIgGgDIgIgCIAAgJIAwgDIACACIAAAUIABAAQAIgMALgGQALgGAKAAQAIAAAGAGQAGAGAAAKQAAAHgDAHQgEAFgIAAQgIAAgEgEQgFgFAAgEIABgHIABgEQgHgBgJAGQgKAFgFALIAABTQAAAFACADQACAEADABIAKACIAJABIAAAKg");
	this.shape_4.setTransform(363.4,22.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AguA+QgKgMAAgYIAAhEQAAgFgCgEQgCgDgEgDIgHgDIgIgBIAAgJIAwgEIACACIAABjQAAAQAHAIQAHAIAKAAQAHAAAGgDQAHgCAEgDIAHgHIAEgGIAAhRQAAgFgCgEQgCgDgDgDQgDgCgFAAIgMgBIAAgJIA1gEIACACIAAByQAAAFACADQACAEAEACIAGACIAIABIAAAKIgvADIgCgCIAAgTIgBAAIgIAIIgKAIIgMAGQgGACgLAAQgTAAgKgNg");
	this.shape_5.setTransform(348.1,22.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgOBXQgIgJAAgRIAAhhIgaAAIAAgOIAbAAIAAgtIAZAAIAAAtIAqAAIAAAOIgqAAIAABQIABAPQABAGACAFQADAEAEACQAFADAIAAIALgBIAKgCIAAALIgSAGQgJADgMAAQgRAAgHgJg");
	this.shape_6.setTransform(334.4,20.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AguA+QgKgMAAgYIAAhEQAAgFgCgEQgCgDgEgDIgHgDIgIgBIAAgJIAwgEIACACIAABjQAAAQAHAIQAHAIAKAAQAHAAAGgDQAHgCAEgDIAHgHIAEgGIAAhRQAAgFgCgEQgCgDgDgDQgDgCgFAAIgMgBIAAgJIA1gEIACACIAAByQAAAFACADQACAEAEACIAGACIAIABIAAAKIgvADIgCgCIAAgTIgBAAIgIAIIgKAIIgMAGQgGACgLAAQgTAAgKgNg");
	this.shape_7.setTransform(320.5,22.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgxByIAAgKIAHgBIAGgBQAEgBACgEQACgDAAgFIAAhpIgcAAIAAgNIAcAAIAAgJQAAgiARgUQAQgUAaAAQANgBAHAGQAGAFAAAIQAAAGgDAFQgEAEgHAAQgEAAgEgCIgGgFIgGgHIgEgHQgKAAgFANQgEAOAAAdIAAAPIAkAAIAAANIgkAAIAABoQAAAEABAEQACADAEABIAJADIAKABIAAAKg");
	this.shape_8.setTransform(308.3,18.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgoBuQgLgFgIgKQgJgLgFgOQgFgOAAgRQAAgQAFgOQAGgNAJgKQAJgKANgGQANgGANAAQAKAAAJADQAKACAHAEIAAgyQAAgGgCgGQgCgFgEgCQgEgDgHgBIgOgCIAAgJIA6gDIADACIAADBQAAAGACADQABAEAEACIAIACIAKABIAAAKIgzADIgCgCIAAgOIgBAAQgIAJgLAFQgKAGgMgBQgMABgMgGgAgXgUQgHAEgGAJQgFAHgEANQgDANAAAPQAAAMADAKQACAKAGAJQAFAIAIAFQAIAFALAAQAKAAAIgFQAIgGAFgFIAAhUIgEgIIgGgJIgKgFQgGgDgHAAQgIAAgIAFg");
	this.shape_9.setTransform(294,18.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgZBGQgNgGgIgLQgJgKgEgOQgEgOAAgPQAAgOAEgOQAFgNAIgLQAJgLAMgGQAMgGAPAAQAQAAALAFQALAFAHAIQAHAJADALQAEALAAANIAAAJIhfAAQAAAOADALQACAMAGAJQAGAIAJAFQAIAFANAAQANAAAKgGQAJgGAJgQIAKAGQgJASgPAKQgPAKgUAAQgRAAgNgGgAAggQIgCgRQgBgKgDgGQgDgHgGgEQgGgEgJAAQgPAAgKANQgKAMgBAXIBCAAg");
	this.shape_10.setTransform(278,22.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("Ag1BKIAAgKIAGgBIAGAAQAFgCACgDQACgDAAgFIAAhYQAAgFgCgEQgDgFgEgCIgGgDIgIgCIAAgJIAwgDIACACIAAAUIABAAQAIgMALgGQALgGAKAAQAIAAAGAGQAGAGAAAKQAAAHgDAHQgEAFgIAAQgIAAgEgEQgFgFAAgEIABgHIABgEQgHgBgJAGQgKAFgFALIAABTQAAAFACADQACAEADABIAKACIAJABIAAAKg");
	this.shape_11.setTransform(264.8,22.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("Ag4BCQgLgKAAgQQAAgIADgHQACgGAFgGQADgEAHgEIALgFIAbgIQASgHAIgEIAAgOIgBgIQgBgFgDgFQgDgFgFgEQgEgFgKAAQgHAAgGADQgGACgCACIACAJIABALQAAAFgFAEQgFAFgHAAQgIAAgDgGQgEgFAAgHQAAgGAFgGQAFgGAHgFQAHgEAJgDQAKgDAIAAQAMAAAJABQAKADAHAFQAHAFAEAKQAEAJAAAPIAAAkIgBAjQAAAGACADQACADAEADIAHABIAKAAIAAAKIgMAEIgMABQgLAAgHgFQgHgFgCgKIgBAAQgJAKgKAGQgLAFgPAAQgRAAgKgKgAgEAAQgKADgHAGQgIAEgEAHQgFAHABAKQAAAMAGAGQAGAFAKAAQALAAAGgFQAJgFAFgHIABgxg");
	this.shape_12.setTransform(251.2,22.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AAMByIAAgKIAIgBIAHgBQAEgBACgEQACgDAAgFIAAhKQAAgPgIgIQgHgJgKAAQgIABgFACIgMAGIgIAHIgEAGIAABTQAAAFACADQACADAEABIAHADIAHABIAAAKIhGAAIAAgKIAHgBIAGgBQAEgBACgEQACgDAAgFIAAioQAAgEgCgGQgDgEgDgDQgDgCgHgBIgKgBIAAgJIA1gDIACACIAABlIABAAIAJgJIAKgIQAFgDAHgCQAIgDAJAAQATAAALANQAKAMAAAWIAABLQAAAFACADQACADAEACIAGACIAHABIAAAKg");
	this.shape_13.setTransform(234.2,18.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgWBIQgLgFgFgEIgDAKIgKAAIgCgzIALAAQABAGADAIQAEAIAFAGQAGAGAJAFQAHAEAJAAQAOAAAIgHQAHgGAAgMQABgGgDgEQgDgFgEgDIgMgGIgPgGIgPgFQgJgEgFgEQgHgFgEgHQgEgIAAgKQAAgSANgMQAOgMAVAAQAIAAAJACIAPAFIACgHIALAAIADAuIgKAAQgEgQgKgJQgKgKgOAAQgMAAgHAGQgGAGAAAJQAAAGACAEQACAFAFADIALAGIAPAFIATAHQAIAFAFADQAHAGACAHQAEAHAAAKQAAAUgPAMQgPANgYAAQgMAAgKgEg");
	this.shape_14.setTransform(219.3,22.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgOBXQgIgJAAgRIAAhhIgaAAIAAgOIAaAAIAAgtIAaAAIAAAtIAqAAIAAAOIgqAAIAABQIABAPQABAGADAFQACAEAEACQAFADAIAAIALgBIAKgCIAAALIgTAGQgIADgMAAQgRAAgHgJg");
	this.shape_15.setTransform(200.4,20.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("Ag4BCQgLgKAAgQQAAgIACgHQADgGAEgGQAFgEAFgEIALgFIAbgIQAUgHAGgEIAAgOIgBgIQAAgFgDgFQgCgFgGgEQgFgFgJAAQgHAAgFADQgGACgDACIABAJIACALQAAAFgEAEQgGAFgIAAQgHAAgDgGQgEgFABgHQgBgGAFgGQAFgGAIgFQAGgEAJgDQAKgDAIAAQAMAAAJABQAKADAHAFQAHAFAEAKQAEAJAAAPIgBAkIAAAjQAAAGACADQACADAEADIAHABIAKAAIAAAKIgMAEIgMABQgMAAgGgFQgHgFgCgKIgBAAQgKAKgJAGQgLAFgQAAQgQAAgKgKgAgEAAQgJADgJAGQgHAEgEAHQgEAHgBAKQABAMAGAGQAHAFAJAAQAKAAAIgFQAHgFAGgHIAAgxg");
	this.shape_16.setTransform(188.1,22.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAnBJIgnhqIgnBqIgLAAIgWhBIgTg2QgCgHgHgEQgGgEgGgBIAAgKIBAAAIAAALIgLABQgFACAAADIAAADIACAEIALAiIAPAwIAkhnIAOAAIAlBmIANglIALgjIACgHIABgGQAAgDgDgCIgGgDIgFgCIgGAAIAAgKIA3AAIAAAKQgGAAgHAFQgHAEgDAJIgOApIgPArIgFAQIgFARg");
	this.shape_17.setTransform(162.1,22.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgbBHQgMgFgKgKQgKgKgFgOQgGgOAAgSQABghATgVQATgWAfABQAfgBAUAVQATAVAAAhQABAOgGAPQgEAPgJAKQgKAMgOAFQgNAHgQAAQgOAAgMgGgAgSg7QgIAGgFAJQgEAJgCAMQgCALAAALQAAANACAMQACAMAFAJQAFAJAHAGQAIAGAKAAQATAAAKgSQALgSAAgfQAAgLgCgLQgCgNgEgJQgGgIgHgGQgIgFgLgBQgKABgIAFg");
	this.shape_18.setTransform(142.8,22.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAMByIAAgKIAIgBIAHgBQAEgBACgEQACgDAAgFIAAhKQAAgPgIgIQgHgJgKAAQgIABgFACIgMAGIgIAHIgEAGIAABTQAAAFACADQACADAEABIAHADIAHABIAAAKIhGAAIAAgKIAHgBIAGgBQAEgBACgEQACgDAAgFIAAioQAAgEgCgGQgDgEgDgDQgDgCgHgBIgKgBIAAgJIA1gDIACACIAABlIABAAIAJgJIAKgIQAFgDAHgCQAIgDAJAAQATAAALANQAKAMAAAWIAABLQAAAFACADQACADAEACIAGACIAHABIAAAKg");
	this.shape_19.setTransform(125.7,18.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgZBGQgNgGgIgLQgJgKgEgOQgEgOAAgPQAAgOAEgOQAFgNAIgLQAJgLAMgGQAMgGAPAAQAQAAALAFQALAFAHAIQAHAJADALQAEALAAANIAAAJIhfAAQAAAOADALQACAMAGAJQAGAIAJAFQAIAFANAAQANAAAKgGQAJgGAJgQIAKAGQgJASgPAKQgPAKgUAAQgRAAgNgGgAAggQIgCgRQgBgKgDgGQgDgHgGgEQgGgEgJAAQgPAAgKANQgKAMgBAXIBCAAg");
	this.shape_20.setTransform(103,22.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgZBGQgNgGgIgLQgJgKgEgOQgEgOAAgPQAAgOAEgOQAFgNAIgLQAJgLAMgGQAMgGAPAAQAQAAALAFQALAFAHAIQAHAJADALQAEALAAANIAAAJIhfAAQAAAOADALQACAMAGAJQAGAIAJAFQAIAFANAAQANAAAKgGQAJgGAJgQIAKAGQgJASgPAKQgPAKgUAAQgRAAgNgGgAAggQIgCgRQgBgKgDgGQgDgHgGgEQgGgEgJAAQgPAAgKANQgKAMgBAXIBCAAg");
	this.shape_21.setTransform(88.5,22.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgaBoQgOgEgKgGIgHAKIgLAAIgChHIALAAQAEANAFALQAFALAIAJQAIAJAKAFQAKAFAMAAQAKAAAIgDQAIgDAEgEQAFgFACgHQACgGAAgJQAAgMgHgLQgHgLgNgFIgVgJIgWgIQgRgHgKgNQgKgNAAgVQAAgLAFgLQAFgKAJgIQAIgIAMgEQAMgEAMAAQAOAAALAEQALAEAKAGIAGgKIALAAIACBFIgMAAIgHgWQgFgLgGgJQgGgIgJgFQgJgGgNAAQgOAAgJAJQgKAJAAANQAAAOAGAJQAGAIAMAGIAUAJIAUAIIARAJQAIADAGAHQAHAHADAJQADAJAAALQAAAcgUASQgUARgfAAQgMAAgOgEg");
	this.shape_22.setTransform(72.8,19.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(62.2,0,360.3,38.1), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgNAOQgGgGAAgIQAAgHAGgGQAGgGAHAAQAIAAAGAGQAGAGAAAHQAAAIgGAGQgGAGgIAAQgHAAgGgGg");
	this.shape.setTransform(404.9,7.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgPBXQgHgJAAgRIAAhhIgaAAIAAgOIAbAAIAAgtIAZAAIAAAtIApAAIAAAOIgoAAIAABQIABAPQAAAGACAFQACAEAGACQAEACAIABIALgBIAKgCIAAALIgTAHQgIACgMAAQgRAAgIgJg");
	this.shape_1.setTransform(395.6,-0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AAKBKIAAgJIAHgBIAHgBQAEgBACgEQACgDAAgFIAAhKQAAgPgHgIQgHgJgLAAQgHAAgGADIgMAGIgHAHIgEAGIAABSQAAAFABADQACAEAFABIAGADIAIABIAAAJIhHAAIAAgJIAHgBIAGgBQAEgBADgEQACgDAAgFIAAhYQgBgFgCgFQgCgEgEgCIgHgDIgIgBIAAgKIAxgDIACACIAAAUIABAAIAIgIIAKgIQAFgDAHgDQAHgCAKAAQAUAAALANQAJANABAVIAABKQAAAGABADQACADAFACIAFACIAHABIAAAJg");
	this.shape_2.setTransform(381.8,1.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AggBvIAAgJIAIgCIAGgBQADAAACgEQACgEABgEIAAhZQgBgEgCgFQgCgDgDgDIgIgDIgKgBIAAgKIAygDIACACIAAB1QAAAFACADQACADAEACIAGACIAHACIAAAJgAgMhMQgGgGABgIQgBgIAGgGQAFgGAHAAQAIAAAFAGQAGAGAAAHQAAAIgGAHQgFAFgIAAQgHABgFgGg");
	this.shape_3.setTransform(368.4,-2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("Ag1BKIAAgJIAGgCIAGgBQAFAAACgEQACgEAAgEIAAhZQAAgEgCgFQgCgEgFgDIgGgCIgIgBIAAgKIAwgDIACACIAAAUIABAAQAIgMALgGQALgGAKAAQAIAAAGAGQAGAGAAAKQAAAIgEAFQgDAGgIAAQgIAAgEgEQgFgFAAgFIABgFIABgGQgHABgJAFQgJAGgGAKIAABTQAAAFACAEQACADADABIAKACIAJACIAAAJg");
	this.shape_4.setTransform(358.3,1.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AhNBrIAAgKIAJgBIAHgBQAFgCACgDQABgEAAgFIAAiZQAAgEgCgEQgCgEgEgDIgHgCIgJgCIAAgJIAxgDIACABIAAARIACAAQAHgJALgGQALgGALAAQANAAAMAGQALAGAIAJQAIALAFANQAFAOAAARQAAARgGAOQgFAOgKAKQgKAKgMAFQgMAGgNAAQgMAAgJgDQgIgDgFgEIgBAAIAAArQAAAGACADQACAEAEABIAKADIAKABIAAAKgAgMhVQgIAFgFAHIAABUIAEAIIAHAIIAJAGQAFACAHAAQAJAAAHgEQAIgFAFgIQAGgJADgLQACgMAAgPQAAgKgCgMQgCgLgFgIQgFgJgIgFQgIgFgMAAQgKAAgHAEg");
	this.shape_5.setTransform(343,4.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgPBXQgHgJAAgRIAAhhIgaAAIAAgOIAbAAIAAgtIAZAAIAAAtIApAAIAAAOIgoAAIAABQIABAPQAAAGACAFQACAEAGACQAEACAIABIALgBIAKgCIAAALIgTAHQgIACgMAAQgRAAgIgJg");
	this.shape_6.setTransform(329.5,-0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgbBIQgMgGgKgKQgJgKgGgOQgFgOgBgRQAAghAUgWQAUgWAfAAQAeAAAUAVQATAUABAiQAAAPgGAPQgEAOgJALQgKALgOAFQgNAHgPgBQgOAAgNgEgAgSg7QgIAGgFAKQgEAJgCALQgCALgBALQAAANADAMQACAMAFAJQAFAJAIAGQAHAFALABQASgBAKgRQALgSAAgfQAAgKgCgMQgDgNgEgIQgFgJgHgGQgHgGgLAAQgLAAgIAGg");
	this.shape_7.setTransform(316.3,1.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgbBIQgNgGgJgKQgJgKgGgOQgGgOABgRQAAghATgWQAUgWAfAAQAeAAATAVQAVAUgBAiQAAAPgEAPQgFAOgJALQgKALgNAFQgOAHgQgBQgOAAgMgEgAgSg7QgIAGgFAKQgFAJgCALQgCALABALQAAANACAMQACAMAFAJQAFAJAHAGQAIAFALABQASgBALgRQAKgSAAgfQAAgKgCgMQgDgNgEgIQgEgJgIgGQgIgGgKAAQgLAAgIAGg");
	this.shape_8.setTransform(300.2,1.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgxBxIAAgJIAHgBIAGgBQAEgBACgEQACgDAAgFIAAhoIgcAAIAAgPIAcAAIAAgJQAAggARgVQAQgVAaABQANAAAHAFQAGAFAAAIQAAAGgDAEQgEAFgHAAQgEAAgEgCIgGgFIgGgIIgEgGQgKABgFANQgEANAAAdIAAAOIAkAAIAAAPIgkAAIAABmQAAAFABAEQACADAEACIAJACIAKABIAAAJg");
	this.shape_9.setTransform(288.4,-2.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AAKBKIAAgJIAIgBIAGgBQAEgBACgEQACgDAAgFIAAhKQAAgPgHgIQgHgJgLAAQgHAAgGADIgLAGIgIAHIgEAGIAABSQAAAFACADQABAEAEABIAHADIAIABIAAAJIhHAAIAAgJIAHgBIAGgBQAEgBACgEQACgDABgFIAAhYQAAgFgDgFQgCgEgEgCIgGgDIgJgBIAAgKIAwgDIADACIAAAUIABAAIAIgIIAKgIQAGgDAGgDQAHgCAKAAQAVAAAJANQALANAAAVIAABKQAAAGACADQABADAEACIAGACIAIABIAAAJg");
	this.shape_10.setTransform(266.4,1.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgbBIQgMgGgKgKQgJgKgGgOQgFgOgBgRQAAghAUgWQATgWAfAAQAfAAAUAVQATAUABAiQAAAPgGAPQgEAOgJALQgKALgOAFQgNAHgPgBQgPAAgMgEgAgSg7QgIAGgFAKQgEAJgCALQgCALAAALQAAANACAMQACAMAFAJQAFAJAIAGQAHAFAKABQATgBAKgRQALgSAAgfQAAgKgCgMQgCgNgEgIQgGgJgHgGQgIgGgLAAQgKAAgIAGg");
	this.shape_11.setTransform(249.4,1.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("Ag0BzIABgaIAAgdIAAiOQAAgGgCgEQgCgGgEgBQgDgCgGgCIgLgBIAAgJIA1gDIACACIAABfIACABQAJgKAKgFQAKgFALAAQAaAAASAVQASAUAAAiQAAAggVAXQgUAWgbAAQgMAAgKgEQgMgEgKgGIgLARgAgKgRQgHAEgHAGIAABTIAEAIIAHAJIAKAHQAEADAIAAQASAAALgSQALgRAAgeQAAgLgCgLQgCgLgFgHQgFgJgIgGQgIgEgMgBQgJABgIAEg");
	this.shape_12.setTransform(232.2,-1.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("Ag2BKIAAgJIAHgCIAHgBQAEAAACgEQACgEAAgEIAAhZQAAgEgCgFQgDgEgDgDIgHgCIgIgBIAAgKIAwgDIACACIAAAUIABAAQAIgMALgGQALgGAJAAQAKAAAFAGQAGAGAAAKQAAAIgEAFQgDAGgIAAQgIAAgEgEQgEgFgBgFIABgFIABgGQgHABgJAFQgJAGgGAKIAABTQAAAFACAEQACADADABIAKACIAKACIAAAJg");
	this.shape_13.setTransform(218.7,1.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("Ag4BCQgLgKAAgQQAAgIADgHQACgGAEgFQAFgFAFgDIAMgGIAbgIQASgHAIgEIAAgPIgBgHQgBgFgDgFQgDgGgFgDQgFgFgJABQgHgBgGADQgFACgDADIABAJIACAKQAAAFgFAFQgFADgHAAQgIAAgDgEQgDgGgBgHQABgGAEgGQAFgGAHgFQAHgEAKgDQAIgDAKAAQALAAAJACQAJACAIAFQAHAGAEAIQAEAKAAAPIAAAkIgBAjQAAAGACADQACAEAEACIAHACIAKAAIAAAJIgMAEIgMABQgLABgHgGQgHgFgCgLIgBAAQgKALgJAGQgLAFgQAAQgQAAgKgKgAgEAAQgJADgJAGQgHAEgEAHQgFAHABAJQgBANAHAFQAGAGAKAAQALAAAGgFQAJgFAFgHIABgyg");
	this.shape_14.setTransform(205.1,1.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgrA3QgTgVABgiQAAgPAEgNQAFgNAJgLQAJgLANgGQANgGAOAAQAVAAAOAKQANAKAAASQAAAHgEAGQgDAFgIAAQgIAAgGgEQgEgFAAgFIACgNIABgLQgCgEgFgCIgMgBQgFAAgGADQgHADgGAIQgGAHgDANQgDAMAAARQAAAbAMARQAMARATAAQAOAAAJgHQAKgHAIgOIAJAHQgJARgQAKQgQAKgRAAQgeAAgRgVg");
	this.shape_15.setTransform(190.8,1.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("Ag2BKIAAgJIAHgCIAHgBQAEAAACgEQACgEAAgEIAAhZQAAgEgCgFQgDgEgDgDIgHgCIgIgBIAAgKIAwgDIACACIAAAUIABAAQAIgMALgGQALgGAJAAQAKAAAFAGQAGAGAAAKQAAAIgEAFQgDAGgIAAQgIAAgEgEQgEgFgBgFIABgFIABgGQgHABgJAFQgJAGgGAKIAABTQAAAFACAEQACADADABIAKACIAKACIAAAJg");
	this.shape_16.setTransform(170.6,1.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AguA+QgKgMAAgYIAAhEQAAgFgCgEQgCgDgEgDIgHgDIgIgBIAAgJIAwgEIACACIAABjQAAAQAHAIQAHAIAKAAQAHAAAGgDQAHgCAEgDIAHgHIAEgGIAAhRQAAgFgCgEQgCgDgDgDQgDgCgFAAIgMgBIAAgJIA1gEIACACIAAByQAAAFACADQACAEAEACIAGACIAIABIAAAKIgvADIgCgCIAAgTIgBAAIgIAIIgKAIIgMAGQgGACgLAAQgTAAgKgNg");
	this.shape_17.setTransform(155.3,2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgbBIQgMgGgKgKQgKgKgFgOQgGgOAAgRQABghATgWQATgWAfAAQAfAAAUAVQATAUABAiQAAAPgGAPQgEAOgJALQgKALgOAFQgNAHgQgBQgOAAgMgEgAgSg7QgIAGgFAKQgEAJgCALQgCALAAALQAAANACAMQACAMAFAJQAFAJAHAGQAIAFAKABQATgBAKgRQALgSAAgfQAAgKgCgMQgCgNgEgIQgGgJgHgGQgIgGgLAAQgKAAgIAGg");
	this.shape_18.setTransform(138.8,1.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgZBGQgNgGgIgLQgJgKgEgOQgEgOAAgPQAAgOAEgOQAFgNAIgLQAJgLAMgGQAMgGAPAAQAQAAALAFQALAFAHAIQAHAJADALQAEALAAANIAAAJIhfAAQAAAOADALQACAMAGAJQAGAIAJAFQAIAFANAAQANAAAKgGQAJgGAJgQIAKAGQgJASgPAKQgPAKgUAAQgRAAgNgGgAAggQIgCgRQgBgKgDgGQgDgHgGgEQgGgEgJAAQgPAAgKANQgKAMgBAXIBCAAg");
	this.shape_19.setTransform(116.4,1.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgsA3QgRgVgBgiQAAgPAGgNQAEgNAJgLQAJgLANgGQANgGAOAAQAWAAANAKQANAKAAASQAAAHgDAGQgEAFgIAAQgJAAgEgEQgFgFAAgFIACgNIACgLQgDgEgFgCIgLgBQgGAAgHADQgGADgGAIQgFAHgEANQgDAMAAARQAAAbAMARQAMARASAAQAOAAAKgHQAKgHAIgOIAKAHQgKARgQAKQgQAKgQAAQgfAAgSgVg");
	this.shape_20.setTransform(102.7,1.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AguA+QgKgMAAgYIAAhEQAAgFgCgEQgCgDgEgDIgHgDIgIgBIAAgJIAwgEIACACIAABjQAAAQAHAIQAHAIAKAAQAHAAAGgDQAHgCAEgDIAHgHIAEgGIAAhRQAAgFgCgEQgCgDgDgDQgDgCgFAAIgMgBIAAgJIA1gEIACACIAAByQAAAFACADQACAEAEACIAGACIAIABIAAAKIgvADIgCgCIAAgTIgBAAIgIAIIgKAIIgMAGQgGACgLAAQgTAAgKgNg");
	this.shape_21.setTransform(86.6,2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgoBuQgLgFgIgLQgJgKgFgNQgFgPAAgRQAAgQAFgNQAGgOAJgLQAJgJANgGQANgGANAAQAKAAAJADQAKACAHAEIAAgyQAAgHgCgEQgCgFgEgDQgEgDgHgBIgOgCIAAgJIA6gDIADACIAADCQAAAEACAFQABADAEACIAIADIAKAAIAAAKIgzADIgCgCIAAgOIgBAAQgIAJgLAFQgKAGgMAAQgMAAgMgGgAgXgUQgHAFgGAIQgFAHgEANQgDANAAAOQAAANADAKQACAKAGAJQAFAIAIAFQAIAFALAAQAKAAAIgFQAIgGAFgGIAAhTIgEgIIgGgIIgKgHQgGgCgHAAQgIAAgIAFg");
	this.shape_22.setTransform(69.9,-2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgZBGQgNgGgIgLQgJgKgEgOQgEgOAAgPQAAgOAEgOQAFgNAIgLQAJgLAMgGQAMgGAPAAQAQAAALAFQALAFAHAIQAHAJADALQAEALAAANIAAAJIhfAAQAAAOADALQACAMAGAJQAGAIAJAFQAIAFANAAQANAAAKgGQAJgGAJgQIAKAGQgJASgPAKQgPAKgUAAQgRAAgNgGgAAggQIgCgRQgBgKgDgGQgDgHgGgEQgGgEgJAAQgPAAgKANQgKAMgBAXIBCAAg");
	this.shape_23.setTransform(53.9,1.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("Ag2BKIAAgJIAIgCIAGgBQAEAAACgEQACgEAAgEIAAhZQAAgEgDgFQgCgEgDgDIgHgCIgIgBIAAgKIAwgDIACACIAAAUIABAAQAIgMALgGQALgGAJAAQAJAAAHAGQAFAGAAAKQAAAIgEAFQgDAGgIAAQgIAAgEgEQgEgFAAgFIAAgFIABgGQgHABgKAFQgIAGgGAKIAABTQAAAFACAEQACADADABIAKACIAKACIAAAJg");
	this.shape_24.setTransform(40.7,1.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgbBIQgMgGgKgKQgJgKgGgOQgGgOABgRQAAghATgWQATgWAgAAQAeAAATAVQAVAUgBAiQAAAPgEAPQgFAOgJALQgKALgNAFQgOAHgQgBQgOAAgMgEgAgSg7QgIAGgFAKQgFAJgCALQgCALAAALQABANACAMQACAMAFAJQAFAJAHAGQAIAFALABQASgBALgRQAKgSAAgfQAAgKgCgMQgDgNgEgIQgEgJgIgGQgIgGgKAAQgLAAgIAGg");
	this.shape_25.setTransform(18.9,1.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgPBXQgHgJAAgRIAAhhIgaAAIAAgOIAbAAIAAgtIAZAAIAAAtIApAAIAAAOIgoAAIAABQIABAPQAAAGACAFQADAEAFACQAEACAIABIALgBIAKgCIAAALIgSAHQgJACgMAAQgRAAgIgJg");
	this.shape_26.setTransform(5.6,-0.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("Ag1BhQgRgJAAgTQABgPAMgIQALgJATgBIAAgCIgKgDIgIgFIgGgHQgCgEgBgGQABgIAFgGQAGgGAKgFIAAgCQgOgHgHgKQgIgKAAgOQAAgUAQgOQAPgNAXAAIANACIANADIAzAAIAAAOIgjAAIAAABQAGAGADAIQACAHAAAIQAAATgQANQgPANgUAAIgRAAIgHAEQgEADAAAFQAAAFAEADQADADAEABIAKABIAMABIAQABIAQABQAHAAAGADQAIADAFAFQAFAFAEAHQADAHABALQgBAKgEAJQgEAKgKAGQgJAHgPAEQgNAEgTAAQghAAgQgKgAglAyQgGAHgBAMQAAAFACAEQADAFAFAEQAGAEAIACQAJADALAAQAVAAANgJQAMgIAAgRQAAgIgDgFQgEgFgIgCIgRgCIgdAAQgPADgHAHgAgThcQgFACgDAGQgDAEgBAHIgCAOQABAQAGALQAIAKALAAQAMAAAGgKQAIgKgBgQQABgRgIgKQgGgKgMAAQgHAAgFADg");
	this.shape_27.setTransform(-14.3,4.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AAKBKIAAgJIAIgBIAGgBQAEgBACgEQACgDAAgFIAAhKQAAgPgHgIQgHgJgLAAQgHAAgGADIgLAGIgIAHIgFAGIAABSQABAFACADQACAEADABIAHADIAIABIAAAJIhHAAIAAgJIAHgBIAGgBQAEgBACgEQACgDAAgFIAAhYQAAgFgCgFQgCgEgEgCIgGgDIgIgBIAAgKIAvgDIACACIAAAUIACAAIAIgIIAKgIQAGgDAGgDQAIgCAJAAQAVAAAJANQAKANAAAVIAABKQABAGACADQABADAEACIAGACIAIABIAAAJg");
	this.shape_28.setTransform(-30.7,1.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgfBvIAAgJIAHgCIAFgBQAFAAABgEQACgEAAgEIAAhZQAAgEgCgFQgBgDgFgDIgIgDIgJgBIAAgKIAygDIACACIAAB1QAAAFABADQADADAEACIAGACIAHACIAAAJgAgMhMQgGgGAAgIQAAgIAGgGQAFgGAHAAQAIAAAFAGQAGAGAAAHQAAAIgGAHQgFAFgIAAQgHABgFgGg");
	this.shape_29.setTransform(-44.1,-2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AAmBxIgZgjIgaglIgMALIAAAjQAAAFACADQACAEAEACIAHACIAHABIAAAJIhGAAIAAgJIAHgBIAGgBQAEgBACgEQACgDAAgFIAAinQAAgGgCgEQgDgFgDgCQgDgDgHgBIgKgBIAAgJIA1gDIACACIAACXIAZgYIAVgWIADgEIABgDQAAgEgGgCIgMgDIAAgJIA/AAIAAAJQgMAEgKAFIgOAKIgKAIIgSASIAbAjIAWAeQAGAJAFADQAGACAJABIAAAJg");
	this.shape_30.setTransform(-56.3,-2.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("Ag1BKIAAgJIAHgCIAFgBQAFAAACgEQACgEAAgEIAAhZQAAgEgDgFQgBgEgFgDIgGgCIgIgBIAAgKIAwgDIACACIAAAUIABAAQAIgMALgGQALgGAKAAQAJAAAGAGQAFAGAAAKQAAAIgDAFQgEAGgIAAQgIAAgEgEQgFgFABgFIAAgFIABgGQgHABgKAFQgJAGgFAKIAABTQAAAFACAEQACADADABIAKACIAJACIAAAJg");
	this.shape_31.setTransform(-70.2,1.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgbBIQgMgGgKgKQgJgKgGgOQgGgOAAgRQABghATgWQAUgWAeAAQAfAAAUAVQATAUAAAiQAAAPgEAPQgFAOgJALQgKALgOAFQgNAHgQgBQgNAAgNgEgAgSg7QgIAGgFAKQgEAJgDALQgBALAAALQgBANADAMQACAMAFAJQAFAJAHAGQAIAFAKABQATgBALgRQAKgSAAgfQAAgKgCgMQgCgNgEgIQgGgJgHgGQgIgGgLAAQgKAAgIAGg");
	this.shape_32.setTransform(-84.8,1.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AAmBJIgmhqIgnBqIgMAAIgVhBIgSg2QgDgHgGgEQgHgEgGgBIAAgKIBAAAIAAALIgLABQgFACAAADIABADIABAEIALAiIAPAwIAkhnIAOAAIAlBmIANglIALgjIACgHIABgGQAAgDgDgCIgGgDIgFgCIgGAAIAAgKIA3AAIAAAKQgGAAgHAFQgHAEgDAJIgOApIgPArIgFAQIgFARg");
	this.shape_33.setTransform(-103.7,1.9);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgZBGQgNgGgIgLQgJgKgEgOQgEgOAAgPQAAgOAEgOQAFgNAIgLQAJgLAMgGQAMgGAPAAQAQAAALAFQALAFAHAIQAHAJADALQAEALAAANIAAAJIhfAAQAAAOADALQACAMAGAJQAGAIAJAFQAIAFANAAQANAAAKgGQAJgGAJgQIAKAGQgJASgPAKQgPAKgUAAQgRAAgNgGgAAggQIgCgRQgBgKgDgGQgDgHgGgEQgGgEgJAAQgPAAgKANQgKAMgBAXIBCAAg");
	this.shape_34.setTransform(-129.2,1.9);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("Ag1BKIAAgJIAGgCIAGgBQAFAAACgEQACgEAAgEIAAhZQAAgEgCgFQgDgEgEgDIgGgCIgIgBIAAgKIAwgDIACACIAAAUIABAAQAIgMALgGQALgGAKAAQAIAAAGAGQAGAGAAAKQAAAIgDAFQgEAGgIAAQgIAAgEgEQgFgFAAgFIABgFIABgGQgHABgJAFQgKAGgFAKIAABTQAAAFACAEQACADADABIAKACIAJACIAAAJg");
	this.shape_35.setTransform(-142.4,1.7);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("Ag4BCQgLgKAAgQQAAgIADgHQACgGAFgFQADgFAHgDIALgGIAbgIQASgHAIgEIAAgPIgBgHQgBgFgDgFQgDgGgFgDQgEgFgKABQgHgBgGADQgGACgCADIACAJIABAKQAAAFgFAFQgFADgHAAQgIAAgDgEQgEgGAAgHQAAgGAFgGQAFgGAHgFQAHgEAJgDQAJgDAJAAQAMAAAJACQAKACAHAFQAHAGAEAIQAEAKAAAPIAAAkIgBAjQAAAGACADQACAEAEACIAHACIAKAAIAAAJIgMAEIgMABQgLABgHgGQgHgFgCgLIgBAAQgJALgKAGQgLAFgPAAQgRAAgKgKgAgEAAQgKADgHAGQgIAEgEAHQgFAHABAJQAAANAGAFQAGAGAKAAQALAAAGgFQAJgFAFgHIABgyg");
	this.shape_36.setTransform(-156.1,1.9);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgWBIQgLgFgFgEIgCAKIgLAAIgCgzIALAAQABAGADAIQAEAIAFAGQAGAGAJAFQAHAEAJAAQAOAAAIgHQAHgGAAgMQAAgGgCgEQgCgFgFgDIgMgGIgOgGIgQgFQgJgEgFgEQgHgFgEgHQgEgIAAgKQAAgSANgMQAOgMAVAAQAIAAAJACIAPAFIACgHIALAAIADAuIgKAAQgEgQgKgJQgKgKgOAAQgMAAgHAGQgGAGgBAJQAAAGADAEQACAFAEADIAMAGIAPAFIATAHQAIAFAFADQAHAGACAHQAEAHAAAKQAAAUgPAMQgPANgYAAQgMAAgKgEg");
	this.shape_37.setTransform(-177.7,1.9);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgOBXQgIgJAAgRIAAhhIgaAAIAAgOIAaAAIAAgtIAaAAIAAAtIAqAAIAAAOIgqAAIAABQIABAPQABAGACAFQADAEAEACQAFACAIABIALgBIAKgCIAAALIgSAHQgJACgMAAQgRAAgHgJg");
	this.shape_38.setTransform(-189.4,-0.2);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgWBIQgLgFgFgEIgDAKIgKAAIgCgzIALAAQABAGADAIQAEAIAFAGQAGAGAJAFQAHAEAJAAQAOAAAIgHQAHgGAAgMQABgGgDgEQgDgFgEgDIgMgGIgPgGIgPgFQgJgEgFgEQgHgFgEgHQgEgIAAgKQAAgSANgMQAOgMAVAAQAIAAAJACIAOAFIADgHIALAAIADAuIgKAAQgEgQgKgJQgKgKgOAAQgMAAgHAGQgGAGAAAJQAAAGACAEQACAFAFADIALAGIAPAFIATAHQAIAFAFADQAHAGACAHQAEAHAAAKQAAAUgPAMQgPANgYAAQgMAAgKgEg");
	this.shape_39.setTransform(-201,1.9);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AggBvIAAgJIAHgCIAHgBQADAAADgEQACgEAAgEIAAhZQAAgEgCgFQgDgDgDgDIgJgDIgJgBIAAgKIAygDIACACIAAB1QAAAFABADQADADAEACIAGACIAHACIAAAJgAgMhMQgFgGgBgIQABgIAFgGQAFgGAHAAQAIAAAGAGQAFAGAAAHQAAAIgFAHQgGAFgIAAQgHABgFgGg");
	this.shape_40.setTransform(-211.9,-2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgOBXQgIgJAAgRIAAhhIgaAAIAAgOIAbAAIAAgtIAZAAIAAAtIApAAIAAAOIgoAAIAABQIAAAPQABAGACAFQACAEAFACQAFACAIABIALgBIAKgCIAAALIgSAHQgJACgMAAQgRAAgHgJg");
	this.shape_41.setTransform(-221.5,-0.2);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AAKBKIAAgJIAHgBIAHgBQAEgBACgEQACgDAAgFIAAhKQAAgPgHgIQgHgJgLAAQgHAAgGADIgMAGIgHAHIgFAGIAABSQAAAFACADQACAEAEABIAIADIAHABIAAAJIhHAAIAAgJIAHgBIAGgBQAFgBACgEQABgDAAgFIAAhYQABgFgDgFQgCgEgEgCIgHgDIgHgBIAAgKIAwgDIABACIAAAUIABAAIAJgIIAKgIQAGgDAGgDQAHgCAKAAQAVAAAJANQALANgBAVIAABKQAAAGACADQACADAEACIAHACIAGABIAAAJg");
	this.shape_42.setTransform(-235.3,1.7);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AgZBGQgNgGgIgLQgJgKgEgOQgEgOAAgPQAAgOAEgOQAFgNAIgLQAJgLAMgGQAMgGAPAAQAQAAALAFQALAFAHAIQAHAJADALQAEALAAANIAAAJIhfAAQAAAOADALQACAMAGAJQAGAIAJAFQAIAFANAAQANAAAKgGQAJgGAJgQIAKAGQgJASgPAKQgPAKgUAAQgRAAgNgGgAAggQIgCgRQgBgKgDgGQgDgHgGgEQgGgEgJAAQgPAAgKANQgKAMgBAXIBCAAg");
	this.shape_43.setTransform(-251.3,1.9);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AggBvIAAgJIAHgCIAHgBQADAAADgEQACgEAAgEIAAhZQAAgEgCgFQgDgDgDgDIgJgDIgJgBIAAgKIAygDIACACIAAB1QAAAFABADQADADAEACIAGACIAHACIAAAJgAgMhMQgFgGgBgIQABgIAFgGQAFgGAHAAQAIAAAGAGQAFAGAAAHQAAAIgFAHQgGAFgIAAQgHABgFgGg");
	this.shape_44.setTransform(-263.2,-2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AgrA3QgTgVABgiQAAgPAEgNQAFgNAJgLQAJgLANgGQANgGAOAAQAVAAAOAKQANAKAAASQAAAHgEAGQgDAFgIAAQgJAAgEgEQgFgFAAgFIABgNIACgLQgCgEgFgCIgMgBQgGAAgFADQgHADgGAIQgFAHgEANQgDAMAAARQAAAbAMARQAMARASAAQAOAAALgHQAJgHAIgOIAKAHQgKARgQAKQgQAKgRAAQgeAAgRgVg");
	this.shape_45.setTransform(-273.8,1.9);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgWBIQgLgFgFgEIgCAKIgLAAIgCgzIALAAQABAGADAIQAEAIAFAGQAGAGAJAFQAHAEAJAAQAOAAAIgHQAHgGABgMQgBgGgCgEQgCgFgFgDIgMgGIgOgGIgQgFQgIgEgHgEQgGgFgEgHQgEgIAAgKQAAgSANgMQAOgMAVAAQAIAAAJACIAPAFIACgHIALAAIADAuIgLAAQgDgQgKgJQgKgKgOAAQgMAAgHAGQgGAGgBAJQAAAGADAEQACAFAEADIAMAGIAPAFIASAHQAJAFAFADQAGAGADAHQAEAHAAAKQAAAUgPAMQgPANgYAAQgMAAgKgEg");
	this.shape_46.setTransform(-287.6,1.9);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("Ag1BKIAAgJIAHgCIAFgBQAFAAACgEQACgEAAgEIAAhZQAAgEgCgFQgCgEgFgDIgGgCIgIgBIAAgKIAwgDIACACIAAAUIABAAQAIgMALgGQALgGAKAAQAIAAAGAGQAGAGAAAKQAAAIgDAFQgEAGgIAAQgIAAgEgEQgFgFABgFIAAgFIABgGQgHABgJAFQgKAGgFAKIAABTQAAAFACAEQACADADABIAKACIAJACIAAAJg");
	this.shape_47.setTransform(-307,1.7);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AguA+QgKgMAAgYIAAhEQAAgFgCgEQgCgDgEgDIgHgDIgIgBIAAgJIAwgEIACACIAABjQAAAQAHAIQAHAIAKAAQAHAAAGgDQAHgCAEgDIAHgHIAEgGIAAhRQAAgFgCgEQgCgDgDgDQgDgCgFAAIgMgBIAAgJIA1gEIACACIAAByQAAAFACADQACAEAEACIAGACIAIABIAAAKIgvADIgCgCIAAgTIgBAAIgIAIIgKAIIgMAGQgGACgLAAQgTAAgKgNg");
	this.shape_48.setTransform(-322.3,2);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AgbBIQgNgGgJgKQgJgKgGgOQgGgOABgRQAAghATgWQATgWAgAAQAeAAATAVQAVAUgBAiQAAAPgEAPQgFAOgJALQgKALgNAFQgOAHgQgBQgOAAgMgEgAgSg7QgIAGgFAKQgFAJgCALQgCALAAALQABANACAMQACAMAFAJQAFAJAHAGQAIAFALABQASgBALgRQAKgSAAgfQAAgKgCgMQgDgNgEgIQgEgJgIgGQgIgGgKAAQgLAAgIAGg");
	this.shape_49.setTransform(-338.8,1.9);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AgoBuQgLgFgIgLQgJgKgFgNQgFgPAAgRQAAgQAFgNQAGgOAJgLQAJgJANgGQANgGANAAQAKAAAJADQAKACAHAEIAAgyQAAgHgCgEQgCgFgEgDQgEgDgHgBIgOgCIAAgJIA6gDIADACIAADCQAAAEACAFQABADAEACIAIADIAKAAIAAAKIgzADIgCgCIAAgOIgBAAQgIAJgLAFQgKAGgMAAQgMAAgMgGgAgXgUQgHAFgGAIQgFAHgEANQgDANAAAOQAAANADAKQACAKAGAJQAFAIAIAFQAIAFALAAQAKAAAIgFQAIgGAFgGIAAhTIgEgIIgGgIIgKgHQgGgCgHAAQgIAAgIAFg");
	this.shape_50.setTransform(-362.4,-2);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AAKBKIAAgJIAHgBIAHgBQAEgBACgEQACgDAAgFIAAhKQAAgPgHgIQgHgJgLAAQgHAAgGADIgMAGIgHAHIgEAGIAABSQAAAFABADQACAEAFABIAGADIAIABIAAAJIhHAAIAAgJIAHgBIAGgBQAEgBADgEQACgDAAgFIAAhYQgBgFgCgFQgCgEgEgCIgHgDIgIgBIAAgKIAxgDIACACIAAAUIABAAIAIgIIAKgIQAFgDAHgDQAHgCAKAAQAUAAALANQAJANABAVIAABKQAAAGABADQACADAFACIAFACIAHABIAAAJg");
	this.shape_51.setTransform(-380.1,1.7);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AAVBpIAAgKQALgBAIgCQAHgCAAgDIAAgDIgBgEIgRgvIhIAAIgHASIgFAPIgCAKIgBAGQAAAGAJAEQAKACALABIAAAKIhOAAIAAgKIAKgBIAJgFQAGgDADgFIAHgMIAihXIAhhWIALAAIBFCyIAGAJIAIAHIAIAEIAJABIAAAKgAAXAVIgehQIgfBQIA9AAg");
	this.shape_52.setTransform(-399,-1.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(-485.3,-20.4,970.4,38.1), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgNAOQgGgFAAgJQAAgHAGgGQAGgGAHAAQAIAAAGAGQAGAGAAAHQAAAJgGAFQgGAGgIAAQgHAAgGgGg");
	this.shape.setTransform(204.8,29.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("Ag1BhQgQgJAAgTQgBgPAMgIQAMgJASgBIAAgCIgJgDIgIgFIgGgHQgCgEAAgGQgBgIAGgGQAFgGALgFIAAgCQgNgHgIgKQgIgKAAgOQAAgUAPgOQAQgNAYAAIAMACIANADIAyAAIAAAOIghAAIAAABQAFAGACAIQADAHAAAIQAAATgQANQgPANgUAAIgRAAIgHAEQgDADAAAFQAAAFACADQADADAFABIAKABIALABIARABIAQABQAGAAAIADQAGADAGAFQAFAFAEAHQADAHAAALQABAKgFAJQgEAKgKAGQgKAHgNAEQgOAEgTAAQghAAgQgKgAglAyQgHAHABAMQAAAFACAEQACAFAFAEQAGAEAIACQAIADAMAAQAWAAAMgJQANgIAAgRQAAgIgFgFQgDgFgIgCIgRgCIgcAAQgQADgHAHgAgThcQgFACgDAGQgDAEgBAHIgBAOQgBAQAIALQAHAKALAAQALAAAIgKQAGgKABgQQgBgRgGgKQgIgKgLAAQgHAAgFADg");
	this.shape_1.setTransform(193.2,27.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AAKBKIAAgJIAHgBIAHgBQAEgBACgEQACgDAAgFIAAhKQAAgPgHgIQgIgJgKAAQgHAAgGADIgMAGIgHAHIgFAGIAABSQABAFABADQADAEAEABIAHADIAHABIAAAJIhHAAIAAgJIAHgBIAGgBQAFgBACgEQABgDAAgFIAAhYQAAgFgCgFQgCgEgEgCIgHgDIgIgBIAAgKIAxgDIABACIAAAUIABAAIAJgIIAKgIQAGgDAGgDQAIgCAJAAQAVAAAKANQAKANgBAVIAABKQABAGABADQACADAFACIAGACIAGABIAAAJg");
	this.shape_2.setTransform(176.8,23.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AggBvIAAgKIAHgBIAHgBQADgBADgDQACgDAAgFIAAhYQAAgGgCgDQgDgEgDgDIgJgCIgJgDIAAgJIAygDIACACIAAB0QAAAGABADQADADAEACIAGACIAHABIAAAKgAgMhMQgFgGAAgIQAAgIAFgGQAFgGAHAAQAIAAAGAGQAFAGAAAHQAAAIgFAGQgGAHgIAAQgHgBgFgFg");
	this.shape_3.setTransform(163.4,20.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAKBKIAAgJIAHgBIAHgBQAEgBACgEQACgDAAgFIAAhKQAAgPgHgIQgHgJgLAAQgHAAgGADIgMAGIgHAHIgFAGIAABSQAAAFACADQACAEAFABIAHADIAHABIAAAJIhHAAIAAgJIAHgBIAGgBQAFgBACgEQABgDAAgFIAAhYQABgFgDgFQgCgEgEgCIgHgDIgHgBIAAgKIAwgDIABACIAAAUIABAAIAJgIIAKgIQAGgDAGgDQAHgCAKAAQAVAAAJANQALANgBAVIAABKQAAAGACADQACADAFACIAGACIAGABIAAAJg");
	this.shape_4.setTransform(150.3,23.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgZBGQgNgGgIgLQgJgKgEgOQgEgOAAgPQAAgOAEgOQAFgNAIgLQAJgLAMgGQAMgGAPAAQAQAAALAFQALAFAHAIQAHAJADALQAEALAAANIAAAJIhfAAQAAAOADALQACAMAGAJQAGAIAJAFQAIAFANAAQANAAAKgGQAJgGAJgQIAKAGQgJASgPAKQgPAKgUAAQgRAAgNgGgAAggQIgCgRQgBgKgDgGQgDgHgGgEQgGgEgJAAQgPAAgKANQgKAMgBAXIBCAAg");
	this.shape_5.setTransform(134.3,24.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgOBXQgIgJAAgRIAAhhIgaAAIAAgOIAaAAIAAgtIAaAAIAAAtIAqAAIAAAOIgqAAIAABQIABAPQABAGADAFQACAEAEACQAFADAIAAIALgBIAKgCIAAALIgSAGQgJADgMAAQgRAAgHgJg");
	this.shape_6.setTransform(121.6,22);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgWBIQgLgFgFgEIgDAKIgKAAIgCgzIALAAQAAAGAEAIQAEAIAFAGQAGAGAIAFQAIAEAJAAQAOAAAIgHQAHgGAAgMQABgGgDgEQgDgFgEgDIgMgGIgPgGIgPgFQgJgEgFgEQgHgFgEgHQgEgIAAgKQAAgSANgMQANgMAXAAQAHAAAJACIAOAFIADgHIALAAIADAuIgKAAQgEgQgKgJQgKgKgOAAQgMAAgHAGQgGAGAAAJQAAAGACAEQACAFAFADIALAGIAPAFIATAHQAIAFAFADQAHAGACAHQAEAHAAAKQAAAUgPAMQgPANgYAAQgMAAgKgEg");
	this.shape_7.setTransform(110,24.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgfBvIAAgKIAGgBIAGgBQAFgBACgDQACgDAAgFIAAhYQAAgGgCgDQgCgEgFgDIgIgCIgJgDIAAgJIAygDIACACIAAB0QAAAGABADQADADAEACIAGACIAHABIAAAKgAgMhMQgFgGgBgIQABgIAFgGQAFgGAHAAQAIAAAGAGQAFAGAAAHQAAAIgFAGQgGAHgIAAQgHgBgFgFg");
	this.shape_8.setTransform(99.2,20.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgeByIAAgKIAHgBIAGgBQAEgBACgEQACgDAAgFIAAinQAAgFgCgFQgCgEgEgCIgKgEIgLgCIAAgJIA1gDIACACIAADFQAAAGACADQACADAEABIAHADIAHABIAAAKg");
	this.shape_9.setTransform(90.2,20);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgZBGQgNgGgIgLQgJgKgEgOQgEgOAAgPQAAgOAEgOQAFgNAIgLQAJgLAMgGQAMgGAPAAQAQAAALAFQALAFAHAIQAHAJADALQAEALAAANIAAAJIhfAAQAAAOADALQACAMAGAJQAGAIAJAFQAIAFANAAQANAAAKgGQAJgGAJgQIAKAGQgJASgPAKQgPAKgUAAQgRAAgNgGgAAggQIgCgRQgBgKgDgGQgDgHgGgEQgGgEgJAAQgPAAgKANQgKAMgBAXIBCAAg");
	this.shape_10.setTransform(72,24.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("Ag1BKIAAgKIAHgBIAFgBQAFgBACgDQACgDAAgFIAAhYQAAgFgCgEQgCgFgFgCIgGgDIgIgCIAAgJIAwgDIACACIAAAUIABAAQAIgMALgGQALgGAKAAQAIAAAGAGQAGAGAAAKQAAAHgDAHQgEAFgIAAQgIAAgEgEQgFgFABgEIAAgHIABgEQgHgBgJAGQgKAFgFALIAABTQAAAFACADQACAEADABIAKACIAJABIAAAKg");
	this.shape_11.setTransform(58.8,23.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgEApIgHgpQgFgSAAgGQAAgGAFgFQADgFAIAAQAIAAAEAFQAEAFABAGQAAAGgFARIgIAqg");
	this.shape_12.setTransform(49.1,13);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgZBGQgNgGgIgLQgJgKgEgOQgEgOAAgPQAAgOAEgOQAFgNAIgLQAJgLAMgGQAMgGAPAAQAQAAALAFQALAFAHAIQAHAJADALQAEALAAANIAAAJIhfAAQAAAOADALQACAMAGAJQAGAIAJAFQAIAFANAAQANAAAKgGQAJgGAJgQIAKAGQgJASgPAKQgPAKgUAAQgRAAgNgGgAAggQIgCgRQgBgKgDgGQgDgHgGgEQgGgEgJAAQgPAAgKANQgKAMgBAXIBCAAg");
	this.shape_13.setTransform(38.8,24.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAyBpIgzifIg3CfIgNAAIgehpIgVhKIgDgIIgHgGIgJgEIgJgCIAAgKIBVAAIAAAKIgTACQgIACAAAEIAAAEIABAEIAMAqIAaBYIAziZIAOAAIA0CdIASg/IANgvIAEgSIABgJQAAgFgGgDQgHgEgQgBIAAgKIBMAAIAAAKIgJACIgJAEQgFADgDAEQgDAFgCAHIgZBOIgdBgg");
	this.shape_14.setTransform(16.9,21);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,1.8,210.9,38.1), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AABAkIAOgIIANgJIAJgLQAEgGACgHIgHAAQgKAAgFgFQgFgGAAgGQAAgIAGgIQAHgHAKAAQAMAAAGAGQAGAHAAAKQAAAPgHAKQgGAMgJAIQgJAIgKAGIgQAJgAg9AkIAOgIIAMgJIAKgLQAEgGACgHIgHAAQgLAAgEgFQgFgGAAgGQAAgIAGgIQAGgHALAAQAMAAAGAGQAFAHAAAKQAAAPgGAKQgGAMgJAIQgJAIgKAGIgRAJg");
	this.shape.setTransform(735.4,12.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgQARQgGgHgBgKQABgIAGgHQAIgHAIAAQAJAAAIAHQAGAHABAIQgBAKgGAHQgIAGgJAAQgIAAgIgGg");
	this.shape_1.setTransform(721.3,32.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag0BQQgRgJAAgPQAAgGAFgGQAFgGAHAAQAHAAAEADQAEADACAEIAFALIADAKIAHAFQAFADAIAAQASAAAJgJQAKgKAAgQQAAgLgJgHQgJgHgRgGIgOgGQgJgEgFgEQgGgGgEgHQgEgIAAgKQAAgWAUgQQATgQAcAAIAOABIARAEQAIACAGAGQAFAFAAAJQAAAHgEAFQgFAGgIAAQgGAAgEgDQgEgCgDgFIgEgKIgEgKIgGgCIgHgBQgPAAgJAJQgJAJAAANQAAAMAIAGQAIAGARAGQAXAJALAJQAKALAAAQQAAAagUAQQgUARgdAAQgaAAgQgJg");
	this.shape_2.setTransform(709.1,25.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgjB/QgHgHAAgKIABgIIACgMIAoizIACgHIABgFQAAgGgDgEQgBgDgDgCIgJgCIgLgBIACgKIA/gEIABADIguDNIgEAMIgBALQAAAJAFAEQADAEAJAAIALgBIAKgCIgDALIgXAJQgIACgKAAQgNAAgIgHg");
	this.shape_3.setTransform(697.8,21.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag4BIQgQgRAAgfQAAgWAGgTQAHgTANgQQANgQASgKQARgKAXAAQAYAAAMAKQAMAKAAAQQAAASgLANQgMANgVAIQgQAEgQAEIgjAGQAAAbAKAOQAKAPASAAQARAAANgJQANgJANgQIAJAHQgNAVgVAMQgUANgVAAQgeAAgQgRgAgPg1QgSAWgEAhIAbgEQAOgDAKgFQAOgIAHgLQAHgMAAgPQAAgHgCgEIgFgGIgHgCIgHgBQgUAAgQAXg");
	this.shape_4.setTransform(683.8,25.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhDBOQgJgJAAgQIAAgKIADgRIAOg1IADgNIABgLQAAgKgEgDQgDgDgJAAIgKACIgJACIADgLIAXgJQAKgDAGgBQAOAAAGAHQAHAGAAAMIgBAIIgCALIgPA+IgDAOIgBAJQAAALAFAIQAFAGALAAQALAAALgFQALgHALgLIAeiAIAegCIACADIgZBtIgEAOIgBAKQAAAJAEAEQAEAEAKAAIAJgCIAKgCIgDALIgXAJQgKADgIAAQgOAAgHgIQgGgIAAgLIgBAAIgPALIgOAKIgPAGQgGACgLAAQgQAAgJgKg");
	this.shape_5.setTransform(665.3,25.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhtCkQgHgFAAgJQAAgHAEgGQAEgGAJAAQAFAAAEADIAHAGIAGAIIAFAIQANgBAJgRQAKgQAGggIAgiSIghAAIADgQIAgAAIADgLQAEgUAJgQQAIgQAMgLQALgLAOgGQAOgGANAAQAPAAAHAGQAHAFAAAJQAAAHgEAGQgEAFgJAAQgFAAgEgCIgHgGIgGgIIgFgIQgMAAgJAPQgJAPgHAjIgEASIArAAIgEAQIgqAAIgdCMQgIAmgaAYQgaAYgbAAQgPAAgHgGg");
	this.shape_6.setTransform(649.3,24.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgiB/QgIgHAAgKIABgIIACgMIAoizIACgHIAAgFQAAgGgCgEQgBgDgDgCIgKgCIgLgBIADgKIA/gEIABADIgvDNIgDAMIgBALQAAAJAEAEQAEAEAKAAIAKgBIAKgCIgDALIgYAJQgGACgLAAQgNAAgHgHg");
	this.shape_7.setTransform(631.3,21.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgdB8QgGgHgBgKIABgIIADgLIAShJIACgNIABgKQAAgKgCgDQgEgDgKAAIgKABIgJACIACgLIAYgJQALgDAGAAQANAAAGAHQAHAGAAAMIgBAIIgCALIgSBIIgCANIgBAKQAAAKADADQAEAEAKAAIAJgBIAJgCIgCALIgZAJIgPACQgOAAgHgHgAAJhbQgFgHAAgJQAAgJAFgHQAHgHAJAAQAJAAAHAGQAGAHAAAJQAAAJgGAIQgHAHgJAAQgJAAgHgHg");
	this.shape_8.setTransform(620.9,21.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag0BQQgRgJAAgPQAAgGAFgGQAFgGAHAAQAHAAAEADQAEADACAEIAFALIADAKIAHAFQAFADAIAAQASAAAJgJQAKgKAAgQQAAgLgJgHQgJgHgRgGIgOgGQgJgEgFgEQgGgGgEgHQgEgIAAgKQAAgWAUgQQATgQAcAAIAOABIARAEQAIACAGAGQAFAFAAAJQAAAHgEAFQgFAGgIAAQgGAAgEgDQgEgCgDgFIgEgKIgEgKIgGgCIgHgBQgPAAgJAJQgJAJAAANQAAAMAIAGQAIAGARAGQAXAJALAJQAKALAAAQQAAAagUAQQgUARgdAAQgaAAgQgJg");
	this.shape_9.setTransform(607.2,25.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag0BQQgRgJAAgPQAAgGAFgGQAFgGAHAAQAHAAAEADQAEADACAEIAFALIADAKIAHAFQAFADAIAAQASAAAJgJQAKgKAAgQQAAgLgJgHQgJgHgRgGIgOgGQgJgEgFgEQgGgGgEgHQgEgIAAgKQAAgWAUgQQATgQAcAAIAOABIARAEQAIACAGAGQAFAFAAAJQAAAHgEAFQgFAGgIAAQgGAAgEgDQgEgCgDgFIgEgKIgEgKIgGgCIgHgBQgPAAgJAJQgJAJAAANQAAAMAIAGQAIAGARAGQAXAJALAJQAKALAAAQQAAAagUAQQgUARgdAAQgaAAgQgJg");
	this.shape_10.setTransform(592.2,25.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhABHQgRgTAAgfQAAgVAHgUQAIgUAMgPQANgPATgJQATgJAVAAQAeAAARATQARASAAAeQABAUgIAUQgGAUgNAPQgNAQgSAJQgUAKgXAAQgcAAgSgSgAgLhDQgNAJgJATQgHAPgEATQgCARAAAPQgBAZAJAMQAIANARAAQAPAAALgKQAMgJAIgPQAHgOAEgTQADgSAAgTQAAgYgIgNQgJgMgQAAQgOAAgLAJg");
	this.shape_11.setTransform(575.5,25.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhtCkQgHgFAAgJQAAgHAEgGQAEgGAJAAQAFAAAEADIAHAGIAGAIIAFAIQANgBAJgRQAKgQAGggIAgiSIghAAIADgQIAgAAIADgLQAEgUAJgQQAIgQAMgLQALgLAOgGQAOgGANAAQAPAAAHAGQAHAFAAAJQAAAHgEAGQgEAFgJAAQgFAAgEgCIgHgGIgGgIIgFgIQgMAAgJAPQgJAPgHAjIgEASIArAAIgEAQIgqAAIgdCMQgIAmgaAYQgaAYgbAAQgPAAgHgGg");
	this.shape_12.setTransform(560.2,24.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAbBQQgHgHAAgKIABgIIACgLIARg/IADgNIABgKQAAgLgGgHQgFgHgKAAQgLAAgMAHQgMAHgMANIgdB9IggAAIAZhuIADgMIACgNQAAgJgDgDQgEgEgKAAIgKACIgIACIACgLIAYgJQAKgDAIAAQANAAAGAHQAFAIABANIABAAQATgPAMgIQAOgHASAAQAPAAAKAKQAJAJAAAPIAAALIgEAQIgOA2IgDAMIgCAMQAAAJAFAEQAEADAJAAIAKgBIAJgCIgCALIgZAJQgIADgJAAQgNAAgHgIg");
	this.shape_13.setTransform(536.1,25.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhABHQgRgTgBgfQAAgVAIgUQAHgUANgPQANgPATgJQASgJAWAAQAeAAASATQAQASABAeQgBAUgHAUQgGAUgNAPQgNAQgTAJQgSAKgYAAQgcAAgSgSgAgMhDQgMAJgJATQgHAPgDATQgEARAAAPQAAAZAJAMQAIANARAAQAOAAAMgKQAMgJAHgPQAIgOADgTQAFgSAAgTQAAgYgJgNQgIgMgRAAQgOAAgMAJg");
	this.shape_14.setTransform(516.3,25.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AguBoQgIgHAAgMIABgHIABgJIAbhxIgfAAIAEgPIAfAAIAMgyIAeAAIgMAyIAwAAIgEAPIgvAAIgVBdIgDANIgBAKQAAAKAFAEQAFAFALAAIAMgCIANgCIgDAMIgXAIQgJADgOAAQgRAAgHgGg");
	this.shape_15.setTransform(493.8,23.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAbBQQgHgHAAgKIABgIIACgLIARg/IADgNIABgKQAAgLgFgHQgGgHgLAAQgKAAgMAHQgNAHgLANIgdB9IggAAIAahuIACgMIABgNQAAgJgDgDQgDgEgJAAIgLACIgJACIADgLIAYgJQAKgDAHAAQAOAAAGAHQAFAIABANIABAAQATgPANgIQANgHARAAQARAAAJAKQAJAJAAAPIgBALIgDAQIgOA2IgDAMIgBAMQAAAJADAEQAFADAKAAIAJgBIAKgCIgDALIgYAJQgJADgIAAQgOAAgHgIg");
	this.shape_16.setTransform(476.2,25.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhKBHQgOgSAAgfQAAgVAIgTQAHgUAOgQQANgPATgJQASgKASAAQAMAAALADQALAEAGAEIAggIIACACIgaBuIgDAMIgBAMQAAAKADADQAFADAKAAIAJgBIAJgCIgCALIgYAJQgHADgLAAQgMAAgHgIQgIgHAAgLIgBAAIgJAIIgMAJIgOAHQgIAEgJAAQgZAAgOgSgAgLhEQgMAJgKAOQgIANgGASQgGASAAATIABASQACAIADAHQADAGAHAEQAFADAKAAQAKAAAKgFQAJgFANgOIAXhbIgCgLQgBgFgEgEQgDgFgGgCQgGgDgJAAQgMAAgLAIg");
	this.shape_17.setTransform(455.8,25.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgdB8QgHgHAAgKIABgIIADgLIAShJIACgNIACgKQgBgKgCgDQgEgDgKAAIgKABIgJACIACgLIAYgJQALgDAGAAQANAAAGAHQAHAGAAAMIgBAIIgCALIgSBIIgCANIgBAKQAAAKADADQAEAEAKAAIAJgBIAJgCIgCALIgZAJIgPACQgOAAgHgHgAAJhbQgFgHAAgJQAAgJAFgHQAHgHAJAAQAJAAAHAGQAGAHAAAJQAAAJgGAIQgHAHgJAAQgJAAgHgHg");
	this.shape_18.setTransform(441.3,21.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgiB/QgIgHAAgKIABgIIACgMIApizIABgHIAAgFQAAgGgBgEQgCgDgDgCIgKgCIgKgBIACgKIA+gEIACADIgvDNIgCAMIgCALQAAAJAEAEQAEAEAKAAIAKgBIAKgCIgCALIgZAJQgGACgLAAQgOAAgGgHg");
	this.shape_19.setTransform(431.3,21.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag4BIQgQgRAAgfQAAgWAGgTQAHgTANgQQANgQASgKQARgKAXAAQAYAAAMAKQAMAKAAAQQAAASgLANQgMANgVAIQgQAEgQAEIgjAGQAAAbAKAOQAKAPASAAQARAAANgJQANgJANgQIAJAHQgNAVgVAMQgUANgVAAQgeAAgQgRgAgPg1QgSAWgEAhIAbgEQAOgDAKgFQAOgIAHgLQAHgMAAgPQAAgHgCgEIgFgGIgHgCIgHgBQgUAAgQAXg");
	this.shape_20.setTransform(417.4,25.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhEBWIAZhuIACgMIACgMQAAgKgDgDQgDgDgKAAIgKABIgJACIADgLIAXgJQALgCAHAAQAOAAAFAHQAGAHAAAPIABAAQAUgRAKgHQALgHALAAIALABQAFABADAEQAEADACAFQACAFAAAIIgCALIgEAJIgGAIQgEACgHAAQgJAAgFgFQgEgEAAgGQAAgFACgHIAGgNIgHABIgLAFIgQAJQgIAHgIALIgcB5g");
	this.shape_21.setTransform(401.6,25.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("Ag0BQQgRgJAAgPQAAgGAFgGQAFgGAHAAQAHAAAEADQAEADACAEIAFALIADAKIAHAFQAFADAIAAQASAAAJgJQAKgKAAgQQAAgLgJgHQgJgHgRgGIgOgGQgJgEgFgEQgGgGgEgHQgEgIAAgKQAAgWAUgQQATgQAcAAIAOABIARAEQAIACAGAGQAFAFAAAJQAAAHgEAFQgFAGgIAAQgGAAgEgDQgEgCgDgFIgEgKIgEgKIgGgCIgHgBQgPAAgJAJQgJAJAAANQAAAMAIAGQAIAGARAGQAXAJALAJQAKALAAAQQAAAagUAQQgUARgdAAQgaAAgQgJg");
	this.shape_22.setTransform(376.6,25.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag0BQQgRgJAAgPQAAgGAFgGQAFgGAHAAQAHAAAEADQAEADACAEIAFALIADAKIAHAFQAFADAIAAQASAAAJgJQAKgKAAgQQAAgLgJgHQgJgHgRgGIgOgGQgJgEgFgEQgGgGgEgHQgEgIAAgKQAAgWAUgQQATgQAcAAIAOABIARAEQAIACAGAGQAFAFAAAJQAAAHgEAFQgFAGgIAAQgGAAgEgDQgEgCgDgFIgEgKIgEgKIgGgCIgHgBQgPAAgJAJQgJAJAAANQAAAMAIAGQAIAGARAGQAXAJALAJQAKALAAAQQAAAagUAQQgUARgdAAQgaAAgQgJg");
	this.shape_23.setTransform(361.6,25.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag4BIQgQgRAAgfQAAgWAGgTQAHgTANgQQANgQASgKQARgKAXAAQAYAAAMAKQAMAKAAAQQAAASgLANQgMANgVAIQgQAEgQAEIgjAGQAAAbAKAOQAKAPASAAQARAAANgJQANgJANgQIAJAHQgNAVgVAMQgUANgVAAQgeAAgQgRgAgPg1QgSAWgEAhIAbgEQAOgDAKgFQAOgIAHgLQAHgMAAgPQAAgHgCgEIgFgGIgHgCIgHgBQgUAAgQAXg");
	this.shape_24.setTransform(346.3,25.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgiB/QgIgHAAgKIABgIIACgMIAoizIACgHIAAgFQAAgGgCgEQgBgDgDgCIgKgCIgLgBIADgKIA+gEIACADIgvDNIgDAMIgBALQAAAJAEAEQAEAEAKAAIAKgBIAKgCIgCALIgZAJQgHACgKAAQgOAAgGgHg");
	this.shape_25.setTransform(333.8,21.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("Ag4BIQgQgRAAgfQAAgWAGgTQAHgTANgQQANgQASgKQARgKAXAAQAYAAAMAKQAMAKAAAQQAAASgLANQgMANgVAIQgQAEgQAEIgjAGQAAAbAKAOQAKAPASAAQARAAANgJQANgJANgQIAJAHQgNAVgVAMQgUANgVAAQgeAAgQgRgAgPg1QgSAWgEAhIAbgEQAOgDAKgFQAOgIAHgLQAHgMAAgPQAAgHgCgEIgFgGIgHgCIgHgBQgUAAgQAXg");
	this.shape_26.setTransform(311.4,25.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgoCEQgMgCgHgEQgIgFgFgFIgKgNIAsjAIACgHIAAgGQAAgGgCgDQgCgEgEgBIgJgCIgLgCIACgKIA+gEIACADIgZBxIABAAQAPgNALgGQAMgFALAAQAaAAAPASQAPASAAAcQAAAXgJAVQgHAVgOAPQgOAPgSAJQgRAJgTAAQgOAAgLgDgAABgVIgJAFIgKAIIgJAIIgXBkIAEAIIAGAHQAFAEAGACQAGACAHAAQAOAAAKgIQAMgIAJgOQAJgOAFgSQAFgTgBgTIgBgSQgBgIgEgGQgFgHgGgDQgHgEgKAAQgGAAgGACg");
	this.shape_27.setTransform(293.5,21.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AhABHQgRgTAAgfQgBgVAIgUQAIgUAMgPQANgPATgJQATgJAVAAQAeAAARATQARASAAAeQABAUgIAUQgGAUgNAPQgNAQgSAJQgUAKgXAAQgcAAgSgSgAgMhDQgMAJgJATQgHAPgDATQgDARAAAPQgBAZAJAMQAIANARAAQAOAAAMgKQAMgJAHgPQAIgOAEgTQADgSAAgTQAAgYgIgNQgJgMgQAAQgOAAgMAJg");
	this.shape_28.setTransform(265.8,25.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AguBoQgIgHAAgMIABgHIABgJIAbhxIgfAAIAEgPIAfAAIAMgyIAeAAIgMAyIAwAAIgEAPIgvAAIgVBdIgDANIgBAKQAAAKAFAEQAFAFALAAIAMgCIANgCIgDAMIgXAIQgJADgOAAQgRAAgHgGg");
	this.shape_29.setTransform(251.8,23.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("Ag0BQQgRgJAAgPQAAgGAFgGQAFgGAHAAQAHAAAEADQAEADACAEIAFALIADAKIAHAFQAFADAIAAQASAAAJgJQAKgKAAgQQAAgLgJgHQgJgHgRgGIgOgGQgJgEgFgEQgGgGgEgHQgEgIAAgKQAAgWAUgQQATgQAcAAIAOABIARAEQAIACAGAGQAFAFAAAJQAAAHgEAFQgFAGgIAAQgGAAgEgDQgEgCgDgFIgEgKIgEgKIgGgCIgHgBQgPAAgJAJQgJAJAAANQAAAMAIAGQAIAGARAGQAXAJALAJQAKALAAAQQAAAagUAQQgUARgdAAQgaAAgQgJg");
	this.shape_30.setTransform(228.1,25.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AhSB1QgOgSAAgfQAAgVAHgVQAIgUANgOQANgPASgJQASgKATAAQALAAAMADQAMADAHAFIANg6IACgIIAAgFQAAgGgCgEQgDgDgEgBIgLgCIgNgCIACgKIBFgEIACADIgvDMIgDANIgCALQAAAJAFAEQAEADAJAAIAKgBIAJgCIgDALIgYAJQgJADgIAAQgMAAgIgHQgHgGAAgOIgBAAIgKAJIgLAJIgPAIQgHADgKAAQgZAAgOgSgAgWgWQgLAJgJANQgJANgFASQgFATAAASIABATQABAIAEAHQADAGAGAEQAGADAKAAQAJAAALgFQAKgGAOgOIAWhcIgDgJIgGgJQgEgEgGgDQgGgDgJAAQgMAAgMAIg");
	this.shape_31.setTransform(211.6,21.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("Ag4BIQgQgRAAgfQAAgWAGgTQAHgTANgQQANgQASgKQARgKAXAAQAYAAAMAKQAMAKAAAQQAAASgLANQgMANgVAIQgQAEgQAEIgjAGQAAAbAKAOQAKAPASAAQARAAANgJQANgJANgQIAJAHQgNAVgVAMQgUANgVAAQgeAAgQgRgAgPg1QgSAWgEAhIAbgEQAOgDAKgFQAOgIAHgLQAHgMAAgPQAAgHgCgEIgFgGIgHgCIgHgBQgUAAgQAXg");
	this.shape_32.setTransform(192.7,25.7);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("Ag4BIQgQgRAAgfQAAgWAGgTQAHgTANgQQANgQASgKQARgKAXAAQAYAAAMAKQAMAKAAAQQAAASgLANQgMANgVAIQgQAEgQAEIgjAGQAAAbAKAOQAKAPASAAQARAAANgJQANgJANgQIAJAHQgNAVgVAMQgUANgVAAQgeAAgQgRgAgPg1QgSAWgEAhIAbgEQAOgDAKgFQAOgIAHgLQAHgMAAgPQAAgHgCgEIgFgGIgHgCIgHgBQgUAAgQAXg");
	this.shape_33.setTransform(176.2,25.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAbBQQgHgHAAgKIABgIIACgLIARg/IADgNIABgKQAAgLgFgHQgGgHgLAAQgKAAgMAHQgNAHgLANIgdB9IggAAIAahuIACgMIABgNQAAgJgDgDQgDgEgJAAIgLACIgJACIADgLIAYgJQAKgDAHAAQAOAAAGAHQAFAIABANIABAAQATgPANgIQANgHARAAQARAAAJAKQAJAJAAAPIgBALIgDAQIgOA2IgDAMIgBAMQAAAJADAEQAFADAKAAIAJgBIAKgCIgDALIgYAJQgJADgIAAQgOAAgHgIg");
	this.shape_34.setTransform(157.6,25.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AhKBHQgOgSAAgfQAAgVAIgTQAIgUANgQQAOgPASgJQASgKASAAQAMAAALADQALAEAGAEIAggIIACACIgaBuIgDAMIgCAMQABAKAEADQAEADAJAAIAKgBIAJgCIgDALIgWAJQgIADgLAAQgMAAgIgIQgGgHgBgLIgCAAIgJAIIgLAJIgOAHQgIAEgJAAQgZAAgOgSgAgMhEQgLAJgJAOQgKANgFASQgGASAAATIACASQABAIADAHQADAGAGAEQAHADAJAAQAJAAALgFQAKgFANgOIAVhbIgBgLQgBgFgEgEQgDgFgGgCQgGgDgJAAQgMAAgMAIg");
	this.shape_35.setTransform(128.8,25.7);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AhSB1QgOgSAAgfQAAgVAHgVQAIgUANgOQANgPASgJQASgKATAAQALAAAMADQAMADAHAFIANg6IACgIIAAgFQAAgGgCgEQgDgDgEgBIgLgCIgNgCIACgKIBFgEIACADIgvDMIgDANIgCALQAAAJAFAEQAEADAJAAIAKgBIAJgCIgDALIgYAJQgJADgIAAQgMAAgIgHQgHgGAAgOIgBAAIgKAJIgLAJIgPAIQgHADgKAAQgZAAgOgSgAgWgWQgLAJgJANQgJANgFASQgFATAAASIABATQABAIAEAHQADAGAGAEQAGADAKAAQAJAAALgFQAKgGAOgOIAWhcIgDgJIgGgJQgEgEgGgDQgGgDgJAAQgMAAgMAIg");
	this.shape_36.setTransform(109.5,21.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AhKBHQgOgSAAgfQAAgVAIgTQAHgUAOgQQANgPATgJQASgKASAAQAMAAALADQALAEAHAEIAfgIIACACIgaBuIgDAMIgBAMQAAAKADADQAFADAKAAIAJgBIAJgCIgCALIgYAJQgHADgLAAQgMAAgHgIQgIgHAAgLIgBAAIgJAIIgLAJIgPAHQgIAEgJAAQgZAAgOgSgAgLhEQgMAJgKAOQgIANgGASQgGASAAATIABASQABAIAEAHQADAGAHAEQAFADAKAAQAJAAALgFQAJgFANgOIAXhbIgCgLQgBgFgEgEQgDgFgGgCQgGgDgJAAQgMAAgLAIg");
	this.shape_37.setTransform(88.7,25.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAbBQQgHgHAAgKIABgIIACgLIARg/IADgNIABgKQAAgLgFgHQgGgHgLAAQgKAAgMAHQgNAHgLANIgdB9IggAAIAahuIACgMIABgNQAAgJgDgDQgDgEgJAAIgLACIgJACIADgLIAYgJQAKgDAHAAQAOAAAGAHQAFAIABANIABAAQATgPANgIQANgHARAAQARAAAJAKQAJAJAAAPIgBALIgDAQIgOA2IgDAMIgBAMQAAAJADAEQAFADAKAAIAJgBIAKgCIgDALIgYAJQgJADgIAAQgOAAgHgIg");
	this.shape_38.setTransform(68.5,25.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AhKBHQgOgSAAgfQAAgVAIgTQAHgUAOgQQANgPATgJQASgKASAAQAMAAALADQALAEAGAEIAggIIACACIgaBuIgDAMIgBAMQAAAKADADQAFADAKAAIAJgBIAJgCIgCALIgXAJQgIADgLAAQgMAAgHgIQgIgHAAgLIgBAAIgJAIIgMAJIgOAHQgIAEgJAAQgZAAgOgSgAgLhEQgMAJgKAOQgIANgGASQgGASAAATIABASQACAIADAHQADAGAHAEQAFADAKAAQAKAAAKgFQAJgFANgOIAXhbIgCgLQgBgFgEgEQgDgFgGgCQgGgDgJAAQgMAAgLAIg");
	this.shape_39.setTransform(48.1,25.7);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("Ag5B5QgQgHgMgMQgNgNgHgSQgIgSABgXQAAgfALgcQALgcASgWQATgVAagNQAagNAbAAQAVAAAQAFQARAFAKAHIAJgLIAPAAIgTBWIgOAAIAAgHQAAgOgCgMQgDgNgGgLQgGgJgLgGQgLgGgQAAQgVAAgRALQgSALgNATQgNASgIAbQgIAaAAAbQAAAkASAXQASAWAeAAQAYAAAVgOQAVgPANgZIANAGQgVAlgbAPQgbAPggAAQgTAAgRgGg");
	this.shape_40.setTransform(28.6,22);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAHAoQgHgHABgKQgBgOAHgKQAGgMAIgIQAKgJAJgGIARgJIAGALIgQAIIgLAIIgKALQgEAFgDAIIAIAAQAKAAAGAGQAEAFAAAGQAAAJgHAHQgFAHgMAAQgLAAgFgGgAg4AoQgFgHAAgKQgBgOAHgKQAGgMAIgIQAKgJAJgGIARgJIAFALIgPAIIgLAIIgKALQgEAFgDAIIAIAAQALAAAEAGQAFAFAAAGQAAAJgHAHQgGAHgLAAQgMAAgFgGg");
	this.shape_41.setTransform(11.6,12.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(0,0,741.8,43.8), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("EhLxgTmMCXjAAAMAAAAnNMiXjAAAg");
	this.shape.setTransform(485,125.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("EhLxATnMAAAgnNMCXjAAAMAAAAnNg");
	this.shape_1.setTransform(485,125.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(-1,-1,972,253), null);


// stage content:
(lib._728x90_listen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// logo
	this.instance = new lib.Symbol6();
	this.instance.parent = this;
	this.instance.setTransform(513,45.4,0.525,0.525,0,0,0,196.7,78.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(316).to({_off:false},0).to({alpha:1},20,cjs.Ease.get(-1)).wait(19));

	// Layer_7
	this.instance_1 = new lib.Symbol5();
	this.instance_1.parent = this;
	this.instance_1.setTransform(231.9,56.1,0.751,0.751,0,0,0,206.3,36.6);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(316).to({_off:false},0).to({alpha:1},20,cjs.Ease.get(-1)).wait(19));

	// Layer_6
	this.instance_2 = new lib.Symbol4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(443.2,59.4,0.751,0.751,0,0,0,105.5,19.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(202).to({_off:false},0).to({alpha:1},19,cjs.Ease.get(-1)).wait(79).to({alpha:0},16).wait(39));

	// Layer_5
	this.instance_3 = new lib.Symbol3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(364.1,43,0.751,0.751,0,0,0,105.5,19.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(123).to({_off:false},0).wait(1).to({regX:104.5,regY:23.2,x:363.3,y:46,alpha:0.002},0).wait(1).to({alpha:0.01},0).wait(1).to({alpha:0.025},0).wait(1).to({alpha:0.047},0).wait(1).to({alpha:0.077},0).wait(1).to({alpha:0.118},0).wait(1).to({alpha:0.171},0).wait(1).to({alpha:0.236},0).wait(1).to({alpha:0.311},0).wait(1).to({alpha:0.395},0).wait(1).to({alpha:0.482},0).wait(1).to({alpha:0.566},0).wait(1).to({alpha:0.643},0).wait(1).to({alpha:0.711},0).wait(1).to({alpha:0.77},0).wait(1).to({alpha:0.819},0).wait(1).to({alpha:0.861},0).wait(1).to({alpha:0.895},0).wait(1).to({alpha:0.923},0).wait(1).to({alpha:0.946},0).wait(1).to({alpha:0.964},0).wait(1).to({alpha:0.978},0).wait(1).to({alpha:0.988},0).wait(1).to({alpha:0.995},0).wait(1).to({alpha:0.999},0).wait(1).to({regX:105.5,regY:19.1,x:364.1,y:43,alpha:1},0).wait(39).to({alpha:0},14).wait(153));

	// Layer_2
	this.instance_4 = new lib.Symbol2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(364,59.9,0.751,0.751,0,0,0,370.9,21.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(4).to({_off:false},0).wait(1).to({regX:373.5,regY:24.7,x:365.9,y:61.6,alpha:0.026},0).wait(1).to({y:61.1,alpha:0.057},0).wait(1).to({y:60.5,alpha:0.094},0).wait(1).to({y:59.9,alpha:0.138},0).wait(1).to({y:59,alpha:0.194},0).wait(1).to({y:58,alpha:0.264},0).wait(1).to({y:56.7,alpha:0.35},0).wait(1).to({y:55.2,alpha:0.447},0).wait(1).to({y:53.9,alpha:0.536},0).wait(1).to({y:52.8,alpha:0.609},0).wait(1).to({y:51.9,alpha:0.667},0).wait(1).to({y:51.2,alpha:0.713},0).wait(1).to({y:50.7,alpha:0.751},0).wait(1).to({y:50.2,alpha:0.783},0).wait(1).to({y:49.8,alpha:0.81},0).wait(1).to({y:49.4,alpha:0.834},0).wait(1).to({y:49.1,alpha:0.854},0).wait(1).to({y:48.9,alpha:0.872},0).wait(1).to({y:48.6,alpha:0.887},0).wait(1).to({y:48.4,alpha:0.901},0).wait(1).to({y:48.2,alpha:0.914},0).wait(1).to({y:48.1,alpha:0.925},0).wait(1).to({y:47.9,alpha:0.935},0).wait(1).to({y:47.8,alpha:0.944},0).wait(1).to({y:47.7,alpha:0.952},0).wait(1).to({y:47.6,alpha:0.959},0).wait(1).to({y:47.5,alpha:0.965},0).wait(1).to({y:47.4,alpha:0.971},0).wait(1).to({y:47.3,alpha:0.976},0).wait(1).to({alpha:0.98},0).wait(1).to({y:47.2,alpha:0.984},0).wait(1).to({y:47.1,alpha:0.987},0).wait(1).to({alpha:0.99},0).wait(1).to({alpha:0.993},0).wait(1).to({y:47,alpha:0.995},0).wait(1).to({alpha:0.996},0).wait(1).to({alpha:0.998},0).wait(1).to({alpha:0.999},0).wait(2).to({alpha:1},0).wait(1).to({regX:370.9,regY:21.9,x:364,y:44.9},0).to({_off:true},92).wait(218));

	// bg
	this.instance_5 = new lib.white();
	this.instance_5.parent = this;
	this.instance_5.setTransform(364.7,46.6,0.751,0.751,0,0,0,496.9,134);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(102).to({_off:false},0).to({alpha:1},35,cjs.Ease.get(1)).wait(218));

	// Layer_3
	this.instance_6 = new lib.Symbol1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(364,44.7,0.751,0.751,0,0,0,485,125.5);
	this.instance_6.alpha = 0.398;

	this.instance_7 = new lib._970x250_solar_bg();
	this.instance_7.parent = this;
	this.instance_7.setTransform(0,-50,0.751,0.751);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_7},{t:this.instance_6}]}).wait(355));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(363.6,-5,728.8,194.4);
// library properties:
lib.properties = {
	id: '71A1C08147E540F29518D65B56296E84',
	width: 728,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/_970x250_solar_bg.jpg", id:"_970x250_solar_bg"},
		{src:"images/CEPA_Horizontal_Logo_RGBK.png", id:"CEPA_Horizontal_Logo_RGBK"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['71A1C08147E540F29518D65B56296E84'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;