(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"728x90_snow_atlas_", frames: [[0,320,318,67],[0,0,397,318]]}
];


// symbols:



(lib.docBC = function() {
	this.spriteSheet = ss["728x90_snow_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.volcanoman = function() {
	this.spriteSheet = ss["728x90_snow_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.docBC();
	this.instance.parent = this;
	this.instance.setTransform(-159,-33);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-159,-33,318,67);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.docBC();
	this.instance.parent = this;
	this.instance.setTransform(-159,-33);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-159,-33,318,67);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAQIgFgFIgEgFIgCgGIACgGIAEgFIAFgEIAGAAIAGAAIAFAEIAEAFIABAGIgBAGIgEAFIgFAFIgGABg");
	this.shape.setTransform(438.6,25.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgFgGQgEgFgCgHQgCgJgBgMIABhIIgVAAIAAgTIAVAAIAAgfIAWgLIAAAqIAfAAIAAATIgfAAIAABLQgBAIACAEQACAGAEABQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHABgJAAQgIAAgGgCg");
	this.shape_1.setTransform(431,18.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgZAgIAYhHIAbALIggBDg");
	this.shape_2.setTransform(422.2,11.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QAAgPgIgHQgHgJgPAAQgHAAgIAEQgJAFgHAFIAABMIASAAIAAAWIg9AAIAAgWIATAAIAAhXIgTAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQAKAAAJADQAIADAHAGQAFAGAEAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_3.setTransform(409.8,20.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXBBQgJgFgGgIIgNAAIAAgWIAaAAQAAAFADAEQACAEAEACQAEADAEABIAJABIAKgBIAIgEQAEgCACgDQABgEAAgEQAAgGgDgFQgFgEgKgEIgYgJQgPgEgHgJQgIgIAAgNQAAgIADgHQAEgIAFgFQAGgFAJgDQAIgDALAAQANAAAKAEQAJAEAIAKIAMAAIAAAWIgaAAQAAgGgCgDQgDgEgEgDIgJgDIgIgBIgJABIgIADQgCACgCAEQgCADAAADQAAAHAEAEQAEAEAJADIAYAJQARAFAIAJQAHAJAAANQAAAJgEAHQgDAIgHAFQgGAFgJADQgJADgLAAQgOAAgKgFg");
	this.shape_4.setTransform(394.8,20.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgFhAIgGgEIgDgFIgCgHIACgGIADgFIAGgEIAFgBIAGABIAGAEIADAFIABAGIgBAHIgDAFIgGAEIgGABg");
	this.shape_5.setTransform(384.6,17.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AA4BDIAAgWIATAAIAAg7QAAgPgIgHQgHgJgPAAQgJAAgJAEQgIAFgGAGIAABLIASAAIAAAWIg8AAIAAgWIASAAIAAg7QAAgPgIgHQgIgJgOAAQgIAAgIAEQgJAFgIAFIAABMIATAAIAAAWIg+AAIAAgWIATAAIAAhXIgTAAIAAgVIArAAIAAAPIAAAAIAJgHIAKgGIALgDIAMgCQAOAAAKAFQAKAGAFALIAKgJIALgHIAMgEQAHgCAGAAQALAAAIADQAJADAGAGQAGAGADAJQAEAKgBAMIAAA+IASAAIAAAWg");
	this.shape_6.setTransform(361.6,20.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AghBCQgIgDgFgFQgGgGgDgGQgDgHAAgJQAAgHACgHQADgGAEgGQAEgEAFgDIAMgEIAMgEIAMAAIAOAAIAMACIAAgLQAAgHgDgFQgCgFgDgEQgEgDgEgBQgGgCgGAAIgLABIgKACIgJADIgHADIgHgQIAKgGIAMgEIAMgDIANgBQAKAAAJADQAKACAGAGQAHAGADAJQAEAJgBAMIAABBIAPAAIAAAVIgmAAIAAgLQgIAHgJAEQgIAEgMAAQgJAAgJgDgAgRAHQgGACgEADQgEACgDAFQgCAEAAAGQAAAFACAEQACADAEADQADACAFACIAKABIAKgBIAIgDIAIgFIAGgFIAAgeIgbAAQgGAAgGACg");
	this.shape_7.setTransform(341.3,20.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AATBCIAAgWIAHAAIgaghIgYAhIAGAAIAAAWIgsAAIAAgWIALAAIAoguIglgpIgOAAIAAgWIAsAAIAAAWIgFAAIAXAfIAZgfIgHAAIAAgWIAsAAIAAAWIgLAAIglArIAnAsIAKAAIAAAWg");
	this.shape_8.setTransform(327.5,20.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIhdAAIABAKIACAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgNAAgLgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgEAFQgEAEgEAGQgCAHgBAIIBDAAg");
	this.shape_9.setTransform(312.8,20.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgEgGQgFgFgCgHQgCgJAAgMIAAhIIgVAAIAAgTIAVAAIAAgfIAWgLIAAAqIAfAAIAAATIgfAAIgBBLQAAAIACAEQACAGAEABQAEACAFAAIAJgBIAJgDIAGAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_10.setTransform(295.3,18.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgXBBQgJgFgGgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQADADAGABIAJABIAJgBIAIgEQADgCACgDQACgEABgEQgBgGgEgFQgEgEgJgEIgYgJQgQgEgIgJQgHgIAAgNQAAgIAEgHQACgIAHgFQAFgFAIgDQAJgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgDgDQgCgEgEgDIgIgDIgJgBIgJABIgHADQgEACgCAEQgBADAAADQAAAHAEAEQAEAEAKADIAYAJQAQAFAHAJQAIAJAAANQAAAJgDAHQgEAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_11.setTransform(284.1,20.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgGhAIgFgEIgDgFIgBgHIABgGIADgFIAFgEIAGgBIAGABIAFAEIAEAFIACAGIgCAHIgEAFIgFAEIgGABg");
	this.shape_12.setTransform(273.8,17.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgvBCIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAAASIAFgIIAGgGIAIgEQAEgBAFAAIANAAIAMAAIAAAdIgZAAIAAgJQgEAAgFACQgEACgEADQgEADgCAFQgCAFgCAHIAAA+IAWAAIAAAWg");
	this.shape_13.setTransform(263.4,20.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgFgGQgEgFgDgHQgCgJAAgMIABhIIgVAAIAAgTIAVAAIAAgfIAXgLIAAAqIAeAAIAAATIgfAAIAABLQAAAIABAEQACAGAEABQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_14.setTransform(252.6,18.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIhdAAIABAKIACAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgNAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgEAFQgEAEgEAGQgCAHgBAIIBDAAg");
	this.shape_15.setTransform(239.9,20.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AA4BDIAAgWIASAAIAAg7QAAgPgHgHQgIgJgOAAQgJAAgIAEQgJAFgHAGIAABLIASAAIAAAWIg8AAIAAgWIATAAIAAg7QAAgPgIgHQgIgJgOAAQgIAAgJAEQgIAFgIAFIAABMIATAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIApAAIAAAPIABAAIAJgHIAKgGIALgDIALgCQAOAAALAFQAKAGAFALIAKgJIALgHIAMgEQAGgCAIAAQAKAAAJADQAIADAGAGQAGAGADAJQADAKABAMIAAA+IASAAIAAAWg");
	this.shape_16.setTransform(219.8,20.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_17.setTransform(198.9,20.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgEgGQgFgFgCgHQgCgJAAgMIAAhIIgVAAIAAgTIAVAAIAAgfIAWgLIAAAqIAfAAIAAATIgfAAIgBBLQAAAIADAEQABAGAEABQAEACAFAAIAJgBIAJgDIAGAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_18.setTransform(186.5,18.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhFBhIAAgWIATAAIAAiSIgTAAIAAgWIAqAAIAAALQAJgHAJgEQAJgDALAAQANAAALAEQAKAFAIAJQAIAJAEAMQAFAMAAAPQAAAQgFANQgFAMgJAJQgIAKgMAFQgMAFgOAAQgJAAgIgCIgPgFIAAAqIAVAAIAAAWgAgMhIQgIAEgHAGIAABGQAFAFAHADQAIAEALAAQAIAAAHgEQAIgDAGgGQAFgGAEgJQADgJAAgMQAAgLgDgJQgDgIgGgGQgFgGgIgDQgHgEgIAAQgJAAgIAEg");
	this.shape_19.setTransform(173.5,23.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_20.setTransform(157.9,20.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AANBDIAAgWIATAAIAAg7QAAgPgJgHQgHgJgOAAQgIAAgIAEQgIAFgIAFIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQALAAAIADQAJADAFAGQAHAGADAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_21.setTransform(135.9,20.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AghBCQgIgDgGgFQgFgGgEgGQgDgHAAgJQABgHACgHQADgGADgGQAEgEAGgDIALgEIANgEIAMAAIAPAAIAKACIABgLQAAgHgCgFQgCgFgEgEQgDgDgGgBQgFgCgGAAIgKABIgLACIgIADIgHADIgIgQIAKgGIAMgEIANgDIAMgBQALAAAJADQAIACAHAGQAGAGAEAJQADAJABAMIgBBBIAOAAIAAAVIgmAAIAAgLQgHAHgJAEQgIAEgMAAQgJAAgJgDgAgRAHQgGACgEADQgEACgCAFQgDAEAAAGQAAAFACAEQACADADADQAEACAFACIALABIAJgBIAIgDIAHgFIAGgFIAAgeIgaAAQgGAAgGACg");
	this.shape_22.setTransform(119.9,20.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgOBfIgOgDIgPgGQgGgDgGgFIAMgTIAJAGIAKAFIAMADIAMABQAJAAAHgCQAHgCAFgFQAFgFACgJQACgJAAgNIAAgCQgGAHgJADQgJAEgLAAQgMAAgMgEQgLgFgJgJQgIgJgEgNQgGgMAAgRQAAgPAGgMQAEgNAIgJQAJgJALgEQAMgFANAAQALAAAHACQAJACAHAFIAAgGIAYAAIAAB9QAAAfgPAQQgPAQgfAAgAgKhHQgHADgGAGQgFAGgEAIQgDAJAAALQAAAMADAJQAEAJAEAGQAGAGAIADQAIAEAIAAIAKgCIAJgCIAHgFIAFgFIAAhHQgGgGgJgCQgJgDgJAAQgGAAgIAEg");
	this.shape_23.setTransform(99.4,23.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QAAgPgIgHQgHgJgPAAQgHAAgIAEQgJAFgHAFIAABMIASAAIAAAWIg9AAIAAgWIATAAIAAhXIgTAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQAKAAAJADQAIADAHAGQAFAGAEAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_24.setTransform(83.6,20.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgFhAIgGgEIgDgFIgCgHIACgGIADgFIAGgEIAFgBIAGABIAGAEIADAFIABAGIgBAHIgDAFIgGAEIgGABg");
	this.shape_25.setTransform(70.9,17.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAtBjIg1g7IgRAAIAAAlIAKAAIAAAWIg4AAIAAgWIAWAAIAAiZIgXAAIAAgWIAvAAIAAAWIAABhIAWAAIAfgfIgIAAIAAgWIAyAAIAAAWIgRAAIgoAoIAsAvIAQAAIAAAWg");
	this.shape_26.setTransform(58.7,17.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_27.setTransform(42.4,20.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_28.setTransform(26.9,20.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhHBgIAAgWIASAAIAAiTIgSAAIAAgWIBWAAQAMAAAJAEQALAFAHAHQAIAIAFAKQAEAKAAAMQAAAMgHALQgHAKgNAGIAMAGQAFAFADAFQAEAFACAGQACAGAAAGQAAAMgEAKQgFALgIAIQgHAHgKAFQgLAEgLAAgAgcBKIAsAAQAGAAAFgDQAGgDADgFQAEgEADgHQACgGAAgGQAAgGgCgFQgCgFgFgEQgDgEgGgDQgFgCgGAAIgsAAgAgcgKIArAAQAGAAAFgDQAGgCADgEQAFgEACgGQACgFAAgGQAAgGgCgGQgCgGgFgFQgDgEgGgDQgFgDgGAAIgrAAg");
	this.shape_29.setTransform(11.1,17.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(0,0,443.6,35.4), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAQIgGgFIgDgFIgBgGIABgGIADgFIAGgEIAFAAIAGAAIAGAEIADAFIABAGIgBAGIgDAFIgGAFIgGABg");
	this.shape.setTransform(330.2,25.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgfBgQgLgFgJgJQgIgJgFgNQgFgNAAgRQAAgPAFgMQAFgMAIgJQAIgJAMgEQAMgFAOAAQAJAAAIACQAIACAHAFIAAgyIgSAAIAAgWIAqAAIAACuIATAAIAAAWIgrAAIAAgLQgGAHgJAEQgIADgKAAQgNAAgMgEgAgTgMQgIADgFAGQgGAFgDAIQgDAJAAALQAAAMADAJQADAKAFAGQAGAGAIADQAHAEAJAAQAKAAAHgDQAHgEAGgGIAAhIQgGgGgJgCQgIgDgIAAQgIAAgHAEg");
	this.shape_1.setTransform(319.4,17.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AguBCIAAgWIASAAIAAhWIgSAAIAAgWIApAAIAAASIAFgIIAHgGIAHgEQAEgBAFAAIAMAAIAMAAIAAAdIgYAAIAAgJQgEAAgEACQgFACgDADQgFADgCAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape_2.setTransform(305.2,20.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AghBCQgIgDgGgFQgFgGgEgGQgDgHAAgJQABgHACgHQADgGADgGQAEgEAGgDIALgEIANgEIAMAAIAPAAIAKACIABgLQAAgHgCgFQgCgFgEgEQgDgDgGgBQgFgCgGAAIgKABIgLACIgIADIgHADIgIgQIAKgGIAMgEIANgDIAMgBQALAAAJADQAIACAHAGQAHAGADAJQADAJABAMIgBBBIAOAAIAAAVIgmAAIAAgLQgHAHgJAEQgIAEgMAAQgJAAgJgDgAgRAHQgGACgEADQgEACgCAFQgDAEAAAGQAAAFACAEQACADADADQAEACAFACIALABIAJgBIAIgDIAHgFIAGgFIAAgeIgaAAQgGAAgGACg");
	this.shape_3.setTransform(291.8,20.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AANBjIAAgWIASAAIAAg8QAAgPgIgHQgIgIgOAAQgIAAgHAEQgJAEgHAFIAABNIATAAIAAAWIg/AAIAAgWIAUAAIAAiZIgSAAIAAgWIAqAAIAABRIABAAIAIgHIAKgFIAKgEIAKgBQALAAAIADQAJADAGAGQAFAGAEAJQADAIAAANIAAA/IAUAAIAAAWg");
	this.shape_4.setTransform(276.6,17.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXBBQgKgFgFgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQAEADAFABIAJABIAJgBIAIgEQAEgCABgDQADgEAAgEQgBgGgEgFQgEgEgJgEIgYgJQgQgEgIgJQgHgIAAgNQAAgIAEgHQACgIAHgFQAFgFAIgDQAJgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgDgDQgCgEgEgDIgIgDIgJgBIgJABIgHADQgDACgDAEQgBADAAADQAAAHAEAEQAEAEAJADIAZAJQAQAFAHAJQAIAJAAANQAAAJgDAHQgEAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_5.setTransform(255.8,20.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgGhAIgFgEIgEgFIgBgHIABgGIAEgFIAFgEIAGgBIAHABIAEAEIAEAFIACAGIgCAHIgEAFIgEAEIgHABg");
	this.shape_6.setTransform(245.6,17.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNBfIgQgDIgNgGQgHgDgHgFIAOgTIAIAGIALAFIALADIAMABQAIAAAIgCQAHgCAFgFQAEgFACgJQADgJAAgNIAAgCQgGAHgJADQgJAEgKAAQgNAAgLgEQgMgFgIgJQgJgJgFgNQgEgMAAgRQAAgPAEgMQAFgNAIgJQAJgJAMgEQALgFAOAAQAKAAAIACQAHACAIAFIAAgGIAXAAIAAB9QAAAfgOAQQgPAQgfAAgAgKhHQgHADgGAGQgFAGgDAIQgEAJAAALQAAAMADAJQADAJAGAGQAFAGAIADQAHAEAIAAIALgCIAJgCIAHgFIAFgFIAAhHQgGgGgJgCQgIgDgJAAQgIAAgHAEg");
	this.shape_7.setTransform(227.6,23.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AANBDIAAgWIATAAIAAg7QgBgPgHgHQgIgJgPAAQgGAAgJAEQgJAFgHAFIAABMIATAAIAAAWIg+AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIABAAIAJgHIAKgGIAKgDIALgCQAKAAAJADQAJADAFAGQAGAGAEAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_8.setTransform(211.8,20.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIArAAIAABsIATAAIAAAWgAgGhAIgFgEIgDgFIgBgHIABgGIADgFIAFgEIAGgBIAGABIAGAEIADAFIACAGIgCAHIgDAFIgGAEIgGABg");
	this.shape_9.setTransform(199.1,17.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgFgGQgEgFgDgHQgCgJAAgMIABhIIgVAAIAAgTIAVAAIAAgfIAXgLIAAAqIAeAAIAAATIgfAAIAABLQAAAIABAEQACAGAEABQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_10.setTransform(190,18.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QABgPgJgHQgHgJgOAAQgIAAgIAEQgJAFgHAFIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQALAAAIADQAJADAFAGQAHAGADAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_11.setTransform(176.5,20.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_12.setTransform(160,20.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgvBCIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAAASIAFgIIAGgGIAIgEQAEgBAFAAIANAAIAMAAIAAAdIgZAAIAAgJQgEAAgFACQgEACgEADQgEADgCAFQgCAFgCAHIAAA+IAWAAIAAAWg");
	this.shape_13.setTransform(146.8,20.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AggBCQgJgDgGgFQgFgGgDgGQgDgHAAgJQAAgHACgHQADgGAEgGQAEgEAFgDIAMgEIAMgEIAMAAIAOAAIAMACIAAgLQAAgHgDgFQgBgFgEgEQgEgDgEgBQgGgCgFAAIgMABIgKACIgJADIgHADIgHgQIAKgGIAMgEIAMgDIANgBQAKAAAJADQAKACAGAGQAHAGADAJQAEAJgBAMIAABBIAPAAIAAAVIgmAAIAAgLQgIAHgJAEQgIAEgLAAQgLAAgHgDgAgRAHQgGACgEADQgEACgDAFQgCAEAAAGQAAAFACAEQACADAEADQADACAFACIAKABIAKgBIAIgDIAIgFIAGgFIAAgeIgbAAQgGAAgGACg");
	this.shape_14.setTransform(133.5,20.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhEBgIAAgWIATAAIAAiTIgTAAIAAgWIBNAAQANAAALADQALAEAIAGQAIAHAEAJQAFAKAAANQAAAKgFAKQgEAJgIAHQgIAHgLADQgLAEgNAAIghAAIAABDIATAAIAAAWgAgYgNIAhAAQAHAAAHgCQAGgCAEgDQAEgEADgGQACgGAAgHQAAgOgIgIQgJgIgTAAIgeAAg");
	this.shape_15.setTransform(119.2,17.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(108.4,0,226.8,35.4), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.volcanoman();
	this.instance.parent = this;
	this.instance.setTransform(-321,-106,2.1,2.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-321,-106,833.7,667.8), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgUA5QgJgEgEgHIgMAAIAAgUIAXAAQAAAFACAEQACADAEACIAIADIAHABIAJgBIAHgDIAFgFQACgDAAgDQAAgGgEgEQgEgEgIgDIgWgIQgNgEgHgIQgGgHAAgLQAAgIACgGQADgGAFgFQAGgEAHgDQAIgDAJAAQAMAAAIAEQAJADAGAJIALAAIAAATIgXAAQAAgFgCgDQgCgDgEgCIgHgDIgIgBIgIABIgGADIgFAEIgBAGQAAAGADAEQAEADAIADIAWAIQAOAFAHAHQAGAIAAAMQAAAIgDAGQgDAHgGAEQgFAFgIACQgIADgKAAQgNAAgIgFg");
	this.shape.setTransform(304.8,32.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBBMQgFgBgEgFQgEgEgCgIQgCgHAAgLIABg/IgTAAIAAgRIATAAIAAgcIATgKIAAAmIAbAAIAAARIgbAAIAABDQAAAGABAFQACAEADACQAEABAEAAIAIgBIAIgDIAFAOIgLAEQgGADgIAAQgIAAgFgDg");
	this.shape_1.setTransform(295,30.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXA5QgKgEgIgJQgHgIgFgLQgEgLAAgOQAAgNAEgLQAFgLAHgJQAIgIALgFQALgDALAAQANAAALADQALAFAHAIQAIAIAEAMQAEALAAANQAAANgEALQgEAMgIAIQgHAIgLAFQgLAFgNgBQgMABgLgFgAgNgoQgGADgFAGQgFAFgDAIQgDAIAAAKQAAAKADAIQADAIAFAGQAFAFAGAEQAHACAGAAQAIAAAHgCQAGgDAFgGQAFgGADgIQADgIAAgKQAAgKgDgIQgDgIgFgFQgEgGgHgDQgHgCgIAAQgGAAgHACg");
	this.shape_2.setTransform(283.7,32.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXA5QgKgEgIgJQgHgIgFgLQgEgLAAgOQAAgNAEgLQAFgLAHgJQAIgIALgFQALgDALAAQANAAALADQALAFAHAIQAIAIAEAMQAEALAAANQAAANgEALQgEAMgIAIQgHAIgLAFQgLAFgNgBQgMABgLgFgAgNgoQgGADgFAGQgFAFgDAIQgDAIAAAKQAAAKADAIQADAIAFAGQAFAFAGAEQAHACAGAAQAIAAAHgCQAGgDAFgGQAFgGADgIQADgIAAgKQAAgKgDgIQgDgIgFgFQgEgGgHgDQgHgCgIAAQgGAAgHACg");
	this.shape_3.setTransform(270,32.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgKBWQgIgDgGgEIAAAHIgUAAIAAiaIgRAAIAAgTIAlAAIAABEQAIgGAJgEQAHgDAKAAQALAAAKAEQAKAFAGAHQAHAIAEAKQAEALAAANQAAAOgFALQgEAMgHAIQgIAIgKAFQgLAEgMAAQgIAAgHgCgAgKgKQgIADgGAGIAAA+QAEADAHADQAHADAJAAQAIAAAHgDQAGgCAFgGQAFgFADgIQADgIAAgLQAAgKgDgIQgDgHgEgFQgFgFgGgDQgHgCgIAAQgHAAgHADg");
	this.shape_4.setTransform(256,29.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAyA7IAAgTIAQAAIAAg0QAAgOgGgGQgIgHgMAAQgIAAgHADQgJAEgFAFIAABDIAQAAIAAATIg1AAIAAgTIAQAAIAAg0QAAgOgHgGQgGgHgNAAQgIAAgHADIgOAJIAABDIARAAIAAATIg3AAIAAgTIAQAAIAAhNIgQAAIAAgTIAmAAIAAANIAIgGIAJgFIAJgDIALgBQAMAAAJAEQAIAFAFAKIAJgHIAKgHIAKgEQAGgBAGAAQAJAAAIACQAIADAFAFQAGAFACAJQADAIAAALIAAA3IAQAAIAAATg");
	this.shape_5.setTransform(237.7,32.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgXA5QgHgDgFgFQgFgFgDgJQgDgIAAgLIAAg3IgPAAIAAgTIAlAAIAABHQAAAOAHAHQAFAGAMAAQAGAAAHgCQAIgDAHgEIAAhGIgQAAIAAgTIAmAAIAABgIANAAIAAATIgiAAIAAgLQgIAHgJADQgKADgJAAQgJAAgHgCg");
	this.shape_6.setTransform(217.9,32.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgMBUIgNgDIgNgFQgGgDgFgEIALgRIAIAFIAJAFIAKACIALABQAIAAAGgBQAGgCAFgFQAEgEACgIQACgIAAgMIAAgBQgGAGgIADQgHADgKAAQgLAAgKgEQgKgEgHgIQgIgIgEgLQgEgLAAgPQAAgNAEgLQAEgLAHgIQAHgIALgEQAKgEAMAAQAJAAAHACQAHACAHAEIAAgGIAUAAIAABvQAAAcgNAOQgNAOgbAAgAgJg/QgGADgFAFQgFAFgDAIQgDAHAAAKQAAALADAIQADAHAEAGQAFAGAHACQAHADAHAAIAJgBIAIgCIAGgEIAFgFIAAg+QgGgFgIgDQgHgCgIAAQgGAAgHADg");
	this.shape_7.setTransform(203.9,34.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgWAdIAVg/IAYAKIgcA7g");
	this.shape_8.setTransform(188.7,38.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgBBMQgFgBgEgFQgEgEgCgIQgCgHAAgLIABg/IgTAAIAAgRIATAAIAAgcIATgKIAAAmIAbAAIAAARIgbAAIAABDQAAAGABAFQACAEADACQAEABAEAAIAIgBIAIgDIAFAOIgLAEQgGADgIAAQgIAAgFgDg");
	this.shape_9.setTransform(181.9,30.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgTA6QgKgFgHgIQgHgHgEgMQgEgLAAgPQAAgMADgLQAEgLAHgIQAGgJALgFQAKgEAMAAQAOAAAIADQAJAEAGAHQAFAHADAIQADAIABAKIABAIIAAAIIhTAAIABAJIACAIQAEAKAJAGQAKAGAKAAQAJAAAJgCQAIgDAKgFIAIAOQgLAHgMAFQgLADgNAAQgLAAgKgDgAAegNIgCgMQgCgFgDgFQgEgEgFgBQgFgDgIAAQgGAAgGADQgFACgEADQgEAEgCAFQgDAHgBAGIA8AAg");
	this.shape_10.setTransform(170.8,32.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAnBXIgug0IgQAAIAAAhIALAAIAAATIgzAAIAAgTIATAAIAAiHIgTAAIAAgTIApAAIAAATIgBAAIAABWIAVAAIAbgcIgHAAIAAgTIAsAAIAAATIgPAAIgkAkIAnApIAOAAIAAATg");
	this.shape_11.setTransform(157.6,29.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTA5QgKgFgIgIQgHgIgEgLQgEgMAAgNQAAgNAEgLQAFgLAHgIQAIgJAKgEQALgFAKAAQALAAAKAEQAJAEAIAIIAMAAIAAATIgVAAQgFgJgHgDQgHgEgKAAQgGAAgHADQgGADgFAFQgFAGgDAIQgCAIAAAJQAAAKACAHQADAIAFAGQAFAFAGADQAHADAGAAQALAAAIgFQAHgFAFgKIARAIQgCAIgGAFQgFAGgGAEQgGAEgIACQgHADgIAAQgMAAgKgFg");
	this.shape_12.setTransform(143.9,32.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgdA6QgHgCgFgFQgFgFgDgGQgDgGAAgHQAAgHACgGQACgGAEgEQAEgEAFgCIAKgFIALgCIAKgBIANABIAKABIAAgKQAAgGgCgEQgBgFgEgDQgDgDgFgBQgEgCgFAAIgKABIgJACIgIADIgGADIgGgPIAJgFIAKgEIALgCIALgBQAJAAAIACQAJADAFAFQAGAFADAIQADAHAAALIAAA5IANAAIAAAUIgiAAIAAgLQgHAGgIAEQgHAEgKAAQgJAAgHgDgAgPAGQgFABgEADQgEACgCAEQgCAEAAAFQAAAFACADQACAEADACQADACAEABIAKABIAIgBIAHgCIAHgEIAFgFIAAgaIgXAAIgLABg");
	this.shape_13.setTransform(131.1,32.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgUBgQAJgBAFgIQAEgIABgOIAAhmIgRAAIAAgUIAkAAIAAB9QABAKgDAIQgDAIgFAGQgEAFgGADQgHADgJABgAADhVIgDgDIgDgFIgCgFIACgFIADgEIADgDIAFgBIAGABIADADIADAEIABAFIgBAFIgDAFIgDADIgGABg");
	this.shape_14.setTransform(121.1,32.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAaA7IgahcIgZBcIgUAAIgghiIgKAAIAAgTIAlAAIAAATIgFAAIAUBJIAchcIARAAIAaBcIAVhJIgGAAIAAgTIAlAAIAAATIgKAAIggBig");
	this.shape_15.setTransform(103.8,32.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgXA5QgKgEgIgJQgHgIgFgLQgEgLAAgOQAAgNAEgLQAFgLAHgJQAIgIALgFQALgDALAAQANAAALADQALAFAHAIQAIAIAEAMQAEALAAANQAAANgEALQgEAMgIAIQgHAIgLAFQgLAFgNgBQgMABgLgFgAgNgoQgGADgFAGQgFAFgDAIQgDAIAAAKQAAAKADAIQADAIAFAGQAFAFAGAEQAHACAGAAQAIAAAHgCQAGgDAFgGQAFgGADgIQADgIAAgKQAAgKgDgIQgDgIgFgFQgEgGgHgDQgHgCgIAAQgGAAgHACg");
	this.shape_16.setTransform(87.9,32.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAMA7IAAgTIAQAAIAAg0QAAgOgHgGQgHgHgMAAQgHAAgIADIgNAJIAABDIAQAAIAAATIg3AAIAAgTIARAAIAAhNIgRAAIAAgTIAmAAIAAAOIAIgHIAIgFIAKgDIAKgBQAJAAAHACQAIADAGAFQAFAFADAJQACAIAAALIAAA3IARAAIAAATg");
	this.shape_17.setTransform(73.5,32.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgUA5QgJgEgEgHIgMAAIAAgUIAXAAQAAAFACAEQACADAEACIAIADIAHABIAJgBIAHgDIAFgFQACgDAAgDQAAgGgEgEQgEgEgIgDIgWgIQgNgEgHgIQgGgHAAgLQAAgIACgGQADgGAFgFQAGgEAHgDQAIgDAJAAQAMAAAIAEQAJADAGAJIALAAIAAATIgXAAQAAgFgCgDQgCgDgEgCIgHgDIgIgBIgIABIgGADIgFAEIgBAGQAAAGADAEQAEADAIADIAWAIQAOAFAHAHQAGAIAAAMQAAAIgDAGQgDAHgGAEQgFAFgIACQgIADgKAAQgNAAgIgFg");
	this.shape_18.setTransform(60.2,32.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgWAdIAVg/IAYAKIgcA7g");
	this.shape_19.setTransform(45.8,38.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgUA5QgJgEgEgHIgMAAIAAgUIAXAAQAAAFACAEQACADAEACIAIADIAHABIAJgBIAHgDIAFgFQACgDAAgDQAAgGgEgEQgEgEgIgDIgWgIQgNgEgHgIQgGgHAAgLQAAgIACgGQADgGAFgFQAGgEAHgDQAIgDAJAAQAMAAAIAEQAJADAGAJIALAAIAAATIgXAAQAAgFgCgDQgCgDgEgCIgHgDIgIgBIgIABIgGADIgFAEIgBAGQAAAGADAEQAEADAIADIAWAIQAOAFAHAHQAGAIAAAMQAAAIgDAGQgDAHgGAEQgFAFgIACQgIADgKAAQgNAAgIgFg");
	this.shape_20.setTransform(37.7,32.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AALA7IAAgTIARAAIAAg0QgBgOgGgGQgHgHgMAAQgHAAgIADIgNAJIAABDIAQAAIAAATIg3AAIAAgTIARAAIAAhNIgRAAIAAgTIAmAAIAAAOIAIgHIAIgFIALgDIAJgBQAJAAAIACQAHADAGAFQAFAFADAJQACAIAAALIAAA3IAQAAIAAATg");
	this.shape_21.setTransform(24.5,32.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgTA6QgKgFgHgIQgHgHgEgMQgEgLAAgPQAAgMADgLQAEgLAHgIQAGgJALgFQAKgEAMAAQAOAAAIADQAJAEAGAHQAFAHADAIQADAIABAKIABAIIAAAIIhTAAIABAJIACAIQAEAKAJAGQAKAGAKAAQAJAAAJgCQAIgDAKgFIAIAOQgLAHgMAFQgLADgNAAQgLAAgKgDgAAegNIgCgMQgCgFgDgFQgEgEgFgBQgFgDgIAAQgGAAgGADQgFACgEADQgEAEgCAFQgDAHgBAGIA8AAg");
	this.shape_22.setTransform(10,32.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgBBMQgFgBgEgFQgEgEgCgIQgCgHAAgLIABg/IgTAAIAAgRIATAAIAAgcIATgKIAAAmIAbAAIAAARIgbAAIAABDQAAAGABAFQACAEADACQAEABAEAAIAIgBIAIgDIAFAOIgLAEQgGADgIAAQgIAAgFgDg");
	this.shape_23.setTransform(-0.6,30.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgBBMQgFgBgEgFQgEgEgCgIQgCgHAAgLIABg/IgTAAIAAgRIATAAIAAgcIATgKIAAAmIAbAAIAAARIgbAAIAABDQAAAGABAFQACAEADACQAEABAEAAIAIgBIAIgDIAFAOIgLAEQgGADgIAAQgIAAgFgDg");
	this.shape_24.setTransform(-9.1,30.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgbBWIAAgTIARAAIAAhNIgRAAIAAgTIAlAAIAABgIASAAIAAATgAgFg4IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgBIAFABIAFADIADAFIABAFIgBAGIgDAFIgFAEIgFABg");
	this.shape_25.setTransform(-16.9,29.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AA0BVIAAgTIASAAIAAiCIg8CVIgSAAIg8iVIAACCIARAAIAAATIg3AAIAAgTIAQAAIAAiBIgQAAIAAgVIA2AAIA1CSIA2iSIA0AAIAAAVIgQAAIAACBIAQAAIAAATg");
	this.shape_26.setTransform(-33,29.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(-47.4,14,359.9,31.8), null);


(lib.shaker = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAKA7IABgUIARABIADg0QAAgNgGgHQgHgIgMAAQgGgBgIADQgIADgGAFIgEBDIAQABIAAAUIg3gEIABgTIARABIADhMIgQgBIABgTIAlACIAAANIAAAAIAIgFIAJgFIAJgDIAKgBQAKAAAHAEQAIACAEAGQAFAGADAIQADAJgBALIgDA2IAQABIgBATg");
	this.shape.setTransform(141.9,41.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgCA9QgNAAgLgFQgKgFgHgJQgHgJgEgLQgDgLAAgNQABgOAFgLQAFgLAIgIQAIgIALgDQALgEAMAAQANABAKAFQALAFAHAJQAHAHAEAMQADAMgBAMQAAAOgFAMQgFAKgIAIQgIAIgLAEQgKAEgLAAIgCgBgAgLgpQgGADgGAFQgFAGgDAHQgEAIAAALQgBAJADAIQACAIAFAGQAFAGAGAEQAHADAHAAQAHABAHgDQAGgCAGgGQAFgFADgIQADgIABgKQAAgKgCgIQgCgJgFgFQgFgGgGgDQgHgDgHgBIgDAAQgFAAgGACg");
	this.shape_1.setTransform(127.6,41);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhABTIABgTIAQAAIAHiBIgQgBIABgTIAlACIgBAKQAIgGAJgDQAIgDAJABQAMAAAJAFQAKAFAGAIQAGAIAEALQADALgBAOQAAAOgFAKQgGALgHAIQgIAIgLAEQgLAEgMgBQgIAAgHgCIgNgGIgCAmIASAAIgBAUgAgGhAQgHADgGAGIgDA+QADAEAHADQAHADAJABQAHAAAHgCQAGgCAGgGQAFgFADgHQAEgIAAgLQABgKgCgIQgDgHgFgGQgEgFgHgEQgGgDgHAAIgCAAQgHAAgGACg");
	this.shape_2.setTransform(108.4,42.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAAA9QgMAAgKgFQgKgFgGgIQgHgIgEgLQgDgMABgPQAAgMAFgLQAEgLAHgIQAHgIALgEQAKgEAMABQANAAAJAFQAJAEAFAHQAFAHADAJQACAIABAJIAAAIIAAAIIhTgFIAAAJIACAJQAEALAIAGQAJAGALABQAJAAAJgCQAIgCAKgFIAIAPQgMAHgMADQgKADgLAAIgCAAgAAfgLIgCgNQgCgFgDgEQgDgEgFgDQgFgDgIAAQgGAAgGABQgFACgEAEQgEADgDAGQgDAFgBAHIA8AEg");
	this.shape_3.setTransform(94.9,39.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAAA9QgMAAgKgFQgKgFgGgIQgHgIgEgLQgDgMABgPQAAgMAFgLQAEgLAHgIQAHgIALgEQAKgEAMABQANAAAJAFQAJAEAFAHQAFAHADAJQACAIABAJIAAAIIAAAIIhTgFIAAAJIACAJQAEALAIAGQAJAGALABQAJAAAJgCQAIgCAKgFIAIAPQgMAHgMADQgKADgLAAIgCAAgAAfgLIgCgNQgCgFgDgEQgDgEgFgDQgFgDgIAAQgGAAgGABQgFACgEAEQgEADgDAGQgDAFgBAHIA8AEg");
	this.shape_4.setTransform(81.8,38.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAmBZIgsg2IgQgBIgBAgIAJABIgBATIgygCIABgUIAUABIAGiGIgTgBIABgUIApACIgBAUIAAAAIgFBVIAUABIAdgaIgHAAIABgTIAsACIgBATIgQAAIgkAhIAkArIAOABIgBAUg");
	this.shape_5.setTransform(68.5,35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAKBOQgIAAgFgDQgGgCgDgFQgEgEgBgHQgBgIAAgLIADg+IgSgBIABgRIASABIACgcIAUgJIgCAmIAbABIgBARIgcgBIgDBCIABALQABAEAEACQADACAEAAIAJgBIAIgCIADAOIgLAEQgEACgGAAIgDgBg");
	this.shape_6.setTransform(51.9,35.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgOAcIAEg5IAYAAIgJA7g");
	this.shape_7.setTransform(46,27.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAKA6IABgTIARABIADg0QAAgNgFgIQgIgHgMgBQgGAAgIADQgHADgIAFIgDBDIARABIgBATIg3gCIABgUIARABIADhNIgQAAIABgTIAlABIgBAOIABAAIAIgGIAJgEIAJgDIAKgBQAJABAIADQAHACAGAGQAEAGADAIQACAIAAALIgDA3IAQABIgBAUg");
	this.shape_8.setTransform(36,36.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgCA9QgNAAgLgFQgKgFgHgIQgHgKgEgLQgDgMAAgMQABgOAFgLQAFgLAIgIQAIgIALgDQALgEAMAAQANABAKAFQALAFAHAJQAHAHAEAMQADAMgBAMQAAAOgFALQgFALgIAIQgIAIgLAEQgKAEgLAAIgCgBgAgLgpQgGADgGAFQgFAFgDAJQgEAHAAALQgBAJADAIQACAIAFAGQAFAHAGADQAHADAHAAQAHABAHgDQAGgDAGgEQAFgHADgHQADgIABgKQAAgKgCgIQgCgJgFgFQgFgGgGgDQgHgDgHgBIgDAAQgFAAgGACg");
	this.shape_9.setTransform(21.6,35.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAVA9IgVhdIgfBbIgTgBIgbhkIgKAAIABgUIAlADIgBATIgFAAIAQBJIAhhaIAQAAIAWBeIAZhIIgHAAIACgTIAkACIgBATIgKAAIglBfg");
	this.shape_10.setTransform(5.7,34.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgsBUIABgUIAOABIAOgfIghhkIgKAAIABgUIAsADIgBATIgNAAIAXBJIAfhHIgNgBIABgSIAsACIgBATIgMgBIg6B/IAPABIgBAUg");
	this.shape_11.setTransform(209.1,23.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAAA9QgMAAgKgFQgKgFgGgIQgHgIgEgLQgDgMABgPQAAgMAFgLQAEgLAHgIQAHgIALgEQAKgEAMABQANAAAJAFQAJAEAFAHQAFAHADAJQACAIABAJIAAAIIAAAIIhTgFIAAAJIACAJQAEALAIAGQAJAGALABQAJAAAJgCQAIgCAKgFIAIAPQgMAHgMADQgKADgLAAIgCAAgAAfgLIgCgNQgCgFgDgEQgDgEgFgDQgFgDgIAAQgGAAgGABQgFACgEAEQgEADgDAGQgDAFgBAHIA8AEg");
	this.shape_12.setTransform(195.9,20.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AALBYIABgUIAQABIADg1QAAgNgGgGQgHgHgNgBQgGgBgHAEQgIADgHAEIgDBDIARABIgBAUIg4gDIABgUIASABIAHiGIgQgBIABgUIAlACIgEBHIABAAIAHgFIAJgEIAJgDIAKgBQAJABAIADQAHADAFAFQAFAGACAIQADAIgBALIgDA3IASABIgBAUg");
	this.shape_13.setTransform(181.9,17);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAJBOQgHAAgFgDQgFgCgEgFQgEgEgBgHQgCgIABgLIADg+IgTgBIABgRIATABIACgcIAUgJIgCAmIAbABIgBARIgcgBIgDBCIABALQACAEADACQADACAFAAIAIgBIAIgCIAEAOIgLAEQgFACgGAAIgEgBg");
	this.shape_14.setTransform(170.1,17.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAAA9QgMAAgKgFQgKgFgGgIQgHgIgEgLQgDgMABgPQAAgMAFgLQAEgLAHgIQAHgIALgEQAKgEAMABQANAAAJAFQAJAEAFAHQAFAHADAJQACAIABAJIAAAIIAAAIIhTgFIAAAJIACAJQAEALAIAGQAJAGALABQAJAAAJgCQAIgCAKgFIAIAPQgMAHgMADQgKADgLAAIgCAAgAAfgLIgCgNQgCgFgDgEQgDgEgFgDQgFgDgIAAQgGAAgGABQgFACgEAEQgEADgDAGQgDAFgBAHIA8AEg");
	this.shape_15.setTransform(154,18.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAZA7IABgLQgIAGgKADQgIADgKgBQgJAAgHgDQgHgDgFgGQgEgFgDgIQgCgJAAgLIAEg3IgQAAIABgTIAlACIgDBHQgBANAFAHQAHAHALABQAGAAAIgCIAOgGIAEhGIgQAAIABgTIAlABIgEBgIAMABIgBATg");
	this.shape_16.setTransform(139.5,17.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AADBVIABgUIARABIACgqQgGAFgHADQgHACgJAAQgLgBgKgEQgKgFgIgIQgHgJgDgKQgDgMAAgPQABgNAFgLQAEgLAIgHQAIgIAKgDQALgEAMAAQAIABAHACQAGACAHAFIAAgFIAVABIgICUIARABIgBAUgAgMhCQgHACgFAFQgFAFgDAIQgEAHAAAKQgBALACAIQADAIAEAFQAFAGAGADQAHADAIABQAJAAAGgCQAHgDAEgEIAEhBQgGgFgHgCQgHgDgHAAIgCAAQgGAAgFACg");
	this.shape_17.setTransform(126.1,19.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgCA9QgNAAgLgFQgKgFgHgJQgHgJgEgLQgDgMAAgMQABgOAFgLQAFgLAIgIQAIgIALgDQALgEAMAAQANABAKAFQALAFAHAJQAHAHAEAMQADAMgBAMQAAAOgFALQgFALgIAIQgIAIgLAEQgKAEgLAAIgCgBgAgLgpQgGADgGAFQgFAGgDAHQgEAIAAALQgBAJADAIQACAJAFAFQAFAGAGAEQAHADAHAAQAHABAHgDQAGgDAGgFQAFgGADgHQADgIABgKQAAgJgCgJQgCgJgFgFQgFgGgGgDQgHgDgHgBIgDAAQgFAAgGACg");
	this.shape_18.setTransform(112.2,16.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAJBOQgHAAgFgDQgFgCgEgFQgEgEgBgHQgBgIAAgLIADg+IgTgBIACgRIATABIABgcIAUgJIgCAmIAbABIgBARIgbgBIgEBCIABALQABAEAEACQADACAFAAIAIgBIAIgCIADAOIgKAEQgFACgGAAIgEgBg");
	this.shape_19.setTransform(101.1,14.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAAA9QgMAAgKgFQgKgFgGgIQgHgIgEgLQgDgMABgPQAAgMAFgLQAEgLAHgIQAHgIALgEQAKgEAMABQANAAAJAFQAJAEAFAHQAFAHADAJQACAIABAJIAAAIIAAAIIhTgFIAAAJIACAJQAEALAIAGQAJAGALABQAJAAAJgCQAIgCAKgFIAIAPQgMAHgMADQgKADgLAAIgCAAgAAfgLIgCgNQgCgFgDgEQgDgEgFgDQgFgDgIAAQgGAAgGABQgFACgEAEQgEADgDAGQgDAFgBAHIA8AEg");
	this.shape_20.setTransform(85,14.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AALBYIABgUIAQABIADg1QAAgNgGgGQgHgHgNgBQgGgBgHAEQgIADgHAEIgDBDIARABIgBAUIg4gDIABgUIASABIAHiGIgQgBIABgUIAlACIgEBHIABAAIAHgFIAJgEIAJgDIAKgBQAJABAIADQAHADAFAFQAFAGACAIQADAIgBALIgDA3IASABIgBAUg");
	this.shape_21.setTransform(71,11.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAJBOQgHAAgFgDQgFgCgEgFQgEgEgBgHQgBgIAAgLIADg+IgTgBIACgRIATABIABgcIAUgJIgCAmIAbABIgBARIgbgBIgEBCIABALQABAEAEACQADACAFAAIAIgBIAIgCIADAOIgKAEQgFACgGAAIgEgBg");
	this.shape_22.setTransform(59.2,11.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgKBWIhAgDIABgTIAQAAIAHiCIgQAAIABgUIBAADQAKABAKAEQALADAJAGQAIAGAHAIQAHAIAFAKQAFAJACAMQACALAAAKQgBAMgDALQgEAKgFAKQgGAJgIAHQgIAIgJAFQgJAFgLADQgIACgHAAIgGgBgAgjBCIAbABQALABALgFQAKgEAIgJQAIgJAFgLQAFgMABgOQABgNgEgMQgEgMgHgJQgHgJgKgGQgKgFgLgBIgbgBg");
	this.shape_23.setTransform(41.9,9.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAgBXIhGiQIgHB5IASABIgBATIg3gDIABgTIAPAAIAHiCIgQAAIABgUIAuACIBFCPIACgFIAFhyIgTgBIABgTIA3ACIgBAUIgOgBIgICWg");
	this.shape_24.setTransform(24.8,9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAdBVIABgUIAPABIgLgnIhBgEIgPAmIASABIgCAUIg3gDIABgUIAPABIA9iTIAgACIAtCYIARABIgBAUgAAcAIIgXhMIgdBJIA0ADg");
	this.shape_25.setTransform(6.2,8.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.shaker, new cjs.Rectangle(-6.2,-8,225.3,67.2), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeA0QgGgCgFgEIgFgGIgDgIIgBgLQAAgHACgIIAJgqIgOAAIAFgRIAjAAIgNA1QgEATADAIQAFAJANAAQAGAAADgCQAFgCAEgDIAGgHIAOg6IgOAAIAEgRIAiAAIgUBXIAQAAIgEASIgkAAIADgLIgHAGIgHAEIgIACIgHABQgHAAgGgCg");
	this.shape.setTransform(191.6,25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZA0QgJgEgHgGQgGgHgEgIQgDgKAAgKQAAgHACgIQACgJAEgGQAEgIAGgGQAGgFAGgFQAIgDAHgCQAIgDAIAAQAKAAAJAEQAJAEAGAGQAHAHAEAJQADAIABAKQgBAIgBAJQgDAHgEAHQgEAHgFAHQgGAGgHAEQgHADgIADQgIACgIAAQgKAAgJgEgAgIghQgIACgFAHQgGAFgDAIQgDAJAAAIQAAAHACAGQACAGAEAEQAEAEAFADQAFACAHAAQAGAAAIgEQAGgCAGgHQAGgGADgHQADgIAAgJQAAgIgCgGQgCgFgEgFQgEgDgFgCQgGgDgGAAQgHAAgGAEg");
	this.shape_1.setTransform(178.5,24.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag+BNIAFgSIAKAAIATgdIgMhZIgKAAIAFgRIAmAAIgDARIgJAAIAGBBIAphBIgJAAIAFgRIAnAAIgFARIgJAAIhKB2IAKAAIgEASg");
	this.shape_2.setTransform(166.5,27.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgsA2IAVhYIgVAAIAEgRIAoAAIgDAOIAFgGIAHgFIAHgDIAIgBIAHAAIAGAAIAIABIgHAcIgVAAIAEgMQgLAAgGAFQgHAFgEAJIgNA0IASAAIgDASg");
	this.shape_3.setTransform(150.8,24.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgfA0QgHgDgFgHQgHgFgCgIQgDgIAAgJQAAgOAEgMQAFgNAKgIQAIgKAMgFQAMgEANgBQAIAAAGADQAHACAFAEIABgFIAUAAIgUBXIARAAIgFASIglAAIACgHQgHAEgGACQgHACgHABQgJgBgIgDgAgHghQgIADgGAGQgGAGgEAIQgDAJAAALQAAAHABAEQACAFAEAEQACAEAGACQAEABAGABIAIgBIAGgDIAGgDIAHgEIAMg4QgCgDgGgCQgGgDgIAAQgIAAgHAEg");
	this.shape_4.setTransform(138,24.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXA1QgIgDgHgGQgGgHgEgJQgDgJAAgLQAAgNAEgLQAFgMAJgIQAIgJALgFQALgFANAAQAJAAAJADQAHAEAGAFQAFAGADAHQADAIAAAIIgBAKIgBAIIhRAAIAAACIAAACQAAAHACAFQACAGAEAEQAEAEAFACQAGACAFAAQAIAAAHgDQAIgDAEgHIAQALQgEAFgFAEIgKAGIgMAEIgNABQgKAAgJgDgAAggMQAAgGgCgFQgBgFgEgDQgDgDgFgCQgEgCgHAAQgFAAgFACQgFACgFAEIgIAIQgDAFgCAFIA7AAIAAAAg");
	this.shape_5.setTransform(125.7,24.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAPA2IAPhAQADgNgFgGQgEgGgMAAQgIAAgGADQgHAEgGAGIgSBMIgVAAIAVhYIgVAAIAFgRIAoAAIgDAKQAHgGAIgDQAJgDAJAAQAJAAAGACQAHACAEAGQAEAFABAIQACAHgCAJIgMAyIAPAAIgEASg");
	this.shape_6.setTransform(112.2,24.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgWA1QgJgDgHgGQgGgHgDgJQgEgJAAgLQAAgNAEgLQAFgMAJgIQAHgJAMgFQALgFAMAAQALAAAHADQAJAEAFAFQAGAGADAHQACAIAAAIIgBAKIgBAIIhQAAIAAACIAAACQAAAHABAFQACAGAFAEQADAEAFACQAGACAGAAQAHAAAHgDQAIgDAEgHIAQALQgEAFgEAEIgLAGIgNAEIgMABQgKAAgIgDgAAggMQABgGgCgFQgCgFgEgDQgDgDgFgCQgFgCgGAAQgFAAgFACQgFACgFAEIgHAIQgEAFgCAFIA7AAIAAAAg");
	this.shape_7.setTransform(94.9,24.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAPA2IAPhAQADgNgFgGQgEgGgMAAQgIAAgGADQgHAEgGAGIgSBMIgVAAIAVhYIgVAAIAFgRIAoAAIgDAKQAHgGAIgDQAJgDAJAAQAJAAAGACQAHACAEAGQAEAFABAIQACAHgCAJIgMAyIAPAAIgEASg");
	this.shape_8.setTransform(81.4,24.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgZA0QgJgEgGgGQgHgHgEgIQgDgKgBgKQABgHACgIQACgJAEgGQAEgIAGgGQAGgFAGgFQAIgDAHgCQAIgDAIAAQAKAAAJAEQAJAEAHAGQAGAHAEAJQAEAIgBAKQAAAIgCAJQgCAHgEAHQgEAHgGAHQgFAGgHAEQgHADgIADQgIACgIAAQgKAAgJgEgAgJghQgGACgGAHQgFAFgDAIQgEAJAAAIQAAAHADAGQACAGADAEQAEAEAFADQAGACAGAAQAHAAAGgEQAIgCAFgHQAGgGADgHQADgIAAgJQAAgIgCgGQgCgFgEgFQgEgDgFgCQgFgDgHAAQgGAAgIAEg");
	this.shape_9.setTransform(68.1,24.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgjBNQgIgDgGgGQgGgGgDgJQgEgIAAgKQAAgOAFgMQAFgLAJgJQAJgJALgFQAMgFAMAAQAIAAAHADQAHACAGAEIAJgpIgSAAIAEgSIAnAAIghCNIASAAIgEASIgnAAIACgHQgGAEgFACQgHADgHAAQgJAAgIgEgAgOgIQgIADgGAFQgFAGgEAIQgDAJAAAKQAAAHACAGQACAFADAEQAEAEAFACQAFACAGAAQAGAAAHgDQAGgDAGgFIAMg2QgDgFgGgCQgGgDgJAAQgHAAgHAEg");
	this.shape_10.setTransform(50.9,22.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAPA2IAPhAQADgNgFgGQgEgGgMAAQgIAAgGADQgHAEgGAGIgSBMIgVAAIAVhYIgVAAIAFgRIAoAAIgDAKQAHgGAIgDQAJgDAJAAQAJAAAGACQAHACAEAGQAEAFABAIQACAHgCAJIgMAyIAPAAIgEASg");
	this.shape_11.setTransform(36.8,24.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgZBPIAVhYIgTAAIADgRIAnAAIgUBXIAQAAIgDASgAAHgzIgEgDIgDgFIAAgFIAAgFIADgEIAEgEIAGgBIAFABIAEAEIADAEIABAFIgBAFIgDAFIgEADIgFAAg");
	this.shape_12.setTransform(26.6,22.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag2BpIAfiIIgWAAIAEgRIAWAAIAFgTQACgLAEgGQAEgIAFgDQAFgFAHgCQAHgCAIAAIAJABIAIABIAGACIAEACIgKAQIgHgDQgFgBgGAAQgIgBgGAFQgFAEgDAMIgEASIAdAAIgEARIgcAAIgfCIg");
	this.shape_13.setTransform(20,24.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(1,1,1).p("AwejbMAg9AAAIAAG3Mgg9AAAg");
	this.shape_14.setTransform(105.5,23);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(-1,0,213,46), null);


(lib.bywhen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shaker();
	this.instance.parent = this;
	this.instance.setTransform(86.3,22.5,1,1,0,0,0,86.3,22.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bywhen, new cjs.Rectangle(-6.2,-8,225.3,67.2), null);


// stage content:
(lib._728x90_snow = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 8
	this.instance = new lib.cta();
	this.instance.parent = this;
	this.instance.setTransform(838.5,45.5,1,1,0,0,0,105.5,22);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(314).to({_off:false},0).wait(1).to({regY:23,x:836.9,y:46.5},0).wait(1).to({x:830.9},0).wait(1).to({x:817.5},0).wait(1).to({x:790.1},0).wait(1).to({x:740.5},0).wait(1).to({x:687.5},0).wait(1).to({x:649.3},0).wait(1).to({x:622.1},0).wait(1).to({x:601.9},0).wait(1).to({x:586.1},0).wait(1).to({x:573.5},0).wait(1).to({x:563.3},0).wait(1).to({x:555},0).wait(1).to({x:548.1},0).wait(1).to({x:542.5},0).wait(1).to({x:538},0).wait(1).to({x:534.3},0).wait(1).to({x:531.3},0).wait(1).to({x:529.1},0).wait(1).to({x:527.5},0).wait(1).to({x:526.3},0).wait(1).to({x:525.7},0).wait(1).to({regY:22,x:525.5,y:45.5},0).wait(25));

	// Layer 6
	this.instance_1 = new lib.Tween1("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(-169,34.5);
	this.instance_1._off = true;

	this.instance_2 = new lib.Tween2("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(241,34.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_1}]},314).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).wait(25));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(314).to({_off:false},0).wait(1).to({regY:0.5,x:-166.9,y:35},0).wait(1).to({x:-159},0).wait(1).to({x:-141.5},0).wait(1).to({x:-105.5},0).wait(1).to({x:-40.6},0).wait(1).to({x:28.8},0).wait(1).to({x:78.9},0).wait(1).to({x:114.4},0).wait(1).to({x:141},0).wait(1).to({x:161.6},0).wait(1).to({x:178.1},0).wait(1).to({x:191.5},0).wait(1).to({x:202.4},0).wait(1).to({x:211.4},0).wait(1).to({x:218.7},0).wait(1).to({x:224.7},0).wait(1).to({x:229.5},0).wait(1).to({x:233.3},0).wait(1).to({x:236.3},0).wait(1).to({x:238.4},0).wait(1).to({x:239.9},0).wait(1).to({x:240.7},0).to({_off:true},1).wait(25));

	// Layer 5
	this.instance_3 = new lib.Symbol3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(364,62,1,1,0,0,0,221.8,32.4);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(182).to({_off:false},0).wait(38).to({regX:222.1,regY:20,x:364.3,y:49.4},0).wait(1).to({y:48.5},0).wait(1).to({y:46.1},0).wait(1).to({y:42},0).wait(1).to({y:39.3},0).wait(1).to({y:37.7},0).wait(1).to({y:36.8},0).wait(1).to({y:36.2},0).wait(1).to({y:35.8},0).wait(1).to({y:35.7},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:48},0).wait(75).to({regX:222.1,regY:20,x:364.3,y:35.8},0).wait(1).to({y:36.3},0).wait(1).to({y:37.4},0).wait(1).to({y:39.2},0).wait(1).to({y:42},0).wait(1).to({y:46.2},0).wait(1).to({y:53},0).wait(1).to({y:64.3},0).wait(1).to({y:80.2},0).wait(1).to({y:92.6},0).wait(1).to({y:100.3},0).wait(1).to({y:105.1},0).wait(1).to({y:108.4},0).wait(1).to({y:110.6},0).wait(1).to({y:112.1},0).wait(1).to({y:113},0).wait(1).to({y:113.5},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:126},0).to({_off:true},2).wait(38));

	// Layer 4
	this.instance_4 = new lib.bywhen();
	this.instance_4.parent = this;
	this.instance_4.setTransform(1116.5,43.7,4.8,4.8,6,0,0,86.5,22.7);
	this.instance_4._off = true;

	this.instance_5 = new lib.Symbol5();
	this.instance_5.parent = this;
	this.instance_5.setTransform(364,60.8,1,1,0,0,0,221.8,17.7);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(93).to({_off:false},0).wait(1).to({regX:106,regY:25.2,scaleX:4.56,scaleY:4.56,rotation:5.2,x:1166.9,y:63.1},0).wait(1).to({scaleX:4.14,scaleY:4.14,rotation:3.8,x:1093.6,y:59.3},0).wait(1).to({scaleX:3.66,scaleY:3.66,rotation:2.2,x:1011,y:55.5},0).wait(1).to({scaleX:3.17,scaleY:3.17,rotation:0.6,x:926.6,y:52.2},0).wait(1).to({scaleX:2.7,scaleY:2.7,rotation:-1,x:844.2,y:49.4},0).wait(1).to({scaleX:2.25,scaleY:2.25,rotation:-2.5,x:766.9,y:47.3},0).wait(1).to({scaleX:1.86,scaleY:1.86,rotation:-3.8,x:697.9,y:45.8},0).wait(1).to({scaleX:1.53,scaleY:1.53,rotation:-4.9,x:640.7,y:44.8},0).wait(1).to({scaleX:1.29,scaleY:1.29,rotation:-5.7,x:600.1,y:44.2},0).wait(1).to({regX:86.3,regY:22.6,scaleX:1.2,scaleY:1.2,rotation:-6,x:560.3,y:43.6},0).to({_off:true},79).wait(180));
	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(219).to({_off:false},0).to({alpha:1},16).wait(70).to({regX:222.1,regY:20.1,x:364.3,y:63.3},0).wait(1).to({y:63.8},0).wait(1).to({y:64.8},0).wait(1).to({y:66.4},0).wait(1).to({y:68.9},0).wait(1).to({y:72.7},0).wait(1).to({y:78.7},0).wait(1).to({y:88.9},0).wait(1).to({y:103.1},0).wait(1).to({y:114.3},0).wait(1).to({y:121.2},0).wait(1).to({y:125.6},0).wait(1).to({y:128.5},0).wait(1).to({y:130.5},0).wait(1).to({y:131.8},0).wait(1).to({y:132.6},0).wait(1).to({y:133},0).wait(1).to({regX:221.8,regY:17.7,x:364,y:130.8},0).to({_off:true},1).wait(39));

	// Layer 3
	this.instance_6 = new lib.Symbol2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(945.5,103.8,0.803,0.803,0,0,0,112.5,113.2);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(4).to({_off:false},0).wait(1).to({regX:95.8,regY:227.9,scaleX:0.78,scaleY:0.78,x:914.7,y:190.3},0).wait(1).to({scaleX:0.75,scaleY:0.75,x:893.5,y:183.4},0).wait(1).to({scaleX:0.72,scaleY:0.72,x:867.5,y:174.9},0).wait(1).to({scaleX:0.67,scaleY:0.67,x:835.7,y:164.5},0).wait(1).to({scaleX:0.62,scaleY:0.62,x:798.4,y:152.4},0).wait(1).to({scaleX:0.56,scaleY:0.56,x:758.3,y:139.3},0).wait(1).to({scaleX:0.51,scaleY:0.51,x:719.8,y:126.8},0).wait(1).to({scaleX:0.47,scaleY:0.47,x:686.4,y:115.9},0).wait(1).to({scaleX:0.43,scaleY:0.43,x:658.9,y:107},0).wait(1).to({scaleX:0.4,scaleY:0.4,x:636.5,y:99.6},0).wait(1).to({scaleX:0.37,scaleY:0.37,x:618.2,y:93.7},0).wait(1).to({scaleX:0.35,scaleY:0.35,x:603.2,y:88.9},0).wait(1).to({scaleX:0.34,scaleY:0.34,x:590.9,y:84.8},0).wait(1).to({scaleX:0.32,scaleY:0.32,x:580.7,y:81.5},0).wait(1).to({scaleX:0.31,scaleY:0.31,x:572.2,y:78.7},0).wait(1).to({scaleX:0.3,scaleY:0.3,x:565.1,y:76.4},0).wait(1).to({scaleX:0.29,scaleY:0.29,x:559.3,y:74.5},0).wait(1).to({scaleX:0.29,scaleY:0.29,x:554.5,y:73},0).wait(1).to({scaleX:0.28,scaleY:0.28,x:550.7,y:71.7},0).wait(1).to({scaleX:0.28,scaleY:0.28,x:547.6,y:70.7},0).wait(1).to({scaleX:0.27,scaleY:0.27,x:545.3,y:69.9},0).wait(1).to({scaleX:0.27,scaleY:0.27,x:543.6,y:69.4},0).wait(1).to({scaleX:0.27,scaleY:0.27,x:542.4,y:69},0).wait(1).to({scaleX:0.27,scaleY:0.27,x:541.7,y:68.8},0).wait(1).to({regX:112.5,regY:113.2,x:546,y:38},0).wait(63).to({regX:95.8,regY:227.9,scaleX:0.27,scaleY:0.27,x:540.5,y:68.8},0).wait(1).to({scaleX:0.27,scaleY:0.27,x:536.8,y:69},0).wait(1).to({scaleX:0.28,scaleY:0.28,x:529.9,y:69.3},0).wait(1).to({scaleX:0.28,scaleY:0.28,x:518.5,y:69.8},0).wait(1).to({scaleX:0.3,scaleY:0.3,x:500.6,y:70.7},0).wait(1).to({scaleX:0.31,scaleY:0.31,x:473.8,y:72},0).wait(1).to({scaleX:0.34,scaleY:0.34,x:435.6,y:73.8},0).wait(1).to({scaleX:0.37,scaleY:0.37,x:390.3,y:76},0).wait(1).to({scaleX:0.4,scaleY:0.4,x:348.9,y:78},0).wait(1).to({scaleX:0.42,scaleY:0.42,x:317.1,y:79.5},0).wait(1).to({scaleX:0.44,scaleY:0.44,x:294,y:80.6},0).wait(1).to({scaleX:0.45,scaleY:0.45,x:277.3,y:81.4},0).wait(1).to({scaleX:0.46,scaleY:0.46,x:265.3,y:81.9},0).wait(1).to({scaleX:0.46,scaleY:0.46,x:256.7,y:82.4},0).wait(1).to({scaleX:0.47,scaleY:0.47,x:250.8,y:82.6},0).wait(1).to({scaleX:0.47,scaleY:0.47,x:247,y:82.8},0).wait(1).to({scaleX:0.47,scaleY:0.47,x:245,y:82.9},0).wait(1).to({regX:112.4,regY:112.5,x:252.3,y:29},0).wait(1).to({regX:95.8,regY:227.9,x:244.5,y:83.3},0).wait(2).to({x:244.6,y:83.4},0).wait(1).to({x:244.7,y:83.5},0).wait(1).to({x:244.9,y:83.7},0).wait(1).to({x:245.1,y:83.9},0).wait(1).to({x:245.4,y:84.2},0).wait(1).to({x:245.6,y:84.4},0).wait(1).to({x:245.9,y:84.7},0).wait(1).to({x:246.1,y:84.9},0).wait(1).to({x:246.3,y:85.1},0).wait(1).to({x:246.4,y:85.2},0).wait(2).to({regX:112.4,regY:112.5,x:254.3,y:31},0).wait(1).to({regX:95.8,regY:227.9,x:246.5,y:85.2},0).wait(3).to({x:246.6,y:85.1},0).wait(1).to({x:246.7,y:85},0).wait(1).to({x:246.8,y:84.9},0).wait(1).to({x:246.9,y:84.8},0).wait(1).to({x:247.1,y:84.6},0).wait(1).to({x:247.3,y:84.4},0).wait(1).to({x:247.5,y:84.2},0).wait(1).to({x:247.7,y:84},0).wait(1).to({x:247.9,y:83.8},0).wait(1).to({x:248,y:83.7},0).wait(1).to({x:248.2,y:83.5},0).wait(1).to({x:248.3,y:83.4},0).wait(1).to({x:248.4,y:83.3},0).wait(3).to({regX:112.4,regY:112.5,x:256.3,y:29},0).wait(1).to({regX:95.8,regY:227.9,x:248.5,y:83.2},0).wait(4).to({y:83.1},0).wait(2).to({y:83},0).wait(1).to({y:82.9},0).wait(1).to({y:82.8},0).wait(1).to({y:82.7},0).wait(1).to({y:82.6},0).wait(1).to({y:82.5},0).wait(2).to({y:82.4},0).wait(1).to({y:82.3},0).wait(4).to({regX:112.4,regY:112.5,x:256.3,y:28},0).wait(1).to({regX:95.8,regY:227.9,x:248.4,y:82.2},0).wait(2).to({x:248.3},0).wait(1).to({x:248.2,y:82.1},0).wait(1).to({x:248},0).wait(1).to({x:247.8,y:82},0).wait(1).to({x:247.5,y:81.9},0).wait(1).to({x:247.1,y:81.7},0).wait(1).to({x:246.7,y:81.5},0).wait(1).to({x:246.2,y:81.3},0).wait(1).to({x:245.7,y:81.1},0).wait(1).to({x:245.2,y:80.9},0).wait(1).to({x:244.7,y:80.8},0).wait(1).to({x:244.4,y:80.6},0).wait(1).to({x:244.1,y:80.5},0).wait(1).to({x:243.8,y:80.4},0).wait(1).to({x:243.6,y:80.3},0).wait(1).to({x:243.5},0).wait(2).to({regX:112.4,regY:112.5,x:251.3,y:26},0).to({_off:true},1).wait(180));

	// Layer 2
	this.instance_7 = new lib.Symbol1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-190.6,45.8,1,1,0,0,0,136.3,32.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(1).to({regX:132.8,regY:32,x:-178,y:45.4},0).wait(1).to({x:-157.7},0).wait(1).to({x:-131.2},0).wait(1).to({x:-95.5},0).wait(1).to({x:-47.1},0).wait(1).to({x:8.2},0).wait(1).to({x:54.8},0).wait(1).to({x:89.1},0).wait(1).to({x:114.6},0).wait(1).to({x:134.2},0).wait(1).to({x:149.9},0).wait(1).to({x:162.7},0).wait(1).to({x:173.4},0).wait(1).to({x:182.3},0).wait(1).to({x:189.9},0).wait(1).to({x:196.3},0).wait(1).to({x:201.8},0).wait(1).to({x:206.5},0).wait(1).to({x:210.4},0).wait(1).to({x:213.8},0).wait(1).to({x:216.7},0).wait(1).to({x:219.1},0).wait(1).to({x:221},0).wait(1).to({x:222.6},0).wait(1).to({x:223.8},0).wait(1).to({x:224.7},0).wait(1).to({x:225.4},0).wait(1).to({x:225.7},0).wait(1).to({regX:136.3,regY:32.4,x:229.4,y:45.8},0).wait(63).to({regX:132.8,regY:32,scaleX:1.01,scaleY:1.01,x:223.2,y:45.4},0).wait(1).to({scaleX:1.03,scaleY:1.03,x:213.9,y:45.3},0).wait(1).to({scaleX:1.07,scaleY:1.07,x:193.8},0).wait(1).to({scaleX:1.16,scaleY:1.16,x:153.6},0).wait(1).to({scaleX:1.36,scaleY:1.36,x:64.7,y:45.2},0).wait(1).to({scaleX:1.77,scaleY:1.77,x:-119.1,y:45.1},0).wait(1).to({scaleX:2.05,scaleY:2.05,x:-246.4,y:44.9},0).wait(1).to({scaleX:2.21,scaleY:2.21,x:-316.4,y:44.8},0).wait(1).to({scaleX:2.31,scaleY:2.31,x:-361.7},0).wait(1).to({scaleX:2.38,scaleY:2.38,x:-393.6},0).wait(1).to({scaleX:2.43,scaleY:2.43,x:-417,y:44.7},0).wait(1).to({scaleX:2.47,scaleY:2.47,x:-434.3},0).wait(1).to({scaleX:2.5,scaleY:2.5,x:-447.3},0).wait(1).to({scaleX:2.52,scaleY:2.52,x:-456.7},0).wait(1).to({scaleX:2.54,scaleY:2.54,x:-463.4},0).wait(1).to({scaleX:2.54,scaleY:2.54,x:-467.7},0).wait(1).to({scaleX:2.55,scaleY:2.55,x:-470.1},0).wait(1).to({regX:136.2,regY:32.4,scaleX:2.55,scaleY:2.55,x:-462.1,y:45.8},0).to({_off:true},113).wait(140));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#01C6AD").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(362));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10.4,45,1102.4,90);
// library properties:
lib.properties = {
	id: '2672068B7FDB4113A44DB72DDA239F2C',
	width: 728,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/728x90_snow_atlas_.png", id:"728x90_snow_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['2672068B7FDB4113A44DB72DDA239F2C'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;