(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"300x250_optom_atlas_", frames: [[0,353,318,67],[0,0,423,351]]}
];


// symbols:



(lib.docBC = function() {
	this.spriteSheet = ss["300x250_optom_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.volcanoman = function() {
	this.spriteSheet = ss["300x250_optom_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.docBC();
	this.instance.parent = this;
	this.instance.setTransform(-142,-30,0.9,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-142,-30,286.2,60.3);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAOIgFgDIgDgFIgBgGIABgFIADgEIAFgEIAFgCIAGACIAFAEIADAEIABAFIgBAGIgDAFIgFADIgGACg");
	this.shape.setTransform(68.9,120.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_1.setTransform(61.8,114.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXAfIAWhDIAYAKIgdA+g");
	this.shape_2.setTransform(53.7,107.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgHgHQgIgHgMAAQgHAAgIADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_3.setTransform(42.2,115.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_4.setTransform(28.4,116);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_5.setTransform(18.9,113.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgNAAQgIAAgIAEQgIADgHAGIAABGIARAAIAAAUIg3AAIAAgUIARAAIAAg3QAAgOgHgHQgIgHgMAAQgJAAgHADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIALgBQANAAAJAFQAJAFAGAKIAJgHIAKgHIALgEQAGgCAGAAQAKAAAIADQAIADAGAFQAFAGADAIQADAJgBALIAAA6IASAAIAAAUg");
	this.shape_6.setTransform(-2.3,115.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_7.setTransform(-21.1,116);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AASA9IAAgUIAGAAIgYgeIgWAeIAGAAIAAAUIgpAAIAAgUIAKAAIAlgqIgigmIgNAAIAAgVIApAAIAAAVIgFAAIAVAcIAXgcIgGAAIAAgVIAoAAIAAAVIgKAAIgiAnIAkApIAJAAIAAAUg");
	this.shape_8.setTransform(-33.8,116);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgUA8QgKgFgIgHQgHgJgEgMQgFgLAAgQQAAgNAEgLQADgMAIgJQAHgIALgFQALgFANAAQANAAAJAEQAJAFAHAGQAFAHADAJQADAJABAJIABAJIAAAIIhWAAIABAJIACAIQAEAMAKAGQAJAGALgBQAKABAJgDQAIgDAKgFIAJAPQgMAIgMAEQgMAEgNAAQgLAAgLgEgAAfgNIgCgNQgCgGgEgEQgDgEgGgCQgFgDgIAAQgHAAgGADQgFACgEADQgEAFgDAFQgCAGgBAIIA+AAg");
	this.shape_9.setTransform(-47.3,116);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_10.setTransform(141.9,87.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_11.setTransform(131.6,89);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_12.setTransform(122.2,86.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_13.setTransform(112.5,88.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_14.setTransform(102.5,87.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgTA8QgLgFgHgHQgIgJgFgMQgDgLAAgQQAAgNADgLQADgMAIgJQAHgIAKgFQALgFANAAQAOAAAKAEQAIAFAGAGQAGAHADAJQADAJACAJIAAAJIAAAIIhWAAIAAAJIADAIQAEAMAJAGQAKAGAMgBQAJABAJgDQAJgDAKgFIAJAPQgMAIgNAEQgMAEgNAAQgLAAgKgEgAAfgNIgCgNQgCgGgDgEQgEgEgFgCQgGgDgIAAQgHAAgFADQgGACgEADQgEAFgCAFQgDAHgBAHIA+AAg");
	this.shape_15.setTransform(90.9,89);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgOAAQgHAAgIAEQgIADgHAGIAABGIARAAIAAAUIg3AAIAAgUIARAAIAAg3QAAgOgHgHQgHgHgNAAQgIAAgIADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIALgBQANAAAKAFQAIAFAGAKIAJgHIAKgHIALgEQAGgCAGAAQAKAAAIADQAIADAGAFQAFAGADAIQACAJAAALIAAA6IASAAIAAAUg");
	this.shape_16.setTransform(72.3,88.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_17.setTransform(53,89);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_18.setTransform(41.5,87.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag/BaIAAgUIARAAIAAiHIgRAAIAAgVIAmAAIAAAKQAIgGAJgDQAIgEAKAAQAMAAAKAFQAKAEAHAIQAHAIAEAMQAEALAAAOQAAAOgEANQgFALgHAIQgIAJgLAFQgLAEgNAAQgIAAgIgBIgNgFIAAAnIATAAIAAAUgAgLhCQgIADgFAGIAABBQADAEAIADQAHADAKAAQAHAAAHgCQAHgDAFgGQAGgGADgIQADgIAAgLQAAgLgDgIQgDgIgFgFQgFgGgHgCQgHgDgIAAQgHAAgIADg");
	this.shape_19.setTransform(29.6,91.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_20.setTransform(15.2,89);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgHgHQgIgHgNAAQgGAAgIADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAFAGAEAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_21.setTransform(-5.1,88.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_22.setTransform(-19.9,89);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgSIAIAGIAKAEIALAEIALABQAIAAAGgCQAHgDAEgEQAFgFACgIQACgIAAgNIAAgBQgGAGgIADQgIAEgKAAQgLAAgLgEQgLgFgHgHQgIgJgFgMQgEgLAAgQQAAgNAEgMQAEgLAIgJQAIgIALgEQALgFAMAAQAJAAAIADQAHACAHAEIAAgGIAWAAIAAB0QAAAcgOAPQgOAPgcAAgAgJhBQgHACgFAGQgFAFgDAIQgDAIAAAKQAAALACAJQADAIAFAGQAFAFAHAEQAHACAIAAIAKgBIAIgCIAGgFIAFgEIAAhBQgGgGgIgCQgIgCgIgBQgHABgGADg");
	this.shape_23.setTransform(-38.9,91.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgHgHQgIgHgMAAQgIAAgHADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_24.setTransform(-53.5,88.9);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_25.setTransform(-65.2,86.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AApBbIgwg2IgQAAIAAAiIAKAAIAAAUIg0AAIAAgUIAUAAIAAiNIgVAAIAAgUIArAAIAAAUIAABaIAVAAIAbgdIgHAAIAAgUIAuAAIAAAUIgPAAIglAlIAoArIAPAAIAAAUg");
	this.shape_26.setTransform(-76.5,85.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_27.setTransform(-91.5,89);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_28.setTransform(-105.9,89);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhBBZIAAgUIAQAAIAAiJIgQAAIAAgUIBOABQALAAAKADQAJAFAHAHQAHAGAEAKQAEAKAAALQAAAKgGAKQgGAKgMAFQAGACAEAEQAFAEADAFQAEAFACAFIABALQAAALgEAKQgEAJgHAIQgHAHgJAEQgKAEgLAAgAgaBFIApAAQAFAAAFgDIAJgHQADgFACgGQACgFAAgGQAAgFgCgFQgCgFgDgEIgJgGQgFgCgFAAIgpAAgAgagJIAoAAQAFgBAFgCQAFgCAEgDQADgEACgFQACgFAAgFQAAgGgCgGQgCgFgDgFQgEgEgFgDQgFgDgFAAIgoAAg");
	this.shape_29.setTransform(-120.4,86.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(-130.8,70,279.3,60), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAOIgFgDIgDgFIgBgGIABgFIADgEIAFgEIAFgCIAGACIAFAEIADAEIABAFIgBAGIgDAFIgFADIgGACg");
	this.shape.setTransform(114,92.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgcBYQgLgEgIgIQgIgIgEgMQgEgNAAgPQAAgOAEgLQAEgLAIgIQAHgJALgEQALgFAOABQAHAAAIACQAHABAHAGIAAgvIgRAAIAAgVIAmAAIAACiIASAAIAAAUIgnAAIAAgKQgGAGgIADQgIAEgJAAQgMAAgKgFgAgSgLQgHACgFAGQgFAEgDAJQgDAHAAALQAAALADAJQADAIAFAGQAFAGAHADQAHADAIAAQAJAAAHgDQAGgDAGgGIAAhCQgGgFgIgDQgHgCgHAAQgIAAgHADg");
	this.shape_1.setTransform(104,85.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_2.setTransform(90.8,87.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_3.setTransform(78.5,88);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAMBbIAAgUIAQAAIAAg3QAAgOgHgGQgHgIgNAAQgHAAgHAEQgIADgHAFIAABHIASAAIAAAUIg6AAIAAgUIASAAIAAiNIgQAAIAAgUIAmAAIAABKIABAAIAHgGIAJgFIAKgDIAKgBQAJAAAIACQAIADAFAGQAGAFADAJQADAHAAAMIAAA6IASAAIAAAUg");
	this.shape_4.setTransform(64.4,84.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_5.setTransform(45.2,88);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_6.setTransform(35.8,85.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgSIAIAGIAKAEIALAEIALABQAIAAAGgDQAHgBAEgFQAFgFACgIQACgIAAgMIAAgCQgGAGgIAEQgIADgKAAQgLAAgLgEQgLgEgHgJQgIgIgFgMQgEgLAAgQQAAgNAEgMQAEgLAIgJQAIgIALgEQALgFAMAAQAJAAAIACQAHADAHAEIAAgGIAWAAIAABzQAAAegOAOQgOAPgcAAgAgJhBQgHACgFAGQgFAFgDAIQgDAIAAAKQAAALACAJQADAIAFAGQAFAFAHAEQAHACAIAAIAKgBIAIgCIAGgFIAFgEIAAhCQgGgFgIgCQgIgDgIAAQgHAAgGAEg");
	this.shape_7.setTransform(19.2,90.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgHgHQgIgHgMAAQgIAAgHADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_8.setTransform(4.5,87.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_9.setTransform(-7.2,85.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_10.setTransform(-15.6,86.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AALA+IAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgHAAgHADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJABALIAAA6IAQAAIAAAUg");
	this.shape_11.setTransform(-28,87.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTA8QgLgFgHgHQgIgJgFgMQgDgMAAgPQAAgNADgLQADgMAIgJQAHgIAKgFQALgFANAAQAOAAAKAEQAIAEAGAHQAGAHADAJQADAJACAJIAAAJIAAAIIhWAAIAAAJIADAIQAEAMAJAGQAKAFAMAAQAJABAJgDQAJgCAKgGIAJAPQgMAIgNAEQgMAEgNAAQgLAAgKgEgAAfgNIgCgNQgCgGgDgEQgEgEgFgDQgGgCgIAAQgHAAgFACQgGADgEADQgEAEgCAGQgDAHgBAHIA+AAg");
	this.shape_12.setTransform(-43.2,88);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_13.setTransform(-55.5,87.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_14.setTransform(-67.8,88);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag+BZIAAgUIAQAAIAAiJIgQAAIAAgUIBGAAQAMAAAKADQAKADAIAGQAHAGAEAJQAEAJAAAMQAAAKgEAJQgEAIgHAHQgHAGgLADQgKADgMAAIgfAAIAAA/IASAAIAAAUgAgXgMIAfAAQAHAAAGgBQAFgCAEgEQAEgDADgGQACgFAAgHQAAgNgIgHQgIgIgSAAIgcAAg");
	this.shape_15.setTransform(-81,85.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(-91.1,69,209.9,33), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.volcanoman();
	this.instance.parent = this;
	this.instance.setTransform(-607,164,1.181,1.181);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-607,164,499.7,414.7), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOBWIgFgDIgDgFIgBgFIABgGIADgEIAFgEIAFgBIAGABIADAEIAEAEIABAGIgBAFIgEAFIgDADIgGACgAgTAxIABgUQABgIADgHQACgHAEgFIAKgKIALgJIAIgHQADgDACgEQACgEAAgGQAAgFgCgFQgCgFgDgDQgEgEgEgCQgFgDgFAAQgJAAgFAEQgGADgEAEQgEAFgCAEIgBAJIgUgBQAAgKAEgIQAFgJAHgGQAGgGAJgEQAKgEAKAAQALAAAJAEQAJADAFAHQAGAGADAIQADAIAAAJQAAALgGAKQgFAKgMAIIgMAIQgHAGgCAJQgDAIgBAGIgBAPg");
	this.shape.setTransform(250.6,42.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBBNQgFgCgEgFQgEgEgCgHQgCgIAAgLIABg/IgTAAIAAgRIATAAIAAgbIATgLIAAAmIAbAAIAAARIgbAAIAABDQAAAGABAEQACAFADACQAEABAEAAIAIgBIAIgDIAFAOIgLAFQgGACgIAAQgIAAgFgCg");
	this.shape_1.setTransform(240,43.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUA5QgJgEgEgHIgMAAIAAgUIAXAAQAAAFACAEQACADAEACIAIADIAHABIAJgBIAHgDIAFgFQACgDAAgDQAAgGgEgEQgEgEgIgDIgWgIQgNgEgHgIQgGgHAAgLQAAgIACgGQADgGAFgFQAGgEAHgDQAIgDAJAAQAMAAAIAEQAJADAGAJIALAAIAAATIgXAAQAAgFgCgDQgCgDgEgCIgHgDIgIgBIgIABIgGADIgFAEIgBAGQAAAGADAEQAEADAIADIAWAIQAOAFAHAHQAGAIAAAMQAAAIgDAGQgDAHgGAEQgFAFgIACQgIADgKAAQgNAAgIgFg");
	this.shape_2.setTransform(230.1,45.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXA5QgKgFgIgHQgHgJgFgLQgEgMAAgNQAAgNAEgLQAFgLAHgJQAIgIALgFQALgDALAAQANAAALADQALAFAHAIQAIAIAEAMQAEALAAANQAAANgEALQgEAMgIAIQgHAJgLAEQgLAFgNgBQgMABgLgFgAgNgoQgGADgFAFQgFAGgDAIQgDAJAAAJQAAAKADAIQADAIAFAFQAFAHAGACQAHADAGAAQAIAAAHgDQAGgDAFgFQAFgGADgIQADgIAAgKQAAgJgDgJQgDgIgFgGQgEgFgHgDQgHgDgIABQgGgBgHADg");
	this.shape_3.setTransform(217.6,45.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("Ag8BWIAAgTIAQAAIAAiCIgRAAIAAgUIAlAAIAAAKQAIgFAJgEQAHgDAKAAQALAAAKAEQAJAFAHAHQAHAIAEALQAEAKAAANQAAAOgFAMQgEALgHAIQgIAJgKAEQgLAFgMgBQgIAAgHgBIgNgFIAAAmIASAAIAAATgAgKhAQgIAEgFAFIAAA+QADAFAHACQAHADAKAAQAHAAAGgDQAHgCAFgGQAFgFADgHQADgJAAgLQAAgJgDgIQgDgIgEgFQgFgFgHgDQgGgDgIABQgHAAgHACg");
	this.shape_4.setTransform(203.7,47.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAxA7IAAgTIARAAIAAg0QAAgOgGgGQgIgHgMAAQgIAAgHADQgJAEgFAFIAABDIAQAAIAAATIg1AAIAAgTIAQAAIAAg0QAAgOgHgGQgHgHgMAAQgIAAgHADIgOAJIAABDIAQAAIAAATIg2AAIAAgTIAQAAIAAhNIgQAAIAAgTIAmAAIAAANIAHgGIAJgFIAKgDIALgBQAMAAAJAEQAIAFAFAKIAJgHIAKgHIALgEQAFgBAGAAQAKAAAHACQAIADAFAFQAFAFADAJQADAIAAALIAAA3IAQAAIAAATg");
	this.shape_5.setTransform(185.4,45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgXA5QgKgFgIgHQgHgJgFgLQgEgMAAgNQAAgNAEgLQAFgLAHgJQAIgIALgFQALgDALAAQANAAALADQALAFAHAIQAIAIAEAMQAEALAAANQAAANgEALQgEAMgIAIQgHAJgLAEQgLAFgNgBQgMABgLgFgAgNgoQgGADgFAFQgFAGgDAIQgDAJAAAJQAAAKADAIQADAIAFAFQAFAHAGACQAHADAGAAQAIAAAHgDQAGgDAFgFQAFgGADgIQADgIAAgKQAAgJgDgJQgDgIgFgGQgEgFgHgDQgHgDgIABQgGgBgHADg");
	this.shape_6.setTransform(166.9,45.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgTA5QgKgFgIgIQgHgIgEgLQgEgMAAgNQAAgNAEgLQAEgLAIgIQAIgJAKgEQAKgFALAAQALAAAKAEQAJAEAIAIIAMAAIAAATIgVAAQgFgJgHgDQgHgEgKAAQgGAAgHADQgGADgFAFQgFAGgDAIQgCAIAAAJQAAAKACAHQADAIAFAGQAFAFAGADQAHADAGAAQALAAAIgFQAHgFAFgKIARAIQgCAIgGAFQgEAGgHAEQgGAEgHACQgIADgIAAQgMAAgKgFg");
	this.shape_7.setTransform(153.9,45.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAxA7IAAgTIARAAIAAg0QAAgOgHgGQgHgHgMAAQgHAAgJADQgHAEgGAFIAABDIAQAAIAAATIg1AAIAAgTIAQAAIAAg0QAAgOgGgGQgIgHgMAAQgIAAgHADIgOAJIAABDIAQAAIAAATIg2AAIAAgTIARAAIAAhNIgRAAIAAgTIAlAAIAAANIAIgGIAJgFIAKgDIAKgBQANAAAJAEQAIAFAFAKIAJgHIAKgHIALgEQAFgBAHAAQAJAAAHACQAIADAFAFQAFAFADAJQADAIAAALIAAA3IAQAAIAAATg");
	this.shape_8.setTransform(131.1,45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgXA5QgKgFgIgHQgHgJgFgLQgEgMAAgNQAAgNAEgLQAFgLAHgJQAIgIALgFQALgDALAAQANAAALADQALAFAHAIQAIAIAEAMQAEALAAANQAAANgEALQgEAMgIAIQgHAJgLAEQgLAFgNgBQgMABgLgFgAgNgoQgGADgFAFQgFAGgDAIQgDAJAAAJQAAAKADAIQADAIAFAFQAFAHAGACQAHADAGAAQAIAAAHgDQAGgDAFgFQAFgGADgIQADgIAAgKQAAgJgDgJQgDgIgFgGQgEgFgHgDQgHgDgIABQgGgBgHADg");
	this.shape_9.setTransform(112.6,45.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgpA7IAAgUIARAAIAAhMIgRAAIAAgUIAmAAIAAAQIADgGIAFgGIAIgDIAIgBIALAAIAKAAIAAAYIgVAAIAAgGIgIABQgEABgEADQgDADgCAEIgDALIAAA3IATAAIAAAUg");
	this.shape_10.setTransform(100.4,45.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgpBXIAAgTIASAAIAAhPIgUAAIAAgRIAUAAIAAgSQAAgKACgIQADgHAFgGQAFgFAGgCQAHgCAIAAIALAAIAJACIAGACIAFACIgHAPIgJgDQgGgCgGAAQgJAAgGAGQgEAGAAALIAAATIAaAAIAAARIgaAAIAABPIASAAIAAATg");
	this.shape_11.setTransform(92.1,42.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTA5QgKgEgHgHQgHgIgEgLQgEgMAAgPQAAgMADgLQAEgLAHgIQAGgIALgGQAKgEAMAAQAOAAAIADQAJAFAGAGQAFAGADAJQADAIABAJIABAJIAAAIIhTAAIABAJIACAIQAEALAJAGQAKAFAKAAQAJAAAJgDQAIgCAKgGIAIAPQgLAIgMADQgLAEgNAAQgLAAgKgEgAAegNIgCgMQgCgFgDgEQgEgFgFgBQgFgDgIAAQgGAAgGADQgFACgEADQgEAEgCAGQgDAFgBAHIA8AAg");
	this.shape_12.setTransform(74.8,45.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgbBVQgKgEgIgIQgHgIgFgMQgDgLAAgQQAAgNADgLQAEgKAIgHQAHgJAKgEQALgEANAAQAHAAAIACQAHACAGAEIAAgsIgQAAIAAgTIAkAAIAACaIARAAIAAATIglAAIAAgJQgGAFgHADQgIADgIAAQgMAAgKgDgAgRgLQgHADgFAFQgEAEgDAIQgDAIAAAJQAAALACAJQADAIAFAFQAFAGAHACQAGADAJAAQAIAAAGgDQAHgCAFgGIAAhAQgGgFgHgCQgHgBgHAAQgIgBgGADg");
	this.shape_13.setTransform(61.6,42.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgdA6QgHgCgFgFQgFgFgDgGQgDgGAAgHQAAgHACgGQACgGAEgEQAEgEAFgCIAKgFIALgCIAKgBIANABIAKABIAAgKQAAgGgCgEQgBgFgEgDQgDgDgFgBQgEgCgFAAIgKABIgJACIgIADIgGADIgGgPIAJgFIAKgEIALgCIALgBQAJAAAIACQAJADAFAFQAGAFADAIQADAHAAALIAAA5IANAAIAAAUIgiAAIAAgLQgHAGgIAEQgHAEgKAAQgJAAgHgDgAgPAGQgFABgEADQgEACgCAEQgCAEAAAFQAAAFACADQACAEADACQADACAEABIAKABIAIgBIAHgCIAHgEIAFgFIAAgaIgXAAIgLABg");
	this.shape_14.setTransform(47.9,45.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAyA7IAAgTIAQAAIAAg0QAAgOgGgGQgIgHgMAAQgIAAgHADQgJAEgFAFIAABDIAQAAIAAATIg1AAIAAgTIAQAAIAAg0QAAgOgHgGQgHgHgMAAQgIAAgHADIgOAJIAABDIARAAIAAATIg3AAIAAgTIAQAAIAAhNIgQAAIAAgTIAmAAIAAANIAIgGIAJgFIAJgDIALgBQAMAAAJAEQAIAFAFAKIAJgHIAKgHIAKgEQAGgBAGAAQAJAAAIACQAIADAFAFQAGAFACAJQADAIAAALIAAA3IAQAAIAAATg");
	this.shape_15.setTransform(30.3,45);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgXA5QgKgFgIgHQgHgJgFgLQgEgMAAgNQAAgNAEgMQAFgLAHgIQAIgIALgEQALgFALAAQANAAALAFQALAEAHAIQAIAIAEALQAEAMAAANQAAANgEAMQgEALgIAIQgHAIgLAFQgLAEgNABQgMgBgLgEgAgNgoQgGADgFAFQgFAGgDAIQgDAJAAAJQAAAKADAIQADAIAFAFQAFAHAGACQAHAEAGAAQAIAAAHgEQAGgDAFgFQAFgGADgIQADgIAAgKQAAgJgDgJQgDgIgFgGQgEgFgHgDQgHgCgIgBQgGABgHACg");
	this.shape_16.setTransform(238.1,19.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AALA7IAAgTIAQAAIAAg0QAAgOgGgGQgHgHgNAAQgGAAgHADIgPAJIAABDIARAAIAAATIg2AAIAAgTIAQAAIAAhNIgQAAIAAgTIAlAAIAAAOIAIgHIAJgFIAKgDIAJgBQAJAAAIACQAHADAFAFQAGAFACAJQADAIABALIAAA3IAPAAIAAATg");
	this.shape_17.setTransform(223.7,19.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgdA6QgHgCgFgFQgFgFgDgGQgDgGAAgHQAAgHACgGQACgGAEgEQAEgEAFgCIAKgFIALgCIAKgBIANABIAKABIAAgKQAAgGgCgEQgBgFgEgDQgDgDgFgBQgEgCgFAAIgKABIgJACIgIADIgGADIgGgPIAJgFIAKgEIALgCIALgBQAJAAAIACQAJADAFAFQAGAFADAIQADAHAAALIAAA5IANAAIAAAUIgiAAIAAgLQgHAGgIAEQgHAEgKAAQgJAAgHgDgAgPAGQgFABgEADQgEACgCAEQgCAEAAAFQAAAFACADQACAEADACQADACAEABIAKABIAIgBIAHgCIAHgEIAFgFIAAgaIgXAAIgLABg");
	this.shape_18.setTransform(209.6,19.3);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgSA5QgLgFgHgIQgIgIgEgLQgEgMAAgNQAAgNAEgLQAFgLAHgIQAIgJAKgEQALgFAKAAQALAAAKAEQAKAEAHAIIAMAAIAAATIgWAAQgEgJgHgDQgIgEgJAAQgHAAgFADQgHADgFAFQgFAGgDAIQgCAIAAAJQAAAKACAHQADAIAFAGQAFAFAHADQAFADAHAAQALAAAHgFQAJgFAFgKIAQAIQgDAIgEAFQgGAGgGAEQgGAEgHACQgIADgIAAQgMAAgJgFg");
	this.shape_19.setTransform(197.3,19.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgaBXIAAgTIAQAAIAAiHIgQAAIAAgTIAkAAIAACaIASAAIAAATg");
	this.shape_20.setTransform(187.3,16.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgXA5QgKgFgIgHQgHgJgFgLQgEgMAAgNQAAgNAEgMQAFgLAHgIQAIgIALgEQALgFALAAQANAAALAFQALAEAHAIQAIAIAEALQAEAMAAANQAAANgEAMQgEALgIAIQgHAIgLAFQgLAEgNABQgMgBgLgEgAgNgoQgGADgFAFQgFAGgDAIQgDAJAAAJQAAAKADAIQADAIAFAFQAFAHAGACQAHAEAGAAQAIAAAHgEQAGgDAFgFQAFgGADgIQADgIAAgKQAAgJgDgJQgDgIgFgGQgEgFgHgDQgHgCgIgBQgGABgHACg");
	this.shape_21.setTransform(176.5,19.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgJA7IgmhiIgKAAIAAgTIAoAAIAAATIgKAAIAbBPIAchPIgHAAIAAgTIAlAAIAAATIgKAAIgmBig");
	this.shape_22.setTransform(163.4,19.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgdA6QgHgCgFgFQgFgFgDgGQgDgGAAgHQAAgHACgGQACgGAEgEQAEgEAFgCIAKgFIALgCIAKgBIANABIAKABIAAgKQAAgGgCgEQgBgFgEgDQgDgDgFgBQgEgCgFAAIgKABIgJACIgIADIgGADIgGgPIAJgFIAKgEIALgCIALgBQAJAAAIACQAJADAFAFQAGAFADAIQADAHAAALIAAA5IANAAIAAAUIgiAAIAAgLQgHAGgIAEQgHAEgKAAQgJAAgHgDgAgPAGQgFABgEADQgEACgCAEQgCAEAAAFQAAAFACADQACAEADACQADACAEABIAKABIAIgBIAHgCIAHgEIAFgFIAAgaIgXAAIgLABg");
	this.shape_23.setTransform(145.9,19.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgbBUQgKgEgIgHQgHgJgEgLQgFgMAAgOQAAgOAFgLQAEgKAHgIQAHgIALgEQAKgEANAAQAIAAAGACQAHABAHAFIAAgtIgQAAIAAgSIAlAAIAACZIARAAIAAAUIgmAAIAAgKQgGAGgIADQgHAEgIAAQgMAAgKgFgAgRgLQgHADgEAFQgFAFgDAHQgDAIAAAKQAAAKADAJQADAHAEAGQAFAGAHACQAGAEAJAAQAIAAAGgEQAGgCAGgGIAAhAQgGgEgHgDQgHgCgHAAQgHABgHACg");
	this.shape_24.setTransform(127.9,16.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgTA5QgKgDgHgIQgHgIgEgLQgEgMAAgPQAAgMADgLQAEgLAHgJQAGgHALgFQAKgGAMAAQAOAAAIAFQAJAEAGAGQAFAHADAIQADAJABAIIABAJIAAAHIhTAAIABAJIACAIQAEAMAJAFQAKAGAKAAQAJAAAJgDQAIgCAKgGIAIAPQgLAHgMAEQgLAFgNAAQgLAAgKgFgAAegNIgCgMQgCgGgDgEQgEgEgFgCQgFgCgIAAQgGAAgGACQgFACgEAEQgEAEgCAFQgDAGgBAHIA8AAg");
	this.shape_25.setTransform(113.8,19.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgTA5QgKgDgHgIQgHgIgEgLQgEgMAAgPQAAgMADgLQAEgLAHgJQAGgHALgFQAKgGAMAAQAOAAAIAFQAJAEAGAGQAFAHADAIQADAJABAIIABAJIAAAHIhTAAIABAJIACAIQAEAMAJAFQAKAGAKAAQAJAAAJgDQAIgCAKgGIAIAPQgLAHgMAEQgLAFgNAAQgLAAgKgFgAAegNIgCgMQgCgGgDgEQgEgEgFgCQgFgCgIAAQgGAAgGACQgFACgEAEQgEAEgCAFQgDAGgBAHIA8AAg");
	this.shape_26.setTransform(100.6,19.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AALA7IAAgTIARAAIAAg0QgBgOgGgGQgHgHgNAAQgGAAgIADIgNAJIAABDIAQAAIAAATIg2AAIAAgTIAQAAIAAhNIgQAAIAAgTIAlAAIAAAOIAIgHIAJgFIAKgDIAJgBQAJAAAIACQAHADAFAFQAGAFACAJQADAIAAALIAAA3IAQAAIAAATg");
	this.shape_27.setTransform(86.7,19.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgXA5QgHgDgFgFQgFgFgDgJQgDgIAAgLIAAg3IgPAAIAAgTIAlAAIAABHQAAAOAHAHQAFAGAMAAQAGAAAHgCQAIgDAHgEIAAhGIgQAAIAAgTIAmAAIAABgIANAAIAAATIgiAAIAAgLQgIAHgJADQgKADgJAAQgJAAgHgCg");
	this.shape_28.setTransform(65.8,19.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgXA5QgKgFgIgHQgHgJgFgLQgEgMAAgNQAAgNAEgMQAFgLAHgIQAIgIALgEQALgFALAAQANAAALAFQALAEAHAIQAIAIAEALQAEAMAAANQAAANgEAMQgEALgIAIQgHAIgLAFQgLAEgNABQgMgBgLgEgAgNgoQgGADgFAFQgFAGgDAIQgDAJAAAJQAAAKADAIQADAIAFAFQAFAHAGACQAHAEAGAAQAIAAAHgEQAGgDAFgFQAFgGADgIQADgIAAgKQAAgJgDgJQgDgIgFgGQgEgFgHgDQgHgCgIgBQgGABgHACg");
	this.shape_29.setTransform(51.9,19.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgbBVIAAgTIAPAAIAAg8IgthHIgNAAIAAgTIA3AAIAAATIgQAAIAfA3IAig3IgRAAIAAgTIA3AAIAAATIgPAAIgvBIIAAA7IARAAIAAATg");
	this.shape_30.setTransform(37.7,16.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(16.8,1,241.6,57.6), null);


(lib.shaker = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHCDIgHgFIgFgIIgCgIIACgIIAFgHIAHgFIAIgBIAIABIAGAFIAFAHIABAIIgBAIIgFAIIgGAFIgIABgAgOA+IgHjBIAqAAIgGDBg");
	this.shape.setTransform(164.8,21.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgWCAIgHgFIgEgHIgDgIIADgIIAEgHIAHgFIAJgCIAIACIAGAFIAEAHIACAIIgCAIIgEAHIgGAFIgIACgAgcBIIABgdQABgMAEgKQADgKAGgIIAQgPIAQgNIAMgKQAFgGADgGQACgGAAgIQAAgIgCgHQgDgHgFgFQgFgGgHgDQgIgDgHAAQgNAAgJAEQgIAFgGAHQgFAGgDAIIgCAMIgegCQACgOAFgMQAGgNAKgJQAKgKAOgFQAOgGAPAAQARAAAMAGQANAFAJAJQAIAJAFANQAFAMAAANQAAARgJAOQgJAOgQAMIgSANQgKAJgFANQgEAMAAAJIgBAVg");
	this.shape_1.setTransform(150.8,21.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AARBXIAAgcIAYAAIAAhOQAAgTgKgKQgKgLgTAAQgKAAgLAFQgLAGgKAHIAABkIAZAAIAAAcIhRAAIAAgcIAYAAIAAhyIgYAAIAAgcIA3AAIAAAUIAMgKIANgHIAOgFIAPgBQAOAAALADQALAEAIAIQAIAHAEANQAEAMAAARIAABRIAYAAIAAAcg");
	this.shape_2.setTransform(130.2,25.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbBVQgPgGgMgMQgKgLgGgRQgGgRAAgWQAAgSAFgRQAFgQALgMQAKgMAPgIQAPgHATAAQATAAANAGQANAGAJAKQAHAJAFANQAEAMACANIABANIAAAMIh7AAIABANIADAMQAHAQANAJQANAIARAAQANAAANgEQAMgDAPgIIAMAVQgRALgRAGQgRAGgSAAQgRAAgOgGgAAsgTIgDgSQgDgIgEgGQgFgGgIgEQgIgDgMAAQgJAAgIADQgIADgGAGQgGAGgDAIQgDAIgCALIBYAAg");
	this.shape_3.setTransform(108.6,26.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AARCBIAAgcIAXAAIAAhPQAAgUgKgJQgKgKgTAAQgJAAgLAFQgLAFgKAHIAABlIAZAAIAAAcIhSAAIAAgcIAaAAIAAjJIgXAAIAAgcIA2AAIAABpIABAAIALgIIAMgIIAOgEIAOgCQAOAAALAEQALAEAIAIQAHAHAFANQAEALAAAQIAABTIAaAAIAAAcg");
	this.shape_4.setTransform(88.4,21.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAnBXIgniIIgmCIIgdAAIgviRIgOAAIAAgcIA2AAIAAAcIgIAAIAeBtIApiJIAZAAIAoCJIAfhtIgKAAIAAgcIA2AAIAAAcIgOAAIgwCRg");
	this.shape_5.setTransform(63,26.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag1B9IAAgdIAVAAIASguIg5iRIgOAAIAAgdIBBAAIAAAdIgUAAIAoBtIAphtIgUAAIAAgdIBBAAIAAAdIgSAAIhLC/IAWAAIAAAdg");
	this.shape_6.setTransform(31.9,30);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgQB/QgLgEgIgGIAAALIgeAAIAAjlIgZAAIAAgcIA3AAIAABkQALgIANgFQAMgFAOAAQARAAAOAGQAOAHALALQAKALAFAQQAFAQAAATQABAVgHARQgGAQgLAMQgLAMgPAHQgQAGgSABQgMgBgMgDgAgQgPQgLAFgIAJIAABbQAFAGALAEQAKAEAPAAQAKAAAKgEQAKgEAIgIQAHgIAEgMQAFgMAAgQQAAgPgFgLQgEgLgGgHQgIgIgKgEQgKgEgKAAQgLAAgMAFg");
	this.shape_7.setTransform(12.1,21.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.shaker, new cjs.Rectangle(0,0,172.7,45.1), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgbAvQgGgCgEgDIgEgGIgDgIQgBgEAAgGIACgMIAJgmIgNAAIADgPIAgAAIgLAvQgFARAEAIQAEAIAMAAQAFAAAEgCIAHgEIAGgIIAMgzIgNAAIAEgPIAfAAIgSBOIAOAAIgEAQIggAAIACgKIgGAGIgGADIgHACIgGAAQgHAAgFgBg");
	this.shape.setTransform(181.9,24.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgXAvQgIgEgGgFQgGgGgDgIQgDgIAAgJQAAgIACgGQACgIAEgHQADgFAGgGQAFgFAFgEQAHgDAHgDQAHgCAGAAQAKABAIADQAIADAGAGQAGAGAEAIQADAIAAAJQAAAHgCAHQgCAHgEAHQgDAGgGAGQgFAFgGAEQgGADgHACQgIACgGAAQgJAAgJgDgAgHgfQgHAEgFAFQgFAFgDAIQgDAHAAAHQAAAHACAFQACAGADADQAEAEAFACQAEACAGAAQAGAAAHgDQAFgDAGgFQAEgGAEgHQADgHAAgIQgBgHgBgEQgCgGgEgDQgEgEgEgCQgFgCgGAAQgFAAgGACg");
	this.shape_1.setTransform(170.2,24.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag3BGIAEgRIAJAAIARgaIgKhQIgJAAIADgPIAjAAIgDAPIgIAAIAGA6IAlg6IgIAAIAEgPIAiAAIgDAPIgIAAIhEBqIAKAAIgEARg");
	this.shape_2.setTransform(159.3,26.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgoAwIAThOIgTAAIAFgQIAjAAIgDANIAFgGIAGgEIAHgDIAHgBIAGAAIAFAAIAHABIgFAaIgTAAIADgLQgKAAgGAEQgFAFgEAHIgLAvIAQAAIgEAQg");
	this.shape_3.setTransform(145.2,24.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbAvQgHgDgFgFQgFgGgDgHQgDgHAAgIQAAgNAFgLQAFgLAHgIQAJgIAKgEQALgFAMAAQAHAAAFACQAGACAFAEIABgFIASAAIgSBOIAOAAIgDAQIgiAAIACgGQgHAEgFACQgGACgGAAQgIAAgHgDgAgGgeQgHADgFAFQgGAGgDAIQgDAIAAAJQAAAGABAFQABAEADADQADAEAFABQAEACAFAAIAHgBIAGgCIAFgDIAGgDIALgzQgCgDgFgCQgFgCgIAAQgHAAgGADg");
	this.shape_4.setTransform(133.7,24.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUAwQgIgDgFgGQgHgGgCgIQgEgIAAgKQAAgLAEgLQAEgKAIgIQAHgIAKgEQALgFALAAQAIAAAIADQAHADAFAGQAFAFADAGQACAHAAAHIAAAJIgBAHIhJAAIAAACIAAACQAAAGACAFQACAFADAEQADADAFACQAEACAGAAQAGAAAHgDQAGgDAFgFIAOAKIgHAHIgKAGQgFACgGABIgMACQgIAAgIgDgAgEggQgEABgEAEQgEADgDAEQgDAEgCAFIA1AAQAAgFgBgFQgCgEgDgDQgDgDgFgCQgEgBgFAAQgGAAgEACg");
	this.shape_5.setTransform(122.6,24.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAOAxIANg6QADgLgEgGQgFgFgKAAQgHAAgFADQgHADgGAFIgQBFIgSAAIAShPIgSAAIAEgQIAkAAIgDAKQAHgGAHgDQAIgDAIAAQAIAAAGADQAFACAEAEQAEAFABAHQABAGgCAJIgKAtIANAAIgDAQg");
	this.shape_6.setTransform(110.5,24.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgUAwQgIgDgFgGQgHgGgCgIQgEgIAAgKQAAgLAFgLQAEgKAHgIQAHgIALgEQAJgFALAAQAJAAAIADQAHADAFAGQAFAFACAGQADAHAAAHIAAAJIgCAHIhIAAIgBACIAAACQAAAGACAFQADAFADAEQADADAFACQAFACAFAAQAHAAAGgDQAHgDAEgFIAOAKIgHAHIgKAGQgFACgHABIgKACQgKAAgHgDgAgDggQgFABgEAEQgEADgDAEQgEAEgBAFIA1AAQAAgFgBgFQgCgEgDgDQgDgDgFgCQgEgBgFAAQgGAAgDACg");
	this.shape_7.setTransform(94.9,24.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAOAxIANg6QADgLgEgGQgFgFgKAAQgHAAgFADQgHADgGAFIgQBFIgSAAIAShPIgSAAIAEgQIAkAAIgDAKQAHgGAHgDQAIgDAIAAQAIAAAGADQAFACAEAEQAEAFABAHQABAGgCAJIgKAtIANAAIgDAQg");
	this.shape_8.setTransform(82.8,24.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgXAvQgHgEgGgFQgHgGgDgIQgDgIAAgJQAAgIACgGQACgIADgHQAEgFAGgGQAEgFAGgEQAHgDAHgDQAHgCAGAAQAKABAIADQAIADAGAGQAGAGAEAIQADAIAAAJQAAAHgDAHQgCAHgDAHQgDAGgGAGQgFAFgGAEQgGADgHACQgIACgGAAQgJAAgJgDgAgHgfQgHAEgFAFQgFAFgDAIQgDAHAAAHQAAAHACAFQACAGADADQAEAEAEACQAFACAGAAQAGAAAHgDQAGgDAFgFQAFgGADgHQACgHAAgIQAAgHgBgEQgCgGgEgDQgDgEgFgCQgFgCgGAAQgFAAgGACg");
	this.shape_9.setTransform(70.9,24.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AggBFQgHgDgFgFQgFgGgDgHQgDgIAAgJQAAgMAEgLQAFgKAIgIQAHgIALgEQAKgFALAAQAHAAAHACIALAGIAIglIgQAAIAEgQIAiAAIgdB/IAQAAIgEAQIgiAAIABgGIgKAFQgGADgGAAQgIAAgIgEgAgNgIQgHADgFAFQgFAFgDAIQgDAHAAAKQAAAGACAFQABAFAEADQADAEAEACQAFACAFAAQAGAAAGgDQAFgDAFgFIAMgwQgDgEgGgCQgFgCgIAAQgGAAgHACg");
	this.shape_10.setTransform(55.3,22.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAOAxIANg6QADgLgEgGQgFgFgKAAQgHAAgFADQgHADgGAFIgQBFIgSAAIAShPIgSAAIAEgQIAkAAIgDAKQAHgGAHgDQAIgDAIAAQAIAAAGADQAFACAEAEQAEAFABAHQABAGgCAJIgKAtIANAAIgDAQg");
	this.shape_11.setTransform(42.7,24.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgXBHIAThPIgSAAIAFgQIAiAAIgSBPIAPAAIgDAQgAAGguIgDgDIgDgEIAAgFIAAgEIADgEIADgDIAGgBIAEABIAEADIACAEIABAEIgBAFIgCAEIgEADIgEABg");
	this.shape_12.setTransform(33.4,22.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgxBfIAdh7IgUAAIAEgPIATAAIAEgRQACgKAEgGQAEgGAEgEQAFgEAGgCQAGgCAIAAIAIABIAGABIAGACIAEACIgKAOIgGgCIgJgBQgIAAgFADQgFAFgCAKIgEAQIAaAAIgEAPIgZAAIgcB7g");
	this.shape_13.setTransform(27.5,24.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(1,1,1).p("A1DjFMAqHAAAIAAGLMgqHAAAg");
	this.shape_14.setTransform(103.5,23);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(-32.2,2.2,271.5,41.6), null);


(lib.doclogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Tween2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(142,30);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.doclogo, new cjs.Rectangle(0,0,286.2,60.3), null);


(lib.bywhen = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shaker();
	this.instance.parent = this;
	this.instance.setTransform(86.3,22.5,1,1,0,0,0,86.3,22.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bywhen, new cjs.Rectangle(0,0,172.7,45.1), null);


// stage content:
(lib._300x250_optom = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 8
	this.instance = new lib.cta();
	this.instance.parent = this;
	this.instance.setTransform(152.5,-33.5,1,1,0,0,0,105.5,22);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(311).to({_off:false},0).wait(1).to({regX:103.5,regY:22.9,x:150.5,y:-31.6},0).wait(1).to({y:-28.1},0).wait(1).to({y:-20.3},0).wait(1).to({y:-4.2},0).wait(1).to({y:24.7},0).wait(1).to({y:55.7},0).wait(1).to({y:78},0).wait(1).to({y:93.9},0).wait(1).to({y:105.8},0).wait(1).to({y:115},0).wait(1).to({y:122.3},0).wait(1).to({y:128.3},0).wait(1).to({y:133.2},0).wait(1).to({y:137.2},0).wait(1).to({y:140.4},0).wait(1).to({y:143.1},0).wait(1).to({y:145.3},0).wait(1).to({y:147},0).wait(1).to({y:148.3},0).wait(1).to({y:149.3},0).wait(1).to({y:149.9},0).wait(1).to({y:150.3},0).wait(1).to({regX:105.5,regY:22,x:152.5,y:149.5},0).wait(27));

	// Layer 6
	this.instance_1 = new lib.doclogo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(142.1,-95.3,1,1,0,0,0,143.1,30.2);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(311).to({_off:false},0).wait(1).to({regY:30.1,y:-94.4},0).wait(1).to({y:-90.9},0).wait(1).to({y:-83},0).wait(1).to({y:-66.9},0).wait(1).to({y:-37.7},0).wait(1).to({y:-6.6},0).wait(1).to({y:15.9},0).wait(1).to({y:31.8},0).wait(1).to({y:43.7},0).wait(1).to({y:53},0).wait(1).to({y:60.4},0).wait(1).to({y:66.4},0).wait(1).to({y:71.3},0).wait(1).to({y:75.3},0).wait(1).to({y:78.6},0).wait(1).to({y:81.3},0).wait(1).to({y:83.4},0).wait(1).to({y:85.2},0).wait(1).to({y:86.5},0).wait(1).to({y:87.4},0).wait(1).to({y:88.1},0).wait(1).to({y:88.5},0).wait(1).to({regY:30.2,y:88.7},0).wait(27));

	// Layer 5
	this.instance_2 = new lib.Symbol3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(364,68,1,1,0,0,0,221.8,32.4);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(182).to({_off:false},0).wait(37).to({y:67},0).wait(1).to({regX:14.1,regY:87.6,x:156.3,y:121.9},0).wait(1).to({y:120.7},0).wait(1).to({y:117.4},0).wait(1).to({y:111.9},0).wait(1).to({y:108.2},0).wait(1).to({y:106.1},0).wait(1).to({y:104.8},0).wait(1).to({y:104},0).wait(1).to({y:103.5},0).wait(1).to({y:103.3},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:48},0).wait(75).to({regX:14.1,regY:87.6,x:156.3,y:103.6},0).wait(1).to({y:104.8},0).wait(1).to({y:107.1},0).wait(1).to({y:111},0).wait(1).to({y:116.9},0).wait(1).to({y:126},0).wait(1).to({y:140.6},0).wait(1).to({y:165},0).wait(1).to({y:199.2},0).wait(1).to({y:226},0).wait(1).to({y:242.5},0).wait(1).to({y:253},0).wait(1).to({y:260},0).wait(1).to({y:264.7},0).wait(1).to({y:267.9},0).wait(1).to({y:269.8},0).wait(1).to({y:270.9},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:216},0).to({_off:true},1).wait(38));

	// Layer 4
	this.instance_3 = new lib.bywhen();
	this.instance_3.parent = this;
	this.instance_3.setTransform(653.5,72.6,4,4,6,0,0,86.5,22.7);
	this.instance_3._off = true;

	this.instance_4 = new lib.Symbol5();
	this.instance_4.parent = this;
	this.instance_4.setTransform(364,60.8,1,1,0,0,0,221.8,17.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(93).to({_off:false},0).wait(1).to({regX:84.9,regY:25.5,scaleX:3.94,scaleY:3.94,rotation:5.7,x:634.7,y:82.2},0).wait(1).to({scaleX:3.75,scaleY:3.75,rotation:4.9,x:602,y:79.8},0).wait(1).to({scaleX:3.46,scaleY:3.46,rotation:3.7,x:550.3,y:75.9},0).wait(1).to({scaleX:3.08,scaleY:3.08,rotation:2,x:483.9,y:70.8},0).wait(1).to({scaleX:2.65,scaleY:2.65,rotation:0.2,x:408.7,y:65.1},0).wait(1).to({scaleX:2.21,scaleY:2.21,rotation:-1.7,x:331.9,y:59},0).wait(1).to({scaleX:1.81,scaleY:1.81,rotation:-3.4,x:261.2,y:53.5},0).wait(1).to({scaleX:1.49,scaleY:1.49,rotation:-4.8,x:204.1,y:49},0).wait(1).to({scaleX:1.27,scaleY:1.27,rotation:-5.7,x:166.8,y:46.1},0).wait(1).to({regX:86.3,regY:22.6,scaleX:1.2,scaleY:1.2,rotation:-6,x:155.3,y:41.6},0).to({_off:true},79).wait(179));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(219).to({_off:false},0).to({alpha:1},16).wait(70).to({regX:9.4,regY:99.6,x:151.6,y:143},0).wait(1).to({y:144.2},0).wait(1).to({y:146.4},0).wait(1).to({y:150},0).wait(1).to({y:155.7},0).wait(1).to({y:164.4},0).wait(1).to({y:178.3},0).wait(1).to({y:201.5},0).wait(1).to({y:234.1},0).wait(1).to({y:259.6},0).wait(1).to({y:275.3},0).wait(1).to({y:285.3},0).wait(1).to({y:292},0).wait(1).to({y:296.5},0).wait(1).to({y:299.5},0).wait(1).to({y:301.4},0).wait(1).to({y:302.3},0).wait(1).to({regX:221.8,regY:17.7,x:364,y:220.8},0).to({_off:true},1).wait(38));

	// Layer 2
	this.instance_5 = new lib.Symbol1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-146.6,45.8,1,1,0,0,0,136.3,32.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({regX:137.7,regY:31.9,x:-133.8,y:45.4},0).wait(1).to({x:-119.5,y:45.6},0).wait(1).to({x:-100.9,y:45.8},0).wait(1).to({x:-75.7,y:46.2},0).wait(1).to({x:-41.6,y:46.6},0).wait(1).to({x:-2.6,y:47.2},0).wait(1).to({x:30.3,y:47.6},0).wait(1).to({x:54.4,y:47.9},0).wait(1).to({x:72.4,y:48.2},0).wait(1).to({x:86.2,y:48.4},0).wait(1).to({x:97.3,y:48.5},0).wait(1).to({x:106.3,y:48.6},0).wait(1).to({x:113.8,y:48.8},0).wait(1).to({x:120.1},0).wait(1).to({x:125.4,y:48.9},0).wait(1).to({x:130,y:49},0).wait(1).to({x:133.8},0).wait(1).to({x:137.1,y:49.1},0).wait(1).to({x:139.9},0).wait(1).to({x:142.3},0).wait(1).to({x:144.3,y:49.2},0).wait(1).to({x:146},0).wait(1).to({x:147.4},0).wait(1).to({x:148.5},0).wait(1).to({x:149.3},0).wait(1).to({x:150},0).wait(1).to({x:150.4},0).wait(1).to({x:150.7},0).wait(1).to({regX:136.3,regY:32.4,x:149.4,y:49.8},0).wait(63).to({regX:137.7,regY:31.9,scaleX:1.01,scaleY:1.01,x:148.7,y:49.4},0).wait(1).to({scaleX:1.02,scaleY:1.02,x:141.9,y:49.9},0).wait(1).to({scaleX:1.06,scaleY:1.06,x:128.7,y:51},0).wait(1).to({scaleX:1.12,scaleY:1.12,x:106.8,y:52.8},0).wait(1).to({scaleX:1.21,scaleY:1.21,x:72.5,y:55.4},0).wait(1).to({scaleX:1.35,scaleY:1.35,x:21,y:59.6},0).wait(1).to({scaleX:1.55,scaleY:1.55,x:-52,y:65.3},0).wait(1).to({scaleX:1.79,scaleY:1.79,x:-138.9,y:72.2},0).wait(1).to({scaleX:2.01,scaleY:2.01,x:-218.2,y:78.5},0).wait(1).to({scaleX:2.17,scaleY:2.17,x:-279,y:83.3},0).wait(1).to({scaleX:2.29,scaleY:2.29,x:-323.3,y:86.8},0).wait(1).to({scaleX:2.38,scaleY:2.38,x:-355.2,y:89.4},0).wait(1).to({scaleX:2.44,scaleY:2.44,x:-378.3,y:91.2},0).wait(1).to({scaleX:2.49,scaleY:2.49,x:-394.7,y:92.5},0).wait(1).to({scaleX:2.52,scaleY:2.52,x:-406,y:93.4},0).wait(1).to({scaleX:2.54,scaleY:2.54,x:-413.2,y:94},0).wait(1).to({scaleX:2.55,scaleY:2.55,x:-417.2,y:94.3},0).wait(1).to({regX:136.2,regY:32.4,scaleX:2.55,scaleY:2.55,x:-422.1,y:95.8},0).to({_off:true},163).wait(89));

	// Layer 3
	this.instance_6 = new lib.Symbol2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(784,51,0.6,0.6,0,0,0,112.1,112.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({regX:-357.1,regY:371.3,x:489.2,y:206},0).wait(1).to({x:472.5},0).wait(1).to({x:450.7},0).wait(1).to({x:421.3},0).wait(1).to({x:381.4},0).wait(1).to({x:335.9},0).wait(1).to({x:297.4},0).wait(1).to({x:269.2},0).wait(1).to({x:248.2},0).wait(1).to({x:232},0).wait(1).to({x:219},0).wait(1).to({x:208.5},0).wait(1).to({x:199.7},0).wait(1).to({x:192.4},0).wait(1).to({x:186.2},0).wait(1).to({x:180.9},0).wait(1).to({x:176.3},0).wait(1).to({x:172.5},0).wait(1).to({x:169.2},0).wait(1).to({x:166.4},0).wait(1).to({x:164},0).wait(1).to({x:162.1},0).wait(1).to({x:160.5},0).wait(1).to({x:159.2},0).wait(1).to({x:158.2},0).wait(1).to({x:157.4},0).wait(1).to({x:156.9},0).wait(1).to({x:156.6},0).wait(1).to({regX:112.1,regY:112.9,x:438,y:51},0).wait(63).to({regX:-357.1,regY:371.3,scaleX:0.6,scaleY:0.6,x:156.5,y:206.2},0).wait(1).to({scaleX:0.61,scaleY:0.61,x:156.6,y:206.9},0).wait(1).to({scaleX:0.61,scaleY:0.61,x:156.7,y:208.1},0).wait(1).to({scaleX:0.63,scaleY:0.63,x:156.9,y:210},0).wait(1).to({scaleX:0.65,scaleY:0.65,x:157.2,y:213.1},0).wait(1).to({scaleX:0.68,scaleY:0.68,x:157.7,y:217.7},0).wait(1).to({scaleX:0.72,scaleY:0.72,x:158.3,y:224.2},0).wait(1).to({scaleX:0.78,scaleY:0.78,x:159.1,y:231.9},0).wait(1).to({scaleX:0.82,scaleY:0.82,x:159.8,y:239.1},0).wait(1).to({scaleX:0.86,scaleY:0.86,x:160.3,y:244.5},0).wait(1).to({scaleX:0.89,scaleY:0.89,x:160.7,y:248.4},0).wait(1).to({scaleX:0.91,scaleY:0.91,x:161,y:251.3},0).wait(1).to({scaleX:0.92,scaleY:0.92,x:161.2,y:253.4},0).wait(1).to({scaleX:0.93,scaleY:0.93,x:161.3,y:254.8},0).wait(1).to({scaleX:0.94,scaleY:0.94,x:161.5,y:255.8},0).wait(1).to({scaleX:0.94,scaleY:0.94,y:256.5},0).wait(1).to({scaleX:0.94,scaleY:0.94,x:161.6,y:256.8},0).wait(1).to({regX:112.4,regY:112.7,x:604.2,y:13.1},0).wait(1).to({regX:-357.1,regY:371.3,x:161.3,y:257.1},0).wait(1).to({y:257},0).wait(1).to({x:161.4},0).wait(1).to({y:256.9},0).wait(1).to({x:161.5,y:256.7},0).wait(1).to({x:161.6,y:256.5},0).wait(1).to({x:161.8,y:256.2},0).wait(1).to({x:161.9,y:255.9},0).wait(1).to({x:162,y:255.6},0).wait(1).to({x:162.1,y:255.4},0).wait(1).to({x:162.2,y:255.3},0).wait(1).to({x:162.3,y:255.2},0).wait(1).to({y:255.1},0).wait(1).to({regX:112.4,regY:112.8,x:605.3,y:11.2},0).wait(1).to({regX:-357.1,regY:371.3,x:162.3,y:255.1},0).wait(4).to({x:162.2,y:255.2},0).wait(2).to({x:162.1,y:255.3},0).wait(1).to({x:162,y:255.4},0).wait(1).to({x:161.9,y:255.5},0).wait(1).to({x:161.8,y:255.6},0).wait(1).to({x:161.7,y:255.7},0).wait(1).to({x:161.6,y:255.8},0).wait(2).to({x:161.5,y:255.9},0).wait(1).to({x:161.4,y:256},0).wait(4).to({regX:112.4,regY:112.7,x:604.2,y:12.1},0).wait(1).to({regX:-357.1,regY:371.3,x:161.3,y:256.1},0).wait(2).to({y:256},0).wait(1).to({x:161.2},0).wait(1).to({y:255.9},0).wait(1).to({x:161.1,y:255.8},0).wait(1).to({y:255.7},0).wait(1).to({x:161,y:255.5},0).wait(1).to({x:160.9,y:255.3},0).wait(1).to({x:160.8,y:255.1},0).wait(1).to({x:160.7,y:254.9},0).wait(1).to({x:160.6,y:254.7},0).wait(1).to({x:160.5,y:254.5},0).wait(1).to({x:160.4,y:254.4},0).wait(1).to({y:254.3},0).wait(1).to({x:160.3,y:254.2},0).wait(1).to({y:254.1},0).wait(2).to({regX:112.4,regY:112.7,x:603.3,y:10.1},0).wait(1).to({regX:-357.1,regY:371.3,x:160.4,y:254.1},0).wait(3).to({x:160.5,y:254.2},0).wait(2).to({x:160.6},0).wait(1).to({x:160.7,y:254.3},0).wait(1).to({x:160.9,y:254.4},0).wait(1).to({x:161.1,y:254.5},0).wait(1).to({x:161.3,y:254.6},0).wait(1).to({x:161.5,y:254.7},0).wait(1).to({x:161.7},0).wait(1).to({x:161.8,y:254.8},0).wait(1).to({x:162,y:254.9},0).wait(1).to({x:162.1,y:255},0).wait(1).to({x:162.2},0).wait(1).to({x:162.3,y:255.1},0).wait(3).to({regX:112.4,regY:112.8,x:605.3,y:11.2},0).to({_off:true},1).wait(179));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E88386").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(361));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-116.2,125,918.6,330.5);
// library properties:
lib.properties = {
	id: 'DCCA7DDDDB474A279771A470BF7560D2',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/300x250_optom_atlas_.png", id:"300x250_optom_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['DCCA7DDDDB474A279771A470BF7560D2'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;