(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"728x90_cupcake_atlas_", frames: [[0,202,318,67],[0,0,250,200]]}
];


// symbols:



(lib.docBC = function() {
	this.spriteSheet = ss["728x90_cupcake_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.volcanoman = function() {
	this.spriteSheet = ss["728x90_cupcake_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.docBC();
	this.instance.parent = this;
	this.instance.setTransform(-159,-33);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-159,-33,318,67);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.docBC();
	this.instance.parent = this;
	this.instance.setTransform(-159,-33);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-159,-33,318,67);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAQIgFgFIgEgFIgCgGIACgGIAEgFIAFgEIAGAAIAGAAIAFAEIAEAFIABAGIgBAGIgEAFIgFAFIgGABg");
	this.shape.setTransform(438.6,25.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgFgGQgEgFgCgHQgCgJgBgMIABhIIgVAAIAAgTIAVAAIAAgfIAWgLIAAAqIAfAAIAAATIgfAAIAABLQgBAIACAEQACAGAEABQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHABgJAAQgIAAgGgCg");
	this.shape_1.setTransform(431,18.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgZAgIAYhHIAbALIggBDg");
	this.shape_2.setTransform(422.2,11.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QAAgPgIgHQgHgJgPAAQgHAAgIAEQgJAFgHAFIAABMIASAAIAAAWIg9AAIAAgWIATAAIAAhXIgTAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQAKAAAJADQAIADAHAGQAFAGAEAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_3.setTransform(409.8,20.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXBBQgJgFgGgIIgNAAIAAgWIAaAAQAAAFADAEQACAEAEACQAEADAEABIAJABIAKgBIAIgEQAEgCACgDQABgEAAgEQAAgGgDgFQgFgEgKgEIgYgJQgPgEgHgJQgIgIAAgNQAAgIADgHQAEgIAFgFQAGgFAJgDQAIgDALAAQANAAAKAEQAJAEAIAKIAMAAIAAAWIgaAAQAAgGgCgDQgDgEgEgDIgJgDIgIgBIgJABIgIADQgCACgCAEQgCADAAADQAAAHAEAEQAEAEAJADIAYAJQARAFAIAJQAHAJAAANQAAAJgEAHQgDAIgHAFQgGAFgJADQgJADgLAAQgOAAgKgFg");
	this.shape_4.setTransform(394.8,20.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgFhAIgGgEIgDgFIgCgHIACgGIADgFIAGgEIAFgBIAGABIAGAEIADAFIABAGIgBAHIgDAFIgGAEIgGABg");
	this.shape_5.setTransform(384.6,17.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AA4BDIAAgWIATAAIAAg7QAAgPgIgHQgHgJgPAAQgJAAgJAEQgIAFgGAGIAABLIASAAIAAAWIg8AAIAAgWIASAAIAAg7QAAgPgIgHQgIgJgOAAQgIAAgIAEQgJAFgIAFIAABMIATAAIAAAWIg+AAIAAgWIATAAIAAhXIgTAAIAAgVIArAAIAAAPIAAAAIAJgHIAKgGIALgDIAMgCQAOAAAKAFQAKAGAFALIAKgJIALgHIAMgEQAHgCAGAAQALAAAIADQAJADAGAGQAGAGADAJQAEAKgBAMIAAA+IASAAIAAAWg");
	this.shape_6.setTransform(361.6,20.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AghBCQgIgDgFgFQgGgGgDgGQgDgHAAgJQAAgHACgHQADgGAEgGQAEgEAFgDIAMgEIAMgEIAMAAIAOAAIAMACIAAgLQAAgHgDgFQgCgFgDgEQgEgDgEgBQgGgCgGAAIgLABIgKACIgJADIgHADIgHgQIAKgGIAMgEIAMgDIANgBQAKAAAJADQAKACAGAGQAHAGADAJQAEAJgBAMIAABBIAPAAIAAAVIgmAAIAAgLQgIAHgJAEQgIAEgMAAQgJAAgJgDgAgRAHQgGACgEADQgEACgDAFQgCAEAAAGQAAAFACAEQACADAEADQADACAFACIAKABIAKgBIAIgDIAIgFIAGgFIAAgeIgbAAQgGAAgGACg");
	this.shape_7.setTransform(341.3,20.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AATBCIAAgWIAHAAIgaghIgYAhIAGAAIAAAWIgsAAIAAgWIALAAIAoguIglgpIgOAAIAAgWIAsAAIAAAWIgFAAIAXAfIAZgfIgHAAIAAgWIAsAAIAAAWIgLAAIglArIAnAsIAKAAIAAAWg");
	this.shape_8.setTransform(327.5,20.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIhdAAIABAKIACAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgNAAgLgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgEAFQgEAEgEAGQgCAHgBAIIBDAAg");
	this.shape_9.setTransform(312.8,20.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgEgGQgFgFgCgHQgCgJAAgMIAAhIIgVAAIAAgTIAVAAIAAgfIAWgLIAAAqIAfAAIAAATIgfAAIgBBLQAAAIACAEQACAGAEABQAEACAFAAIAJgBIAJgDIAGAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_10.setTransform(295.3,18.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgXBBQgJgFgGgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQADADAGABIAJABIAJgBIAIgEQADgCACgDQACgEABgEQgBgGgEgFQgEgEgJgEIgYgJQgQgEgIgJQgHgIAAgNQAAgIAEgHQACgIAHgFQAFgFAIgDQAJgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgDgDQgCgEgEgDIgIgDIgJgBIgJABIgHADQgEACgCAEQgBADAAADQAAAHAEAEQAEAEAKADIAYAJQAQAFAHAJQAIAJAAANQAAAJgDAHQgEAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_11.setTransform(284.1,20.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgGhAIgFgEIgDgFIgBgHIABgGIADgFIAFgEIAGgBIAGABIAFAEIAEAFIACAGIgCAHIgEAFIgFAEIgGABg");
	this.shape_12.setTransform(273.8,17.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgvBCIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAAASIAFgIIAGgGIAIgEQAEgBAFAAIANAAIAMAAIAAAdIgZAAIAAgJQgEAAgFACQgEACgEADQgEADgCAFQgCAFgCAHIAAA+IAWAAIAAAWg");
	this.shape_13.setTransform(263.4,20.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgFgGQgEgFgDgHQgCgJAAgMIABhIIgVAAIAAgTIAVAAIAAgfIAXgLIAAAqIAeAAIAAATIgfAAIAABLQAAAIABAEQACAGAEABQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_14.setTransform(252.6,18.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIhdAAIABAKIACAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgNAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgEAFQgEAEgEAGQgCAHgBAIIBDAAg");
	this.shape_15.setTransform(239.9,20.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AA4BDIAAgWIASAAIAAg7QAAgPgHgHQgIgJgOAAQgJAAgIAEQgJAFgHAGIAABLIASAAIAAAWIg8AAIAAgWIATAAIAAg7QAAgPgIgHQgIgJgOAAQgIAAgJAEQgIAFgIAFIAABMIATAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIApAAIAAAPIABAAIAJgHIAKgGIALgDIALgCQAOAAALAFQAKAGAFALIAKgJIALgHIAMgEQAGgCAIAAQAKAAAJADQAIADAGAGQAGAGADAJQADAKABAMIAAA+IASAAIAAAWg");
	this.shape_16.setTransform(219.8,20.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_17.setTransform(198.9,20.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgEgGQgFgFgCgHQgCgJAAgMIAAhIIgVAAIAAgTIAVAAIAAgfIAWgLIAAAqIAfAAIAAATIgfAAIgBBLQAAAIADAEQABAGAEABQAEACAFAAIAJgBIAJgDIAGAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_18.setTransform(186.5,18.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhFBhIAAgWIATAAIAAiSIgTAAIAAgWIAqAAIAAALQAJgHAJgEQAJgDALAAQANAAALAEQAKAFAIAJQAIAJAEAMQAFAMAAAPQAAAQgFANQgFAMgJAJQgIAKgMAFQgMAFgOAAQgJAAgIgCIgPgFIAAAqIAVAAIAAAWgAgMhIQgIAEgHAGIAABGQAFAFAHADQAIAEALAAQAIAAAHgEQAIgDAGgGQAFgGAEgJQADgJAAgMQAAgLgDgJQgDgIgGgGQgFgGgIgDQgHgEgIAAQgJAAgIAEg");
	this.shape_19.setTransform(173.5,23.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_20.setTransform(157.9,20.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AANBDIAAgWIATAAIAAg7QAAgPgJgHQgHgJgOAAQgIAAgIAEQgIAFgIAFIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQALAAAIADQAJADAFAGQAHAGADAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_21.setTransform(135.9,20.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AghBCQgIgDgGgFQgFgGgEgGQgDgHAAgJQABgHACgHQADgGADgGQAEgEAGgDIALgEIANgEIAMAAIAPAAIAKACIABgLQAAgHgCgFQgCgFgEgEQgDgDgGgBQgFgCgGAAIgKABIgLACIgIADIgHADIgIgQIAKgGIAMgEIANgDIAMgBQALAAAJADQAIACAHAGQAGAGAEAJQADAJABAMIgBBBIAOAAIAAAVIgmAAIAAgLQgHAHgJAEQgIAEgMAAQgJAAgJgDgAgRAHQgGACgEADQgEACgCAFQgDAEAAAGQAAAFACAEQACADADADQAEACAFACIALABIAJgBIAIgDIAHgFIAGgFIAAgeIgaAAQgGAAgGACg");
	this.shape_22.setTransform(119.9,20.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgOBfIgOgDIgPgGQgGgDgGgFIAMgTIAJAGIAKAFIAMADIAMABQAJAAAHgCQAHgCAFgFQAFgFACgJQACgJAAgNIAAgCQgGAHgJADQgJAEgLAAQgMAAgMgEQgLgFgJgJQgIgJgEgNQgGgMAAgRQAAgPAGgMQAEgNAIgJQAJgJALgEQAMgFANAAQALAAAHACQAJACAHAFIAAgGIAYAAIAAB9QAAAfgPAQQgPAQgfAAgAgKhHQgHADgGAGQgFAGgEAIQgDAJAAALQAAAMADAJQAEAJAEAGQAGAGAIADQAIAEAIAAIAKgCIAJgCIAHgFIAFgFIAAhHQgGgGgJgCQgJgDgJAAQgGAAgIAEg");
	this.shape_23.setTransform(99.4,23.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QAAgPgIgHQgHgJgPAAQgHAAgIAEQgJAFgHAFIAABMIASAAIAAAWIg9AAIAAgWIATAAIAAhXIgTAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQAKAAAJADQAIADAHAGQAFAGAEAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_24.setTransform(83.6,20.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgFhAIgGgEIgDgFIgCgHIACgGIADgFIAGgEIAFgBIAGABIAGAEIADAFIABAGIgBAHIgDAFIgGAEIgGABg");
	this.shape_25.setTransform(70.9,17.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAtBjIg1g7IgRAAIAAAlIAKAAIAAAWIg4AAIAAgWIAWAAIAAiZIgXAAIAAgWIAvAAIAAAWIAABhIAWAAIAfgfIgIAAIAAgWIAyAAIAAAWIgRAAIgoAoIAsAvIAQAAIAAAWg");
	this.shape_26.setTransform(58.7,17.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_27.setTransform(42.4,20.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_28.setTransform(26.9,20.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhHBgIAAgWIASAAIAAiTIgSAAIAAgWIBWAAQAMAAAJAEQALAFAHAHQAIAIAFAKQAEAKAAAMQAAAMgHALQgHAKgNAGIAMAGQAFAFADAFQAEAFACAGQACAGAAAGQAAAMgEAKQgFALgIAIQgHAHgKAFQgLAEgLAAgAgcBKIAsAAQAGAAAFgDQAGgDADgFQAEgEADgHQACgGAAgGQAAgGgCgFQgCgFgFgEQgDgEgGgDQgFgCgGAAIgsAAgAgcgKIArAAQAGAAAFgDQAGgCADgEQAFgEACgGQACgFAAgGQAAgGgCgGQgCgGgFgFQgDgEgGgDQgFgDgGAAIgrAAg");
	this.shape_29.setTransform(11.1,17.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(0,0,443.6,35.4), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAQIgGgFIgDgFIgBgGIABgGIADgFIAGgEIAFAAIAGAAIAGAEIADAFIABAGIgBAGIgDAFIgGAFIgGABg");
	this.shape.setTransform(330.2,25.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgfBgQgLgFgJgJQgIgJgFgNQgFgNAAgRQAAgPAFgMQAFgMAIgJQAIgJAMgEQAMgFAOAAQAJAAAIACQAIACAHAFIAAgyIgSAAIAAgWIAqAAIAACuIATAAIAAAWIgrAAIAAgLQgGAHgJAEQgIADgKAAQgNAAgMgEgAgTgMQgIADgFAGQgGAFgDAIQgDAJAAALQAAAMADAJQADAKAFAGQAGAGAIADQAHAEAJAAQAKAAAHgDQAHgEAGgGIAAhIQgGgGgJgCQgIgDgIAAQgIAAgHAEg");
	this.shape_1.setTransform(319.4,17.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AguBCIAAgWIASAAIAAhWIgSAAIAAgWIApAAIAAASIAFgIIAHgGIAHgEQAEgBAFAAIAMAAIAMAAIAAAdIgYAAIAAgJQgEAAgEACQgFACgDADQgFADgCAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape_2.setTransform(305.2,20.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AghBCQgIgDgGgFQgFgGgEgGQgDgHAAgJQABgHACgHQADgGADgGQAEgEAGgDIALgEIANgEIAMAAIAPAAIAKACIABgLQAAgHgCgFQgCgFgEgEQgDgDgGgBQgFgCgGAAIgKABIgLACIgIADIgHADIgIgQIAKgGIAMgEIANgDIAMgBQALAAAJADQAIACAHAGQAHAGADAJQADAJABAMIgBBBIAOAAIAAAVIgmAAIAAgLQgHAHgJAEQgIAEgMAAQgJAAgJgDgAgRAHQgGACgEADQgEACgCAFQgDAEAAAGQAAAFACAEQACADADADQAEACAFACIALABIAJgBIAIgDIAHgFIAGgFIAAgeIgaAAQgGAAgGACg");
	this.shape_3.setTransform(291.8,20.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AANBjIAAgWIASAAIAAg8QAAgPgIgHQgIgIgOAAQgIAAgHAEQgJAEgHAFIAABNIATAAIAAAWIg/AAIAAgWIAUAAIAAiZIgSAAIAAgWIAqAAIAABRIABAAIAIgHIAKgFIAKgEIAKgBQALAAAIADQAJADAGAGQAFAGAEAJQADAIAAANIAAA/IAUAAIAAAWg");
	this.shape_4.setTransform(276.6,17.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXBBQgKgFgFgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQAEADAFABIAJABIAJgBIAIgEQAEgCABgDQADgEAAgEQgBgGgEgFQgEgEgJgEIgYgJQgQgEgIgJQgHgIAAgNQAAgIAEgHQACgIAHgFQAFgFAIgDQAJgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgDgDQgCgEgEgDIgIgDIgJgBIgJABIgHADQgDACgDAEQgBADAAADQAAAHAEAEQAEAEAJADIAZAJQAQAFAHAJQAIAJAAANQAAAJgDAHQgEAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_5.setTransform(255.8,20.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgGhAIgFgEIgEgFIgBgHIABgGIAEgFIAFgEIAGgBIAHABIAEAEIAEAFIACAGIgCAHIgEAFIgEAEIgHABg");
	this.shape_6.setTransform(245.6,17.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNBfIgQgDIgNgGQgHgDgHgFIAOgTIAIAGIALAFIALADIAMABQAIAAAIgCQAHgCAFgFQAEgFACgJQADgJAAgNIAAgCQgGAHgJADQgJAEgKAAQgNAAgLgEQgMgFgIgJQgJgJgFgNQgEgMAAgRQAAgPAEgMQAFgNAIgJQAJgJAMgEQALgFAOAAQAKAAAIACQAHACAIAFIAAgGIAXAAIAAB9QAAAfgOAQQgPAQgfAAgAgKhHQgHADgGAGQgFAGgDAIQgEAJAAALQAAAMADAJQADAJAGAGQAFAGAIADQAHAEAIAAIALgCIAJgCIAHgFIAFgFIAAhHQgGgGgJgCQgIgDgJAAQgIAAgHAEg");
	this.shape_7.setTransform(227.6,23.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AANBDIAAgWIATAAIAAg7QgBgPgHgHQgIgJgPAAQgGAAgJAEQgJAFgHAFIAABMIATAAIAAAWIg+AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIABAAIAJgHIAKgGIAKgDIALgCQAKAAAJADQAJADAFAGQAGAGAEAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_8.setTransform(211.8,20.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIArAAIAABsIATAAIAAAWgAgGhAIgFgEIgDgFIgBgHIABgGIADgFIAFgEIAGgBIAGABIAGAEIADAFIACAGIgCAHIgDAFIgGAEIgGABg");
	this.shape_9.setTransform(199.1,17.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgFgGQgEgFgDgHQgCgJAAgMIABhIIgVAAIAAgTIAVAAIAAgfIAXgLIAAAqIAeAAIAAATIgfAAIAABLQAAAIABAEQACAGAEABQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_10.setTransform(190,18.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QABgPgJgHQgHgJgOAAQgIAAgIAEQgJAFgHAFIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQALAAAIADQAJADAFAGQAHAGADAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_11.setTransform(176.5,20.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_12.setTransform(160,20.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgvBCIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAAASIAFgIIAGgGIAIgEQAEgBAFAAIANAAIAMAAIAAAdIgZAAIAAgJQgEAAgFACQgEACgEADQgEADgCAFQgCAFgCAHIAAA+IAWAAIAAAWg");
	this.shape_13.setTransform(146.8,20.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AggBCQgJgDgGgFQgFgGgDgGQgDgHAAgJQAAgHACgHQADgGAEgGQAEgEAFgDIAMgEIAMgEIAMAAIAOAAIAMACIAAgLQAAgHgDgFQgBgFgEgEQgEgDgEgBQgGgCgFAAIgMABIgKACIgJADIgHADIgHgQIAKgGIAMgEIAMgDIANgBQAKAAAJADQAKACAGAGQAHAGADAJQAEAJgBAMIAABBIAPAAIAAAVIgmAAIAAgLQgIAHgJAEQgIAEgLAAQgLAAgHgDgAgRAHQgGACgEADQgEACgDAFQgCAEAAAGQAAAFACAEQACADAEADQADACAFACIAKABIAKgBIAIgDIAIgFIAGgFIAAgeIgbAAQgGAAgGACg");
	this.shape_14.setTransform(133.5,20.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhEBgIAAgWIATAAIAAiTIgTAAIAAgWIBNAAQANAAALADQALAEAIAGQAIAHAEAJQAFAKAAANQAAAKgFAKQgEAJgIAHQgIAHgLADQgLAEgNAAIghAAIAABDIATAAIAAAWgAgYgNIAhAAQAHAAAHgCQAGgCAEgDQAEgEADgGQACgGAAgHQAAgOgIgIQgJgIgTAAIgeAAg");
	this.shape_15.setTransform(119.2,17.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(108.4,0,226.8,35.4), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.volcanoman();
	this.instance.parent = this;
	this.instance.setTransform(13,16,0.9,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(13,16,225,180), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgRBiIgFgEIgDgFIgCgHIACgGIADgFIAFgEIAGgBIAHABIAEAEIADAFIACAGIgCAHIgDAFIgEAEIgHABgAgWA3IABgWQABgKADgHQACgIAGgGIALgLIAMgKIAJgIIAGgIQACgFAAgHQABgFgDgGQgCgFgEgEQgEgEgFgDQgGgCgGAAQgIAAgIADQgGAEgEAFQgEAFgDAFIgCAKIgVgCQAAgKAEgKQAFgJAHgHQAIgIAKgEQALgEALAAQANAAAKAEQAKAEAGAHQAIAHADAJQADAKABAKQAAANgIAKQgGALgNAKIgOAJQgIAHgDAKQgDAJAAAHIgBAQg");
	this.shape.setTransform(289.6,46.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgvBCIAAgWIATAAIAAhWIgTAAIAAgWIArAAIAAASIAEgIIAGgGIAIgEQAEgBAFAAIAMAAIANAAIAAAdIgZAAIAAgJQgEAAgFACQgEACgEADQgEADgCAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape_1.setTransform(276.3,49.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgJgJQgIgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAGAIADAJQADAKABAKIABAJIAAAJIhdAAIABAKIABAJQAFANALAGQAKAHAMAAQALAAAJgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgNAAgLgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgEAFQgFAEgDAGQgCAHgBAIIBDAAg");
	this.shape_2.setTransform(262.5,49.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXBBQgKgFgFgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQAEADAFABIAJABIAJgBIAIgEQAEgCABgDQADgEAAgEQAAgGgFgFQgEgEgJgEIgYgJQgQgEgIgJQgHgIAAgNQAAgIAEgHQACgIAHgFQAFgFAIgDQAJgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgDgDQgCgEgEgDIgIgDIgJgBIgJABIgHADQgDACgDAEQgBADAAADQAAAHAEAEQAEAEAJADIAZAJQAQAFAHAJQAIAJAAANQAAAJgDAHQgEAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_3.setTransform(249.1,49.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgGhAIgFgEIgEgFIgBgHIABgGIAEgFIAFgEIAGgBIAHABIAEAEIAEAFIACAGIgCAHIgEAFIgEAEIgHABg");
	this.shape_4.setTransform(238.8,46.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AggBCQgIgDgHgFQgFgFgEgIQgCgHAAgHQgBgJADgGQACgHAFgEQAEgFAFgDIALgFIANgDIAMAAIAPAAIALACIAAgLQAAgHgCgFQgDgFgDgDQgEgEgFgCQgFgBgFAAIgMABIgKACIgJADIgGADIgIgQIAKgFIAMgFIANgDIAMgBQALAAAIADQAKADAGAFQAGAGAEAJQADAJAAAMIAABAIAOAAIAAAXIglAAIAAgNQgIAHgJAFQgIAEgLAAQgLAAgHgDgAgRAHQgGABgEAEQgEADgCADQgDAFAAAGQAAAFACAEQACAEADACQAEACAFACIAKACIAKgCIAIgDIAHgEIAHgGIAAgeIgbAAQgHABgFABg");
	this.shape_5.setTransform(227.2,49.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AguBCIAAgWIASAAIAAhWIgSAAIAAgWIApAAIAAASIAFgIIAHgGIAHgEQAEgBAFAAIANAAIALAAIAAAdIgYAAIAAgJQgEAAgEACQgFACgDADQgEADgDAFQgCAFgCAHIAAA+IAWAAIAAAWg");
	this.shape_6.setTransform(214.2,49.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgfBgQgLgFgJgJQgIgJgFgNQgFgNAAgRQAAgPAFgMQAFgMAIgJQAIgJAMgEQAMgFAOAAQAJAAAIACQAIACAHAFIAAgyIgSAAIAAgWIAqAAIAACuIATAAIAAAWIgrAAIAAgLQgGAHgJAEQgIADgKAAQgNAAgMgEgAgTgMQgIADgFAGQgGAFgDAIQgDAJAAALQAAAMADAJQADAKAFAGQAGAGAIADQAHAEAJAAQAKAAAHgDQAHgEAGgGIAAhIQgGgGgJgCQgIgDgIAAQgIAAgHAEg");
	this.shape_7.setTransform(200.2,46.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QAAgPgIgHQgHgIgPAAQgHAAgIADQgJAEgHAGIAABMIASAAIAAAWIg9AAIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAAAPIAAAAIAJgHIAKgFIALgFIALgBQAKAAAJADQAIADAHAGQAFAGAEAJQADAJAAANIAAA+IASAAIAAAWg");
	this.shape_8.setTransform(183.5,49.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgaBAQgIgDgGgGQgGgGgDgJQgDgKAAgNIAAg9IgSAAIAAgWIArAAIAABRQAAAPAHAIQAHAHANABQAHgBAIgDQAJgCAHgFIAAhPIgRAAIAAgWIAqAAIAABsIAPAAIAAAXIgnAAIAAgNQgJAHgKAEQgLAEgKAAQgKAAgIgDg");
	this.shape_9.setTransform(165.5,50);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgvBjIAAgWIAUAAIAAhaIgWAAIAAgTIAWAAIAAgUQAAgMADgIQADgJAGgFQAFgGAJgDQAGgDAKAAIAMABIAJACIAIACIAFACIgGARIgLgDQgGgCgIAAQgKAAgHAHQgEAGgBANIAAAVIAeAAIAAATIgeAAIAABaIAUAAIAAAWg");
	this.shape_10.setTransform(154.3,46.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgeBjIAAgWIATAAIAAiZIgTAAIAAgWIAqAAIAACvIATAAIAAAWg");
	this.shape_11.setTransform(138.4,46.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_12.setTransform(126.3,49.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_13.setTransform(110.7,49.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AANBjIAAgWIASAAIAAg8QAAgPgIgHQgIgIgOAAQgIAAgIAEQgIAEgHAFIAABNIATAAIAAAWIg/AAIAAgWIAUAAIAAiZIgSAAIAAgWIAqAAIAABRIABAAIAIgHIAKgFIAKgEIAKgBQALAAAIADQAJADAGAGQAGAGADAJQADAIAAANIAAA/IAUAAIAAAWg");
	this.shape_14.setTransform(94.7,46.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVBBQgLgFgJgKQgJgJgEgNQgFgNAAgPQAAgOAFgNQAFgNAJgJQAIgKAMgEQAMgGAMAAQAMAAALAFQAMAEAHAIIAOAAIAAAWIgYAAQgFgJgIgEQgJgFgKAAQgHAAgIAEQgHADgGAHQgFAFgDAKQgDAJAAAKQAAALADAJQADAJAFAGQAGAHAIADQAGADAIAAQAMAAAJgFQAJgHAFgLIAUAKQgEAHgFAHQgGAGgHAFQgIAEgHADQgJACgJABQgNgBgMgEg");
	this.shape_15.setTransform(78.9,49.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgXBBQgJgFgGgIIgNAAIAAgWIAaAAQAAAFADAEQACAEAEACQAEADAEABIAJABIAKgBIAIgEQAEgCACgDQABgEAAgEQAAgGgDgFQgFgEgKgEIgYgJQgPgEgHgJQgIgIAAgNQAAgIADgHQAEgIAFgFQAGgFAJgDQAIgDALAAQANAAAKAEQAJAEAIAKIAMAAIAAAWIgaAAQAAgGgCgDQgDgEgEgDIgJgDIgIgBIgJABIgIADQgCACgCAEQgCADAAADQAAAHAEAEQAEAEAJADIAYAJQARAFAIAJQAHAJAAANQAAAJgEAHQgDAIgHAFQgGAFgJADQgJADgLAAQgOAAgKgFg");
	this.shape_16.setTransform(65.4,49.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgJgJQgHgJgFgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAFAIAEAJQADAKABAKIABAJIAAAJIhdAAIABAKIABAJQAGANAKAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgMAAgMgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgFAFQgDAEgEAGQgCAHgBAIIBDAAg");
	this.shape_17.setTransform(45.7,49.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAMBjIAAgWIASAAIAAg8QABgPgIgHQgIgIgOAAQgHAAgJAEQgIAEgHAFIAABNIATAAIAAAWIg/AAIAAgWIAUAAIAAiZIgSAAIAAgWIAqAAIAABRIABAAIAIgHIAKgFIAKgEIAKgBQALAAAIADQAJADAGAGQAGAGADAJQADAIAAANIAAA/IAUAAIAAAWg");
	this.shape_18.setTransform(30.2,46.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgBBXQgHgDgEgFQgEgEgDgIQgCgJAAgNIABhHIgVAAIAAgTIAVAAIAAgfIAXgMIAAArIAeAAIAAATIgfAAIAABLQAAAIACAEQABAFAEADQAEABAFAAIAKAAIAJgEIAFAQIgNAFQgHABgJABQgJAAgFgCg");
	this.shape_19.setTransform(16.7,47.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgvBCIAAgWIATAAIAAhWIgTAAIAAgWIArAAIAAASIAEgIIAGgGIAIgEQAEgBAFAAIAMAAIANAAIAAAdIgZAAIAAgJQgEAAgFACQgEACgEADQgEADgCAFQgCAFgCAHIAAA+IAWAAIAAAWg");
	this.shape_20.setTransform(0,49.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_21.setTransform(-13.9,49.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgvBjIAAgWIAUAAIAAhaIgVAAIAAgTIAVAAIAAgUQAAgMAEgIQADgJAFgFQAFgGAIgDQAIgDAJAAIAMABIAJACIAIACIAGACIgIARIgKgDQgHgCgHAAQgKAAgHAHQgEAGAAANIAAAVIAdAAIAAATIgdAAIAABaIATAAIAAAWg");
	this.shape_22.setTransform(-24.9,46.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgXBBQgKgFgFgIIgNAAIAAgWIAaAAQAAAFADAEQACAEAEACQADADAFABIAJABIAKgBIAIgEQADgCADgDQABgEAAgEQAAgGgDgFQgFgEgKgEIgYgJQgPgEgHgJQgIgIAAgNQAAgIADgHQAEgIAFgFQAGgFAJgDQAIgDALAAQANAAAKAEQAJAEAIAKIAMAAIAAAWIgaAAQAAgGgCgDQgDgEgEgDIgJgDIgIgBIgJABIgIADQgDACgBAEQgCADAAADQAAAHAEAEQAEAEAKADIAXAJQARAFAHAJQAIAJAAANQAAAJgEAHQgDAIgHAFQgGAFgJADQgJADgLAAQgOAAgKgFg");
	this.shape_23.setTransform(242.4,20.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgJgJQgIgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAGAIADAJQADAKABAKIABAJIAAAJIhdAAIABAKIABAJQAFANALAGQAKAHAMAAQALAAAJgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgNAAgLgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgFAFQgEAEgDAGQgCAHgBAIIBDAAg");
	this.shape_24.setTransform(228.3,20.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAtBjIg1g7IgRAAIAAAlIAKAAIAAAWIg4AAIAAgWIAWAAIAAiZIgXAAIAAgWIAvAAIAAAWIAABhIAWAAIAfgfIgIAAIAAgWIAyAAIAAAWIgRAAIgoAoIAsAvIAQAAIAAAWg");
	this.shape_25.setTransform(213.3,17.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AggBCQgIgDgHgFQgFgGgEgGQgCgHAAgJQgBgHADgHQADgGAEgGQADgEAGgDIALgEIANgEIAMAAIAPAAIALACIAAgLQAAgHgCgFQgCgFgEgEQgEgDgFgBQgFgCgFAAIgLABIgLACIgJADIgGADIgIgQIAKgGIAMgEIANgDIAMgBQAKAAAJADQAJACAHAGQAGAGAEAJQAEAJAAAMIgBBBIAOAAIAAAVIglAAIAAgLQgIAHgJAEQgIAEgLAAQgLAAgHgDgAgRAHQgGACgEADQgEACgCAFQgDAEAAAGQAAAFACAEQACADADADQAEACAFACIAKABIAKgBIAIgDIAHgFIAHgFIAAgeIgbAAQgHAAgFACg");
	this.shape_26.setTransform(197.6,20.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgVBAQgLgEgJgKQgJgJgEgNQgFgNAAgPQAAgOAFgNQAFgNAJgJQAJgKALgFQAMgEAMgBQAMABAMAEQAKAEAJAIIANAAIAAAXIgYAAQgFgKgJgFQgHgEgLAAQgIAAgHADQgHAEgFAGQgGAHgDAJQgDAJAAAKQAAALADAJQADAJAGAGQAFAGAHAEQAHADAIAAQAMAAAJgFQAJgHAFgLIAUAKQgEAIgGAGQgFAHgHAEQgHAEgJAEQgIACgJAAQgNAAgMgGg");
	this.shape_27.setTransform(183.7,20.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AhFBhIAAgWIATAAIAAiSIgTAAIAAgWIAqAAIAAALQAJgHAJgEQAJgDALAAQANAAALAEQAKAFAIAJQAIAJAEAMQAFAMAAAPQAAAQgFANQgFAMgJAJQgIAKgMAFQgMAFgOAAQgJAAgIgCIgPgFIAAAqIAVAAIAAAWgAgMhIQgIAEgHAGIAABGQAFAFAHADQAIAEALAAQAIAAAHgEQAIgDAGgGQAFgGAEgJQADgJAAgMQAAgLgDgJQgDgIgGgGQgFgGgIgDQgHgEgIAAQgJAAgIAEg");
	this.shape_28.setTransform(168.4,23.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgaBAQgIgDgGgGQgGgGgDgKQgDgIAAgNIAAg+IgSAAIAAgWIArAAIAABRQAAAPAHAHQAHAJANAAQAHAAAIgDQAJgDAHgFIAAhPIgRAAIAAgWIAqAAIAABtIAPAAIAAAWIgnAAIAAgMQgJAGgKAEQgLAEgKAAQgKAAgIgDg");
	this.shape_29.setTransform(151.4,20.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgVBAQgMgEgIgKQgJgJgEgNQgFgNAAgPQAAgOAFgNQAFgNAJgJQAJgKALgFQAMgEAMgBQAMABALAEQAMAEAHAIIAOAAIAAAXIgYAAQgFgKgIgFQgJgEgKAAQgIAAgHADQgHAEgFAGQgGAHgDAJQgDAJAAAKQAAALADAJQADAJAGAGQAFAGAHAEQAIADAHAAQAMAAAJgFQAJgHAFgLIAUAKQgEAIgFAGQgGAHgHAEQgIAEgHAEQgJACgJAAQgNAAgMgGg");
	this.shape_30.setTransform(136.6,20.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgZBiIAshJIgMAEIgKAAQgLAAgMgEQgMgEgJgIQgIgIgGgLQgFgLAAgMQAAgQAFgNQAGgNAJgIQAJgJANgEQAMgFAMAAQAOAAAMAFQAMAEAJAJQAJAIAGAMQAFAMAAAPQAAALgEALIgLAWIgwBWgAgQhIQgIADgFAGQgGAFgEAIQgEAIAAAJQAAALAEAIQAEAIAHAFQAGAEAIADQAIADAHAAQALAAAHgDQAGgDAGgEQAGgFADgIQADgIAAgLQAAgKgDgHQgDgIgGgGQgGgFgIgDQgIgDgJAAQgIAAgIADg");
	this.shape_31.setTransform(115.7,17.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgWBfQgKgDgIgFQgIgGgFgHQgGgIgDgIIAUgLQACAHAEAFQAEAGAGAEQAFAEAGACQAGACAIAAQAIAAAIgDQAHgEAHgFQAFgGAEgIQADgIAAgJQAAgJgDgHQgEgIgFgGQgHgEgHgEQgIgDgIAAQgKAAgJAEQgIADgGAFIgSgDIAAhjIBrAAIAAAVIhXAAIAAA6QAIgFAHgCQAHgDAKAAQANAAAMAFQAMAFAJAJQAIAIAFALQAEALABANQgBANgEAMQgFALgIAJQgJAJgMAFQgMAFgOAAQgMAAgJgDg");
	this.shape_32.setTransform(100.6,17.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgfBgQgLgFgJgJQgIgJgFgNQgFgNAAgRQAAgPAFgMQAFgMAIgJQAIgJAMgEQAMgFAOAAQAJAAAIACQAIACAHAFIAAgyIgSAAIAAgWIAqAAIAACuIATAAIAAAWIgrAAIAAgLQgGAHgJAEQgIADgKAAQgNAAgMgEgAgTgMQgIADgFAGQgGAFgDAIQgDAJAAALQAAAMADAJQADAKAFAGQAGAGAIADQAHAEAJAAQAKAAAHgDQAHgEAGgGIAAhIQgGgGgJgCQgIgDgIAAQgIAAgHAEg");
	this.shape_33.setTransform(79.7,17.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_34.setTransform(63.7,20.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgJgJQgHgJgFgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAFAIAEAJQADAKABAKIABAJIAAAJIhdAAIABAKIABAJQAGANAKAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgMAAgMgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgFAFQgDAEgEAGQgCAHgBAIIBDAAg");
	this.shape_35.setTransform(48.8,20.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AANBDIAAgWIATAAIAAg7QgBgPgHgHQgIgJgPAAQgGAAgJAEQgJAFgHAFIAABMIATAAIAAAWIg+AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIABAAIAJgHIAKgGIAKgDIALgCQAKAAAJADQAJADAFAGQAGAGAEAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_36.setTransform(33.1,20.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgaBAQgIgDgGgGQgGgGgDgKQgDgIAAgNIAAg+IgSAAIAAgWIArAAIAABRQAAAPAHAHQAHAJANAAQAHAAAIgDQAJgDAHgFIAAhPIgRAAIAAgWIAqAAIAABtIAPAAIAAAWIgnAAIAAgMQgJAGgKAEQgLAEgKAAQgKAAgIgDg");
	this.shape_37.setTransform(9.5,20.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_38.setTransform(-6.2,20.4);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgfBgIAAgWIARAAIAAhDIgzhQIgPAAIAAgWIA/AAIAAAWIgTAAIAkA+IAmg+IgUAAIAAgWIA/AAIAAAWIgRAAIg2BRIAABCIAUAAIAAAWg");
	this.shape_39.setTransform(-22.3,17.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(-33,0,331.2,64.8), null);


(lib.shaker = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHCDIgHgFIgFgIIgCgIIACgIIAFgHIAHgFIAIgBIAIABIAGAFIAFAHIABAIIgBAIIgFAIIgGAFIgIABgAgOA+IgHjBIAqAAIgGDBg");
	this.shape.setTransform(164.8,21.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgWCAIgHgFIgEgHIgDgIIADgIIAEgHIAHgFIAJgCIAIACIAGAFIAEAHIACAIIgCAIIgEAHIgGAFIgIACgAgcBIIABgdQABgMAEgKQADgKAGgIIAQgPIAQgNIAMgKQAFgGADgGQACgGAAgIQAAgIgCgHQgDgHgFgFQgFgGgHgDQgIgDgHAAQgNAAgJAEQgIAFgGAHQgFAGgDAIIgCAMIgegCQACgOAFgMQAGgNAKgJQAKgKAOgFQAOgGAPAAQARAAAMAGQANAFAJAJQAIAJAFANQAFAMAAANQAAARgJAOQgJAOgQAMIgSANQgKAJgFANQgEAMAAAJIgBAVg");
	this.shape_1.setTransform(150.8,21.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AARBXIAAgcIAYAAIAAhOQAAgTgKgKQgKgLgTAAQgKAAgLAFQgLAGgKAHIAABkIAZAAIAAAcIhRAAIAAgcIAYAAIAAhyIgYAAIAAgcIA3AAIAAAUIAMgKIANgHIAOgFIAPgBQAOAAALADQALAEAIAIQAIAHAEANQAEAMAAARIAABRIAYAAIAAAcg");
	this.shape_2.setTransform(130.2,25.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbBVQgPgGgMgMQgKgLgGgRQgGgRAAgWQAAgSAFgRQAFgQALgMQAKgMAPgIQAPgHATAAQATAAANAGQANAGAJAKQAHAJAFANQAEAMACANIABANIAAAMIh7AAIABANIADAMQAHAQANAJQANAIARAAQANAAANgEQAMgDAPgIIAMAVQgRALgRAGQgRAGgSAAQgRAAgOgGgAAsgTIgDgSQgDgIgEgGQgFgGgIgEQgIgDgMAAQgJAAgIADQgIADgGAGQgGAGgDAIQgDAIgCALIBYAAg");
	this.shape_3.setTransform(108.6,26.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AARCBIAAgcIAXAAIAAhPQAAgUgKgJQgKgKgTAAQgJAAgLAFQgLAFgKAHIAABlIAZAAIAAAcIhSAAIAAgcIAaAAIAAjJIgXAAIAAgcIA2AAIAABpIABAAIALgIIAMgIIAOgEIAOgCQAOAAALAEQALAEAIAIQAHAHAFANQAEALAAAQIAABTIAaAAIAAAcg");
	this.shape_4.setTransform(88.4,21.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAnBXIgniIIgmCIIgdAAIgviRIgOAAIAAgcIA2AAIAAAcIgIAAIAeBtIApiJIAZAAIAoCJIAfhtIgKAAIAAgcIA2AAIAAAcIgOAAIgwCRg");
	this.shape_5.setTransform(63,26.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag1B9IAAgdIAVAAIASguIg5iRIgOAAIAAgdIBBAAIAAAdIgUAAIAoBtIAphtIgUAAIAAgdIBBAAIAAAdIgSAAIhLC/IAWAAIAAAdg");
	this.shape_6.setTransform(31.9,30);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgQB/QgLgEgIgGIAAALIgeAAIAAjlIgZAAIAAgcIA3AAIAABkQALgIANgFQAMgFAOAAQARAAAOAGQAOAHALALQAKALAFAQQAFAQAAATQABAVgHARQgGAQgLAMQgLAMgPAHQgQAGgSABQgMgBgMgDgAgQgPQgLAFgIAJIAABbQAFAGALAEQAKAEAPAAQAKAAAKgEQAKgEAIgIQAHgIAEgMQAFgMAAgQQAAgPgFgLQgEgLgGgHQgIgIgKgEQgKgEgKAAQgLAAgMAFg");
	this.shape_7.setTransform(12.1,21.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.shaker, new cjs.Rectangle(0,0,172.7,45.1), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeA0QgGgCgFgEIgFgGIgDgIIgBgLQAAgHACgIIAJgqIgOAAIAFgRIAjAAIgNA1QgEATADAIQAFAJANAAQAGAAADgCQAFgCAEgDIAGgHIAOg6IgOAAIAEgRIAiAAIgUBXIAQAAIgEASIgkAAIADgLIgHAGIgHAEIgIACIgHABQgHAAgGgCg");
	this.shape.setTransform(191.6,25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZA0QgJgEgHgGQgGgHgEgIQgDgKAAgKQAAgHACgIQACgJAEgGQAEgIAGgGQAGgFAGgFQAIgDAHgCQAIgDAIAAQAKAAAJAEQAJAEAGAGQAHAHAEAJQADAIABAKQgBAIgBAJQgDAHgEAHQgEAHgFAHQgGAGgHAEQgHADgIADQgIACgIAAQgKAAgJgEgAgIghQgIACgFAHQgGAFgDAIQgDAJAAAIQAAAHACAGQACAGAEAEQAEAEAFADQAFACAHAAQAGAAAIgEQAGgCAGgHQAGgGADgHQADgIAAgJQAAgIgCgGQgCgFgEgFQgEgDgFgCQgGgDgGAAQgHAAgGAEg");
	this.shape_1.setTransform(178.5,24.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag+BNIAFgSIAKAAIATgdIgMhZIgKAAIAFgRIAmAAIgDARIgJAAIAGBBIAphBIgJAAIAFgRIAnAAIgFARIgJAAIhKB2IAKAAIgEASg");
	this.shape_2.setTransform(166.5,27.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgsA2IAVhYIgVAAIAEgRIAoAAIgDAOIAFgGIAHgFIAHgDIAIgBIAHAAIAGAAIAIABIgHAcIgVAAIAEgMQgLAAgGAFQgHAFgEAJIgNA0IASAAIgDASg");
	this.shape_3.setTransform(150.8,24.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgfA0QgHgDgFgHQgHgFgCgIQgDgIAAgJQAAgOAEgMQAFgNAKgIQAIgKAMgFQAMgEANgBQAIAAAGADQAHACAFAEIABgFIAUAAIgUBXIARAAIgFASIglAAIACgHQgHAEgGACQgHACgHABQgJgBgIgDgAgHghQgIADgGAGQgGAGgEAIQgDAJAAALQAAAHABAEQACAFAEAEQACAEAGACQAEABAGABIAIgBIAGgDIAGgDIAHgEIAMg4QgCgDgGgCQgGgDgIAAQgIAAgHAEg");
	this.shape_4.setTransform(138,24.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXA1QgIgDgHgGQgGgHgEgJQgDgJAAgLQAAgNAEgLQAFgMAJgIQAIgJALgFQALgFANAAQAJAAAJADQAHAEAGAFQAFAGADAHQADAIAAAIIgBAKIgBAIIhRAAIAAACIAAACQAAAHACAFQACAGAEAEQAEAEAFACQAGACAFAAQAIAAAHgDQAIgDAEgHIAQALQgEAFgFAEIgKAGIgMAEIgNABQgKAAgJgDgAAggMQAAgGgCgFQgBgFgEgDQgDgDgFgCQgEgCgHAAQgFAAgFACQgFACgFAEIgIAIQgDAFgCAFIA7AAIAAAAg");
	this.shape_5.setTransform(125.7,24.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAPA2IAPhAQADgNgFgGQgEgGgMAAQgIAAgGADQgHAEgGAGIgSBMIgVAAIAVhYIgVAAIAFgRIAoAAIgDAKQAHgGAIgDQAJgDAJAAQAJAAAGACQAHACAEAGQAEAFABAIQACAHgCAJIgMAyIAPAAIgEASg");
	this.shape_6.setTransform(112.2,24.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgWA1QgJgDgHgGQgGgHgDgJQgEgJAAgLQAAgNAEgLQAFgMAJgIQAHgJAMgFQALgFAMAAQALAAAHADQAJAEAFAFQAGAGADAHQACAIAAAIIgBAKIgBAIIhQAAIAAACIAAACQAAAHABAFQACAGAFAEQADAEAFACQAGACAGAAQAHAAAHgDQAIgDAEgHIAQALQgEAFgEAEIgLAGIgNAEIgMABQgKAAgIgDgAAggMQABgGgCgFQgCgFgEgDQgDgDgFgCQgFgCgGAAQgFAAgFACQgFACgFAEIgHAIQgEAFgCAFIA7AAIAAAAg");
	this.shape_7.setTransform(94.9,24.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAPA2IAPhAQADgNgFgGQgEgGgMAAQgIAAgGADQgHAEgGAGIgSBMIgVAAIAVhYIgVAAIAFgRIAoAAIgDAKQAHgGAIgDQAJgDAJAAQAJAAAGACQAHACAEAGQAEAFABAIQACAHgCAJIgMAyIAPAAIgEASg");
	this.shape_8.setTransform(81.4,24.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgZA0QgJgEgGgGQgHgHgEgIQgDgKgBgKQABgHACgIQACgJAEgGQAEgIAGgGQAGgFAGgFQAIgDAHgCQAIgDAIAAQAKAAAJAEQAJAEAHAGQAGAHAEAJQAEAIgBAKQAAAIgCAJQgCAHgEAHQgEAHgGAHQgFAGgHAEQgHADgIADQgIACgIAAQgKAAgJgEgAgJghQgGACgGAHQgFAFgDAIQgEAJAAAIQAAAHADAGQACAGADAEQAEAEAFADQAGACAGAAQAHAAAGgEQAIgCAFgHQAGgGADgHQADgIAAgJQAAgIgCgGQgCgFgEgFQgEgDgFgCQgFgDgHAAQgGAAgIAEg");
	this.shape_9.setTransform(68.1,24.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgjBNQgIgDgGgGQgGgGgDgJQgEgIAAgKQAAgOAFgMQAFgLAJgJQAJgJALgFQAMgFAMAAQAIAAAHADQAHACAGAEIAJgpIgSAAIAEgSIAnAAIghCNIASAAIgEASIgnAAIACgHQgGAEgFACQgHADgHAAQgJAAgIgEgAgOgIQgIADgGAFQgFAGgEAIQgDAJAAAKQAAAHACAGQACAFADAEQAEAEAFACQAFACAGAAQAGAAAHgDQAGgDAGgFIAMg2QgDgFgGgCQgGgDgJAAQgHAAgHAEg");
	this.shape_10.setTransform(50.9,22.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAPA2IAPhAQADgNgFgGQgEgGgMAAQgIAAgGADQgHAEgGAGIgSBMIgVAAIAVhYIgVAAIAFgRIAoAAIgDAKQAHgGAIgDQAJgDAJAAQAJAAAGACQAHACAEAGQAEAFABAIQACAHgCAJIgMAyIAPAAIgEASg");
	this.shape_11.setTransform(36.8,24.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgZBPIAVhYIgTAAIADgRIAnAAIgUBXIAQAAIgDASgAAHgzIgEgDIgDgFIAAgFIAAgFIADgEIAEgEIAGgBIAFABIAEAEIADAEIABAFIgBAFIgDAFIgEADIgFAAg");
	this.shape_12.setTransform(26.6,22.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag2BpIAfiIIgWAAIAEgRIAWAAIAFgTQACgLAEgGQAEgIAFgDQAFgFAHgCQAHgCAIAAIAJABIAIABIAGACIAEACIgKAQIgHgDQgFgBgGAAQgIgBgGAFQgFAEgDAMIgEASIAdAAIgEARIgcAAIgfCIg");
	this.shape_13.setTransform(20,24.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(1,1,1).p("AwejbMAg9AAAIAAG3Mgg9AAAg");
	this.shape_14.setTransform(105.5,23);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(-1,0,213,46), null);


(lib.bywhen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shaker();
	this.instance.parent = this;
	this.instance.setTransform(86.3,22.5,1,1,0,0,0,86.3,22.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bywhen, new cjs.Rectangle(0,0,172.7,45.1), null);


// stage content:
(lib._728x90_cupcake = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 8
	this.instance = new lib.cta();
	this.instance.parent = this;
	this.instance.setTransform(838.5,45.5,1,1,0,0,0,105.5,22);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(314).to({_off:false},0).wait(1).to({regY:23,x:836.9,y:46.5},0).wait(1).to({x:830.9},0).wait(1).to({x:817.5},0).wait(1).to({x:790.1},0).wait(1).to({x:740.5},0).wait(1).to({x:687.5},0).wait(1).to({x:649.3},0).wait(1).to({x:622.1},0).wait(1).to({x:601.9},0).wait(1).to({x:586.1},0).wait(1).to({x:573.5},0).wait(1).to({x:563.3},0).wait(1).to({x:555},0).wait(1).to({x:548.1},0).wait(1).to({x:542.5},0).wait(1).to({x:538},0).wait(1).to({x:534.3},0).wait(1).to({x:531.3},0).wait(1).to({x:529.1},0).wait(1).to({x:527.5},0).wait(1).to({x:526.3},0).wait(1).to({x:525.7},0).wait(1).to({regY:22,x:525.5,y:45.5},0).wait(25));

	// Layer 6
	this.instance_1 = new lib.Tween1("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(-169,34.5);
	this.instance_1._off = true;

	this.instance_2 = new lib.Tween2("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(241,34.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_1}]},314).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).wait(25));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(314).to({_off:false},0).wait(1).to({regY:0.5,x:-166.9,y:35},0).wait(1).to({x:-159},0).wait(1).to({x:-141.5},0).wait(1).to({x:-105.5},0).wait(1).to({x:-40.6},0).wait(1).to({x:28.8},0).wait(1).to({x:78.9},0).wait(1).to({x:114.4},0).wait(1).to({x:141},0).wait(1).to({x:161.6},0).wait(1).to({x:178.1},0).wait(1).to({x:191.5},0).wait(1).to({x:202.4},0).wait(1).to({x:211.4},0).wait(1).to({x:218.7},0).wait(1).to({x:224.7},0).wait(1).to({x:229.5},0).wait(1).to({x:233.3},0).wait(1).to({x:236.3},0).wait(1).to({x:238.4},0).wait(1).to({x:239.9},0).wait(1).to({x:240.7},0).to({_off:true},1).wait(25));

	// Layer 5
	this.instance_3 = new lib.Symbol3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(364,62,1,1,0,0,0,221.8,32.4);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(182).to({_off:false},0).wait(38).to({regX:222.1,regY:20,x:364.3,y:49.4},0).wait(1).to({y:48.5},0).wait(1).to({y:46.1},0).wait(1).to({y:42},0).wait(1).to({y:39.3},0).wait(1).to({y:37.7},0).wait(1).to({y:36.8},0).wait(1).to({y:36.2},0).wait(1).to({y:35.8},0).wait(1).to({y:35.7},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:48},0).wait(75).to({regX:222.1,regY:20,x:364.3,y:35.8},0).wait(1).to({y:36.3},0).wait(1).to({y:37.4},0).wait(1).to({y:39.2},0).wait(1).to({y:42},0).wait(1).to({y:46.2},0).wait(1).to({y:53},0).wait(1).to({y:64.3},0).wait(1).to({y:80.2},0).wait(1).to({y:92.6},0).wait(1).to({y:100.3},0).wait(1).to({y:105.1},0).wait(1).to({y:108.4},0).wait(1).to({y:110.6},0).wait(1).to({y:112.1},0).wait(1).to({y:113},0).wait(1).to({y:113.5},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:126},0).to({_off:true},2).wait(38));

	// Layer 4
	this.instance_4 = new lib.bywhen();
	this.instance_4.parent = this;
	this.instance_4.setTransform(1116.5,43.7,4.8,4.8,6,0,0,86.5,22.7);
	this.instance_4._off = true;

	this.instance_5 = new lib.Symbol5();
	this.instance_5.parent = this;
	this.instance_5.setTransform(364,60.8,1,1,0,0,0,221.8,17.7);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(93).to({_off:false},0).wait(1).to({regX:84.9,regY:25.5,scaleX:4.56,scaleY:4.56,rotation:5.2,x:1070.9,y:55.7},0).wait(1).to({scaleX:4.14,scaleY:4.14,rotation:3.8,x:1006.4,y:54.8},0).wait(1).to({scaleX:3.66,scaleY:3.66,rotation:2.2,x:933.9,y:53.7},0).wait(1).to({scaleX:3.17,scaleY:3.17,rotation:0.6,x:859.7,y:52.4},0).wait(1).to({scaleX:2.7,scaleY:2.7,rotation:-1,x:787.3,y:51.2},0).wait(1).to({scaleX:2.25,scaleY:2.25,rotation:-2.5,x:719.5,y:50},0).wait(1).to({scaleX:1.86,scaleY:1.86,rotation:-3.8,x:658.9,y:48.9},0).wait(1).to({scaleX:1.53,scaleY:1.53,rotation:-4.9,x:608.6,y:48},0).wait(1).to({scaleX:1.29,scaleY:1.29,rotation:-5.7,x:572.9,y:47.3},0).wait(1).to({regX:86.3,regY:22.6,scaleX:1.2,scaleY:1.2,rotation:-6,x:560.3,y:43.6},0).to({_off:true},79).wait(180));
	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(219).to({_off:false},0).to({alpha:1},16).wait(70).to({regX:222.1,regY:20.1,x:364.3,y:63.3},0).wait(1).to({y:63.8},0).wait(1).to({y:64.8},0).wait(1).to({y:66.4},0).wait(1).to({y:68.9},0).wait(1).to({y:72.7},0).wait(1).to({y:78.7},0).wait(1).to({y:88.9},0).wait(1).to({y:103.1},0).wait(1).to({y:114.3},0).wait(1).to({y:121.2},0).wait(1).to({y:125.6},0).wait(1).to({y:128.5},0).wait(1).to({y:130.5},0).wait(1).to({y:131.8},0).wait(1).to({y:132.6},0).wait(1).to({y:133},0).wait(1).to({regX:221.8,regY:17.7,x:364,y:130.8},0).to({_off:true},1).wait(39));

	// Layer 3
	this.instance_6 = new lib.Symbol2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(784,49,0.6,0.6,0,0,0,112.1,112.9);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(4).to({_off:false},0).wait(1).to({regX:125.5,regY:106,x:779.8,y:44.9},0).wait(1).to({x:764.3},0).wait(1).to({x:744.1},0).wait(1).to({x:716.9},0).wait(1).to({x:680.1},0).wait(1).to({x:637.9},0).wait(1).to({x:602.4},0).wait(1).to({x:576.3},0).wait(1).to({x:556.8},0).wait(1).to({x:541.8},0).wait(1).to({x:529.9},0).wait(1).to({x:520.1},0).wait(1).to({x:512},0).wait(1).to({x:505.2},0).wait(1).to({x:499.5},0).wait(1).to({x:494.6},0).wait(1).to({x:490.4},0).wait(1).to({x:486.8},0).wait(1).to({x:483.8},0).wait(1).to({x:481.2},0).wait(1).to({x:479},0).wait(1).to({x:477.2},0).wait(1).to({x:475.7},0).wait(1).to({x:474.5},0).wait(1).to({x:473.6},0).wait(1).to({x:472.9},0).wait(1).to({x:472.4},0).wait(1).to({x:472.1},0).wait(1).to({regX:112.1,regY:112.9,x:464,y:49},0).wait(59).to({regX:125.5,regY:106,scaleX:0.6,scaleY:0.6,x:471.6,y:44.9},0).wait(1).to({scaleX:0.61,scaleY:0.61,x:470.3},0).wait(1).to({scaleX:0.62,scaleY:0.62,x:467.6},0).wait(1).to({scaleX:0.63,scaleY:0.63,x:463.2,y:44.8},0).wait(1).to({scaleX:0.65,scaleY:0.65,x:456.3},0).wait(1).to({scaleX:0.69,scaleY:0.69,x:445.9,y:44.7},0).wait(1).to({scaleX:0.74,scaleY:0.74,x:431.2},0).wait(1).to({scaleX:0.79,scaleY:0.79,x:413.7,y:44.6},0).wait(1).to({scaleX:0.85,scaleY:0.85,x:397.7,y:44.5},0).wait(1).to({scaleX:0.89,scaleY:0.89,x:385.5,y:44.4},0).wait(1).to({scaleX:0.92,scaleY:0.92,x:376.6,y:44.3},0).wait(1).to({scaleX:0.94,scaleY:0.94,x:370.1},0).wait(1).to({scaleX:0.95,scaleY:0.95,x:365.5},0).wait(1).to({scaleX:0.96,scaleY:0.96,x:362.1},0).wait(1).to({scaleX:0.97,scaleY:0.97,x:359.9,y:44.2},0).wait(1).to({scaleX:0.98,scaleY:0.98,x:358.4,y:44.3},0).wait(1).to({scaleX:0.98,scaleY:0.98,x:357.6,y:44.2},0).wait(1).to({regX:112.4,regY:112.8,scaleX:0.98,scaleY:0.98,x:344.3,y:51},0).wait(1).to({regX:125.5,regY:106,x:357.2,y:44.4},0).wait(2).to({x:357.3},0).wait(1).to({x:357.4},0).wait(1).to({x:357.6},0).wait(1).to({x:357.8},0).wait(1).to({x:358.1},0).wait(1).to({x:358.3},0).wait(1).to({x:358.6},0).wait(1).to({x:358.8},0).wait(1).to({x:359},0).wait(1).to({x:359.1},0).wait(2).to({regX:112.4,regY:112.8,x:346.3,y:51},0).wait(1).to({regX:125.5,regY:106,x:359.1,y:44.4},0).wait(3).to({x:359},0).wait(1).to({x:358.9},0).wait(1).to({x:358.8},0).wait(1).to({x:358.7},0).wait(1).to({x:358.5},0).wait(1).to({x:358.3},0).wait(1).to({x:358.1},0).wait(1).to({x:357.9},0).wait(1).to({x:357.7},0).wait(1).to({x:357.6},0).wait(1).to({x:357.4},0).wait(1).to({x:357.3},0).wait(1).to({x:357.2},0).wait(3).to({regX:112.4,regY:112.8,x:344.3,y:51},0).wait(1).to({regX:125.5,regY:106,x:357.2,y:44.4},0).wait(18).to({regX:112.4,regY:112.8,x:344.3,y:51},0).wait(1).to({regX:125.5,regY:106,x:357.2,y:44.4},0).wait(3).to({y:44.5},0).wait(2).to({x:357.3},0).wait(1).to({y:44.6},0).wait(1).to({x:357.4,y:44.7},0).wait(1).to({x:357.5,y:44.8},0).wait(1).to({x:357.6,y:44.9},0).wait(1).to({x:357.7,y:45},0).wait(1).to({x:357.8,y:45.1},0).wait(1).to({x:357.9},0).wait(1).to({x:358,y:45.2},0).wait(1).to({y:45.3},0).wait(1).to({x:358.1},0).wait(1).to({y:45.4},0).wait(3).to({regX:112.4,regY:112.8,x:345.3,y:52},0).to({_off:true},1).wait(180));

	// Layer 2
	this.instance_7 = new lib.Symbol1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-140.6,45.8,1,1,0,0,0,136.3,32.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(1).to({regX:132.4,regY:32,x:-130.3,y:45.4},0).wait(1).to({x:-112.4},0).wait(1).to({x:-89.1},0).wait(1).to({x:-57.6},0).wait(1).to({x:-15},0).wait(1).to({x:33.7},0).wait(1).to({x:74.8},0).wait(1).to({x:105},0).wait(1).to({x:127.5},0).wait(1).to({x:144.8},0).wait(1).to({x:158.6},0).wait(1).to({x:169.9},0).wait(1).to({x:179.2},0).wait(1).to({x:187.1},0).wait(1).to({x:193.7},0).wait(1).to({x:199.4},0).wait(1).to({x:204.2},0).wait(1).to({x:208.4},0).wait(1).to({x:211.9},0).wait(1).to({x:214.9},0).wait(1).to({x:217.4},0).wait(1).to({x:219.5},0).wait(1).to({x:221.2},0).wait(1).to({x:222.6},0).wait(1).to({x:223.7},0).wait(1).to({x:224.5},0).wait(1).to({x:225},0).wait(1).to({x:225.3},0).wait(1).to({regX:136.3,regY:32.4,x:229.4,y:45.8},0).wait(63).to({regX:132.4,regY:32,scaleX:1.01,scaleY:1.01,x:223,y:45.4},0).wait(1).to({scaleX:1.03,scaleY:1.03,x:214.2,y:45.3},0).wait(1).to({scaleX:1.07,scaleY:1.07,x:195.2},0).wait(1).to({scaleX:1.16,scaleY:1.16,x:157.3},0).wait(1).to({scaleX:1.36,scaleY:1.36,x:73.4,y:45.2},0).wait(1).to({scaleX:1.77,scaleY:1.77,x:-100,y:45.1},0).wait(1).to({scaleX:2.05,scaleY:2.05,x:-220.1,y:44.9},0).wait(1).to({scaleX:2.21,scaleY:2.21,x:-286.1,y:44.8},0).wait(1).to({scaleX:2.31,scaleY:2.31,x:-328.9},0).wait(1).to({scaleX:2.38,scaleY:2.38,x:-359},0).wait(1).to({scaleX:2.43,scaleY:2.43,x:-381.1,y:44.7},0).wait(1).to({scaleX:2.47,scaleY:2.47,x:-397.4},0).wait(1).to({scaleX:2.5,scaleY:2.5,x:-409.6},0).wait(1).to({scaleX:2.52,scaleY:2.52,x:-418.5},0).wait(1).to({scaleX:2.54,scaleY:2.54,x:-424.8},0).wait(1).to({scaleX:2.54,scaleY:2.54,x:-428.9},0).wait(1).to({scaleX:2.55,scaleY:2.55,x:-431.1},0).wait(1).to({regX:136.2,regY:32.4,scaleX:2.55,scaleY:2.55,x:-422.1,y:45.8},0).to({_off:true},113).wait(140));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C08632").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(362));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(54.1,45,1038,90);
// library properties:
lib.properties = {
	id: '2672068B7FDB4113A44DB72DDA239F2C',
	width: 728,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/728x90_cupcake_atlas_.png", id:"728x90_cupcake_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['2672068B7FDB4113A44DB72DDA239F2C'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;