(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"300x250_zebra_atlas_", frames: [[0,273,300,250],[254,726,226,185],[0,0,300,271],[254,525,227,199],[0,525,252,260]]}
];


// symbols:



(lib.bb_bg = function() {
	this.spriteSheet = ss["300x250_zebra_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.bb_pandas = function() {
	this.spriteSheet = ss["300x250_zebra_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.bb_pingu = function() {
	this.spriteSheet = ss["300x250_zebra_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.bb_redpa = function() {
	this.spriteSheet = ss["300x250_zebra_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.zebras = function() {
	this.spriteSheet = ss["300x250_zebra_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHAsQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIAAgnIgggsIgBgBIACgBIAUAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABIARAcIASgcQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAUAAIACABIgBABIggAsIAAAnQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape.setTransform(124.2,13.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAWAsQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAAAIgFgRIgdAAIgFARQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgRAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAABgBIAehUIACgCIAPAAIACACIAfBVQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAgAgJAKIATAAIgKgdg");
	this.shape_1.setTransform(116.8,13.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AglAsQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIAAhTQAAgBAAAAQABAAAAgBQAAAAAAAAQABAAAAAAIAjAAQASAAAMANQAMAMAAASQAAATgNAMQgNANgSAAgAgTAbIANAAQAKAAAIgIQAIgIAAgLQAAgMgKgJQgEgEgIgBIgEAAIgIAAIgFAAg");
	this.shape_2.setTransform(108.4,13.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AggAhQgNgNAAgUQAAgSANgNQAOgNASgBQATABANANQAOANABASQgBAUgOANQgMAMgUAAQgSAAgOgMgAgRgSQgJAIABAKQAAAMAHAHQAIAJAKgBQALABAIgJQAIgHAAgMQAAgKgIgIQgIgIgLAAQgKAAgHAIg");
	this.shape_3.setTransform(98.3,13.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgGAsQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAhEIgYAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgNQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIBAAAQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAANQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAgBAAIgWAAIAABEQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_4.setTransform(90.2,13.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeAjQgBAAAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAIAJgLQAAgBAAAAQAAAAABAAQAAAAAAAAQABAAAAAAQAJAHAKAAQANAAAAgKQAAgEgIgDIgGgDIgHgCQgMgEgFgEQgHgHAAgLQAAgFADgFQACgEAEgEQAEgDAHgCQAGgBAHAAQANAAANAHQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAIgIAMQAAABgBAAQAAAAAAAAQAAAAgBAAQAAAAgBAAQgIgGgJAAQgMAAABAHQgBAFAJADIAIADIAJADQATAGAAASQAAAMgJAIQgJAHgPAAQgQAAgOgKg");
	this.shape_5.setTransform(80.3,13.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgGAsQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhEIgWAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgNQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIA/AAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAANQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAgBAAIgWAAIAABEQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_6.setTransform(73.4,13.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgfAsQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhTQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIA/AAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAANQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIguAAIAAASIAnAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAMQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgnAAIAAATIAuAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIAAANQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_7.setTransform(66.2,13.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AANAsQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAgBAAIgUghIgFAHIAAAZQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgPAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAhTQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAgIAXggQABgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAVAAIABABIAAABIgfAlIAhAuIAAABIgBABg");
	this.shape_8.setTransform(58.3,13.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgXAgQgNgNAAgTQAAgSANgOQAOgMASAAQANAAAOAJQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIgIAMQgBABAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAQgJgHgIABQgKAAgIAIQgHAIAAAKQAAALAHAIQAIAIAKAAQAGAAAFgDIADgCIADgBQABgBAAAAQAAAAABAAQAAAAAAABQAAAAABAAIAIAMQAAABAAAAQAAAAAAABQAAAAAAAAQAAABgBAAQgLAKgQAAQgTgBgNgNg");
	this.shape_9.setTransform(50,13.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgHAsQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhTQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAPAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAABTQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_10.setTransform(43.8,13.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgHAsQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAhEIgYAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQgBAAAAgBIAAgNQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAAAAAIBAAAQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAANQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAgBAAIgWAAIAABEQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_11.setTransform(38.6,13.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgHAsQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgnIgggsIgBgBIACgBIAUAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABIARAcIASgcQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAUAAIACABIgBABIggAsIAAAnQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_12.setTransform(28.1,13.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgOAqQgHgCgFgFQgEgFgDgGQgCgHAAgIIAAgzQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAABAAIAPAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAxQAAAUAQAAQARAAAAgUIAAgxQAAAAAAgBQAAAAABAAQAAAAAAgBQAAAAABAAIAPAAQABAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAzQAAAIgCAHQgDAGgEAFQgFAFgHACQgGADgJAAQgIAAgGgDg");
	this.shape_13.setTransform(19.5,13.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgeAsQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAhTQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAdAAQAJAAAHAEQALAGAAAMQAAAOgLAFIAAAAQASAEAAASQAAAMgKAHQgIAFgNAAgAgNAbIANAAQAFAAADgBQAFgDAAgFQAAgKgRAAIgJAAgAgNgIIAFAAQAOAAAAgKQAAgFgEgCQgCgBgDAAIgKAAg");
	this.shape_14.setTransform(11.3,13.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#FFFFFF").ss(2,1,1).p("AqniIIVPAAIAAERI1PAAg");
	this.shape_15.setTransform(68,13.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol8, new cjs.Rectangle(-1,-1,138,29.5), null);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNAOQgFgGgBgIQABgHAFgGQAGgFAHAAQAIAAAFAFQAHAGAAAHQAAAIgHAGQgFAFgIAAQgHAAgGgFg");
	this.shape.setTransform(194.5,63.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgMBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAgBIAAh0IgnAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAgXQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAXQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgnAAIAAB0QAAABAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_1.setTransform(187.5,58);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAAAIAACOQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_2.setTransform(178.6,58);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_3.setTransform(169.1,58);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAgBIAAiOQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAAAIAACOQAAABgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_4.setTransform(159.7,58);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgOBLQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIg0iPQgBgDAEAAIAdAAQABAAAAAAQAAAAABABQAAAAABABQAAAAABABIAhBqIAjhqQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAeAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAQAAAAAAABIg1COQAAABgBABQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_5.setTransform(149.3,58);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag2A4QgYgXAAghQAAghAYgWQAXgVAfAAQAgAAAXAVQAYAWAAAhQAAAhgYAXQgWAVghAAQgfAAgXgVgAgfgfQgNAOAAARQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgNQgNgOgTAAQgSAAgNAOg");
	this.shape_6.setTransform(127.7,58);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAh0IgnAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAgXQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAXQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgnAAIAAB0QAAABAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_7.setTransform(114,58);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_8.setTransform(97.1,58);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAlBLIgCgBIhEheIAABbQAAABAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIAAiOQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABABAAIBDBcIAAhbQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAACOQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_9.setTransform(82.9,58);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag2A4QgYgXAAghQAAghAYgWQAXgVAfAAQAgAAAXAVQAYAWAAAhQAAAhgYAXQgWAVghAAQgfAAgXgVgAgfgfQgNAOAAARQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgNQgNgOgTAAQgSAAgNAOg");
	this.shape_10.setTransform(66,58);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_11.setTransform(51.2,58);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_12.setTransform(37.9,57.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBrAAQABAAABAAQAAAAABABQAAAAAAABQABABAAAAIAAAXQAAABgBABQAAAAAAABQgBAAAAAAQgBAAgBAAIhNAAIAAAfIBCAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIhCAAIAAAgIBNAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAWQAAABgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_13.setTransform(24.1,58);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAYBLQgDAAgCgEIgYgwIgWAAIAAAwQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAPQANAOAAAVQAAAPgJAMQgJANgOAFIAbAxIABAEQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgbgEIAiAAQAHAAAHgFQAHgHAAgIQAAgKgHgGQgHgFgHAAIgiAAg");
	this.shape_14.setTransform(9.8,58);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#BEA149").s().p("AgwA3QgXgXAAggQAAgeAYgXQAWgXAfAAQAXAAAYAQQABAAAAABQABAAAAAAQAAABAAABQAAAAgBABIgNAVQgCADgEgCQgOgLgPAAQgRAAgNAOQgNAOAAARQAAATANAOQANANARAAQAUAAANgKIAAgMIgcAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgYQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIA5AAQABAAABAAQAAABABAAQAAAAAAABQAAABAAAAIAABKQAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAIgaAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAgBQgQAHgRAAQghAAgVgWg");
	this.shape_15.setTransform(175.8,35.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEhdIAABaQAAABAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIAAiOQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAAAAAQABAAAAAAQABABAAAAQAAABABAAIBDBcIAAhbQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAACOQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_16.setTransform(159.6,35.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAAAIAACOQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_17.setTransform(148.2,35.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#BEA149").s().p("Ag4BLQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBBAAQAVAAAPAPQAPAPAAAXQAAAWgPAPQgPAPgVAAIgjAAIAAAoQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAgAgaABIAcAAQALAAAHgEQAHgGAAgMQAAgNgIgFQgGgGgLAAIgcAAg");
	this.shape_18.setTransform(138.1,35.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#BEA149").s().p("Ag4BLQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBBAAQAVAAAPAPQAPAPAAAXQAAAWgPAPQgPAPgVAAIgjAAIAAAoQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAgAgaABIAcAAQALAAAHgEQAHgGAAgMQAAgNgIgFQgGgGgLAAIgcAAg");
	this.shape_19.setTransform(123.6,35.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#BEA149").s().p("Ag2A3QgYgWAAghQAAggAYgXQAXgVAfAAQAgAAAXAVQAYAXAAAgQAAAigYAVQgWAWghAAQgfAAgXgWgAgfgfQgNANAAASQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgNQgNgOgTAAQgSAAgNAOg");
	this.shape_20.setTransform(107.2,35.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAgBIAAh0IgnAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAgXQAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAXQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgnAAIAAB0QAAABAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_21.setTransform(93.5,35.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_22.setTransform(82.2,35.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#BEA149").s().p("AAeBLQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIgchYIgbBYQAAABAAABQgBAAAAABQAAAAgBAAQAAAAAAAAIgjAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQgBgBAAgBIgtiPQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAeAAQAAAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAeBqIAfhqQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAcAAQAAAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAfBqIAehqQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAeAAQABAAAAAAQABAAAAABQAAAAAAABQAAABAAABIguCOQAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_23.setTransform(59,35.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#BEA149").s().p("Ag2A3QgYgWAAghQAAggAYgXQAXgVAfAAQAgAAAXAVQAYAXAAAgQAAAigYAVQgWAWghAAQgfAAgXgWgAgfgfQgNANAAASQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgNQgNgOgTAAQgSAAgNAOg");
	this.shape_24.setTransform(39,35.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#BEA149").s().p("AAiBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAg5Ig8AAIAAA5QAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAaAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAAA5IA8AAIAAg5QAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAABAAQAAAAAAABQABAAAAABQAAABAAAAIAACOQAAABAAABQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_25.setTransform(22.2,35.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_26.setTransform(8.1,35.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_27.setTransform(118.5,15);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_28.setTransform(106.6,15);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAAWQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIhPAAIAAAeIBDAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIhDAAIAAAgIBPAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAXQAAAAAAABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_29.setTransform(94.4,15);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#BEA149").s().p("AgoBLQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAB0IA1AAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAAXQAAAAAAABQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_30.setTransform(82.1,15);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBABAAQAAgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_31.setTransform(70.3,15);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEheIAABcQAAAAAAABQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABABAAIBDBcIAAhaQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAACOQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_32.setTransform(56.5,15);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#BEA149").s().p("AgZBIQgMgFgHgIQgIgHgEgMQgEgLgBgPIAAhVQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAABSQAAAiAcAAQAdAAAAgiIAAhSQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAbAAQAAAAABAAQAAAAABABQAAAAAAABQAAABAAABIAABVQAAAPgEALQgEAMgIAHQgHAIgMAFQgLAEgPAAQgNAAgMgEg");
	this.shape_33.setTransform(40.8,15.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#BEA149").s().p("Ag2A4QgYgXAAghQAAggAYgXQAXgVAfAAQAgAAAXAVQAYAXAAAgQAAAigYAWQgWAVghAAQgfAAgXgVgAgfggQgNAPAAARQAAATANANQANAOASAAQATAAANgOQANgNAAgTQAAgSgNgOQgNgNgTAAQgSAAgNANg");
	this.shape_34.setTransform(24.4,15);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#BEA149").s().p("AgoA4QgWgWAAgiQAAgeAXgXQAWgXAfAAQAYAAAXAQQABAAABABQAAAAAAABQAAAAAAABQAAAAgBABIgNAVQgCADgDgCQgPgLgPABQgRAAgNANQgNAOAAARQAAATANANQANAOARAAQALAAAIgEIAGgDIAFgDQABgBABAAQAAAAABAAQAAAAABABQAAAAABABIANAUQABAAAAABQAAABAAAAQAAABAAAAQgBABgBAAQgTAQgcAAQgfAAgXgVg");
	this.shape_35.setTransform(9.2,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol7, new cjs.Rectangle(0,0,199.7,72.8), null);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AoyRKQidhkh3iYQizjmhMklQiMoaF2lpQEHj/F1AfIEOAYIgVJuICgD5IGQgeIIiSQQl1BYmEAVQguACgtAAQnGAAmEj2g");
	mask.setTransform(63,134.4);

	// Layer_1
	this.instance = new lib.zebras();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol6, new cjs.Rectangle(0,54,176.3,206), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bb_redpa();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(0,0,227,199), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape.setTransform(97.1,37);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAlBLIgCgBIhEhdIAABaQAAABAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIAAiOQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABABIBDBcIAAhbQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAACOQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(82.9,37);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag2A3QgYgWAAghQAAggAYgWQAXgWAfAAQAgAAAXAWQAYAWAAAgQAAAigYAVQgWAWghAAQgfAAgXgWgAgfggQgNAOAAASQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgOQgNgNgTAAQgSAAgNANg");
	this.shape_2.setTransform(66,37);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_3.setTransform(51.2,37);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_4.setTransform(37.9,36.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBrAAQABAAABAAQAAAAABABQAAAAAAABQABABAAAAIAAAXQAAABgBABQAAAAAAABQgBAAAAAAQgBAAgBAAIhNAAIAAAfIBCAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAABIAAAVQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIhCAAIAAAgIBNAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAWQAAABgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_5.setTransform(24.1,37);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAYBLQgDAAgCgEIgYgvIgWAAIAAAvQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAOQANAPAAAUQAAAQgJAMQgJANgOAFIAbAyIABACQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgbgEIAiAAQAHAAAHgFQAHgGAAgKQAAgJgHgGQgHgFgHAAIgiAAg");
	this.shape_6.setTransform(9.8,37);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#BEA149").s().p("AgwA3QgXgXABggQgBgeAXgXQAXgXAfAAQAXAAAYAQQABAAAAABQABAAAAAAQAAABAAABQgBAAAAABIgNAVQgCADgEgCQgPgLgOAAQgRAAgNAOQgNAOAAARQAAATANAOQANANARAAQAUAAANgKIAAgMIgcAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgYQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIA5AAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAABKQAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAIgaAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAgBQgQAHgRAAQggAAgWgWg");
	this.shape_7.setTransform(155.7,15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEheIAABcQAAAAAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABABAAIBDBcIAAhaQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAACOQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_8.setTransform(139.6,15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBgBAAIAAiOQABgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAACOQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_9.setTransform(128.1,15);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEheIAABcQAAAAAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABABAAIBDBcIAAhaQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAACOQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_10.setTransform(116.6,15);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#BEA149").s().p("AAYBLQgDAAgCgDIgYgxIgWAAIAAAxQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAPQANAOAAAVQAAAQgJALQgJANgOAFIAbAxIABAEQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgbgEIAiAAQAHAAAHgFQAHgHAAgIQAAgKgHgGQgHgFgHAAIgiAAg");
	this.shape_11.setTransform(101.6,15);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#BEA149").s().p("AgZBIQgMgFgHgIQgIgHgEgMQgEgLgBgPIAAhVQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAABSQAAAiAcAAQAdAAAAgiIAAhSQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAbAAQAAAAABAAQAAAAABABQAAAAAAABQAAABAAABIAABVQAAAPgEALQgEAMgIAHQgHAIgMAFQgLAEgPAAQgNAAgMgEg");
	this.shape_12.setTransform(86.2,15.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBABAAQAAgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_13.setTransform(72.9,15);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#BEA149").s().p("Ag/BLQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIA6AAQAgAAAUAWQAUAVAAAfQAAAggWAWQgWAVgeAAgAghAvIAWAAQASAAANgOQAOgOAAgTQAAgWgQgOQgIgIgOgBIgHgBIgOAAIgIAAg");
	this.shape_14.setTransform(54.6,15);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#BEA149").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_15.setTransform(39.3,14.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAAWQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIhPAAIAAAeIBDAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIhDAAIAAAgIBPAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAXQAAAAAAABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_16.setTransform(25.5,15);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#BEA149").s().p("AAiBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAg6Ig8AAIAAA6QAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAaAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAAA4IA8AAIAAg4QAAgBAAgBQAAgBABAAQAAgBAAAAQABAAABAAIAaAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_17.setTransform(10,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(0,0,166.5,51.8), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bb_pandas();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,0,226,185), null);


(lib.Symbol2copy4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAAWQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIhOAAIAAAeIBBAAQABAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhBAAIAAAgIBOAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAXQAAAAAAABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape.setTransform(132,15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BEA149").s().p("AgoBLQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAB0IA1AAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAAXQAAAAAAABQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_1.setTransform(119.7,15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BEA149").s().p("Ag0BLQAAAAgBAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQABAAAAAAIAyAAQAQAAAMAHQASALAAAVQAAAWgTAIIAAABQAfAIAAAeQAAAVgRALQgOAJgVAAgAgWAuIAWAAQAJAAAGgDQAHgDABgJQgBgRgdgBIgPAAgAgWgOIAIAAQAYAAAAgSQAAgIgGgDQgEgBgGAAIgQAAg");
	this.shape_2.setTransform(107.4,15);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_3.setTransform(96.8,15);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBABAAQAAgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_4.setTransform(87.8,15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_5.setTransform(76.5,15);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_6.setTransform(67.1,15);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_7.setTransform(57.6,15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBrAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAAWQAAABAAABQAAAAAAABQgBAAAAAAQgBABgBAAIhOAAIAAAeIBDAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIhDAAIAAAgIBOAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAXQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_8.setTransform(45.4,15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#BEA149").s().p("AAYBLQgDAAgCgDIgYgxIgWAAIAAAxQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAPQANAOAAAVQAAAQgJALQgJANgOAFIAbAxIABAEQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgbgEIAiAAQAHAAAHgFQAHgHAAgIQAAgKgHgGQgHgFgHAAIgiAAg");
	this.shape_9.setTransform(31.1,15);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#BEA149").s().p("AAYBLQgDAAgCgDIgYgxIgWAAIAAAxQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAPQANAOAAAVQAAAQgJALQgJANgOAFIAbAxIABAEQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgbgEIAiAAQAHAAAHgFQAHgHAAgIQAAgKgHgGQgHgFgHAAIgiAAg");
	this.shape_10.setTransform(16.5,15);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAACOQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_11.setTransform(5.4,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2copy4, new cjs.Rectangle(0,0,140.3,29.8), null);


(lib.Symbol2copy2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BEA149").s().p("AgoA4QgWgWAAgiQAAgeAXgXQAWgXAfAAQAYAAAXAQQABAAABABQAAAAAAABQAAAAAAABQAAAAgBABIgNAVQgCADgDgCQgPgLgPABQgRAAgNANQgNAOAAARQAAATANANQANAOARAAQALAAAIgEIAGgDIAFgDQABgBABAAQAAAAABAAQAAAAABABQAAAAABABIANAUQABAAAAABQAAABAAAAQAAABAAAAQgBABgBAAQgTAQgcAAQgfAAgXgVg");
	this.shape.setTransform(102.9,15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAACOQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(92.5,15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBABAAQAAgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_2.setTransform(83.5,15);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BEA149").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_3.setTransform(71.7,14.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#BEA149").s().p("AAvBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAhWIgeAyQgBABAAABQgBAAAAABQAAAAgBAAQAAAAAAAAIgUAAIgEgDIgdgyIAABWQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgZAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAbAAQABAAAAAAQAAAAABABQAAAAABABQAAABABABIAoBGIAphGIAEgEIAbAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_4.setTransform(55.6,15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BEA149").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_5.setTransform(39.5,14.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BEA149").s().p("AAYBLQgDAAgCgDIgYgxIgWAAIAAAxQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAPQANAOAAAVQAAAQgJALQgJANgOAFIAbAxIABAEQAAAAAAAAQgBAAAAABQAAAAgBAAQgBAAAAAAgAgbgEIAiAAQAHAAAHgFQAHgHAAgIQAAgKgHgGQgHgFgHAAIgiAAg");
	this.shape_6.setTransform(25.8,15);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#BEA149").s().p("Ag/BLQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIA6AAQAgAAAUAWQAUAVAAAfQAAAggWAWQgWAVgeAAgAghAvIAWAAQASAAANgOQAOgOAAgTQAAgWgQgOQgIgIgOgBIgHgBIgOAAIgIAAg");
	this.shape_7.setTransform(10.4,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2copy2, new cjs.Rectangle(0,0,111.9,29.8), null);


(lib.Symbol2copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape.setTransform(97.1,9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAlBLIgCgBIhEhdIAABbQAAAAAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiPQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABABIBDBcIAAhbQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAACPQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(82.9,9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag2A3QgYgWAAghQAAghAYgVQAXgWAfAAQAgAAAXAWQAYAVAAAhQAAAhgYAWQgWAWghAAQgfAAgXgWgAgfggQgNAOAAASQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgOQgNgNgTAAQgSAAgNANg");
	this.shape_2.setTransform(66,9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_3.setTransform(51.2,9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_4.setTransform(37.9,8.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiPQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBrAAQABAAABAAQAAAAABABQAAAAAAABQABABAAAAIAAAXQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAIhNAAIAAAeIBCAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAABIAAAVQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIhCAAIAAAgIBNAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAXQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_5.setTransform(24.1,9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAYBLQgDAAgCgDIgYgwIgWAAIAAAwQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiPQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAOQANAPAAAUQAAAQgJAMQgJANgOAFIAbAyIABACQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgbgEIAiAAQAHAAAHgFQAHgGAAgKQAAgJgHgGQgHgFgHAAIgiAAg");
	this.shape_6.setTransform(9.8,9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2copy, new cjs.Rectangle(0,-6,105.4,29.8), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BEA149").s().p("AgwA3QgXgXAAggQAAgeAYgXQAWgXAfAAQAYAAAXAQQABAAAAABQABAAAAAAQAAABAAABQAAAAgBABIgNAVQgCADgDgCQgQgLgOAAQgRAAgNAOQgNAOAAARQAAATANAOQANANARAAQAUAAAMgKIAAgMIgbAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgYQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIA5AAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAABKQAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAIgaAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIAAgBQgPAHgRAAQghAAgVgWg");
	this.shape.setTransform(146.8,15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEheIAABcQAAAAAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAAAAAQABAAAAABQABAAAAAAQAAABABAAIBDBcIAAhaQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAACOQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(130.6,15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_2.setTransform(119.2,15);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BEA149").s().p("AAiBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAg6Ig8AAIAAA6QAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAaAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAAA4IA8AAIAAg4QAAgBAAgBQAAgBABAAQAAgBAAAAQABAAABAAIAaAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_3.setTransform(107.8,15);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#BEA149").s().p("AgoA4QgWgWAAgiQAAgeAXgXQAWgXAfAAQAYAAAXAQQABAAABABQAAAAAAABQAAAAAAABQAAAAgBABIgNAVQgCADgDgCQgPgLgPABQgRAAgNANQgNAOAAARQAAATANANQANAOARAAQALAAAIgEIAGgDIAFgDQABgBABAAQAAAAABAAQAAAAABABQAAAAABABIANAUQABAAAAABQAAABAAAAQAAABAAAAQgBABgBAAQgTAQgcAAQgfAAgXgVg");
	this.shape_4.setTransform(93,15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_5.setTransform(81.1,15);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BEA149").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_6.setTransform(69.3,14.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#BEA149").s().p("AgoA4QgWgWAAgiQAAgeAXgXQAWgXAfAAQAYAAAXAQQABAAABABQAAAAAAABQAAAAAAABQAAAAgBABIgNAVQgCADgDgCQgPgLgPABQgRAAgNANQgNAOAAARQAAATANANQANAOARAAQALAAAIgEIAGgDIAFgDQABgBABAAQAAAAABAAQAAAAABABQAAAAABABIANAUQABAAAAABQAAABAAAAQAAABAAAAQgBABgBAAQgTAQgcAAQgfAAgXgVg");
	this.shape_7.setTransform(55.3,15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBrAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAAAWQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAIhNAAIAAAeIBCAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIhCAAIAAAgIBNAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAXQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_8.setTransform(36.3,15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAhDIg3hKIAAgDQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAhAAQAEAAADAEIAdAvIAegvQADgEADAAIAiAAQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIgBADIg3BKIAABDQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_9.setTransform(22.6,15);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIAAAWQAAABgBABQAAAAAAABQgBAAAAAAQgBABAAAAIhOAAIAAAeIBBAAQABAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhBAAIAAAgIBOAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAXQAAAAgBABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_10.setTransform(9.5,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(0,0,157.6,29.8), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.zebras();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,252,260), null);


(lib.pingus = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bb_pingu();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pingus, new cjs.Rectangle(0,0,300,271), null);


// stage content:
(lib._300x250_zebra = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer_12
	this.instance = new lib.Symbol6();
	this.instance.parent = this;
	this.instance.setTransform(358.1,98,1.152,1.152,0,0,0,126.2,102.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(295).to({_off:false},0).wait(1).to({regX:88.1,regY:130,x:313.9,y:129.3,alpha:0.033},0).wait(1).to({x:313.6,y:128.3,alpha:0.07},0).wait(1).to({x:313.3,y:127.3,alpha:0.114},0).wait(1).to({x:312.9,y:126,alpha:0.164},0).wait(1).to({x:312.4,y:124.6,alpha:0.221},0).wait(1).to({x:311.9,y:122.9,alpha:0.286},0).wait(1).to({x:311.3,y:121.2,alpha:0.357},0).wait(1).to({x:310.8,y:119.4,alpha:0.43},0).wait(1).to({x:310.2,y:117.6,alpha:0.502},0).wait(1).to({x:309.6,y:115.9,alpha:0.569},0).wait(1).to({x:309.2,y:114.4,alpha:0.63},0).wait(1).to({x:308.7,y:113,alpha:0.682},0).wait(1).to({x:308.4,y:111.9,alpha:0.728},0).wait(1).to({x:308.1,y:110.9,alpha:0.768},0).wait(1).to({x:307.8,y:110,alpha:0.803},0).wait(1).to({x:307.5,y:109.3,alpha:0.833},0).wait(1).to({x:307.3,y:108.6,alpha:0.859},0).wait(1).to({x:307.2,y:108.1,alpha:0.881},0).wait(1).to({x:307,y:107.6,alpha:0.901},0).wait(1).to({x:306.9,y:107.2,alpha:0.918},0).wait(1).to({x:306.7,y:106.8,alpha:0.932},0).wait(1).to({x:306.6,y:106.5,alpha:0.945},0).wait(1).to({y:106.2,alpha:0.956},0).wait(1).to({x:306.5,y:106,alpha:0.966},0).wait(1).to({x:306.4,y:105.8,alpha:0.974},0).wait(1).to({y:105.6,alpha:0.98},0).wait(1).to({x:306.3,y:105.4,alpha:0.986},0).wait(1).to({y:105.3,alpha:0.991},0).wait(1).to({x:306.2,y:105.2,alpha:0.994},0).wait(1).to({alpha:0.997},0).wait(1).to({y:105.1,alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:126.2,regY:102.2,x:350.1,y:73},0).wait(24));

	// Layer_9
	this.instance_1 = new lib.pingus();
	this.instance_1.parent = this;
	this.instance_1.setTransform(167,159.1,0.299,0.299,0,0,0,150.6,136.4);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(295).to({_off:false},0).wait(1).to({regX:150,regY:135.5,y:158.8,alpha:0.033},0).wait(1).to({x:167.2,y:158.7,alpha:0.07},0).wait(1).to({x:167.5,alpha:0.114},0).wait(1).to({x:167.8,y:158.6,alpha:0.164},0).wait(1).to({x:168.1,alpha:0.221},0).wait(1).to({x:168.5,y:158.5,alpha:0.286},0).wait(1).to({x:168.9,y:158.4,alpha:0.357},0).wait(1).to({x:169.4,alpha:0.43},0).wait(1).to({x:169.8,y:158.3,alpha:0.502},0).wait(1).to({x:170.2,y:158.2,alpha:0.569},0).wait(1).to({x:170.6,alpha:0.63},0).wait(1).to({x:170.9,y:158.1,alpha:0.682},0).wait(1).to({x:171.2,alpha:0.728},0).wait(1).to({x:171.4,y:158,alpha:0.768},0).wait(1).to({x:171.6,alpha:0.803},0).wait(1).to({x:171.8,alpha:0.833},0).wait(1).to({x:172,y:157.9,alpha:0.859},0).wait(1).to({x:172.1,alpha:0.881},0).wait(1).to({x:172.2,alpha:0.901},0).wait(1).to({x:172.3,alpha:0.918},0).wait(1).to({x:172.4,alpha:0.932},0).wait(1).to({x:172.5,alpha:0.945},0).wait(1).to({y:157.8,alpha:0.956},0).wait(1).to({x:172.6,alpha:0.966},0).wait(1).to({alpha:0.974},0).wait(1).to({x:172.7,alpha:0.98},0).wait(1).to({alpha:0.986},0).wait(1).to({alpha:0.991},0).wait(1).to({x:172.8,alpha:0.994},0).wait(1).to({alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:150.6,regY:136.4,x:173,y:158.1},0).wait(24));

	// Layer_8
	this.instance_2 = new lib.Symbol5();
	this.instance_2.parent = this;
	this.instance_2.setTransform(74,187.1,0.18,0.18,0,0,180,113,100.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(295).to({_off:false},0).wait(1).to({regX:113.5,regY:99.5,x:74.2,y:186.9,alpha:0.033},0).wait(1).to({x:74.6,alpha:0.07},0).wait(1).to({x:75,alpha:0.114},0).wait(1).to({x:75.5,alpha:0.164},0).wait(1).to({x:76.1,alpha:0.221},0).wait(1).to({x:76.8,alpha:0.286},0).wait(1).to({x:77.5,alpha:0.357},0).wait(1).to({x:78.2,alpha:0.43},0).wait(1).to({x:78.9,alpha:0.502},0).wait(1).to({x:79.6,alpha:0.569},0).wait(1).to({x:80.2,alpha:0.63},0).wait(1).to({x:80.7,alpha:0.682},0).wait(1).to({x:81.2,alpha:0.728},0).wait(1).to({x:81.6,alpha:0.768},0).wait(1).to({x:81.9,alpha:0.803},0).wait(1).to({x:82.2,alpha:0.833},0).wait(1).to({x:82.5,alpha:0.859},0).wait(1).to({x:82.7,alpha:0.881},0).wait(1).to({x:82.9,alpha:0.901},0).wait(1).to({x:83.1,alpha:0.918},0).wait(1).to({x:83.2,alpha:0.932},0).wait(1).to({x:83.4,alpha:0.945},0).wait(1).to({x:83.5,alpha:0.956},0).wait(1).to({x:83.6,alpha:0.966},0).wait(1).to({alpha:0.974},0).wait(1).to({x:83.7,alpha:0.98},0).wait(1).to({x:83.8,alpha:0.986},0).wait(1).to({alpha:0.991},0).wait(1).to({alpha:0.994},0).wait(1).to({x:83.9,alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:113,regY:100.5,x:84,y:187.1},0).wait(24));

	// Layer_4
	this.instance_3 = new lib.Symbol2copy();
	this.instance_3.parent = this;
	this.instance_3.setTransform(92.9,35.9,1,1,0,0,0,77.9,14.8);
	this.instance_3.alpha = 0;

	this.instance_4 = new lib.Symbol3();
	this.instance_4.parent = this;
	this.instance_4.setTransform(52,144.6,0.57,0.57,0,0,180,112.9,92.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:55.9,alpha:1},29,cjs.Ease.quartOut).wait(170).to({y:65.9,alpha:0},10).to({_off:true},1).wait(142));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(295).to({_off:false},0).wait(1).to({regX:113,regY:92.5,x:52.6,y:144.5,alpha:0.033},0).wait(1).to({x:53.4,alpha:0.07},0).wait(1).to({x:54.2,alpha:0.114},0).wait(1).to({x:55.2,alpha:0.164},0).wait(1).to({x:56.4,alpha:0.221},0).wait(1).to({x:57.7,alpha:0.286},0).wait(1).to({x:59.1,alpha:0.357},0).wait(1).to({x:60.5,alpha:0.43},0).wait(1).to({x:62,alpha:0.502},0).wait(1).to({x:63.3,alpha:0.569},0).wait(1).to({x:64.5,alpha:0.63},0).wait(1).to({x:65.6,alpha:0.682},0).wait(1).to({x:66.5,alpha:0.728},0).wait(1).to({x:67.3,alpha:0.768},0).wait(1).to({x:68,alpha:0.803},0).wait(1).to({x:68.6,alpha:0.833},0).wait(1).to({x:69.1,alpha:0.859},0).wait(1).to({x:69.6,alpha:0.881},0).wait(1).to({x:70,alpha:0.901},0).wait(1).to({x:70.3,alpha:0.918},0).wait(1).to({x:70.6,alpha:0.932},0).wait(1).to({x:70.9,alpha:0.945},0).wait(1).to({x:71.1,alpha:0.956},0).wait(1).to({x:71.3,alpha:0.966},0).wait(1).to({x:71.4,alpha:0.974},0).wait(1).to({x:71.6,alpha:0.98},0).wait(1).to({x:71.7,alpha:0.986},0).wait(1).to({x:71.8,alpha:0.991},0).wait(1).to({alpha:0.994},0).wait(1).to({x:71.9,alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:112.9,regY:92.7,x:72,y:144.6},0).wait(24));

	// type2
	this.instance_5 = new lib.Symbol2copy2();
	this.instance_5.parent = this;
	this.instance_5.setTransform(92.9,7.9,1,1,0,0,0,77.9,14.8);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.instance_6 = new lib.Symbol4();
	this.instance_6.parent = this;
	this.instance_6.setTransform(102.2,202.6,1,1,0,0,0,83.2,25.9);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.instance_7 = new lib.Symbol8();
	this.instance_7.parent = this;
	this.instance_7.setTransform(86,221.3,1,1,0,0,0,68,13.7);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(75).to({_off:false},0).to({y:27.9,alpha:1},29,cjs.Ease.quartOut).wait(29).to({y:37.9,alpha:0},10).to({_off:true},1).wait(208));
	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(209).to({_off:false},0).wait(1).to({regX:83.3,x:102.3,y:203.2,alpha:0.053},0).wait(1).to({y:204,alpha:0.118},0).wait(1).to({y:204.9,alpha:0.196},0).wait(1).to({y:206,alpha:0.289},0).wait(1).to({y:207.2,alpha:0.391},0).wait(1).to({y:208.5,alpha:0.495},0).wait(1).to({y:209.6,alpha:0.591},0).wait(1).to({y:210.6,alpha:0.674},0).wait(1).to({y:211.5,alpha:0.743},0).wait(1).to({y:212.1,alpha:0.799},0).wait(1).to({y:212.7,alpha:0.845},0).wait(1).to({y:213.1,alpha:0.882},0).wait(1).to({y:213.5,alpha:0.912},0).wait(1).to({y:213.8,alpha:0.937},0).wait(1).to({y:214,alpha:0.956},0).wait(1).to({y:214.2,alpha:0.971},0).wait(1).to({y:214.3,alpha:0.982},0).wait(1).to({y:214.4,alpha:0.99},0).wait(1).to({y:214.5,alpha:0.996},0).wait(1).to({alpha:0.999},0).wait(1).to({regX:83.2,x:102.2,y:214.6,alpha:1},0).wait(42).to({alpha:0},10).to({_off:true},1).wait(69));
	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(334).to({_off:false},0).to({alpha:1},17).wait(1));

	// type
	this.instance_8 = new lib.Symbol2();
	this.instance_8.parent = this;
	this.instance_8.setTransform(92.9,7.9,1,1,0,0,0,77.9,14.8);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.instance_9 = new lib.Symbol2copy4();
	this.instance_9.parent = this;
	this.instance_9.setTransform(92.9,7.9,1,1,0,0,0,77.9,14.8);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.instance_10 = new lib.Symbol7();
	this.instance_10.parent = this;
	this.instance_10.setTransform(113.7,39.1,1,1,0,0,0,99.9,36.4);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(4).to({_off:false},0).to({y:27.9,alpha:1},29,cjs.Ease.quartOut).wait(32).to({y:37.9,alpha:0},10).to({_off:true},1).wait(276));
	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(143).to({_off:false},0).to({y:27.9,alpha:1},29,cjs.Ease.quartOut).wait(27).to({y:37.9,alpha:0},10).to({_off:true},2).wait(141));
	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(310).to({_off:false},0).wait(1).to({regX:99.5,regY:36.5,x:113.3,y:39.6,alpha:0.046},0).wait(1).to({y:40.1,alpha:0.1},0).wait(1).to({y:40.8,alpha:0.163},0).wait(1).to({y:41.5,alpha:0.237},0).wait(1).to({y:42.3,alpha:0.32},0).wait(1).to({y:43.2,alpha:0.407},0).wait(1).to({y:44.1,alpha:0.495},0).wait(1).to({y:44.9,alpha:0.578},0).wait(1).to({y:45.7,alpha:0.651},0).wait(1).to({y:46.3,alpha:0.715},0).wait(1).to({y:46.8,alpha:0.769},0).wait(1).to({y:47.3,alpha:0.815},0).wait(1).to({y:47.7,alpha:0.853},0).wait(1).to({y:48,alpha:0.885},0).wait(1).to({y:48.3,alpha:0.911},0).wait(1).to({y:48.5,alpha:0.933},0).wait(1).to({y:48.7,alpha:0.951},0).wait(1).to({y:48.8,alpha:0.966},0).wait(1).to({y:48.9,alpha:0.977},0).wait(1).to({y:49,alpha:0.986},0).wait(1).to({y:49.1,alpha:0.992},0).wait(1).to({alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({regX:99.9,regY:36.4,x:113.7,alpha:1},0).wait(18));

	// Layer_7
	this.instance_11 = new lib.Symbol3();
	this.instance_11.parent = this;
	this.instance_11.setTransform(227,165.5,1,1,0,0,0,113,92.5);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(141).to({_off:false},0).to({x:224.7,y:167.8,alpha:1},19).to({x:219,y:173.6},40).to({x:217,y:175.5,alpha:0},16).to({_off:true},1).wait(135));

	// Layer_6
	this.instance_12 = new lib.pingus();
	this.instance_12.parent = this;
	this.instance_12.setTransform(130,175.5,1,1,0,0,0,150,135.5);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.instance_13 = new lib.Symbol5();
	this.instance_13.parent = this;
	this.instance_13.setTransform(103.5,95.5,1,1,0,0,0,113.5,99.5);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(71).to({_off:false},0).to({x:134.2,y:173.4,alpha:1},19).to({x:146,y:167.6},36).to({x:150,y:165.5,alpha:0},17).to({_off:true},2).wait(207));
	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(214).to({_off:false},0).to({x:108.6,alpha:1},22).to({x:119.5},40).to({x:123.5,alpha:0},19).to({_off:true},34).wait(23));

	// animals
	this.instance_14 = new lib.Symbol1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(187,159,0.95,0.95,0,0,0,126,102);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({regY:102.1,scaleX:0.96,scaleY:0.96,x:183.9,y:156.8,alpha:1},21).to({scaleX:0.99,scaleY:0.99,x:178.1,y:152.3},32).to({regY:102,scaleX:1,scaleY:1,x:175,y:150,alpha:0},21).to({_off:true},1).wait(277));

	// bg
	this.instance_15 = new lib.bb_bg();
	this.instance_15.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(352));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,125,306.7,309.1);
// library properties:
lib.properties = {
	id: '0267BCEF7A554799BD8E2A3CB4CDA28B',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/300x250_zebra_atlas_.png", id:"300x250_zebra_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0267BCEF7A554799BD8E2A3CB4CDA28B'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;