(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"728x90_change_atlas_", frames: [[0,0,728,95],[730,0,155,61],[730,63,142,10]]}
];


// symbols:



(lib._970x250_bg = function() {
	this.spriteSheet = ss["728x90_change_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.LogoWhite = function() {
	this.spriteSheet = ss["728x90_change_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.SHAREDFUTURE = function() {
	this.spriteSheet = ss["728x90_change_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib._970x250_bg();
	this.instance.parent = this;
	this.instance.setTransform(0,-59);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(0,-59,728,95), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAJQgEgEAAgFQAAgFAEgEQAEgDAFAAQAGAAAEADQAEAEAAAFQAAAFgEAFQgEADgGABQgFAAgEgFg");
	this.shape.setTransform(14.8,56.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgWAsQgEAEgCAHIgFAAIAAgiIAFAAQAJAdAVABQAKgBAFgFQAEgGAAgHQAAgIgFgGQgFgEgOgIQgQgHgHgHQgGgIAAgKQAAgLAHgJQAHgJAOAAQAMAAAJALIAFgKIAFAAIAAAhIgFAAQgDgMgHgIQgHgJgJABQgIgBgEAFQgFAFAAAGQAAAHAFAFQAFAFAOAHQAVAJAFAIQAFAKAAAJQAAANgJAIQgJAJgOAAQgNAAgLgMg");
	this.shape_1.setTransform(7.3,51.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgTAyQgMgHgHgMQgIgMAAgSQAAgYAOgQQAPgQAUAAQAVAAALAMQALANABAOIhIAAIAAAMQAAAaAIANQAJAPAQAAQAXAAAKgWIAGAAQgEAOgNAHQgMAHgOAAQgMAAgLgGgAgYgVIAxAAIAAgFQAAgLgHgHQgGgFgKAAQgVAAgFAcg");
	this.shape_2.setTransform(-2.7,51.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAcBHQgKAJgKAFQgJAEgKAAQgVAAgOgQQgPgQAAgXQAAgaAPgOQAPgQAVAAQAKAAAJAEQAJAEAIAHIAAgoIAAgVQgBgFgDgCQgDgCgIAAIgDAAIAAgGQAQAAASgFIADAAIAACKIAAAXQABADADACQAEACAJAAIAAAGQgTABgOACQgBgGAAgMgAgegDQgKAKAAAZQAAAaAKAMQAKAMAOAAQAJAAAIgFQAIgEAHgJIAAhAQgIgHgIgDQgJgEgHAAQgPAAgJALg");
	this.shape_3.setTransform(-14.8,48.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgbBXIAAgGIAEAAQAKAAACgCQADgDAAgDIAAgVIAAggQAAgSgBgDQgBgEgEgBIgKgBIgDAAIAAgGQAWgCAMgFIADAAIAABIIAAAVQABAEADACQADACAJAAIACAAIAAAGgAgJg/QgFgEAAgGQAAgFAFgEQADgEAGAAQAEAAAEAEQAEAEgBAFQABAGgEAEQgEADgEAAQgGAAgDgDg");
	this.shape_4.setTransform(-25.2,48.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgWAsQgEAEgCAHIgFAAIAAgiIAFAAQAJAdAVABQAKgBAFgFQAEgGAAgHQAAgIgFgGQgFgEgOgIQgQgHgHgHQgGgIAAgKQAAgLAHgJQAHgJAOAAQAMAAAJALIAFgKIAFAAIAAAhIgFAAQgDgMgHgIQgHgJgJABQgIgBgEAFQgFAFAAAGQAAAHAFAFQAFAFAOAHQAVAJAFAIQAFAKAAAJQAAANgJAIQgJAJgOAAQgNAAgLgMg");
	this.shape_5.setTransform(-32.7,51.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAKBXIAAgGIACAAQAJAAADgCQADgDAAgDIABgVIAAggQAAgNgCgGQgBgFgGgEQgGgEgIAAQgJAAgIAGQgIAFgGALIAAAqIABAVQAAAEAEACQADACAJAAIAAAGIg1AAIAAgGIADAAQAJAAACgCQADgDABgDIAAgVIAAhnQAAgQgDgEQgDgEgLAAIAAgGQATAAANgFIADAAIAABWQAIgJAJgGQAJgFALAAQANAAAIAFQAJAGACAIQADAGAAASIAAAdIABAWQAAAEAEACQADABAJAAIAAAGg");
	this.shape_6.setTransform(-50.5,48.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgIBBQgGgFgDgIQgBgHAAgSIAAg6IgPAAIAAgGQAKAAAJgIQAHgJADgPIAEAAIAAAgIAfAAIAAAGIgfAAIAAA+QAAAOAAAGQACAEADAEQAFADAEAAQAJAAAIgLIADADQgDAIgIAEQgIAEgIAAQgIAAgHgFg");
	this.shape_7.setTransform(-60.8,50.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgmApQgQgPgBgaQAAgXAQgQQAQgQAXAAQAYAAAPAQQAQAQABAXQAAAagRAPQgQAPgXAAQgWAAgQgPgAgYglQgKALABAaQgBAcAKAMQAJAKAPABQARgBAIgKQAJgMAAgcQAAgagJgLQgIgMgRAAQgQAAgIAMg");
	this.shape_8.setTransform(-71.4,51.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLBVQgJgFgFgKQgJAJgFAKIgFAAIAAiKIAAgTQgBgFgEgCQgDgCgIAAIAAgGIASgCIAOgDIADAAIAABSQAIgIAKgEQAIgEAJAAQAXAAAOAQQAOAOAAAZQAAAYgOAQQgPAQgYAAQgKAAgJgEgAgJgLQgIAEgIAHIAAApQAAAQACAHQACAHAIAGQAIAGAJAAQARAAAKgNQAJgNAAgaQAAgXgJgLQgJgMgPAAQgIAAgIAEg");
	this.shape_9.setTransform(-85,48.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgUAyQgLgHgIgMQgHgMAAgSQAAgYAOgQQAOgQAWAAQAUAAALAMQALANABAOIhHAAIgBAMQAAAaAIANQAJAPAQAAQAXAAAKgWIAGAAQgEAOgMAHQgMAHgOAAQgNAAgMgGgAgYgVIAwAAIABgFQAAgLgHgHQgGgFgJAAQgXAAgEAcg");
	this.shape_10.setTransform(-103.6,51.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgUAyQgLgHgHgMQgIgMAAgSQAAgYAOgQQAOgQAWAAQAUAAALAMQALANABAOIhIAAIAAAMQAAAaAIANQAJAPAQAAQAXAAAKgWIAGAAQgEAOgMAHQgMAHgOAAQgNAAgMgGgAgYgVIAwAAIABgFQAAgLgHgHQgGgFgJAAQgXAAgEAcg");
	this.shape_11.setTransform(-114.9,51.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgWAsQgEAEgCAHIgFAAIAAgiIAFAAQAJAdAVABQAKgBAFgFQAEgGAAgHQAAgIgFgGQgFgEgOgIQgQgHgHgHQgGgIAAgKQAAgLAHgJQAHgJAOAAQAMAAAJALIAFgKIAFAAIAAAhIgFAAQgDgMgHgIQgHgJgJABQgIgBgEAFQgFAFAAAGQAAAHAFAFQAFAFAOAHQAVAJAFAIQAFAKAAAJQAAANgJAIQgJAJgOAAQgNAAgLgMg");
	this.shape_12.setTransform(-124.9,51.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgbBXIAAgGIAEAAQAHAAADgCQAEgCABgEIAAgVIAAhmQAAgRgDgEQgDgEgLAAIAAgGIASgCIANgDIAEAAIAACKIAAAVQAAAEADACQAEACAHAAIAEAAIAAAGg");
	this.shape_13.setTransform(-138.9,48.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgbBXIAAgGIADAAQAJAAACgCQAEgCABgEIAAgVIAAhmQAAgRgDgEQgDgEgLAAIAAgGIASgCIANgDIAEAAIAACKIAAAVQAAAEADACQADACAIAAIAEAAIAAAGg");
	this.shape_14.setTransform(-145.1,48.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAUAzQgFgFgCgJQgMAJgKAFQgKAEgJAAQgKAAgIgGQgIgGAAgKQAAgNAOgKQAMgJAXgJIASgIIAAgFIgBgPQgCgFgGgEQgFgEgJAAQgTAAgCANQgCANgIAAQgJAAABgIQAAgHAKgIQAKgIAWAAQAPAAAJAFQAJAFADAGQACAHAAANIAAApQABAPABAEQACAEAFAAQAIAAACgMIAFAAQgCAVgUAAQgIAAgFgEgAAAgEQggAMAAAUQgBAIAFAFQAEAFAGAAQAGAAAIgEQAIgEAJgIIAAgog");
	this.shape_15.setTransform(-153.9,51.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgTAyQgMgHgIgMQgHgMAAgSQAAgYAOgQQAPgQAUAAQAVAAALAMQALANABAOIhIAAIAAAMQAAAaAJANQAIAPAQAAQAXAAAKgWIAGAAQgEAOgNAHQgMAHgOAAQgMAAgLgGgAgYgVIAxAAIAAgFQAAgLgGgHQgHgFgKAAQgWAAgEAcg");
	this.shape_16.setTransform(-172.5,51.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAfA2IgfhSIgfBSIgFAAIgghSQgGgNgCgEQgDgCgIAAIAAgGIAwAAIAAAGQgIAAgDABQgDACAAAEQAAACAFAMIAVA3IAfhSIAFAAIAfBSIAXg6IAEgLQAAgHgNAAIAAgGIAiAAIAAAGQgGAAgEACQgDACgDAIIgDAHIggBSg");
	this.shape_17.setTransform(-187,52.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAKA2IAAgGIACAAQAJAAADgDQADgCAAgEIAAgVIAAggIgBgSQgBgFgFgEQgFgEgJAAQgIAAgIAFQgJAGgHALIAAApIABAWQAAAEAEACQADACAJAAIAAAGIg1AAIAAgGQAJAAAEgCQADgCABgDIABgXIAAgdIgBgXQgBgDgDgDQgDgCgKAAIAAgFQAOgCAPgEIADAAQADAHABAOQAJgKAKgGQAJgFALAAQAMAAAIAFQAIAFACAIQADAIAAAOIAAAfIAAAWQABAEADACQAEACAJAAIAAAGg");
	this.shape_18.setTransform(-209.1,51.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgUAyQgLgHgIgMQgHgMAAgSQAAgYAOgQQAPgQAUAAQAVAAALAMQALANABAOIhHAAIgBAMQAAAaAJANQAIAPAQAAQAXAAAKgWIAGAAQgEAOgNAHQgMAHgOAAQgMAAgMgGgAgYgVIAwAAIABgFQAAgLgGgHQgHgFgJAAQgWAAgFAcg");
	this.shape_19.setTransform(-221.7,51.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAKBXIAAgGIACAAQAJAAADgCQADgDAAgDIABgVIAAggQAAgNgCgGQgBgFgGgEQgGgEgIAAQgJAAgIAGQgIAFgGALIAAAqIABAVQAAAEAEACQADACAJAAIAAAGIg1AAIAAgGIADAAQAJAAACgCQADgDABgDIAAgVIAAhnQAAgQgDgEQgDgEgLAAIAAgGQATAAANgFIADAAIAABWQAIgJAJgGQAJgFALAAQANAAAIAFQAJAGACAIQADAGAAASIAAAdIABAWQAAAEAEACQADABAJAAIAAAGg");
	this.shape_20.setTransform(-234.3,48.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAfA2IgfhSIgfBSIgFAAIgghSQgGgNgCgEQgDgCgIAAIAAgGIAwAAIAAAGQgIAAgDABQgDACAAAEQAAACAFAMIAVA3IAfhSIAFAAIAfBSIAXg6IAEgLQAAgHgNAAIAAgGIAiAAIAAAGQgGAAgEACQgDACgDAIIgDAHIggBSg");
	this.shape_21.setTransform(-250,52.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAcBHQgKAJgKAFQgJAEgKAAQgVAAgOgQQgPgQAAgXQAAgaAPgOQAPgQAVAAQAKAAAJAEQAJAEAIAHIAAgoIAAgVQgBgFgDgCQgDgCgIAAIgDAAIAAgGQAQAAASgFIADAAIAACKIAAAXQABADADACQAEACAJAAIAAAGQgTABgOACQgBgGAAgMgAgegDQgKAKAAAZQAAAaAKAMQAKAMAOAAQAJAAAIgFQAIgEAHgJIAAhAQgIgHgIgDQgJgEgHAAQgPAAgJALg");
	this.shape_22.setTransform(11.8,17.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgqA2IAAgGIACAAQAIAAADgCQAEgCAAgEIABgWIAAgcIgBgVQAAgEgDgCQgDgDgJAAIgCAAIAAgGQAMgBATgGQAEAKAAAQQAEgLAJgIQAKgHAJAAQAIAAAFAFQAFAFAAAGQAAADgCADQgDACgDAAQgHABgDgJQgCgHgFAAQgFAAgIAHQgHAIgCAIQgCAIAAANIAAASIABAWQAAAEADACQACACAIAAIAEAAIAAAGg");
	this.shape_23.setTransform(0.3,21);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAUAzQgGgFgBgJQgMAJgKAFQgLAEgHAAQgLAAgIgGQgHgGAAgKQgBgNANgKQANgJAWgJIATgIIAAgFIgBgPQgBgFgHgEQgEgEgKAAQgTAAgCANQgCANgJAAQgHAAgBgIQAAgHALgIQAKgIAWAAQAPAAAJAFQAJAFACAGQADAHAAANIAAApQAAAPACAEQACAEAEAAQAJAAACgMIAFAAQgCAVgTAAQgKAAgEgEgAAAgEQghAMAAAUQABAIAEAFQAEAFAHAAQAGAAAHgEQAIgEAJgIIAAgog");
	this.shape_24.setTransform(-10.5,21.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAfA2IgfhRIgfBRIgFAAIgghRQgGgOgCgDQgDgDgIAAIAAgGIAwAAIAAAGQgIAAgDACQgDABAAADQAAADAFAMIAVA3IAfhSIAFAAIAfBSIAXg6IAEgMQAAgFgNgBIAAgGIAiAAIAAAGQgGAAgEADQgDACgDAHIgDAIIggBRg");
	this.shape_25.setTransform(-25.7,21.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgqA2IAAgGIACAAQAIAAADgCQAEgCAAgEIABgWIAAgcIgBgVQAAgEgDgCQgDgDgJAAIgCAAIAAgGQAMgBATgGQAEAKAAAQQAEgLAJgIQAKgHAJAAQAIAAAFAFQAFAFAAAGQAAADgCADQgDACgDAAQgHABgDgJQgCgHgFAAQgFAAgIAHQgHAIgCAIQgCAIAAANIAAASIABAWQAAAEADACQACACAIAAIAEAAIAAAGg");
	this.shape_26.setTransform(-38.9,21);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgmApQgRgQAAgZQABgXAPgQQAQgQAXAAQAYAAAQAQQAQAQAAAXQgBAagQAPQgQAPgXAAQgWAAgQgPgAgYgmQgJAMAAAbQAAAbAJAMQAJALAPgBQARABAIgLQAKgMgBgbQABgbgKgMQgIgMgRABQgQgBgIAMg");
	this.shape_27.setTransform(-50.5,21.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgtBXIAAgGQAIAAAEgBQADgCABgEIAAgWIAAg+IgTAAIAAgGIATAAIAAgJQAAgQACgIQABgJAGgJQAGgKAJgEQAIgFAMAAQAQAAAIAGQAKAGgBAGQABAEgDADQgDACgDAAQgHAAgFgKQgHgMgKAAQgIAAgFAGQgGAGgBAIQgBAJAAAcIAAAIIAVAAIAAAGIgVAAIAAA+IABAVQAAAEADACQAEACAGAAIAGAAIAAAGg");
	this.shape_28.setTransform(-58.7,17.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgUAyQgLgHgIgMQgHgNAAgRQAAgYAOgQQAOgQAWAAQAUAAALANQALAMABAOIhHAAIgBAMQAAAaAIANQAJAOAQABQAXgBAKgUIAGAAQgEANgMAHQgMAHgOAAQgNAAgMgGgAgYgVIAwAAIABgFQAAgMgHgFQgGgHgJABQgXgBgEAdg");
	this.shape_29.setTransform(-76.1,21.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgDA2IglhSQgFgNgEgCQgDgEgHAAIAAgGIAvAAIAAAGIgLABQgCABAAAEQAAADAFALIAbA+IAZg4QAGgNAAgEQAAgJgNAAIAAgGIAjAAIAAAGQgGAAgFAGQgEAEgIASIgiBJg");
	this.shape_30.setTransform(-87.8,21.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgmApQgQgQgBgZQAAgXAQgQQAQgQAXAAQAYAAAPAQQAQAQABAXQAAAagRAPQgQAPgXAAQgWAAgQgPgAgYgmQgKAMABAbQgBAbAKAMQAJALAPgBQARABAIgLQAJgMAAgbQAAgbgJgMQgIgMgRABQgQgBgIAMg");
	this.shape_31.setTransform(-100.2,21.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAuA2IAAgGQAJAAADgCQADgBABgEIABgXIAAgiIgBgPQgCgFgFgEQgFgEgIAAQgIAAgIAGQgJAFgIAMIAAAnIAAAWQABAEADACQADACAIAAIAAAGIgxAAIAAgGQAIAAAEgCQADgBABgEIABgXIAAgcIgBgTQgCgGgFgFQgFgEgJgBQgHABgJAFQgIAFgIAKIAAAqIAAAWQABAEADACQADACAJAAIAAAGIgzAAIAAgGQAIAAAEgCQADgBABgEIAAgXIAAgeIAAgWQgBgEgDgBQgDgCgJAAIAAgGQASgCAMgEIABAAQAEAIAAAOQAIgLAKgFQAKgGALAAQANAAAIAGQAHAFADAMQAKgMAKgFQAKgGALAAQAMAAAIAGQAIAFACAHQACAHAAAQIAAAeQAAASABAFQAAADAEACQADACAJAAIAAAGg");
	this.shape_32.setTransform(-117.1,21);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgmApQgRgQAAgZQABgXAQgQQAPgQAXAAQAXAAARAQQAPAQAAAXQAAAagQAPQgQAPgXAAQgWAAgQgPgAgZgmQgIAMgBAbQABAbAIAMQAKALAPgBQAQABAJgLQAKgMgBgbQABgbgKgMQgIgMgRABQgPgBgKAMg");
	this.shape_33.setTransform(-140.6,21.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgIBBQgGgFgCgIQgCgHAAgSIAAg6IgPAAIAAgGQAKAAAIgIQAIgJADgPIAEAAIAAAgIAeAAIAAAGIgeAAIAAA+QAAAOABAGQABAEADAEQAFADAEAAQAKAAAGgLIAFADQgFAIgHAEQgIAEgIAAQgIAAgHgFg");
	this.shape_34.setTransform(-150.5,19.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgqA2IAAgGIACAAQAIAAADgCQAEgCAAgEIABgWIAAgcIgBgVQAAgEgDgCQgDgDgJAAIgCAAIAAgGQAMgBATgGQAEAKAAAQQAEgLAJgIQAKgHAJAAQAIAAAFAFQAFAFAAAGQAAADgCADQgDACgDAAQgHABgDgJQgCgHgFAAQgFAAgIAHQgHAIgCAIQgCAIAAANIAAASIABAWQAAAEADACQACACAIAAIAEAAIAAAGg");
	this.shape_35.setTransform(-165.5,21);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgTAyQgMgHgHgMQgIgNAAgRQAAgYAOgQQAOgQAWAAQAUAAALANQALAMABAOIhIAAIAAAMQAAAaAIANQAJAOAQABQAXgBAKgUIAGAAQgEANgMAHQgMAHgOAAQgNAAgLgGgAgYgVIAxAAIAAgFQAAgMgHgFQgGgHgKABQgVgBgFAdg");
	this.shape_36.setTransform(-176.2,21.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgbBXIAAgGIAFAAQAIAAADgCQADgDAAgDIAAgVIAAggQABgSgCgDQgCgEgCgBIgLgBIgDAAIAAgGQAXgCALgFIADAAIAABIIAAAVQABAEADACQADACAIAAIADAAIAAAGgAgKg/QgDgEAAgGQAAgFADgEQAEgEAFAAQAFAAAEAEQADAEAAAFQAAAGgDAEQgEADgFAAQgFAAgEgDg");
	this.shape_37.setTransform(-185.2,17.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgWAsQgEAEgCAIIgFAAIAAgjIAFAAQAJAeAVgBQAKAAAFgFQAEgGAAgHQAAgIgFgFQgFgGgOgHQgQgGgHgIQgGgIAAgKQAAgLAHgJQAHgJAOAAQAMAAAJALIAFgKIAFAAIAAAgIgFAAQgDgLgHgIQgHgIgJAAQgIAAgEAEQgFAFAAAGQAAAHAFAFQAFAFAOAGQAVALAFAHQAFAKAAAIQAAAOgJAJQgJAIgOAAQgNAAgLgMg");
	this.shape_38.setTransform(-192.7,21.2);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AAUAzQgGgFgBgJQgNAJgJAFQgKAEgJAAQgKAAgIgGQgHgGgBgKQABgNANgKQAMgJAWgJIATgIIAAgFIgBgPQgCgFgFgEQgGgEgJAAQgTAAgCANQgCANgJAAQgHAAAAgIQgBgHALgIQAKgIAWAAQAPAAAJAFQAJAFACAGQAEAHAAANIAAApQAAAPABAEQABAEAGAAQAIAAACgMIAEAAQgBAVgTAAQgKAAgEgEgAAAgEQggAMgBAUQAAAIAFAFQAEAFAGAAQAHAAAIgEQAGgEAKgIIAAgog");
	this.shape_39.setTransform(-202.8,21.1);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgUAyQgLgHgIgMQgHgNAAgRQAAgYAOgQQAOgQAVAAQAVAAALANQALAMABAOIhHAAIgBAMQAAAaAJANQAIAOAQABQAXgBAKgUIAGAAQgEANgNAHQgMAHgOAAQgMAAgMgGgAgYgVIAwAAIABgFQAAgMgGgFQgHgHgKABQgVgBgFAdg");
	this.shape_40.setTransform(-214.9,21.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgWAsQgEAEgCAIIgFAAIAAgjIAFAAQAJAeAVgBQAKAAAFgFQAEgGAAgHQAAgIgFgFQgFgGgOgHQgQgGgHgIQgGgIAAgKQAAgLAHgJQAHgJAOAAQAMAAAJALIAFgKIAFAAIAAAgIgFAAQgDgLgHgIQgHgIgJAAQgIAAgEAEQgFAFAAAGQAAAHAFAFQAFAFAOAGQAVALAFAHQAFAKAAAIQAAAOgJAJQgJAIgOAAQgNAAgLgMg");
	this.shape_41.setTransform(-231.3,21.2);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgPAaQAYgEAAgWQAAgIgFAAIgCAAIgEABQgHAAgDgEQgEgEAAgFQAAgFAEgDQADgEAGAAQAIAAAGAHQAGAIAAANQAAANgJALQgIAKgPADg");
	this.shape_42.setTransform(-238.9,12.5);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgIBBQgGgFgCgIQgCgHAAgSIAAg6IgPAAIAAgGQAKAAAJgIQAHgJADgPIAEAAIAAAgIAfAAIAAAGIgfAAIAAA+QAAAOABAGQABAEADAEQAFADAEAAQAJAAAIgLIADADQgEAIgHAEQgIAEgIAAQgIAAgHgFg");
	this.shape_43.setTransform(-245.7,19.7);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgnBWIAAgGIAGAAQALAAAEgDQAFgCAAgHQABgFAAgWIAAhTQAAgVgBgGQgBgFgDgDQgFgDgMABIgFAAIAAgGIBOAAIAAAGIgDAAQgNgBgEADQgEACgBAGQgBAFgBAWIAABTIABAbQACAGAEADQADADANAAIAEAAIAAAGg");
	this.shape_44.setTransform(-254.4,17.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(-261,1,281.3,64.5), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.749)").s().p("As/AAQFzjYHMAAQHNAAFzDYQlzDZnNAAQnMAAlzjZg");
	this.shape.setTransform(-117.8,-12.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-201,-34.2,166.4,43.4), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAJQgDgEAAgFQAAgEAEgEQADgEAFAAQAFAAAEAEQAEAEAAAEQAAAGgEADQgEAEgFAAQgFAAgEgEg");
	this.shape.setTransform(-38.5,220.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AglBKQAAgJANgFQAHgEADgCQACgCADgHIAJgXIglhQQgFgKgEgDQgDgDgIAAIAAgGIAuAAIAAAGQgMAAAAAFIAFAMIAaA5IAXg2IAFgOQAAgGgNAAIAAgGIAjAAIAAAGQgIAAgEAEQgEAEgFAOIgsBqQgGAQgFAFQgFAGgGAAQgIAAAAgHg");
	this.shape_1.setTransform(-47.4,219.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgHA/QgHgGgCgHQgCgHABgRIAAg4IgPAAIAAgFQAKAAAIgJQAIgIACgPIAEAAIAAAgIAdAAIAAAFIgdAAIAAA8IAAATQABAEAEADQAFADAEAAQAJAAAGgKIAEADQgEAIgHAEQgHAEgIAAQgIAAgGgFg");
	this.shape_2.setTransform(-56.4,214.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaBUIAAgGIAEAAQAJABADgDQACgDABgDIAAgUIAAgeQAAgSgCgDQgBgEgDgBIgKgBIgDAAIAAgFQAWgDALgEIADAAIAABFIAAAUQABAEADACQADADAHgBIADAAIAAAGgAgJg9QgEgDAAgGQAAgGAEgDQADgEAGAAQAEAAAEAEQADADAAAGQAAAGgDADQgEAEgEAAQgGAAgDgEg");
	this.shape_3.setTransform(-63.5,212.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgaBUIAAgGIAEAAQAHAAADgBQADgCABgFIABgUIAAhiQAAgQgDgEQgDgEgLAAIAAgFIASgCQAJgCADgCIADAAIAACFIABAUQAAAEADACQADADAIgBIADAAIAAAGg");
	this.shape_4.setTransform(-69.6,212.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgaBUIAAgGIAEAAQAJABADgDQACgDABgDIAAgUIAAgeQAAgSgCgDQgBgEgDgBIgKgBIgDAAIAAgFQAWgDALgEIADAAIAABFIAAAUQABAEADACQADADAHgBIADAAIAAAGgAgJg9QgEgDAAgGQAAgGAEgDQADgEAGAAQAEAAAEAEQADADAAAGQAAAGgDADQgEAEgEAAQgGAAgDgEg");
	this.shape_5.setTransform(-75.7,212.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgKBSQgIgFgGgKQgIAJgFAKIgEAAIAAiFIgBgTQgCgEgDgCQgDgCgIAAIAAgFIASgCQAKgCADgCIADAAIAABPQAIgIAJgDQAIgEAJAAQAWAAANAPQAOAOAAAXQAAAYgOAQQgOAPgXAAQgKAAgIgEgAgJgLQgHAFgIAHIAAAmQAAAQACAHQACAGAIAGQAHAHAKAAQAPAAAKgOQAJgNAAgYQAAgWgIgLQgKgMgOAAQgHAAgJAEg");
	this.shape_6.setTransform(-85.6,213.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgaBUIAAgGIAEAAQAJABADgDQACgDABgDIAAgUIAAgeQAAgSgCgDQgBgEgDgBIgKgBIgDAAIAAgFQAWgDALgEIADAAIAABFIAAAUQABAEADACQADADAHgBIADAAIAAAGgAgJg9QgEgDAAgGQAAgGAEgDQADgEAGAAQAEAAAEAEQADADAAAGQAAAGgDADQgEAEgEAAQgGAAgDgEg");
	this.shape_7.setTransform(-95,212.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgVArQgDADgDAHIgFAAIAAggIAFAAQAJAcAUAAQAJAAAFgGQAFgFgBgHQAAgIgEgFQgGgFgNgHQgPgGgHgIQgGgHAAgKQAAgKAHgJQAHgJANAAQAMAAAJAKQACgBACgIIAFAAIAAAgIgFAAQgCgMgHgHQgIgJgIABQgHAAgFAEQgEAEAAAHQAAAGAFAFQAFAFAMAGQAVAJAFAIQAFAJAAAIQAAANgJAJQgIAIgOAAQgNAAgKgLg");
	this.shape_8.setTransform(-102.1,216.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAJA0IAAgGIACAAQAJABADgDQADgDAAgDIAAgUIAAggIgBgQQgBgGgFgDQgFgFgIAAQgIABgIAFQgIAGgHAKIAAAoIAAAVQABADADACQADACAJAAIAAAGIgyAAIAAgGQAIAAADgCQAEgBABgEIAAgVIAAgdIAAgVQgBgEgDgCQgEgCgIAAIAAgFQANgCAOgEIADAAQADAHABAOQAIgKAKgGQAJgFAKAAQAMAAAIAFQAHAFADAHQACAIAAAOIAAAeIAAAVQABADADACQAEACAIAAIAAAGg");
	this.shape_9.setTransform(-112.9,216.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AglAoQgPgPAAgZQAAgWAPgQQAPgPAWAAQAWAAAQAPQAPAQAAAWQAAAZgQAPQgPAOgWAAQgVAAgQgOgAgYgkQgIALAAAZQAAAbAIALQAJALAPAAQAQAAAIgLQAJgLAAgbQAAgZgJgLQgIgLgQAAQgPAAgJALg");
	this.shape_10.setTransform(-125.8,216.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag7BTIAAgGIADAAQAJAAADgCQACgDABgDIABgVIAAhZIgBgUQAAgFgEgCQgCgCgJAAIgDAAIAAgGQAMgBASgFIAEAAQACAHAAAKQAIgJAJgEQAHgEALAAQAUAAAOAPQAOAOAAAYQAAAYgOAPQgOAPgWAAQgJAAgIgDQgJgEgHgHIAAAlIABAWQAAADADACQAEACAIAAIAAAGgAgJhGQgIAEgGAJIAAA7QAGAJAIAEQAHAEAHAAQAOAAALgMQAKgLAAgaQAAgWgKgLQgKgMgOAAQgIAAgHAFg");
	this.shape_11.setTransform(-139,219.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgVArQgEADgCAHIgEAAIAAggIAEAAQAIAcAVAAQAJAAAFgGQAFgFAAgHQgBgIgFgFQgEgFgOgHQgPgGgHgIQgGgHAAgKQAAgKAHgJQAHgJANAAQAMAAAIAKQACgBADgIIAEAAIAAAgIgEAAQgCgMgHgHQgHgJgJABQgHAAgFAEQgEAEAAAHQAAAGAFAFQAFAFANAGQAVAJAEAIQAEAJABAIQAAANgJAJQgIAIgNAAQgNAAgLgLg");
	this.shape_12.setTransform(-149.1,216.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgTAwQgLgHgHgLQgHgMAAgRQAAgXAOgQQANgPAUAAQAUAAALAMQAKAMABAOIhFAAIAAALQAAAZAIANQAIAOAQAAQAWAAAJgVIAGAAQgEANgLAHQgMAHgOAAQgLAAgMgGgAgXgUIAvAAIAAgFQAAgLgGgFQgGgHgKABQgVgBgEAcg");
	this.shape_13.setTransform(-158.8,216.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgoA0IAAgGIACAAQAHAAAEgCQADgBABgFIAAgUIAAgbIAAgUQgBgFgDgCQgDgCgIAAIgCAAIAAgGQALgBASgGQAEAJAAAQQAFgKAIgIQAJgHAJAAQAJAAAEAFQAEAFABAFQAAAEgCADQgDACgEAAQgFAAgEgJQgCgGgFAAQgEAAgIAHQgGAHgCAIQgCAIAAAMIAAASIAAAUQABAEACACQADADAHgBIAEAAIAAAGg");
	this.shape_14.setTransform(-168.5,216.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgTAwQgLgHgHgLQgHgMAAgRQAAgXAOgQQANgPAUAAQAUAAALAMQAKAMABAOIhFAAIAAALQAAAZAIANQAIAOAQAAQAWAAAJgVIAGAAQgEANgLAHQgMAHgOAAQgLAAgMgGgAgXgUIAvAAIAAgFQAAgLgGgFQgGgHgKABQgVgBgEAcg");
	this.shape_15.setTransform(-185.1,216.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAGBUIAAgGQANAAAAgFQAAgDgIgJIgZgdIgFADIAAAPIAAAUQABAEADACQADADAHgBIAAAGIgyAAIAAgGIADAAQAJABADgDQACgDABgDIAAgUIAAhjQAAgPgDgEQgCgEgLAAIAAgFIARgCQAKgCAEgCIADAAIAABwIAKgHQAZgTAAgHQAAgFgKgBIAAgFIApAAIAAAFQgMABgSAPIgSAQIAjApQAIAKAFADQAEACAFAAIAAAGg");
	this.shape_16.setTransform(-196,212.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AATAxQgFgEgCgJQgMAJgIAEQgLAEgHAAQgLAAgHgGQgHgFgBgKQAAgNANgJQAMgJAWgIIARgIIAAgFIgBgPQgBgFgGgDQgEgEgJAAQgTAAgBAMQgDANgIAAQgIAAABgHQAAgHAKgIQAJgIAVAAQAPAAAIAFQAJAFACAGQADAGAAANIAAAnQAAAOACAEQABAEAFAAQAIAAACgMIAFAAQgCAVgTAAQgIAAgFgEgAAAgEQgfAMAAATQAAAIAEAFQAEAEAGAAQAGAAAHgDQAIgEAIgIIAAgmg");
	this.shape_17.setTransform(-207.5,216.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgIA/QgGgGgCgHQgCgHAAgRIAAg4IgOAAIAAgFQAKAAAIgJQAIgIACgPIAEAAIAAAgIAdAAIAAAFIgdAAIAAA8IAAATQACAEADADQAEADAFAAQAJAAAGgKIAEADQgEAIgHAEQgIAEgHAAQgIAAgHgFg");
	this.shape_18.setTransform(-217,214.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgaBUIAAgGIAEAAQAHAAADgBQADgCABgFIABgUIAAhiQAAgQgDgEQgDgEgLAAIAAgFIASgCQAJgCADgCIADAAIAACFIABAUQAAAEADACQADADAIgBIADAAIAAAGg");
	this.shape_19.setTransform(-230.2,212.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgaBUIAAgGIAEAAQAHAAADgBQADgCABgFIABgUIAAhiQAAgQgDgEQgDgEgLAAIAAgFIASgCQAJgCADgCIADAAIAACFIABAUQAAAEADACQADADAIgBIADAAIAAAGg");
	this.shape_20.setTransform(-236.2,212.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AATAxQgFgEgCgJQgMAJgIAEQgLAEgHAAQgKAAgIgGQgHgFAAgKQAAgNAMgJQAMgJAWgIIARgIIAAgFIgBgPQgBgFgGgDQgEgEgJAAQgTAAgCAMQgCANgIAAQgIAAAAgHQABgHAJgIQALgIAUAAQAOAAAJAFQAJAFADAGQACAGAAANIAAAnQABAOABAEQABAEAFAAQAIAAACgMIAFAAQgCAVgTAAQgIAAgFgEgAAAgEQgfAMAAATQAAAIAEAFQAEAEAHAAQAFAAAHgDQAHgEAJgIIAAgmg");
	this.shape_21.setTransform(-244.6,216.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgTAwQgLgHgHgLQgHgMAAgRQAAgXAOgQQANgPAUAAQAUAAALAMQAKAMABAOIhFAAIAAALQAAAZAIANQAIAOAQAAQAWAAAJgVIAGAAQgEANgLAHQgMAHgOAAQgLAAgMgGgAgXgUIAvAAIAAgFQAAgLgGgFQgGgHgKABQgVgBgEAcg");
	this.shape_22.setTransform(-262.5,216.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAeA0IgehPIgdBPIgGAAIgehPQgGgNgCgCQgDgEgHAAIAAgFIAtAAIAAAFQgHAAgDACQgDABAAAEQAAACAFAMIAUA1IAehPIAFAAIAeBPIAWg4IADgLQAAgGgMgBIAAgFIAgAAIAAAFQgFABgEACQgDACgDAIIgDAGIgfBPg");
	this.shape_23.setTransform(-276.4,216.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgaBUIAAgFIAEAAQAHAAADgDQADgCABgDIABgWIAAhhQAAgQgDgEQgDgEgLAAIAAgGIASgCQAJgBADgCIADAAIAACEIABAVQAAAEADACQADADAIAAIADAAIAAAFg");
	this.shape_24.setTransform(-68.4,177.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgaBUIAAgFIAEAAQAJAAADgDQACgDABgDIAAgVIAAgeQAAgRgCgDQgBgEgDgBIgKgBIgDAAIAAgGQAWgBALgFIADAAIAABEIAAAVQABAEADACQADADAHAAIADAAIAAAFgAgJg9QgEgEAAgFQAAgGAEgDQADgEAGAAQAEAAAEAEQADADAAAGQAAAFgDAEQgEAEgEAAQgGAAgDgEg");
	this.shape_25.setTransform(-74.5,177.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgHA/QgHgGgCgHQgBgHAAgRIAAg4IgPAAIAAgFQAKAAAIgJQAIgIACgPIAEAAIAAAgIAdAAIAAAFIgdAAIAAA8IAAATQABAEAEADQAFADAEAAQAIAAAHgKIAEADQgEAIgHAEQgIAEgHAAQgIAAgGgFg");
	this.shape_26.setTransform(-80.9,179.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAJA0IAAgFIACAAQAJAAADgDQADgDAAgDIAAgVIAAgeIgBgRQgBgFgFgFQgFgDgIAAQgIgBgIAGQgIAGgHAKIAAAnIAAAWQABAEADABQADADAJAAIAAAFIgyAAIAAgFQAIAAADgDQAEgBABgDIAAgXIAAgcIAAgVQgBgEgDgCQgEgCgIAAIAAgGQANgBAOgEIADAAQADAIABANQAIgLAKgFQAJgFAKAAQAMAAAIAFQAHAFADAIQACAGAAAOIAAAeIAAAWQABAEADABQAEADAIAAIAAAFg");
	this.shape_27.setTransform(-91.4,180.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAfA0QgEgHgBgRQgHAMgKAGQgJAGgLAAQgKAAgHgFQgIgEgDgHQgDgHAAgMIAAgiIgBgVQAAgDgDgDQgEgBgIAAIAAgGIAiAAIAABFIABAPQABAEAFADQAFAEAHAAQAIAAAJgHQAIgFADgHQADgIAAgMIAAgWIAAgTQAAgEgDgDQgDgCgIAAIgDAAIAAgGIAjAAIAABAIAAAVQABAEADACQADADAIAAIAAAFQgSAAgJAEg");
	this.shape_28.setTransform(-104.6,180.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAJA0IAAgFIACAAQAJAAADgDQADgDAAgDIAAgVIAAgeIgBgRQgBgFgFgFQgFgDgIAAQgIgBgIAGQgIAGgHAKIAAAnIAAAWQABAEADABQADADAJAAIAAAFIgyAAIAAgFQAIAAADgDQAEgBABgDIAAgXIAAgcIAAgVQgBgEgDgCQgEgCgIAAIAAgGQANgBAOgEIADAAQADAIABANQAIgLAKgFQAJgFAKAAQAMAAAIAFQAHAFADAIQACAGAAAOIAAAeIAAAWQABAEADABQAEADAIAAIAAAFg");
	this.shape_29.setTransform(-123.9,180.5);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgTAvQgLgGgHgMQgHgLAAgRQAAgWAOgRQANgPAUAAQAUAAALAMQAKAMABAOIhFAAIAAAKQAAAaAIAOQAIANAQgBQAWAAAJgTIAGAAQgEAMgLAHQgMAHgOAAQgLAAgMgHgAgXgUIAvAAIAAgFQAAgLgGgGQgGgFgKgBQgVAAgEAcg");
	this.shape_30.setTransform(-136,180.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("Ag7BTIAAgGIAEAAQAIAAADgCQADgDAAgDIAAgVIAAhZIAAgUQgBgFgDgCQgDgCgHAAIgEAAIAAgGQAMgBATgFIACAAQADAHAAAKQAIgJAIgEQAJgEAJAAQAWAAANAPQAOAOAAAYQAAAYgOAPQgOAPgXAAQgJAAgHgDQgJgEgHgHIAAAlIAAAWQABADAEACQACACAJAAIAAAGgAgJhGQgIAEgGAJIAAA7QAGAJAIAEQAHAEAIAAQANAAAKgMQAKgLAAgaQAAgWgKgLQgJgMgOAAQgHAAgIAFg");
	this.shape_31.setTransform(-148.4,183.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("Ag7BTIAAgGIADAAQAJAAADgCQACgDABgDIAAgVIAAhZIAAgUQgBgFgCgCQgEgCgIAAIgDAAIAAgGQAMgBASgFIAEAAQACAHAAAKQAHgJAKgEQAHgEALAAQAUAAAOAPQAOAOAAAYQAAAYgOAPQgOAPgWAAQgJAAgIgDQgIgEgIgHIAAAlIAAAWQABADADACQAEACAIAAIAAAGgAgJhGQgIAEgGAJIAAA7QAGAJAIAEQAHAEAHAAQAOAAALgMQAKgLgBgaQABgWgKgLQgKgMgOAAQgHAAgIAFg");
	this.shape_32.setTransform(-161.4,183.5);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AATAxQgFgEgBgJQgMAJgKAEQgKAEgIAAQgKAAgHgGQgIgFAAgKQAAgNANgJQAMgJAWgIIASgIIAAgFIgBgPQgCgFgFgDQgFgEgKAAQgRAAgCAMQgCANgJAAQgHAAAAgHQgBgHAKgIQAKgIAVAAQAOAAAJAFQAJAFACAGQAEAGAAANIAAAnQAAAOABAEQABAEAFAAQAIAAACgMIAEAAQAAAVgUAAQgIAAgFgEgAAAgEQgfAMAAATQAAAIAEAFQAEAEAGAAQAGAAAIgDQAGgEAKgIIAAgmg");
	this.shape_33.setTransform(-173,180.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAJBUIAAgFIACAAQAJAAADgDQADgDAAgDIAAgVIAAgeQAAgMgBgGQgCgFgFgEQgFgDgJAAQgIgBgIAGQgHAFgGAKIAAAoIABAWQAAADADACQADADAJAAIAAAFIgzAAIAAgFIADAAQAIAAADgDQADgDAAgDIABgVIAAhiQAAgPgDgEQgDgEgLAAIAAgGQATABAMgGIADAAIAABUQAHgKAKgFQAIgFAKAAQANAAAIAFQAIAGACAHQADAHAAAQIAAAbIABAWQAAAEADABQAEADAJAAIAAAFg");
	this.shape_34.setTransform(-185.8,177.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgIA/QgGgGgCgHQgBgHgBgRIAAg4IgOAAIAAgFQAKAAAIgJQAIgIACgPIAEAAIAAAgIAdAAIAAAFIgdAAIAAA8IAAATQABAEAFADQAEADAEAAQAIAAAHgKIAEADQgEAIgHAEQgIAEgHAAQgIAAgHgFg");
	this.shape_35.setTransform(-202,179.3);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgOAaQAXgFAAgVQAAgHgFgBIgCAAIgEABQgGAAgEgDQgDgEAAgFQAAgEAEgEQADgEAGAAQAHAAAFAHQAGAIAAAMQAAANgIAKQgIAKgOADg");
	this.shape_36.setTransform(-209,172.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAJA0IAAgFIACAAQAJAAADgDQADgDAAgDIAAgVIAAgeIgBgRQgBgFgFgFQgFgDgIAAQgIgBgIAGQgIAGgHAKIAAAnIAAAWQABAEADABQADADAJAAIAAAFIgyAAIAAgFQAIAAADgDQAEgBABgDIAAgXIAAgcIAAgVQgBgEgDgCQgEgCgIAAIAAgGQANgBAOgEIADAAQADAIABANQAIgLAKgFQAJgFAKAAQAMAAAIAFQAHAFADAIQACAGAAAOIAAAeIAAAWQABAEADABQAEADAIAAIAAAFg");
	this.shape_37.setTransform(-218.7,180.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AglAnQgPgOAAgZQAAgWAPgQQAPgPAWAAQAWAAAQAPQAPAQAAAWQAAAZgQAOQgPAPgWAAQgVAAgQgPgAgYgkQgIALAAAaQAAAaAIALQAJAKAPAAQAQAAAIgKQAJgLAAgaQAAgagJgLQgIgMgQAAQgPAAgJAMg");
	this.shape_38.setTransform(-231.7,180.7);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AAeA0IgehOIgdBOIgGAAIgehOQgGgOgCgDQgDgCgHAAIAAgGIAtAAIAAAGQgHgBgDACQgDACAAADQAAACAFAMIAUA0IAehOIAFAAIAeBOIAWg3IADgLQAAgGgMAAIAAgGIAgAAIAAAGQgFAAgEACQgDACgDAHIgDAIIgfBOg");
	this.shape_39.setTransform(-246.4,180.9);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgTAvQgLgGgHgMQgHgLAAgRQAAgXAOgPQANgQAUAAQAUAAALAMQAKAMABAOIhFAAIAAALQAAAZAIANQAIANAQAAQAWABAJgVIAGAAQgEANgLAHQgMAHgOAAQgLAAgMgHgAgXgUIAvAAIAAgFQAAgLgGgGQgGgFgKAAQgVgBgEAcg");
	this.shape_40.setTransform(-129.8,145.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgpBKQgOgJAAgNQAAgIAEgEQAEgFAHAAIADAAQgHAJAAAJQAAALAKAHQAKAHAUAAQARAAAKgHQAKgIAAgLQAAgMgJgFQgJgFgWgBQgagBgIgFQgIgFABgJQAAgPAWgEQgMgHgGgIQgFgJAAgLQAAgPAMgLQALgLARAAQATAAANANQAKgMAKAAQAGAAAEAEQADADAAADQAAAJgHAAQgFAAgCgFQgDgFgDAAQgFAAgFAGQAGAKAAALQAAAPgKALQgLAMgXABQgaAAAAAJQAAAFAFABQAGACASABQAUABALADQAKADAHAIQAGAIAAAMQAAAQgNAKQgNAKgYAAQgXAAgNgJgAgahEQgFAJAAARQAAAPAGAIQAGAHAKAAQAJAAAHgHQAGgHABgSQAAgSgIgHQgGgHgJAAQgLAAgGAIg");
	this.shape_41.setTransform(-140.7,147.9);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AAJA0IAAgGIACAAQAJABADgDQADgDAAgDIAAgUIAAggIgBgRQgBgEgFgFQgFgDgIgBQgIABgIAFQgIAGgHAKIAAAoIAAAVQABAEADACQADABAJAAIAAAGIgyAAIAAgGQAIAAADgBQAEgCABgEIAAgVIAAgdIAAgVQgBgEgDgCQgEgCgIAAIAAgFQANgCAOgEIADAAQADAHABANQAIgJAKgGQAJgFAKAAQAMAAAIAFQAHAFADAHQACAIAAANIAAAfIAAAVQABAEADACQAEABAIAAIAAAGg");
	this.shape_42.setTransform(-153.5,144.9);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AATAxQgFgEgCgJQgLAJgJAEQgLAEgHAAQgKAAgIgGQgHgFgBgKQAAgNANgJQAMgJAWgIIARgIIAAgFIgBgPQgBgFgGgDQgEgEgJAAQgSAAgDAMQgCANgIAAQgIAAAAgHQAAgHALgIQAJgIAVAAQAPAAAIAFQAJAFADAGQACAGAAANIAAAnQABAOABAEQABAEAFAAQAIAAACgMIAFAAQgCAVgTAAQgIAAgFgEgAAAgEQgfAMAAATQAAAIAEAFQAEAEAHAAQAFAAAHgDQAIgEAIgIIAAgmg");
	this.shape_43.setTransform(-165.7,145);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AAJBUIAAgGIACAAQAJABADgDQADgDAAgDIAAgUIAAgeQAAgNgBgGQgCgEgFgFQgFgDgJgBQgIABgIAFQgHAGgGAJIAAApIABAUQAAAFADACQADABAJAAIAAAGIgzAAIAAgGIADAAQAIABADgDQADgDAAgDIABgUIAAhjQAAgPgDgEQgDgEgLAAIAAgFQATAAAMgGIADAAIAABTQAHgIAKgGQAIgFAKAAQANAAAIAFQAIAGACAHQADAGAAARIAAAcIABAVQAAAEADACQAEABAJAAIAAAGg");
	this.shape_44.setTransform(-178.5,141.7);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgfAoQgOgPAAgYQAAgYAPgOQAQgQAVAAQANAAALAGQALAGgBAHQAAAEgBACQgCADgFAAQgHAAgCgKQgBgGgDgEQgEgCgJAAQgPAAgIALQgJALAAAYQAAAWAJANQAJANARAAQAYABAGgXIAGAAQgJAdghAAQgUAAgPgOg");
	this.shape_45.setTransform(-190.3,145.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgTAwQgLgHgHgLQgHgMAAgRQAAgWAOgRQANgPAUAAQAUAAALAMQAKAMABAOIhFAAIAAALQAAAZAIANQAIANAQABQAWgBAJgTIAGAAQgEAMgLAHQgMAHgOAAQgLAAgMgGgAgXgUIAvAAIAAgFQAAgLgGgFQgGgHgKAAQgVABgEAbg");
	this.shape_46.setTransform(-57.3,109.5);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgIA/QgGgGgCgHQgBgHgBgRIAAg4IgOAAIAAgFQAKAAAIgJQAIgIACgPIAEAAIAAAgIAdAAIAAAFIgdAAIAAA8IAAATQABAEAFADQAEADAEAAQAIAAAHgKIAEADQgEAIgHAEQgIAEgHAAQgIAAgHgFg");
	this.shape_47.setTransform(-66.1,108.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AATAxQgFgEgCgJQgLAJgKAEQgJAEgJAAQgKAAgHgGQgIgFAAgKQAAgNANgJQAMgJAWgIIARgIIAAgFIgBgPQgBgFgFgDQgFgEgJAAQgSAAgCAMQgCANgJAAQgIAAABgHQAAgHAKgIQAKgIAUAAQAPAAAIAFQAJAFACAGQADAGAAANIAAAnQAAAOACAEQABAEAFAAQAIAAACgMIAFAAQgBAVgUAAQgIAAgFgEgAAAgEQgfAMAAATQAAAIAEAFQAEAEAGAAQAGAAAIgDQAHgEAIgIIAAgmg");
	this.shape_48.setTransform(-75.5,109.4);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AAtA0IAAgFQAHgBAEgCQADgBABgDIAAgXIAAgfIgBgQQgBgFgFgEQgFgDgIAAQgHgBgIAGQgIAFgIALIAAAmIAAAVQAAAEADACQADADAIAAIAAAFIgvAAIAAgFQAIgBADgCQADgBABgDIABgXIAAgaIgBgTQgBgGgFgEQgGgFgHABQgIAAgIAEQgIAGgIAJIAAAoIABAVQAAAEADACQADACAJABIAAAFIgxAAIAAgFQAIgBADgCQADgBABgDIABgXIAAgcIgBgVQgBgEgDgCQgDgCgIAAIAAgGQARgBALgEIACAAQADAIAAANQAIgKAKgGQAJgFALAAQAMAAAIAFQAHAGADALQAJgLAKgGQAKgFAKAAQALAAAIAFQAIAGACAHQACAGAAAPIAAAdQAAASABAEQAAADADACQAEACAIABIAAAFg");
	this.shape_49.setTransform(-91.7,109.3);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgaBUIAAgFIAEAAQAJAAADgDQACgDABgDIAAgVIAAgeQAAgRgCgDQgBgEgDgBIgKgBIgDAAIAAgGQAWgCALgEIADAAIAABEIAAAVQABAEADACQADADAHAAIADAAIAAAFgAgJg9QgEgDAAgGQAAgFAEgEQADgEAGAAQAEAAAEAEQADAEAAAFQAAAGgDADQgEAEgEAAQgGAAgDgEg");
	this.shape_50.setTransform(-105,106.1);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgaBUIAAgFIAEAAQAHgBADgCQADgCABgDIABgWIAAhhQAAgQgDgEQgDgEgLAAIAAgGIASgBQAJgCADgCIADAAIAACEIABAVQAAAEADACQADADAIAAIADAAIAAAFg");
	this.shape_51.setTransform(-111.1,106.1);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgfAoQgOgPAAgYQAAgYAPgPQAQgPAVAAQANAAAKAFQAMAHgBAIQAAACgCADQgBADgFAAQgHAAgCgJQgBgIgDgCQgEgDgJAAQgQAAgHALQgJAMAAAWQAAAXAJANQAJANARABQAYAAAGgXIAGAAQgIAdgiAAQgUAAgPgOg");
	this.shape_52.setTransform(-119.1,109.5);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AglAoQgPgPAAgZQAAgWAPgQQAPgPAWAAQAWAAAQAPQAPAQAAAWQAAAZgQAPQgPAOgWAAQgVAAgQgOgAgYgkQgIALAAAaQAAAaAIALQAJAKAPAAQAQAAAIgKQAJgLAAgaQAAgagJgLQgIgMgQAAQgPAAgJAMg");
	this.shape_53.setTransform(-137.1,109.5);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgHA/QgHgGgCgHQgCgHAAgRIAAg4IgOAAIAAgFQAKAAAIgJQAIgIACgPIAEAAIAAAgIAdAAIAAAFIgdAAIAAA8IAAATQACAEADADQAEADAFAAQAIAAAHgKIAEADQgEAIgHAEQgIAEgHAAQgIAAgGgFg");
	this.shape_54.setTransform(-146.7,108.1);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgVAqQgEAFgCAGIgEAAIAAggIAEAAQAIAcAVAAQAKAAAEgGQAFgGgBgGQAAgIgEgFQgFgFgOgHQgPgHgHgGQgGgIAAgKQAAgKAHgJQAHgJANAAQAMAAAIALQADgCACgHIAEAAIAAAeIgEAAQgCgKgHgJQgIgHgIgBQgHABgFAEQgEAFAAAGQAAAGAFAFQAFAEAMAHQAVAKAFAHQAEAKABAHQAAAOgJAIQgIAIgOAAQgNAAgKgMg");
	this.shape_55.setTransform(-160.9,109.5);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgTAwQgLgHgHgLQgHgMAAgRQAAgWAOgRQANgPAUAAQAUAAALAMQAKAMABAOIhFAAIAAALQAAAZAIANQAIANAQABQAWgBAJgTIAGAAQgEAMgLAHQgMAHgOAAQgLAAgMgGgAgXgUIAvAAIAAgFQAAgLgGgFQgGgHgKAAQgVABgEAbg");
	this.shape_56.setTransform(-170.6,109.5);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgIA/QgGgGgCgHQgBgHgBgRIAAg4IgOAAIAAgFQAKAAAIgJQAIgIACgPIAEAAIAAAgIAdAAIAAAFIgdAAIAAA8IAAATQABAEAFADQAEADAEAAQAIAAAHgKIAEADQgEAIgHAEQgHAEgIAAQgIAAgHgFg");
	this.shape_57.setTransform(-179.4,108.1);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AAfA0QgEgHgBgRQgHANgKAFQgJAGgLAAQgKAAgHgFQgIgEgDgGQgDgIAAgMIAAghIgBgWQAAgDgDgCQgEgCgIAAIAAgGIAiAAIAABFIABAOQABAFAFADQAFAEAHAAQAIAAAJgGQAIgGADgHQADgIAAgMIAAgVIAAgUQAAgEgDgDQgDgCgIAAIgDAAIAAgGIAjAAIAABAIAAAVQABAEADACQADACAIABIAAAFQgSAAgJAEg");
	this.shape_58.setTransform(-189.9,109.7);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgKBRQgJgEgFgJQgIAHgFALIgEAAIAAiFIgCgSQgBgFgDgCQgDgCgIAAIAAgGIASgBQAJgCAEgCIADAAIAABPQAJgHAIgEQAIgEAJAAQAVAAAOAPQAOAOAAAYQAAAXgOAQQgOAPgXAAQgKAAgIgFgAgJgKQgHAEgIAGIAAAnQAAAQACAHQACAGAIAGQAHAGAKAAQAPABAKgNQAJgNAAgZQAAgWgIgLQgJgMgPAAQgHAAgJAFg");
	this.shape_59.setTransform(-203.1,106.3);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgaBUIAAgFIAEAAQAJAAADgDQACgDABgDIAAgVIAAgeQAAgRgCgDQgBgEgDgBIgKgBIgDAAIAAgGQAWgCALgEIADAAIAABEIAAAVQABAEADACQADADAHAAIADAAIAAAFgAgJg9QgEgDAAgGQAAgFAEgEQADgEAGAAQAEAAAEAEQADAEAAAFQAAAGgDADQgEAEgEAAQgGAAgDgEg");
	this.shape_60.setTransform(-212.5,106.1);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AgoA0IAAgFIACAAQAHgBAEgCQADgCABgDIAAgWIAAgbIAAgUQgBgEgDgCQgDgCgIgBIgCAAIAAgFQALgBASgGQAEAKAAAPQAFgKAIgIQAJgHAJAAQAJAAAEAFQAEAFABAFQAAAEgCACQgDADgEAAQgFAAgEgJQgCgGgFAAQgEAAgIAHQgGAHgCAIQgCAHAAANIAAARIAAAVQABAEACACQADADAHAAIAEAAIAAAFg");
	this.shape_61.setTransform(-219.8,109.3);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgIA/QgGgGgCgHQgBgHgBgRIAAg4IgOAAIAAgFQAKAAAIgJQAIgIACgPIAEAAIAAAgIAdAAIAAAFIgdAAIAAA8IAAATQABAEAFADQAEADAEAAQAIAAAHgKIAEADQgEAIgHAEQgHAEgIAAQgIAAgHgFg");
	this.shape_62.setTransform(-228,108.1);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AAJA0IAAgFIACAAQAJAAADgDQADgDAAgDIAAgVIAAgeIgBgRQgBgFgFgEQgFgEgIgBQgIAAgIAGQgIAGgHAKIAAAnIAAAWQABADADACQADACAJABIAAAFIgyAAIAAgFQAIgBADgCQAEgBABgDIAAgXIAAgcIAAgVQgBgEgDgCQgEgCgIAAIAAgGQANgBAOgEIADAAQADAIABANQAIgLAKgFQAJgFAKAAQAMAAAIAFQAHAFADAIQACAGAAAPIAAAdIAAAWQABADADACQAEACAIABIAAAFg");
	this.shape_63.setTransform(-238.5,109.3);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("AglAoQgPgPAAgZQAAgWAPgQQAPgPAWAAQAWAAAQAPQAPAQAAAWQAAAZgQAPQgPAOgWAAQgVAAgQgOgAgYgkQgIALAAAaQAAAaAIALQAJAKAPAAQAQAAAIgKQAJgLAAgaQAAgagJgLQgIgMgQAAQgPAAgJAMg");
	this.shape_64.setTransform(-251.4,109.5);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AgfAoQgOgPAAgYQAAgYAQgPQAQgPAUAAQANAAAKAFQAMAHAAAIQgBACgCADQgCADgDAAQgJAAgBgJQgCgIgDgCQgDgDgJAAQgPAAgJALQgIAMAAAWQAAAXAJANQAJANARABQAYAAAGgXIAGAAQgIAdgiAAQgUAAgPgOg");
	this.shape_65.setTransform(-262.8,109.5);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AglBKQAAgJANgFQAHgEADgCQACgCADgHIAJgXIglhQQgFgKgEgDQgDgDgIAAIAAgGIAuAAIAAAGQgMAAAAAFIAFAMIAaA5IAXg2IAFgOQAAgGgNAAIAAgGIAjAAIAAAGQgIAAgEAEQgEAEgFAOIgsBqQgGAQgFAFQgFAGgGAAQgIAAAAgHg");
	this.shape_66.setTransform(-64.4,76.9);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFFFF").s().p("AgpA0IAAgGIAEAAQAGAAAEgBQADgDAAgEIABgUIAAgbIgBgVQAAgEgDgCQgDgDgHAAIgEAAIAAgFQAMgBATgGQADAJAAARQAFgMAIgGQAKgIAJAAQAHAAAFAFQAFAFAAAGQgBADgCACQgCADgDAAQgHAAgDgJQgCgGgEAAQgFAAgIAHQgGAHgDAIQgCAIAAAMIAAASIABAUQAAAEAEACQABACAJAAIADAAIAAAGg");
	this.shape_67.setTransform(-74.3,73.7);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFFFF").s().p("AgHA/QgHgGgCgHQgCgHABgRIAAg4IgPAAIAAgFQAKAAAIgJQAIgIACgPIAEAAIAAAgIAdAAIAAAFIgdAAIAAA8IAAATQABAEAEADQAFADAEAAQAJAAAGgKIAEADQgEAIgHAEQgHAEgIAAQgIAAgGgFg");
	this.shape_68.setTransform(-82.5,72.5);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFFFF").s().p("AgVArQgDAEgCAGIgGAAIAAghIAGAAQAHAdAVAAQAJAAAFgGQAFgGgBgGQAAgIgEgFQgGgFgNgHQgPgGgHgIQgGgHAAgKQAAgKAHgJQAHgJANAAQAMAAAJAKQACgBACgIIAFAAIAAAgIgFAAQgCgMgHgHQgHgIgJAAQgHgBgFAFQgEAFAAAFQAAAHAFAFQAFAEAMAHQAVAJAFAJQAFAJAAAIQAAANgJAIQgJAIgNAAQgMAAgLgLg");
	this.shape_69.setTransform(-90.5,73.9);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFFFF").s().p("AAfA0QgEgHgBgRQgHAMgKAGQgJAGgLAAQgKAAgHgEQgIgFgDgHQgDgGAAgOIAAghIgBgVQAAgEgDgCQgEgCgIAAIAAgFIAiAAIAABEIABAQQABAEAFAEQAFADAHAAQAIAAAJgHQAIgFADgHQADgIAAgMIAAgWIAAgUQAAgDgDgDQgDgDgIAAIgDAAIAAgFIAjAAIAABBIAAAUQABAEADADQADABAIAAIAAAGQgSAAgJAEg");
	this.shape_70.setTransform(-101.3,74.1);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFFFF").s().p("AAbBEQgKAJgJAFQgIAEgLAAQgTAAgOgQQgPgPAAgXQAAgYAPgOQAOgPAUAAQAKAAAJADQAJAFAIAHIAAgoIgBgUQAAgDgEgDQgCgCgJAAIgCAAIAAgFQAPgBARgFIADAAIAACGIABAVQAAAEADACQADABAKAAIAAAGQgTAAgNADQgCgGABgMgAgdgDQgKAKABAYQgBAZAKALQAKALANAAQAJAAAHgDQAIgFAIgJIAAg9QgIgGgJgEQgIgDgHAAQgOAAgJAKg");
	this.shape_71.setTransform(-113.9,70.7);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFFFF").s().p("AAJA0IAAgGIACAAQAJAAADgCQADgCAAgEIAAgUIAAggIgBgRQgBgEgFgFQgFgDgIAAQgIAAgIAFQgIAFgHALIAAAoIAAAVQABAEADACQADABAJAAIAAAGIgyAAIAAgGQAIAAADgBQAEgCABgEIAAgVIAAgdIAAgVQgBgEgDgCQgEgCgIAAIAAgFQANgCAOgEIADAAQADAHABANQAIgJAKgGQAJgFAKAAQAMAAAIAFQAHAFADAHQACAIAAANIAAAfIAAAVQABAEADACQAEABAIAAIAAAGg");
	this.shape_72.setTransform(-127.3,73.7);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#FFFFFF").s().p("AgaBUIAAgGIAEAAQAJAAADgCQACgCABgEIAAgUIAAgfQAAgRgCgDQgBgEgDgBIgKgBIgDAAIAAgFQAWgCALgFIADAAIAABFIAAAUQABAEADACQADACAHAAIADAAIAAAGgAgJg9QgEgEAAgFQAAgGAEgDQADgEAGAAQAEAAAEAEQADADAAAGQAAAFgDAEQgEAEgEAAQgGAAgDgEg");
	this.shape_73.setTransform(-137.2,70.5);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFFFFF").s().p("AglBKQAAgJANgFQAHgEADgCQACgCADgHIAJgXIglhQQgFgKgEgDQgDgDgIAAIAAgGIAuAAIAAAGQgMAAAAAFIAFAMIAaA5IAXg2IAFgOQAAgGgNAAIAAgGIAjAAIAAAGQgIAAgEAEQgEAEgFAOIgsBqQgGAQgFAFQgFAGgGAAQgIAAAAgHg");
	this.shape_74.setTransform(-152.3,76.9);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#FFFFFF").s().p("AgpBKQgOgJAAgNQAAgIAEgEQAEgFAHAAIADAAQgHAJAAAJQAAALAKAHQAKAHAUAAQARAAAKgHQAKgIAAgLQAAgMgJgFQgJgFgVgBQgbgBgIgFQgHgFgBgJQAAgPAXgEQgMgHgFgIQgHgJABgLQgBgPAMgLQANgLAQAAQATAAAMANQALgMAKAAQAHAAADAEQADADAAADQAAAJgHAAQgEAAgEgFQgCgFgDAAQgFAAgFAGQAGAKAAALQAAAPgKALQgLAMgYABQgaAAAAAJQAAAFAHABQAFACASABQAUABALADQALADAGAIQAHAIAAAMQAAAQgOAKQgNAKgYAAQgWAAgOgJgAgZhEQgGAJAAARQAAAPAGAIQAHAHAJAAQAJAAAGgHQAIgHgBgSQAAgSgHgHQgGgHgJAAQgLAAgFAIg");
	this.shape_75.setTransform(-163.3,76.7);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#FFFFFF").s().p("AgpA0IAAgGIAEAAQAGAAAEgBQADgDAAgEIABgUIAAgbIgBgVQAAgEgDgCQgDgDgHAAIgEAAIAAgFQAMgBATgGQADAJAAARQAFgMAIgGQAKgIAJAAQAHAAAFAFQAFAFgBAGQAAADgCACQgCADgDAAQgHAAgDgJQgCgGgEAAQgGAAgHAHQgGAHgDAIQgCAIAAAMIAAASIABAUQAAAEAEACQABACAJAAIADAAIAAAGg");
	this.shape_76.setTransform(-173.8,73.7);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#FFFFFF").s().p("AgTAvQgLgGgHgMQgHgLAAgRQAAgXAOgPQANgQAUAAQAUAAALAMQAKAMABAOIhFAAIAAAKQAAAaAIAOQAIAMAQAAQAWABAJgVIAGAAQgEANgLAHQgMAHgOAAQgLAAgMgHgAgXgUIAvAAIAAgFQAAgLgGgGQgGgFgKAAQgVAAgEAbg");
	this.shape_77.setTransform(-184.2,73.9);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#FFFFFF").s().p("AAJA0IAAgGIACAAQAJAAADgCQADgCAAgEIAAgUIAAggIgBgRQgBgEgFgFQgFgDgIAAQgIAAgIAFQgIAFgHALIAAAoIAAAVQABAEADACQADABAJAAIAAAGIgyAAIAAgGQAIAAADgBQAEgCABgEIAAgVIAAgdIAAgVQgBgEgDgCQgEgCgIAAIAAgFQANgCAOgEIADAAQADAHABANQAIgJAKgGQAJgFAKAAQAMAAAIAFQAHAFADAHQACAIAAANIAAAfIAAAVQABAEADACQAEABAIAAIAAAGg");
	this.shape_78.setTransform(-196.2,73.7);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#FFFFFF").s().p("AgTAvQgLgGgHgMQgHgLAAgRQAAgXAOgPQANgQAUAAQAUAAALAMQAKAMABAOIhFAAIAAAKQAAAaAIAOQAIAMAQAAQAWABAJgVIAGAAQgEANgLAHQgMAHgOAAQgLAAgMgHgAgXgUIAvAAIAAgFQAAgLgGgGQgGgFgKAAQgVAAgEAbg");
	this.shape_79.setTransform(-208.3,73.9);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#FFFFFF").s().p("AgTAvQgLgGgHgMQgHgLAAgRQAAgXAOgPQANgQAUAAQAUAAALAMQAKAMABAOIhFAAIAAAKQAAAaAIAOQAIAMAQAAQAWABAJgVIAGAAQgEANgLAHQgMAHgOAAQgLAAgMgHgAgXgUIAvAAIAAgFQAAgLgGgGQgGgFgKAAQgVAAgEAbg");
	this.shape_80.setTransform(-225.5,73.9);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#FFFFFF").s().p("AAJBUIAAgGIACAAQAJAAADgCQADgCAAgEIAAgUIAAgfQAAgMgBgGQgCgFgFgEQgFgDgJAAQgIAAgIAFQgHAGgGAJIAAApIABAUQAAAEADADQADABAJAAIAAAGIgzAAIAAgGIADAAQAIAAADgCQADgCAAgEIABgUIAAhjQAAgPgDgEQgDgEgLAAIAAgFQATAAAMgGIADAAIAABTQAHgIAKgGQAIgFAKAAQANAAAIAFQAIAGACAHQADAGAAARIAAAcIABAVQAAAEADACQAEABAJAAIAAAGg");
	this.shape_81.setTransform(-237.5,70.5);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFFFF").s().p("AgpBTIAAgGIAJAAQAKAAAFgDQAEgCABgGQABgGAAgUIAAh0IgZAAQgPAAgGABQgGACgEAIQgFAHgCAQIgGAAIAAgoICgAAIABAoIgFAAQgDgQgEgIQgGgHgFgBQgGgCgOAAIgaAAIAAB0IABAZQABAGAEADQAEADALAAIAIAAIAAAGg");
	this.shape_82.setTransform(-252.8,70.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(-286.9,54.4,253.6,210.6), null);


(lib.redcircle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,55,66,0.698)").s().p("AswMxQlSlSAAnfQAAndFSlTQFTlSHdAAQHfAAFSFSQFSFTAAHdQAAHflSFSQlSFSnfAAQndAAlTlSg");
	this.shape.setTransform(-41.9,78.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.redcircle, new cjs.Rectangle(-157.4,-37,231,231), null);


(lib.blue = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,192,174,0.698)").s().p("AswMxQlSlSAAnfQAAndFSlTQFTlSHdAAQHfAAFSFSQFSFTAAHdQAAHflSFSQlSFSnfAAQndAAlTlSg");
	this.shape.setTransform(-41.9,89.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blue, new cjs.Rectangle(-157.4,-26.2,231,231), null);


// stage content:
(lib._728x90_change = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// logos
	this.instance = new lib.LogoWhite();
	this.instance.parent = this;
	this.instance.setTransform(596,23,0.751,0.751);

	this.instance_1 = new lib.SHAREDFUTURE();
	this.instance_1.parent = this;
	this.instance_1.setTransform(454,43,0.908,0.908);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(327));

	// Layer_5
	this.instance_2 = new lib.Symbol3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(304,39.1,0.469,0.469,0,0,0,151.6,37.9);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(258).to({_off:false},0).wait(1).to({regX:-120.4,regY:33.2,x:176.4,y:36.9,alpha:0.001},0).wait(1).to({scaleX:0.47,scaleY:0.47,x:176.3,alpha:0.005},0).wait(1).to({scaleX:0.47,scaleY:0.47,x:176.2,y:37,alpha:0.011},0).wait(1).to({scaleX:0.48,scaleY:0.48,x:176.1,alpha:0.021},0).wait(1).to({scaleX:0.48,scaleY:0.48,x:175.9,y:37.1,alpha:0.035},0).wait(1).to({scaleX:0.48,scaleY:0.48,x:175.5,y:37.3,alpha:0.054},0).wait(1).to({scaleX:0.49,scaleY:0.49,x:175.1,y:37.4,alpha:0.079},0).wait(1).to({scaleX:0.5,scaleY:0.5,x:174.6,y:37.7,alpha:0.111},0).wait(1).to({scaleX:0.51,scaleY:0.51,x:173.9,y:38,alpha:0.153},0).wait(1).to({scaleX:0.53,scaleY:0.53,x:173,y:38.4,alpha:0.204},0).wait(1).to({scaleX:0.54,scaleY:0.54,x:172,y:38.8,alpha:0.267},0).wait(1).to({scaleX:0.56,scaleY:0.56,x:170.8,y:39.4,alpha:0.338},0).wait(1).to({scaleX:0.59,scaleY:0.59,x:169.6,y:40,alpha:0.414},0).wait(1).to({scaleX:0.61,scaleY:0.61,x:168.4,y:40.5,alpha:0.488},0).wait(1).to({scaleX:0.63,scaleY:0.63,x:167.2,y:41,alpha:0.556},0).wait(1).to({scaleX:0.64,scaleY:0.64,x:166.2,y:41.5,alpha:0.617},0).wait(1).to({scaleX:0.66,scaleY:0.66,x:165.4,y:41.9,alpha:0.669},0).wait(1).to({scaleX:0.67,scaleY:0.67,x:164.6,y:42.2,alpha:0.715},0).wait(1).to({scaleX:0.68,scaleY:0.68,x:163.9,y:42.4,alpha:0.755},0).wait(1).to({scaleX:0.69,scaleY:0.69,x:163.4,y:42.7,alpha:0.789},0).wait(1).to({scaleX:0.7,scaleY:0.7,x:162.9,y:43,alpha:0.819},0).wait(1).to({scaleX:0.71,scaleY:0.71,x:162.4,y:43.1,alpha:0.846},0).wait(1).to({scaleX:0.71,scaleY:0.71,x:162.1,y:43.3,alpha:0.869},0).wait(1).to({scaleX:0.72,scaleY:0.72,x:161.7,y:43.5,alpha:0.889},0).wait(1).to({scaleX:0.72,scaleY:0.72,x:161.4,y:43.6,alpha:0.907},0).wait(1).to({scaleX:0.73,scaleY:0.73,x:161.1,y:43.7,alpha:0.922},0).wait(1).to({scaleX:0.73,scaleY:0.73,x:160.9,y:43.8,alpha:0.936},0).wait(1).to({scaleX:0.74,scaleY:0.74,x:160.7,y:43.9,alpha:0.948},0).wait(1).to({scaleX:0.74,scaleY:0.74,x:160.6,y:44,alpha:0.958},0).wait(1).to({scaleX:0.74,scaleY:0.74,x:160.4,alpha:0.967},0).wait(1).to({scaleX:0.74,scaleY:0.74,x:160.3,y:44.1,alpha:0.975},0).wait(1).to({scaleX:0.75,scaleY:0.75,x:160.2,y:44.2,alpha:0.981},0).wait(1).to({scaleX:0.75,scaleY:0.75,x:160.1,alpha:0.987},0).wait(1).to({scaleX:0.75,scaleY:0.75,x:160,alpha:0.991},0).wait(1).to({scaleX:0.75,scaleY:0.75,alpha:0.994},0).wait(1).to({scaleX:0.75,scaleY:0.75,x:159.9,y:44.3,alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:151.5,regY:37.6,scaleX:0.75,scaleY:0.75,x:364.1,y:47.8},0).wait(30));

	// Layer_3
	this.instance_3 = new lib.Symbol1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(364,52.8,0.751,0.751,0,0,0,69.3,119.2);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(14).to({_off:false},0).to({alpha:1},25).wait(109).to({regX:-161,regY:144.7,x:191.2,y:71.9},0).wait(2).to({y:71.8},0).wait(1).to({y:71.6},0).wait(1).to({y:71.4},0).wait(1).to({y:71.1},0).wait(1).to({y:70.7},0).wait(1).to({y:70.3},0).wait(1).to({y:69.7},0).wait(1).to({y:69},0).wait(1).to({y:68.1},0).wait(1).to({y:67.1},0).wait(1).to({y:65.7},0).wait(1).to({y:64},0).wait(1).to({y:61.6},0).wait(1).to({y:58.2},0).wait(1).to({y:52.7},0).wait(1).to({y:43.9},0).wait(1).to({y:37},0).wait(1).to({y:32.9},0).wait(1).to({y:30.2},0).wait(1).to({y:28.4},0).wait(1).to({y:26.9},0).wait(1).to({y:25.8},0).wait(1).to({y:24.9},0).wait(1).to({y:24.2},0).wait(1).to({y:23.7},0).wait(1).to({y:23.3},0).wait(1).to({y:22.9},0).wait(1).to({y:22.7},0).wait(1).to({y:22.5},0).wait(1).to({y:22.4},0).wait(1).to({y:22.3},0).wait(1).to({regX:69.3,regY:119.2,x:364,y:3.1},0).wait(66).to({alpha:0},23,cjs.Ease.get(-1)).to({_off:true},2).wait(55));

	// Black (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_94 = new cjs.Graphics().p("AAYEWQEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_147 = new cjs.Graphics().p("AAYEWQEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_148 = new cjs.Graphics().p("AAYEWQEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_149 = new cjs.Graphics().p("AAYEWQEXijFZAAQFaAAEXCjQkXCjlaAAQlZAAkXijg");
	var mask_graphics_150 = new cjs.Graphics().p("AAYEVQEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_151 = new cjs.Graphics().p("AAYEVQEXijFZAAQFaAAEXCjQkXCilaAAQlZAAkXiig");
	var mask_graphics_152 = new cjs.Graphics().p("AAYETQEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_153 = new cjs.Graphics().p("AAYESQEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_154 = new cjs.Graphics().p("AAYEQQEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_155 = new cjs.Graphics().p("AAYEOQEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_156 = new cjs.Graphics().p("AAYELQEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_157 = new cjs.Graphics().p("AAYEIQEXijFZAAQFaAAEXCjQkXCjlaAAQlZAAkXijg");
	var mask_graphics_158 = new cjs.Graphics().p("AAYEEQEXijFZAAQFaAAEXCjQkXCilaAAQlZAAkXiig");
	var mask_graphics_159 = new cjs.Graphics().p("AAYD+QEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_160 = new cjs.Graphics().p("AAYD4QEXijFZAAQFaAAEXCjQkXCjlaAAQlZAAkXijg");
	var mask_graphics_161 = new cjs.Graphics().p("AAYDvQEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_162 = new cjs.Graphics().p("AAYDkQEXijFZAAQFaAAEXCjQkXCilaAAQlZAAkXiig");
	var mask_graphics_163 = new cjs.Graphics().p("AAYDTQEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_164 = new cjs.Graphics().p("AAYC4QEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_165 = new cjs.Graphics().p("AAYCNQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_166 = new cjs.Graphics().p("AAYBrQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_167 = new cjs.Graphics().p("AAYBXQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_168 = new cjs.Graphics().p("AAYBKQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_169 = new cjs.Graphics().p("AAYBBQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_170 = new cjs.Graphics().p("AAYA6QEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_171 = new cjs.Graphics().p("AAYA1QEXiiFZAAQFaAAEXCiQkXCilaAAQlZAAkXiig");
	var mask_graphics_172 = new cjs.Graphics().p("AAYAwQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_173 = new cjs.Graphics().p("AAYAtQEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_174 = new cjs.Graphics().p("AAYAqQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_175 = new cjs.Graphics().p("AAYAoQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_176 = new cjs.Graphics().p("AAYAmQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_177 = new cjs.Graphics().p("AAYAlQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_178 = new cjs.Graphics().p("AAYAkQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_179 = new cjs.Graphics().p("AAYAkQEXiiFZAAQFaAAEXCiQkXCjlaAAQlZAAkXijg");
	var mask_graphics_180 = new cjs.Graphics().p("AAYAjQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_181 = new cjs.Graphics().p("AAYAjQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_247 = new cjs.Graphics().p("AAYAjQEXihFZAAQFaAAEXChQkXCjlaAAQlZAAkXijg");
	var mask_graphics_248 = new cjs.Graphics().p("AAYAjQEWihFaAAQFaAAEXChQkXCjlaAAQlaAAkWijg");
	var mask_graphics_249 = new cjs.Graphics().p("AAWAjQEXiiFbAAQFaAAEXCiQkXCjlaAAQlbAAkXijg");
	var mask_graphics_250 = new cjs.Graphics().p("AAUAjQEXiiFcAAQFbAAEYCiQkYCklbAAQlcAAkXikg");
	var mask_graphics_251 = new cjs.Graphics().p("AAQAjQEZijFcAAQFdAAEZCjQkZCkldAAQlcAAkZikg");
	var mask_graphics_252 = new cjs.Graphics().p("AALAjQEaikFeAAQFfAAEaCkQkaCllfAAQleAAkailg");
	var mask_graphics_253 = new cjs.Graphics().p("AAFAjQEbilFhAAQFgAAEcClQkcCmlgAAQlhAAkbimg");
	var mask_graphics_254 = new cjs.Graphics().p("AgCAiQEdilFjAAQFjAAEeClQkeColjAAQljAAkdiog");
	var mask_graphics_255 = new cjs.Graphics().p("AgMAiQEginFmAAQFmAAEhCnQkhCplmAAQlmAAkgipg");
	var mask_graphics_256 = new cjs.Graphics().p("AgXAiQEiipFqAAQFrAAEjCpQkjCqlrAAQlqAAkiiqg");
	var mask_graphics_257 = new cjs.Graphics().p("AglAhQEmirFvAAQFvAAEnCrQknCtlvAAQlvAAkmitg");
	var mask_graphics_258 = new cjs.Graphics().p("Ag1AhQEriuF0AAQF0AAEsCuQksCvl0AAQl0AAkrivg");
	var mask_graphics_259 = new cjs.Graphics().p("AhIAgQEwiwF7AAQF6AAExCwQkxCzl6AAQl7AAkwizg");
	var mask_graphics_260 = new cjs.Graphics().p("AheAgQE2i1GCAAQGCAAE3C1Qk3C2mCAAQmCAAk2i2g");
	var mask_graphics_261 = new cjs.Graphics().p("Ah3AfQE9i4GKAAQGLAAE+C4Qk+C6mLAAQmKAAk9i6g");
	var mask_graphics_262 = new cjs.Graphics().p("AiVAeQFFi9GVAAQGUAAFGC9QlGC/mUAAQmVAAlFi/g");
	var mask_graphics_263 = new cjs.Graphics().p("Ai4AdQFOjDGhAAQGhAAFPDDQlPDEmhAAQmhAAlOjEg");
	var mask_graphics_264 = new cjs.Graphics().p("AjhAcQFZjJGvAAQGuAAFbDJQlbDLmuAAQmvAAlZjLg");
	var mask_graphics_265 = new cjs.Graphics().p("AkTAaQFnjRG/AAQHAAAFoDRQloDTnAAAQm/AAlnjTg");
	var mask_graphics_266 = new cjs.Graphics().p("AlQAZQF4jbHUAAQHUAAF4DbQl4DcnUAAQnUAAl4jcg");
	var mask_graphics_267 = new cjs.Graphics().p("AmbAXQGNjnHsAAQHuAAGNDnQmNDonuAAQnsAAmNjog");
	var mask_graphics_268 = new cjs.Graphics().p("An8AUQGnj3INAAQIPAAGoD3QmoD3oPAAQoNAAmnj3g");
	var mask_graphics_269 = new cjs.Graphics().p("AqBAQQHMkLI6AAQI7AAHMELQnMENo7AAQo6AAnMkNg");
	var mask_graphics_270 = new cjs.Graphics().p("AtDAKQIBkqJ7AAQJ9AAIBEqQoBEsp9AAQp7AAoBksg");
	var mask_graphics_271 = new cjs.Graphics().p("AxeACQJNlXLcAAQLdAAJNFXQpNFZrdAAQrcAApNlZg");
	var mask_graphics_272 = new cjs.Graphics().p("A12AAQKamEM6AAQM7AAKaGEQqaGFs7AAQs6AAqamFg");
	var mask_graphics_273 = new cjs.Graphics().p("A4yAAQLOmiN5AAQN7AALMGiQrMGjt7AAQt5AArOmjg");
	var mask_graphics_274 = new cjs.Graphics().p("A6UAAQLwm2OkAAQOmAALvG2QrvG3umAAQukAArwm3g");
	var mask_graphics_275 = new cjs.Graphics().p("A7NAAQMJnFPEAAQPFAAMJHFQsJHGvFAAQvEAAsJnGg");
	var mask_graphics_276 = new cjs.Graphics().p("A75AAQMdnQPcAAQPeAAMcHQQscHRveAAQvcAAsdnRg");
	var mask_graphics_277 = new cjs.Graphics().p("A8cAAQMsnZPwAAQPxAAMsHZQssHavxAAQvwAAssnag");
	var mask_graphics_278 = new cjs.Graphics().p("A84AAQM5nhP/AAQQBAAM4HhQs4HiwBAAQv/AAs5nig");
	var mask_graphics_279 = new cjs.Graphics().p("A9QAAQNEnnQMAAQQOAANDHnQtDHowOAAQwMAAtEnog");
	var mask_graphics_280 = new cjs.Graphics().p("A9jAAQNMnsQXAAQQZAANLHsQtLHtwZAAQwXAAtMntg");
	var mask_graphics_281 = new cjs.Graphics().p("A90AAQNUnwQgAAQQiAANTHwQtTHxwiAAQwgAAtUnxg");
	var mask_graphics_282 = new cjs.Graphics().p("A+CAAQNan0QoAAQQpAANaH0QtaH1wpAAQwoAAtan1g");
	var mask_graphics_283 = new cjs.Graphics().p("A+OAAQNfn3QvAAQQwAANfH3QtfH4wwAAQwvAAtfn4g");
	var mask_graphics_284 = new cjs.Graphics().p("A+YAAQNkn6Q0AAQQ2AANjH6QtjH7w2AAQw0AAtkn7g");
	var mask_graphics_285 = new cjs.Graphics().p("A+gAAQNnn8Q5AAQQ6AANnH8QtnH9w6AAQw5AAtnn9g");
	var mask_graphics_286 = new cjs.Graphics().p("A+nAAQNqn+Q9AAQQ+AANqH+QtqH/w+AAQw9AAtqn/g");
	var mask_graphics_287 = new cjs.Graphics().p("A+sAAQNsn/RAAAQRBAANsH/QtsIAxBAAQxAAAtsoAg");
	var mask_graphics_288 = new cjs.Graphics().p("A+xAAQNvoARCAAQREAANuIAQtuIBxEAAQxCAAtvoBg");
	var mask_graphics_289 = new cjs.Graphics().p("A+0AAQNwoBREAAQRGAANvIBQtvICxGAAQxEAAtwoCg");
	var mask_graphics_290 = new cjs.Graphics().p("A+3AAQNxoCRGAAQRHAANxICQtxIDxHAAQxGAAtxoDg");
	var mask_graphics_291 = new cjs.Graphics().p("A+5AAQNyoCRHAAQRIAANyICQtyIDxIAAQxHAAtyoDg");
	var mask_graphics_292 = new cjs.Graphics().p("A+6AAQNzoDRHAAQRIAANzIDQtzIExIAAQxHAAtzoEg");
	var mask_graphics_293 = new cjs.Graphics().p("A+6AAQNzoDRHAAQRJAANyIDQtyIExJAAQxHAAtzoEg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(94).to({graphics:mask_graphics_94,x:127.3,y:44.1}).wait(53).to({graphics:mask_graphics_147,x:127.3,y:44.1}).wait(1).to({graphics:mask_graphics_148,x:127.3,y:44.1}).wait(1).to({graphics:mask_graphics_149,x:127.3,y:44.1}).wait(1).to({graphics:mask_graphics_150,x:127.3,y:44}).wait(1).to({graphics:mask_graphics_151,x:127.3,y:43.9}).wait(1).to({graphics:mask_graphics_152,x:127.3,y:43.8}).wait(1).to({graphics:mask_graphics_153,x:127.3,y:43.7}).wait(1).to({graphics:mask_graphics_154,x:127.3,y:43.5}).wait(1).to({graphics:mask_graphics_155,x:127.3,y:43.3}).wait(1).to({graphics:mask_graphics_156,x:127.3,y:43}).wait(1).to({graphics:mask_graphics_157,x:127.3,y:42.7}).wait(1).to({graphics:mask_graphics_158,x:127.3,y:42.2}).wait(1).to({graphics:mask_graphics_159,x:127.3,y:41.7}).wait(1).to({graphics:mask_graphics_160,x:127.3,y:41.1}).wait(1).to({graphics:mask_graphics_161,x:127.3,y:40.2}).wait(1).to({graphics:mask_graphics_162,x:127.3,y:39}).wait(1).to({graphics:mask_graphics_163,x:127.3,y:37.4}).wait(1).to({graphics:mask_graphics_164,x:127.3,y:34.7}).wait(1).to({graphics:mask_graphics_165,x:127.3,y:30.4}).wait(1).to({graphics:mask_graphics_166,x:127.3,y:27}).wait(1).to({graphics:mask_graphics_167,x:127.3,y:25}).wait(1).to({graphics:mask_graphics_168,x:127.3,y:23.7}).wait(1).to({graphics:mask_graphics_169,x:127.3,y:22.8}).wait(1).to({graphics:mask_graphics_170,x:127.3,y:22.1}).wait(1).to({graphics:mask_graphics_171,x:127.3,y:21.5}).wait(1).to({graphics:mask_graphics_172,x:127.3,y:21.1}).wait(1).to({graphics:mask_graphics_173,x:127.3,y:20.8}).wait(1).to({graphics:mask_graphics_174,x:127.3,y:20.5}).wait(1).to({graphics:mask_graphics_175,x:127.3,y:20.3}).wait(1).to({graphics:mask_graphics_176,x:127.3,y:20.1}).wait(1).to({graphics:mask_graphics_177,x:127.3,y:20}).wait(1).to({graphics:mask_graphics_178,x:127.3,y:19.9}).wait(1).to({graphics:mask_graphics_179,x:127.3,y:19.9}).wait(1).to({graphics:mask_graphics_180,x:127.3,y:19.8}).wait(1).to({graphics:mask_graphics_181,x:127.3,y:19.8}).wait(66).to({graphics:mask_graphics_247,x:127.3,y:19.8}).wait(1).to({graphics:mask_graphics_248,x:127.3,y:19.8}).wait(1).to({graphics:mask_graphics_249,x:127.3,y:19.8}).wait(1).to({graphics:mask_graphics_250,x:127.4,y:19.9}).wait(1).to({graphics:mask_graphics_251,x:127.5,y:19.9}).wait(1).to({graphics:mask_graphics_252,x:127.6,y:20}).wait(1).to({graphics:mask_graphics_253,x:127.7,y:20.1}).wait(1).to({graphics:mask_graphics_254,x:127.9,y:20.2}).wait(1).to({graphics:mask_graphics_255,x:128.1,y:20.3}).wait(1).to({graphics:mask_graphics_256,x:128.3,y:20.4}).wait(1).to({graphics:mask_graphics_257,x:128.6,y:20.6}).wait(1).to({graphics:mask_graphics_258,x:129,y:20.8}).wait(1).to({graphics:mask_graphics_259,x:129.4,y:21.1}).wait(1).to({graphics:mask_graphics_260,x:129.9,y:21.4}).wait(1).to({graphics:mask_graphics_261,x:130.5,y:21.7}).wait(1).to({graphics:mask_graphics_262,x:131.1,y:22.1}).wait(1).to({graphics:mask_graphics_263,x:131.9,y:22.5}).wait(1).to({graphics:mask_graphics_264,x:132.8,y:23.1}).wait(1).to({graphics:mask_graphics_265,x:133.9,y:23.7}).wait(1).to({graphics:mask_graphics_266,x:135.2,y:24.5}).wait(1).to({graphics:mask_graphics_267,x:136.9,y:25.5}).wait(1).to({graphics:mask_graphics_268,x:139.1,y:26.7}).wait(1).to({graphics:mask_graphics_269,x:142,y:28.5}).wait(1).to({graphics:mask_graphics_270,x:146.3,y:31}).wait(1).to({graphics:mask_graphics_271,x:152.5,y:34.7}).wait(1).to({graphics:mask_graphics_272,x:158.7,y:37.7}).wait(1).to({graphics:mask_graphics_273,x:162.8,y:39.6}).wait(1).to({graphics:mask_graphics_274,x:162.8,y:40.9}).wait(1).to({graphics:mask_graphics_275,x:161.2,y:41.9}).wait(1).to({graphics:mask_graphics_276,x:160,y:42.6}).wait(1).to({graphics:mask_graphics_277,x:159,y:43.2}).wait(1).to({graphics:mask_graphics_278,x:158.3,y:43.6}).wait(1).to({graphics:mask_graphics_279,x:157.6,y:44}).wait(1).to({graphics:mask_graphics_280,x:157.1,y:44.4}).wait(1).to({graphics:mask_graphics_281,x:156.6,y:44.6}).wait(1).to({graphics:mask_graphics_282,x:156.2,y:44.9}).wait(1).to({graphics:mask_graphics_283,x:155.9,y:45.1}).wait(1).to({graphics:mask_graphics_284,x:155.6,y:45.2}).wait(1).to({graphics:mask_graphics_285,x:155.4,y:45.4}).wait(1).to({graphics:mask_graphics_286,x:155.2,y:45.5}).wait(1).to({graphics:mask_graphics_287,x:155,y:45.6}).wait(1).to({graphics:mask_graphics_288,x:154.9,y:45.6}).wait(1).to({graphics:mask_graphics_289,x:154.8,y:45.7}).wait(1).to({graphics:mask_graphics_290,x:154.7,y:45.7}).wait(1).to({graphics:mask_graphics_291,x:154.7,y:45.8}).wait(1).to({graphics:mask_graphics_292,x:154.7,y:45.8}).wait(1).to({graphics:mask_graphics_293,x:154.5,y:45.8}).wait(34));

	// eye
	this.instance_4 = new lib.Symbol2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(354.3,141.9,0.751,0.751,0,0,0,98.2,31.6);
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(94).to({_off:false},0).wait(1).to({regX:-117.8,regY:-12.5,x:192.2,y:108.7},0).wait(1).to({y:108.6},0).wait(1).to({y:108.4},0).wait(1).to({y:108.2},0).wait(1).to({y:107.8},0).wait(1).to({y:107.2},0).wait(1).to({y:106.6},0).wait(1).to({y:105.7},0).wait(1).to({x:192.3,y:104.6},0).wait(1).to({y:103.3},0).wait(1).to({y:101.7},0).wait(1).to({x:192.4,y:99.7},0).wait(1).to({x:192.5,y:97.5},0).wait(1).to({y:95},0).wait(1).to({x:192.6,y:92.5},0).wait(1).to({x:192.7,y:90.1},0).wait(1).to({y:87.9},0).wait(1).to({x:192.8,y:85.9},0).wait(1).to({y:84.1},0).wait(1).to({x:192.9,y:82.6},0).wait(1).to({y:81.2},0).wait(1).to({y:80},0).wait(1).to({x:193,y:78.9},0).wait(1).to({y:78},0).wait(1).to({y:77.1},0).wait(1).to({y:76.4},0).wait(1).to({y:75.7},0).wait(1).to({x:193.1,y:75.1},0).wait(1).to({y:74.6},0).wait(1).to({y:74.1},0).wait(1).to({y:73.7},0).wait(1).to({y:73.3},0).wait(1).to({y:73},0).wait(1).to({y:72.7},0).wait(1).to({y:72.5},0).wait(1).to({y:72.3},0).wait(1).to({y:72.1},0).wait(1).to({y:71.9},0).wait(1).to({y:71.8},0).wait(1).to({y:71.7},0).wait(1).to({y:71.6},0).wait(3).to({regX:98.2,regY:31.6,x:355.3,y:104.7},0).wait(9).to({x:354.3},0).wait(1).to({regX:-117.8,regY:-12.5,x:192.2,y:71.5},0).wait(2).to({y:71.4},0).wait(1).to({y:71.2},0).wait(1).to({y:71},0).wait(1).to({y:70.7},0).wait(1).to({y:70.4},0).wait(1).to({y:69.9},0).wait(1).to({y:69.4},0).wait(1).to({y:68.7},0).wait(1).to({y:67.9},0).wait(1).to({y:66.9},0).wait(1).to({y:65.5},0).wait(1).to({y:63.9},0).wait(1).to({y:61.6},0).wait(1).to({y:58.3},0).wait(1).to({y:53},0).wait(1).to({y:44.6},0).wait(1).to({y:37.9},0).wait(1).to({y:34},0).wait(1).to({y:31.4},0).wait(1).to({y:29.6},0).wait(1).to({y:28.2},0).wait(1).to({y:27.2},0).wait(1).to({y:26.3},0).wait(1).to({y:25.7},0).wait(1).to({y:25.1},0).wait(1).to({y:24.7},0).wait(1).to({y:24.4},0).wait(1).to({y:24.1},0).wait(1).to({y:24},0).wait(1).to({y:23.8},0).wait(2).to({regX:98.2,regY:31.6,x:354.3,y:56.9},0).wait(67).to({regX:-117.8,regY:-12.5,x:192.1,y:23.8},0).wait(1).to({scaleX:0.75,scaleY:0.75},0).wait(1).to({scaleX:0.75,scaleY:0.75},0).wait(1).to({scaleX:0.76,scaleY:0.76,x:192,y:23.9},0).wait(1).to({scaleX:0.76,scaleY:0.76,x:191.9},0).wait(1).to({scaleX:0.77,scaleY:0.77,x:191.8,y:24},0).wait(1).to({scaleX:0.77,scaleY:0.77,x:191.7},0).wait(1).to({scaleX:0.78,scaleY:0.78,x:191.5,y:24.2},0).wait(1).to({scaleX:0.79,scaleY:0.79,x:191.3},0).wait(1).to({scaleX:0.8,scaleY:0.8,x:191.1,y:24.4},0).wait(1).to({scaleX:0.81,scaleY:0.81,x:190.8,y:24.6},0).wait(1).to({scaleX:0.82,scaleY:0.82,x:190.5,y:24.8},0).wait(1).to({scaleX:0.84,scaleY:0.84,x:190.2,y:25},0).wait(1).to({scaleX:0.86,scaleY:0.86,x:189.7,y:25.2},0).wait(1).to({scaleX:0.88,scaleY:0.88,x:189.2,y:25.5},0).wait(1).to({scaleX:0.9,scaleY:0.9,x:188.6,y:25.9},0).wait(1).to({scaleX:0.93,scaleY:0.93,x:187.9,y:26.3},0).wait(1).to({scaleX:0.97,scaleY:0.97,x:187.1,y:26.8},0).wait(1).to({scaleX:1.01,scaleY:1.01,x:186.1,y:27.4},0).wait(1).to({scaleX:1.07,scaleY:1.07,x:184.8,y:28.2},0).wait(1).to({scaleX:1.14,scaleY:1.14,x:183.2,y:29.2},0).wait(1).to({scaleX:1.24,scaleY:1.24,x:180.9,y:30.5},0).wait(1).to({scaleX:1.38,scaleY:1.38,x:177.7,y:32.5},0).wait(1).to({scaleX:1.59,scaleY:1.59,x:172.9,y:35.4},0).wait(1).to({scaleX:1.8,scaleY:1.8,x:168.2,y:38.2},0).wait(1).to({scaleX:1.93,scaleY:1.93,x:165,y:40.1},0).wait(1).to({scaleX:2.03,scaleY:2.03,x:162.9,y:41.4},0).wait(1).to({scaleX:2.09,scaleY:2.09,x:161.3,y:42.3},0).wait(1).to({scaleX:2.15,scaleY:2.15,x:160.1,y:43.1},0).wait(1).to({scaleX:2.19,scaleY:2.19,x:159.1,y:43.7},0).wait(1).to({scaleX:2.22,scaleY:2.22,x:158.3,y:44.1},0).wait(1).to({scaleX:2.25,scaleY:2.25,x:157.7,y:44.5},0).wait(1).to({scaleX:2.28,scaleY:2.28,x:157.2,y:44.9},0).wait(1).to({scaleX:2.3,scaleY:2.3,x:156.7,y:45.1},0).wait(1).to({scaleX:2.31,scaleY:2.31,x:156.3,y:45.4},0).wait(1).to({scaleX:2.33,scaleY:2.33,x:156,y:45.6},0).wait(1).to({scaleX:2.34,scaleY:2.34,x:155.7,y:45.8},0).wait(1).to({scaleX:2.35,scaleY:2.35,x:155.5,y:45.9},0).wait(1).to({scaleX:2.36,scaleY:2.36,x:155.3,y:46},0).wait(1).to({scaleX:2.36,scaleY:2.36,x:155.2,y:46.1},0).wait(1).to({scaleX:2.37,scaleY:2.37,x:155,y:46.2},0).wait(1).to({scaleX:2.37,scaleY:2.37,x:154.9},0).wait(1).to({scaleX:2.38,scaleY:2.38,x:154.8,y:46.3},0).wait(1).to({scaleX:2.38,scaleY:2.38},0).wait(1).to({scaleX:2.38,scaleY:2.38},0).wait(1).to({regX:98.2,regY:31.6,x:668.6,y:151.3},0).wait(34));

	// blue
	this.instance_5 = new lib.blue();
	this.instance_5.parent = this;
	this.instance_5.setTransform(364.1,247.9,1.095,1.095,0,0,0,115.6,115.5);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(94).to({_off:false},0).wait(1).to({regX:-41.9,regY:89.3,x:191.7,y:219.1},0).wait(1).to({y:219},0).wait(1).to({y:218.8},0).wait(1).to({y:218.6},0).wait(1).to({y:218.2},0).wait(1).to({y:217.7},0).wait(1).to({y:217},0).wait(1).to({y:216.2},0).wait(1).to({y:215.1},0).wait(1).to({y:213.8},0).wait(1).to({y:212.2},0).wait(1).to({y:210.3},0).wait(1).to({y:208},0).wait(1).to({y:205.6},0).wait(1).to({y:203.2},0).wait(1).to({y:200.8},0).wait(1).to({y:198.6},0).wait(1).to({y:196.6},0).wait(1).to({y:194.9},0).wait(1).to({y:193.4},0).wait(1).to({y:192},0).wait(1).to({y:190.8},0).wait(1).to({y:189.8},0).wait(1).to({y:188.8},0).wait(1).to({y:188},0).wait(1).to({y:187.3},0).wait(1).to({y:186.6},0).wait(1).to({y:186},0).wait(1).to({y:185.5},0).wait(1).to({y:185},0).wait(1).to({y:184.6},0).wait(1).to({y:184.3},0).wait(1).to({y:183.9},0).wait(1).to({y:183.7},0).wait(1).to({y:183.4},0).wait(1).to({y:183.2},0).wait(1).to({y:183},0).wait(1).to({y:182.9},0).wait(1).to({y:182.8},0).wait(1).to({y:182.7},0).wait(1).to({y:182.6},0).wait(1).to({y:182.5},0).wait(2).to({regX:115.6,regY:115.5,x:364.1,y:211.2},0).wait(10).to({regX:-41.9,regY:89.3,x:191.7,y:182.5},0).wait(1).to({y:182.4},0).wait(1).to({y:182.3},0).wait(1).to({y:182.2},0).wait(1).to({y:181.9},0).wait(1).to({y:181.7},0).wait(1).to({y:181.3},0).wait(1).to({y:180.9},0).wait(1).to({y:180.3},0).wait(1).to({y:179.6},0).wait(1).to({y:178.8},0).wait(1).to({y:177.8},0).wait(1).to({y:176.4},0).wait(1).to({y:174.7},0).wait(1).to({y:172.4},0).wait(1).to({y:169.1},0).wait(1).to({y:163.8},0).wait(1).to({y:155.3},0).wait(1).to({y:148.5},0).wait(1).to({y:144.5},0).wait(1).to({y:142},0).wait(1).to({y:140.1},0).wait(1).to({y:138.7},0).wait(1).to({y:137.7},0).wait(1).to({y:136.8},0).wait(1).to({y:136.1},0).wait(1).to({y:135.6},0).wait(1).to({y:135.2},0).wait(1).to({y:134.8},0).wait(1).to({y:134.6},0).wait(1).to({y:134.4},0).wait(1).to({y:134.3},0).wait(1).to({y:134.2},0).wait(1).to({regX:115.6,regY:115.5,x:364.1,y:162.9},0).wait(67).to({regX:-41.9,regY:89.3,x:191.6,y:134.3},0).wait(1).to({scaleX:1.1,scaleY:1.1,y:134.4},0).wait(1).to({scaleX:1.1,scaleY:1.1,y:134.7},0).wait(1).to({scaleX:1.1,scaleY:1.1,x:191.5,y:135.2},0).wait(1).to({scaleX:1.11,scaleY:1.11,x:191.4,y:135.7},0).wait(1).to({scaleX:1.12,scaleY:1.12,x:191.3,y:136.5},0).wait(1).to({scaleX:1.12,scaleY:1.12,x:191.1,y:137.4},0).wait(1).to({scaleX:1.13,scaleY:1.13,x:191,y:138.6},0).wait(1).to({scaleX:1.15,scaleY:1.15,x:190.8,y:139.9},0).wait(1).to({scaleX:1.16,scaleY:1.16,x:190.5,y:141.5},0).wait(1).to({scaleX:1.18,scaleY:1.18,x:190.3,y:143.3},0).wait(1).to({scaleX:1.2,scaleY:1.2,x:190,y:145.6},0).wait(1).to({scaleX:1.22,scaleY:1.22,x:189.6,y:148.1},0).wait(1).to({scaleX:1.25,scaleY:1.25,x:189.1,y:151.1},0).wait(1).to({scaleX:1.28,scaleY:1.28,x:188.6,y:154.6},0).wait(1).to({scaleX:1.32,scaleY:1.32,x:188,y:158.6},0).wait(1).to({scaleX:1.36,scaleY:1.36,x:187.3,y:163.5},0).wait(1).to({scaleX:1.41,scaleY:1.41,x:186.5,y:169.3},0).wait(1).to({scaleX:1.48,scaleY:1.48,x:185.4,y:176.4},0).wait(1).to({scaleX:1.56,scaleY:1.56,x:184.1,y:185.2},0).wait(1).to({scaleX:1.66,scaleY:1.66,x:182.4,y:196.6},0).wait(1).to({scaleX:1.8,scaleY:1.8,x:180.1,y:212.1},0).wait(1).to({scaleX:2.01,scaleY:2.01,x:176.8,y:234.8},0).wait(1).to({scaleX:2.31,scaleY:2.31,x:171.9,y:267.9},0).wait(1).to({scaleX:2.6,scaleY:2.6,x:167,y:300.6},0).wait(1).to({scaleX:2.8,scaleY:2.8,x:163.8,y:322.6},0).wait(1).to({scaleX:2.94,scaleY:2.94,x:161.6,y:337.4},0).wait(1).to({scaleX:3.04,scaleY:3.04,x:160,y:348.3},0).wait(1).to({scaleX:3.11,scaleY:3.11,x:158.8,y:356.7},0).wait(1).to({scaleX:3.17,scaleY:3.17,x:157.8,y:363.4},0).wait(1).to({scaleX:3.22,scaleY:3.22,x:157,y:368.8},0).wait(1).to({scaleX:3.26,scaleY:3.26,x:156.3,y:373.3},0).wait(1).to({scaleX:3.3,scaleY:3.3,x:155.8,y:377.1},0).wait(1).to({scaleX:3.33,scaleY:3.33,x:155.3,y:380.3},0).wait(1).to({scaleX:3.35,scaleY:3.35,x:154.9,y:382.9},0).wait(1).to({scaleX:3.37,scaleY:3.37,x:154.5,y:385.2},0).wait(1).to({scaleX:3.39,scaleY:3.39,x:154.3,y:387.1},0).wait(1).to({scaleX:3.4,scaleY:3.4,x:154,y:388.7},0).wait(1).to({scaleX:3.42,scaleY:3.42,x:153.8,y:390},0).wait(1).to({scaleX:3.43,scaleY:3.43,x:153.7,y:391.1},0).wait(1).to({scaleX:3.43,scaleY:3.43,x:153.6,y:392},0).wait(1).to({scaleX:3.44,scaleY:3.44,x:153.5,y:392.6},0).wait(1).to({scaleX:3.44,scaleY:3.44,x:153.4,y:393.1},0).wait(1).to({scaleX:3.45,scaleY:3.45,x:153.3,y:393.5},0).wait(1).to({scaleX:3.45,scaleY:3.45,y:393.7},0).wait(1).to({regX:115.7,regY:115.7,x:696.6,y:484.5},0).wait(34));

	// red
	this.instance_6 = new lib.redcircle();
	this.instance_6.parent = this;
	this.instance_6.setTransform(364.1,-80.8,1.095,1.095,0,0,0,115.6,115.5);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({regX:-41.9,regY:78.5,x:191.7,y:-121.2,alpha:0.001},0).wait(1).to({y:-121,alpha:0.003},0).wait(1).to({y:-120.6,alpha:0.008},0).wait(1).to({y:-120,alpha:0.015},0).wait(1).to({y:-119.2,alpha:0.025},0).wait(1).to({y:-118.1,alpha:0.038},0).wait(1).to({y:-116.7,alpha:0.055},0).wait(1).to({y:-114.9,alpha:0.077},0).wait(1).to({y:-112.7,alpha:0.104},0).wait(1).to({y:-109.9,alpha:0.138},0).wait(1).to({y:-106.5,alpha:0.179},0).wait(1).to({y:-102.5,alpha:0.228},0).wait(1).to({y:-97.8,alpha:0.285},0).wait(1).to({y:-92.6,alpha:0.348},0).wait(1).to({y:-87.1,alpha:0.414},0).wait(1).to({y:-81.8,alpha:0.478},0).wait(1).to({y:-76.8,alpha:0.539},0).wait(1).to({y:-72.3,alpha:0.593},0).wait(1).to({y:-68.3,alpha:0.642},0).wait(1).to({y:-64.7,alpha:0.685},0).wait(1).to({y:-61.6,alpha:0.723},0).wait(1).to({y:-58.8,alpha:0.757},0).wait(1).to({y:-56.3,alpha:0.787},0).wait(1).to({y:-54.1,alpha:0.814},0).wait(1).to({y:-52.2,alpha:0.837},0).wait(1).to({y:-50.4,alpha:0.858},0).wait(1).to({y:-48.9,alpha:0.877},0).wait(1).to({y:-47.5,alpha:0.894},0).wait(1).to({y:-46.3,alpha:0.909},0).wait(1).to({y:-45.2,alpha:0.922},0).wait(1).to({y:-44.2,alpha:0.934},0).wait(1).to({y:-43.3,alpha:0.945},0).wait(1).to({y:-42.5,alpha:0.954},0).wait(1).to({y:-41.8,alpha:0.963},0).wait(1).to({y:-41.2,alpha:0.97},0).wait(1).to({y:-40.7,alpha:0.976},0).wait(1).to({y:-40.3,alpha:0.982},0).wait(1).to({y:-39.9,alpha:0.986},0).wait(1).to({y:-39.6,alpha:0.99},0).wait(1).to({y:-39.3,alpha:0.993},0).wait(1).to({y:-39.1,alpha:0.996},0).wait(1).to({y:-38.9,alpha:0.998},0).wait(1).to({y:-38.8,alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:115.6,regY:115.5,x:364.1,y:1.7},0).wait(103).to({regX:-41.9,regY:78.5,x:191.7,y:-38.8},0).wait(2).to({y:-38.9},0).wait(1).to({y:-39.1},0).wait(1).to({y:-39.3},0).wait(1).to({y:-39.6},0).wait(1).to({y:-40},0).wait(1).to({y:-40.4},0).wait(1).to({y:-41},0).wait(1).to({y:-41.7},0).wait(1).to({y:-42.6},0).wait(1).to({y:-43.7},0).wait(1).to({y:-45},0).wait(1).to({y:-46.8},0).wait(1).to({y:-49.2},0).wait(1).to({y:-52.6},0).wait(1).to({y:-58.2},0).wait(1).to({y:-67},0).wait(1).to({y:-74},0).wait(1).to({y:-78.1},0).wait(1).to({y:-80.8},0).wait(1).to({y:-82.7},0).wait(1).to({y:-84.2},0).wait(1).to({y:-85.3},0).wait(1).to({y:-86.2},0).wait(1).to({y:-86.9},0).wait(1).to({y:-87.4},0).wait(1).to({y:-87.9},0).wait(1).to({y:-88.2},0).wait(1).to({y:-88.4},0).wait(1).to({y:-88.6},0).wait(1).to({y:-88.8},0).wait(2).to({regX:115.6,regY:115.5,x:364.1,y:-48.3},0).wait(67).to({regX:-41.9,regY:78.5,x:191.6,y:-88.8},0).wait(1).to({scaleX:1.1,scaleY:1.1,y:-89},0).wait(1).to({scaleX:1.1,scaleY:1.1,y:-89.3},0).wait(1).to({scaleX:1.1,scaleY:1.1,x:191.5,y:-89.6},0).wait(1).to({scaleX:1.11,scaleY:1.11,x:191.4,y:-90.1},0).wait(1).to({scaleX:1.12,scaleY:1.12,x:191.3,y:-90.7},0).wait(1).to({scaleX:1.12,scaleY:1.12,x:191.1,y:-91.4},0).wait(1).to({scaleX:1.13,scaleY:1.13,x:191,y:-92.3},0).wait(1).to({scaleX:1.15,scaleY:1.15,x:190.8,y:-93.4},0).wait(1).to({scaleX:1.16,scaleY:1.16,x:190.5,y:-94.8},0).wait(1).to({scaleX:1.18,scaleY:1.18,x:190.3,y:-96.3},0).wait(1).to({scaleX:1.2,scaleY:1.2,x:190,y:-98.1},0).wait(1).to({scaleX:1.22,scaleY:1.22,x:189.6,y:-100.2},0).wait(1).to({scaleX:1.25,scaleY:1.25,x:189.1,y:-102.6},0).wait(1).to({scaleX:1.28,scaleY:1.28,x:188.6,y:-105.5},0).wait(1).to({scaleX:1.32,scaleY:1.32,x:188,y:-108.8},0).wait(1).to({scaleX:1.36,scaleY:1.36,x:187.3,y:-112.8},0).wait(1).to({scaleX:1.41,scaleY:1.41,x:186.5,y:-117.5},0).wait(1).to({scaleX:1.48,scaleY:1.48,x:185.4,y:-123.3},0).wait(1).to({scaleX:1.56,scaleY:1.56,x:184.1,y:-130.5},0).wait(1).to({scaleX:1.66,scaleY:1.66,x:182.4,y:-139.8},0).wait(1).to({scaleX:1.8,scaleY:1.8,x:180.1,y:-152.5},0).wait(1).to({scaleX:2.01,scaleY:2.01,x:176.8,y:-171.1},0).wait(1).to({scaleX:2.31,scaleY:2.31,x:171.9,y:-198.2},0).wait(1).to({scaleX:2.6,scaleY:2.6,x:167,y:-224.9},0).wait(1).to({scaleX:2.8,scaleY:2.8,x:163.8,y:-242.9},0).wait(1).to({scaleX:2.94,scaleY:2.94,x:161.6,y:-255.1},0).wait(1).to({scaleX:3.04,scaleY:3.04,x:160,y:-264},0).wait(1).to({scaleX:3.11,scaleY:3.11,x:158.8,y:-270.8},0).wait(1).to({scaleX:3.17,scaleY:3.17,x:157.8,y:-276.3},0).wait(1).to({scaleX:3.22,scaleY:3.22,x:157,y:-280.8},0).wait(1).to({scaleX:3.26,scaleY:3.26,x:156.3,y:-284.4},0).wait(1).to({scaleX:3.3,scaleY:3.3,x:155.8,y:-287.6},0).wait(1).to({scaleX:3.33,scaleY:3.33,x:155.3,y:-290.2},0).wait(1).to({scaleX:3.35,scaleY:3.35,x:154.9,y:-292.4},0).wait(1).to({scaleX:3.37,scaleY:3.37,x:154.5,y:-294.2},0).wait(1).to({scaleX:3.39,scaleY:3.39,x:154.3,y:-295.7},0).wait(1).to({scaleX:3.4,scaleY:3.4,x:154,y:-297.1},0).wait(1).to({scaleX:3.42,scaleY:3.42,x:153.8,y:-298.1},0).wait(1).to({scaleX:3.43,scaleY:3.43,x:153.7,y:-299},0).wait(1).to({scaleX:3.43,scaleY:3.43,x:153.6,y:-299.7},0).wait(1).to({scaleX:3.44,scaleY:3.44,x:153.5,y:-300.3},0).wait(1).to({scaleX:3.44,scaleY:3.44,x:153.4,y:-300.7},0).wait(1).to({scaleX:3.45,scaleY:3.45,x:153.3,y:-301},0).wait(1).to({scaleX:3.45,scaleY:3.45,y:-301.1},0).wait(1).to({regX:115.7,regY:115.4,x:696.6,y:-173.6},0).wait(34));

	// bg
	this.instance_7 = new lib.Symbol4();
	this.instance_7.parent = this;
	this.instance_7.setTransform(485,182,1,1,0,0,0,485,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(327));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(364,-202.8,728,340.8);
// library properties:
lib.properties = {
	id: '56C55D65B0334AFAB2334CB62EE25078',
	width: 728,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/728x90_change_atlas_.png", id:"728x90_change_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['56C55D65B0334AFAB2334CB62EE25078'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;