(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"300x600_bcd_phone_atlas_", frames: [[0,936,626,120],[0,0,854,934]]}
];


// symbols:



(lib.docBC = function() {
	this.initialize(ss["300x600_bcd_phone_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.volcanoman = function() {
	this.initialize(ss["300x600_bcd_phone_atlas_"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.docBC();
	this.instance.parent = this;
	this.instance.setTransform(-142,-30,0.9,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-142,-30,563.4,108);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAOIgEgDIgEgFIgBgGIABgFIAEgFIAEgDIAFgBIAGABIAFADIADAFIABAFIgBAGIgDAFIgFADIgGABg");
	this.shape.setTransform(68.7,280.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_1.setTransform(61.625,273.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXAeIAWhBIAZAKIgeA+g");
	this.shape_2.setTransform(53.5,267.15);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgIgHQgGgHgNAAQgIAAgHADQgIAEgGAFIAABHIAQAAIAAAUIg5AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_3.setTransform(42.05,275.675);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_4.setTransform(28.225,275.775);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_5.setTransform(18.775,272.875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgNAAQgIAAgJAEQgHADgGAGIAABGIAQAAIAAAUIg4AAIAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgIAAgHADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIALgEIAKgBQANAAAJAFQAJAFAFAKIAJgHIALgHIALgEQAGgCAHAAQAJAAAIADQAIADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_6.setTransform(-2.45,275.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_7.setTransform(-21.225,275.825);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AASA9IAAgUIAGAAIgYgeIgWAeIAGAAIAAAUIgpAAIAAgUIAKAAIAlgqIgigmIgNAAIAAgVIApAAIAAAVIgFAAIAVAcIAXgcIgGAAIAAgVIAoAAIAAAVIgKAAIgiAnIAkApIAJAAIAAAUg");
	this.shape_8.setTransform(-33.925,275.775);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgUA8QgKgEgIgJQgHgHgFgNQgDgMAAgPQgBgNAEgLQADgMAIgIQAHgJAKgFQAMgFAMAAQAOAAAKAEQAIAFAGAGQAGAHADAJQADAJACAIIAAAJIABAIIhXAAIAAAKIADAIQAEAMAKAGQAJAFALABQAKgBAJgCQAJgCAJgGIAJAOQgLAJgMAEQgNAEgNAAQgLAAgLgEgAAfgOIgCgMQgCgFgEgFQgDgEgGgDQgFgCgIAAQgGAAgHACQgFACgEAFQgEADgCAHQgDAFgBAHIA+AAg");
	this.shape_9.setTransform(-47.5,275.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_10.setTransform(141.775,246.975);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_11.setTransform(131.475,248.775);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_12.setTransform(122.025,245.875);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_13.setTransform(112.325,248.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_14.setTransform(102.375,246.975);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgTA8QgLgEgIgJQgHgHgEgMQgFgNAAgPQABgMADgMQADgMAIgIQAHgJALgFQALgFANAAQANAAAJAEQAJAFAHAGQAFAHADAJQADAJABAIIABAJIAAAIIhWAAIABAKIACAIQAEAMAJAGQAKAFAMABQAJgBAJgCQAIgCAKgGIAJAOQgMAJgMAEQgMAEgNAAQgLAAgKgEgAAfgOIgCgMQgCgFgDgFQgEgEgFgDQgGgCgIAAQgHAAgFACQgGACgEAFQgEADgDAHQgCAFgBAHIA+AAg");
	this.shape_15.setTransform(90.7,248.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgNAAQgIAAgJAEQgIADgGAGIAABGIARAAIAAAUIg4AAIAAgUIASAAIAAg3QAAgOgIgHQgGgHgNAAQgJAAgHADQgIAEgGAFIAABHIAQAAIAAAUIg5AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAJgHIAJgFIALgEIAKgBQANAAAJAFQAJAFAGAKIAJgHIAKgHIALgEQAGgCAHAAQAJAAAIADQAIADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_16.setTransform(72.15,248.675);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_17.setTransform(52.875,248.775);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_18.setTransform(41.375,246.975);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag/BaIAAgUIARAAIAAiHIgRAAIAAgVIAmAAIAAAKQAIgGAJgDQAIgEAKAAQAMAAAKAFQAKAEAHAIQAHAIAEAMQAEALAAAOQAAAOgEANQgFALgHAIQgIAJgLAFQgLAEgNAAQgIAAgIgBIgNgFIAAAnIATAAIAAAUgAgLhCQgIADgFAGIAABBQADAEAIADQAHADAKAAQAHAAAHgCQAHgDAFgGQAGgGADgIQADgIAAgLQAAgLgDgIQgDgIgFgFQgFgGgHgCQgHgDgIAAQgHAAgIADg");
	this.shape_19.setTransform(29.425,251.375);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_20.setTransform(15.025,248.775);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgIgHQgHgHgMAAQgIAAgHADQgIAEgHAFIAABHIARAAIAAAUIg5AAIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAGAGACAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_21.setTransform(-5.3,248.675);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_22.setTransform(-20.075,248.825);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgRIAIAFIAKAFIALACIALABQAIAAAGgCQAHgCAEgEQAFgFACgIQACgIAAgMIAAgCQgGAGgIAEQgIADgKAAQgLAAgLgEQgLgEgHgJQgIgIgFgMQgEgLAAgPQAAgOAEgMQAEgLAIgIQAIgJALgFQALgEAMAAQAJAAAIACQAHADAHAFIAAgHIAWAAIAABzQAAAdgOAPQgOAPgcAAgAgJhCQgHADgFAFQgFAGgDAIQgDAIAAALQAAALACAIQADAIAFAGQAFAFAHAEQAHACAIAAIAKgBIAIgDIAGgEIAFgEIAAhCQgGgFgIgDQgIgCgIAAQgHAAgGADg");
	this.shape_23.setTransform(-39.025,251.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AALA+IAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgHAAgHADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJABALIAAA6IAQAAIAAAUg");
	this.shape_24.setTransform(-53.7,248.675);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_25.setTransform(-65.375,245.875);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AApBbIgwg2IgQAAIAAAiIAKAAIAAAUIg0AAIAAgUIAUAAIAAiNIgVAAIAAgUIArAAIAAAUIAABaIAVAAIAbgdIgHAAIAAgUIAuAAIAAAUIgPAAIglAlIAoArIAPAAIAAAUg");
	this.shape_26.setTransform(-76.625,245.725);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_27.setTransform(-91.675,248.775);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_28.setTransform(-106.025,248.775);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhBBZIAAgUIAQAAIAAiIIgQAAIAAgVIBOAAQALABAKAEQAJAEAHAGQAHAIAEAJQAEAJAAALQAAALgGAKQgGAJgMAGQAGACAEAEQAFAEADAFQAEAFACAFIABALQAAALgEAKQgEAKgHAGQgHAIgJAEQgKAEgLAAgAgaBFIApAAQAFAAAFgDIAJgHQADgFACgFQACgHAAgGQAAgFgCgEQgCgFgDgEIgJgGQgFgCgFAAIgpAAgAgagKIAoAAQAFAAAFgBQAFgDAEgEQADgEACgEQACgFAAgGQAAgFgCgFQgCgHgDgDQgEgFgFgDQgFgCgFAAIgoAAg");
	this.shape_29.setTransform(-120.575,245.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(-477,229.8,971.3,60), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAOIgFgDIgDgFIgBgGIABgFIADgFIAFgDIAFgBIAGABIAFADIADAFIABAFIgBAGIgDAFIgFADIgGABg");
	this.shape.setTransform(112.85,250.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgcBZQgLgFgIgIQgIgJgEgMQgEgMAAgPQAAgOAEgMQAEgKAIgIQAHgIALgFQALgEAOgBQAHAAAIACQAHADAHAEIAAguIgRAAIAAgUIAmAAIAAChIASAAIAAAUIgnAAIAAgKQgGAGgIAEQgIACgJAAQgMAAgKgDgAgSgLQgHADgFAFQgFAFgDAHQgDAJAAAKQAAALADAIQADAKAFAFQAFAGAHADQAHADAIgBQAJABAHgDQAGgDAGgGIAAhDQgGgFgIgCQgHgCgHAAQgIAAgHADg");
	this.shape_1.setTransform(102.875,242.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_2.setTransform(89.625,245.475);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_3.setTransform(77.325,245.575);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAMBbIAAgUIAQAAIAAg3QAAgOgHgGQgHgIgNAAQgHAAgHAEQgIADgHAFIAABHIASAAIAAAUIg6AAIAAgUIASAAIAAiNIgQAAIAAgUIAmAAIAABKIABAAIAHgGIAJgFIAKgDIAKgBQAJAAAIACQAIADAFAGQAGAFADAJQADAHAAAMIAAA6IASAAIAAAUg");
	this.shape_4.setTransform(63.225,242.475);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_5.setTransform(44.075,245.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_6.setTransform(34.625,242.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgRIAIAFIAKAFIALACIALABQAIAAAGgCQAHgCAEgEQAFgFACgIQACgIAAgMIAAgCQgGAGgIADQgIAEgKAAQgLAAgLgEQgLgEgHgJQgIgIgFgMQgEgLAAgPQAAgOAEgMQAEgMAIgHQAIgJALgFQALgEAMAAQAJAAAIACQAHACAHAGIAAgHIAWAAIAAB0QAAAdgOAPQgOAOgcAAgAgJhCQgHADgFAFQgFAGgDAIQgDAIAAALQAAAKACAJQADAIAFAFQAFAHAHACQAHADAIAAIAKgBIAIgDIAGgDIAFgFIAAhCQgGgFgIgDQgIgBgIAAQgHAAgGACg");
	this.shape_7.setTransform(18.025,248.05);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgIgHQgGgHgNAAQgIAAgHADQgIAEgGAFIAABHIAQAAIAAAUIg5AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_8.setTransform(3.35,245.425);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_9.setTransform(-8.325,242.625);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_10.setTransform(-16.725,243.725);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AALA+IAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgGAAgIADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAFAGADAIQAEAJAAALIAAA6IARAAIAAAUg");
	this.shape_11.setTransform(-29.2,245.425);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTA8QgLgEgHgJQgIgHgEgMQgFgNAAgPQABgNADgLQAEgMAHgIQAHgJALgFQAKgFANAAQAOAAAJAEQAJAEAHAHQAFAHADAJQADAIABAJIABAJIAAAIIhWAAIABAKIACAIQAEAMAJAGQAKAGAMAAQAJAAAJgDQAIgDALgFIAJAOQgNAJgMAEQgMAEgNAAQgLAAgKgEgAAfgOIgCgMQgCgFgDgFQgEgEgFgDQgGgCgIAAQgHAAgFACQgGACgEAFQgEADgDAHQgCAGgBAGIA+AAg");
	this.shape_12.setTransform(-44.4,245.55);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_13.setTransform(-56.675,245.475);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_14.setTransform(-68.975,245.575);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag+BZIAAgUIAQAAIAAiJIgQAAIAAgUIBGAAQAMAAAKADQAKADAIAGQAHAGAEAJQAEAJAAAMQAAAKgEAJQgEAIgHAHQgHAGgLADQgKADgMAAIgfAAIAAA/IASAAIAAAUgAgXgMIAfAAQAHAAAGgBQAFgCAEgEQAEgDADgGQACgFAAgHQAAgNgIgHQgIgIgSAAIgcAAg");
	this.shape_15.setTransform(-82.175,242.725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(-92.3,226.6,209.89999999999998,33.00000000000003), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.volcanoman();
	this.instance.parent = this;
	this.instance.setTransform(-496,324,0.3411,0.3411);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-496,324,291.3,318.6), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgWA2QgHgCgFgFQgFgFgCgIQgDgIAAgLIAAg0IgPAAIAAgTIAkAAIAABFQAAANAGAGQAGAHALAAQAGAAAHgDQAHgCAGgEIAAhDIgOAAIAAgTIAjAAIAABcIANAAIAAATIghAAIAAgLQgHAGgJADQgJAEgJAAQgIAAgHgDg");
	this.shape.setTransform(258.825,185.675);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgVA3QgLgFgHgIQgHgHgEgLQgEgLgBgNQABgNAEgKQAEgLAHgIQAIgIAKgEQAKgEALAAQANAAAKAEQAKAEAIAIQAHAHAEALQAEAMAAAMQAAANgEAKQgEAMgHAHQgIAIgKAFQgKAEgNAAQgLAAgKgEgAgMgmQgGACgFAGQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAFQAFAFAGADQAGADAGAAQAIAAAGgDQAHgCAEgGQAFgFADgHQACgJAAgJQAAgJgCgIQgDgIgFgFQgEgGgHgCQgGgDgIAAQgGAAgGADg");
	this.shape_1.setTransform(245.525,185.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgiBRIAAgTIANAAIAMgeIglhdIgJAAIAAgTIAqAAIAAATIgNAAIAaBFIAahFIgNAAIAAgTIArAAIAAATIgMAAIgwB7IAOAAIAAATg");
	this.shape_2.setTransform(232.375,188.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaBRQgKgEgHgIQgHgHgEgLQgEgLAAgOQAAgNAEgLQADgKAIgHQAHgHAKgFQAKgEAMAAQAHAAAHACQAGACAGAEIAAgqIgOAAIAAgTIAjAAIAACUIAQAAIAAASIglAAIAAgJQgFAGgHADQgHADgIAAQgLAAgKgEgAgQgKQgHACgEAFQgFAEgCAIQgDAHAAAJQAAALACAHQADAIAFAGQAEAFAHADQAGACAHAAQAJAAAFgCQAHgDAEgFIAAg+QgFgEgHgCQgHgCgGAAQgHAAgGADg");
	this.shape_3.setTransform(214.95,182.925);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgaBSIAAgSIAQAAIAAhKIgQAAIAAgSIAjAAIAABcIARAAIAAASgAgEg2IgFgDIgDgFIgBgFIABgGIADgEIAFgDIAEgBIAFABIAEADIAEAEIABAGIgBAFIgEAFIgEADIgFABg");
	this.shape_4.setTransform(204.65,182.925);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgaBRQgKgEgHgIQgHgHgEgLQgEgLAAgOQAAgNAEgLQAEgKAGgHQAIgHAKgFQAKgEAMAAQAHAAAGACQAHACAHAEIAAgqIgQAAIAAgTIAjAAIAACUIARAAIAAASIgkAAIAAgJQgGAGgHADQgHADgIAAQgLAAgKgEgAgRgKQgFACgGAFQgEAEgDAIQgDAHAAAJQABALACAHQADAIAEAGQAFAFAGADQAHACAHAAQAIAAAHgCQAGgDAFgFIAAg+QgGgEgHgCQgHgCgGAAQgHAAgHADg");
	this.shape_5.setTransform(194.3,182.925);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgVA3QgLgFgHgIQgHgHgEgLQgEgLgBgNQABgNAEgKQAEgLAHgIQAIgIAKgEQAKgEALAAQANAAAKAEQAKAEAIAIQAHAHAEALQAEAMAAAMQAAANgEAKQgEAMgHAHQgIAIgKAFQgKAEgNAAQgLAAgKgEgAgMgmQgGACgFAGQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAFQAFAFAGADQAGADAGAAQAIAAAGgDQAHgCAEgGQAFgFADgHQACgJAAgJQAAgJgCgIQgDgIgFgFQgEgGgHgCQgGgDgIAAQgGAAgGADg");
	this.shape_6.setTransform(175.925,185.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgLBQIgNgCIgMgFQgGgDgFgEIALgQIAIAFIAIAEIAKACIAKABQAHABAHgCQAGgCAEgEQADgEACgIQACgHAAgMIAAgBQgFAGgIADQgHADgJAAQgLAAgJgEQgKgEgHgIQgHgHgEgLQgEgKAAgOQAAgNAEgLQAEgKAGgIQAIgHAKgEQAKgFALAAQAIAAAHACQAHADAGAEIAAgGIAUAAIAABqQAAAagMAOQgNANgaAAgAgJg8QgGACgFAFQgEAGgDAHQgCAHAAAKQgBAKADAIQADAGAEAGQAFAFAGADQAHADAHgBIAJgBIAHgCIAGgEIAEgEIAAg8QgFgEgIgDQgGgCgIAAQgGAAgHADg");
	this.shape_7.setTransform(162.7,187.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgbA4QgHgDgFgEQgFgFgDgGQgDgFAAgHQAAgHACgGQADgFAEgEQACgEAGgCIAJgEIAKgCIAKgBIANABIAKABIAAgJQAAgHgDgEQgBgEgDgDQgEgDgEgBQgEgBgFgBIgJABIgIACIgIADIgGACIgGgNIAJgFIAKgEIAKgDIAKgBQAJABAIACQAHACAGAFQAGAFADAIQADAHAAALIgBA2IAMAAIAAATIggAAIAAgLQgGAGgIAEQgGAEgLgBQgHABgHgDgAgOAGIgIAEQgEACgCAEQgCAEAAAEQAAAFABADIAFAGIAHADIAJABIAIgBIAGgDIAHgDIAFgFIABgaIgXAAQgGABgEABg");
	this.shape_8.setTransform(150.4,185.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgMBQIgMgCIgMgFQgGgDgFgEIALgQIAIAFIAIAEIAKACIAKABQAIABAFgCQAHgCADgEQAEgEACgIQACgHAAgMIAAgBQgGAGgGADQgIADgJAAQgKAAgKgEQgKgEgHgIQgHgHgEgLQgEgKAAgOQAAgNAEgLQADgKAIgIQAHgHAKgEQAKgFALAAQAIAAAHACQAHADAGAEIAAgGIAUAAIAABqQAAAagNAOQgMANgaAAgAgIg8QgHACgEAFQgFAGgCAHQgDAHgBAKQAAAKADAIQADAGAFAGQAEAFAHADQAGADAGgBIAJgBIAIgCIAGgEIAEgEIAAg8QgGgEgGgDQgIgCgHAAQgGAAgGADg");
	this.shape_9.setTransform(133.05,187.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AALA5IAAgTIAPAAIAAgyQAAgMgGgHQgHgHgMAAQgGAAgHAEQgHADgGAFIAABAIAPAAIAAATIg0AAIAAgTIAQAAIAAhJIgQAAIAAgTIAkAAIAAAOIAAAAIAIgGIAIgFIAJgDIAJgCQAJAAAIADQAHACAFAFQAFAFADAIQACAIAAALIAAA0IAQAAIAAATg");
	this.shape_10.setTransform(119.625,185.475);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVA3QgLgFgHgIQgHgHgEgLQgEgLgBgNQABgNAEgKQAEgLAHgIQAIgIAKgEQAKgEALAAQANAAAKAEQAKAEAIAIQAHAHAEALQAEAMAAAMQAAANgEAKQgEAMgHAHQgIAIgKAFQgKAEgNAAQgLAAgKgEgAgMgmQgGACgFAGQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAFQAFAFAGADQAGADAGAAQAIAAAGgDQAHgCAEgGQAFgFADgHQACgJAAgJQAAgJgCgIQgDgIgFgFQgEgGgHgCQgGgDgIAAQgGAAgGADg");
	this.shape_11.setTransform(105.625,185.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgZBUIAAgTIAQAAIAAiBIgQAAIAAgTIAjAAIAACUIAQAAIAAATg");
	this.shape_12.setTransform(95.625,182.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAZA5IgZhYIgYBYIgTAAIgeheIgKAAIAAgTIAkAAIAAATIgGAAIAUBGIAbhZIAPAAIAaBZIAUhGIgGAAIAAgTIAjAAIAAATIgKAAIgeBeg");
	this.shape_13.setTransform(78.175,185.65);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgVA3QgLgFgHgIQgHgHgEgLQgEgLgBgNQABgNAEgKQAEgLAHgIQAIgIAKgEQAKgEALAAQANAAAKAEQAKAEAIAIQAHAHAEALQAEAMAAAMQAAANgEAKQgEAMgHAHQgIAIgKAFQgKAEgNAAQgLAAgKgEgAgMgmQgGACgFAGQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAFQAFAFAGADQAGADAGAAQAIAAAGgDQAHgCAEgGQAFgFADgHQACgJAAgJQAAgJgCgIQgDgIgFgFQgEgGgHgCQgGgDgIAAQgGAAgGADg");
	this.shape_14.setTransform(62.925,185.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAKBUIAAgTIAQAAIAAgzQAAgNgHgFQgGgHgMAAQgGAAgHAEQgIADgFAEIAABBIAQAAIAAATIg1AAIAAgTIARAAIAAiBIgQAAIAAgTIAkAAIAABFIAAAAIAHgGIAJgEIAIgEIAJgBQAJAAAHADQAHACAFAFQAGAFACAIQACAHAAALIAAA1IASAAIAAATg");
	this.shape_15.setTransform(49.35,182.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgVAcIAUg9IAXAKIgbA4g");
	this.shape_16.setTransform(33.425,191.45);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgVA3QgLgFgHgIQgHgHgEgLQgEgLgBgNQABgNAEgKQAEgLAHgIQAIgIAKgEQAKgEALAAQANAAAKAEQAKAEAIAIQAHAHAEALQAEAMAAAMQAAANgEAKQgEAMgHAHQgIAIgKAFQgKAEgNAAQgLAAgKgEgAgMgmQgGACgFAGQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAFQAFAFAGADQAGADAGAAQAIAAAGgDQAHgCAEgGQAFgFADgHQACgJAAgJQAAgJgCgIQgDgIgFgFQgEgGgHgCQgGgDgIAAQgGAAgGADg");
	this.shape_17.setTransform(24.375,185.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgTBSQgJgDgGgFQgGgFgDgGQgEgGgCgHIgIAAIAAgSIAbAAQAAAMACAFQADAFAEADQAFADAGACQAGACAHAAQAHAAAGgCQAGgCAEgDQAEgDADgFQACgFAAgGQAAgGgDgFQgDgEgEgEIgJgFIgKgDIgXgHQgIgCgGgDQgGgEgFgFQgFgFgCgHQgCgHAAgKQAAgJADgIQAEgIAHgGQAHgGAKgEQALgDAMAAQAIAAAIACQAHACAGADQAGAEAFAFQAEAFADAHIAIAAIAAASIgaAAQAAgJgDgFQgEgFgEgCIgJgEIgKgBQgHAAgGABQgGACgEADQgEAEgCAEQgCAEAAAFQAAAHACAFIAGAHIAJAEIAJADIAVAHQAJADAIAEQAHADAFAFQAFAGADAHQADAHAAAJQAAAKgEAJQgFAIgHAHQgHAGgLAEQgKADgMAAQgMAAgJgCg");
	this.shape_18.setTransform(11.625,183.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(2.9,168,265.90000000000003,30.599999999999994), null);


(lib.shaker = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgNBLIgDgCIgEgFIgBgFIABgEIAEgEIADgDIAGgBIAEABIADADIADAEIABAEIgBAFIgDAFIgDACIgEABgAgQAqIABgRQAAgHACgGQADgGADgEIAJgIIAJgIIAHgGQADgDABgEQACgDAAgGQAAgEgCgEQgBgEgDgDQgDgEgEgBQgEgCgFAAQgHAAgFACQgFADgEAEQgDAEgBAEIgBAHIgRgBQAAgIADgHQADgIAGgFQAHgGAIgDQAIgDAIAAQAKAAAIADQAHADAFAGQAFAFADAHQADAHgBAIQAAAKgEAIQgGAJgKAHIgKAHQgGAFgCAIQgDAHAAAFIAAAMg");
	this.shape.setTransform(178.2,51.725);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAXAzIgXhPIgWBPIgRAAIgchVIgIAAIAAgQIAgAAIAAAQIgFAAIASBAIAYhQIAPAAIAWBQIAThAIgGAAIAAgQIAgAAIAAAQIgJAAIgbBVg");
	this.shape_1.setTransform(164.55,54.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUAxQgJgDgHgIQgGgHgEgKQgEgJAAgMQAAgLAEgKQAEgKAHgHQAGgHAKgEQAJgEAKABQALgBAKAEQAJAEAGAHQAHAHAEAKQAEAJAAAMQAAAMgEAJQgEAKgHAHQgGAIgJADQgKAFgLAAQgKAAgKgFgAgLgiQgGACgEAFQgFAEgCAIQgDAHAAAIQAAAJADAGQACAHAFAGQAEAEAGAEQAFACAGAAQAHAAAGgCQAFgEAFgEQAEgFACgIQADgGAAgJQAAgIgDgHQgCgIgEgEQgFgFgFgCQgGgDgHAAQgGAAgFADg");
	this.shape_2.setTransform(150.725,54.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXBKQgJgEgHgGQgGgIgEgJQgEgLABgNQgBgMAEgJQADgIAHgHQAGgHAKgEQAJgEAKAAQAHAAAGACQAGACAGADIAAgmIgOAAIAAgRIAgAAIAACGIAPAAIAAARIghAAIAAgIQgFAFgGADQgHACgIAAQgJAAgJgDgAgOgJQgHACgDAFQgFADgCAHQgDAGABAJQAAAJABAIQADAHAEAFQAFAEAGADQAFACAHAAQAHAAAGgCQAFgDAFgEIAAg4QgFgEgGgCQgHgCgGAAQgGABgFACg");
	this.shape_3.setTransform(138.7,51.75);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAKAzIAAgRIAOAAIAAgtQAAgLgGgGQgGgGgLAAQgFAAgHADQgGADgGAFIAAA5IAOAAIAAARIgvAAIAAgRIAOAAIAAhCIgOAAIAAgRIAgAAIAAAMIAHgFIAIgFIAIgDIAIAAQAJAAAGABQAHADAEAFQAFAEACAHQADAHAAAKIAAAvIAOAAIAAARg");
	this.shape_4.setTransform(125.825,54.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXBLIAAgRIAPAAIAAhDIgPAAIAAgQIAgAAIAABTIAPAAIAAARgAgEgxIgEgDIgCgEIgCgFIACgFIACgEIAEgDIAEgBIAFABIAEADIACAEIABAFIgBAFIgCAEIgEADIgFABg");
	this.shape_5.setTransform(116.05,51.775);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAXAzIgXhPIgWBPIgRAAIgbhVIgJAAIAAgQIAgAAIAAAQIgEAAIARBAIAYhQIAOAAIAYBQIAShAIgGAAIAAgQIAgAAIAAAQIgIAAIgcBVg");
	this.shape_6.setTransform(104.55,54.275);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgjAzIAAgRIANAAIABhDIgOAAIAAgQIAgAAIAAAOIADgGIAFgEIAGgEIAHgBIAJAAIAJAAIAAAWIgSAAIAAgGIgHABIgGAEQgDADgCAEQgBADgBAGIAAAvIAQAAIAAARg");
	this.shape_7.setTransform(87.675,54.15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgZAzQgGgDgEgEQgFgEgCgFQgDgFAAgHQAAgGACgFQACgFADgEQADgDAFgCIAIgEIAKgCIAJgBIALABIAJABIAAgIQAAgGgCgDQgBgEgDgDQgDgDgEgBQgEgBgEAAIgJABIgHABIgHADIgGACIgFgMIAHgFIAKgDIAJgCIAKgBQAIAAAHACQAHACAFAEQAEAFADAHQADAGAAAKIAAAxIALAAIAAARIgeAAIAAgJQgFAFgHAEQgGADgJAAQgIAAgGgCgAgNAFQgEABgEADQgDACgCADQgBAEAAAEQAAAEABADIAEAFQADACAEABIAIABIAHgBIAGgCIAGgEIAEgEIABgXIgVAAIgJABg");
	this.shape_8.setTransform(77.425,54.225);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgQAyQgJgEgGgHQgHgIgEgJQgDgKAAgMQAAgLAEgKQAEgJAGgIQAHgHAJgEQAJgEAJAAQAJAAAJAEQAJADAGAHIAKAAIAAARIgSAAQgFgIgGgDQgGgEgIAAQgFAAgGADQgGADgEAFQgEAEgDAHQgCAHAAAIQAAAIACAHQADAHAEAFQAEAFAGACQAGADAFAAQAJAAAHgFQAHgEAEgJIAPAIQgDAGgEAFIgKAIQgFAEgGACQgHACgIAAQgJAAgJgEg");
	this.shape_9.setTransform(66.75,54.175);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgQAyQgJgDgGgHQgGgHgEgKQgDgKgBgNQAAgKADgKQAEgKAFgGQAGgIAJgEQAKgFAKABQAMgBAHAEQAIAEAFAFQAFAGACAIQACAHABAHIABAIIAAAHIhIAAIABAHIACAHQADAKAJAEQAHAGAKAAQAHAAAIgCQAHgDAJgEIAHAMQgKAHgKADQgKAEgLAAQgKAAgIgEgAAagLIgCgLQgCgEgDgEQgCgDgFgCQgEgCgHAAQgFAAgFACQgFACgEADIgFAIIgDALIA0AAg");
	this.shape_10.setTransform(50.9,54.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAKBMIAAgRIANAAIAAguQAAgMgFgEQgHgHgKAAQgGAAgGAEQgGADgHADIAAA7IAQAAIAAARIgxAAIAAgRIAPAAIAAh1IgNAAIAAgRIAfAAIAAA+IABAAIAHgFIAHgEIAIgDIAIgBQAIAAAGACQAHADAEAEQAGAFACAHQADAGAAAKIAAAwIAOAAIAAARg");
	this.shape_11.setTransform(39,51.65);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAABDQgFgCgEgEQgDgEgCgGQgBgGAAgKIAAg3IgQAAIAAgOIAQAAIAAgZIARgIIAAAhIAYAAIAAAOIgYAAIgBA6QAAAGACADQABAEADACIAHABIAHgBIAHgCIAEAMIgKAEQgFABgHAAQgHAAgDgBg");
	this.shape_12.setTransform(28.575,52.675);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAABDQgFgCgEgEQgDgEgCgGQgBgGAAgKIAAg3IgQAAIAAgOIAQAAIAAgZIARgIIAAAhIAYAAIAAAOIgYAAIgBA6QAAAGACADQABAEADACIAHABIAHgBIAHgCIAEAMIgKAEQgFABgHAAQgHAAgDgBg");
	this.shape_13.setTransform(16.825,52.675);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgUAxQgGgCgFgEQgEgGgCgHQgDgGAAgLIAAgvIgNAAIAAgRIAgAAIAAA+QAAAMAGAGQAFAGAKAAQAFAAAHgDQAGgCAGgDIAAg9IgOAAIAAgRIAhAAIAABTIALAAIAAARIgdAAIAAgJQgHAFgIADQgIADgIABQgIAAgGgDg");
	this.shape_14.setTransform(5.975,54.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgUAxQgJgDgHgIQgGgHgEgKQgEgJAAgMQAAgLAEgKQAEgKAHgHQAGgHAKgEQAJgEAKABQALgBAKAEQAJAEAGAHQAHAHAEAKQAEAJAAAMQAAAMgEAJQgEAKgHAHQgGAIgJADQgKAFgLAAQgKAAgKgFgAgLgiQgGACgEAFQgFAEgCAIQgDAHAAAIQAAAJADAGQACAHAFAGQAEAEAGAEQAFACAGAAQAHAAAGgCQAFgEAFgEQAEgFACgIQADgGAAgJQAAgIgDgHQgCgIgEgEQgFgFgFgCQgGgDgHAAQgGAAgFADg");
	this.shape_15.setTransform(-6.075,54.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgQAyQgJgEgGgGQgHgHgDgKQgEgKABgNQAAgLACgJQAEgJAFgIQAGgHAKgEQAJgFAKABQAMgBAHAEQAIAEAFAFQAEAGADAIQADAHABAHIAAAIIABAHIhIAAIAAAHIACAHQAEAKAHAEQAIAFAJABQAJAAAHgDQAHgCAJgEIAHAMQgKAGgKAEQgKAEgLAAQgJAAgJgEgAAagLIgCgLQgBgEgDgEQgDgDgFgCQgFgCgGAAQgGAAgEACQgFABgDAEIgGAIIgCALIAzAAg");
	this.shape_16.setTransform(158.6,32.05);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAKAzIAAgRIAOAAIAAgtQAAgLgGgGQgGgGgLAAQgFAAgHADQgGADgGAFIAAA5IAOAAIAAARIgvAAIAAgRIAOAAIAAhCIgOAAIAAgRIAgAAIAAAMIAHgFIAIgFIAIgCIAIgBQAJAAAGABQAHADAEAFQAFAEACAHQADAIAAAKIAAAuIAOAAIAAARg");
	this.shape_17.setTransform(146.525,31.95);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgUAxQgJgEgHgGQgGgIgEgJQgEgKAAgMQAAgLAEgKQAEgKAHgHQAGgHAKgEQAJgEAKABQALgBAKAEQAJAEAGAHQAHAHAEAKQAEAJAAAMQAAALgEALQgEAJgHAIQgGAGgJAEQgKAEgLABQgKgBgKgEgAgLgiQgGACgEAEQgFAGgCAHQgDAGAAAJQAAAJADAGQACAHAFAGQAEAEAGAEQAFACAGAAQAHAAAGgCQAFgEAFgEQAEgFACgIQADgGAAgJQAAgJgDgGQgCgHgEgGQgFgEgFgCQgGgDgHAAQgGAAgFADg");
	this.shape_18.setTransform(133.825,32.05);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAKBMIAAgRIAOAAIAAguQgBgMgFgEQgHgHgLAAQgFAAgGADQgGADgHAEIAAA7IAQAAIAAARIgwAAIAAgRIAOAAIAAh1IgNAAIAAgRIAfAAIAAA+IABAAIAGgFIAIgEIAIgDIAIgBQAIAAAGACQAHACAFAFQAFAFACAHQADAGAAAKIAAAwIAOAAIAAARg");
	this.shape_19.setTransform(121.45,29.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag1BLIAAgRIAPAAIAAhxIgPAAIAAgQIAhAAIAAAIQAGgFAHgDQAHgDAIAAQAKAAAJAEQAIAEAGAGQAGAHADAKQADAJAAALQAAANgDAKQgEAJgHAHQgGAHgJAEQgJAEgLAAQgHAAgGgCIgLgEIAAAhIAPAAIAAARgAgJg3QgGADgFAFIAAA2IAJAGQAGACAIAAQAGAAAGgCQAGgDAEgEQAFgFACgHQACgHABgJQAAgJgCgGQgDgHgEgEQgEgFgGgCQgGgDgHAAQgFAAgHADg");
	this.shape_20.setTransform(108.5,34.225);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgfBJIAAgRIANAAIAKgbIgihVIgIAAIAAgRIAnAAIAAARIgMAAIAXA/IAYg/IgMAAIAAgRIAnAAIAAARIgLAAIgsBwIANAAIAAARg");
	this.shape_21.setTransform(92.125,34.35);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AArAzIAAgRIAOAAIAAgtQAAgLgGgGQgGgGgLAAQgGAAgHADQgHADgFAFIAAA5IAOAAIAAARIguAAIAAgRIAOAAIAAgtQAAgLgFgGQgGgGgLAAQgHAAgGADQgHADgFAFIAAA5IAOAAIAAARIgvAAIAAgRIAOAAIAAhCIgOAAIAAgRIAgAAIAAAMIAHgFIAIgFIAIgCIAJgBQALAAAIADQAHAFAEAIIAIgGIAIgGIAKgDIAKgBQAIAAAHABQAGADAFAFQAEAEADAHQACAIAAAKIAAAuIAOAAIAAARg");
	this.shape_22.setTransform(76.775,31.95);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAXAzIgXhPIgWBPIgRAAIgchVIgIAAIAAgQIAgAAIAAAQIgFAAIASBAIAYhQIAPAAIAWBQIAThAIgGAAIAAgQIAgAAIAAAQIgJAAIgbBVg");
	this.shape_23.setTransform(54.2,32.125);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgUAxQgJgEgHgGQgGgIgEgJQgEgKAAgMQAAgLAEgKQAEgKAHgHQAGgHAKgEQAJgEAKABQALgBAKAEQAJAEAGAHQAHAHAEAKQAEAJAAAMQAAALgEALQgEAJgHAIQgGAGgJAEQgKAEgLABQgKgBgKgEgAgLgiQgGACgEAEQgFAGgCAHQgDAGAAAJQAAAJADAGQACAHAFAGQAEAEAGAEQAFACAGAAQAHAAAGgCQAFgEAFgEQAEgFACgIQADgGAAgJQAAgJgDgGQgCgHgEgGQgFgEgFgCQgGgDgHAAQgGAAgFADg");
	this.shape_24.setTransform(40.375,32.05);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgjAzIAAgRIANAAIABhDIgOAAIAAgQIAgAAIAAAOIADgGIAFgEIAGgEIAHgBIAJAAIAJAAIAAAWIgSAAIAAgGIgHABIgGAEQgDACgCAEQgBAEgBAFIAAAwIAQAAIAAARg");
	this.shape_25.setTransform(29.725,32);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAKBMIAAgRIANAAIAAguQAAgMgFgEQgHgHgKAAQgGAAgGADQgHADgGAEIAAA7IAQAAIAAARIgxAAIAAgRIAPAAIAAh1IgOAAIAAgRIAgAAIAAA+IABAAIAHgFIAHgEIAIgDIAIgBQAIAAAGACQAHACAEAFQAFAFADAHQACAGAAAKIAAAwIAPAAIAAARg");
	this.shape_26.setTransform(18.65,29.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgZBKIAAgRIAOAAIAAhyIgiAAIAAAXIgUAAIAAgnICDAAIAAAnIgUAAIAAgXIgnAAIAAByIAPAAIAAARg");
	this.shape_27.setTransform(4.9,29.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.shaker, new cjs.Rectangle(-22.7,15.9,208,50.300000000000004), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AghA5QgHgDgEgEIgFgGIgEgJIgBgNQAAgGACgKIAKgtIgPAAIAEgTIAmAAIgNA6QgFAVAEAJQAFAKAOAAQAHAAAEgCQAFgCAEgEIAHgJIAOg+IgPAAIAFgTIAlAAIgWBgIARAAIgEATIgnAAIADgMIgIAGIgHAFIgJACIgIABQgHAAgHgCg");
	this.shape.setTransform(111.725,71.825);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgbA5QgKgEgHgIQgHgGgEgLQgEgJAAgLQAAgIACgJQACgKAFgHQAEgIAGgGQAHgGAHgFQAIgEAIgCQAJgDAIAAQALAAAKAEQAKAEAHAHQAHAHAEAKQAEAJAAALQAAAJgCAJQgCAJgFAHQgEAIgGAHQgHAGgHAFQgIAEgIADQgJACgIAAQgMAAgJgEgAgJglQgIAEgGAGQgGAGgDAJQgEAJAAAKQAAAHACAGQADAHAEAFQAEAEAGACQAFADAHAAQAHAAAIgEQAIgDAGgHQAGgGAEgJQADgJAAgKQAAgHgCgGQgDgHgEgEQgEgEgGgDQgGgCgGAAQgIAAgHADg");
	this.shape_1.setTransform(97.525,71.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhDBUIAEgTIAMAAIAVghIgNhgIgLAAIAFgTIAqAAIgEATIgJAAIAHBGIAshGIgJAAIAEgTIAqAAIgFATIgJAAIhSCBIALAAIgEATg");
	this.shape_2.setTransform(84.4,74.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgwA6IAWhfIgWAAIAFgTIArAAIgDAPIAFgGIAIgGIAIgDIAJgBIAHAAIAGAAIAJABIgHAgIgXAAIADgOQgLAAgHAFQgHAGgFAJIgNA5IATAAIgEATg");
	this.shape_3.setTransform(67.275,71.675);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AghA5QgIgEgGgGQgGgHgEgIQgEgJAAgKQAAgPAGgOQAGgNAKgKQAJgKANgFQANgFAOAAQAIAAAIACQAHADAFAEIABgGIAXAAIgXBfIASAAIgEATIgoAAIABgIQgHAFgHADQgHACgIAAQgKAAgIgDgAgIglQgIAEgHAGQgGAHgEAKQgEAJAAAMQAAAHACAGQACAFADAEQAEAEAFACQAFACAGAAIAIgBIAIgDIAHgDIAGgEIAOg9QgCgEgHgDQgGgCgKAAQgIAAgIADg");
	this.shape_4.setTransform(53.375,71.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZA6QgJgEgHgHQgHgHgEgJQgEgKAAgNQAAgNAFgNQAFgNAJgJQAJgJANgGQAMgFANAAQALAAAJADQAIAEAGAGQAHAGADAIQADAIAAAJIgBALIgBAJIhYAAIAAACIgBADQAAAHADAGQACAGAEAEQAEAFAGACQAFADAHAAQAIAAAIgEQAIgEAGgHIAQAMIgJAJQgFAFgGACQgHADgHACIgOABQgKAAgKgDgAAjgNQAAgHgCgFQgCgGgDgDQgEgEgFgCQgGgBgGAAQgHAAgEACQgGACgFAEQgFADgEAGIgGALIBBAAIAAAAg");
	this.shape_5.setTransform(39.925,71.725);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAQA7IARhGQADgNgFgIQgFgGgMAAQgJAAgHADQgIAEgHAHIgTBTIgXAAIAXhfIgWAAIAEgTIAsAAIgDALQAIgGAJgEQAIgEALAAQAJAAAIADQAGADAFAFQAFAGABAHQABAJgCAKIgNA3IARAAIgFATg");
	this.shape_6.setTransform(25.35,71.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgZA6QgJgEgHgHQgHgHgEgJQgEgKAAgNQAAgNAFgNQAFgNAJgJQAJgJANgGQAMgFANAAQALAAAJADQAIAEAGAGQAHAGADAIQADAIAAAJIgBALIgBAJIhYAAIAAACIgBADQAAAHADAGQACAGAEAEQAEAFAGACQAFADAHAAQAIAAAIgEQAIgEAGgHIAQAMIgJAJQgFAFgGACQgHADgHACIgOABQgKAAgKgDgAAjgNQAAgHgCgFQgCgGgDgDQgEgEgFgCQgGgBgGAAQgHAAgEACQgGACgFAEQgFADgEAGIgGALIBBAAIAAAAg");
	this.shape_7.setTransform(6.425,71.725);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAQA7IARhGQADgNgFgIQgFgGgMAAQgJAAgHADQgIAEgHAHIgTBTIgXAAIAWhfIgVAAIAEgTIArAAIgCALQAIgGAJgEQAIgEALAAQAJAAAIADQAGADAFAFQAEAGACAHQABAJgCAKIgNA3IARAAIgEATg");
	this.shape_8.setTransform(-8.2,71.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgbA5QgKgEgHgIQgHgGgEgLQgEgJAAgLQAAgIACgJQACgKAFgHQAEgIAGgGQAHgGAHgFQAIgEAIgCQAJgDAIAAQALAAAKAEQAKAEAHAHQAHAHAEAKQAEAJAAALQAAAJgCAJQgCAJgFAHQgEAIgGAHQgHAGgHAFQgIAEgIADQgJACgIAAQgMAAgJgEgAgJglQgIAEgGAGQgGAGgDAJQgEAJAAAKQAAAHACAGQADAHAEAFQAEAEAGACQAFADAHAAQAHAAAIgEQAIgDAGgHQAGgGAEgJQADgJAAgKQAAgHgCgGQgDgHgEgEQgEgEgGgDQgGgCgGAAQgIAAgHADg");
	this.shape_9.setTransform(-22.725,71.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgnBUQgIgEgHgGQgGgHgEgJQgDgJAAgLQAAgPAFgNQAGgMAJgKQAJgKANgFQANgFANAAQAJAAAHACQAIADAGAEIAKgtIgTAAIAEgTIAqAAIgkCaIAUAAIgFATIgpAAIABgIQgGAFgGACQgHADgIAAQgKAAgJgEgAgQgJQgIADgGAGQgHAGgDAKQgEAJAAALQAAAIACAGQACAGAEAEQAEAEAFACQAGADAGAAQAHAAAIgEQAGgDAGgGIAOg7QgEgEgGgDQgHgDgJAAQgIAAgIAEg");
	this.shape_10.setTransform(-41.475,68.925);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAQA7IARhGQADgNgFgIQgFgGgMAAQgJAAgHADQgIAEgHAHIgTBTIgXAAIAWhfIgVAAIAEgTIArAAIgCALQAIgGAJgEQAIgEALAAQAJAAAIADQAGADAFAFQAEAGACAHQABAJgCAKIgNA3IARAAIgEATg");
	this.shape_11.setTransform(-56.8,71.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgbBVIAWhfIgVAAIAFgTIAqAAIgVBfIARAAIgEATgAAIg4IgFgDIgDgFIAAgGIAAgGIADgEIAFgEIAGgBIAFABIAGAEIACAEIABAGIgBAGIgCAFIgGADIgFABg");
	this.shape_12.setTransform(-68,68.95);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag7ByIAiiUIgYAAIAFgTIAXAAIAFgUQACgLAFgIQAEgHAFgFQAGgFAIgCQAIgCAIAAIAKAAIAJACIAGACIAFACIgLASIgIgEIgLgBQgJAAgHAFQgGAFgDAMIgEATIAfAAIgEATIgfAAIgiCUg");
	this.shape_13.setTransform(-75.025,71.325);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(1,1,1).p("A2PjWMAsfAAAIAAGtMgsfAAAg");
	this.shape_14.setTransform(15.425,69.775);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(-127.9,47.3,286.70000000000005,45), null);


(lib.doclogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Tween2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(276.95,101.25,0.6296,0.6296,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.doclogo, new cjs.Rectangle(187.5,82.3,354.70000000000005,68.00000000000001), null);


(lib.bywhen = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shaker();
	this.instance.parent = this;
	this.instance.setTransform(86.3,22.5,1,1,0,0,0,86.3,22.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bywhen, new cjs.Rectangle(-22.7,15.9,208,50.300000000000004), null);


// stage content:
(lib._300x600_bcd_phone = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 8
	this.instance = new lib.cta();
	this.instance.parent = this;
	this.instance.setTransform(536.1,270.9,0.95,0.95,0,0,0,105.5,22.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(311).to({_off:false},0).wait(1).to({regX:15.4,regY:69.8,x:449,y:316.2},0).wait(1).to({x:443.3},0).wait(1).to({x:430.45},0).wait(1).to({x:404.1},0).wait(1).to({x:356.6},0).wait(1).to({x:305.75},0).wait(1).to({x:269.15},0).wait(1).to({x:243.15},0).wait(1).to({x:223.7},0).wait(1).to({x:208.6},0).wait(1).to({x:196.55},0).wait(1).to({x:186.75},0).wait(1).to({x:178.75},0).wait(1).to({x:172.2},0).wait(1).to({x:166.85},0).wait(1).to({x:162.45},0).wait(1).to({x:158.95},0).wait(1).to({x:156.15},0).wait(1).to({x:154},0).wait(1).to({x:152.4},0).wait(1).to({x:151.35},0).wait(1).to({x:150.7},0).wait(1).to({regX:105.5,regY:22.1,x:236.1,y:270.9},0).wait(27));

	// Layer 6
	this.instance_1 = new lib.doclogo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-339.8,195.15,0.8,0.8,0,0,0,143.1,30.2);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(311).to({_off:false},0).wait(1).to({regX:364.9,regY:116.3,x:-160.8,y:264.05},0).wait(1).to({x:-154.85},0).wait(1).to({x:-141.5},0).wait(1).to({x:-114.1},0).wait(1).to({x:-64.7},0).wait(1).to({x:-11.8},0).wait(1).to({x:26.25},0).wait(1).to({x:53.3},0).wait(1).to({x:73.5},0).wait(1).to({x:89.25},0).wait(1).to({x:101.75},0).wait(1).to({x:111.95},0).wait(1).to({x:120.25},0).wait(1).to({x:127.05},0).wait(1).to({x:132.65},0).wait(1).to({x:137.2},0).wait(1).to({x:140.9},0).wait(1).to({x:143.8},0).wait(1).to({x:146.05},0).wait(1).to({x:147.65},0).wait(1).to({x:148.8},0).wait(1).to({x:149.4},0).wait(1).to({regX:143.1,regY:30.2,x:-27.8,y:195.15},0).wait(27));

	// Layer 5
	this.instance_2 = new lib.Symbol3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(364,68,1,1,0,0,0,221.8,32.4);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(182).to({_off:false},0).wait(37).to({y:67},0).wait(1).to({regX:12.9,regY:245.1,x:155.1,y:279.4},0).wait(1).to({y:278.2},0).wait(1).to({y:274.9},0).wait(1).to({y:269.4},0).wait(1).to({y:265.7},0).wait(1).to({y:263.55},0).wait(1).to({y:262.3},0).wait(1).to({y:261.5},0).wait(1).to({y:261},0).wait(1).to({y:260.75},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:48},0).wait(75).to({regX:12.9,regY:245.1,x:155.1,y:261.45},0).wait(1).to({y:264.1},0).wait(1).to({y:269.1},0).wait(1).to({y:277.3},0).wait(1).to({y:290},0).wait(1).to({y:309.6},0).wait(1).to({y:340.85},0).wait(1).to({y:393.1},0).wait(1).to({y:466.35},0).wait(1).to({y:523.9},0).wait(1).to({y:559.15},0).wait(1).to({y:581.65},0).wait(1).to({y:596.7},0).wait(1).to({y:606.8},0).wait(1).to({y:613.55},0).wait(1).to({y:617.75},0).wait(1).to({y:620},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:408},0).to({_off:true},1).wait(38));

	// Layer 4
	this.instance_3 = new lib.bywhen();
	this.instance_3.parent = this;
	this.instance_3.setTransform(808.2,72.7,4.8399,4.8399,5.9978,0,0,86.5,22.7);
	this.instance_3._off = true;

	this.instance_4 = new lib.Symbol5();
	this.instance_4.parent = this;
	this.instance_4.setTransform(364,60.75,1,1,0,0,0,221.8,17.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(93).to({_off:false},0).wait(1).to({regX:85.6,regY:40.7,scaleX:4.7585,scaleY:4.7585,rotation:5.7232,x:780.4,y:159.5},0).wait(1).to({scaleX:4.5209,scaleY:4.5209,rotation:4.9235,x:738.3,y:161.15},0).wait(1).to({scaleX:4.1461,scaleY:4.1461,rotation:3.6617,x:671.7,y:163.8},0).wait(1).to({scaleX:3.665,scaleY:3.665,rotation:2.0414,x:585.75,y:167},0).wait(1).to({scaleX:3.1202,scaleY:3.1202,rotation:0.2069,x:487.9,y:170.6},0).wait(1).to({scaleX:2.5641,scaleY:2.5641,rotation:-1.6653,x:387.4,y:174.15},0).wait(1).to({scaleX:2.0533,scaleY:2.0533,rotation:-3.3853,x:294.4,y:177.35},0).wait(1).to({scaleX:1.6412,scaleY:1.6412,rotation:-4.7729,x:219,y:179.95},0).wait(1).to({scaleX:1.3722,scaleY:1.3722,rotation:-5.679,x:169.65,y:181.65},0).wait(1).to({regX:86.3,regY:22.7,scaleX:1.2777,scaleY:1.2777,rotation:-5.997,x:150.95,y:159.3},0).to({_off:true},79).wait(179));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(219).to({_off:false},0).to({alpha:1},16).wait(70).to({regX:9.2,regY:259.4,x:151.4,y:303.2},0).wait(1).to({y:305.75},0).wait(1).to({y:310.65},0).wait(1).to({y:318.65},0).wait(1).to({y:331.1},0).wait(1).to({y:350.25},0).wait(1).to({y:380.85},0).wait(1).to({y:431.9},0).wait(1).to({y:503.5},0).wait(1).to({y:559.8},0).wait(1).to({y:594.3},0).wait(1).to({y:616.3},0).wait(1).to({y:630.95},0).wait(1).to({y:640.9},0).wait(1).to({y:647.45},0).wait(1).to({y:651.55},0).wait(1).to({y:653.75},0).wait(1).to({regX:221.8,regY:17.7,x:364,y:412.75},0).to({_off:true},1).wait(38));

	// Layer 2
	this.instance_5 = new lib.Symbol1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-200.65,49.75,1,1,0,0,0,136.3,32.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({regX:135.3,regY:185.3,x:-188.2,y:202.65},0).wait(1).to({x:-171.25},0).wait(1).to({x:-149.2},0).wait(1).to({x:-119.45},0).wait(1).to({x:-79.15},0).wait(1).to({x:-33.05},0).wait(1).to({x:5.85},0).wait(1).to({x:34.4},0).wait(1).to({x:55.65},0).wait(1).to({x:72.05},0).wait(1).to({x:85.1},0).wait(1).to({x:95.8},0).wait(1).to({x:104.65},0).wait(1).to({x:112.1},0).wait(1).to({x:118.4},0).wait(1).to({x:123.75},0).wait(1).to({x:128.3},0).wait(1).to({x:132.2},0).wait(1).to({x:135.5},0).wait(1).to({x:138.3},0).wait(1).to({x:140.7},0).wait(1).to({x:142.65},0).wait(1).to({x:144.3},0).wait(1).to({x:145.6},0).wait(1).to({x:146.65},0).wait(1).to({x:147.4},0).wait(1).to({x:147.95},0).wait(1).to({x:148.25},0).wait(1).to({regX:136.3,regY:32.4,x:149.35,y:49.75},0).wait(63).to({regX:135.3,regY:185.3,scaleX:1.0075,scaleY:1.0075,x:146.15,y:202.75},0).wait(1).to({scaleX:1.0326,scaleY:1.0326,x:138.9,y:203},0).wait(1).to({scaleX:1.0812,scaleY:1.0812,x:124.85,y:203.6},0).wait(1).to({scaleX:1.1616,scaleY:1.1616,x:101.5,y:204.6},0).wait(1).to({scaleX:1.2869,scaleY:1.2869,x:65.15,y:206.1},0).wait(1).to({scaleX:1.4759,scaleY:1.4759,x:10.35,y:208.4},0).wait(1).to({scaleX:1.7436,scaleY:1.7436,x:-67.3,y:211.6},0).wait(1).to({scaleX:2.0621,scaleY:2.0621,x:-159.7,y:215.4},0).wait(1).to({scaleX:2.3531,scaleY:2.3531,x:-244.15,y:218.9},0).wait(1).to({scaleX:2.5761,scaleY:2.5761,x:-308.8,y:221.55},0).wait(1).to({scaleX:2.7383,scaleY:2.7383,x:-355.8,y:223.5},0).wait(1).to({scaleX:2.8555,scaleY:2.8555,x:-389.85,y:224.9},0).wait(1).to({scaleX:2.9401,scaleY:2.9401,x:-414.35,y:225.9},0).wait(1).to({scaleX:3.0003,scaleY:3.0003,x:-431.8,y:226.6},0).wait(1).to({scaleX:3.0417,scaleY:3.0417,x:-443.8,y:227.1},0).wait(1).to({scaleX:3.0682,scaleY:3.0682,x:-451.5,y:227.45},0).wait(1).to({scaleX:3.0826,scaleY:3.0826,x:-455.7,y:227.6},0).wait(1).to({regX:136.2,regY:32.4,scaleX:3.0871,scaleY:3.0871,x:-454.1,y:-244.25},0).to({_off:true},163).wait(89));

	// Layer 3
	this.instance_6 = new lib.Symbol2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(539.85,458.95,0.8348,0.8348,0,0,0,112.2,112.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({regX:-350.4,regY:483.3,x:153.7,y:757.15},0).wait(1).to({y:743.25},0).wait(1).to({y:725.1},0).wait(1).to({y:700.6},0).wait(1).to({y:667.45},0).wait(1).to({y:629.5},0).wait(1).to({y:597.5},0).wait(1).to({y:574},0).wait(1).to({y:556.55},0).wait(1).to({y:543.05},0).wait(1).to({y:532.3},0).wait(1).to({y:523.5},0).wait(1).to({y:516.2},0).wait(1).to({y:510.1},0).wait(1).to({y:504.9},0).wait(1).to({y:500.5},0).wait(1).to({y:496.75},0).wait(1).to({y:493.5},0).wait(1).to({y:490.8},0).wait(1).to({y:488.45},0).wait(1).to({y:486.5},0).wait(1).to({y:484.85},0).wait(1).to({y:483.55},0).wait(1).to({y:482.45},0).wait(1).to({y:481.6},0).wait(1).to({y:481},0).wait(1).to({y:480.55},0).wait(1).to({y:480.3},0).wait(1).to({regX:112.2,regY:112.8,x:539.85,y:170.95},0).wait(63).to({regX:-350.4,regY:483.3,scaleX:0.8368,scaleY:0.8368,x:153.6,y:480.3},0).wait(1).to({scaleX:0.8434,scaleY:0.8434,x:153.45,y:480.5},0).wait(1).to({scaleX:0.8561,scaleY:0.8561,x:153.15,y:480.95},0).wait(1).to({scaleX:0.8771,scaleY:0.8771,x:152.6,y:481.6},0).wait(1).to({scaleX:0.9099,scaleY:0.9099,x:151.8,y:482.65},0).wait(1).to({scaleX:0.9594,scaleY:0.9594,x:150.6,y:484.25},0).wait(1).to({scaleX:1.0294,scaleY:1.0294,x:148.85,y:486.6},0).wait(1).to({scaleX:1.1128,scaleY:1.1128,x:146.8,y:489.3},0).wait(1).to({scaleX:1.189,scaleY:1.189,x:144.95,y:491.8},0).wait(1).to({scaleX:1.2473,scaleY:1.2473,x:143.5,y:493.7},0).wait(1).to({scaleX:1.2898,scaleY:1.2898,x:142.45,y:495.05},0).wait(1).to({scaleX:1.3205,scaleY:1.3205,x:141.7,y:496.05},0).wait(1).to({scaleX:1.3426,scaleY:1.3426,x:141.15,y:496.75},0).wait(1).to({scaleX:1.3584,scaleY:1.3584,x:140.75,y:497.25},0).wait(1).to({scaleX:1.3692,scaleY:1.3692,x:140.5,y:497.65},0).wait(1).to({scaleX:1.3761,scaleY:1.3761,x:140.3,y:497.85},0).wait(1).to({scaleX:1.3799,scaleY:1.3799,x:140.25,y:497.95},0).wait(1).to({regX:112.5,regY:112.5,scaleX:1.3811,scaleY:1.3811,x:779.15,y:-13.8},0).wait(1).to({regX:-350.4,regY:483.3,x:139.85,y:498.35},0).wait(1).to({x:139.9},0).wait(1).to({x:140},0).wait(1).to({x:140.1},0).wait(1).to({x:140.3},0).wait(1).to({x:140.6},0).wait(1).to({x:140.9},0).wait(1).to({x:141.25},0).wait(1).to({x:141.6},0).wait(1).to({x:141.85},0).wait(1).to({x:142},0).wait(1).to({x:142.15},0).wait(1).to({x:142.2},0).wait(1).to({regX:112.5,regY:112.5,x:781.55,y:-13.8},0).wait(1).to({regX:-350.4,regY:483.3,x:142.25,y:498.4},0).wait(1).to({y:498.45},0).wait(1).to({y:498.55},0).wait(1).to({y:498.7},0).wait(1).to({y:498.85},0).wait(1).to({y:499.15},0).wait(1).to({y:499.45},0).wait(1).to({y:499.85},0).wait(1).to({y:500.3},0).wait(1).to({y:500.8},0).wait(1).to({y:501.3},0).wait(1).to({y:501.8},0).wait(1).to({y:502.2},0).wait(1).to({y:502.55},0).wait(1).to({y:502.8},0).wait(1).to({y:502.95},0).wait(1).to({y:503.1},0).wait(1).to({y:503.15},0).wait(1).to({regX:112.5,regY:112.5,x:781.55,y:-9},0).wait(1).to({regX:-350.4,regY:483.3,x:142.2,y:503.15},0).wait(1).to({y:503.1},0).wait(1).to({y:503.05},0).wait(1).to({x:142.15,y:502.95},0).wait(1).to({x:142.1,y:502.8},0).wait(1).to({x:142.05,y:502.6},0).wait(1).to({x:141.95,y:502.35},0).wait(1).to({x:141.85,y:502.05},0).wait(1).to({x:141.75,y:501.75},0).wait(1).to({x:141.6,y:501.35},0).wait(1).to({x:141.5,y:501},0).wait(1).to({x:141.35,y:500.6},0).wait(1).to({x:141.25,y:500.3},0).wait(1).to({x:141.2,y:500.05},0).wait(1).to({x:141.1,y:499.85},0).wait(1).to({y:499.75},0).wait(1).to({x:141.05,y:499.65},0).wait(1).to({y:499.6},0).wait(1).to({regX:112.5,regY:112.5,x:780.35,y:-12.6},0).wait(1).to({regX:-350.4,regY:483.3,x:141.05,y:499.55},0).wait(3).to({x:141.1,y:499.5},0).wait(1).to({x:141.15,y:499.45},0).wait(1).to({x:141.2,y:499.4},0).wait(1).to({x:141.25,y:499.35},0).wait(1).to({x:141.35,y:499.25},0).wait(1).to({x:141.45,y:499.15},0).wait(1).to({x:141.55,y:499.05},0).wait(1).to({x:141.7,y:498.9},0).wait(1).to({x:141.8,y:498.8},0).wait(1).to({x:141.9,y:498.7},0).wait(1).to({x:142,y:498.6},0).wait(1).to({x:142.1,y:498.5},0).wait(1).to({x:142.15,y:498.45},0).wait(1).to({x:142.2,y:498.4},0).wait(3).to({regX:112.5,regY:112.5,x:781.55,y:-13.8},0).to({_off:true},1).wait(179));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D93D43").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(1,1,1,1,0,0,0,-149,-299);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(361));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-715.6,284.8,2002.6,616.5);
// library properties:
lib.properties = {
	id: 'F3B295547F6C4148B2E896B46B1DB47D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/300x600_bcd_phone_atlas_.png", id:"300x600_bcd_phone_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['F3B295547F6C4148B2E896B46B1DB47D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;