(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"728x90_aaoo_boy_atlas_", frames: [[0,0,728,90]]}
];


// symbols:



(lib.bb_boy = function() {
	this.initialize(ss["728x90_aaoo_boy_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#51C4ED").s().p("AgOCEIgUgEIgSgGIgRgJIgPgLIgRgSIgLgPIgJgSIgGgSIgEgUIAAgbIAEgTIAGgTIAJgRIAOgUIAOgMIAPgLIARgJIANgFIAZgEIATgBIAhAFIAYAKIAGAEIAQALIANAMIAQAUIAJARIAIAZIACAUIAAANIgCAUIgIAZIgDAGIgKARIgQAUIgOAMIgWANIgMAFIgTAGIgaACg");
	this.shape.setTransform(13.2,13.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol6, new cjs.Rectangle(0,0,26.4,26.4), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#51C4ED").s().p("AgIAqIAAhDIgVAAIAAgQIA7AAIAAAQIgVAAIAABDg");
	this.shape.setTransform(238.525,-43.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#51C4ED").s().p("AgcAfIAKgNQAKAJAJAAQAGABACgDQADgCAAgEQAAgDgDgCQgCgDgIgEQgMgEgGgEQgGgGgBgKIAAgBQAAgKAIgIQAIgGALAAQAQAAALAKIgKANQgJgIgIAAQgDAAgEACQgCACAAAEQAAAEADACQADACAJAEQAMAFAFAEQAGAGgBAJIAAABQAAAMgIAGQgHAHgNAAQgQAAgNgMg");
	this.shape_1.setTransform(231.8,-43.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#51C4ED").s().p("AgIAqIAAhTIARAAIAABTg");
	this.shape_2.setTransform(226.875,-43.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#51C4ED").s().p("AAMAqIgPgbIgKAAIAAAbIgSAAIAAhTIAfAAQAOAAAJAIQAHAHAAANIAAAAQAAARgQAHIASAfgAgNAAIAMAAQAGAAAEgDQADgEAAgFQAAgNgNgBIgMAAg");
	this.shape_3.setTransform(221.625,-43.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#51C4ED").s().p("AgIAqIAAhDIgVAAIAAgQIA7AAIAAAQIgVAAIAABDg");
	this.shape_4.setTransform(214.325,-43.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#51C4ED").s().p("AgaAqIAAhTIA1AAIAAAPIgkAAIAAATIAfAAIAAAOIgfAAIAAATIAkAAIAAAQg");
	this.shape_5.setTransform(207.775,-43.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#51C4ED").s().p("AAUAqIAAg0IgUAhIAAAAIgTghIAAA0IgRAAIAAhTIASAAIASAiIATgiIASAAIAABTg");
	this.shape_6.setTransform(199.675,-43.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#51C4ED").s().p("AgbAgQgKgNAAgSIAAgBQAAgSAKgMQALgNAQAAQAQAAALANQALALAAATIAAAAQAAAUgLAMQgKAMgRgBQgQABgLgMgAgOgTQgFAHAAAMIAAAAQAAAMAFAIQAGAHAIAAQAJAAAGgHQAFgHAAgNIAAAAQAAgMgGgHQgGgHgIgBQgIABgGAHg");
	this.shape_7.setTransform(190.85,-43.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#51C4ED").s().p("AgIAqIAAhDIgVAAIAAgQIA7AAIAAAQIgVAAIAABDg");
	this.shape_8.setTransform(183.225,-43.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#51C4ED").s().p("AgcAqIAAhTIAcAAQANAAAIAHQAIAJAAANQAAANgJAIQgIAHgNAAIgKAAIAAAagAgLABIAKAAQAFAAAEgDQAEgEAAgFQAAgOgNgBIgKAAg");
	this.shape_9.setTransform(176.675,-43.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#51C4ED").s().p("AgaAgQgLgNAAgSIAAgBQAAgSALgMQALgNAPAAQARAAALANQAKALAAATIAAAAQAAAUgLAMQgKAMgRgBQgQABgKgMgAgOgTQgFAHAAAMIAAAAQAAAMAFAIQAGAHAIAAQAJAAAFgHQAGgHAAgNIAAAAQAAgMgGgHQgGgHgIgBQgIABgGAHg");
	this.shape_10.setTransform(168.6,-43.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#51C4ED").s().p("AASAqIghgyIAAAyIgRAAIAAhTIAQAAIAgAwIAAgwIARAAIAABTg");
	this.shape_11.setTransform(157.55,-43.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#51C4ED").s().p("AAUAqIgGgSIgcAAIgGASIgRAAIAdhTIAQAAIAeBTgAAJAJIgJgbIgIAbIARAAg");
	this.shape_12.setTransform(149.45,-43.525);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#51C4ED").s().p("AghAqIAAhTIAbAAQASAAAKAMQAMALAAASIAAAAQAAATgMAMQgKALgSAAgAgPAaIAJAAQAJABAHgIQAFgGABgNIAAAAQgBgLgFgIQgHgHgJAAIgJAAg");
	this.shape_13.setTransform(138.9,-43.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#51C4ED").s().p("AARAqIgggyIAAAyIgQAAIAAhTIAPAAIAgAwIAAgwIARAAIAABTg");
	this.shape_14.setTransform(130.65,-43.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#51C4ED").s().p("AgIAqIAAhTIARAAIAABTg");
	this.shape_15.setTransform(124.825,-43.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#51C4ED").s().p("AgaAqIAAhTIA1AAIAAAQIgjAAIAAATIAeAAIAAAPIgeAAIAAAhg");
	this.shape_16.setTransform(120,-43.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgEANIgFgDIgDgFIgBgFIABgFIADgEIAFgDIAEgBIAGABIAEADIADAEIABAFIgBAFIgDAFIgEADIgGABg");
	this.shape_17.setTransform(330.625,-74.125);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAvA5IAAgTIAQAAIAAgyQAAgMgHgHQgFgHgNAAQgHAAgHAEQgIADgGAGIAAA/IAQAAIAAATIgzAAIAAgTIAQAAIAAgyQgBgMgGgHQgHgHgMAAQgHAAgHAEQgGADgHAFIAABAIAQAAIAAATIg0AAIAAgTIAPAAIAAhJIgPAAIAAgTIAjAAIAAANIABAAIAHgFIAJgFIAJgDIAKgCQALAAAJAFQAIAEAFAKIAJgHIAJgGIAKgEIALgCQAJAAAIADQAGACAFAFQAFAFAEAIQACAIAAALIAAA0IAPAAIAAATg");
	this.shape_18.setTransform(317.2,-78.525);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgbA4QgHgCgFgFQgFgFgCgFQgEgHAAgGQAAgHACgFQADgGADgEQAEgEAEgCIAKgEIAKgDIAKAAIANAAIAKABIAAgJQAAgGgCgEQgCgEgDgDQgEgDgEgBQgEgCgFABIgJAAIgJACIgHACIgGAEIgHgPIAJgEIAKgEIALgDIAKAAQAJgBAIADQAHADAGAEQAGAFADAHQACAIAAAKIAAA3IAMAAIAAATIggAAIAAgLQgGAGgIAEQgHADgKABQgHgBgHgCgAgPAGIgIADQgEADgBAEQgCADAAAFQAAAEACAEIAEAGIAHADIAJABIAIgBIAHgCIAGgFIAFgEIABgZIgXAAQgGgBgFACg");
	this.shape_19.setTransform(300,-78.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAQA4IAAgTIAHAAIgXgbIgVAbIAGAAIAAATIglAAIAAgTIAJAAIAigmIgfgjIgMAAIAAgTIAlAAIAAATIgFAAIAUAaIAVgaIgGAAIAAgTIAlAAIAAATIgJAAIgfAkIAhAlIAIAAIAAATg");
	this.shape_20.setTransform(288.35,-78.425);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgSA3QgJgEgIgIQgGgGgEgMQgEgLAAgOQAAgMADgKQAEgKAGgIQAHgJAKgEQAKgEALAAQANAAAJADQAHAEAGAGQAFAGADAIQADAJABAIIABAJIAAAHIhPAAIABAIIABAHQAEALAJAGQAJAFAKAAQAIAAAJgCQAIgCAJgGIAIAOQgLAHgLAEQgLADgMABQgKgBgKgDgAAcgMIgCgLQgBgGgEgEQgDgDgEgDQgGgCgHAAQgGAAgFACQgFACgEAEQgEADgCAGIgDAMIA4AAg");
	this.shape_21.setTransform(275.9,-78.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgRA3QgLgEgGgIQgIgGgDgMQgEgLAAgOQAAgMADgKQAEgKAGgIQAHgJAJgEQAKgEANAAQAMAAAIADQAJAEAFAGQAGAGACAIQADAJABAIIAAAJIABAHIhQAAIABAIIADAHQADALAJAGQAJAFAKAAQAIAAAJgCQAIgCAJgGIAIAOQgLAHgLAEQgLADgMABQgKgBgJgDgAAdgMIgCgLQgCgGgEgEQgCgDgGgDQgEgCgIAAQgGAAgFACQgFACgEAEQgEADgCAGIgEAMIA6AAg");
	this.shape_22.setTransform(258.5,-78.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgiBRIAAgTIANAAIAMgeIglheIgJAAIAAgSIAqAAIAAASIgNAAIAaBGIAahGIgNAAIAAgSIArAAIAAASIgMAAIgwB8IAOAAIAAATg");
	this.shape_23.setTransform(245.825,-75.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgRA3QgLgEgGgIQgIgGgDgMQgEgLAAgOQAAgMADgKQAEgKAGgIQAHgJAJgEQAKgEANAAQAMAAAIADQAJAEAFAGQAGAGACAIQADAJABAIIAAAJIABAHIhQAAIABAIIADAHQADALAJAGQAJAFAKAAQAIAAAJgCQAIgCAJgGIAIAOQgLAHgLAEQgLADgMABQgKgBgJgDgAAdgMIgCgLQgCgGgEgEQgCgDgGgDQgEgCgIAAQgGAAgFACQgFACgEAEQgEADgCAGIgEAMIA6AAg");
	this.shape_24.setTransform(233.3,-78.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AALA5IAAgTIAPAAIAAgyQAAgMgGgHQgHgHgMAAQgGAAgHAEQgHADgGAFIAABAIAPAAIAAATIg0AAIAAgTIAQAAIAAhJIgQAAIAAgTIAkAAIAAAOIAAAAIAIgGIAIgFIAJgDIAJgCQAJAAAIADQAHACAFAFQAFAFADAIQACAIAAALIAAA0IAQAAIAAATg");
	this.shape_25.setTransform(215.175,-78.525);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgbA4QgHgCgFgFQgFgFgCgFQgDgHgBgGQABgHACgFQACgGADgEQAEgEAEgCIAKgEIAKgDIALAAIAMAAIAJABIAAgJQAAgGgBgEQgCgEgDgDQgDgDgEgBQgFgCgFABIgJAAIgJACIgHACIgGAEIgHgPIAJgEIAKgEIALgDIALAAQAIgBAIADQAIADAFAEQAGAFACAHQADAIAAAKIAAA3IANAAIAAATIghAAIAAgLQgGAGgIAEQgHADgJABQgIgBgHgCgAgPAGIgIADQgEADgBAEQgCADAAAFQAAAEACAEIAEAGIAHADIAJABIAIgBIAHgCIAGgFIAFgEIAAgZIgWAAQgFgBgGACg");
	this.shape_26.setTransform(201.65,-78.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgaBRQgKgEgHgIQgHgHgEgLQgEgLAAgOQAAgNAEgLQADgKAIgHQAHgHAKgFQAKgEAMAAQAHAAAHACQAGACAGAEIAAgqIgOAAIAAgTIAjAAIAACUIAQAAIAAASIglAAIAAgJQgFAGgHADQgHADgIAAQgLAAgKgEgAgQgKQgHACgEAFQgFAEgCAIQgDAHAAAJQAAALACAHQADAIAFAGQAEAFAHADQAGACAHAAQAJAAAFgCQAHgDAEgFIAAg+QgFgEgHgCQgHgCgGAAQgHAAgGADg");
	this.shape_27.setTransform(184.35,-81.075);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgZBUIAAgTIAQAAIAAiBIgQAAIAAgTIAjAAIAACUIAQAAIAAATg");
	this.shape_28.setTransform(173.925,-81.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgaBSIAAgSIARAAIAAhKIgRAAIAAgSIAjAAIAABcIASAAIAAASgAgFg2IgEgDIgDgFIgCgFIACgGIADgEIAEgDIAFgBIAFABIAEADIADAEIABAGIgBAFIgDAFIgEADIgFABg");
	this.shape_29.setTransform(166.9,-81.075);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AALBUIAAgTIAPAAIAAgzQAAgMgGgGQgHgHgMAAQgGAAgHADQgIAEgFAEIAABBIAPAAIAAATIg1AAIAAgTIARAAIAAiBIgPAAIAAgTIAkAAIAABFIAAAAIAHgGIAIgFIAJgDIAJgBQAJAAAHACQAHADAFAFQAFAFADAIQADAHAAALIAAA1IARAAIAAATg");
	this.shape_30.setTransform(156.15,-81.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgSA3QgKgFgHgHQgHgIgEgLQgEgLAAgNQAAgMAEgLQAFgLAHgHQAHgIAKgEQAKgFAKAAQAKAAAKAEQAJADAHAIIAMAAIAAASIgVAAQgEgIgHgDQgHgEgJAAQgGAAgGADQgGADgFAFQgFAFgCAIQgDAIAAAIQAAAKADAHQACAHAFAGQAFAFAGADQAGADAGAAQAKAAAIgFQAHgFAFgKIAQAIQgDAHgEAFQgFAGgGAEQgGAEgHACQgHACgIAAQgLAAgKgEg");
	this.shape_31.setTransform(142.825,-78.45);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgnA4IAAgTIAPAAIAAhJIgPAAIAAgSIAkAAIAAAPIADgGIAFgGIAHgDIAIgBIAKAAIAKAAIAAAYIgUAAIAAgGIgIABQgDABgEADQgDADgCAEQgCAEgBAGIAAA0IASAAIAAATg");
	this.shape_32.setTransform(126.725,-78.45);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgWA2QgHgCgFgFQgFgFgCgIQgDgIAAgLIAAg0IgPAAIAAgTIAkAAIAABFQAAANAGAGQAGAHALAAQAGAAAHgDQAHgCAGgEIAAhDIgOAAIAAgTIAjAAIAABcIANAAIAAATIghAAIAAgLQgHAGgJADQgJAEgJAAQgIAAgHgDg");
	this.shape_33.setTransform(113.775,-78.325);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgVA2QgLgEgHgIQgHgHgEgLQgEgLgBgNQABgMAEgLQAEgLAHgIQAIgHAKgFQAKgEALAAQANAAAKAEQAKAFAIAHQAHAIAEALQAEAKAAANQAAAMgEALQgEAMgHAHQgIAIgKAEQgKAFgNAAQgLAAgKgFgAgMgmQgGADgFAFQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAGQAFAEAGAEQAGACAGAAQAIAAAGgCQAHgDAEgFQAFgGADgIQACgHAAgKQAAgJgCgIQgDgIgFgFQgEgFgHgDQgGgDgIAAQgGAAgGADg");
	this.shape_34.setTransform(100.475,-78.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgiBRIAAgTIANAAIAMgeIglheIgJAAIAAgSIAqAAIAAASIgNAAIAaBGIAahGIgNAAIAAgSIArAAIAAASIgMAAIgwB8IAOAAIAAATg");
	this.shape_35.setTransform(87.325,-75.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAmBUIgtgyIgOAAIAAAfIAJAAIAAATIgwAAIAAgTIATAAIAAiBIgTAAIAAgTIAnAAIAAATIAABSIATAAIAZgbIgGAAIAAgSIAqAAIAAASIgOAAIgiAiIAlAoIANAAIAAATg");
	this.shape_36.setTransform(69.925,-81.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgVA2QgLgEgHgIQgHgHgEgLQgEgLgBgNQABgMAEgLQAEgLAHgIQAIgHAKgFQAKgEALAAQANAAAKAEQAKAFAIAHQAHAIAEALQAEAKAAANQAAAMgEALQgEAMgHAHQgIAIgKAEQgKAFgNAAQgLAAgKgFgAgMgmQgGADgFAFQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAGQAFAEAGAEQAGACAGAAQAIAAAGgCQAHgDAEgFQAFgGADgIQACgHAAgKQAAgJgCgIQgDgIgFgFQgEgFgHgDQgGgDgIAAQgGAAgGADg");
	this.shape_37.setTransform(56.125,-78.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgVA2QgLgEgHgIQgHgHgEgLQgEgLgBgNQABgMAEgLQAEgLAHgIQAIgHAKgFQAKgEALAAQANAAAKAEQAKAFAIAHQAHAIAEALQAEAKAAANQAAAMgEALQgEAMgHAHQgIAIgKAEQgKAFgNAAQgLAAgKgFgAgMgmQgGADgFAFQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAGQAFAEAGAEQAGACAGAAQAIAAAGgCQAHgDAEgFQAFgGADgIQACgHAAgKQAAgJgCgIQgDgIgFgFQgEgFgHgDQgGgDgIAAQgGAAgGADg");
	this.shape_38.setTransform(42.975,-78.4);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("Ag8BSIAAgTIAQAAIAAh9IgQAAIAAgTIBIAAQAKABAJAEQAJADAGAGQAHAHADAJQAEAIAAAKQAAAKgGAKQgGAIgKAFIAJAFIAHAIIAFAKIACAKQAAAKgEAJQgEAJgGAGQgGAHgJADQgJAEgKABgAgXA/IAlAAQAFAAAEgDQAFgCADgEQADgEACgGQACgFAAgGIgCgJQgCgEgDgEQgDgDgFgCQgEgCgFAAIglAAgAgXgJIAkAAQAFAAAEgCQAFgCADgDQADgDACgFQACgEAAgFQAAgGgCgEQgCgGgDgEQgDgEgFgCQgEgDgFAAIgkAAg");
	this.shape_39.setTransform(29.625,-81);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("ArUCqIAAkXIAAg8IWpAAIAAA8IAAEXg");
	this.shape_40.setTransform(178.5,-40.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(20,-96,412,72.1), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAOIgFgDIgDgFIgBgGIABgFIADgEIAFgEIAFgCIAGACIAFAEIADAEIABAFIgBAGIgDAFIgFADIgGACg");
	this.shape.setTransform(270.7,-86.35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_1.setTransform(262.325,-91.075);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_2.setTransform(250.025,-90.975);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUA8QgKgFgIgHQgHgJgEgMQgFgLAAgQQABgNADgLQADgMAIgJQAHgIALgFQALgFANAAQANAAAJAEQAJAFAHAGQAFAHADAJQADAJABAJIABAJIAAAIIhWAAIABAJIACAIQAEAMAJAGQAKAGAMgBQAJABAJgDQAIgDALgFIAIAPQgMAIgMAEQgMAEgNAAQgLAAgLgEgAAfgNIgCgNQgCgGgDgEQgEgEgFgCQgGgDgIAAQgHAAgFADQgGACgEADQgEAFgDAFQgCAGgBAIIA+AAg");
	this.shape_3.setTransform(236.5,-91);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AglBYIAAgUIAPAAIAMghIgohmIgKAAIAAgUIAuAAIAAAUIgOAAIAcBMIAdhMIgPAAIAAgUIAvAAIAAAUIgNAAIg1CHIAQAAIAAAUg");
	this.shape_4.setTransform(222.65,-88.275);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgcBbIAAgUIASAAIAAiNIgSAAIAAgUIAmAAIAAChIATAAIAAAUg");
	this.shape_5.setTransform(207.125,-94.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_6.setTransform(195.875,-91.025);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_7.setTransform(181.525,-91.025);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAMBbIAAgUIAQAAIAAg3QAAgOgHgGQgHgIgNAAQgHAAgHAEQgIADgHAFIAABHIASAAIAAAUIg6AAIAAgUIASAAIAAiNIgQAAIAAgUIAmAAIAABKIABAAIAHgGIAJgFIAKgDIAKgBQAJAAAIACQAIADAFAGQAGAFADAJQADAHAAAMIAAA6IASAAIAAAUg");
	this.shape_8.setTransform(166.675,-94.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgTA7QgLgEgIgJQgIgIgEgMQgEgMAAgOQAAgNAEgMQAFgLAIgJQAIgIAKgGQALgEALAAQAMAAAKADQAKAEAIAJIAMAAIAAAUIgWAAQgFgJgHgEQgIgEgKAAQgGAAgHADQgHADgFAGQgFAGgDAJQgDAIAAAJQAAAKADAJQADAHAFAGQAFAHAHACQAHAEAGAAQALgBAJgFQAIgGAFgKIASAJQgEAHgFAHQgFAFgGAEQgHAFgIACQgHACgJAAQgMABgKgGg");
	this.shape_9.setTransform(152.125,-91.05);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_10.setTransform(139.675,-91.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_11.setTransform(122.825,-91.025);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_12.setTransform(113.375,-93.925);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAMBbIAAgUIAQAAIAAg3QAAgOgHgGQgHgIgNAAQgHAAgHAEQgIADgHAFIAABHIASAAIAAAUIg6AAIAAgUIASAAIAAiNIgQAAIAAgUIAmAAIAABKIABAAIAHgGIAJgFIAKgDIAKgBQAJAAAIACQAIADAFAGQAGAFADAJQADAHAAAMIAAA6IASAAIAAAUg");
	this.shape_13.setTransform(101.625,-94.075);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_14.setTransform(89.125,-92.825);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_15.setTransform(310.925,-118.025);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_16.setTransform(299.325,-118.025);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgTA8QgLgFgHgHQgIgJgEgMQgFgLAAgQQABgNADgLQAEgMAHgJQAHgIALgFQAKgFANAAQAOAAAJAEQAJAFAHAGQAFAHADAJQADAJABAJIABAJIAAAIIhWAAIABAJIACAIQAEAMAJAGQAKAGAMgBQAJABAJgDQAIgDALgFIAJAPQgNAIgMAEQgMAEgNAAQgLAAgKgEgAAfgNIgCgNQgCgGgDgEQgEgEgFgCQgGgDgIAAQgHAAgFADQgGACgEADQgEAFgDAFQgCAGgBAIIA+AAg");
	this.shape_17.setTransform(286.35,-118);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgTA7QgLgEgIgJQgIgIgEgMQgEgMAAgOQAAgNAEgMQAFgLAIgJQAIgIAKgGQALgEALAAQAMAAAKADQAKAEAIAJIAMAAIAAAUIgWAAQgFgJgHgEQgIgEgKAAQgGAAgHADQgHADgFAGQgFAGgDAJQgDAIAAAJQAAAKADAJQADAHAFAGQAFAHAHACQAHAEAGAAQALgBAJgFQAIgGAFgKIASAJQgEAHgFAHQgFAFgGAEQgHAFgIACQgHACgJAAQgMABgKgGg");
	this.shape_18.setTransform(273.325,-118.05);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgTA7QgLgEgIgJQgIgIgEgMQgEgMAAgOQAAgNAEgMQAFgLAIgJQAIgIAKgGQALgEALAAQAMAAAKADQAKAEAIAJIAMAAIAAAUIgWAAQgFgJgHgEQgIgEgKAAQgGAAgHADQgHADgFAGQgFAGgDAJQgDAIAAAJQAAAKADAJQADAHAFAGQAFAHAHACQAHAEAGAAQALgBAJgFQAIgGAFgKIASAJQgEAHgFAHQgFAFgGAEQgHAFgIACQgHACgJAAQgMABgKgGg");
	this.shape_19.setTransform(260.225,-118.05);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgYA7QgIgCgFgGQgFgGgDgIQgDgJAAgLIAAg5IgQAAIAAgVIAnAAIAABLQAAAOAGAHQAHAHAMAAQAGAAAIgCQAIgDAHgFIAAhIIgQAAIAAgVIAnAAIAABlIANAAIAAAUIgjAAIAAgLQgIAGgKADQgKAEgKAAQgJAAgHgDg");
	this.shape_20.setTransform(245.025,-117.925);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_21.setTransform(231.975,-118.025);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_22.setTransform(215.225,-118.075);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_23.setTransform(202.425,-118.025);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgrBbIAAgUIASAAIAAhSIgUAAIAAgSIAUAAIAAgTQAAgLADgIQADgHAFgGQAFgFAIgDQAGgCAJAAIALAAIAJACIAHACIAFADIgHAPIgJgDIgNgCQgKAAgFAGQgFAGAAAMIAAAUIAbAAIAAASIgbAAIAABSIASAAIAAAUg");
	this.shape_24.setTransform(192.225,-121.075);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("Ag/BaIAAgUIARAAIAAiHIgRAAIAAgVIAmAAIAAAKQAIgGAJgDQAIgEAKAAQAMAAAKAFQAKAEAHAIQAHAIAEAMQAEALAAAOQAAAOgEANQgFALgHAIQgIAJgLAFQgLAEgNAAQgIAAgIgBIgNgFIAAAnIATAAIAAAUgAgLhCQgIADgFAGIAABBQADAEAIADQAHADAKAAQAHAAAHgCQAHgDAFgGQAGgGADgIQADgIAAgLQAAgLgDgIQgDgIgFgFQgFgGgHgCQgHgDgIAAQgHAAgIADg");
	this.shape_25.setTransform(173.925,-115.425);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgYA7QgIgCgFgGQgFgGgDgIQgDgJAAgLIAAg5IgQAAIAAgVIAnAAIAABLQAAAOAGAHQAHAHAMAAQAGAAAIgCQAIgDAHgFIAAhIIgQAAIAAgVIAnAAIAABlIANAAIAAAUIgjAAIAAgLQgIAGgKADQgKAEgKAAQgJAAgHgDg");
	this.shape_26.setTransform(158.225,-117.925);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgOAAQgHAAgJAEQgIADgFAGIAABGIAQAAIAAAUIg4AAIAAgUIASAAIAAg3QAAgOgHgHQgIgHgNAAQgHAAgIADQgIAEgGAFIAABHIARAAIAAAUIg5AAIAAgUIAQAAIAAhQIgQAAIAAgVIAnAAIAAAPIAIgHIAJgFIAKgEIALgBQANAAAKAFQAIAFAFAKIAJgHIALgHIALgEQAGgCAGAAQAKAAAIADQAIADAGAFQAFAGADAIQACAJABALIAAA6IARAAIAAAUg");
	this.shape_27.setTransform(133.75,-118.125);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgTA8QgLgFgIgHQgHgJgEgMQgFgLAAgQQABgNADgLQAEgMAHgJQAHgIALgFQALgFANAAQANAAAJAEQAJAFAHAGQAFAHADAJQADAJABAJIABAJIAAAIIhWAAIABAJIACAIQAEAMAJAGQAKAGAMgBQAJABAJgDQAIgDAKgFIAJAPQgMAIgMAEQgMAEgNAAQgLAAgKgEgAAfgNIgCgNQgCgGgDgEQgEgEgFgCQgGgDgIAAQgHAAgFADQgGACgEADQgEAFgDAFQgCAGgBAIIA+AAg");
	this.shape_28.setTransform(114.55,-118);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAMBbIAAgUIAQAAIAAg3QAAgOgHgGQgHgIgNAAQgHAAgHAEQgIADgHAFIAABHIASAAIAAAUIg6AAIAAgUIASAAIAAiNIgQAAIAAgUIAmAAIAABKIABAAIAHgGIAJgFIAKgDIAKgBQAJAAAIACQAIADAFAGQAGAFADAJQADAHAAAMIAAA6IASAAIAAAUg");
	this.shape_29.setTransform(100.225,-121.075);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_30.setTransform(87.725,-119.825);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_31.setTransform(73.575,-119.825);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgUA8QgKgFgIgHQgHgJgEgMQgFgLAAgQQABgNADgLQAEgMAHgJQAHgIALgFQALgFANAAQANAAAJAEQAJAFAHAGQAFAHADAJQADAJABAJIABAJIAAAIIhWAAIABAJIACAIQAEAMAJAGQAKAGAMgBQAJABAJgDQAIgDALgFIAIAPQgMAIgMAEQgMAEgNAAQgLAAgLgEgAAfgNIgCgNQgCgGgDgEQgEgEgFgCQgGgDgIAAQgHAAgFADQgGACgEADQgEAFgDAFQgCAGgBAIIA+AAg");
	this.shape_32.setTransform(61.9,-118);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgVBZQgKgEgGgEQgHgGgEgHQgEgGgCgHIgJAAIAAgUIAeAAQAAANADAFQACAGAGADQAEADAHACQAHACAHABQAIgBAGgCQAHgCAFgDQAEgEACgEQACgGABgHQgBgHgDgFQgDgEgEgEQgEgEgGgBIgLgFIgZgHQgIgCgHgDQgHgFgFgFQgFgGgDgIQgDgHAAgKQAAgKAEgJQAFgKAIgGQAHgHAMgEQALgDANAAQAJAAAJACQAHACAHAFQAGAEAGAFQAEAGADAGIAJAAIAAAUIgcAAQAAgKgEgFQgDgFgFgCQgEgEgGgBIgLgCQgIAAgGACQgHACgEAEQgFAEgCAFQgCAEAAAFQAAAIADAFQACAEAFADIAJAFIAKADIAWAIQALAEAIAEQAIADAFAGQAGAGADAHQADAIAAAKQAAALgEAKQgFAJgJAHQgHAHgMAEQgLAEgNAAQgNAAgKgDg");
	this.shape_33.setTransform(48.5,-120.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(-36,-137,430,60), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bb_boy();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,0,728,90), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEAMIgEgDIgDgEIgBgFIABgEIADgEIAEgDIAEgBIAFABIAEADIADAEIABAEIgBAFIgDAEIgEADIgFABg");
	this.shape.setTransform(394.525,-81.825);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAKA0IAAgSIAOAAIAAgsQAAgMgGgGQgGgGgLAAQgFAAgHADQgGADgGAEIAAA6IAOAAIAAASIgvAAIAAgSIAOAAIAAhCIgOAAIAAgQIAgAAIAAALIAHgFIAIgEIAIgDIAIgCQAJABAGACQAHACAEAEQAFAFACAIQADAGAAALIAAAuIAOAAIAAASg");
	this.shape_1.setTransform(385.675,-85.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUAyQgJgFgHgGQgGgIgEgJQgEgKAAgMQAAgLAEgKQAEgKAHgHQAGgHAKgEQAJgEAKAAQALAAAKAEQAJAEAGAHQAHAHAEAKQAEAJAAAMQAAALgEALQgEAJgHAIQgGAGgJAFQgKADgLAAQgKAAgKgDgAgLgjQgGADgEAEQgFAFgCAHQgDAIAAAIQAAAIADAHQACAIAFAEQAEAGAGACQAFADAGAAQAHAAAGgDQAFgCAFgGQAEgEACgIQADgHAAgIQAAgIgDgIQgCgHgEgFQgFgEgFgDQgGgCgHAAQgGAAgFACg");
	this.shape_2.setTransform(372.975,-85.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXBLIAAgRIAOAAIAAhDIgOAAIAAgQIAgAAIAABTIAPAAIAAARgAgEgxIgEgDIgDgEIgBgFIABgFIADgEIAEgDIAEgBIAFABIAEADIADAEIABAFIgBAFIgDAEIgEADIgFABg");
	this.shape_3.setTransform(363.95,-88.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgRAyQgIgEgEgGIgKAAIAAgRIAUAAQAAAEACADIAFAFIAGACIAHACIAIgCIAGgCIAEgEQACgDgBgEQAAgEgCgEQgEgDgHgDIgTgHQgLgDgGgHQgGgGAAgKQAAgGACgGQADgGAFgDQAEgEAGgCQAHgDAIAAQAKAAAIAEQAHACAFAIIAKAAIAAARIgUAAQAAgFgBgCQgCgDgEgCIgGgDIgHgBIgHABIgGADQgCABgBADQgCACABADQAAAFACADQADADAIADIASAHQANAEAFAGQAHAHgBALQAAAGgCAFQgDAGgFAEQgFAEgGACQgIACgIAAQgLAAgHgDg");
	this.shape_4.setTransform(355.8,-85.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXBLIAAgRIAOAAIAAhDIgOAAIAAgQIAgAAIAABTIAPAAIAAARgAgEgxIgEgDIgCgEIgCgFIACgFIACgEIAEgDIAEgBIAFABIAEADIACAEIABAFIgBAFIgCAEIgEADIgFABg");
	this.shape_5.setTransform(347.9,-88.125);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgIAzIghhVIgIAAIAAgQIAjAAIAAAQIgKAAIAYBFIAZhFIgHAAIAAgQIAgAAIAAAQIgIAAIghBVg");
	this.shape_6.setTransform(339.125,-85.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAKA0IAAgSIAOAAIAAgsQAAgMgGgGQgGgGgLAAQgFAAgHADQgGADgGAEIAAA6IAOAAIAAASIgvAAIAAgSIAOAAIAAhCIgOAAIAAgQIAgAAIAAALIAHgFIAIgEIAIgDIAIgCQAJABAGACQAHACAEAEQAFAFACAIQADAGAAALIAAAuIAOAAIAAASg");
	this.shape_7.setTransform(322.925,-85.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgUAyQgJgFgHgGQgGgIgEgJQgEgKAAgMQAAgLAEgKQAEgKAHgHQAGgHAKgEQAJgEAKAAQALAAAKAEQAJAEAGAHQAHAHAEAKQAEAJAAAMQAAALgEALQgEAJgHAIQgGAGgJAFQgKADgLAAQgKAAgKgDgAgLgjQgGADgEAEQgFAFgCAHQgDAIAAAIQAAAIADAHQACAIAFAEQAEAGAGACQAFADAGAAQAHAAAGgDQAFgCAFgGQAEgEACgIQADgHAAgIQAAgIgDgIQgCgHgEgFQgFgEgFgDQgGgCgHAAQgGAAgFACg");
	this.shape_8.setTransform(310.225,-85.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgXBJQgJgDgHgHQgGgGgEgLQgDgKAAgMQAAgNADgJQAEgIAGgIQAGgGAKgEQAIgDALAAQAHgBAGACQAGABAGAFIAAgnIgOAAIAAgRIAgAAIAACGIAOAAIAAARIggAAIAAgJQgFAGgGACQgHADgHAAQgLAAgIgEgAgOgJQgHACgDAFQgFAEgCAGQgCAGAAAJQAAAKACAGQACAIAEAFQAEAFAHACQAFACAHABQAHgBAGgCQAFgCAFgFIAAg4QgFgEgGgBQgHgCgGAAQgGAAgFACg");
	this.shape_9.setTransform(293.85,-88.15);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgQAyQgJgDgGgHQgHgHgDgKQgEgKAAgNQAAgLAEgJQACgJAHgIQAGgHAIgEQAJgFALAAQALAAAJAEQAHADAFAHQAEAFADAHQADAHAAAJIABAHIAAAHIhIAAIABAHIACAHQADAJAJAGQAHAEAKAAQAHAAAIgCQAIgCAHgFIAIANQgKAHgKADQgKAEgLgBQgJABgJgEgAAagLIgCgKQgCgFgCgDQgDgEgFgCQgFgCgGAAQgFAAgFACQgFACgEADIgEAIIgEALIA0AAg");
	this.shape_10.setTransform(281.6,-85.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgRAyQgIgEgEgGIgKAAIAAgRIAUAAQAAAEACADIAFAFIAGACIAHACIAIgCIAGgCIAEgEQACgDgBgEQAAgEgCgEQgEgDgHgDIgSgHQgNgDgFgHQgGgGAAgKQAAgGACgGQADgGAEgDQAFgEAGgCQAHgDAIAAQAKAAAIAEQAHACAFAIIAKAAIAAARIgUAAQAAgFgCgCQgBgDgEgCIgGgDIgHgBIgHABIgGADQgCABgBADQgCACABADQAAAFACADQADADAIADIATAHQAMAEAGAGQAFAHAAALQABAGgDAFQgDAGgFAEQgFAEgGACQgIACgIAAQgLAAgHgDg");
	this.shape_11.setTransform(271.3,-85.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgZAzQgGgDgEgEQgFgEgCgFQgDgFAAgHQAAgGACgFQACgFADgEQADgDAFgCIAIgEIAKgCIAJgBIALABIAJABIAAgIQAAgGgCgDQgBgEgDgDQgDgDgEgBQgEgBgEAAIgJABIgHABIgHADIgGACIgFgMIAHgFIAKgDIAJgCIAKgBQAIAAAHACQAHACAFAEQAEAFADAHQADAGAAAKIAAAxIALAAIAAARIgeAAIAAgJQgFAFgHAEQgGADgJAAQgIAAgGgCgAgNAFQgEABgEADQgDACgCADQgBAEAAAEQAAAEABADIAEAFQADACAEABIAIABIAHgBIAGgCIAGgEIAEgEIABgXIgVAAIgJABg");
	this.shape_12.setTransform(260.875,-85.675);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgJBLQgGgDgFgDIAAAGIgSAAIAAiGIgPAAIAAgRIAhAAIAAA7QAHgFAHgCQAGgDAIAAQALAAAIADQAIAEAHAHQAFAHAEAIQADAJAAAMQAAAMgEAKQgEAKgGAHQgGAHgKAEQgJAEgKAAQgHAAgHgCgAgJgIQgGADgFAEIAAA2QADADAGADQAGACAIAAQAGAAAHgCQAFgDAFgEQAEgFADgHQACgHAAgKQAAgIgCgHQgDgGgEgEQgEgFgGgCQgGgCgGAAQgGAAgHADg");
	this.shape_13.setTransform(249.35,-88.175);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgRAyQgIgEgEgGIgKAAIAAgRIAUAAQAAAEACADIAFAFIAHACIAGACIAIgCIAGgCIAEgEQABgDABgEQAAgEgDgEQgEgDgIgDIgSgHQgMgDgFgHQgGgGAAgKQAAgGACgGQADgGAFgDQAEgEAGgCQAHgDAIAAQAKAAAIAEQAHACAFAIIAKAAIAAARIgUAAQAAgFgBgCQgDgDgDgCIgHgDIgGgBIgHABIgGADQgCABgBADQgBACAAADQAAAFACADQADADAIADIASAHQANAEAFAGQAHAHAAALQgBAGgCAFQgDAGgFAEQgFAEgGACQgIACgIAAQgLAAgHgDg");
	this.shape_14.setTransform(234.2,-85.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgXBLIAAgRIAPAAIAAhDIgPAAIAAgQIAgAAIAABTIAPAAIAAARgAgEgxIgEgDIgCgEIgCgFIACgFIACgEIAEgDIAEgBIAFABIAEADIACAEIABAFIgBAFIgCAEIgEADIgFABg");
	this.shape_15.setTransform(226.3,-88.125);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgLBJIgLgCIgKgEQgGgDgEgEIAKgPIAGAFIAIADIAJADIAJABQAHAAAFgCQAGgBADgEQAEgEACgHQACgGAAgLIAAgCQgFAGgHADQgHADgIAAQgKAAgIgEQgJgDgHgHQgGgHgEgKQgDgJAAgNQAAgMADgKQAEgJAGgHQAGgGAKgFQAIgDAKAAQAJAAAGABQAFACAHAFIAAgGIASAAIAABgQAAAZgMAMQgMAMgXAAgAgHg3QgHACgDAGQgFAEgCAGQgCAHAAAJQAAAJACAHQACAHAEAFQAEAEAHADQAFACAGAAIAIgBIAHgCIAFgEIAFgDIAAg3QgFgEgHgCQgGgCgIAAQgFAAgFACg");
	this.shape_16.setTransform(405.2,-108.75);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAKAzIAAgQIAOAAIAAguQAAgLgGgGQgGgGgLAAQgFAAgHADQgGADgGAEIAAA7IAOAAIAAAQIgvAAIAAgQIAOAAIAAhDIgOAAIAAgRIAgAAIAAAMIAHgFIAIgFIAIgDIAIgBQAJAAAGACQAHADAEAEQAFAFACAHQADAHAAAKIAAAwIAOAAIAAAQg");
	this.shape_17.setTransform(393.025,-110.95);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgXBLIAAgRIAPAAIAAhDIgPAAIAAgQIAgAAIAABTIAPAAIAAARgAgEgxIgEgDIgCgEIgCgFIACgFIACgEIAEgDIAEgBIAFABIAEADIACAEIABAFIgBAFIgCAEIgEADIgFABg");
	this.shape_18.setTransform(383.25,-113.275);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAKAzIAAgQIAOAAIAAguQAAgLgGgGQgGgGgLAAQgFAAgHADQgGADgGAEIAAA7IAOAAIAAAQIgvAAIAAgQIAOAAIAAhDIgOAAIAAgRIAgAAIAAAMIAHgFIAIgFIAIgDIAIgBQAJAAAGACQAHADAEAEQAFAFACAHQADAHAAAKIAAAwIAOAAIAAAQg");
	this.shape_19.setTransform(373.325,-110.95);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgjAzIAAgRIANAAIABhCIgOAAIAAgRIAgAAIAAAOIADgGIAFgFIAGgDIAHgBIAJAAIAJAAIAAAWIgSAAIAAgGIgHABIgGAEQgDADgCAEQgBADgBAGIAAAvIAQAAIAAARg");
	this.shape_20.setTransform(361.925,-110.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgZAzQgGgDgEgEQgFgEgCgFQgDgFAAgHQAAgGACgFQACgFADgEQADgDAFgCIAIgEIAKgCIAJgBIALABIAJABIAAgIQAAgGgCgDQgBgEgDgDQgDgDgEgBQgEgBgEAAIgJABIgHABIgHADIgGACIgFgMIAHgFIAKgDIAJgCIAKgBQAIAAAHACQAHACAFAEQAEAFADAHQADAGAAAKIAAAxIALAAIAAARIgeAAIAAgJQgFAFgHAEQgGADgJAAQgIAAgGgCgAgNAFQgEABgEADQgDACgCADQgBAEAAAEQAAAEABADIAEAFQADACAEABIAIABIAHgBIAGgCIAGgEIAEgEIABgXIgVAAIgJABg");
	this.shape_21.setTransform(351.675,-110.825);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgQAyQgJgEgGgGQgHgHgDgKQgEgKABgNQAAgKACgKQAEgKAFgGQAGgIAKgEQAJgEAKAAQAMAAAHADQAIAEAFAFQAEAGADAIQADAGABAIIAAAIIABAGIhIAAIAAAIIACAHQAEAKAHAEQAIAGAJAAQAJAAAHgCQAHgDAJgEIAHAMQgKAGgKAEQgKADgLABQgJgBgJgDgAAagLIgCgLQgBgEgDgEQgDgDgFgCQgFgCgGAAQgGAAgEACQgFABgDAEIgGAIIgCALIAzAAg");
	this.shape_22.setTransform(340.4,-110.85);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgXBMIAAgRIAPAAIAAh1IgPAAIAAgRIAgAAIAACGIAPAAIAAARg");
	this.shape_23.setTransform(331.75,-113.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgRAxQgIgDgEgHIgKAAIAAgQIAUAAQAAAEACADIAFAFIAHACIAGABIAIgBIAGgCIAEgFQABgCAAgDQAAgFgCgDQgEgEgIgDIgSgHQgMgDgFgHQgGgGAAgKQAAgGACgGQADgFAFgEQAEgEAGgDQAHgBAIAAQAKAAAIACQAHADAFAHIAKAAIAAARIgUAAQAAgDgBgEQgDgCgDgCIgHgDIgGAAIgHAAIgGADQgCACgBACQgBACAAADQAAAFACADQADADAIACIASAHQANAFAFAGQAHAHAAAKQgBAHgCAGQgDAFgFAEQgFAEgGADQgIACgIAAQgLAAgHgFg");
	this.shape_24.setTransform(319.25,-110.85);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgKAaIAAgyIAVgBIgFAzg");
	this.shape_25.setTransform(312.625,-118.75);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgYBKQgIgEgGgGQgHgHgEgKQgDgLgBgNQABgMADgJQAEgIAGgIQAHgGAIgEQAKgEAKAAQAHAAAGACQAGABAFAEIAAgmIgNAAIAAgRIAgAAIAACGIAPAAIAAARIgiAAIAAgJQgEAFgGAEQgHACgIAAQgJAAgKgDgAgPgJQgGACgEAFQgEAEgCAGQgCAGgBAJQAAAJACAHQADAIAEAFQAFAEAFADQAGACAHAAQAHAAAFgCQAGgDAEgEIAAg4QgEgEgGgCQgHgCgFAAQgHABgGACg");
	this.shape_26.setTransform(305.05,-113.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgXBMIAAgRIAPAAIAAh1IgPAAIAAgRIAgAAIAACGIAPAAIAAARg");
	this.shape_27.setTransform(295.6,-113.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgXBLIAAgRIAPAAIAAhDIgPAAIAAgQIAgAAIAABTIAPAAIAAARgAgEgxIgEgDIgCgEIgCgFIACgFIACgEIAEgDIAEgBIAFABIAEADIACAEIABAFIgBAFIgCAEIgEADIgFABg");
	this.shape_28.setTransform(289.2,-113.275);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAKBMIAAgRIANAAIAAguQABgLgHgGQgGgFgKgBQgGAAgGAEQgHADgFADIAAA7IAOAAIAAARIgwAAIAAgRIAQAAIAAh1IgPAAIAAgRIAhAAIAAA+IABAAIAGgFIAHgEIAIgDIAIgBQAIAAAHACQAGACAEAFQAFAEADAIQADAGgBAKIAAAwIAQAAIAAARg");
	this.shape_29.setTransform(279.45,-113.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgQAyQgJgEgGgHQgHgIgDgJQgEgKAAgMQAAgLAEgKQAEgJAGgIQAHgHAJgEQAJgEAJAAQAKAAAIAEQAJADAGAHIAKAAIAAARIgSAAQgEgIgHgDQgGgEgIAAQgGAAgFADQgFADgFAFQgEAEgCAHQgDAHAAAIQAAAIADAHQACAHAEAFQAFAFAFACQAFADAGAAQAJAAAHgFQAHgEAEgJIAPAIQgCAGgFAFIgJAIQgGAEgHACQgGACgHAAQgKAAgJgEg");
	this.shape_30.setTransform(267.3,-110.875);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgZAzQgGgDgEgEQgFgEgCgFQgDgFAAgHQAAgGACgFQACgFADgEQADgDAFgCIAIgEIAKgCIAJgBIALABIAJABIAAgIQAAgGgCgDQgBgEgDgDQgDgDgEgBQgEgBgEAAIgJABIgHABIgHADIgGACIgFgMIAHgFIAKgDIAJgCIAKgBQAIAAAHACQAHACAFAEQAEAFADAHQADAGAAAKIAAAxIALAAIAAARIgeAAIAAgJQgFAFgHAEQgGADgJAAQgIAAgGgCgAgNAFQgEABgEADQgDACgCADQgBAEAAAEQAAAEABADIAEAFQADACAEABIAIABIAHgBIAGgCIAGgEIAEgEIABgXIgVAAIgJABg");
	this.shape_31.setTransform(251.825,-110.825);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgkBMIAAgRIAPAAIAAhFIgQAAIAAgOIAQAAIAAgQQAAgJADgHQACgGAEgFQAFgDAGgDQAFgCAHAAIAKAAIAHACIAGABIAEADIgGAMIgIgCQgFgBgFAAQgIAAgFAEQgEAGAAAKIAAAQIAXAAIAAAOIgXAAIAABFIAPAAIAAARg");
	this.shape_32.setTransform(239.625,-113.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgUAxQgJgDgHgIQgGgGgEgLQgEgJAAgMQAAgLAEgKQAEgKAHgHQAGgHAKgEQAJgDAKAAQALAAAKADQAJAEAGAHQAHAHAEAKQAEAKAAALQAAALgEAKQgEALgHAGQgGAIgJADQgKAFgLAAQgKAAgKgFgAgLgiQgGACgEAFQgFAEgCAHQgDAIAAAIQAAAIADAIQACAHAFAFQAEAFAGADQAFACAGAAQAHAAAGgCQAFgDAFgFQAEgFACgHQADgIAAgIQAAgIgDgIQgCgHgEgEQgFgFgFgCQgGgDgHAAQgGAAgFADg");
	this.shape_33.setTransform(228.925,-110.85);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(221,-127,192.60000000000002,53.3), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjGDzIFEnlIA8AAIlEHlgABbDpQgUgIgNgOQgOgPgIgTQgIgSAAgWQAAgVAIgTQAIgTAOgOQAOgOAUgIQAUgIAXgBQAYABATAIQAUAIAOAOQAOAOAIATQAIATAAAVQAAAWgHASQgIATgOAPQgOAOgUAIQgTAIgZAAQgYAAgUgIgABzBYQgKAEgIAIQgHAHgEAJQgFAKAAALQAAALAFAKQAEAKAHAHQAIAHAKAFQAJAEALAAQALAAAKgEQAKgFAHgHQAHgHAEgJQAEgLAAgLQAAgLgEgKQgEgJgHgHQgHgIgKgEQgKgDgLAAQgLAAgJADgAiygdQgUgJgOgPQgOgOgHgSQgIgUAAgVQAAgUAIgTQAHgUAPgOQAOgOATgIQAUgJAYABQAXgBAUAJQATAIAOAOQAPAOAIAUQAHATAAAUQAAAVgHAUQgIASgOAOQgOAPgUAJQgTAHgYABQgZgBgTgHgAibiuQgKAEgIAHQgHAGgEALQgEAJAAALQAAAMAEAKQAEAJAHAHQAIAIAKAEQAJAEAMAAQALAAAJgEQAKgEAHgIQAHgHAFgJQAEgKAAgMQAAgLgEgJQgFgLgHgGQgHgHgKgEQgJgEgLAAQgMAAgJAEg");
	this.shape.setTransform(156.025,-26.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhVDhQghgTgVghQgVghgIgsQgJgsAAgyQAAg2AMguQAMgwAUgcQAUgcAegUQAfgUA0AAQAyAAAhAPQAiAQAWAiQAVAgAJAvQAJAuAAA0QAAAzgJAsQgJAsgUAhQgVAhgjATQgiATgyAAQgyAAgjgSgAg6itQgWAQgKAWQgLAWgFAmQgHAmAAAlQAAAmAEAjQAEAiAMAZQAMAaAWAPQAWAPAlAAQAkAAAWgPQAXgPALgaQAMgZAFgiQAGgjgBgmQABglgFgiQgEgigNgaQgMgagXgQQgWgQgkAAQglAAgVAQg");
	this.shape_1.setTransform(110.45,-26.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag6DpQgbgMgWgTQgUgUgMgaQgMgaAAgdQAAgTAGgSQAEgSAKgQQAKgPANgNQANgMAQgKQgYgRgOgZQgOgaAAgfQAAgZALgXQAKgXATgQQARgRAYgKQAZgKAaAAQAbAAAZAKQAXAKATARQARAQAMAXQAKAXAAAZQAAAfgPAaQgOAagYARQAQAJANAMQANANAKAQQAIAPAGASQAFASAAATQAAAdgMAaQgMAagVAUQgVATgbAMQgcALgfAAQgeAAgcgLgAgkASQgRAGgMANQgOAMgIAQQgHAQAAASQAAATAHAQQAIARAOAMQAMAMARAHQASAHASAAQAUAAARgHQARgHAOgMQAMgMAIgRQAHgQAAgTQAAgSgHgQQgIgQgMgMQgOgNgRgGQgRgIgUAAQgSAAgSAIgAgdi6QgPAGgKAKQgLAKgGAOQgFANgBAQQABAPAFAOQAGANALALQAKAKAPAGQAOAGAQAAQARAAAOgGQAOgGAKgKQAMgLAFgNQAHgOAAgPQAAgQgHgNQgFgOgMgKQgKgKgOgGQgOgGgRAAQgQAAgOAGg");
	this.shape_2.setTransform(71.6,-26.375);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(50,-66,133.6,81.3), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol6();
	this.instance.parent = this;
	this.instance.setTransform(551.4,185.65,1,1,0,0,0,13.2,13.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(125).to({_off:false},0).to({alpha:1},14).wait(145).to({_off:true},1).wait(225));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A7iQiIAAmbIBJAAIAAA0IAEgGIAOgSIAYgTIAHgEIAOgGIAQgFIAWgDIAaABIAjAKIAGADIATALIAXATIATAXIAOAeIAIAXIAFAvIgFAuIgIAYIgKAWIgNATIgVAUIgMAJIggAQIgVAFIgVADIgagBIgYgFIgVgKIgMgIIgQgPIgOgQIAACQgA5OK/IgMADIgFACIgMAFIgLAIIgHAGIgJALIgDADIgKARIgGATIgDAQIAAAXIADAQIAGATIAKARIAJALIAOAMIALAIIARAGIAEABIAEABIAOABIAOgBIAEgBIAEgBIARgGIAIgFIAOgMIAMgOIAHgMIAJgYIACgQIAAgXIgCgRIgJgXIgHgNIgPgRIgLgIIgMgGIgRgGIgOgBgEAl6AQfIgegEIgrgQIgCgCIonk8IIqklIACgBIAngMIAkgFIAsAAIAmAHIAZAJIIQEpIhhA4Imkj9IgCgBIgVgMIgngNIgegEIgeABIgSACIhCAYIlnDGIF9DhIABABIAKAFIAmAMIAfABIAIgBIAjgJIAQgHID9iWIj9iTIgBgBIgJgFIgQgFIgSgFIgUgBIgQACIgxAQIgBABIjUB7Ihng1IEtifIA4gUIAOgDIAHgBIAhACIAWAEIAHADIAGACIASAIIGdDsImiDyIgBACIgeALIgNAFIgfAEgAWZPHIgRgDIgjgLIgZgLIgfgUIAhgyIATANIAaAOIAnAKIANABIAWgBIAFgBIAMgEIAHgEIAFgFIADgGIACgIIAAgIIgBgHIgCgDIgBgBIgFgFIgRgLIhjgiIgLgGIgEgEIgNgLIgIgKIgIgRIgCgKIgBgWIABgLIAEgOIACgFIABgFIALgQIADgEIADgEIAQgNIASgJIAFgCIAagHIAuAAIAmAIIAeAMIAbAPIgcAyIgjgRIgSgHIgcgGIgQgBIgOADIgLAEIgFAFIgFAFIgDAHIgBAGIAAAJIABACIAAABIABACIABADIABABIACACIADADIAEADIAUAKIBCAWIAhARIALAIIAKAJIAKAOIAFAMIABAFIACAFIABAPIgBASIgEAQIgEAJIgIAOIgDAEIgLALIgVAOIgPAGIgWAFIgYADgASlPHIgNgDIgQgHIgHgEIgGgGIgIgJIgJgPIgGgTIgCgRIAAizIgqAAIAAg9IAqAAIAAhZIBIAAIAABZIBWAAIAAA9IhWAAIAAChIABAIIAFALIACACIAFAGIADACIADABIAHACIANABIAdgDIAPgFIAAA6IgJAGIgTAHIgaAEgAOPPJIgjgFIgSgEIgZgKIghgRIgPgLIAigyIAfAVIANAGIAnAKIAZABIAKgBIAFgBIAQgGIAIgHIACgDIACgDIABgEIAAgEIAAgKIgBgFIgCgDIgBgBIgEgFIgIgFIgQgIIhTgcIgUgKIgNgMIgIgKIgIgQIgCgEIgCgKIgBgQIABgRIAEgOIAEgKIAHgNIAJgLIAEgEIALgJIASgJIAZgHIARgDIATAAIAfAEIAXAFIAxAXIAGAEIgcAyIgugWIghgIIgPgBIgGABIgJACIgLAEIgCADIgDACIgEAFIgCAEIgCAGIAAAEIAAAFIACAIIAGAJIAIAGIAPAHIBbAiIAPAKIANAMIAIAKIACADIAGANIACAKIABAJIgBAYIgEAQIgEAJIgIAOIgDAEIgKALIgJAGIgEADIgEADIgUAIIgWAFIgYADgAD9PHIgNgDIgQgHIgKgGIgMgNIgDgDIgIgRIgDgJIgDgWIAAizIgnAAIAAg9IAnAAIAAhZIBIAAIAABZIBWAAIAAA9IhWAAIAAClIACAIIACADIACAEIABACIAFAGIADACIAHACIARACIASgBIAdgHIAAA6IgHAEIgPAHIgIACIgbAEgAhOPEIgQgEIgcgNIgHgEIgXgTIgLgMIgNgTIgKgVIgIgYIgFgrIAHgyIAFgPIAWgpIAagcIASgNIAcgMIAQgFIAXgDIASAAIAjAGIAWAIIAOAHIAYATIAOASIAQAaIAKAfIAFAXIADA2IjpAAIACAOIAGARIAIAOIARARIADADIAHAEIAPAHIAMACIAJABIAEABIAVAAIALgCIAQgFIAFgDIAPgIIAagUIAqAmIgMAOIgcAVIgPAIIgaAKIgcAFIgeABgAg9K9IgMACIgHAEIgMAHIgLALIgKANIgJASIgHAbICjAAIgDgSIgIgWIgJgOIgKgLIgIgHIgGgEIgLgFIgQgCIgIgBgAwIPEIgngOIgVgOIgdgbIgFgGIgWgpIgIggIgCgZIACgZIAIghIAWgqIAigiIAVgNIAfgMIAQgFIAagDIATAAIAaADIAQAFIAfAMIAVANIAMALIAWAXIANAVIAJAVIAJAhIABAQIgBAhIgEAQIgOAlIgNAUIgWAYIgTAPIgdAPIggAJIgJACIgkACgAv2LBIgOAFIgRAKIgLAJIgGAHIgLAQIgEAJIgIAdIgBAKIABAUIADAPIACAFIAKAWIADAEIAMAPIAEACIAHAHIAMAIIAJADIATAGIAPABIARgBIATgGIAVgLIAOgNIAMgPIACgFIACgDIAGgOIAEgUIABgUIgCgQIgJgcIgLgQIgGgIIgWgSIgFgCIgEgCIgJgDIgEgCIgKgCIgVgBgAz1PJIgXgDIgIgCIgIgDIgPgIIgHgGIgIgJIgHgLIgEgJIgEgOIgCgRIgBizIgmAAIAAg9IAmAAIAAhZIBJAAIAABZIBWAAIAAA9IhWAAIAAChIAAAEIACAIIADAHIAFAFIAFAFIADABIAIACIANABIAdgDIASgFIAAA6IgPAIIgPAFIgbAEgEgtiAPJIgjgFIgfgLIgIgDIgagSIgGgGIgRgRIgKgMIgPgcIgDgHIgFgQIgEgYIABgqIADgQIAIgYIAPgdIAFgGIAQgSIAZgVIANgIIAfgMIAZgGIAkgCIArAIIAfAMIAbASIAWAXIASAbIANAdIAGAhIABAZIgDAYIgRAtIgNAUIgVAYIgTAPIgdAPIgQAGIgrAHgEgtzALBIgOAFIgIAEIgXASIgGAIIgKAQIgIAYIgBAEIgBAaIABAKIADAPIAFAOIAJARIAJALIALAKIAQALIAJADIATAGIAPABIAagDIAOgFIARgKIAHgHIAEgCIAMgPIAFgJIAHgRIAEgOIACgVIgCgVIgKgcIgQgYIgXgSIgIgEIgJgDIgFgCIgKgCIgUgBgEggoAPIIgigGIgVgGIgdgNIgTgLIgYgTIgWgXIgMgQIgPgbIgOgnIgGggIAAguIAGgfIAGgVIASglIASgaIAVgWIAZgUIAmgVIAggKIAWgEIAkgDIAuAFIAqAMIAdAOIAZATIAXAVIATAZIAPAbIAIATIAKAqIADAhIgDAhIgKAqIgIATIgPAbIgaAhIgYAUIgbARIgeANIg4AMgEggoAJbIgcAIIgGACIgTAKIgLAIIgPAPIgNAQIgLASIgKAbIgDAOIgDAXIAAAPIADAYIADAOIALAbIAPAYIAOAPIAWASIATAJIAVAIIAWADIAPABIAXgCIAVgEIAUgIIAGgEIALgHIAQgOIAOgPIAMgRIAGgNIAJgbIADgVIABgZIgBgIIgFgcIgIgVIgGgNIgQgXIgagYIgGgEIgagNIgVgGIgPgCIgeAAgAKMPDIAAk8IBIAAIAAE8gAGaPDIAAk8IBIAAIAABFIATggIAPgRIAHgFIADgDIAMgGIADgDIAVgIIAOgDIAUgBIAABOIgiADIgUAHIgKAEIgQAOIgLALIgLAUIgEALIgFATIgDAkIAAB6gAlUPDIgBjGIgEgQIAAgDIgEgKIgKgOIgHgGIgCgCIgDgCIgDgBIgDgBIgDgBIgDgBIgDgBIgDgBIgIgBIgEAAIgDgBIgEABIgDAAIgOADIgKADIgDABIgCACIgDACIgDACIgIAHIgIALIgCADIgCAEIgBADIgBADIgCAEIgCAIIgBAJIgBADIAAC+IhIAAIAAi0IgCgaIgEgOIgCgEIgBgDIgCgDIgCgDIgDgFIgKgJIgCgCIgDgCIgDgBIgDgBIgDgBIgDgBIgDgBIgDgBIgIgBIgDAAIgEgBIgEABIgDAAIgHABIgNAEIgJAFIgFAEIgJAKIgGAJIgFAKIgEAQIgCAMIAAC7IhLAAIAAk8IBLAAIAAAvIAEgFIARgVIAKgJIAMgIIANgGIAOgEIAUgDIAVABIAQADIAbALIAPANIAJAKIAIALIADAHIAFgHIAXgVIATgNIAdgLIAQgDIAXgBIAYADIARAFIAOAHIAEADIAJAHIAIAHIAMARIALAbIAGAgIAADZgEgphAPDIAAj/IgqAAIAAg9IAqAAIAAgkIAGghIAEgJIABgEIAIgMIAJgKIATgMIANgFIAPgEIAWgBIAnADIATAGIAAA9IgKgEIgQgDIgUgBIgFAAIgMAEIgEABIgFAFIgFAHIgDAIIgDAPIAAAaIBTAAIAAA7IhTAAIAAD/gEAl4AOiIgTgEIgSgGIgRgJIgQgLIgRgSIgLgPIgJgSIgGgSIgEgUIAAgcIAEgSIAGgTIAJgRIAPgUIANgNIAQgLIARgJIAMgEIAZgFIAUgBIAiAGIAYAKIAFADIAQALIAOANIAPAUIAJARIAIAZIACAUIAAANIgCAVIgIAYIgDAGIgJASIgRATIgOANIgWANIgMAFIgTAFIgbACgEAnSAEzIgHgCIgZgGIgjgCIgSABIgbAGIgRAHIpOEsIAA6EIUAAAIAAaEgAKJJUIAAhFIBOAAIAABFgAP0F1IgRgEIgXgJIgOgIIgUgNIgRgRIgKgMIgQgcIgGgOIgGgXIgDghIABgTIAEgYIALgeIAVghIALgMIAZgUIAdgPIAYgIIAigGIASAAIAjAGIAYAHIAPAHIAVANIAXAVIAUAZIAKAVIAIAXIAFAhIAAARIgFAhIgIAYIgKAVIgKANIgVAYIgiAXIgnAPIgSAEIgbACgAP9BxIgOAEIgMAHIgLAIIgMANIgIANIgEAIIgEAOIgEAZIACAZIABAEIABAGIALAbIAJALIANANIAEAEIAMAHIATAHIAUAEIALAAIAFgBIALgBIAJgDIARgIIAIgEIAOgMIAIgMIADgDIAIgSIAFgYIABgSIgBgPIgDgOIgDgKIgGgMIgFgIIgPgSIgQgKIgEgDIgEgCIgOgEIgVgEIgLAAgADEF0IgVgGIgEgDIgFgCIgNgIIgEgDIgOgOIgJgNIgGgOIgEgPIgBgSIABgSIABgHIAFgQIAFgJIAJgNIAMgLIANgKIAPgHIAFgCIAGgCIALgDIAmgFIBDAGIAdAGIAAgOIgDgPIgBgDIgBgDIgIgPIgFgEIgNgJIgHgEIgWgFIgZgBIgkAEIgRAEIggAMIgTg7IAGgDIAhgNIAdgHIAqgFIAjABIAkAIIAMAGIARAJIASARIAEAEIAKAQIAIASIAEANIADAWIABDRIhFAAIAAgnIgEAFIgaAXIgTAJIgVAHIghAEgAD0DgIgVAFIgLAFIgKAHIgFAFIgCADIgDADIgDAIIAAACIgBADIAAADIgBACIAAAGIABADIAAACIABADIAAADIACAEIABADIAGAIIAHAGIAJAGIAQAFIAMACIAPAAIANgCIALgDIAPgGIAGgEIADgCIADgCIAKgJIACgEIACgCIACgDIAEgJIACgHIABgEIABgDIAAgYIgYgIIgmgFgAj8F3IgYgGIgegMIgagSIgRgRIgKgMIgMgVIgKgVIgGgXIgDghIAAgLIADgYIAJgfIAHgOIARgaIAWgXIAagSIAOgGIAYgIIAhgGIApACIAjAKIAXALIAaATIAMAMIgtAyIgEgFIgWgSIgggOIgTgDIgVABIgJADIgNAEIgQAJIgQAQIgKAQIgGAMIgHAdIAAAVIAFAZIAIASIAHANIAGAHIAEADIADADIALAJIAMAHIAOAEIAUAEIAEAAIAUgCIARgFIAPgIIAPgJIARgQIAtAtIggAdIgnAUIgcAHIggADgAp/F3IgagGIgmgRIgTgNIgSgRIgPgSIgSgkIgGgXIgDgQIAAgkIADgQIAJgfIAPgcIAKgMIARgRIAZgTIAXgLIAYgIIAigGIASAAIAjAGIAYAHIAdAPIANAJIARARIAPASIAPAcIAGAPIAGAgIAAAiIgGAhIgGAQIgLAVIgTAaIgRAQIgUAOIgeAOIghAJIgbACgAp/BxIgOAEIgIAFIgQAKIgNANIgHANIgLAbIAAAEIgBAFIgBAPIABAQIACAJIAGATIAEAJIALAQIAEADIAGAHIAIAHIAQAJIAOAFIAUAEIAKAAIAVgEIAXgJIAMgHIAKgJIALgPIAJgSIADgJIADgTIAAgYIgCgKIAAgEIgFgPIgEgJIgHgLIgJgMIgHgGIgPgKIgJgFIgOgEIgKgDIgUgBgAvUF3IgjgIIgzgYIgWgRIAegvIAvAaIAUAIIAaAEIASABIAGgBIASgEIAHgFIAGgFIAEgGIACgDIACgIIAAgIIgBgDIgBgEIgCgBIAAgCIgCgCIgDgEIgEgCIgJgGIgKgEIhMgZIgdgPIgKgIIgJgKIgIgLIgGgRIgDgPIAAgMIAFgaIAEgKIAIgMIAGgIIAOgNIAJgGIAEgBIAFgEIAZgIIAcgEIAVABIAfAFIAWAGIAeANIATALIgcA2IgdgRIgXgIIgXgFIgVgBIgKABIgEACIgEAAIgEACIgJAGIgEAFIgDAFIgBADIgBAEIAAAHIACAGIABACIABACIABACIABABIAMAJIAQAIIBBAVIAaAMIATANIAJAJIAJAKIAEAIIAEAMIACAJIAAAZIgGAbIgIAOIgJAMIgLAKIgNAJIgUAIIgcAHIgYACgA0BF2IgagHIgzgYIgXgRIAigvIAmAYIAaAKIAaAEIAYAAIAJgCIAJgCIAHgFIADgCIAFgGIACgDIACgDIACgIIAAgHIgBgBIAAgDIgBgCIAAgCIgDgDIgEgGIgEgCIgJgGIgKgEIhDgWIgagLIgEgCIgIgFIgNgLIgJgKIgCgEIgDgEIgGgRIgCgLIgBgQIABgFIAEgVIAEgKIADgDIACgFIAGgIIANgOIANgJIAEgBIAFgEIAEgCIAagHIAXgDIAVABIAfAFIAWAGIAkAQIANAIIgcA2IgFgEIgYgNIgXgIIgXgFIgLgBIgUABIgIACIgEACIgGAEIgFAEIgCADIgDAFIgBADIgBAEIAAAKIABABIABACIABACIABACIABACIABABIAHAGIAFADIAVAKIA8ATIAaAMIATANIAMAMIAIAKIAGARIADAPIAAANIgCAMIgEAQIgEAKIgHANIgHAIIgLAKIgEADIgdAOIgcAHIgYACgAI7F0IgEgBIgFAAIgIgCIgMgEIgHgEIgKgHIgJgJIgHgLIgBgEIgCgFIgGgUIgBi+IgqAAIAAhAIAqAAIAAhWIBIAAIAABWIBWAAIAABAIhWAAIAAChIADAMIADAIIAHAHIAJAEIAMACIAXgBIAQgEIALgGIAAA7IgHAEIgVAIIgaAFgAXcFwIgBjGIgEgSIgCgDIgBgEIgBgCIgCgDIgIgLIgFgEIgCgBIgDgCIgFgEIgDgBIgEgBIgDgBIgDgBIgQgCIgIAAIgOACIgEABIgDABIgEABIgDABIgDACIgGAEIgIAGIgHAHIgCAEIgEAFIgGAPIgDALIgBAJIAAC7IhIAAIAAk9IBIAAIAAAyIAXgbIAFgEIASgMIAVgIIAYgFIAdABIAXAGIAQAHIASAMIAOAQIAGAJIAIAPIAGAYIADAaIAADPgALdFwIAAk9IBIAAIAAE9gAgdFwIAAk9IBKAAIAAE9gA3WFwIgqhkIjIAAIgqBkIhOAAIC6mmIBGAAIC3GmgA6tDJICRAAIhIimgALaADIAAhDIBNAAIAABDgAgfADIAAhDIBMAAIAABDgAVvjRIglgIIgKgEIgNgHIgIgGIgLgKIgGgIIgIgMIgGgPIgDgQIAAgbIACgLIAFgRIAIgOIADgFIAHgIIALgKIAJgGIAVgKIAXgGIAggEIA4AEIAoAIIAAgKIgCgOIgDgKIgFgIIgGgIIgKgJIgDgBIgDgDIgGgDIgDAAIgEgCIgPgEIgZgBIgpAGIgsAOIgUg6IAwgTIBBgJIAjABIAdAGIAeANIAUAQIAMANIAJARIAJAZIAFAlIAADDIhIAAIAAgoIgJALIgQANIgRAKIgVAIIgfAGgAV7lnIgGACIgLAGIgKAGIgGAFIgDAFIgBACIgBACIgCAGIgCAIIAAALIACAHIACAFIABACIACAEIAHAIIAIAFIAKAFIARAEIARABIAEgBIAEAAIAYgFIAOgHIAJgGIAHgGIAHgJIAGgMIACgGIACgLIAAgVIgHgCIgQgGIgdgEIglAAgAJDjSIgYgEIgXgHIgVgLIgTgMIgQgQIgTgZIgKgWIgJggIgDgjIABgbIAFgXIAIgXIAPgbIAJgMIAWgVIAggUIAXgIIAYgFIAjAAIAhAIIAcAMIASAOIAPAQIAJANIAOAbIALAlIAEBAIjqAAIABAGIABADIABAGIADAIIACADIABAFIAGALIANAPIAGAFIAEACIADADIAKAGIALAEIAVAEIAcgBIAMgCIAQgHIAUgMIATgQIAqAmIgGAHIgaAXIgPAJIgiAOIgnAGgAIxndIgHADIgKAGIgJAIIgOASIgIATIgDAIIgDARICiAAIgDgRIgEgRIgFgKIgGgKIgIgIIgFgGIgNgIIgIgDIgQgEIgNgBIgEAAIgEAAgADSjSIgZgGIgWgKIgSgOIgQgOIgIgLIAAAwIhJAAIAAm4IBJAAIAACvIAEgGIAQgRIAYgSIAWgKIAhgHIAQAAIAVACIAUAGIAUAJIASALIALAJIAPAQIAQAaIAHAOIALAqIABAqIgFAjIgHAXIgLAXIgMASIgKAMIgQAOIgSAMIgUAJIgNADIgVAEIgYABgADCnbIgNAEIgIAEIgTALIgMAOIgIALIgGAOIgHAYIAAAkIAHAZIAGANIAIAMIAJAKIAWAPIAMAFIASAEIATAAIAWgGIAQgIIAKgHIAHgGIADgEIADgDIAMgUIAIgeIAAgkIgCgKIgGgTIgMgUIgDgEIgDgDIgHgHIgKgHIgQgIIgNgEIgTgCgAR6jWIgRgEIgLgFIgKgGIgGgGIgDgCIgJgPIgGgSIgDgQIgBi4IgqAAIAAhAIAqAAIAAhXIBIAAIAABXIBUAAIAABAIhUAAIAACgIADANIADAHIAEAFIAGAEIADACIAEAAIADACIAJABIARgBIALgCIAQgFIAFgDIAAA9IgOAGIghAHgAMwjZIAAk9IBIAAIAABIIAIgRIAPgXIAQgQIAKgHIAUgJIASgFIAOgBIAKAAIAABOIgfADIgFABIgPAGIgOAHIgIAGIgLAMIgJANIgIAQIgHAYIgDAdIAACAgAkJjZIgqhkIjIAAIgqBkIhOAAIC7mnIBFAAIC4GngAnfmBICQAAIhIimgAh2jaIAAm3IBJAAIAAG3g");
	this.shape.setTransform(307.475,105.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(284).to({_off:true},1).wait(225));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,615,211.6);


// stage content:
(lib._728x90_aaoo_boy = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// logo
	this.instance = new lib.logo("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(633.45,44.65,0.2418,0.2418,0,0,0,308.2,106);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(285));

	// Layer_8
	this.instance_1 = new lib.Symbol5();
	this.instance_1.parent = this;
	this.instance_1.setTransform(84.5,195.2,1,1,0,0,0,64.5,45.3);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(207).to({_off:false},0).to({y:165.2,alpha:1},32,cjs.Ease.quartInOut).wait(46));

	// frame
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#51C4ED").ss(8,1,1).p("Eg43gHBMBxvAAAIAAODMhxvAAAg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(285));

	// Layer_7
	this.instance_2 = new lib.Symbol4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(108.95,201.75,1,1,0,0,0,88.5,39.9);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(129).to({_off:false},0).to({y:191.75,alpha:1},30,cjs.Ease.cubicOut).wait(38).to({y:171.75,alpha:0},23,cjs.Ease.quartInOut).wait(65));

	// Layer_6
	this.instance_3 = new lib.Symbol3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150,125,1,1,0,0,0,150,125);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(111).to({_off:false},0).to({alpha:1},26,cjs.Ease.cubicIn).wait(148));

	// Layer_5
	this.instance_4 = new lib.Symbol2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(149.95,180.25,1,1,0,0,0,96.2,26.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(9).to({_off:false},0).to({y:170.25,alpha:1},41,cjs.Ease.quartInOut).wait(51).to({alpha:0},18).wait(166));

	// Layer_1
	this.instance_5 = new lib.Symbol1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(150,121.55,1,1,0,0,0,66.8,40.6);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({y:111.55,alpha:1},41,cjs.Ease.quartInOut).wait(60).to({alpha:0},18).wait(166));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#51C4ED").s().p("Eg5BAHHIAAuNMByDAAAIAAONg");
	this.shape_1.setTransform(365,45.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(285));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(348.5,39.9,383.5,86.1);
// library properties:
lib.properties = {
	id: 'EA7F868821484FEEB1ACA9412835E0FD',
	width: 728,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/728x90_aaoo_boy_atlas_.png", id:"728x90_aaoo_boy_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['EA7F868821484FEEB1ACA9412835E0FD'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;