(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"970x250_change_atlas_", frames: [[0,0,970,250],[0,252,155,61],[157,252,142,10]]}
];


// symbols:



(lib._970x250_bg = function() {
	this.spriteSheet = ss["970x250_change_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.LogoWhite = function() {
	this.spriteSheet = ss["970x250_change_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.SHAREDFUTURE = function() {
	this.spriteSheet = ss["970x250_change_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib._970x250_bg();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(0,0,970,250), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAKQgFgEAAgGQAAgFAFgEQAEgFAFAAQAGAAAFAFQAEAEAAAFQAAAGgFAFQgEAEgGAAQgFAAgEgFg");
	this.shape.setTransform(297,66.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAwQgEAEgCAIIgFAAIAAglIAFAAQAJAfAXAAQALABAFgHQAFgGAAgHQAAgJgGgGQgFgGgPgHQgRgIgIgIQgHgHAAgMQAAgLAIgLQAIgJAOgBQAOABAJAMQACgDAEgIIAFAAIAAAjIgFAAQgDgMgIgJQgIgKgKABQgIAAgFAEQgFAGAAAHQAAAHAGAFQAFAFAPAIQAXAKAFAJQAFAKAAAJQAAAPgJAKQgKAIgPABQgOAAgMgNg");
	this.shape_1.setTransform(289,61.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgVA2QgNgIgIgNQgIgNAAgTQAAgZAQgSQAPgSAXAAQAWAAAMAOQAMANABAQIhNAAIgBAMQAAAcAJAPQAJAPASAAQAZAAAKgWIAHAAQgFAOgNAIQgNAHgPABQgNgBgNgGgAgagXIA1AAIAAgFQAAgMgHgHQgHgGgKAAQgYAAgFAeg");
	this.shape_2.setTransform(278.1,61.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAeBMQgKAKgLAFQgKAFgLAAQgWAAgQgRQgQgSAAgZQAAgbAQgQQAQgRAXAAQALAAAJAEQAKAEAJAJIAAgsIAAgXQgBgEgDgDQgDgCgJAAIgDAAIAAgGQARgBATgFIADAAIAACVIABAYQAAAEAEACQAEACAKAAIAAAHQgUAAgQADQgBgGAAgOgAghgDQgKALAAAbQAAAbALANQAKANAQAAQAJAAAJgFQAJgFAHgKIAAhEQgJgHgJgEQgJgEgIAAQgPAAgLAMg");
	this.shape_3.setTransform(265.1,58);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgdBeIAAgHIAFAAQAJAAADgCQADgDABgEIAAgWIAAgjQAAgTgCgEQgCgEgCgBIgLgBIgEAAIAAgGQAYgDAMgFIAEAAIAABOIAAAWQABAFADACQADACAKAAIACAAIAAAHgAgLhFQgEgEAAgFQAAgHAEgDQAFgFAFAAQAFAAAFAFQADADAAAHQAAAFgDAEQgFAFgFAAQgFAAgFgFg");
	this.shape_4.setTransform(253.9,57.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAwQgEAEgCAIIgFAAIAAglIAFAAQAJAfAXAAQALABAFgHQAFgGAAgHQAAgJgGgGQgFgGgPgHQgRgIgIgIQgHgHAAgMQAAgLAIgLQAIgJAOgBQAOABAJAMQACgDAEgIIAFAAIAAAjIgFAAQgDgMgIgJQgIgKgKABQgIAAgFAEQgFAGAAAHQAAAHAGAFQAFAFAPAIQAXAKAFAJQAFAKAAAJQAAAPgJAKQgKAIgPABQgOAAgMgNg");
	this.shape_5.setTransform(245.9,61.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAKBeIAAgHIADAAQAKAAADgCQADgDAAgEIABgWIAAgiQAAgOgCgGQgCgHgGgEQgFgEgKAAQgJAAgJAGQgIAHgHALIAAAtIABAXQABAEADACQAEACAJAAIAAAHIg5AAIAAgHIADAAQAKAAADgCQADgDAAgEIABgWIAAhvQgBgRgDgFQgDgEgMAAIAAgGQAVAAAOgGIADAAIAABeQAJgLAKgFQAJgHAMAAQAOAAAJAHQAJAFACAIQADAIAAASIAAAgIABAYQABAEADACQAEABAKAAIAAAHg");
	this.shape_6.setTransform(226.8,57.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgJBGQgHgGgCgIQgCgHAAgUIAAg+IgQAAIAAgHQAMAAAJgJQAIgJADgRIAEAAIAAAjIAhAAIAAAHIghAAIAABCQAAAQABAFQABAGAEADQAFADAEAAQAKAAAIgLIAEADQgEAJgIAEQgIAFgJAAQgJAAgIgGg");
	this.shape_7.setTransform(215.6,60.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgpAsQgSgRAAgbQABgZAQgRQASgSAYAAQAZAAASASQAQARAAAZQAAAcgRARQgRAQgZAAQgXAAgSgRgAgagpQgKANAAAcQAAAeAKANQAKALAQAAQASAAAKgLQAJgNAAgeQAAgcgJgNQgKgMgSAAQgRAAgJAMg");
	this.shape_8.setTransform(204.2,61.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgMBbQgJgFgGgKQgJAJgGALIgFAAIAAiVIgBgVQgBgFgDgCQgEgCgJAAIAAgGIATgCQAMgCAEgCIADAAIAABYQAJgIAKgEQAJgFAKAAQAYAAAQARQAPAQAAAaQAAAagQASQgQARgZAAQgLAAgKgFgAgKgMQgJAEgIAIIAAAsQAAARACAIQACAHAJAHQAIAHALAAQARAAALgPQAKgOAAgbQAAgZgJgMQgKgNgRAAQgIAAgJAEg");
	this.shape_9.setTransform(189.6,58);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgVA2QgNgIgIgNQgIgNAAgTQAAgZAQgSQAPgSAXAAQAWAAAMAOQAMANABAQIhNAAIgBAMQAAAcAJAPQAJAPASAAQAZAAAKgWIAHAAQgFAOgNAIQgNAHgPABQgNgBgNgGgAgagXIA1AAIAAgFQAAgMgHgHQgHgGgKAAQgYAAgFAeg");
	this.shape_10.setTransform(169.5,61.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVA2QgNgIgIgNQgIgNAAgTQAAgZAQgSQAPgSAXAAQAWAAAMAOQAMANABAQIhNAAIgBAMQAAAcAJAPQAJAPASAAQAZAAAKgWIAHAAQgFAOgNAIQgNAHgPABQgNgBgNgGgAgagXIA1AAIAAgFQAAgMgHgHQgHgGgKAAQgYAAgFAeg");
	this.shape_11.setTransform(157.2,61.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgYAwQgEAEgCAIIgFAAIAAglIAFAAQAJAfAXAAQALABAFgHQAFgGAAgHQAAgJgGgGQgFgGgPgHQgRgIgIgIQgHgHAAgMQAAgLAIgLQAIgJAOgBQAOABAJAMQACgDAEgIIAFAAIAAAjIgFAAQgDgMgIgJQgIgKgKABQgIAAgFAEQgFAGAAAHQAAAHAGAFQAFAFAPAIQAXAKAFAJQAFAKAAAJQAAAPgJAKQgKAIgPABQgOAAgMgNg");
	this.shape_12.setTransform(146.6,61.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgdBeIAAgHIAEAAQAIAAAEgCQADgCAAgEIABgXIAAhuQAAgSgDgFQgDgEgMAAIAAgGIAUgCQAJgCAFgCIADAAIAACVIABAWQAAAFADACQAEACAIAAIAEAAIAAAHg");
	this.shape_13.setTransform(131.4,57.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgdBeIAAgHIADAAQAJAAADgCQAEgCABgEIAAgXIAAhuQAAgSgDgFQgDgEgMAAIAAgGIATgCQALgCAEgCIADAAIAACVIAAAWQABAFAEACQACACAJAAIAEAAIAAAHg");
	this.shape_14.setTransform(124.7,57.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAVA3QgFgFgCgKQgOAKgKAFQgLAFgJAAQgMAAgIgHQgIgHAAgKQAAgOAOgLQAOgKAYgJIAUgJIAAgGQAAgLgCgFQgBgGgGgEQgGgEgKAAQgUAAgDAOQgCAOgJAAQgJAAAAgIQAAgIAMgJQALgJAXAAQAQAAAKAGQAJAFAEAHQADAHAAAPIAAAsQAAAQABAEQACAFAFAAQAJAAADgOIAFAAQgCAYgVAAQgKAAgFgFgAAAgFQgjAOAAAWQAAAIAEAFQAFAGAHAAQAGAAAJgFQAHgEALgIIAAgsg");
	this.shape_15.setTransform(115.3,61.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgVA2QgNgIgIgNQgIgNAAgTQAAgZAQgSQAPgSAXAAQAWAAAMAOQAMANABAQIhNAAIgBAMQAAAcAJAPQAJAPASAAQAZAAAKgWIAHAAQgFAOgNAIQgNAHgPABQgNgBgNgGgAgagXIA1AAIAAgFQAAgMgHgHQgHgGgKAAQgYAAgFAeg");
	this.shape_16.setTransform(95.2,61.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAhA6IghhYIghBYIgGAAIgihYQgGgPgDgDQgDgDgJAAIAAgGIAzAAIAAAGQgIAAgDACQgEABAAAEQAAADAGANIAXA7IAhhYIAFAAIAjBYIAYg/IAEgMQAAgGgOgBIAAgGIAkAAIAAAGQgGAAgEADQgDACgDAIIgEAIIgjBYg");
	this.shape_17.setTransform(79.6,61.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAKA6IAAgGIADAAQAKAAADgDQADgDAAgEIAAgWIAAgjIgBgTQgBgGgGgEQgFgFgJAAQgJAAgJAGQgJAGgIAMIAAAtIAAAXQABAFAEACQADACAKAAIAAAGIg4AAIAAgGQAJAAAEgCQADgCABgEIABgYIAAghIgBgXQAAgEgEgCQgEgDgJAAIAAgGQAPgCAPgEIAEAAQADAIABAPQAJgMALgFQAKgGAMAAQANAAAJAFQAIAGADAIQACAIAAAQIAAAiIABAXQABAFADACQAEACAJAAIAAAGg");
	this.shape_18.setTransform(55.8,61.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgVA2QgNgIgIgNQgIgNAAgTQAAgZAQgSQAPgSAXAAQAWAAAMAOQAMANABAQIhNAAIgBAMQAAAcAJAPQAJAPASAAQAZAAAKgWIAHAAQgFAOgNAIQgNAHgPABQgNgBgNgGgAgagXIA1AAIAAgFQAAgMgHgHQgHgGgKAAQgYAAgFAeg");
	this.shape_19.setTransform(42.1,61.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAKBeIAAgHIADAAQAKAAADgCQADgDABgEIAAgWIAAgiQAAgOgCgGQgBgHgGgEQgHgEgJAAQgJAAgJAGQgIAHgHALIAAAtIABAXQABAEADACQADACAKAAIAAAHIg5AAIAAgHIADAAQAKAAADgCQACgDABgEIABgWIAAhvQAAgRgDgFQgEgEgMAAIAAgGQAVAAAPgGIACAAIAABeQAIgLAKgFQAKgHAMAAQANAAAKAHQAJAFACAIQAEAIAAASIAAAgIAAAYQABAEADACQAFABAJAAIAAAHg");
	this.shape_20.setTransform(28.6,57.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAhA6IghhYIghBYIgGAAIgjhYQgFgPgDgDQgDgDgJAAIAAgGIA0AAIAAAGQgJAAgDACQgDABgBAEQABADAFANIAWA7IAihYIAGAAIAhBYIAZg/IAEgMQAAgGgOgBIAAgGIAkAAIAAAGQgGAAgEADQgEACgDAIIgCAIIgjBYg");
	this.shape_21.setTransform(11.7,61.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAeBMQgKAKgLAFQgKAFgLAAQgWAAgQgRQgQgSAAgZQAAgbAQgQQAQgRAXAAQALAAAJAEQAKAEAJAJIAAgsIAAgXQgBgEgDgDQgDgCgJAAIgDAAIAAgGQARgBATgFIADAAIAACVIABAYQAAAEAEACQAEACAKAAIAAAHQgUAAgQADQgBgGAAgOgAghgDQgKALAAAbQAAAbALANQAKANAQAAQAJAAAJgFQAJgFAHgKIAAhEQgJgHgJgEQgJgEgIAAQgPAAgLAMg");
	this.shape_22.setTransform(293.8,19);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgtA6IAAgGIADAAQAHAAAEgCQAEgDABgEIAAgXIAAgfIAAgWQgBgFgEgCQgDgDgIAAIgDAAIAAgGQAMgCAVgGQAEALABARQAEgMAKgIQAKgIAKAAQAJAAAFAFQAGAGAAAGQgBAEgCADQgDADgDAAQgIAAgDgLQgDgGgEAAQgGAAgJAIQgGAIgDAIQgDAJABAOIAAAUIAAAWQABAFADADQACACAKAAIADAAIAAAGg");
	this.shape_23.setTransform(281.5,22.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAVA3QgFgFgCgKQgOAKgKAFQgLAFgJAAQgMAAgIgHQgIgHAAgKQAAgOAOgLQAOgKAYgJIAUgJIAAgGQAAgLgCgFQgBgGgGgEQgGgEgKAAQgUAAgDAOQgCAOgJAAQgJAAAAgIQAAgIAMgJQALgJAXAAQAQAAAKAGQAJAFAEAHQADAHAAAPIAAAsQAAAQABAEQACAFAFAAQAJAAADgOIAFAAQgCAYgVAAQgKAAgFgFgAAAgFQgjAOAAAWQAAAIAEAFQAFAGAHAAQAGAAAJgFQAHgEALgIIAAgsg");
	this.shape_24.setTransform(269.8,22.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAhA6IghhYIghBYIgGAAIgihYQgGgPgDgDQgDgDgIAAIAAgGIAyAAIAAAGQgIAAgDACQgDABAAAEQgBADAGANIAXA7IAihYIAEAAIAjBYIAYg/IAEgMQAAgGgOgBIAAgGIAlAAIAAAGQgHAAgEADQgDACgDAIIgEAIIgjBYg");
	this.shape_25.setTransform(253.4,22.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AguA6IAAgGIADAAQAJAAADgCQADgDABgEIABgXIAAgfIgBgWQAAgFgDgCQgEgDgJAAIgDAAIAAgGQAOgCAUgGQAEALAAARQAGgMAJgIQAKgIAKAAQAJAAAGAFQAEAGAAAGQAAAEgCADQgDADgEAAQgGAAgEgLQgCgGgGAAQgFAAgIAIQgIAIgCAIQgDAJAAAOIAAAUIACAWQAAAFADADQADACAIAAIAEAAIAAAGg");
	this.shape_26.setTransform(239.2,22.3);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgpAsQgRgQAAgcQgBgZASgRQARgSAYAAQAaAAAQASQARARAAAZQABAcgSAQQgSAQgYABQgXAAgSgRgAgbgpQgJANAAAcQAAAeAKANQAKALAQAAQASAAAJgLQAKgNAAgeQAAgcgKgNQgJgMgSAAQgRAAgKAMg");
	this.shape_27.setTransform(226.7,22.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgxBeIAAgGQAKAAADgCQAEgCABgEIABgZIAAhBIgVAAIAAgHIAVAAIAAgKQAAgRABgJQACgKAGgJQAGgKAKgGQAIgFAOAAQAQAAAKAGQAJAIAAAGQAAAEgCADQgDADgEAAQgHAAgGgMQgHgMgKAAQgJAAgGAGQgGAHgBAIQgCAKAAAfIAAAIIAXAAIAAAHIgXAAIAABBIABAXQAAAFAEACQADACAIABIAGAAIAAAGg");
	this.shape_28.setTransform(217.8,18.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgVA1QgNgHgIgNQgIgNAAgTQAAgZAQgSQAPgSAXAAQAWAAAMAOQAMANABAQIhNAAIgBAMQAAAcAJAPQAJAPASAAQAZAAAKgWIAHAAQgFAOgNAIQgNAHgPABQgNAAgNgIgAgagXIA1AAIAAgFQAAgMgHgHQgHgGgKAAQgYgBgFAfg");
	this.shape_29.setTransform(199,22.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgDA6IgohZQgGgNgDgDQgEgEgIAAIAAgGIAzAAIAAAGIgLABQgDACAAAEQAAADAFALIAdBDIAbg7QAHgPAAgEQAAgJgOgBIAAgGIAmAAIAAAGQgHAAgFAGQgEAFgJATIgkBPg");
	this.shape_30.setTransform(186.5,22.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgpAsQgSgQAAgcQABgZAQgRQASgSAYAAQAZAAASASQAQARAAAZQAAAcgRAQQgRAQgZABQgXAAgSgRgAgagpQgKANAAAcQAAAeAKANQAKALAQAAQASAAAKgLQAJgNAAgeQAAgcgJgNQgKgMgSAAQgRAAgJAMg");
	this.shape_31.setTransform(173.1,22.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAyA6IAAgGQAJAAAEgCQADgCABgEQABgEAAgUIAAgkQAAgMgCgGQgBgFgFgEQgGgFgJAAQgIAAgJAGQgJAHgJAMIAAArIAAAWQABAFADADQADACAJAAIAAAGIg1AAIAAgGQAJAAAEgCQADgCABgEIABgYIAAgeIgBgWQgBgGgGgFQgGgFgJAAQgIAAgJAGQgJAFgJALIAAAuIAAAXQABAEADADQAEACAJAAIAAAGIg3AAIAAgGQAJAAAEgCQAEgCAAgEIABgYIAAghIAAgXQgBgEgEgDQgDgCgKAAIAAgGQAUgCAMgEIACAAQAEAJAAAOQAJgLALgGQAKgGAMAAQAOAAAJAGQAHAGAEANQAKgNALgGQALgGALAAQANAAAJAGQAJAGACAHQACAIAAARIAAAhQAAATABAFQABAEADACQAEACAKAAIAAAGg");
	this.shape_32.setTransform(154.9,22.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgpAsQgRgQgBgcQAAgZARgRQASgSAYAAQAZAAASASQARARAAAZQAAAcgSAQQgSAQgYABQgYAAgRgRgAgagpQgKANAAAcQAAAeAKANQAJALARAAQASAAAJgLQAKgNAAgeQAAgcgKgNQgJgMgSAAQgRAAgJAMg");
	this.shape_33.setTransform(129.7,22.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgIBGQgIgGgBgIQgDgHAAgUIAAg+IgQAAIAAgHQALAAAKgJQAIgJACgRIAFAAIAAAjIAhAAIAAAHIghAAIAABCQAAAQABAFQABAGAEADQAFADAEAAQAKAAAIgLIAEADQgEAJgIAEQgIAFgJAAQgJAAgHgGg");
	this.shape_34.setTransform(118.9,21);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgtA6IAAgGIADAAQAHAAAEgCQAEgDABgEIAAgXIAAgfIAAgWQgBgFgEgCQgDgDgIAAIgDAAIAAgGQANgCAUgGQAEALABARQAEgMAKgIQAKgIAKAAQAJAAAFAFQAGAGAAAGQgBAEgCADQgDADgDAAQgIAAgDgLQgDgGgEAAQgGAAgJAIQgGAIgDAIQgDAJABAOIAAAUIABAWQAAAFADADQACACAKAAIADAAIAAAGg");
	this.shape_35.setTransform(102.8,22.3);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgVA1QgNgHgIgNQgIgNAAgTQAAgZAQgSQAPgSAXAAQAWAAAMAOQAMANABAQIhNAAIgBAMQAAAcAJAPQAJAPASAAQAZAAAKgWIAHAAQgFAOgNAIQgNAHgPABQgNAAgNgIgAgagXIA1AAIAAgFQAAgMgHgHQgHgGgKAAQgYgBgFAfg");
	this.shape_36.setTransform(91.2,22.6);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgdBeIAAgGIAEAAQAKAAADgDQADgDAAgDIABgYIAAgiQAAgTgBgDQgCgFgEgBIgLgBIgDAAIAAgGQAYgDANgFIACAAIAABNIABAXQABAFADACQADACAJABIADAAIAAAGgAgKhFQgFgEAAgFQAAgGAFgEQADgFAHAAQAEAAAEAFQAEAEAAAGQAAAFgEAEQgEAFgEAAQgHAAgDgFg");
	this.shape_37.setTransform(81.5,18.8);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgYAwQgEAEgCAIIgFAAIAAglIAFAAQAJAfAXAAQALABAFgHQAFgGAAgHQAAgJgGgGQgFgGgPgHQgRgIgIgIQgHgHAAgMQAAgMAIgKQAIgJAOgBQAOAAAJANQACgCAEgIIAFAAIAAAiIgFAAQgDgMgIgKQgIgJgKABQgIgBgFAGQgFAFAAAHQAAAHAGAFQAFAFAPAIQAXAKAFAJQAFAKAAAJQAAAPgJAKQgKAIgPABQgOAAgMgNg");
	this.shape_38.setTransform(73.5,22.6);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AAVA3QgFgFgCgKQgOAKgKAFQgLAFgJAAQgMAAgIgHQgIgHAAgKQAAgOAOgLQAOgKAYgJIAUgJIAAgGQAAgLgCgFQgBgGgGgEQgGgEgKAAQgUAAgDAOQgCAOgJAAQgJAAAAgIQAAgIAMgJQALgJAXAAQAQAAAKAGQAJAFAEAHQADAHAAAPIAAAsQAAAQABAEQACAFAFAAQAJAAADgOIAFAAQgCAYgVAAQgKAAgFgFgAAAgFQgjAOAAAWQAAAIAEAFQAFAGAHAAQAGAAAJgFQAHgEALgIIAAgsg");
	this.shape_39.setTransform(62.6,22.5);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgVA1QgNgHgIgNQgIgNAAgTQAAgZAQgSQAPgSAXAAQAWAAAMAOQAMANABAQIhNAAIgBAMQAAAcAJAPQAJAPASAAQAZAAAKgWIAHAAQgFAOgNAIQgNAHgPABQgNAAgNgIgAgagXIA1AAIAAgFQAAgMgHgHQgHgGgKAAQgYgBgFAfg");
	this.shape_40.setTransform(49.5,22.6);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgYAwQgEAEgCAIIgFAAIAAglIAFAAQAJAfAXAAQALABAFgHQAFgGAAgHQAAgJgGgGQgFgGgPgHQgRgIgIgIQgHgHAAgMQAAgMAIgKQAIgJAOgBQAOAAAJANQACgCAEgIIAFAAIAAAiIgFAAQgDgMgIgKQgIgJgKABQgIgBgFAGQgFAFAAAHQAAAHAGAFQAFAFAPAIQAXAKAFAJQAFAKAAAJQAAAPgJAKQgKAIgPABQgOAAgMgNg");
	this.shape_41.setTransform(31.9,22.6);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AgQAcQAagFAAgXQAAgJgFAAIgDAAIgFABQgGAAgEgDQgEgFAAgFQAAgFAEgEQAEgFAGAAQAIAAAHAIQAGAJAAAOQAAAOgJAMQgJAKgQAEg");
	this.shape_42.setTransform(23.7,13.2);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgJBGQgHgGgCgIQgBgHAAgUIAAg+IgRAAIAAgHQALAAAJgJQAJgJADgRIAEAAIAAAjIAhAAIAAAHIghAAIAABCQAAAQAAAFQACAGAFADQAEADAFAAQAKAAAHgLIAEADQgEAJgIAEQgJAFgIAAQgJAAgIgGg");
	this.shape_43.setTransform(16.4,21);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgpBdIAAgHIAFAAQAMAAAFgDQAFgDABgGQABgGAAgYIAAhZQAAgXgBgGQgBgGgFgDQgEgCgPAAIgDAAIAAgHIBUAAIAAAHIgEAAQgOAAgEACQgEACgCAGQgCAGABAYIAABZIABAdQABAHAEADQAEADANAAIAGAAIAAAHg");
	this.shape_44.setTransform(7,18.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,1,302.8,75.1), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.749)").s().p("AvVAAQGqk7IrAAQItAAGoE7QmoE8otAAQorAAmqk8g");
	this.shape.setTransform(98.2,31.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(0,0,196.3,63.2), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJAKQgEgEAAgGQAAgFAEgEQAEgEAFAAQAGAAAEAEQAEAEAAAFQAAAGgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape.setTransform(140.4,360.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgoBPQAAgJAOgGQAIgDADgDQACgCADgHIAKgaIgohWQgGgLgDgDQgEgDgJAAIAAgGIAyAAIAAAGQgNAAAAAFIAFANIAdA+IAZg7IAFgOQAAgHgOAAIAAgGIAmAAIAAAGQgJAAgEAFQgEAEgHAOIgvB0QgHAQgFAGQgFAGgGAAQgJAAAAgIg");
	this.shape_1.setTransform(130.8,359.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgIBEQgIgGgBgIQgCgHAAgTIAAg8IgQAAIAAgGQALAAAJgJQAIgJADgQIAEAAIAAAiIAfAAIAAAGIgfAAIAABAQAAAPAAAFQABAGAFADQAEADAFAAQAJAAAHgLIAFADQgFAIgHAFQgIAEgJAAQgIAAgHgFg");
	this.shape_2.setTransform(121.1,354.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgcBbIAAgGIAEAAQAKAAADgDQACgDABgDIAAgWIAAghQAAgTgBgDQgCgEgDgBIgKgCIgEAAIAAgGQAXgCAMgFIADAAIAABLIABAVQAAAFAEACQADADAIAAIADAAIAAAGgAgKhCQgEgEAAgGQAAgFAEgEQAEgFAGAAQAEAAAEAFQAEAEAAAFQAAAGgEAEQgEAEgEAAQgGAAgEgEg");
	this.shape_3.setTransform(113.4,352.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgcBbIAAgGIAEAAQAIAAADgCQADgDABgEIABgWIAAhqQAAgRgDgEQgDgFgMAAIAAgGIATgCQAKgCAEgCIADAAIAACQIAAAVQABAFADACQADADAJAAIADAAIAAAGg");
	this.shape_4.setTransform(106.8,352.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgcBbIAAgGIAEAAQAKAAADgDQACgDABgDIAAgWIAAghQAAgTgBgDQgCgEgDgBIgKgCIgEAAIAAgGQAXgCAMgFIADAAIAABLIABAVQAAAFAEACQADADAIAAIADAAIAAAGgAgKhCQgEgEAAgGQAAgFAEgEQAEgFAGAAQAEAAAEAFQAEAEAAAFQAAAGgEAEQgEAEgEAAQgGAAgEgEg");
	this.shape_5.setTransform(100.2,352.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgLBYQgJgFgGgKQgJAJgFALIgFAAIAAiPIgBgVQgBgFgEgCQgDgCgJAAIAAgGIATgCQALgCAEgCIADAAIAABVQAJgIAJgEQAJgEAKAAQAXAAAPAQQAPAQAAAZQAAAZgQARQgPARgYAAQgLAAgJgFgAgJgLQgJAEgIAHIAAArQAAAQACAIQACAGAIAHQAJAGAKABQARgBAKgOQAKgOAAgZQAAgZgKgLQgJgNgQAAQgIAAgIAFg");
	this.shape_6.setTransform(89.6,352.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgcBbIAAgGIAEAAQAKAAADgDQACgDABgDIAAgWIAAghQAAgTgBgDQgCgEgDgBIgKgCIgEAAIAAgGQAXgCAMgFIADAAIAABLIABAVQAAAFAEACQADADAIAAIADAAIAAAGgAgKhCQgEgEAAgGQAAgFAEgEQAEgFAGAAQAEAAAEAFQAEAEAAAFQAAAGgEAEQgEAEgEAAQgGAAgEgEg");
	this.shape_7.setTransform(79.4,352.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgXAuQgDAEgDAHIgFAAIAAgjIAFAAQAJAeAWAAQAKAAAFgFQAFgHAAgHQAAgIgFgFQgGgGgOgIQgQgGgIgIQgHgIAAgMQAAgKAIgKQAHgKAPAAQAMAAAJAMIAGgKIAEAAIAAAiIgEAAQgDgMgHgIQgIgKgJABQgIAAgFAEQgFAGAAAGQAAAHAFAFQAGAFANAHQAXAKAFAJQAFAKAAAJQAAANgJAJQgKAKgOgBQgOAAgLgMg");
	this.shape_8.setTransform(71.7,356.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAKA4IAAgGIACAAQAKAAADgDQACgCABgEIABgWIAAgiIgBgSQgCgFgGgFQgFgEgJAAQgIAAgJAGQgIAGgIALIAAArIABAXQAAAEADACQAEACAKAAIAAAGIg3AAIAAgGQAJAAAEgCQADgCABgDIABgYIAAgfIgBgXQAAgEgEgCQgDgCgKAAIAAgGQAPgCAPgEIADAAQAEAIAAAOQAJgLALgGQAJgFALAAQANAAAJAFQAHAGADAIQACAHAAAPIAAAhIABAXQABAEAEACQADACAJAAIAAAGg");
	this.shape_9.setTransform(60.1,355.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgnAqQgSgQABgaQAAgYAQgRQAQgQAYgBQAYABARAQQAQARABAYQAAAbgRAQQgRAPgYAAQgXABgQgRgAgagnQgIAMgBAcQAAAcAKAMQAJALAQAAQARAAAJgLQAKgMgBgcQABgcgKgMQgJgMgRAAQgRAAgJAMg");
	this.shape_10.setTransform(46.1,356.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhABaIAAgHIAEAAQAJAAADgDQADgCABgEIAAgVIAAhhIAAgWQgBgFgDgCQgDgCgJAAIgEAAIAAgGQANgCAUgGIAEAAQACAIAAAKQAIgJAKgEQAJgEALgBQAWABAPAQQAPAPAAAaQAAAagPAPQgPARgZAAQgKAAgIgDQgJgFgIgIIAAAqIABAWQAAAEAEACQADACAKAAIAAAHgAgKhMQgIAEgHAKIAABAQAHAKAIAEQAIAEAIAAQAPAAALgMQALgNAAgcQAAgXgLgNQgLgMgOABQgIAAgJAEg");
	this.shape_11.setTransform(31.8,359.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgXAuQgDAEgDAHIgFAAIAAgjIAFAAQAJAeAWAAQAKAAAFgFQAFgHAAgHQAAgIgFgFQgGgGgOgIQgQgGgIgIQgHgIAAgMQAAgKAIgKQAHgKAPAAQAMAAAJAMIAGgKIAEAAIAAAiIgEAAQgDgMgHgIQgIgKgJABQgIAAgFAEQgFAGAAAGQAAAHAFAFQAGAFANAHQAXAKAFAJQAFAKAAAJQAAANgJAJQgKAKgOgBQgOAAgLgMg");
	this.shape_12.setTransform(20.9,356.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgUAzQgMgGgIgNQgIgNAAgSQAAgZAPgRQAPgQAWgBQAVABAMANQALANABAPIhKAAIgBALQAAAcAJAOQAJAOAQAAQAYAAAKgVIAHAAQgFANgMAIQgMAHgPAAQgNABgMgIgAgZgWIAzAAIAAgFQAAgMgGgGQgHgGgKAAQgYAAgEAdg");
	this.shape_13.setTransform(10.4,356.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgsA4IAAgGIADAAQAIAAADgCQADgCABgEIABgXIAAgdIgBgWQAAgEgDgDQgEgCgIAAIgDAAIAAgGQAMgCAUgGQAEAKABARQAEgLAJgIQAKgIAKAAQAJAAAFAFQAFAGAAAFQAAAEgDADQgCADgEAAQgHAAgDgKQgDgHgEAAQgGAAgIAIQgHAIgCAIQgCAIAAAOIAAATIAAAWQABAEADADQACACAJAAIADAAIAAAGg");
	this.shape_14.setTransform(0,355.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgUAzQgMgGgIgNQgIgNAAgSQAAgZAPgQQAPgRAWgBQAVABALANQAMANABAPIhLAAIAAALQAAAcAJAOQAJAOAQAAQAYAAALgVIAGAAQgEANgNAIQgNAHgOAAQgNABgMgIgAgZgWIAzAAIAAgFQAAgMgHgGQgHgGgJAAQgYAAgEAdg");
	this.shape_15.setTransform(148.3,301.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAHBbIAAgGQAOgBAAgFQAAgDgJgKIgbggIgGAEIAAAQIABAVQAAAFAEACQADADAIAAIAAAGIg3AAIAAgGIAEAAQAKAAADgDQADgDAAgDIAAgWIAAhsQAAgPgDgFQgDgEgLAAIAAgGIATgCQALgCAEgCIACAAIAAB5IAMgIQAagUAAgHQAAgGgKAAIAAgGIAsAAIAAAGQgMAAgVARIgTAQIAmAtQAJAKAFADQAFADAFABIAAAGg");
	this.shape_16.setTransform(136.5,297.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAUA1QgFgFgCgJQgNAJgKAFQgLAFgIAAQgLAAgIgHQgIgGAAgLQAAgNANgKQAOgKAXgJIATgIIAAgGQAAgLgBgFQgBgFgHgEQgFgEgJAAQgUAAgCANQgDAOgJAAQgIAAAAgIQAAgHALgJQALgJAWAAQAQAAAJAGQAJAFAEAHQACAGAAAOIAAArQAAAPACAFQACAEAFAAQAJAAACgNIAFAAQgCAXgVAAQgJAAgFgFgAAAgEQgiAMAAAVQAAAJAEAFQAFAFAHAAQAGAAAIgEQAHgEAKgIIAAgqg");
	this.shape_17.setTransform(124.1,301.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgIBEQgIgGgBgIQgCgHAAgTIAAg8IgQAAIAAgGQALAAAJgJQAIgJADgQIAEAAIAAAiIAfAAIAAAGIgfAAIAABAQAAAPAAAFQABAGAFADQAEADAFAAQAJAAAHgLIAFADQgFAIgHAFQgIAEgJAAQgIAAgHgFg");
	this.shape_18.setTransform(113.8,299.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgcBbIAAgGIAEAAQAIAAADgCQADgDABgEIABgWIAAhqQAAgRgDgEQgDgFgMAAIAAgGIATgCQAKgCAEgCIADAAIAACQIAAAVQABAFADACQADADAJAAIADAAIAAAGg");
	this.shape_19.setTransform(99.5,297.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgcBbIAAgGIAEAAQAIAAADgCQADgDABgEIABgWIAAhqQAAgRgDgEQgDgFgMAAIAAgGIATgCQAKgCAEgCIADAAIAACQIAAAVQABAFADACQADADAJAAIADAAIAAAGg");
	this.shape_20.setTransform(93.1,297.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAUA1QgFgFgCgJQgNAJgKAFQgLAFgIAAQgLAAgIgHQgIgGAAgLQAAgNANgKQAOgKAXgJIATgIIAAgGQAAgLgBgFQgBgFgHgEQgFgEgJAAQgUAAgCANQgDAOgJAAQgIAAAAgIQAAgHALgJQALgJAWAAQAQAAAJAGQAJAFAEAHQACAGAAAOIAAArQAAAPACAFQACAEAFAAQAJAAACgNIAFAAQgCAXgVAAQgJAAgFgFgAAAgEQgiAMAAAVQAAAJAEAFQAFAFAHAAQAGAAAIgEQAHgEAKgIIAAgqg");
	this.shape_21.setTransform(84,301.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgUAzQgMgGgIgNQgIgNAAgSQAAgZAPgQQAPgRAWgBQAVABALANQAMANABAPIhLAAIAAALQAAAcAJAOQAJAOAQAAQAYAAAKgVIAHAAQgEANgNAIQgNAHgOAAQgNABgMgIgAgZgWIAzAAIAAgFQAAgMgHgGQgHgGgJAAQgYAAgEAdg");
	this.shape_22.setTransform(64.6,301.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAgA4IgghUIggBUIgGAAIgghUQgHgPgCgDQgDgDgIAAIAAgGIAxAAIAAAGQgIAAgDABQgDACAAAEQAAACAFANIAWA5IAghVIAGAAIAgBVIAYg8IADgMQAAgHgNAAIAAgGIAjAAIAAAGQgGAAgDADQgFACgCAIIgDAIIgiBUg");
	this.shape_23.setTransform(49.6,301.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgcBbIAAgGIAEAAQAIAAADgCQADgDABgEIABgWIAAhqQAAgRgDgEQgDgFgMAAIAAgGIATgCQAKgCAEgCIADAAIAACQIAAAVQABAFADACQADADAJAAIADAAIAAAGg");
	this.shape_24.setTransform(30.4,297.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgcBbIAAgGIAEAAQAKAAADgDQACgDABgDIAAgWIAAghQAAgTgBgDQgCgEgDgBIgKgCIgEAAIAAgGQAXgCAMgFIADAAIAABLIABAVQAAAFAEACQADADAIAAIADAAIAAAGgAgKhCQgEgEAAgGQAAgFAEgEQAEgFAGAAQAEAAAEAFQAEAEAAAFQAAAGgEAEQgEAEgEAAQgGAAgEgEg");
	this.shape_25.setTransform(23.8,297.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgIBEQgIgGgBgIQgCgHAAgTIAAg8IgQAAIAAgGQALAAAJgJQAIgJADgQIAEAAIAAAiIAfAAIAAAGIgfAAIAABAQAAAPAAAFQABAGAFADQAEADAFAAQAJAAAHgLIAFADQgFAIgHAFQgIAEgJAAQgIAAgHgFg");
	this.shape_26.setTransform(16.9,299.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAKA4IAAgGIACAAQAKAAADgDQACgCABgEIABgWIAAgiIgBgSQgCgFgFgFQgGgEgJAAQgIAAgJAGQgIAGgIALIAAArIABAXQAAAEADACQAEACAKAAIAAAGIg3AAIAAgGQAJAAAEgCQADgCABgDIABgYIAAgfIgBgXQAAgEgEgCQgDgCgKAAIAAgGQAPgCAPgEIADAAQAEAIAAAOQAJgLALgGQAJgFALAAQANAAAJAFQAHAGADAIQACAHAAAPIAAAhIABAXQABAEAEACQADACAJAAIAAAGg");
	this.shape_27.setTransform(5.6,300.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgfAzQgIgFgDgHQgEgHABgOIAAgkIgBgXQgBgEgDgCQgEgCgJAAIAAgGIAlAAIAABKQgBALACAFQABAFAGAEQAFADAHAAQAKAAAIgGQAKgHADgHQADgIAAgOIAAgXIAAgWQgBgDgCgDQgDgDgKAAIgCAAIAAgGIAlAAIAABGIABAWQABAEADACQADADAJAAIAAAGQgUAAgJAEIgCAAQgEgHgBgSQgIAMgKAHQgKAGgMAAQgLAAgIgFg");
	this.shape_28.setTransform(-8.7,301.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAKA4IAAgGIACAAQAKAAADgDQACgCABgEIABgWIAAgiIgBgSQgCgFgFgFQgGgEgJAAQgIAAgJAGQgIAGgJALIAAArIACAXQAAAEADACQAEACAJAAIAAAGIg2AAIAAgGQAJAAAEgCQADgCABgDIABgYIAAgfIgBgXQAAgEgEgCQgDgCgKAAIAAgGQAPgCAPgEIADAAQADAIAAAOQAKgLALgGQAJgFALAAQANAAAIAFQAJAGACAIQACAHABAPIAAAhIAAAXQABAEADACQAEACAJAAIAAAGg");
	this.shape_29.setTransform(136.5,246);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgUAzQgMgGgIgNQgIgNAAgSQAAgZAPgRQAPgQAWgBQAVABAMANQALANABAPIhKAAIgBALQAAAcAJAOQAJAOAQAAQAYAAAKgVIAHAAQgFANgMAIQgMAHgPAAQgNABgMgIgAgZgWIAzAAIAAgFQAAgMgGgGQgHgGgKAAQgYAAgEAdg");
	this.shape_30.setTransform(123.3,246.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AhABZIAAgGIAEAAQAJAAADgDQADgCABgEIAAgVIAAhhIAAgWQgBgFgDgCQgDgCgJAAIgEAAIAAgGQANgCAUgGIAEAAQACAIAAAKQAIgJAKgEQAJgEALgBQAWABAPAQQAPAPAAAaQAAAagPAPQgPARgZAAQgKAAgIgDQgJgFgIgIIAAAqIABAWQAAAEAEACQADACAKAAIAAAGgAgKhMQgIAEgHAKIAABAQAHAKAIAEQAIAEAIAAQAPAAALgMQALgNAAgcQAAgXgLgNQgLgMgOAAQgIABgJAEg");
	this.shape_31.setTransform(109.9,249.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AhABZIAAgGIAEAAQAJAAADgDQADgCABgEIAAgVIAAhhIAAgWQgBgFgDgCQgDgCgJAAIgEAAIAAgGQANgCAUgGIAEAAQACAIAAAKQAIgJAKgEQAJgEALgBQAWABAPAQQAPAPAAAaQAAAagPAPQgPARgZAAQgKAAgIgDQgJgFgIgIIAAAqIABAWQAAAEAEACQADACAKAAIAAAGgAgKhMQgIAEgHAKIAABAQAHAKAIAEQAIAEAIAAQAPAAALgMQALgNAAgcQAAgXgLgNQgLgMgOAAQgIABgJAEg");
	this.shape_32.setTransform(95.8,249.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AAUA1QgFgFgCgJQgNAJgKAFQgLAFgIAAQgLAAgIgHQgIgGAAgLQAAgNANgKQAOgKAXgJIATgIIAAgGQAAgLgBgFQgBgFgHgEQgFgEgJAAQgUAAgCANQgDAOgJAAQgIAAAAgIQAAgHALgJQALgJAWAAQAQAAAJAGQAJAFAEAHQACAGAAAOIAAArQAAAPACAFQACAEAFAAQAJAAACgNIAFAAQgCAXgVAAQgJAAgFgFgAAAgEQgiAMAAAVQAAAJAEAFQAFAFAHAAQAGAAAIgEQAHgEAKgIIAAgqg");
	this.shape_33.setTransform(83.4,246.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAKBbIAAgGIADAAQAJAAADgDQADgDAAgEIAAgVIAAghQAAgNgBgHQgBgFgHgEQgFgFgJAAQgJAAgIAHQgJAFgGALIAAAsIAAAWQABAEAEADQADACAJAAIAAAGIg2AAIAAgGIACAAQAJAAAEgDQADgDAAgDIAAgWIAAhrQAAgQgDgFQgDgEgMAAIAAgGQAVAAAOgGIACAAIAABbQAIgKAKgGQAJgGAMAAQAMAAAKAGQAIAGADAIQADAHAAASIAAAeIAAAXQABAEADACQAEACAKAAIAAAGg");
	this.shape_34.setTransform(69.6,242.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgIBEQgIgGgBgIQgCgHAAgTIAAg8IgQAAIAAgGQALAAAJgJQAIgJADgQIAEAAIAAAiIAfAAIAAAGIgfAAIAABAQAAAPAAAFQABAGAFADQAEADAFAAQAJAAAHgLIAFADQgFAIgHAFQgIAEgJAAQgIAAgHgFg");
	this.shape_35.setTransform(52,244.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgQAcQAZgFABgXQAAgIgGAAIgCAAIgEABQgHAAgEgEQgDgEgBgFQAAgFAEgEQAEgFAHAAQAHAAAGAIQAGAIABAOQAAAOgJALQgJAKgQAEg");
	this.shape_36.setTransform(44.5,237.2);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAKA4IAAgGIACAAQAKAAADgDQACgCABgEIABgWIAAgiIgBgSQgCgFgGgFQgFgEgJAAQgIAAgJAGQgIAGgIALIAAArIABAXQAAAEADACQAEACAKAAIAAAGIg3AAIAAgGQAJAAAEgCQADgCABgDIABgYIAAgfIgBgXQAAgEgEgCQgDgCgKAAIAAgGQAPgCAPgEIADAAQAEAIAAAOQAJgLALgGQAJgFALAAQANAAAJAFQAHAGADAIQACAHABAPIAAAhIAAAXQABAEAEACQADACAJAAIAAAGg");
	this.shape_37.setTransform(34,246);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgnAqQgSgQABgaQAAgYAQgRQAQgQAYgBQAYABARAQQAQARABAYQAAAbgRAQQgRAPgYAAQgXABgQgRgAgagnQgIAMgBAcQAAAcAKAMQAJAMAQgBQARABAJgMQAKgMgBgcQABgcgKgMQgJgMgRAAQgRAAgJAMg");
	this.shape_38.setTransform(20,246.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AAgA4IgghUIggBUIgFAAIgihUQgFgPgDgDQgDgDgIAAIAAgGIAxAAIAAAGQgIAAgDABQgDACAAAEQAAACAFANIAWA5IAhhVIAEAAIAhBVIAXg8IAFgMQAAgHgOAAIAAgGIAjAAIAAAGQgGAAgEADQgDACgEAIIgCAIIgiBUg");
	this.shape_39.setTransform(4.1,246.5);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgUAzQgMgGgIgNQgIgNAAgSQAAgZAPgRQAPgQAWgBQAVABALANQAMANABAPIhLAAIAAALQAAAcAJAOQAJAOAQAAQAYAAAKgVIAHAAQgEANgNAIQgNAHgOAAQgNABgMgIgAgZgWIAzAAIAAgFQAAgMgHgGQgHgGgJAAQgYAAgEAdg");
	this.shape_40.setTransform(102,191.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgsBQQgPgJAAgPQAAgIAEgFQAEgFAIgBIADABQgHAKgBAJQAAAMAMAIQAKAHAWAAQASAAALgHQALgJAAgMQAAgNgKgFQgKgFgXgBQgcgCgJgFQgIgGAAgJQAAgQAXgEQgMgIgGgJQgHgKABgMQAAgQAMgMQAOgLARgBQAVABANAOQAMgNALAAQAGAAAEAEQADADAAAEQAAAJgHgBQgFABgDgGQgDgFgDAAQgFAAgGAHQAHALAAAMQAAAPgMANQgLAMgaABQgcABAAAJQAAAFAHACQAGACAUACQAUABAMACQAMAEAHAIQAHAKAAAMQAAARgOALQgOAKgbAAQgYAAgOgJgAgbhJQgHAJAAATQAAARAHAHQAHAIALAAQAJAAAIgHQAGgIAAgUQABgTgIgIQgHgHgJAAQgMAAgGAJg");
	this.shape_41.setTransform(90.2,194.5);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AAKA4IAAgGIACAAQAKAAADgDQACgCABgEIAAgWIAAgiIAAgSQgCgFgGgFQgFgEgIAAQgJAAgIAGQgKAGgHALIAAArIABAXQAAAEADACQAEACAKAAIAAAGIg3AAIAAgGQAJAAADgCQAEgCABgDIABgYIAAgfIAAgXQgCgEgDgCQgEgCgJAAIAAgGQAPgCAPgEIADAAQAEAIAAAOQAJgLALgGQAJgFALAAQANAAAJAFQAHAGADAIQADAHgBAPIAAAhIABAXQABAEAEACQADACAJAAIAAAGg");
	this.shape_42.setTransform(76.4,191.1);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AAUA1QgFgFgCgJQgNAJgKAFQgLAFgIAAQgLAAgIgHQgIgGAAgLQAAgNANgKQAOgKAXgJIATgIIAAgGQAAgLgBgFQgBgFgHgEQgFgEgJAAQgUAAgCANQgDAOgJAAQgIAAAAgIQAAgHALgJQALgJAWAAQAQAAAJAGQAJAFAEAHQACAGAAAOIAAArQAAAPACAFQACAEAFAAQAJAAACgNIAFAAQgCAXgVAAQgJAAgFgFgAAAgEQgiAMAAAVQAAAJAEAFQAFAFAHAAQAGAAAIgEQAHgEAKgIIAAgqg");
	this.shape_43.setTransform(63.2,191.3);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AAKBbIAAgGIACAAQAKAAADgDQACgDABgEIABgVIAAghQgBgNgBgHQgCgFgGgEQgFgFgJAAQgJAAgJAHQgIAFgGALIAAAsIABAWQAAAEADADQAEACAJAAIAAAGIg2AAIAAgGIACAAQAKAAACgDQADgDABgDIAAgWIAAhrQAAgQgDgFQgDgEgLAAIAAgGQATAAAOgGIADAAIAABbQAIgKAKgGQAJgGALAAQANAAAKAGQAIAGADAIQADAHgBASIAAAeIABAXQABAEAEACQADACAJAAIAAAGg");
	this.shape_44.setTransform(49.4,187.7);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AghAqQgQgPAAgaQAAgZARgRQARgRAXAAQAOABALAGQAMAGAAAJQAAADgCADQgCADgEAAQgJAAgCgLQgCgHgDgDQgDgDgKAAQgRAAgJAMQgJAMAAAZQAAAZAKAOQAJAOATAAQAaAAAHgXIAGAAQgJAegkAAQgWABgQgRg");
	this.shape_45.setTransform(36.6,191.4);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgUAzQgMgGgIgNQgIgNAAgSQAAgZAPgQQAPgRAWgBQAVABALANQAMANABAPIhLAAIAAALQAAAcAJAOQAJAOAQAAQAYAAALgVIAGAAQgEANgNAIQgNAHgOAAQgNABgMgIgAgZgWIAzAAIAAgFQAAgMgHgGQgGgGgLAAQgWAAgFAdg");
	this.shape_46.setTransform(116.7,136.5);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgIBEQgIgGgBgIQgCgHAAgTIAAg8IgQAAIAAgGQALAAAJgJQAIgJADgQIAEAAIAAAiIAfAAIAAAGIgfAAIAABAQAAAPAAAFQABAGAFADQAEADAFAAQAJAAAHgLIAFADQgFAIgHAFQgIAEgJAAQgIAAgHgFg");
	this.shape_47.setTransform(107.2,135);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AAUA1QgFgFgCgJQgNAJgKAFQgLAFgIAAQgLAAgIgHQgIgGAAgLQAAgNANgKQAOgKAXgJIATgIIAAgGQAAgLgBgFQgBgFgHgEQgFgEgJAAQgUAAgCANQgDAOgJAAQgIAAAAgIQAAgHALgJQALgJAWAAQAQAAAJAGQAJAFAEAHQACAGAAAOIAAArQAAAPACAFQACAEAFAAQAJAAACgNIAFAAQgCAXgVAAQgJAAgFgFgAAAgEQgiAMAAAVQAAAJAEAFQAFAFAHAAQAGAAAIgEQAHgEAKgIIAAgqg");
	this.shape_48.setTransform(97,136.4);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AAwA4IAAgGQAIAAAEgCQAEgCAAgDQABgEAAgUIAAgjIgBgQQgBgGgGgEQgFgEgJAAQgIAAgJAGQgIAGgJAMIAAApIAAAWQABAEADADQAEACAHAAIAAAGIgzAAIAAgGQAKAAADgCQADgCABgDIABgYIAAgdIgBgUQgBgHgGgEQgGgFgIAAQgIAAgJAFQgIAGgJAKIAAAsIAAAWQABAFAEACQADACAJAAIAAAGIg1AAIAAgGQAJAAADgCQADgCACgDIAAgYIAAgfIAAgXQgBgEgEgCQgDgCgJAAIAAgGQASgCANgEIABAAQAEAJAAAOQAJgMAKgFQAKgGAMAAQANAAAIAGQAIAGADAMQAKgMALgGQAKgGALAAQANAAAIAGQAJAGACAHQACAHAAARIAAAfIABAXQABAEADACQAEACAJAAIAAAGg");
	this.shape_49.setTransform(79.6,136.2);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgcBbIAAgGIAEAAQAKAAADgDQACgDABgDIAAgWIAAghQAAgTgBgDQgCgEgDgBIgKgCIgEAAIAAgGQAXgCAMgFIADAAIAABLIABAVQAAAFAEACQADADAIAAIADAAIAAAGgAgKhCQgEgEAAgGQAAgFAEgEQAEgFAGAAQAEAAAEAFQAEAEAAAFQAAAGgEAEQgEAEgEAAQgGAAgEgEg");
	this.shape_50.setTransform(65.2,132.8);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgcBbIAAgGIAEAAQAIAAADgCQADgDABgEIABgWIAAhqQAAgRgDgEQgDgFgMAAIAAgGIATgCQAKgCAEgCIADAAIAACQIAAAVQABAFADACQADADAJAAIADAAIAAAGg");
	this.shape_51.setTransform(58.6,132.8);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AghAqQgQgPAAgaQAAgZARgRQARgRAXAAQAOABALAGQAMAGAAAJQAAADgCADQgCADgEAAQgJAAgCgLQgCgHgDgDQgDgDgKAAQgRAAgJAMQgJAMAAAZQAAAZAKAOQAJAOATAAQAaAAAHgXIAGAAQgJAegkAAQgWABgQgRg");
	this.shape_52.setTransform(49.9,136.5);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgoAqQgRgQAAgaQABgYAQgQQARgRAXgBQAZABAQARQAQAQAAAYQABAbgSAQQgQAPgYAAQgXABgRgRgAgZgnQgKAMABAcQAAAcAJAMQAJAMAQgBQASABAJgMQAIgMABgcQgBgcgIgMQgJgMgSAAQgQAAgJAMg");
	this.shape_53.setTransform(30.5,136.5);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgIBEQgIgGgBgIQgCgHAAgTIAAg8IgQAAIAAgGQALAAAJgJQAIgJADgQIAEAAIAAAiIAfAAIAAAGIgfAAIAABAQAAAPAAAFQABAGAFADQAEADAFAAQAJAAAHgLIAFADQgFAIgHAFQgIAEgJAAQgIAAgHgFg");
	this.shape_54.setTransform(20.1,135);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgXAuQgDAEgDAHIgFAAIAAgjIAFAAQAJAeAWAAQAKAAAFgFQAFgHAAgHQAAgIgFgFQgGgGgOgIQgQgGgIgIQgHgIAAgMQAAgKAIgKQAHgKAPAAQAMAAAJAMIAGgKIAEAAIAAAiIgEAAQgDgMgHgIQgIgKgJABQgIAAgFAEQgFAGAAAGQAAAHAFAFQAGAFANAHQAXAKAFAJQAFAKAAAJQAAANgJAJQgKAKgOgBQgOAAgLgMg");
	this.shape_55.setTransform(172.5,81.6);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgUAzQgMgGgIgNQgIgNAAgSQAAgZAPgQQAPgRAWgBQAVABAMANQALANABAPIhKAAIgBALQAAAcAJAOQAJAOAQAAQAYAAAKgVIAHAAQgFANgMAIQgMAHgPAAQgNABgMgIgAgZgWIAzAAIAAgFQAAgMgGgGQgHgGgKAAQgYAAgEAdg");
	this.shape_56.setTransform(162,81.6);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgIBEQgIgGgBgIQgCgHAAgTIAAg8IgQAAIAAgGQALAAAJgJQAIgJADgQIAEAAIAAAiIAfAAIAAAGIgfAAIAABAQAAAPAAAFQABAGAFADQAEADAFAAQAJAAAHgLIAFADQgFAIgHAFQgIAEgJAAQgIAAgHgFg");
	this.shape_57.setTransform(152.5,80.1);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgfAzQgIgFgDgHQgDgHgBgOIAAgkIAAgXQgBgEgDgCQgEgCgJAAIAAgGIAkAAIAABKQAAALACAFQABAFAFAEQAGADAHAAQAJAAAKgGQAJgHADgHQAEgIAAgOIAAgXIgBgWQAAgDgDgDQgDgDgJAAIgEAAIAAgGIAnAAIAABGIAAAWQAAAEAEACQADADAJAAIAAAGQgUAAgKAEIgBAAQgFgHABgSQgIAMgLAHQgKAGgMAAQgKAAgJgFg");
	this.shape_58.setTransform(141.2,81.8);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgLBYQgJgFgGgKQgJAJgFALIgFAAIAAiPIgBgVQgBgFgEgCQgDgCgJAAIAAgGIATgCQALgCAEgCIADAAIAABVQAJgIAJgEQAJgEAKAAQAXAAAPAQQAPAQAAAZQAAAZgQARQgPARgYAAQgLAAgJgFgAgJgLQgJAEgIAHIAAArQAAAQACAIQACAGAIAHQAJAGAKABQARgBAKgOQAKgOAAgZQAAgZgKgLQgJgNgQAAQgIAAgIAFg");
	this.shape_59.setTransform(126.9,78.1);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgcBbIAAgGIAEAAQAKAAADgDQACgDABgDIAAgWIAAghQAAgTgBgDQgCgEgDgBIgKgCIgEAAIAAgGQAXgCAMgFIADAAIAABLIABAVQAAAFAEACQADADAIAAIADAAIAAAGgAgKhCQgEgEAAgGQAAgFAEgEQAEgFAGAAQAEAAAEAFQAEAEAAAFQAAAGgEAEQgEAEgEAAQgGAAgEgEg");
	this.shape_60.setTransform(116.7,77.9);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AgsA4IAAgGIADAAQAIAAADgCQADgCABgEIABgXIAAgdIgBgWQAAgEgDgDQgEgCgIAAIgDAAIAAgGQAMgCAUgGQAEAKABARQAEgLAJgIQAKgIAKAAQAJAAAFAFQAFAGAAAFQAAAEgDADQgCADgEAAQgHAAgDgKQgDgHgEAAQgGAAgIAIQgHAIgCAIQgCAIAAAOIAAATIAAAWQABAEADADQACACAJAAIADAAIAAAGg");
	this.shape_61.setTransform(108.9,81.3);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgIBEQgIgGgBgIQgCgHAAgTIAAg8IgQAAIAAgGQALAAAJgJQAIgJADgQIAEAAIAAAiIAfAAIAAAGIgfAAIAABAQAAAPAAAFQABAGAFADQAEADAFAAQAJAAAHgLIAFADQgFAIgHAFQgIAEgJAAQgIAAgHgFg");
	this.shape_62.setTransform(100,80.1);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AAKA4IAAgGIACAAQAKAAADgDQADgCAAgEIAAgWIAAgiIgBgSQgBgFgGgFQgFgEgIAAQgJAAgIAGQgKAGgHALIAAArIAAAXQABAEADACQAEACAKAAIAAAGIg3AAIAAgGQAJAAADgCQAEgCABgDIABgYIAAgfIAAgXQgBgEgEgCQgDgCgKAAIAAgGQAOgCAPgEIAEAAQADAIABAOQAJgLAKgGQAKgFAMAAQAMAAAJAFQAHAGADAIQACAHAAAPIAAAhIABAXQABAEAEACQADACAJAAIAAAGg");
	this.shape_63.setTransform(88.7,81.3);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("AgnAqQgRgQgBgaQAAgYARgQQARgRAXgBQAYABARARQARAQAAAYQgBAbgRAQQgQAPgYAAQgXABgQgRgAgZgnQgJAMAAAcQgBAcAKAMQAJAMAQgBQASABAIgMQAJgMAAgcQAAgcgJgMQgIgMgSAAQgRAAgIAMg");
	this.shape_64.setTransform(74.7,81.6);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AghAqQgQgPAAgaQAAgZARgRQARgRAXAAQAOABALAGQAMAGAAAJQAAADgCADQgCADgEAAQgJAAgCgLQgCgHgDgDQgDgDgKAAQgRAAgJAMQgJAMAAAZQAAAZAKAOQAJAOATAAQAaAAAHgXIAGAAQgJAegkAAQgWABgQgRg");
	this.shape_65.setTransform(62.4,81.6);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AgoBPQAAgJAOgGQAIgDADgDQACgCADgHIAKgaIgohWQgGgLgDgDQgEgDgJAAIAAgGIAyAAIAAAGQgNAAAAAFIAFANIAdA+IAZg7IAFgOQAAgHgOAAIAAgGIAmAAIAAAGQgJAAgEAFQgEAEgHAOIgvB0QgHAQgFAGQgFAGgGAAQgJAAAAgIg");
	this.shape_66.setTransform(43.5,84.9);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFFFF").s().p("AgsA4IAAgGIADAAQAIAAADgCQADgCABgEIABgXIAAgdIgBgWQAAgEgDgDQgEgCgIAAIgDAAIAAgGQAMgCAUgGQAEAKABARQAEgLAJgIQAKgIAKAAQAJAAAFAFQAFAGAAAFQAAAEgDADQgCADgEAAQgHAAgDgKQgDgHgEAAQgGAAgIAIQgHAIgCAIQgCAIAAAOIAAATIAAAWQABAEADADQACACAJAAIADAAIAAAGg");
	this.shape_67.setTransform(32.9,81.3);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFFFF").s().p("AgIBEQgIgGgBgIQgCgHAAgTIAAg8IgQAAIAAgGQALAAAJgJQAIgJADgQIAEAAIAAAiIAfAAIAAAGIgfAAIAABAQAAAPAAAFQABAGAFADQAEADAFAAQAJAAAHgLIAFADQgFAIgHAFQgIAEgJAAQgIAAgHgFg");
	this.shape_68.setTransform(24,80.1);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFFFF").s().p("AgXAuQgDAEgDAHIgFAAIAAgjIAFAAQAJAeAWAAQAKAAAFgFQAFgHAAgHQAAgIgFgFQgGgGgOgIQgRgGgHgIQgHgIAAgMQAAgKAIgKQAIgKAOAAQANAAAIAMIAGgKIAFAAIAAAiIgFAAQgDgMgHgIQgIgKgJABQgIAAgFAEQgFAGAAAGQAAAHAGAFQAFAFAOAHQAWAKAFAJQAFAKAAAJQAAANgJAJQgKAKgNgBQgOAAgMgMg");
	this.shape_69.setTransform(15.3,81.6);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFFFF").s().p("AgfAzQgIgFgDgHQgDgHAAgOIAAgkIgBgXQgBgEgDgCQgDgCgKAAIAAgGIAkAAIAABKQABALABAFQABAFAGAEQAFADAHAAQAKAAAIgGQAKgHADgHQAEgIgBgOIAAgXIAAgWQAAgDgDgDQgDgDgKAAIgDAAIAAgGIAmAAIAABGIABAWQABAEADACQADADAJAAIAAAGQgUAAgJAEIgCAAQgEgHgBgSQgIAMgKAHQgKAGgMAAQgKAAgJgFg");
	this.shape_70.setTransform(3.7,81.8);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFFFF").s().p("AAdBJQgKAKgKAFQgKAFgLAAQgVAAgPgRQgPgRAAgYQAAgaAPgQQAQgQAVAAQALAAAJAEQAKAEAJAIIAAgqIgBgWQAAgFgEgCQgDgCgIAAIgDAAIAAgGQAQAAATgGIADAAIAACQIAAAYQABADADACQAEACAJABIAAAFQgTABgPADQgBgGAAgOgAgfgDQgKAKAAAaQAAAbAKAMQAKANAPAAQAJAAAJgFQAIgFAIgJIAAhCQgJgHgJgEQgJgDgHAAQgPgBgKAMg");
	this.shape_71.setTransform(-10,78.1);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFFFF").s().p("AAKA4IAAgGIACAAQAKAAADgDQACgCABgEIAAgWIAAgiIAAgSQgCgFgGgFQgFgEgIAAQgJAAgIAGQgKAGgHALIAAArIABAXQAAAEADACQAEACAKAAIAAAGIg3AAIAAgGQAJAAADgCQAEgCABgDIABgYIAAgfIAAgXQgCgEgDgCQgEgCgJAAIAAgGQAPgCAPgEIADAAQAEAIAAAOQAJgLALgGQAJgFALAAQANAAAJAFQAHAGADAIQADAHgBAPIAAAhIABAXQABAEAEACQADACAJAAIAAAGg");
	this.shape_72.setTransform(-24.4,81.3);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#FFFFFF").s().p("AgcBbIAAgGIAEAAQAKAAADgDQACgDABgDIAAgWIAAghQAAgTgBgDQgCgEgDgBIgKgCIgEAAIAAgGQAXgCAMgFIADAAIAABLIABAVQAAAFAEACQADADAIAAIADAAIAAAGgAgKhCQgEgEAAgGQAAgFAEgEQAEgFAGAAQAEAAAEAFQAEAEAAAFQAAAGgEAEQgEAEgEAAQgGAAgEgEg");
	this.shape_73.setTransform(-35.1,77.9);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFFFFF").s().p("AgoBPQAAgJAOgGQAIgDADgDQACgCADgHIAKgaIgohWQgGgLgDgDQgEgDgJAAIAAgGIAyAAIAAAGQgNAAAAAFIAFANIAdA+IAZg7IAFgOQAAgHgOAAIAAgGIAmAAIAAAGQgJAAgEAFQgEAEgHAOIgvB0QgHAQgFAGQgFAGgGAAQgJAAAAgIg");
	this.shape_74.setTransform(125.2,30);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#FFFFFF").s().p("AgtBQQgOgJAAgPQgBgIAFgFQAEgFAIgBIAEABQgJAKABAJQgBAMALAIQAMAHAVAAQASAAALgHQAKgJAAgMQAAgNgJgFQgKgFgYgBQgcgCgIgFQgJgGAAgJQAAgQAYgEQgMgIgGgJQgGgKgBgMQABgQANgMQAMgLASgBQAVABAOAOQALgNALAAQAGAAAEAEQADADAAAEQABAJgJgBQgDABgEgGQgDgFgDAAQgFAAgGAHQAHALAAAMQAAAPgLANQgMAMgZABQgcABAAAJQAAAFAFACQAHACATACQAVABAMADQAMADAHAIQAHAKAAAMQAAARgPALQgNAKgaABQgZgBgPgJgAgchJQgGAJAAATQAAARAHAHQAHAIALAAQAJAAAHgHQAIgIAAgUQgBgTgHgIQgHgHgKAAQgLAAgHAJg");
	this.shape_75.setTransform(113.2,29.8);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#FFFFFF").s().p("AgsA4IAAgGIADAAQAIAAADgCQADgCABgEIABgXIAAgdIgBgWQAAgEgDgDQgEgCgIAAIgDAAIAAgGQAMgCAUgGQAEAKABARQAEgLAJgIQAKgIAKAAQAJAAAFAFQAFAGAAAFQAAAEgDADQgCADgEAAQgHAAgDgKQgDgHgEAAQgGAAgIAIQgHAIgCAIQgCAIAAAOIAAATIAAAWQABAEADADQACACAJAAIADAAIAAAGg");
	this.shape_76.setTransform(101.9,26.4);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#FFFFFF").s().p("AgUAzQgMgGgIgNQgIgNAAgSQAAgZAPgQQAPgRAWgBQAVABALANQAMANABAPIhLAAIAAALQAAAcAJAOQAJAOAQAAQAYAAAKgVIAHAAQgEANgNAIQgNAHgOAAQgNABgMgIgAgZgWIAzAAIAAgFQAAgMgHgGQgHgGgJAAQgYAAgEAdg");
	this.shape_77.setTransform(90.7,26.7);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#FFFFFF").s().p("AAKA4IAAgGIADAAQAJAAADgDQADgCAAgEIABgWIAAgiIgCgSQgBgFgFgFQgGgEgJAAQgIAAgJAGQgJAGgIALIAAArIABAXQABAEAEACQADACAJAAIAAAGIg2AAIAAgGQAJAAAEgCQADgCABgDIABgYIAAgfIgBgXQgBgEgDgCQgEgCgJAAIAAgGQAOgCAPgEIAEAAQAEAIgBAOQAKgLAKgGQAKgFAMAAQAMAAAIAFQAJAGACAIQADAHAAAPIAAAhIAAAXQABAEADACQAEACAJAAIAAAGg");
	this.shape_78.setTransform(77.8,26.4);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#FFFFFF").s().p("AgUAzQgMgGgIgNQgIgNAAgSQAAgZAPgQQAPgRAWgBQAVABALANQAMANABAPIhLAAIAAALQAAAcAJAOQAJAOAQAAQAYAAAKgVIAHAAQgEANgNAIQgNAHgOAAQgNABgMgIgAgZgWIAzAAIAAgFQAAgMgHgGQgHgGgJAAQgYAAgEAdg");
	this.shape_79.setTransform(64.6,26.7);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#FFFFFF").s().p("AgUAzQgMgGgIgNQgIgNAAgSQAAgZAPgQQAPgRAWgBQAVABALANQAMANABAPIhLAAIAAALQAAAcAJAOQAJAOAQAAQAYAAALgVIAGAAQgEANgNAIQgNAHgOAAQgNABgMgIgAgZgWIAzAAIAAgFQAAgMgHgGQgGgGgLAAQgWAAgFAdg");
	this.shape_80.setTransform(46.1,26.7);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#FFFFFF").s().p("AAKBbIAAgGIACAAQAKAAADgDQACgDABgEIABgVIAAghQgBgNgBgHQgCgFgFgEQgHgFgIAAQgJAAgJAHQgIAFgGALIAAAsIABAWQAAAEADADQAEACAJAAIAAAGIg3AAIAAgGIADAAQAKAAACgDQADgDABgDIAAgWIAAhrQAAgQgDgFQgDgEgLAAIAAgGQATAAAOgGIADAAIAABbQAIgKAKgGQAJgGAMAAQANAAAIAGQAJAGADAIQACAHAAASIAAAeIABAXQABAEAEACQADACAJAAIAAAGg");
	this.shape_81.setTransform(33.1,23);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFFFF").s().p("AgsBZIAAgGIAKAAQALAAAFgDQAEgCABgHQABgFAAgXIAAh9IgbAAQgRAAgFABQgHACgEAIQgGAJgCAQIgHAAIABgrICtAAIABArIgGAAQgDgRgFgIQgFgHgGgDQgGgBgQAAIgcAAIAAB9IABAbQABAHAEADQAEADANAAIAJAAIAAAGg");
	this.shape_82.setTransform(16.5,23.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(-40.5,5.8,219.5,419.2), null);


(lib.redcircle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,55,66,0.698)").s().p("AswMxQlSlSAAnfQAAndFSlTQFTlSHdAAQHfAAFSFSQFSFTAAHdQAAHflSFSQlSFSnfAAQndAAlTlSg");
	this.shape.setTransform(115.5,115.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.redcircle, new cjs.Rectangle(0,0,231,231), null);


(lib.blue = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,192,174,0.698)").s().p("AswMxQlSlSAAnfQAAndFSlTQFTlSHdAAQHfAAFSFSQFSFTAAHdQAAHflSFSQlSFSnfAAQndAAlTlSg");
	this.shape.setTransform(115.5,115.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blue, new cjs.Rectangle(0,0,231,231), null);


// stage content:
(lib._970x250_change = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// logos
	this.instance = new lib.LogoWhite();
	this.instance.parent = this;
	this.instance.setTransform(802,177);

	this.instance_1 = new lib.SHAREDFUTURE();
	this.instance_1.parent = this;
	this.instance_1.setTransform(22,219);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(327));

	// Layer_5
	this.instance_2 = new lib.Symbol3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(485.1,104,0.625,0.625,0,0,0,151.6,37.8);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(258).to({_off:false},0).wait(1).to({regX:151.4,regY:38.5,x:484.9,y:104.5,alpha:0.001},0).wait(1).to({scaleX:0.63,scaleY:0.63,y:104.6,alpha:0.005},0).wait(1).to({scaleX:0.63,scaleY:0.63,y:104.7,alpha:0.011},0).wait(1).to({scaleX:0.63,scaleY:0.63,y:105,alpha:0.021},0).wait(1).to({scaleX:0.64,scaleY:0.64,y:105.3,alpha:0.035},0).wait(1).to({scaleX:0.65,scaleY:0.65,y:105.8,alpha:0.054},0).wait(1).to({scaleX:0.66,scaleY:0.66,y:106.5,alpha:0.079},0).wait(1).to({scaleX:0.67,scaleY:0.67,y:107.3,alpha:0.111},0).wait(1).to({scaleX:0.68,scaleY:0.68,y:108.3,alpha:0.153},0).wait(1).to({scaleX:0.7,scaleY:0.7,y:109.6,alpha:0.204},0).wait(1).to({scaleX:0.73,scaleY:0.73,y:111.2,alpha:0.267},0).wait(1).to({scaleX:0.75,scaleY:0.75,y:113,alpha:0.338},0).wait(1).to({scaleX:0.78,scaleY:0.78,y:114.9,alpha:0.414},0).wait(1).to({scaleX:0.81,scaleY:0.81,y:116.8,alpha:0.488},0).wait(1).to({scaleX:0.83,scaleY:0.83,y:118.5,alpha:0.556},0).wait(1).to({scaleX:0.86,scaleY:0.86,y:120,alpha:0.617},0).wait(1).to({scaleX:0.88,scaleY:0.88,y:121.4,alpha:0.669},0).wait(1).to({scaleX:0.89,scaleY:0.89,x:484.8,y:122.6,alpha:0.715},0).wait(1).to({scaleX:0.91,scaleY:0.91,y:123.5,alpha:0.755},0).wait(1).to({scaleX:0.92,scaleY:0.92,x:484.9,y:124.4,alpha:0.789},0).wait(1).to({scaleX:0.93,scaleY:0.93,y:125.2,alpha:0.819},0).wait(1).to({scaleX:0.94,scaleY:0.94,y:125.8,alpha:0.846},0).wait(1).to({scaleX:0.95,scaleY:0.95,y:126.4,alpha:0.869},0).wait(1).to({scaleX:0.96,scaleY:0.96,y:126.9,alpha:0.889},0).wait(1).to({scaleX:0.97,scaleY:0.97,y:127.4,alpha:0.907},0).wait(1).to({scaleX:0.97,scaleY:0.97,y:127.8,alpha:0.922},0).wait(1).to({scaleX:0.98,scaleY:0.98,x:484.8,y:128.2,alpha:0.936},0).wait(1).to({scaleX:0.98,scaleY:0.98,x:484.9,y:128.4,alpha:0.948},0).wait(1).to({scaleX:0.98,scaleY:0.98,y:128.7,alpha:0.958},0).wait(1).to({scaleX:0.99,scaleY:0.99,y:128.9,alpha:0.967},0).wait(1).to({scaleX:0.99,scaleY:0.99,x:484.8,y:129.1,alpha:0.975},0).wait(1).to({scaleX:0.99,scaleY:0.99,x:484.9,y:129.3,alpha:0.981},0).wait(1).to({scaleX:1,scaleY:1,y:129.4,alpha:0.987},0).wait(1).to({scaleX:1,scaleY:1,y:129.5,alpha:0.991},0).wait(1).to({scaleX:1,scaleY:1,x:484.8,y:129.6,alpha:0.994},0).wait(1).to({scaleX:1,scaleY:1,y:129.7,alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({scaleX:1,scaleY:1,x:484.9,alpha:1},0).wait(1).to({regY:37.6,x:485,y:129.1},0).wait(30));

	// Layer_3
	this.instance_3 = new lib.Symbol1();
	this.instance_3.parent = this;
	this.instance_3.setTransform(485,135.6,1,1,0,0,0,69.2,119.2);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(14).to({_off:false},0).to({alpha:1},25).wait(109).to({regX:69,regY:191,x:484.8,y:207.3},0).wait(1).to({y:207.1},0).wait(1).to({y:206.8},0).wait(1).to({y:206.3},0).wait(1).to({y:205.6},0).wait(1).to({y:204.6},0).wait(1).to({y:203.4},0).wait(1).to({y:202},0).wait(1).to({y:200.1},0).wait(1).to({y:197.9},0).wait(1).to({y:195.1},0).wait(1).to({y:191.6},0).wait(1).to({y:187.3},0).wait(1).to({y:181.6},0).wait(1).to({y:174},0).wait(1).to({y:163},0).wait(1).to({y:145.2},0).wait(1).to({y:116.8},0).wait(1).to({y:94.2},0).wait(1).to({y:81.1},0).wait(1).to({y:72.5},0).wait(1).to({y:66.4},0).wait(1).to({y:61.7},0).wait(1).to({y:58.1},0).wait(1).to({y:55.3},0).wait(1).to({y:53.1},0).wait(1).to({y:51.3},0).wait(1).to({y:49.9},0).wait(1).to({y:48.8},0).wait(1).to({y:47.9},0).wait(1).to({y:47.3},0).wait(1).to({y:46.9},0).wait(1).to({y:46.7},0).wait(1).to({regX:69.2,regY:119.2,x:485,y:-25.2},0).wait(66).to({alpha:0},23,cjs.Ease.get(-1)).to({_off:true},2).wait(55));

	// Black (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_94 = new cjs.Graphics().p("AO6NkQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_147 = new cjs.Graphics().p("AO6NkQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_148 = new cjs.Graphics().p("AO6NkQGqk8IsAAQIsAAGpE8QmpE8osAAQosAAmqk8g");
	var mask_graphics_149 = new cjs.Graphics().p("AO6NjQGqk8IsAAQIsAAGpE8QmpE8osAAQosAAmqk8g");
	var mask_graphics_150 = new cjs.Graphics().p("AO6NhQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_151 = new cjs.Graphics().p("AO6NfQGqk8IsAAQIsAAGpE8QmpE8osAAQosAAmqk8g");
	var mask_graphics_152 = new cjs.Graphics().p("AO6NbQGqk8IsAAQIsAAGpE8QmpE8osAAQosAAmqk8g");
	var mask_graphics_153 = new cjs.Graphics().p("AO6NWQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_154 = new cjs.Graphics().p("AO6NQQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_155 = new cjs.Graphics().p("AO6NJQGqk8IsAAQIsAAGpE8QmpE8osAAQosAAmqk8g");
	var mask_graphics_156 = new cjs.Graphics().p("AO6NAQGqk8IsAAQIsAAGpE8QmpE8osAAQosAAmqk8g");
	var mask_graphics_157 = new cjs.Graphics().p("AO6M0QGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_158 = new cjs.Graphics().p("AO6MmQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_159 = new cjs.Graphics().p("AO6MVQGqk8IsAAQIsAAGpE8QmpE8osAAQosAAmqk8g");
	var mask_graphics_160 = new cjs.Graphics().p("AO6L/QGqk8IsAAQIsAAGpE8QmpE8osAAQosAAmqk8g");
	var mask_graphics_161 = new cjs.Graphics().p("AO6LiQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_162 = new cjs.Graphics().p("AO6K8QGqk8IsAAQIsAAGpE8QmpE8osAAQosAAmqk8g");
	var mask_graphics_163 = new cjs.Graphics().p("AO6KEQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_164 = new cjs.Graphics().p("AO6IqQGqk7IsAAQIsAAGpE7QmpE9osAAQosAAmqk9g");
	var mask_graphics_165 = new cjs.Graphics().p("AO6GcQGqk8IsAAQIsAAGpE8QmpE8osAAQosAAmqk8g");
	var mask_graphics_166 = new cjs.Graphics().p("AO6EqQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_167 = new cjs.Graphics().p("AO6DoQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_168 = new cjs.Graphics().p("AO6C8QGqk6IsAAQIsAAGpE6QmpE8osAAQosAAmqk8g");
	var mask_graphics_169 = new cjs.Graphics().p("AO6CeQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_170 = new cjs.Graphics().p("AO6CGQGqk6IsAAQIsAAGpE6QmpE8osAAQosAAmqk8g");
	var mask_graphics_171 = new cjs.Graphics().p("AO6B0QGqk6IsAAQIsAAGpE6QmpE8osAAQosAAmqk8g");
	var mask_graphics_172 = new cjs.Graphics().p("AO6BmQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_173 = new cjs.Graphics().p("AO6BbQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_174 = new cjs.Graphics().p("AO6BSQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_175 = new cjs.Graphics().p("AO6BKQGqk6IsAAQIsAAGpE6QmpE8osAAQosAAmqk8g");
	var mask_graphics_176 = new cjs.Graphics().p("AO6BFQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_177 = new cjs.Graphics().p("AO6BBQGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_178 = new cjs.Graphics().p("AO6A+QGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_179 = new cjs.Graphics().p("AO6A8QGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_180 = new cjs.Graphics().p("AO6A7QGqk7IsAAQIsAAGpE7QmpE8osAAQosAAmqk8g");
	var mask_graphics_181 = new cjs.Graphics().p("AO6A6QGqk6IsAAQIsAAGpE6QmpE8osAAQosAAmqk8g");
	var mask_graphics_247 = new cjs.Graphics().p("AO6A6QGqk6IsAAQIsAAGpE6QmpE8osAAQosAAmqk8g");
	var mask_graphics_248 = new cjs.Graphics().p("AO6A6QGpk6ItAAQIsAAGpE6QmpE8osAAQotAAmpk8g");
	var mask_graphics_249 = new cjs.Graphics().p("AO4A6QGqk7ItAAQItAAGqE7QmqE9otAAQotAAmqk9g");
	var mask_graphics_250 = new cjs.Graphics().p("AO1A7QGrk8IuAAQIuAAGrE8QmrE9ouAAQouAAmrk9g");
	var mask_graphics_251 = new cjs.Graphics().p("AOxA7QGsk8IwAAQIwAAGrE8QmrE+owAAQowAAmsk+g");
	var mask_graphics_252 = new cjs.Graphics().p("AOsA7QGuk9IxAAQIyAAGtE9QmtE/oyAAQoxAAmuk/g");
	var mask_graphics_253 = new cjs.Graphics().p("AOlA8QGwk/I0AAQI0AAGvE/QmvFAo0AAQo0AAmwlAg");
	var mask_graphics_254 = new cjs.Graphics().p("AOdA8QGylAI3AAQI4AAGxFAQmxFDo4AAQo3AAmylDg");
	var mask_graphics_255 = new cjs.Graphics().p("AOSA9QG1lDI7AAQI8AAG1FDQm1FFo8AAQo7AAm1lFg");
	var mask_graphics_256 = new cjs.Graphics().p("AOGA+QG5lGI/AAQJBAAG4FGQm4FHpBAAQo/AAm5lHg");
	var mask_graphics_257 = new cjs.Graphics().p("AN4A/QG8lJJGAAQJFAAG8FJQm8FKpFAAQpGAAm8lKg");
	var mask_graphics_258 = new cjs.Graphics().p("ANmBAQHClMJMAAQJMAAHBFMQnBFOpMAAQpMAAnClOg");
	var mask_graphics_259 = new cjs.Graphics().p("ANSBCQHIlRJTAAQJUAAHHFRQnHFSpUAAQpTAAnIlSg");
	var mask_graphics_260 = new cjs.Graphics().p("AM7BEQHOlWJcAAQJdAAHOFWQnOFXpdAAQpcAAnOlXg");
	var mask_graphics_261 = new cjs.Graphics().p("AMfBGQHXlcJmAAQJnAAHWFcQnWFdpnAAQpmAAnXldg");
	var mask_graphics_262 = new cjs.Graphics().p("AL/BIQHgljJyAAQJ0AAHfFjQnfFkp0AAQpyAAnglkg");
	var mask_graphics_263 = new cjs.Graphics().p("ALaBLQHqlrKBAAQKBAAHqFrQnqFsqBAAQqBAAnqlsg");
	var mask_graphics_264 = new cjs.Graphics().p("AKtBOQH3l0KSAAQKSAAH3F0Qn3F2qSAAQqSAAn3l2g");
	var mask_graphics_265 = new cjs.Graphics().p("AJ4BSQIGmAKmAAQKnAAIGGAQoGGBqnAAQqmAAoGmBg");
	var mask_graphics_266 = new cjs.Graphics().p("AI3BXQIZmOK+AAQLAAAIYGOQoYGPrAAAQq+AAoZmPg");
	var mask_graphics_267 = new cjs.Graphics().p("AHlBdQIxmfLdAAQLeAAIwGfQowGgreAAQrdAAoxmgg");
	var mask_graphics_268 = new cjs.Graphics().p("AF9BkQJPm1MFAAQMFAAJOG1QpOG3sFAAQsFAApPm3g");
	var mask_graphics_269 = new cjs.Graphics().p("ADvBvQJ4nUM6AAQM7AAJ4HUQp4HVs7AAQs6AAp4nVg");
	var mask_graphics_270 = new cjs.Graphics().p("AAeB+QK1oBOJAAQOJAAK0IBQq0ICuJAAQuJAAq1oCg");
	var mask_graphics_271 = new cjs.Graphics().p("AkSCUQMMpCP8AAQP9AAMMJCQsMJEv9AAQv8AAsMpEg");
	var mask_graphics_272 = new cjs.Graphics().p("Ao+CqQNjqCRtAAQRuAANjKCQtjKExuAAQxtAAtjqEg");
	var mask_graphics_273 = new cjs.Graphics().p("AsIC5QOdquS6AAQS6AAOdKuQudKvy6AAQy6AAudqvg");
	var mask_graphics_274 = new cjs.Graphics().p("AuRDDQPFrLTtAAQTuAAPFLLQvFLNzuAAQztAAvFrNg");
	var mask_graphics_275 = new cjs.Graphics().p("Av1DKQPjrgUSAAQUUAAPhLgQvhLi0UAAQ0SAAvjrig");
	var mask_graphics_276 = new cjs.Graphics().p("AxCDQQP5rxUvAAQUxAAP4LxQv4Lz0xAAQ0vAAv5rzg");
	var mask_graphics_277 = new cjs.Graphics().p("Ax/DUQQKr+VHAAQVIAAQJL+QwJMA1IAAQ1HAAwKsAg");
	var mask_graphics_278 = new cjs.Graphics().p("AyxDYQQZsJVZAAQVbAAQYMJQwYML1bAAQ1ZAAwZsLg");
	var mask_graphics_279 = new cjs.Graphics().p("AzbDbQQlsSVpAAQVrAAQkMSQwkMU1rAAQ1pAAwlsUg");
	var mask_graphics_280 = new cjs.Graphics().p("Az9DdQQusYV2AAQV5AAQtMYQwtMc15AAQ12AAwuscg");
	var mask_graphics_281 = new cjs.Graphics().p("A0aDgQQ3sgWBAAQWDAAQ2MgQw2Mh2DAAQ2BAAw3shg");
	var mask_graphics_282 = new cjs.Graphics().p("A0zDhQQ+skWLAAQWMAAQ9MkQw9Mn2MAAQ2LAAw+sng");
	var mask_graphics_283 = new cjs.Graphics().p("A1IDjQREspWTAAQWUAARDMpQxDMr2UAAQ2TAAxEsrg");
	var mask_graphics_284 = new cjs.Graphics().p("A1ZDkQRJssWZAAQWbAARIMsQxIMv2bAAQ2ZAAxJsvg");
	var mask_graphics_285 = new cjs.Graphics().p("A1oDlQROsvWeAAQWgAARNMvQxNMy2gAAQ2eAAxOsyg");
	var mask_graphics_286 = new cjs.Graphics().p("A10DmQRRsyWjAAQWlAARQMyQxQM12lAAQ2jAAxRs1g");
	var mask_graphics_287 = new cjs.Graphics().p("A1+DnQRUs1WnAAQWoAARTM1QxTM32oAAQ2nAAxUs3g");
	var mask_graphics_288 = new cjs.Graphics().p("A2GDnQRWs2WqAAQWsAARVM2QxVM52sAAQ2qAAxWs5g");
	var mask_graphics_289 = new cjs.Graphics().p("A2MDoQRYs4WsAAQWuAARXM4QxXM62uAAQ2sAAxYs6g");
	var mask_graphics_290 = new cjs.Graphics().p("A2RDoQRas4WtAAQWwAARYM4QxYM72wAAQ2tAAxas7g");
	var mask_graphics_291 = new cjs.Graphics().p("A2UDoQRas5WvAAQWxAARZM5QxZM82xAAQ2vAAxas8g");
	var mask_graphics_292 = new cjs.Graphics().p("A2VDpQRas6WwAAQWyAARZM6QxZM72yAAQ2wAAxas7g");
	var mask_graphics_293 = new cjs.Graphics().p("A2WDpQRbs6WvAAQWzAARZM6QxZM82zAAQ2vAAxbs8g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(94).to({graphics:mask_graphics_94,x:291.7,y:118.4}).wait(53).to({graphics:mask_graphics_147,x:291.7,y:118.4}).wait(1).to({graphics:mask_graphics_148,x:291.7,y:118.4}).wait(1).to({graphics:mask_graphics_149,x:291.7,y:118.3}).wait(1).to({graphics:mask_graphics_150,x:291.7,y:118.1}).wait(1).to({graphics:mask_graphics_151,x:291.7,y:117.9}).wait(1).to({graphics:mask_graphics_152,x:291.7,y:117.5}).wait(1).to({graphics:mask_graphics_153,x:291.7,y:117}).wait(1).to({graphics:mask_graphics_154,x:291.7,y:116.4}).wait(1).to({graphics:mask_graphics_155,x:291.7,y:115.7}).wait(1).to({graphics:mask_graphics_156,x:291.7,y:114.8}).wait(1).to({graphics:mask_graphics_157,x:291.7,y:113.6}).wait(1).to({graphics:mask_graphics_158,x:291.7,y:112.2}).wait(1).to({graphics:mask_graphics_159,x:291.7,y:110.5}).wait(1).to({graphics:mask_graphics_160,x:291.7,y:108.3}).wait(1).to({graphics:mask_graphics_161,x:291.7,y:105.4}).wait(1).to({graphics:mask_graphics_162,x:291.7,y:101.6}).wait(1).to({graphics:mask_graphics_163,x:291.7,y:96}).wait(1).to({graphics:mask_graphics_164,x:291.7,y:87.1}).wait(1).to({graphics:mask_graphics_165,x:291.7,y:72.8}).wait(1).to({graphics:mask_graphics_166,x:291.7,y:61.4}).wait(1).to({graphics:mask_graphics_167,x:291.7,y:54.8}).wait(1).to({graphics:mask_graphics_168,x:291.7,y:50.4}).wait(1).to({graphics:mask_graphics_169,x:291.7,y:47.4}).wait(1).to({graphics:mask_graphics_170,x:291.7,y:45}).wait(1).to({graphics:mask_graphics_171,x:291.7,y:43.2}).wait(1).to({graphics:mask_graphics_172,x:291.7,y:41.8}).wait(1).to({graphics:mask_graphics_173,x:291.7,y:40.7}).wait(1).to({graphics:mask_graphics_174,x:291.7,y:39.8}).wait(1).to({graphics:mask_graphics_175,x:291.7,y:39}).wait(1).to({graphics:mask_graphics_176,x:291.7,y:38.5}).wait(1).to({graphics:mask_graphics_177,x:291.7,y:38.1}).wait(1).to({graphics:mask_graphics_178,x:291.7,y:37.8}).wait(1).to({graphics:mask_graphics_179,x:291.7,y:37.6}).wait(1).to({graphics:mask_graphics_180,x:291.7,y:37.5}).wait(1).to({graphics:mask_graphics_181,x:291.7,y:37.4}).wait(66).to({graphics:mask_graphics_247,x:291.7,y:37.4}).wait(1).to({graphics:mask_graphics_248,x:291.7,y:37.4}).wait(1).to({graphics:mask_graphics_249,x:291.8,y:37.5}).wait(1).to({graphics:mask_graphics_250,x:291.9,y:37.6}).wait(1).to({graphics:mask_graphics_251,x:292,y:37.7}).wait(1).to({graphics:mask_graphics_252,x:292.2,y:37.8}).wait(1).to({graphics:mask_graphics_253,x:292.4,y:38}).wait(1).to({graphics:mask_graphics_254,x:292.7,y:38.3}).wait(1).to({graphics:mask_graphics_255,x:293.1,y:38.6}).wait(1).to({graphics:mask_graphics_256,x:293.5,y:38.9}).wait(1).to({graphics:mask_graphics_257,x:293.9,y:39.3}).wait(1).to({graphics:mask_graphics_258,x:294.5,y:39.8}).wait(1).to({graphics:mask_graphics_259,x:295.2,y:40.4}).wait(1).to({graphics:mask_graphics_260,x:296,y:41.1}).wait(1).to({graphics:mask_graphics_261,x:296.9,y:41.9}).wait(1).to({graphics:mask_graphics_262,x:298,y:42.8}).wait(1).to({graphics:mask_graphics_263,x:299.2,y:43.9}).wait(1).to({graphics:mask_graphics_264,x:300.7,y:45.2}).wait(1).to({graphics:mask_graphics_265,x:302.5,y:46.7}).wait(1).to({graphics:mask_graphics_266,x:304.6,y:48.6}).wait(1).to({graphics:mask_graphics_267,x:307.3,y:50.9}).wait(1).to({graphics:mask_graphics_268,x:310.8,y:53.9}).wait(1).to({graphics:mask_graphics_269,x:315.6,y:58}).wait(1).to({graphics:mask_graphics_270,x:322.5,y:64}).wait(1).to({graphics:mask_graphics_271,x:332.7,y:72.8}).wait(1).to({graphics:mask_graphics_272,x:342.7,y:81.4}).wait(1).to({graphics:mask_graphics_273,x:349.4,y:87.2}).wait(1).to({graphics:mask_graphics_274,x:354,y:91.2}).wait(1).to({graphics:mask_graphics_275,x:357.3,y:94}).wait(1).to({graphics:mask_graphics_276,x:359.9,y:96.3}).wait(1).to({graphics:mask_graphics_277,x:361.9,y:98}).wait(1).to({graphics:mask_graphics_278,x:363.6,y:99.5}).wait(1).to({graphics:mask_graphics_279,x:365,y:100.7}).wait(1).to({graphics:mask_graphics_280,x:366.1,y:101.7}).wait(1).to({graphics:mask_graphics_281,x:367.1,y:102.5}).wait(1).to({graphics:mask_graphics_282,x:367.9,y:103.2}).wait(1).to({graphics:mask_graphics_283,x:368.6,y:103.8}).wait(1).to({graphics:mask_graphics_284,x:369.2,y:104.3}).wait(1).to({graphics:mask_graphics_285,x:369.7,y:104.7}).wait(1).to({graphics:mask_graphics_286,x:370.1,y:105.1}).wait(1).to({graphics:mask_graphics_287,x:370.4,y:105.4}).wait(1).to({graphics:mask_graphics_288,x:370.7,y:105.6}).wait(1).to({graphics:mask_graphics_289,x:370.9,y:105.8}).wait(1).to({graphics:mask_graphics_290,x:371,y:105.9}).wait(1).to({graphics:mask_graphics_291,x:371.1,y:106}).wait(1).to({graphics:mask_graphics_292,x:371.2,y:106}).wait(1).to({graphics:mask_graphics_293,x:371.2,y:106.1}).wait(34));

	// eye
	this.instance_4 = new lib.Symbol2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(485.4,294.3,1,1,0,0,0,98.2,31.6);
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(94).to({_off:false},0).wait(1).to({y:294.2},0).wait(1).to({y:294},0).wait(1).to({y:293.5},0).wait(1).to({y:292.9},0).wait(1).to({y:291.9},0).wait(1).to({y:290.7},0).wait(1).to({y:289.1},0).wait(1).to({y:287},0).wait(1).to({y:284.4},0).wait(1).to({y:281.2},0).wait(1).to({y:277.3},0).wait(1).to({y:272.6},0).wait(1).to({y:267.2},0).wait(1).to({y:261.3},0).wait(1).to({y:255.3},0).wait(1).to({y:249.5},0).wait(1).to({y:244.1},0).wait(1).to({y:239.3},0).wait(1).to({y:235.1},0).wait(1).to({y:231.4},0).wait(1).to({y:228.1},0).wait(1).to({y:225.2},0).wait(1).to({y:222.6},0).wait(1).to({y:220.3},0).wait(1).to({y:218.3},0).wait(1).to({y:216.5},0).wait(1).to({y:214.9},0).wait(1).to({y:213.4},0).wait(1).to({y:212.1},0).wait(1).to({y:211},0).wait(1).to({y:210},0).wait(1).to({y:209.1},0).wait(1).to({y:208.3},0).wait(1).to({y:207.6},0).wait(1).to({y:207},0).wait(1).to({y:206.5},0).wait(1).to({y:206.1},0).wait(1).to({y:205.7},0).wait(1).to({y:205.4},0).wait(1).to({y:205.2},0).wait(1).to({y:205},0).wait(1).to({y:204.9},0).wait(1).to({y:204.8},0).wait(11).to({y:204.7},0).wait(1).to({y:204.5},0).wait(1).to({y:204.2},0).wait(1).to({y:203.7},0).wait(1).to({y:203},0).wait(1).to({y:202},0).wait(1).to({y:200.8},0).wait(1).to({y:199.4},0).wait(1).to({y:197.5},0).wait(1).to({y:195.3},0).wait(1).to({y:192.5},0).wait(1).to({y:189},0).wait(1).to({y:184.6},0).wait(1).to({y:178.9},0).wait(1).to({y:171.3},0).wait(1).to({y:160.3},0).wait(1).to({y:142.4},0).wait(1).to({y:114},0).wait(1).to({y:91.4},0).wait(1).to({y:78.3},0).wait(1).to({y:69.7},0).wait(1).to({y:63.5},0).wait(1).to({y:58.9},0).wait(1).to({y:55.3},0).wait(1).to({y:52.5},0).wait(1).to({y:50.2},0).wait(1).to({y:48.4},0).wait(1).to({y:47},0).wait(1).to({y:45.9},0).wait(1).to({y:45.1},0).wait(1).to({y:44.5},0).wait(1).to({y:44.1},0).wait(1).to({y:43.9},0).wait(1).to({y:43.8},0).wait(68).to({scaleX:1,scaleY:1,y:43.9},0).wait(1).to({scaleX:1,scaleY:1,x:485.3,y:44},0).wait(1).to({scaleX:1.01,scaleY:1.01,x:485.4,y:44.1},0).wait(1).to({scaleX:1.01,scaleY:1.01,y:44.3},0).wait(1).to({scaleX:1.01,scaleY:1.01,x:485.3,y:44.6},0).wait(1).to({scaleX:1.02,scaleY:1.02,y:44.9},0).wait(1).to({scaleX:1.03,scaleY:1.03,y:45.2},0).wait(1).to({scaleX:1.03,scaleY:1.03,x:485.4,y:45.7},0).wait(1).to({scaleX:1.05,scaleY:1.05,y:46.2},0).wait(1).to({scaleX:1.06,scaleY:1.06,y:46.8},0).wait(1).to({scaleX:1.07,scaleY:1.07,y:47.6},0).wait(1).to({scaleX:1.09,scaleY:1.09,y:48.4},0).wait(1).to({scaleX:1.11,scaleY:1.11,y:49.4},0).wait(1).to({scaleX:1.13,scaleY:1.13,x:485.3,y:50.5},0).wait(1).to({scaleX:1.15,scaleY:1.15,x:485.4,y:51.9},0).wait(1).to({scaleX:1.18,scaleY:1.18,x:485.3,y:53.5},0).wait(1).to({scaleX:1.22,scaleY:1.22,y:55.5},0).wait(1).to({scaleX:1.26,scaleY:1.26,y:57.8},0).wait(1).to({scaleX:1.32,scaleY:1.32,y:60.7},0).wait(1).to({scaleX:1.39,scaleY:1.39,x:485.4,y:64.5},0).wait(1).to({scaleX:1.49,scaleY:1.49,x:485.3,y:69.6},0).wait(1).to({scaleX:1.63,scaleY:1.63,y:77.2},0).wait(1).to({scaleX:1.84,scaleY:1.84,x:485.4,y:88.2},0).wait(1).to({scaleX:2.04,scaleY:2.04,y:99},0).wait(1).to({scaleX:2.18,scaleY:2.18,y:106.3},0).wait(1).to({scaleX:2.27,scaleY:2.27,y:111.3},0).wait(1).to({scaleX:2.34,scaleY:2.34,y:114.9},0).wait(1).to({scaleX:2.39,scaleY:2.39,y:117.7},0).wait(1).to({scaleX:2.43,scaleY:2.43,y:119.9},0).wait(1).to({scaleX:2.47,scaleY:2.47,y:121.7},0).wait(1).to({scaleX:2.49,scaleY:2.49,y:123.2},0).wait(1).to({scaleX:2.52,scaleY:2.52,y:124.4},0).wait(1).to({scaleX:2.54,scaleY:2.54,y:125.5},0).wait(1).to({scaleX:2.55,scaleY:2.55,y:126.3},0).wait(1).to({scaleX:2.57,scaleY:2.57,y:127.1},0).wait(1).to({scaleX:2.58,scaleY:2.58,y:127.8},0).wait(1).to({scaleX:2.59,scaleY:2.59,y:128.3},0).wait(1).to({scaleX:2.6,scaleY:2.6,y:128.7},0).wait(1).to({scaleX:2.6,scaleY:2.6,y:129},0).wait(1).to({scaleX:2.61,scaleY:2.61,y:129.4},0).wait(1).to({scaleX:2.61,scaleY:2.61,y:129.6},0).wait(1).to({scaleX:2.62,scaleY:2.62,y:129.7},0).wait(1).to({scaleX:2.62,scaleY:2.62,y:129.9},0).wait(1).to({scaleX:2.62,scaleY:2.62},0).wait(1).to({y:130},0).wait(34));

	// blue
	this.instance_5 = new lib.blue();
	this.instance_5.parent = this;
	this.instance_5.setTransform(485,431.6,1.459,1.459,0,0,0,115.5,115.5);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(94).to({_off:false},0).wait(1).to({y:431.5},0).wait(1).to({y:431.2},0).wait(1).to({y:430.8},0).wait(1).to({y:430.1},0).wait(1).to({y:429.2},0).wait(1).to({y:428},0).wait(1).to({y:426.3},0).wait(1).to({y:424.3},0).wait(1).to({y:421.7},0).wait(1).to({y:418.6},0).wait(1).to({y:414.7},0).wait(1).to({y:410},0).wait(1).to({y:404.6},0).wait(1).to({y:398.8},0).wait(1).to({y:392.8},0).wait(1).to({y:387.1},0).wait(1).to({y:381.8},0).wait(1).to({y:377},0).wait(1).to({y:372.8},0).wait(1).to({y:369.1},0).wait(1).to({y:365.8},0).wait(1).to({y:362.9},0).wait(1).to({y:360.4},0).wait(1).to({y:358.1},0).wait(1).to({y:356.1},0).wait(1).to({y:354.3},0).wait(1).to({y:352.7},0).wait(1).to({y:351.3},0).wait(1).to({y:350},0).wait(1).to({y:348.9},0).wait(1).to({y:347.9},0).wait(1).to({y:347},0).wait(1).to({y:346.3},0).wait(1).to({y:345.6},0).wait(1).to({y:345},0).wait(1).to({y:344.5},0).wait(1).to({y:344},0).wait(1).to({y:343.7},0).wait(1).to({y:343.4},0).wait(1).to({y:343.1},0).wait(1).to({y:343},0).wait(1).to({y:342.8},0).wait(12).to({y:342.7},0).wait(1).to({y:342.5},0).wait(1).to({y:342.1},0).wait(1).to({y:341.6},0).wait(1).to({y:340.9},0).wait(1).to({y:340},0).wait(1).to({y:338.8},0).wait(1).to({y:337.3},0).wait(1).to({y:335.4},0).wait(1).to({y:333.2},0).wait(1).to({y:330.4},0).wait(1).to({y:326.9},0).wait(1).to({y:322.5},0).wait(1).to({y:316.8},0).wait(1).to({y:309.1},0).wait(1).to({y:298.1},0).wait(1).to({y:280.2},0).wait(1).to({y:251.6},0).wait(1).to({y:228.9},0).wait(1).to({y:215.8},0).wait(1).to({y:207.1},0).wait(1).to({y:201},0).wait(1).to({y:196.3},0).wait(1).to({y:192.7},0).wait(1).to({y:189.9},0).wait(1).to({y:187.6},0).wait(1).to({y:185.8},0).wait(1).to({y:184.4},0).wait(1).to({y:183.3},0).wait(1).to({y:182.5},0).wait(1).to({y:181.9},0).wait(1).to({y:181.4},0).wait(1).to({y:181.2},0).wait(69).to({scaleX:1.46,scaleY:1.46,y:181.4},0).wait(1).to({scaleX:1.46,scaleY:1.46,y:181.8},0).wait(1).to({scaleX:1.47,scaleY:1.47,y:182.3},0).wait(1).to({scaleX:1.47,scaleY:1.47,y:183},0).wait(1).to({scaleX:1.48,scaleY:1.48,y:183.9},0).wait(1).to({scaleX:1.49,scaleY:1.49,y:184.9},0).wait(1).to({scaleX:1.5,scaleY:1.5,y:186.2},0).wait(1).to({scaleX:1.51,scaleY:1.51,y:187.8},0).wait(1).to({scaleX:1.52,scaleY:1.52,y:189.7},0).wait(1).to({scaleX:1.54,scaleY:1.54,y:191.9},0).wait(1).to({scaleX:1.56,scaleY:1.56,y:194.4},0).wait(1).to({scaleX:1.58,scaleY:1.58,y:197.5},0).wait(1).to({scaleX:1.61,scaleY:1.61,y:201},0).wait(1).to({scaleX:1.64,scaleY:1.64,y:205.1},0).wait(1).to({scaleX:1.68,scaleY:1.68,y:209.9},0).wait(1).to({scaleX:1.72,scaleY:1.72,y:215.6},0).wait(1).to({scaleX:1.78,scaleY:1.78,y:222.5},0).wait(1).to({scaleX:1.84,scaleY:1.84,y:230.8},0).wait(1).to({scaleX:1.92,scaleY:1.92,y:241.2},0).wait(1).to({scaleX:2.02,scaleY:2.02,x:484.9,y:254.5},0).wait(1).to({scaleX:2.16,scaleY:2.16,y:272.7},0).wait(1).to({scaleX:2.37,scaleY:2.37,y:299.4},0).wait(1).to({scaleX:2.66,scaleY:2.66,y:338.5},0).wait(1).to({scaleX:2.96,scaleY:2.96,y:376.9},0).wait(1).to({scaleX:3.16,scaleY:3.16,y:402.8},0).wait(1).to({scaleX:3.29,scaleY:3.29,y:420.3},0).wait(1).to({scaleX:3.39,scaleY:3.39,y:433.1},0).wait(1).to({scaleX:3.46,scaleY:3.46,y:443},0).wait(1).to({scaleX:3.52,scaleY:3.52,x:484.8,y:450.8},0).wait(1).to({scaleX:3.57,scaleY:3.57,x:484.9,y:457.3},0).wait(1).to({scaleX:3.61,scaleY:3.61,x:484.8,y:462.6},0).wait(1).to({scaleX:3.65,scaleY:3.65,x:484.9,y:467},0).wait(1).to({scaleX:3.68,scaleY:3.68,y:470.7},0).wait(1).to({scaleX:3.7,scaleY:3.7,y:473.9},0).wait(1).to({scaleX:3.72,scaleY:3.72,y:476.6},0).wait(1).to({scaleX:3.74,scaleY:3.74,x:484.8,y:478.8},0).wait(1).to({scaleX:3.75,scaleY:3.75,y:480.6},0).wait(1).to({scaleX:3.76,scaleY:3.76,x:484.9,y:482.2},0).wait(1).to({scaleX:3.77,scaleY:3.77,x:484.8,y:483.5},0).wait(1).to({scaleX:3.78,scaleY:3.78,y:484.5},0).wait(1).to({scaleX:3.79,scaleY:3.79,y:485.3},0).wait(1).to({scaleX:3.79,scaleY:3.79,x:484.9,y:485.9},0).wait(1).to({scaleX:3.8,scaleY:3.8,y:486.3},0).wait(1).to({scaleX:3.8,scaleY:3.8,y:486.5},0).wait(1).to({regX:115.6,regY:115.6,x:485.1,y:486.6},0).wait(34));

	// red
	this.instance_6 = new lib.redcircle();
	this.instance_6.parent = this;
	this.instance_6.setTransform(485,-42.4,1.459,1.459,0,0,0,115.5,115.5);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({y:-42.3,alpha:0.001},0).wait(1).to({y:-42,alpha:0.003},0).wait(1).to({y:-41.5,alpha:0.008},0).wait(1).to({y:-40.7,alpha:0.015},0).wait(1).to({y:-39.6,alpha:0.025},0).wait(1).to({y:-38.2,alpha:0.038},0).wait(1).to({y:-36.3,alpha:0.055},0).wait(1).to({y:-33.9,alpha:0.077},0).wait(1).to({y:-30.9,alpha:0.104},0).wait(1).to({y:-27.2,alpha:0.138},0).wait(1).to({y:-22.7,alpha:0.179},0).wait(1).to({y:-17.3,alpha:0.228},0).wait(1).to({y:-11.1,alpha:0.285},0).wait(1).to({y:-4.1,alpha:0.348},0).wait(1).to({y:3.1,alpha:0.414},0).wait(1).to({y:10.2,alpha:0.478},0).wait(1).to({y:16.9,alpha:0.539},0).wait(1).to({y:22.9,alpha:0.593},0).wait(1).to({y:28.2,alpha:0.642},0).wait(1).to({y:33,alpha:0.685},0).wait(1).to({y:37.2,alpha:0.723},0).wait(1).to({y:40.9,alpha:0.757},0).wait(1).to({y:44.2,alpha:0.787},0).wait(1).to({y:47.1,alpha:0.814},0).wait(1).to({y:49.7,alpha:0.837},0).wait(1).to({y:52,alpha:0.858},0).wait(1).to({y:54.1,alpha:0.877},0).wait(1).to({y:55.9,alpha:0.894},0).wait(1).to({y:57.6,alpha:0.909},0).wait(1).to({y:59.1,alpha:0.922},0).wait(1).to({y:60.4,alpha:0.934},0).wait(1).to({y:61.5,alpha:0.945},0).wait(1).to({y:62.6,alpha:0.954},0).wait(1).to({y:63.5,alpha:0.963},0).wait(1).to({y:64.3,alpha:0.97},0).wait(1).to({y:65,alpha:0.976},0).wait(1).to({y:65.6,alpha:0.982},0).wait(1).to({y:66.1,alpha:0.986},0).wait(1).to({y:66.5,alpha:0.99},0).wait(1).to({y:66.9,alpha:0.993},0).wait(1).to({y:67.1,alpha:0.996},0).wait(1).to({y:67.3,alpha:0.998},0).wait(1).to({y:67.5,alpha:0.999},0).wait(1).to({y:67.6,alpha:1},0).wait(104).to({y:67.5},0).wait(1).to({y:67.3},0).wait(1).to({y:67},0).wait(1).to({y:66.5},0).wait(1).to({y:65.8},0).wait(1).to({y:64.8},0).wait(1).to({y:63.7},0).wait(1).to({y:62.2},0).wait(1).to({y:60.4},0).wait(1).to({y:58.1},0).wait(1).to({y:55.3},0).wait(1).to({y:51.9},0).wait(1).to({y:47.5},0).wait(1).to({y:41.9},0).wait(1).to({y:34.3},0).wait(1).to({y:23.4},0).wait(1).to({y:5.6},0).wait(1).to({y:-22.6},0).wait(1).to({y:-45.1},0).wait(1).to({y:-58.1},0).wait(1).to({y:-66.7},0).wait(1).to({y:-72.8},0).wait(1).to({y:-77.4},0).wait(1).to({y:-81},0).wait(1).to({y:-83.8},0).wait(1).to({y:-86},0).wait(1).to({y:-87.8},0).wait(1).to({y:-89.2},0).wait(1).to({y:-90.3},0).wait(1).to({y:-91.1},0).wait(1).to({y:-91.7},0).wait(1).to({y:-92.1},0).wait(1).to({y:-92.3},0).wait(1).to({y:-92.4},0).wait(68).to({scaleX:1.46,scaleY:1.46,y:-92.5},0).wait(1).to({scaleX:1.46,scaleY:1.46,y:-92.7},0).wait(1).to({scaleX:1.47,scaleY:1.47,y:-92.9},0).wait(1).to({scaleX:1.47,scaleY:1.47,y:-93.2},0).wait(1).to({scaleX:1.48,scaleY:1.48,y:-93.6},0).wait(1).to({scaleX:1.49,scaleY:1.49,y:-94},0).wait(1).to({scaleX:1.5,scaleY:1.5,y:-94.6},0).wait(1).to({scaleX:1.51,scaleY:1.51,y:-95.3},0).wait(1).to({scaleX:1.52,scaleY:1.52,y:-96.1},0).wait(1).to({scaleX:1.54,scaleY:1.54,y:-97.1},0).wait(1).to({scaleX:1.56,scaleY:1.56,y:-98.2},0).wait(1).to({scaleX:1.58,scaleY:1.58,y:-99.5},0).wait(1).to({scaleX:1.61,scaleY:1.61,y:-101},0).wait(1).to({scaleX:1.64,scaleY:1.64,y:-102.9},0).wait(1).to({scaleX:1.68,scaleY:1.68,y:-104.9},0).wait(1).to({scaleX:1.72,scaleY:1.72,y:-107.4},0).wait(1).to({scaleX:1.78,scaleY:1.78,y:-110.4},0).wait(1).to({scaleX:1.84,scaleY:1.84,y:-114.1},0).wait(1).to({scaleX:1.92,scaleY:1.92,y:-118.6},0).wait(1).to({scaleX:2.02,scaleY:2.02,x:484.9,y:-124.5},0).wait(1).to({scaleX:2.16,scaleY:2.16,y:-132.4},0).wait(1).to({scaleX:2.37,scaleY:2.37,y:-144.1},0).wait(1).to({scaleX:2.66,scaleY:2.66,y:-161.1},0).wait(1).to({scaleX:2.96,scaleY:2.96,y:-177.9},0).wait(1).to({scaleX:3.16,scaleY:3.16,y:-189.2},0).wait(1).to({scaleX:3.29,scaleY:3.29,y:-196.8},0).wait(1).to({scaleX:3.39,scaleY:3.39,y:-202.4},0).wait(1).to({scaleX:3.46,scaleY:3.46,y:-206.7},0).wait(1).to({scaleX:3.52,scaleY:3.52,x:484.8,y:-210.1},0).wait(1).to({scaleX:3.57,scaleY:3.57,x:484.9,y:-212.9},0).wait(1).to({scaleX:3.61,scaleY:3.61,x:484.8,y:-215.3},0).wait(1).to({scaleX:3.65,scaleY:3.65,x:484.9,y:-217.2},0).wait(1).to({scaleX:3.68,scaleY:3.68,y:-218.8},0).wait(1).to({scaleX:3.7,scaleY:3.7,y:-220.2},0).wait(1).to({scaleX:3.72,scaleY:3.72,y:-221.3},0).wait(1).to({scaleX:3.74,scaleY:3.74,x:484.8,y:-222.3},0).wait(1).to({scaleX:3.75,scaleY:3.75,y:-223.2},0).wait(1).to({scaleX:3.76,scaleY:3.76,x:484.9,y:-223.8},0).wait(1).to({scaleX:3.77,scaleY:3.77,x:484.8,y:-224.4},0).wait(1).to({scaleX:3.78,scaleY:3.78,y:-224.8},0).wait(1).to({scaleX:3.79,scaleY:3.79,y:-225.2},0).wait(1).to({scaleX:3.79,scaleY:3.79,x:484.9,y:-225.4},0).wait(1).to({scaleX:3.8,scaleY:3.8,y:-225.6},0).wait(1).to({scaleX:3.8,scaleY:3.8,y:-225.7},0).wait(1).to({regX:115.6,regY:115.4,x:485.1,y:-225.8},0).wait(34));

	// bg
	this.instance_7 = new lib.Symbol4();
	this.instance_7.parent = this;
	this.instance_7.setTransform(485,125,1,1,0,0,0,485,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(327));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(485,-85.9,970,461);
// library properties:
lib.properties = {
	id: '56C55D65B0334AFAB2334CB62EE25078',
	width: 970,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/970x250_change_atlas_.png", id:"970x250_change_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['56C55D65B0334AFAB2334CB62EE25078'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;