(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"160x600_aaoo_boy_atlas_", frames: [[0,0,160,600]]}
];


// symbols:



(lib.bb_boy = function() {
	this.initialize(ss["160x600_aaoo_boy_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#51C4ED").s().p("AgOCEIgUgEIgSgGIgRgJIgPgLIgRgSIgLgPIgJgSIgGgSIgEgUIAAgbIAEgTIAGgTIAJgRIAOgUIAOgMIAPgLIARgJIANgFIAZgEIATgBIAhAFIAYAKIAGAEIAQALIANAMIAQAUIAJARIAIAZIACAUIAAANIgCAUIgIAZIgDAGIgKARIgQAUIgOAMIgWANIgMAFIgTAGIgaACg");
	this.shape.setTransform(13.2,13.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol6, new cjs.Rectangle(0,0,26.4,26.4), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#51C4ED").s().p("AgIAqIAAhDIgVAAIAAgQIA7AAIAAAQIgVAAIAABDg");
	this.shape.setTransform(187.525,425.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#51C4ED").s().p("AgdAfIAKgNQAMAKAJAAQAEAAADgDQAEgCAAgEQAAgDgEgDQgDgCgHgEQgNgFgFgDQgHgGAAgKIAAgBQABgKAHgIQAIgGALAAQAQAAAMAKIgLANQgJgHgIgBQgDABgDACQgDACAAADQAAADADADQADADAJAEQAMAEAFAFQAGAGAAAIIAAABQgBALgHAIQgIAGgMAAQgSAAgNgMg");
	this.shape_1.setTransform(180.8,425.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#51C4ED").s().p("AgIAqIAAhTIARAAIAABTg");
	this.shape_2.setTransform(175.875,425.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#51C4ED").s().p("AAMAqIgPgcIgKAAIAAAcIgSAAIAAhTIAfAAQAOAAAJAIQAHAHAAANIAAAAQAAARgQAHIASAfgAgNAAIAMAAQAGAAAEgDQADgEAAgFQAAgNgNAAIgMAAg");
	this.shape_3.setTransform(170.625,425.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#51C4ED").s().p("AgIAqIAAhDIgVAAIAAgQIA7AAIAAAQIgVAAIAABDg");
	this.shape_4.setTransform(163.325,425.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#51C4ED").s().p("AgaAqIAAhTIA1AAIAAAQIgkAAIAAASIAfAAIAAAOIgfAAIAAATIAkAAIAAAQg");
	this.shape_5.setTransform(156.775,425.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#51C4ED").s().p("AAUAqIAAg1IgUAiIAAAAIgTgiIAAA1IgRAAIAAhTIASAAIASAiIATgiIASAAIAABTg");
	this.shape_6.setTransform(148.675,425.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#51C4ED").s().p("AgbAgQgKgNAAgSIAAgBQAAgSAKgNQAMgLAPAAQARAAAKALQALANAAASIAAABQAAASgLANQgLALgQAAQgQAAgLgLgAgNgTQgGAHAAAMIAAABQAAALAGAIQAFAIAIAAQAJAAAGgIQAFgHAAgMIAAgBQAAgLgGgIQgFgIgJAAQgIAAgFAIg");
	this.shape_7.setTransform(139.85,425.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#51C4ED").s().p("AgIAqIAAhDIgVAAIAAgQIA7AAIAAAQIgVAAIAABDg");
	this.shape_8.setTransform(132.225,425.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#51C4ED").s().p("AgcAqIAAhTIAcAAQANAAAIAIQAIAHAAAOQAAANgJAIQgIAHgNAAIgKAAIAAAagAgLABIAKAAQAFAAAEgDQAEgEAAgGQAAgNgNAAIgKAAg");
	this.shape_9.setTransform(125.675,425.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#51C4ED").s().p("AgbAgQgKgNAAgSIAAgBQAAgSAKgNQALgLAQAAQAQAAALALQALANAAASIAAABQAAASgLANQgLALgQAAQgQAAgLgLgAgNgTQgGAHAAAMIAAABQAAALAGAIQAFAIAIAAQAJAAAGgIQAFgHAAgMIAAgBQAAgLgGgIQgGgIgIAAQgIAAgFAIg");
	this.shape_10.setTransform(117.6,425.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#51C4ED").s().p("AARAqIgfgxIAAAxIgRAAIAAhTIAQAAIAeAwIAAgwIARAAIAABTg");
	this.shape_11.setTransform(106.55,425.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#51C4ED").s().p("AAVAqIgHgSIgcAAIgGASIgSAAIAehTIAQAAIAfBTgAAJAJIgJgbIgJAbIASAAg");
	this.shape_12.setTransform(98.45,425.675);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#51C4ED").s().p("AghAqIAAhTIAbAAQASAAALALQAKAMABASIAAABQgBASgKAMQgLALgSAAgAgPAaIAJAAQAKAAAFgGQAHgIAAgLIAAgBQAAgLgHgIQgFgGgKAAIgJAAg");
	this.shape_13.setTransform(87.9,425.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#51C4ED").s().p("AARAqIgfgxIAAAxIgRAAIAAhTIAQAAIAeAwIAAgwIARAAIAABTg");
	this.shape_14.setTransform(79.65,425.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#51C4ED").s().p("AgIAqIAAhTIARAAIAABTg");
	this.shape_15.setTransform(73.825,425.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#51C4ED").s().p("AgaAqIAAhTIA1AAIAAAQIgkAAIAAATIAgAAIAAAPIggAAIAAAhg");
	this.shape_16.setTransform(69,425.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgEANIgFgDIgDgFIgBgFIABgFIADgEIAFgDIAEgBIAGABIAEADIADAEIABAFIgBAFIgDAFIgEADIgGABg");
	this.shape_17.setTransform(168.325,389.325);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAwA5IAAgTIAPAAIAAgyQAAgMgGgHQgHgHgMAAQgHAAgIAEQgHADgFAGIAAA/IAPAAIAAATIgzAAIAAgTIAPAAIAAgyQABgMgHgHQgGgHgMAAQgHAAgIAEQgGADgHAFIAABAIAPAAIAAATIgzAAIAAgTIAPAAIAAhJIgPAAIAAgTIAjAAIAAANIABAAIAHgFIAIgFIAKgDIAJgCQAMAAAKAFQAHAEAFAKIAIgHIAKgGIAKgEQAFgCAGAAQAJAAAHADQAHACAGAFQAEAFAEAIQACAIAAALIAAA0IAQAAIAAATg");
	this.shape_18.setTransform(154.9,384.925);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgbA4QgHgDgFgEQgFgFgDgGQgCgFAAgHQAAgHABgGQACgFAFgEQACgEAGgBIAJgFIALgCIAKgBIALABIALABIAAgJQgBgGgCgFQgBgEgDgDQgEgDgEgBQgEgCgEAAIgKABIgIACIgIADIgGACIgGgNIAJgFIAKgEIAKgDIAKgBQAJAAAIADQAIADAFAEQAFAFADAIQAEAHAAALIgBA2IAMAAIAAATIggAAIAAgLQgGAGgIAEQgGAEgLgBQgIAAgGgCgAgOAGIgIAEQgEACgCAEQgCAEAAAEQAAAFABADIAFAFIAHAEIAJABIAIgBIAGgDIAHgDIAFgFIABgaIgXAAQgGAAgEACg");
	this.shape_19.setTransform(137.7,385.05);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAQA4IAAgTIAHAAIgXgbIgUAbIAFAAIAAATIglAAIAAgTIAJAAIAigmIgggjIgLAAIAAgTIAlAAIAAATIgEAAIATAaIAVgaIgFAAIAAgTIAlAAIAAATIgKAAIggAkIAiAlIAIAAIAAATg");
	this.shape_20.setTransform(126.05,385.025);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgRA3QgLgEgGgHQgIgIgDgLQgEgLAAgOQAAgLADgLQAEgKAGgJQAHgHAJgFQAKgFAMAAQANAAAIAEQAJAEAFAHQAGAFACAIQADAIABAJIAAAIIABAHIhQAAIABAJIADAIQADALAJAFQAJAFAKAAQAIAAAJgCQAIgDAJgFIAIAOQgLAIgLADQgLAEgMgBQgKABgJgEgAAdgMIgCgMQgCgFgEgEQgCgEgGgCQgEgCgIAAQgGAAgFACQgFACgEAEQgEADgCAGIgEAMIA6AAg");
	this.shape_21.setTransform(113.6,385.05);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgSA3QgJgEgIgHQgGgIgEgLQgEgLAAgOQAAgLADgLQADgKAHgJQAHgHAJgFQALgFAMAAQAMAAAIAEQAJAEAFAHQAFAFADAIQADAIABAJIABAIIAAAHIhPAAIAAAJIACAIQAFALAIAFQAJAFAKAAQAJAAAIgCQAIgDAJgFIAIAOQgLAIgLADQgLAEgMgBQgKABgKgEgAAdgMIgDgMQgBgFgDgEQgDgEgFgCQgFgCgIAAQgGAAgFACQgGACgDAEQgEADgCAGIgEAMIA6AAg");
	this.shape_22.setTransform(96.2,385.05);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgiBRIAAgSIANAAIAMgfIglhdIgJAAIAAgTIAqAAIAAATIgNAAIAaBGIAahGIgNAAIAAgTIArAAIAAATIgMAAIgwB8IAOAAIAAASg");
	this.shape_23.setTransform(83.525,387.55);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgSA3QgJgEgIgHQgGgIgEgLQgEgLAAgOQAAgLADgLQADgKAHgJQAHgHAJgFQALgFAMAAQAMAAAIAEQAJAEAFAHQAFAFADAIQADAIABAJIABAIIAAAHIhQAAIABAJIACAIQAFALAIAFQAJAFAKAAQAJAAAIgCQAIgDAJgFIAIAOQgLAIgLADQgLAEgMgBQgKABgKgEgAAdgMIgDgMQgBgFgDgEQgDgEgFgCQgFgCgIAAQgGAAgFACQgGACgDAEQgEADgCAGIgEAMIA6AAg");
	this.shape_24.setTransform(71,385.05);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AALA5IAAgTIAPAAIAAgyQAAgMgGgHQgHgHgMAAQgGAAgHAEQgHADgGAFIAABAIAPAAIAAATIg0AAIAAgTIAQAAIAAhJIgQAAIAAgTIAkAAIAAAOIAAAAIAIgGIAIgFIAJgDIAJgCQAJAAAIADQAHACAFAFQAFAFADAIQACAIAAALIAAA0IAQAAIAAATg");
	this.shape_25.setTransform(143.425,360.325);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgbA4QgHgCgFgFQgFgFgCgFQgEgHAAgGQAAgHACgGQADgFADgEQAEgEAEgCIAKgEIAKgDIAKAAIANAAIAKACIAAgJQAAgHgCgEQgCgEgDgDQgEgDgEgBQgEgBgFgBIgJABIgJACIgHADIgGADIgGgPIAIgEIAKgEIALgDIAKAAQAJAAAIACQAHACAGAFQAGAFADAHQACAIAAAKIAAA3IAMAAIAAATIggAAIAAgLQgGAGgIAEQgHADgKAAQgHAAgHgCgAgPAGIgIAEQgEACgBAEQgCADAAAFQAAAEACAEIAEAGIAHADIAJABIAIgBIAHgCIAGgFIAFgEIABgaIgXAAQgGABgFABg");
	this.shape_26.setTransform(129.9,360.45);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgaBRQgKgEgHgIQgHgHgEgLQgEgLAAgOQAAgNAEgLQADgKAIgHQAHgHAKgFQAKgEAMAAQAHAAAHACQAHACAFAEIAAgqIgPAAIAAgTIAjAAIAACUIARAAIAAASIglAAIAAgJQgFAGgHADQgHADgIAAQgLAAgKgEgAgQgKQgHACgFAFQgEAEgCAIQgEAHAAAJQAAALADAHQADAIAEAGQAFAFAHADQAGACAHAAQAIAAAHgCQAFgDAFgFIAAg+QgFgEgHgCQgHgCgGAAQgHAAgGADg");
	this.shape_27.setTransform(112.6,357.775);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgZBUIAAgTIAQAAIAAiBIgQAAIAAgTIAjAAIAACUIAQAAIAAATg");
	this.shape_28.setTransform(102.175,357.65);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgZBSIAAgSIAQAAIAAhKIgQAAIAAgSIAjAAIAABcIARAAIAAASgAgFg2IgEgDIgDgFIgCgFIACgGIADgEIAEgDIAFgBIAFABIAFADIACAEIABAGIgBAFIgCAFIgFADIgFABg");
	this.shape_29.setTransform(95.15,357.775);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAKBUIAAgTIAQAAIAAgzQAAgMgHgGQgGgHgMAAQgGAAgHADQgHAEgHAEIAABBIAQAAIAAATIg1AAIAAgTIARAAIAAiBIgPAAIAAgTIAjAAIAABFIABAAIAHgGIAIgEIAJgEIAJgBQAJAAAHACQAHADAFAFQAFAFADAIQACAHAAALIAAA1IARAAIAAATg");
	this.shape_30.setTransform(84.4,357.65);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgSA3QgKgFgHgHQgHgJgEgKQgEgLAAgNQAAgLAEgMQAFgKAHgIQAHgIAKgEQAKgFAKAAQAKAAAKAEQAJAEAHAHIAMAAIAAASIgVAAQgEgHgHgEQgHgEgJAAQgGAAgGADQgGADgFAFQgFAGgCAHQgDAIAAAIQAAAKADAHQACAHAFAGQAFAFAGADQAGADAGAAQAKAAAIgFQAHgFAFgKIAQAIQgDAHgEAGQgFAFgGAEQgGAEgHACQgHACgIAAQgLAAgKgEg");
	this.shape_31.setTransform(71.075,360.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgnA4IAAgSIAPAAIAAhKIgPAAIAAgTIAkAAIAAAQIADgHIAFgEIAHgEIAIgBIAKAAIAKAAIAAAYIgUAAIAAgHIgIACQgDABgEADQgDADgCAEQgCAEgBAGIAAA1IASAAIAAASg");
	this.shape_32.setTransform(169.725,335.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgWA2QgHgCgFgFQgFgFgCgIQgDgIAAgLIAAg0IgPAAIAAgTIAkAAIAABFQAAANAGAGQAGAHALAAQAGAAAHgDQAHgCAGgEIAAhDIgOAAIAAgTIAjAAIAABcIANAAIAAATIghAAIAAgLQgHAGgJADQgJAEgJAAQgIAAgHgDg");
	this.shape_33.setTransform(156.775,335.925);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgVA2QgLgEgHgHQgHgJgEgKQgEgLgBgNQABgMAEgLQAEgLAHgIQAIgIAKgEQAKgEALAAQANAAAKAEQAKAEAIAIQAHAIAEAKQAEALAAANQAAAMgEAMQgEAKgHAJQgIAHgKAEQgKAFgNAAQgLAAgKgFgAgMgmQgGADgFAFQgFAFgDAIQgCAIAAAJQAAAJACAIQADAIAFAGQAFAEAGADQAGAEAGAAQAIAAAGgEQAHgCAEgFQAFgGADgIQACgHAAgKQAAgJgCgIQgDgIgFgFQgEgFgHgDQgGgDgIAAQgGAAgGADg");
	this.shape_34.setTransform(143.475,335.85);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgiBRIAAgSIANAAIAMgfIglhdIgJAAIAAgTIAqAAIAAATIgNAAIAaBGIAahGIgNAAIAAgTIArAAIAAATIgMAAIgwB8IAOAAIAAASg");
	this.shape_35.setTransform(130.325,338.35);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAmBTIgtgxIgOAAIAAAfIAJAAIAAASIgwAAIAAgSIATAAIAAiBIgTAAIAAgSIAnAAIAAASIAABSIATAAIAZgaIgGAAIAAgTIAqAAIAAATIgOAAIgiAiIAlAnIANAAIAAASg");
	this.shape_36.setTransform(112.925,333.05);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgVA2QgLgEgHgHQgHgJgEgKQgEgLgBgNQABgMAEgLQAEgLAHgIQAIgIAKgEQAKgEALAAQANAAAKAEQAKAEAIAIQAHAIAEAKQAEALAAANQAAAMgEAMQgEAKgHAJQgIAHgKAEQgKAFgNAAQgLAAgKgFgAgMgmQgGADgFAFQgFAFgDAIQgCAIAAAJQAAAJACAIQADAIAFAGQAFAEAGADQAGAEAGAAQAIAAAGgEQAHgCAEgFQAFgGADgIQACgHAAgKQAAgJgCgIQgDgIgFgFQgEgFgHgDQgGgDgIAAQgGAAgGADg");
	this.shape_37.setTransform(99.125,335.85);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgVA2QgLgEgHgHQgHgJgEgKQgEgLgBgNQABgMAEgLQAEgLAHgIQAIgIAKgEQAKgEALAAQANAAAKAEQAKAEAIAIQAHAIAEAKQAEALAAANQAAAMgEAMQgEAKgHAJQgIAHgKAEQgKAFgNAAQgLAAgKgFgAgMgmQgGADgFAFQgFAFgDAIQgCAIAAAJQAAAJACAIQADAIAFAGQAFAEAGADQAGAEAGAAQAIAAAGgEQAHgCAEgFQAFgGADgIQACgHAAgKQAAgJgCgIQgDgIgFgFQgEgFgHgDQgGgDgIAAQgGAAgGADg");
	this.shape_38.setTransform(85.975,335.85);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("Ag8BRIAAgSIAQAAIAAh9IgQAAIAAgTIBIAAQAKAAAJAFQAJADAGAHQAHAGADAIQAEAJAAAKQAAALgGAJQgGAIgKAFIAJAGIAHAIIAFAJIACAKQAAAKgEAJQgEAJgGAHQgGAGgJAEQgJADgKAAgAgXA/IAlAAQAFAAAEgDQAFgCADgEQADgFACgFIACgKIgCgKQgCgEgDgEQgDgDgFgCQgEgCgFAAIglAAgAgXgJIAkAAQAFAAAEgBQAFgDADgDQADgEACgEQACgEAAgGQAAgEgCgGQgCgFgDgEQgDgEgFgCQgEgDgFAAIgkAAg");
	this.shape_39.setTransform(72.625,333.25);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("ArtCqIAAlTIXbAAIAAFTg");
	this.shape_40.setTransform(126,426.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(51,318.3,170.3,125), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEANIgFgDIgDgFIgBgFIABgFIADgEIAFgDIAEgBIAGABIAEADIADAEIABAFIgBAFIgDAFIgEADIgGABg");
	this.shape.setTransform(114.425,392.675);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgnA4IAAgSIAPAAIAAhKIgPAAIAAgTIAkAAIAAAQIADgHIAFgEIAHgEIAIgBIAKAAIAKAAIAAAYIgUAAIAAgHIgIACQgDABgEADQgDADgCAEQgCAEgBAGIAAA1IASAAIAAASg");
	this.shape_1.setTransform(106.775,388.35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgbA4QgHgDgFgEQgFgEgDgHQgDgFAAgHQABgHABgFQADgGAEgEQACgEAGgBIAJgFIAKgDIAKAAIANAAIAKABIAAgJQAAgFgDgFQgBgEgDgDQgEgDgEgBQgEgBgFAAIgJAAIgIACIgIACIgGADIgGgNIAJgFIAKgEIAKgCIAKgBQAJAAAIACQAHADAGAEQAGAFADAIQADAHAAAKIgBA3IAMAAIAAASIggAAIAAgKQgGAGgIAEQgGAEgLAAQgHAAgHgDgAgOAGIgIADQgEADgCAEQgCAEAAAEQAAAFABADIAFAFIAHAEIAJABIAIgBIAGgDIAHgDIAFgFIABgZIgXAAQgGAAgEABg");
	this.shape_2.setTransform(95.5,388.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgRA3QgLgEgGgHQgIgIgDgLQgEgLAAgOQAAgLADgLQADgLAHgIQAHgHAKgFQAJgFAMABQANAAAIADQAJAEAFAGQAGAHACAIQADAHABAJIAAAIIABAHIhQAAIACAJIACAHQADAMAJAFQAJAFAKAAQAJAAAIgCQAIgDAJgFIAIAOQgLAHgLAEQgLAEgMAAQgKAAgJgEgAAcgMIgBgMQgCgFgEgEQgCgDgGgDQgEgCgIAAQgGAAgFACQgGACgDAEQgEADgCAGIgDAMIA4AAg");
	this.shape_3.setTransform(83.1,388.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgiBRIAAgSIANAAIAMgfIglhdIgJAAIAAgTIAqAAIAAATIgNAAIAaBGIAahGIgNAAIAAgTIArAAIAAATIgMAAIgwB8IAOAAIAAASg");
	this.shape_4.setTransform(70.425,390.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZBUIAAgTIAQAAIAAiBIgQAAIAAgTIAjAAIAACUIAQAAIAAATg");
	this.shape_5.setTransform(176.725,361);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgVA3QgLgFgHgIQgHgHgEgLQgEgLgBgNQABgNAEgKQAEgLAHgIQAIgIAKgEQAKgEALAAQANAAAKAEQAKAEAIAIQAHAHAEAMQAEALAAAMQAAAMgEALQgEAMgHAHQgIAIgKAFQgKAEgNAAQgLAAgKgEgAgMgmQgGACgFAGQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAFQAFAFAGADQAGADAGAAQAIAAAGgDQAHgCAEgGQAFgFADgHQACgJAAgJQAAgJgCgIQgDgIgFgFQgEgGgHgCQgGgDgIAAQgGAAgGADg");
	this.shape_6.setTransform(166.425,363.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgVA3QgLgFgHgIQgHgHgEgLQgEgLgBgNQABgNAEgKQAEgLAHgIQAIgIAKgEQAKgEALAAQANAAAKAEQAKAEAIAIQAHAHAEAMQAEALAAAMQAAAMgEALQgEAMgHAHQgIAIgKAFQgKAEgNAAQgLAAgKgEgAgMgmQgGACgFAGQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAFQAFAFAGADQAGADAGAAQAIAAAGgDQAHgCAEgGQAFgFADgHQACgJAAgJQAAgJgCgIQgDgIgFgFQgEgGgHgCQgGgDgIAAQgGAAgGADg");
	this.shape_7.setTransform(153.275,363.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AALBUIAAgTIAPAAIAAgzQAAgNgGgFQgHgHgMAAQgGAAgHAEQgIADgFAEIAABBIAQAAIAAATIg1AAIAAgTIARAAIAAiBIgQAAIAAgTIAkAAIAABFIAAAAIAHgGIAJgEIAIgEIAJgBQAJAAAHADQAHACAFAFQAGAFACAIQACAHABALIAAA1IARAAIAAATg");
	this.shape_8.setTransform(139.7,361);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgSA3QgKgFgHgHQgHgJgEgKQgEgLAAgNQAAgMAEgKQAFgLAHgIQAHgIAKgFQAKgEAKAAQAKAAAKAEQAJADAHAIIAMAAIAAASIgVAAQgEgHgHgFQgHgDgJAAQgGAAgGADQgGADgFAFQgFAGgCAHQgDAHAAAJQAAAJADAIQACAIAFAFQAFAFAGADQAGADAGAAQAKAAAIgFQAHgFAFgKIAQAIQgDAHgEAGQgFAFgGAEQgGAEgHACQgHACgIAAQgLAAgKgEg");
	this.shape_9.setTransform(126.375,363.75);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgUA3QgHgFgFgGIgLAAIAAgTIAWAAQAAAFACADQACADADACIAIADIAHABIAIgBIAHgDQADgBACgEQABgDAAgDQABgFgEgEQgDgDgJgEIgUgIQgNgEgHgGQgGgIAAgKQAAgIADgGQACgFAFgFQAGgEAHgDQAHgCAJAAQALAAAIADQAIADAGAJIALAAIAAASIgWAAQAAgFgCgDQgCgDgEgCIgHgDIgHgBIgHABIgHADIgEAFIgCAGQAAAFAEAEQAEADAHACIAUAIQAOAFAHAGQAGAJAAALQAAAHgDAGQgDAGgFAEQgGAFgHACQgIADgJAAQgMAAgJgEg");
	this.shape_10.setTransform(114.95,363.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgTA3QgJgFgEgGIgLAAIAAgTIAWAAQAAAFACADQACADADACIAIADIAHABIAIgBIAHgDQADgBABgEQACgDABgDQAAgFgEgEQgEgDgIgEIgUgIQgNgEgHgGQgGgIAAgKQAAgIADgGQADgFAFgFQAFgEAGgDQAIgCAJAAQALAAAIADQAIADAHAJIAKAAIAAASIgWAAQAAgFgCgDQgCgDgDgCIgIgDIgHgBIgIABIgGADIgEAFIgBAGQgBAFAEAEQAEADAHACIAVAIQAOAFAFAGQAHAJAAALQAAAHgDAGQgDAGgFAEQgFAFgIACQgIADgKAAQgMAAgHgEg");
	this.shape_11.setTransform(99.5,363.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgaBSIAAgSIAQAAIAAhKIgQAAIAAgSIAjAAIAABcIARAAIAAASgAgEg2IgFgDIgDgFIgBgFIABgGIADgEIAFgDIAEgBIAFABIAEADIAEAEIABAGIgBAFIgEAFIgEADIgFABg");
	this.shape_12.setTransform(90.8,361.125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAKBUIAAgTIAQAAIAAgzQAAgNgHgFQgGgHgMAAQgGAAgHAEQgIADgFAEIAABBIAQAAIAAATIg1AAIAAgTIARAAIAAiBIgQAAIAAgTIAkAAIAABFIAAAAIAHgGIAJgEIAIgEIAJgBQAJAAAHADQAHACAFAFQAGAFACAIQADAHgBALIAAA1IASAAIAAATg");
	this.shape_13.setTransform(80.05,361);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAABJQgGgCgDgEQgFgEgBgHQgCgHAAgLIAAg8IgRAAIAAgQIASAAIAAgbIASgJIAAAkIAaAAIAAAQIgaAAIAAA/QgBAHACAEQACAEADACQADABAEAAIAIAAIAIgDIAFANIgMAEQgFACgIAAQgHAAgEgCg");
	this.shape_14.setTransform(68.6,362.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgUA2QgIgDgEgIIgLAAIAAgSIAWAAQAAAEACAEQACADAEADIAHADIAHAAIAIAAIAHgDQADgDACgDQACgDAAgDQgBgFgDgEQgDgEgJgDIgUgHQgNgFgGgHQgHgGAAgMQAAgHADgGQADgFAFgFQAEgEAHgDQAIgCAJAAQALAAAIADQAIAEAHAHIAKAAIAAATIgWAAQAAgEgCgDQgCgEgDgCIgIgCIgHgBIgIABIgGACIgEAFIgCAFQABAGADADQADADAJAEIAUAHQAOAFAFAGQAHAJAAAKQAAAIgDAGQgDAHgFAEQgFAEgJADQgHACgKAAQgLAAgJgFg");
	this.shape_15.setTransform(178.45,339.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgTA2QgJgDgEgIIgLAAIAAgSIAWAAQAAAEACAEQACADADADIAIADIAHAAIAIAAIAHgDQADgDABgDQACgDAAgDQAAgFgDgEQgEgEgIgDIgUgHQgNgFgHgHQgGgGAAgMQAAgHADgGQADgFAFgFQAEgEAIgDQAHgCAJAAQALAAAIADQAIAEAHAHIAKAAIAAATIgWAAQAAgEgCgDQgCgEgDgCIgIgCIgHgBIgIABIgGACIgEAFIgBAFQgBAGAEADQAEADAHAEIAVAHQANAFAHAGQAGAJAAAKQAAAIgDAGQgDAHgFAEQgGAEgHADQgIACgKAAQgMAAgHgFg");
	this.shape_16.setTransform(167.8,339.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgRA3QgLgEgGgIQgIgGgDgMQgEgLAAgOQAAgMADgKQAEgKAGgIQAHgJAJgEQAKgEAMAAQANAAAIADQAJAEAFAGQAGAGACAIQADAJABAIIAAAJIABAHIhQAAIABAIIADAHQADALAJAGQAJAFAKAAQAIAAAJgCQAIgCAJgGIAIAOQgLAHgLAEQgLADgMABQgKgBgJgDgAAdgMIgCgLQgCgGgEgEQgCgDgGgDQgEgCgIAAQgGAAgFACQgFACgEAEQgEADgCAGIgEAMIA6AAg");
	this.shape_17.setTransform(155.9,339.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgSA3QgKgFgHgHQgHgIgEgLQgEgLAAgNQAAgMAEgLQAFgLAHgHQAHgIAKgEQAKgFAKAAQAKAAAKAEQAJADAHAIIAMAAIAAATIgVAAQgEgJgHgDQgHgEgJAAQgGAAgGADQgGADgFAFQgFAFgCAIQgDAIAAAIQAAAKADAHQACAHAFAGQAFAFAGADQAGADAGAAQAKAAAIgFQAHgFAFgKIAQAIQgDAHgEAFQgFAGgGAEQgGAEgHACQgHACgIAAQgLAAgKgEg");
	this.shape_18.setTransform(143.975,339.15);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgSA3QgKgFgHgHQgHgIgEgLQgEgLAAgNQAAgMAEgLQAFgLAHgHQAHgIAKgEQAKgFAKAAQAKAAAKAEQAJADAHAIIAMAAIAAATIgVAAQgEgJgHgDQgHgEgJAAQgGAAgGADQgGADgFAFQgFAFgCAIQgDAIAAAIQAAAKADAHQACAHAFAGQAFAFAGADQAGADAGAAQAKAAAIgFQAHgFAFgKIAQAIQgDAHgEAFQgFAGgGAEQgGAEgHACQgHACgIAAQgLAAgKgEg");
	this.shape_19.setTransform(131.975,339.15);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgWA2QgHgCgFgFQgFgFgCgIQgDgIAAgLIAAg0IgPAAIAAgTIAkAAIAABFQAAANAGAGQAGAHALAAQAGAAAHgDQAHgCAGgEIAAhDIgOAAIAAgTIAjAAIAABcIANAAIAAATIghAAIAAgLQgHAGgJADQgJAEgJAAQgIAAgHgDg");
	this.shape_20.setTransform(118.025,339.275);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgTA2QgJgDgEgIIgLAAIAAgSIAWAAQAAAEACAEQACADADADIAIADIAHAAIAIAAIAHgDQADgDABgDQACgDAAgDQABgFgEgEQgDgEgJgDIgUgHQgNgFgHgHQgGgGAAgMQAAgHADgGQACgFAGgFQAEgEAIgDQAHgCAJAAQALAAAIADQAIAEAHAHIAKAAIAAATIgWAAQAAgEgCgDQgCgEgEgCIgHgCIgHgBIgHABIgHACIgEAFIgBAFQAAAGADADQAEADAHAEIAVAHQANAFAHAGQAGAJAAAKQAAAIgDAGQgDAHgFAEQgGAEgHADQgIACgJAAQgNAAgHgFg");
	this.shape_21.setTransform(106.05,339.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgnA4IAAgTIAPAAIAAhJIgPAAIAAgSIAkAAIAAAPIADgGIAFgGIAHgDIAIgBIAKAAIAKAAIAAAYIgUAAIAAgGIgIABQgDABgEADQgDADgCAEQgCAEgBAGIAAA0IASAAIAAATg");
	this.shape_22.setTransform(90.725,339.15);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgVA2QgLgEgHgIQgHgIgEgKQgEgLgBgNQABgMAEgLQAEgLAHgIQAIgHAKgFQAKgEALAAQANAAAKAEQAKAFAIAHQAHAIAEALQAEAKAAANQAAAMgEALQgEALgHAIQgIAIgKAEQgKAFgNAAQgLAAgKgFgAgMgmQgGADgFAFQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAGQAFAEAGAEQAGACAGABQAIgBAGgCQAHgDAEgFQAFgGADgIQACgHAAgKQAAgJgCgIQgDgIgFgFQgEgFgHgDQgGgDgIAAQgGAAgGADg");
	this.shape_23.setTransform(78.975,339.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgoBUIAAgTIARAAIAAhLIgSAAIAAgRIASAAIAAgRQAAgKAEgHQACgIAEgEQAGgFAGgDQAGgBAIgBIAKABIAIABIAGACIAFADIgGAOIgJgDIgLgBQgKgBgEAGQgEAFgBALIAAASIAZAAIAAARIgZAAIAABLIARAAIAAATg");
	this.shape_24.setTransform(69.6,336.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("Ag6BSIAAgSIAPAAIAAh8IgPAAIAAgTIAkAAIAAAKQAGgGAJgDQAHgDAJAAQALAAAJAEQAJAEAHAHQAHAIADAKQAEAKAAANQAAANgFAMQgDAKgIAIQgHAHgKAFQgKAEgMAAQgHAAgHgBIgMgFIAAAkIARAAIAAASgAgKg8QgHADgFAFIAAA7QADAEAHADQAGADAJAAQAHAAAGgDQAHgDAEgFQAGgFACgHQADgIAAgKQAAgKgDgHQgDgHgEgFQgEgFgHgDQgGgDgHAAQgHAAgHAEg");
	this.shape_25.setTransform(186.1,316.975);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgWA2QgHgCgFgFQgFgFgCgIQgDgIAAgLIAAg0IgPAAIAAgTIAkAAIAABFQAAANAGAGQAGAHALAAQAGAAAHgDQAHgCAGgEIAAhDIgOAAIAAgTIAjAAIAABcIANAAIAAATIghAAIAAgLQgHAGgJADQgJAEgJAAQgIAAgHgDg");
	this.shape_26.setTransform(171.675,314.675);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAvA5IAAgTIAQAAIAAgyQAAgMgHgHQgGgHgMAAQgHAAgIAEQgHADgFAGIAAA/IAPAAIAAATIgzAAIAAgTIAQAAIAAgyQAAgMgHgHQgGgHgMAAQgIAAgHAEQgGADgHAFIAABAIAQAAIAAATIg0AAIAAgTIAPAAIAAhJIgPAAIAAgTIAjAAIAAANIABAAIAHgFIAJgFIAJgDIAKgCQALAAAJAFQAIAEAFAKIAIgHIAKgGIAKgEIALgCQAJAAAIADQAHACAEAFQAFAFAEAIQACAIAAALIAAA0IAQAAIAAATg");
	this.shape_27.setTransform(149.25,314.475);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgSA3QgKgEgHgHQgGgIgEgLQgEgLAAgOQAAgLADgLQADgLAHgIQAHgHAJgFQALgFAMABQAMAAAJADQAHAEAGAGQAFAHADAIQADAHABAJIABAIIAAAHIhPAAIAAAJIACAHQAFAMAIAFQAJAFAKAAQAJAAAIgCQAIgCAJgGIAIAOQgLAHgLAEQgLAEgMAAQgKAAgKgEgAAcgMIgCgMQgBgFgDgEQgEgDgEgDQgGgCgHAAQgGAAgFACQgGACgDAEQgEADgCAGIgEAMIA5AAg");
	this.shape_28.setTransform(131.65,314.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AALBTIAAgSIAPAAIAAgzQAAgNgGgFQgHgHgMAAQgGAAgHADQgIAEgFAEIAABBIAQAAIAAASIg1AAIAAgSIARAAIAAiBIgQAAIAAgSIAkAAIAABDIAAAAIAHgFIAJgFIAIgDIAJgBQAJAAAHADQAHACAFAFQAGAFACAIQACAHABAKIAAA2IARAAIAAASg");
	this.shape_29.setTransform(118.55,311.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgBBJQgFgCgEgEQgDgEgCgHQgCgHAAgLIAAg8IgRAAIAAgQIASAAIAAgbIASgJIAAAkIAaAAIAAAQIgaAAIAAA/QAAAHABAEQABAEAEACQADABAEAAIAIAAIAIgDIAEANIgLAEQgFACgIAAQgHAAgFgCg");
	this.shape_30.setTransform(107.1,312.925);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgBBJQgFgCgEgEQgEgEgBgHQgCgHAAgLIAAg8IgRAAIAAgQIASAAIAAgbIASgJIAAAkIAaAAIAAAQIgaAAIAAA/QgBAHACAEQACAEADACQADABAEAAIAIAAIAIgDIAFANIgMAEQgFACgIAAQgHAAgFgCg");
	this.shape_31.setTransform(94.15,312.925);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgRA3QgLgEgGgHQgIgIgDgLQgEgLAAgOQAAgLADgLQAEgLAGgIQAHgHAJgFQAKgFAMABQANAAAIADQAJAEAFAGQAGAHACAIQADAHABAJIAAAIIABAHIhQAAIABAJIADAHQADAMAJAFQAJAFAKAAQAIAAAJgCQAIgCAJgGIAIAOQgLAHgLAEQgLAEgMAAQgKAAgJgEgAAdgMIgCgMQgCgFgEgEQgCgDgGgDQgEgCgIAAQgGAAgFACQgFACgEAEQgEADgCAGIgEAMIA6AAg");
	this.shape_32.setTransform(83.45,314.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgTBSQgJgDgGgFQgGgFgDgGQgEgGgCgHIgIAAIAAgSIAbAAQAAAMACAFQADAFAEADQAFADAGACQAGACAHAAQAHAAAGgCQAGgCAEgDQAEgDADgFQACgFAAgGQAAgGgDgFQgDgEgEgEIgJgFIgKgDIgXgHQgIgCgGgDQgGgEgFgFQgFgFgCgHQgCgHAAgKQAAgJADgIQAEgIAHgGQAHgGAKgEQALgDAMAAQAIAAAIACQAHACAGADQAGAEAFAFQAEAFADAHIAIAAIAAASIgaAAQAAgJgDgFQgEgFgEgCIgJgEIgKgBQgHAAgGABQgGACgEADQgEAEgCAEQgCAEAAAFQAAAHACAFIAGAHIAJAEIAJADIAVAHQAJADAIAEQAHADAFAFQAFAGADAHQADAHAAAJQAAAKgEAJQgFAIgHAHQgHAGgLAEQgKADgMAAQgMAAgJgCg");
	this.shape_33.setTransform(71.175,312.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(62.5,297,139.4,104.39999999999998), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bb_boy();
	this.instance.parent = this;
	this.instance.setTransform(71,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(71,0,160,600), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgDALIgEgDIgDgEIAAgEIAAgDIADgEIAEgDIADgBIAFABIADADIACAEIABADIgBAEIgCAEIgDADIgFABg");
	this.shape.setTransform(163.95,213.75);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAIAuIAAgPIANAAIAAgoQAAgLgFgFQgFgGgKAAQgFAAgGADQgGADgFAEIAAA0IANAAIAAAPIgqAAIAAgPIAMAAIAAg8IgMAAIAAgPIAdAAIAAALIAGgFIAHgEIAHgDIAIAAQAHAAAGACQAGACAEAEQAEAEACAGQACAHAAAJIAAAqIANAAIAAAPg");
	this.shape_1.setTransform(155.975,210.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSAtQgIgEgGgGQgGgHgDgIQgEgKAAgKQAAgKAEgJQADgIAGgHQAGgHAJgDQAIgDAJAAQAKAAAJADQAIADAGAHQAGAGADAJQAEAJAAAKQAAAKgEAKQgDAIgGAGQgGAHgIAEQgJADgKAAQgJAAgJgDgAgKgfQgFACgEAFQgEAEgCAHQgCAFAAAIQAAAIACAGQACAHAEAEQAEAEAFADQAFACAFAAQAGAAAFgCQAGgDADgEQAEgEACgHQADgGAAgIQAAgIgDgFQgCgHgEgEQgDgFgGgCQgFgCgGAAQgFAAgFACg");
	this.shape_2.setTransform(144.525,210.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUBDIAAgPIANAAIAAg8IgOAAIAAgPIAdAAIAABLIAOAAIAAAPgAgEgsIgDgDIgDgEIgBgEIABgEIADgEIADgCIAEgBIAEABIAEACIACAEIABAEIgBAEIgCAEIgEADIgEABg");
	this.shape_3.setTransform(136.425,208.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQAtQgGgDgEgGIgJAAIAAgPIASAAQAAAEACACQABADADACIAGACIAGABIAHgBIAFgCIAEgEIABgFQAAgFgCgDQgDgDgHgCIgRgHQgKgDgFgGQgFgFAAgJQAAgGACgFQACgFAEgDIAKgGQAGgCAHAAQAJAAAHADQAGACAGAHIAIAAIAAAPIgSAAQAAgEgCgCQgBgDgDgBIgGgDIgGAAIgGAAIgFADIgDADQgCACAAADQAAAFADACQADADAGACIARAGQALAEAFAGQAGAGAAAJQAAAGgDAFQgCAFgFAEQgEAEgGACQgHABgHAAQgKAAgHgDg");
	this.shape_4.setTransform(129.075,210.225);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgUBDIAAgPIANAAIAAg8IgOAAIAAgPIAdAAIAABLIAOAAIAAAPgAgEgsIgDgDIgDgEIgBgEIABgEIADgEIADgCIAEgBIAEABIAEACIACAEIABAEIgBAEIgCAEIgEADIgEABg");
	this.shape_5.setTransform(121.975,208.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgIAuIgdhMIgHAAIAAgPIAfAAIAAAPIgJAAIAWA+IAWg+IgGAAIAAgPIAdAAIAAAPIgIAAIgdBMg");
	this.shape_6.setTransform(114.075,210.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAIAuIAAgPIANAAIAAgoQAAgLgFgFQgFgGgKAAQgFAAgGADQgGADgFAEIAAA0IANAAIAAAPIgqAAIAAgPIAMAAIAAg8IgMAAIAAgPIAdAAIAAALIAGgFIAHgEIAHgDIAIAAQAHAAAGACQAGACAEAEQAEAEACAGQACAHAAAJIAAAqIANAAIAAAPg");
	this.shape_7.setTransform(99.475,210.175);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgSAtQgIgEgGgGQgGgHgDgIQgEgKAAgKQAAgKAEgJQADgIAGgHQAGgHAJgDQAIgDAJAAQAKAAAJADQAIADAGAHQAGAGADAJQAEAJAAAKQAAAKgEAKQgDAIgGAGQgGAHgIAEQgJADgKAAQgJAAgJgDgAgKgfQgFACgEAFQgEAEgCAHQgCAFAAAIQAAAIACAGQACAHAEAEQAEAEAFADQAFACAFAAQAGAAAFgCQAGgDADgEQAEgEACgHQADgGAAgIQAAgIgDgFQgCgHgEgEQgDgFgGgCQgFgCgGAAQgFAAgFACg");
	this.shape_8.setTransform(88.025,210.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgVBDQgIgEgGgGQgGgHgDgIQgDgKAAgLQAAgKADgJQADgIAGgGQAGgGAIgDQAIgEAKAAQAGAAAFABQAGACAFAEIAAgjIgNAAIAAgQIAdAAIAAB6IANAAIAAAPIgdAAIAAgIQgFAFgGACQgFACgHABQgJAAgIgDgAgNgIQgFACgEAEQgEADgCAGQgCAGAAAIQAAAJACAGQACAGAEAEQAEAFAFACQAFACAGAAQAHAAAFgCQAFgCAEgFIAAgxQgFgEgFgCQgGgBgFAAQgGgBgFADg");
	this.shape_9.setTransform(73.325,208.05);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgOAtQgIgDgGgGQgFgGgDgJQgEgKAAgLQAAgJADgIQACgJAGgHQAFgHAJgDQAHgEAKAAQALAAAGADQAHADAEAGQAFAFACAGIADANIAAAHIABAGIhBAAIABAHIABAGQADAJAIAFQAHAEAIAAQAHAAAHgCIAOgGIAHALQgKAGgJADQgJADgJAAQgIAAgIgDgAAXgKIgBgJQgCgEgCgDIgHgGQgEgBgGAAQgFAAgEABQgEACgDADQgDADgCAEIgDAKIAuAAg");
	this.shape_10.setTransform(62.3,210.25);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgQAtQgGgDgEgGIgJAAIAAgPIASAAQAAAEACACQABADADACIAGACIAGABIAHgBIAFgCIAEgEIABgFQAAgFgCgDQgDgDgHgCIgRgHQgKgDgFgGQgFgFAAgJQAAgGACgFQACgFAEgDIAKgGQAGgCAHAAQAJAAAHADQAGACAGAHIAIAAIAAAPIgSAAQAAgEgCgCQgBgDgDgBIgGgDIgGAAIgGAAIgFADIgDADQgCACAAADQAAAFADACQADADAGACIARAGQALAEAFAGQAGAGAAAJQAAAGgDAFQgCAFgFAEQgEAEgGACQgHABgHAAQgKAAgHgDg");
	this.shape_11.setTransform(53.025,210.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgWAuQgGgCgEgEQgEgEgCgFQgDgEABgGQAAgGABgEQACgFADgDIAGgEIAIgEIAJgCIAIgBIAKABIAIABIAAgIQAAgEgBgEIgEgGQgDgCgDgBIgHgBIgJAAIgHACIgFACIgFACIgFgLIAGgEIAIgDIAJgCIAJgBQAHAAAHACQAFACAFAEQAFAEACAGQACAGAAAJIAAAsIAKAAIAAAPIgaAAIAAgIQgGAFgFADQgGADgIAAQgHAAgFgCgAgMAFIgHADQgDACgBADQgBADAAAEQAAADABADQABADACABIAHADIAHABIAGgBIAFgCIAGgDIAEgEIAAgUIgSAAIgJABg");
	this.shape_12.setTransform(43.65,210.275);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgIBDIgKgFIAAAGIgRAAIAAh5IgMAAIAAgPIAdAAIAAA1QAGgEAGgDQAHgDAHAAQAJAAAIAEQAHADAFAGQAGAGACAIQADAIAAALQABALgEAJQgDAIgGAHQgGAGgIAEQgIADgKAAQgGAAgGgCgAgIgHQgFACgFAFIAAAwQADADAGACQAFACAHAAQAGAAAFgCQAFgCAEgEQAEgFACgGQACgGAAgJQAAgIgCgGQgCgGgDgDQgFgEgEgCQgGgCgGAAQgFAAgGADg");
	this.shape_13.setTransform(33.25,208.025);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgQAtQgGgDgEgGIgJAAIAAgPIASAAQAAAEACACQABADADACIAGACIAGABIAHgBIAFgCIAEgEIABgFQAAgFgCgDQgDgDgHgCIgRgHQgKgDgFgGQgFgFAAgJQAAgGACgFQACgFAEgDIAKgGQAGgCAHAAQAJAAAHADQAGACAGAHIAIAAIAAAPIgSAAQAAgEgCgCQgBgDgDgBIgGgDIgGAAIgGAAIgFADIgDADQgCACAAADQAAAFADACQADADAGACIARAGQALAEAFAGQAGAGAAAJQAAAGgDAFQgCAFgFAEQgEAEgGACQgHABgHAAQgKAAgHgDg");
	this.shape_14.setTransform(139.025,187.475);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgUBDIAAgPIANAAIAAg8IgOAAIAAgPIAdAAIAABLIAOAAIAAAPgAgEgsIgDgDIgDgEIgBgEIABgEIADgEIADgCIAEgBIAEABIAEACIACAEIABAEIgBAEIgCAEIgEADIgEABg");
	this.shape_15.setTransform(131.925,185.325);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgJBCIgKgCIgLgEIgIgGIAIgNIAGAEIAIAEIAIACIAIAAIALgBQAFgBADgEQADgDACgHQACgGAAgJIAAgBQgFAEgGADQgGADgIAAQgHAAgJgDQgHgEgGgGQgHgGgCgJQgEgIAAgMQAAgKAEgJQADgJAFgGQAGgGAIgDQAIgEAJAAQAHAAAGACQAFACAGADIAAgEIAQAAIAABWQAAAWgLALQgJALgWAAgAgHgxQgFACgDAEQgEAEgDAGQgCAGAAAIQAAAJACAGQACAFAEAFQAEAEAFACQAGADAEAAIAIgBIAGgCIAFgDIAEgEIAAgxQgFgEgGgBQgGgCgGAAQgFAAgFACg");
	this.shape_16.setTransform(119.55,189.375);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAIAuIAAgPIANAAIAAgoQAAgLgFgFQgFgGgKAAQgFAAgGADQgGADgFAEIAAA0IANAAIAAAPIgqAAIAAgPIAMAAIAAg8IgMAAIAAgPIAdAAIAAALIAGgFIAHgEIAHgDIAIAAQAHAAAGACQAGACAEAEQAEAEACAGQACAHAAAJIAAAqIANAAIAAAPg");
	this.shape_17.setTransform(108.575,187.425);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgUBDIAAgPIANAAIAAg8IgOAAIAAgPIAdAAIAABLIAOAAIAAAPgAgEgsIgDgDIgDgEIgBgEIABgEIADgEIADgCIAEgBIAEABIAEACIACAEIABAEIgBAEIgCAEIgEADIgEABg");
	this.shape_18.setTransform(99.775,185.325);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAIAuIAAgPIANAAIAAgoQAAgLgFgFQgFgGgKAAQgFAAgGADQgGADgFAEIAAA0IANAAIAAAPIgqAAIAAgPIAMAAIAAg8IgMAAIAAgPIAdAAIAAALIAGgFIAHgEIAHgDIAIAAQAHAAAGACQAGACAEAEQAEAEACAGQACAHAAAJIAAAqIANAAIAAAPg");
	this.shape_19.setTransform(90.825,187.425);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AggAuIAAgPIANAAIAAg8IgNAAIAAgPIAdAAIAAANIADgGIAEgEIAFgDQADgBAEAAIAIAAIAJAAIAAAUIgRAAIAAgFIgGABIgGADQgCACgCAEQgBADgBAFIAAArIAOAAIAAAPg");
	this.shape_20.setTransform(80.575,187.45);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgWAuQgGgCgEgEQgEgEgCgFQgCgEAAgGQAAgGACgEQABgFADgDIAGgEIAIgEIAJgCIAJgBIAJABIAIABIAAgIQAAgEgBgEIgFgGQgCgCgDgBIgHgBIgIAAIgIACIgGACIgEACIgGgLIAHgEIAIgDIAJgCIAJgBQAHAAAHACQAGACAEAEQAFAEACAGQACAGABAJIgBAsIALAAIAAAPIgbAAIAAgIQgGAFgFADQgGADgIAAQgGAAgGgCgAgLAFIgIADQgDACgBADQgCADAAAEQAAADACADQABADACABIAHADIAGABIAHgBIAGgCIAEgDIAFgEIAAgUIgSAAIgIABg");
	this.shape_21.setTransform(71.35,187.525);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgOAtQgIgDgGgGQgFgGgEgKQgDgJAAgLQAAgJADgIQACgKAGgGQAFgGAJgEQAHgEAKAAQALAAAGADQAHAEAFAFQAEAEACAHIADAOIAAAGIABAGIhAAAIAAAHIACAHQACAIAIAEQAHAFAIAAQAHAAAHgCIAOgGIAHALQgKAGgIADQgKADgJAAQgIAAgIgDgAAXgJIgBgKQgCgEgCgDIgHgGQgEgBgGAAQgFAAgEABQgEACgDADQgEADgBAFIgDAKIAuAAg");
	this.shape_22.setTransform(61.2,187.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgVBFIAAgQIAOAAIAAhpIgOAAIAAgPIAdAAIAAB4IAOAAIAAAQg");
	this.shape_23.setTransform(53.425,185.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgQAtQgGgDgEgGIgJAAIAAgPIASAAQAAAEACACQABADADACIAGACIAGABIAHgBIAFgCIAEgEIABgFQAAgFgCgDQgDgDgHgCIgRgHQgKgDgFgGQgFgFAAgJQAAgGACgFQACgFAEgDIAKgGQAGgCAHAAQAJAAAHADQAGACAGAHIAIAAIAAAPIgSAAQAAgEgCgCQgBgDgDgBIgGgDIgGAAIgGAAIgFADIgDADQgCACAAADQAAAFADACQADADAGACIARAGQALAEAFAGQAGAGAAAJQAAAGgDAFQgCAFgFAEQgEAEgGACQgHABgHAAQgKAAgHgDg");
	this.shape_24.setTransform(138.025,164.725);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgJAYIAAgtIATgBIgEAug");
	this.shape_25.setTransform(132.075,157.65);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgVBCQgIgDgGgGQgGgGgDgKQgDgIAAgMQAAgKADgJQADgIAGgGQAGgGAIgEQAIgDAKAAQAGAAAFACQAGABAFAEIAAgjIgNAAIAAgPIAdAAIAAB4IANAAIAAAPIgdAAIAAgHQgFAEgGADQgFACgHAAQgJAAgIgDgAgNgIQgFACgEAEQgEADgCAGQgCAGAAAIQAAAJACAGQACAGAEAFQAEAEAFACQAFACAGABQAHgBAFgCQAFgCAEgEIAAgzQgFgDgFgBQgGgDgFAAQgGAAgFADg");
	this.shape_26.setTransform(125.275,162.55);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgVBEIAAgPIAOAAIAAhpIgOAAIAAgPIAdAAIAAB4IAOAAIAAAPg");
	this.shape_27.setTransform(116.775,162.45);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgUBDIAAgPIANAAIAAg8IgOAAIAAgPIAdAAIAABLIAOAAIAAAPgAgEgsIgDgDIgDgEIgBgEIABgEIADgEIADgCIAEgBIAEABIAEACIACAEIABAEIgBAEIgCAEIgEADIgEABg");
	this.shape_28.setTransform(111.025,162.575);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAJBEIAAgPIAMAAIAAgpQAAgKgFgFQgGgGgKAAQgEABgGADQgGACgFADIAAA1IANAAIAAAPIgrAAIAAgPIAOAAIAAhpIgNAAIAAgPIAdAAIAAA3IABAAIAFgEIAHgEIAHgCIAHgBQAIAAAFACQAGACAEAEQAFAEACAHQACAFAAAJIAAArIAOAAIAAAPg");
	this.shape_29.setTransform(102.225,162.45);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgOAtQgIgEgGgGQgGgHgDgJQgEgIAAgLQAAgJAEgJQADgJAHgHQAGgGAHgEQAJgDAHAAQAJAAAIADQAHADAHAGIAJAAIAAAPIgRAAQgEgHgFgDQgGgDgIAAQgEAAgFADQgFACgEAEQgEAFgCAGQgCAGAAAHQAAAIACAGQACAGAEAEQAEAFAFACQAFACAEAAQAJAAAGgEQAHgEADgIIANAHQgCAGgEAEQgEAFgEADIgLAFQgGABgHAAQgIAAgIgDg");
	this.shape_30.setTransform(91.3,164.725);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgWAuQgGgCgEgEQgEgEgCgFQgDgEABgGQAAgGABgEQACgFADgDIAGgEIAIgEIAJgCIAIgBIAKABIAIABIAAgIQAAgEgCgEIgDgGQgDgCgDgBIgIgBIgIAAIgHACIgFACIgFACIgFgLIAGgEIAIgDIAJgCIAJgBQAHAAAHACQAFACAFAEQAFAEACAGQACAGAAAJIAAAsIAKAAIAAAPIgaAAIAAgIQgGAFgFADQgGADgIAAQgHAAgFgCgAgMAFIgHADQgDACgBADQgBADAAAEQAAADABADQABADACABIAHADIAHABIAGgBIAFgCIAGgDIAEgEIAAgUIgSAAIgJABg");
	this.shape_31.setTransform(77.4,164.775);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AggBEIAAgPIAOAAIAAg+IgQAAIAAgNIAQAAIAAgOQAAgIACgFQACgHAEgDQADgFAGgCQAFgBAGAAIAJAAIAGABIAFACIAFACIgGAMIgHgDIgKgBQgHAAgEAFQgDAEAAAIIAAAPIAUAAIAAANIgUAAIAAA+IANAAIAAAPg");
	this.shape_32.setTransform(66.45,162.45);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgSAsQgIgDgGgGQgGgGgDgKQgEgIAAgLQAAgKAEgIQADgKAGgGQAGgHAJgDQAIgDAJAAQAKAAAJADQAIADAGAHQAGAGADAJQAEAJAAAKQAAALgEAIQgDAJgGAHQgGAGgIADQgJAEgKAAQgJAAgJgEgAgKgfQgFACgEAEQgEAFgCAGQgCAHAAAHQAAAIACAGQACAHAEAEQAEAFAFACQAFACAFAAQAGAAAFgCQAGgCADgFQAEgEACgHQADgGAAgIQAAgHgDgHQgCgGgEgFQgDgEgGgCQgFgCgGAAQgFAAgFACg");
	this.shape_33.setTransform(56.825,164.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(19.3,150,155.39999999999998,71.30000000000001), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AizDcIElm3IA3AAIklG3gABTDTQgSgHgNgNQgMgNgHgRQgHgRAAgUQAAgTAHgRQAHgRANgMQANgNASgIQASgIAVAAQAVAAASAIQASAIANANQAMAMAHARQAIARgBATQAAAUgGARQgHARgNANQgMANgSAHQgSAIgWAAQgWAAgSgIgABoBQQgJAEgHAHQgGAGgEAJQgEAIAAAKQAAAKAEAJQAEAJAGAHQAHAGAJAEQAJAEAKAAQAKAAAIgEQAJgEAHgGQAGgHAEgIQAEgKAAgKQAAgKgEgIQgEgJgGgGQgHgHgJgEQgIgDgKAAQgKAAgJADgAihgbQgSgHgNgNQgNgOgGgQQgIgRAAgUQAAgTAIgRQAHgRANgNQAMgNATgHQARgIAVAAQAWAAARAIQATAHANANQAMANAHARQAIARAAATQAAAUgIARQgHAQgMAOQgNANgSAHQgRAIgXAAQgWAAgRgIgAiMieQgKAEgGAGQgHAGgEAJQgDAJAAAKQAAAKADAJQAEAJAHAHQAGAGAKAEQAJAEAJAAQAKAAAJgEQAJgEAHgGQAGgHAEgIQAEgKgBgKQABgKgEgJQgEgJgGgGQgHgGgJgEQgJgDgKAAQgJAAgJADg");
	this.shape.setTransform(102.25,182.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhMDMQgfgSgTgdQgSgegIgoQgIgnAAgvQAAgvAKgrQALgrASgaQASgZAcgTQAcgSAvAAQAtAAAfAPQAeAPAUAeQATAdAIAqQAIArAAAuQAAAugIAoQgIAogSAeQgTAegfASQggAQgtAAQguAAgegQgAg0idQgUAPgKATQgJAVgGAiQgFAjAAAhQAAAjADAfQAEAfALAXQALAYAUANQAUANAhAAQAgAAAVgNQAUgNAKgYQALgXAFgfQAFgfAAgjQAAghgEgfQgEgfgMgYQgLgYgUgOQgVgOggAAQghAAgTAOg");
	this.shape_1.setTransform(61.175,182.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag0DTQgagLgSgRQgTgSgLgXQgLgYAAgaQAAgSAFgQQAEgQAJgOQAJgPAMgLQAMgLAPgIQgWgQgMgYQgNgXAAgbQAAgXAJgVQAJgUARgQQAQgPAWgJQAWgJAYAAQAZAAAWAJQAVAJARAPQAQAQAKAUQAJAVAAAXQAAAbgNAYQgNAYgWAPQAPAIALALQAMALAJAPQAIAOAFAQQAFAQAAASQAAAagLAYQgLAXgTASQgTARgYALQgZAKgdAAQgbAAgZgKgAggAQQgQAGgMAMQgLAKgHAPQgHAPAAAQQAAARAHAPQAHAOALALQAMALAQAHQAPAHARAAQASAAAPgHQAQgHAMgLQAMgLAGgOQAHgPAAgRQAAgQgHgPQgGgPgMgKQgMgMgQgGQgPgGgSAAQgRAAgPAGgAgaipQgNAGgKAJQgKAKgFAMQgFAMAAAOQAAAOAFANQAFAMAKAJQAKAJANAGQANAFAOAAQAPAAANgFQAMgGAKgJQAKgJAGgMQAFgNAAgOQAAgOgFgMQgGgMgKgKQgKgJgMgGQgNgFgPAAQgOAAgNAFg");
	this.shape_2.setTransform(26.175,182.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(6.4,146,120.89999999999999,74.1), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol6();
	this.instance.parent = this;
	this.instance.setTransform(551.4,185.65,1,1,0,0,0,13.2,13.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(125).to({_off:false},0).to({alpha:1},14).wait(145).to({_off:true},1).wait(225));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A7iQiIAAmbIBJAAIAAA0IAEgGIAOgSIAYgTIAHgEIAOgGIAQgFIAWgDIAaABIAjAKIAGADIATALIAXATIATAXIAOAeIAIAXIAFAvIgFAuIgIAYIgKAWIgNATIgVAUIgMAJIggAQIgVAFIgVADIgagBIgYgFIgVgKIgMgIIgQgPIgOgQIAACQgA5OK/IgMADIgFACIgMAFIgLAIIgHAGIgJALIgDADIgKARIgGATIgDAQIAAAXIADAQIAGATIAKARIAJALIAOAMIALAIIARAGIAEABIAEABIAOABIAOgBIAEgBIAEgBIARgGIAIgFIAOgMIAMgOIAHgMIAJgYIACgQIAAgXIgCgRIgJgXIgHgNIgPgRIgLgIIgMgGIgRgGIgOgBgEAl6AQfIgegEIgrgQIgCgCIonk8IIqklIACgBIAngMIAkgFIAsAAIAmAHIAZAJIIQEpIhhA4Imkj9IgCgBIgVgMIgngNIgegEIgeABIgSACIhCAYIlnDGIF9DhIABABIAKAFIAmAMIAfABIAIgBIAjgJIAQgHID9iWIj9iTIgBgBIgJgFIgQgFIgSgFIgUgBIgQACIgxAQIgBABIjUB7Ihng1IEtifIA4gUIAOgDIAHgBIAhACIAWAEIAHADIAGACIASAIIGdDsImiDyIgBACIgeALIgNAFIgfAEgAWZPHIgRgDIgjgLIgZgLIgfgUIAhgyIATANIAaAOIAnAKIANABIAWgBIAFgBIAMgEIAHgEIAFgFIADgGIACgIIAAgIIgBgHIgCgDIgBgBIgFgFIgRgLIhjgiIgLgGIgEgEIgNgLIgIgKIgIgRIgCgKIgBgWIABgLIAEgOIACgFIABgFIALgQIADgEIADgEIAQgNIASgJIAFgCIAagHIAuAAIAmAIIAeAMIAbAPIgcAyIgjgRIgSgHIgcgGIgQgBIgOADIgLAEIgFAFIgFAFIgDAHIgBAGIAAAJIABACIAAABIABACIABADIABABIACACIADADIAEADIAUAKIBCAWIAhARIALAIIAKAJIAKAOIAFAMIABAFIACAFIABAPIgBASIgEAQIgEAJIgIAOIgDAEIgLALIgVAOIgPAGIgWAFIgYADgASlPHIgNgDIgQgHIgHgEIgGgGIgIgJIgJgPIgGgTIgCgRIAAizIgqAAIAAg9IAqAAIAAhZIBIAAIAABZIBWAAIAAA9IhWAAIAAChIABAIIAFALIACACIAFAGIADACIADABIAHACIANABIAdgDIAPgFIAAA6IgJAGIgTAHIgaAEgAOPPJIgjgFIgSgEIgZgKIghgRIgPgLIAigyIAfAVIANAGIAnAKIAZABIAKgBIAFgBIAQgGIAIgHIACgDIACgDIABgEIAAgEIAAgKIgBgFIgCgDIgBgBIgEgFIgIgFIgQgIIhTgcIgUgKIgNgMIgIgKIgIgQIgCgEIgCgKIgBgQIABgRIAEgOIAEgKIAHgNIAJgLIAEgEIALgJIASgJIAZgHIARgDIATAAIAfAEIAXAFIAxAXIAGAEIgcAyIgugWIghgIIgPgBIgGABIgJACIgLAEIgCADIgDACIgEAFIgCAEIgCAGIAAAEIAAAFIACAIIAGAJIAIAGIAPAHIBbAiIAPAKIANAMIAIAKIACADIAGANIACAKIABAJIgBAYIgEAQIgEAJIgIAOIgDAEIgKALIgJAGIgEADIgEADIgUAIIgWAFIgYADgAD9PHIgNgDIgQgHIgKgGIgMgNIgDgDIgIgRIgDgJIgDgWIAAizIgnAAIAAg9IAnAAIAAhZIBIAAIAABZIBWAAIAAA9IhWAAIAAClIACAIIACADIACAEIABACIAFAGIADACIAHACIARACIASgBIAdgHIAAA6IgHAEIgPAHIgIACIgbAEgAhOPEIgQgEIgcgNIgHgEIgXgTIgLgMIgNgTIgKgVIgIgYIgFgrIAHgyIAFgPIAWgpIAagcIASgNIAcgMIAQgFIAXgDIASAAIAjAGIAWAIIAOAHIAYATIAOASIAQAaIAKAfIAFAXIADA2IjpAAIACAOIAGARIAIAOIARARIADADIAHAEIAPAHIAMACIAJABIAEABIAVAAIALgCIAQgFIAFgDIAPgIIAagUIAqAmIgMAOIgcAVIgPAIIgaAKIgcAFIgeABgAg9K9IgMACIgHAEIgMAHIgLALIgKANIgJASIgHAbICjAAIgDgSIgIgWIgJgOIgKgLIgIgHIgGgEIgLgFIgQgCIgIgBgAwIPEIgngOIgVgOIgdgbIgFgGIgWgpIgIggIgCgZIACgZIAIghIAWgqIAigiIAVgNIAfgMIAQgFIAagDIATAAIAaADIAQAFIAfAMIAVANIAMALIAWAXIANAVIAJAVIAJAhIABAQIgBAhIgEAQIgOAlIgNAUIgWAYIgTAPIgdAPIggAJIgJACIgkACgAv2LBIgOAFIgRAKIgLAJIgGAHIgLAQIgEAJIgIAdIgBAKIABAUIADAPIACAFIAKAWIADAEIAMAPIAEACIAHAHIAMAIIAJADIATAGIAPABIARgBIATgGIAVgLIAOgNIAMgPIACgFIACgDIAGgOIAEgUIABgUIgCgQIgJgcIgLgQIgGgIIgWgSIgFgCIgEgCIgJgDIgEgCIgKgCIgVgBgAz1PJIgXgDIgIgCIgIgDIgPgIIgHgGIgIgJIgHgLIgEgJIgEgOIgCgRIgBizIgmAAIAAg9IAmAAIAAhZIBJAAIAABZIBWAAIAAA9IhWAAIAAChIAAAEIACAIIADAHIAFAFIAFAFIADABIAIACIANABIAdgDIASgFIAAA6IgPAIIgPAFIgbAEgEgtiAPJIgjgFIgfgLIgIgDIgagSIgGgGIgRgRIgKgMIgPgcIgDgHIgFgQIgEgYIABgqIADgQIAIgYIAPgdIAFgGIAQgSIAZgVIANgIIAfgMIAZgGIAkgCIArAIIAfAMIAbASIAWAXIASAbIANAdIAGAhIABAZIgDAYIgRAtIgNAUIgVAYIgTAPIgdAPIgQAGIgrAHgEgtzALBIgOAFIgIAEIgXASIgGAIIgKAQIgIAYIgBAEIgBAaIABAKIADAPIAFAOIAJARIAJALIALAKIAQALIAJADIATAGIAPABIAagDIAOgFIARgKIAHgHIAEgCIAMgPIAFgJIAHgRIAEgOIACgVIgCgVIgKgcIgQgYIgXgSIgIgEIgJgDIgFgCIgKgCIgUgBgEggoAPIIgigGIgVgGIgdgNIgTgLIgYgTIgWgXIgMgQIgPgbIgOgnIgGggIAAguIAGgfIAGgVIASglIASgaIAVgWIAZgUIAmgVIAggKIAWgEIAkgDIAuAFIAqAMIAdAOIAZATIAXAVIATAZIAPAbIAIATIAKAqIADAhIgDAhIgKAqIgIATIgPAbIgaAhIgYAUIgbARIgeANIg4AMgEggoAJbIgcAIIgGACIgTAKIgLAIIgPAPIgNAQIgLASIgKAbIgDAOIgDAXIAAAPIADAYIADAOIALAbIAPAYIAOAPIAWASIATAJIAVAIIAWADIAPABIAXgCIAVgEIAUgIIAGgEIALgHIAQgOIAOgPIAMgRIAGgNIAJgbIADgVIABgZIgBgIIgFgcIgIgVIgGgNIgQgXIgagYIgGgEIgagNIgVgGIgPgCIgeAAgAKMPDIAAk8IBIAAIAAE8gAGaPDIAAk8IBIAAIAABFIATggIAPgRIAHgFIADgDIAMgGIADgDIAVgIIAOgDIAUgBIAABOIgiADIgUAHIgKAEIgQAOIgLALIgLAUIgEALIgFATIgDAkIAAB6gAlUPDIgBjGIgEgQIAAgDIgEgKIgKgOIgHgGIgCgCIgDgCIgDgBIgDgBIgDgBIgDgBIgDgBIgDgBIgIgBIgEAAIgDgBIgEABIgDAAIgOADIgKADIgDABIgCACIgDACIgDACIgIAHIgIALIgCADIgCAEIgBADIgBADIgCAEIgCAIIgBAJIgBADIAAC+IhIAAIAAi0IgCgaIgEgOIgCgEIgBgDIgCgDIgCgDIgDgFIgKgJIgCgCIgDgCIgDgBIgDgBIgDgBIgDgBIgDgBIgDgBIgIgBIgDAAIgEgBIgEABIgDAAIgHABIgNAEIgJAFIgFAEIgJAKIgGAJIgFAKIgEAQIgCAMIAAC7IhLAAIAAk8IBLAAIAAAvIAEgFIARgVIAKgJIAMgIIANgGIAOgEIAUgDIAVABIAQADIAbALIAPANIAJAKIAIALIADAHIAFgHIAXgVIATgNIAdgLIAQgDIAXgBIAYADIARAFIAOAHIAEADIAJAHIAIAHIAMARIALAbIAGAgIAADZgEgphAPDIAAj/IgqAAIAAg9IAqAAIAAgkIAGghIAEgJIABgEIAIgMIAJgKIATgMIANgFIAPgEIAWgBIAnADIATAGIAAA9IgKgEIgQgDIgUgBIgFAAIgMAEIgEABIgFAFIgFAHIgDAIIgDAPIAAAaIBTAAIAAA7IhTAAIAAD/gEAl4AOiIgTgEIgSgGIgRgJIgQgLIgRgSIgLgPIgJgSIgGgSIgEgUIAAgcIAEgSIAGgTIAJgRIAPgUIANgNIAQgLIARgJIAMgEIAZgFIAUgBIAiAGIAYAKIAFADIAQALIAOANIAPAUIAJARIAIAZIACAUIAAANIgCAVIgIAYIgDAGIgJASIgRATIgOANIgWANIgMAFIgTAFIgbACgEAnSAEzIgHgCIgZgGIgjgCIgSABIgbAGIgRAHIpOEsIAA6EIUAAAIAAaEgAKJJUIAAhFIBOAAIAABFgAP0F1IgRgEIgXgJIgOgIIgUgNIgRgRIgKgMIgQgcIgGgOIgGgXIgDghIABgTIAEgYIALgeIAVghIALgMIAZgUIAdgPIAYgIIAigGIASAAIAjAGIAYAHIAPAHIAVANIAXAVIAUAZIAKAVIAIAXIAFAhIAAARIgFAhIgIAYIgKAVIgKANIgVAYIgiAXIgnAPIgSAEIgbACgAP9BxIgOAEIgMAHIgLAIIgMANIgIANIgEAIIgEAOIgEAZIACAZIABAEIABAGIALAbIAJALIANANIAEAEIAMAHIATAHIAUAEIALAAIAFgBIALgBIAJgDIARgIIAIgEIAOgMIAIgMIADgDIAIgSIAFgYIABgSIgBgPIgDgOIgDgKIgGgMIgFgIIgPgSIgQgKIgEgDIgEgCIgOgEIgVgEIgLAAgADEF0IgVgGIgEgDIgFgCIgNgIIgEgDIgOgOIgJgNIgGgOIgEgPIgBgSIABgSIABgHIAFgQIAFgJIAJgNIAMgLIANgKIAPgHIAFgCIAGgCIALgDIAmgFIBDAGIAdAGIAAgOIgDgPIgBgDIgBgDIgIgPIgFgEIgNgJIgHgEIgWgFIgZgBIgkAEIgRAEIggAMIgTg7IAGgDIAhgNIAdgHIAqgFIAjABIAkAIIAMAGIARAJIASARIAEAEIAKAQIAIASIAEANIADAWIABDRIhFAAIAAgnIgEAFIgaAXIgTAJIgVAHIghAEgAD0DgIgVAFIgLAFIgKAHIgFAFIgCADIgDADIgDAIIAAACIgBADIAAADIgBACIAAAGIABADIAAACIABADIAAADIACAEIABADIAGAIIAHAGIAJAGIAQAFIAMACIAPAAIANgCIALgDIAPgGIAGgEIADgCIADgCIAKgJIACgEIACgCIACgDIAEgJIACgHIABgEIABgDIAAgYIgYgIIgmgFgAj8F3IgYgGIgegMIgagSIgRgRIgKgMIgMgVIgKgVIgGgXIgDghIAAgLIADgYIAJgfIAHgOIARgaIAWgXIAagSIAOgGIAYgIIAhgGIApACIAjAKIAXALIAaATIAMAMIgtAyIgEgFIgWgSIgggOIgTgDIgVABIgJADIgNAEIgQAJIgQAQIgKAQIgGAMIgHAdIAAAVIAFAZIAIASIAHANIAGAHIAEADIADADIALAJIAMAHIAOAEIAUAEIAEAAIAUgCIARgFIAPgIIAPgJIARgQIAtAtIggAdIgnAUIgcAHIggADgAp/F3IgagGIgmgRIgTgNIgSgRIgPgSIgSgkIgGgXIgDgQIAAgkIADgQIAJgfIAPgcIAKgMIARgRIAZgTIAXgLIAYgIIAigGIASAAIAjAGIAYAHIAdAPIANAJIARARIAPASIAPAcIAGAPIAGAgIAAAiIgGAhIgGAQIgLAVIgTAaIgRAQIgUAOIgeAOIghAJIgbACgAp/BxIgOAEIgIAFIgQAKIgNANIgHANIgLAbIAAAEIgBAFIgBAPIABAQIACAJIAGATIAEAJIALAQIAEADIAGAHIAIAHIAQAJIAOAFIAUAEIAKAAIAVgEIAXgJIAMgHIAKgJIALgPIAJgSIADgJIADgTIAAgYIgCgKIAAgEIgFgPIgEgJIgHgLIgJgMIgHgGIgPgKIgJgFIgOgEIgKgDIgUgBgAvUF3IgjgIIgzgYIgWgRIAegvIAvAaIAUAIIAaAEIASABIAGgBIASgEIAHgFIAGgFIAEgGIACgDIACgIIAAgIIgBgDIgBgEIgCgBIAAgCIgCgCIgDgEIgEgCIgJgGIgKgEIhMgZIgdgPIgKgIIgJgKIgIgLIgGgRIgDgPIAAgMIAFgaIAEgKIAIgMIAGgIIAOgNIAJgGIAEgBIAFgEIAZgIIAcgEIAVABIAfAFIAWAGIAeANIATALIgcA2IgdgRIgXgIIgXgFIgVgBIgKABIgEACIgEAAIgEACIgJAGIgEAFIgDAFIgBADIgBAEIAAAHIACAGIABACIABACIABACIABABIAMAJIAQAIIBBAVIAaAMIATANIAJAJIAJAKIAEAIIAEAMIACAJIAAAZIgGAbIgIAOIgJAMIgLAKIgNAJIgUAIIgcAHIgYACgA0BF2IgagHIgzgYIgXgRIAigvIAmAYIAaAKIAaAEIAYAAIAJgCIAJgCIAHgFIADgCIAFgGIACgDIACgDIACgIIAAgHIgBgBIAAgDIgBgCIAAgCIgDgDIgEgGIgEgCIgJgGIgKgEIhDgWIgagLIgEgCIgIgFIgNgLIgJgKIgCgEIgDgEIgGgRIgCgLIgBgQIABgFIAEgVIAEgKIADgDIACgFIAGgIIANgOIANgJIAEgBIAFgEIAEgCIAagHIAXgDIAVABIAfAFIAWAGIAkAQIANAIIgcA2IgFgEIgYgNIgXgIIgXgFIgLgBIgUABIgIACIgEACIgGAEIgFAEIgCADIgDAFIgBADIgBAEIAAAKIABABIABACIABACIABACIABACIABABIAHAGIAFADIAVAKIA8ATIAaAMIATANIAMAMIAIAKIAGARIADAPIAAANIgCAMIgEAQIgEAKIgHANIgHAIIgLAKIgEADIgdAOIgcAHIgYACgAI7F0IgEgBIgFAAIgIgCIgMgEIgHgEIgKgHIgJgJIgHgLIgBgEIgCgFIgGgUIgBi+IgqAAIAAhAIAqAAIAAhWIBIAAIAABWIBWAAIAABAIhWAAIAAChIADAMIADAIIAHAHIAJAEIAMACIAXgBIAQgEIALgGIAAA7IgHAEIgVAIIgaAFgAXcFwIgBjGIgEgSIgCgDIgBgEIgBgCIgCgDIgIgLIgFgEIgCgBIgDgCIgFgEIgDgBIgEgBIgDgBIgDgBIgQgCIgIAAIgOACIgEABIgDABIgEABIgDABIgDACIgGAEIgIAGIgHAHIgCAEIgEAFIgGAPIgDALIgBAJIAAC7IhIAAIAAk9IBIAAIAAAyIAXgbIAFgEIASgMIAVgIIAYgFIAdABIAXAGIAQAHIASAMIAOAQIAGAJIAIAPIAGAYIADAaIAADPgALdFwIAAk9IBIAAIAAE9gAgdFwIAAk9IBKAAIAAE9gA3WFwIgqhkIjIAAIgqBkIhOAAIC6mmIBGAAIC3GmgA6tDJICRAAIhIimgALaADIAAhDIBNAAIAABDgAgfADIAAhDIBMAAIAABDgAVvjRIglgIIgKgEIgNgHIgIgGIgLgKIgGgIIgIgMIgGgPIgDgQIAAgbIACgLIAFgRIAIgOIADgFIAHgIIALgKIAJgGIAVgKIAXgGIAggEIA4AEIAoAIIAAgKIgCgOIgDgKIgFgIIgGgIIgKgJIgDgBIgDgDIgGgDIgDAAIgEgCIgPgEIgZgBIgpAGIgsAOIgUg6IAwgTIBBgJIAjABIAdAGIAeANIAUAQIAMANIAJARIAJAZIAFAlIAADDIhIAAIAAgoIgJALIgQANIgRAKIgVAIIgfAGgAV7lnIgGACIgLAGIgKAGIgGAFIgDAFIgBACIgBACIgCAGIgCAIIAAALIACAHIACAFIABACIACAEIAHAIIAIAFIAKAFIARAEIARABIAEgBIAEAAIAYgFIAOgHIAJgGIAHgGIAHgJIAGgMIACgGIACgLIAAgVIgHgCIgQgGIgdgEIglAAgAJDjSIgYgEIgXgHIgVgLIgTgMIgQgQIgTgZIgKgWIgJggIgDgjIABgbIAFgXIAIgXIAPgbIAJgMIAWgVIAggUIAXgIIAYgFIAjAAIAhAIIAcAMIASAOIAPAQIAJANIAOAbIALAlIAEBAIjqAAIABAGIABADIABAGIADAIIACADIABAFIAGALIANAPIAGAFIAEACIADADIAKAGIALAEIAVAEIAcgBIAMgCIAQgHIAUgMIATgQIAqAmIgGAHIgaAXIgPAJIgiAOIgnAGgAIxndIgHADIgKAGIgJAIIgOASIgIATIgDAIIgDARICiAAIgDgRIgEgRIgFgKIgGgKIgIgIIgFgGIgNgIIgIgDIgQgEIgNgBIgEAAIgEAAgADSjSIgZgGIgWgKIgSgOIgQgOIgIgLIAAAwIhJAAIAAm4IBJAAIAACvIAEgGIAQgRIAYgSIAWgKIAhgHIAQAAIAVACIAUAGIAUAJIASALIALAJIAPAQIAQAaIAHAOIALAqIABAqIgFAjIgHAXIgLAXIgMASIgKAMIgQAOIgSAMIgUAJIgNADIgVAEIgYABgADCnbIgNAEIgIAEIgTALIgMAOIgIALIgGAOIgHAYIAAAkIAHAZIAGANIAIAMIAJAKIAWAPIAMAFIASAEIATAAIAWgGIAQgIIAKgHIAHgGIADgEIADgDIAMgUIAIgeIAAgkIgCgKIgGgTIgMgUIgDgEIgDgDIgHgHIgKgHIgQgIIgNgEIgTgCgAR6jWIgRgEIgLgFIgKgGIgGgGIgDgCIgJgPIgGgSIgDgQIgBi4IgqAAIAAhAIAqAAIAAhXIBIAAIAABXIBUAAIAABAIhUAAIAACgIADANIADAHIAEAFIAGAEIADACIAEAAIADACIAJABIARgBIALgCIAQgFIAFgDIAAA9IgOAGIghAHgAMwjZIAAk9IBIAAIAABIIAIgRIAPgXIAQgQIAKgHIAUgJIASgFIAOgBIAKAAIAABOIgfADIgFABIgPAGIgOAHIgIAGIgLAMIgJANIgIAQIgHAYIgDAdIAACAgAkJjZIgqhkIjIAAIgqBkIhOAAIC7mnIBFAAIC4GngAnfmBICQAAIhIimgAh2jaIAAm3IBJAAIAAG3g");
	this.shape.setTransform(307.475,105.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(284).to({_off:true},1).wait(225));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,615,211.6);


// stage content:
(lib._160x600_aaoo_boy = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// logo
	this.instance = new lib.logo("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(87.35,32,0.192,0.192,0,0,0,308.1,105.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(285));

	// Layer_8
	this.instance_1 = new lib.Symbol5();
	this.instance_1.parent = this;
	this.instance_1.setTransform(14.5,195.2,1,1,0,0,0,64.5,45.3);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(207).to({_off:false},0).to({y:165.2,alpha:1},32,cjs.Ease.quartInOut).wait(46));

	// frame
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#51C4ED").ss(8,1,1).p("EgMfgu3IY/AAMAAABdvI4/AAg");
	this.shape.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(285));

	// Layer_7
	this.instance_2 = new lib.Symbol4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(38.95,201.75,1,1,0,0,0,88.5,39.9);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(129).to({_off:false},0).to({y:191.75,alpha:1},30,cjs.Ease.cubicOut).wait(38).to({y:171.75,alpha:0},23,cjs.Ease.quartInOut).wait(65));

	// Layer_6
	this.instance_3 = new lib.Symbol3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(80,125,1,1,0,0,0,150,125);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(111).to({_off:false},0).to({alpha:1},26,cjs.Ease.cubicIn).wait(148));

	// Layer_5
	this.instance_4 = new lib.Symbol2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(79.95,180.25,1,1,0,0,0,96.2,26.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(9).to({_off:false},0).to({y:170.25,alpha:1},41,cjs.Ease.quartInOut).wait(51).to({alpha:0},18).wait(166));

	// Layer_1
	this.instance_5 = new lib.Symbol1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(80,121.55,1,1,0,0,0,66.8,40.6);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({y:111.55,alpha:1},41,cjs.Ease.quartInOut).wait(60).to({alpha:0},18).wait(166));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#51C4ED").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_1.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(285));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(10,296,220,308);
// library properties:
lib.properties = {
	id: 'EA7F868821484FEEB1ACA9412835E0FD',
	width: 160,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/160x600_aaoo_boy_atlas_.png", id:"160x600_aaoo_boy_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['EA7F868821484FEEB1ACA9412835E0FD'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;