(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib._970x250_solar_bg = function() {
	this.initialize(img._970x250_solar_bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,308,600);


(lib.CEPA_Horizontal_Logo_RGBK = function() {
	this.initialize(img.CEPA_Horizontal_Logo_RGBK);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,393,157);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.white = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(495.5,131.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.white, new cjs.Rectangle(345.5,-168.7,300,600), null);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_4 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A7yQiIAApVIg6AAIAAiNIA6AAIAAqwMA4fAAAIAAKwIg6AAIAACNIA6AAIAAJVg");
	mask.setTransform(-90.8,105.8);

	// Layer_3
	this.instance = new lib.CEPA_Horizontal_Logo_RGBK();
	this.instance.parent = this;
	this.instance.setTransform(-255,77,0.846,0.846);

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol6, new cjs.Rectangle(-255,77,332.7,132.9), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgvA3QgJgIAAgNQAAgIACgFQACgGAEgEQADgDAFgEIAJgEIAXgHQAPgFAGgEIAAgLIAAgHIgDgIQgDgFgEgDQgEgEgHABQgGAAgFABIgHAEIACAHIAAAJQAAAFgDADQgEAEgHAAQgGAAgDgFQgDgEAAgFQAAgGAEgFQAEgFAHgEQAFgDAHgDQAJgDAHABQAJgBAIACQAIACAFAEQAHAEADAIQADAIABAMIgBAfIAAAdQAAAFACADQABACADACIAGABIAJAAIAAAIIgKAEIgKABQgKAAgGgFQgFgEgCgIIgBAAQgIAJgIAEQgJAEgMABQgOAAgJgJgAgEAAQgHADgHAEQgGAEgDAGQgEAGAAAHQAAALAFAFQAGAEAHAAQAKAAAFgEQAGgEAFgGIAAgpg");
	this.shape.setTransform(430,-17.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AglAuQgOgRAAgdQAAgMAEgLQAEgLAHgJQAIgJAKgFQALgGAMABQARgBAMAKQALAHAAAPQAAAHgDAEQgDAFgHAAQgHAAgDgEQgFgDAAgFIACgLIACgIQgDgEgEgCIgKgBQgEAAgFACQgGADgFAGQgFAHgCAKQgDAKAAAPQAAAWAKAOQAKAOAQAAQALAAAJgFQAHgGAHgLIAIAEQgIAPgNAIQgNAJgOAAQgagBgPgRg");
	this.shape_1.setTransform(418.1,-17.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgLAMQgFgFAAgHQAAgGAFgFQAFgFAGAAQAHAAAFAFQAFAFAAAGQAAAHgFAFQgFAFgHAAQgGAAgFgFg");
	this.shape_2.setTransform(408.6,-13.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgUA6QgLgFgHgIQgIgJgDgMQgDgLAAgNQAAgLADgMQAEgLAHgJQAHgJALgFQAKgGAMABQANgBAJAFQAKAEAFAHQAGAHADAJQADAKAAALIAAAHIhPAAQAAAMACAJQACAKAFAHQAFAHAIAEQAGAFALgBQALABAIgGQAIgFAHgNIAIAFQgHAPgNAIQgMAJgRAAQgNAAgLgGgAAagNIgBgOQgBgIgCgGQgDgFgFgEQgFgDgIAAQgLAAgJAKQgIALgBATIA2AAg");
	this.shape_3.setTransform(399.4,-17.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgsA+IAAgIIAFgBIAGgBQADgBACgDQABgCAAgFIAAhJQAAgEgBgDQgCgEgDgCIgGgCIgHgBIAAgIIAogDIACACIAAARIABAAQAGgKAJgFQAKgGAHAAQAIAAAFAFQAFAFAAAJQAAAGgDAFQgDAFgHAAQgHAAgDgEQgEgDAAgFIABgEIAAgFQgFAAgIAFQgIAEgEAJIAABFQAAAEACADQABADADABIAIACIAIABIAAAIg");
	this.shape_4.setTransform(388.4,-17.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgnA0QgIgLAAgTIAAg5QAAgEgCgDQgBgDgEgCIgFgDIgHgBIAAgIIApgDIABACIAABTQAAANAGAHQAGAGAIAAQAGAAAFgCIAJgEIAGgGIADgGIAAhCQAAgEgCgEQgBgDgDgCQgCgCgEAAIgKgBIAAgIIAsgDIACACIAABfQgBAEACADIAFAFIAFACIAHAAIAAAIIgnADIgDgCIAAgPIAAAAIgGAGIgJAHIgKAFQgFABgJABQgQAAgJgLg");
	this.shape_5.setTransform(375.8,-17.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgMBIQgGgHAAgOIAAhQIgWAAIAAgNIAXAAIAAglIAVAAIAAAlIAiAAIAAANIgiAAIAABBIABANQAAAGACADQACADAEACQAEACAHAAIAJAAIAIgCIAAAJIgPAGQgHACgKAAQgPAAgGgIg");
	this.shape_6.setTransform(364.3,-19.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgnA0QgIgLAAgTIAAg5QAAgEgBgDQgCgDgEgCIgFgDIgHgBIAAgIIApgDIABACIAABTQAAANAGAHQAGAGAIAAQAGAAAFgCIAJgEIAGgGIADgGIAAhCQAAgEgCgEQgBgDgDgCQgCgCgEAAIgKgBIAAgIIAsgDIACACIAABfQgBAEACADIAFAFIAFACIAHAAIAAAIIgnADIgDgCIAAgPIAAAAIgGAGIgJAHIgKAFQgFABgJABQgQAAgJgLg");
	this.shape_7.setTransform(352.8,-17.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgpBfIAAgIIAGgBIAFgBQAEgBABgDQACgDAAgEIAAhWIgYAAIAAgNIAYAAIAAgHQAAgbAOgSQANgQAWAAQALgBAFAFQAGAEAAAGQAAAFgDAEQgDAEgGAAQgEAAgDgCIgFgEIgFgGIgDgFQgIAAgFALQgDALAAAZIAAALIAeAAIAAANIgeAAIAABVQAAAEAAADQACADAEABIAHACIAJABIAAAIg");
	this.shape_8.setTransform(342.7,-21.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AghBcQgJgFgHgIQgIgJgEgMQgEgLAAgPQAAgNAFgLQAEgLAIgJQAHgIALgFQALgFALAAQAIAAAIACQAIACAGAEIAAgqQAAgFgCgFQgCgEgDgCQgDgCgGgBIgMgCIAAgIIAxgCIACACIAAChQAAAEABADQACADADACQACACAFAAIAIAAIAAAJIgqACIgCgBIAAgMIgBAAQgGAHgKAFQgIAEgKAAQgKAAgKgEgAgTgRQgGAEgFAHQgEAGgDAKQgCALAAANQAAAKACAIQABAJAFAHQAEAHAHAEQAHAEAJAAQAIAAAHgEQAGgEAFgGIAAhFIgDgHIgGgHIgIgFQgFgCgFAAQgIAAgGAEg");
	this.shape_9.setTransform(330.7,-20.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgUA6QgLgFgHgIQgIgJgDgMQgDgLAAgNQAAgLADgMQAEgLAHgJQAHgJALgFQAKgGAMABQANgBAJAFQAKAEAFAHQAGAHADAJQADAKAAALIAAAHIhPAAQAAAMACAJQACAKAFAHQAFAHAIAEQAGAFALgBQALABAIgGQAIgFAHgNIAIAFQgHAPgNAIQgMAJgRAAQgNAAgLgGgAAagNIgBgOQgBgIgCgGQgDgFgFgEQgFgDgIAAQgLAAgJAKQgIALgBATIA2AAg");
	this.shape_10.setTransform(317.4,-17.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgsA+IAAgIIAFgBIAGgBQADgBACgDQABgCAAgFIAAhJQAAgEgBgDQgCgEgDgCIgGgCIgHgBIAAgIIAogDIACACIAAARIABAAQAGgKAJgFQAKgGAHAAQAIAAAFAFQAFAFAAAJQAAAGgDAFQgDAFgHAAQgHAAgDgEQgEgDAAgFIABgEIAAgFQgFAAgIAFQgIAEgEAJIAABFQAAAEACADQABADADABIAIACIAIABIAAAIg");
	this.shape_11.setTransform(306.4,-17.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgvA3QgJgIAAgNQABgIABgFQACgGAEgEQADgDAFgEIAKgEIAWgHQAPgFAHgEIAAgLIgBgHIgDgIQgCgFgFgDQgDgEgJABQgFAAgFABIgHAEIACAHIABAJQAAAFgFADQgDAEgHAAQgGAAgDgFQgDgEAAgFQAAgGAEgFQAEgFAGgEQAGgDAIgDQAHgDAIABQAJgBAIACQAIACAFAEQAHAEADAIQADAIAAAMIAAAfIgBAdQAAAFADADQABACADACIAGABIAJAAIAAAIIgKAEIgLABQgJAAgFgFQgGgEgCgIIgBAAQgHAJgJAEQgJAEgMABQgPAAgIgJgAgDAAQgJADgGAEQgGAEgEAGQgDAGAAAHQAAALAFAFQAFAEAJAAQAJAAAFgEQAHgEAEgGIABgpg");
	this.shape_12.setTransform(295.1,-17.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AAKBfIAAgIIAHgBIAFgBQAEgBABgDQACgDAAgEIAAg+QAAgMgGgHQgGgGgJgBQgGABgFACIgJAEIgHAHIgDADIAABGQAAAEABADQACADADABIAGACIAGABIAAAIIg7AAIAAgIIAGgBIAFgBQAEgBABgDQACgDAAgEIAAiLQAAgFgCgDQgCgFgDgCQgCgCgFAAIgKgBIAAgIIAtgCIACACIAABTIAAAAIAIgHIAIgGQAFgEAFgBQAGgCAIAAQAQAAAJAKQAJAKAAASIAAA/QAAAEABADQACADADABIAGACIAGABIAAAIg");
	this.shape_13.setTransform(280.9,-21.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgSA8QgJgEgEgDIgCAIIgKAAIgBgqIAJAAQABAFADAGQADAGAEAFQAFAGAHADQAGAFAIAAQAMgBAGgFQAGgGAAgJQAAgGgCgDQgCgEgEgCIgKgGIgMgEIgMgFQgHgDgFgDQgGgEgDgHQgEgFAAgJQAAgPALgKQALgKATAAQAGAAAHABQAIADAEACIADgGIAJAAIACAmIgJAAQgCgMgJgJQgIgIgMAAQgKAAgFAFQgGAFAAAHQAAAFACAFQACADAEACIAJAFIANAFIAPAGIAMAGQAFAFACAFQADAHAAAIQAAAQgNALQgMALgUAAQgKgBgIgDg");
	this.shape_14.setTransform(268.5,-17.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgMBIQgGgHAAgOIAAhQIgWAAIAAgMIAXAAIAAgmIAVAAIAAAmIAiAAIAAAMIgiAAIAABBIABAOQAAAEACAEQACADAEACQAEACAHABIAJgBIAIgCIAAAJIgPAGQgHACgKAAQgPAAgGgIg");
	this.shape_15.setTransform(376.4,-48.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgvA3QgJgIABgNQAAgIABgFQACgFAEgFQADgDAFgDIAJgFIAXgHQAQgFAFgEIAAgMIAAgGIgDgIQgDgEgEgEQgEgDgHgBQgGAAgFACIgHAFIABAHIABAJQAAAEgDADQgEAEgHAAQgGAAgDgFQgDgEAAgFQAAgGAEgFQAEgFAHgEQAFgEAHgCQAJgCAHgBQAJABAIABQAHACAHAEQAGAFADAHQADAIAAANIAAAdIAAAeQAAAEABADQACADAEACIAFACIAIAAIAAAIIgKACIgKACQgJAAgGgEQgFgFgCgJIgBAAQgIAKgIAEQgJAFgNgBQgNABgJgJgAgEAAQgHADgHAEQgGAFgDAFQgEAGAAAIQAAAJAFAFQAGAFAHAAQAJAAAGgEQAHgEAEgGIAAgpg");
	this.shape_16.setTransform(366.3,-47.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAgA9IgghYIggBYIgKAAIgSg2IgPguQgCgFgGgEQgFgDgFgBIAAgIIA1AAIAAAJIgIABQgFABAAADIAAACIABAEIAJAcIANAoIAehVIALAAIAgBUIAKgeIAJgdIACgGIABgFQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAIgFgDIgFgBIgEgBIAAgIIAtAAIAAAIQgFABgGADQgGAEgCAIIgMAiIgMAjIgEAOIgFAOg");
	this.shape_17.setTransform(344.6,-47);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgWA8QgKgFgIgIQgIgIgFgMQgFgMAAgOQAAgcARgSQAQgSAaAAQAZAAAQASQARARAAAcQAAAMgEAMQgEAMgIAJQgIAJgLAFQgLAFgNAAQgMAAgKgEgAgOgxQgHAFgEAIQgEAIgCAJIgBASQAAALACAKQABAKAEAIQAFAIAGAEQAGAFAJAAQAPAAAJgPQAJgPAAgZQAAgJgCgKQgCgKgEgIQgEgHgGgFQgGgEgJAAQgJAAgGAEg");
	this.shape_18.setTransform(328.5,-47.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAKBfIAAgJIAHAAIAFgBQAEgBABgDQACgDAAgEIAAg+QAAgMgGgGQgGgIgJABQgGAAgFABIgJAGIgHAFIgDAFIAABFQAAAEABACQACADADACIAGACIAGAAIAAAJIg7AAIAAgJIAGAAIAFgBQAEgBABgDQACgDAAgEIAAiMQAAgEgCgEQgCgDgDgDQgCgBgFgBIgKgBIAAgIIAtgCIACABIAABUIAAAAIAIgGIAIgHQAFgDAFgCQAGgCAIAAQAQAAAJAKQAJAKAAATIAAA+QAAAEABADQACACADACIAGACIAGAAIAAAJg");
	this.shape_19.setTransform(314.2,-50.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgUA7QgLgGgHgJQgIgIgDgMQgDgMAAgMQAAgMADgKQAEgMAHgJQAHgIALgGQAKgFAMgBQANABAJAEQAKAEAFAHQAGAHADAKQADAIAAAMIAAAIIhPAAQAAALACAJQACAKAFAHQAFAHAIAEQAGAEALABQALgBAIgFQAIgFAHgNIAIAFQgHAOgNAJQgMAIgRAAQgNAAgLgEgAAagMIgBgQQgBgHgCgFQgDgGgFgDQgFgEgIAAQgLAAgJAKQgIALgBAUIA2AAg");
	this.shape_20.setTransform(295.4,-47.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgUA7QgLgGgHgJQgIgIgDgMQgDgMAAgMQAAgMADgKQAEgMAHgJQAHgIALgGQAKgFAMgBQANABAJAEQAKAEAFAHQAGAHADAKQADAIAAAMIAAAIIhPAAQAAALACAJQACAKAFAHQAFAHAIAEQAGAEALABQALgBAIgFQAIgFAHgNIAIAFQgHAOgNAJQgMAIgRAAQgNAAgLgEgAAagMIgBgQQgBgHgCgFQgDgGgFgDQgFgEgIAAQgLAAgJAKQgIALgBAUIA2AAg");
	this.shape_21.setTransform(283.3,-47.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgWBXQgLgEgJgFIgFAJIgKAAIgCg7IAKAAQADALAEAIQAFAJAGAIQAHAHAIAEQAJAFAKAAQAIAAAHgDQAGgCAEgEQAEgEABgFQADgGAAgHQgBgKgGgJQgGgJgLgFIgRgHIgSgHQgPgGgHgKQgIgLAAgRQAAgKADgJQAEgIAIgHQAHgGAJgEQAKgDAKAAQAMAAAJADQAJAEAJAFIAEgIIAKAAIABA5IgKAAIgFgTQgEgJgFgHQgGgHgIgEQgHgFgKAAQgLAAgJAIQgIAHAAALQAAALAGAIQAFAHAJAFIARAHIARAHIAOAHQAGADAGAFQAFAGADAIQACAHAAAKQABAXgSAOQgQAPgZAAQgLAAgMgDg");
	this.shape_22.setTransform(270.2,-49.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(261.1,-65.9,177,61.8), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgLAMQgFgFAAgHQAAgGAFgFQAFgFAGAAQAHAAAFAFQAFAFAAAGQAAAHgFAFQgFAFgHAAQgGAAgFgFg");
	this.shape.setTransform(-0.2,48.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgMBJQgGgIAAgOIAAhRIgWAAIAAgMIAXAAIAAglIAVAAIAAAlIAiAAIAAAMIgiAAIAABDIABAMQAAAFACAEQACAEAEACQAEABAHAAIAJAAIAIgBIAAAJIgPAFQgHACgKAAQgPAAgGgHg");
	this.shape_1.setTransform(-8,42.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AAJA+IAAgIIAFgBIAGgBQAEgBABgDQACgCAAgFIAAg9QAAgMgHgHQgFgHgJAAQgGAAgFACIgKAFIgGAGIgEAFIAABEQAAAEACADQACADAEABIAFACIAGABIAAAIIg6AAIAAgIIAFgBIAGgBQACgBACgDQACgCAAgFIAAhJQAAgEgCgEQgCgDgCgCIgGgCIgHgBIAAgIIAogDIABACIAAARIABAAIAIgHIAIgHQAFgDAEgCQAHgCAIAAQARAAAIALQAJALAAASIAAA9IABAHQABADAEABIAGACIAFABIAAAIg");
	this.shape_2.setTransform(-19.5,43.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgaBcIAAgIIAGAAIAFgBQADgBACgDQABgDABgEIAAhJQgBgEgBgEIgFgFIgHgCIgIgBIAAgJIApgCIACABIAABiQAAAEACADQABADAEABIAGABIAFABIAAAIgAgJg/QgGgFAAgGQAAgHAGgGQAEgEAFAAQAHAAAEAEQAFAFAAAGQAAAHgFAGQgEAEgHAAQgFAAgEgEg");
	this.shape_3.setTransform(-30.6,40.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgsA+IAAgIIAFgBIAGgBQADgBACgDQABgCAAgFIAAhJQAAgEgBgDQgCgEgDgCIgGgCIgHgBIAAgIIAogDIACACIAAARIABAAQAGgKAJgFQAKgGAHAAQAIAAAFAFQAFAFAAAJQAAAGgDAFQgDAFgHAAQgHAAgDgEQgEgDAAgFIABgEIAAgFQgFAAgIAFQgIAEgEAJIAABFQAAAEACADQABADADABIAIACIAIABIAAAIg");
	this.shape_4.setTransform(-39,43.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AhABZIAAgIIAIgBIAFgBQAFgBABgDQABgDAAgEIAAh/QAAgEgBgEIgGgFIgFgCIgIgBIAAgIIApgDIACABIAAAOIABAAQAGgHAJgFQAJgFAJAAQAMAAAJAFQAJAFAHAIQAHAIAEAMQAEALAAAOQAAAPgFAKQgEAMgJAIQgHAJgLAEQgKAFgLAAQgJAAgHgDQgIgCgEgDIgBAAIAAAkQAAAEACADQACADADACIAIACIAIABIAAAIgAgKhGQgHAEgEAFIAABGIAEAHIAFAGIAIAFQAEACAGAAQAHAAAGgEQAGgDAFgHQAFgHACgJQACgKAAgNQAAgJgCgJQgBgKgFgGQgEgIgHgEQgGgEgKAAQgHAAgHAEg");
	this.shape_5.setTransform(-51.8,46.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgMBJQgGgIAAgOIAAhRIgWAAIAAgMIAXAAIAAglIAVAAIAAAlIAiAAIAAAMIgiAAIAABDIABAMQAAAFACAEQACAEAEACQAEABAHAAIAJAAIAIgBIAAAJIgPAFQgHACgKAAQgPAAgGgHg");
	this.shape_6.setTransform(-63.1,42.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgWA8QgKgFgIgIQgIgIgFgMQgFgMAAgOQAAgcARgSQAQgSAaAAQAZAAAQASQARARAAAcQAAAMgEAMQgEAMgIAJQgIAJgLAFQgLAFgNAAQgMAAgKgEgAgOgxQgHAFgEAIQgEAIgCAJIgBASQAAALACAKQABAKAEAIQAFAIAGAEQAGAFAJAAQAPAAAJgPQAJgPAAgZQAAgJgCgKQgCgKgEgIQgEgHgGgFQgGgEgJAAQgJAAgGAEg");
	this.shape_7.setTransform(-74,43.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgWA8QgKgFgIgIQgIgIgFgMQgFgMAAgOQAAgcARgSQAQgSAaAAQAZAAAQASQARARAAAcQAAAMgEAMQgEAMgIAJQgIAJgLAFQgLAFgNAAQgMAAgKgEgAgOgxQgHAFgEAIQgEAIgCAJIgBASQAAALACAKQABAKAEAIQAFAIAGAEQAGAFAJAAQAPAAAJgPQAJgPAAgZQAAgJgCgKQgCgKgEgIQgEgHgGgFQgGgEgJAAQgJAAgGAEg");
	this.shape_8.setTransform(-87.5,43.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgpBeIAAgIIAGAAIAFgBQAEgBABgDQACgDAAgEIAAhXIgYAAIAAgMIAYAAIAAgHQAAgcAOgRQANgRAWAAQALAAAFAFQAGAEAAAGQAAAGgDADQgDAEgGAAQgEAAgDgCIgFgDIgFgHIgDgFQgIAAgFALQgDAMAAAYIAAALIAeAAIAAAMIgeAAIAABWQAAAEAAADQACADAEABIAHABIAJABIAAAIg");
	this.shape_9.setTransform(-97.2,40.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AAIA+IAAgIIAHgBIAFgBQADgBACgDQACgCAAgFIAAg9QAAgMgHgHQgFgHgJAAQgGAAgFACIgKAFIgGAGIgEAFIAABEQAAAEADADQABADADABIAGACIAGABIAAAIIg6AAIAAgIIAFgBIAFgBQAEgBACgDQABgCAAgFIAAhJQAAgEgBgEQgCgDgEgCIgFgCIgHgBIAAgIIAogDIABACIAAARIABAAIAHgHIAJgHQAFgDAEgCQAHgCAIAAQARAAAJALQAIALAAASIAAA9IABAHQABADAEABIAFACIAGABIAAAIg");
	this.shape_10.setTransform(91.1,12.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgWA8QgKgFgIgIQgIgIgFgMQgFgMAAgOQAAgcARgSQAQgSAaAAQAZAAAQASQARARAAAcQAAAMgEAMQgEAMgIAJQgIAJgLAFQgLAFgNAAQgMAAgKgEgAgOgxQgHAFgEAIQgEAIgCAJIgBASQAAALACAKQABAKAEAIQAFAIAGAEQAGAFAJAAQAPAAAJgPQAJgPAAgZQAAgJgCgKQgCgKgEgIQgEgHgGgFQgGgEgJAAQgJAAgGAEg");
	this.shape_11.setTransform(76.9,12.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgsBgIABgWIAAgYIAAh3IgBgIQgCgEgDgCIgHgCIgJgBIAAgIIAsgDIACACIAABPIABABQAHgIAJgEQAIgEAJAAQAVAAAQARQAOARAAAcQAAAbgQASQgSATgXAAQgJAAgJgDQgKgDgIgFIgJAOgAgIgOQgHADgEAGIAABFIACAGIAGAIIAJAGQADACAHAAQAPAAAJgPQAJgOAAgZQAAgJgCgKQgCgJgEgGQgEgHgHgEQgGgFgKAAQgHAAgHAEg");
	this.shape_12.setTransform(62.6,9.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgsA+IAAgIIAFgBIAGgBQADgBACgDQABgCAAgFIAAhJQAAgEgBgDQgCgEgDgCIgGgCIgHgBIAAgIIAogDIACACIAAARIABAAQAGgKAJgFQAKgGAHAAQAIAAAFAFQAFAFAAAJQAAAGgDAFQgDAFgHAAQgHAAgDgEQgEgDAAgFIABgEIAAgFQgFAAgIAFQgIAEgEAJIAABFQAAAEACADQABADADABIAIACIAIABIAAAIg");
	this.shape_13.setTransform(51.4,12.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgvA4QgJgJAAgOQABgGABgGQACgFAEgFQADgEAFgDIAJgEIAXgGQAQgGAFgDIAAgMIAAgGIgDgJQgCgEgFgEQgDgEgJABQgFAAgFACIgHADIACAHIABAJQAAAFgFADQgDAEgHAAQgGAAgDgEQgDgFAAgFQAAgGAEgFQAEgFAGgEQAGgDAIgDQAHgCAIAAQAJAAAIABQAIABAFAFQAHAEADAJQAEAHAAAMIgBAfIgBAdQABAEACAEQABACADACIAGABIAJAAIAAAIIgKAEIgKABQgKAAgFgFQgHgEgBgIIgBAAQgIAIgIAFQgJAEgMABQgPgBgIgHgAgEAAQgIADgGAEQgGAEgEAGQgDAGAAAHQAAAKAFAGQAFAEAJAAQAJAAAFgEQAHgEAEgGIAAgpg");
	this.shape_14.setTransform(40.1,12.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AglAvQgOgSAAgdQAAgMAEgLQAEgLAHgJQAHgIALgGQALgGAMABQASAAALAJQALAHAAAPQAAAHgDAEQgDAFgGAAQgIAAgDgEQgFgEAAgEIABgLIADgJQgDgEgEgBIgJgBQgGAAgEACQgGADgFAGQgEAHgDAKQgDAKAAAPQAAAWAKAOQAKAOAPAAQAMAAAJgFQAHgGAHgLIAIAEQgIAPgNAJQgNAHgOABQgagBgPgQg");
	this.shape_15.setTransform(28.2,12.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgsA+IAAgIIAFgBIAGgBQADgBACgDQABgCAAgFIAAhJQAAgEgBgDQgCgEgDgCIgGgCIgHgBIAAgIIAogDIACACIAAARIABAAQAGgKAJgFQAKgGAHAAQAIAAAFAFQAFAFAAAJQAAAGgDAFQgDAFgHAAQgHAAgDgEQgEgDAAgFIABgEIAAgFQgFAAgIAFQgIAEgEAJIAABFQAAAEACADQABADADABIAIACIAIABIAAAIg");
	this.shape_16.setTransform(11.3,12.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgmA0QgJgLAAgTIAAg4QAAgFgCgDQgBgDgDgDIgGgCIgHgBIAAgIIAogCIACABIAABTQAAANAGAHQAGAGAIAAQAGAAAFgCIAJgEIAFgGIAFgGIAAhCQAAgFgCgDQgCgDgDgCQgCgBgFgBIgKgBIAAgIIAsgCIACABIAABfQAAAEACADIAFAFIAFACIAHAAIAAAIIgnADIgCgCIAAgPIgBAAIgHAGIgIAHIgKAFQgFABgJABQgQAAgIgLg");
	this.shape_17.setTransform(-1.4,12.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgWA8QgKgFgIgIQgIgIgFgMQgFgMAAgOQAAgcARgSQAQgSAaAAQAZAAAQASQARARAAAcQAAAMgEAMQgEAMgIAJQgIAJgLAFQgLAFgNAAQgMAAgKgEgAgOgxQgHAFgEAIQgEAIgCAJIgBASQAAALACAKQABAKAEAIQAFAIAGAEQAGAFAJAAQAPAAAJgPQAJgPAAgZQAAgJgCgKQgCgKgEgIQgEgHgGgFQgGgEgJAAQgJAAgGAEg");
	this.shape_18.setTransform(-15.2,12.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgUA6QgLgFgHgIQgIgJgDgMQgDgLAAgNQAAgLADgMQAEgLAHgJQAHgIALgGQAKgGAMABQANgBAJAFQAKAEAFAHQAGAHADAJQADAKAAAKIAAAIIhPAAQAAAMACAJQACAKAFAHQAFAHAIAEQAGAFALgBQALABAIgGQAIgFAHgNIAIAFQgHAPgNAIQgMAJgRAAQgNAAgLgGgAAagNIgBgOQgBgIgCgGQgDgFgFgEQgFgDgIAAQgLAAgJALQgIAKgBATIA2AAg");
	this.shape_19.setTransform(-33.8,12.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgkAvQgPgSAAgdQAAgMAEgLQADgLAJgJQAGgIAMgGQAKgGAMABQARAAAMAJQALAHAAAPQAAAHgDAEQgDAFgHAAQgHAAgEgEQgEgEAAgEIACgLIABgJQgCgEgEgBIgKgBQgFAAgFACQgFADgFAGQgEAHgDAKQgDAKAAAPQAAAWAKAOQAKAOAQAAQALAAAIgFQAJgGAGgLIAIAEQgIAPgOAJQgNAHgOABQgYgBgPgQg");
	this.shape_20.setTransform(-45.2,12.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgnA0QgIgLAAgTIAAg4QAAgFgBgDQgCgDgEgDIgFgCIgHgBIAAgIIAogCIACABIAABTQAAANAGAHQAGAGAIAAQAGAAAFgCIAJgEIAGgGIADgGIAAhCQAAgFgCgDQgBgDgDgCQgCgBgEgBIgKgBIAAgIIAsgCIACABIAABfQgBAEACADIAFAFIAFACIAHAAIAAAIIgoADIgCgCIAAgPIAAAAIgHAGIgIAHIgKAFQgFABgJABQgQAAgJgLg");
	this.shape_21.setTransform(-58.6,12.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AghBcQgJgFgHgIQgIgJgEgMQgEgLAAgPQAAgNAFgLQAEgLAIgJQAHgIALgFQALgFALAAQAIAAAIACQAIACAGAEIAAgqQAAgFgCgFQgCgEgDgCQgDgCgGgBIgMgCIAAgIIAxgCIACACIAAChQAAAEABADQACADADACQACACAFAAIAIAAIAAAJIgqACIgCgBIAAgMIgBAAQgGAHgKAFQgIAEgKAAQgKAAgKgEgAgTgRQgGAEgFAHQgEAGgDAKQgCALAAANQAAAKACAIQABAJAFAHQAEAHAHAEQAHAEAJAAQAIAAAHgEQAGgEAFgGIAAhFIgDgHIgGgHIgIgFQgFgCgFAAQgIAAgGAEg");
	this.shape_22.setTransform(-72.6,9.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgUA6QgLgFgHgIQgIgJgDgMQgDgLAAgNQAAgLADgMQAEgLAHgJQAHgIALgGQAKgGAMABQANgBAJAFQAKAEAFAHQAGAHADAJQADAKAAAKIAAAIIhPAAQAAAMACAJQACAKAFAHQAFAHAIAEQAGAFALgBQALABAIgGQAIgFAHgNIAIAFQgHAPgNAIQgMAJgRAAQgNAAgLgGgAAagNIgBgOQgBgIgCgGQgDgFgFgEQgFgDgIAAQgLAAgJALQgIAKgBATIA2AAg");
	this.shape_23.setTransform(-85.9,12.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgsA+IAAgIIAFgBIAGgBQADgBACgDQABgCAAgFIAAhJQAAgEgBgDQgCgEgDgCIgGgCIgHgBIAAgIIAogDIACACIAAARIABAAQAGgKAJgFQAKgGAHAAQAIAAAFAFQAFAFAAAJQAAAGgDAFQgDAFgHAAQgHAAgDgEQgEgDAAgFIABgEIAAgFQgFAAgIAFQgIAEgEAJIAABFQAAAEACADQABADADABIAIACIAIABIAAAIg");
	this.shape_24.setTransform(-96.9,12.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgWA8QgKgFgIgIQgIgIgFgMQgFgMAAgOQAAgcARgSQAQgSAaAAQAZAAAQASQARARAAAcQAAAMgEAMQgEAMgIAJQgIAJgLAFQgLAFgNAAQgMAAgKgEgAgOgxQgHAFgEAIQgEAIgCAJIgBASQAAALACAKQABAKAEAIQAFAIAGAEQAGAFAJAAQAPAAAJgPQAJgPAAgZQAAgJgCgKQgCgKgEgIQgEgHgGgFQgGgEgJAAQgJAAgGAEg");
	this.shape_25.setTransform(50,-19);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgMBIQgGgHAAgOIAAhQIgWAAIAAgNIAXAAIAAglIAVAAIAAAlIAiAAIAAANIgiAAIAABBIABANQAAAGACADQACADAEACQAEACAHAAIAJAAIAIgCIAAAJIgPAGQgHACgKAAQgPAAgGgIg");
	this.shape_26.setTransform(38.9,-20.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgsBRQgOgIAAgPQAAgNAKgHQAKgHAPAAIAAgDIgIgCIgGgEIgFgGQgCgEAAgFQAAgGAEgEQAFgGAJgEIAAgCQgMgFgGgIQgHgKAAgKQAAgSANgLQANgLAUAAIAKABIALADIAqAAIAAAMIgcAAIAAAAQAEAGACAGQACAGAAAHQAAAPgMAMQgNALgQgBIgPAAIgGAEQgDACAAAEQAAAEACADIAHADIAIABIAKAAIANACIAOAAQAFAAAGADQAGADAEAEQAFAEADAGQADAGAAAIQAAAJgEAIQgEAHgIAGQgIAGgLADQgLADgQAAQgcAAgNgIgAgfAqQgFAGAAAKQAAADACAEQACAFAEACQAEAEAIACQAHACAJAAQASAAAKgHQALgHAAgOQAAgGgEgFQgDgEgGgCIgOgBIgYgBQgNADgGAGgAgQhMQgEABgCAFQgDAEgBAGIgBAMQAAANAGAIQAGAJAJAAQAKAAAGgJQAFgIAAgNQAAgOgGgJQgFgIgKAAQgGAAgEADg");
	this.shape_27.setTransform(22.3,-16.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AAJA+IAAgIIAFgBIAGgBQAEgBABgDQACgCAAgFIAAg9QAAgMgGgHQgHgHgIAAQgGAAgFACIgJAFIgHAGIgDAFIAABEQAAAEABADQACADAEABIAFACIAGABIAAAIIg7AAIAAgIIAGgBIAGgBQADgBABgDQACgCAAgFIAAhJQAAgEgCgEQgBgDgDgCIgGgCIgHgBIAAgIIAogDIACACIAAARIABAAIAHgHIAIgHQAEgDAGgCQAGgCAHAAQASAAAIALQAJALAAASIAAA9IABAHQACADADABIAFACIAGABIAAAIg");
	this.shape_28.setTransform(8.7,-19.2);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgaBdIAAgIIAGgBIAFgBQAEgBABgDQACgDAAgEIAAhJQAAgEgCgEIgFgFIgHgCIgIgCIAAgIIApgDIACACIAABhQABAFABADQACADADABIAGACIAFABIAAAIgAgJhAQgGgFAAgFQAAgIAGgEQAEgGAFAAQAHAAAEAGQAFAEAAAGQAAAHgFAFQgEAFgHABQgFgBgEgFg");
	this.shape_29.setTransform(-2.5,-22.2);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AAfBfIgUgeIgWgeIgKAJIAAAcQABAEABAEQACADADABIAGACIAGABIAAAIIg7AAIAAgIIAGgBIAFgBQAEgBABgDQACgDAAgEIAAiLQAAgEgCgEQgCgFgDgCQgCgCgGAAIgJgBIAAgIIAtgCIABACIAAB+IAVgUIARgTIADgDIABgDQAAgDgGgCIgKgCIAAgIIA1AAIAAAHQgKAEgIAFIgLAIIgJAHIgPAOIAXAeIASAYQAFAIAFACQADACAJABIAAAIg");
	this.shape_30.setTransform(-12.6,-22.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgsA+IAAgIIAFgBIAGgBQADgBACgDQABgCAAgFIAAhJQAAgEgBgDQgCgEgDgCIgGgCIgHgBIAAgIIAogDIACACIAAARIABAAQAGgKAJgFQAKgGAHAAQAIAAAFAFQAFAFAAAJQAAAGgDAFQgDAFgHAAQgHAAgDgEQgEgDAAgFIABgEIAAgFQgFAAgIAFQgIAEgEAJIAABFQAAAEACADQABADADABIAIACIAIABIAAAIg");
	this.shape_31.setTransform(-24.2,-19.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("AgWA8QgKgFgIgIQgIgIgFgMQgFgMAAgOQAAgcARgSQAQgSAaAAQAZAAAQASQARARAAAcQAAAMgEAMQgEAMgIAJQgIAJgLAFQgLAFgNAAQgMAAgKgEgAgOgxQgHAFgEAIQgEAIgCAJIgBASQAAALACAKQABAKAEAIQAFAIAGAEQAGAFAJAAQAPAAAJgPQAJgPAAgZQAAgJgCgKQgCgKgEgIQgEgHgGgFQgGgEgJAAQgJAAgGAEg");
	this.shape_32.setTransform(-36.4,-19);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AAgA9IgghYIggBYIgKAAIgSg2IgPguQgCgFgGgEQgFgDgFgBIAAgIIA1AAIAAAJIgIABQgFABAAADIAAACIABAEIAJAcIANAoIAehVIALAAIAgBUIAKgeIAJgdIACgGIABgFQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBgBAAAAIgFgDIgFgBIgEgBIAAgIIAtAAIAAAIQgFABgGADQgGAEgCAIIgMAiIgMAjIgEAOIgFAOg");
	this.shape_33.setTransform(-52.1,-19);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgUA6QgLgFgHgIQgIgJgDgMQgDgLAAgNQAAgLADgMQAEgLAHgJQAHgJALgFQAKgGAMABQANgBAJAFQAKAEAFAHQAGAHADAJQADAKAAALIAAAHIhPAAQAAAMACAJQACAKAFAHQAFAHAIAEQAGAFALgBQALABAIgGQAIgFAHgNIAIAFQgHAPgNAIQgMAJgRAAQgNAAgLgGgAAagNIgBgOQgBgIgCgGQgDgFgFgEQgFgDgIAAQgLAAgJAKQgIALgBATIA2AAg");
	this.shape_34.setTransform(-73.3,-19);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AgsA+IAAgIIAFgBIAGgBQADgBACgDQABgCAAgFIAAhJQAAgEgBgDQgCgEgDgCIgGgCIgHgBIAAgIIAogDIACACIAAARIABAAQAGgKAJgFQAKgGAHAAQAIAAAFAFQAFAFAAAJQAAAGgDAFQgDAFgHAAQgHAAgDgEQgEgDAAgFIABgEIAAgFQgFAAgIAFQgIAEgEAJIAABFQAAAEACADQABADADABIAIACIAIABIAAAIg");
	this.shape_35.setTransform(-84.3,-19.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AgvA3QgJgIAAgNQAAgIACgFQACgGAEgEQADgDAFgEIAJgEIAXgHQAPgFAGgEIAAgLIAAgHIgDgIQgDgFgEgDQgEgEgHABQgGAAgFABIgHAEIACAHIAAAJQAAAFgDADQgEAEgHAAQgGAAgDgFQgDgEAAgFQAAgGAEgFQAEgFAHgEQAFgDAHgDQAJgDAHABQAJgBAIACQAIACAFAEQAHAEADAIQADAIABAMIgBAfIAAAdQAAAFACADQABACADACIAGABIAIAAIAAAIIgJAEIgKABQgKAAgGgFQgFgEgCgIIgBAAQgIAJgIAEQgJAEgMABQgOAAgJgJgAgEAAQgHADgHAEQgGAEgDAGQgEAGAAAHQAAALAFAFQAGAEAHAAQAKAAAFgEQAGgEAFgGIAAgpg");
	this.shape_36.setTransform(-95.6,-19);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgSA8QgJgEgEgDIgCAIIgKAAIgBgqIAJAAQABAFADAGQADAGAEAGQAFAFAHAEQAGADAIAAQAMAAAGgFQAGgGAAgJQAAgGgCgDQgCgEgEgDIgKgFIgMgEIgMgFQgHgDgFgDQgGgEgDgHQgEgFAAgJQAAgPALgKQALgKATAAQAGAAAHABQAIACAEADIADgGIAJAAIACAmIgJAAQgCgNgJgIQgIgIgMAAQgKAAgFAFQgGAFAAAHQAAAGACAEQACADAEADIAJAEIANAFIAPAGIAMAGQAFAFACAFQADAHAAAIQAAARgNAKQgMAKgUAAQgKAAgIgDg");
	this.shape_37.setTransform(90.5,-50.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgMBIQgGgHAAgOIAAhQIgWAAIAAgNIAXAAIAAglIAVAAIAAAlIAiAAIAAANIgiAAIAABBIABAOQAAAFACADQACADAEACQAEACAHAAIAJAAIAIgCIAAAJIgPAGQgHACgKAAQgPAAgGgIg");
	this.shape_38.setTransform(80.7,-52.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgSA8QgJgEgEgDIgCAIIgKAAIgBgqIAJAAQABAFADAGQADAGAEAGQAFAFAHAEQAGADAIAAQAMAAAGgFQAGgGAAgJQAAgGgCgDQgCgEgEgDIgKgFIgMgEIgMgFQgHgDgFgDQgGgEgDgHQgEgFAAgJQAAgPALgKQALgKATAAQAGAAAHABQAIACAEADIADgGIAJAAIACAmIgJAAQgCgNgJgIQgIgIgMAAQgKAAgFAFQgGAFAAAHQAAAGACAEQACADAEADIAJAEIANAFIAPAGIAMAGQAFAFACAFQADAHAAAIQAAARgNAKQgMAKgUAAQgKAAgIgDg");
	this.shape_39.setTransform(71.1,-50.4);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AgaBdIAAgIIAGgBIAFgBQADgBACgDQABgDAAgEIAAhJQAAgEgBgEIgFgFIgGgCIgJgCIAAgIIAqgDIACACIAABhQgBAFACACQABADAFACIAEACIAGABIAAAIgAgKhAQgEgFAAgGQAAgHAEgEQAFgGAFAAQAHAAAFAGQAEAEAAAGQAAAHgEAFQgGAGgGAAQgFAAgFgGg");
	this.shape_40.setTransform(62,-53.6);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgMBIQgGgHAAgOIAAhQIgWAAIAAgNIAXAAIAAglIAVAAIAAAlIAiAAIAAANIgiAAIAABBIABAOQAAAFACADQACADAEACQAEACAHAAIAJAAIAIgCIAAAJIgPAGQgHACgKAAQgPAAgGgIg");
	this.shape_41.setTransform(54,-52.1);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AAJA+IAAgIIAFgBIAGgBQAEgBABgDQACgCAAgFIAAg9QAAgMgHgHQgFgHgJAAQgGAAgFACIgJAFIgHAGIgDAFIAABEQAAAEABADQACADAEABIAFACIAGABIAAAIIg7AAIAAgIIAGgBIAGgBQACgBACgDQACgCAAgFIAAhJQAAgEgCgEQgCgDgCgCIgGgCIgHgBIAAgIIAogDIACACIAAARIAAAAIAIgHIAIgHQAFgDAFgCQAGgCAHAAQASAAAIALQAJALAAASIAAA9IABAHQABADAEABIAGACIAFABIAAAIg");
	this.shape_42.setTransform(42.5,-50.6);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AgUA6QgLgEgHgJQgIgJgDgMQgDgMAAgMQAAgMADgLQAEgLAHgJQAHgJALgFQAKgFAMAAQANAAAJAEQAKAEAFAHQAGAHADAJQADAKAAALIAAAIIhPAAQAAAKACAKQACAKAFAHQAFAHAIAEQAGAFALAAQALAAAIgGQAIgFAHgNIAIAFQgHAOgNAJQgMAIgRAAQgNABgLgGgAAagNIgBgOQgBgIgCgGQgDgFgFgEQgFgDgIAAQgLAAgJAKQgIALgBATIA2AAg");
	this.shape_43.setTransform(29.2,-50.4);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgaBdIAAgIIAGgBIAFgBQADgBACgDQABgDABgEIAAhJQgBgEgBgEIgFgFIgHgCIgIgCIAAgIIApgDIACACIAABhQAAAFACACQABADAEACIAGACIAFABIAAAIgAgJhAQgGgFAAgGQAAgHAGgEQAEgGAFAAQAHAAAEAGQAFAEAAAGQAAAHgFAFQgEAGgHAAQgFAAgEgGg");
	this.shape_44.setTransform(19.3,-53.6);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AglAuQgOgRAAgdQAAgMAEgLQADgLAJgJQAGgJAMgFQAKgFAMAAQARgBAMAKQALAHAAAPQAAAHgDAEQgDAFgHAAQgHAAgEgEQgEgDAAgFIACgLIACgIQgDgFgEgBIgKgBQgEAAgFACQgGADgFAGQgEAHgDAKQgDAKAAAPQAAAVAKAPQAKAPAQAAQALgBAJgFQAHgGAHgMIAIAGQgIAOgNAIQgOAJgNgBQgZAAgQgRg");
	this.shape_45.setTransform(10.5,-50.4);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("AgSA8QgJgEgEgDIgCAIIgKAAIgBgqIAJAAQABAFADAGQADAGAEAGQAFAFAHAEQAGADAIAAQAMAAAGgFQAGgGAAgJQAAgGgCgDQgCgEgEgDIgKgFIgMgEIgMgFQgHgDgFgDQgGgEgDgHQgEgFAAgJQAAgPALgKQALgKATAAQAGAAAHABQAIACAEADIADgGIAJAAIACAmIgJAAQgCgNgJgIQgIgIgMAAQgKAAgFAFQgGAFAAAHQAAAGACAEQACADAEADIAJAEIANAFIAPAGIAMAGQAFAFACAFQADAHAAAIQAAARgNAKQgMAKgUAAQgKAAgIgDg");
	this.shape_46.setTransform(-1.1,-50.4);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AgsA+IAAgIIAFgBIAGgBQADgBACgDQABgCAAgFIAAhJQAAgEgBgDQgCgEgDgCIgGgCIgHgBIAAgIIAogDIACACIAAARIABAAQAGgKAJgFQAKgGAHAAQAIAAAFAFQAFAFAAAJQAAAGgDAFQgDAFgHAAQgHAAgDgEQgEgDAAgFIABgEIAAgFQgFAAgIAFQgIAEgEAJIAABFQAAAEACADQABADADABIAIACIAIABIAAAIg");
	this.shape_47.setTransform(-17.2,-50.6);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("AgmA0QgJgKAAgUIAAg5QAAgEgBgDQgCgDgEgCIgFgDIgHgBIAAgIIAogDIACACIAABTQAAANAGAHQAGAGAIAAQAGAAAFgCIAJgEIAGgGIADgFIAAhEQAAgDgBgEQgCgDgDgCQgCgCgEAAIgKgBIAAgIIArgDIADACIAABfQAAAEABADIAFAFIAFACIAHAAIAAAIIgoADIgCgBIAAgQIAAAAIgHAHIgIAGIgKAFQgFABgJAAQgQAAgIgKg");
	this.shape_48.setTransform(-29.9,-50.3);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AgWA8QgKgFgIgIQgIgIgFgMQgFgMAAgOQAAgcARgSQAQgSAaAAQAZAAAQASQARARAAAcQAAAMgEAMQgEAMgIAJQgIAJgLAFQgLAFgNAAQgMAAgKgEgAgOgxQgHAFgEAIQgEAIgCAJIgBASQAAALACAKQABAKAEAIQAFAIAGAEQAGAFAJAAQAPAAAJgPQAJgPAAgZQAAgJgCgKQgCgKgEgIQgEgHgGgFQgGgEgJAAQgJAAgGAEg");
	this.shape_49.setTransform(-43.7,-50.4);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AghBcQgJgFgHgIQgIgJgEgMQgEgLAAgPQAAgNAFgLQAEgLAIgJQAHgIALgFQALgFALAAQAIAAAIACQAIACAGAEIAAgqQAAgFgCgFQgCgEgDgCQgDgCgGgBIgMgCIAAgIIAxgCIACACIAAChQAAAEABADQACADADACQACACAFAAIAIAAIAAAJIgqACIgCgBIAAgMIgBAAQgGAHgKAFQgIAEgKAAQgKAAgKgEgAgTgRQgGAEgFAHQgEAGgDAKQgCALAAANQAAAKACAIQABAJAFAHQAEAHAHAEQAHAEAJAAQAIAAAHgEQAGgEAFgGIAAhFIgDgHIgGgHIgIgFQgFgCgFAAQgIAAgGAEg");
	this.shape_50.setTransform(-63.3,-53.7);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("AAJA+IAAgIIAFgBIAGgBQAEgBABgDQACgCAAgFIAAg9QAAgMgHgHQgFgHgJAAQgGAAgFACIgKAFIgGAGIgDAFIAABEQAAAEABADQACADAEABIAFACIAGABIAAAIIg7AAIAAgIIAGgBIAGgBQACgBACgDQACgCAAgFIAAhJQAAgEgCgEQgCgDgCgCIgGgCIgHgBIAAgIIAogDIACACIAAARIAAAAIAIgHIAIgHQAFgDAFgCQAGgCAHAAQASAAAIALQAJALAAASIAAA9IABAHQABADAEABIAGACIAFABIAAAIg");
	this.shape_51.setTransform(-78.1,-50.6);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#000000").s().p("AARBYIAAgJIAQgCQAGgCAAgDIAAgDIgBgCIgOgnIg8AAIgFAPIgEALIgCAJIgBAFQAAAFAIADQAHADAKAAIAAAJIhBAAIAAgJIAIgBIAHgDIAIgHIAFgKIAdhJIAchIIAJAAIA6CVIAEAHIAGAGIAIADIAHABIAAAJgAAUARIgahCIgaBCIA0AAg");
	this.shape_52.setTransform(-93.9,-53.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(-104.3,-69.3,204.9,126.6), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgLAMQgFgFAAgHQAAgGAFgFQAFgFAGAAQAHAAAFAFQAFAFAAAGQAAAHgFAFQgFAFgHAAQgGAAgFgFg");
	this.shape.setTransform(188.2,23.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgsBRQgOgIAAgPQAAgMAKgIQAKgHAPAAIAAgDIgIgCIgGgEIgFgGQgCgEAAgFQAAgGAEgEQAFgGAJgEIAAgBQgMgGgGgJQgHgJAAgKQAAgSANgLQANgLAUAAIAKACIALACIAqAAIAAAMIgcAAIAAAAQAEAGACAGQACAGAAAHQAAAPgMAMQgNALgQgBIgPAAIgGAEQgDACAAAEQAAAEACADIAHADIAIACIAKAAIANABIAOAAQAFAAAGADQAGACAEAFQAFAEADAGQADAGAAAJQAAAIgEAIQgEAHgIAGQgIAGgLADQgLADgQAAQgcAAgNgIgAgfAqQgFAGAAAKQAAADACAFQACADAEADQAEAEAIACQAHACAJAAQASAAAKgHQALgHAAgOQAAgGgEgFQgDgEgGgCIgOgBIgYgBQgNADgGAGgAgQhMQgEACgCAEQgDAEgBAGIgBAMQAAANAGAIQAGAJAJAAQAKAAAGgJQAFgIAAgNQAAgOgGgJQgFgIgKAAQgGAAgEADg");
	this.shape_1.setTransform(178.5,21.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AAJA+IAAgIIAFgBIAGgBQAEgBABgDQACgCAAgFIAAg9QAAgMgGgHQgHgHgIAAQgGAAgFACIgJAFIgHAGIgDAFIAABEQAAAEABADQACADAEABIAFACIAGABIAAAIIg7AAIAAgIIAGgBIAGgBQADgBABgDQACgCAAgFIAAhJQAAgEgCgEQgBgDgDgCIgGgCIgHgBIAAgIIAogDIACACIAAARIABAAIAHgHIAIgHQAEgDAGgCQAGgCAHAAQASAAAIALQAJALAAASIAAA9IABAHQACADADABIAFACIAGABIAAAIg");
	this.shape_2.setTransform(164.8,18.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgaBdIAAgIIAGgBIAFgBQAEgBABgDQACgDAAgEIAAhJQAAgEgCgEIgFgFIgHgCIgIgCIAAgIIAqgDIABACIAABhQABAFABACQACADADACIAGACIAFABIAAAIgAgJhAQgGgFAAgGQAAgHAGgEQAEgGAFAAQAHAAAFAGQAEAEAAAGQAAAHgEAFQgFAGgHAAQgFAAgEgGg");
	this.shape_3.setTransform(153.7,15.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAJA+IAAgIIAFgBIAGgBQAEgBABgDQACgCAAgFIAAg9QAAgMgGgHQgHgHgIAAQgGAAgFACIgJAFIgHAGIgDAFIAABEQAAAEABADQACADAEABIAFACIAGABIAAAIIg7AAIAAgIIAGgBIAGgBQADgBABgDQACgCAAgFIAAhJQAAgEgCgEQgBgDgDgCIgGgCIgHgBIAAgIIAogDIACACIAAARIABAAIAHgHIAIgHQAEgDAGgCQAGgCAHAAQASAAAIALQAJALAAASIAAA9IABAHQACADADABIAFACIAGABIAAAIg");
	this.shape_4.setTransform(142.8,18.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgUA6QgLgEgHgJQgIgJgDgMQgDgMAAgMQAAgMADgLQAEgLAHgJQAHgJALgFQAKgFAMAAQANAAAJAEQAKAEAFAHQAGAHADAJQADAKAAALIAAAIIhPAAQAAAKACAKQACAKAFAHQAFAHAIAEQAGAFALAAQALAAAIgGQAIgFAHgNIAIAFQgHAOgNAJQgMAIgRAAQgNABgLgGgAAagNIgBgOQgBgIgCgGQgDgFgFgEQgFgDgIAAQgLAAgJAKQgIALgBATIA2AAg");
	this.shape_5.setTransform(129.5,18.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgMBIQgGgHAAgOIAAhQIgWAAIAAgNIAXAAIAAglIAVAAIAAAlIAiAAIAAANIgiAAIAABBIABAOQAAAFACADQACADAEACQAEACAHAAIAJAAIAIgCIAAAJIgPAGQgHACgKAAQgPAAgGgIg");
	this.shape_6.setTransform(118.9,17.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgSA8QgJgEgEgDIgCAIIgKAAIgBgqIAJAAQABAFADAGQADAGAEAGQAFAFAHAEQAGADAIAAQAMAAAGgFQAGgGAAgJQAAgGgCgDQgCgEgEgDIgKgFIgMgEIgMgFQgHgDgFgDQgGgEgDgHQgEgFAAgJQAAgPALgKQALgKATAAQAGAAAHABQAIACAEADIADgGIAJAAIACAmIgJAAQgCgNgJgIQgIgIgMAAQgKAAgFAFQgGAFAAAHQAAAGACAEQACADAEADIAJAEIANAFIAPAGIAMAGQAFAFACAFQADAHAAAIQAAARgNAKQgMAKgUAAQgKAAgIgDg");
	this.shape_7.setTransform(109.2,18.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AgaBdIAAgIIAGgBIAFgBQADgBACgDQACgDgBgEIAAhJQABgEgCgEIgFgFIgGgCIgJgCIAAgIIAqgDIACACIAABhQgBAFACACQACADAEACIAEACIAGABIAAAIgAgKhAQgEgFAAgGQAAgHAEgEQAFgGAFAAQAHAAAFAGQAEAEAAAGQAAAHgEAFQgGAGgGAAQgFAAgFgGg");
	this.shape_8.setTransform(100.2,15.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgZBfIAAgIIAGgBIAFgBQAEgBACgDQABgDAAgEIAAiKQAAgFgCgEQgCgDgDgDIgIgDIgKgBIAAgIIAtgCIACACIAACjQAAAFACACQABADADACIAGACIAGABIAAAIg");
	this.shape_9.setTransform(92.7,15.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgUA6QgLgEgHgJQgIgJgDgMQgDgMAAgMQAAgMADgLQAEgLAHgJQAHgJALgFQAKgFAMAAQANAAAJAEQAKAEAFAHQAGAHADAJQADAKAAALIAAAIIhPAAQAAAKACAKQACAKAFAHQAFAHAIAEQAGAFALAAQALAAAIgGQAIgFAHgNIAIAFQgHAOgNAJQgMAIgRAAQgNABgLgGgAAagNIgBgOQgBgIgCgGQgDgFgFgEQgFgDgIAAQgLAAgJAKQgIALgBATIA2AAg");
	this.shape_10.setTransform(77.6,18.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgsA+IAAgIIAFgBIAGgBQADgBACgDQABgCAAgFIAAhJQAAgEgBgDQgCgEgDgCIgGgCIgHgBIAAgIIAogDIACACIAAARIABAAQAGgKAJgFQAKgGAHAAQAIAAAFAFQAFAFAAAJQAAAGgDAFQgDAFgHAAQgHAAgDgEQgEgDAAgFIABgEIAAgFQgFAAgIAFQgIAEgEAJIAABFQAAAEACADQABADADABIAIACIAIABIAAAIg");
	this.shape_11.setTransform(66.6,18.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AgDAjIgGgjQgEgPAAgFQAAgFAEgEQADgEAGAAQAHAAADAEQAEAEAAAFQAAAGgDANIgHAkg");
	this.shape_12.setTransform(58.5,9.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgUA6QgLgEgHgJQgIgJgDgMQgDgMAAgMQAAgMADgLQAEgLAHgJQAHgJALgFQAKgFAMAAQANAAAJAEQAKAEAFAHQAGAHADAJQADAKAAALIAAAIIhPAAQAAAKACAKQACAKAFAHQAFAHAIAEQAGAFALAAQALAAAIgGQAIgFAHgNIAIAFQgHAOgNAJQgMAIgRAAQgNABgLgGgAAagNIgBgOQgBgIgCgGQgDgFgFgEQgFgDgIAAQgLAAgJAKQgIALgBATIA2AAg");
	this.shape_13.setTransform(50,18.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AAqBYIgriFIguCFIgKAAIgZhYIgSg+IgCgHIgHgEIgHgDIgHgCIAAgJIBGAAIAAAJIgPACQgHABAAADIABADIAAAEIAKAkIAVBIIArh/IAMAAIArCCIAPg0IALgnIAEgPIAAgHQAAgFgGgCQgFgDgNgBIAAgJIA/AAIAAAJIgHACIgIADIgGAGQgDADgCAHIgUBBIgZBQg");
	this.shape_14.setTransform(31.8,16.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(17.3,0,176.3,32.4), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AABAfIANgHIALgIIAIgJQAEgFACgHIgHAAQgJAAgEgEQgFgFAAgGQAAgHAGgGQAGgHAJAAQALAAAFAGQAEAFAAAKQAAAMgFAKQgFAKgIAHQgIAHgJAGIgPAIgAg2AfIANgHIALgIIAIgJQAEgFACgHIgHAAQgJAAgEgEQgFgFAAgGQAAgHAGgGQAGgHAJAAQALAAAFAGQAEAFAAAKQAAAMgFAKQgFAKgIAHQgIAHgJAGIgPAIg");
	this.shape.setTransform(447.9,49.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgNAOQgHgFAAgJQAAgHAHgHQAGgFAHAAQAJAAAGAFQAGAHAAAHQAAAJgGAFQgGAHgJgBQgHABgGgHg");
	this.shape_1.setTransform(435.4,66.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgvBHQgPgIABgNQgBgGAFgFQAEgGAGAAQAHAAAEADQADADACAEIAFAJIADAJIAGAFQAEACAHAAQAQAAAIgIQAJgIAAgOQgBgLgHgGQgJgGgOgFIgNgGQgIgDgFgEQgFgEgDgHQgDgHgBgJQABgTARgOQARgPAZAAIAMABIAPADQAIADAEAFQAFAEABAIQAAAGgFAFQgEAFgHAAQgFAAgEgCQgEgDgCgEIgEgJIgEgJIgEgBIgHgBQgNAAgIAIQgHAIAAALQAAALAGAFQAHAFAPAGQAUAIAKAIQAJAKAAAOQAAAXgRAOQgTAPgZAAQgWAAgQgIg");
	this.shape_2.setTransform(424.6,61.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgfBxQgGgHAAgJIABgHIACgKIAjieIACgHIAAgEQAAgGgCgDQgBgDgDgBIgIgCIgKgBIACgJIA4gEIABADIgpC1IgDALIgBAKQAAAIAEAEQADADAIAAIAJgBIAJgCIgCAKIgVAIQgGACgJAAQgNAAgGgGg");
	this.shape_3.setTransform(414.5,57.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgyBAQgOgPAAgcQAAgTAGgQQAGgRAMgPQALgOAQgJQAPgIAUAAQAWgBAKAKQALAIAAAOQAAAQgKAMQgKALgTAHQgPAEgNADIggAGQAAAYAJANQAJAMAQAAQAPAAAMgHQALgIAMgPIAIAGQgMATgSAKQgSAMgTgBQgaAAgPgOgAgNgvQgQAUgEAdIAYgDQAMgDAJgFQANgGAGgKQAGgKAAgOQAAgGgCgEIgEgFIgGgCIgGAAQgSAAgOATg");
	this.shape_4.setTransform(402.2,61.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag8BFQgHgJAAgNIAAgJIADgPIAMguIADgMIABgKQAAgJgEgDQgDgCgIAAIgJABIgIACIADgKIAVgIQAIgCAGgBQAMABAGAFQAFAGABAKIgBAHIgCAKIgNA3IgDAMIAAAJQAAAKADAGQAFAFAKAAQAJAAAKgEQAKgGAKgKIAahxIAbgCIABACIgWBhIgCANIgCAIQAAAJAEADQAEADAIAAIAIgBIAIgCIgCAKIgUAIQgJACgHAAQgNAAgFgHQgHgHAAgKIgBAAIgMALIgNAHIgMAGQgHACgJgBQgPAAgIgIg");
	this.shape_5.setTransform(385.8,61.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhhCSQgGgFAAgIQAAgGAEgFQAEgFAHAAQAFAAAEACIAGAFIAFAHIAEAIQAMgBAIgPQAIgPAHgcIAbiBIgdAAIADgOIAcAAIACgKQAEgSAIgOQAIgOAKgKQAKgKAMgFQANgGALAAQANAAAHAGQAGAFAAAHQAAAHgEAFQgDAFgIAAQgFAAgEgCIgGgGIgFgHIgEgHQgLAAgIAOQgIANgGAfIgEAQIAnAAIgEAOIglAAIgaB8QgHAhgXAWQgXAVgYAAQgNAAgHgFg");
	this.shape_6.setTransform(371.6,60.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgfBxQgGgHAAgJIABgHIACgKIAjieIACgHIAAgEQAAgGgCgDQgBgDgDgBIgIgCIgKgBIACgJIA4gEIABADIgpC1IgDALIgBAKQAAAIAEAEQADADAIAAIAJgBIAJgCIgCAKIgVAIQgGACgJAAQgNAAgGgGg");
	this.shape_7.setTransform(355.7,57.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgZBuQgGgGAAgJIABgIIABgJIAQhBIADgLIABgJQAAgJgDgCQgDgDgIAAIgJABIgIACIACgKIAVgIQAJgDAGAAQALAAAGAGQAFAGABAKIgBAIIgCAJIgQA/IgCAMIgBAJQAAAJADADQAEADAIAAIAJAAIAIgCIgCAJIgXAIIgNACQgMAAgGgGgAAJhQQgGgHAAgHQAAgJAGgGQAFgGAIAAQAJAAAFAGQAFAFAAAIQAAAJgFAGQgFAHgJAAQgIAAgFgGg");
	this.shape_8.setTransform(346.5,57.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AguBHQgPgIgBgNQABgGAEgFQAEgGAHAAQAGAAAEADQADADADAEIADAJIADAJIAGAFQAEACAIAAQAPAAAJgIQAIgIAAgOQABgLgJgGQgHgGgPgFIgNgGQgIgDgEgEQgGgEgDgHQgEgHAAgJQAAgTASgOQARgPAYAAIANABIAPADQAHADAFAFQAGAEgBAIQAAAGgEAFQgEAFgHAAQgGAAgDgCQgDgDgDgEIgEgJIgDgJIgGgBIgFgBQgPAAgHAIQgIAIAAALQABALAGAFQAHAFAPAGQAVAIAJAIQAJAKAAAOQAAAXgRAOQgSAPgaAAQgWAAgPgIg");
	this.shape_9.setTransform(334.4,61.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgvBHQgPgIABgNQgBgGAFgFQAEgGAGAAQAHAAAEADQADADACAEIAFAJIADAJIAGAFQAEACAHAAQAQAAAIgIQAJgIAAgOQgBgLgHgGQgJgGgOgFIgNgGQgIgDgFgEQgFgEgDgHQgDgHgBgJQAAgTASgOQARgPAZAAIAMABIAPADQAIADAEAFQAFAEABAIQAAAGgFAFQgEAFgHAAQgFAAgEgCQgEgDgCgEIgEgJIgEgJIgEgBIgHgBQgNAAgIAIQgHAIAAALQAAALAGAFQAHAFAPAGQAUAIAKAIQAJAKAAAOQAAAXgRAOQgTAPgZAAQgWAAgQgIg");
	this.shape_10.setTransform(321.1,61.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag4A/QgQgRAAgbQAAgTAHgSQAGgRALgNQAMgNARgIQAQgJATAAQAbAAAPARQAPAQAAAbQAAASgGARQgGASgMANQgLAOgRAIQgQAJgVAAQgZAAgPgQgAgKg7QgLAIgIARQgGANgDAQQgDAQAAANQAAAWAHALQAIALAPAAQAMAAALgIQAKgJAHgNQAGgNAEgQQADgQAAgRQAAgVgHgLQgIgLgOAAQgNAAgKAIg");
	this.shape_11.setTransform(306.2,61.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhhCSQgGgFAAgIQAAgGAEgFQAEgFAHAAQAFAAAEACIAGAFIAFAHIAEAIQAMgBAIgPQAIgPAHgcIAbiBIgdAAIADgOIAcAAIACgKQAEgSAIgOQAIgOAKgKQAKgKAMgFQANgGALAAQANAAAHAGQAGAFAAAHQAAAHgEAFQgDAFgIAAQgFAAgEgCIgGgGIgFgHIgEgHQgLAAgIAOQgIANgGAfIgEAQIAnAAIgEAOIglAAIgaB8QgHAhgXAWQgXAVgYAAQgNAAgHgFg");
	this.shape_12.setTransform(292.7,60.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAYBHQgGgGAAgJIAAgHIACgKIAPg3IADgMIABgJQAAgKgFgGQgEgGgKAAQgKAAgKAGQgLAGgKAMIgaBuIgcAAIAWhhIACgKIACgMQAAgIgDgDQgDgDgJAAIgIABIgIACIACgKIAWgHQAIgDAHAAQAMAAAFAHQAFAGAAAMIABAAQARgOALgGQAMgHAPAAQAPAAAIAJQAJAIAAAOIgBAJIgDAOIgNAwIgCALIgCAKQAAAJAEADQAEADAIAAIAIgBIAJgCIgCAJIgVAIQgIADgIAAQgMAAgGgHg");
	this.shape_13.setTransform(477.2,21.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("Ag4A/QgQgRAAgbQAAgTAHgSQAGgRALgNQAMgNARgIQAQgJATAAQAbAAAPARQAPAQAAAbQAAASgGARQgGASgMANQgLAOgRAIQgQAJgVAAQgZAAgPgQgAgKg7QgLAIgIARQgGANgDAQQgDAQAAANQAAAWAHALQAIALAPAAQAMAAALgIQAKgJAHgNQAGgNAEgQQADgQAAgRQAAgVgHgLQgIgLgOAAQgNAAgKAIg");
	this.shape_14.setTransform(459.5,22);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgpBcQgHgGAAgLIABgGIABgHIAYhkIgbAAIADgPIAbAAIALgsIAaAAIgKAsIAqAAIgDAPIgqAAIgSBSIgDALIgBAJQAAAIAFAFQAEADAKAAIALgBIALgCIgDALIgUAHQgIACgNAAQgOAAgHgFg");
	this.shape_15.setTransform(439.7,20);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAYBHQgGgGAAgJIAAgHIACgKIAPg3IADgMIABgJQAAgKgFgGQgEgGgKAAQgKAAgKAGQgLAGgKAMIgaBuIgcAAIAWhhIACgKIACgMQAAgIgDgDQgDgDgIAAIgJABIgIACIACgKIAWgHQAIgDAHAAQAMAAAFAHQAFAGABAMIAAAAQARgOALgGQAMgHAPAAQAPAAAIAJQAJAIAAAOIgBAJIgDAOIgNAwIgCALIgCAKQAAAJAEADQAEADAIAAIAIgBIAJgCIgCAJIgVAIQgIADgIAAQgMAAgGgHg");
	this.shape_16.setTransform(424.1,21.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhBA/QgNgPAAgcQAAgTAHgQQAHgTAMgNQAMgOAQgIQAQgJAQABQAKAAAKACQAKADAGAEIAcgHIABACIgWBhIgDALIgCAKQABAJADADQAEADAIAAIAJgBIAIgCIgCAKIgVAIQgGACgKAAQgLAAgGgHQgHgFAAgLIgBAAIgIAHIgKAIIgNAHQgHADgIgBQgWAAgMgPgAgKg7QgKAHgJAMQgHALgGARQgEAPAAASIABAPQABAIACAGQAEAFAEAEQAGADAJAAQAIAAAJgFQAJgFALgLIAThRIgBgKQgBgEgDgEQgDgEgFgDQgGgBgIAAQgKgBgKAIg");
	this.shape_17.setTransform(406,22);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgZBuQgGgGAAgJIAAgIIACgJIAQhBIADgLIABgJQAAgJgDgCQgDgDgIAAIgJABIgJACIADgKIAVgIQAJgDAGAAQALAAAGAGQAFAGABAKIgBAIIgCAJIgQA/IgCAMIgBAJQAAAJADADQAEADAIAAIAIAAIAJgCIgCAJIgXAIIgNACQgMAAgGgGgAAJhQQgGgHAAgHQAAgJAGgGQAGgGAHAAQAJAAAFAGQAGAFgBAIQABAJgGAGQgGAHgIAAQgHAAgGgGg");
	this.shape_18.setTransform(393.1,18.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgfBxQgGgHAAgJIABgHIACgKIAjieIACgHIAAgEQAAgGgCgDQgBgDgDgBIgIgCIgKgBIACgJIA4gEIABADIgpC1IgDALIgBAKQAAAIAEAEQADADAIAAIAJgBIAJgCIgCAKIgVAIQgGACgJAAQgNAAgGgGg");
	this.shape_19.setTransform(384.3,17.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgyBAQgOgPAAgcQAAgTAGgQQAGgSAMgOQALgOAQgJQAPgJAUABQAWAAAKAJQALAIAAAOQAAAQgKAMQgKALgTAHQgPAEgNADIggAGQAAAYAJANQAJAMAQAAQAPAAAMgIQALgHAMgPIAIAGQgMASgSAMQgSALgTgBQgaAAgPgOgAgNgvQgQAUgEAdIAYgDQAMgDAJgFQANgGAGgLQAGgJAAgOQAAgHgCgDIgEgFIgGgCIgGAAQgSAAgOATg");
	this.shape_20.setTransform(371.9,22);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("Ag8BNIAWhhIACgLIACgMQAAgIgDgDQgDgCgJAAIgIABIgIABIACgJIAVgIQAJgDAGABQANAAAFAGQAFAHAAANIABAAQARgQAJgGQAJgHALABIAJABQAEABAEADQADADACAEQABAEAAAIIgBAJIgEAJIgFAGQgEACgGAAQgIAAgEgDQgEgEAAgFQAAgFACgGIAFgMIgGACIgKADIgOAJIgOAPIgZBsg");
	this.shape_21.setTransform(357.9,21.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgvBHQgOgIAAgNQgBgGAFgFQAFgGAFAAQAHAAADADQAEADACAEIAFAJIADAJIAGAFQAEACAHAAQAQAAAIgIQAJgIAAgOQgBgLgHgGQgJgGgOgFIgNgGQgIgDgFgEQgFgEgDgHQgEgHABgJQAAgTARgOQARgPAZAAIAMABIAPADQAIADAEAFQAFAEABAIQAAAGgFAFQgEAFgHAAQgFAAgEgCQgDgDgDgEIgEgJIgEgJIgEgBIgHgBQgNAAgIAIQgHAIAAALQAAALAGAFQAHAFAPAGQAUAIAKAIQAJAKAAAOQAAAXgSAOQgRAPgaAAQgXAAgPgIg");
	this.shape_22.setTransform(335.8,22);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgvBHQgPgIAAgNQAAgGAFgFQAFgGAFAAQAHAAADADQAEADADAEIADAJIAEAJIAFAFQAFACAHAAQAPAAAJgIQAIgIAAgOQABgLgJgGQgHgGgPgFIgNgGQgIgDgEgEQgGgEgDgHQgDgHAAgJQAAgTARgOQARgPAYAAIANABIAPADQAHADAGAFQAEAEAAAIQABAGgFAFQgEAFgHAAQgFAAgEgCQgEgDgCgEIgEgJIgEgJIgFgBIgFgBQgPAAgHAIQgIAIAAALQAAALAHAFQAHAFAPAGQAVAIAJAIQAJAKAAAOQAAAXgSAOQgRAPgaAAQgXAAgPgIg");
	this.shape_23.setTransform(322.5,22);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgyBAQgOgPAAgcQAAgTAGgQQAGgSAMgOQALgOAQgJQAPgJAUABQAWAAAKAJQALAIAAAOQAAAQgKAMQgKALgTAHQgPAEgNADIggAGQAAAYAJANQAJAMAQAAQAPAAAMgIQALgHAMgPIAIAGQgMASgSAMQgSALgTgBQgaAAgPgOgAgNgvQgQAUgEAdIAYgDQAMgDAJgFQANgGAGgLQAGgJAAgOQAAgHgCgDIgEgFIgGgCIgGAAQgSAAgOATg");
	this.shape_24.setTransform(308.9,22);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgfBxQgGgHAAgJIABgHIACgKIAjieIACgHIAAgEQAAgGgCgDQgBgDgDgBIgIgCIgKgBIACgJIA4gEIABADIgpC1IgDALIgBAKQAAAIAEAEQADADAIAAIAJgBIAJgCIgCAKIgVAIQgGACgJAAQgNAAgGgGg");
	this.shape_25.setTransform(297.8,17.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgyBAQgOgPAAgcQAAgTAGgQQAGgSAMgOQALgOAQgJQAPgJAUABQAWAAAKAJQALAIAAAOQAAAQgKAMQgKALgTAHQgPAEgNADIggAGQAAAYAJANQAJAMAQAAQAPAAAMgIQALgHAMgPIAIAGQgMASgSAMQgSALgTgBQgaAAgPgOgAgNgvQgQAUgEAdIAYgDQAMgDAJgFQANgGAGgLQAGgJAAgOQAAgHgCgDIgEgFIgGgCIgGAAQgSAAgOATg");
	this.shape_26.setTransform(278,22);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgjB1QgKgCgHgDQgHgFgFgEIgIgLIAnirIABgGIAAgFQAAgFgBgEQgCgDgEgBIgIgBIgKgCIADgJIA3gEIABADIgWBlIABAAQANgMAKgFQAKgFAKAAQAXAAANAQQANAQABAZQAAAUgIATQgHASgMANQgMAOgPAIQgQAHgRABQgNAAgJgDgAACgTIgJAGIgIAGIgJAHIgTBYIACAHIAGAHQAEADAGACQAFACAGAAQAMAAAKgHQAKgIAIgLQAIgNAEgRQAEgQAAgQIgBgQQgCgIgDgFQgEgGgFgDQgHgDgJgBQgFAAgEACg");
	this.shape_27.setTransform(262.1,17.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("Ag4A/QgQgRAAgbQAAgTAHgSQAGgRALgNQAMgNARgIQAQgJATAAQAbAAAPARQAPAQAAAbQAAASgGARQgGASgMANQgLAOgRAIQgQAJgVAAQgZAAgPgQgAgKg7QgLAIgIARQgGANgDAQQgDAQAAANQAAAWAHALQAIALAPAAQAMAAALgIQAKgJAHgNQAGgNAEgQQADgQAAgRQAAgVgHgLQgIgLgOAAQgNAAgKAIg");
	this.shape_28.setTransform(482.4,-17.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgpBcQgHgGAAgLIABgGIABgHIAYhkIgbAAIADgPIAbAAIALgsIAaAAIgKAsIAqAAIgDAPIgqAAIgSBSIgDALIgBAJQAAAIAFAFQAEADAKAAIALgBIALgCIgDALIgUAHQgIACgNABQgOgBgHgFg");
	this.shape_29.setTransform(470,-19.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AguBHQgPgIgBgNQABgGAEgFQAEgGAHAAQAGAAAEADQADADACAEIAFAJIACAJIAHAFQADACAIAAQAQAAAIgIQAJgIAAgOQAAgLgJgGQgIgGgOgFIgNgGQgIgDgEgEQgGgEgDgHQgDgHgBgJQAAgTASgOQARgPAZAAIAMABIAPADQAIADAEAFQAGAEAAAIQgBAGgEAFQgEAFgHAAQgGAAgDgCQgEgDgCgEIgEgJIgDgJIgGgBIgGgBQgOAAgHAIQgHAIgBALQABALAGAFQAHAFAPAGQAVAIAJAIQAJAKAAAOQAAAXgRAOQgTAPgZAAQgWAAgPgIg");
	this.shape_30.setTransform(449.1,-17.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AhJBoQgMgQAAgbQAAgTAHgSQAGgSAMgNQAMgNAPgIQARgJAQAAQAKAAAKADQALADAGAEIANg0IABgGIAAgFQAAgGgCgCQgCgDgEgCIgKgBIgLgCIACgJIA9gDIABACIgqC1IgCALIgBAKQgBAJAEADQAEADAIAAIAIgBIAIgCIgCAKIgUAIQgJACgHAAQgLAAgHgGQgGgGAAgLIgBAAIgJAHIgJAIIgOAHQgGACgJAAQgWAAgNgPgAgTgTQgKAIgIALQgIALgEARQgEAQgBARIABAQQABAHAEAGQACAGAGADQAFAEAIAAQAJAAAJgFQAKgFAMgNIAThRIgDgJIgEgHQgEgEgFgCQgGgDgIAAQgLAAgKAHg");
	this.shape_31.setTransform(434.4,-21.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgyBAQgOgPAAgcQAAgTAGgQQAGgSAMgOQALgOAQgJQAPgJAUABQAWAAAKAJQALAIAAAOQAAARgKALQgKAMgTAGQgPAEgNADIggAGQAAAXAJAOQAJAMAQAAQAPAAAMgIQALgHAMgPIAIAGQgMASgSAMQgSALgTgBQgaAAgPgOgAgNgvQgQAUgEAdIAYgDQAMgDAJgFQANgGAGgLQAGgJAAgOQAAgHgCgDIgEgFIgGgCIgGAAQgSAAgOATg");
	this.shape_32.setTransform(417.7,-17.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgyBAQgOgPAAgcQAAgTAGgQQAGgSAMgOQALgOAQgJQAPgJAUABQAWAAAKAJQALAIAAAOQAAARgKALQgKAMgTAGQgPAEgNADIggAGQAAAXAJAOQAJAMAQAAQAPAAAMgIQALgHAMgPIAIAGQgMASgSAMQgSALgTgBQgaAAgPgOgAgNgvQgQAUgEAdIAYgDQAMgDAJgFQANgGAGgLQAGgJAAgOQAAgHgCgDIgEgFIgGgCIgGAAQgSAAgOATg");
	this.shape_33.setTransform(403.1,-17.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAYBHQgGgGAAgJIAAgHIACgKIAPg3IADgMIABgJQAAgKgFgGQgFgGgJAAQgJAAgLAGQgLAGgKAMIgaBuIgcAAIAWhhIACgKIACgMQAAgIgDgDQgDgDgIAAIgJABIgIACIACgKIAWgHQAIgDAHAAQAMAAAFAHQAFAGABAMIAAAAQARgOALgGQAMgHAPAAQAPAAAIAJQAJAIAAAOIgBAJIgDAOIgNAwIgCALIgCAKQAAAJAEADQAEADAIAAIAIgBIAJgCIgCAJIgWAIQgHADgIAAQgMAAgGgHg");
	this.shape_34.setTransform(386.6,-17.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AhBA/QgNgPAAgcQAAgTAHgRQAHgRAMgOQAMgOAQgIQAQgJAQABQALAAAJADQAKADAFADIAcgHIACACIgWBhIgDALIgCAKQAAAJAEADQAEADAIAAIAJgBIAIgCIgCAKIgVAIQgGACgKAAQgLAAgGgHQgHgFAAgLIgBAAIgIAHIgKAIIgNAHQgHACgIAAQgWAAgMgPgAgKg7QgKAHgJAMQgHALgGARQgEAQAAARIAAAPQABAIADAGQAEAGAEADQAGADAJAAQAIAAAJgFQAJgFALgLIAThRIgBgKQgBgEgDgEQgDgEgFgDQgGgBgIAAQgKgBgKAIg");
	this.shape_35.setTransform(361.1,-17.3);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AhIBoQgNgQAAgbQAAgTAHgSQAGgSAMgNQAMgNAPgIQARgJAQAAQAKAAAKADQALADAGAEIANg0IABgGIAAgFQAAgGgCgCQgCgDgEgCIgKgBIgLgCIACgJIA9gDIABACIgqC1IgCALIgBAKQgBAJAEADQAEADAIAAIAIgBIAIgCIgCAKIgUAIQgJACgHAAQgLAAgGgGQgHgGAAgLIgBAAIgJAHIgKAIIgNAHQgGACgJAAQgWAAgMgPgAgTgTQgKAIgIALQgIALgEARQgEAQgBARIABAQQABAHAEAGQACAGAGADQAFAEAIAAQAJAAAJgFQAKgFAMgNIAThRIgDgJIgEgHQgEgEgFgCQgGgDgIAAQgLAAgKAHg");
	this.shape_36.setTransform(344,-21.4);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AhBA/QgNgPAAgcQAAgTAHgRQAHgRAMgOQAMgOAQgIQAQgJAQABQALAAAJADQAKADAGADIAbgHIACACIgWBhIgDALIgCAKQAAAJAEADQAEADAIAAIAIgBIAJgCIgCAKIgVAIQgGACgKAAQgLAAgGgHQgHgFAAgLIgBAAIgIAHIgKAIIgNAHQgHACgIAAQgWAAgMgPgAgKg7QgKAHgJAMQgHALgGARQgEAQAAARIABAPQAAAIADAGQAEAGAEADQAGADAJAAQAIAAAJgFQAJgFALgLIAThRIgBgKQgBgEgDgEQgDgEgFgDQgGgBgIAAQgKgBgKAIg");
	this.shape_37.setTransform(325.5,-17.3);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAYBHQgGgGAAgJIAAgHIADgKIAOg3IADgMIABgJQAAgKgFgGQgFgGgJAAQgKAAgKAGQgLAGgKAMIgaBuIgcAAIAWhhIADgKIABgMQAAgIgDgDQgDgDgJAAIgIABIgIACIACgKIAWgHQAJgDAGAAQAMAAAFAHQAFAGAAAMIABAAQARgOALgGQAMgHAPAAQAPAAAIAJQAJAIAAAOIgBAJIgDAOIgNAwIgCALIgCAKQAAAJAEADQAEADAIAAIAIgBIAJgCIgDAJIgUAIQgJADgHAAQgMAAgGgHg");
	this.shape_38.setTransform(307.6,-17.4);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AhBA/QgNgPAAgcQAAgTAHgRQAHgRAMgOQAMgOAQgIQAQgJAQABQALAAAJADQAKADAGADIAbgHIACACIgWBhIgDALIgCAKQAAAJAEADQAEADAIAAIAIgBIAJgCIgCAKIgVAIQgGACgKAAQgLAAgGgHQgHgFAAgLIgBAAIgIAHIgKAIIgNAHQgHACgIAAQgWAAgMgPgAgKg7QgKAHgJAMQgHALgGARQgEAQAAARIABAPQAAAIADAGQAEAGAEADQAGADAJAAQAIAAAJgFQAJgFALgLIAThRIgBgKQgBgEgDgEQgDgEgFgDQgGgBgIAAQgKgBgKAIg");
	this.shape_39.setTransform(289.5,-17.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgyBrQgPgGgLgLQgLgLgGgQQgGgQAAgUQgBgbALgZQAJgZARgUQARgSAWgMQAXgMAYAAQATABAOAEQAPAEAJAHIAJgKIALAAIgQBMIgMAAIAAgGQgBgMgBgLQgCgMgGgJQgFgJgKgFQgJgFgPAAQgSAAgPAKQgRAKgLAQQgMARgGAXQgIAXABAXQgBAhARAUQAPAUAbAAQAVAAATgNQATgNALgWIALAGQgTAggXAOQgYANgdgBQgQAAgPgFg");
	this.shape_40.setTransform(272.2,-20.6);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAGAjQgFgGAAgJQAAgMAFgJQAFgKAIgIQAIgHAJgGIAPgIIAEAJIgNAIIgLAHIgIAJQgDAFgDAIIAHAAQAJgBAEAFQAFAFAAAFQAAAHgGAIQgGAGgJAAQgLAAgEgGgAgxAjQgFgGAAgJQAAgMAFgJQAFgKAIgIQAIgHAJgGIAPgIIAEAJIgNAIIgLAHIgIAJQgDAFgDAIIAHAAQAJgBAEAFQAFAFAAAFQAAAHgGAIQgGAGgJAAQgLAAgEgGg");
	this.shape_41.setTransform(257.1,-28.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(246.7,-40.3,246.2,117.8), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FFFFFF").ss(1,1,1).p("EhLxgTmMCXjAAAMAAAAnNMiXjAAAg");
	this.shape.setTransform(485,125.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("EhLxATnMAAAgnNMCXjAAAMAAAAnNg");
	this.shape_1.setTransform(485,125.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(-1,-1,972,253), null);


// stage content:
(lib._300x250_listen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// logo
	this.instance = new lib.Symbol6();
	this.instance.parent = this;
	this.instance.setTransform(348.5,125.5,0.7,0.7,0,0,0,196.6,78.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(316).to({_off:false},0).to({alpha:1},20,cjs.Ease.get(-1)).wait(19));

	// Layer_7
	this.instance_1 = new lib.Symbol5();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-26,139.8,1,1,0,0,0,206.3,36.6);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(316).to({_off:false},0).to({alpha:1},20,cjs.Ease.get(-1)).wait(19));

	// Layer_6
	this.instance_2 = new lib.Symbol4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(255.5,144.1,1,1,0,0,0,105.5,19.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(202).to({_off:false},0).to({alpha:1},19,cjs.Ease.get(-1)).wait(79).to({alpha:0},16).wait(39));

	// Layer_5
	this.instance_3 = new lib.Symbol3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150.1,122.3,1,1,0,0,0,105.5,19.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(123).to({_off:false},0).wait(1).to({regX:104.6,regY:18.1,x:149.2,y:121.3,alpha:0.002},0).wait(1).to({alpha:0.01},0).wait(1).to({alpha:0.025},0).wait(1).to({alpha:0.047},0).wait(1).to({alpha:0.077},0).wait(1).to({alpha:0.118},0).wait(1).to({alpha:0.171},0).wait(1).to({alpha:0.236},0).wait(1).to({alpha:0.311},0).wait(1).to({alpha:0.395},0).wait(1).to({alpha:0.482},0).wait(1).to({alpha:0.566},0).wait(1).to({alpha:0.643},0).wait(1).to({alpha:0.711},0).wait(1).to({alpha:0.77},0).wait(1).to({alpha:0.819},0).wait(1).to({alpha:0.861},0).wait(1).to({alpha:0.895},0).wait(1).to({alpha:0.923},0).wait(1).to({alpha:0.946},0).wait(1).to({alpha:0.964},0).wait(1).to({alpha:0.978},0).wait(1).to({alpha:0.988},0).wait(1).to({alpha:0.995},0).wait(1).to({alpha:0.999},0).wait(1).to({regX:105.5,regY:19.1,x:150.1,y:122.3,alpha:1},0).wait(39).to({alpha:0},14).wait(153));

	// Layer_2
	this.instance_4 = new lib.Symbol2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(150,144.8,1,1,0,0,0,370.9,21.9);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(4).to({_off:false},0).wait(1).to({regX:370.7,regY:21,x:149.8,y:143.4,alpha:0.026},0).wait(1).to({y:142.8,alpha:0.057},0).wait(1).to({y:142,alpha:0.094},0).wait(1).to({y:141.1,alpha:0.138},0).wait(1).to({y:140,alpha:0.194},0).wait(1).to({y:138.6,alpha:0.264},0).wait(1).to({y:136.9,alpha:0.35},0).wait(1).to({y:135,alpha:0.447},0).wait(1).to({y:133.2,alpha:0.536},0).wait(1).to({y:131.7,alpha:0.609},0).wait(1).to({y:130.6,alpha:0.667},0).wait(1).to({y:129.6,alpha:0.713},0).wait(1).to({y:128.9,alpha:0.751},0).wait(1).to({y:128.2,alpha:0.783},0).wait(1).to({y:127.7,alpha:0.81},0).wait(1).to({y:127.2,alpha:0.834},0).wait(1).to({y:126.8,alpha:0.854},0).wait(1).to({y:126.5,alpha:0.872},0).wait(1).to({y:126.2,alpha:0.887},0).wait(1).to({y:125.9,alpha:0.901},0).wait(1).to({y:125.6,alpha:0.914},0).wait(1).to({y:125.4,alpha:0.925},0).wait(1).to({y:125.2,alpha:0.935},0).wait(1).to({y:125,alpha:0.944},0).wait(1).to({y:124.9,alpha:0.952},0).wait(1).to({y:124.7,alpha:0.959},0).wait(1).to({y:124.6,alpha:0.965},0).wait(1).to({y:124.5,alpha:0.971},0).wait(1).to({y:124.4,alpha:0.976},0).wait(1).to({y:124.3,alpha:0.98},0).wait(1).to({y:124.2,alpha:0.984},0).wait(1).to({alpha:0.987},0).wait(1).to({y:124.1,alpha:0.99},0).wait(1).to({y:124,alpha:0.993},0).wait(1).to({alpha:0.995},0).wait(1).to({alpha:0.996},0).wait(1).to({y:123.9,alpha:0.998},0).wait(1).to({alpha:0.999},0).wait(2).to({alpha:1},0).wait(1).to({regX:370.9,regY:21.9,x:150,y:124.8},0).to({_off:true},92).wait(218));

	// bg
	this.instance_5 = new lib.white();
	this.instance_5.parent = this;
	this.instance_5.setTransform(151,127.1,1,1,0,0,0,496.9,134);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(102).to({_off:false},0).to({alpha:1},35,cjs.Ease.get(1)).wait(218));

	// Layer_3
	this.instance_6 = new lib.Symbol1();
	this.instance_6.parent = this;
	this.instance_6.setTransform(150,125.5,0.309,2.39,0,0,0,485,125.7);
	this.instance_6.alpha = 0.398;

	this.instance_7 = new lib._970x250_solar_bg();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-4,-175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_7},{t:this.instance_6}]}).wait(355));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(146,-51.2,308,602.4);
// library properties:
lib.properties = {
	id: '71A1C08147E540F29518D65B56296E84',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/_970x250_solar_bg.jpg", id:"_970x250_solar_bg"},
		{src:"images/CEPA_Horizontal_Logo_RGBK.png", id:"CEPA_Horizontal_Logo_RGBK"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['71A1C08147E540F29518D65B56296E84'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;