(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgsA3IAEgRQAUAEAPAAQAHABACgJIADgSQgLAIgNgBQgZABAFgeIADgTQAEgUAHgGQAKgKAYAAQATAAAPAFIgRBeQgDAOgHAFQgHAFgRAAQgQAAgWgHgAgFgkQgCADgBAHIgFAXQgBAGAGAAQAIAAAKgGIAHglIgJgBQgIABgFAEg");
	this.shape.setTransform(611.6,-146.1,1.012,1.012);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AAHAsIAKg8QAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAQgHAAgOAIIgKA3IgZAAIAPhTIAWgEIgBAKQATgKAOAAQAQAAAAARIgBAKIgLA8g");
	this.shape_1.setTransform(602,-148,1.012,1.012);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#231F20").s().p("AgWA/IAPhTIAYgEIgPBXgAgBg6IAYgEIgEAbIgYADg");
	this.shape_2.setTransform(595.2,-149.9,1.012,1.012);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#231F20").s().p("AgaAoIAJgzIgNAAIAEgUIANAAIADgUIAZgEIgEAYIAUAAIgFAUIgTAAIgHAqIAAACQAAABAAAAQAAAAAAABQAAAAABAAQAAAAABAAQADAAAKgDIAFARQgMAHgOAAQgUAAAAgQg");
	this.shape_3.setTransform(589.6,-149,1.012,1.012);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#231F20").s().p("AghAnIAFgSQALAEAMAAQAFAAACgBIACgGQAAgEgLgHQgMgGgEgFQgCgGACgKQACgOAHgFQAGgFAQAAQAPAAALAFIgEASQgKgDgMAAQgFAAgCABQgBABAAADQAAABAAABQAAABAAAAQAAABAAAAQAAABAAAAIAHAEQAPAIAEAFQADAEgCAKQgDAQgGAGQgHAFgRAAQgPABgMgGg");
	this.shape_4.setTransform(582.1,-147.9,1.012,1.012);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#231F20").s().p("AgkAWIAGghQADgRAIgHQAJgJASAAQANAAAIAGQAIAFAAALQAAAMgHAHQgHAGgQAEIgRAGIgBAFQgBAHAFgBQANAAAUgJIAFASQgTALgWAAQgaABAAgXgAgFgMIgBAFIAKgDQAKgCAAgIQAAgEgIgBQgKAAgBANg");
	this.shape_5.setTransform(574.3,-147.9,1.012,1.012);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#231F20").s().p("AgZAsIgMhTIAZgDIAGA/IARgqQACgFAAgGIgBgHIAZgEQABAEAAAHQAAAIgDAHIgbA9g");
	this.shape_6.setTransform(566.3,-148,1.012,1.012);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#231F20").s().p("AAGAsIALg8QAAgBAAAAQAAgBgBAAQAAAAgBgBQgBAAgBAAQgGAAgOAIIgKA3IgZAAIAOhTIAXgEIAAAKQARgKAPAAQAQAAAAARIgMBGg");
	this.shape_7.setTransform(556.6,-148,1.012,1.012);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#231F20").s().p("AgWA7IAUh1IAZAAIgUB1g");
	this.shape_8.setTransform(549.6,-149.5,1.012,1.012);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#231F20").s().p("AAHAsIAKg8QAAgBAAAAQAAgBAAAAQgBAAAAgBQgBAAgBAAQgGAAgQAIIgJA3IgZAAIAPhTIAVgEIAAAKQATgKAOAAQAQAAAAARIgBAKIgKA8g");
	this.shape_9.setTransform(537.9,-148,1.012,1.012);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#231F20").s().p("AgXA/IAQhTIAYgEIgPBXgAgBg6IAYgEIgEAbIgYADg");
	this.shape_10.setTransform(531.2,-149.9,1.012,1.012);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#231F20").s().p("AghAnIAFgSQALAEAMAAQAFAAACgBIACgGQAAgEgLgHQgMgGgDgFQgDgGACgKQACgOAHgFQAGgFAQAAQAPAAALAFIgEASQgJgDgNAAQgFAAgCABQgBABAAADQAAABAAABQAAABAAAAQAAABAAAAQAAABAAAAIAHAEQAPAIAEAFQAEAEgCAKQgDAQgGAGQgIAFgRAAQgPABgMgGg");
	this.shape_11.setTransform(521,-147.9,1.012,1.012);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#231F20").s().p("AAGAsIALg8QAAgBAAAAQAAgBgBAAQAAAAgBgBQgBAAAAAAQgIAAgNAIIgKA3IgZAAIAOhTIAXgEIAAAKQARgKAPAAQAQAAAAARIgMBGg");
	this.shape_12.setTransform(512.3,-148,1.012,1.012);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#231F20").s().p("AggAkQgIgIAAgMIAAgGIAEgTQADgSAJgIQALgIAVgBQAQAAAJAJQAIAHAAANIgBAGIgDATQgDARgJAIQgLAJgVAAQgPAAgKgIgAgLgKIgEAUIAAAEQAAAKAMAAQAMAAADgOIAEgXQAAgKgMAAQgMAAgDANg");
	this.shape_13.setTransform(502.9,-147.9,1.012,1.012);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#231F20").s().p("AghAnIAFgSQALAEAMAAQAFAAACgBIACgGQAAgEgLgHQgMgGgEgFQgCgGACgKQACgOAHgFQAGgFAQAAQAPAAALAFIgEASQgKgDgMAAQgFAAgCABQgBABAAADQAAABAAABQAAABAAAAQAAABAAAAQAAABAAAAIAHAEQAPAIAEAFQADAEgBAKQgDAQgGAGQgIAFgRAAQgPABgMgGg");
	this.shape_14.setTransform(494.6,-147.9,1.012,1.012);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#231F20").s().p("AghAnIAFgSQALAEAMAAQAFAAACgBIACgGQAAgDgCgBIgJgHQgNgGgCgFQgDgGACgKQADgOAGgFQAFgFARAAQAPAAALAFIgEASQgJgDgNAAQgGAAgBABQAAAAgBABQAAAAAAABQAAAAAAABQAAABAAAAQAAABAAABQAAABAAAAQAAABAAAAQAAABAAAAIAHAEQAPAIAEAFQADAEgBAKQgEAQgFAGQgIAFgRAAQgPABgMgGg");
	this.shape_15.setTransform(487.2,-147.9,1.012,1.012);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#231F20").s().p("AgkAWIAGghQADgRAIgHQAJgJASAAQANAAAIAGQAIAFAAALQAAAMgHAHQgHAGgQAEIgRAGIgBAFQgBAHAFgBQANAAAUgJIAFASQgTALgWAAQgaABAAgXgAgGgMIgBAFIALgDQAJgCAAgIQAAgEgHgBQgJAAgDANg");
	this.shape_16.setTransform(479.5,-147.9,1.012,1.012);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#231F20").s().p("AgmA7IAWh1IAYAAIgPBeIAuAAIgFAXg");
	this.shape_17.setTransform(470.8,-149.5,1.012,1.012);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(466.9,-156.2,149.2,16.4), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AAHBDIgJABIgBgBIgCABIAAgBIgDABIgCAAIgCgCIgCgDIAAgCIABgGIgBgBIABgDIgBAAIABgDIgBgDIABgDIABgBIgCgBIAAgQIABgFIgBgBIAAgSIABgEIgBgDIABgCIgBgBIAAgEIACgBIgCgCIABgDIAAgDIgBgJIAAgCIABgCIgCgDIgKAAIgDgBIgDABIgFAAIgEgCIgBgBIgCgGIAAgEIAAgDIAAgGIABgCIADgDIADAAIABgBIACABIAIAAIABAAIACAAIADAAIACgBIAFABIADgBIACABIACgBIAJABIAFgBIACABIACgBIANABIAIgBIABABIAFgBIACACIABAAIABADIAAAKIgBABIABACIgBAGIgCADIgNAAIgEABIgCgBIgBAAIgBAAIgCABIgBgBIgBACIAAAEIgBABIABADIAAADIgBAEIABACIgBAHIAAADIABABIgBACIABAGIgBACIABACIgBADIABABIAAAGIgBAAIABAGIgBAEIABABIAAADIAAACIgBADIABADIgBAFIABACIgBAHIABACIgBAEIABAHIgCAFIgBABIgBAAIgCABgAgHAkIABABIACgBIgBgBgAgGAhIACABIAAgCIgBAAIgCAAgAgDAPIABAAIAAgBIgBgBgAgFAKIAAAAIABgCIgBAAgAgCgIIACAAIAAgBIgBgBgAgHgbIgCACIAEgBIABgBIgDgBgAgHgeIACAAIAAgBIgCAAgAAAgoIAAABIAAABIACgBIgBgBIAAgBIgBAAIgBgBgAADgrIgBACIACAAIABgCIgBgBgAABgxIgBABIgCABIABAAIABAAIAAACIABABIACgCIABgCIACgBIgBAAIgBAAIgBACIgBAAIgBAAIACgCIgCgCIACAAIAAgCIgBAAIgCACIAAABIgCABIAAABIACgBIAAgBgAARgtIABAAIAAgCIgBAAgAAPgvIgBAAIABAAIABAAIgBgCgAAJgzIAAACIABABIAAgCIADAAIACgDIgBgBIAAABIAAACIgFgBgAgUgxIgBABIABAAIACgBIgBgBgAAGg1IABABIAAABIABgBIAAgBIgCAAgAAIg1IABAAIAAgBIgBAAgAgDg1IABgCIgCAAIgDAAIAAACIACgBgAgLg3IABACIABgBIABgBIgDgBgAAPg3IABAAIAAgBIgBAAgAAcg5IAAACIACgBIAAgBgAgLg6IABgBIgBgBg");
	this.shape.setTransform(597.3,-146.4,1.25,1.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AAbBEIgCgBIgFABIgDAAIgBgBIgCABIgDAAIgDgBIgBABIgCAAIgEgBIgBABIgCAAIgHAAIgCgBIgCABIgBAAIgBgBIgHABIgCgBIgCABIgDgBIgCgBIgFgDIgCgCIgBgEIAAgCIgBgBIAAgDIABgDIgBgBIAAgCIABgDIgBgCIAAgDIACgDIAAgBIAHgEIADAAIACgBIAEgCIAAABIACgDIACAAIACAAIABAAIABgBIACABIACACIABACIgBACIABACIgBACIABAFIAFACIADAAIADgBIABABIABgBIABABIAGgDIgBgMIACAAIgCgCIABgBIgBgEIABgBIABACIABgBIgCgDIgBABIgBAAIgDgBIgDAAIgDgBIgBgCIgJAAIAAgDIgBAAIAAACIgCgCIgMgCIgNgDIAAgCIgBgDIAAAAIgBgBIAAgGIABgCIgBgBIAAgDIAAgGIABgBIgBgGIABgDIgBgDIAAgCIABgDIgBgEIAAgCIABgCIgBgCIABgBIAAgCIAAgFIABgBIAAgCIABgCIACgCIABgCIACAAIACgCIAEAAIABgBIADABIALgBIADABIADAAIAJAAIABgBIACABIAGgBIAFAAIACABIABgBIACABIACAAIABAAIACAAIACAAIABABIADABIAEAGIABADIABADIgBAHIAAABIABADIAAAFIgCABIAAACIgCACIgCACIgCAAIgHACIgBABIgGADIgCgBIgBABIAAACIgDgBIgCgCIAAgBIgBgDIABgGIgBgEIgBgBIgCAAIgBgCIgBACIgDgBIgJABIAAABIgBAEIgBADIABADIgBAFIAAABIABAGIACAAIAAACIABABIAAgDIAJAEIAFABIABABIACAAIABAAIABAAIACAAIABABIAEAAIAAABIAFABIACgBIAAACIABgBIADAAIABACIABAAIAGADIAAABIAAABIABAAIAAAfIgBABIABACIABAAIgBABIAAAJIAAAFIgBADIABADIAAACIgBADIgHAHIgBgBIgBABIgCABgAghBAIAAAAIgBgBgAAUA4IAAACIACgBIgBgCgAgCA2IACAAIAAAAIgBgBgAgIAzIAEAAIABABIgBABIAAABIACgBIABgCIgDAAIgBgBIAAgBIABAAIgBgBIgBAAIgBACIgCAAgAgMAxIgBABIAAABIgBABIACABIAAABIABgBIgCgBIACgDIAAgBIgBgCgAgZA0IAAACIACgBIAAgCgAgQAzIAAABIABAAIAAgBIAAgBgAAMAyIAAAAIAAgBIAAgBgAgNAtIABACIAAgCIgBgBgAgUAuIgBABIACAAIACgCIgCAAgAgPArIgBABIABACIABAAIAAgCIABgBIgBgBgAgTArIADAAIABgBIgEAAgAgZAqIABABIABAAIAAgCIgBAAgAgdAqIABABIABgBIgBAAIgBgBgAgTAkIgBABIABAAIACAAIAAgCgAAfAjIABABIAAgCIgBAAgAAQAWIAAACIACAAIAAgBIABgBIgCAAgAAVAWIACABIAAgCIgCAAgAAQATIABACIABgCIAAgBgAAYAQIABAAIAAgBIgBAAgAATANIgDAAIgBABIABACIACAAIABgBIgBgBIABgBIABABIAAgBIAAgBgAAdANIABAAIAAgBIgBAAgAAFALIABABIABgBIgBgBgAAOAKIAAABIACAAIgBgCgAgFAJIAAABIABAAIAAgCIgBAAIAAAAgAASAGIgCABIABABIABgBIACAAIgBgBgAALAGIgBAAIgBABIACABIABgBIABgBIgBgBIADgBIABgBIgBAAIgCAAIgBABIgCAAgAgCAIIACgBIAAAAIgCgBgAASACIgBACIADABIgBgBIAAgBIABABIABAAIAAgCIgCgBgAAJADIABgBIgCgCIACAAIgBAAIgCgCIAAABIgBABIgCAAIAAAAIAAgBIgBAAIABACIABAAIABABIACgBgAgIACIACgBIAAgBIgCAAgAASABIgBgBIgCAAIgBAAIgCAAIACABIACAAIACAAgAgOAAIgBgBIgBgBIgCAAIgBABIABABIACgBIAAABIACAAgAgNgCIABABIABAAIABgBIgBAAgAgUgEIABACIAAgCIACgBIgCAAgAAAgFIABABIABAAIgBgCgAAKgFIACAAIgBgCgAgIgFIACAAIgCgCgAgBgIIAAABIABABIABgCgAgigXIABAAIAAgBgAAdggIABAAIgBgCgAgUgoIAAABIABAAIAAgCgAAWgoIACAAIAAgBIgBAAgAAggrIABAAIAAgBgAgNgsIABABIACAAIgBgBIgCgBgAgQgrIADAAIgBgBIgBAAgAANgsIABgDIgCAAIAAABIgBgBIgCABIACACIABgBgAgXgvIADABIABgBIgCAAIgCgCgAgIgxIABABIACAAIgBgBIgCgBgAANgwIgBgBIgBgBIgCgDIgBAEIACAAIABABIABgBgAAFg1IgBADIAAACIAAgCIADgEIgBAAIgBgBgAACgyIgBACIACAAIAAgCgAgOgyIABABIAAgBIAAgBgAgQg0IABABIAAgCgAATg3IACAAIAAgBIgBAAgAgHg4IACABIAAgBgAAUg5IABgBIgCAAgAAFg7IAAACIACAAIgBgCIgBgBgAAJg7IABgBIgBgBgAgIg/IACgBIgCgBg");
	this.shape_1.setTransform(584.7,-146.4,1.25,1.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#231F20").s().p("AAoBDIgBABIgEAAIgBgBIgCAAIAAABIgBAAIgGAAIgCgBIgBAAIgBABIgGgEIAAgBIgBgBIAAgCIgBgBIgCgCIgCgDIgDgFIAAgDIgCgDIAAgBIgDgDIgBgCIAAgCIgBgCIgHgMIABgBIgCgBIgCgBIgBAAIgCACIgBACIABAKIgBAGIABACIAAAFIgBACIAAAEIAAAKIAAADIgCACIgBACIgDAAIgBgBIgBABIgEAAIgCAAIgBgBIgDABIgGgBIgCABIgBgBIgDgDIAAgBIAAgEIABAAIgBgDIAAgBIAAgHIAAgBIAAgHIAAgCIAAgCIAAgGIgBgFIABgCIAAgGIAAgFIAAgDIAAgJIgBgCIABgDIgBgCIABgDIAAgJIAAgDIAAgBIgBgDIACgEIgBgDIAAgEIAAgBIAAgGIAAgJIgBgCIACAAIgBgHIABgDIACAAIACgCIABAAIAEAAIADABIADgBIABABIAEgBIAPAAIABACIAAgCIAGABIABAAIACgBIAGAAIAFABIAAgBIADABIANAAIADAAIABABIAAABIABgBIAFAEIABADIAAACIACABIAAADIAAAFIAAADIgBACIABADIAAADIAAAJIAAAFIAAADIAAATIAAABIgBAGIABACIgGAHIgDABIgBABIgBAAIgFAAIgCACIACAFIABABIANAWIAAACIACACIAAACIABABIAAABIAAABIACAAIAAADIABABIAAABIACABIgCADIgBACIgBgBIgBABgAARAxIADAAIgBgBIgBgBgAAOAtIABAAIABAAIgBgBgAAUAsIABAAIABgBIgBAAgAgfAnIABACIABAAIAAgBIgCgCgAgkAjIADACIACAAIgCgBIgCgCIgCAAgAgcAcIgBABIABACIAAABIAAgDIABAAIABgCIgBAAgAgYAYIACAAIAAABIABAAIAAgCIAAgBIgBAAIgBgBIAAABIABABIgBAAIgBAAgAAJAXIABAAIABgBIgCgBgAghAXIACgBIgBgBIgBgBgAgYARIAAABIgCABIAAABIACAAIABgBIABgBIgCgCgAgSARIgBABIACABIAAgBIABgBIgBgBgAAFAQIACAAIAAACIgBAAIADAAIAAgCIgBgBIgCAAgAAOALIABADIABABIABgBIgCgDIABAAIAAgBgAgVAOIABgBIABgBIgCAAgAgFANIACAAIgBgCIgCAAgAAFALIAAACIABgCIgBAAIABgBIgBgBgAgRANIACAAIAAgCIgBAAgAgdAMIABgBIAAgBIgBAAgAgVALIAAgBIACgBIgBgBIgCABIgBABIgCgBIgBACIACAAIABAAgAgDAKIABABIAAgEIgBgBIgBgBgAAXAJIABgBIgBgBgAABAGIACABIgBACIABgBIABgCIABgBIgCAAgAgJAHIAAACIABgCIgBgBgAgPAHIABAAIABgBIgDAAgAANAGIgBgBIgBAAIgCAAIAAABIABAAIABAAIACAAgAgaAEIABABIAAgCIgCgBgAgJACIAAACIABAAIADABIAAgDIgDgCgAgTAAIACACIgCAAIABABIABABIABgBIAAgBIACgCIABgBIgBAAIgBgBIAAABIgCABIgBAAgAARADIACABIAAgCIgBAAIgBAAgAAYABIABABIACAAIgBgBgAAJACIACAAIAAAAIgCAAgAAFAAIgBABIABABIABgBIABgBIABAAIAAAAIgBgDIAAACIgBABIgBAAgAgMAAIAAACIACgCIAAAAIgBAAIgBgBgAAUgBIABABIAAgCgAAKgBIACABIAAgCIgDAAgAAWgCIACAAIAAgCIgBABIgCgBgAgPgEIACABIAAgCIgBAAgAAOgEIACAAIAAgDIgBAAgAgNgnIgBABIgBABIAAACIAAACIAAABIABABIgBACIAAAGIAAAFIAAAEIAAADIACADIAEAAIABABIAGgBIACAAIACAAIADAAIADAAIAEgCIAAgJIgBgEIABgFIgBgKIgEgCIgCABIgCgBIgDAAIgFABIgDAAIgBgBgAgWgIIABAAIAAgBIgBgBgAAYgLIADgBIgDgBgAAfgNIABgBIgCAAgAAWgQIgBABIACACIABgBIABgCIgDABIABgBIgBgBgAgagQIABAAIAAAAIgBAAgAAZgTIADABIABgBIAAgBIgCABIgCgBgAAUgTIABABIABgCIgBgBgAgegWIAAACIABABIACAAIgBgCIgBgBIAAgCIgBgBgAAYgXIgBAAIABABIAAABIACgBIAAgCgAgggZIAAAAIABABIABgBIgBgBgAARgaIABABIABgBIgCgBgAgfgbIAAABIABgDIgBAAgAgigeIABAAIABgBIgBgBgAAdgjIABAAIAAgBIAAgBIgCAAgAAXgjIAAgBIgBgBIgBAAIAAABIABAAIABABIAAAAgAASgoIACABIABAAIAAgBIgBgBIgCAAgAAagqIAAABIABgBIgCgBgAAWgsIAAACIACgBIgCgCgAAUgsIABAAIAAgBIgBAAgAgMguIAAABIAAABIABgBIABAAIAAgBIgCgBgAAQgtIgCgDIAAgBIAAABIAAABIgCAAIABABIADABgAgCgtIABAAIAAgBIgBAAgAgBgxIAAACIACgCIABgBIgCgBgAgWgzIABAAIAAgBIgBAAgAgSg1IABAAIAAgBIgCAAgAgVg2IAAgBIAAAAg");
	this.shape_2.setTransform(571.5,-146.5,1.25,1.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAIBEIgCAAIgBAAIgGAAIgCgBIgEABIgBgBIgCABIgEgBIgGABIgCgBIgCABIgGgBIgCAAIgCgDIgCAAIAAgDIAAgBIABgCIgBgCIAAgDIAAgBIAAgBIABgBIgBgDIAAgEIAFgCIADAAIACAAIAIAAIACAAIACgCIABgBIgBgBIAAgBIAAgDIAAgCIAAgBIAAgDIAAgIIAAgFIAAgCIAAgEIAAgCIAAgCIABgBIgBgDIAAgBIAAgBIAAgDIABgCIgBgBIAAgFIAAgDIAAgNIAAgFIABgBIgCgDIgDgCIgHABIgCgBIgCABIgFgBIgBgBIgBgEIACgCIABgCIAAgCIACgDIABgCIAAgBIABgBIAAgCIABgBIABgDIAFgDIADABIAFgBIABABIAEgBIAEABIAFgBIAAAAIACABIABgBIACAAIACABIAEAAIACABIACADIAAACIgBACIABABIAAAFIgBABIABADIAAADIgBACIABACIAAABIgBACIABACIAAAGIgBABIABADIgBAEIABABIAAAGIAAAEIgBACIABADIAAACIAAAEIgBADIABACIAAABIAAADIgBABIABADIAAACIAAACIgBABIABABIAAAEIAAACIAAADIAAACIgBACIABABIAAAGIACABIADABIAKAAIAEABIABACIABADIAAAKIABACIgCAGIgCACIgGABgAgRA7IACgBIgBgBIgBAAgAgDAzIABgBIgBgBgAgHAtIAAABIABACIABgCIAAgCgAAIAtIABABIAAgCIAAgBIgCAAgAgCAkIgBABIACAAIABgCgAgCATIABABIAAgCgAgIgEIACAAIgBgBgAgEgNIABgDIgBAAgAgFgSIABABIABgCIgDAAgAgJgVIgBABIADAAIgBgCIgBgBgAgCghIAAABIABABIAAgDgAgGglIgBACIAAABIABgBIABgBIADABIgBgCIgBAAgAAHgkIABAAIAAgBIgBAAgAgJglIABgBIAAAAIgCAAgAgCgoIABAAIABAAIAAgCIgCgBgAgKgqIACAAIABgCIgCAAgAgKgtIAAABIABgBIABgBIABgBIACAAIABACIAAgCIgDAAIgCgBIAAACIgBABIgBgBgAAGguIgBgCIABABIAAgBIgCgBIgBAAIABACIgBABIADAAgAgBgyIAAACIAAABIABAAIAAgBIAAgCIAAgBgAgSgwIAAABIABgBgAgCg2IABABIABgBIgBAAIgBgBgAgEg2IABgBIgBgBg");
	this.shape_3.setTransform(559,-146.4,1.25,1.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#231F20").s().p("AgcBDIgEABIgEgBIgBgCIgBgDIAAgFIABgCIgBgDIABgBIgBgCIAAgBIAAgGIABgCIgBgBIAAgEIAAgGIAAgEIABgBIgBgCIABgGIgBgCIAAgCIABgCIgBgCIAAgCIAAgRIABgBIgBgCIABgEIgBgFIABgBIgBgDIABgBIgBgBIAAgBIABgEIgBgCIAAgEIAAgFIAAgDIAAgCIAAgJIABgGIADgBIADgBIABABIABgBIACABIABAAIABAAIADgBIADABIABAAIACgBIAIABIAGgBIACABIABgBIAEABIABgBIAZABIAGAAIACAMIgBANIgFABIgDABIgFgBIgGABIgTgBIgFABIgCAAIAAABIgBAHIAAABIAAAHIAAADIABABIgBADIAAADIACACIAHAAIABABIACgBIADAAIAEAAIABAAIAEAAIAEAAIACABIABgBIACACIAAACIACACIgBAFIABAGIgBADIgBADIgEABIgBAAIgKAAIgBAAIgDAAIgCAAIgBgBIgCABIgEAAIABgBIgCABIgBAAIgBABIgDADIABACIAAANIgBACIABABIABAGIgBABIAAABIgBABIACAHIAAAEIgBADIAAADIAAACIgCAEIgCABIgKAAIgDAAgAgVAwIABABIABgCIgCgBgAgZAuIgBACIADgBIgBgDIgBAAgAgdAmIAAACIABABIAAgBIABgBIABAAIAAgCIgCAAgAgSAoIABAAIAAgBIgBAAgAgYAnIABABIAAgCIgCAAgAgTAmIABAAIABgCIgBAAgAgYAjIABAAIABgBIgCAAgAgZAXIABABIABAAIAAgBgAgWAOIAAACIABAAIABgBIABABIAAgCIgBgBgAgOAKIACAAIAAAAgAgTAHIgBAAIACACIABgCIAAgBIgBAAgAgWAGIgBABIACAAIABgBIgCgBgAgaAHIACgBIgCgBgAgdAFIACABIAAgCIgBAAgAgNAEIAAAAIABABIABgBIgBgBgAgVADIABABIABAAIAAgBIABgBIABABIABgBIgEgBgAgCABIABABIABgBIgCgBgAgZABIABABIACgCIAAAAIgBAAIAAAAIgDAAgAgIgBIABABIABAAIAAgCIgBAAIgCAAgAgTAAIACAAIADgBIgCgDIAAACIgCACIgBgCgAgZgBIACgBIgDAAgAgNgKIAAACIABABIgCACIABABIAAABIADABIAAgBIgCAAIAAgBIADgBIAAgCIgCAAIABgCIgCgBIAAABIgBgBgAgZgGIAAADIACAAIgBgCIACAAIAAgCIgEgBgAgIgDIABgBIAAgBIgBABIgBAAgAgTgHIgBACIACAAIABgCIgBgBgAgUgKIABABIABgBIgCgBgAgYgKIABAAIAAgBIgBAAgAgXgUIAAABIABABIABABIABgBIgBgCgAgUgTIABABIACgCIAAAAgAgWgWIAAACIACgBIABgBgAgXgeIABAAIABgBIgCgBgAgSgqIgBABIAAABIACAAIADgBIgBgCgAgZgvIACAAIgBgBg");
	this.shape_4.setTransform(547.9,-146.4,1.25,1.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#231F20").s().p("AAqBDIgEABIgBAAIgCAAIgCgBIgDABIgFAAIgDAAIgDgBIgCAAIAAgCIgDgDIAAgBIgCgBIgBgCIAAgEIgEgEIgBgEIAAgCIgCgCIgDgHIgBgBIAAgCIgBAAIgBgCIABgCIgCAAIgBgCIgEgHIABgBIgCgBIAAgCIgDgBIgBgBIgCABIgBABIgBALIAAABIABAEIgBACIABABIgBACIABAFIgBABIABAIIgBAFIABADIgBACIAAADIgBADIgFACIgCgBIgBAAIgHABIgBAAIgJgBIgCAAIgBgDIgBgDIABgBIgBgCIABgDIAAgDIgBgBIABgEIgBgPIABgFIgBgDIABgDIgBgCIABgBIAAgGIABgCIgCgEIABAAIgBgFIABgCIgBgBIABgJIgBgCIAAgEIABgCIAAgMIgBgEIABgCIgBgBIABgHIgBgCIABgDIgBgEIABgFIAAgCIABgEIADgBIADAAIACgBIACABIABAAIABgBIAEABIADgBIAFABIADABIABABIABAMIgBAFIABAAIAAAHIAAACIgBADIABABIAAADIgBADIABACIAAAMIABABIADAAIABAAIACgDIACgEIABgCIACgBIgBgDIABAAIABgBIABgBIABgDIADgIIAAgBIACgBIAAgEIADgCIgBgCIACgBIABgDIAEgIIABgDIAEgCIADgBIABAAIACABIADgBIAFABIABgBIADABIABgBIACABIADAAIADAAIABABIAAAEIgCADIAAABIgCAEIgBACIgCACIAAACIgBABIgBABIAAADIgEAFIAAACIgBABIgCAEIgBABIgBACIgCAEIgCAGIgCADIgCADIAAABIAAABIgDACIgCAGIAAACIACADIAAABIADAEIAAABIADAGIADAHIAFAGIAAACIABABIAAACIACABIACAGIACABIABAEIACACIAAACIACADIAAABIACACIACAFIABAAIAAACIgCAEIgDABgAgdAlIABAAIAAgBIgBAAgAAQAkIABAAIAAgBIgBgBgAAAAXIAAABIAAgCgAAPAWIACAAIAAgBgAgUANIAAABIABAAIABgBIgBAAgAgZAMIABgBIAAgBIgBAAgAAHAKIABAAIgBgCIgDAAgAgEAIIAAABIABABIABAAIAAgBIgCgCgAgGAKIAAAAIAAgBIAAAAgAgMAIIABACIABAAIgBgBIAAgCIAAAAgAgVAIIABAAIAAgBIgBgBgAgDAGIADABIAAgBIABAAIgBgDIAAACIgCAAIgBAAgAgPAGIABAAIAAABIACgBIgCgBgAgmAFIAAABIABAAIABgBgAAFABIgBACIgBABIAAABIABAAIABAAIAAgCIABgBIACAAIgBgCgAgaADIgBABIABABIACAAIgBgBIAAgCgAgGACIgBABIABAAIACABIACgCIgCgCIgBgBIABgBIgCAAIAAABIgBABIgCAAIAAABIADgBgAgUAAIgBACIADACIADgBIACgBIACABIgBgCIgCAAIgBgBIgBAAIAAABIgBABIAAgBIgCAAIAAgBgAgBABIABAAIABACIABgCIACgBIAAAAIgCAAIgBAAIAAAAIgCAAgAghABIABABIACgBIgCAAIgBgBgAgPgCIgBACIABAAIACAAIAAAAIgBgBIAAgBIAAgCIgDAAIAAACIABABIgBgBIAAgBIACAAgAgBAAIABAAIAAgBIAAgBIAAABIgBAAgAgJAAIABgBIAAgBIgBAAgAgMgBIABAAIAAgBIgBAAgAgcgDIABABIABgDIgCAAgAAAgEIABACIACgBIgBgBgAgIgEIACACIAAgBIAAgBIACABIgBgBIgBgBgAglgHIAAACIACAAIAAgDgAgHgIIgBADIACgDIAEAAIACgBIgBgBIgBAAIgBgBIgBABIAAABIgDAAgAgQgIIgBABIACAAIAAgBIABgBIgCAAgAgWgLIADABIgBgBIgBAAIABgCIgCgBIgBAAgAgBgLIABAAIABgBIgCAAgAgagMIAAABIACAAIAAgBIgDgBgAgdgNIABgBIgBgBIgCAAIgBACIADgBgAgYgSIABABIAAgCIgCAAgAgcgSIABAAIABAAIAAgBgAADgUIABAAIAAgBIgBAAgAAGgWIAAgBIgCgBgAAKgYIABAAIAAgCgAAJgfIABgBIgBAAgAgjgiIABABIAAgCIgBAAgAgbgjIABAAIAAgBIgBAAgAgcgoIABAAIAAAAIgBAAgAATguIAAACIABgBIABgBIgBgBIgBAAgAAPgvIABAAIAAgBIgBAAgAAcgwIAAABIABgBIgBAAgAARgwIABgBIAAgBIgBAAg");
	this.shape_5.setTransform(535.1,-146.4,1.25,1.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#231F20").s().p("AAZBDIgIABIgCgBIgCABIgBgBIgBAAIgBABIgGgBIgBABIgDAAIgFAAIgCgBIgFABIgDAAIgIAAIgBgBIAAAAIgBABIgCAAIgBgBIgBAAIgCAAIgBAAIgBgCIgCgBIgBgCIgDgBIgBgDIgBgDIAAgCIABgCIgBgGIABgCIgBgBIAAgDIAAgJIABgFIgBgCIAAgBIAAgHIABgCIgBgDIAAgBIABgBIgBgCIAAgBIAAgCIAAgCIAAgIIABgCIgBgDIABgFIgBgBIABgCIgBAAIABgDIgBgDIAAgDIABgBIgBgFIAAgBIABgCIgBgBIAAgJIABgBIgBgCIAAgBIAAgDIABgCIAFgHIACgBIACgBIASgBIACABIADgBIACABIABAAIACAAIABgBIACABIABAAIABgBIADABIAGgBIACABIAFgBIACABIAGgBIABABIADAAIADABIADABIABABIABAAIADAIIAAADIABADIgBAEIABACIgBAGIABAGIAAABIgBABIAAACIgBABIgDAEIgCABIgDAAIgBABIgCABIgBgBIgDACIgLAFIgCgDIAAgGIgBgEIAAgBIABgBIgBgCIABgEIgBgFIgBgBIgCAAIgBABIgDgBIgBABIgCgBIgDAAIgBABIgBgBIgFABIgBABIgCACIABAAIAAAJIAAABIAAACIAAABIAAARIgBAEIABACIAAAAIAAAJIgCADIACABIAAADIABABIgBANIABACIgBACIAAAEIACACIABABIABgBIACABIAAABIABgBIAEAAIACAAIAAABIABgBIABAAIAFAAIADgCIAAgEIABgDIgBgBIAAgKIAAgBIAAgEIABAAIABgBIABABIAGAAIABABIABABIAGABIAIAEIAEAEIAAABIABACIgBAJIABAEIgBAEIABADIgBACIABACIgCABIABADIgCACIAAABIAAABIgCADIgCAAIgBgBIAAADIgCAAIgDABIAAgCIgBABIgBABgAAOA5IAAACIABABIAAgFIgBAAgAAFA8IABAAIAAgBIgBAAgAADA8IABAAIAAgCgAAYA5IABAAIABgBIgCgBgAAeA4IACABIABgBIgDgCgAgTA5IABAAIAAgCIgBAAgAgNA3IABAAIAAgBIgBAAgAAGA3IABAAIAAgBIgBAAgAgYA1IAAABIABABIAAgCgAAPA2IABgBIgCAAgAACA0IACAAIABAAIgDgBgAgeA0IABAAIgBgBIgCAAIgBAAgAAXAyIAEACIACgBIgDgBIAAgBIgCAAgAAkAyIAAABIABAAIAAgCIAAgBgAALAyIABABIABAAIAAgBIgBgBIgBAAgAAQAwIACAAIAAAAIgBABIACACIABgBIgCgCIACgBIABgCIgCABIgCAAgAAIAzIACAAIAAgBIgCAAgAADAwIAAACIABABIACgDIgCgBgAABAwIAAACIABgBIABgCIgBgBgAAiAwIAAABIACgBIAAgBgAANAuIgBACIACAAIAAgDgAAJAuIgBAAIgBACIADgBIABABIAAgDgAgQAwIADAAIAAgBIgCABIgBgCgAAZAvIACgBIAAgBIgBAAgAgUAuIACABIAAgBIgBgBgAAeAqIgBADIABAAIAAAAIABgDIgCgBgAAWAsIABABIABgBIACgCIgCAAgAAAAtIAAgBIAAAAgAAQAsIABABIACAAIAAgBIgCgBgAAkArIgBABIACAAIAAgCgAgeAsIABgBIgBAAgAgcAqIABABIABgBgAgPApIAAABIACgBIABgBIgBgBgAAUAqIABgBIgBgBgAgWApIABABIAAgCIgBAAgAAXAlIgCACIABABIABgBIABAAIAAgCIAAgBgAgVAiIgBABIAAABIADgCgAghAfIABAAIgBgBgAgRAQIABAAIABgBIgBgBgAgRAGIABAAIABAAIAAgBIAAAAgAgUgCIABABIABgDIgCAAgAgQgEIABAAIAAgBgAgTgLIABABIACAAIAAgBIgBgBgAgcgRIABgBIgCAAgAgkgTIACABIABgBIAAgBIgBAAIgBAAIgBAAgAgWgYIACABIACAAIgBgCIABgCIgBgBgAgagZIgBgDIgCAAIgDgCIAAABIABABIAAABIACAAIABABIACABgAgZgcIACABIACgBIABgDIABgBIACAAIgBgCIgBAAIABgBIgCgBIgBACIgBAAIAAgBIgBABIAAABIABAAIABABIgBABIAAACIgBABIgCgBgAgPgdIABAAIgBgCgAAVgfIABgBIABgBIgCgBgAgcgjIgBABIACAAIABgCIgDgBIgBAAgAgUgmIACABIACAAIgBgCIgBgBIgBAAgAgbgmIADAAIACABIACAAIgBgBIgBAAIgBAAIgCgBIgBAAgAgPgrIAAACIABAAIADAAIgBgEIgDABIAAgBIAAgBgAgVgsIgBABIADAAIgBgCgAgcgrIABAAIABgCIgDAAgAAOgvIAAABIABAAIACgBIgCAAgAAhgvIADAAIgBgCgAgLgxIACABIAAgCgAgVg0IgBABIABACIABgBIABgCIgBgBgAAPg6IACAAIAAgCIgCAAg");
	this.shape_6.setTransform(521.3,-146.4,1.25,1.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#231F20").s().p("AgVBEIgBgBIgBAAIgDAAIgBAAIgCAAIgDAAIgDAAIgBgBIgBgCIABgDIgBgFIABgEIgBgCIAAgCIAAgDIABgBIgBgCIAAgDIAAgEIAAgBIABgBIgBgCIAAgJIAAgFIAAgDIAAgMIABgCIgBAAIAAgBIAAgCIAAgBIAAgIIABgDIgBgCIAAgBIABgBIgBgFIAAgDIAAgDIAAgBIAAgCIABgCIgBgEIABgDIgBgDIAAgBIAAgCIAAgBIAAgCIAAgDIAAgCIAAgFIAAgCIACgDIADgBIABAAIAJAAIACABIABgBIACAAIACAAIABABIABgBIABABIABgBIAJAAIACAAIABABIADgBIACAAIABABIACgBIADAAIACABIABgBIAGAAIAEAAIABAAIADAAIAJACIgBACIABAEIgBABIABAJIAAAEIgCADIgBABIgEABIgBAAIgLAAIgCABIgDgBIgBAAIgJAAIgBgBIgCABIgBAAIAAAAIgCAAIgCAAIgDACIAAAFIAAACIABADIAAABIgBADIABADIAAAHIAAABIACABIABAAIAAABIABgBIACAAIADAAIACABIABgBIABAAIAGAAIADAAIAFAAIABABIABgBIABABIACADIAAAGIAAACIgBAAIABABIAAADIgBAGIgCABIgCABIgHAAIgCgBIgCACIgBgBIgJAAIgEABIgDABIAAABIAAABIAAACIAAAGIABACIgBABIAAAGIgBACIABABIABAEIAIABIAEgBIABACIABgCIACAAIABAAIABABIADgBIADAAIAEAAIAEABIABgBIAJABIACADIAAAEIgCAAIACAFIAAABIAAABIgBAFIABADIgDAEIgMAAIgDABIgCgBIgEABIgDgBIgCABIgCAAIgBgBIgFAAIgHAAIgCABIgGAAgAAUAyIAAABIABABIABgDgAAEAxIAAABIACgBIgBgBIgCgBgAgOAuIACABIAAgCIgBAAgAgOAqIABAAIgBgBIgBAAgAgTAnIABAAIAAgBIgBAAgAgMAlIABAAIgBgBIgBAAgAgaAfIAAACIACAAIAAgBIgBgBgAgcAeIgBABIABAAIABgBIgBgCgAgUATIABABIAAACIACABIAAACIgBABIAEgDIAAgBIgCAAIgBgBIAAgBIgDgCgAgMAXIABgCIgBAAgAgaAQIABABIABABIAAgCIgCgDgAgMAKIABAAIAAgDIgCAAgAgUAKIAAAAIAAgBIAAAAgAgRAEIABACIgBAAIAAACIgBABIACgBIABgDIAAgBgAgWADIgBABIABADIACgCIABABIABgBIgBgCIACABIgBgCIgBgBIgBADIgBABIAAgBIAAgBIAAgBgAAOAFIABABIAAgCIgBAAgAgEADIABABIABgBIgBgBgAgaACIACACIAAgCIgBgBgAgbAAIAAABIADgBIgCAAgAgPAAIACAAIABAAIAAAAIgCAAgAgLgCIABABIAAgBIgBgBgAgGgGIABAAIgBgBIgBgBIgEAAIABACIABAAIABgBIABgBgAgTgHIABABIABgBIgBgBgAgUgJIACABIABgDIAAgBIgBgBIAAABIgCABIABABIAAgBIAAACIgBgBgAgSgPIABABIABgBgAgTgWIABABIABgBIgBAAgAgVgXIABAAIAAgBIgBAAgAgWgfIABABIABgCIgBgBgAgZgfIABABIABgCIgCgBgAgVgqIABAAIgBgBIgBAAgAgPgqIgBgCIgBgBIACAAIAAgBIgCAAIgBAAIgCAAIADADIACABgAgNgsIAAABIABgBgAgYguIABABIABAAIgBgBgAgTgwIABABIABAAIABgBIgCgBIgBgBgAAQgyIACABIAAgCIgCgBgAgDg0IABAAIgBACIABABIACgBIAAgBIgCgDIgDABIgBABIABgBgAATgyIACgBIgBgBIgBgBIgBAAgAADg2IAAACIABgBIABgBIgBAAgAgUg0IABAAIABgBIgDAAgAAGg2IAAAAIABABIAAgBIgBgBgAAAg4IAAABIACAAIgBgCgAAGg7IAAACIABgBIACAAIgBgBgAgIg5IABgBIgBgBIgBAAgAgDg6IACgCIgDAAgAgQg7IACAAIgBgBIgBAAg");
	this.shape_7.setTransform(508.8,-146.4,1.25,1.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#231F20").s().p("AAnBDIgRABIgEgCIgBAAIgCgGIAAgDIABgDIgBgFIABgCIgBgGIAAgMIAAgGIAAgBIAAgBIABgBIgBgBIABgBIgBgDIgCgCIgCgBIgDABIgCAAIAAgBIgDABIgBgBIgCABIgDAAIgBgBIgIABIgCACIAAAEIAAABIAAABIAAABIAAACIAAAFIAAABIAAABIAAADIAAACIAAADIAAACIAAAGIAAABIAAABIAAABIAAAIIgBACIABACIAAACIgDADIgNAAIgFAAIgCABIgBAAIgCgBIgCAAIgBgBIgBgDIABgEIgBgCIAAgBIABgBIgBAAIAAgOIgBgHIABgCIABgCIgBgBIAAgMIABgFIgBgGIAAgGIABgDIgBgBIAAgCIABgCIgBgBIABgCIgBgCIABgLIgBgCIABgBIgBgCIAAgBIgBgCIABgEIgBgCIABgBIAAgCIAAgCIAAgEIABgBIgBgCIAAgJIAAgCIABgDIACgCIAEgBIAIAAIABABIADgBIAEAAIADABIABAAIACACIABACIAAACIAAAQIgBADIABABIgBABIABABIAAAEIAAACIAAACIAAABIAAACIAAABIgBABIABABIAAABIAAAIIADACIACAAIACAAIARAAIAGgCIgBgCIABgBIgBgGIAAgFIABgBIgBgEIABgCIgBgCIAAgFIABAAIAAgBIgBgGIAAgFIABgCIgBgCIABgGIACgBIAEgBIAFAAIABAAIADAAIAEAAIABABIACgBIAFABIACADIgBACIABABIgBABIAAABIACAFIgBADIAAABIAAAEIAAANIgBACIABADIAAACIAAABIAAADIgBACIACABIgBAEIgBABIABAEIAAALIABABIgBABIAAABIAAAFIAAABIAAACIAAAHIABAFIgBABIABADIgBACIABACIgBACIAAAMIABACIgBAFIABADIgBAEIAAACIgBACIAAABIgBABIgCAAIgBABgAAdAzIABAAIAAgBIgBAAgAAnAyIACAAIgCgBgAgfAuIABADIAAABIAAgDIABgCIgBAAgAgaAoIAAABIACABIABgBIgCgBgAAgApIADAAIAAgBIgCgBIgBAAgAAhAfIABABIABgBIgBgBgAAbAfIAAgBIgBAAgAgbAcIABAAIAAgBIgBAAgAgdAZIABAAIAAgBIgBAAgAggASIABACIACAAIAAABIABABIgBgEIgCAAIgBgBgAAkARIABAAIABgBIgBgBgAAaAPIAEACIAAgCIgCgBIgBAAgAAZANIgBABIADgBIgBgBgAgXAJIAAADIABAAIAAgBIACgBIgCAAIAAAAIAAgBIACgBIgBgCIgCACIAAgDIgCAAgAAZAIIACACIABgBIACgBIgBgBIgCgBIgBACIAAgBIgBAAgAAgAGIABABIACAAIACgCIgCgBIAAACIgCAAgAgPAHIABAAIAAgBIgBAAgAgIAFIABABIABgBIgBgBgAAEAEIAAABIABgBIABgBIgBgBgAAaAEIABAAIABgBIgDAAgAgGAAIgCAAIABABIgBABIgCABIACAAIABgBIABgBIACAAIgBgBIAAAAgAgQADIACgBIgBgBIgBABIgBAAgAgLACIABgBIgCAAgAAXABIADAAIgCgBIgBAAgAATABIACgBIAAAAIgCAAgAAGABIACgBIAAAAIgBAAgAAZgCIACAAIAAABIACgBIABAAIgBgCIgBgBgAALgCIACAAIgBgBgAAVgDIACABIgBgDIgBAAgAgQgDIABABIABgBIABgBIgDgBgAAZgIIAAACIgBABIgBABIACABIAAgCIABgBIACgDIgCAAgAgJgFIAAABIACgBIgBAAgAARgFIABAAIABgBIgCAAgAgXgFIABAAIAAgBIgBAAgAgFgGIABAAIgBgBgAAegIIABAAIABgBIgCgBgAAYgIIgBgEIgCACIgCgBIgBACIABgBIABABIABAAIACABIABAAgAAcgMIACAAIgBgBIgBAAgAgYgMIABAAIAAgBIgBAAgAgdgQIAAABIABABIABgBIABAAIgBgBIAAgBgAAjgQIABAAIAAgBIgBAAgAAegSIACACIAAgCIgBAAgAAcgfIACAAIgBgBgAgWgfIABAAIAAgBIgCAAg");
	this.shape_8.setTransform(495.3,-146.5,1.25,1.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#231F20").s().p("AAZBDIgIABIgCgBIgCABIgCgBIgCABIgEgBIgCABIgDAAIgFAAIgCgBIgDABIgCAAIgDAAIgIAAIgBgBIgBAAIgBABIgBAAIgBgBIgBAAIgBAAIgCAAIgCgCIgBgBIgCgCIgCgBIgCgGIAAgCIABgCIgBgGIABgCIgBgBIABgDIgBgJIABgFIgBgCIAAgBIAAgHIABgCIgBgDIAAgBIABgBIgBgCIABgBIgBgCIAAgCIAAgIIABgCIgBgDIABgFIgBgBIABgCIgBAAIABgDIgBgDIAAgDIABgBIgBgFIAAgBIABgCIgBgBIAAgJIABgBIAAgCIgBgBIAAgDIABgCIAFgHIABgBIADgBIANAAIAFgBIACABIADgBIABABIACAAIACAAIABgBIACABIABAAIABgBIAEABIAEgBIADABIAEgBIACABIAGgBIACABIADAAIADABIACABIABABIACAAIADAIIABABIgBACIABADIgBAEIABACIAAAGIAAAGIAAABIgBABIAAACIgBABIgDAEIgDABIgCAAIgBABIgCABIgCgBIgCACIgLAFIgCgDIAAgCIAAgEIgBgEIABgCIgBgCIABgEIAAgDIgCgCIgBgBIgBAAIgBABIgDgBIgBABIgCgBIgDAAIgBABIgBgBIgFABIgBABIgCACIABAAIAAAJIAAABIAAACIABABIgBAEIAAANIgBAEIABACIABAAIgBAJIgCADIADABIgBADIABABIgBAFIABADIgBAFIABACIgBACIAAAEIABACIABABIACgBIABABIABABIACgBIADAAIABAAIABABIABgBIABAAIAFAAIADgCIAAgEIABgDIgBgBIAAgKIAAgBIABgEIAAAAIABgBIACABIAFAAIACACIAGABIAGADIABABIAGAEIgBABIABACIgBAFIABACIgBACIABAEIgBAEIABADIgBACIABACIgBABIAAADIgBACIAAABIgCABIgCADIgBAAIgBgBIAAADIgCAAIgCABIgBgCIgBABIgBABgAgQA/IABAAIAAgBIgBAAgAAOA7IACABIgBgDIABgCIgCAAgAAYA5IABAAIAAgBIgBgBgAAfA4IABABIABgBIgDgCgAgTA5IABAAIAAgCIgBAAgAgYA1IgBABIACABIAAgCgAgDA1IABABIACAAIAAgBIgCAAIgBgBgAACA0IACAAIABAAIgEgBgAgeA0IABAAIgBgBIgBAAIgCAAgAAXAyIAEACIACgBIgDgBIgBgBIgBAAgAgWAwIgBABIACAAIAAABIgCABIABABIABgBIACAAIABgBIgDAAIABgDgAAjAyIAAABIABAAIABgCIgBgBgAAQAwIABAAIABAAIgBABIACACIAAgBIgBgCIABgBIABgCIgBABIgCAAgAADAwIAAACIACABIABgDIgCgBgAABAwIAAACIABgBIABgCIgBgBgAANAuIgBACIACAAIABgBIgBgCgAAIAuIgBAAIAAACIADgBIABABIAAgDgAgRAwIAEAAIAAgBIgCABIgBgCgAAZAvIACgBIAAgBIgBAAgAAeAqIgBACIAAABIABAAIABAAIAAgDIgBgBgAAXAsIAAABIABgBIACgCIgCAAgAgBAtIABgBIgBAAgAAQAsIABABIACAAIAAgBIgCgBgAAOAtIACAAIgBgBIgBAAgAAjArIAAABIACAAIAAgCgAgeAsIABgBIgBAAgAgOApIAAABIABgBIABgBIgBgBgAATAqIABgBIgBgBgAgWApIABABIAAgCIgBAAgAAXAlIgBACIAAABIABgBIABAAIAAgCIAAgBgAgVAiIgBABIABABIACgCgAgSAQIACAAIABgBIgCgBgAgRAGIABAAIABAAIAAgBIgBAAgAgUgCIABABIABgDIgCAAgAgQgEIABAAIAAgBgAgTgLIABABIABAAIAAgBIgBgBgAgbgKIABAAIAAgBIgBAAgAgZgQIABAAIAAACIABABIACgBIgCgBIAAgBIgBgBgAgcgRIAAgBIgBAAgAgkgTIABABIACgBIgBgBIgBAAIgBAAgAgVgYIABABIABAAIAAgCIAAgCIAAgBgAgbgZIAAgDIgCAAIgCgCIgBABIABABIABABIABAAIABABIABABgAgagcIADABIACgBIABgDIABgBIABAAIAAgCIgBAAIABgBIgCgBIAAACIgBAAIAAgBIgCABIAAABIACAAIABABIgBABIgBACIgBABIgDgBgAgcgjIgBABIABAAIABgCIgCgBIgBAAgAgTgmIAAABIACAAIgBgCIgBgBIAAAAgAgbgmIADAAIACABIACAAIAAgBIgCAAIgCAAIgBgBIgBAAgAgPgrIgBACIACAAIADAAIgBgEIgCABIAAgBIgBgBgAgVgsIgBABIADAAIgBgCgAgcgrIABAAIABgCIgDAAgAAhgvIACAAIAAgCgAgPgxIAAgBIgBAAgAgVg0IgBABIABACIABgBIABgCIgBgBgAAAg4IABAAIAAAAIgBAAgAAPg6IABAAIAAgCIgBAAg");
	this.shape_9.setTransform(481.8,-146.4,1.25,1.25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#E9212D").s().p("ArNCHIAAkOIWbAAIAAEOg");
	this.shape_10.setTransform(539.7,-146.4,1.25,1.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(450,-163.4,179.4,33.9), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#304850").s().p("AgSAWIAAgrIAlAAIAAArg");
	this.shape.setTransform(432.5,-60.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#304850").s().p("Ag3BVIAFgcQAWAFAUABQAPAAAFgCQAGgBAAgGQAAgEgCgBIgIgCIgfgEQgPgBgFgEQgHgFAAgMQAAgNALgKQgQgJAAgXIAAgQQABgpAzAAQAKAAAKADIAnAAIAAASIgMAEQADAHAAAJIAAAQQAAATgMAKQgOAKgYAAIgFAAQgFAFAAACQAAAEAEACIAeADQARABAHAHQAHAGABAQQAAAXgPAJQgOAJgdAAQgXgBgbgGgAgUgwIAAAMQgBANASAAQAPAAAAgNIAAgMQAAgNgPAAQgSAAABANg");
	this.shape_1.setTransform(422.9,-62.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#304850").s().p("AASBBIAAhTQAAgKgJAAQgJAAgRAKIAABTIgmAAIAAh+IAcAAIAEAKQAYgNAaAAQAdAAAAApIAABYg");
	this.shape_2.setTransform(409.2,-64.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#304850").s().p("AgSBbIAAh9IAlAAIAAB9gAgSgyIAAgoIAlAAIAAAog");
	this.shape_3.setTransform(398.4,-67.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#304850").s().p("AgYAyIAAhBIgRAAIAAgfIARAAIAAgeIAlgGIAAAkIAdAAIgCAfIgbAAIAAA8QAAAHAIAAQAIAAAHgCIAFAcQgNAFgOAAQgmAAAAghg");
	this.shape_4.setTransform(390.1,-66.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#304850").s().p("AguA6IAHgcQAQAGAWAAQAGAAADgCQACgCAAgGQAAgHgCgCQgDgCgOgEQgWgFgGgHQgGgHAAgTQAAgVALgIQAKgJAbAAQAXAAAPAEIgDAdQgUgDgPAAQgNAAAAAIQAAAGADACQACACAKACQAaAGAIAJQAFAGAAAUQAAAUgKAKQgKAKgaAAQgWAAgYgIg");
	this.shape_5.setTransform(379.9,-64.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#304850").s().p("Ag0AOIAAgcQAAgzA2AAQAdAAAMAQQAKANAAAYIAAAZIhDAAIAAAEQAAALAFADQAFAEAMAAQAUAAASgFIAFAcQgWAIgZAAQg4AAAAg0gAgOgTIAAAFIAfAAIAAgFQAAgRgPAAQgQAAAAARg");
	this.shape_6.setTransform(367.9,-64.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#304850").s().p("AgXA/Igoh9IAmAAIAZBYIAahYIAmAAIgoB9g");
	this.shape_7.setTransform(355.1,-64.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#304850").s().p("AASBBIAAhTQAAgKgJAAQgJAAgRAKIAABTIgmAAIAAh+IAcAAIAEAKQAYgNAaAAQAdAAAAApIAABYg");
	this.shape_8.setTransform(341.4,-64.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#304850").s().p("AgSBbIAAh9IAlAAIAAB9gAgSgyIAAgoIAlAAIAAAog");
	this.shape_9.setTransform(330.6,-67.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#304850").s().p("AgZBcIAAhdIgTAAIAAgeIATAAIAAgTQAAgpAqAAQALAAARAEIgEAdIgRgCQgIAAgDAEQgCADAAAHIAAAPIAfAAIgEAeIgbAAIAABdg");
	this.shape_10.setTransform(317.1,-67.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#304850").s().p("Ag4APIAAgdQAAgzA4AAQA5AAAAAzIAAAdQAAAzg5AAQg4AAAAgzgAgTgPIAAAfQAAASATAAQAUAAAAgSIAAgfQAAgTgUAAQgTAAAAATg");
	this.shape_11.setTransform(305.2,-64.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#304850").s().p("AgtA6IAGgcQARAGAVAAQAGAAADgCQACgCAAgGQABgHgDgCQgDgCgOgEQgWgFgGgHQgFgHgBgTQABgVAJgIQALgJAbAAQAYAAAPAEIgEAdQgTgDgPAAQgNAAAAAIQAAAGACACQADACAKACQAaAGAHAJQAGAGgBAUQABAUgLAKQgLAKgZAAQgWAAgXgIg");
	this.shape_12.setTransform(287.5,-64.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#304850").s().p("AASBBIAAhTQAAgKgJAAQgJAAgRAKIAABTIglAAIAAh+IAbAAIAEAKQAYgNAaAAQAcAAAAApIAABYg");
	this.shape_13.setTransform(274.7,-64.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#304850").s().p("AAZA/IgZhRIgYBRIgoAAIgWh9IAiAAIANBJIAWhJIAkAAIAWBJIAMhJIAiAAIgWB9g");
	this.shape_14.setTransform(258.2,-64.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#304850").s().p("Ag4APIAAgdQAAgzA4AAQA5AAAAAzIAAAdQAAAzg5AAQg4AAAAgzgAgTgPIAAAfQAAASATAAQATAAABgSIAAgfQgBgTgTAAQgTAAAAATg");
	this.shape_15.setTransform(242.3,-64.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#304850").s().p("Ag3AvIAAgnQAAgtArgBQAQAAAPAEIAAg1IAlgFIAAC3IgdAAIgEgKQgUAMgSAAQgoAAAAgugAgSAIIAAAnQAAANAOAAQAMAAALgKIAAg0QgNgDgKAAQgOAAAAANg");
	this.shape_16.setTransform(228.2,-67.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#304850").s().p("Ag3AuIAAgmQAAgtAqAAQARAAAPADIAAg1IAlgFIAAC3IgdAAIgEgKQgVAMgRAAQgoAAAAgvgAgSAIIAAAmQAAAPAOAAQAMAAALgLIAAg0QgNgDgKAAQgOAAAAANg");
	this.shape_17.setTransform(409.9,-93.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#304850").s().p("AASBBIAAhTQAAgKgJABQgJgBgRAKIAABTIgmAAIAAh+IAcAAIAEAKQAYgMAaAAQAdAAAAAoIAABYg");
	this.shape_18.setTransform(396.1,-90.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#304850").s().p("AgyAbQAAgTAJgIQAJgHAUAAIAaAAIAAgKQAAgKgEgDQgEgEgOAAQgRAAgRADIgFgcQAVgGAZAAQAfAAALALQAKAKAAAbIAABQIgeAAIgDgIQgSALgRAAQghAAAAgngAgOAbQAAAKAKAAQAIAAAKgFIAAgOIgRAAQgLAAAAAJg");
	this.shape_19.setTransform(382.3,-90.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#304850").s().p("AgtA6IAGgcQAQAGAWAAQAGAAADgCQADgCgBgGQABgHgDgCQgDgCgOgEQgWgFgGgHQgFgHgBgTQABgVAJgIQALgJAbAAQAYAAAOAEIgDAdQgUgDgPAAQgNAAAAAIQABAGACACQACACALACQAZAGAIAJQAFAGAAAUQABAUgLAKQgLAKgZAAQgWAAgXgIg");
	this.shape_20.setTransform(364.9,-90.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#304850").s().p("Ag3hZIAdAAIAEAKQAVgNARAAQAoAAAAAvIAAAmQAAAugqAAQgRAAgPgEIAAA0IglAGgAgSgyIAAA1QANADAKAAQAOAAAAgNIAAgmQAAgOgOAAQgLAAgMAJg");
	this.shape_21.setTransform(352.5,-88.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#304850").s().p("Ag3AYIAAhYIAmAAIAABTQAAAJAJAAQAKAAAQgJIAAhTIAmAAIAAB+IgcAAIgEgKQgYANgaAAQgdAAAAgpg");
	this.shape_22.setTransform(337.9,-90.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#304850").s().p("Ag0AOIAAgcQAAgzA2AAQAdAAAMAQQAKANAAAYIAAAZIhDAAIAAAEQAAALAFADQAFAEAMAAQAUAAASgFIAFAcQgWAIgZAAQg4AAAAg0gAgOgTIAAAFIAfAAIAAgFQAAgRgPAAQgQAAAAARg");
	this.shape_23.setTransform(319,-90.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#304850").s().p("AASBcIAAhUQAAgIgJAAQgIAAgSAIIAABUIgmAAIAAiyIAlgFIAABCQAZgLAUAAQAdAAAAAnIAABZg");
	this.shape_24.setTransform(305.6,-93.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#304850").s().p("AgYAyIAAhBIgRAAIAAgfIARAAIAAgeIAlgGIAAAkIAdAAIgCAfIgbAAIAAA8QAAAHAIAAQAIAAAHgCIAFAcQgNAFgOAAQgmAAAAghg");
	this.shape_25.setTransform(293.5,-92.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#304850").s().p("AASBBIAAhTQAAgKgJABQgJgBgRAKIAABTIgmAAIAAh+IAcAAIAEAKQAYgMAaAAQAdAAAAAoIAABYg");
	this.shape_26.setTransform(276.4,-90.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#304850").s().p("AgjBBIAAh+IAgAAIADAMQAPgLASgDIACAiQgYALgJAGIAABNg");
	this.shape_27.setTransform(265.4,-90.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#304850").s().p("AgyAbQAAgTAJgIQAJgHATAAIAbAAIAAgKQAAgKgEgDQgEgEgOAAQgRAAgRADIgFgcQAUgGAZAAQAfAAAMALQAKAKAAAbIAABQIgfAAIgCgIQgSALgRAAQghAAAAgngAgPAbQAAAKALAAQAHAAALgFIAAgOIgRAAQgMAAAAAJg");
	this.shape_28.setTransform(253.6,-90.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#304850").s().p("Ag0AOIAAgcQAAgzA1AAQAeAAAMAQQAKANAAAYIAAAZIhDAAIAAAEQAAALAFADQAEAEAMAAQAVAAASgFIAFAcQgXAIgYAAQg4AAAAg0gAgOgTIAAAFIAfAAIAAgFQAAgRgPAAQgQAAAAARg");
	this.shape_29.setTransform(240.9,-90.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#304850").s().p("Ag1BXIAAisIAnAAIAACJIBEAAIAAAjg");
	this.shape_30.setTransform(228.7,-93.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(222.6,-102.8,211.8,49.7), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E2F3EF").s().p("A3bNXIAA6tMAu3AAAIAAatg");
	this.shape.setTransform(150,85.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,300,171), null);


(lib.redtween = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#E9212D").ss(2.5,1).p("AhjBpIDHjR");
	this.shape.setTransform(10,31.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.redtween, new cjs.Rectangle(-1.2,19.7,22.5,23.3), null);


(lib.Path_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#80C9B6").s().p("AlsFsIABhLIBchWIAcAoIBEhoIAmAtIH2ojIAALXg");
	this.shape.setTransform(36.5,57.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path_1, new cjs.Rectangle(0,21,72.9,72.9), null);


(lib.brokenline = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#E9212D").ss(2.5,1).p("AhjBpIDHjR");
	this.shape.setTransform(10,31.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.brokenline, new cjs.Rectangle(-1.2,19.7,22.5,23.3), null);


(lib.Symbol10 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 4
	this.instance = new lib.brokenline();
	this.instance.parent = this;
	this.instance.setTransform(63.1,59.6,1,1,0,0,0,0,41.9);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(70).to({_off:false},0).wait(1).to({regX:10,regY:31.4,rotation:8.7,x:74.6,y:50.7},0).wait(1).to({rotation:19.3,x:76,y:53},0).wait(1).to({rotation:32.1,x:77.1,y:55.9},0).wait(1).to({rotation:47,x:77.5,y:59.7},0).wait(1).to({rotation:63.5,x:76.9,y:63.8},0).wait(1).to({rotation:80.3,x:75.1,y:67.6},0).wait(1).to({rotation:96,x:72.4,y:70.6},0).wait(1).to({rotation:109.7,x:69.5,y:72.4},0).wait(1).to({rotation:121.3,x:66.8,y:73.5},0).wait(1).to({rotation:130.8,x:64.4,y:73.9},0).wait(1).to({rotation:138.6,x:62.4},0).wait(1).to({rotation:144.9,x:60.9,y:73.8},0).wait(1).to({rotation:150,x:59.6,y:73.6},0).wait(1).to({rotation:154.2,x:58.6,y:73.3},0).wait(1).to({rotation:157.4,x:57.8,y:73},0).wait(1).to({rotation:160,x:57.2,y:72.7},0).wait(1).to({rotation:161.9,x:56.8,y:72.6},0).wait(1).to({rotation:163.4,x:56.4,y:72.4},0).wait(1).to({rotation:164.3,x:56.2,y:72.3},0).wait(1).to({rotation:164.8,x:56.1,y:72.2},0).wait(1).to({regX:0,regY:41.8,rotation:165,x:63.1,y:59.5},0).wait(1).to({regX:10,regY:31.4,rotation:164.7,x:56.1,y:72.1},0).wait(1).to({rotation:163.8,x:56.4,y:72.3},0).wait(1).to({rotation:162.1,x:56.8,y:72.5},0).wait(1).to({rotation:159.3,x:57.3,y:72.7},0).wait(1).to({rotation:155.4,x:58.3,y:73.1},0).wait(1).to({rotation:150.1,x:59.6,y:73.5},0).wait(1).to({rotation:143.6,x:61.2,y:73.8},0).wait(1).to({rotation:136.4,x:63,y:73.9},0).wait(1).to({rotation:129.5,x:64.8,y:73.8},0).wait(1).to({rotation:123.7,x:66.2,y:73.6},0).wait(1).to({rotation:119.2,x:67.4,y:73.3},0).wait(1).to({rotation:115.8,x:68.1,y:73},0).wait(1).to({rotation:113.5,x:68.6,y:72.8},0).wait(1).to({rotation:112.1,x:69,y:72.6},0).wait(1).to({rotation:111.3,x:69.2,y:72.5},0).wait(1).to({regX:0,regY:41.7,rotation:111,x:63.2,y:59.5},0).wait(1).to({regX:10,regY:31.4,rotation:111.1,x:69.2,y:72.6},0).wait(1).to({rotation:111.4,x:69.1,y:72.5},0).wait(1).to({rotation:112,x:69,y:72.6},0).wait(1).to({rotation:112.9,x:68.8,y:72.7},0).wait(1).to({rotation:114.2,x:68.5,y:72.8},0).wait(1).to({rotation:115.9,x:68.1,y:73},0).wait(1).to({rotation:118.1,x:67.6,y:73.1},0).wait(1).to({rotation:120.8,x:67,y:73.4},0).wait(1).to({rotation:124,x:66.1,y:73.5},0).wait(1).to({rotation:127.4,x:65.3,y:73.7},0).wait(1).to({rotation:130.9,x:64.4,y:73.8},0).wait(1).to({rotation:134.1,x:63.7,y:73.9},0).wait(1).to({rotation:136.9,x:63},0).wait(1).to({rotation:139.2,x:62.4},0).wait(1).to({rotation:141.1,x:61.9,y:73.8},0).wait(1).to({rotation:142.5,x:61.6},0).wait(1).to({rotation:143.6,x:61.3},0).wait(1).to({rotation:144.4,x:61.1,y:73.7},0).wait(1).to({rotation:144.9,x:61,y:73.6},0).wait(1).to({rotation:145.1,x:60.9,y:73.7},0).wait(1).to({regX:0,regY:41.7,rotation:145.2,x:63.2,y:59.5},0).wait(1).to({regX:10,regY:31.4,x:60.9,y:73.6},0).wait(1).to({rotation:145.1},0).wait(1).to({rotation:144.9,y:73.7},0).wait(1).to({rotation:144.7,x:61},0).wait(1).to({rotation:144.3,x:61.1},0).wait(1).to({rotation:143.9,x:61.2},0).wait(1).to({rotation:143.3,x:61.4,y:73.8},0).wait(1).to({rotation:142.6,x:61.5},0).wait(1).to({rotation:141.7,x:61.7},0).wait(1).to({rotation:140.7,x:62},0).wait(1).to({rotation:139.6,x:62.3,y:73.9},0).wait(1).to({rotation:138.2,x:62.6},0).wait(1).to({rotation:136.8,x:63},0).wait(1).to({rotation:135.3,x:63.4},0).wait(1).to({rotation:133.7,x:63.8},0).wait(1).to({rotation:132.2,x:64.2,y:73.8},0).wait(1).to({rotation:130.8,x:64.4},0).wait(1).to({rotation:129.5,x:64.8},0).wait(1).to({rotation:128.3,x:65.1},0).wait(1).to({rotation:127.3,x:65.4,y:73.7},0).wait(1).to({rotation:126.5,x:65.6},0).wait(1).to({rotation:125.7,x:65.7},0).wait(1).to({rotation:125.1,x:65.9},0).wait(1).to({rotation:124.6,x:66},0).wait(1).to({rotation:124.3,x:66.1,y:73.6},0).wait(1).to({rotation:124},0).wait(1).to({rotation:123.7,x:66.2},0).wait(1).to({rotation:123.6},0).wait(1).to({rotation:123.5,x:66.3},0).wait(1).to({regX:0,regY:41.6,x:63.3,y:59.6},0).wait(1).to({regX:10,regY:31.4,x:66.3,y:73.6},0).wait(1).to({rotation:123.7,x:66.2},0).wait(1).to({rotation:124,x:66.1},0).wait(1).to({rotation:124.4,x:66},0).wait(1).to({rotation:125.1,x:65.9,y:73.7},0).wait(1).to({rotation:125.9,x:65.7},0).wait(1).to({rotation:127,x:65.4},0).wait(1).to({rotation:128.3,x:65.1,y:73.8},0).wait(1).to({rotation:129.9,x:64.7},0).wait(1).to({rotation:131.7,x:64.2},0).wait(1).to({rotation:133.5,x:63.8},0).wait(1).to({rotation:135.3,x:63.4,y:73.9},0).wait(1).to({rotation:136.9,x:63},0).wait(1).to({rotation:138.3,x:62.7},0).wait(1).to({rotation:139.5,x:62.3,y:73.8},0).wait(1).to({rotation:140.4,x:62.1},0).wait(1).to({rotation:141.1,x:61.9},0).wait(1).to({rotation:141.6,x:61.8},0).wait(1).to({rotation:142,x:61.7},0).wait(1).to({rotation:142.3,y:73.7},0).wait(1).to({rotation:142.4,x:61.6},0).wait(1).to({regX:-0.1,regY:41.6,rotation:142.5,x:63.4,y:59.5},0).wait(1).to({regX:10,regY:31.4,x:61.5,y:73.7},0).wait(1).to({rotation:142.4,x:61.6},0).wait(1).to({y:73.8},0).wait(1).to({rotation:142.3,y:73.7},0).wait(1).to({rotation:142.2,y:73.8},0).wait(1).to({rotation:142,y:73.7},0).wait(1).to({rotation:141.8,x:61.7,y:73.8},0).wait(1).to({rotation:141.6,x:61.8,y:73.7},0).wait(1).to({rotation:141.3,y:73.8},0).wait(1).to({rotation:140.9,x:61.9},0).wait(1).to({rotation:140.5,x:62.1},0).wait(1).to({rotation:140.1,x:62.2},0).wait(1).to({rotation:139.6,x:62.3},0).wait(1).to({rotation:139,x:62.4},0).wait(1).to({rotation:138.5,x:62.5},0).wait(1).to({rotation:138,x:62.7},0).wait(1).to({rotation:137.5,x:62.8},0).wait(1).to({rotation:137.1,x:62.9},0).wait(1).to({rotation:136.7,x:63},0).wait(1).to({rotation:136.3,x:63.1,y:73.9},0).wait(1).to({rotation:136,x:63.2},0).wait(1).to({rotation:135.8,y:73.8},0).wait(1).to({rotation:135.6,x:63.3,y:73.9},0).wait(1).to({rotation:135.4},0).wait(1).to({rotation:135.3,x:63.4},0).wait(1).to({rotation:135.2},0).wait(1).to({rotation:135.1,y:73.8},0).wait(1).to({rotation:135,y:73.9},0).wait(2).to({regX:-0.1,regY:41.6,y:59.6},0).wait(1));

	// Layer 5
	this.instance_1 = new lib.redtween();
	this.instance_1.parent = this;
	this.instance_1.setTransform(83.2,38.6,1,1,0,0,0,20.1,20.9);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(54).to({_off:false},0).wait(1).to({regX:10,regY:31.4,x:73.1,y:49.1,alpha:0.002},0).wait(1).to({alpha:0.006},0).wait(1).to({alpha:0.015},0).wait(1).to({alpha:0.029},0).wait(1).to({alpha:0.048},0).wait(1).to({alpha:0.074},0).wait(1).to({alpha:0.109},0).wait(1).to({alpha:0.156},0).wait(1).to({alpha:0.219},0).wait(1).to({alpha:0.303},0).wait(1).to({alpha:0.415},0).wait(1).to({alpha:0.555},0).wait(1).to({alpha:0.703},0).wait(1).to({alpha:0.83},0).wait(1).to({alpha:0.927},0).wait(1).to({regX:20.1,regY:20.9,x:83.2,y:38.6,alpha:1},0).to({_off:true},1).wait(140));

	// Layer 3 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_1 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_2 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_3 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_4 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_5 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_6 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_7 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_8 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_9 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_10 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_11 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_12 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_13 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_14 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_15 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_16 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_17 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_18 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_19 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_20 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_21 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_22 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_23 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_24 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_25 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_26 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_27 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_28 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_29 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_30 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_31 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_32 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_33 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_34 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_35 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_36 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_37 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_38 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_39 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_40 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_41 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_42 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_43 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_44 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_45 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_46 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_47 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_48 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_49 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_50 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_51 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_52 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_53 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_54 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_55 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_56 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_57 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_58 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_59 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_60 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_61 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_62 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_63 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_64 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_65 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_66 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_67 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_68 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_69 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_70 = new cjs.Graphics().p("Ap/IuIAAv7IT/AAIAAP7g");
	var mask_graphics_71 = new cjs.Graphics().p("AoTHIIAAogII/AAIHdlvIALFvIgiAAIAAIgg");
	var mask_graphics_72 = new cjs.Graphics().p("Ao1GbIAAofII/AAQA8gvD9h4QB/g8B0gzQgSAugSA7QghB1ABA3IghABIAAIfg");
	var mask_graphics_73 = new cjs.Graphics().p("ApEFaIAAofIJAAAQBQgbEEg/ID0g7IiCK0g");
	var mask_graphics_74 = new cjs.Graphics().p("ApHERIAAogII/AAQCWgBG6AIIiKIZg");
	var mask_graphics_75 = new cjs.Graphics().p("ApCEQIAAofII/AAIJGC9IiAFig");
	var mask_graphics_76 = new cjs.Graphics().p("AoiEQIAAofII/AAQB/BQDQCYQBpBLBOA6IhACyg");
	var mask_graphics_77 = new cjs.Graphics().p("AoCEQIAAofII/AAIEEE7QCTCzAAgBIAvAyg");
	var mask_graphics_78 = new cjs.Graphics().p("AmpEQIAAofII/AAQBFCGBwDeIBfC7g");
	var mask_graphics_79 = new cjs.Graphics().p("AllEQIAAofII/AAQA3EDBVEcg");
	var mask_graphics_80 = new cjs.Graphics().p("Ak3kPII/AAQAtIeADABIpvAAgAE4EQIAAAAIAAAAIAAAAg");
	var mask_graphics_81 = new cjs.Graphics().p("AkgkPII+AAQADFrAAC0IpBAAg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:-54.7,y:55.8}).wait(1).to({graphics:mask_graphics_1,x:-54.7,y:55.8}).wait(1).to({graphics:mask_graphics_2,x:-54.6,y:55.8}).wait(1).to({graphics:mask_graphics_3,x:-54.4,y:55.8}).wait(1).to({graphics:mask_graphics_4,x:-54.2,y:55.8}).wait(1).to({graphics:mask_graphics_5,x:-53.9,y:55.8}).wait(1).to({graphics:mask_graphics_6,x:-53.5,y:55.8}).wait(1).to({graphics:mask_graphics_7,x:-53.1,y:55.8}).wait(1).to({graphics:mask_graphics_8,x:-52.6,y:55.8}).wait(1).to({graphics:mask_graphics_9,x:-52,y:55.8}).wait(1).to({graphics:mask_graphics_10,x:-51.3,y:55.8}).wait(1).to({graphics:mask_graphics_11,x:-50.6,y:55.8}).wait(1).to({graphics:mask_graphics_12,x:-49.8,y:55.8}).wait(1).to({graphics:mask_graphics_13,x:-48.9,y:55.8}).wait(1).to({graphics:mask_graphics_14,x:-48,y:55.8}).wait(1).to({graphics:mask_graphics_15,x:-47,y:55.8}).wait(1).to({graphics:mask_graphics_16,x:-45.9,y:55.8}).wait(1).to({graphics:mask_graphics_17,x:-44.8,y:55.8}).wait(1).to({graphics:mask_graphics_18,x:-43.5,y:55.8}).wait(1).to({graphics:mask_graphics_19,x:-42.2,y:55.8}).wait(1).to({graphics:mask_graphics_20,x:-40.9,y:55.8}).wait(1).to({graphics:mask_graphics_21,x:-39.5,y:55.8}).wait(1).to({graphics:mask_graphics_22,x:-38,y:55.8}).wait(1).to({graphics:mask_graphics_23,x:-36.5,y:55.8}).wait(1).to({graphics:mask_graphics_24,x:-34.9,y:55.8}).wait(1).to({graphics:mask_graphics_25,x:-33.2,y:55.8}).wait(1).to({graphics:mask_graphics_26,x:-31.6,y:55.8}).wait(1).to({graphics:mask_graphics_27,x:-29.8,y:55.8}).wait(1).to({graphics:mask_graphics_28,x:-28.1,y:55.8}).wait(1).to({graphics:mask_graphics_29,x:-26.3,y:55.8}).wait(1).to({graphics:mask_graphics_30,x:-24.5,y:55.8}).wait(1).to({graphics:mask_graphics_31,x:-22.6,y:55.8}).wait(1).to({graphics:mask_graphics_32,x:-20.8,y:55.8}).wait(1).to({graphics:mask_graphics_33,x:-18.9,y:55.8}).wait(1).to({graphics:mask_graphics_34,x:-17,y:55.8}).wait(1).to({graphics:mask_graphics_35,x:-15.2,y:55.8}).wait(1).to({graphics:mask_graphics_36,x:-13.3,y:55.8}).wait(1).to({graphics:mask_graphics_37,x:-11.5,y:55.8}).wait(1).to({graphics:mask_graphics_38,x:-9.6,y:55.8}).wait(1).to({graphics:mask_graphics_39,x:-7.8,y:55.8}).wait(1).to({graphics:mask_graphics_40,x:-6.1,y:55.8}).wait(1).to({graphics:mask_graphics_41,x:-4.3,y:55.8}).wait(1).to({graphics:mask_graphics_42,x:-2.6,y:55.8}).wait(1).to({graphics:mask_graphics_43,x:-1,y:55.8}).wait(1).to({graphics:mask_graphics_44,x:0.6,y:55.8}).wait(1).to({graphics:mask_graphics_45,x:2.2,y:55.8}).wait(1).to({graphics:mask_graphics_46,x:3.7,y:55.8}).wait(1).to({graphics:mask_graphics_47,x:5.2,y:55.8}).wait(1).to({graphics:mask_graphics_48,x:6.6,y:55.8}).wait(1).to({graphics:mask_graphics_49,x:7.9,y:55.8}).wait(1).to({graphics:mask_graphics_50,x:9.2,y:55.8}).wait(1).to({graphics:mask_graphics_51,x:10.4,y:55.8}).wait(1).to({graphics:mask_graphics_52,x:11.6,y:55.8}).wait(1).to({graphics:mask_graphics_53,x:12.7,y:55.8}).wait(1).to({graphics:mask_graphics_54,x:13.7,y:55.8}).wait(1).to({graphics:mask_graphics_55,x:14.7,y:55.8}).wait(1).to({graphics:mask_graphics_56,x:15.5,y:55.8}).wait(1).to({graphics:mask_graphics_57,x:16.4,y:55.8}).wait(1).to({graphics:mask_graphics_58,x:17.1,y:55.8}).wait(1).to({graphics:mask_graphics_59,x:17.8,y:55.8}).wait(1).to({graphics:mask_graphics_60,x:18.5,y:55.8}).wait(1).to({graphics:mask_graphics_61,x:19,y:55.8}).wait(1).to({graphics:mask_graphics_62,x:19.5,y:55.8}).wait(1).to({graphics:mask_graphics_63,x:20,y:55.8}).wait(1).to({graphics:mask_graphics_64,x:20.4,y:55.8}).wait(1).to({graphics:mask_graphics_65,x:20.7,y:55.8}).wait(1).to({graphics:mask_graphics_66,x:20.9,y:55.8}).wait(1).to({graphics:mask_graphics_67,x:21.1,y:55.8}).wait(1).to({graphics:mask_graphics_68,x:21.3,y:55.8}).wait(1).to({graphics:mask_graphics_69,x:21.4,y:55.8}).wait(1).to({graphics:mask_graphics_70,x:21.4,y:55.8}).wait(1).to({graphics:mask_graphics_71,x:59.3,y:68.4}).wait(1).to({graphics:mask_graphics_72,x:62.7,y:72.9}).wait(1).to({graphics:mask_graphics_73,x:64.2,y:79.4}).wait(1).to({graphics:mask_graphics_74,x:64.6,y:86.8}).wait(1).to({graphics:mask_graphics_75,x:64.1,y:86.8}).wait(1).to({graphics:mask_graphics_76,x:60.9,y:86.8}).wait(1).to({graphics:mask_graphics_77,x:57.7,y:86.8}).wait(1).to({graphics:mask_graphics_78,x:48.7,y:86.8}).wait(1).to({graphics:mask_graphics_79,x:42,y:86.8}).wait(1).to({graphics:mask_graphics_80,x:37.3,y:86.8}).wait(1).to({graphics:mask_graphics_81,x:35.1,y:86.8}).wait(130));

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#80C9B6").ss(2.5,1).p("AFilBIntIMIgngtIhDBoIgcgoIhQBk");
	this.shape.setTransform(46,71.7);

	this.instance_2 = new lib.Path_1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(56.3,64.6,1,1,0,0,0,47,46.9);
	this.instance_2.alpha = 0.301;

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#80C9B6").ss(2.5,1).p("AEHjdIk4FEIgmgtIhEBpIgcgoIhPBj");
	this.shape_1.setTransform(37,81.7);

	var maskedShapeInstanceList = [this.shape,this.instance_2,this.shape_1];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.shape}]}).to({state:[{t:this.instance_2},{t:this.shape_1}]},70).wait(141));

	// bg
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFFFFF").ss(0.5).p("AAAnQIAAOh");
	this.shape_2.setTransform(138.8,78,1,0.726);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFFFFF").ss(0.5).p("AAAniIAAPG");
	this.shape_3.setTransform(124.4,79.3,1,0.726);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#FFFFFF").ss(0.5).p("AAAnQIAAOh");
	this.shape_4.setTransform(110,78,1,0.726);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f().s("#FFFFFF").ss(0.5).p("AAAniIAAPG");
	this.shape_5.setTransform(95.5,79.3,1,0.726);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#FFFFFF").ss(0.5).p("AAAnQIAAOh");
	this.shape_6.setTransform(81.1,78,1,0.726);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#FFFFFF").ss(0.5).p("AAAniIAAPG");
	this.shape_7.setTransform(66.7,79.3,1,0.726);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FFFFFF").ss(0.5).p("AAAnQIAAOh");
	this.shape_8.setTransform(52.2,78,1,0.726);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#FFFFFF").ss(0.5).p("AAAniIAAPG");
	this.shape_9.setTransform(37.8,79.3,1,0.726);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#FFFFFF").ss(0.5).p("AAAnQIAAOh");
	this.shape_10.setTransform(23.4,78,1,0.726);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#FFFFFF").ss(0.5).p("ArLAAIWYAA");
	this.shape_11.setTransform(81.6,46.9,1,0.726);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#FFFFFF").ss(0.5).p("AriAAIXFAA");
	this.shape_12.setTransform(79.4,56.1,1,0.726);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#FFFFFF").ss(0.5).p("ArLAAIWYAA");
	this.shape_13.setTransform(81.6,65.3,1,0.726);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(0.5).p("AriAAIXFAA");
	this.shape_14.setTransform(79.4,74.5,1,0.726);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#FFFFFF").ss(0.5).p("ArLAAIWYAA");
	this.shape_15.setTransform(81.6,83.7,1,0.726);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("#FFFFFF").ss(0.5).p("AriAAIXFAA");
	this.shape_16.setTransform(79.4,92.9,1,0.726);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f().s("#FFFFFF").ss(0.5).p("ArKAAIWVAA");
	this.shape_17.setTransform(81.5,102.1,1,0.726);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("#FFFFFF").ss(0.7).p("ALQHiI2aAAIAAvI");
	this.shape_18.setTransform(81.1,76.9,1,0.726);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#304850").s().p("Az0G9IAAt5MAnpAAAIAAN5g");
	this.shape_19.setTransform(78.7,74.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2}]}).wait(211));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-48.1,30,253.7,89);


// stage content:
(lib._728x90_stocks = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// graph
	this.instance = new lib.Symbol10("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(132.8,27.1,1.075,1.075,0,0,0,81.8,60.6);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(440));

	// Layer 1
	this.instance_1 = new lib.Symbol4();
	this.instance_1.parent = this;
	this.instance_1.setTransform(147.5,224.8,1,1,0,0,0,73.5,9.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(66).to({_off:false},0).to({alpha:1},15,cjs.Ease.get(-1)).wait(359));

	// Layer 1
	this.instance_2 = new lib.Symbol3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(147.7,194.3,1,1,0,0,0,71.8,13.6);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(51).to({_off:false},0).to({alpha:1},19,cjs.Ease.get(-1)).wait(370));

	// Text
	this.instance_3 = new lib.Symbol2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(149.9,154.1,1,1,0,0,0,78.9,20.6);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(27).to({_off:false},0).wait(1).to({regX:328.5,regY:-78,x:399.5,y:55,alpha:0.045},0).wait(1).to({y:54.4,alpha:0.105},0).wait(1).to({y:53.6,alpha:0.189},0).wait(1).to({y:52.4,alpha:0.31},0).wait(1).to({y:50.8,alpha:0.466},0).wait(1).to({y:49.5,alpha:0.599},0).wait(1).to({y:48.6,alpha:0.69},0).wait(1).to({y:47.9,alpha:0.755},0).wait(1).to({y:47.5,alpha:0.804},0).wait(1).to({y:47.1,alpha:0.842},0).wait(1).to({y:46.8,alpha:0.872},0).wait(1).to({y:46.5,alpha:0.897},0).wait(1).to({y:46.3,alpha:0.917},0).wait(1).to({y:46.2,alpha:0.934},0).wait(1).to({y:46,alpha:0.948},0).wait(1).to({y:45.9,alpha:0.96},0).wait(1).to({y:45.8,alpha:0.97},0).wait(1).to({y:45.7,alpha:0.978},0).wait(1).to({alpha:0.984},0).wait(1).to({y:45.6,alpha:0.99},0).wait(1).to({alpha:0.994},0).wait(1).to({y:45.5,alpha:0.996},0).wait(1).to({alpha:0.998},0).wait(1).to({alpha:1},0).wait(1).to({regX:78.9,regY:20.6,x:149.9,y:144.1},0).wait(388));

	// teal
	this.instance_4 = new lib.Symbol1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(364,47.5,2.447,0.673,0,0,0,150,85.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(440));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(357.1,35,738,115);
// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;