(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"300x600_drive_atlas_", frames: [[0,0,500,445],[0,447,626,120]]}
];


// symbols:



(lib.beardyl = function() {
	this.spriteSheet = ss["300x600_drive_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.docBC = function() {
	this.spriteSheet = ss["300x600_drive_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.docBC();
	this.instance.parent = this;
	this.instance.setTransform(-142,-30,0.9,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-142,-30,563.4,108);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAOIgEgDIgEgFIgBgGIABgFIAEgFIAEgDIAFgBIAGABIAFADIADAFIABAFIgBAGIgDAFIgFADIgGABg");
	this.shape.setTransform(68.7,280.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_1.setTransform(61.6,274);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXAeIAWhBIAZAKIgeA+g");
	this.shape_2.setTransform(53.5,267.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgIgHQgGgHgNAAQgIAAgHADQgIAEgGAFIAABHIAQAAIAAAUIg5AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_3.setTransform(42.1,275.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_4.setTransform(28.2,275.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_5.setTransform(18.8,272.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgNAAQgIAAgJAEQgHADgGAGIAABGIAQAAIAAAUIg4AAIAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgIAAgHADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIALgEIAKgBQANAAAJAFQAJAFAFAKIAJgHIALgHIALgEQAGgCAHAAQAJAAAIADQAIADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_6.setTransform(-2.4,275.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_7.setTransform(-21.2,275.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AASA9IAAgUIAGAAIgYgeIgWAeIAGAAIAAAUIgpAAIAAgUIAKAAIAlgqIgigmIgNAAIAAgVIApAAIAAAVIgFAAIAVAcIAXgcIgGAAIAAgVIAoAAIAAAVIgKAAIgiAnIAkApIAJAAIAAAUg");
	this.shape_8.setTransform(-33.9,275.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgUA8QgKgEgIgJQgHgHgFgNQgDgMAAgPQgBgNAEgLQADgMAIgIQAHgJAKgFQAMgFAMAAQAOAAAKAEQAIAFAGAGQAGAHADAJQADAJACAIIAAAJIABAIIhXAAIAAAKIADAIQAEAMAKAGQAJAFALABQAKgBAJgCQAJgCAJgGIAJAOQgLAJgMAEQgNAEgNAAQgLAAgLgEgAAfgOIgCgMQgCgFgEgFQgDgEgGgDQgFgCgIAAQgGAAgHACQgFACgEAFQgEADgCAHQgDAFgBAHIA+AAg");
	this.shape_9.setTransform(-47.5,275.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_10.setTransform(141.8,247);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_11.setTransform(131.5,248.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_12.setTransform(122,245.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_13.setTransform(112.3,248.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_14.setTransform(102.4,247);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgTA8QgLgEgIgJQgHgHgEgMQgFgNAAgPQABgMADgMQADgMAIgIQAHgJALgFQALgFANAAQANAAAJAEQAJAFAHAGQAFAHADAJQADAJABAIIABAJIAAAIIhWAAIABAKIACAIQAEAMAJAGQAKAFAMABQAJgBAJgCQAIgCAKgGIAJAOQgMAJgMAEQgMAEgNAAQgLAAgKgEgAAfgOIgCgMQgCgFgDgFQgEgEgFgDQgGgCgIAAQgHAAgFACQgGACgEAFQgEADgDAHQgCAFgBAHIA+AAg");
	this.shape_15.setTransform(90.7,248.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgNAAQgIAAgJAEQgIADgGAGIAABGIARAAIAAAUIg4AAIAAgUIASAAIAAg3QAAgOgIgHQgGgHgNAAQgJAAgHADQgIAEgGAFIAABHIAQAAIAAAUIg5AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAJgHIAJgFIALgEIAKgBQANAAAJAFQAJAFAGAKIAJgHIAKgHIALgEQAGgCAHAAQAJAAAIADQAIADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_16.setTransform(72.2,248.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_17.setTransform(52.9,248.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_18.setTransform(41.4,247);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag/BaIAAgUIARAAIAAiHIgRAAIAAgVIAmAAIAAAKQAIgGAJgDQAIgEAKAAQAMAAAKAFQAKAEAHAIQAHAIAEAMQAEALAAAOQAAAOgEANQgFALgHAIQgIAJgLAFQgLAEgNAAQgIAAgIgBIgNgFIAAAnIATAAIAAAUgAgLhCQgIADgFAGIAABBQADAEAIADQAHADAKAAQAHAAAHgCQAHgDAFgGQAGgGADgIQADgIAAgLQAAgLgDgIQgDgIgFgFQgFgGgHgCQgHgDgIAAQgHAAgIADg");
	this.shape_19.setTransform(29.4,251.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_20.setTransform(15,248.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgIgHQgHgHgMAAQgIAAgHADQgIAEgHAFIAABHIARAAIAAAUIg5AAIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAGAGACAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_21.setTransform(-5.3,248.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_22.setTransform(-20.1,248.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgRIAIAFIAKAFIALACIALABQAIAAAGgCQAHgCAEgEQAFgFACgIQACgIAAgMIAAgCQgGAGgIAEQgIADgKAAQgLAAgLgEQgLgEgHgJQgIgIgFgMQgEgLAAgPQAAgOAEgMQAEgLAIgIQAIgJALgFQALgEAMAAQAJAAAIACQAHADAHAFIAAgHIAWAAIAABzQAAAdgOAPQgOAPgcAAgAgJhCQgHADgFAFQgFAGgDAIQgDAIAAALQAAALACAIQADAIAFAGQAFAFAHAEQAHACAIAAIAKgBIAIgDIAGgEIAFgEIAAhCQgGgFgIgDQgIgCgIAAQgHAAgGADg");
	this.shape_23.setTransform(-39,251.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AALA+IAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgHAAgHADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJABALIAAA6IAQAAIAAAUg");
	this.shape_24.setTransform(-53.7,248.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_25.setTransform(-65.4,245.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AApBbIgwg2IgQAAIAAAiIAKAAIAAAUIg0AAIAAgUIAUAAIAAiNIgVAAIAAgUIArAAIAAAUIAABaIAVAAIAbgdIgHAAIAAgUIAuAAIAAAUIgPAAIglAlIAoArIAPAAIAAAUg");
	this.shape_26.setTransform(-76.6,245.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_27.setTransform(-91.7,248.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_28.setTransform(-106,248.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhBBZIAAgUIAQAAIAAiIIgQAAIAAgVIBOAAQALABAKAEQAJAEAHAGQAHAIAEAJQAEAJAAALQAAALgGAKQgGAJgMAGQAGACAEAEQAFAEADAFQAEAFACAFIABALQAAALgEAKQgEAKgHAGQgHAIgJAEQgKAEgLAAgAgaBFIApAAQAFAAAFgDIAJgHQADgFACgFQACgHAAgGQAAgFgCgEQgCgFgDgEIgJgGQgFgCgFAAIgpAAgAgagKIAoAAQAFAAAFgBQAFgDAEgEQADgEACgEQACgFAAgGQAAgFgCgFQgCgHgDgDQgEgFgFgDQgFgCgFAAIgoAAg");
	this.shape_29.setTransform(-120.6,246);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(-477,229.8,971.3,60), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAOIgFgDIgDgFIgBgGIABgFIADgFIAFgDIAFgBIAGABIAFADIADAFIABAFIgBAGIgDAFIgFADIgGABg");
	this.shape.setTransform(112.9,250.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgcBZQgLgFgIgIQgIgJgEgMQgEgMAAgPQAAgOAEgMQAEgKAIgIQAHgIALgFQALgEAOgBQAHAAAIACQAHADAHAEIAAguIgRAAIAAgUIAmAAIAAChIASAAIAAAUIgnAAIAAgKQgGAGgIAEQgIACgJAAQgMAAgKgDgAgSgLQgHADgFAFQgFAFgDAHQgDAJAAAKQAAALADAIQADAKAFAFQAFAGAHADQAHADAIgBQAJABAHgDQAGgDAGgGIAAhDQgGgFgIgCQgHgCgHAAQgIAAgHADg");
	this.shape_1.setTransform(102.9,242.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_2.setTransform(89.6,245.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_3.setTransform(77.3,245.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAMBbIAAgUIAQAAIAAg3QAAgOgHgGQgHgIgNAAQgHAAgHAEQgIADgHAFIAABHIASAAIAAAUIg6AAIAAgUIASAAIAAiNIgQAAIAAgUIAmAAIAABKIABAAIAHgGIAJgFIAKgDIAKgBQAJAAAIACQAIADAFAGQAGAFADAJQADAHAAAMIAAA6IASAAIAAAUg");
	this.shape_4.setTransform(63.2,242.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_5.setTransform(44.1,245.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_6.setTransform(34.6,242.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgRIAIAFIAKAFIALACIALABQAIAAAGgCQAHgCAEgEQAFgFACgIQACgIAAgMIAAgCQgGAGgIADQgIAEgKAAQgLAAgLgEQgLgEgHgJQgIgIgFgMQgEgLAAgPQAAgOAEgMQAEgMAIgHQAIgJALgFQALgEAMAAQAJAAAIACQAHACAHAGIAAgHIAWAAIAAB0QAAAdgOAPQgOAOgcAAgAgJhCQgHADgFAFQgFAGgDAIQgDAIAAALQAAAKACAJQADAIAFAFQAFAHAHACQAHADAIAAIAKgBIAIgDIAGgDIAFgFIAAhCQgGgFgIgDQgIgBgIAAQgHAAgGACg");
	this.shape_7.setTransform(18,248.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgIgHQgGgHgNAAQgIAAgHADQgIAEgGAFIAABHIAQAAIAAAUIg5AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_8.setTransform(3.4,245.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_9.setTransform(-8.3,242.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_10.setTransform(-16.7,243.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AALA+IAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgGAAgIADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAFAGADAIQAEAJAAALIAAA6IARAAIAAAUg");
	this.shape_11.setTransform(-29.2,245.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTA8QgLgEgHgJQgIgHgEgMQgFgNAAgPQABgNADgLQAEgMAHgIQAHgJALgFQAKgFANAAQAOAAAJAEQAJAEAHAHQAFAHADAJQADAIABAJIABAJIAAAIIhWAAIABAKIACAIQAEAMAJAGQAKAGAMAAQAJAAAJgDQAIgDALgFIAJAOQgNAJgMAEQgMAEgNAAQgLAAgKgEgAAfgOIgCgMQgCgFgDgFQgEgEgFgDQgGgCgIAAQgHAAgFACQgGACgEAFQgEADgDAHQgCAGgBAGIA+AAg");
	this.shape_12.setTransform(-44.4,245.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_13.setTransform(-56.7,245.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_14.setTransform(-69,245.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag+BZIAAgUIAQAAIAAiJIgQAAIAAgUIBGAAQAMAAAKADQAKADAIAGQAHAGAEAJQAEAJAAAMQAAAKgEAJQgEAIgHAHQgHAGgLADQgKADgMAAIgfAAIAAA/IASAAIAAAUgAgXgMIAfAAQAHAAAGgBQAFgCAEgEQAEgDADgGQACgFAAgHQAAgNgIgHQgIgIgSAAIgcAAg");
	this.shape_15.setTransform(-82.2,242.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(-92.3,226.6,209.9,33), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.beardyl();
	this.instance.parent = this;
	this.instance.setTransform(-538,229,0.752,0.752);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-538,229,376,334.6), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIheAAIACAKIACAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgEAFQgFAEgDAGQgCAHgBAIIBDAAg");
	this.shape.setTransform(253.7,245.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLBDIgrhvIgLAAIAAgWIAuAAIAAAWIgNAAIAgBaIAghaIgIAAIAAgWIAqAAIAAAWIgLAAIgsBvg");
	this.shape_1.setTransform(239.5,245.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIArAAIAABsIATAAIAAAWgAgFhAIgGgEIgDgFIgBgHIABgGIADgFIAGgEIAFgBIAGABIAGAEIADAFIABAGIgBAHIgDAFIgGAEIgGABg");
	this.shape_2.setTransform(228.7,242.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgvBCIAAgWIATAAIAAhWIgTAAIAAgWIArAAIAAASIAEgIIAGgGIAIgEQAEgBAFAAIAMAAIANAAIAAAdIgZAAIAAgJQgEAAgFACQgEACgEADQgEADgCAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape_3.setTransform(218.3,245.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgfBgQgLgFgJgJQgIgJgFgNQgFgNAAgRQAAgPAFgMQAFgMAIgJQAIgJAMgEQAMgFAOAAQAJAAAIACQAIACAHAFIAAgyIgSAAIAAgWIAqAAIAACuIATAAIAAAWIgrAAIAAgLQgGAHgJAEQgIADgKAAQgNAAgMgEgAgTgMQgIADgFAGQgGAFgDAIQgDAJAAALQAAAMADAJQADAKAFAGQAGAGAIADQAHAEAJAAQAKAAAHgDQAHgEAGgGIAAhIQgGgGgJgCQgIgDgIAAQgIAAgHAEg");
	this.shape_4.setTransform(204.3,242.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgoBgIAAgWIAQAAIAOgkIgshvIgLAAIAAgWIAyAAIAAAWIgQAAIAfBTIAghTIgQAAIAAgWIAyAAIAAAWIgOAAIg5CTIARAAIAAAWg");
	this.shape_5.setTransform(182.6,248.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AggBCQgIgDgHgFQgFgGgEgGQgCgIAAgHQgBgJADgGQADgHAEgFQADgEAGgDIALgEIANgEIAMAAIAPAAIALACIAAgLQAAgHgCgFQgCgFgEgDQgEgEgFgCQgFgBgFAAIgLABIgLACIgJADIgGADIgIgQIAKgFIAMgFIANgDIAMgBQAKAAAJADQAJACAHAGQAGAGAEAJQAEAJAAAMIgBBAIAOAAIAAAXIglAAIAAgNQgIAHgJAFQgIAEgLAAQgLAAgHgDgAgRAHQgGACgEADQgEACgCAFQgDAEAAAGQAAAFACAEQACAEADACQAEACAFACIAKABIAKgBIAIgDIAHgEIAHgGIAAgeIgbAAQgHABgFABg");
	this.shape_6.setTransform(168.3,245.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgfBgQgLgFgJgJQgIgJgFgNQgFgNAAgRQAAgPAFgMQAFgMAIgJQAIgJAMgEQAMgFAOAAQAJAAAIACQAIACAHAFIAAgyIgSAAIAAgWIAqAAIAACuIATAAIAAAWIgrAAIAAgLQgGAHgJAEQgIADgKAAQgNAAgMgEgAgTgMQgIADgFAGQgGAFgDAIQgDAJAAALQAAAMADAJQADAKAFAGQAGAGAIADQAHAEAJAAQAKAAAHgDQAHgEAGgGIAAhIQgGgGgJgCQgIgDgIAAQgIAAgHAEg");
	this.shape_7.setTransform(153.5,242.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIArAAIAABsIATAAIAAAWgAgFhAIgGgEIgDgFIgBgHIABgGIADgFIAGgEIAFgBIAGABIAGAEIADAFIABAGIgBAHIgDAFIgGAEIgGABg");
	this.shape_8.setTransform(141.4,242.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgeBjIAAgWIATAAIAAiZIgTAAIAAgWIAqAAIAACvIATAAIAAAWg");
	this.shape_9.setTransform(132.9,241.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_10.setTransform(120.8,245.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAMBjIAAgWIASAAIAAg8QAAgPgHgHQgIgIgOAAQgHAAgJAEQgIAEgIAFIAABNIATAAIAAAWIg+AAIAAgWIAUAAIAAiZIgSAAIAAgWIApAAIAABRIABAAIAIgHIAKgFIALgEIAKgBQALAAAIADQAJADAGAGQAGAGADAJQADAIAAANIAAA/IAUAAIAAAWg");
	this.shape_11.setTransform(104.7,241.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgJgJQgIgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAGAIADAJQADAKABAKIABAJIAAAJIhdAAIABAKIABAJQAFANALAGQAKAHAMAAQALAAAJgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgNAAgLgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgFAFQgEAEgDAGQgCAHgBAIIBDAAg");
	this.shape_12.setTransform(82.5,245.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAMBjIAAgWIASAAIAAg8QABgPgIgHQgIgIgOAAQgHAAgJAEQgIAEgIAFIAABNIAUAAIAAAWIg/AAIAAgWIAUAAIAAiZIgSAAIAAgWIApAAIAABRIACAAIAHgHIALgFIAKgEIAKgBQALAAAIADQAJADAGAGQAGAGADAJQADAIAAANIAAA/IAUAAIAAAWg");
	this.shape_13.setTransform(67,241.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBXQgHgDgDgFQgFgFgDgHQgBgJgBgNIABhHIgVAAIAAgTIAVAAIAAgfIAXgMIAAArIAeAAIAAATIgfAAIAABLQAAAIACAEQABAFAEADQAEABAFAAIAJgBIAJgDIAGAQIgNAFQgHACgJgBQgIAAgGgBg");
	this.shape_14.setTransform(53.5,243.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QABgPgJgHQgHgJgOABQgIAAgIADQgJAFgHAFIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQALAAAIADQAJADAFAGQAHAGADAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_15.setTransform(34.3,245.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_16.setTransform(17.8,245.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAKAhIgBhBIAdAAIgGBBgAgfAhIgGhBIAdAAIgCBBg");
	this.shape_17.setTransform(243.8,206.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBBWQgGgCgFgEQgEgGgCgIQgCgIgBgMIABhIIgVAAIAAgTIAVAAIAAggIAWgKIAAAqIAfAAIAAATIgfAAIgBBLQAAAIACAFQACAEAEACQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHACgJAAQgIgBgGgCg");
	this.shape_18.setTransform(234.8,214.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgJgJQgHgJgFgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAFAIAEAJQADAKABAKIABAJIAAAJIhdAAIABAKIABAJQAGANAKAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgMAAgMgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgFAFQgDAEgEAGQgCAHgBAIIBDAAg");
	this.shape_19.setTransform(222.1,216.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgoBgIAAgWIAQAAIAOgkIgshvIgLAAIAAgWIAyAAIAAAWIgQAAIAfBTIAghTIgQAAIAAgWIAyAAIAAAWIgOAAIg5CTIARAAIAAAWg");
	this.shape_20.setTransform(207.1,219.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgJgJQgHgJgFgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAFAIAEAJQADAKABAKIABAJIAAAJIhdAAIAAAKIACAJQAGANAKAGQAKAHAMAAQALAAAJgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgMAAgMgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgFAFQgDAEgEAGQgCAHgBAIIBDAAg");
	this.shape_21.setTransform(186.6,216.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AguBCIAAgWIASAAIAAhWIgSAAIAAgWIAqAAIAAASIAEgIIAHgGIAHgEQAEgBAFAAIAMAAIAMAAIAAAdIgYAAIAAgJQgEAAgEACQgFACgDADQgEADgDAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape_22.setTransform(173.4,216.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_23.setTransform(159.6,216.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAMBjIAAgWIASAAIAAg8QAAgPgHgHQgIgIgOAAQgIAAgHAEQgJAEgIAFIAABNIATAAIAAAWIg+AAIAAgWIAUAAIAAiZIgSAAIAAgWIApAAIAABRIABAAIAIgHIAKgFIALgEIAKgBQALAAAJADQAIADAGAGQAGAGADAJQADAIAAANIAAA/IAUAAIAAAWg");
	this.shape_24.setTransform(144.1,213.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgBBWQgGgCgEgEQgFgGgCgIQgCgIAAgMIAAhIIgVAAIAAgTIAVAAIAAggIAWgKIAAAqIAfAAIAAATIgfAAIgBBLQAAAIACAFQACAEAEACQAEACAFAAIAJgBIAJgDIAGAQIgNAFQgHACgJAAQgJgBgFgCg");
	this.shape_25.setTransform(130.6,214.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAGAIAEAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQALAAAJgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_26.setTransform(112.2,216.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAeBDIgehoIgdBoIgWAAIgjhvIgMAAIAAgWIApAAIAAAWIgGAAIAXBTIAghpIATAAIAeBpIAYhTIgHAAIAAgWIApAAIAAAWIgMAAIgkBvg");
	this.shape_27.setTransform(94.5,216.9);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgJgJQgHgJgFgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAFAIAEAJQADAKABAKIABAJIAAAJIhdAAIABAKIABAJQAGANAKAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgMAAgMgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgFAFQgDAEgEAGQgCAHgBAIIBDAAg");
	this.shape_28.setTransform(70.9,216.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AguBCIAAgWIASAAIAAhWIgSAAIAAgWIApAAIAAASIAFgIIAHgGIAHgEQAEgBAFAAIANAAIALAAIAAAdIgYAAIAAgJQgEAAgEACQgFACgDADQgFADgCAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape_29.setTransform(57.7,216.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAiBgIAAgWIAQAAIgPgrIhJAAIgPArIATAAIAAAWIg+AAIAAgWIARAAIA8ipIAkAAIA8CpIAUAAIAAAWgAAbAKIgchVIgeBVIA6AAg");
	this.shape_30.setTransform(41.9,213.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AAKAhIgBhBIAdAAIgGBBgAgfAhIgGhBIAdAAIgCBBg");
	this.shape_31.setTransform(28.1,206.7);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgOBfIgPgDIgNgGQgIgDgGgFIAOgTIAIAGIALAFIALADIAMABQAIAAAIgCQAHgCAFgFQAFgFABgJQADgJAAgNIAAgCQgHAHgIADQgIAEgLAAQgNAAgMgEQgLgFgIgJQgJgJgFgNQgEgMAAgRQAAgPAEgMQAFgNAIgJQAIgJAMgEQAMgFANAAQAKAAAIACQAJACAHAFIAAgGIAXAAIAAB9QAAAfgOAQQgPAQgfAAgAgKhHQgIADgFAGQgGAGgCAIQgEAJAAALQAAAMADAJQAEAJAFAGQAFAGAIADQAIAEAHAAIALgCIAJgCIAHgFIAFgFIAAhHQgHgGgIgCQgIgDgKAAQgGAAgIAEg");
	this.shape_32.setTransform(180.6,191.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QABgPgJgHQgHgIgOAAQgIAAgIADQgIAEgIAGIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhWIgSAAIAAgWIAqAAIAAAPIABAAIAIgHIAKgFIALgFIALgBQALAAAIADQAJADAFAGQAHAGADAJQADAJAAANIAAA+IASAAIAAAWg");
	this.shape_33.setTransform(164.7,188.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIATAAIAAhWIgUAAIAAgWIAqAAIAABsIAUAAIAAAWgAgGhAIgFgEIgEgFIgBgHIABgGIAEgFIAFgEIAGgBIAHABIAEAEIAEAFIACAGIgCAHIgEAFIgEAEIgHABg");
	this.shape_34.setTransform(152.1,185.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AguBCIAAgWIASAAIAAhWIgSAAIAAgWIApAAIAAASIAFgIIAHgGIAHgEQAEgBAFAAIANAAIALAAIAAAdIgYAAIAAgJQgEAAgFACQgEACgDADQgEADgDAFQgCAFgCAHIAAA+IAWAAIAAAWg");
	this.shape_35.setTransform(141.6,188.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AggBCQgIgDgHgFQgFgFgEgIQgCgHAAgHQgBgJADgGQADgHAEgEQADgFAGgDIALgFIANgDIAMAAIAPAAIALACIAAgLQAAgHgCgFQgCgFgEgDQgEgEgFgCQgFgBgFAAIgLABIgLACIgJADIgGADIgIgQIAKgFIAMgFIANgDIAMgBQAKAAAJADQAJADAHAFQAGAGAEAJQAEAJAAAMIgBBAIAOAAIAAAXIglAAIAAgNQgIAHgJAFQgIAEgLAAQgLAAgHgDgAgRAHQgGABgEAEQgEADgCADQgDAFAAAGQAAAFACAEQACAEADACQAEACAFACIAKACIAKgCIAIgDIAHgEIAHgGIAAgdIgbAAQgHAAgFABg");
	this.shape_36.setTransform(128.3,188.5);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAGAIAEAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQALAAAJgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_37.setTransform(113.6,188.4);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAkBgIAAgWIAUAAIAAhFIhvAAIAABFIATAAIAAAWIg+AAIAAgWIASAAIAAiTIgSAAIAAgWIA+AAIAAAWIgTAAIAAA6IBvAAIAAg6IgUAAIAAgWIA/AAIAAAWIgTAAIAACTIATAAIAAAWg");
	this.shape_38.setTransform(94.9,185.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(8.1,168,255.6,92.2), null);


(lib.shaker = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgoBgIAAgWIAQAAIAOgkIgshvIgLAAIAAgWIAyAAIAAAWIgQAAIAfBTIAghTIgQAAIAAgWIAyAAIAAAWIgOAAIg5CTIARAAIAAAWg");
	this.shape.setTransform(128.3,-0.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggBCQgJgDgGgFQgFgGgEgGQgDgIAAgIQABgHACgHQADgGAEgGQADgEAGgCIALgGIANgCIAMgBIAPABIAKABIABgLQAAgHgCgFQgCgFgEgEQgEgDgFgBQgFgCgFAAIgLABIgLACIgIADIgHAEIgIgRIAKgGIAMgEIANgDIAMgBQALAAAIADQAJADAHAFQAHAGADAJQAEAIAAANIgBBBIAOAAIAAAVIgmAAIAAgLQgHAGgJAEQgIAFgLAAQgLAAgHgDgAgRAHQgGABgEADQgEADgCAEQgDAFAAAFQAAAGACADQACAEADADQAEADAFABIAKABIAKgBIAIgDIAHgFIAGgFIAAgdIgaAAQgGAAgGABg");
	this.shape_1.setTransform(114,-3.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAeBDIgehoIgdBoIgWAAIgkhvIgLAAIAAgWIAqAAIAAAWIgHAAIAYBTIAfhpIATAAIAeBpIAYhTIgHAAIAAgWIApAAIAAAWIgLAAIgkBvg");
	this.shape_2.setTransform(96.5,-3.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAGAIAEAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQALAAAJgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_3.setTransform(78.5,-3.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLBDIgrhvIgLAAIAAgWIAuAAIAAAWIgMAAIAfBaIAghaIgIAAIAAgWIAqAAIAAAWIgMAAIgrBvg");
	this.shape_4.setTransform(64.3,-3.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgFhAIgGgEIgDgFIgBgHIABgGIADgFIAGgEIAFgBIAGABIAGAEIADAFIABAGIgBAHIgDAFIgGAEIgGABg");
	this.shape_5.setTransform(53.5,-6.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgvBCIAAgWIATAAIAAhWIgTAAIAAgWIArAAIAAASIAEgIIAGgGIAIgEQAEgBAFAAIAMAAIANAAIAAAdIgZAAIAAgJQgEAAgEACQgFACgEADQgDADgDAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape_6.setTransform(43,-3.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgfBgQgLgFgJgJQgIgJgFgNQgFgNAAgRQAAgPAFgMQAFgMAIgJQAIgJAMgEQAMgFAOAAQAJAAAIACQAIACAHAFIAAgyIgSAAIAAgWIAqAAIAACuIATAAIAAAWIgrAAIAAgLQgGAHgJAEQgIADgKAAQgNAAgMgEgAgTgMQgIADgFAGQgGAFgDAIQgDAJAAALQAAAMADAJQADAKAFAGQAGAGAIADQAHAEAJAAQAKAAAHgDQAHgEAGgGIAAhIQgGgGgJgCQgIgDgIAAQgIAAgHAEg");
	this.shape_7.setTransform(29.1,-6.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgJgJQgHgJgFgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAFAIAEAJQADAKABAKIABAJIAAAJIheAAIABAKIACAJQAGANAKAGQAKAHAMAAQALAAAJgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgNAAgKgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgFAFQgDAEgDAGQgDAHgBAIIBDAAg");
	this.shape_8.setTransform(126.9,-28.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AANBjIAAgWIASAAIAAg8QAAgPgIgHQgIgIgOAAQgIAAgHAEQgJAEgHAFIAABNIATAAIAAAWIg/AAIAAgWIAUAAIAAiZIgSAAIAAgWIAqAAIAABRIABAAIAIgHIAKgFIAKgEIAKgBQALAAAIADQAJADAGAGQAFAGAEAJQADAIAAANIAAA/IAUAAIAAAWg");
	this.shape_9.setTransform(111.4,-31.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgFgGQgEgFgCgHQgDgJAAgMIABhIIgVAAIAAgTIAVAAIAAgfIAWgLIAAAqIAfAAIAAATIgfAAIAABLQAAAIABAEQACAGAEABQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_10.setTransform(97.9,-30.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgJgJQgHgJgFgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAFAIAEAJQADAKABAKIABAJIAAAJIhdAAIAAAKIACAJQAGANAKAGQAKAHAMAAQALAAAJgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgMAAgMgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgFAFQgDAEgEAGQgCAHgBAIIBDAAg");
	this.shape_11.setTransform(79.5,-28.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgLBDIgrhvIgKAAIAAgWIAtAAIAAAWIgNAAIAgBaIAghaIgIAAIAAgWIApAAIAAAWIgLAAIgrBvg");
	this.shape_12.setTransform(65.3,-28.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AghBCQgHgDgGgFQgGgGgDgGQgEgIAAgIQABgHACgHQACgGAEgGQAFgEAFgDIAMgEIAMgEIAMAAIAPAAIAKACIABgLQAAgHgDgFQgCgFgDgEQgDgDgGgBQgFgCgGAAIgKABIgLACIgIADIgIADIgHgQIAKgGIAMgEIAMgDIANgBQALAAAJADQAIACAHAGQAGAGAEAJQADAJABAMIgBBBIAOAAIAAAVIgmAAIAAgLQgHAHgJAEQgIAEgMAAQgKAAgIgDgAgRAHQgGACgEACQgEADgCAFQgDAEAAAGQAAAFACAEQACADAEADQADACAFACIALABIAJgBIAIgDIAIgFIAFgFIAAgeIgaAAQgGAAgGACg");
	this.shape_13.setTransform(51.2,-28.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIhdAAIABAKIACAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgNAAgLgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgEAFQgEAEgEAGQgCAHgBAIIBDAAg");
	this.shape_14.setTransform(36.5,-28.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgeBjIAAgWIATAAIAAiZIgTAAIAAgWIAqAAIAACvIATAAIAAAWg");
	this.shape_15.setTransform(25.2,-31.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgaBAQgIgDgGgGQgGgGgDgKQgDgJAAgMIAAg+IgSAAIAAgWIArAAIAABRQAAAPAHAIQAHAHANABQAHAAAIgEQAJgCAHgFIAAhPIgRAAIAAgWIAqAAIAABsIAPAAIAAAXIgnAAIAAgNQgJAHgKAEQgLAEgKAAQgKAAgIgDg");
	this.shape_16.setTransform(149,-53.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_17.setTransform(133.3,-54);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgoBgIAAgWIAQAAIAOgkIgshvIgLAAIAAgWIAyAAIAAAWIgQAAIAfBTIAghTIgQAAIAAgWIAyAAIAAAWIgOAAIg5CTIARAAIAAAWg");
	this.shape_18.setTransform(117.7,-51);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIhdAAIABAKIACAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgNAAgLgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgEAFQgEAEgEAGQgCAHgBAIIBDAAg");
	this.shape_19.setTransform(97.2,-54);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AguBCIAAgWIASAAIAAhWIgSAAIAAgWIApAAIAAASIAFgIIAHgGIAHgEQAEgBAFAAIANAAIALAAIAAAdIgYAAIAAgJQgEAAgFACQgEACgDADQgEADgDAFQgCAFgCAHIAAA+IAWAAIAAAWg");
	this.shape_20.setTransform(84,-54.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_21.setTransform(70.1,-54);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgvBjIAAgWIAUAAIAAhaIgWAAIAAgTIAWAAIAAgUQABgMADgIQADgJAFgFQAGgGAHgDQAIgDAJAAIAMABIAKACIAHACIAFACIgHARIgKgDQgGgCgIAAQgLAAgFAHQgGAGAAANIAAAVIAeAAIAAATIgeAAIAABaIAUAAIAAAWg");
	this.shape_22.setTransform(59.1,-57.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAGAIAEAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_23.setTransform(45.2,-54);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AhHBgIAAgWIASAAIAAiTIgSAAIAAgWIBWAAQAMAAAJAEQALAFAHAHQAIAIAFAKQAEAKAAAMQAAAMgHALQgHAKgNAGIAMAGQAFAFADAFQAEAFACAGQACAGAAAGQAAAMgEAKQgFALgIAIQgHAHgKAFQgLAEgLAAgAgcBKIAsAAQAGAAAFgDQAGgDADgFQAEgEADgHQACgGAAgGQAAgGgCgFQgCgFgFgEQgDgEgGgDQgFgCgGAAIgsAAgAgcgKIArAAQAGAAAFgDQAGgCADgEQAFgEACgGQACgFAAgGQAAgGgCgGQgCgGgFgFQgDgEgGgDQgFgDgGAAIgrAAg");
	this.shape_24.setTransform(30,-57.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.shaker, new cjs.Rectangle(19,-74.4,141.5,86.2), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AghA5QgHgDgEgEIgFgGIgEgJIgBgNQAAgGACgKIAKgtIgPAAIAEgTIAmAAIgNA6QgFAVAEAJQAFAKAOAAQAHAAAEgCQAFgCAEgEIAHgJIAOg+IgPAAIAFgTIAlAAIgWBgIARAAIgEATIgnAAIADgMIgIAGIgHAFIgJACIgIABQgHAAgHgCg");
	this.shape.setTransform(111.7,71.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgbA5QgKgEgHgIQgHgGgEgLQgEgJAAgLQAAgIACgJQACgKAFgHQAEgIAGgGQAHgGAHgFQAIgEAIgCQAJgDAIAAQALAAAKAEQAKAEAHAHQAHAHAEAKQAEAJAAALQAAAJgCAJQgCAJgFAHQgEAIgGAHQgHAGgHAFQgIAEgIADQgJACgIAAQgMAAgJgEgAgJglQgIAEgGAGQgGAGgDAJQgEAJAAAKQAAAHACAGQADAHAEAFQAEAEAGACQAFADAHAAQAHAAAIgEQAIgDAGgHQAGgGAEgJQADgJAAgKQAAgHgCgGQgDgHgEgEQgEgEgGgDQgGgCgGAAQgIAAgHADg");
	this.shape_1.setTransform(97.5,71.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhDBUIAEgTIAMAAIAVghIgNhgIgLAAIAFgTIAqAAIgEATIgJAAIAHBGIAshGIgJAAIAEgTIAqAAIgFATIgJAAIhSCBIALAAIgEATg");
	this.shape_2.setTransform(84.4,74.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgwA6IAWhfIgWAAIAFgTIArAAIgDAPIAFgGIAIgGIAIgDIAJgBIAHAAIAGAAIAJABIgHAgIgXAAIADgOQgLAAgHAFQgHAGgFAJIgNA5IATAAIgEATg");
	this.shape_3.setTransform(67.3,71.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AghA5QgIgEgGgGQgGgHgEgIQgEgJAAgKQAAgPAGgOQAGgNAKgKQAJgKANgFQANgFAOAAQAIAAAIACQAHADAFAEIABgGIAXAAIgXBfIASAAIgEATIgoAAIABgIQgHAFgHADQgHACgIAAQgKAAgIgDgAgIglQgIAEgHAGQgGAHgEAKQgEAJAAAMQAAAHACAGQACAFADAEQAEAEAFACQAFACAGAAIAIgBIAIgDIAHgDIAGgEIAOg9QgCgEgHgDQgGgCgKAAQgIAAgIADg");
	this.shape_4.setTransform(53.4,71.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZA6QgJgEgHgHQgHgHgEgJQgEgKAAgNQAAgNAFgNQAFgNAJgJQAJgJANgGQAMgFANAAQALAAAJADQAIAEAGAGQAHAGADAIQADAIAAAJIgBALIgBAJIhYAAIAAACIgBADQAAAHADAGQACAGAEAEQAEAFAGACQAFADAHAAQAIAAAIgEQAIgEAGgHIAQAMIgJAJQgFAFgGACQgHADgHACIgOABQgKAAgKgDgAAjgNQAAgHgCgFQgCgGgDgDQgEgEgFgCQgGgBgGAAQgHAAgEACQgGACgFAEQgFADgEAGIgGALIBBAAIAAAAg");
	this.shape_5.setTransform(39.9,71.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAQA7IARhGQADgNgFgIQgFgGgMAAQgJAAgHADQgIAEgHAHIgTBTIgXAAIAXhfIgWAAIAEgTIAsAAIgDALQAIgGAJgEQAIgEALAAQAJAAAIADQAGADAFAFQAFAGABAHQABAJgCAKIgNA3IARAAIgFATg");
	this.shape_6.setTransform(25.4,71.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgZA6QgJgEgHgHQgHgHgEgJQgEgKAAgNQAAgNAFgNQAFgNAJgJQAJgJANgGQAMgFANAAQALAAAJADQAIAEAGAGQAHAGADAIQADAIAAAJIgBALIgBAJIhYAAIAAACIgBADQAAAHADAGQACAGAEAEQAEAFAGACQAFADAHAAQAIAAAIgEQAIgEAGgHIAQAMIgJAJQgFAFgGACQgHADgHACIgOABQgKAAgKgDgAAjgNQAAgHgCgFQgCgGgDgDQgEgEgFgCQgGgBgGAAQgHAAgEACQgGACgFAEQgFADgEAGIgGALIBBAAIAAAAg");
	this.shape_7.setTransform(6.4,71.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAQA7IARhGQADgNgFgIQgFgGgMAAQgJAAgHADQgIAEgHAHIgTBTIgXAAIAWhfIgVAAIAEgTIArAAIgCALQAIgGAJgEQAIgEALAAQAJAAAIADQAGADAFAFQAEAGACAHQABAJgCAKIgNA3IARAAIgEATg");
	this.shape_8.setTransform(-8.2,71.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgbA5QgKgEgHgIQgHgGgEgLQgEgJAAgLQAAgIACgJQACgKAFgHQAEgIAGgGQAHgGAHgFQAIgEAIgCQAJgDAIAAQALAAAKAEQAKAEAHAHQAHAHAEAKQAEAJAAALQAAAJgCAJQgCAJgFAHQgEAIgGAHQgHAGgHAFQgIAEgIADQgJACgIAAQgMAAgJgEgAgJglQgIAEgGAGQgGAGgDAJQgEAJAAAKQAAAHACAGQADAHAEAFQAEAEAGACQAFADAHAAQAHAAAIgEQAIgDAGgHQAGgGAEgJQADgJAAgKQAAgHgCgGQgDgHgEgEQgEgEgGgDQgGgCgGAAQgIAAgHADg");
	this.shape_9.setTransform(-22.7,71.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgnBUQgIgEgHgGQgGgHgEgJQgDgJAAgLQAAgPAFgNQAGgMAJgKQAJgKANgFQANgFANAAQAJAAAHACQAIADAGAEIAKgtIgTAAIAEgTIAqAAIgkCaIAUAAIgFATIgpAAIABgIQgGAFgGACQgHADgIAAQgKAAgJgEgAgQgJQgIADgGAGQgHAGgDAKQgEAJAAALQAAAIACAGQACAGAEAEQAEAEAFACQAGADAGAAQAHAAAIgEQAGgDAGgGIAOg7QgEgEgGgDQgHgDgJAAQgIAAgIAEg");
	this.shape_10.setTransform(-41.5,68.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAQA7IARhGQADgNgFgIQgFgGgMAAQgJAAgHADQgIAEgHAHIgTBTIgXAAIAWhfIgVAAIAEgTIArAAIgCALQAIgGAJgEQAIgEALAAQAJAAAIADQAGADAFAFQAEAGACAHQABAJgCAKIgNA3IARAAIgEATg");
	this.shape_11.setTransform(-56.8,71.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgbBVIAWhfIgVAAIAFgTIAqAAIgVBfIARAAIgEATgAAIg4IgFgDIgDgFIAAgGIAAgGIADgEIAFgEIAGgBIAFABIAGAEIACAEIABAGIgBAGIgCAFIgGADIgFABg");
	this.shape_12.setTransform(-68,69);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag7ByIAiiUIgYAAIAFgTIAXAAIAFgUQACgLAFgIQAEgHAFgFQAGgFAIgCQAIgCAIAAIAKAAIAJACIAGACIAFACIgLASIgIgEIgLgBQgJAAgHAFQgGAFgDAMIgEATIAfAAIgEATIgfAAIgiCUg");
	this.shape_13.setTransform(-75,71.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(1,1,1).p("A2PjWMAsfAAAIAAGtMgsfAAAg");
	this.shape_14.setTransform(15.4,69.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(-127.9,47.3,286.8,45), null);


(lib.doclogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Tween2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(277,101.3,0.63,0.63,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.doclogo, new cjs.Rectangle(187.5,82.3,354.7,68), null);


(lib.bywhen = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shaker();
	this.instance.parent = this;
	this.instance.setTransform(86.3,22.4,1.112,1.112,0,0,0,86.3,22.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bywhen, new cjs.Rectangle(11.4,-85.3,157.4,95.9), null);


// stage content:
(lib._300x600_drive = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 8
	this.instance = new lib.cta();
	this.instance.parent = this;
	this.instance.setTransform(536.1,270.9,0.95,0.95,0,0,0,105.5,22.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(311).to({_off:false},0).wait(1).to({regX:15.4,regY:69.8,x:449,y:316.2},0).wait(1).to({x:443.3},0).wait(1).to({x:430.5},0).wait(1).to({x:404.1},0).wait(1).to({x:356.6},0).wait(1).to({x:305.8},0).wait(1).to({x:269.2},0).wait(1).to({x:243.2},0).wait(1).to({x:223.7},0).wait(1).to({x:208.6},0).wait(1).to({x:196.6},0).wait(1).to({x:186.8},0).wait(1).to({x:178.8},0).wait(1).to({x:172.2},0).wait(1).to({x:166.9},0).wait(1).to({x:162.5},0).wait(1).to({x:159},0).wait(1).to({x:156.2},0).wait(1).to({x:154},0).wait(1).to({x:152.4},0).wait(1).to({x:151.4},0).wait(1).to({x:150.7},0).wait(1).to({regX:105.5,regY:22.1,x:236.1,y:270.9},0).wait(27));

	// Layer 6
	this.instance_1 = new lib.doclogo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-339.8,195.2,0.8,0.8,0,0,0,143.1,30.2);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(311).to({_off:false},0).wait(1).to({regX:364.9,regY:116.3,x:-160.8,y:264.1},0).wait(1).to({x:-154.8},0).wait(1).to({x:-141.5},0).wait(1).to({x:-114.1},0).wait(1).to({x:-64.7},0).wait(1).to({x:-11.8},0).wait(1).to({x:26.3},0).wait(1).to({x:53.3},0).wait(1).to({x:73.5},0).wait(1).to({x:89.3},0).wait(1).to({x:101.8},0).wait(1).to({x:112},0).wait(1).to({x:120.3},0).wait(1).to({x:127.1},0).wait(1).to({x:132.7},0).wait(1).to({x:137.2},0).wait(1).to({x:140.9},0).wait(1).to({x:143.8},0).wait(1).to({x:146.1},0).wait(1).to({x:147.7},0).wait(1).to({x:148.8},0).wait(1).to({x:149.4},0).wait(1).to({regX:143.1,regY:30.2,x:-27.8,y:195.2},0).wait(27));

	// Layer 5
	this.instance_2 = new lib.Symbol3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(364,68,1,1,0,0,0,221.8,32.4);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(182).to({_off:false},0).wait(37).to({y:67},0).wait(1).to({regX:12.9,regY:245.1,x:155.1,y:279.4},0).wait(1).to({y:278.2},0).wait(1).to({y:274.9},0).wait(1).to({y:269.4},0).wait(1).to({y:265.7},0).wait(1).to({y:263.6},0).wait(1).to({y:262.3},0).wait(1).to({y:261.5},0).wait(1).to({y:261},0).wait(1).to({y:260.8},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:48},0).wait(75).to({regX:12.9,regY:245.1,x:155.1,y:261.5},0).wait(1).to({y:264.1},0).wait(1).to({y:269.1},0).wait(1).to({y:277.3},0).wait(1).to({y:290},0).wait(1).to({y:309.6},0).wait(1).to({y:340.9},0).wait(1).to({y:393.1},0).wait(1).to({y:466.4},0).wait(1).to({y:523.9},0).wait(1).to({y:559.2},0).wait(1).to({y:581.7},0).wait(1).to({y:596.7},0).wait(1).to({y:606.8},0).wait(1).to({y:613.6},0).wait(1).to({y:617.8},0).wait(1).to({y:620},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:408},0).to({_off:true},1).wait(38));

	// Layer 4
	this.instance_3 = new lib.bywhen();
	this.instance_3.parent = this;
	this.instance_3.setTransform(808.2,72.7,4.84,4.84,6,0,0,86.5,22.7);
	this.instance_3._off = true;

	this.instance_4 = new lib.Symbol5();
	this.instance_4.parent = this;
	this.instance_4.setTransform(364,60.8,1,1,0,0,0,221.8,17.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(93).to({_off:false},0).wait(1).to({regX:89.4,regY:-34.7,scaleX:4.76,scaleY:4.76,rotation:5.7,x:834.1,y:-195.7},0).wait(1).to({scaleX:4.52,scaleY:4.52,rotation:4.9,x:784.7,y:-176.9},0).wait(1).to({scaleX:4.15,scaleY:4.15,rotation:3.7,x:707.4,y:-147.2},0).wait(1).to({scaleX:3.67,scaleY:3.67,rotation:2,x:609.6,y:-108.6},0).wait(1).to({scaleX:3.12,scaleY:3.12,rotation:0.2,x:500.6,y:-64.6},0).wait(1).to({scaleX:2.56,scaleY:2.56,rotation:-1.7,x:391.5,y:-19.3},0).wait(1).to({scaleX:2.05,scaleY:2.05,rotation:-3.4,x:293.1,y:22.4},0).wait(1).to({scaleX:1.64,scaleY:1.64,rotation:-4.8,x:214.9,y:56.2},0).wait(1).to({scaleX:1.37,scaleY:1.37,rotation:-5.7,x:164.6,y:78.2},0).wait(1).to({regX:86.3,regY:22.7,scaleX:1.28,scaleY:1.28,rotation:-6,x:151,y:159.3},0).to({_off:true},79).wait(179));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(219).to({_off:false},0).to({alpha:1},16).wait(70).to({regX:9.2,regY:259.4,x:151.4,y:303.2},0).wait(1).to({y:305.8},0).wait(1).to({y:310.7},0).wait(1).to({y:318.7},0).wait(1).to({y:331.1},0).wait(1).to({y:350.3},0).wait(1).to({y:380.9},0).wait(1).to({y:431.9},0).wait(1).to({y:503.5},0).wait(1).to({y:559.8},0).wait(1).to({y:594.3},0).wait(1).to({y:616.3},0).wait(1).to({y:631},0).wait(1).to({y:640.9},0).wait(1).to({y:647.5},0).wait(1).to({y:651.6},0).wait(1).to({y:653.8},0).wait(1).to({regX:221.8,regY:17.7,x:364,y:412.8},0).to({_off:true},1).wait(38));

	// Layer 2
	this.instance_5 = new lib.Symbol1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-200.6,49.8,1,1,0,0,0,136.3,32.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({regX:135.4,regY:216.7,x:-188.1,y:234.1},0).wait(1).to({x:-171.1},0).wait(1).to({x:-149.1},0).wait(1).to({x:-119.3},0).wait(1).to({x:-79},0).wait(1).to({x:-32.9},0).wait(1).to({x:6},0).wait(1).to({x:34.5},0).wait(1).to({x:55.8},0).wait(1).to({x:72.2},0).wait(1).to({x:85.2},0).wait(1).to({x:95.9},0).wait(1).to({x:104.8},0).wait(1).to({x:112.2},0).wait(1).to({x:118.5},0).wait(1).to({x:123.9},0).wait(1).to({x:128.4},0).wait(1).to({x:132.3},0).wait(1).to({x:135.6},0).wait(1).to({x:138.4},0).wait(1).to({x:140.8},0).wait(1).to({x:142.8},0).wait(1).to({x:144.4},0).wait(1).to({x:145.7},0).wait(1).to({x:146.8},0).wait(1).to({x:147.5},0).wait(1).to({x:148.1},0).wait(1).to({x:148.4},0).wait(1).to({regX:136.3,regY:32.4,x:149.4,y:49.8},0).wait(63).to({regX:135.4,regY:216.7,scaleX:1.01,scaleY:1.01,x:146.3,y:234.4},0).wait(1).to({scaleX:1.03,scaleY:1.03,x:139,y:235.4},0).wait(1).to({scaleX:1.08,scaleY:1.08,x:125,y:237.6},0).wait(1).to({scaleX:1.16,scaleY:1.16,x:101.7,y:241.1},0).wait(1).to({scaleX:1.29,scaleY:1.29,x:65.3,y:246.5},0).wait(1).to({scaleX:1.48,scaleY:1.48,x:10.5,y:254.8},0).wait(1).to({scaleX:1.74,scaleY:1.74,x:-67.1,y:266.4},0).wait(1).to({scaleX:2.06,scaleY:2.06,x:-159.5,y:280.2},0).wait(1).to({scaleX:2.35,scaleY:2.35,x:-243.9,y:292.8},0).wait(1).to({scaleX:2.58,scaleY:2.58,x:-308.5,y:302.5},0).wait(1).to({scaleX:2.74,scaleY:2.74,x:-355.5,y:309.5},0).wait(1).to({scaleX:2.86,scaleY:2.86,x:-389.5,y:314.6},0).wait(1).to({scaleX:2.94,scaleY:2.94,x:-414,y:318.2},0).wait(1).to({scaleX:3,scaleY:3,x:-431.5,y:320.8},0).wait(1).to({scaleX:3.04,scaleY:3.04,x:-443.5,y:322.7},0).wait(1).to({scaleX:3.07,scaleY:3.07,x:-451.2,y:323.8},0).wait(1).to({scaleX:3.08,scaleY:3.08,x:-455.4,y:324.4},0).wait(1).to({regX:136.2,regY:32.4,scaleX:3.09,scaleY:3.09,x:-454.1,y:-244.2},0).to({_off:true},163).wait(89));

	// Layer 3
	this.instance_6 = new lib.Symbol2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(539.9,459,0.835,0.835,0,0,0,112.2,112.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({regX:-350,regY:396.3,x:154,y:686.9},0).wait(1).to({y:675.9},0).wait(1).to({y:661.5},0).wait(1).to({y:642.1},0).wait(1).to({y:615.9},0).wait(1).to({y:585.8},0).wait(1).to({y:560.5},0).wait(1).to({y:541.9},0).wait(1).to({y:528.1},0).wait(1).to({y:517.4},0).wait(1).to({y:508.9},0).wait(1).to({y:501.9},0).wait(1).to({y:496.1},0).wait(1).to({y:491.3},0).wait(1).to({y:487.2},0).wait(1).to({y:483.7},0).wait(1).to({y:480.7},0).wait(1).to({y:478.2},0).wait(1).to({y:476},0).wait(1).to({y:474.2},0).wait(1).to({y:472.6},0).wait(1).to({y:471.3},0).wait(1).to({y:470.3},0).wait(1).to({y:469.4},0).wait(1).to({y:468.7},0).wait(1).to({y:468.2},0).wait(1).to({y:467.9},0).wait(1).to({y:467.7},0).wait(1).to({regX:112.2,regY:112.8,x:539.9,y:231},0).wait(63).to({regX:-350,regY:396.3,scaleX:0.84,scaleY:0.84,x:154,y:467.3},0).wait(1).to({scaleX:0.84,scaleY:0.84,x:153.8,y:466.2},0).wait(1).to({scaleX:0.86,scaleY:0.86,x:153.5,y:464.1},0).wait(1).to({scaleX:0.88,scaleY:0.88,x:153,y:460.7},0).wait(1).to({scaleX:0.91,scaleY:0.91,x:152.2,y:455.3},0).wait(1).to({scaleX:0.96,scaleY:0.96,x:151,y:447.2},0).wait(1).to({scaleX:1.03,scaleY:1.03,x:149.3,y:435.6},0).wait(1).to({scaleX:1.11,scaleY:1.11,x:147.3,y:422},0).wait(1).to({scaleX:1.19,scaleY:1.19,x:145.4,y:409.5},0).wait(1).to({scaleX:1.25,scaleY:1.25,x:144,y:399.8},0).wait(1).to({scaleX:1.29,scaleY:1.29,x:143,y:392.9},0).wait(1).to({scaleX:1.32,scaleY:1.32,x:142.3,y:387.8},0).wait(1).to({scaleX:1.34,scaleY:1.34,x:141.7,y:384.2},0).wait(1).to({scaleX:1.36,scaleY:1.36,x:141.3,y:381.6},0).wait(1).to({scaleX:1.37,scaleY:1.37,x:141.1,y:379.8},0).wait(1).to({scaleX:1.38,scaleY:1.38,x:140.9,y:378.7},0).wait(1).to({scaleX:1.38,scaleY:1.38,x:140.8,y:378.1},0).wait(1).to({regX:112.5,regY:112.5,scaleX:1.38,scaleY:1.38,x:779.2,y:-13.8},0).wait(1).to({regX:-350,regY:396.3,x:140.4,y:378.2},0).wait(1).to({x:140.5},0).wait(1).to({x:140.6},0).wait(1).to({x:140.7},0).wait(1).to({x:140.9},0).wait(1).to({x:141.2},0).wait(1).to({x:141.5},0).wait(1).to({x:141.8},0).wait(1).to({x:142.2},0).wait(1).to({x:142.4},0).wait(1).to({x:142.6},0).wait(1).to({x:142.7},0).wait(1).to({x:142.8},0).wait(1).to({regX:112.5,regY:112.5,x:781.6,y:-13.8},0).wait(1).to({regX:-350,regY:396.3,x:142.8,y:378.3},0).wait(2).to({y:378.4},0).wait(1).to({y:378.6},0).wait(1).to({y:378.7},0).wait(1).to({y:379},0).wait(1).to({y:379.3},0).wait(1).to({y:379.7},0).wait(1).to({y:380.2},0).wait(1).to({y:380.7},0).wait(1).to({y:381.2},0).wait(1).to({y:381.7},0).wait(1).to({y:382.1},0).wait(1).to({y:382.4},0).wait(1).to({y:382.7},0).wait(1).to({y:382.8},0).wait(1).to({y:383},0).wait(2).to({regX:112.5,regY:112.5,x:781.6,y:-9},0).wait(1).to({regX:-350,regY:396.3,x:142.8,y:383},0).wait(2).to({y:382.9},0).wait(1).to({x:142.7,y:382.8},0).wait(1).to({y:382.7},0).wait(1).to({x:142.6,y:382.5},0).wait(1).to({x:142.5,y:382.2},0).wait(1).to({x:142.4,y:381.9},0).wait(1).to({x:142.3,y:381.6},0).wait(1).to({x:142.2,y:381.2},0).wait(1).to({x:142.1,y:380.9},0).wait(1).to({x:141.9,y:380.5},0).wait(1).to({x:141.8,y:380.2},0).wait(1).to({y:379.9},0).wait(1).to({x:141.7,y:379.7},0).wait(1).to({y:379.6},0).wait(1).to({x:141.6,y:379.5},0).wait(2).to({regX:112.5,regY:112.5,x:780.4,y:-12.6},0).wait(1).to({regX:-350,regY:396.3,x:141.6,y:379.4},0).wait(3).to({x:141.7},0).wait(1).to({y:379.3},0).wait(1).to({x:141.8},0).wait(1).to({y:379.2},0).wait(1).to({x:141.9,y:379.1},0).wait(1).to({x:142,y:379},0).wait(1).to({x:142.1,y:378.9},0).wait(1).to({x:142.3,y:378.8},0).wait(1).to({x:142.4,y:378.7},0).wait(1).to({x:142.5,y:378.6},0).wait(1).to({x:142.6,y:378.5},0).wait(1).to({x:142.7,y:378.4},0).wait(1).to({y:378.3},0).wait(1).to({x:142.8},0).wait(3).to({regX:112.5,regY:112.5,x:781.6,y:-13.8},0).to({_off:true},1).wait(179));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#7FCCD9").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(1,1,1,1,0,0,0,-149,-299);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(361));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-178.9,300,639.8,835.3);
// library properties:
lib.properties = {
	id: '3B7A4E1EAA3C4C4793A36D8DF72D359B',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/300x600_drive_atlas_.png", id:"300x600_drive_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['3B7A4E1EAA3C4C4793A36D8DF72D359B'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;