(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"300x600_zebra_atlas_", frames: [[0,273,300,250],[302,519,226,185],[0,0,300,271],[302,318,227,199],[302,0,252,316]]}
];


// symbols:



(lib.bb_bg = function() {
	this.spriteSheet = ss["300x600_zebra_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.bb_pandas = function() {
	this.spriteSheet = ss["300x600_zebra_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.bb_pingu = function() {
	this.spriteSheet = ss["300x600_zebra_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.bb_redpa = function() {
	this.spriteSheet = ss["300x600_zebra_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.zebras = function() {
	this.spriteSheet = ss["300x600_zebra_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJA2QAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAgvIgog2IAAgCQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAABAAIAYAAQABAAAAAAQABAAAAABQAAAAABAAQAAABABABIAVAhIAWgiQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAIAYAAIACABIAAACIgpA2IAAAvQAAABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape.setTransform(202.7,294.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAbA2QAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIgGgUIglAAIgGAUQAAAAAAABQAAAAgBABQAAAAAAAAQgBAAAAAAIgVAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAgBABgBIAlhmQAAAAABgBQAAAAAAgBQABAAAAAAQAAAAABAAIASAAQAAAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIAmBnQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAAAAAgAgLAMIAXAAIgMgjg");
	this.shape_1.setTransform(193.7,294.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgtA2QgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAhmQAAgBAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIAqAAQAWAAAPAQQAOAPAAAWQAAAXgPAQQgRAPgVAAgAgYAhIAQAAQANABAKgKQAJgLAAgNQAAgPgLgLQgGgFgKgBIgFAAIgKAAIgGAAg");
	this.shape_2.setTransform(183.4,294.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgnAoQgRgQAAgYQAAgXARgQQAQgQAXAAQAXAAARAQQARAQAAAXQAAAYgRAQQgRAPgXABQgXgBgQgPgAgWgWQgKAKAAAMQAAANAKALQAKAJAMAAQANAAAKgJQAKgLAAgNQAAgMgKgKQgKgKgNAAQgMAAgKAKg");
	this.shape_3.setTransform(171.1,294.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgJA2QAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAhTIgcAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAgPQAAgBAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIBOAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAAPQAAABAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgcAAIAABTQAAABAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_4.setTransform(161.2,294.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AglArQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAIALgOQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQALAJANAAQAPAAAAgLQAAgGgJgEIgHgCIgJgEQgPgFgGgFQgIgIAAgNQAAgHACgGQADgFAGgEQAFgEAHgCQAIgCAJgBQAQAAAQAKQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAABIgKAOQAAABgBAAQAAAAAAAAQgBAAAAAAQgBAAAAgBQgKgGgKAAQgQAAAAAJQAAAFALAEIAJADIALAEQAYAIAAAXQAAAOgLAKQgMAIgRABQgUAAgRgNg");
	this.shape_5.setTransform(149,294.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgIA2QgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAhTIgcAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAgPQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIBOAAQABAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAAPQAAABAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIgcAAIAABTQAAABAAABQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_6.setTransform(140.6,294.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgmA2QgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAhlQAAgBAAgBQAAAAAAAAQABgBAAAAQAAAAABAAIBNAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAABIAAAPQAAABAAABQAAAAAAAAQgBABAAAAQAAAAgBAAIg4AAIAAAWIAwAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAQQAAABAAAAQAAAAAAABQgBAAAAAAQgBAAAAAAIgwAAIAAAXIA4AAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAQQAAABAAABQAAAAAAAAQgBABAAAAQAAAAgBAAg");
	this.shape_7.setTransform(131.9,294.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAQA2QAAAAgBAAQAAAAgBAAQAAgBgBAAQAAAAAAgBIgZgnIgGAIIAAAeQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIgTAAQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAhlQAAgBAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIATAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAABIAAAmIAcgmQAAgBABgBQAAAAABAAQAAgBABAAQAAAAABAAIAZAAIABABIAAACIgmAtIAoA4IABACQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAg");
	this.shape_8.setTransform(122.2,294.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgdAoQgQgQAAgYQAAgWARgQQAQgRAWAAQARAAARAMQABAAAAABQAAAAAAAAQABABgBAAQAAAAAAABIgKAPQAAAAAAABQgBAAAAAAQgBAAAAAAQgBAAAAAAQgLgIgLAAQgMAAgJAKQgJAKAAAMQAAANAJALQAJAJAMAAQAIAAAGgCIAEgDIAEgDQAAAAABAAQAAAAABAAQAAAAABABQAAAAAAAAIAKAPQABAAAAABQAAAAAAABQgBAAAAAAQAAABgBAAQgOAMgUAAQgWgBgRgPg");
	this.shape_9.setTransform(112.1,294.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgJA2QAAAAgBAAQAAAAAAgBQAAAAgBAAQAAgBAAgBIAAhlQAAgBAAgBQABAAAAAAQAAgBAAAAQABAAAAAAIASAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAABIAABlQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_10.setTransform(104.6,294.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgJA2QAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAhTIgcAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAgBIAAgPQAAgBAAgBQAAAAAAAAQABgBAAAAQABAAAAAAIBPAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAABIAAAPQAAABAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgcAAIAABTQAAABgBABQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_11.setTransform(98.1,294.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgIA2QgBAAgBAAQAAAAAAgBQgBAAAAAAQAAgBAAgBIAAgvIgog2IAAgCQAAAAAAAAQAAgBAAAAQABAAAAAAQAAAAAAAAIAZAAQAAAAABAAQABAAAAABQABAAAAAAQABABAAABIAVAhIAWgiQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAIAYAAIACABIAAACIgpA2IAAAvQAAABAAABQAAAAAAAAQAAABgBAAQAAAAAAAAg");
	this.shape_12.setTransform(85.4,294.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgSA0QgIgDgGgGQgFgGgDgIQgDgIAAgLIAAg9QAAgBAAAAQAAgBAAAAQAAAAABgBQAAAAABAAIATAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAA7QAAAYAUAAQAVAAAAgYIAAg7QAAgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAIATAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAA9QAAALgDAIQgDAIgFAGQgGAGgIADQgJADgKAAQgKAAgIgDg");
	this.shape_13.setTransform(74.8,294.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AglA2QgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAgBIAAhlQAAgBAAgBQAAAAAAAAQAAgBABAAQAAAAABAAIAkAAQALAAAJAFQAMAIAAAOQAAARgNAGIAAAAQAWAFAAAXQAAAOgMAJQgKAGgPAAgAgQAhIAQAAQAGAAAEgCQAGgCAAgHQAAgNgVAAIgLAAgAgQgKIAGAAQARAAAAgNQAAgFgFgCQgCgCgEAAIgMAAg");
	this.shape_14.setTransform(64.9,294.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#FFFFFF").ss(2,1,1).p("As9inIZ7AAIAAFPI57AAg");
	this.shape_15.setTransform(134.2,294.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol8, new cjs.Rectangle(50.2,277,168,35.5), null);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMAOQgHgGABgIQgBgHAHgGQAFgFAHAAQAIAAAGAFQAFAGAAAHQAAAIgFAGQgGAFgIAAQgHAAgFgFg");
	this.shape.setTransform(216.5,83.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_1.setTransform(209.5,78);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAACOQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_2.setTransform(200.6,78);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_3.setTransform(191.1,78);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_4.setTransform(181.7,78);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgOBLQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIg0iPQgBgDAEAAIAdAAQABAAAAAAQAAAAABABQAAAAABABQAAAAABABIAhBqIAjhqQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAeAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAQAAAAAAABIg1COQAAABgBABQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_5.setTransform(171.3,78);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag2A4QgYgXAAghQAAggAYgXQAXgVAfAAQAgAAAXAVQAYAXAAAgQAAAigYAWQgWAVghAAQgfAAgXgVgAgfggQgNAPAAARQAAATANANQANAOASAAQATAAANgOQANgNAAgTQAAgSgNgOQgNgNgTAAQgSAAgNANg");
	this.shape_6.setTransform(149.7,78);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgMBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_7.setTransform(136,78);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_8.setTransform(119.1,78);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAlBLIgCgBIhEheIAABcQAAAAAAABQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABABAAIBDBcIAAhaQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAACOQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_9.setTransform(104.9,78);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag2A4QgYgXAAghQAAggAYgXQAXgVAfAAQAgAAAXAVQAYAXAAAgQAAAigYAWQgWAVghAAQgfAAgXgVgAgfggQgNAPAAARQAAATANANQANAOASAAQATAAANgOQANgNAAgTQAAgSgNgOQgNgNgTAAQgSAAgNANg");
	this.shape_10.setTransform(88,78);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_11.setTransform(73.2,78);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_12.setTransform(59.9,77.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAAWQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIhPAAIAAAeIBCAAQABAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhCAAIAAAgIBPAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAXQAAAAAAABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_13.setTransform(46.1,78);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAYBLQgDAAgCgDIgYgxIgWAAIAAAxQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAPQANAOAAAVQAAAQgJALQgJANgOAFIAbAxIABAEQAAAAAAAAQgBAAAAABQAAAAgBAAQgBAAAAAAgAgbgEIAiAAQAHAAAHgFQAHgHAAgIQAAgKgHgGQgHgFgHAAIgiAAg");
	this.shape_14.setTransform(31.8,78);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#BEA149").s().p("AgxA3QgVgXAAggQAAgeAWgXQAXgXAfAAQAXAAAYAQQABAAAAABQABAAAAAAQAAABAAABQgBAAAAABIgOAVQgBADgDgCQgPgLgPAAQgRAAgNAOQgNAOAAARQAAATANAOQANANARAAQAUAAAMgKIAAgMIgbAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgYQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIA5AAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIAABKQAAABgBABQAAAAAAABQgBAAAAABQgBAAgBAAIgaAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIAAgBQgPAHgRAAQghAAgWgWg");
	this.shape_15.setTransform(197.8,55.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEheIAABbQAAABAAABQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIAAiOQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABABAAIBDBcIAAhbQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAACOQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_16.setTransform(181.6,55.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAgBIAAiOQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAAAIAACOQAAABgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_17.setTransform(170.2,55.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#BEA149").s().p("Ag4BLQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBBAAQAVAAAPAPQAPAPAAAXQAAAWgPAOQgPAPgVABIgjAAIAAAoQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAgAgaACIAcAAQALgBAHgEQAHgGAAgMQAAgMgIgGQgGgGgLAAIgcAAg");
	this.shape_18.setTransform(160.1,55.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#BEA149").s().p("Ag4BLQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBBAAQAVAAAPAPQAPAPAAAXQAAAWgPAOQgPAPgVABIgjAAIAAAoQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAgAgaACIAcAAQALgBAHgEQAHgGAAgMQAAgMgIgGQgGgGgLAAIgcAAg");
	this.shape_19.setTransform(145.6,55.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#BEA149").s().p("Ag2A4QgYgXAAghQAAghAYgWQAXgVAfAAQAgAAAXAVQAYAWAAAhQAAAhgYAXQgWAVghAAQgfAAgXgVgAgfgfQgNAOAAARQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgNQgNgOgTAAQgSAAgNAOg");
	this.shape_20.setTransform(129.2,55.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAh0IgnAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgXQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAXQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgnAAIAAB0QAAABAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_21.setTransform(115.5,55.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_22.setTransform(104.2,55.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#BEA149").s().p("AAeBLQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIgchYIgbBYQAAABAAABQgBAAAAABQAAAAgBAAQAAAAAAAAIgjAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQgBgBAAgBIgtiPQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAeAAQAAAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAeBqIAfhqQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAcAAQAAAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAfBqIAehqQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAeAAQABAAAAAAQABAAAAABQAAAAAAABQAAABAAABIguCOQAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_23.setTransform(81,55.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#BEA149").s().p("Ag2A4QgYgXAAghQAAghAYgWQAXgVAfAAQAgAAAXAVQAYAWAAAhQAAAhgYAXQgWAVghAAQgfAAgXgVgAgfgfQgNAOAAARQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgNQgNgOgTAAQgSAAgNAOg");
	this.shape_24.setTransform(61,55.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#BEA149").s().p("AAiBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAgBIAAg5Ig8AAIAAA5QAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAaAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAAA5IA8AAIAAg5QAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABAAIAaAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAAAIAACOQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_25.setTransform(44.2,55.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_26.setTransform(30.1,55.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_27.setTransform(140.5,35);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_28.setTransform(128.6,35);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBrAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAAAWQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAIhNAAIAAAeIBBAAQABAAABAAQABAAAAABQABAAAAABQAAABAAABIAAAVQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhBAAIAAAgIBNAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAXQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_29.setTransform(116.4,35);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#BEA149").s().p("AgoBLQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAB0IA1AAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAAAXQAAAAAAABQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_30.setTransform(104.1,35);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_31.setTransform(92.3,35);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEhdIAABbQAAAAAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAAAAAQABAAAAAAQABABAAAAQAAAAABABIBDBcIAAhaQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAACOQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_32.setTransform(78.5,35);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#BEA149").s().p("AgZBIQgMgEgHgIQgIgJgFgLQgDgLAAgOIAAhWQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAABSQAAAiAcAAQAdAAAAgiIAAhSQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAaAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAABWQAAAOgFALQgEALgHAJQgJAIgLAEQgMAEgOAAQgOAAgLgEg");
	this.shape_33.setTransform(62.8,35.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#BEA149").s().p("Ag2A3QgYgWAAghQAAghAYgVQAXgWAfAAQAgAAAXAWQAYAVAAAhQAAAhgYAWQgWAWghAAQgfAAgXgWgAgfggQgNAOAAASQAAATANANQANAOASAAQATAAANgOQANgNAAgTQAAgSgNgOQgNgNgTAAQgSAAgNANg");
	this.shape_34.setTransform(46.4,35);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#BEA149").s().p("AgoA3QgWgWAAghQAAgeAXgXQAWgXAfAAQAYAAAXAQQABAAABABQAAAAAAABQAAAAAAABQAAAAgBABIgNAVQgCADgDgCQgPgKgPAAQgRAAgNANQgNAOAAARQAAATANANQANAOARAAQALAAAIgEIAGgDIAFgDQABgBABAAQAAAAABAAQAAAAABABQAAAAABABIANAUQABABAAAAQAAABAAAAQAAABAAAAQgBABgBABQgTAPgcAAQgfAAgXgWg");
	this.shape_35.setTransform(31.2,35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol7, new cjs.Rectangle(22,20,199.7,72.8), null);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("ABqWGQpagkiIncQiInch8jSQh9jThMkkQiMocF2lpQEHj+F1AfIEOAYIgVJuICgD6IGQgeQGnGyB7LcQmVMao7AAIgygBg");
	mask.setTransform(64.5,191.2);

	// Layer_1
	this.instance = new lib.zebras();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol6, new cjs.Rectangle(0,49.7,177.7,266.4), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bb_redpa();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(0,0,227,199), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BEA149").s().p("AgwA3QgXgXAAggQAAgeAYgXQAWgXAfAAQAXAAAYAQQABAAAAABQABAAAAAAQAAABAAABQAAAAgBABIgNAVQgCADgEgCQgOgLgPAAQgRAAgNAOQgNAOAAARQAAATANAOQANANARAAQAUAAANgKIAAgMIgcAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgYQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIA5AAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAABKQAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAIgaAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAgBQgQAHgRAAQghAAgVgWg");
	this.shape.setTransform(171.7,-139);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEheIAABbQAAABAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIAAiNQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAAAAAQABAAAAABQABAAAAAAQAAABABAAIBDBcIAAhaQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAACNQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(155.6,-139);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAiNQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACNQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_2.setTransform(144.1,-139);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEheIAABbQAAABAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIAAiNQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAAAAAQABAAAAABQABAAAAAAQAAABABAAIBDBcIAAhaQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAACNQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_3.setTransform(132.6,-139);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#BEA149").s().p("AAYBLQgDAAgCgEIgYgwIgWAAIAAAwQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiNQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAPQANAOAAAVQAAAPgJAMQgJANgOAFIAbAxIABAEQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgbgEIAiAAQAHAAAHgFQAHgHAAgIQAAgKgHgGQgHgFgHAAIgiAAg");
	this.shape_4.setTransform(117.6,-139);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BEA149").s().p("AgZBIQgMgFgHgIQgIgHgEgMQgFgLAAgPIAAhVQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAABTQAAAhAcAAQAdAAAAghIAAhTQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAbAAQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIAABVQgBAPgEALQgEAMgIAHQgHAIgMAFQgLAEgPAAQgOAAgLgEg");
	this.shape_5.setTransform(102.2,-138.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAh0IgnAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgnAAIAAB0QAAABAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_6.setTransform(88.9,-139);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#BEA149").s().p("Ag/BLQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIA6AAQAgAAAUAWQAUAVAAAfQAAAggWAVQgWAWgeAAgAghAvIAWAAQASAAANgOQAOgOAAgTQAAgWgQgOQgIgIgOgBIgHgBIgOAAIgIAAg");
	this.shape_7.setTransform(70.6,-139);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#BEA149").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_8.setTransform(55.3,-139.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAgBIAAiNQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIAAAWQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAIhOAAIAAAfIBBAAQABAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhBAAIAAAgIBOAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAWQAAABgBABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_9.setTransform(41.5,-139);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#BEA149").s().p("AAiBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAg5Ig8AAIAAA5QAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiNQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAaAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAAA4IA8AAIAAg4QAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAABAAQAAAAAAABQABAAAAABQAAABAAABIAACNQAAABAAABQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_10.setTransform(26,-139);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(16,-154,166.5,29.8), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bb_pandas();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,0,226,185), null);


(lib.Symbol2copy4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAAWQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIhPAAIAAAeIBDAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAABIAAAVQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIhDAAIAAAgIBPAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAXQAAAAAAABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape.setTransform(152,35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BEA149").s().p("AgoBLQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAB0IA1AAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAAXQAAAAAAABQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_1.setTransform(139.7,35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BEA149").s().p("AgzBLQgBAAgBAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQABAAABAAIAxAAQAQAAAMAHQASALAAAVQAAAWgTAIIAAABQAfAHAAAgQAAATgRAMQgOAJgVAAgAgWAuIAWAAQAJAAAFgCQAJgEgBgKQAAgRgdAAIgPAAgAgWgOIAIAAQAYAAAAgSQAAgHgGgEQgEgCgGABIgQAAg");
	this.shape_2.setTransform(127.4,35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAACOQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_3.setTransform(116.8,35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBABAAQAAgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_4.setTransform(107.8,35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_5.setTransform(96.5,35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAACOQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_6.setTransform(87.1,35);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_7.setTransform(77.6,35);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBrAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAAAWQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAIhOAAIAAAeIBDAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAABIAAAVQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIhDAAIAAAgIBOAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAXQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_8.setTransform(65.4,35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#BEA149").s().p("AAYBLQgDAAgCgDIgYgxIgWAAIAAAxQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAOQANAPAAAUQAAAQgJAMQgJANgOAFIAbAyIABACQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgbgEIAiAAQAHAAAHgFQAHgGAAgKQAAgJgHgGQgHgFgHAAIgiAAg");
	this.shape_9.setTransform(51.1,35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#BEA149").s().p("AAYBLQgDAAgCgDIgYgxIgWAAIAAAxQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAOQANAPAAAUQAAAQgJAMQgJANgOAFIAbAyIABACQAAABAAAAQgBAAAAABQAAAAgBAAQgBAAAAAAgAgbgEIAiAAQAHAAAHgFQAHgGAAgKQAAgJgHgGQgHgFgHAAIgiAAg");
	this.shape_10.setTransform(36.5,35);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_11.setTransform(25.4,35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2copy4, new cjs.Rectangle(20,20,140.3,29.8), null);


(lib.Symbol2copy2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BEA149").s().p("AgoA3QgWgWAAghQAAgeAXgXQAWgXAfAAQAYAAAXAQQABAAABABQAAAAAAABQAAAAAAABQAAAAgBABIgNAVQgCADgDgCQgPgKgPAAQgRAAgNANQgNAOAAARQAAATANANQANAOARAAQALAAAIgEIAGgDIAFgDQABgBABAAQAAAAABAAQAAAAABABQAAAAABABIANAUQABABAAAAQAAABAAAAQAAABAAAAQgBABgBABQgTAPgcAAQgfAAgXgWg");
	this.shape.setTransform(122.9,35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAACOQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(112.5,35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_2.setTransform(103.5,35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BEA149").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_3.setTransform(91.7,34.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#BEA149").s().p("AAvBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAhWIgeAyQgBABAAABQgBAAAAABQAAAAgBAAQAAAAAAAAIgUAAIgEgDIgdgyIAABWQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgZAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAbAAQABAAAAAAQAAAAABABQAAAAABABQAAABABABIAoBGIAphGIAEgEIAbAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_4.setTransform(75.6,35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BEA149").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_5.setTransform(59.5,34.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BEA149").s().p("AAYBLQgDAAgCgDIgYgxIgWAAIAAAxQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAOQANAPAAAUQAAAQgJAMQgJANgOAFIAbAyIABACQAAABAAAAQgBAAAAABQAAAAgBAAQgBAAAAAAgAgbgEIAiAAQAHAAAHgFQAHgGAAgKQAAgJgHgGQgHgFgHAAIgiAAg");
	this.shape_6.setTransform(45.8,35);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#BEA149").s().p("Ag/BLQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIA6AAQAgAAAUAWQAUAVAAAfQAAAggWAWQgWAVgeAAgAghAuIAWAAQASAAANgNQAOgOAAgTQAAgVgQgPQgIgHgOgCIgHAAIgOAAIgIAAg");
	this.shape_7.setTransform(30.4,35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2copy2, new cjs.Rectangle(20,20,111.9,29.8), null);


(lib.Symbol2copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape.setTransform(117.1,29);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAlBLIgCgBIhEhdIAABaQAAABAAABQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIAAiOQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABABAAIBDBcIAAhbQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAACOQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(102.9,29);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag2A3QgYgWAAghQAAggAYgXQAXgVAfAAQAgAAAXAVQAYAXAAAgQAAAigYAVQgWAWghAAQgfAAgXgWgAgfgfQgNANAAASQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgNQgNgOgTAAQgSAAgNAOg");
	this.shape_2.setTransform(86,29);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_3.setTransform(71.2,29);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_4.setTransform(57.9,28.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAgBIAAiOQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQABABAAAAIAAAXQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAIhOAAIAAAfIBBAAQABAAABAAQABAAAAABQABAAAAABQAAABAAABIAAAVQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhBAAIAAAgIBOAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAWQAAABgBABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_5.setTransform(44.1,29);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAYBLQgDAAgCgEIgYgvIgWAAIAAAvQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAOQANAPAAAUQAAARgJALQgJANgOAFIAbAxIABADQAAABAAAAQgBAAAAABQAAAAgBAAQgBAAAAAAgAgbgEIAiAAQAHAAAHgFQAHgHAAgJQAAgJgHgGQgHgFgHAAIgiAAg");
	this.shape_6.setTransform(29.8,29);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2copy, new cjs.Rectangle(20,14,105.4,29.8), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BEA149").s().p("AgwA3QgXgXAAggQAAgeAYgXQAWgXAfAAQAXAAAYAQQABAAAAABQABAAAAABQAAAAAAABQAAAAgBABIgNAVQgCADgEgCQgOgLgPAAQgRAAgNAOQgNAOAAARQAAATANAOQANANARAAQAUAAANgKIAAgMIgcAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgYQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIA5AAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAABKQAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAIgaAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAgBQgQAHgRAAQghAAgVgWg");
	this.shape.setTransform(166.8,35);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEhdIAABbQAAAAAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAAAAAQABAAAAAAQABABAAAAQAAAAABABIBDBcIAAhaQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAACOQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(150.6,35);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_2.setTransform(139.2,35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BEA149").s().p("AAiBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAg6Ig8AAIAAA6QAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAaAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAAA4IA8AAIAAg4QAAgBAAgBQAAgBABAAQAAgBAAAAQABAAABAAIAaAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_3.setTransform(127.8,35);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#BEA149").s().p("AgoA3QgWgWAAghQAAgeAXgXQAWgXAfAAQAYAAAXAQQABAAABABQAAAAAAABQAAAAAAABQAAAAgBABIgNAVQgCADgDgCQgPgKgPAAQgRAAgNANQgNAOAAARQAAATANANQANAOARAAQALAAAIgEIAGgDIAFgDQABgBABAAQAAAAABAAQAAAAABABQAAAAABABIANAUQABABAAAAQAAABAAAAQAAABAAAAQgBABgBABQgTAPgcAAQgfAAgXgWg");
	this.shape_4.setTransform(113,35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_5.setTransform(101.1,35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BEA149").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_6.setTransform(89.3,34.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#BEA149").s().p("AgoA3QgWgWAAghQAAgeAXgXQAWgXAfAAQAYAAAXAQQABAAABABQAAAAAAABQAAAAAAABQAAAAgBABIgNAVQgCADgDgCQgPgKgPAAQgRAAgNANQgNAOAAARQAAATANANQANAOARAAQALAAAIgEIAGgDIAFgDQABgBABAAQAAAAABAAQAAAAABABQAAAAABABIANAUQABABAAAAQAAABAAAAQAAABAAAAQgBABgBABQgTAPgcAAQgfAAgXgWg");
	this.shape_7.setTransform(75.3,35);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIAAAWQAAABgBABQAAAAAAABQgBAAAAAAQgBABAAAAIhOAAIAAAeIBBAAQABAAABAAQABAAAAABQABAAAAABQAAABAAABIAAAVQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhBAAIAAAgIBOAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAXQAAAAgBABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_8.setTransform(56.3,35);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAhDIg3hLIAAgCQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAhAAQAEAAADAEIAdAuIAfguQACgEADAAIAiAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIgBACIg3BLIAABDQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_9.setTransform(42.6,35);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAAWQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIhPAAIAAAeIBCAAQABAAABAAQABAAAAABQABAAAAABQAAABAAABIAAAVQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhCAAIAAAgIBPAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAXQAAAAAAABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_10.setTransform(29.5,35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(20,20,157.6,29.8), null);


(lib.Symbol1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AB/SgQAAgDjjmmQjimigCgIIAAAAIAAAAQgHgDjOiAQAEADh4AlQh4AmADADQAEADhugsQhmgogEAAQADgKgXq1QgYrCADACQW1FUAHAFQAEACEiE3IElE6QAEADgsLMQgsLMADADQABABgYAAQhzAAqqgWgAB/SgIAAAAIAAAAIAAAAg");
	mask.setTransform(171.1,111);

	// Layer_1
	this.instance = new lib.zebras();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1copy, new cjs.Rectangle(68.3,0,183.8,231.6), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AmKPHQgHgGpj7IQgDgDHfhdQHNhaAOgFQgDAIABDAIADDMIC/DLQABgFB0guQB3gwgDgCQgDgDCCBFQB7BAAEABQABAHCwGiQC1GsgEgDQAvFUgGgGQgDgDq9A7QqaA4gjAAIgCAAgAJqlJIAAAAIAAAAIAAAAg");
	mask.setTransform(73.4,179.4);

	// Layer_1
	this.instance = new lib.zebras();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,82.7,174.8,193.4), null);


(lib.pingus = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bb_pingu();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pingus, new cjs.Rectangle(0,0,300,271), null);


// stage content:
(lib._300x600_zebra = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer_12
	this.instance = new lib.Symbol6();
	this.instance.parent = this;
	this.instance.setTransform(304,218.3,0.829,0.829,0,0,0,126.2,102.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(295).to({_off:false},0).wait(1).to({regX:88.8,regY:182.8,x:272.7,y:285.2,alpha:0.033},0).wait(1).to({x:272.3,alpha:0.07},0).wait(1).to({x:271.9,alpha:0.114},0).wait(1).to({x:271.4,alpha:0.164},0).wait(1).to({x:270.8,alpha:0.221},0).wait(1).to({x:270.1,alpha:0.286},0).wait(1).to({x:269.4,alpha:0.357},0).wait(1).to({x:268.7,alpha:0.43},0).wait(1).to({x:268,alpha:0.502},0).wait(1).to({x:267.3,alpha:0.569},0).wait(1).to({x:266.7,alpha:0.63},0).wait(1).to({x:266.2,alpha:0.682},0).wait(1).to({x:265.7,alpha:0.728},0).wait(1).to({x:265.3,alpha:0.768},0).wait(1).to({x:265,alpha:0.803},0).wait(1).to({x:264.7,alpha:0.833},0).wait(1).to({x:264.4,alpha:0.859},0).wait(1).to({x:264.2,alpha:0.881},0).wait(1).to({x:264,alpha:0.901},0).wait(1).to({x:263.8,alpha:0.918},0).wait(1).to({x:263.7,alpha:0.932},0).wait(1).to({x:263.5,alpha:0.945},0).wait(1).to({x:263.4,alpha:0.956},0).wait(1).to({x:263.3,alpha:0.966},0).wait(1).to({alpha:0.974},0).wait(1).to({x:263.2,alpha:0.98},0).wait(1).to({x:263.1,alpha:0.986},0).wait(1).to({alpha:0.991},0).wait(1).to({alpha:0.994},0).wait(1).to({x:263,alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:126.2,regY:102.2,x:294,y:218.3},0).wait(24));

	// Layer_9
	this.instance_1 = new lib.pingus();
	this.instance_1.parent = this;
	this.instance_1.setTransform(175.5,335,0.299,0.299,0,0,0,150.6,136.4);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(295).to({_off:false},0).wait(1).to({regX:150,regY:135.5,x:175.1,y:334.6,alpha:0.033},0).wait(1).to({x:174.9,y:334.5,alpha:0.07},0).wait(1).to({x:174.7,y:334.3,alpha:0.114},0).wait(1).to({x:174.5,y:334.1,alpha:0.164},0).wait(1).to({x:174.2,y:333.9,alpha:0.221},0).wait(1).to({x:173.9,y:333.6,alpha:0.286},0).wait(1).to({x:173.5,y:333.3,alpha:0.357},0).wait(1).to({x:173.2,y:333,alpha:0.43},0).wait(1).to({x:172.8,y:332.7,alpha:0.502},0).wait(1).to({x:172.5,y:332.5,alpha:0.569},0).wait(1).to({x:172.2,y:332.2,alpha:0.63},0).wait(1).to({x:171.9,y:332,alpha:0.682},0).wait(1).to({x:171.7,y:331.8,alpha:0.728},0).wait(1).to({x:171.5,y:331.7,alpha:0.768},0).wait(1).to({x:171.3,y:331.5,alpha:0.803},0).wait(1).to({x:171.1,y:331.4,alpha:0.833},0).wait(1).to({x:171,y:331.3,alpha:0.859},0).wait(1).to({x:170.9,y:331.2,alpha:0.881},0).wait(1).to({x:170.8,y:331.1,alpha:0.901},0).wait(1).to({x:170.7,alpha:0.918},0).wait(1).to({x:170.6,y:331,alpha:0.932},0).wait(1).to({alpha:0.945},0).wait(1).to({x:170.5,y:330.9,alpha:0.956},0).wait(1).to({alpha:0.966},0).wait(1).to({x:170.4,alpha:0.974},0).wait(1).to({y:330.8,alpha:0.98},0).wait(1).to({alpha:0.986},0).wait(1).to({x:170.3,alpha:0.991},0).wait(1).to({alpha:0.994},0).wait(1).to({alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:150.6,regY:136.4,x:170.5,y:331},0).wait(24));

	// Layer_8
	this.instance_2 = new lib.Symbol5();
	this.instance_2.parent = this;
	this.instance_2.setTransform(73.7,347.2,0.244,0.244,0,0,180,112.9,100.6);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(295).to({_off:false},0).wait(1).to({regX:113.5,regY:99.5,y:347,alpha:0.033},0).wait(1).to({x:73.9,alpha:0.07},0).wait(1).to({x:74.1,alpha:0.114},0).wait(1).to({x:74.3,alpha:0.164},0).wait(1).to({x:74.6,alpha:0.221},0).wait(1).to({x:74.9,alpha:0.286},0).wait(1).to({x:75.3,alpha:0.357},0).wait(1).to({x:75.6,alpha:0.43},0).wait(1).to({x:76,alpha:0.502},0).wait(1).to({x:76.3,alpha:0.569},0).wait(1).to({x:76.6,alpha:0.63},0).wait(1).to({x:76.9,alpha:0.682},0).wait(1).to({x:77.1,alpha:0.728},0).wait(1).to({x:77.3,alpha:0.768},0).wait(1).to({x:77.5,alpha:0.803},0).wait(1).to({x:77.7,alpha:0.833},0).wait(1).to({x:77.8,alpha:0.859},0).wait(1).to({x:77.9,alpha:0.881},0).wait(1).to({x:78,alpha:0.901},0).wait(1).to({x:78.1,alpha:0.918},0).wait(1).to({x:78.2,alpha:0.932},0).wait(1).to({alpha:0.945},0).wait(1).to({x:78.3,alpha:0.956},0).wait(1).to({alpha:0.966},0).wait(1).to({x:78.4,alpha:0.974},0).wait(1).to({alpha:0.98},0).wait(1).to({alpha:0.986},0).wait(1).to({x:78.5,alpha:0.991},0).wait(1).to({alpha:0.994},0).wait(1).to({alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:112.9,regY:100.6,x:78.7,y:347.2},0).wait(24));

	// Layer_4
	this.instance_3 = new lib.Symbol2copy();
	this.instance_3.parent = this;
	this.instance_3.setTransform(92.9,35.9,1,1,0,0,0,77.9,14.8);
	this.instance_3.alpha = 0;

	this.instance_4 = new lib.Symbol3();
	this.instance_4.parent = this;
	this.instance_4.setTransform(65,296.6,0.57,0.57,0,0,180,112.9,92.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:55.9,alpha:1},29,cjs.Ease.quartOut).wait(249).to({alpha:0},14).to({_off:true},1).wait(59));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(295).to({_off:false},0).wait(1).to({regX:113,regY:92.5,x:65.3,y:296.5,alpha:0.033},0).wait(1).to({x:65.7,alpha:0.07},0).wait(1).to({x:66.1,alpha:0.114},0).wait(1).to({x:66.6,alpha:0.164},0).wait(1).to({x:67.2,alpha:0.221},0).wait(1).to({x:67.8,alpha:0.286},0).wait(1).to({x:68.5,alpha:0.357},0).wait(1).to({x:69.2,alpha:0.43},0).wait(1).to({x:70,alpha:0.502},0).wait(1).to({x:70.6,alpha:0.569},0).wait(1).to({x:71.2,alpha:0.63},0).wait(1).to({x:71.8,alpha:0.682},0).wait(1).to({x:72.2,alpha:0.728},0).wait(1).to({x:72.6,alpha:0.768},0).wait(1).to({x:73,alpha:0.803},0).wait(1).to({x:73.3,alpha:0.833},0).wait(1).to({x:73.5,alpha:0.859},0).wait(1).to({x:73.8,alpha:0.881},0).wait(1).to({x:74,alpha:0.901},0).wait(1).to({x:74.1,alpha:0.918},0).wait(1).to({x:74.3,alpha:0.932},0).wait(1).to({x:74.4,alpha:0.945},0).wait(1).to({x:74.5,alpha:0.956},0).wait(1).to({x:74.6,alpha:0.966},0).wait(1).to({x:74.7,alpha:0.974},0).wait(1).to({x:74.8,alpha:0.98},0).wait(1).to({alpha:0.986},0).wait(1).to({x:74.9,alpha:0.991},0).wait(1).to({alpha:0.994},0).wait(1).to({alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:112.9,regY:92.7,x:75,y:296.6},0).wait(24));

	// type2
	this.instance_5 = new lib.Symbol2copy2();
	this.instance_5.parent = this;
	this.instance_5.setTransform(92.9,7.9,1,1,0,0,0,77.9,14.8);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.instance_6 = new lib.Symbol4();
	this.instance_6.parent = this;
	this.instance_6.setTransform(102.2,202.6,1,1,0,0,0,83.2,25.9);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.instance_7 = new lib.Symbol8();
	this.instance_7.parent = this;
	this.instance_7.setTransform(86,221.3,1,1,0,0,0,68,13.7);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(75).to({_off:false},0).to({y:27.9,alpha:1},29,cjs.Ease.quartOut).wait(29).to({y:37.9,alpha:0},10).to({_off:true},1).wait(208));
	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(209).to({_off:false},0).wait(1).to({regX:99.3,regY:-139,x:118.3,y:38.2,alpha:0.053},0).wait(1).to({y:38.8,alpha:0.118},0).wait(1).to({y:39.6,alpha:0.196},0).wait(1).to({y:40.5,alpha:0.289},0).wait(1).to({y:41.6,alpha:0.391},0).wait(1).to({y:42.6,alpha:0.495},0).wait(1).to({y:43.6,alpha:0.591},0).wait(1).to({y:44.4,alpha:0.674},0).wait(1).to({y:45.1,alpha:0.743},0).wait(1).to({y:45.6,alpha:0.799},0).wait(1).to({y:46.1,alpha:0.845},0).wait(1).to({y:46.5,alpha:0.882},0).wait(1).to({y:46.8,alpha:0.912},0).wait(1).to({y:47,alpha:0.937},0).wait(1).to({y:47.2,alpha:0.956},0).wait(1).to({y:47.4,alpha:0.971},0).wait(1).to({y:47.5,alpha:0.982},0).wait(1).to({y:47.6,alpha:0.99},0).wait(1).to({alpha:0.996},0).wait(1).to({alpha:0.999},0).wait(1).to({regX:83.2,regY:25.9,x:102.2,y:212.6,alpha:1},0).wait(42).to({y:214.6,alpha:0},10).to({_off:true},1).wait(69));
	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(334).to({_off:false},0).to({alpha:1},17).wait(1));

	// type
	this.instance_8 = new lib.Symbol2();
	this.instance_8.parent = this;
	this.instance_8.setTransform(92.9,7.9,1,1,0,0,0,77.9,14.8);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.instance_9 = new lib.Symbol2copy4();
	this.instance_9.parent = this;
	this.instance_9.setTransform(15,-6.9);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.instance_10 = new lib.Symbol7();
	this.instance_10.parent = this;
	this.instance_10.setTransform(113.7,39.1,1,1,0,0,0,99.9,36.4);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(4).to({_off:false},0).to({y:27.9,alpha:1},29,cjs.Ease.quartOut).wait(32).to({y:37.9,alpha:0},10).to({_off:true},1).wait(276));
	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(143).to({_off:false},0).to({y:13.1,alpha:1},29,cjs.Ease.quartOut).wait(27).to({regX:77.9,regY:14.8,x:92.9,y:27.9},0).to({y:37.9,alpha:0},10).to({_off:true},2).wait(141));
	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(298).to({_off:false},0).wait(1).to({regX:121.5,regY:56.5,x:135.3,y:59.6,alpha:0.046},0).wait(1).to({y:60.1,alpha:0.1},0).wait(1).to({y:60.8,alpha:0.163},0).wait(1).to({y:61.5,alpha:0.237},0).wait(1).to({y:62.3,alpha:0.32},0).wait(1).to({y:63.2,alpha:0.407},0).wait(1).to({y:64.1,alpha:0.495},0).wait(1).to({y:64.9,alpha:0.578},0).wait(1).to({y:65.7,alpha:0.651},0).wait(1).to({y:66.3,alpha:0.715},0).wait(1).to({y:66.8,alpha:0.769},0).wait(1).to({y:67.3,alpha:0.815},0).wait(1).to({y:67.7,alpha:0.853},0).wait(1).to({y:68,alpha:0.885},0).wait(1).to({y:68.3,alpha:0.911},0).wait(1).to({y:68.5,alpha:0.933},0).wait(1).to({y:68.7,alpha:0.951},0).wait(1).to({y:68.8,alpha:0.966},0).wait(1).to({y:68.9,alpha:0.977},0).wait(1).to({y:69,alpha:0.986},0).wait(1).to({y:69.1,alpha:0.992},0).wait(1).to({alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({regX:99.9,regY:36.4,x:113.7,y:49.1,alpha:1},0).wait(30));

	// Layer_7
	this.instance_11 = new lib.Symbol3();
	this.instance_11.parent = this;
	this.instance_11.setTransform(174.7,271.8,1,1,0,0,0,113,92.5);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(141).to({_off:false},0).to({x:166.7,alpha:1},19).to({x:151.7},40).to({x:146.7,alpha:0},16).to({_off:true},1).wait(135));

	// Layer_6
	this.instance_12 = new lib.pingus();
	this.instance_12.parent = this;
	this.instance_12.setTransform(147.3,277.4,0.7,0.7,0,0,0,150.2,135.6);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.instance_13 = new lib.Symbol5();
	this.instance_13.parent = this;
	this.instance_13.setTransform(140.4,282.5,1,1,0,0,0,113.5,99.5);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(71).to({_off:false},0).to({x:155.3,alpha:1},19).to({x:166.3},36).to({x:170.3,alpha:0},17).to({_off:true},2).wait(207));
	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(214).to({_off:false},0).to({x:150.4,alpha:1},22).to({x:160.4},40).to({x:166.4,alpha:0},19).to({_off:true},34).wait(23));

	// animals copy
	this.instance_14 = new lib.Symbol1copy();
	this.instance_14.parent = this;
	this.instance_14.setTransform(245.6,474.7,1.333,1.333,0,0,0,126.1,102.2);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({x:236.6,y:466.7,alpha:1},21).to({x:224.6,y:458.7},32).to({x:216.6,y:453.7,alpha:0},21).to({_off:true},1).wait(277));

	// animals
	this.instance_15 = new lib.Symbol1();
	this.instance_15.parent = this;
	this.instance_15.setTransform(203.7,412.4,1.333,1.333,0,0,0,126,102.2);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({x:194.7,y:404.4,alpha:1},21).to({x:182.7,y:396.4},32).to({x:174.7,y:391.4,alpha:0},21).to({_off:true},1).wait(277));

	// bg
	this.instance_16 = new lib.bb_bg();
	this.instance_16.parent = this;
	this.instance_16.setTransform(0,0,1.003,2.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(352));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(148.5,300,444.2,759.6);
// library properties:
lib.properties = {
	id: '0267BCEF7A554799BD8E2A3CB4CDA28B',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/300x600_zebra_atlas_.png", id:"300x600_zebra_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0267BCEF7A554799BD8E2A3CB4CDA28B'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;