(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"970x250_cupcake_atlas_", frames: [[0,273,626,120],[0,0,286,271]]}
];


// symbols:



(lib.docBC = function() {
	this.spriteSheet = ss["970x250_cupcake_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.volcanoman = function() {
	this.spriteSheet = ss["970x250_cupcake_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.docBC();
	this.instance.parent = this;
	this.instance.setTransform(-142,-30,0.9,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-142,-30,563.4,108);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAQIgGgFIgDgFIgBgGIABgGIADgFIAGgEIAFgBIAGABIAGAEIADAFIABAGIgBAGIgDAFIgGAFIgGABg");
	this.shape.setTransform(560.2,99.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBBWQgHgCgEgEQgEgGgDgIQgCgIAAgMIABhIIgVAAIAAgTIAVAAIAAggIAXgKIAAAqIAeAAIAAATIgfAAIAABLQAAAIACAFQABAEAEACQAEACAFAAIAJgBIAJgDIAGAQIgNAFQgHACgJAAQgIgBgGgCg");
	this.shape_1.setTransform(552.5,92.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgZAhIAYhHIAbAKIggBDg");
	this.shape_2.setTransform(543.7,85.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AANBDIAAgWIATAAIAAg7QAAgPgIgIQgIgHgOgBQgHAAgJAFQgIAEgIAFIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhWIgSAAIAAgXIAqAAIAAAQIABAAIAJgHIAJgGIALgDIALgCQAKAAAJADQAJADAFAGQAHAGADAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_3.setTransform(531.4,94.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXBBQgKgFgFgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQADADAGABIAJABIAJgBIAIgEQAEgCABgDQADgEAAgEQgBgGgEgFQgEgEgJgEIgYgJQgQgEgIgJQgHgIAAgNQAAgIAEgHQACgIAHgFQAFgFAIgDQAJgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgDgDQgCgEgEgDIgIgDIgJgBIgJABIgHADQgDACgDAEQgBADAAADQAAAHAEAEQAEAEAKADIAYAJQAQAFAHAJQAIAJAAANQAAAJgDAHQgEAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_4.setTransform(516.4,94.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgGhAIgFgEIgEgFIAAgHIAAgGIAEgFIAFgEIAGgBIAHABIAEAEIAEAFIACAGIgCAHIgEAFIgEAEIgHABg");
	this.shape_5.setTransform(506.1,91.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AA4BDIAAgWIASAAIAAg7QAAgPgHgIQgIgHgOgBQgIAAgJAFQgJADgHAHIAABLIASAAIAAAWIg8AAIAAgWIATAAIAAg7QAAgPgIgIQgHgHgPgBQgIAAgJAFQgIAEgHAFIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhWIgSAAIAAgXIApAAIAAAQIABAAIAJgHIAKgGIALgDIALgCQAPAAAKAFQAKAGAFALIAKgJIALgGIAMgFQAGgCAIAAQAKAAAJADQAIADAGAGQAGAGADAJQADAKABAMIAAA+IASAAIAAAWg");
	this.shape_6.setTransform(483.2,94.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AghBCQgIgDgGgFQgFgGgEgGQgDgIAAgIQABgHACgHQADgGADgGQAEgEAGgCIALgGIANgCIAMgBIAPABIAKABIABgLQAAgHgCgFQgCgFgEgEQgDgDgGgBQgFgCgGAAIgKABIgLACIgIADIgHAEIgIgRIAKgGIAMgEIANgDIAMgBQALAAAJADQAIADAHAFQAHAGADAJQADAIABANIgBBBIAOAAIAAAVIgmAAIAAgLQgHAGgJAEQgIAFgMAAQgJAAgJgDgAgRAHQgGABgEADQgEADgCAEQgDAFAAAFQAAAGACADQACAEADADQAEADAFABIALABIAJgBIAIgDIAHgFIAGgFIAAgdIgaAAQgGAAgGABg");
	this.shape_7.setTransform(462.8,94.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AATBCIAAgWIAHAAIgaghIgYAhIAGAAIAAAWIgsAAIAAgWIALAAIAoguIglgpIgOAAIAAgWIAsAAIAAAWIgFAAIAXAfIAZgfIgHAAIAAgWIAsAAIAAAWIgLAAIglArIAnAsIAKAAIAAAWg");
	this.shape_8.setTransform(449.1,94.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgJgJQgHgJgFgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAFAIAEAJQADAKABAKIABAJIAAAJIheAAIABAKIACAJQAGANAKAGQAKAHAMAAQALAAAJgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgNAAgKgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgFAFQgDAEgDAGQgDAHgBAIIBDAAg");
	this.shape_9.setTransform(434.3,94.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBWQgHgCgEgEQgEgGgDgIQgCgIAAgMIABhIIgVAAIAAgTIAVAAIAAggIAXgKIAAAqIAeAAIAAATIgfAAIAABLQAAAIABAFQACAEAEACQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHACgJAAQgJgBgFgCg");
	this.shape_10.setTransform(416.8,92.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgXBBQgJgFgGgIIgNAAIAAgWIAaAAQAAAFADAEQACAEAEACQAEADAEABIAJABIAKgBIAIgEQAEgCACgDQABgEAAgEQAAgGgDgFQgFgEgKgEIgYgJQgPgEgHgJQgIgIAAgNQAAgIADgHQAEgIAFgFQAGgFAJgDQAIgDALAAQANAAAKAEQAJAEAIAKIAMAAIAAAWIgaAAQAAgGgCgDQgDgEgEgDIgJgDIgIgBIgJABIgIADQgCACgCAEQgCADAAADQAAAHAEAEQAEAEAJADIAYAJQARAFAIAJQAHAJAAANQAAAJgEAHQgDAIgHAFQgGAFgJADQgJADgLAAQgOAAgKgFg");
	this.shape_11.setTransform(405.6,94.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgFhAIgGgEIgDgFIgCgHIACgGIADgFIAGgEIAFgBIAGABIAGAEIADAFIABAGIgBAHIgDAFIgGAEIgGABg");
	this.shape_12.setTransform(395.4,91.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AguBCIAAgWIASAAIAAhWIgSAAIAAgWIAqAAIAAASIAEgIIAHgGIAHgEQAEgBAFAAIAMAAIAMAAIAAAdIgYAAIAAgJQgEAAgEACQgFACgDADQgEADgDAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape_13.setTransform(384.9,94.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBWQgGgCgEgEQgFgGgDgIQgBgIAAgMIAAhIIgVAAIAAgTIAVAAIAAggIAWgKIAAAqIAfAAIAAATIgfAAIgBBLQAAAIADAFQABAEAEACQAEACAFAAIAJgBIAJgDIAGAQIgNAFQgHACgJAAQgJgBgFgCg");
	this.shape_14.setTransform(374.1,92.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgJgJQgHgJgFgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAFAIAEAJQADAKABAKIABAJIAAAJIheAAIABAKIACAJQAGANAKAGQAKAHAMAAQALAAAJgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgNAAgKgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgFAFQgEAEgCAGQgDAHgBAIIBDAAg");
	this.shape_15.setTransform(361.4,94.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AA4BDIAAgWIATAAIAAg7QAAgPgIgIQgHgHgPgBQgJAAgJAFQgIADgGAHIAABLIASAAIAAAWIg8AAIAAgWIASAAIAAg7QAAgPgIgIQgIgHgOgBQgIAAgIAFQgJAEgIAFIAABMIATAAIAAAWIg+AAIAAgWIATAAIAAhWIgTAAIAAgXIArAAIAAAQIAAAAIAJgHIAKgGIALgDIAMgCQAOAAAKAFQAKAGAFALIAKgJIALgGIAMgFQAHgCAGAAQALAAAIADQAJADAGAGQAGAGADAJQAEAKgBAMIAAA+IASAAIAAAWg");
	this.shape_16.setTransform(341.4,94.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_17.setTransform(320.5,94.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBBWQgGgCgFgEQgEgGgCgIQgDgIAAgMIABhIIgVAAIAAgTIAVAAIAAggIAXgKIAAAqIAeAAIAAATIgfAAIAABLQAAAIABAFQACAEAEACQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHACgJAAQgJgBgFgCg");
	this.shape_18.setTransform(308,92.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhFBhIAAgWIATAAIAAiSIgTAAIAAgWIAqAAIAAALQAJgHAJgEQAJgDALAAQANAAALAEQAKAFAIAJQAIAJAEAMQAFAMAAAPQAAAQgFANQgFAMgJAJQgIAKgMAFQgMAFgOAAQgJAAgIgCIgPgFIAAAqIAVAAIAAAWgAgMhIQgIAEgHAGIAABGQAFAFAHADQAIAEALAAQAIAAAHgEQAIgDAGgGQAFgGAEgJQADgJAAgMQAAgLgDgJQgDgIgGgGQgFgGgIgDQgHgEgIAAQgJAAgIAEg");
	this.shape_19.setTransform(295,97.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_20.setTransform(279.4,94.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AANBDIAAgWIATAAIAAg7QgBgPgHgIQgIgHgPgBQgGAAgJAFQgIAEgIAFIAABMIATAAIAAAWIg+AAIAAgWIATAAIAAhWIgTAAIAAgXIAqAAIAAAQIABAAIAJgHIAKgGIAKgDIALgCQAKAAAJADQAIADAHAGQAFAGAEAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_21.setTransform(257.5,94.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AggBCQgJgDgGgFQgFgGgDgGQgDgIAAgIQAAgHACgHQADgGAEgGQAEgEAFgCIAMgGIAMgCIAMgBIAOABIAMABIAAgLQAAgHgDgFQgBgFgEgEQgEgDgEgBQgGgCgFAAIgMABIgKACIgJADIgHAEIgHgRIAKgGIAMgEIAMgDIANgBQAKAAAJADQAKADAGAFQAHAGADAJQAEAIgBANIAABBIAPAAIAAAVIgmAAIAAgLQgIAGgJAEQgIAFgLAAQgLAAgHgDgAgRAHQgGABgEADQgEADgDAEQgCAFAAAFQAAAGACADQACAEAEADQADADAFABIAKABIAKgBIAIgDIAIgFIAGgFIAAgdIgbAAQgGAAgGABg");
	this.shape_22.setTransform(241.5,94.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgNBfIgQgDIgNgGQgHgDgHgFIAOgTIAIAGIALAFIALADIAMABQAJAAAHgCQAHgCAFgFQAEgFACgJQADgJAAgNIAAgCQgGAHgJADQgIAEgLAAQgNAAgMgEQgLgFgIgJQgJgJgFgNQgEgMAAgRQAAgPAEgMQAFgNAIgJQAJgJALgEQAMgFAOAAQAJAAAJACQAHACAIAFIAAgGIAXAAIAAB9QAAAfgOAQQgPAQgfAAgAgKhHQgHADgGAGQgFAGgDAIQgEAJAAALQAAAMADAJQAEAJAFAGQAFAGAIADQAHAEAIAAIALgCIAJgCIAHgFIAFgFIAAhHQgGgGgJgCQgIgDgKAAQgHAAgHAEg");
	this.shape_23.setTransform(221,97.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AANBDIAAgWIATAAIAAg7QAAgPgJgIQgHgHgOgBQgHAAgJAFQgIAEgIAFIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhWIgSAAIAAgXIAqAAIAAAQIABAAIAJgHIAJgGIALgDIALgCQAKAAAJADQAJADAFAGQAHAGADAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_24.setTransform(205.1,94.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgGhAIgFgEIgEgFIAAgHIAAgGIAEgFIAFgEIAGgBIAHABIAEAEIAEAFIACAGIgCAHIgEAFIgEAEIgHABg");
	this.shape_25.setTransform(192.5,91.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAtBjIg1g7IgRAAIAAAlIAKAAIAAAWIg4AAIAAgWIAWAAIAAiZIgXAAIAAgWIAvAAIAAAWIAABhIAWAAIAfgfIgIAAIAAgWIAyAAIAAAWIgRAAIgoAoIAsAvIAQAAIAAAWg");
	this.shape_26.setTransform(180.3,91.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_27.setTransform(164,94.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_28.setTransform(148.4,94.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhHBgIAAgWIATAAIAAiTIgTAAIAAgWIBVAAQAMAAALAEQAKAFAIAHQAHAIAEAKQAFAKAAAMQAAAMgHALQgGAKgNAGIALAGQAFAFAEAFQADAFACAGQACAGAAAGQAAAMgFAKQgEALgIAIQgHAHgKAFQgKAEgMAAgAgbBKIArAAQAGAAAGgDQAFgDAEgFQADgEADgHQACgGAAgGQAAgGgCgFQgDgFgDgEQgEgEgFgDQgGgCgGAAIgrAAgAgbgKIAqAAQAGAAAGgDQAEgCAFgEQADgEACgGQADgFAAgGQAAgGgDgGQgCgGgDgFQgFgEgEgDQgGgDgGAAIgqAAg");
	this.shape_29.setTransform(132.6,91.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(-142.3,74,971.3,35.4), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAPIgGgDIgDgGIgBgGIABgFIADgGIAGgDIAGgBIAFABIAGADIADAGIABAFIgBAGIgDAGIgGADIgFABg");
	this.shape.setTransform(444.2,94.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgfBgQgLgFgJgJQgIgJgFgNQgFgNAAgRQAAgPAFgMQAFgMAIgJQAIgJAMgEQAMgFAOAAQAJAAAIACQAIACAHAFIAAgyIgSAAIAAgWIAqAAIAACuIATAAIAAAWIgrAAIAAgLQgGAHgJAEQgIADgKAAQgNAAgMgEgAgTgMQgIADgFAGQgGAFgDAIQgDAJAAALQAAAMADAJQADAKAFAGQAGAGAIADQAHAEAJAAQAKAAAHgDQAHgEAGgGIAAhIQgGgGgJgCQgIgDgIAAQgIAAgHAEg");
	this.shape_1.setTransform(433.4,86.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AguBCIAAgWIASAAIAAhWIgSAAIAAgWIAqAAIAAASIAEgIIAHgGIAHgEQAEgBAFAAIAMAAIAMAAIAAAdIgYAAIAAgJQgEAAgEACQgFACgDADQgEADgDAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape_2.setTransform(419.1,89.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AghBCQgHgDgGgFQgGgFgDgIQgEgHAAgHQABgJACgGQACgHAEgEQAFgFAFgDIAMgFIAMgDIAMAAIAOAAIALACIABgLQAAgHgDgFQgCgFgDgDQgDgEgGgCQgFgBgGAAIgKABIgLACIgIADIgIADIgHgQIAKgFIAMgFIANgDIAMgBQALAAAJADQAIADAHAFQAGAGAEAJQADAJABAMIgBBAIAOAAIAAAXIgmAAIAAgNQgHAHgJAFQgIAEgMAAQgKAAgIgDgAgRAHQgGABgEAEQgEACgDAEQgCAFAAAGQAAAFACAEQACAEAEACQADACAFACIALACIAJgCIAIgDIAIgEIAFgGIAAgdIgaAAQgGAAgGABg");
	this.shape_3.setTransform(405.8,89.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AANBjIAAgWIASAAIAAg8QAAgPgIgHQgIgIgOAAQgIAAgHAEQgJAEgHAFIAABNIASAAIAAAWIg+AAIAAgWIAUAAIAAiZIgSAAIAAgWIAqAAIAABRIAAAAIAJgHIAJgFIALgEIAKgBQALAAAJADQAIADAGAGQAFAGAEAJQADAIAAANIAAA/IAUAAIAAAWg");
	this.shape_4.setTransform(390.5,86.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXBBQgKgFgFgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQADADAGABIAIABIAKgBIAIgEQADgCADgDQACgEAAgEQAAgGgFgFQgDgEgKgEIgYgJQgQgEgIgJQgHgIAAgNQAAgIADgHQAEgIAFgFQAGgFAJgDQAIgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgDgDQgCgEgEgDIgIgDIgJgBIgJABIgHADQgEACgCAEQgBADAAADQAAAHAEAEQAEAEAJADIAZAJQAQAFAIAJQAHAJAAANQAAAJgEAHQgDAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_5.setTransform(369.8,89.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIATAAIAAhWIgUAAIAAgWIAqAAIAABsIAUAAIAAAWgAgGhAIgFgEIgEgFIgBgHIABgGIAEgFIAFgEIAGgBIAHABIAEAEIAEAFIACAGIgCAHIgEAFIgEAEIgHABg");
	this.shape_6.setTransform(359.5,86.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNBfIgQgDIgNgGQgHgDgHgFIAOgTIAIAGIALAFIALADIAMABQAJAAAHgCQAHgCAFgFQAEgFACgJQADgJAAgNIAAgCQgGAHgJADQgIAEgLAAQgNAAgMgEQgLgFgIgJQgJgJgFgNQgEgMAAgRQAAgPAEgMQAFgNAIgJQAJgJALgEQAMgFAOAAQAJAAAJACQAHACAIAFIAAgGIAXAAIAAB9QAAAfgOAQQgPAQgfAAgAgKhHQgHADgGAGQgFAGgDAIQgEAJAAALQAAAMADAJQAEAJAFAGQAFAGAIADQAHAEAIAAIALgCIAJgCIAHgFIAFgFIAAhHQgGgGgJgCQgIgDgKAAQgHAAgHAEg");
	this.shape_7.setTransform(341.6,92.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AANBDIAAgWIATAAIAAg7QAAgPgJgHQgHgIgOAAQgHAAgJADQgIAEgIAGIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIABAAIAJgHIAJgFIALgFIALgBQAKAAAJADQAJADAFAGQAHAGADAJQADAJAAANIAAA+IASAAIAAAWg");
	this.shape_8.setTransform(325.7,89.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgGhAIgFgEIgEgFIgBgHIABgGIAEgFIAFgEIAGgBIAHABIAEAEIAEAFIACAGIgCAHIgEAFIgEAEIgHABg");
	this.shape_9.setTransform(313.1,86.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBXQgGgDgFgEQgEgFgCgIQgDgJAAgNIABhHIgVAAIAAgTIAVAAIAAgfIAWgMIAAArIAfAAIAAATIgfAAIAABLQAAAIABAEQACAFAEADQAEABAFAAIAKAAIAJgEIAFAQIgNAFQgHABgJAAQgJAAgFgBg");
	this.shape_10.setTransform(304,87.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QABgPgJgHQgHgIgOAAQgIAAgIADQgJAEgHAGIAABMIASAAIAAAWIg9AAIAAgWIATAAIAAhXIgTAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgFIALgFIALgBQALAAAIADQAIADAHAGQAGAGADAJQADAJAAANIAAA+IASAAIAAAWg");
	this.shape_11.setTransform(290.5,89.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIheAAIACAKIACAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgMAAgMgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgEAFQgFAEgDAGQgCAHgBAIIBDAAg");
	this.shape_12.setTransform(274,89.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgvBCIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAAASIAFgIIAGgGIAIgEQAEgBAFAAIANAAIAMAAIAAAdIgZAAIAAgJQgEAAgFACQgEACgEADQgEADgCAFQgCAFgCAHIAAA+IAWAAIAAAWg");
	this.shape_13.setTransform(260.8,89.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AggBCQgIgDgHgFQgFgFgEgIQgCgHAAgHQgBgJADgGQACgHAFgEQAEgFAFgDIALgFIANgDIAMAAIAPAAIALACIAAgLQAAgHgCgFQgDgFgDgDQgEgEgFgCQgFgBgFAAIgMABIgKACIgJADIgGADIgIgQIAKgFIAMgFIANgDIAMgBQALAAAIADQAKADAGAFQAGAGAEAJQADAJAAAMIAABAIAPAAIAAAXIgmAAIAAgNQgIAHgJAFQgIAEgLAAQgLAAgHgDgAgRAHQgGABgEAEQgEACgCAEQgDAFAAAGQAAAFACAEQACAEADACQAEACAFACIAKACIAKgCIAIgDIAHgEIAHgGIAAgdIgbAAQgHAAgFABg");
	this.shape_14.setTransform(247.4,89.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhEBgIAAgWIATAAIAAiTIgTAAIAAgWIBNAAQANAAALADQALAEAIAGQAIAHAEAJQAFAKAAANQAAAKgFAKQgEAJgIAHQgIAHgLADQgLAEgNAAIghAAIAABDIATAAIAAAWgAgYgNIAhAAQAHAAAHgCQAGgCAEgDQAEgEADgGQACgGAAgHQAAgOgIgIQgJgIgTAAIgeAAg");
	this.shape_15.setTransform(233.1,86.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(222.4,69,226.8,35.4), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.volcanoman();
	this.instance.parent = this;
	this.instance.setTransform(-537,244,1.181,1.181);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-537,244,337.9,320.2), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgRBiIgFgEIgEgFIgBgHIABgGIAEgFIAFgEIAGgBIAHABIAEAEIAEAFIABAGIgBAHIgEAFIgEAEIgHABgAgVA3IABgWQABgKACgHQADgIAEgGIALgLIANgKIAJgIQAEgEADgEQACgFAAgHQgBgFgCgGQgCgFgEgEQgEgEgFgDQgFgCgGAAQgKAAgGADQgHAEgFAFQgEAFgBAFIgCAKIgXgCQABgKAFgKQAEgJAHgHQAIgIAKgEQALgEAMAAQAMAAAKAEQAKAEAHAHQAGAHAEAJQADAKAAAKQAAANgGAKQgHALgNAKIgNAJQgJAHgCAKQgEAJgBAHIAAAQg");
	this.shape.setTransform(364.3,111.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AguBCIAAgWIASAAIAAhWIgSAAIAAgWIApAAIAAASIAFgIIAHgGIAHgEQAEgBAFAAIANAAIALAAIAAAdIgYAAIAAgJQgEAAgEACQgFACgDADQgFADgCAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape_1.setTransform(351.1,114.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAGAIAEAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_2.setTransform(337.2,114.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXBBQgKgFgFgIIgNAAIAAgWIAaAAQAAAFADAEQACAEAEACQADADAFABIAJABIAKgBIAIgEQADgCACgDQACgEAAgEQAAgGgDgFQgFgEgKgEIgYgJQgPgEgHgJQgIgIAAgNQAAgIADgHQAEgIAFgFQAGgFAIgDQAJgDALAAQANAAAKAEQAJAEAIAKIAMAAIAAAWIgaAAQAAgGgCgDQgDgEgEgDIgJgDIgIgBIgJABIgIADQgDACgBAEQgCADAAADQAAAHAEAEQAEAEAKADIAXAJQARAFAHAJQAIAJAAANQAAAJgEAHQgDAIgHAFQgGAFgJADQgJADgLAAQgOAAgKgFg");
	this.shape_3.setTransform(323.8,114.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgSAAIAAgWIAqAAIAABsIAUAAIAAAWgAgFhAIgGgEIgDgFIgBgHIABgGIADgFIAGgEIAFgBIAGABIAGAEIADAFIABAGIgBAHIgDAFIgGAEIgGABg");
	this.shape_4.setTransform(313.6,111.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AghBCQgHgDgGgFQgGgGgDgGQgEgHAAgIQAAgJADgGQACgHAEgFQAEgEAGgDIAMgEIAMgEIAMAAIAOAAIALACIABgLQAAgHgDgFQgCgFgDgEQgDgDgFgCQgGgBgGAAIgLABIgKACIgIADIgIADIgHgQIAKgFIAMgFIAMgDIANgBQAKAAAKADQAIACAHAGQAGAGAEAJQADAJAAAMIAABAIAPAAIAAAXIgnAAIAAgMQgHAGgJAFQgIAEgMAAQgKAAgIgDgAgRAHQgGACgEADQgEACgDAFQgCAEAAAGQAAAFACAEQACAEAEACQADACAFACIALABIAJgBIAIgDIAIgFIAFgFIAAgeIgaAAQgHABgFABg");
	this.shape_5.setTransform(301.9,114.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgvBCIAAgWIATAAIAAhWIgTAAIAAgWIArAAIAAASIAEgIIAGgGIAIgEQAEgBAFAAIAMAAIANAAIAAAdIgZAAIAAgJQgEAAgFACQgEACgEADQgEADgCAFQgCAFgCAHIAAA+IAWAAIAAAWg");
	this.shape_6.setTransform(288.9,114.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgfBgQgLgFgJgJQgIgJgFgNQgFgNAAgRQAAgPAFgMQAFgMAIgJQAIgJAMgEQAMgFAOAAQAJAAAIACQAIACAHAFIAAgyIgSAAIAAgWIAqAAIAACuIATAAIAAAWIgrAAIAAgLQgGAHgJAEQgIADgKAAQgNAAgMgEgAgTgMQgIADgFAGQgGAFgDAIQgDAJAAALQAAAMADAJQADAKAFAGQAGAGAIADQAHAEAJAAQAKAAAHgDQAHgEAGgGIAAhIQgGgGgJgCQgIgDgIAAQgIAAgHAEg");
	this.shape_7.setTransform(275,111.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AANBDIAAgWIATAAIAAg7QAAgPgJgHQgHgJgOABQgHAAgJADQgIAEgIAGIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIABAAIAJgHIAJgGIALgDIALgCQAKAAAJADQAJADAFAGQAHAGADAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_8.setTransform(258.2,114.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgaBAQgIgDgGgGQgGgGgDgKQgDgJAAgMIAAg+IgSAAIAAgWIArAAIAABRQAAAPAHAIQAHAHANABQAHAAAIgEQAJgCAHgFIAAhPIgRAAIAAgWIAqAAIAABsIAPAAIAAAXIgnAAIAAgMQgJAGgKAEQgLAEgKAAQgKAAgIgDg");
	this.shape_9.setTransform(240.3,115);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgvBjIAAgWIAUAAIAAhaIgWAAIAAgTIAWAAIAAgUQABgMADgIQADgJAFgFQAGgGAHgDQAIgDAJAAIAMABIAKACIAHACIAFACIgHARIgKgDQgGgCgIAAQgLAAgFAHQgGAGAAANIAAAVIAeAAIAAATIgeAAIAABaIAUAAIAAAWg");
	this.shape_10.setTransform(229.1,111.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgeBjIAAgWIATAAIAAiZIgTAAIAAgWIAqAAIAACvIATAAIAAAWg");
	this.shape_11.setTransform(213.2,111.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_12.setTransform(201,114.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_13.setTransform(185.5,114.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAMBjIAAgWIASAAIAAg8QAAgPgHgHQgIgIgOAAQgHAAgJAEQgIAEgIAFIAABNIATAAIAAAWIg+AAIAAgWIAUAAIAAiZIgSAAIAAgWIApAAIAABRIABAAIAIgHIAKgFIALgEIAKgBQALAAAJADQAIADAGAGQAFAGAEAJQADAIAAANIAAA/IAUAAIAAAWg");
	this.shape_14.setTransform(169.4,111.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVBAQgMgEgIgKQgJgJgEgNQgFgNAAgPQAAgOAFgNQAFgNAIgJQAKgKALgEQAMgFALgBQANAAAMAFQALAEAIAIIANAAIAAAXIgYAAQgFgKgJgFQgHgEgMAAQgGAAgIAEQgHADgGAGQgFAHgDAJQgDAJAAAKQAAALADAJQADAJAFAGQAGAGAHAEQAIADAGAAQANAAAJgFQAJgHAFgLIAUAKQgEAHgGAHQgFAGgHAFQgHAFgJADQgIACgKAAQgMAAgMgGg");
	this.shape_15.setTransform(153.7,114.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgXBBQgKgFgFgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQAEADAFABIAJABIAJgBIAIgEQAEgCABgDQADgEAAgEQAAgGgFgFQgEgEgJgEIgYgJQgQgEgIgJQgHgIAAgNQAAgIAEgHQACgIAHgFQAFgFAIgDQAJgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgDgDQgCgEgEgDIgIgDIgJgBIgJABIgHADQgDACgDAEQgBADAAADQAAAHAEAEQAEAEAKADIAYAJQAQAFAHAJQAIAJAAANQAAAJgDAHQgEAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_16.setTransform(140.2,114.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_17.setTransform(120.4,114.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAMBjIAAgWIASAAIAAg8QAAgPgHgHQgIgIgOAAQgIAAgHAEQgJAEgIAFIAABNIATAAIAAAWIg+AAIAAgWIAUAAIAAiZIgSAAIAAgWIApAAIAABRIABAAIAIgHIAKgFIALgEIAKgBQALAAAJADQAIADAGAGQAGAGADAJQADAIAAANIAAA/IAUAAIAAAWg");
	this.shape_18.setTransform(105,111.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgBBXQgGgCgEgGQgFgFgCgHQgCgJAAgNIAAhHIgVAAIAAgTIAVAAIAAgfIAWgLIAAAqIAfAAIAAATIgfAAIgBBLQAAAIACAEQACAGAEABQAEACAFAAIAJgBIAJgDIAGAQIgNAFQgHACgJgBQgJAAgFgBg");
	this.shape_19.setTransform(91.4,112.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AguBCIAAgWIASAAIAAhWIgSAAIAAgWIApAAIAAASIAFgIIAHgGIAHgEQAEgBAFAAIAMAAIAMAAIAAAdIgYAAIAAgJQgEAAgEACQgFACgDADQgFADgCAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape_20.setTransform(74.8,114.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_21.setTransform(60.9,114.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgvBjIAAgWIAUAAIAAhaIgWAAIAAgTIAWAAIAAgUQAAgMADgIQADgJAGgFQAFgGAJgDQAGgDAKAAIAMABIAKACIAHACIAFACIgGARIgLgDQgHgCgHAAQgKAAgGAHQgFAGgBANIAAAVIAeAAIAAATIgeAAIAABaIAUAAIAAAWg");
	this.shape_22.setTransform(49.8,111.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgXBBQgKgFgFgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQADADAGABIAIABIAKgBIAIgEQADgCADgDQACgEAAgEQAAgGgFgFQgDgEgKgEIgZgJQgPgEgIgJQgHgIAAgNQAAgIADgHQAEgIAFgFQAGgFAJgDQAIgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgDgDQgCgEgEgDIgIgDIgJgBIgJABIgHADQgEACgCAEQgBADAAADQAAAHAEAEQAEAEAJADIAZAJQAQAFAIAJQAHAJAAANQAAAJgEAHQgDAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_23.setTransform(317.1,85.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAGAIAEAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_24.setTransform(303,85.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAtBjIg1g7IgRAAIAAAlIAKAAIAAAWIg4AAIAAgWIAWAAIAAiZIgXAAIAAgWIAvAAIAAAWIAABhIAWAAIAfgfIgIAAIAAgWIAyAAIAAAWIgRAAIgoAoIAsAvIAQAAIAAAWg");
	this.shape_25.setTransform(288.1,82.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AghBCQgHgDgGgFQgGgGgDgGQgDgIgBgIQAAgHADgHQACgGAEgGQAFgEAFgCIAMgGIAMgCIAMgBIAOABIALABIABgLQAAgHgDgFQgCgFgDgEQgDgDgFgBQgGgCgGAAIgLABIgKACIgJADIgHAEIgHgRIAKgGIAMgEIAMgDIANgBQAKAAAKADQAJADAGAFQAHAGADAJQADAIAAANIAABBIAPAAIAAAVIgnAAIAAgLQgHAGgJAEQgIAFgMAAQgJAAgJgDgAgRAHQgGABgEADQgEADgDAEQgCAFAAAFQAAAGACADQACAEAEADQADADAFABIALABIAJgBIAIgDIAIgFIAFgFIAAgdIgaAAQgHAAgFABg");
	this.shape_26.setTransform(272.3,85.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgVBBQgLgGgJgJQgJgJgEgNQgFgNAAgPQAAgOAFgNQAFgNAJgJQAIgJAMgGQAMgEAMAAQAMAAALADQAMAFAHAJIAOAAIAAAVIgYAAQgFgJgIgFQgJgEgKAAQgHAAgIADQgHAEgGAGQgFAHgDAJQgDAJAAAKQAAALADAJQADAJAFAGQAGAGAIAEQAGADAIAAQAMAAAJgGQAJgFAFgMIAUAJQgEAJgFAGQgGAGgHAFQgIAFgHADQgJABgJAAQgNAAgMgEg");
	this.shape_27.setTransform(258.5,85.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AhFBhIAAgWIATAAIAAiSIgTAAIAAgWIAqAAIAAALQAJgHAJgEQAJgDALAAQANAAALAEQAKAFAIAJQAIAJAEAMQAFAMAAAPQAAAQgFANQgFAMgJAJQgIAKgMAFQgMAFgOAAQgJAAgIgCIgPgFIAAAqIAVAAIAAAWgAgMhIQgIAEgHAGIAABGQAFAFAHADQAIAEALAAQAIAAAHgEQAIgDAGgGQAFgGAEgJQADgJAAgMQAAgLgDgJQgDgIgGgGQgFgGgIgDQgHgEgIAAQgJAAgIAEg");
	this.shape_28.setTransform(243.2,88.3);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgaBAQgIgDgGgGQgGgGgDgKQgDgIAAgOIAAg9IgSAAIAAgWIArAAIAABRQAAAPAHAHQAHAJANgBQAHAAAIgCQAJgDAHgFIAAhPIgRAAIAAgWIAqAAIAABtIAPAAIAAAVIgnAAIAAgLQgJAGgKAEQgLAEgKAAQgKAAgIgDg");
	this.shape_29.setTransform(226.2,85.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgVBBQgMgGgIgJQgIgJgFgNQgFgNAAgPQAAgOAFgNQAFgNAIgJQAKgJALgGQALgEAMAAQANAAAMADQAKAFAJAJIANAAIAAAVIgYAAQgFgJgJgFQgHgEgMAAQgGAAgIADQgHAEgGAGQgFAHgDAJQgDAJAAAKQAAALADAJQADAJAFAGQAGAGAIAEQAHADAGAAQANAAAJgGQAJgFAFgMIAUAJQgEAJgGAGQgFAGgHAFQgHAFgJADQgIABgKAAQgMAAgMgEg");
	this.shape_30.setTransform(211.4,85.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgZBiIAshJIgMAEIgKAAQgLAAgMgEQgMgEgJgIQgIgIgGgLQgFgLAAgMQAAgQAFgNQAGgNAJgIQAJgJANgEQAMgFAMAAQAOAAAMAFQAMAEAJAJQAJAIAGAMQAFAMAAAPQAAALgEALIgLAWIgwBWgAgQhIQgIADgFAGQgGAFgEAIQgEAIAAAJQAAALAEAIQAEAIAHAFQAGAEAIADQAIADAHAAQALAAAHgDQAGgDAGgEQAGgFADgIQADgIAAgLQAAgKgDgHQgDgIgGgGQgGgFgIgDQgIgDgJAAQgIAAgIADg");
	this.shape_31.setTransform(190.5,82.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgWBfQgKgDgIgFQgHgGgHgHQgFgIgEgIIAVgLQACAHAEAFQAEAGAFAEQAGAEAHACQAFACAIAAQAIAAAIgDQAIgEAFgFQAHgGACgIQAEgIAAgJQAAgJgEgHQgCgIgHgGQgFgEgIgEQgIgDgIAAQgKAAgJAEQgJADgFAFIgTgDIAAhjIBrAAIAAAVIhWAAIAAA6QAIgFAHgCQAHgDAKAAQANAAAMAFQAMAFAIAJQAJAIAFALQAFALgBANQABANgFAMQgEALgKAJQgIAJgMAFQgMAFgOAAQgLAAgKgDg");
	this.shape_32.setTransform(175.3,82.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgfBgQgLgFgJgJQgIgJgFgNQgFgNAAgRQAAgPAFgMQAFgMAIgJQAIgJAMgEQAMgFAOAAQAJAAAIACQAIACAHAFIAAgyIgSAAIAAgWIAqAAIAACuIATAAIAAAWIgrAAIAAgLQgGAHgJAEQgIADgKAAQgNAAgMgEgAgTgMQgIADgFAGQgGAFgDAIQgDAJAAALQAAAMADAJQADAKAFAGQAGAGAIADQAHAEAJAAQAKAAAHgDQAHgEAGgGIAAhIQgGgGgJgCQgIgDgIAAQgIAAgHAEg");
	this.shape_33.setTransform(154.4,82.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgJgJQgHgJgFgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAFAIAEAJQADAKABAKIABAJIAAAJIhdAAIABAKIABAJQAGANAKAGQAKAHAMAAQALAAAJgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgMgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgFAFQgDAEgEAGQgCAHgBAIIBDAAg");
	this.shape_34.setTransform(138.5,85.4);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_35.setTransform(123.6,85.4);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QAAgPgIgIQgHgHgOgBQgIAAgIAFQgJAEgHAFIAABMIASAAIAAAWIg9AAIAAgWIATAAIAAhWIgTAAIAAgXIAqAAIAAAQIAAAAIAJgHIAKgGIALgDIALgCQAKAAAJADQAIADAHAGQAFAGAEAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_36.setTransform(107.9,85.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgaBAQgIgDgGgGQgGgGgDgKQgDgIAAgOIAAg9IgSAAIAAgWIArAAIAABRQAAAPAHAHQAHAJANgBQAHAAAIgCQAJgDAHgFIAAhPIgRAAIAAgWIAqAAIAABtIAPAAIAAAVIgnAAIAAgLQgJAGgKAEQgLAEgKAAQgKAAgIgDg");
	this.shape_37.setTransform(84.3,85.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_38.setTransform(68.6,85.4);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgfBgIAAgWIARAAIAAhDIgzhQIgPAAIAAgWIA/AAIAAAWIgTAAIAkA+IAmg+IgUAAIAAgWIA/AAIAAAWIgRAAIg2BRIAABCIAUAAIAAAWg");
	this.shape_39.setTransform(52.5,82.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(41.8,65,331.2,64.8), null);


(lib.shaker = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHCDIgHgFIgFgIIgCgIIACgIIAFgHIAHgFIAIgBIAIABIAGAFIAFAHIABAIIgBAIIgFAIIgGAFIgIABgAgOA+IgHjBIAqAAIgGDBg");
	this.shape.setTransform(164.8,21.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgWCAIgHgFIgEgHIgDgIIADgIIAEgHIAHgFIAJgCIAIACIAGAFIAEAHIACAIIgCAIIgEAHIgGAFIgIACgAgcBIIABgdQABgMAEgKQADgKAGgIIAQgPIAQgNIAMgKQAFgGADgGQACgGAAgIQAAgIgCgHQgDgHgFgFQgFgGgHgDQgIgDgHAAQgNAAgJAEQgIAFgGAHQgFAGgDAIIgCAMIgegCQACgOAFgMQAGgNAKgJQAKgKAOgFQAOgGAPAAQARAAAMAGQANAFAJAJQAIAJAFANQAFAMAAANQAAARgJAOQgJAOgQAMIgSANQgKAJgFANQgEAMAAAJIgBAVg");
	this.shape_1.setTransform(150.8,21.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AARBXIAAgcIAYAAIAAhOQAAgTgKgKQgKgLgTAAQgKAAgLAFQgLAGgKAHIAABkIAZAAIAAAcIhRAAIAAgcIAYAAIAAhyIgYAAIAAgcIA3AAIAAAUIAMgKIANgHIAOgFIAPgBQAOAAALADQALAEAIAIQAIAHAEANQAEAMAAARIAABRIAYAAIAAAcg");
	this.shape_2.setTransform(130.2,25.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbBVQgPgGgMgMQgKgLgGgRQgGgRAAgWQAAgSAFgRQAFgQALgMQAKgMAPgIQAPgHATAAQATAAANAGQANAGAJAKQAHAJAFANQAEAMACANIABANIAAAMIh7AAIABANIADAMQAHAQANAJQANAIARAAQANAAANgEQAMgDAPgIIAMAVQgRALgRAGQgRAGgSAAQgRAAgOgGgAAsgTIgDgSQgDgIgEgGQgFgGgIgEQgIgDgMAAQgJAAgIADQgIADgGAGQgGAGgDAIQgDAIgCALIBYAAg");
	this.shape_3.setTransform(108.6,26.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AARCBIAAgcIAXAAIAAhPQAAgUgKgJQgKgKgTAAQgJAAgLAFQgLAFgKAHIAABlIAZAAIAAAcIhSAAIAAgcIAaAAIAAjJIgXAAIAAgcIA2AAIAABpIABAAIALgIIAMgIIAOgEIAOgCQAOAAALAEQALAEAIAIQAHAHAFANQAEALAAAQIAABTIAaAAIAAAcg");
	this.shape_4.setTransform(88.4,21.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAnBXIgniIIgmCIIgdAAIgviRIgOAAIAAgcIA2AAIAAAcIgIAAIAeBtIApiJIAZAAIAoCJIAfhtIgKAAIAAgcIA2AAIAAAcIgOAAIgwCRg");
	this.shape_5.setTransform(63,26.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag1B9IAAgdIAVAAIASguIg5iRIgOAAIAAgdIBBAAIAAAdIgUAAIAoBtIAphtIgUAAIAAgdIBBAAIAAAdIgSAAIhLC/IAWAAIAAAdg");
	this.shape_6.setTransform(31.9,30);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgQB/QgLgEgIgGIAAALIgeAAIAAjlIgZAAIAAgcIA3AAIAABkQALgIANgFQAMgFAOAAQARAAAOAGQAOAHALALQAKALAFAQQAFAQAAATQABAVgHARQgGAQgLAMQgLAMgPAHQgQAGgSABQgMgBgMgDgAgQgPQgLAFgIAJIAABbQAFAGALAEQAKAEAPAAQAKAAAKgEQAKgEAIgIQAHgIAEgMQAFgMAAgQQAAgPgFgLQgEgLgGgHQgIgIgKgEQgKgEgKAAQgLAAgMAFg");
	this.shape_7.setTransform(12.1,21.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.shaker, new cjs.Rectangle(0,0,172.7,45.1), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AghA5QgHgDgEgEIgFgGIgEgJIgBgNQAAgGACgKIAKgtIgPAAIAEgTIAmAAIgNA6QgFAVAEAJQAFAKAOAAQAHAAAEgCQAFgCAEgEIAHgJIAOg+IgPAAIAFgTIAlAAIgWBgIARAAIgEATIgnAAIADgMIgIAGIgHAFIgJACIgIABQgHAAgHgCg");
	this.shape.setTransform(118.3,27);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgbA5QgKgEgHgIQgHgHgEgJQgEgKAAgLQAAgIACgKQACgIAFgIQAEgIAGgGQAHgHAHgEQAIgEAIgCQAJgDAIAAQALAAAKAEQAKAEAHAHQAHAHAEAKQAEAJAAALQAAAJgCAJQgCAJgFAHQgEAIgGAHQgHAGgHAEQgIAFgIADQgJACgIAAQgMAAgJgEgAgJglQgIADgGAHQgGAGgDAJQgEAJAAAJQAAAIACAHQADAGAEAFQAEAEAGADQAFACAHAAQAHAAAIgDQAIgEAGgHQAGgGAEgJQADgJAAgJQAAgIgCgGQgDgHgEgEQgEgEgGgDQgGgDgGABQgIgBgHAEg");
	this.shape_1.setTransform(104.1,26.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhDBUIAFgTIALAAIAUghIgMhgIgLAAIAEgTIArAAIgFATIgJAAIAHBHIAthHIgJAAIAEgTIAqAAIgEATIgKAAIhSCBIAMAAIgGATg");
	this.shape_2.setTransform(91,29.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgwA6IAWhfIgWAAIAFgTIArAAIgDAPIAFgGIAIgGIAIgDIAJgBIAHAAIAGAAIAJABIgHAgIgXAAIADgOQgLAAgHAFQgHAGgFAJIgNA5IATAAIgEATg");
	this.shape_3.setTransform(73.9,26.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AghA5QgIgEgGgGQgGgHgEgIQgEgJAAgKQAAgPAGgOQAGgNAKgKQAJgKANgFQANgFAOAAQAIAAAIACQAHADAFAEIABgGIAXAAIgXBfIASAAIgEATIgoAAIABgIQgHAFgHADQgHACgIAAQgKAAgIgDgAgIglQgIAEgHAGQgGAHgEAKQgEAJAAAMQAAAHACAGQACAFADAEQAEAEAFACQAFACAGAAIAIgBIAIgDIAHgDIAGgEIAOg9QgCgEgHgDQgGgCgKAAQgIAAgIADg");
	this.shape_4.setTransform(60,26.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZA6QgJgEgHgHQgHgHgEgJQgEgKAAgNQAAgNAFgNQAFgNAJgJQAJgJANgGQAMgFANAAQALAAAJADQAIAEAGAGQAHAGADAIQADAIAAAJIgBALIgBAJIhYAAIAAACIgBADQAAAHADAGQACAGAEAEQAEAFAGACQAFADAHAAQAIAAAIgEQAIgEAGgHIAQAMIgJAJQgFAFgGACQgHADgHACIgOABQgKAAgKgDgAAjgNQAAgHgCgFQgCgGgDgDQgEgEgFgCQgGgBgGAAQgHAAgEACQgGACgFAEQgFADgEAGIgGALIBBAAIAAAAg");
	this.shape_5.setTransform(46.5,26.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAQA7IARhGQADgOgFgGQgFgHgNAAQgIAAgHADQgIAFgHAGIgTBTIgXAAIAWhgIgVAAIAEgTIArAAIgCAMQAIgHAJgDQAJgEAKAAQAJAAAIADQAGADAFAFQAEAGACAHQABAJgCALIgNA2IARAAIgEATg");
	this.shape_6.setTransform(32,26.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgZA6QgJgEgHgHQgHgHgEgJQgEgKAAgNQAAgNAFgNQAFgNAJgJQAJgJANgGQAMgFANAAQALAAAJADQAIAEAGAGQAHAGADAIQADAIAAAJIgBALIgBAJIhYAAIAAACIgBADQAAAHADAGQACAGAEAEQAEAFAGACQAFADAHAAQAIAAAIgEQAIgEAGgHIAQAMIgJAJQgFAFgGACQgHADgHACIgOABQgKAAgKgDgAAjgNQAAgHgCgFQgCgGgDgDQgEgEgFgCQgGgBgGAAQgHAAgEACQgGACgFAEQgFADgEAGIgGALIBBAAIAAAAg");
	this.shape_7.setTransform(13,26.9);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AARA7IAQhGQADgOgFgGQgFgHgNAAQgIAAgHADQgIAFgHAGIgTBTIgXAAIAXhgIgXAAIAFgTIArAAIgCAMQAIgHAIgDQAKgEAKAAQAJAAAHADQAIADAEAFQAEAGACAHQACAJgDALIgMA2IAQAAIgEATg");
	this.shape_8.setTransform(-1.6,26.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgbA5QgKgEgHgIQgHgHgEgJQgEgKAAgLQAAgIACgKQACgIAFgIQAEgIAGgGQAHgHAHgEQAIgEAIgCQAJgDAIAAQALAAAKAEQAKAEAHAHQAHAHAEAKQAEAJAAALQAAAJgCAJQgCAJgFAHQgEAIgGAHQgHAGgHAEQgIAFgIADQgJACgIAAQgMAAgJgEgAgJglQgIADgGAHQgGAGgDAJQgEAJAAAJQAAAIACAHQADAGAEAFQAEAEAGADQAFACAHAAQAHAAAIgDQAIgEAGgHQAGgGAEgJQADgJAAgJQAAgIgCgGQgDgHgEgEQgEgEgGgDQgGgDgGABQgIgBgHAEg");
	this.shape_9.setTransform(-16.1,26.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgnBUQgIgEgHgGQgGgHgEgJQgDgJAAgLQAAgPAFgNQAGgMAJgKQAJgKANgFQANgFANAAQAJAAAHACQAIADAGAEIAKgtIgTAAIAEgTIAqAAIgkCaIAUAAIgFATIgpAAIABgIQgGAFgGACQgHADgIAAQgKAAgJgEgAgQgJQgIADgGAGQgHAGgDAKQgEAJAAALQAAAIACAGQACAGAEAEQAEAEAFACQAGADAGAAQAHAAAIgEQAGgDAGgGIAOg7QgEgEgGgDQgHgDgJAAQgIAAgIAEg");
	this.shape_10.setTransform(-34.9,24.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AARA7IAQhGQADgOgFgGQgFgHgNAAQgIAAgHADQgIAFgHAGIgTBTIgXAAIAXhgIgXAAIAFgTIArAAIgCAMQAIgHAIgDQAKgEAKAAQAJAAAHADQAIADAEAFQAEAGACAHQACAJgDALIgMA2IAQAAIgEATg");
	this.shape_11.setTransform(-50.2,26.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcBVIAXhfIgVAAIAFgTIAqAAIgWBfIASAAIgEATgAAIg4IgEgEIgEgEIAAgGIAAgGIAEgEIAEgEIAGgBIAFABIAFAEIADAEIABAGIgBAGIgDAEIgFAEIgFABg");
	this.shape_12.setTransform(-61.4,24.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag7ByIAiiUIgYAAIAFgTIAXAAIAFgUQACgLAFgIQAEgHAFgFQAGgFAIgCQAIgCAIAAIAKAAIAJACIAGACIAFACIgLASIgIgEQgGgBgFAAQgJAAgHAFQgGAFgDAMIgEATIAfAAIgEATIgfAAIgiCUg");
	this.shape_13.setTransform(-68.4,26.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(1,1,1).p("AzzjvMAnnAAAIAAHfMgnnAAAg");
	this.shape_14.setTransform(23.6,25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(-104.2,0,255.5,50), null);


(lib.doclogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Tween2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(277,45,0.63,0.63,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.doclogo, new cjs.Rectangle(187.5,26.1,354.7,68), null);


(lib.bywhen = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shaker();
	this.instance.parent = this;
	this.instance.setTransform(86.3,22.5,1,1,0,0,0,86.3,22.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bywhen, new cjs.Rectangle(0,0,172.7,45.1), null);


// stage content:
(lib._970x250_cupcake = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 8
	this.instance = new lib.cta();
	this.instance.parent = this;
	this.instance.setTransform(1181.5,115.5,1,1,0,0,0,105.5,22);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(311).to({_off:false},0).wait(1).to({regX:23.6,regY:25,x:1097.3,y:118.5},0).wait(1).to({x:1088.9},0).wait(1).to({x:1070.1},0).wait(1).to({x:1031.5},0).wait(1).to({x:961.8},0).wait(1).to({x:887.2},0).wait(1).to({x:833.5},0).wait(1).to({x:795.4},0).wait(1).to({x:766.9},0).wait(1).to({x:744.7},0).wait(1).to({x:727},0).wait(1).to({x:712.7},0).wait(1).to({x:701},0).wait(1).to({x:691.4},0).wait(1).to({x:683.5},0).wait(1).to({x:677.1},0).wait(1).to({x:671.9},0).wait(1).to({x:667.8},0).wait(1).to({x:664.6},0).wait(1).to({x:662.3},0).wait(1).to({x:660.7},0).wait(1).to({x:659.8},0).wait(1).to({regX:105.5,regY:22,x:741.5,y:115.5},0).wait(27));

	// Layer 6
	this.instance_1 = new lib.doclogo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-407.9,88.7,1,1,0,0,0,143.1,30.2);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(311).to({_off:false},0).wait(1).to({regX:364.9,regY:60.1,x:-183.3,y:118.6},0).wait(1).to({x:-173.2},0).wait(1).to({x:-150.6},0).wait(1).to({x:-104.1},0).wait(1).to({x:-20.1},0).wait(1).to({x:69.7},0).wait(1).to({x:134.4},0).wait(1).to({x:180.3},0).wait(1).to({x:214.6},0).wait(1).to({x:241.4},0).wait(1).to({x:262.7},0).wait(1).to({x:279.9},0).wait(1).to({x:294},0).wait(1).to({x:305.6},0).wait(1).to({x:315.1},0).wait(1).to({x:322.9},0).wait(1).to({x:329.1},0).wait(1).to({x:334},0).wait(1).to({x:337.8},0).wait(1).to({x:340.6},0).wait(1).to({x:342.5},0).wait(1).to({x:343.6},0).wait(1).to({regX:143.1,regY:30.2,x:122.1,y:88.7},0).wait(27));

	// Layer 5
	this.instance_2 = new lib.Symbol3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(364,68,1,1,0,0,0,221.8,32.4);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(182).to({_off:false},0).wait(37).to({y:67},0).wait(1).to({regX:336,regY:89,x:478.2,y:123.3},0).wait(1).to({y:122.1},0).wait(1).to({y:118.8},0).wait(1).to({y:113.3},0).wait(1).to({y:109.6},0).wait(1).to({y:107.5},0).wait(1).to({y:106.2},0).wait(1).to({y:105.4},0).wait(1).to({y:104.9},0).wait(1).to({y:104.7},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:48},0).wait(75).to({regX:336,regY:89,x:478.2,y:105},0).wait(1).to({y:106.2},0).wait(1).to({y:108.5},0).wait(1).to({y:112.4},0).wait(1).to({y:118.3},0).wait(1).to({y:127.4},0).wait(1).to({y:142},0).wait(1).to({y:166.4},0).wait(1).to({y:200.6},0).wait(1).to({y:227.4},0).wait(1).to({y:243.9},0).wait(1).to({y:254.4},0).wait(1).to({y:261.4},0).wait(1).to({y:266.1},0).wait(1).to({y:269.3},0).wait(1).to({y:271.2},0).wait(1).to({y:272.3},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:216},0).to({_off:true},1).wait(38));

	// Layer 4
	this.instance_3 = new lib.bywhen();
	this.instance_3.parent = this;
	this.instance_3.setTransform(1397.4,72.7,4.84,4.84,6,0,0,86.5,22.7);
	this.instance_3._off = true;

	this.instance_4 = new lib.Symbol5();
	this.instance_4.parent = this;
	this.instance_4.setTransform(364,60.8,1,1,0,0,0,221.8,17.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(93).to({_off:false},0).wait(1).to({regX:84.9,regY:25.5,scaleX:4.77,scaleY:4.77,rotation:5.7,x:1373.9,y:86.3},0).wait(1).to({scaleX:4.55,scaleY:4.55,rotation:4.9,x:1331.9,y:88.8},0).wait(1).to({scaleX:4.21,scaleY:4.21,rotation:3.7,x:1265.7,y:92.6},0).wait(1).to({scaleX:3.77,scaleY:3.77,rotation:2,x:1180.6,y:97.6},0).wait(1).to({scaleX:3.27,scaleY:3.27,rotation:0.2,x:1084.1,y:103},0).wait(1).to({scaleX:2.77,scaleY:2.77,rotation:-1.7,x:985.5,y:108.6},0).wait(1).to({scaleX:2.3,scaleY:2.3,rotation:-3.4,x:894.9,y:113.7},0).wait(1).to({scaleX:1.93,scaleY:1.93,rotation:-4.8,x:821.8,y:117.8},0).wait(1).to({scaleX:1.68,scaleY:1.68,rotation:-5.7,x:774,y:120.3},0).wait(1).to({regX:86.3,regY:22.7,scaleX:1.6,scaleY:1.6,rotation:-6,x:759.3,y:116.7},0).to({_off:true},79).wait(179));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(219).to({_off:false},0).to({alpha:1},16).wait(70).to({regX:343.6,regY:94.1,x:485.8,y:137.5},0).wait(1).to({y:138.7},0).wait(1).to({y:140.9},0).wait(1).to({y:144.5},0).wait(1).to({y:150.2},0).wait(1).to({y:158.9},0).wait(1).to({y:172.8},0).wait(1).to({y:196},0).wait(1).to({y:228.6},0).wait(1).to({y:254.1},0).wait(1).to({y:269.8},0).wait(1).to({y:279.8},0).wait(1).to({y:286.5},0).wait(1).to({y:291},0).wait(1).to({y:294},0).wait(1).to({y:295.9},0).wait(1).to({y:296.8},0).wait(1).to({regX:221.8,regY:17.7,x:364,y:220.8},0).to({_off:true},1).wait(38));

	// Layer 2
	this.instance_5 = new lib.Symbol1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-200.6,49.8,1,1,0,0,0,136.3,32.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({regX:207.1,regY:97,x:-116.4,y:114.4},0).wait(1).to({x:-99.4},0).wait(1).to({x:-77.4},0).wait(1).to({x:-47.6},0).wait(1).to({x:-7.3},0).wait(1).to({x:38.8},0).wait(1).to({x:77.7},0).wait(1).to({x:106.2},0).wait(1).to({x:127.5},0).wait(1).to({x:143.9},0).wait(1).to({x:156.9},0).wait(1).to({x:167.6},0).wait(1).to({x:176.5},0).wait(1).to({x:183.9},0).wait(1).to({x:190.2},0).wait(1).to({x:195.6},0).wait(1).to({x:200.1},0).wait(1).to({x:204},0).wait(1).to({x:207.3},0).wait(1).to({x:210.1},0).wait(1).to({x:212.5},0).wait(1).to({x:214.5},0).wait(1).to({x:216.1},0).wait(1).to({x:217.4},0).wait(1).to({x:218.5},0).wait(1).to({x:219.2},0).wait(1).to({x:219.8},0).wait(1).to({x:220.1},0).wait(1).to({regX:136.3,regY:32.4,x:149.4,y:49.8},0).wait(63).to({regX:207.1,regY:97,scaleX:1.01,scaleY:1.01,x:218.1,y:115},0).wait(1).to({scaleX:1.03,scaleY:1.03,x:211.4,y:117.5},0).wait(1).to({scaleX:1.08,scaleY:1.08,x:198.3,y:122.1},0).wait(1).to({scaleX:1.16,scaleY:1.16,x:176.6,y:129.9},0).wait(1).to({scaleX:1.29,scaleY:1.29,x:142.7,y:142},0).wait(1).to({scaleX:1.48,scaleY:1.48,x:91.7,y:160.1},0).wait(1).to({scaleX:1.74,scaleY:1.74,x:19.4,y:185.9},0).wait(1).to({scaleX:2.06,scaleY:2.06,x:-66.6,y:216.5},0).wait(1).to({scaleX:2.35,scaleY:2.35,x:-145.1,y:244.5},0).wait(1).to({scaleX:2.58,scaleY:2.58,x:-205.4,y:265.9},0).wait(1).to({scaleX:2.74,scaleY:2.74,x:-249.1,y:281.5},0).wait(1).to({scaleX:2.86,scaleY:2.86,x:-280.8,y:292.8},0).wait(1).to({scaleX:2.94,scaleY:2.94,x:-303.6,y:300.9},0).wait(1).to({scaleX:3,scaleY:3,x:-319.9,y:306.7},0).wait(1).to({scaleX:3.04,scaleY:3.04,x:-331,y:310.7},0).wait(1).to({scaleX:3.07,scaleY:3.07,x:-338.2,y:313.2},0).wait(1).to({scaleX:3.08,scaleY:3.08,x:-342.1,y:314.6},0).wait(1).to({regX:136.2,regY:32.4,scaleX:3.09,scaleY:3.09,x:-562.1,y:115.8},0).to({_off:true},163).wait(89));

	// Layer 3
	this.instance_6 = new lib.Symbol2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(1449,-77.6,0.726,0.726,0,0,0,112.2,112.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({regX:-368.1,regY:404.1,x:1076.5,y:133.9},0).wait(1).to({x:1046.6,y:134},0).wait(1).to({x:1007.6,y:134.1},0).wait(1).to({x:955,y:134.2},0).wait(1).to({x:883.7,y:134.3},0).wait(1).to({x:802.2,y:134.5},0).wait(1).to({x:733.4,y:134.7},0).wait(1).to({x:682.9,y:134.8},0).wait(1).to({x:645.3},0).wait(1).to({x:616.3,y:134.9},0).wait(1).to({x:593.2,y:135},0).wait(1).to({x:574.4},0).wait(1).to({x:558.7},0).wait(1).to({x:545.5,y:135.1},0).wait(1).to({x:534.4},0).wait(1).to({x:524.9},0).wait(1).to({x:516.8},0).wait(1).to({x:509.9},0).wait(1).to({x:504,y:135.2},0).wait(1).to({x:499.1},0).wait(1).to({x:494.9},0).wait(1).to({x:491.3},0).wait(1).to({x:488.5},0).wait(1).to({x:486.1},0).wait(1).to({x:484.3},0).wait(1).to({x:483},0).wait(1).to({x:482.1},0).wait(1).to({x:481.5},0).wait(1).to({regX:112.2,regY:112.8,x:830,y:-76.3},0).wait(63).to({regX:-368.1,regY:404.1,scaleX:0.73,scaleY:0.73,x:481.3,y:135.4},0).wait(1).to({scaleX:0.74,scaleY:0.74,x:481.4,y:136.1},0).wait(1).to({scaleX:0.75,scaleY:0.75,x:481.5,y:137.3},0).wait(1).to({scaleX:0.78,scaleY:0.78,x:481.6,y:139.4},0).wait(1).to({scaleX:0.82,scaleY:0.82,x:481.8,y:142.7},0).wait(1).to({scaleX:0.88,scaleY:0.88,x:482.1,y:147.6},0).wait(1).to({scaleX:0.96,scaleY:0.96,x:482.6,y:154.5},0).wait(1).to({scaleX:1.06,scaleY:1.06,x:483.1,y:162.8},0).wait(1).to({scaleX:1.15,scaleY:1.15,x:483.7,y:170.4},0).wait(1).to({scaleX:1.22,scaleY:1.22,x:484,y:176.1},0).wait(1).to({scaleX:1.27,scaleY:1.27,x:484.3,y:180.4},0).wait(1).to({scaleX:1.31,scaleY:1.31,x:484.5,y:183.4},0).wait(1).to({scaleX:1.34,scaleY:1.34,x:484.6,y:185.6},0).wait(1).to({scaleX:1.35,scaleY:1.35,x:484.7,y:187.2},0).wait(1).to({scaleX:1.37,scaleY:1.37,x:484.8,y:188.3},0).wait(1).to({scaleX:1.38,scaleY:1.38,x:484.9,y:189},0).wait(1).to({scaleX:1.38,scaleY:1.38,y:189.4},0).wait(1).to({regX:112.5,regY:112.5,scaleX:1.38,scaleY:1.38,x:1148.2,y:-213},0).wait(1).to({regX:-368.1,regY:404.1,x:484.4,y:189.8},0).wait(1).to({y:189.9},0).wait(2).to({x:484.3,y:190},0).wait(1).to({x:484.2,y:190.2},0).wait(1).to({x:484.1,y:190.4},0).wait(1).to({x:484,y:190.7},0).wait(1).to({x:483.9,y:191},0).wait(1).to({x:483.7,y:191.3},0).wait(1).to({x:483.6,y:191.5},0).wait(1).to({x:483.5,y:191.6},0).wait(1).to({y:191.7},0).wait(1).to({y:191.8},0).wait(1).to({regX:112.5,regY:112.5,x:1147.2,y:-211},0).wait(1).to({regX:-368.1,regY:404.1,x:483.5,y:191.8},0).wait(2).to({x:483.6,y:191.7},0).wait(2).to({x:483.8,y:191.6},0).wait(1).to({x:483.9,y:191.5},0).wait(1).to({x:484.1,y:191.4},0).wait(1).to({x:484.4,y:191.2},0).wait(1).to({x:484.7,y:191},0).wait(1).to({x:485,y:190.8},0).wait(1).to({x:485.3,y:190.6},0).wait(1).to({x:485.6,y:190.4},0).wait(1).to({x:485.8,y:190.2},0).wait(1).to({x:486,y:190.1},0).wait(1).to({x:486.2,y:190},0).wait(1).to({x:486.3,y:189.9},0).wait(1).to({x:486.4,y:189.8},0).wait(2).to({regX:112.5,regY:112.5,x:1150.2,y:-213},0).wait(1).to({regX:-368.1,regY:404.1,x:486.4,y:189.8},0).wait(2).to({x:486.3},0).wait(1).to({x:486.2},0).wait(1).to({x:486},0).wait(1).to({x:485.8},0).wait(1).to({x:485.6},0).wait(1).to({x:485.2},0).wait(1).to({x:484.8},0).wait(1).to({x:484.4},0).wait(1).to({x:484},0).wait(1).to({x:483.6},0).wait(1).to({x:483.3},0).wait(1).to({x:483},0).wait(1).to({x:482.8},0).wait(1).to({x:482.6},0).wait(1).to({x:482.5},0).wait(2).to({regX:112.5,regY:112.5,x:1146.2,y:-213},0).wait(1).to({regX:-368.1,regY:404.1,x:482.5,y:189.8},0).wait(2).to({y:189.9},0).wait(1).to({x:482.6,y:190},0).wait(1).to({x:482.7,y:190.1},0).wait(1).to({x:482.9,y:190.2},0).wait(1).to({x:483,y:190.4},0).wait(1).to({x:483.3,y:190.6},0).wait(1).to({x:483.5,y:190.9},0).wait(1).to({x:483.8,y:191.2},0).wait(1).to({x:484.1,y:191.5},0).wait(1).to({x:484.4,y:191.8},0).wait(1).to({x:484.7,y:192},0).wait(1).to({x:484.9,y:192.3},0).wait(1).to({x:485.1,y:192.4},0).wait(1).to({x:485.2,y:192.6},0).wait(1).to({x:485.3,y:192.7},0).wait(1).to({x:485.4,y:192.8},0).wait(2).to({regX:112.5,regY:112.5,x:1149.2,y:-210},0).to({_off:true},1).wait(179));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C08632").s().p("EhLxATiMAAAgnDMCXjAAAMAAAAnDg");
	this.shape.setTransform(485,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(361));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(189.8,125,1518.2,250);
// library properties:
lib.properties = {
	id: 'DCCA7DDDDB474A279771A470BF7560D2',
	width: 970,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/970x250_cupcake_atlas_.png", id:"970x250_cupcake_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['DCCA7DDDDB474A279771A470BF7560D2'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;