(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.tree = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#327351").s().p("AgKCcQgzAAgigmQgignAHgyIALhVQAFgqAggcQAhgdApAAQAqAAAhAdQAgAcAFAqIALBVQAHAygjAnQghAmgzAAg");
	this.shape.setTransform(12.4,16.7,0.8,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C59C70").s().p("AgWBTIAAilIAtAAIAAClg");
	this.shape_1.setTransform(12.4,31.6,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.tree, new cjs.Rectangle(2.5,4.3,19.9,34), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AgsA3IAEgRQAUAEAPAAQAHABACgJIADgSQgLAIgNgBQgZABAFgeIADgTQAEgUAHgGQAKgKAYAAQATAAAPAFIgRBeQgDAOgHAFQgHAFgRAAQgQAAgWgHgAgFgkQgCADgBAHIgFAXQgBAGAGAAQAIAAAKgGIAHglIgJgBQgIABgFAEg");
	this.shape.setTransform(611.6,-146.1,1.012,1.012);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AAHAsIAKg8QAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAQgHAAgOAIIgKA3IgZAAIAPhTIAWgEIgBAKQATgKAOAAQAQAAAAARIgBAKIgLA8g");
	this.shape_1.setTransform(602,-148,1.012,1.012);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#231F20").s().p("AgWA/IAPhTIAYgEIgPBXgAgBg6IAYgEIgEAbIgYADg");
	this.shape_2.setTransform(595.2,-149.9,1.012,1.012);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#231F20").s().p("AgaAoIAJgzIgNAAIAEgUIANAAIADgUIAZgEIgEAYIAUAAIgFAUIgTAAIgHAqIAAACQAAABAAAAQAAAAAAABQAAAAABAAQAAAAABAAQADAAAKgDIAFARQgMAHgOAAQgUAAAAgQg");
	this.shape_3.setTransform(589.6,-149,1.012,1.012);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#231F20").s().p("AghAnIAFgSQALAEAMAAQAFAAACgBIACgGQAAgEgLgHQgMgGgEgFQgCgGACgKQACgOAHgFQAGgFAQAAQAPAAALAFIgEASQgKgDgMAAQgFAAgCABQgBABAAADQAAABAAABQAAABAAAAQAAABAAAAQAAABAAAAIAHAEQAPAIAEAFQADAEgCAKQgDAQgGAGQgHAFgRAAQgPABgMgGg");
	this.shape_4.setTransform(582.1,-147.9,1.012,1.012);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#231F20").s().p("AgkAWIAGghQADgRAIgHQAJgJASAAQANAAAIAGQAIAFAAALQAAAMgHAHQgHAGgQAEIgRAGIgBAFQgBAHAFgBQANAAAUgJIAFASQgTALgWAAQgaABAAgXgAgFgMIgBAFIAKgDQAKgCAAgIQAAgEgIgBQgKAAgBANg");
	this.shape_5.setTransform(574.3,-147.9,1.012,1.012);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#231F20").s().p("AgZAsIgMhTIAZgDIAGA/IARgqQACgFAAgGIgBgHIAZgEQABAEAAAHQAAAIgDAHIgbA9g");
	this.shape_6.setTransform(566.3,-148,1.012,1.012);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#231F20").s().p("AAGAsIALg8QAAgBAAAAQAAgBgBAAQAAAAgBgBQgBAAgBAAQgGAAgOAIIgKA3IgZAAIAOhTIAXgEIAAAKQARgKAPAAQAQAAAAARIgMBGg");
	this.shape_7.setTransform(556.6,-148,1.012,1.012);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#231F20").s().p("AgWA7IAUh1IAZAAIgUB1g");
	this.shape_8.setTransform(549.6,-149.5,1.012,1.012);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#231F20").s().p("AAHAsIAKg8QAAgBAAAAQAAgBAAAAQgBAAAAgBQgBAAgBAAQgGAAgQAIIgJA3IgZAAIAPhTIAVgEIAAAKQATgKAOAAQAQAAAAARIgBAKIgKA8g");
	this.shape_9.setTransform(537.9,-148,1.012,1.012);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#231F20").s().p("AgXA/IAQhTIAYgEIgPBXgAgBg6IAYgEIgEAbIgYADg");
	this.shape_10.setTransform(531.2,-149.9,1.012,1.012);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#231F20").s().p("AghAnIAFgSQALAEAMAAQAFAAACgBIACgGQAAgEgLgHQgMgGgDgFQgDgGACgKQACgOAHgFQAGgFAQAAQAPAAALAFIgEASQgJgDgNAAQgFAAgCABQgBABAAADQAAABAAABQAAABAAAAQAAABAAAAQAAABAAAAIAHAEQAPAIAEAFQAEAEgCAKQgDAQgGAGQgIAFgRAAQgPABgMgGg");
	this.shape_11.setTransform(521,-147.9,1.012,1.012);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#231F20").s().p("AAGAsIALg8QAAgBAAAAQAAgBgBAAQAAAAgBgBQgBAAAAAAQgIAAgNAIIgKA3IgZAAIAOhTIAXgEIAAAKQARgKAPAAQAQAAAAARIgMBGg");
	this.shape_12.setTransform(512.3,-148,1.012,1.012);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#231F20").s().p("AggAkQgIgIAAgMIAAgGIAEgTQADgSAJgIQALgIAVgBQAQAAAJAJQAIAHAAANIgBAGIgDATQgDARgJAIQgLAJgVAAQgPAAgKgIgAgLgKIgEAUIAAAEQAAAKAMAAQAMAAADgOIAEgXQAAgKgMAAQgMAAgDANg");
	this.shape_13.setTransform(502.9,-147.9,1.012,1.012);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#231F20").s().p("AghAnIAFgSQALAEAMAAQAFAAACgBIACgGQAAgEgLgHQgMgGgEgFQgCgGACgKQACgOAHgFQAGgFAQAAQAPAAALAFIgEASQgKgDgMAAQgFAAgCABQgBABAAADQAAABAAABQAAABAAAAQAAABAAAAQAAABAAAAIAHAEQAPAIAEAFQADAEgBAKQgDAQgGAGQgIAFgRAAQgPABgMgGg");
	this.shape_14.setTransform(494.6,-147.9,1.012,1.012);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#231F20").s().p("AghAnIAFgSQALAEAMAAQAFAAACgBIACgGQAAgDgCgBIgJgHQgNgGgCgFQgDgGACgKQADgOAGgFQAFgFARAAQAPAAALAFIgEASQgJgDgNAAQgGAAgBABQAAAAgBABQAAAAAAABQAAAAAAABQAAABAAAAQAAABAAABQAAABAAAAQAAABAAAAQAAABAAAAIAHAEQAPAIAEAFQADAEgBAKQgEAQgFAGQgIAFgRAAQgPABgMgGg");
	this.shape_15.setTransform(487.2,-147.9,1.012,1.012);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#231F20").s().p("AgkAWIAGghQADgRAIgHQAJgJASAAQANAAAIAGQAIAFAAALQAAAMgHAHQgHAGgQAEIgRAGIgBAFQgBAHAFgBQANAAAUgJIAFASQgTALgWAAQgaABAAgXgAgGgMIgBAFIALgDQAJgCAAgIQAAgEgHgBQgJAAgDANg");
	this.shape_16.setTransform(479.5,-147.9,1.012,1.012);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#231F20").s().p("AgmA7IAWh1IAYAAIgPBeIAuAAIgFAXg");
	this.shape_17.setTransform(470.8,-149.5,1.012,1.012);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(466.9,-156.2,149.2,16.4), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AAHBDIgJABIgBgBIgCABIAAgBIgDABIgCAAIgCgCIgCgDIAAgCIABgGIgBgBIABgDIgBAAIABgDIgBgDIABgDIABgBIgCgBIAAgQIABgFIgBgBIAAgSIABgEIgBgDIABgCIgBgBIAAgEIACgBIgCgCIABgDIAAgDIgBgJIAAgCIABgCIgCgDIgKAAIgDgBIgDABIgFAAIgEgCIgBgBIgCgGIAAgEIAAgDIAAgGIABgCIADgDIADAAIABgBIACABIAIAAIABAAIACAAIADAAIACgBIAFABIADgBIACABIACgBIAJABIAFgBIACABIACgBIANABIAIgBIABABIAFgBIACACIABAAIABADIAAAKIgBABIABACIgBAGIgCADIgNAAIgEABIgCgBIgBAAIgBAAIgCABIgBgBIgBACIAAAEIgBABIABADIAAADIgBAEIABACIgBAHIAAADIABABIgBACIABAGIgBACIABACIgBADIABABIAAAGIgBAAIABAGIgBAEIABABIAAADIAAACIgBADIABADIgBAFIABACIgBAHIABACIgBAEIABAHIgCAFIgBABIgBAAIgCABgAgHAkIABABIACgBIgBgBgAgGAhIACABIAAgCIgBAAIgCAAgAgDAPIABAAIAAgBIgBgBgAgFAKIAAAAIABgCIgBAAgAgCgIIACAAIAAgBIgBgBgAgHgbIgCACIAEgBIABgBIgDgBgAgHgeIACAAIAAgBIgCAAgAAAgoIAAABIAAABIACgBIgBgBIAAgBIgBAAIgBgBgAADgrIgBACIACAAIABgCIgBgBgAABgxIgBABIgCABIABAAIABAAIAAACIABABIACgCIABgCIACgBIgBAAIgBAAIgBACIgBAAIgBAAIACgCIgCgCIACAAIAAgCIgBAAIgCACIAAABIgCABIAAABIACgBIAAgBgAARgtIABAAIAAgCIgBAAgAAPgvIgBAAIABAAIABAAIgBgCgAAJgzIAAACIABABIAAgCIADAAIACgDIgBgBIAAABIAAACIgFgBgAgUgxIgBABIABAAIACgBIgBgBgAAGg1IABABIAAABIABgBIAAgBIgCAAgAAIg1IABAAIAAgBIgBAAgAgDg1IABgCIgCAAIgDAAIAAACIACgBgAgLg3IABACIABgBIABgBIgDgBgAAPg3IABAAIAAgBIgBAAgAAcg5IAAACIACgBIAAgBgAgLg6IABgBIgBgBg");
	this.shape.setTransform(597.3,-146.4,1.25,1.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#231F20").s().p("AAbBEIgCgBIgFABIgDAAIgBgBIgCABIgDAAIgDgBIgBABIgCAAIgEgBIgBABIgCAAIgHAAIgCgBIgCABIgBAAIgBgBIgHABIgCgBIgCABIgDgBIgCgBIgFgDIgCgCIgBgEIAAgCIgBgBIAAgDIABgDIgBgBIAAgCIABgDIgBgCIAAgDIACgDIAAgBIAHgEIADAAIACgBIAEgCIAAABIACgDIACAAIACAAIABAAIABgBIACABIACACIABACIgBACIABACIgBACIABAFIAFACIADAAIADgBIABABIABgBIABABIAGgDIgBgMIACAAIgCgCIABgBIgBgEIABgBIABACIABgBIgCgDIgBABIgBAAIgDgBIgDAAIgDgBIgBgCIgJAAIAAgDIgBAAIAAACIgCgCIgMgCIgNgDIAAgCIgBgDIAAAAIgBgBIAAgGIABgCIgBgBIAAgDIAAgGIABgBIgBgGIABgDIgBgDIAAgCIABgDIgBgEIAAgCIABgCIgBgCIABgBIAAgCIAAgFIABgBIAAgCIABgCIACgCIABgCIACAAIACgCIAEAAIABgBIADABIALgBIADABIADAAIAJAAIABgBIACABIAGgBIAFAAIACABIABgBIACABIACAAIABAAIACAAIACAAIABABIADABIAEAGIABADIABADIgBAHIAAABIABADIAAAFIgCABIAAACIgCACIgCACIgCAAIgHACIgBABIgGADIgCgBIgBABIAAACIgDgBIgCgCIAAgBIgBgDIABgGIgBgEIgBgBIgCAAIgBgCIgBACIgDgBIgJABIAAABIgBAEIgBADIABADIgBAFIAAABIABAGIACAAIAAACIABABIAAgDIAJAEIAFABIABABIACAAIABAAIABAAIACAAIABABIAEAAIAAABIAFABIACgBIAAACIABgBIADAAIABACIABAAIAGADIAAABIAAABIABAAIAAAfIgBABIABACIABAAIgBABIAAAJIAAAFIgBADIABADIAAACIgBADIgHAHIgBgBIgBABIgCABgAghBAIAAAAIgBgBgAAUA4IAAACIACgBIgBgCgAgCA2IACAAIAAAAIgBgBgAgIAzIAEAAIABABIgBABIAAABIACgBIABgCIgDAAIgBgBIAAgBIABAAIgBgBIgBAAIgBACIgCAAgAgMAxIgBABIAAABIgBABIACABIAAABIABgBIgCgBIACgDIAAgBIgBgCgAgZA0IAAACIACgBIAAgCgAgQAzIAAABIABAAIAAgBIAAgBgAAMAyIAAAAIAAgBIAAgBgAgNAtIABACIAAgCIgBgBgAgUAuIgBABIACAAIACgCIgCAAgAgPArIgBABIABACIABAAIAAgCIABgBIgBgBgAgTArIADAAIABgBIgEAAgAgZAqIABABIABAAIAAgCIgBAAgAgdAqIABABIABgBIgBAAIgBgBgAgTAkIgBABIABAAIACAAIAAgCgAAfAjIABABIAAgCIgBAAgAAQAWIAAACIACAAIAAgBIABgBIgCAAgAAVAWIACABIAAgCIgCAAgAAQATIABACIABgCIAAgBgAAYAQIABAAIAAgBIgBAAgAATANIgDAAIgBABIABACIACAAIABgBIgBgBIABgBIABABIAAgBIAAgBgAAdANIABAAIAAgBIgBAAgAAFALIABABIABgBIgBgBgAAOAKIAAABIACAAIgBgCgAgFAJIAAABIABAAIAAgCIgBAAIAAAAgAASAGIgCABIABABIABgBIACAAIgBgBgAALAGIgBAAIgBABIACABIABgBIABgBIgBgBIADgBIABgBIgBAAIgCAAIgBABIgCAAgAgCAIIACgBIAAAAIgCgBgAASACIgBACIADABIgBgBIAAgBIABABIABAAIAAgCIgCgBgAAJADIABgBIgCgCIACAAIgBAAIgCgCIAAABIgBABIgCAAIAAAAIAAgBIgBAAIABACIABAAIABABIACgBgAgIACIACgBIAAgBIgCAAgAASABIgBgBIgCAAIgBAAIgCAAIACABIACAAIACAAgAgOAAIgBgBIgBgBIgCAAIgBABIABABIACgBIAAABIACAAgAgNgCIABABIABAAIABgBIgBAAgAgUgEIABACIAAgCIACgBIgCAAgAAAgFIABABIABAAIgBgCgAAKgFIACAAIgBgCgAgIgFIACAAIgCgCgAgBgIIAAABIABABIABgCgAgigXIABAAIAAgBgAAdggIABAAIgBgCgAgUgoIAAABIABAAIAAgCgAAWgoIACAAIAAgBIgBAAgAAggrIABAAIAAgBgAgNgsIABABIACAAIgBgBIgCgBgAgQgrIADAAIgBgBIgBAAgAANgsIABgDIgCAAIAAABIgBgBIgCABIACACIABgBgAgXgvIADABIABgBIgCAAIgCgCgAgIgxIABABIACAAIgBgBIgCgBgAANgwIgBgBIgBgBIgCgDIgBAEIACAAIABABIABgBgAAFg1IgBADIAAACIAAgCIADgEIgBAAIgBgBgAACgyIgBACIACAAIAAgCgAgOgyIABABIAAgBIAAgBgAgQg0IABABIAAgCgAATg3IACAAIAAgBIgBAAgAgHg4IACABIAAgBgAAUg5IABgBIgCAAgAAFg7IAAACIACAAIgBgCIgBgBgAAJg7IABgBIgBgBgAgIg/IACgBIgCgBg");
	this.shape_1.setTransform(584.7,-146.4,1.25,1.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#231F20").s().p("AAoBDIgBABIgEAAIgBgBIgCAAIAAABIgBAAIgGAAIgCgBIgBAAIgBABIgGgEIAAgBIgBgBIAAgCIgBgBIgCgCIgCgDIgDgFIAAgDIgCgDIAAgBIgDgDIgBgCIAAgCIgBgCIgHgMIABgBIgCgBIgCgBIgBAAIgCACIgBACIABAKIgBAGIABACIAAAFIgBACIAAAEIAAAKIAAADIgCACIgBACIgDAAIgBgBIgBABIgEAAIgCAAIgBgBIgDABIgGgBIgCABIgBgBIgDgDIAAgBIAAgEIABAAIgBgDIAAgBIAAgHIAAgBIAAgHIAAgCIAAgCIAAgGIgBgFIABgCIAAgGIAAgFIAAgDIAAgJIgBgCIABgDIgBgCIABgDIAAgJIAAgDIAAgBIgBgDIACgEIgBgDIAAgEIAAgBIAAgGIAAgJIgBgCIACAAIgBgHIABgDIACAAIACgCIABAAIAEAAIADABIADgBIABABIAEgBIAPAAIABACIAAgCIAGABIABAAIACgBIAGAAIAFABIAAgBIADABIANAAIADAAIABABIAAABIABgBIAFAEIABADIAAACIACABIAAADIAAAFIAAADIgBACIABADIAAADIAAAJIAAAFIAAADIAAATIAAABIgBAGIABACIgGAHIgDABIgBABIgBAAIgFAAIgCACIACAFIABABIANAWIAAACIACACIAAACIABABIAAABIAAABIACAAIAAADIABABIAAABIACABIgCADIgBACIgBgBIgBABgAARAxIADAAIgBgBIgBgBgAAOAtIABAAIABAAIgBgBgAAUAsIABAAIABgBIgBAAgAgfAnIABACIABAAIAAgBIgCgCgAgkAjIADACIACAAIgCgBIgCgCIgCAAgAgcAcIgBABIABACIAAABIAAgDIABAAIABgCIgBAAgAgYAYIACAAIAAABIABAAIAAgCIAAgBIgBAAIgBgBIAAABIABABIgBAAIgBAAgAAJAXIABAAIABgBIgCgBgAghAXIACgBIgBgBIgBgBgAgYARIAAABIgCABIAAABIACAAIABgBIABgBIgCgCgAgSARIgBABIACABIAAgBIABgBIgBgBgAAFAQIACAAIAAACIgBAAIADAAIAAgCIgBgBIgCAAgAAOALIABADIABABIABgBIgCgDIABAAIAAgBgAgVAOIABgBIABgBIgCAAgAgFANIACAAIgBgCIgCAAgAAFALIAAACIABgCIgBAAIABgBIgBgBgAgRANIACAAIAAgCIgBAAgAgdAMIABgBIAAgBIgBAAgAgVALIAAgBIACgBIgBgBIgCABIgBABIgCgBIgBACIACAAIABAAgAgDAKIABABIAAgEIgBgBIgBgBgAAXAJIABgBIgBgBgAABAGIACABIgBACIABgBIABgCIABgBIgCAAgAgJAHIAAACIABgCIgBgBgAgPAHIABAAIABgBIgDAAgAANAGIgBgBIgBAAIgCAAIAAABIABAAIABAAIACAAgAgaAEIABABIAAgCIgCgBgAgJACIAAACIABAAIADABIAAgDIgDgCgAgTAAIACACIgCAAIABABIABABIABgBIAAgBIACgCIABgBIgBAAIgBgBIAAABIgCABIgBAAgAARADIACABIAAgCIgBAAIgBAAgAAYABIABABIACAAIgBgBgAAJACIACAAIAAAAIgCAAgAAFAAIgBABIABABIABgBIABgBIABAAIAAAAIgBgDIAAACIgBABIgBAAgAgMAAIAAACIACgCIAAAAIgBAAIgBgBgAAUgBIABABIAAgCgAAKgBIACABIAAgCIgDAAgAAWgCIACAAIAAgCIgBABIgCgBgAgPgEIACABIAAgCIgBAAgAAOgEIACAAIAAgDIgBAAgAgNgnIgBABIgBABIAAACIAAACIAAABIABABIgBACIAAAGIAAAFIAAAEIAAADIACADIAEAAIABABIAGgBIACAAIACAAIADAAIADAAIAEgCIAAgJIgBgEIABgFIgBgKIgEgCIgCABIgCgBIgDAAIgFABIgDAAIgBgBgAgWgIIABAAIAAgBIgBgBgAAYgLIADgBIgDgBgAAfgNIABgBIgCAAgAAWgQIgBABIACACIABgBIABgCIgDABIABgBIgBgBgAgagQIABAAIAAAAIgBAAgAAZgTIADABIABgBIAAgBIgCABIgCgBgAAUgTIABABIABgCIgBgBgAgegWIAAACIABABIACAAIgBgCIgBgBIAAgCIgBgBgAAYgXIgBAAIABABIAAABIACgBIAAgCgAgggZIAAAAIABABIABgBIgBgBgAARgaIABABIABgBIgCgBgAgfgbIAAABIABgDIgBAAgAgigeIABAAIABgBIgBgBgAAdgjIABAAIAAgBIAAgBIgCAAgAAXgjIAAgBIgBgBIgBAAIAAABIABAAIABABIAAAAgAASgoIACABIABAAIAAgBIgBgBIgCAAgAAagqIAAABIABgBIgCgBgAAWgsIAAACIACgBIgCgCgAAUgsIABAAIAAgBIgBAAgAgMguIAAABIAAABIABgBIABAAIAAgBIgCgBgAAQgtIgCgDIAAgBIAAABIAAABIgCAAIABABIADABgAgCgtIABAAIAAgBIgBAAgAgBgxIAAACIACgCIABgBIgCgBgAgWgzIABAAIAAgBIgBAAgAgSg1IABAAIAAgBIgCAAgAgVg2IAAgBIAAAAg");
	this.shape_2.setTransform(571.5,-146.5,1.25,1.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAIBEIgCAAIgBAAIgGAAIgCgBIgEABIgBgBIgCABIgEgBIgGABIgCgBIgCABIgGgBIgCAAIgCgDIgCAAIAAgDIAAgBIABgCIgBgCIAAgDIAAgBIAAgBIABgBIgBgDIAAgEIAFgCIADAAIACAAIAIAAIACAAIACgCIABgBIgBgBIAAgBIAAgDIAAgCIAAgBIAAgDIAAgIIAAgFIAAgCIAAgEIAAgCIAAgCIABgBIgBgDIAAgBIAAgBIAAgDIABgCIgBgBIAAgFIAAgDIAAgNIAAgFIABgBIgCgDIgDgCIgHABIgCgBIgCABIgFgBIgBgBIgBgEIACgCIABgCIAAgCIACgDIABgCIAAgBIABgBIAAgCIABgBIABgDIAFgDIADABIAFgBIABABIAEgBIAEABIAFgBIAAAAIACABIABgBIACAAIACABIAEAAIACABIACADIAAACIgBACIABABIAAAFIgBABIABADIAAADIgBACIABACIAAABIgBACIABACIAAAGIgBABIABADIgBAEIABABIAAAGIAAAEIgBACIABADIAAACIAAAEIgBADIABACIAAABIAAADIgBABIABADIAAACIAAACIgBABIABABIAAAEIAAACIAAADIAAACIgBACIABABIAAAGIACABIADABIAKAAIAEABIABACIABADIAAAKIABACIgCAGIgCACIgGABgAgRA7IACgBIgBgBIgBAAgAgDAzIABgBIgBgBgAgHAtIAAABIABACIABgCIAAgCgAAIAtIABABIAAgCIAAgBIgCAAgAgCAkIgBABIACAAIABgCgAgCATIABABIAAgCgAgIgEIACAAIgBgBgAgEgNIABgDIgBAAgAgFgSIABABIABgCIgDAAgAgJgVIgBABIADAAIgBgCIgBgBgAgCghIAAABIABABIAAgDgAgGglIgBACIAAABIABgBIABgBIADABIgBgCIgBAAgAAHgkIABAAIAAgBIgBAAgAgJglIABgBIAAAAIgCAAgAgCgoIABAAIABAAIAAgCIgCgBgAgKgqIACAAIABgCIgCAAgAgKgtIAAABIABgBIABgBIABgBIACAAIABACIAAgCIgDAAIgCgBIAAACIgBABIgBgBgAAGguIgBgCIABABIAAgBIgCgBIgBAAIABACIgBABIADAAgAgBgyIAAACIAAABIABAAIAAgBIAAgCIAAgBgAgSgwIAAABIABgBgAgCg2IABABIABgBIgBAAIgBgBgAgEg2IABgBIgBgBg");
	this.shape_3.setTransform(559,-146.4,1.25,1.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#231F20").s().p("AgcBDIgEABIgEgBIgBgCIgBgDIAAgFIABgCIgBgDIABgBIgBgCIAAgBIAAgGIABgCIgBgBIAAgEIAAgGIAAgEIABgBIgBgCIABgGIgBgCIAAgCIABgCIgBgCIAAgCIAAgRIABgBIgBgCIABgEIgBgFIABgBIgBgDIABgBIgBgBIAAgBIABgEIgBgCIAAgEIAAgFIAAgDIAAgCIAAgJIABgGIADgBIADgBIABABIABgBIACABIABAAIABAAIADgBIADABIABAAIACgBIAIABIAGgBIACABIABgBIAEABIABgBIAZABIAGAAIACAMIgBANIgFABIgDABIgFgBIgGABIgTgBIgFABIgCAAIAAABIgBAHIAAABIAAAHIAAADIABABIgBADIAAADIACACIAHAAIABABIACgBIADAAIAEAAIABAAIAEAAIAEAAIACABIABgBIACACIAAACIACACIgBAFIABAGIgBADIgBADIgEABIgBAAIgKAAIgBAAIgDAAIgCAAIgBgBIgCABIgEAAIABgBIgCABIgBAAIgBABIgDADIABACIAAANIgBACIABABIABAGIgBABIAAABIgBABIACAHIAAAEIgBADIAAADIAAACIgCAEIgCABIgKAAIgDAAgAgVAwIABABIABgCIgCgBgAgZAuIgBACIADgBIgBgDIgBAAgAgdAmIAAACIABABIAAgBIABgBIABAAIAAgCIgCAAgAgSAoIABAAIAAgBIgBAAgAgYAnIABABIAAgCIgCAAgAgTAmIABAAIABgCIgBAAgAgYAjIABAAIABgBIgCAAgAgZAXIABABIABAAIAAgBgAgWAOIAAACIABAAIABgBIABABIAAgCIgBgBgAgOAKIACAAIAAAAgAgTAHIgBAAIACACIABgCIAAgBIgBAAgAgWAGIgBABIACAAIABgBIgCgBgAgaAHIACgBIgCgBgAgdAFIACABIAAgCIgBAAgAgNAEIAAAAIABABIABgBIgBgBgAgVADIABABIABAAIAAgBIABgBIABABIABgBIgEgBgAgCABIABABIABgBIgCgBgAgZABIABABIACgCIAAAAIgBAAIAAAAIgDAAgAgIgBIABABIABAAIAAgCIgBAAIgCAAgAgTAAIACAAIADgBIgCgDIAAACIgCACIgBgCgAgZgBIACgBIgDAAgAgNgKIAAACIABABIgCACIABABIAAABIADABIAAgBIgCAAIAAgBIADgBIAAgCIgCAAIABgCIgCgBIAAABIgBgBgAgZgGIAAADIACAAIgBgCIACAAIAAgCIgEgBgAgIgDIABgBIAAgBIgBABIgBAAgAgTgHIgBACIACAAIABgCIgBgBgAgUgKIABABIABgBIgCgBgAgYgKIABAAIAAgBIgBAAgAgXgUIAAABIABABIABABIABgBIgBgCgAgUgTIABABIACgCIAAAAgAgWgWIAAACIACgBIABgBgAgXgeIABAAIABgBIgCgBgAgSgqIgBABIAAABIACAAIADgBIgBgCgAgZgvIACAAIgBgBg");
	this.shape_4.setTransform(547.9,-146.4,1.25,1.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#231F20").s().p("AAqBDIgEABIgBAAIgCAAIgCgBIgDABIgFAAIgDAAIgDgBIgCAAIAAgCIgDgDIAAgBIgCgBIgBgCIAAgEIgEgEIgBgEIAAgCIgCgCIgDgHIgBgBIAAgCIgBAAIgBgCIABgCIgCAAIgBgCIgEgHIABgBIgCgBIAAgCIgDgBIgBgBIgCABIgBABIgBALIAAABIABAEIgBACIABABIgBACIABAFIgBABIABAIIgBAFIABADIgBACIAAADIgBADIgFACIgCgBIgBAAIgHABIgBAAIgJgBIgCAAIgBgDIgBgDIABgBIgBgCIABgDIAAgDIgBgBIABgEIgBgPIABgFIgBgDIABgDIgBgCIABgBIAAgGIABgCIgCgEIABAAIgBgFIABgCIgBgBIABgJIgBgCIAAgEIABgCIAAgMIgBgEIABgCIgBgBIABgHIgBgCIABgDIgBgEIABgFIAAgCIABgEIADgBIADAAIACgBIACABIABAAIABgBIAEABIADgBIAFABIADABIABABIABAMIgBAFIABAAIAAAHIAAACIgBADIABABIAAADIgBADIABACIAAAMIABABIADAAIABAAIACgDIACgEIABgCIACgBIgBgDIABAAIABgBIABgBIABgDIADgIIAAgBIACgBIAAgEIADgCIgBgCIACgBIABgDIAEgIIABgDIAEgCIADgBIABAAIACABIADgBIAFABIABgBIADABIABgBIACABIADAAIADAAIABABIAAAEIgCADIAAABIgCAEIgBACIgCACIAAACIgBABIgBABIAAADIgEAFIAAACIgBABIgCAEIgBABIgBACIgCAEIgCAGIgCADIgCADIAAABIAAABIgDACIgCAGIAAACIACADIAAABIADAEIAAABIADAGIADAHIAFAGIAAACIABABIAAACIACABIACAGIACABIABAEIACACIAAACIACADIAAABIACACIACAFIABAAIAAACIgCAEIgDABgAgdAlIABAAIAAgBIgBAAgAAQAkIABAAIAAgBIgBgBgAAAAXIAAABIAAgCgAAPAWIACAAIAAgBgAgUANIAAABIABAAIABgBIgBAAgAgZAMIABgBIAAgBIgBAAgAAHAKIABAAIgBgCIgDAAgAgEAIIAAABIABABIABAAIAAgBIgCgCgAgGAKIAAAAIAAgBIAAAAgAgMAIIABACIABAAIgBgBIAAgCIAAAAgAgVAIIABAAIAAgBIgBgBgAgDAGIADABIAAgBIABAAIgBgDIAAACIgCAAIgBAAgAgPAGIABAAIAAABIACgBIgCgBgAgmAFIAAABIABAAIABgBgAAFABIgBACIgBABIAAABIABAAIABAAIAAgCIABgBIACAAIgBgCgAgaADIgBABIABABIACAAIgBgBIAAgCgAgGACIgBABIABAAIACABIACgCIgCgCIgBgBIABgBIgCAAIAAABIgBABIgCAAIAAABIADgBgAgUAAIgBACIADACIADgBIACgBIACABIgBgCIgCAAIgBgBIgBAAIAAABIgBABIAAgBIgCAAIAAgBgAgBABIABAAIABACIABgCIACgBIAAAAIgCAAIgBAAIAAAAIgCAAgAghABIABABIACgBIgCAAIgBgBgAgPgCIgBACIABAAIACAAIAAAAIgBgBIAAgBIAAgCIgDAAIAAACIABABIgBgBIAAgBIACAAgAgBAAIABAAIAAgBIAAgBIAAABIgBAAgAgJAAIABgBIAAgBIgBAAgAgMgBIABAAIAAgBIgBAAgAgcgDIABABIABgDIgCAAgAAAgEIABACIACgBIgBgBgAgIgEIACACIAAgBIAAgBIACABIgBgBIgBgBgAglgHIAAACIACAAIAAgDgAgHgIIgBADIACgDIAEAAIACgBIgBgBIgBAAIgBgBIgBABIAAABIgDAAgAgQgIIgBABIACAAIAAgBIABgBIgCAAgAgWgLIADABIgBgBIgBAAIABgCIgCgBIgBAAgAgBgLIABAAIABgBIgCAAgAgagMIAAABIACAAIAAgBIgDgBgAgdgNIABgBIgBgBIgCAAIgBACIADgBgAgYgSIABABIAAgCIgCAAgAgcgSIABAAIABAAIAAgBgAADgUIABAAIAAgBIgBAAgAAGgWIAAgBIgCgBgAAKgYIABAAIAAgCgAAJgfIABgBIgBAAgAgjgiIABABIAAgCIgBAAgAgbgjIABAAIAAgBIgBAAgAgcgoIABAAIAAAAIgBAAgAATguIAAACIABgBIABgBIgBgBIgBAAgAAPgvIABAAIAAgBIgBAAgAAcgwIAAABIABgBIgBAAgAARgwIABgBIAAgBIgBAAg");
	this.shape_5.setTransform(535.1,-146.4,1.25,1.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#231F20").s().p("AAZBDIgIABIgCgBIgCABIgBgBIgBAAIgBABIgGgBIgBABIgDAAIgFAAIgCgBIgFABIgDAAIgIAAIgBgBIAAAAIgBABIgCAAIgBgBIgBAAIgCAAIgBAAIgBgCIgCgBIgBgCIgDgBIgBgDIgBgDIAAgCIABgCIgBgGIABgCIgBgBIAAgDIAAgJIABgFIgBgCIAAgBIAAgHIABgCIgBgDIAAgBIABgBIgBgCIAAgBIAAgCIAAgCIAAgIIABgCIgBgDIABgFIgBgBIABgCIgBAAIABgDIgBgDIAAgDIABgBIgBgFIAAgBIABgCIgBgBIAAgJIABgBIgBgCIAAgBIAAgDIABgCIAFgHIACgBIACgBIASgBIACABIADgBIACABIABAAIACAAIABgBIACABIABAAIABgBIADABIAGgBIACABIAFgBIACABIAGgBIABABIADAAIADABIADABIABABIABAAIADAIIAAADIABADIgBAEIABACIgBAGIABAGIAAABIgBABIAAACIgBABIgDAEIgCABIgDAAIgBABIgCABIgBgBIgDACIgLAFIgCgDIAAgGIgBgEIAAgBIABgBIgBgCIABgEIgBgFIgBgBIgCAAIgBABIgDgBIgBABIgCgBIgDAAIgBABIgBgBIgFABIgBABIgCACIABAAIAAAJIAAABIAAACIAAABIAAARIgBAEIABACIAAAAIAAAJIgCADIACABIAAADIABABIgBANIABACIgBACIAAAEIACACIABABIABgBIACABIAAABIABgBIAEAAIACAAIAAABIABgBIABAAIAFAAIADgCIAAgEIABgDIgBgBIAAgKIAAgBIAAgEIABAAIABgBIABABIAGAAIABABIABABIAGABIAIAEIAEAEIAAABIABACIgBAJIABAEIgBAEIABADIgBACIABACIgCABIABADIgCACIAAABIAAABIgCADIgCAAIgBgBIAAADIgCAAIgDABIAAgCIgBABIgBABgAAOA5IAAACIABABIAAgFIgBAAgAAFA8IABAAIAAgBIgBAAgAADA8IABAAIAAgCgAAYA5IABAAIABgBIgCgBgAAeA4IACABIABgBIgDgCgAgTA5IABAAIAAgCIgBAAgAgNA3IABAAIAAgBIgBAAgAAGA3IABAAIAAgBIgBAAgAgYA1IAAABIABABIAAgCgAAPA2IABgBIgCAAgAACA0IACAAIABAAIgDgBgAgeA0IABAAIgBgBIgCAAIgBAAgAAXAyIAEACIACgBIgDgBIAAgBIgCAAgAAkAyIAAABIABAAIAAgCIAAgBgAALAyIABABIABAAIAAgBIgBgBIgBAAgAAQAwIACAAIAAAAIgBABIACACIABgBIgCgCIACgBIABgCIgCABIgCAAgAAIAzIACAAIAAgBIgCAAgAADAwIAAACIABABIACgDIgCgBgAABAwIAAACIABgBIABgCIgBgBgAAiAwIAAABIACgBIAAgBgAANAuIgBACIACAAIAAgDgAAJAuIgBAAIgBACIADgBIABABIAAgDgAgQAwIADAAIAAgBIgCABIgBgCgAAZAvIACgBIAAgBIgBAAgAgUAuIACABIAAgBIgBgBgAAeAqIgBADIABAAIAAAAIABgDIgCgBgAAWAsIABABIABgBIACgCIgCAAgAAAAtIAAgBIAAAAgAAQAsIABABIACAAIAAgBIgCgBgAAkArIgBABIACAAIAAgCgAgeAsIABgBIgBAAgAgcAqIABABIABgBgAgPApIAAABIACgBIABgBIgBgBgAAUAqIABgBIgBgBgAgWApIABABIAAgCIgBAAgAAXAlIgCACIABABIABgBIABAAIAAgCIAAgBgAgVAiIgBABIAAABIADgCgAghAfIABAAIgBgBgAgRAQIABAAIABgBIgBgBgAgRAGIABAAIABAAIAAgBIAAAAgAgUgCIABABIABgDIgCAAgAgQgEIABAAIAAgBgAgTgLIABABIACAAIAAgBIgBgBgAgcgRIABgBIgCAAgAgkgTIACABIABgBIAAgBIgBAAIgBAAIgBAAgAgWgYIACABIACAAIgBgCIABgCIgBgBgAgagZIgBgDIgCAAIgDgCIAAABIABABIAAABIACAAIABABIACABgAgZgcIACABIACgBIABgDIABgBIACAAIgBgCIgBAAIABgBIgCgBIgBACIgBAAIAAgBIgBABIAAABIABAAIABABIgBABIAAACIgBABIgCgBgAgPgdIABAAIgBgCgAAVgfIABgBIABgBIgCgBgAgcgjIgBABIACAAIABgCIgDgBIgBAAgAgUgmIACABIACAAIgBgCIgBgBIgBAAgAgbgmIADAAIACABIACAAIgBgBIgBAAIgBAAIgCgBIgBAAgAgPgrIAAACIABAAIADAAIgBgEIgDABIAAgBIAAgBgAgVgsIgBABIADAAIgBgCgAgcgrIABAAIABgCIgDAAgAAOgvIAAABIABAAIACgBIgCAAgAAhgvIADAAIgBgCgAgLgxIACABIAAgCgAgVg0IgBABIABACIABgBIABgCIgBgBgAAPg6IACAAIAAgCIgCAAg");
	this.shape_6.setTransform(521.3,-146.4,1.25,1.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#231F20").s().p("AgVBEIgBgBIgBAAIgDAAIgBAAIgCAAIgDAAIgDAAIgBgBIgBgCIABgDIgBgFIABgEIgBgCIAAgCIAAgDIABgBIgBgCIAAgDIAAgEIAAgBIABgBIgBgCIAAgJIAAgFIAAgDIAAgMIABgCIgBAAIAAgBIAAgCIAAgBIAAgIIABgDIgBgCIAAgBIABgBIgBgFIAAgDIAAgDIAAgBIAAgCIABgCIgBgEIABgDIgBgDIAAgBIAAgCIAAgBIAAgCIAAgDIAAgCIAAgFIAAgCIACgDIADgBIABAAIAJAAIACABIABgBIACAAIACAAIABABIABgBIABABIABgBIAJAAIACAAIABABIADgBIACAAIABABIACgBIADAAIACABIABgBIAGAAIAEAAIABAAIADAAIAJACIgBACIABAEIgBABIABAJIAAAEIgCADIgBABIgEABIgBAAIgLAAIgCABIgDgBIgBAAIgJAAIgBgBIgCABIgBAAIAAAAIgCAAIgCAAIgDACIAAAFIAAACIABADIAAABIgBADIABADIAAAHIAAABIACABIABAAIAAABIABgBIACAAIADAAIACABIABgBIABAAIAGAAIADAAIAFAAIABABIABgBIABABIACADIAAAGIAAACIgBAAIABABIAAADIgBAGIgCABIgCABIgHAAIgCgBIgCACIgBgBIgJAAIgEABIgDABIAAABIAAABIAAACIAAAGIABACIgBABIAAAGIgBACIABABIABAEIAIABIAEgBIABACIABgCIACAAIABAAIABABIADgBIADAAIAEAAIAEABIABgBIAJABIACADIAAAEIgCAAIACAFIAAABIAAABIgBAFIABADIgDAEIgMAAIgDABIgCgBIgEABIgDgBIgCABIgCAAIgBgBIgFAAIgHAAIgCABIgGAAgAAUAyIAAABIABABIABgDgAAEAxIAAABIACgBIgBgBIgCgBgAgOAuIACABIAAgCIgBAAgAgOAqIABAAIgBgBIgBAAgAgTAnIABAAIAAgBIgBAAgAgMAlIABAAIgBgBIgBAAgAgaAfIAAACIACAAIAAgBIgBgBgAgcAeIgBABIABAAIABgBIgBgCgAgUATIABABIAAACIACABIAAACIgBABIAEgDIAAgBIgCAAIgBgBIAAgBIgDgCgAgMAXIABgCIgBAAgAgaAQIABABIABABIAAgCIgCgDgAgMAKIABAAIAAgDIgCAAgAgUAKIAAAAIAAgBIAAAAgAgRAEIABACIgBAAIAAACIgBABIACgBIABgDIAAgBgAgWADIgBABIABADIACgCIABABIABgBIgBgCIACABIgBgCIgBgBIgBADIgBABIAAgBIAAgBIAAgBgAAOAFIABABIAAgCIgBAAgAgEADIABABIABgBIgBgBgAgaACIACACIAAgCIgBgBgAgbAAIAAABIADgBIgCAAgAgPAAIACAAIABAAIAAAAIgCAAgAgLgCIABABIAAgBIgBgBgAgGgGIABAAIgBgBIgBgBIgEAAIABACIABAAIABgBIABgBgAgTgHIABABIABgBIgBgBgAgUgJIACABIABgDIAAgBIgBgBIAAABIgCABIABABIAAgBIAAACIgBgBgAgSgPIABABIABgBgAgTgWIABABIABgBIgBAAgAgVgXIABAAIAAgBIgBAAgAgWgfIABABIABgCIgBgBgAgZgfIABABIABgCIgCgBgAgVgqIABAAIgBgBIgBAAgAgPgqIgBgCIgBgBIACAAIAAgBIgCAAIgBAAIgCAAIADADIACABgAgNgsIAAABIABgBgAgYguIABABIABAAIgBgBgAgTgwIABABIABAAIABgBIgCgBIgBgBgAAQgyIACABIAAgCIgCgBgAgDg0IABAAIgBACIABABIACgBIAAgBIgCgDIgDABIgBABIABgBgAATgyIACgBIgBgBIgBgBIgBAAgAADg2IAAACIABgBIABgBIgBAAgAgUg0IABAAIABgBIgDAAgAAGg2IAAAAIABABIAAgBIgBgBgAAAg4IAAABIACAAIgBgCgAAGg7IAAACIABgBIACAAIgBgBgAgIg5IABgBIgBgBIgBAAgAgDg6IACgCIgDAAgAgQg7IACAAIgBgBIgBAAg");
	this.shape_7.setTransform(508.8,-146.4,1.25,1.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#231F20").s().p("AAnBDIgRABIgEgCIgBAAIgCgGIAAgDIABgDIgBgFIABgCIgBgGIAAgMIAAgGIAAgBIAAgBIABgBIgBgBIABgBIgBgDIgCgCIgCgBIgDABIgCAAIAAgBIgDABIgBgBIgCABIgDAAIgBgBIgIABIgCACIAAAEIAAABIAAABIAAABIAAACIAAAFIAAABIAAABIAAADIAAACIAAADIAAACIAAAGIAAABIAAABIAAABIAAAIIgBACIABACIAAACIgDADIgNAAIgFAAIgCABIgBAAIgCgBIgCAAIgBgBIgBgDIABgEIgBgCIAAgBIABgBIgBAAIAAgOIgBgHIABgCIABgCIgBgBIAAgMIABgFIgBgGIAAgGIABgDIgBgBIAAgCIABgCIgBgBIABgCIgBgCIABgLIgBgCIABgBIgBgCIAAgBIgBgCIABgEIgBgCIABgBIAAgCIAAgCIAAgEIABgBIgBgCIAAgJIAAgCIABgDIACgCIAEgBIAIAAIABABIADgBIAEAAIADABIABAAIACACIABACIAAACIAAAQIgBADIABABIgBABIABABIAAAEIAAACIAAACIAAABIAAACIAAABIgBABIABABIAAABIAAAIIADACIACAAIACAAIARAAIAGgCIgBgCIABgBIgBgGIAAgFIABgBIgBgEIABgCIgBgCIAAgFIABAAIAAgBIgBgGIAAgFIABgCIgBgCIABgGIACgBIAEgBIAFAAIABAAIADAAIAEAAIABABIACgBIAFABIACADIgBACIABABIgBABIAAABIACAFIgBADIAAABIAAAEIAAANIgBACIABADIAAACIAAABIAAADIgBACIACABIgBAEIgBABIABAEIAAALIABABIgBABIAAABIAAAFIAAABIAAACIAAAHIABAFIgBABIABADIgBACIABACIgBACIAAAMIABACIgBAFIABADIgBAEIAAACIgBACIAAABIgBABIgCAAIgBABgAAdAzIABAAIAAgBIgBAAgAAnAyIACAAIgCgBgAgfAuIABADIAAABIAAgDIABgCIgBAAgAgaAoIAAABIACABIABgBIgCgBgAAgApIADAAIAAgBIgCgBIgBAAgAAhAfIABABIABgBIgBgBgAAbAfIAAgBIgBAAgAgbAcIABAAIAAgBIgBAAgAgdAZIABAAIAAgBIgBAAgAggASIABACIACAAIAAABIABABIgBgEIgCAAIgBgBgAAkARIABAAIABgBIgBgBgAAaAPIAEACIAAgCIgCgBIgBAAgAAZANIgBABIADgBIgBgBgAgXAJIAAADIABAAIAAgBIACgBIgCAAIAAAAIAAgBIACgBIgBgCIgCACIAAgDIgCAAgAAZAIIACACIABgBIACgBIgBgBIgCgBIgBACIAAgBIgBAAgAAgAGIABABIACAAIACgCIgCgBIAAACIgCAAgAgPAHIABAAIAAgBIgBAAgAgIAFIABABIABgBIgBgBgAAEAEIAAABIABgBIABgBIgBgBgAAaAEIABAAIABgBIgDAAgAgGAAIgCAAIABABIgBABIgCABIACAAIABgBIABgBIACAAIgBgBIAAAAgAgQADIACgBIgBgBIgBABIgBAAgAgLACIABgBIgCAAgAAXABIADAAIgCgBIgBAAgAATABIACgBIAAAAIgCAAgAAGABIACgBIAAAAIgBAAgAAZgCIACAAIAAABIACgBIABAAIgBgCIgBgBgAALgCIACAAIgBgBgAAVgDIACABIgBgDIgBAAgAgQgDIABABIABgBIABgBIgDgBgAAZgIIAAACIgBABIgBABIACABIAAgCIABgBIACgDIgCAAgAgJgFIAAABIACgBIgBAAgAARgFIABAAIABgBIgCAAgAgXgFIABAAIAAgBIgBAAgAgFgGIABAAIgBgBgAAegIIABAAIABgBIgCgBgAAYgIIgBgEIgCACIgCgBIgBACIABgBIABABIABAAIACABIABAAgAAcgMIACAAIgBgBIgBAAgAgYgMIABAAIAAgBIgBAAgAgdgQIAAABIABABIABgBIABAAIgBgBIAAgBgAAjgQIABAAIAAgBIgBAAgAAegSIACACIAAgCIgBAAgAAcgfIACAAIgBgBgAgWgfIABAAIAAgBIgCAAg");
	this.shape_8.setTransform(495.3,-146.5,1.25,1.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#231F20").s().p("AAZBDIgIABIgCgBIgCABIgCgBIgCABIgEgBIgCABIgDAAIgFAAIgCgBIgDABIgCAAIgDAAIgIAAIgBgBIgBAAIgBABIgBAAIgBgBIgBAAIgBAAIgCAAIgCgCIgBgBIgCgCIgCgBIgCgGIAAgCIABgCIgBgGIABgCIgBgBIABgDIgBgJIABgFIgBgCIAAgBIAAgHIABgCIgBgDIAAgBIABgBIgBgCIABgBIgBgCIAAgCIAAgIIABgCIgBgDIABgFIgBgBIABgCIgBAAIABgDIgBgDIAAgDIABgBIgBgFIAAgBIABgCIgBgBIAAgJIABgBIAAgCIgBgBIAAgDIABgCIAFgHIABgBIADgBIANAAIAFgBIACABIADgBIABABIACAAIACAAIABgBIACABIABAAIABgBIAEABIAEgBIADABIAEgBIACABIAGgBIACABIADAAIADABIACABIABABIACAAIADAIIABABIgBACIABADIgBAEIABACIAAAGIAAAGIAAABIgBABIAAACIgBABIgDAEIgDABIgCAAIgBABIgCABIgCgBIgCACIgLAFIgCgDIAAgCIAAgEIgBgEIABgCIgBgCIABgEIAAgDIgCgCIgBgBIgBAAIgBABIgDgBIgBABIgCgBIgDAAIgBABIgBgBIgFABIgBABIgCACIABAAIAAAJIAAABIAAACIABABIgBAEIAAANIgBAEIABACIABAAIgBAJIgCADIADABIgBADIABABIgBAFIABADIgBAFIABACIgBACIAAAEIABACIABABIACgBIABABIABABIACgBIADAAIABAAIABABIABgBIABAAIAFAAIADgCIAAgEIABgDIgBgBIAAgKIAAgBIABgEIAAAAIABgBIACABIAFAAIACACIAGABIAGADIABABIAGAEIgBABIABACIgBAFIABACIgBACIABAEIgBAEIABADIgBACIABACIgBABIAAADIgBACIAAABIgCABIgCADIgBAAIgBgBIAAADIgCAAIgCABIgBgCIgBABIgBABgAgQA/IABAAIAAgBIgBAAgAAOA7IACABIgBgDIABgCIgCAAgAAYA5IABAAIAAgBIgBgBgAAfA4IABABIABgBIgDgCgAgTA5IABAAIAAgCIgBAAgAgYA1IgBABIACABIAAgCgAgDA1IABABIACAAIAAgBIgCAAIgBgBgAACA0IACAAIABAAIgEgBgAgeA0IABAAIgBgBIgBAAIgCAAgAAXAyIAEACIACgBIgDgBIgBgBIgBAAgAgWAwIgBABIACAAIAAABIgCABIABABIABgBIACAAIABgBIgDAAIABgDgAAjAyIAAABIABAAIABgCIgBgBgAAQAwIABAAIABAAIgBABIACACIAAgBIgBgCIABgBIABgCIgBABIgCAAgAADAwIAAACIACABIABgDIgCgBgAABAwIAAACIABgBIABgCIgBgBgAANAuIgBACIACAAIABgBIgBgCgAAIAuIgBAAIAAACIADgBIABABIAAgDgAgRAwIAEAAIAAgBIgCABIgBgCgAAZAvIACgBIAAgBIgBAAgAAeAqIgBACIAAABIABAAIABAAIAAgDIgBgBgAAXAsIAAABIABgBIACgCIgCAAgAgBAtIABgBIgBAAgAAQAsIABABIACAAIAAgBIgCgBgAAOAtIACAAIgBgBIgBAAgAAjArIAAABIACAAIAAgCgAgeAsIABgBIgBAAgAgOApIAAABIABgBIABgBIgBgBgAATAqIABgBIgBgBgAgWApIABABIAAgCIgBAAgAAXAlIgBACIAAABIABgBIABAAIAAgCIAAgBgAgVAiIgBABIABABIACgCgAgSAQIACAAIABgBIgCgBgAgRAGIABAAIABAAIAAgBIgBAAgAgUgCIABABIABgDIgCAAgAgQgEIABAAIAAgBgAgTgLIABABIABAAIAAgBIgBgBgAgbgKIABAAIAAgBIgBAAgAgZgQIABAAIAAACIABABIACgBIgCgBIAAgBIgBgBgAgcgRIAAgBIgBAAgAgkgTIABABIACgBIgBgBIgBAAIgBAAgAgVgYIABABIABAAIAAgCIAAgCIAAgBgAgbgZIAAgDIgCAAIgCgCIgBABIABABIABABIABAAIABABIABABgAgagcIADABIACgBIABgDIABgBIABAAIAAgCIgBAAIABgBIgCgBIAAACIgBAAIAAgBIgCABIAAABIACAAIABABIgBABIgBACIgBABIgDgBgAgcgjIgBABIABAAIABgCIgCgBIgBAAgAgTgmIAAABIACAAIgBgCIgBgBIAAAAgAgbgmIADAAIACABIACAAIAAgBIgCAAIgCAAIgBgBIgBAAgAgPgrIgBACIACAAIADAAIgBgEIgCABIAAgBIgBgBgAgVgsIgBABIADAAIgBgCgAgcgrIABAAIABgCIgDAAgAAhgvIACAAIAAgCgAgPgxIAAgBIgBAAgAgVg0IgBABIABACIABgBIABgCIgBgBgAAAg4IABAAIAAAAIgBAAgAAPg6IABAAIAAgCIgBAAg");
	this.shape_9.setTransform(481.8,-146.4,1.25,1.25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#E9212D").s().p("ArNCHIAAkOIWbAAIAAEOg");
	this.shape_10.setTransform(539.7,-146.4,1.25,1.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(450,-163.4,179.4,33.9), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#304850").s().p("AgOARIAAghIAdAAIAAAhg");
	this.shape.setTransform(401.4,-58.3,1.25,1.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#304850").s().p("AAOA0IAAhCQABgIgIAAQgHAAgNAIIAABCIgfAAIAAhlIAWAAIADAIQAUgKAVAAQAXAAAAAgIAABHg");
	this.shape_1.setTransform(390.7,-62.6,1.25,1.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#304850").s().p("AgtAMIAAgXQAAgpAtAAQAuAAAAApIAAAXQAAApguAAQgtAAAAgpgAgPgMIAAAZQAAAPAPAAQAQAAAAgPIAAgZQAAgPgQAAQgPAAAAAPg");
	this.shape_2.setTransform(376.5,-62.5,1.25,1.25);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#304850").s().p("AgOBKIAAhmIAdAAIAABmgAgOgoIAAghIAdAAIAAAhg");
	this.shape_3.setTransform(366.1,-65.3,1.25,1.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#304850").s().p("AgTAoIAAg0IgOAAIAAgZIAOAAIAAgYIAdgFIAAAdIAYAAIgCAZIgWAAIAAAwQABAGAFAAQAIAAAFgCIAEAXQgLAEgLAAQgeAAAAgbg");
	this.shape_4.setTransform(357.7,-64.2,1.25,1.25);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#304850").s().p("AgoAWQAAgPAHgHQAHgGAQAAIAVAAIAAgIQAAgIgDgDQgDgDgLAAQgNAAgPADIgEgWQAQgFAVAAQAZAAAJAJQAIAIAAAWIAABAIgYAAIgDgHQgPAJgNAAQgaAAAAgfgAgLAWQAAAIAIAAQAGAAAIgEIAAgMIgNAAQgJAAAAAIg");
	this.shape_5.setTransform(346.4,-62.5,1.25,1.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#304850").s().p("AgsAlIAAgfQAAgkAiAAQAPAAAKADIAAgrIAegEIAACTIgXAAIgDgIQgSAKgNAAQggAAAAgmgAgOAGIAAAfQAAAMALAAQAJAAAJgIIAAgrQgNgCgFAAQgLAAAAAKg");
	this.shape_6.setTransform(332.6,-65.2,1.25,1.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#304850").s().p("AAOA0IAAhCQABgIgIAAQgHAAgNAIIAABCIgfAAIAAhlIAXAAIACAIQAUgKAVAAQAXAAAAAgIAABHg");
	this.shape_7.setTransform(318.7,-62.6,1.25,1.25);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#304850").s().p("AgsATIAAhGIAeAAIAABCQAAAIAIAAQAGAAAOgIIAAhCIAfAAIAABlIgXAAIgDgIQgUAKgUAAQgXAAAAghg");
	this.shape_8.setTransform(304,-62.4,1.25,1.25);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#304850").s().p("AgtAMIAAgXQAAgpAtAAQAuAAAAApIAAAXQAAApguAAQgtAAAAgpgAgPgMIAAAZQAAAPAPAAQAQAAAAgPIAAgZQAAgPgQAAQgPAAAAAPg");
	this.shape_9.setTransform(290,-62.5,1.25,1.25);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#304850").s().p("AgUBKIAAhKIgQAAIAAgZIAQAAIAAgQQAAggAhAAQAMAAAMADIgEAYIgNgCQgHAAgCADQgCADAAAFIAAAMIAYAAIgCAZIgWAAIAABKg");
	this.shape_10.setTransform(278.7,-65.4,1.25,1.25);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#304850").s().p("AgoAWQAAgQAHgGQAHgGAQAAIAVAAIAAgIQAAgIgDgDQgDgDgLAAQgNAAgPADIgEgWQAQgFAVAAQAZAAAJAJQAIAIAAAWIAABAIgZAAIgCgHQgPAJgNAAQgaAAAAgfgAgLAWQAAAIAIAAQAGAAAIgEIAAgMIgNAAQgJAAAAAIg");
	this.shape_11.setTransform(261.5,-62.5,1.25,1.25);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#304850").s().p("AgTAoIAAg0IgOAAIAAgZIAOAAIAAgYIAegFIAAAdIAXAAIgCAZIgVAAIAAAwQAAAGAGAAQAHAAAFgCIAEAXQgLAEgLAAQgeAAAAgbg");
	this.shape_12.setTransform(244.6,-64.2,1.25,1.25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#304850").s().p("AgqALIAAgWQABgpAqAAQAqAAAAAqIAAAUIg2AAIAAADQAAAJADADQAEADAKAAQARAAAOgEIAFAXQgUAGgTAAQgtAAAAgqgAgLgQIAAAFIAZAAIAAgFQAAgNgNAAQgMAAAAANg");
	this.shape_13.setTransform(233.7,-62.5,1.25,1.25);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#304850").s().p("AgtBFIAFgWQAQAEARAAIARgBQAFgCAAgFQAAgFgIAAIgZgDQgMgBgEgDQgGgEAAgKQAAgLAJgHQgOgIAAgSIAAgNQABghApAAQAKAAAHACIAgAAIAAAOIgLAEIADANIAAANQAAAPgKAIQgLAIgUAAIgDAAQgEAEAAACQAAAEADAAIAYADQAOABAFAFQAGAGAAANQAAASgLAHQgLAHgYAAQgVAAgUgFgAgQgmIAAAJQAAAKANAAQANAAAAgKIAAgJQAAgLgNAAQgNAAAAALg");
	this.shape_14.setTransform(221.2,-59.9,1.25,1.25);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#304850").s().p("AgPAZIAMgYIgKAAIAAghIAdAAIAAAkIgSAdg");
	this.shape_15.setTransform(411.4,-83.8,1.25,1.25);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#304850").s().p("AgTAoIAAg0IgOAAIAAgZIAOAAIAAgYIAdgFIAAAdIAYAAIgCAZIgWAAIAAAwQAAAGAHAAQAGAAAGgCIAEAXQgLAEgLAAQgeAAAAgbg");
	this.shape_16.setTransform(403.1,-91.7,1.25,1.25);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#304850").s().p("AglAvIAFgXQAOAFARAAQAFAAACgCQACgCAAgFQAAgFgCgBIgNgFQgSgEgFgGQgEgFAAgQQAAgQAIgHQAJgHAVAAQASAAANADIgDAXQgPgCgNAAQgKAAAAAGQAAAFACACQACABAIACQAVAFAGAHQAFAEAAAQQgBARgHAIQgKAIgUAAQgSAAgTgGg");
	this.shape_17.setTransform(392.9,-90,1.25,1.25);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#304850").s().p("AgqALIAAgWQAAgpArAAQAqAAAAAqIAAAUIg2AAIAAADQAAAJAEADQAEADAJAAQASAAANgEIAFAXQgVAGgSAAQgtAAAAgqgAgLgQIAAAFIAZAAIAAgFQAAgNgMAAQgNAAAAANg");
	this.shape_18.setTransform(380.7,-90,1.25,1.25);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#304850").s().p("AgSAzIgghlIAeAAIAUBHIAVhHIAeAAIggBlg");
	this.shape_19.setTransform(367.8,-90,1.25,1.25);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#304850").s().p("AAPA0IAAhDQAAgHgIAAQgHAAgOAHIAABDIgeAAIAAhlIAXAAIADAHQATgJAUAAQAYAAAAAhIAABGg");
	this.shape_20.setTransform(354,-90.1,1.25,1.25);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#304850").s().p("AgOBJIAAhkIAdAAIAABkgAgOgpIAAgfIAdAAIAAAfg");
	this.shape_21.setTransform(343.1,-92.8,1.25,1.25);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#304850").s().p("AgsATIAAhGIAfAAIAABCQAAAIAGAAQAIAAAOgIIAAhCIAeAAIAABlIgWAAIgEgIQgUAKgTAAQgYAAAAghg");
	this.shape_22.setTransform(326.7,-89.9,1.25,1.25);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#304850").s().p("AgtAMIAAgXQAAgpAtAAQAuAAAAApIAAAXQAAApguAAQgtAAAAgpgAgPgMIAAAZQAAAPAPAAQAQAAAAgPIAAgZQAAgPgQAAQgPAAAAAPg");
	this.shape_23.setTransform(312.6,-90,1.25,1.25);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#304850").s().p("AgVBIIAMgqIgKAAIgfhlIAeAAIAUBIIAVhIIAeAAIgtCPg");
	this.shape_24.setTransform(299.4,-87.4,1.25,1.25);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#304850").s().p("AgqALIAAgWQAAgpArAAQAqAAAAAqIAAAUIg3AAIAAADQAAAJAEADQAEADAKAAQASAAANgEIAEAXQgTAGgTAAQgtAAAAgqgAgMgQIAAAFIAaAAIAAgFQAAgNgNAAQgNAAAAANg");
	this.shape_25.setTransform(280.9,-90,1.25,1.25);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#304850").s().p("AgcA0IAAhlIAZAAIACAKQANgKAOgCIADAcQgUAIgHAGIAAA9g");
	this.shape_26.setTransform(270.8,-90.1,1.25,1.25);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#304850").s().p("AgtAMIAAgXQAAgpAtAAQAuAAAAApIAAAXQAAApguAAQgtAAAAgpgAgPgMIAAAZQAAAPAPAAQAQAAAAgPIAAgZQAAgPgQAAQgPAAAAAPg");
	this.shape_27.setTransform(258.7,-90,1.25,1.25);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#304850").s().p("AgUBKIAAhKIgQAAIAAgZIAQAAIAAgPQAAghAiAAQALAAAMADIgEAXIgNgBQgHAAgCADQgCACAAAGIAAAMIAYAAIgCAZIgWAAIAABKg");
	this.shape_28.setTransform(247.4,-92.9,1.25,1.25);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#304850").s().p("AgpALIAAgWQgBgpAsAAQApAAgBAqIAAAUIg2AAIAAADQAAAJAFADQADADAKAAQARAAAOgEIAEAXQgTAGgTAAQgsAAAAgqgAgMgQIAAAFIAaAAIAAgFQAAgNgMAAQgNAAgBANg");
	this.shape_29.setTransform(235.9,-90,1.25,1.25);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#304850").s().p("AgxBGIAAiLIA2AAQAoAAAAAfIAAAOQAAAPgQAHQAKACAFAGQAGAHAAAKIAAAOQAAAhgpAAgAgRAtIASAAQARAAAAgNIAAgIQABgMgNAAIgXAAgAgRgMIASAAQANAAAAgJIAAgNQAAgJgNAAIgSAAg");
	this.shape_30.setTransform(222.5,-92.4,1.25,1.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(215.5,-102.1,197.9,51.5), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E2F3EF").s().p("A3bNXIAA6tMAu3AAAIAAatg");
	this.shape.setTransform(150,85.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,300,171), null);


(lib.roof = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#4F5F66").s().p("AhOAKIBLghIBSAOIhMAhgAgsAGIAuAHIArgSIgugIg");
	this.shape.setTransform(78.4,9.7,0.8,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#304850").s().p("AglAKIBLghIAAAMIhLAjg");
	this.shape_1.setTransform(81.7,10.8,0.8,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#304850").s().p("AgoAAIAAgNIBRANIAAAOg");
	this.shape_2.setTransform(75.4,11.7,0.8,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#304850").s().p("AhOAKIBLghIBSAOIhMAhg");
	this.shape_3.setTransform(78.4,9.7,0.8,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#939C9F").s().p("AghgqIBDgfIAABzIhDAgg");
	this.shape_4.setTransform(81.4,15.6,0.8,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#5E7376").s().p("AgjAFIAAhFIBHANIAAB0g");
	this.shape_5.setTransform(75.8,16.3,0.8,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#788588").s().p("AlYgRIHqjjIDHEGInqDjg");
	this.shape_6.setTransform(76.8,18.5,0.8,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#304850").s().p("Al8BxIHpjiIEQAAInqDig");
	this.shape_7.setTransform(58,8,0.8,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#5E7376").s().p("AlOCDIDHkGIEOAAIDHEGg");
	this.shape_8.setTransform(38.4,27.6,0.8,0.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.roof, new cjs.Rectangle(11.7,-1,92.8,39.2), null);


(lib.housemask = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E1F3EF").s().p("Ap+LWIAAzAILQAAIH2jrIA3AAIAAWrg");
	this.shape.setTransform(63.9,75.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.housemask, new cjs.Rectangle(0,2.6,127.9,145.1), null);


(lib.house = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BE1F2B").s().p("AA9BjIAAi8Ih5AAIAAC8IgKAAIAAjGICNAAIAADGg");
	this.shape.setTransform(38,40.2,0.8,0.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E8B458").s().p("AgBACIAAgDQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAIAAADQAAAAAAABQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAg");
	this.shape_1.setTransform(41.9,41.5,0.8,0.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E8B458").s().p("AgFAAQAAgFAFAAQAGAAAAAFQAAAGgGAAQgFAAAAgGg");
	this.shape_2.setTransform(41.9,40.7,0.8,0.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BE1F2B").s().p("AgQAlIAAhJIAhAAIAABJg");
	this.shape_3.setTransform(39.8,44.1,0.8,0.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#BE1F2B").s().p("AgQAlIAAhJIAhAAIAABJg");
	this.shape_4.setTransform(36.1,44.1,0.8,0.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BE1F2B").s().p("AgQAlIAAhJIAhAAIAABJg");
	this.shape_5.setTransform(39.8,37.2,0.8,0.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BE1F2B").s().p("AgQAlIAAhJIAhAAIAABJg");
	this.shape_6.setTransform(36.1,37.2,0.8,0.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#FFFFFF").p("AhLAjICWhF");
	this.shape_7.setTransform(94.2,9.1,0.8,0.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FFFFFF").p("AAAgrIAABX");
	this.shape_8.setTransform(94.3,8.9,0.8,0.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#FFFFFF").p("AhLAjICXhF");
	this.shape_9.setTransform(77.8,16.5,0.8,0.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#FFFFFF").p("AAAgrIAABX");
	this.shape_10.setTransform(77.8,16.4,0.8,0.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#FFFFFF").p("AhLAAICXAA");
	this.shape_11.setTransform(53.2,36.2,0.8,0.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#FFFFFF").p("AAAgrIAABX");
	this.shape_12.setTransform(53.2,36.3,0.8,0.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f().s("#FFFFFF").p("AhKAAICVAA");
	this.shape_13.setTransform(22.6,36.2,0.8,0.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").p("AAAgrIAABX");
	this.shape_14.setTransform(22.6,36.3,0.8,0.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgqArQgSgSAAgZQAAgYASgSQASgSAYAAQAZAAASASQASASAAAYQAAAZgSASQgSASgZAAQgYAAgSgSgAgfgfQgOANAAASQAAATAOAOQANANASAAQATAAAOgNQANgOAAgTQAAgSgNgNQgOgOgTAAQgSAAgNAOg");
	this.shape_15.setTransform(38,21.4,0.8,0.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhRgKICkhNIAABiIikBNgAhDgBIAABCICGg/IAAhCg");
	this.shape_16.setTransform(94.2,8.9,0.8,0.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhRgKICjhNIAABiIijBNgAhCgBIAABCICFg/IAAhCg");
	this.shape_17.setTransform(77.8,16.4,0.8,0.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhRAyIAAhjICkAAIAABjgAhDAjICGAAIAAhFIiGAAg");
	this.shape_18.setTransform(53.2,36.2,0.8,0.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhSAyIAAhjIClAAIAABjgAhCAjICGAAIAAhFIiGAAg");
	this.shape_19.setTransform(22.6,36.2,0.8,0.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#5E7376").s().p("AhRgKICkhNIAABiIikBNg");
	this.shape_20.setTransform(94.2,8.9,0.8,0.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#5E7376").s().p("AhRgKICjhNIAABiIijBNg");
	this.shape_21.setTransform(77.8,16.4,0.8,0.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#5E7376").s().p("AhRAyIAAhjICkAAIAABjg");
	this.shape_22.setTransform(53.2,36.2,0.8,0.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#5E7376").s().p("AhSAyIAAhjIClAAIAABjg");
	this.shape_23.setTransform(22.6,36.2,0.8,0.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#E8B458").s().p("AgqArQgSgSAAgZQAAgYASgSQASgSAYAAQAZAAASASQASASAAAYQAAAZgSASQgSASgZAAQgYAAgSgSg");
	this.shape_24.setTransform(38,21.4,0.8,0.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#E52836").s().p("AhGBjIAAjGICNAAIAADGg");
	this.shape_25.setTransform(38,40.2,0.8,0.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#FFFFFF").ss(0.3).p("Aj0BvIHpjd");
	this.shape_26.setTransform(84.8,34.7,0.8,0.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#FFFFFF").ss(0.3).p("Aj0BwIHpjf");
	this.shape_27.setTransform(84.8,29.4,0.8,0.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("#FFFFFF").ss(0.3).p("Aj0BvIHpje");
	this.shape_28.setTransform(84.8,24.1,0.8,0.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f().s("#FFFFFF").ss(0.3).p("Aj0BvIHpjd");
	this.shape_29.setTransform(84.8,18.8,0.8,0.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("#FFFFFF").ss(0.3).p("Aj0BvIHpje");
	this.shape_30.setTransform(84.8,13.5,0.8,0.8);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("#FFFFFF").ss(0.3).p("Aj0BvIHpje");
	this.shape_31.setTransform(84.8,8.2,0.8,0.8);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("#FFFFFF").ss(0.3).p("AlOAAIKcAA");
	this.shape_32.setTransform(38.4,43.6,0.8,0.8);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f().s("#FFFFFF").ss(0.3).p("AlOAAIKcAA");
	this.shape_33.setTransform(38.4,38.4,0.8,0.8);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f().s("#FFFFFF").ss(0.3).p("AlOAAIKcAA");
	this.shape_34.setTransform(38.4,33,0.8,0.8);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f().s("#FFFFFF").ss(0.3).p("AlOAAIKcAA");
	this.shape_35.setTransform(38.4,27.7,0.8,0.8);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f().s("#FFFFFF").ss(0.3).p("AlOAAIKcAA");
	this.shape_36.setTransform(38.4,22.4,0.8,0.8);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f().s("#FFFFFF").ss(0.3).p("AlOAAIKcAA");
	this.shape_37.setTransform(38.4,17.1,0.8,0.8);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#B9E0D4").s().p("ABHhZIGJi2IAAFpImJC1gAnPhZIGii2IAAC2g");
	this.shape_38.setTransform(58,21);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#80C9B6").s().p("AkKC0IAAloIGgAAIB1AAIAAFog");
	this.shape_39.setTransform(38.4,30.1);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#6EAD9D").s().p("Aj+BbIAAi1IH9AAImIC1g");
	this.shape_40.setTransform(78.9,2.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.house, new cjs.Rectangle(10.7,-6.2,94.8,54.4), null);


// stage content:
(lib._728x90_home = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol4();
	this.instance.parent = this;
	this.instance.setTransform(147.5,224.8,1,1,0,0,0,73.5,9.1);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(66).to({_off:false},0).to({alpha:1},15,cjs.Ease.get(-1)).wait(359));

	// Layer 1
	this.instance_1 = new lib.Symbol3();
	this.instance_1.parent = this;
	this.instance_1.setTransform(147.7,194.3,1,1,0,0,0,71.8,13.6);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(51).to({_off:false},0).to({alpha:1},19,cjs.Ease.get(-1)).wait(370));

	// Text
	this.instance_2 = new lib.Symbol2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(149.9,154.1,1,1,0,0,0,78.9,20.6);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(27).to({_off:false},0).wait(1).to({regX:314.4,regY:-76.4,x:385.4,y:56.6,alpha:0.045},0).wait(1).to({y:56,alpha:0.105},0).wait(1).to({y:55.2,alpha:0.189},0).wait(1).to({y:54,alpha:0.31},0).wait(1).to({y:52.4,alpha:0.466},0).wait(1).to({y:51.1,alpha:0.599},0).wait(1).to({y:50.2,alpha:0.69},0).wait(1).to({y:49.5,alpha:0.755},0).wait(1).to({y:49.1,alpha:0.804},0).wait(1).to({y:48.7,alpha:0.842},0).wait(1).to({y:48.4,alpha:0.872},0).wait(1).to({y:48.1,alpha:0.897},0).wait(1).to({y:47.9,alpha:0.917},0).wait(1).to({y:47.8,alpha:0.934},0).wait(1).to({y:47.6,alpha:0.948},0).wait(1).to({y:47.5,alpha:0.96},0).wait(1).to({y:47.4,alpha:0.97},0).wait(1).to({y:47.3,alpha:0.978},0).wait(1).to({alpha:0.984},0).wait(1).to({y:47.2,alpha:0.99},0).wait(1).to({alpha:0.994},0).wait(1).to({y:47.1,alpha:0.996},0).wait(1).to({alpha:0.998},0).wait(1).to({alpha:1},0).wait(1).to({regX:78.9,regY:20.6,x:149.9,y:144.1},0).wait(388));

	// mask_house
	this.instance_3 = new lib.housemask();
	this.instance_3.parent = this;
	this.instance_3.setTransform(153.7,102.8,1,1,0,0,0,63.9,46.4);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(22).to({_off:false},0).wait(1).to({regY:75.1,y:131.5},0).wait(11).to({y:131.4},0).wait(7).to({y:131.3},0).wait(5).to({y:131.2},0).wait(4).to({y:131.1},0).wait(3).to({y:131},0).wait(3).to({y:130.9},0).wait(3).to({y:130.8},0).wait(2).to({y:130.7},0).wait(2).to({y:130.6},0).wait(2).to({y:130.5},0).wait(1).to({y:130.4},0).wait(2).to({y:130.3},0).wait(2).to({y:130.2},0).wait(1).to({y:130.1},0).wait(1).to({y:130},0).wait(2).to({y:129.9},0).wait(1).to({y:129.8},0).wait(1).to({y:129.7},0).wait(1).to({y:129.6},0).wait(1).to({y:129.5},0).wait(1).to({y:129.4},0).wait(1).to({y:129.3},0).wait(1).to({y:129.2},0).wait(1).to({y:129.1},0).wait(1).to({y:129},0).wait(1).to({y:128.9},0).wait(1).to({y:128.7},0).wait(1).to({y:128.6},0).wait(1).to({y:128.5},0).wait(1).to({y:128.3},0).wait(1).to({y:128.2},0).wait(1).to({y:128},0).wait(1).to({y:127.8},0).wait(1).to({y:127.7},0).wait(1).to({y:127.5},0).wait(1).to({y:127.3},0).wait(1).to({y:127.1},0).wait(1).to({y:126.9},0).wait(1).to({y:126.7},0).wait(1).to({y:126.5},0).wait(1).to({y:126.2},0).wait(1).to({y:126},0).wait(1).to({y:125.8},0).wait(1).to({y:125.5},0).wait(1).to({y:125.2},0).wait(1).to({y:125},0).wait(1).to({y:124.7},0).wait(1).to({y:124.4},0).wait(1).to({y:124.1},0).wait(1).to({y:123.8},0).wait(1).to({y:123.5},0).wait(1).to({y:123.2},0).wait(1).to({y:122.9},0).wait(1).to({y:122.6},0).wait(1).to({y:122.3},0).wait(1).to({y:122},0).wait(1).to({y:121.7},0).wait(1).to({y:121.4},0).wait(1).to({y:121.1},0).wait(1).to({y:120.9},0).wait(1).to({y:120.6},0).wait(1).to({y:120.4},0).wait(1).to({y:120.1},0).wait(1).to({y:119.9},0).wait(1).to({y:119.7},0).wait(1).to({y:119.4},0).wait(1).to({y:119.2},0).wait(1).to({y:119},0).wait(1).to({y:118.9},0).wait(1).to({y:118.7},0).wait(1).to({y:118.5},0).wait(1).to({y:118.3},0).wait(1).to({y:118.2},0).wait(1).to({y:118},0).wait(1).to({y:117.9},0).wait(1).to({y:117.7},0).wait(1).to({y:117.6},0).wait(1).to({y:117.5},0).wait(1).to({y:117.3},0).wait(1).to({y:117.2},0).wait(1).to({y:117.1},0).wait(1).to({y:117},0).wait(1).to({y:116.9},0).wait(1).to({y:116.8},0).wait(1).to({y:116.7},0).wait(1).to({y:116.6},0).wait(1).to({y:116.5},0).wait(1).to({y:116.4},0).wait(1).to({y:116.3},0).wait(1).to({y:116.2},0).wait(1).to({y:116.1},0).wait(2).to({y:116},0).wait(1).to({y:115.9},0).wait(2).to({y:115.8},0).wait(1).to({y:115.7},0).wait(2).to({y:115.6},0).wait(2).to({y:115.5},0).wait(1).to({y:115.4},0).wait(2).to({y:115.3},0).wait(3).to({y:115.2},0).wait(2).to({y:115.1},0).wait(3).to({y:115},0).wait(3).to({y:114.9},0).wait(3).to({y:114.8},0).wait(4).to({y:114.7},0).wait(6).to({y:114.6},0).wait(8).to({y:114.5},0).wait(11).to({regY:46.4,y:85.8},0).wait(235));

	// tree
	this.instance_4 = new lib.tree();
	this.instance_4.parent = this;
	this.instance_4.setTransform(94.6,-23.7,1,1,0,0,0,12.4,21.2);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(6).to({_off:false},0).wait(1).to({regY:21.3,y:-23.3},0).wait(1).to({x:94.7,y:-22.7},0).wait(1).to({x:94.8,y:-21.3},0).wait(1).to({x:95,y:-19.1},0).wait(1).to({x:95.2,y:-15.5},0).wait(1).to({x:95.7,y:-9.6},0).wait(1).to({x:96.5,y:0.4},0).wait(1).to({x:97.8,y:17.3},0).wait(1).to({x:99.1,y:34},0).wait(1).to({x:100,y:44.6},0).wait(1).to({x:100.5,y:51.3},0).wait(1).to({x:100.8,y:55.8},0).wait(1).to({x:101.1,y:59.1},0).wait(1).to({x:101.3,y:61.4},0).wait(1).to({x:101.4,y:63},0).wait(1).to({x:101.5,y:64.2},0).wait(1).to({x:101.6,y:64.9},0).wait(1).to({y:65.3},0).wait(1).to({regY:21.2},0).wait(1).to({regY:21.3,y:65.4},0).wait(11).to({y:65.3},0).wait(7).to({y:65.2},0).wait(5).to({y:65.1},0).wait(4).to({y:65},0).wait(3).to({y:64.9},0).wait(3).to({y:64.8},0).wait(3).to({y:64.7},0).wait(2).to({y:64.6},0).wait(2).to({y:64.5},0).wait(2).to({y:64.4},0).wait(1).to({y:64.3},0).wait(2).to({y:64.2},0).wait(1).to({y:64.1},0).wait(2).to({y:64},0).wait(1).to({y:63.9},0).wait(1).to({y:63.8},0).wait(1).to({y:63.7},0).wait(1).to({y:63.6},0).wait(1).to({y:63.5},0).wait(1).to({y:63.4},0).wait(1).to({y:63.3},0).wait(1).to({y:63.2},0).wait(1).to({y:63.1},0).wait(1).to({y:63},0).wait(1).to({y:62.8},0).wait(1).to({y:62.7},0).wait(1).to({y:62.6},0).wait(1).to({y:62.4},0).wait(1).to({y:62.3},0).wait(1).to({y:62.1},0).wait(1).to({y:61.9},0).wait(1).to({y:61.7},0).wait(1).to({y:61.5},0).wait(1).to({y:61.3},0).wait(1).to({y:61.1},0).wait(1).to({y:60.8},0).wait(1).to({y:60.6},0).wait(1).to({y:60.3},0).wait(1).to({y:60.1},0).wait(1).to({y:59.8},0).wait(1).to({y:59.5},0).wait(1).to({y:59.2},0).wait(1).to({y:58.8},0).wait(1).to({y:58.5},0).wait(1).to({y:58.2},0).wait(1).to({y:57.8},0).wait(1).to({y:57.5},0).wait(1).to({y:57.2},0).wait(1).to({y:56.8},0).wait(1).to({y:56.5},0).wait(1).to({y:56.2},0).wait(1).to({y:55.9},0).wait(1).to({y:55.6},0).wait(1).to({y:55.3},0).wait(1).to({y:55.1},0).wait(1).to({y:54.8},0).wait(1).to({y:54.6},0).wait(1).to({y:54.3},0).wait(1).to({y:54.1},0).wait(1).to({y:53.9},0).wait(1).to({y:53.7},0).wait(1).to({y:53.5},0).wait(1).to({y:53.4},0).wait(1).to({y:53.2},0).wait(1).to({y:53},0).wait(1).to({y:52.9},0).wait(1).to({y:52.7},0).wait(1).to({y:52.6},0).wait(1).to({y:52.5},0).wait(1).to({y:52.3},0).wait(1).to({y:52.2},0).wait(1).to({y:52.1},0).wait(1).to({y:52},0).wait(1).to({y:51.9},0).wait(1).to({y:51.8},0).wait(1).to({y:51.7},0).wait(1).to({y:51.6},0).wait(1).to({y:51.5},0).wait(1).to({y:51.4},0).wait(1).to({y:51.3},0).wait(1).to({y:51.2},0).wait(2).to({y:51.1},0).wait(1).to({y:51},0).wait(1).to({y:50.9},0).wait(2).to({y:50.8},0).wait(1).to({y:50.7},0).wait(2).to({y:50.6},0).wait(2).to({y:50.5},0).wait(2).to({y:50.4},0).wait(2).to({y:50.3},0).wait(2).to({y:50.2},0).wait(2).to({y:50.1},0).wait(3).to({y:50},0).wait(3).to({y:49.9},0).wait(3).to({y:49.8},0).wait(4).to({y:49.7},0).wait(4).to({y:49.6},0).wait(6).to({y:49.5},0).wait(9).to({y:49.4},0).wait(13).to({regY:21.2,y:49.3},0).wait(235));

	// roof
	this.instance_5 = new lib.roof();
	this.instance_5.parent = this;
	this.instance_5.setTransform(153.3,-72.5,1,1,0,0,0,58,24.5);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(3).to({_off:false},0).wait(1).to({regY:18.5,y:-78.2},0).wait(1).to({y:-77.4},0).wait(1).to({y:-75.8},0).wait(1).to({y:-73.2},0).wait(1).to({y:-68.9},0).wait(1).to({y:-62},0).wait(1).to({y:-50.2},0).wait(1).to({y:-30.3},0).wait(1).to({y:-10.5},0).wait(1).to({y:2},0).wait(1).to({y:9.9},0).wait(1).to({y:15.3},0).wait(1).to({y:19},0).wait(1).to({y:21.8},0).wait(1).to({y:23.7},0).wait(1).to({y:25},0).wait(1).to({y:25.9},0).wait(1).to({y:26.4},0).wait(1).to({regY:24.5,y:32.5},0).wait(1).to({regY:18.5,y:26.5},0).wait(9).to({y:26.6},0).wait(7).to({y:26.7},0).wait(5).to({y:26.8},0).wait(4).to({y:26.9},0).wait(3).to({y:27},0).wait(2).to({y:27.1},0).wait(3).to({y:27.2},0).wait(2).to({y:27.3},0).wait(2).to({y:27.4},0).wait(2).to({y:27.5},0).wait(2).to({y:27.6},0).wait(1).to({y:27.7},0).wait(2).to({y:27.8},0).wait(1).to({y:27.9},0).wait(2).to({y:28},0).wait(1).to({y:28.1},0).wait(1).to({y:28.2},0).wait(2).to({y:28.3},0).wait(1).to({y:28.4},0).wait(1).to({y:28.5},0).wait(1).to({y:28.6},0).wait(1).to({y:28.7},0).wait(1).to({y:28.8},0).wait(1).to({y:28.9},0).wait(1).to({y:29},0).wait(1).to({y:29.1},0).wait(1).to({y:29.2},0).wait(1).to({y:29.3},0).wait(1).to({y:29.5},0).wait(1).to({y:29.6},0).wait(1).to({y:29.7},0).wait(1).to({y:29.8},0).wait(1).to({y:30},0).wait(1).to({y:30.1},0).wait(1).to({y:30.3},0).wait(1).to({y:30.4},0).wait(1).to({y:30.6},0).wait(1).to({y:30.7},0).wait(1).to({y:30.9},0).wait(1).to({y:31.1},0).wait(1).to({y:31.2},0).wait(1).to({y:31.4},0).wait(1).to({y:31.6},0).wait(1).to({y:31.8},0).wait(1).to({y:32},0).wait(1).to({y:32.2},0).wait(1).to({y:32.4},0).wait(1).to({y:32.6},0).wait(1).to({y:32.9},0).wait(1).to({y:33.1},0).wait(1).to({y:33.4},0).wait(1).to({y:33.6},0).wait(1).to({y:33.9},0).wait(1).to({y:34.2},0).wait(1).to({y:34.4},0).wait(1).to({y:34.7},0).wait(1).to({y:35},0).wait(1).to({y:35.3},0).wait(1).to({y:35.7},0).wait(1).to({y:36},0).wait(1).to({y:36.4},0).wait(1).to({y:36.7},0).wait(1).to({y:37.1},0).wait(1).to({y:37.5},0).wait(1).to({y:37.9},0).wait(1).to({y:38.3},0).wait(1).to({y:38.7},0).wait(1).to({y:39.1},0).wait(1).to({y:39.6},0).wait(1).to({y:40},0).wait(1).to({y:40.5},0).wait(1).to({y:40.9},0).wait(1).to({y:41.4},0).wait(1).to({y:41.9},0).wait(1).to({y:42.4},0).wait(1).to({y:42.9},0).wait(1).to({y:43.4},0).wait(1).to({y:43.8},0).wait(1).to({y:44.3},0).wait(1).to({y:44.8},0).wait(1).to({y:45.3},0).wait(1).to({y:45.7},0).wait(1).to({y:46.2},0).wait(1).to({y:46.6},0).wait(1).to({y:47},0).wait(1).to({y:47.4},0).wait(1).to({y:47.8},0).wait(1).to({y:48.2},0).wait(1).to({y:48.5},0).wait(1).to({y:48.9},0).wait(1).to({y:49.2},0).wait(1).to({y:49.5},0).wait(1).to({y:49.8},0).wait(1).to({y:50.1},0).wait(1).to({y:50.4},0).wait(1).to({y:50.7},0).wait(1).to({y:50.9},0).wait(1).to({y:51.2},0).wait(1).to({y:51.4},0).wait(1).to({y:51.6},0).wait(1).to({y:51.9},0).wait(1).to({y:52.1},0).wait(1).to({y:52.3},0).wait(1).to({y:52.4},0).wait(1).to({y:52.6},0).wait(1).to({y:52.8},0).wait(1).to({y:52.9},0).wait(1).to({y:53.1},0).wait(1).to({y:53.2},0).wait(1).to({y:53.4},0).wait(1).to({y:53.5},0).wait(1).to({y:53.6},0).wait(1).to({y:53.8},0).wait(1).to({y:53.9},0).wait(1).to({y:54},0).wait(1).to({y:54.1},0).wait(1).to({y:54.2},0).wait(1).to({y:54.3},0).wait(1).to({y:54.4},0).wait(1).to({y:54.5},0).wait(1).to({y:54.6},0).wait(2).to({y:54.7},0).wait(1).to({y:54.8},0).wait(2).to({y:54.9},0).wait(1).to({y:55},0).wait(2).to({y:55.1},0).wait(3).to({y:55.2},0).wait(2).to({y:55.3},0).wait(3).to({y:55.4},0).wait(5).to({y:55.5},0).wait(7).to({regY:24.5,y:61.5},0).wait(235));

	// hosuey
	this.instance_6 = new lib.house();
	this.instance_6.parent = this;
	this.instance_6.setTransform(153.3,-36.8,1,1,0,0,0,58,34);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({regX:58.1,regY:21,x:153.4,y:-49.5},0).wait(1).to({y:-48.7},0).wait(1).to({y:-47.1},0).wait(1).to({y:-44.5},0).wait(1).to({y:-40.2},0).wait(1).to({y:-33.3},0).wait(1).to({y:-21.5},0).wait(1).to({y:-1.6},0).wait(1).to({y:18.2},0).wait(1).to({y:30.6},0).wait(1).to({y:38.5},0).wait(1).to({y:43.9},0).wait(1).to({y:47.7},0).wait(1).to({y:50.5},0).wait(1).to({y:52.4},0).wait(1).to({y:53.7},0).wait(1).to({y:54.6},0).wait(1).to({y:55.1},0).wait(1).to({regX:58,regY:34,x:153.3,y:68.2},0).wait(4).to({regX:58.1,regY:21,x:153.4,y:55.2},0).wait(10).to({y:55.3},0).wait(7).to({y:55.4},0).wait(5).to({y:55.5},0).wait(3).to({y:55.6},0).wait(4).to({y:55.7},0).wait(2).to({y:55.8},0).wait(3).to({y:55.9},0).wait(2).to({y:56},0).wait(2).to({y:56.1},0).wait(2).to({y:56.2},0).wait(2).to({y:56.3},0).wait(2).to({y:56.4},0).wait(1).to({y:56.5},0).wait(2).to({y:56.6},0).wait(1).to({y:56.7},0).wait(2).to({y:56.8},0).wait(1).to({y:56.9},0).wait(1).to({y:57},0).wait(1).to({y:57.1},0).wait(1).to({y:57.2},0).wait(2).to({y:57.3},0).wait(1).to({y:57.4},0).wait(1).to({y:57.5},0).wait(1).to({y:57.6},0).wait(1).to({y:57.7},0).wait(1).to({y:57.8},0).wait(1).to({y:58},0).wait(1).to({y:58.1},0).wait(1).to({y:58.2},0).wait(1).to({y:58.3},0).wait(1).to({y:58.4},0).wait(1).to({y:58.6},0).wait(1).to({y:58.7},0).wait(1).to({y:58.8},0).wait(1).to({y:59},0).wait(1).to({y:59.1},0).wait(1).to({y:59.3},0).wait(1).to({y:59.4},0).wait(1).to({y:59.6},0).wait(1).to({y:59.8},0).wait(1).to({y:60},0).wait(1).to({y:60.1},0).wait(1).to({y:60.3},0).wait(1).to({y:60.5},0).wait(1).to({y:60.7},0).wait(1).to({y:60.9},0).wait(1).to({y:61.1},0).wait(1).to({y:61.4},0).wait(1).to({y:61.6},0).wait(1).to({y:61.8},0).wait(1).to({y:62.1},0).wait(1).to({y:62.3},0).wait(1).to({y:62.6},0).wait(1).to({y:62.9},0).wait(1).to({y:63.1},0).wait(1).to({y:63.4},0).wait(1).to({y:63.7},0).wait(1).to({y:64},0).wait(1).to({y:64.4},0).wait(1).to({y:64.7},0).wait(1).to({y:65.1},0).wait(1).to({y:65.4},0).wait(1).to({y:65.8},0).wait(1).to({y:66.2},0).wait(1).to({y:66.5},0).wait(1).to({y:66.9},0).wait(1).to({y:67.4},0).wait(1).to({y:67.8},0).wait(1).to({y:68.2},0).wait(1).to({y:68.6},0).wait(1).to({y:69.1},0).wait(1).to({y:69.5},0).wait(1).to({y:70},0).wait(1).to({y:70.4},0).wait(1).to({y:70.9},0).wait(1).to({y:71.3},0).wait(1).to({y:71.8},0).wait(1).to({y:72.2},0).wait(1).to({y:72.7},0).wait(1).to({y:73.1},0).wait(1).to({y:73.5},0).wait(1).to({y:73.9},0).wait(1).to({y:74.3},0).wait(1).to({y:74.7},0).wait(1).to({y:75},0).wait(1).to({y:75.4},0).wait(1).to({y:75.7},0).wait(1).to({y:76},0).wait(1).to({y:76.4},0).wait(1).to({y:76.6},0).wait(1).to({y:76.9},0).wait(1).to({y:77.2},0).wait(1).to({y:77.5},0).wait(1).to({y:77.7},0).wait(1).to({y:78},0).wait(1).to({y:78.2},0).wait(1).to({y:78.4},0).wait(1).to({y:78.6},0).wait(1).to({y:78.8},0).wait(1).to({y:79},0).wait(1).to({y:79.2},0).wait(1).to({y:79.4},0).wait(1).to({y:79.5},0).wait(1).to({y:79.7},0).wait(1).to({y:79.8},0).wait(1).to({y:80},0).wait(1).to({y:80.1},0).wait(1).to({y:80.2},0).wait(1).to({y:80.4},0).wait(1).to({y:80.5},0).wait(1).to({y:80.6},0).wait(1).to({y:80.7},0).wait(1).to({y:80.8},0).wait(1).to({y:80.9},0).wait(1).to({y:81},0).wait(1).to({y:81.1},0).wait(1).to({y:81.2},0).wait(2).to({y:81.3},0).wait(1).to({y:81.4},0).wait(1).to({y:81.5},0).wait(2).to({y:81.6},0).wait(2).to({y:81.7},0).wait(2).to({y:81.8},0).wait(2).to({y:81.9},0).wait(3).to({y:82},0).wait(3).to({y:82.1},0).wait(5).to({y:82.2},0).wait(7).to({regX:58,regY:34,x:153.3,y:95.2},0).wait(235));

	// teal
	this.instance_7 = new lib.Symbol1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(364,47.5,2.447,0.673,0,0,0,150,85.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(440));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(361,-32,734,182);
// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;