(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"300x600_pandamonium_atlas_", frames: [[0,602,300,227],[0,831,300,158],[302,0,151,126],[302,128,99,58],[0,0,300,600]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.bb_pandas = function() {
	this.spriteSheet = ss["300x600_pandamonium_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.BB_PENGUINS = function() {
	this.spriteSheet = ss["300x600_pandamonium_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.BB_REDPANDA = function() {
	this.spriteSheet = ss["300x600_pandamonium_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.calzooLogo = function() {
	this.spriteSheet = ss["300x600_pandamonium_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.db_bg = function() {
	this.spriteSheet = ss["300x600_pandamonium_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgXA/QgMgEgKgHQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAABgBIANgQQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAABQAHAFAHACQAHADAIAAQAIAAAFgDQAFgEAAgHQAAgHgLgEIgJgEIgKgDQgSgGgHgGQgFgFgCgHQgDgGAAgJQAAgIADgGQAEgGAGgFQAGgFAJgDQAKgCAKAAQATAAAUALQAAABABAAQAAAAAAABQAAAAAAABQAAABAAAAIgMASQAAAAgBABQAAAAAAAAQgBAAgBAAQAAAAgBgBQgMgIgMAAQgJAAgFADQgEACgBAFQAAAHANAFIAMAEIANAFQAOAFAHAIQAHAJAAAOQAAARgNALQgHAGgJADQgJACgKAAQgMAAgLgDg");
	this.shape.setTransform(40.4,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAgBBIgCgBIg7hRIAABPQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgVAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAh7QAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIAVAAIACACIA6BPIAAhOQAAgBAAAAQABgBAAAAQAAAAABgBQABAAAAAAIAVAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAAB7QAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_1.setTransform(27.2,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgZA+QgMgEgKgKQgKgKgFgLQgFgNAAgOQAAgNAFgMQAFgMAKgJQAUgUAbABQAOAAAMAEQAMAFAKAKQAUASAAAcQAAAdgUATQgUATgcgBQgNABgMgFgAgagbQgMAMAAAPQAAAIADAIQADAGAFAGQAGAGAHADQAHADAHAAQAIAAAHgDQAHgDAGgGQALgLAAgRQAAgHgDgHQgDgHgFgGQgMgLgQAAQgPAAgLALg");
	this.shape_2.setTransform(11.6,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXA/QgMgEgKgHQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAABgBIANgQQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAABQAHAFAHACQAHADAIAAQAIAAAFgDQAFgEAAgHQAAgHgLgEIgJgEIgKgDQgSgGgHgGQgFgFgCgHQgDgGAAgJQAAgIADgGQAEgGAGgFQAGgFAJgDQAKgCAKAAQATAAAUALQAAABABAAQAAAAAAABQAAAAAAABQAAABAAAAIgMASQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBgBQgMgIgMAAQgJAAgFADQgEACgBAFQAAAHANAFIAMAEIANAFQAOAFAHAIQAHAJAAAOQAAARgNALQgHAGgJADQgJACgKAAQgMAAgLgDg");
	this.shape_3.setTransform(-2.2,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAgBBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAgBgBIgHgXIgrAAIgIAXQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBABgBIAth6QAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAAAIAXAAQAAAAABAAQAAAAAAABQABAAAAABQAAAAABABIAsB7QABABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAgAgNAPIAbAAIgOgrg");
	this.shape_4.setTransform(-14.4,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguBBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBgBAAAAIAAh7QAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIBdAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAAUQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAIhDAAIAAAbIA4AAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAASQAAABAAABQAAAAAAAAQgBABAAAAQgBAAgBAAIg4AAIAAAcIBDAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAUQAAAAAAABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_5.setTransform(-26.6,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAUBBQgCAAgCgDIgUgqIgUAAIAAAqQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgXAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAh7QAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIA9AAQARAAAMANQAGAGADAIQADAHAAAJQAAAOgIAKQgIALgMAEIAXArIABACQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAgAgYgDIAeAAQAGAAAGgFQADgCABgEQACgDAAgEQAAgEgCgEIgEgGQgGgEgGAAIgeAAg");
	this.shape_6.setTransform(-39.9,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-48.7,-13.1,97.5,26.3);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgXA/QgMgEgKgHQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAABgBIANgQQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAABQAHAFAHACQAHADAIAAQAIAAAFgDQAFgEAAgHQAAgHgLgEIgJgEIgKgDQgSgGgHgGQgFgFgCgHQgDgGAAgJQAAgIADgGQAEgGAGgFQAGgFAJgDQAKgCAKAAQATAAAUALQAAABABAAQAAAAAAABQAAAAAAABQAAABAAAAIgMASQAAAAgBABQAAAAAAAAQgBAAgBAAQAAAAgBgBQgMgIgMAAQgJAAgFADQgEACgBAFQAAAHANAFIAMAEIANAFQAOAFAHAIQAHAJAAAOQAAARgNALQgHAGgJADQgJACgKAAQgMAAgLgDg");
	this.shape.setTransform(40.4,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAgBBIgCgBIg7hRIAABPQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgVAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAh7QAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIAVAAIACACIA6BPIAAhOQAAgBAAAAQABgBAAAAQAAAAABgBQABAAAAAAIAVAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAAB7QAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_1.setTransform(27.2,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgZA+QgMgEgKgKQgKgKgFgLQgFgNAAgOQAAgNAFgMQAFgMAKgJQAUgUAbABQAOAAAMAEQAMAFAKAKQAUASAAAcQAAAdgUATQgUATgcgBQgNABgMgFgAgagbQgMAMAAAPQAAAIADAIQADAGAFAGQAGAGAHADQAHADAHAAQAIAAAHgDQAHgDAGgGQALgLAAgRQAAgHgDgHQgDgHgFgGQgMgLgQAAQgPAAgLALg");
	this.shape_2.setTransform(11.6,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXA/QgMgEgKgHQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAABgBIANgQQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAABQAHAFAHACQAHADAIAAQAIAAAFgDQAFgEAAgHQAAgHgLgEIgJgEIgKgDQgSgGgHgGQgFgFgCgHQgDgGAAgJQAAgIADgGQAEgGAGgFQAGgFAJgDQAKgCAKAAQATAAAUALQAAABABAAQAAAAAAABQAAAAAAABQAAABAAAAIgMASQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBgBQgMgIgMAAQgJAAgFADQgEACgBAFQAAAHANAFIAMAEIANAFQAOAFAHAIQAHAJAAAOQAAARgNALQgHAGgJADQgJACgKAAQgMAAgLgDg");
	this.shape_3.setTransform(-2.2,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAgBBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAgBgBIgHgXIgrAAIgIAXQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBABgBIAth6QAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAAAIAXAAQAAAAABAAQAAAAAAABQABAAAAABQAAAAABABIAsB7QABABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAgAgNAPIAbAAIgOgrg");
	this.shape_4.setTransform(-14.4,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguBBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBgBAAAAIAAh7QAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIBdAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAAUQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAIhDAAIAAAbIA4AAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAASQAAABAAABQAAAAAAAAQgBABAAAAQgBAAgBAAIg4AAIAAAcIBDAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAUQAAAAAAABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_5.setTransform(-26.6,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAUBBQgCAAgCgDIgUgqIgUAAIAAAqQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgXAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAh7QAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIA9AAQARAAAMANQAGAGADAIQADAHAAAJQAAAOgIAKQgIALgMAEIAXArIABACQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAgAgYgDIAeAAQAGAAAGgFQADgCABgEQACgDAAgEQAAgEgCgEIgEgGQgGgEgGAAIgeAAg");
	this.shape_6.setTransform(-39.9,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-48.7,-13.1,97.5,26.3);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgmA0QgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhhQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIAsAAQAPAAAKALQAKAKAAAPQAAAPgKAKQgFAFgGADQgHADgHAAIgYAAIAAAcQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAgAgSABIATAAQAHAAAFgDIAEgFIABgIQAAgDgBgEQgBgDgDgCQgCgCgDgBIgHgBIgTAAg");
	this.shape.setTransform(197.5,243.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgIA0QgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhhQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIARAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAABhQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_1.setTransform(189.9,243.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAXA0QAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgnIgpAAIAAAnQAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgSAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhhQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIASAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAAAnIApAAIAAgnQAAgBAAAAQAAgBAAAAQABAAAAAAQABgBAAAAIASAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAABhQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_2.setTransform(182.1,243.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgTAyQgJgDgIgGQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBABAAIAKgNQABgBAAAAQAAAAABAAQAAAAAAAAQABAAAAAAQAGAEAFACQAGACAGAAQAGAAAEgCQAEgDAAgGQAAgFgIgEIgHgCIgIgDQgPgFgFgFQgEgEgCgFQgCgFAAgHQAAgGACgFQADgFAFgEQAFgEAHgCQAHgCAJAAQAPAAAPAJQABAAAAABQAAAAABAAQAAABAAAAQAAABgBAAIgJAOQAAABgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgKgHgKAAQgGAAgEACQgEACAAAEQAAAGAKADIAJAEIAKAEQAMAEAGAGQAFAHAAALQAAAOgLAJQgFAEgHACQgHADgIAAQgKAAgJgDg");
	this.shape_3.setTransform(172.4,243.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAQA0QgBAAAAgBQAAAAgBAAQAAAAAAgBQgBAAAAgBIgQghIgPAAIAAAhQgBABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIgSAAQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhhQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIAxAAQANAAAKAKQAEAGADAFQACAGAAAIQAAALgGAHQgGAJgKADIASAiIABACQAAABAAAAQAAAAAAAAQgBAAAAAAQAAABgBAAgAgSgDIAXAAQAFAAAEgDIAEgFIABgFIgBgHIgEgEQgEgEgFAAIgXAAg");
	this.shape_4.setTransform(163.5,243.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgkA0QgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhhQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIBJAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIAAAPQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIg1AAIAAAWIAtAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAPQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIgtAAIAAAVIA1AAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIAAAPQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_5.setTransform(153.9,243.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgjA0QgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhhQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIAiAAQAKAAAJAGQAMAHAAANQAAAQgNAGIAAABQALACAFAHQAFAGAAALQAAAOgLAHQgKAHgOAAgAgPAfIAPAAQAGAAAEgCQAFgCAAgGQAAgMgUAAIgKAAgAgPgJIAFAAQARAAAAgNQAAgFgFgCQgCgCgEAAIgLAAg");
	this.shape_6.setTransform(144.6,243.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAgA0QAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAg6IgUAiIgDACIgNAAIgDgCIgUgiIAAA6QAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgRAAQgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhhQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIASAAIACADIAcAwIAdgwIACgDIASAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAABhQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_7.setTransform(133.2,243.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgkA0QgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhhQAAgBAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIBJAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIAAAPQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIg1AAIAAAWIAtAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAPQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIgtAAIAAAVIA1AAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIAAAPQAAABAAAAQAAABAAAAQgBAAAAAAQAAABgBAAg");
	this.shape_8.setTransform(122.6,243.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAgA0QAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAg6IgUAiIgDACIgNAAIgDgCIgUgiIAAA6QAAABAAAAQAAABAAAAQgBAAAAAAQgBABAAAAIgSAAQAAAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhhQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBAAAAIATAAIACADIAcAwIAdgwIACgDIASAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAABhQAAABAAAAQAAABAAAAQAAAAgBAAQAAABgBAAg");
	this.shape_9.setTransform(111.2,243.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAaA0QgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIgGgSIgiAAIgGASQgBABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAIgTAAQgBAAgBAAQAAgBAAAAQAAAAAAgBQAAgBAAAAIAkhhQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIASAAQAAAAAAAAQAAABABAAQAAAAAAABQAAAAABABIAjBhQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAgAgKAMIAVAAIgLgig");
	this.shape_10.setTransform(96.1,243.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgIA0QgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAguIgmgzIgBgCQAAAAABAAQAAAAAAAAQAAAAAAAAQABgBAAAAIAXAAQABAAAAABQABAAAAAAQABAAAAABQABAAAAABIAUAgIAVghQAAAAABAAQAAgBABAAQAAAAABAAQAAgBABAAIAXAAQAAAAABABQAAAAAAAAQAAAAAAAAQAAAAAAAAIAAACIgmAzIAAAuQAAABAAAAQAAABgBAAQAAAAAAAAQgBABAAAAg");
	this.shape_11.setTransform(82.6,243.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgRAxQgIgDgFgFIgFgGIgEgHQgCgIAAgKIAAg7QAAAAAAgBQAAAAAAgBQABAAAAAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAA5QAAALAFAGQAFAGAJAAQAKAAAFgGQAFgGAAgLIAAg5QAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAA7QgBAMgCAGQgDAHgFAGQgFAFgIADQgIADgKAAQgMgBgFgCg");
	this.shape_12.setTransform(72.6,243.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgjA0QgBAAAAgBQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAhhQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIAiAAQAKAAAJAGQAMAHAAANQAAAQgNAGIAAABQALACAFAHQAFAGAAALQAAAOgLAHQgKAHgOAAgAgPAfIAPAAQAGAAAEgCQAFgCAAgGQAAgMgUAAIgKAAgAgPgJIAFAAQARAAAAgNQAAgFgFgCQgCgCgEAAIgLAAg");
	this.shape_13.setTransform(63.1,243.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(2,1,1).p("AtZicIazAAIAAE5I6zAAg");
	this.shape_14.setTransform(129.8,243.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol9, new cjs.Rectangle(43,227,173.7,33.3), null);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.calzooLogo();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol7, new cjs.Rectangle(0,0,99,58), null);


(lib.Symbol5copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag2BBQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAh7QAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAyAAQANAAALAFQAMAFAJAJQARASAAAbQAAAOgFALQgEAMgKAJQgKAJgLAFQgMAFgMAAgAgdAoIAUAAQAIAAAGgDQAHgDAGgGQALgLAAgRQAAgJgDgIQgEgIgHgGQgDgDgFgCQgFgCgFgBIgHAAIgLAAIgIAAg");
	this.shape.setTransform(84.2,13.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZA+QgMgEgKgKQgKgKgFgLQgFgMAAgOQAAgOAFgMQAFgMAKgKQAUgSAbgBQAOAAAMAGQAMAEAKAJQAUAUAAAcQAAAcgUAUQgUARgcAAQgNAAgMgEgAgagaQgMALAAAQQAAAHADAHQADAHAFAHQAGAFAHADQAHADAHAAQAIAAAHgDQAHgDAGgFQALgMAAgQQAAgIgDgHQgDgHgFgFQgMgMgQgBQgPABgLAMg");
	this.shape_1.setTransform(69.4,13.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgZA+QgMgEgKgKQgKgKgFgLQgFgMAAgOQAAgOAFgMQAFgMAKgKQAUgSAbgBQAOAAAMAGQAMAEAKAJQAUAUAAAcQAAAcgUAUQgUARgcAAQgNAAgMgEgAgagaQgMALAAAQQAAAHADAHQADAHAFAHQAGAFAHADQAHADAHAAQAIAAAHgDQAHgDAGgFQALgMAAgQQAAgIgDgHQgDgHgFgFQgMgMgQgBQgPABgLAMg");
	this.shape_2.setTransform(54.4,13.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUA+QgMgFgJgKQgKgJgFgNQgFgLAAgOQAAgNAFgMQAFgLAKgKQAKgKAMgFQAMgEANAAQAUAAAUANQABAAAAABQABAAAAABQAAAAgBABQAAAAAAABIgMASQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQgGgFgHgDQgGgCgGAAQgPAAgLAMQgGAGgDAHQgCAHAAAHQAAAQALAMQALAMAPAAQARgBALgHIAAgLIgYAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgUQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAxAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAABAQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIgWAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgBQgOAFgOABQgOAAgMgFg");
	this.shape_3.setTransform(39.4,13.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgZA+QgMgEgKgKQgKgKgFgLQgFgMAAgOQAAgOAFgMQAFgMAKgKQAUgSAbgBQAOAAAMAGQAMAEAKAJQAUAUAAAcQAAAcgUAUQgUARgcAAQgNAAgMgEgAgagaQgMALAAAQQAAAHADAHQADAHAFAHQAGAFAHADQAHADAHAAQAIAAAHgDQAHgDAGgFQALgMAAgQQAAgIgDgHQgDgHgFgFQgMgMgQgBQgPABgLAMg");
	this.shape_4.setTransform(20,13.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXA/QgMgEgKgHQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAABgBIANgQQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAABQAHAFAHACQAHADAIAAQAIAAAFgDQAFgEAAgHQAAgHgLgEIgJgEIgKgDQgSgGgHgGQgFgFgCgHQgDgGAAgJQAAgIADgGQAEgGAGgFQAGgFAJgDQAKgCAKAAQATAAAUALQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAIgMASQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBgBQgMgIgMAAQgJAAgFADQgEACgBAFQAAAHANAFIAMAEIANAFQAOAFAHAIQAHAJAAAOQAAARgNALQgHAGgJADQgJACgKAAQgMAAgLgDg");
	this.shape_5.setTransform(7.3,13.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5copy, new cjs.Rectangle(0,0,92.9,26.3), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhaBrQgEAAgBgFIAAjLQABgFAEAAIBTAAQAWAAATAIQASAIAPAQQAcAdAAAtQAAAXgHATQgIATgPAPQgRAPgSAIQgUAIgVAAgAgwBCIAgAAQAOAAALgFQALgEAJgKQATgUAAgbQAAgPgGgNQgFgOgMgKQgGgFgHgDQgJgEgJgBIgKAAIgTAAIgNAAg");
	this.shape.setTransform(242.2,55.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhMBrQgFAAAAgFIAAjLQAAgFAFAAICZAAQAFAAAAAFIAAAgQAAAFgFAAIhvAAIAAArIBfAAQAEAAAAAFIAAAgQAAAEgEAAIhfAAIAAAtIBvAAQAFAAAAAFIAAAgQAAAFgFAAg");
	this.shape_1.setTransform(221.5,55.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAgBrQgFAAgCgEIgyhOIgMAQIAAA9QAAAFgFAAIglAAQgFAAAAgFIAAjLQAAgFAFAAIAlAAQAFAAAAAFIAABNIA5hNQADgFAEAAIAyAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIgBAEIhJBZIBPBwQAAAAAAABQAAAAABABQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAAAQgBAAAAABQgBAAAAAAg");
	this.shape_2.setTransform(202.3,55.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgqBmQgUgIgQgPQgRgQgIgUQgIgTAAgYQAAgXAIgTQAIgUARgQQAhgfAtAAQAXAAAUAIQAUAHAQAQQAhAfAAAvQAAAwghAfQggAfgvAAQgWAAgUgIgAgsgtQgTATAAAaQAAAOAEALQAFALAJAKQAKAKALAFQAMAEAMAAQAOAAALgEQALgFAKgKQASgTAAgbQAAgMgEgMQgFgMgKgJQgSgUgbAAQgZAAgTAUg");
	this.shape_3.setTransform(179,55.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgqBmQgUgIgQgPQgRgQgIgUQgIgTAAgYQAAgXAIgTQAIgUARgQQAhgfAtAAQAXAAAUAIQAUAHAQAQQAhAfAAAvQAAAwghAfQggAfgvAAQgWAAgUgIgAgsgtQgTATAAAaQAAAOAEALQAFALAJAKQAKAKALAFQAMAEAMAAQAOAAALgEQALgFAKgKQASgTAAgbQAAgMgEgMQgFgMgKgJQgSgUgbAAQgZAAgTAUg");
	this.shape_4.setTransform(154.2,55.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag6BrQgFAAAAgFIAAjLQAAgFAFAAIAlAAQAFAAAAAFIAACmIBLAAQAFAAAAAFIAAAgQAAAFgFAAg");
	this.shape_5.setTransform(135,55.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAiBrQgFAAgCgFIgjhFIggAAIAABFQAAAFgEAAIgmAAQgEAAAAgFIAAjLQAAgFAEAAIBnAAQAbAAATAVQAKAKAFANQAFAMAAAOQAAAXgMASQgNASgVAHIAmBGIACAFQAAAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAgAgogGIAyAAQAKAAAJgIQAFgEADgFQADgGAAgHQAAgGgDgGQgDgFgFgFQgJgHgKAAIgyAAg");
	this.shape_6.setTransform(108.2,55.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhMBrQgFAAAAgFIAAjLQAAgFAFAAICZAAQAFAAAAAFIAAAgQAAAFgFAAIhvAAIAAArIBfAAQAEAAAAAFIAAAgQAAAEgEAAIhfAAIAAAtIBvAAQAFAAAAAFIAAAgQAAAFgFAAg");
	this.shape_7.setTransform(88.3,55.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgVBrQgDAAgBgFIhKjMQgCgEAHAAIAqAAQACAAACAEIAwCXIAyiXQABgEADAAIAqAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIhLDLQgCAFgCAAg");
	this.shape_8.setTransform(67.7,55.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhMBrQgFAAAAgFIAAjLQAAgFAFAAICZAAQAFAAAAAFIAAAgQAAAFgFAAIhvAAIAAArIBfAAQAEAAAAAFIAAAgQAAAEgEAAIhfAAIAAAtIBvAAQAFAAAAAFIAAAgQAAAFgFAAg");
	this.shape_9.setTransform(48.9,55.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AA1BrIgEgBIhhiGIAACCQABAFgFAAIgjAAQgEAAAAgFIAAjLQAAgFAEAAIAjAAQAAAAABAAQAAABABAAQABAAAAABQABAAAAABIBgCEIAAiCQABgFAEAAIAiAAQAFAAAAAFIAADLQAAAFgFAAg");
	this.shape_10.setTransform(26.8,55.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(11.8,33.5,244.7,43.3), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C39C00").s().p("AhQBrQgFAAAAgFIAAjLQAAgFAFAAIBdAAQAeAAAVAWQAWAVAAAgQAAAggWAVQgKALgNAFQgNAFgPAAIgzAAIAAA7QAAAFgFAAgAgmACIAoAAQAQAAAKgHQAFgEACgHQADgGAAgJQAAgJgDgGQgCgHgGgEQgFgEgGgCQgGgCgIAAIgoAAg");
	this.shape.setTransform(205.8,49.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C39C00").s().p("AgSBrQgEAAAAgFIAAjLQAAgFAEAAIAlAAQAEAAAAAFIAADLQAAAFgEAAg");
	this.shape_1.setTransform(190.1,49.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#C39C00").s().p("AAwBrQgFAAABgFIAAhSIhWAAIAABSQgBAFgEAAIgmAAQgEAAAAgFIAAjLQAAgFAEAAIAmAAQAEAAABAFIAABQIBWAAIAAhQQgBgFAFAAIAlAAQAFAAAAAFIAADLQAAAFgFAAg");
	this.shape_2.setTransform(173.9,49.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#C39C00").s().p("AgoBnQgSgFgRgNQgEgDADgDIAVgcQADgDAEACQALAJAMAEQALAFAMgBQAPAAAJgFQAIgGAAgLQAAgNgSgGIgQgGIgRgFQgdgLgLgKQgKgIgEgLQgDgLAAgOQgBgNAGgLQAFgKALgJQALgHAPgEQAOgFATABQAfgBAhAUQAEACgDAEIgTAdQgDADgEgCQgUgNgUAAQgPAAgIAEQgIAEAAAIQAAALAUAIIAVAHIAVAIQAYAIALAOQAMAQAAAXQAAAcgWASQgLAJgPAFQgPAEgRABQgVAAgSgHg");
	this.shape_3.setTransform(153.9,49.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#C39C00").s().p("AAiBrQgFAAgCgFIgjhFIggAAIAABFQAAAFgEAAIgmAAQgEAAAAgFIAAjLQAAgFAEAAIBnAAQAbAAATAVQAKAKAFANQAFAMAAAOQAAAXgMASQgNASgVAHIAmBGIACAFQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBAAgAgogGIAyAAQAKAAAJgIQAFgEADgFQADgGAAgHQAAgGgDgGQgDgFgFgFQgJgHgKAAIgyAAg");
	this.shape_4.setTransform(135.4,49.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#C39C00").s().p("AhMBrQgFAAAAgFIAAjLQAAgFAFAAICZAAQAFAAAAAFIAAAgQAAAFgFAAIhvAAIAAArIBfAAQAEAAAAAFIAAAgQAAAEgEAAIhfAAIAAAtIBvAAQAFAAAAAFIAAAgQAAAFgFAAg");
	this.shape_5.setTransform(115.6,49.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#C39C00").s().p("AhKBrQgFAAAAgFIAAjLQAAgFAFAAIBGAAQAXAAASALQAZAPAAAdQAAAggaAMIAAABQAWAGALANQALAOAAAWQAAAcgZARQgTANgeAAgAggBBIAfAAQANAAAJgDQALgFAAgOQAAgYgqAAIgWAAgAgggUIALAAQAjAAAAgaQAAgLgJgFQgGgCgIAAIgXAAg");
	this.shape_6.setTransform(96.2,49.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#C39C00").s().p("ABDBrQgFAAAAgFIAAh7IgrBIQgCAFgCAAIgdAAQgCAAgDgFIgqhIIAAB7QAAAFgFAAIgkAAQgEAAAAgFIAAjLQAAgFAEAAIAnAAQACAAADAFIA6BkIA7hkQADgFACAAIAmAAQAFAAAAAFIAADLQAAAFgFAAg");
	this.shape_7.setTransform(72.6,49.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#C39C00").s().p("AhMBrQgFAAAAgFIAAjLQAAgFAFAAICZAAQAFAAAAAFIAAAgQAAAFgFAAIhvAAIAAArIBfAAQAEAAAAAFIAAAgQAAAEgEAAIhfAAIAAAtIBvAAQAFAAAAAFIAAAgQAAAFgFAAg");
	this.shape_8.setTransform(50.7,49.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#C39C00").s().p("ABDBrQgFAAAAgFIAAh7IgrBIQgCAFgCAAIgdAAQgCAAgDgFIgqhIIAAB7QAAAFgFAAIgkAAQgEAAAAgFIAAjLQAAgFAEAAIAnAAQACAAADAFIA6BkIA7hkQADgFACAAIAmAAQAFAAAAAFIAADLQAAAFgFAAg");
	this.shape_9.setTransform(27,49.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(10.5,27.5,208.6,43.3), null);


(lib.Symbol3copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgXA/QgMgEgKgHQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAABgBIANgQQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAABQAHAFAHACQAHADAIAAQAIAAAFgDQAFgEAAgHQAAgHgLgEIgJgEIgKgDQgSgGgHgGQgFgFgCgHQgDgGAAgJQAAgIADgGQAEgGAGgFQAGgFAJgDQAKgCAKAAQATAAAUALQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAIgMASQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBgBQgMgIgMAAQgJAAgFADQgEACgBAFQAAAHANAFIAMAEIANAFQAOAFAHAIQAHAJAAAOQAAARgNALQgHAGgJADQgJACgKAAQgMAAgLgDg");
	this.shape.setTransform(89.2,193.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAgBBIgCgBIg7hRIAABPQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgVAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAh7QAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAVAAIACACIA6BPIAAhOQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAVAAQAAAAABAAQABABAAAAQAAAAABABQAAABAAAAIAAB7QAAAAAAABQgBABAAAAQAAAAgBABQgBAAAAAAg");
	this.shape_1.setTransform(75.9,193.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgZA+QgMgEgKgKQgKgKgFgLQgFgMAAgOQAAgOAFgMQAFgMAKgKQAUgSAbgBQAOAAAMAGQAMAEAKAJQAUAUAAAcQAAAcgUATQgUASgcABQgNgBgMgEgAgagaQgMALAAAQQAAAHADAHQADAHAFAHQAGAFAHADQAHADAHAAQAIAAAHgDQAHgDAGgFQALgMAAgQQAAgIgDgHQgDgHgFgFQgMgMgQgBQgPABgLAMg");
	this.shape_2.setTransform(60.3,193.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXA/QgMgEgKgHQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAABgBIANgQQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAABQAHAFAHACQAHADAIAAQAIAAAFgDQAFgEAAgHQAAgHgLgEIgJgEIgKgDQgSgGgHgGQgFgFgCgHQgDgGAAgJQAAgIADgGQAEgGAGgFQAGgFAJgDQAKgCAKAAQATAAAUALQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAIgMASQAAAAgBABQAAAAAAAAQgBAAgBAAQAAAAgBgBQgMgIgMAAQgJAAgFADQgEACgBAFQAAAHANAFIAMAEIANAFQAOAFAHAIQAHAJAAAOQAAARgNALQgHAGgJADQgJACgKAAQgMAAgLgDg");
	this.shape_3.setTransform(46.6,193.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAgBBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAgBgBIgHgXIgrAAIgIAXQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAgBAAAAQgBgBAAAAQAAgBABgBIAth6QAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAAAIAXAAQAAAAABAAQAAAAAAABQABAAAAABQAAAAABABIAsB7QABABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAgAgNAOIAbAAIgOgqg");
	this.shape_4.setTransform(34.4,193.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguBBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBgBAAAAIAAh7QAAAAABgBQAAgBAAAAQAAAAABgBQAAAAABAAIBdAAQABAAAAAAQABABAAAAQAAAAAAABQAAABAAAAIAAAUQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAIhEAAIAAAbIA6AAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAABIAAASQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAIg6AAIAAAcIBEAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAUQAAAAAAABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_5.setTransform(22.2,193.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAUBBQgCAAgCgDIgUgqIgUAAIAAAqQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgXAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAh7QAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIA9AAQARAAAMANQAGAGADAIQADAHAAAJQAAAOgIAKQgIALgMAEIAXArIABACQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAgAgYgDIAeAAQAGAAAGgFQADgCABgEQACgDAAgEQAAgEgCgEIgEgGQgGgEgGAAIgeAAg");
	this.shape_6.setTransform(8.8,193.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3copy, new cjs.Rectangle(0,180,97.5,26.3), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgXA/QgMgEgKgHQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAABgBIANgQQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAABQAHAFAHACQAHADAIAAQAIAAAFgDQAFgEAAgHQAAgHgLgEIgJgEIgKgDQgSgGgHgGQgFgFgCgHQgDgGAAgJQAAgIADgGQAEgGAGgFQAGgFAJgDQAKgCAKAAQATAAAUALQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAIgMASQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBgBQgMgIgMAAQgJAAgFADQgEACgBAFQAAAHANAFIAMAEIANAFQAOAFAHAIQAHAJAAAOQAAARgNALQgHAGgJADQgJACgKAAQgMAAgLgDg");
	this.shape.setTransform(89.2,193.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAgBBIgCgBIg7hRIAABPQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgVAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAh7QAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAVAAIACACIA6BPIAAhOQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAVAAQAAAAABAAQABABAAAAQAAAAABABQAAABAAAAIAAB7QAAAAAAABQgBABAAAAQAAAAgBABQgBAAAAAAg");
	this.shape_1.setTransform(75.9,193.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgZA+QgMgEgKgKQgKgKgFgLQgFgMAAgOQAAgOAFgMQAFgMAKgKQAUgSAbgBQAOAAAMAGQAMAEAKAJQAUAUAAAcQAAAcgUATQgUASgcABQgNgBgMgEgAgagaQgMALAAAQQAAAHADAHQADAHAFAHQAGAFAHADQAHADAHAAQAIAAAHgDQAHgDAGgFQALgMAAgQQAAgIgDgHQgDgHgFgFQgMgMgQgBQgPABgLAMg");
	this.shape_2.setTransform(60.3,193.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXA/QgMgEgKgHQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAABgBIANgQQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAABQAHAFAHACQAHADAIAAQAIAAAFgDQAFgEAAgHQAAgHgLgEIgJgEIgKgDQgSgGgHgGQgFgFgCgHQgDgGAAgJQAAgIADgGQAEgGAGgFQAGgFAJgDQAKgCAKAAQATAAAUALQAAABABAAQAAABAAAAQAAABAAAAQAAABAAAAIgMASQAAAAgBABQAAAAAAAAQgBAAgBAAQAAAAgBgBQgMgIgMAAQgJAAgFADQgEACgBAFQAAAHANAFIAMAEIANAFQAOAFAHAIQAHAJAAAOQAAARgNALQgHAGgJADQgJACgKAAQgMAAgLgDg");
	this.shape_3.setTransform(46.6,193.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAgBBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAgBgBIgHgXIgrAAIgIAXQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAgBAAAAQgBgBAAAAQAAgBABgBIAth6QAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAAAIAXAAQAAAAABAAQAAAAAAABQABAAAAABQAAAAABABIAsB7QABABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAgAgNAOIAbAAIgOgqg");
	this.shape_4.setTransform(34.4,193.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AguBBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBgBAAAAIAAh7QAAAAABgBQAAgBAAAAQAAAAABgBQAAAAABAAIBdAAQABAAAAAAQABABAAAAQAAAAAAABQAAABAAAAIAAAUQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAIhEAAIAAAbIA6AAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAABIAAASQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAIg6AAIAAAcIBEAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAUQAAAAAAABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_5.setTransform(22.2,193.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAUBBQgCAAgCgDIgUgqIgUAAIAAAqQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgXAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAh7QAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIA9AAQARAAAMANQAGAGADAIQADAHAAAJQAAAOgIAKQgIALgMAEIAXArIABACQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAgAgYgDIAeAAQAGAAAGgFQADgCABgEQACgDAAgEQAAgEgCgEIgEgGQgGgEgGAAIgeAAg");
	this.shape_6.setTransform(8.8,193.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,180,97.5,26.3), null);


(lib.Symbol2copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C39C00").s().p("AgqBCQgHAAAAgIIAAgKQAAgaAUgOIALgHIAQgHQAJgFAEgEQAFgFAAgFQAAgMgQABQgHAAgHADQgHAEgGAGQgEAEgCgDIgPgQQgDgDADgDQAKgLAMgFQANgEAPgBQAVAAANAMQANAKAAASQAAAYgcANIgSAJQgMAIgBAHIA2AAQAGgBAAAGIAAATQAAAFgGABg");
	this.shape.setTransform(31.7,197.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C39C00").s().p("AgKBBQgBAAgBAAQAAgBAAAAQgBAAAAgBQAAgBAAAAIAAg6IgvhAIgBgCQAAgBAAAAQAAAAAAAAQABgBAAAAQAAAAABAAIAdAAQADAAACADIAZApIAbgpQABgDADAAIAdAAQABAAAAAAQAAAAABABQAAAAAAAAQAAAAAAABIAAACIgwBBIAAA5QAAAAAAABQAAABgBAAQAAAAAAABQgBAAgBAAg");
	this.shape_1.setTransform(88.3,197.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#C39C00").s().p("AgtBBQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAh7QAAgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAIArAAQAOAAAKAHQAQAJAAARQAAAUgQAHIgBABQAOADAHAIQAGAJAAANQAAARgPAKQgMAIgSAAgAgTAoIATAAQAHAAAFgDQAHgDAAgIQAAgOgZAAIgNAAgAgTgMIAGAAQAWAAAAgPQAAgHgGgDQgDgCgFAAIgOAAg");
	this.shape_2.setTransform(76,197.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#C39C00").s().p("AAgBBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAgBgBIgHgXIgrAAIgIAXQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBABgBIAth6QAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAAAIAXAAQAAAAABAAQAAAAAAABQABAAAAABQAAAAABABIAsB7QABABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAgAgNAPIAbAAIgOgrg");
	this.shape_3.setTransform(62.7,197.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#C39C00").s().p("AgtBBQAAAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAAAIAAh7QAAgBAAAAQAAgBAAAAQABAAAAgBQABAAAAAAIArAAQAOAAAKAHQAQAJAAARQAAAUgQAHIgBABQAOADAHAIQAGAJAAANQAAARgPAKQgMAIgSAAgAgTAoIATAAQAHAAAFgDQAHgDAAgIQAAgOgZAAIgNAAgAgTgMIAGAAQAWAAAAgPQAAgHgGgDQgDgCgFAAIgOAAg");
	this.shape_4.setTransform(50.4,197.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#C39C00").s().p("Ag2BBQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAAAAAgBIAAh7QAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIAyAAQANAAALAFQAMAFAJAJQARASAAAbQAAAOgFALQgEAMgKAJQgKAJgLAFQgMAFgMAAgAgdAoIAUAAQAIAAAGgDQAHgDAGgGQALgLAAgRQAAgJgDgIQgEgIgHgGQgDgDgFgCQgFgCgFgBIgHAAIgLAAIgIAAg");
	this.shape_5.setTransform(12.6,197.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#C39C00").s().p("AAgBBIgCgBIg7hRIAABPQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgVAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAh7QAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIAVAAIACACIA6BPIAAhOQAAgBAAAAQABgBAAAAQAAAAABgBQABAAAAAAIAVAAQAAAAABAAQABABAAAAQAAAAABABQAAAAAAABIAAB7QAAAAAAABQgBABAAAAQAAAAgBABQgBAAAAAAg");
	this.shape_6.setTransform(-2.6,197.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#C39C00").s().p("AAgBBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAgBgBIgHgXIgrAAIgIAXQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBABgBIAth6QAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAAAIAXAAQAAAAABAAQAAAAAAABQABAAAAABQAAAAABABIAsB7QABABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAgAgNAPIAbAAIgOgrg");
	this.shape_7.setTransform(-16.6,197.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2copy, new cjs.Rectangle(-24.6,180,122.1,32.1), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C39C00").s().p("AgeA+QgFgCgHgFQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAgBABAAIANgQQAAgBAAAAQABAAAAAAQABAAAAAAQABAAAAABQAFADAFACQAFACAFAAQAFAAADgCQAEgCAEgEQAGgIACgNQgFADgGACQgFACgGAAQgJAAgIgDQgHgDgGgGQgMgLABgVQAAgJADgHQAEgIAGgGQANgLATAAQAvAAAAA8QAAAcgKATQgOAYgdAAQgOAAgKgEgAgNgkQgFAFAAAHQAAAKAEAFQADAFAIAAQAOAAAIgKQgBgbgSAAQgIAAgFAFg");
	this.shape.setTransform(-9.2,195.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C39C00").s().p("AAUBBQgCAAgCgDIgUgqIgUAAIAAAqQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgXAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAh7QAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIA9AAQARAAAMANQAGAGADAIQADAHAAAJQAAAOgIAKQgIALgMAEIAXArIABACQAAABAAAAQgBAAAAAAQAAABgBAAQAAAAgBAAgAgYgDIAeAAQAGAAAGgFQADgCABgEQACgDAAgEQAAgEgCgEIgEgGQgGgEgGAAIgeAAg");
	this.shape_1.setTransform(87.2,196.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#C39C00").s().p("AguBBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBgBAAAAIAAh7QAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIBdAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAAAUQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAIhDAAIAAAbIA4AAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAASQAAABAAABQAAAAAAAAQgBABAAAAQgBAAgBAAIg4AAIAAAcIBDAAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAUQAAAAAAABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_2.setTransform(74.2,196.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#C39C00").s().p("AgjBBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBgBAAAAIAAh7QAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIAXAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAABlIAuAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIAAAUQAAAAgBABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_3.setTransform(62.7,196.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#C39C00").s().p("AgjBBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBgBAAAAIAAh7QAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIAXAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIAABlIAuAAQABAAAAAAQABAAAAAAQAAABAAAAQABABAAAAIAAAUQAAAAgBABQAAABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_4.setTransform(52.2,196.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#C39C00").s().p("AAgBBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAgBgBIgHgXIgrAAIgIAXQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBABgBIAth6QAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAAAIAXAAQAAAAABAAQAAAAAAABQABAAAAABQAAAAABABIAsB7QABABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAgAgNAPIAbAAIgOgrg");
	this.shape_5.setTransform(39.9,196.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#C39C00").s().p("AAoBBQgBAAAAAAQgBgBAAAAQAAAAAAgBQgBgBAAAAIAAhKIgZArIgDADIgSAAIgCgDIgagrIAABKQAAAAAAABQAAABgBAAQAAAAAAABQgBAAAAAAIgXAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAgBAAAAIAAh7QAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAYAAQAAAAABAAQAAABABAAQAAAAAAABQABAAAAABIAjA9IAjg9IAEgDIAXAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIAAB7QAAAAAAABQAAABgBAAQAAAAgBABQAAAAgBAAg");
	this.shape_6.setTransform(25,196.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#C39C00").s().p("AgXA/QgMgEgKgHQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAABgBIANgQQAAgBABAAQAAgBAAAAQABAAAAAAQABAAAAABQAHAFAHACQAHADAIAAQAIAAAFgDQAFgEAAgHQAAgHgLgEIgJgEIgKgDQgSgGgHgGQgFgFgCgHQgDgGAAgJQAAgIADgGQAEgGAGgFQAGgFAJgDQAKgCAKAAQATAAAUALQAAABABAAQAAAAAAABQAAAAAAABQAAABAAAAIgMASQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBgBQgMgIgMAAQgJAAgFADQgEACgBAFQAAAHANAFIAMAEIANAFQAOAFAHAIQAHAJAAAOQAAARgNALQgHAGgJADQgJACgKAAQgMAAgLgDg");
	this.shape_7.setTransform(10.8,196.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-17,180,113.2,29.3), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C39C00").s().p("AAGBBQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAAAAAgBIAAgXIgyAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAgTIACgFIAzhJQACgDACAAIAVAAQABAAABAAQAAABAAAAQABAAAAABQAAABAAAAIAABNIARAAQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAAARQAAAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAIgRAAIAAAXQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAgAgVAQIAYAAIAAgig");
	this.shape.setTransform(7.8,15.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C39C00").s().p("AgKBBQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAhlIghAAQgBAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAAAIAAgUQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAABAAIBeAAQAAAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAAAUQAAAAAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgiAAIAABlQAAAAAAABQAAABgBAAQAAAAAAABQgBAAgBAAg");
	this.shape_1.setTransform(75.3,16.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#C39C00").s().p("AAgBBIgCgBIg7hRIAABPQAAAAAAABQAAABAAAAQgBAAAAABQgBAAAAAAIgVAAQgBAAAAAAQgBgBAAAAQAAAAgBgBQAAgBAAAAIAAh7QAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIAVAAIACACIA6BPIAAhOQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIAVAAQAAAAABAAQABABAAAAQAAAAABABQAAAAAAABIAAB7QAAAAAAABQgBABAAAAQAAAAgBABQgBAAAAAAg");
	this.shape_2.setTransform(62.4,16.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#C39C00").s().p("AAgBBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAgBgBIgHgXIgrAAIgIAXQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBABgBIAth6QAAgBAAAAQABgBAAAAQAAgBABAAQAAAAAAAAIAXAAQAAAAABAAQAAAAAAABQABAAAAABQAAAAABABIAsB7QABABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAgAgNAPIAbAAIgOgrg");
	this.shape_3.setTransform(48.4,16.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#C39C00").s().p("AgLBBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAgBAAAAIAAh7QAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAXAAQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAAB7QAAAAAAABQAAABgBAAQAAAAAAABQgBAAAAAAg");
	this.shape_4.setTransform(38.6,16.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#C39C00").s().p("AgUA+QgMgFgJgJQgKgLgFgMQgFgLAAgOQAAgNAFgLQAFgMAKgKQAKgKAMgEQAMgGANAAQAUAAAUAOQABAAAAABQABAAAAABQAAAAgBABQAAAAAAAAIgMATQAAABgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQgGgEgHgDQgGgCgGAAQgPAAgLAMQgGAGgDAHQgCAHAAAHQAAARALALQALAMAPAAQARAAALgIIAAgLIgYAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAgUQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAxAAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAA/QAAABAAABQgBAAAAABQAAAAgBAAQAAABgBAAIgWAAQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAgBQgOAHgOAAQgOgBgMgEg");
	this.shape_5.setTransform(27.3,16.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,83.3,29.3), null);


(lib.PANDAS = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.BB_REDPANDA();
	this.instance.parent = this;
	this.instance.setTransform(701,241);

	this.instance_1 = new lib.BB_PENGUINS();
	this.instance_1.parent = this;
	this.instance_1.setTransform(311,225);

	this.instance_2 = new lib.bb_pandas();
	this.instance_2.parent = this;
	this.instance_2.setTransform(0,184);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.PANDAS, new cjs.Rectangle(0,184,852,227), null);


(lib.family = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.BB_REDPANDA();
	this.instance.parent = this;
	this.instance.setTransform(90,372,0.59,0.59);

	this.instance_1 = new lib.BB_PENGUINS();
	this.instance_1.parent = this;
	this.instance_1.setTransform(14,314,0.744,0.744);

	this.instance_2 = new lib.bb_pandas();
	this.instance_2.parent = this;
	this.instance_2.setTransform(2,218,0.84,0.84);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.family, new cjs.Rectangle(2,218,252,228.4), null);


(lib.ZOOLOGO = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol7();
	this.instance.parent = this;
	this.instance.setTransform(-64.5,332.3,0.864,0.864,0,0,0,49.4,29.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.ZOOLOGO, new cjs.Rectangle(-107.2,306.9,85.6,50.2), null);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol5copy();
	this.instance.parent = this;
	this.instance.setTransform(134.3,62.3,1.65,1.65,0,0,0,74.2,13.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol6, new cjs.Rectangle(11.8,40.7,153.3,43.3), null);


// stage content:
(lib._300x600_pandamonium = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 9
	this.instance = new lib.Symbol9();
	this.instance.parent = this;
	this.instance.setTransform(98.6,216.1,1,1,0,0,0,79.5,14.5);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(340).to({_off:false},0).to({alpha:1},20).wait(43));

	// LOGO
	this.instance_1 = new lib.ZOOLOGO();
	this.instance_1.parent = this;
	this.instance_1.setTransform(243.4,215.9,1,1,0,0,0,29.2,17.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(316).to({_off:false},0).to({alpha:1},25).wait(62));

	// Layer 7
	this.instance_2 = new lib.Symbol6();
	this.instance_2.parent = this;
	this.instance_2.setTransform(45.6,74.8,1,1,0,0,0,46.5,13.1);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(306).to({_off:false},0).wait(1).to({regX:88.1,regY:62.4,x:87.2,y:124.1,alpha:0.001},0).wait(1).to({alpha:0.003},0).wait(1).to({x:87.3,alpha:0.006},0).wait(1).to({x:87.4,alpha:0.011},0).wait(1).to({x:87.5,alpha:0.018},0).wait(1).to({x:87.6,alpha:0.026},0).wait(1).to({x:87.8,alpha:0.037},0).wait(1).to({x:88,alpha:0.049},0).wait(1).to({x:88.2,alpha:0.064},0).wait(1).to({x:88.4,alpha:0.081},0).wait(1).to({x:88.8,alpha:0.1},0).wait(1).to({x:89.1,alpha:0.123},0).wait(1).to({x:89.5,alpha:0.148},0).wait(1).to({x:90,alpha:0.176},0).wait(1).to({x:90.5,alpha:0.207},0).wait(1).to({x:91,alpha:0.242},0).wait(1).to({x:91.6,alpha:0.279},0).wait(1).to({x:92.3,alpha:0.319},0).wait(1).to({x:92.9,alpha:0.361},0).wait(1).to({x:93.6,alpha:0.406},0).wait(1).to({x:94.4,alpha:0.451},0).wait(1).to({x:95.1,alpha:0.497},0).wait(1).to({x:95.8,alpha:0.543},0).wait(1).to({x:96.6,alpha:0.588},0).wait(1).to({x:97.2,alpha:0.631},0).wait(1).to({x:97.9,alpha:0.672},0).wait(1).to({x:98.5,alpha:0.71},0).wait(1).to({x:99.1,alpha:0.746},0).wait(1).to({x:99.6,alpha:0.779},0).wait(1).to({x:100.1,alpha:0.809},0).wait(1).to({x:100.5,alpha:0.836},0).wait(1).to({x:100.9,alpha:0.861},0).wait(1).to({x:101.3,alpha:0.883},0).wait(1).to({x:101.6,alpha:0.903},0).wait(1).to({x:101.9,alpha:0.921},0).wait(1).to({x:102.1,alpha:0.936},0).wait(1).to({x:102.3,alpha:0.949},0).wait(1).to({x:102.5,alpha:0.961},0).wait(1).to({x:102.7,alpha:0.971},0).wait(1).to({x:102.8,alpha:0.979},0).wait(1).to({x:102.9,alpha:0.986},0).wait(1).to({x:103,alpha:0.991},0).wait(1).to({x:103.1,alpha:0.995},0).wait(1).to({alpha:0.998},0).wait(1).to({alpha:0.999},0).wait(1).to({regX:46.5,regY:13.1,x:61.6,y:74.8,alpha:1},0).wait(51));

	// Layer 6
	this.instance_3 = new lib.Symbol5();
	this.instance_3.parent = this;
	this.instance_3.setTransform(72.3,53.5,1,1,0,0,0,74.2,13.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(304).to({_off:false},0).wait(1).to({regX:134.7,regY:55.2,x:132.8,y:95.6,alpha:0.001},0).wait(1).to({alpha:0.003},0).wait(1).to({x:132.9,alpha:0.006},0).wait(1).to({x:133,alpha:0.011},0).wait(1).to({x:133.1,alpha:0.018},0).wait(1).to({x:133.2,alpha:0.026},0).wait(1).to({x:133.4,alpha:0.037},0).wait(1).to({x:133.6,alpha:0.049},0).wait(1).to({x:133.8,alpha:0.064},0).wait(1).to({x:134.1,alpha:0.081},0).wait(1).to({x:134.4,alpha:0.1},0).wait(1).to({x:134.7,alpha:0.123},0).wait(1).to({x:135.1,alpha:0.148},0).wait(1).to({x:135.6,alpha:0.176},0).wait(1).to({x:136.1,alpha:0.207},0).wait(1).to({x:136.6,alpha:0.242},0).wait(1).to({x:137.2,alpha:0.279},0).wait(1).to({x:137.9,alpha:0.319},0).wait(1).to({x:138.5,alpha:0.361},0).wait(1).to({x:139.2,alpha:0.406},0).wait(1).to({x:140,alpha:0.451},0).wait(1).to({x:140.7,alpha:0.497},0).wait(1).to({x:141.4,alpha:0.543},0).wait(1).to({x:142.2,alpha:0.588},0).wait(1).to({x:142.8,alpha:0.631},0).wait(1).to({x:143.5,alpha:0.672},0).wait(1).to({x:144.1,alpha:0.71},0).wait(1).to({x:144.7,alpha:0.746},0).wait(1).to({x:145.2,alpha:0.779},0).wait(1).to({x:145.7,alpha:0.809},0).wait(1).to({x:146.1,alpha:0.836},0).wait(1).to({x:146.5,alpha:0.861},0).wait(1).to({x:146.9,alpha:0.883},0).wait(1).to({x:147.2,alpha:0.903},0).wait(1).to({x:147.5,alpha:0.921},0).wait(1).to({x:147.7,alpha:0.936},0).wait(1).to({x:147.9,alpha:0.949},0).wait(1).to({x:148.1,alpha:0.961},0).wait(1).to({x:148.3,alpha:0.971},0).wait(1).to({x:148.4,alpha:0.979},0).wait(1).to({x:148.5,alpha:0.986},0).wait(1).to({x:148.6,alpha:0.991},0).wait(1).to({x:148.7,alpha:0.995},0).wait(1).to({alpha:0.998},0).wait(1).to({alpha:0.999},0).wait(1).to({regX:74.2,regY:13.1,x:88.3,y:53.5,alpha:1},0).wait(53));

	// Layer 5
	this.instance_4 = new lib.Symbol4();
	this.instance_4.parent = this;
	this.instance_4.setTransform(61,30.9,1,1,0,0,0,63.2,13.1);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(302).to({_off:false},0).wait(1).to({regX:115.3,regY:49.2,x:113.2,y:67,alpha:0.001},0).wait(1).to({alpha:0.003},0).wait(1).to({alpha:0.006},0).wait(1).to({x:113.3,alpha:0.011},0).wait(1).to({x:113.4,alpha:0.018},0).wait(1).to({x:113.6,alpha:0.026},0).wait(1).to({x:113.7,alpha:0.037},0).wait(1).to({x:113.9,alpha:0.049},0).wait(1).to({x:114.2,alpha:0.064},0).wait(1).to({x:114.4,alpha:0.081},0).wait(1).to({x:114.8,alpha:0.1},0).wait(1).to({x:115.1,alpha:0.123},0).wait(1).to({x:115.5,alpha:0.148},0).wait(1).to({x:115.9,alpha:0.176},0).wait(1).to({x:116.4,alpha:0.207},0).wait(1).to({x:117,alpha:0.242},0).wait(1).to({x:117.6,alpha:0.279},0).wait(1).to({x:118.2,alpha:0.319},0).wait(1).to({x:118.9,alpha:0.361},0).wait(1).to({x:119.6,alpha:0.406},0).wait(1).to({x:120.3,alpha:0.451},0).wait(1).to({x:121.1,alpha:0.497},0).wait(1).to({x:121.8,alpha:0.543},0).wait(1).to({x:122.5,alpha:0.588},0).wait(1).to({x:123.2,alpha:0.631},0).wait(1).to({x:123.8,alpha:0.672},0).wait(1).to({x:124.5,alpha:0.71},0).wait(1).to({x:125,alpha:0.746},0).wait(1).to({x:125.6,alpha:0.779},0).wait(1).to({x:126,alpha:0.809},0).wait(1).to({x:126.5,alpha:0.836},0).wait(1).to({x:126.9,alpha:0.861},0).wait(1).to({x:127.2,alpha:0.883},0).wait(1).to({x:127.5,alpha:0.903},0).wait(1).to({x:127.8,alpha:0.921},0).wait(1).to({x:128.1,alpha:0.936},0).wait(1).to({x:128.3,alpha:0.949},0).wait(1).to({x:128.5,alpha:0.961},0).wait(1).to({x:128.6,alpha:0.971},0).wait(1).to({x:128.8,alpha:0.979},0).wait(1).to({x:128.9,alpha:0.986},0).wait(1).to({x:129,alpha:0.991},0).wait(1).to({alpha:0.995},0).wait(1).to({x:129.1,alpha:0.998},0).wait(1).to({alpha:0.999},0).wait(1).to({regX:63.2,regY:13.1,x:77,y:30.9,alpha:1},0).wait(55));

	// famjam
	this.instance_5 = new lib.family();
	this.instance_5.parent = this;
	this.instance_5.setTransform(170,69.5,1,1,0,0,0,150,113.5);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(302).to({_off:false},0).wait(1).to({regX:128,regY:332.2,x:148,y:288.2,alpha:0.001},0).wait(1).to({alpha:0.005},0).wait(1).to({alpha:0.011},0).wait(1).to({alpha:0.021},0).wait(1).to({alpha:0.034},0).wait(1).to({alpha:0.051},0).wait(1).to({alpha:0.071},0).wait(1).to({alpha:0.097},0).wait(1).to({alpha:0.127},0).wait(1).to({alpha:0.163},0).wait(1).to({alpha:0.204},0).wait(1).to({alpha:0.25},0).wait(1).to({alpha:0.302},0).wait(1).to({alpha:0.359},0).wait(1).to({alpha:0.419},0).wait(1).to({alpha:0.481},0).wait(1).to({alpha:0.543},0).wait(1).to({alpha:0.603},0).wait(1).to({alpha:0.66},0).wait(1).to({alpha:0.712},0).wait(1).to({alpha:0.76},0).wait(1).to({alpha:0.802},0).wait(1).to({alpha:0.839},0).wait(1).to({alpha:0.872},0).wait(1).to({alpha:0.9},0).wait(1).to({alpha:0.923},0).wait(1).to({alpha:0.943},0).wait(1).to({alpha:0.96},0).wait(1).to({alpha:0.973},0).wait(1).to({alpha:0.983},0).wait(1).to({alpha:0.991},0).wait(1).to({alpha:0.996},0).wait(1).to({alpha:0.999},0).wait(1).to({regX:150,regY:113.5,x:170,y:69.5,alpha:1},0).wait(67));

	// Layer 3
	this.instance_6 = new lib.PANDAS();
	this.instance_6.parent = this;
	this.instance_6.setTransform(451,111.5,1,1,0,0,0,150,113.5);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({regX:426,regY:297.5,x:714.1,y:295.5,alpha:0.044},0).wait(1).to({x:698.2,alpha:0.099},0).wait(1).to({x:678.6,alpha:0.166},0).wait(1).to({x:654.6,alpha:0.248},0).wait(1).to({x:626.4,alpha:0.345},0).wait(1).to({x:596,alpha:0.449},0).wait(1).to({x:567,alpha:0.548},0).wait(1).to({x:542.1,alpha:0.633},0).wait(1).to({x:521.6,alpha:0.703},0).wait(1).to({x:505,alpha:0.76},0).wait(1).to({x:491.6,alpha:0.806},0).wait(1).to({x:480.5,alpha:0.844},0).wait(1).to({x:471.4,alpha:0.875},0).wait(1).to({x:463.9,alpha:0.901},0).wait(1).to({x:457.6,alpha:0.923},0).wait(1).to({x:452.4,alpha:0.94},0).wait(1).to({x:448.1,alpha:0.955},0).wait(1).to({x:444.6,alpha:0.967},0).wait(1).to({x:441.8,alpha:0.977},0).wait(1).to({x:439.5,alpha:0.985},0).wait(1).to({x:437.8,alpha:0.99},0).wait(1).to({x:436.5,alpha:0.995},0).wait(1).to({x:435.7,alpha:0.998},0).wait(1).to({x:435.2,alpha:0.999},0).wait(1).to({regX:150,regY:113.5,x:159,y:111.5,alpha:1},0).to({x:149},67).wait(1).to({regX:426,regY:297.5,x:423.9,y:295.5},0).wait(1).to({x:419.9},0).wait(1).to({x:411.7},0).wait(1).to({x:396.7},0).wait(1).to({x:370.8},0).wait(1).to({x:330.8},0).wait(1).to({x:286.5},0).wait(1).to({x:250.7},0).wait(1).to({x:223.7},0).wait(1).to({x:203.2},0).wait(1).to({x:186.9},0).wait(1).to({x:173.9},0).wait(1).to({x:163.3},0).wait(1).to({x:154.5},0).wait(1).to({x:147.3},0).wait(1).to({x:141.3},0).wait(1).to({x:136.3},0).wait(1).to({x:132.3},0).wait(1).to({x:129},0).wait(1).to({x:126.3},0).wait(1).to({x:124.3},0).wait(1).to({x:122.8},0).wait(1).to({x:121.8},0).wait(1).to({x:121.2},0).wait(1).to({regX:150,regY:113.5,x:-155,y:111.5},0).to({x:-161},68).wait(1).to({regX:426,regY:297.5,x:114.4,y:295.5},0).wait(1).to({x:112.3},0).wait(1).to({x:108.5},0).wait(1).to({x:102.5},0).wait(1).to({x:93.9},0).wait(1).to({x:82.2},0).wait(1).to({x:66.4},0).wait(1).to({x:46.1},0).wait(1).to({x:20.9},0).wait(1).to({x:-7.9},0).wait(1).to({x:-37.7},0).wait(1).to({x:-65.7},0).wait(1).to({x:-90.2},0).wait(1).to({x:-110.8},0).wait(1).to({x:-127.8},0).wait(1).to({x:-141.8},0).wait(1).to({x:-153.2},0).wait(1).to({x:-162.5},0).wait(1).to({x:-170},0).wait(1).to({x:-176},0).wait(1).to({x:-180.7},0).wait(1).to({x:-184.3},0).wait(1).to({x:-186.9},0).wait(1).to({x:-188.6},0).wait(1).to({x:-189.6},0).wait(1).to({regX:150,regY:113.5,x:-466,y:111.5},0).to({x:-473},67).to({x:-477,alpha:0},26,cjs.Ease.get(-1)).wait(99));

	// Layer 2
	this.instance_7 = new lib.Symbol1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-143.1,398.1,1,1,0,0,0,41.6,14.6);
	this.instance_7._off = true;

	this.instance_8 = new lib.Symbol2();
	this.instance_8.parent = this;
	this.instance_8.setTransform(100.6,215.6,1,1,0,0,0,41.6,14.6);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.instance_9 = new lib.Symbol2copy();
	this.instance_9.parent = this;
	this.instance_9.setTransform(106.6,215.6,1,1,0,0,0,41.6,14.6);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(2).to({_off:false},0).wait(1).to({regX:41.5,regY:16.1,x:-133,y:399.7},0).wait(1).to({x:-120.8},0).wait(1).to({x:-106.1,y:399.8},0).wait(1).to({x:-88.6,y:400},0).wait(1).to({x:-68.4,y:400.1},0).wait(1).to({x:-46.3,y:400.2},0).wait(1).to({x:-24.1,y:400.4},0).wait(1).to({x:-3.6,y:400.5},0).wait(1).to({x:14.2,y:400.6},0).wait(1).to({x:29.2,y:400.7},0).wait(1).to({x:41.6,y:400.8},0).wait(1).to({x:52,y:400.9},0).wait(1).to({x:60.7,y:401},0).wait(1).to({x:67.9},0).wait(1).to({x:74},0).wait(1).to({x:79.1,y:401.1},0).wait(1).to({x:83.3},0).wait(1).to({x:86.9},0).wait(1).to({x:89.8},0).wait(1).to({x:92.1,y:401.2},0).wait(1).to({x:94},0).wait(1).to({x:95.5},0).wait(1).to({x:96.5},0).wait(1).to({x:97.3},0).wait(1).to({x:97.7},0).wait(1).to({regX:41.6,regY:14.6,x:97.9,y:399.7},0).wait(64).to({y:395.7,alpha:0},9).to({_off:true},1).wait(301));
	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(102).to({_off:false},0).to({alpha:1},15).wait(68).to({alpha:0},10).to({_off:true},1).wait(207));
	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(196).to({_off:false},0).to({alpha:1},15).wait(67).to({alpha:0},20).wait(105));

	// Layer 1
	this.instance_10 = new lib.Tween1("synched",0);
	this.instance_10.parent = this;
	this.instance_10.setTransform(-48.9,399.6);

	this.instance_11 = new lib.Tween2("synched",0);
	this.instance_11.parent = this;
	this.instance_11.setTransform(192.1,401.2);
	this.instance_11._off = true;

	this.instance_12 = new lib.Symbol3();
	this.instance_12.parent = this;
	this.instance_12.setTransform(207.6,217,1,1,0,0,0,48.8,13.1);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.instance_13 = new lib.Symbol3copy();
	this.instance_13.parent = this;
	this.instance_13.setTransform(213.6,218,1,1,0,0,0,48.8,13.1);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(1).to({x:-38.3,y:399.7},0).wait(1).to({x:-25.4,y:399.8},0).wait(1).to({x:-9.9,y:399.9},0).wait(1).to({x:8.7,y:400},0).wait(1).to({x:30.1,y:400.1},0).wait(1).to({x:53.3,y:400.3},0).wait(1).to({x:76.1,y:400.4},0).wait(1).to({x:96.7,y:400.6},0).wait(1).to({x:114.2,y:400.7},0).wait(1).to({x:128.7,y:400.8},0).wait(1).to({x:140.7,y:400.9},0).wait(1).to({x:150.7},0).wait(1).to({x:158.9,y:401},0).wait(1).to({x:165.8},0).wait(1).to({x:171.5,y:401.1},0).wait(1).to({x:176.2},0).wait(1).to({x:180.1},0).wait(1).to({x:183.3},0).wait(1).to({x:185.9,y:401.2},0).wait(1).to({x:188},0).wait(1).to({x:189.6},0).wait(1).to({x:190.7},0).wait(1).to({x:191.5},0).wait(1).to({x:192},0).to({_off:true},1).wait(378));
	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(25).to({_off:false},0).wait(70).to({startPosition:0},0).to({y:397.2,alpha:0},9).to({_off:true},1).wait(298));
	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(105).to({_off:false},0).to({alpha:1},15).wait(68).to({alpha:0},10).to({_off:true},1).wait(204));
	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(199).to({_off:false},0).to({alpha:1},15).wait(67).to({alpha:0},20).wait(102));

	// Layer 10
	this.instance_14 = new lib.db_bg();
	this.instance_14.parent = this;
	this.instance_14.setTransform(0,1);

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(403));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(52.4,301,1250.7,600);
// library properties:
lib.properties = {
	width: 300,
	height: 600,
	fps: 30,
	color: "#000000",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/300x600_pandamonium_atlas_.png", id:"300x600_pandamonium_atlas_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;