(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"300x600_bcd_park_atlas_", frames: [[0,792,626,120],[0,0,744,790]]}
];


// symbols:



(lib.docBC = function() {
	this.initialize(ss["300x600_bcd_park_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.volcanoman = function() {
	this.initialize(ss["300x600_bcd_park_atlas_"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.docBC();
	this.instance.parent = this;
	this.instance.setTransform(-142,-30,0.9,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-142,-30,563.4,108);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAOIgEgDIgEgFIgBgGIABgFIAEgFIAEgDIAFgBIAGABIAFADIADAFIABAFIgBAGIgDAFIgFADIgGABg");
	this.shape.setTransform(68.7,280.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_1.setTransform(61.625,273.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXAeIAWhBIAZAKIgeA+g");
	this.shape_2.setTransform(53.5,267.15);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgIgHQgGgHgNAAQgIAAgHADQgIAEgGAFIAABHIAQAAIAAAUIg5AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_3.setTransform(42.05,275.675);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_4.setTransform(28.225,275.775);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_5.setTransform(18.775,272.875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgNAAQgIAAgJAEQgHADgGAGIAABGIAQAAIAAAUIg4AAIAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgIAAgHADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIALgEIAKgBQANAAAJAFQAJAFAFAKIAJgHIALgHIALgEQAGgCAHAAQAJAAAIADQAIADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_6.setTransform(-2.45,275.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_7.setTransform(-21.225,275.825);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AASA9IAAgUIAGAAIgYgeIgWAeIAGAAIAAAUIgpAAIAAgUIAKAAIAlgqIgigmIgNAAIAAgVIApAAIAAAVIgFAAIAVAcIAXgcIgGAAIAAgVIAoAAIAAAVIgKAAIgiAnIAkApIAJAAIAAAUg");
	this.shape_8.setTransform(-33.925,275.775);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgUA8QgKgEgIgJQgHgHgFgNQgDgMAAgPQgBgNAEgLQADgMAIgIQAHgJAKgFQAMgFAMAAQAOAAAKAEQAIAFAGAGQAGAHADAJQADAJACAIIAAAJIABAIIhXAAIAAAKIADAIQAEAMAKAGQAJAFALABQAKgBAJgCQAJgCAJgGIAJAOQgLAJgMAEQgNAEgNAAQgLAAgLgEgAAfgOIgCgMQgCgFgEgFQgDgEgGgDQgFgCgIAAQgGAAgHACQgFACgEAFQgEADgCAHQgDAFgBAHIA+AAg");
	this.shape_9.setTransform(-47.5,275.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_10.setTransform(141.775,246.975);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_11.setTransform(131.475,248.775);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_12.setTransform(122.025,245.875);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_13.setTransform(112.325,248.725);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_14.setTransform(102.375,246.975);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgTA8QgLgEgIgJQgHgHgEgMQgFgNAAgPQABgMADgMQADgMAIgIQAHgJALgFQALgFANAAQANAAAJAEQAJAFAHAGQAFAHADAJQADAJABAIIABAJIAAAIIhWAAIABAKIACAIQAEAMAJAGQAKAFAMABQAJgBAJgCQAIgCAKgGIAJAOQgMAJgMAEQgMAEgNAAQgLAAgKgEgAAfgOIgCgMQgCgFgDgFQgEgEgFgDQgGgCgIAAQgHAAgFACQgGACgEAFQgEADgDAHQgCAFgBAHIA+AAg");
	this.shape_15.setTransform(90.7,248.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgNAAQgIAAgJAEQgIADgGAGIAABGIARAAIAAAUIg4AAIAAgUIASAAIAAg3QAAgOgIgHQgGgHgNAAQgJAAgHADQgIAEgGAFIAABHIAQAAIAAAUIg5AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAJgHIAJgFIALgEIAKgBQANAAAJAFQAJAFAGAKIAJgHIAKgHIALgEQAGgCAHAAQAJAAAIADQAIADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_16.setTransform(72.15,248.675);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_17.setTransform(52.875,248.775);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_18.setTransform(41.375,246.975);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag/BaIAAgUIARAAIAAiHIgRAAIAAgVIAmAAIAAAKQAIgGAJgDQAIgEAKAAQAMAAAKAFQAKAEAHAIQAHAIAEAMQAEALAAAOQAAAOgEANQgFALgHAIQgIAJgLAFQgLAEgNAAQgIAAgIgBIgNgFIAAAnIATAAIAAAUgAgLhCQgIADgFAGIAABBQADAEAIADQAHADAKAAQAHAAAHgCQAHgDAFgGQAGgGADgIQADgIAAgLQAAgLgDgIQgDgIgFgFQgFgGgHgCQgHgDgIAAQgHAAgIADg");
	this.shape_19.setTransform(29.425,251.375);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_20.setTransform(15.025,248.775);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgIgHQgHgHgMAAQgIAAgHADQgIAEgHAFIAABHIARAAIAAAUIg5AAIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAGAGACAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_21.setTransform(-5.3,248.675);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_22.setTransform(-20.075,248.825);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgRIAIAFIAKAFIALACIALABQAIAAAGgCQAHgCAEgEQAFgFACgIQACgIAAgMIAAgCQgGAGgIAEQgIADgKAAQgLAAgLgEQgLgEgHgJQgIgIgFgMQgEgLAAgPQAAgOAEgMQAEgLAIgIQAIgJALgFQALgEAMAAQAJAAAIACQAHADAHAFIAAgHIAWAAIAABzQAAAdgOAPQgOAPgcAAgAgJhCQgHADgFAFQgFAGgDAIQgDAIAAALQAAALACAIQADAIAFAGQAFAFAHAEQAHACAIAAIAKgBIAIgDIAGgEIAFgEIAAhCQgGgFgIgDQgIgCgIAAQgHAAgGADg");
	this.shape_23.setTransform(-39.025,251.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AALA+IAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgHAAgHADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJABALIAAA6IAQAAIAAAUg");
	this.shape_24.setTransform(-53.7,248.675);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_25.setTransform(-65.375,245.875);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AApBbIgwg2IgQAAIAAAiIAKAAIAAAUIg0AAIAAgUIAUAAIAAiNIgVAAIAAgUIArAAIAAAUIAABaIAVAAIAbgdIgHAAIAAgUIAuAAIAAAUIgPAAIglAlIAoArIAPAAIAAAUg");
	this.shape_26.setTransform(-76.625,245.725);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_27.setTransform(-91.675,248.775);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_28.setTransform(-106.025,248.775);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhBBZIAAgUIAQAAIAAiIIgQAAIAAgVIBOAAQALABAKAEQAJAEAHAGQAHAIAEAJQAEAJAAALQAAALgGAKQgGAJgMAGQAGACAEAEQAFAEADAFQAEAFACAFIABALQAAALgEAKQgEAKgHAGQgHAIgJAEQgKAEgLAAgAgaBFIApAAQAFAAAFgDIAJgHQADgFACgFQACgHAAgGQAAgFgCgEQgCgFgDgEIgJgGQgFgCgFAAIgpAAgAgagKIAoAAQAFAAAFgBQAFgDAEgEQADgEACgEQACgFAAgGQAAgFgCgFQgCgHgDgDQgEgFgFgDQgFgCgFAAIgoAAg");
	this.shape_29.setTransform(-120.575,245.95);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(-477,229.8,971.3,60), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAOIgFgDIgDgFIgBgGIABgFIADgFIAFgDIAFgBIAGABIAFADIADAFIABAFIgBAGIgDAFIgFADIgGABg");
	this.shape.setTransform(112.85,250.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgcBZQgLgFgIgIQgIgJgEgMQgEgMAAgPQAAgOAEgMQAEgKAIgIQAHgIALgFQALgEAOgBQAHAAAIACQAHADAHAEIAAguIgRAAIAAgUIAmAAIAAChIASAAIAAAUIgnAAIAAgKQgGAGgIAEQgIACgJAAQgMAAgKgDgAgSgLQgHADgFAFQgFAFgDAHQgDAJAAAKQAAALADAIQADAKAFAFQAFAGAHADQAHADAIgBQAJABAHgDQAGgDAGgGIAAhDQgGgFgIgCQgHgCgHAAQgIAAgHADg");
	this.shape_1.setTransform(102.875,242.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_2.setTransform(89.625,245.475);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_3.setTransform(77.325,245.575);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAMBbIAAgUIAQAAIAAg3QAAgOgHgGQgHgIgNAAQgHAAgHAEQgIADgHAFIAABHIASAAIAAAUIg6AAIAAgUIASAAIAAiNIgQAAIAAgUIAmAAIAABKIABAAIAHgGIAJgFIAKgDIAKgBQAJAAAIACQAIADAFAGQAGAFADAJQADAHAAAMIAAA6IASAAIAAAUg");
	this.shape_4.setTransform(63.225,242.475);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_5.setTransform(44.075,245.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_6.setTransform(34.625,242.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgRIAIAFIAKAFIALACIALABQAIAAAGgCQAHgCAEgEQAFgFACgIQACgIAAgMIAAgCQgGAGgIADQgIAEgKAAQgLAAgLgEQgLgEgHgJQgIgIgFgMQgEgLAAgPQAAgOAEgMQAEgMAIgHQAIgJALgFQALgEAMAAQAJAAAIACQAHACAHAGIAAgHIAWAAIAAB0QAAAdgOAPQgOAOgcAAgAgJhCQgHADgFAFQgFAGgDAIQgDAIAAALQAAAKACAJQADAIAFAFQAFAHAHACQAHADAIAAIAKgBIAIgDIAGgDIAFgFIAAhCQgGgFgIgDQgIgBgIAAQgHAAgGACg");
	this.shape_7.setTransform(18.025,248.05);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgIgHQgGgHgNAAQgIAAgHADQgIAEgGAFIAABHIAQAAIAAAUIg5AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_8.setTransform(3.35,245.425);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_9.setTransform(-8.325,242.625);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_10.setTransform(-16.725,243.725);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AALA+IAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgGAAgIADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAFAGADAIQAEAJAAALIAAA6IARAAIAAAUg");
	this.shape_11.setTransform(-29.2,245.425);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTA8QgLgEgHgJQgIgHgEgMQgFgNAAgPQABgNADgLQAEgMAHgIQAHgJALgFQAKgFANAAQAOAAAJAEQAJAEAHAHQAFAHADAJQADAIABAJIABAJIAAAIIhWAAIABAKIACAIQAEAMAJAGQAKAGAMAAQAJAAAJgDQAIgDALgFIAJAOQgNAJgMAEQgMAEgNAAQgLAAgKgEgAAfgOIgCgMQgCgFgDgFQgEgEgFgDQgGgCgIAAQgHAAgFACQgGACgEAFQgEADgDAHQgCAGgBAGIA+AAg");
	this.shape_12.setTransform(-44.4,245.55);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_13.setTransform(-56.675,245.475);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_14.setTransform(-68.975,245.575);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag+BZIAAgUIAQAAIAAiJIgQAAIAAgUIBGAAQAMAAAKADQAKADAIAGQAHAGAEAJQAEAJAAAMQAAAKgEAJQgEAIgHAHQgHAGgLADQgKADgMAAIgfAAIAAA/IASAAIAAAUgAgXgMIAfAAQAHAAAGgBQAFgCAEgEQAEgDADgGQACgFAAgHQAAgNgIgHQgIgIgSAAIgcAAg");
	this.shape_15.setTransform(-82.175,242.725);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(-92.3,226.6,209.89999999999998,33.00000000000003), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.volcanoman();
	this.instance.parent = this;
	this.instance.setTransform(-477,358,0.3411,0.3411);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-477,358,253.8,269.5), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape.setTransform(250.325,213.925);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_1.setTransform(237.525,213.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrBbIAAgUIASAAIAAhSIgUAAIAAgSIAUAAIAAgTQAAgLADgIQADgHAFgGQAFgFAIgDQAGgCAJAAIALAAIAJACIAHACIAFADIgHAPIgJgDIgNgCQgKAAgFAGQgFAGAAAMIAAAUIAbAAIAAASIgbAAIAABSIASAAIAAAUg");
	this.shape_2.setTransform(227.325,210.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgOAAQgHAAgIAEQgJADgGAGIAABGIARAAIAAAUIg3AAIAAgUIARAAIAAg3QAAgOgHgHQgIgHgNAAQgHAAgIADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAIgHIAJgFIAKgEIALgBQANAAAKAFQAIAFAFAKIAJgHIALgHIALgEQAGgCAGAAQAKAAAIADQAIADAGAFQAFAGADAIQACAJABALIAAA6IARAAIAAAUg");
	this.shape_3.setTransform(204.5,213.875);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AglBYIAAgUIAPAAIAMghIgohmIgKAAIAAgUIAuAAIAAAUIgOAAIAcBMIAdhMIgOAAIAAgUIAuAAIAAAUIgNAAIg1CHIAQAAIAAAUg");
	this.shape_4.setTransform(185.2,216.725);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AALA+IAAgUIASAAIAAg3QAAgOgIgHQgGgHgNAAQgIAAgHADQgIAEgGAFIAABHIAQAAIAAAUIg5AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_5.setTransform(170.75,213.875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_6.setTransform(155.475,213.975);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgHgHQgIgHgMAAQgIAAgHADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_7.setTransform(140.4,213.875);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AglBYIAAgUIAPAAIAMghIgohmIgKAAIAAgUIAuAAIAAAUIgOAAIAcBMIAdhMIgPAAIAAgUIAvAAIAAAUIgNAAIg1CHIAQAAIAAAUg");
	this.shape_8.setTransform(125.1,216.725);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_9.setTransform(112.825,213.975);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_10.setTransform(95.025,214.025);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_11.setTransform(79.025,212.175);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_12.setTransform(68.725,213.975);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgYA7QgIgCgFgGQgFgGgDgIQgDgJAAgLIAAg5IgQAAIAAgVIAnAAIAABLQAAAOAGAHQAHAHAMAAQAGAAAIgCQAIgDAHgFIAAhIIgQAAIAAgVIAnAAIAABlIANAAIAAAUIgjAAIAAgLQgIAGgKADQgKAEgKAAQgJAAgHgDg");
	this.shape_13.setTransform(54.375,214.075);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgWBkQALgBAFgJQAFgIAAgNIAAhrIgRAAIAAgVIAmAAIAACCQgBALgCAHQgDAJgEAGQgGAGgGADQgIADgJAAgAADhZIgDgDIgDgFIgBgFIABgFIADgEIADgEIAGgBIAFABIAFAEIACAEIABAFIgBAFIgCAFIgFADIgFABg");
	this.shape_14.setTransform(43.05,213.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_15.setTransform(29.025,213.975);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_16.setTransform(19.575,211.075);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AACAaIAXg7IAWAJIgdA6gAguAaIAWg7IAWAJIgdA6g");
	this.shape_17.setTransform(244.425,178.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AApBbIgwg2IgQAAIAAAiIAKAAIAAAUIg0AAIAAgUIAUAAIAAiNIgVAAIAAgUIArAAIAAAUIAABaIAVAAIAbgdIgHAAIAAgUIAuAAIAAAUIgPAAIglAlIAoArIAPAAIAAAUg");
	this.shape_18.setTransform(231.325,183.925);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_19.setTransform(217.825,186.925);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_20.setTransform(205.525,187.025);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("Ag/BaIAAgUIARAAIAAiHIgRAAIAAgVIAmAAIAAAKQAIgGAJgDQAIgEAKAAQAMAAAKAFQAKAEAHAIQAHAIAEAMQAEALAAAOQAAAOgEANQgFALgHAIQgIAJgLAFQgLAEgNAAQgIAAgIgBIgNgFIAAAnIATAAIAAAUgAgLhCQgIADgFAGIAABBQADAEAIADQAHADAKAAQAHAAAHgCQAHgDAFgGQAGgGADgIQADgIAAgLQAAgLgDgIQgDgIgFgFQgFgGgHgCQgHgDgIAAQgHAAgIADg");
	this.shape_21.setTransform(191.725,189.575);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_22.setTransform(174.925,185.175);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgHgHQgIgHgMAAQgIAAgHADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_23.setTransform(162.45,186.875);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgUA8QgKgFgIgHQgHgJgFgMQgDgMAAgPQAAgNADgLQAEgMAHgJQAHgIAKgFQAMgFANAAQANAAAJAEQAKAEAFAHQAGAHADAJQADAJACAJIAAAJIABAIIhXAAIAAAJIADAIQAEAMAKAGQAJAFALAAQAKABAJgDQAJgCAJgGIAJAPQgLAIgMAEQgNAEgNAAQgLAAgLgEgAAfgNIgCgNQgCgGgEgEQgDgEgGgDQgFgCgIAAQgGAAgHACQgFADgEADQgEAEgDAGQgCAHgBAHIA+AAg");
	this.shape_24.setTransform(147.25,187);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgOAAQgHAAgJAEQgHADgGAGIAABGIAQAAIAAAUIg4AAIAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgHAAgIADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIALgEIAKgBQANAAAKAFQAIAFAFAKIAJgHIALgHIALgEQAGgCAGAAQAKAAAIADQAIADAFAFQAGAGADAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_25.setTransform(128.7,186.875);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgTA8QgLgFgHgHQgIgJgEgMQgFgMAAgPQABgNADgLQAEgMAHgJQAHgIALgFQAKgFANAAQAOAAAJAEQAJAEAHAHQAFAHADAJQADAJABAJIABAJIAAAIIhWAAIABAJIACAIQAEAMAJAGQAKAFAMAAQAJABAJgDQAIgCALgGIAJAPQgNAIgMAEQgMAEgNAAQgLAAgKgEgAAfgNIgCgNQgCgGgDgEQgEgEgFgDQgGgCgIAAQgHAAgFACQgGADgEADQgEAEgCAGQgDAHgBAHIA+AAg");
	this.shape_26.setTransform(109.5,187);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_27.setTransform(97.125,186.975);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgYA7QgIgCgFgGQgFgGgDgIQgDgJAAgLIAAg5IgQAAIAAgVIAnAAIAABLQAAAOAGAHQAHAHAMAAQAGAAAIgCQAIgDAHgFIAAhIIgQAAIAAgVIAnAAIAABlIANAAIAAAUIgjAAIAAgLQgIAGgKADQgKAEgKAAQgJAAgHgDg");
	this.shape_28.setTransform(82.775,187.075);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgOAAQgHAAgJAEQgIADgFAGIAABGIAQAAIAAAUIg4AAIAAgUIASAAIAAg3QAAgOgHgHQgIgHgNAAQgHAAgIADQgIAEgGAFIAABHIARAAIAAAUIg5AAIAAgUIAQAAIAAhQIgQAAIAAgVIAnAAIAAAPIAIgHIAJgFIAKgEIALgBQANAAAKAFQAIAFAFAKIAJgHIALgHIALgEQAGgCAGAAQAKAAAIADQAIADAGAFQAFAGADAIQACAJABALIAAA6IARAAIAAAUg");
	this.shape_29.setTransform(63.55,186.875);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAgBZIAAgUIAOAAIgOgpIhDAAIgOApIATAAIAAAUIg6AAIAAgUIAPAAIA4idIAhAAIA3CdIASAAIAAAUgAAaAJIgbhPIgbBPIA2AAg");
	this.shape_30.setTransform(42.525,184.175);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AADAYIAdg5IAPAIIgWA7gAguAYIAdg5IAQAIIgXA7g");
	this.shape_31.setTransform(27.275,178.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(13.6,168,244.6,60), null);


(lib.shaker = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEANIgFgDIgDgFIgBgFIABgFIADgEIAFgDIAEgBIAGABIAEADIADAEIABAFIgBAFIgDAFIgEADIgGABg");
	this.shape.setTransform(179.225,62.375);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAKBTIAAgSIAQAAIAAgzQAAgNgHgFQgGgHgMAAQgGAAgHAEQgHADgHAEIAABBIARAAIAAASIg2AAIAAgSIASAAIAAiBIgQAAIAAgSIAjAAIAABDIABAAIAHgFIAJgFIAIgDIAJgBQAJAAAHADQAHACAFAFQAFAFADAIQADAHgBAKIAAA2IARAAIAAASg");
	this.shape_1.setTransform(169.7,55.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUA2QgHgEgFgGIgLAAIAAgTIAWAAQAAAFACADQACADAEACIAHAEIAHABIAIgBIAHgEQADgCACgCQACgDAAgEQgBgFgDgEQgEgEgIgDIgUgIQgNgDgGgIQgHgGAAgMQAAgGADgGQADgHAEgEQAFgEAHgCQAIgDAJAAQALAAAIADQAIAEAGAHIALAAIAAATIgWAAQAAgEgCgEQgCgDgEgBIgHgEIgHgBIgIABIgGADIgEAEIgCAHQABAFADAEQADACAJAEIATAHQAPAEAFAIQAHAHAAAMQAAAHgDAGQgDAGgFAFQgFAEgJACQgHADgKAAQgMAAgIgFg");
	this.shape_2.setTransform(156.95,58.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgbA4QgHgDgFgEQgFgEgDgHQgDgFAAgHQAAgHACgFQADgGAEgEQACgEAGgBIAJgFIALgDIAJAAIANAAIAKABIAAgJQAAgFgDgFQgBgEgDgDQgEgDgEgBQgEgBgFAAIgJAAIgJACIgHACIgGADIgGgNIAJgFIAKgEIAKgCIAKgBQAJAAAIACQAHADAGAEQAGAFADAIQADAHAAAKIgBA3IAMAAIAAASIggAAIAAgKQgGAGgIAEQgGAEgLAAQgHAAgHgDgAgOAGIgJADQgDADgCAEQgCAEAAAEQAAAFABADIAFAFIAHAEIAJABIAIgBIAGgDIAHgDIAFgFIABgZIgXAAQgGAAgEABg");
	this.shape_3.setTransform(145.45,58.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgnA4IAAgSIAPAAIAAhKIgPAAIAAgTIAkAAIAAAQIADgHIAFgEIAHgEIAIgBIAKAAIAKAAIAAAYIgUAAIAAgHIgIACQgDABgEADQgDADgCAEQgCAEgBAGIAAA1IASAAIAAASg");
	this.shape_4.setTransform(134.425,58.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgSA3QgKgEgHgJQgHgIgEgKQgEgLAAgNQAAgLAEgLQAFgLAHgIQAHgIAKgFQAKgEAKAAQAKAAAKAEQAJAEAHAHIAMAAIAAATIgVAAQgEgIgHgFQgHgDgJAAQgGAAgGACQgGADgFAGQgFAGgCAHQgDAIAAAIQAAAJADAIQACAHAFAGQAFAFAGADQAGADAGAAQAKAAAIgFQAHgFAFgKIAQAJQgDAGgEAFQgFAGgGAEQgGAEgHACQgHACgIAAQgLAAgKgEg");
	this.shape_5.setTransform(123.425,58.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgnA4IAAgSIAPAAIAAhKIgPAAIAAgTIAkAAIAAAQIADgHIAFgEIAHgEIAIgBIAKAAIAKAAIAAAYIgUAAIAAgHIgIACQgDABgEADQgDADgCAEQgCAEgBAGIAAA1IASAAIAAASg");
	this.shape_6.setTransform(107.325,58.05);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgbA4QgHgDgFgEQgFgEgDgHQgDgFAAgHQAAgHACgFQACgGAEgEQAEgEAFgBIAJgFIAKgDIAKAAIANAAIAKABIAAgJQAAgFgCgFQgCgEgDgDQgDgDgFgBQgEgBgFAAIgJAAIgJACIgHACIgGADIgGgNIAJgFIAJgEIALgCIAKgBQAJAAAIACQAHADAGAEQAFAFAEAIQADAHAAAKIgBA3IAMAAIAAASIggAAIAAgKQgGAGgIAEQgHAEgKAAQgHAAgHgDgAgOAGIgJADQgDADgCAEQgCAEAAAEQAAAFABADIAFAFIAHAEIAJABIAIgBIAGgDIAHgDIAFgFIABgZIgXAAQgGAAgEABg");
	this.shape_7.setTransform(96.05,58.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgLBRIgNgDIgMgFQgGgCgFgFIALgQIAHAFIAJAEIAKACIAKACQAHAAAHgCQAGgCAEgEQADgFACgHQACgIAAgLIAAgCQgFAHgIACQgHAEgJAAQgLAAgJgEQgKgEgHgHQgHgIgEgLQgEgKAAgOQAAgNAEgLQAEgKAGgIQAIgHAKgFQAKgDALAAQAIAAAHACQAHACAGAEIAAgGIAUAAIAABqQAAAbgMANQgNAOgaAAgAgJg8QgGADgFAFQgEAEgDAIQgCAHAAAKQgBAKADAIQADAGAEAGQAFAFAGADQAHADAHAAIAJgCIAHgCIAGgDIAEgFIAAg7QgFgGgIgBQgGgDgIAAQgGAAgHADg");
	this.shape_8.setTransform(83.5,60.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgWA2QgHgCgFgFQgFgFgCgIQgDgIAAgLIAAg0IgPAAIAAgTIAkAAIAABFQAAANAGAGQAGAHALAAQAGAAAHgDQAHgCAGgEIAAhDIgOAAIAAgTIAjAAIAABcIANAAIAAATIghAAIAAgLQgHAGgJADQgJAEgJAAQgIAAgHgDg");
	this.shape_9.setTransform(69.525,58.175);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgTA2QgJgEgEgGIgLAAIAAgTIAWAAQAAAFACADQACADADACIAIAEIAHABIAIgBIAHgEQADgCABgCQACgDAAgEQAAgFgDgEQgEgEgIgDIgUgIQgNgDgHgIQgGgGAAgMQAAgGADgGQADgHAFgEQAEgEAHgCQAIgDAJAAQALAAAIADQAIAEAHAHIAKAAIAAATIgWAAQAAgEgCgEQgCgDgDgBIgIgEIgHgBIgHABIgHADIgEAEIgBAHQgBAFAEAEQAEACAHAEIAVAHQANAEAHAIQAGAHAAAMQAAAHgDAGQgDAGgFAFQgGAEgHACQgIADgKAAQgMAAgHgFg");
	this.shape_10.setTransform(57.55,58.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgbA4QgHgDgFgEQgFgEgCgHQgEgFAAgHQAAgHACgFQADgGADgEQAEgEAEgBIAKgFIAKgDIAKAAIANAAIAKABIAAgJQAAgFgCgFQgCgEgDgDQgEgDgEgBQgEgBgFAAIgJAAIgJACIgHACIgGADIgHgNIAJgFIAKgEIALgCIAKgBQAJAAAIACQAHADAGAEQAGAFADAIQACAHAAAKIAAA3IAMAAIAAASIggAAIAAgKQgGAGgIAEQgHAEgKAAQgHAAgHgDgAgPAGIgIADQgEADgBAEQgCAEAAAEQAAAFACADIAEAFIAHAEIAJABIAIgBIAHgDIAGgDIAFgFIABgZIgXAAQgGAAgFABg");
	this.shape_11.setTransform(41.25,58.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgaBRQgKgEgHgIQgHgHgEgLQgEgLAAgOQAAgNAEgLQADgKAIgHQAHgHAKgFQAKgEAMAAQAHAAAHACQAHACAFAEIAAgqIgPAAIAAgTIAjAAIAACUIARAAIAAASIglAAIAAgJQgFAGgHADQgHADgIAAQgLAAgKgEgAgQgKQgHACgFAFQgEAEgCAIQgEAHAAAJQAAALADAHQADAIAEAGQAFAFAHADQAGACAHAAQAIAAAHgCQAFgDAFgFIAAg+QgFgEgHgCQgHgCgGAAQgHAAgGADg");
	this.shape_12.setTransform(23.95,55.425);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AALA5IAAgTIAPAAIAAgyQAAgMgGgHQgHgHgMAAQgGAAgHAEQgHADgGAFIAABAIAPAAIAAATIg0AAIAAgTIAQAAIAAhJIgQAAIAAgTIAkAAIAAAOIAAAAIAIgGIAIgFIAJgDIAJgCQAJAAAIADQAHACAFAFQAFAFADAIQACAIAAALIAAA0IAQAAIAAATg");
	this.shape_13.setTransform(9.725,57.975);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgbA4QgHgDgFgEQgFgEgDgHQgCgFAAgHQAAgHACgFQABgGAFgEQADgEAEgBIAKgFIALgDIAKAAIALAAIAKABIAAgJQAAgFgCgFQgBgEgDgDQgDgDgEgBQgFgBgEAAIgKAAIgIACIgIACIgGADIgHgNIAJgFIALgEIAKgCIALgBQAIAAAIACQAHADAGAEQAFAFADAIQADAHABAKIgBA3IANAAIAAASIghAAIAAgKQgGAGgIAEQgGAEgKAAQgJAAgGgDgAgOAGIgIADQgFADgBAEQgCAEAAAEQAAAFABADIAFAFIAHAEIAJABIAIgBIAGgDIAHgDIAFgFIAAgZIgWAAQgFAAgFABg");
	this.shape_14.setTransform(-3.8,58.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgUA3QgHgFgFgGIgLAAIAAgTIAWAAQAAAEACAEQACADAEACIAHADIAHABIAIgBIAHgDQADgBACgEQABgDAAgDQAAgFgDgEQgDgDgJgEIgUgIQgNgEgGgGQgHgIAAgKQAAgIADgGQACgFAFgFQAGgEAHgDQAHgCAJAAQALAAAIADQAIADAGAJIALAAIAAASIgWAAQAAgFgCgDQgCgDgEgCIgHgDIgHgBIgHABIgHADIgEAFIgCAGQAAAFAEAEQADADAIACIAUAIQAOAFAHAGQAGAJAAALQAAAHgDAGQgDAGgFAEQgGAFgHACQgIADgJAAQgMAAgJgEg");
	this.shape_15.setTransform(161.2,33.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAwA5IAAgTIAPAAIAAgyQAAgMgGgHQgHgHgMAAQgHAAgIAEQgHADgFAGIAAA/IAPAAIAAATIgzAAIAAgTIAPAAIAAgyQABgMgHgHQgHgHgLAAQgHAAgIAEQgHADgGAFIAABAIAPAAIAAATIg0AAIAAgTIAQAAIAAhJIgQAAIAAgTIAkAAIAAANIAAAAIAIgFIAIgFIAKgDIAJgCQAMAAAKAFQAHAEAFAKIAIgHIAKgGIAKgEIALgCQAJAAAHADQAHACAGAFQAEAFAEAIQACAIAAALIAAA0IAQAAIAAATg");
	this.shape_16.setTransform(144.9,33.375);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgWA2QgHgCgFgFQgFgFgCgIQgDgIAAgLIAAg0IgPAAIAAgTIAkAAIAABFQAAANAGAGQAGAHALAAQAGAAAHgDQAHgCAGgEIAAhDIgOAAIAAgTIAjAAIAABcIANAAIAAATIghAAIAAgLQgHAGgJADQgJAEgJAAQgIAAgHgDg");
	this.shape_17.setTransform(126.025,33.575);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgnA4IAAgTIAPAAIAAhJIgPAAIAAgTIAkAAIAAAQIADgHIAFgFIAHgDIAIgBIAKAAIAKAAIAAAYIgUAAIAAgGIgIABQgDABgEADQgDACgCAFQgCAEgBAGIAAA0IASAAIAAATg");
	this.shape_18.setTransform(114.175,33.45);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAABJQgGgCgDgEQgFgEgBgHQgCgHAAgLIAAg8IgRAAIAAgQIASAAIAAgbIASgJIAAAkIAaAAIAAAQIgaAAIAAA/QgBAHACAEQACAEADACQADABAEAAIAIAAIAIgDIAFANIgMAEQgFACgIAAQgHAAgEgCg");
	this.shape_19.setTransform(105.05,31.825);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AALA5IAAgTIAPAAIAAgyQAAgMgGgHQgHgHgMAAQgGAAgHAEQgHADgGAFIAABAIAPAAIAAATIg0AAIAAgTIAQAAIAAhJIgQAAIAAgTIAkAAIAAAOIAAAAIAIgGIAIgFIAJgDIAJgCQAJAAAIADQAHACAFAFQAFAFADAIQACAIAAALIAAA0IAQAAIAAATg");
	this.shape_20.setTransform(93.625,33.375);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgbA4QgHgDgFgEQgFgFgDgGQgCgFAAgHQAAgHABgGQACgFAFgEQACgEAGgCIAJgEIALgCIAKgBIALABIALABIAAgJQgBgHgCgEQgBgEgDgDQgEgDgEgBQgEgBgEgBIgKABIgIACIgIADIgGACIgGgNIAJgFIAKgEIAKgDIAKgBQAJABAIACQAIACAFAFQAFAFADAIQAEAHAAALIgBA2IAMAAIAAATIggAAIAAgLQgGAGgIAEQgGAEgKgBQgJABgGgDgAgOAGIgIAEQgEACgCAEQgCAEAAAEQAAAFABADIAFAGIAHADIAJABIAIgBIAGgDIAHgDIAFgFIABgaIgXAAQgGABgEABg");
	this.shape_21.setTransform(80.1,33.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAABJQgGgCgDgEQgEgEgDgHQgBgHAAgLIAAg8IgSAAIAAgQIASAAIAAgbIATgJIAAAkIAaAAIAAAQIgaAAIgBA/QABAHABAEQABAEAEACQADABAFAAIAHAAIAIgDIAEANIgKAEQgGACgIAAQgHAAgEgCg");
	this.shape_22.setTransform(70.25,31.825);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgRA3QgLgEgGgHQgIgIgDgLQgEgLAAgOQAAgMADgKQADgKAHgJQAHgHAKgFQAJgEAMgBQANABAIADQAJAEAFAHQAGAGACAHQADAJABAIIAAAIIABAIIhQAAIACAIIACAIQADALAJAFQAJAFAKAAQAJAAAIgCQAIgDAJgFIAIAOQgLAIgLADQgLAEgMgBQgKABgJgEgAAcgMIgBgMQgCgFgEgEQgCgEgGgCQgEgCgIAAQgGAAgFACQgGACgDAEQgEAEgCAFIgDAMIA4AAg");
	this.shape_23.setTransform(54.75,33.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgRA3QgLgEgGgHQgIgIgDgLQgEgLAAgOQAAgMADgKQADgKAHgJQAHgHAKgFQAJgEAMgBQANABAIADQAJAEAFAHQAGAGACAHQADAJABAIIAAAIIABAIIhQAAIACAIIACAIQADALAJAFQAJAFAKAAQAJAAAIgCQAIgDAJgFIAIAOQgLAIgLADQgLAEgMgBQgKABgJgEgAAdgMIgCgMQgCgFgEgEQgCgEgGgCQgEgCgIAAQgGAAgFACQgGACgDAEQgEAEgCAFIgDAMIA5AAg");
	this.shape_24.setTransform(42.15,33.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgnA4IAAgTIAPAAIAAhJIgPAAIAAgTIAkAAIAAAQIADgHIAFgFIAHgDIAIgBIAKAAIAKAAIAAAYIgUAAIAAgGIgIABQgDABgEADQgDACgCAFQgCAEgBAGIAAA0IASAAIAAATg");
	this.shape_25.setTransform(30.925,33.45);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAKBUIAAgTIAQAAIAAgzQAAgNgHgFQgGgHgMAAQgGAAgHAEQgIADgFAEIAABBIAQAAIAAATIg1AAIAAgTIARAAIAAiBIgQAAIAAgTIAkAAIAABFIAAAAIAHgGIAJgEIAIgEIAJgBQAJAAAHADQAHACAFAFQAGAFACAIQACAHAAALIAAA1IASAAIAAATg");
	this.shape_26.setTransform(18.75,30.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgbBSIAAgTIAPAAIAAh9IgmAAIAAAZIgWAAIAAgrICQAAIAAArIgVAAIAAgZIgrAAIAAB9IARAAIAAATg");
	this.shape_27.setTransform(3.65,30.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.shaker, new cjs.Rectangle(-21.2,15.9,205,55.199999999999996), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AghA5QgHgDgEgEIgFgGIgEgJIgBgNQAAgGACgKIAKgtIgPAAIAEgTIAmAAIgNA6QgFAVAEAJQAFAKAOAAQAHAAAEgCQAFgCAEgEIAHgJIAOg+IgPAAIAFgTIAlAAIgWBgIARAAIgEATIgnAAIADgMIgIAGIgHAFIgJACIgIABQgHAAgHgCg");
	this.shape.setTransform(111.725,71.825);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgbA5QgKgEgHgIQgHgGgEgLQgEgJAAgLQAAgIACgJQACgKAFgHQAEgIAGgGQAHgGAHgFQAIgEAIgCQAJgDAIAAQALAAAKAEQAKAEAHAHQAHAHAEAKQAEAJAAALQAAAJgCAJQgCAJgFAHQgEAIgGAHQgHAGgHAFQgIAEgIADQgJACgIAAQgMAAgJgEgAgJglQgIAEgGAGQgGAGgDAJQgEAJAAAKQAAAHACAGQADAHAEAFQAEAEAGACQAFADAHAAQAHAAAIgEQAIgDAGgHQAGgGAEgJQADgJAAgKQAAgHgCgGQgDgHgEgEQgEgEgGgDQgGgCgGAAQgIAAgHADg");
	this.shape_1.setTransform(97.525,71.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhDBUIAEgTIAMAAIAVghIgNhgIgLAAIAFgTIAqAAIgEATIgJAAIAHBGIAshGIgJAAIAEgTIAqAAIgFATIgJAAIhSCBIALAAIgEATg");
	this.shape_2.setTransform(84.4,74.35);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgwA6IAWhfIgWAAIAFgTIArAAIgDAPIAFgGIAIgGIAIgDIAJgBIAHAAIAGAAIAJABIgHAgIgXAAIADgOQgLAAgHAFQgHAGgFAJIgNA5IATAAIgEATg");
	this.shape_3.setTransform(67.275,71.675);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AghA5QgIgEgGgGQgGgHgEgIQgEgJAAgKQAAgPAGgOQAGgNAKgKQAJgKANgFQANgFAOAAQAIAAAIACQAHADAFAEIABgGIAXAAIgXBfIASAAIgEATIgoAAIABgIQgHAFgHADQgHACgIAAQgKAAgIgDgAgIglQgIAEgHAGQgGAHgEAKQgEAJAAAMQAAAHACAGQACAFADAEQAEAEAFACQAFACAGAAIAIgBIAIgDIAHgDIAGgEIAOg9QgCgEgHgDQgGgCgKAAQgIAAgIADg");
	this.shape_4.setTransform(53.375,71.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZA6QgJgEgHgHQgHgHgEgJQgEgKAAgNQAAgNAFgNQAFgNAJgJQAJgJANgGQAMgFANAAQALAAAJADQAIAEAGAGQAHAGADAIQADAIAAAJIgBALIgBAJIhYAAIAAACIgBADQAAAHADAGQACAGAEAEQAEAFAGACQAFADAHAAQAIAAAIgEQAIgEAGgHIAQAMIgJAJQgFAFgGACQgHADgHACIgOABQgKAAgKgDgAAjgNQAAgHgCgFQgCgGgDgDQgEgEgFgCQgGgBgGAAQgHAAgEACQgGACgFAEQgFADgEAGIgGALIBBAAIAAAAg");
	this.shape_5.setTransform(39.925,71.725);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAQA7IARhGQADgNgFgIQgFgGgMAAQgJAAgHADQgIAEgHAHIgTBTIgXAAIAXhfIgWAAIAEgTIAsAAIgDALQAIgGAJgEQAIgEALAAQAJAAAIADQAGADAFAFQAFAGABAHQABAJgCAKIgNA3IARAAIgFATg");
	this.shape_6.setTransform(25.35,71.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgZA6QgJgEgHgHQgHgHgEgJQgEgKAAgNQAAgNAFgNQAFgNAJgJQAJgJANgGQAMgFANAAQALAAAJADQAIAEAGAGQAHAGADAIQADAIAAAJIgBALIgBAJIhYAAIAAACIgBADQAAAHADAGQACAGAEAEQAEAFAGACQAFADAHAAQAIAAAIgEQAIgEAGgHIAQAMIgJAJQgFAFgGACQgHADgHACIgOABQgKAAgKgDgAAjgNQAAgHgCgFQgCgGgDgDQgEgEgFgCQgGgBgGAAQgHAAgEACQgGACgFAEQgFADgEAGIgGALIBBAAIAAAAg");
	this.shape_7.setTransform(6.425,71.725);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAQA7IARhGQADgNgFgIQgFgGgMAAQgJAAgHADQgIAEgHAHIgTBTIgXAAIAWhfIgVAAIAEgTIArAAIgCALQAIgGAJgEQAIgEALAAQAJAAAIADQAGADAFAFQAEAGACAHQABAJgCAKIgNA3IARAAIgEATg");
	this.shape_8.setTransform(-8.2,71.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgbA5QgKgEgHgIQgHgGgEgLQgEgJAAgLQAAgIACgJQACgKAFgHQAEgIAGgGQAHgGAHgFQAIgEAIgCQAJgDAIAAQALAAAKAEQAKAEAHAHQAHAHAEAKQAEAJAAALQAAAJgCAJQgCAJgFAHQgEAIgGAHQgHAGgHAFQgIAEgIADQgJACgIAAQgMAAgJgEgAgJglQgIAEgGAGQgGAGgDAJQgEAJAAAKQAAAHACAGQADAHAEAFQAEAEAGACQAFADAHAAQAHAAAIgEQAIgDAGgHQAGgGAEgJQADgJAAgKQAAgHgCgGQgDgHgEgEQgEgEgGgDQgGgCgGAAQgIAAgHADg");
	this.shape_9.setTransform(-22.725,71.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgnBUQgIgEgHgGQgGgHgEgJQgDgJAAgLQAAgPAFgNQAGgMAJgKQAJgKANgFQANgFANAAQAJAAAHACQAIADAGAEIAKgtIgTAAIAEgTIAqAAIgkCaIAUAAIgFATIgpAAIABgIQgGAFgGACQgHADgIAAQgKAAgJgEgAgQgJQgIADgGAGQgHAGgDAKQgEAJAAALQAAAIACAGQACAGAEAEQAEAEAFACQAGADAGAAQAHAAAIgEQAGgDAGgGIAOg7QgEgEgGgDQgHgDgJAAQgIAAgIAEg");
	this.shape_10.setTransform(-41.475,68.925);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAQA7IARhGQADgNgFgIQgFgGgMAAQgJAAgHADQgIAEgHAHIgTBTIgXAAIAWhfIgVAAIAEgTIArAAIgCALQAIgGAJgEQAIgEALAAQAJAAAIADQAGADAFAFQAEAGACAHQABAJgCAKIgNA3IARAAIgEATg");
	this.shape_11.setTransform(-56.8,71.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgbBVIAWhfIgVAAIAFgTIAqAAIgVBfIARAAIgEATgAAIg4IgFgDIgDgFIAAgGIAAgGIADgEIAFgEIAGgBIAFABIAGAEIACAEIABAGIgBAGIgCAFIgGADIgFABg");
	this.shape_12.setTransform(-68,68.95);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag7ByIAiiUIgYAAIAFgTIAXAAIAFgUQACgLAFgIQAEgHAFgFQAGgFAIgCQAIgCAIAAIAKAAIAJACIAGACIAFACIgLASIgIgEIgLgBQgJAAgHAFQgGAFgDAMIgEATIAfAAIgEATIgfAAIgiCUg");
	this.shape_13.setTransform(-75.025,71.325);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(1,1,1).p("A2PjWMAsfAAAIAAGtMgsfAAAg");
	this.shape_14.setTransform(15.425,69.775);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(-127.9,47.3,286.70000000000005,45), null);


(lib.doclogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Tween2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(276.95,101.25,0.6296,0.6296,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.doclogo, new cjs.Rectangle(187.5,82.3,354.70000000000005,68.00000000000001), null);


(lib.bywhen = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shaker();
	this.instance.parent = this;
	this.instance.setTransform(86.3,22.5,1,1,0,0,0,86.3,22.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bywhen, new cjs.Rectangle(-21.2,15.9,205,55.199999999999996), null);


// stage content:
(lib._300x600_bcd_park = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 8
	this.instance = new lib.cta();
	this.instance.parent = this;
	this.instance.setTransform(536.1,270.9,0.95,0.95,0,0,0,105.5,22.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(311).to({_off:false},0).wait(1).to({regX:15.4,regY:69.8,x:449,y:316.2},0).wait(1).to({x:443.3},0).wait(1).to({x:430.45},0).wait(1).to({x:404.1},0).wait(1).to({x:356.6},0).wait(1).to({x:305.75},0).wait(1).to({x:269.15},0).wait(1).to({x:243.15},0).wait(1).to({x:223.7},0).wait(1).to({x:208.6},0).wait(1).to({x:196.55},0).wait(1).to({x:186.75},0).wait(1).to({x:178.75},0).wait(1).to({x:172.2},0).wait(1).to({x:166.85},0).wait(1).to({x:162.45},0).wait(1).to({x:158.95},0).wait(1).to({x:156.15},0).wait(1).to({x:154},0).wait(1).to({x:152.4},0).wait(1).to({x:151.35},0).wait(1).to({x:150.7},0).wait(1).to({regX:105.5,regY:22.1,x:236.1,y:270.9},0).wait(27));

	// Layer 6
	this.instance_1 = new lib.doclogo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-339.8,195.15,0.8,0.8,0,0,0,143.1,30.2);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(311).to({_off:false},0).wait(1).to({regX:364.9,regY:116.3,x:-160.8,y:264.05},0).wait(1).to({x:-154.85},0).wait(1).to({x:-141.5},0).wait(1).to({x:-114.1},0).wait(1).to({x:-64.7},0).wait(1).to({x:-11.8},0).wait(1).to({x:26.25},0).wait(1).to({x:53.3},0).wait(1).to({x:73.5},0).wait(1).to({x:89.25},0).wait(1).to({x:101.75},0).wait(1).to({x:111.95},0).wait(1).to({x:120.25},0).wait(1).to({x:127.05},0).wait(1).to({x:132.65},0).wait(1).to({x:137.2},0).wait(1).to({x:140.9},0).wait(1).to({x:143.8},0).wait(1).to({x:146.05},0).wait(1).to({x:147.65},0).wait(1).to({x:148.8},0).wait(1).to({x:149.4},0).wait(1).to({regX:143.1,regY:30.2,x:-27.8,y:195.15},0).wait(27));

	// Layer 5
	this.instance_2 = new lib.Symbol3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(364,68,1,1,0,0,0,221.8,32.4);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(182).to({_off:false},0).wait(37).to({y:67},0).wait(1).to({regX:12.9,regY:245.1,x:155.1,y:279.4},0).wait(1).to({y:278.2},0).wait(1).to({y:274.9},0).wait(1).to({y:269.4},0).wait(1).to({y:265.7},0).wait(1).to({y:263.55},0).wait(1).to({y:262.3},0).wait(1).to({y:261.5},0).wait(1).to({y:261},0).wait(1).to({y:260.75},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:48},0).wait(75).to({regX:12.9,regY:245.1,x:155.1,y:261.45},0).wait(1).to({y:264.1},0).wait(1).to({y:269.1},0).wait(1).to({y:277.3},0).wait(1).to({y:290},0).wait(1).to({y:309.6},0).wait(1).to({y:340.85},0).wait(1).to({y:393.1},0).wait(1).to({y:466.35},0).wait(1).to({y:523.9},0).wait(1).to({y:559.15},0).wait(1).to({y:581.65},0).wait(1).to({y:596.7},0).wait(1).to({y:606.8},0).wait(1).to({y:613.55},0).wait(1).to({y:617.75},0).wait(1).to({y:620},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:408},0).to({_off:true},1).wait(38));

	// Layer 4
	this.instance_3 = new lib.bywhen();
	this.instance_3.parent = this;
	this.instance_3.setTransform(808.2,72.7,4.8399,4.8399,5.9978,0,0,86.5,22.7);
	this.instance_3._off = true;

	this.instance_4 = new lib.Symbol5();
	this.instance_4.parent = this;
	this.instance_4.setTransform(364,60.75,1,1,0,0,0,221.8,17.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(93).to({_off:false},0).wait(1).to({regX:85.9,regY:45.5,scaleX:4.7585,scaleY:4.7585,rotation:5.7232,x:779.5,y:182.35},0).wait(1).to({scaleX:4.5209,scaleY:4.5209,rotation:4.9235,x:737.8,y:182.95},0).wait(1).to({scaleX:4.1461,scaleY:4.1461,rotation:3.6617,x:671.65,y:183.75},0).wait(1).to({scaleX:3.665,scaleY:3.665,rotation:2.0414,x:586.2,y:184.65},0).wait(1).to({scaleX:3.1202,scaleY:3.1202,rotation:0.2069,x:488.75,y:185.55},0).wait(1).to({scaleX:2.5641,scaleY:2.5641,rotation:-1.6653,x:388.5,y:186.45},0).wait(1).to({scaleX:2.0533,scaleY:2.0533,rotation:-3.3853,x:295.55,y:187.2},0).wait(1).to({scaleX:1.6412,scaleY:1.6412,rotation:-4.7729,x:220.15,y:187.75},0).wait(1).to({scaleX:1.3722,scaleY:1.3722,rotation:-5.679,x:170.7,y:188.2},0).wait(1).to({regX:86.3,regY:22.7,scaleX:1.2777,scaleY:1.2777,rotation:-5.997,x:150.95,y:159.3},0).to({_off:true},79).wait(179));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(219).to({_off:false},0).to({alpha:1},16).wait(70).to({regX:9.2,regY:259.4,x:151.4,y:303.2},0).wait(1).to({y:305.75},0).wait(1).to({y:310.65},0).wait(1).to({y:318.65},0).wait(1).to({y:331.1},0).wait(1).to({y:350.25},0).wait(1).to({y:380.85},0).wait(1).to({y:431.9},0).wait(1).to({y:503.5},0).wait(1).to({y:559.8},0).wait(1).to({y:594.3},0).wait(1).to({y:616.3},0).wait(1).to({y:630.95},0).wait(1).to({y:640.9},0).wait(1).to({y:647.45},0).wait(1).to({y:651.55},0).wait(1).to({y:653.75},0).wait(1).to({regX:221.8,regY:17.7,x:364,y:412.75},0).to({_off:true},1).wait(38));

	// Layer 2
	this.instance_5 = new lib.Symbol1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-200.65,49.75,1,1,0,0,0,136.3,32.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({regX:135.7,regY:200.2,x:-187.8,y:217.55},0).wait(1).to({x:-170.85},0).wait(1).to({x:-148.8},0).wait(1).to({x:-119.05},0).wait(1).to({x:-78.75},0).wait(1).to({x:-32.65},0).wait(1).to({x:6.25},0).wait(1).to({x:34.8},0).wait(1).to({x:56.05},0).wait(1).to({x:72.45},0).wait(1).to({x:85.5},0).wait(1).to({x:96.2},0).wait(1).to({x:105.05},0).wait(1).to({x:112.5},0).wait(1).to({x:118.8},0).wait(1).to({x:124.15},0).wait(1).to({x:128.7},0).wait(1).to({x:132.6},0).wait(1).to({x:135.9},0).wait(1).to({x:138.7},0).wait(1).to({x:141.1},0).wait(1).to({x:143.05},0).wait(1).to({x:144.7},0).wait(1).to({x:146},0).wait(1).to({x:147.05},0).wait(1).to({x:147.8},0).wait(1).to({x:148.35},0).wait(1).to({x:148.65},0).wait(1).to({regX:136.3,regY:32.4,x:149.35,y:49.75},0).wait(63).to({regX:135.7,regY:200.2,scaleX:1.0075,scaleY:1.0075,x:146.55,y:217.75},0).wait(1).to({scaleX:1.0326,scaleY:1.0326,x:139.35,y:218.4},0).wait(1).to({scaleX:1.0812,scaleY:1.0812,x:125.25,y:219.7},0).wait(1).to({scaleX:1.1616,scaleY:1.1616,x:101.95,y:221.9},0).wait(1).to({scaleX:1.2869,scaleY:1.2869,x:65.7,y:225.3},0).wait(1).to({scaleX:1.4759,scaleY:1.4759,x:10.95,y:230.35},0).wait(1).to({scaleX:1.7436,scaleY:1.7436,x:-66.6,y:237.55},0).wait(1).to({scaleX:2.0621,scaleY:2.0621,x:-158.85,y:246.15},0).wait(1).to({scaleX:2.3531,scaleY:2.3531,x:-243.2,y:253.95},0).wait(1).to({scaleX:2.5761,scaleY:2.5761,x:-307.8,y:259.95},0).wait(1).to({scaleX:2.7383,scaleY:2.7383,x:-354.7,y:264.3},0).wait(1).to({scaleX:2.8555,scaleY:2.8555,x:-388.7,y:267.45},0).wait(1).to({scaleX:2.9401,scaleY:2.9401,x:-413.2,y:269.7},0).wait(1).to({scaleX:3.0003,scaleY:3.0003,x:-430.6,y:271.3},0).wait(1).to({scaleX:3.0417,scaleY:3.0417,x:-442.6,y:272.45},0).wait(1).to({scaleX:3.0682,scaleY:3.0682,x:-450.3,y:273.15},0).wait(1).to({scaleX:3.0826,scaleY:3.0826,x:-454.5,y:273.55},0).wait(1).to({regX:136.2,regY:32.4,scaleX:3.0871,scaleY:3.0871,x:-454.1,y:-244.25},0).to({_off:true},163).wait(89));

	// Layer 3
	this.instance_6 = new lib.Symbol2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(539.85,458.95,0.8348,0.8348,0,0,0,112.2,112.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({regX:-350.1,regY:492.7,x:153.95,y:765},0).wait(1).to({y:751.1},0).wait(1).to({y:732.95},0).wait(1).to({y:708.45},0).wait(1).to({y:675.3},0).wait(1).to({y:637.35},0).wait(1).to({y:605.35},0).wait(1).to({y:581.85},0).wait(1).to({y:564.4},0).wait(1).to({y:550.9},0).wait(1).to({y:540.15},0).wait(1).to({y:531.35},0).wait(1).to({y:524.05},0).wait(1).to({y:517.95},0).wait(1).to({y:512.75},0).wait(1).to({y:508.35},0).wait(1).to({y:504.6},0).wait(1).to({y:501.35},0).wait(1).to({y:498.65},0).wait(1).to({y:496.3},0).wait(1).to({y:494.35},0).wait(1).to({y:492.7},0).wait(1).to({y:491.4},0).wait(1).to({y:490.3},0).wait(1).to({y:489.45},0).wait(1).to({y:488.85},0).wait(1).to({y:488.4},0).wait(1).to({y:488.15},0).wait(1).to({regX:112.2,regY:112.8,x:539.85,y:170.95},0).wait(63).to({regX:-350.1,regY:492.7,scaleX:0.8368,scaleY:0.8368,x:153.85,y:488.15},0).wait(1).to({scaleX:0.8434,scaleY:0.8434,x:153.7,y:488.4},0).wait(1).to({scaleX:0.8561,scaleY:0.8561,x:153.4,y:489},0).wait(1).to({scaleX:0.8771,scaleY:0.8771,x:152.9,y:489.85},0).wait(1).to({scaleX:0.9099,scaleY:0.9099,x:152.1,y:491.2},0).wait(1).to({scaleX:0.9594,scaleY:0.9594,x:150.9,y:493.3},0).wait(1).to({scaleX:1.0294,scaleY:1.0294,x:149.15,y:496.25},0).wait(1).to({scaleX:1.1128,scaleY:1.1128,x:147.15,y:499.8},0).wait(1).to({scaleX:1.189,scaleY:1.189,x:145.3,y:502.95},0).wait(1).to({scaleX:1.2473,scaleY:1.2473,x:143.85,y:505.4},0).wait(1).to({scaleX:1.2898,scaleY:1.2898,x:142.85,y:507.15},0).wait(1).to({scaleX:1.3205,scaleY:1.3205,x:142.1,y:508.45},0).wait(1).to({scaleX:1.3426,scaleY:1.3426,x:141.55,y:509.35},0).wait(1).to({scaleX:1.3584,scaleY:1.3584,x:141.15,y:510},0).wait(1).to({scaleX:1.3692,scaleY:1.3692,x:140.9,y:510.5},0).wait(1).to({scaleX:1.3761,scaleY:1.3761,x:140.7,y:510.8},0).wait(1).to({scaleX:1.3799,scaleY:1.3799,x:140.65,y:510.95},0).wait(1).to({regX:112.5,regY:112.5,scaleX:1.3811,scaleY:1.3811,x:779.15,y:-13.8},0).wait(1).to({regX:-350.1,regY:492.7,x:140.3,y:511.3},0).wait(1).to({x:140.35},0).wait(1).to({x:140.45},0).wait(1).to({x:140.55},0).wait(1).to({x:140.75},0).wait(1).to({x:141.05},0).wait(1).to({x:141.35},0).wait(1).to({x:141.7},0).wait(1).to({x:142.05},0).wait(1).to({x:142.3},0).wait(1).to({x:142.45},0).wait(1).to({x:142.6},0).wait(1).to({x:142.65},0).wait(1).to({regX:112.5,regY:112.5,x:781.55,y:-13.8},0).wait(1).to({regX:-350.1,regY:492.7,x:142.7,y:511.35},0).wait(1).to({y:511.4},0).wait(1).to({y:511.5},0).wait(1).to({y:511.65},0).wait(1).to({y:511.8},0).wait(1).to({y:512.1},0).wait(1).to({y:512.4},0).wait(1).to({y:512.8},0).wait(1).to({y:513.25},0).wait(1).to({y:513.75},0).wait(1).to({y:514.25},0).wait(1).to({y:514.75},0).wait(1).to({y:515.15},0).wait(1).to({y:515.5},0).wait(1).to({y:515.75},0).wait(1).to({y:515.9},0).wait(1).to({y:516.05},0).wait(1).to({y:516.1},0).wait(1).to({regX:112.5,regY:112.5,x:781.55,y:-9},0).wait(1).to({regX:-350.1,regY:492.7,x:142.65,y:516.1},0).wait(1).to({y:516.05},0).wait(1).to({y:516},0).wait(1).to({x:142.6,y:515.9},0).wait(1).to({x:142.55,y:515.75},0).wait(1).to({x:142.5,y:515.55},0).wait(1).to({x:142.4,y:515.3},0).wait(1).to({x:142.3,y:515},0).wait(1).to({x:142.2,y:514.7},0).wait(1).to({x:142.05,y:514.3},0).wait(1).to({x:141.95,y:513.95},0).wait(1).to({x:141.8,y:513.55},0).wait(1).to({x:141.7,y:513.25},0).wait(1).to({x:141.65,y:513},0).wait(1).to({x:141.55,y:512.8},0).wait(1).to({y:512.7},0).wait(1).to({x:141.5,y:512.6},0).wait(1).to({y:512.55},0).wait(1).to({regX:112.5,regY:112.5,x:780.35,y:-12.6},0).wait(1).to({regX:-350.1,regY:492.7,x:141.5,y:512.5},0).wait(3).to({x:141.55,y:512.45},0).wait(1).to({x:141.6,y:512.4},0).wait(1).to({x:141.65,y:512.35},0).wait(1).to({x:141.7,y:512.3},0).wait(1).to({x:141.8,y:512.2},0).wait(1).to({x:141.9,y:512.1},0).wait(1).to({x:142,y:512},0).wait(1).to({x:142.15,y:511.85},0).wait(1).to({x:142.25,y:511.75},0).wait(1).to({x:142.35,y:511.65},0).wait(1).to({x:142.45,y:511.55},0).wait(1).to({x:142.55,y:511.45},0).wait(1).to({x:142.6,y:511.4},0).wait(1).to({x:142.65,y:511.35},0).wait(3).to({regX:112.5,regY:112.5,x:781.55,y:-13.8},0).to({_off:true},1).wait(179));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EEB1AC").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(1,1,1,1,0,0,0,-149,-299);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(361));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-682.7,285.5,1962.5,603.1);
// library properties:
lib.properties = {
	id: 'F3B295547F6C4148B2E896B46B1DB47D',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/300x600_bcd_park_atlas_.png", id:"300x600_bcd_park_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['F3B295547F6C4148B2E896B46B1DB47D'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;