(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"300x250_aaoo_boy_atlas_", frames: [[0,0,300,250]]}
];


// symbols:



(lib.bb_boy = function() {
	this.initialize(ss["300x250_aaoo_boy_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#51C4ED").s().p("AgOCEIgUgEIgSgGIgRgJIgPgLIgRgSIgLgPIgJgSIgGgSIgEgUIAAgbIAEgTIAGgTIAJgRIAOgUIAOgMIAPgLIARgJIANgFIAZgEIATgBIAhAFIAYAKIAGAEIAQALIANAMIAQAUIAJARIAIAZIACAUIAAANIgCAUIgIAZIgDAGIgKARIgQAUIgOAMIgWANIgMAFIgTAGIgaACg");
	this.shape.setTransform(13.2,13.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol6, new cjs.Rectangle(0,0,26.4,26.4), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#51C4ED").s().p("AgIAqIAAhDIgVAAIAAgQIA7AAIAAAQIgVAAIAABDg");
	this.shape.setTransform(134.525,114.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#51C4ED").s().p("AgdAfIAKgNQALAJAKAAQAEABAEgDQADgCAAgEQAAgDgDgCQgEgDgHgEQgNgEgFgEQgHgGABgKIAAgBQAAgKAHgIQAIgGALAAQAQAAAMAKIgKANQgKgIgIAAQgDAAgDACQgDACAAAEQAAAEADACQADACAJAEQALAFAGAEQAFAGABAJIAAABQgBAMgHAGQgIAHgMAAQgSAAgNgMg");
	this.shape_1.setTransform(127.8,114.45);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#51C4ED").s().p("AgIAqIAAhTIARAAIAABTg");
	this.shape_2.setTransform(122.875,114.45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#51C4ED").s().p("AAMAqIgPgbIgKAAIAAAbIgSAAIAAhTIAfAAQAOAAAJAIQAHAHAAANIAAAAQAAARgQAHIASAfgAgNAAIAMAAQAGAAAEgDQADgEAAgFQAAgNgNgBIgMAAg");
	this.shape_3.setTransform(117.625,114.45);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#51C4ED").s().p("AgIAqIAAhDIgVAAIAAgQIA7AAIAAAQIgVAAIAABDg");
	this.shape_4.setTransform(110.325,114.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#51C4ED").s().p("AgaAqIAAhTIA1AAIAAAPIgkAAIAAATIAfAAIAAAOIgfAAIAAATIAkAAIAAAQg");
	this.shape_5.setTransform(103.775,114.45);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#51C4ED").s().p("AAUAqIAAg0IgUAhIAAAAIgTghIAAA0IgRAAIAAhTIASAAIASAiIATgiIASAAIAABTg");
	this.shape_6.setTransform(95.675,114.45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#51C4ED").s().p("AgbAgQgKgNAAgSIAAgBQAAgSAKgMQAMgNAPAAQAQAAAMANQAKALAAATIAAAAQAAAUgLAMQgLAMgQgBQgQABgLgMgAgNgTQgGAHAAAMIAAAAQAAAMAGAIQAFAHAIAAQAJAAAFgHQAGgHAAgNIAAAAQAAgMgGgHQgFgHgJgBQgIABgFAHg");
	this.shape_7.setTransform(86.85,114.45);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#51C4ED").s().p("AgIAqIAAhDIgVAAIAAgQIA7AAIAAAQIgVAAIAABDg");
	this.shape_8.setTransform(79.225,114.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#51C4ED").s().p("AgcAqIAAhTIAcAAQANAAAIAHQAIAJAAANQAAANgJAIQgIAHgNAAIgKAAIAAAagAgLABIAKAAQAFAAAEgDQAEgEAAgFQAAgOgNgBIgKAAg");
	this.shape_9.setTransform(72.675,114.45);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#51C4ED").s().p("AgbAgQgKgNAAgSIAAgBQAAgSAKgMQAMgNAPAAQARAAAKANQALALAAATIAAAAQAAAUgLAMQgLAMgQgBQgQABgLgMgAgNgTQgGAHAAAMIAAAAQAAAMAGAIQAFAHAIAAQAJAAAGgHQAFgHAAgNIAAAAQAAgMgGgHQgGgHgIgBQgIABgFAHg");
	this.shape_10.setTransform(64.6,114.45);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#51C4ED").s().p("AARAqIgfgyIAAAyIgRAAIAAhTIAQAAIAeAwIAAgwIARAAIAABTg");
	this.shape_11.setTransform(53.55,114.45);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#51C4ED").s().p("AAVAqIgHgSIgcAAIgGASIgSAAIAfhTIAPAAIAfBTgAAJAJIgJgbIgJAbIASAAg");
	this.shape_12.setTransform(45.45,114.425);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#51C4ED").s().p("AggAqIAAhTIAbAAQAQAAAMAMQALALAAASIAAAAQAAATgLAMQgMALgQAAgAgPAaIAKAAQAIABAGgIQAHgGAAgNIAAAAQAAgLgHgIQgGgHgIAAIgKAAg");
	this.shape_13.setTransform(34.9,114.45);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#51C4ED").s().p("AASAqIgggyIAAAyIgSAAIAAhTIARAAIAeAwIAAgwIARAAIAABTg");
	this.shape_14.setTransform(26.65,114.45);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#51C4ED").s().p("AgIAqIAAhTIARAAIAABTg");
	this.shape_15.setTransform(20.825,114.45);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#51C4ED").s().p("AgaAqIAAhTIA1AAIAAAQIgkAAIAAATIAgAAIAAAPIggAAIAAAhg");
	this.shape_16.setTransform(16,114.45);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgFAPIgFgEIgDgFIgCgGIACgGIADgEIAFgEIAFgBIAHABIAEAEIAEAEIABAGIgBAGIgEAFIgEAEIgHABg");
	this.shape_17.setTransform(119.4,80.95);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AA2BBIAAgWIASAAIAAg4QAAgPgHgHQgIgIgNAAQgJAAgIAEQgJAEgGAGIAABIIARAAIAAAWIg6AAIAAgWIASAAIAAg4QABgPgIgHQgHgIgPAAQgHAAgJAEQgIAEgGAGIAABIIASAAIAAAWIg8AAIAAgWIASAAIAAhTIgSAAIAAgVIApAAIAAAPIAJgHIAJgFIALgEIALgCQAOABAKAFQAIAFAFALIALgIIAKgHIALgFQAHgCAGAAQAKAAAJAEQAIADAFAFQAGAGAEAJQACAJAAAMIAAA7IASAAIAAAWg");
	this.shape_18.setTransform(104.15,75.95);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgfA/QgIgCgGgGQgFgEgEgHQgDgHAAgIQABgHACgGQADgHADgEQAEgFAFgCIALgFIANgDIALAAIAOAAIALACIAAgLQAAgGgCgFQgCgGgEgDQgDgDgFgCQgFgBgFAAIgLAAIgKACIgIAEIgHADIgHgQIAJgFIAMgFIAMgCIAMgBQAKAAAJADQAIACAHAGQAGAFADAIQAEAJgBAMIAAA+IAPAAIAAAVIglAAIAAgLQgIAGgJAEQgHAEgLAAQgJAAgIgDgAgQAHQgGABgEADQgEADgCAEQgCAEAAAFQAAAFACAEQABAEADADIAIADIALABIAJgBIAHgCIAIgFIAGgFIAAgcIgZAAIgMABg");
	this.shape_19.setTransform(84.6,76.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AASA/IAAgVIAIAAIgZgfIgYAfIAGAAIAAAVIgqAAIAAgVIAKAAIAngsIgkgnIgNAAIAAgVIAqAAIAAAVIgFAAIAXAeIAXgeIgGAAIAAgVIAqAAIAAAVIgLAAIgkApIAmAqIAJAAIAAAVg");
	this.shape_20.setTransform(71.325,76.075);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgUA/QgLgFgIgIQgIgJgFgMQgEgNAAgQQAAgNAEgMQAEgMAHgJQAIgJALgFQALgGAOAAQAOAAAJAFQAKAEAHAHQAGAHADAKQADAJABAJIAAAKIABAIIhbAAIABAKIADAIQAEAMAKAHQAKAGAMAAQAJAAAKgDQAJgDAKgGIAJAQQgMAIgNAFQgMAEgOAAQgMAAgKgEgAAhgOIgDgNQgBgGgEgEQgEgFgFgCQgHgCgIAAQgHAAgFACQgHACgDAEQgFAEgCAHQgDAGgBAHIBBAAg");
	this.shape_21.setTransform(57.2,76.075);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgUA/QgLgFgIgIQgIgJgEgMQgFgNAAgQQAAgNAEgMQAEgMAHgJQAIgJALgFQALgGAOAAQAOAAAKAFQAJAEAGAHQAHAHACAKQAEAJABAJIABAKIAAAIIhaAAIABAKIABAIQAFAMALAHQAJAGALAAQAKAAAKgDQAKgDAKgGIAJAQQgMAIgNAFQgNAEgNAAQgMAAgLgEgAAggOIgCgNQgCgGgDgEQgEgFgGgCQgFgCgJAAQgGAAgHACQgGACgEAEQgEAEgDAHQgCAGgBAHIBAAAg");
	this.shape_22.setTransform(37.45,76.075);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgnBcIAAgVIAQAAIANgjIgqhqIgKAAIAAgVIAwAAIAAAVIgQAAIAeBQIAehQIgPAAIAAgVIAwAAIAAAVIgNAAIg3CNIAQAAIAAAVg");
	this.shape_23.setTransform(23.025,78.95);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgUA/QgLgFgIgIQgIgJgFgMQgEgNAAgQQAAgNAEgMQAEgMAIgJQAHgJALgFQALgGAOAAQAOAAAJAFQAKAEAHAHQAFAHADAKQADAJACAJIABAKIAAAIIhbAAIACAKIACAIQAFAMAJAHQAKAGAMAAQAKAAAJgDQAJgDAKgGIAJAQQgMAIgNAFQgMAEgNAAQgMAAgLgEgAAhgOIgCgNQgCgGgEgEQgEgFgGgCQgFgCgJAAQgHAAgFACQgHACgDAEQgFAEgDAHQgCAGgBAHIBBAAg");
	this.shape_24.setTransform(8.8,76.075);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAMBAIAAgUIASAAIAAg5QAAgPgHgHQgIgIgOAAQgGAAgJAEQgIAEgHAGIAABJIASAAIAAAUIg7AAIAAgUIASAAIAAhUIgSAAIAAgVIAoAAIAAAPIAJgHIAKgGIAKgDIALgBQAKAAAIACQAIADAGAGQAFAGAEAJQADAJAAAMIAAA8IARAAIAAAUg");
	this.shape_25.setTransform(91.075,47.75);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgfBAQgIgDgFgFQgGgFgDgHQgEgHAAgIQABgIACgGQACgGAEgFQAEgEAFgCIALgFIANgDIALgBIAOABIALACIAAgLQAAgGgCgGQgCgEgEgEQgDgDgFgBQgFgCgFAAIgLABIgKACIgIACIgHAEIgIgPIAKgGIAMgEIAMgDIAMgCQAKAAAJAEQAJACAFAGQAHAFADAIQADAJAAAMIAAA+IAOAAIAAAVIgkAAIAAgMQgIAHgJAFQgHADgLAAQgJAAgIgCgAgQAGQgGACgEADQgEADgCAEQgCAEAAAGQAAAEACAFQABADADACIAIAFIALAAIAJAAIAHgDIAIgFIAGgFIAAgdIgZAAIgMABg");
	this.shape_26.setTransform(75.7,47.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgeBcQgLgFgIgIQgIgJgEgNQgFgMAAgQQAAgPAEgMQAFgLAIgIQAIgIALgGQAMgEAOAAQAIAAAHACQAIACAHAFIAAgxIgRAAIAAgVIAnAAIAACpIATAAIAAAUIgpAAIAAgKQgGAGgIAEQgIAEgKAAQgNAAgLgFgAgTgMQgHADgFAFQgFAGgDAIQgDAIAAALQAAALACAJQADAKAGAFQAFAGAHAEQAIACAIAAQAJAAAHgCQAHgEAGgGIAAhFQgGgGgIgCQgIgCgIAAQgIAAgHADg");
	this.shape_27.setTransform(56.025,44.85);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgdBfIAAgVIASAAIAAiTIgSAAIAAgVIAoAAIAACoIATAAIAAAVg");
	this.shape_28.setTransform(44.225,44.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgdBdIAAgUIASAAIAAhUIgSAAIAAgVIAoAAIAABpIATAAIAAAUgAgFg9IgFgFIgEgEIgBgHIABgFIAEgGIAFgDIAFgCIAGACIAFADIAEAGIABAFIgBAHIgEAEIgFAFIgGABg");
	this.shape_29.setTransform(36.225,44.85);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAMBfIAAgVIARAAIAAg6QAAgPgHgFQgHgIgOAAQgHAAgIADQgIAEgHAFIAABKIASAAIAAAVIg8AAIAAgVIATAAIAAiTIgRAAIAAgVIAoAAIAABNIAAAAIAIgGIAKgFIAKgDIAKgCQAKAAAIADQAIADAGAGQAGAGADAIQADAJAAAMIAAA8IATAAIAAAVg");
	this.shape_30.setTransform(24.025,44.7);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgUA+QgLgFgIgJQgIgJgFgMQgFgMAAgPQAAgNAFgNQAFgMAIgJQAJgJALgFQALgFAMAAQALAAALAEQALAEAIAJIANAAIAAAVIgXAAQgFgJgIgFQgIgEgKAAQgHAAgHADQgHAEgFAFQgGAHgDAIQgDAKAAAJQAAAKADAJQADAIAGAHQAFAGAHADQAHAEAHgBQALAAAJgFQAJgGAFgLIASAJQgDAIgGAGQgFAHgHAEQgGAEgJACQgIADgJAAQgMAAgLgFg");
	this.shape_31.setTransform(8.875,47.85);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgsBAIAAgVIARAAIABhUIgSAAIAAgVIAoAAIAAASIAEgHIAGgGIAHgEQAFgCAEAAIANAAIALABIAAAbIgYAAIAAgIIgHACQgFABgDADQgEADgDAFQgCAFgBAHIAAA8IAVAAIAAAVg");
	this.shape_32.setTransform(121,19.625);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgZA+QgIgDgFgGQgGgGgDgJQgDgIAAgNIAAg7IgRAAIAAgVIApAAIAABOQAAAOAHAHQAGAIANAAQAGAAAJgDQAIgCAHgFIAAhMIgRAAIAAgVIApAAIAABoIAOAAIAAAVIglAAIAAgLQgIAGgKAEQgLADgKAAQgKAAgHgCg");
	this.shape_33.setTransform(106.325,19.775);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgZA+QgLgFgJgJQgIgIgEgNQgFgMAAgPQAAgOAFgNQAEgMAJgJQAIgJAMgFQALgEANAAQAOAAAMAEQAMAGAIAIQAIAJAFAMQAEANAAAOQAAAOgEAMQgFANgIAJQgIAJgMAFQgMAFgOAAQgNAAgMgFgAgOgsQgHAEgFAFQgGAGgDAJQgDAKAAAKQAAALADAJQADAIAGAGQAFAHAHADQAHAEAHAAQAJAAAHgEQAHgDAGgHQAFgGADgIQADgJAAgLQAAgKgDgKQgDgJgFgGQgGgFgHgEQgHgDgJAAQgHAAgHADg");
	this.shape_34.setTransform(91.225,19.7);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgnBcIAAgVIAQAAIANgjIgqhqIgKAAIAAgVIAwAAIAAAVIgQAAIAeBPIAehPIgPAAIAAgVIAwAAIAAAVIgNAAIg3CNIAQAAIAAAVg");
	this.shape_35.setTransform(76.225,22.55);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AArBfIgzg5IgRAAIAAAkIALAAIAAAVIg2AAIAAgVIAVAAIAAiTIgWAAIAAgVIAtAAIAAAVIgBAAIAABdIAXAAIAcgdIgHAAIAAgWIAwAAIAAAWIgQAAIgmAmIApAtIAQAAIAAAVg");
	this.shape_36.setTransform(56.5,16.5);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgZA+QgLgFgJgJQgIgIgEgNQgFgMAAgPQAAgOAFgNQAEgMAJgJQAIgJAMgFQALgEANAAQAOAAAMAEQAMAGAIAIQAIAJAFAMQAEANAAAOQAAAOgEAMQgFANgIAJQgIAJgMAFQgMAFgOAAQgNAAgMgFgAgOgsQgHAEgFAFQgGAGgDAJQgDAKAAAKQAAALADAJQADAIAGAGQAFAHAHADQAHAEAHAAQAJAAAHgEQAHgDAGgHQAFgGADgIQADgJAAgLQAAgKgDgKQgDgJgFgGQgGgFgHgEQgHgDgJAAQgHAAgHADg");
	this.shape_37.setTransform(40.825,19.7);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgZA+QgLgFgJgJQgIgIgEgNQgFgMAAgPQAAgOAFgNQAEgMAJgJQAIgJAMgFQALgEANAAQAOAAAMAEQAMAGAIAIQAIAJAFAMQAEANAAAOQAAAOgEAMQgFANgIAJQgIAJgMAFQgMAFgOAAQgNAAgMgFgAgOgsQgHAEgFAFQgGAGgDAJQgDAKAAAKQAAALADAJQADAIAGAGQAFAHAHADQAHAEAHAAQAJAAAHgEQAHgDAGgHQAFgGADgIQADgJAAgLQAAgKgDgKQgDgJgFgGQgGgFgHgEQgHgDgJAAQgHAAgHADg");
	this.shape_38.setTransform(25.875,19.7);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AhEBdIAAgVIARAAIAAiOIgRAAIAAgWIBSABQALAAAKAEQAKAEAHAHQAIAIAEAKQAEAJAAAMQAAAMgHAJQgGAKgMAGIALAGIAIAKQADAFACAFQACAGAAAGQAAALgEAKQgEAKgIAIQgHAHgKAEQgKAFgLAAgAgbBIIAqAAQAGAAAFgDQAFgDAEgFQAEgFACgFQACgGAAgHQAAgFgCgFQgCgFgEgEQgEgEgFgCQgFgDgGAAIgqAAgAgbgKIApAAQAGAAAFgCQAFgCAEgEQAEgEACgFQACgFAAgGQAAgGgCgGQgCgGgEgEQgEgFgFgCQgFgDgGAAIgpAAg");
	this.shape_39.setTransform(10.675,16.725);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("ArUCqIAAlTIWpAAIAAFTg");
	this.shape_40.setTransform(74.5,117.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(0,0,147,134.1), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEANIgFgDIgDgFIgBgFIABgFIADgEIAFgDIAEgBIAGABIAEADIADAEIABAFIgBAFIgDAFIgEADIgGABg");
	this.shape.setTransform(172.475,71.075);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgnA4IAAgTIAPAAIAAhJIgPAAIAAgSIAkAAIAAAPIADgHIAFgFIAHgDIAIgBIAKAAIAKAAIAAAYIgUAAIAAgGIgIABQgDABgEADQgDACgCAFQgCAEgBAGIAAA0IASAAIAAATg");
	this.shape_1.setTransform(164.825,66.75);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgbA4QgHgDgFgEQgFgFgDgFQgDgGAAgHQAAgHACgGQADgFAEgEQACgEAGgCIAJgEIAKgCIAKgBIANABIAKABIAAgJQAAgHgDgEQgBgEgDgDQgEgDgEgBQgEgBgFgBIgJABIgJACIgHADIgGACIgGgNIAJgFIAKgEIAKgDIAKgBQAJABAIACQAHACAGAFQAGAFADAIQADAHAAALIgBA2IAMAAIAAATIggAAIAAgLQgGAGgIAEQgGAEgLgBQgHABgHgDgAgOAGIgJAEQgDACgCAEQgCAEAAAEQAAAFABADIAFAGIAHADIAJABIAIgBIAGgCIAHgEIAFgFIABgaIgXAAQgGABgEABg");
	this.shape_2.setTransform(153.55,66.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgRA3QgLgEgGgHQgIgIgDgLQgEgLAAgOQAAgMADgKQADgKAHgJQAHgHAKgFQAJgEAMgBQANABAIADQAJAEAFAHQAGAGACAHQADAJABAIIAAAIIABAHIhQAAIACAJIACAIQADALAJAFQAJAFAKAAQAJAAAIgCQAIgDAJgFIAIAOQgLAIgLADQgLAEgMgBQgKABgJgEgAAcgMIgBgMQgCgFgEgEQgCgEgGgCQgEgCgIAAQgGAAgFACQgGACgDAEQgEAEgCAFIgDAMIA4AAg");
	this.shape_3.setTransform(141.15,66.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgiBRIAAgTIANAAIAMgeIglhdIgJAAIAAgTIAqAAIAAATIgNAAIAaBFIAahFIgNAAIAAgTIArAAIAAATIgMAAIgwB7IAOAAIAAATg");
	this.shape_4.setTransform(128.475,69.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZBUIAAgTIAQAAIAAiBIgQAAIAAgTIAjAAIAACUIAQAAIAAATg");
	this.shape_5.setTransform(114.225,64);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgVA3QgLgFgHgIQgHgHgEgLQgEgLgBgNQABgNAEgKQAEgLAHgIQAIgIAKgEQAKgEALAAQANAAAKAEQAKAEAIAIQAHAHAEALQAEAMAAAMQAAANgEAKQgEAMgHAHQgIAIgKAFQgKAEgNAAQgLAAgKgEgAgMgmQgGACgFAGQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAFQAFAFAGAEQAGACAGAAQAIAAAGgCQAHgDAEgGQAFgFADgHQACgJAAgJQAAgJgCgIQgDgIgFgFQgEgGgHgCQgGgDgIAAQgGAAgGADg");
	this.shape_6.setTransform(103.925,66.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgVA3QgLgFgHgIQgHgHgEgLQgEgLgBgNQABgNAEgKQAEgLAHgIQAIgIAKgEQAKgEALAAQANAAAKAEQAKAEAIAIQAHAHAEALQAEAMAAAMQAAANgEAKQgEAMgHAHQgIAIgKAFQgKAEgNAAQgLAAgKgEgAgMgmQgGACgFAGQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAFQAFAFAGAEQAGACAGAAQAIAAAGgCQAHgDAEgGQAFgFADgHQACgJAAgJQAAgJgCgIQgDgIgFgFQgEgGgHgCQgGgDgIAAQgGAAgGADg");
	this.shape_7.setTransform(90.775,66.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAKBUIAAgTIAQAAIAAgzQAAgNgHgFQgGgHgMAAQgGAAgHAEQgHADgHAEIAABBIAQAAIAAATIg1AAIAAgTIARAAIAAiBIgPAAIAAgTIAjAAIAABFIABAAIAHgGIAIgEIAJgEIAJgBQAJAAAHADQAHACAFAFQAFAFADAIQACAHAAALIAAA1IARAAIAAATg");
	this.shape_8.setTransform(77.2,64);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgSA3QgKgFgHgHQgHgJgEgKQgEgLAAgNQAAgMAEgKQAFgLAHgIQAHgIAKgFQAKgEAKAAQAKAAAKAEQAJADAHAIIAMAAIAAASIgVAAQgEgHgHgFQgHgDgJAAQgGAAgGADQgGADgFAFQgFAGgCAHQgDAHAAAJQAAAJADAIQACAIAFAFQAFAFAGADQAGADAGAAQAKAAAIgFQAHgFAFgKIAQAIQgDAHgEAGQgFAFgGAEQgGAEgHACQgHACgIAAQgLAAgKgEg");
	this.shape_9.setTransform(63.875,66.75);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgUA3QgIgFgEgGIgLAAIAAgTIAWAAQAAAFACADQACADAEADIAHACIAHABIAIgBIAHgCQADgCACgEQACgDAAgDQgBgFgDgEQgDgDgJgEIgUgIQgNgEgGgGQgHgHAAgLQAAgIADgGQADgFAEgFQAFgEAHgDQAIgCAJAAQALAAAIADQAIADAGAJIALAAIAAASIgWAAQAAgFgCgCQgCgEgDgCIgIgDIgHgBIgIABIgGADIgEAFIgCAGQABAFADAEQADADAJACIATAIQAPAFAFAGQAHAJAAALQAAAHgDAGQgDAGgFAEQgFAFgJACQgHADgKAAQgLAAgJgEg");
	this.shape_10.setTransform(52.45,66.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgUA3QgHgFgFgGIgLAAIAAgTIAWAAQAAAFACADQACADADADIAIACIAHABIAIgBIAHgCQADgCACgEQABgDAAgDQAAgFgDgEQgDgDgJgEIgUgIQgNgEgGgGQgHgHAAgLQAAgIADgGQACgFAFgFQAGgEAHgDQAHgCAJAAQALAAAIADQAIADAGAJIALAAIAAASIgWAAQAAgFgCgCQgCgEgEgCIgHgDIgHgBIgHABIgHADIgEAFIgCAGQAAAFAEAEQADADAJACIATAIQAOAFAHAGQAGAJAAALQAAAHgDAGQgDAGgFAEQgGAFgHACQgIADgJAAQgMAAgJgEg");
	this.shape_11.setTransform(37,66.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgaBSIAAgSIARAAIAAhKIgRAAIAAgSIAkAAIAABcIARAAIAAASgAgFg2IgEgDIgDgFIgCgFIACgGIADgEIAEgDIAFgBIAFABIAFADIACAEIABAGIgBAFIgCAFIgFADIgFABg");
	this.shape_12.setTransform(28.3,64.125);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AALBUIAAgTIAPAAIAAgzQAAgNgGgFQgHgHgMAAQgGAAgHAEQgIADgFAEIAABBIAPAAIAAATIg1AAIAAgTIARAAIAAiBIgPAAIAAgTIAkAAIAABFIAAAAIAHgGIAIgEIAJgEIAJgBQAJAAAHADQAHACAFAFQAFAFADAIQADAHAAALIAAA1IARAAIAAATg");
	this.shape_13.setTransform(17.55,64);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBJQgFgCgEgEQgDgEgDgHQgBgHAAgLIAAg8IgSAAIAAgQIASAAIAAgbIATgJIAAAkIAaAAIAAAQIgaAAIgBA/QAAAHACAEQABAEAEACQADABAFAAIAHAAIAIgDIAEANIgKAEQgGACgIAAQgHAAgFgCg");
	this.shape_14.setTransform(6.1,65.125);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgTA2QgJgDgEgIIgLAAIAAgSIAWAAQAAAEACAEQACAEADACIAIACIAHABIAIgBIAHgCQADgCABgEQACgDAAgDQABgFgEgEQgDgEgJgDIgUgHQgNgFgHgHQgGgGAAgMQAAgHADgGQACgFAGgFQAEgEAIgDQAHgCAJAAQALAAAIADQAIAEAHAHIAKAAIAAATIgWAAQAAgEgCgDQgCgEgEgCIgHgCIgHgBIgHABIgHACIgEAFIgBAFQAAAGADADQAEADAHAEIAVAHQANAFAHAGQAGAIAAALQAAAIgDAGQgDAHgFAEQgGAEgHADQgIACgJAAQgNAAgHgFg");
	this.shape_15.setTransform(115.95,42.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgUA2QgHgDgFgIIgLAAIAAgSIAWAAQAAAEACAEQACAEAEACIAHACIAHABIAIgBIAHgCQADgCACgEQABgDAAgDQAAgFgDgEQgEgEgIgDIgUgHQgNgFgGgHQgHgGAAgMQAAgHADgGQADgFAEgFQAGgEAHgDQAHgCAJAAQALAAAIADQAIAEAGAHIALAAIAAATIgWAAQAAgEgCgDQgCgEgEgCIgHgCIgHgBIgHABIgHACIgEAFIgCAFQABAGADADQADADAJAEIATAHQAOAFAGAGQAHAIAAALQAAAIgDAGQgDAHgFAEQgFAEgJADQgHACgJAAQgMAAgJgFg");
	this.shape_16.setTransform(105.3,42.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgSA3QgKgEgHgIQgGgGgEgMQgEgLAAgOQAAgMADgKQADgKAHgIQAHgJAJgEQALgEAMAAQAMAAAJADQAHAEAGAGQAFAGADAIQADAJABAIIABAJIAAAHIhPAAIAAAIIACAHQAFALAIAGQAJAFAKAAQAJAAAIgCQAIgCAJgGIAIAOQgLAHgLAEQgLADgMABQgKgBgKgDgAAcgMIgCgLQgBgGgDgEQgEgDgEgDQgGgCgHAAQgGAAgFACQgGACgDAEQgEAEgCAFIgEAMIA5AAg");
	this.shape_17.setTransform(93.4,42.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgSA3QgKgFgHgHQgHgIgEgLQgEgLAAgNQAAgMAEgLQAFgLAHgHQAHgIAKgEQAKgFAKAAQAKAAAKAEQAJADAHAIIAMAAIAAASIgVAAQgEgIgHgDQgHgEgJAAQgGAAgGADQgGADgFAFQgFAFgCAIQgDAIAAAIQAAAKADAHQACAHAFAGQAFAFAGADQAGADAGAAQAKAAAIgFQAHgFAFgKIAQAIQgDAHgEAFQgFAGgGAEQgGAEgHACQgHACgIAAQgLAAgKgEg");
	this.shape_18.setTransform(81.475,42.15);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgSA3QgKgFgHgHQgHgIgEgLQgEgLAAgNQAAgMAEgLQAFgLAHgHQAHgIAKgEQAKgFAKAAQAKAAAKAEQAJADAHAIIAMAAIAAASIgVAAQgEgIgHgDQgHgEgJAAQgGAAgGADQgGADgFAFQgFAFgCAIQgDAIAAAIQAAAKADAHQACAHAFAGQAFAFAGADQAGADAGAAQAKAAAIgFQAHgFAFgKIAQAIQgDAHgEAFQgFAGgGAEQgGAEgHACQgHACgIAAQgLAAgKgEg");
	this.shape_19.setTransform(69.475,42.15);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgWA2QgHgCgFgFQgFgFgCgIQgDgIAAgLIAAg0IgPAAIAAgTIAkAAIAABFQAAANAGAGQAGAHALAAQAGAAAHgDQAHgCAGgEIAAhDIgOAAIAAgTIAjAAIAABcIANAAIAAATIghAAIAAgLQgHAGgJADQgJAEgJAAQgIAAgHgDg");
	this.shape_20.setTransform(55.525,42.275);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgUA2QgHgDgFgIIgLAAIAAgSIAWAAQAAAEACAEQACAEAEACIAHACIAHABIAIgBIAHgCQADgCACgEQACgDAAgDQgBgFgDgEQgEgEgIgDIgUgHQgNgFgGgHQgHgGAAgMQAAgHADgGQADgFAEgFQAFgEAHgDQAIgCAJAAQALAAAIADQAIAEAGAHIALAAIAAATIgWAAQAAgEgCgDQgCgEgDgCIgIgCIgHgBIgIABIgGACIgEAFIgCAFQABAGADADQADADAJAEIATAHQAPAFAFAGQAHAIAAALQAAAIgDAGQgDAHgFAEQgFAEgJADQgHACgKAAQgMAAgIgFg");
	this.shape_21.setTransform(43.55,42.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgnA4IAAgTIAPAAIAAhJIgPAAIAAgSIAkAAIAAAPIADgGIAFgGIAHgDIAIgBIAKAAIAKAAIAAAYIgUAAIAAgGIgIABQgDABgEADQgDADgCAEQgCAEgBAGIAAA0IASAAIAAATg");
	this.shape_22.setTransform(28.225,42.15);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgVA2QgLgEgHgIQgHgHgEgLQgEgLgBgNQABgMAEgLQAEgLAHgIQAIgHAKgFQAKgEALAAQANAAAKAEQAKAFAIAHQAHAIAEALQAEAKAAANQAAAMgEALQgEAMgHAHQgIAIgKAEQgKAFgNAAQgLAAgKgFgAgMgmQgGADgFAFQgFAFgDAIQgCAIAAAJQAAAKACAHQADAIAFAGQAFAEAGAEQAGACAGAAQAIAAAGgCQAHgDAEgFQAFgGADgIQACgHAAgKQAAgJgCgIQgDgIgFgFQgEgFgHgDQgGgDgIAAQgGAAgGADg");
	this.shape_23.setTransform(16.475,42.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgnBUIAAgTIARAAIAAhLIgTAAIAAgRIATAAIAAgRQAAgKACgHQADgIAFgEQAEgFAHgDQAGgCAIAAIAKABIAIABIAHACIAEADIgGAOIgJgDIgMgBQgJgBgEAGQgFAFAAALIAAASIAaAAIAAARIgaAAIAABLIARAAIAAATg");
	this.shape_24.setTransform(7.1,39.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("Ag6BSIAAgSIAQAAIAAh8IgQAAIAAgTIAjAAIAAAKQAIgGAIgDQAHgDAJAAQALAAAJAEQAJAEAHAHQAHAIADAKQAEAKAAANQAAANgEAMQgEAKgHAIQgIAHgKAFQgKAEgMAAQgHAAgHgBIgNgFIAAAkIASAAIAAASgAgKg8QgHADgGAFIAAA7QAEAEAGADQAIADAIAAQAHAAAHgDQAGgDAFgFQAFgFADgHQACgIAAgKQAAgKgCgHQgDgHgFgFQgEgFgHgDQgGgDgHAAQgHAAgHAEg");
	this.shape_25.setTransform(123.6,19.975);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgWA2QgHgCgFgFQgFgFgCgIQgDgIAAgLIAAg0IgPAAIAAgTIAkAAIAABFQAAANAGAGQAGAHALAAQAGAAAHgDQAHgCAGgEIAAhDIgOAAIAAgTIAjAAIAABcIANAAIAAATIghAAIAAgLQgHAGgJADQgJAEgJAAQgIAAgHgDg");
	this.shape_26.setTransform(109.175,17.675);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAwA5IAAgTIAPAAIAAgyQAAgMgGgHQgHgHgMAAQgHAAgIAEQgHADgFAGIAAA/IAPAAIAAATIgzAAIAAgTIAPAAIAAgyQAAgMgGgHQgGgHgNAAQgHAAgGAEQgIADgGAFIAABAIAPAAIAAATIg0AAIAAgTIAQAAIAAhJIgQAAIAAgTIAkAAIAAANIAAAAIAIgFIAIgFIAKgDIAJgCQAMAAAKAFQAHAEAFAKIAIgHIAKgGIAKgEIALgCQAJAAAHADQAHACAGAFQAEAFADAIQADAIAAALIAAA0IAPAAIAAATg");
	this.shape_27.setTransform(86.75,17.475);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgRA3QgLgEgGgHQgIgIgDgLQgEgLAAgOQAAgLADgLQADgLAHgIQAHgHAKgFQAJgFAMABQANAAAIADQAJAEAFAGQAGAHACAIQADAHABAJIAAAIIABAHIhQAAIACAJIACAHQADAMAJAFQAJAFAKAAQAJAAAIgCQAIgCAJgGIAIAOQgLAHgLAEQgLAEgMAAQgKAAgJgEgAAcgMIgBgMQgCgFgEgEQgCgDgGgDQgEgCgIAAQgGAAgFACQgGACgDAEQgEADgCAGIgDAMIA4AAg");
	this.shape_28.setTransform(69.15,17.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAKBTIAAgSIAQAAIAAgzQAAgNgHgFQgGgHgMAAQgGAAgHADQgHAEgHAEIAABBIAQAAIAAASIg1AAIAAgSIARAAIAAiBIgPAAIAAgSIAjAAIAABDIABAAIAHgFIAIgFIAJgDIAJgBQAJAAAHADQAHACAFAFQAFAFADAIQACAHAAAKIAAA2IARAAIAAASg");
	this.shape_29.setTransform(56.05,14.8);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAABJQgGgCgDgEQgEgEgDgHQgBgHAAgLIAAg8IgSAAIAAgQIASAAIAAgbIATgJIAAAkIAaAAIAAAQIgaAAIgBA/QABAHABAEQABAEAEACQADABAFAAIAHAAIAIgDIAEANIgKAEQgGACgIAAQgHAAgEgCg");
	this.shape_30.setTransform(44.6,15.925);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgBBJQgFgCgDgEQgFgEgCgHQgBgHAAgLIAAg8IgSAAIAAgQIASAAIAAgbIATgJIAAAkIAaAAIAAAQIgaAAIgBA/QAAAHACAEQABAEAEACQADABAFAAIAHAAIAIgDIAEANIgKAEQgGACgIAAQgHAAgFgCg");
	this.shape_31.setTransform(31.65,15.925);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgSA3QgKgEgHgHQgGgIgEgLQgEgLAAgOQAAgLADgLQADgLAHgIQAHgHAJgFQALgFAMABQAMAAAJADQAHAEAGAGQAFAHADAIQADAHABAJIABAIIAAAHIhPAAIABAJIABAHQAFAMAIAFQAJAFAKAAQAJAAAIgCQAIgCAJgGIAIAOQgLAHgLAEQgLAEgMAAQgKAAgKgEgAAcgMIgCgMQgBgFgDgEQgEgDgEgDQgGgCgHAAQgGAAgFACQgGACgDAEQgEADgCAGIgDAMIA4AAg");
	this.shape_32.setTransform(20.95,17.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgTBSQgJgDgGgFQgGgFgDgGQgEgGgCgHIgIAAIAAgSIAbAAQAAAMACAFQADAFAEADQAFADAGACQAGACAHAAQAHAAAGgCQAGgCAEgDQAEgDADgFQACgFAAgGQAAgGgDgFQgDgEgEgEIgJgFIgKgDIgXgHQgIgCgGgDQgGgEgFgFQgFgFgCgHQgCgHAAgKQAAgJADgIQAEgIAHgGQAHgGAKgEQALgDAMAAQAIAAAIACQAHACAGADQAGAEAFAFQAEAFADAHIAIAAIAAASIgaAAQAAgJgDgFQgEgFgEgCIgJgEIgKgBQgHAAgGABQgGACgEADQgEAEgCAEQgCAEAAAFQAAAHACAFIAGAHIAJAEIAJADIAVAHQAJADAIAEQAHADAFAFQAFAGADAHQADAHAAAJQAAAKgEAJQgFAIgHAHQgHAGgLAEQgKADgMAAQgMAAgJgCg");
	this.shape_33.setTransform(8.675,15.075);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(0,0,177.1,79.8), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bb_boy();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,0,300,250), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgEAMIgEgDIgDgEIgBgFIABgEIADgEIAEgDIAEgBIAFABIAEADIADAEIABAEIgBAFIgDAEIgEADIgFABg");
	this.shape.setTransform(180.875,45.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAKAzIAAgRIAOAAIAAgtQAAgLgGgGQgGgGgLAAQgFAAgHADQgGADgGAFIAAA5IAOAAIAAARIgvAAIAAgRIAOAAIAAhCIgOAAIAAgQIAgAAIAAALIAHgFIAIgEIAIgDIAIgBQAJAAAGACQAHACAEAFQAFAEACAIQADAGAAALIAAAuIAOAAIAAARg");
	this.shape_1.setTransform(172.025,41.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUAyQgJgEgHgHQgGgHgEgKQgEgKAAgMQAAgLAEgKQAEgKAHgHQAGgHAKgEQAJgEAKAAQALAAAKAEQAJAEAGAHQAHAHAEAKQAEAJAAAMQAAALgEALQgEAKgHAHQgGAHgJAEQgKADgLAAQgKAAgKgDgAgLgjQgGADgEAEQgFAGgCAHQgDAGAAAJQAAAJADAGQACAIAFAEQAEAGAGACQAFADAGAAQAHAAAGgDQAFgCAFgGQAEgEACgIQADgGAAgJQAAgJgDgGQgCgHgEgGQgFgEgFgDQgGgCgHAAQgGAAgFACg");
	this.shape_2.setTransform(159.325,41.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgXBLIAAgRIAOAAIAAhDIgOAAIAAgQIAgAAIAABTIAPAAIAAARgAgEgxIgEgDIgDgEIgBgFIABgFIADgEIAEgDIAEgBIAFABIAEADIADAEIABAFIgBAFIgDAEIgEADIgFABg");
	this.shape_3.setTransform(150.3,38.875);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgRAyQgIgEgEgGIgKAAIAAgRIAUAAQAAAEACADIAFAFIAGADIAHABIAIgBIAGgDIAEgEQACgDgBgEQAAgEgCgEQgEgDgHgCIgSgIQgMgDgGgGQgGgHAAgKQAAgHACgFQADgGAEgDQAFgEAGgCQAHgCAIgBQAKABAIADQAHACAFAIIAKAAIAAARIgUAAQAAgFgCgCQgBgDgEgCIgGgDIgHgBIgHABIgGADQgCABgBADQgCACABADQAAAFACADQADADAIACIATAIQAMADAGAHQAFAHAAAKQABAHgDAFQgDAGgFAEQgFAEgGACQgIACgIAAQgLAAgHgDg");
	this.shape_4.setTransform(142.15,41.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXBLIAAgRIAOAAIAAhDIgOAAIAAgQIAgAAIAABTIAPAAIAAARgAgEgxIgEgDIgCgEIgCgFIACgFIACgEIAEgDIAEgBIAFABIAEADIACAEIACAFIgCAFIgCAEIgEADIgFABg");
	this.shape_5.setTransform(134.25,38.875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgIAzIghhVIgIAAIAAgQIAjAAIAAAQIgKAAIAYBFIAZhFIgHAAIAAgQIAgAAIAAAQIgIAAIghBVg");
	this.shape_6.setTransform(125.475,41.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAKAzIAAgRIAOAAIAAgtQAAgLgGgGQgGgGgLAAQgFAAgHADQgGADgGAFIAAA5IAOAAIAAARIgvAAIAAgRIAOAAIAAhCIgOAAIAAgQIAgAAIAAALIAHgFIAIgEIAIgDIAIgBQAJAAAGACQAHACAEAFQAFAEACAIQADAGAAALIAAAuIAOAAIAAARg");
	this.shape_7.setTransform(109.275,41.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgUAyQgJgEgHgHQgGgHgEgKQgEgKAAgMQAAgLAEgKQAEgKAHgHQAGgHAKgEQAJgEAKAAQALAAAKAEQAJAEAGAHQAHAHAEAKQAEAJAAAMQAAALgEALQgEAKgHAHQgGAHgJAEQgKADgLAAQgKAAgKgDgAgLgjQgGADgEAEQgFAGgCAHQgDAGAAAJQAAAJADAGQACAIAFAEQAEAGAGACQAFADAGAAQAHAAAGgDQAFgCAFgGQAEgEACgIQADgGAAgJQAAgJgDgGQgCgHgEgGQgFgEgFgDQgGgCgHAAQgGAAgFACg");
	this.shape_8.setTransform(96.575,41.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgXBJQgJgDgHgHQgGgGgEgLQgEgJABgNQgBgMAEgKQADgJAHgGQAGgHAKgEQAJgDAKAAQAHAAAGABQAGABAGAFIAAgnIgOAAIAAgRIAgAAIAACGIAPAAIAAARIghAAIAAgIQgFAEgGADQgHADgHAAQgKAAgJgEgAgOgJQgHACgDAFQgFAEgCAGQgDAHABAIQAAAJABAIQADAHAEAFQAFAFAGACQAFACAHABQAHgBAGgCQAFgCAFgFIAAg4QgFgEgGgCQgHgBgGAAQgGgBgFADg");
	this.shape_9.setTransform(80.2,38.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgQAyQgJgDgGgHQgGgHgEgKQgEgKAAgNQABgKADgKQACgJAHgIQAGgHAIgEQAJgFALAAQALAAAJAEQAHAEAFAGQAEAFADAHQACAHABAIIABAIIABAHIhJAAIABAHIACAHQADAJAIAGQAJAEAJAAQAIAAAHgCQAIgCAHgFIAIANQgKAHgKADQgKAEgLgBQgKABgIgEgAAagLIgCgKQgBgFgDgDQgDgEgFgCQgEgCgHAAQgFAAgFACQgFABgEAEIgEAIIgDALIAzAAg");
	this.shape_10.setTransform(67.95,41.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgSAyQgHgEgEgGIgKAAIAAgRIAUAAQAAAEACADIAFAFIAGADIAHABIAIgBIAGgDIAEgEQABgDAAgEQAAgEgDgEQgDgDgHgCIgSgIQgMgDgGgGQgGgHAAgKQAAgHACgFQADgGAEgDQAFgEAGgCQAHgCAIgBQAKABAHADQAIACAFAIIAKAAIAAARIgUAAQAAgFgCgCQgBgDgDgCIgHgDIgHgBIgHABIgFADQgDABgBADQgBACgBADQAAAFADADQAEADAHACIATAIQAMADAGAHQAFAHAAAKQAAAHgCAFQgDAGgFAEQgFAEgGACQgIACgIAAQgLAAgIgDg");
	this.shape_11.setTransform(57.65,41.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgZAzQgGgDgEgEQgFgEgCgFQgDgFAAgHQAAgGACgFQACgFADgEQADgDAFgCIAIgEIAKgCIAJgBIALABIAJABIAAgIQAAgGgCgDQgBgEgDgDQgDgDgEgBQgEgBgEAAIgJABIgHABIgHADIgGACIgFgMIAHgFIAKgDIAJgCIAKgBQAIAAAHACQAHACAFAEQAEAFADAHQADAGAAAKIAAAxIALAAIAAARIgeAAIAAgJQgFAFgHAEQgGADgJAAQgIAAgGgCgAgNAFQgEABgEADQgDACgCADQgBAEAAAEQAAAEABADIAEAFQADACAEABIAIABIAHgBIAGgCIAGgEIAEgEIABgXIgVAAIgJABg");
	this.shape_12.setTransform(47.225,41.325);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgJBLQgGgDgFgDIAAAGIgSAAIAAiGIgPAAIAAgRIAhAAIAAA7QAGgFAIgCQAHgDAHAAQALAAAIADQAIAEAHAHQAFAHAEAIQADAJAAAMQAAAMgEAKQgDAKgHAHQgGAHgKAEQgJAEgKAAQgHAAgHgCgAgJgIQgGADgFAEIAAA2QADADAGADQAGACAJAAQAFAAAHgCQAFgDAEgEQAFgFADgHQACgHAAgKQAAgIgCgHQgDgGgEgEQgFgFgFgCQgFgCgHAAQgGAAgHADg");
	this.shape_13.setTransform(35.7,38.825);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgRAyQgIgEgEgGIgKAAIAAgRIAUAAQAAAEACADIAFAFIAGADIAHABIAIgBIAGgDIAEgEQACgDgBgEQAAgEgCgEQgEgDgHgCIgTgIQgLgDgGgGQgGgHAAgKQAAgHACgFQADgGAFgDQAEgEAGgCQAHgCAIgBQAKABAIADQAHACAFAIIAKAAIAAARIgUAAQAAgFgBgCQgCgDgEgCIgGgDIgHgBIgHABIgGADQgCABgBADQgCACABADQAAAFACADQADADAIACIASAIQANADAFAHQAHAHgBAKQABAHgDAFQgDAGgFAEQgFAEgGACQgIACgIAAQgLAAgHgDg");
	this.shape_14.setTransform(20.55,41.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgXBLIAAgRIAOAAIAAhDIgOAAIAAgQIAgAAIAABTIAPAAIAAARgAgEgxIgEgDIgCgEIgCgFIACgFIACgEIAEgDIAEgBIAFABIAEADIACAEIABAFIgBAFIgCAEIgEADIgFABg");
	this.shape_15.setTransform(12.65,38.875);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgLBJIgLgCIgLgEQgFgDgEgEIAJgPIAHAFIAIADIAJADIAJABQAHAAAFgCQAGgBADgEQAEgEACgHQACgGAAgLIAAgBQgFAFgHADQgHACgIABQgKgBgIgDQgJgEgHgGQgGgHgEgKQgDgJAAgNQAAgMADgKQAEgJAGgHQAGgGAKgFQAIgDALAAQAIAAAGABQAFADAHAEIAAgGIASAAIAABgQAAAZgMAMQgMAMgXAAgAgHg3QgHADgDAFQgFAEgCAGQgCAHAAAJQAAAJACAHQACAHAEAEQAEAFAHADQAFACAGAAIAIgBIAHgCIAFgEIAFgDIAAg3QgFgEgHgCQgGgCgIAAQgFAAgFACg");
	this.shape_16.setTransform(184.25,18.25);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAKA0IAAgRIAOAAIAAgtQAAgMgGgGQgGgGgLAAQgFAAgHADQgGADgGAEIAAA7IAOAAIAAARIgvAAIAAgRIAOAAIAAhDIgOAAIAAgRIAgAAIAAAMIAHgFIAIgEIAIgEIAIgBQAJAAAGACQAHADAEAEQAFAFACAHQADAIAAAJIAAAwIAOAAIAAARg");
	this.shape_17.setTransform(172.075,16.05);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgXBLIAAgRIAPAAIAAhDIgPAAIAAgQIAgAAIAABTIAPAAIAAARgAgEgxIgEgDIgCgEIgCgFIACgFIACgEIAEgDIAEgBIAFABIAEADIACAEIABAFIgBAFIgCAEIgEADIgFABg");
	this.shape_18.setTransform(162.3,13.725);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAKA0IAAgRIAOAAIAAgtQAAgMgGgGQgGgGgLAAQgFAAgHADQgGADgGAEIAAA7IAOAAIAAARIgvAAIAAgRIAOAAIAAhDIgOAAIAAgRIAgAAIAAAMIAHgFIAIgEIAIgEIAIgBQAJAAAGACQAHADAEAEQAFAFACAHQADAIAAAJIAAAwIAOAAIAAARg");
	this.shape_19.setTransform(152.375,16.05);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgjAzIAAgRIANAAIABhCIgOAAIAAgRIAgAAIAAAOIADgGIAFgFIAGgDIAHgBIAJAAIAJAAIAAAWIgSAAIAAgGIgHABIgGAEQgDACgCAFQgBADgBAGIAAAvIAQAAIAAARg");
	this.shape_20.setTransform(140.975,16.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgZAzQgGgDgEgEQgFgEgCgFQgDgFAAgHQAAgGACgFQACgFADgEQADgDAFgCIAIgEIAKgCIAJgBIALABIAJABIAAgIQAAgGgCgDQgBgEgDgDQgDgDgEgBQgEgBgEAAIgJABIgHABIgHADIgGACIgFgMIAHgFIAKgDIAJgCIAKgBQAIAAAHACQAHACAFAEQAEAFADAHQADAGAAAKIAAAxIALAAIAAARIgeAAIAAgJQgFAFgHAEQgGADgJAAQgIAAgGgCgAgNAFQgEABgEADQgDACgCADQgBAEAAAEQAAAEABADIAEAFQADACAEABIAIABIAHgBIAGgCIAGgEIAEgEIABgXIgVAAIgJABg");
	this.shape_21.setTransform(130.725,16.175);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgQAyQgJgEgGgGQgHgHgDgKQgEgKABgNQAAgKACgKQAEgKAFgGQAGgIAKgEQAJgEAKAAQAMAAAHADQAIADAFAGQAEAGADAIQADAGABAJIAAAHIABAGIhIAAIAAAIIACAHQAEAKAHAEQAIAGAJgBQAJABAHgCQAHgDAJgFIAHANQgKAGgKAEQgKADgLABQgJgBgJgDgAAagLIgCgLQgBgEgDgDQgDgEgFgCQgFgCgGAAQgGAAgEACQgFACgDADIgGAIIgCALIAzAAg");
	this.shape_22.setTransform(119.45,16.15);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgXBMIAAgRIAPAAIAAh1IgPAAIAAgRIAgAAIAACGIAPAAIAAARg");
	this.shape_23.setTransform(110.8,13.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgRAxQgIgDgEgHIgKAAIAAgQIAUAAQAAAEACADIAFAFIAHACIAGABIAIgBIAGgCIAEgFQABgCAAgDQAAgFgCgDQgEgEgIgDIgSgHQgMgDgFgHQgGgGAAgKQAAgHACgFQADgFAFgEQAEgEAHgDQAGgBAIAAQAKgBAIADQAHAEAFAGIAKAAIAAARIgUAAQAAgDgBgDQgDgEgDgBIgHgDIgGAAIgHAAIgGADQgCACgBACQgBACAAADQAAAFADADQACADAIADIASAGQANAFAFAGQAHAHAAALQgBAGgCAGQgDAFgFAEQgFAEgGADQgIACgIAAQgLAAgHgFg");
	this.shape_24.setTransform(98.3,16.15);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgKAaIAAgyIAVgBIgFAzg");
	this.shape_25.setTransform(91.675,8.25);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgYBKQgIgEgGgGQgHgIgEgJQgDgLAAgNQAAgMADgJQAEgIAGgIQAHgGAIgEQAKgDAKAAQAHAAAGABQAGABAFAEIAAgmIgNAAIAAgRIAgAAIAACGIAPAAIAAARIgiAAIAAgJQgEAFgHADQgGADgIAAQgJAAgKgDgAgPgJQgGACgEAFQgEAEgCAGQgCAHgBAIQAAAJACAHQADAIAEAFQAFAEAFADQAGADAHAAQAHAAAFgDQAGgDAEgEIAAg4QgEgEgHgBQgGgDgFAAQgHAAgGADg");
	this.shape_26.setTransform(84.1,13.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgXBMIAAgRIAPAAIAAh1IgPAAIAAgRIAgAAIAACGIAPAAIAAARg");
	this.shape_27.setTransform(74.65,13.6);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgXBLIAAgRIAPAAIAAhDIgPAAIAAgQIAgAAIAABTIAPAAIAAARgAgEgxIgEgDIgCgEIgCgFIACgFIACgEIAEgDIAEgBIAFABIAEADIACAEIABAFIgBAFIgCAEIgEADIgFABg");
	this.shape_28.setTransform(68.25,13.725);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAKBMIAAgRIANAAIAAguQABgLgHgGQgGgFgKgBQgGABgGADQgHADgFADIAAA7IAOAAIAAARIgwAAIAAgRIAQAAIAAh1IgPAAIAAgRIAhAAIAAA+IABAAIAGgFIAHgEIAIgDIAIgBQAIAAAHACQAGADAEAEQAFAEADAIQADAGgBAKIAAAwIAQAAIAAARg");
	this.shape_29.setTransform(58.5,13.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgQAyQgJgEgGgHQgHgIgDgJQgEgKAAgMQAAgLAEgKQAEgJAGgIQAHgHAJgEQAJgEAJAAQAKAAAIAEQAJADAGAHIAKAAIAAARIgSAAQgEgIgHgDQgGgEgIAAQgGAAgFADQgFADgFAFQgEAEgCAHQgDAHAAAIQAAAIADAHQACAHAEAFQAFAFAFACQAFADAGAAQAJAAAHgFQAHgEAEgJIAPAIQgCAGgFAFIgJAIQgGAEgHACQgGACgHAAQgKAAgJgEg");
	this.shape_30.setTransform(46.35,16.125);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgZAzQgGgDgEgEQgFgEgCgFQgDgFAAgHQAAgGACgFQACgFADgEQADgDAFgCIAIgEIAKgCIAJgBIALABIAJABIAAgIQAAgGgCgDQgBgEgDgDQgDgDgEgBQgEgBgEAAIgJABIgHABIgHADIgGACIgFgMIAHgFIAKgDIAJgCIAKgBQAIAAAHACQAHACAFAEQAEAFADAHQADAGAAAKIAAAxIALAAIAAARIgeAAIAAgJQgFAFgHAEQgGADgJAAQgIAAgGgCgAgNAFQgEABgEADQgDACgCADQgBAEAAAEQAAAEABADIAEAFQADACAEABIAIABIAHgBIAGgCIAGgEIAEgEIABgXIgVAAIgJABg");
	this.shape_31.setTransform(30.875,16.175);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgkBMIAAgRIAPAAIAAhFIgQAAIAAgOIAQAAIAAgQQAAgJADgHQACgGAEgFQAFgDAGgDQAFgCAHAAIAKAAIAHACIAGACIAEACIgGAMIgIgCQgFgCgFABQgIAAgFAEQgEAGAAAJIAAARIAXAAIAAAOIgXAAIAABFIAPAAIAAARg");
	this.shape_32.setTransform(18.675,13.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgUAxQgJgDgHgIQgGgGgEgLQgEgJAAgMQAAgLAEgKQAEgKAHgHQAGgHAKgEQAJgDAKAAQALAAAKADQAJAEAGAHQAHAHAEAKQAEAKAAALQAAAMgEAJQgEALgHAGQgGAIgJADQgKAFgLAAQgKAAgKgFgAgLgjQgGADgEAFQgFAFgCAGQgDAIAAAIQAAAIADAIQACAHAFAEQAEAFAGAEQAFACAGAAQAHAAAGgCQAFgEAFgFQAEgEACgHQADgIAAgIQAAgIgDgIQgCgGgEgFQgFgFgFgDQgGgCgHAAQgGAAgFACg");
	this.shape_33.setTransform(7.975,16.15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(0,0,192.5,53.3), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjGDzIFEnlIA8AAIlEHlgABbDpQgUgJgNgOQgOgOgIgTQgIgSAAgWQAAgVAIgTQAIgSAOgOQAOgPAUgIQAUgJAXAAQAYAAATAJQAUAIAOAPQAOAOAIASQAIATAAAVQAAAWgHASQgIATgOAOQgOAOgUAJQgTAJgZgBQgYABgUgJgABzBYQgKAFgIAHQgHAHgEAKQgFAJAAALQAAALAFAKQAEAJAHAIQAIAIAKAEQAJAEALAAQALAAAKgEQAKgEAHgIQAHgHAEgKQAEgKAAgLQAAgLgEgJQgEgKgHgHQgHgHgKgFQgKgEgLAAQgLAAgJAEgAiygeQgUgIgOgOQgOgPgHgTQgIgSAAgVQAAgVAIgUQAHgTAPgOQAOgOATgIQAUgIAYgBQAXABAUAIQATAIAOAOQAPAOAIATQAHAUAAAVQAAAVgHASQgIATgOAPQgOAOgUAIQgTAJgYgBQgZABgTgJgAibiuQgKADgIAIQgHAGgEAKQgEAKAAAMQAAAKAEALQAEAJAHAIQAIAGAKAFQAJAEAMAAQALAAAJgEQAKgFAHgGQAHgIAFgJQAEgLAAgKQAAgMgEgKQgFgKgHgGQgHgIgKgDQgJgEgLAAQgMAAgJAEg");
	this.shape.setTransform(106.025,39.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhUDhQgigTgVghQgUghgJgsQgJgsAAgyQAAg2AMguQAMgwAUgcQAUgcAfgUQAegUA0AAQAyAAAhAPQAiAQAWAiQAWAgAIAvQAJAuAAA0QAAAzgJAsQgIAsgVAhQgVAhgiATQgjATgyAAQgzAAghgSgAg6itQgVAQgLAWQgKAWgHAmQgGAmAAAlQAAAmAEAjQAEAiAMAZQAMAaAXAPQAVAPAlAAQAkAAAXgPQAVgPAMgaQALgZAGgiQAFgjABgmQgBglgEgiQgEgigMgaQgNgagWgQQgXgQgkAAQgkAAgWAQg");
	this.shape_1.setTransform(60.45,39.725);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag6DpQgcgMgUgTQgVgUgMgaQgMgaAAgdQAAgTAFgSQAGgSAJgQQAKgPANgNQANgMAQgKQgYgRgOgZQgOgaABgfQAAgZAKgXQAKgXASgQQASgRAZgKQAYgKAbAAQAbAAAXAKQAZAKARARQASAQALAXQAKAXAAAZQAAAfgOAaQgOAagYARQAPAJAOAMQANANAJAQQAKAPAFASQAFASAAATQAAAdgMAaQgMAagVAUQgUATgcAMQgbALgfAAQgfAAgcgLgAgkASQgRAGgNANQgNAMgHAQQgIAQAAASQAAATAIAQQAHARANAMQANAMARAHQASAHATAAQATAAARgHQARgHAOgMQAMgMAHgRQAIgQAAgTQAAgSgIgQQgHgQgMgMQgOgNgRgGQgRgIgTAAQgTAAgSAIgAgdi6QgOAGgLAKQgLAKgFAOQgHANABAQQgBAPAHAOQAFANALALQALAKAOAGQAOAGARAAQAQAAAOgGQAOgGALgKQAKgLAHgNQAGgOAAgPQAAgQgGgNQgHgOgKgKQgLgKgOgGQgOgGgQAAQgRAAgOAGg");
	this.shape_2.setTransform(21.6,39.625);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,133.6,81.3), null);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol6();
	this.instance.parent = this;
	this.instance.setTransform(551.4,185.65,1,1,0,0,0,13.2,13.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(125).to({_off:false},0).to({alpha:1},14).wait(145).to({_off:true},1).wait(225));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A7iQiIAAmbIBJAAIAAA0IAEgGIAOgSIAYgTIAHgEIAOgGIAQgFIAWgDIAaABIAjAKIAGADIATALIAXATIATAXIAOAeIAIAXIAFAvIgFAuIgIAYIgKAWIgNATIgVAUIgMAJIggAQIgVAFIgVADIgagBIgYgFIgVgKIgMgIIgQgPIgOgQIAACQgA5OK/IgMADIgFACIgMAFIgLAIIgHAGIgJALIgDADIgKARIgGATIgDAQIAAAXIADAQIAGATIAKARIAJALIAOAMIALAIIARAGIAEABIAEABIAOABIAOgBIAEgBIAEgBIARgGIAIgFIAOgMIAMgOIAHgMIAJgYIACgQIAAgXIgCgRIgJgXIgHgNIgPgRIgLgIIgMgGIgRgGIgOgBgEAl6AQfIgegEIgrgQIgCgCIonk8IIqklIACgBIAngMIAkgFIAsAAIAmAHIAZAJIIQEpIhhA4Imkj9IgCgBIgVgMIgngNIgegEIgeABIgSACIhCAYIlnDGIF9DhIABABIAKAFIAmAMIAfABIAIgBIAjgJIAQgHID9iWIj9iTIgBgBIgJgFIgQgFIgSgFIgUgBIgQACIgxAQIgBABIjUB7Ihng1IEtifIA4gUIAOgDIAHgBIAhACIAWAEIAHADIAGACIASAIIGdDsImiDyIgBACIgeALIgNAFIgfAEgAWZPHIgRgDIgjgLIgZgLIgfgUIAhgyIATANIAaAOIAnAKIANABIAWgBIAFgBIAMgEIAHgEIAFgFIADgGIACgIIAAgIIgBgHIgCgDIgBgBIgFgFIgRgLIhjgiIgLgGIgEgEIgNgLIgIgKIgIgRIgCgKIgBgWIABgLIAEgOIACgFIABgFIALgQIADgEIADgEIAQgNIASgJIAFgCIAagHIAuAAIAmAIIAeAMIAbAPIgcAyIgjgRIgSgHIgcgGIgQgBIgOADIgLAEIgFAFIgFAFIgDAHIgBAGIAAAJIABACIAAABIABACIABADIABABIACACIADADIAEADIAUAKIBCAWIAhARIALAIIAKAJIAKAOIAFAMIABAFIACAFIABAPIgBASIgEAQIgEAJIgIAOIgDAEIgLALIgVAOIgPAGIgWAFIgYADgASlPHIgNgDIgQgHIgHgEIgGgGIgIgJIgJgPIgGgTIgCgRIAAizIgqAAIAAg9IAqAAIAAhZIBIAAIAABZIBWAAIAAA9IhWAAIAAChIABAIIAFALIACACIAFAGIADACIADABIAHACIANABIAdgDIAPgFIAAA6IgJAGIgTAHIgaAEgAOPPJIgjgFIgSgEIgZgKIghgRIgPgLIAigyIAfAVIANAGIAnAKIAZABIAKgBIAFgBIAQgGIAIgHIACgDIACgDIABgEIAAgEIAAgKIgBgFIgCgDIgBgBIgEgFIgIgFIgQgIIhTgcIgUgKIgNgMIgIgKIgIgQIgCgEIgCgKIgBgQIABgRIAEgOIAEgKIAHgNIAJgLIAEgEIALgJIASgJIAZgHIARgDIATAAIAfAEIAXAFIAxAXIAGAEIgcAyIgugWIghgIIgPgBIgGABIgJACIgLAEIgCADIgDACIgEAFIgCAEIgCAGIAAAEIAAAFIACAIIAGAJIAIAGIAPAHIBbAiIAPAKIANAMIAIAKIACADIAGANIACAKIABAJIgBAYIgEAQIgEAJIgIAOIgDAEIgKALIgJAGIgEADIgEADIgUAIIgWAFIgYADgAD9PHIgNgDIgQgHIgKgGIgMgNIgDgDIgIgRIgDgJIgDgWIAAizIgnAAIAAg9IAnAAIAAhZIBIAAIAABZIBWAAIAAA9IhWAAIAAClIACAIIACADIACAEIABACIAFAGIADACIAHACIARACIASgBIAdgHIAAA6IgHAEIgPAHIgIACIgbAEgAhOPEIgQgEIgcgNIgHgEIgXgTIgLgMIgNgTIgKgVIgIgYIgFgrIAHgyIAFgPIAWgpIAagcIASgNIAcgMIAQgFIAXgDIASAAIAjAGIAWAIIAOAHIAYATIAOASIAQAaIAKAfIAFAXIADA2IjpAAIACAOIAGARIAIAOIARARIADADIAHAEIAPAHIAMACIAJABIAEABIAVAAIALgCIAQgFIAFgDIAPgIIAagUIAqAmIgMAOIgcAVIgPAIIgaAKIgcAFIgeABgAg9K9IgMACIgHAEIgMAHIgLALIgKANIgJASIgHAbICjAAIgDgSIgIgWIgJgOIgKgLIgIgHIgGgEIgLgFIgQgCIgIgBgAwIPEIgngOIgVgOIgdgbIgFgGIgWgpIgIggIgCgZIACgZIAIghIAWgqIAigiIAVgNIAfgMIAQgFIAagDIATAAIAaADIAQAFIAfAMIAVANIAMALIAWAXIANAVIAJAVIAJAhIABAQIgBAhIgEAQIgOAlIgNAUIgWAYIgTAPIgdAPIggAJIgJACIgkACgAv2LBIgOAFIgRAKIgLAJIgGAHIgLAQIgEAJIgIAdIgBAKIABAUIADAPIACAFIAKAWIADAEIAMAPIAEACIAHAHIAMAIIAJADIATAGIAPABIARgBIATgGIAVgLIAOgNIAMgPIACgFIACgDIAGgOIAEgUIABgUIgCgQIgJgcIgLgQIgGgIIgWgSIgFgCIgEgCIgJgDIgEgCIgKgCIgVgBgAz1PJIgXgDIgIgCIgIgDIgPgIIgHgGIgIgJIgHgLIgEgJIgEgOIgCgRIgBizIgmAAIAAg9IAmAAIAAhZIBJAAIAABZIBWAAIAAA9IhWAAIAAChIAAAEIACAIIADAHIAFAFIAFAFIADABIAIACIANABIAdgDIASgFIAAA6IgPAIIgPAFIgbAEgEgtiAPJIgjgFIgfgLIgIgDIgagSIgGgGIgRgRIgKgMIgPgcIgDgHIgFgQIgEgYIABgqIADgQIAIgYIAPgdIAFgGIAQgSIAZgVIANgIIAfgMIAZgGIAkgCIArAIIAfAMIAbASIAWAXIASAbIANAdIAGAhIABAZIgDAYIgRAtIgNAUIgVAYIgTAPIgdAPIgQAGIgrAHgEgtzALBIgOAFIgIAEIgXASIgGAIIgKAQIgIAYIgBAEIgBAaIABAKIADAPIAFAOIAJARIAJALIALAKIAQALIAJADIATAGIAPABIAagDIAOgFIARgKIAHgHIAEgCIAMgPIAFgJIAHgRIAEgOIACgVIgCgVIgKgcIgQgYIgXgSIgIgEIgJgDIgFgCIgKgCIgUgBgEggoAPIIgigGIgVgGIgdgNIgTgLIgYgTIgWgXIgMgQIgPgbIgOgnIgGggIAAguIAGgfIAGgVIASglIASgaIAVgWIAZgUIAmgVIAggKIAWgEIAkgDIAuAFIAqAMIAdAOIAZATIAXAVIATAZIAPAbIAIATIAKAqIADAhIgDAhIgKAqIgIATIgPAbIgaAhIgYAUIgbARIgeANIg4AMgEggoAJbIgcAIIgGACIgTAKIgLAIIgPAPIgNAQIgLASIgKAbIgDAOIgDAXIAAAPIADAYIADAOIALAbIAPAYIAOAPIAWASIATAJIAVAIIAWADIAPABIAXgCIAVgEIAUgIIAGgEIALgHIAQgOIAOgPIAMgRIAGgNIAJgbIADgVIABgZIgBgIIgFgcIgIgVIgGgNIgQgXIgagYIgGgEIgagNIgVgGIgPgCIgeAAgAKMPDIAAk8IBIAAIAAE8gAGaPDIAAk8IBIAAIAABFIATggIAPgRIAHgFIADgDIAMgGIADgDIAVgIIAOgDIAUgBIAABOIgiADIgUAHIgKAEIgQAOIgLALIgLAUIgEALIgFATIgDAkIAAB6gAlUPDIgBjGIgEgQIAAgDIgEgKIgKgOIgHgGIgCgCIgDgCIgDgBIgDgBIgDgBIgDgBIgDgBIgDgBIgIgBIgEAAIgDgBIgEABIgDAAIgOADIgKADIgDABIgCACIgDACIgDACIgIAHIgIALIgCADIgCAEIgBADIgBADIgCAEIgCAIIgBAJIgBADIAAC+IhIAAIAAi0IgCgaIgEgOIgCgEIgBgDIgCgDIgCgDIgDgFIgKgJIgCgCIgDgCIgDgBIgDgBIgDgBIgDgBIgDgBIgDgBIgIgBIgDAAIgEgBIgEABIgDAAIgHABIgNAEIgJAFIgFAEIgJAKIgGAJIgFAKIgEAQIgCAMIAAC7IhLAAIAAk8IBLAAIAAAvIAEgFIARgVIAKgJIAMgIIANgGIAOgEIAUgDIAVABIAQADIAbALIAPANIAJAKIAIALIADAHIAFgHIAXgVIATgNIAdgLIAQgDIAXgBIAYADIARAFIAOAHIAEADIAJAHIAIAHIAMARIALAbIAGAgIAADZgEgphAPDIAAj/IgqAAIAAg9IAqAAIAAgkIAGghIAEgJIABgEIAIgMIAJgKIATgMIANgFIAPgEIAWgBIAnADIATAGIAAA9IgKgEIgQgDIgUgBIgFAAIgMAEIgEABIgFAFIgFAHIgDAIIgDAPIAAAaIBTAAIAAA7IhTAAIAAD/gEAl4AOiIgTgEIgSgGIgRgJIgQgLIgRgSIgLgPIgJgSIgGgSIgEgUIAAgcIAEgSIAGgTIAJgRIAPgUIANgNIAQgLIARgJIAMgEIAZgFIAUgBIAiAGIAYAKIAFADIAQALIAOANIAPAUIAJARIAIAZIACAUIAAANIgCAVIgIAYIgDAGIgJASIgRATIgOANIgWANIgMAFIgTAFIgbACgEAnSAEzIgHgCIgZgGIgjgCIgSABIgbAGIgRAHIpOEsIAA6EIUAAAIAAaEgAKJJUIAAhFIBOAAIAABFgAP0F1IgRgEIgXgJIgOgIIgUgNIgRgRIgKgMIgQgcIgGgOIgGgXIgDghIABgTIAEgYIALgeIAVghIALgMIAZgUIAdgPIAYgIIAigGIASAAIAjAGIAYAHIAPAHIAVANIAXAVIAUAZIAKAVIAIAXIAFAhIAAARIgFAhIgIAYIgKAVIgKANIgVAYIgiAXIgnAPIgSAEIgbACgAP9BxIgOAEIgMAHIgLAIIgMANIgIANIgEAIIgEAOIgEAZIACAZIABAEIABAGIALAbIAJALIANANIAEAEIAMAHIATAHIAUAEIALAAIAFgBIALgBIAJgDIARgIIAIgEIAOgMIAIgMIADgDIAIgSIAFgYIABgSIgBgPIgDgOIgDgKIgGgMIgFgIIgPgSIgQgKIgEgDIgEgCIgOgEIgVgEIgLAAgADEF0IgVgGIgEgDIgFgCIgNgIIgEgDIgOgOIgJgNIgGgOIgEgPIgBgSIABgSIABgHIAFgQIAFgJIAJgNIAMgLIANgKIAPgHIAFgCIAGgCIALgDIAmgFIBDAGIAdAGIAAgOIgDgPIgBgDIgBgDIgIgPIgFgEIgNgJIgHgEIgWgFIgZgBIgkAEIgRAEIggAMIgTg7IAGgDIAhgNIAdgHIAqgFIAjABIAkAIIAMAGIARAJIASARIAEAEIAKAQIAIASIAEANIADAWIABDRIhFAAIAAgnIgEAFIgaAXIgTAJIgVAHIghAEgAD0DgIgVAFIgLAFIgKAHIgFAFIgCADIgDADIgDAIIAAACIgBADIAAADIgBACIAAAGIABADIAAACIABADIAAADIACAEIABADIAGAIIAHAGIAJAGIAQAFIAMACIAPAAIANgCIALgDIAPgGIAGgEIADgCIADgCIAKgJIACgEIACgCIACgDIAEgJIACgHIABgEIABgDIAAgYIgYgIIgmgFgAj8F3IgYgGIgegMIgagSIgRgRIgKgMIgMgVIgKgVIgGgXIgDghIAAgLIADgYIAJgfIAHgOIARgaIAWgXIAagSIAOgGIAYgIIAhgGIApACIAjAKIAXALIAaATIAMAMIgtAyIgEgFIgWgSIgggOIgTgDIgVABIgJADIgNAEIgQAJIgQAQIgKAQIgGAMIgHAdIAAAVIAFAZIAIASIAHANIAGAHIAEADIADADIALAJIAMAHIAOAEIAUAEIAEAAIAUgCIARgFIAPgIIAPgJIARgQIAtAtIggAdIgnAUIgcAHIggADgAp/F3IgagGIgmgRIgTgNIgSgRIgPgSIgSgkIgGgXIgDgQIAAgkIADgQIAJgfIAPgcIAKgMIARgRIAZgTIAXgLIAYgIIAigGIASAAIAjAGIAYAHIAdAPIANAJIARARIAPASIAPAcIAGAPIAGAgIAAAiIgGAhIgGAQIgLAVIgTAaIgRAQIgUAOIgeAOIghAJIgbACgAp/BxIgOAEIgIAFIgQAKIgNANIgHANIgLAbIAAAEIgBAFIgBAPIABAQIACAJIAGATIAEAJIALAQIAEADIAGAHIAIAHIAQAJIAOAFIAUAEIAKAAIAVgEIAXgJIAMgHIAKgJIALgPIAJgSIADgJIADgTIAAgYIgCgKIAAgEIgFgPIgEgJIgHgLIgJgMIgHgGIgPgKIgJgFIgOgEIgKgDIgUgBgAvUF3IgjgIIgzgYIgWgRIAegvIAvAaIAUAIIAaAEIASABIAGgBIASgEIAHgFIAGgFIAEgGIACgDIACgIIAAgIIgBgDIgBgEIgCgBIAAgCIgCgCIgDgEIgEgCIgJgGIgKgEIhMgZIgdgPIgKgIIgJgKIgIgLIgGgRIgDgPIAAgMIAFgaIAEgKIAIgMIAGgIIAOgNIAJgGIAEgBIAFgEIAZgIIAcgEIAVABIAfAFIAWAGIAeANIATALIgcA2IgdgRIgXgIIgXgFIgVgBIgKABIgEACIgEAAIgEACIgJAGIgEAFIgDAFIgBADIgBAEIAAAHIACAGIABACIABACIABACIABABIAMAJIAQAIIBBAVIAaAMIATANIAJAJIAJAKIAEAIIAEAMIACAJIAAAZIgGAbIgIAOIgJAMIgLAKIgNAJIgUAIIgcAHIgYACgA0BF2IgagHIgzgYIgXgRIAigvIAmAYIAaAKIAaAEIAYAAIAJgCIAJgCIAHgFIADgCIAFgGIACgDIACgDIACgIIAAgHIgBgBIAAgDIgBgCIAAgCIgDgDIgEgGIgEgCIgJgGIgKgEIhDgWIgagLIgEgCIgIgFIgNgLIgJgKIgCgEIgDgEIgGgRIgCgLIgBgQIABgFIAEgVIAEgKIADgDIACgFIAGgIIANgOIANgJIAEgBIAFgEIAEgCIAagHIAXgDIAVABIAfAFIAWAGIAkAQIANAIIgcA2IgFgEIgYgNIgXgIIgXgFIgLgBIgUABIgIACIgEACIgGAEIgFAEIgCADIgDAFIgBADIgBAEIAAAKIABABIABACIABACIABACIABACIABABIAHAGIAFADIAVAKIA8ATIAaAMIATANIAMAMIAIAKIAGARIADAPIAAANIgCAMIgEAQIgEAKIgHANIgHAIIgLAKIgEADIgdAOIgcAHIgYACgAI7F0IgEgBIgFAAIgIgCIgMgEIgHgEIgKgHIgJgJIgHgLIgBgEIgCgFIgGgUIgBi+IgqAAIAAhAIAqAAIAAhWIBIAAIAABWIBWAAIAABAIhWAAIAAChIADAMIADAIIAHAHIAJAEIAMACIAXgBIAQgEIALgGIAAA7IgHAEIgVAIIgaAFgAXcFwIgBjGIgEgSIgCgDIgBgEIgBgCIgCgDIgIgLIgFgEIgCgBIgDgCIgFgEIgDgBIgEgBIgDgBIgDgBIgQgCIgIAAIgOACIgEABIgDABIgEABIgDABIgDACIgGAEIgIAGIgHAHIgCAEIgEAFIgGAPIgDALIgBAJIAAC7IhIAAIAAk9IBIAAIAAAyIAXgbIAFgEIASgMIAVgIIAYgFIAdABIAXAGIAQAHIASAMIAOAQIAGAJIAIAPIAGAYIADAaIAADPgALdFwIAAk9IBIAAIAAE9gAgdFwIAAk9IBKAAIAAE9gA3WFwIgqhkIjIAAIgqBkIhOAAIC6mmIBGAAIC3GmgA6tDJICRAAIhIimgALaADIAAhDIBNAAIAABDgAgfADIAAhDIBMAAIAABDgAVvjRIglgIIgKgEIgNgHIgIgGIgLgKIgGgIIgIgMIgGgPIgDgQIAAgbIACgLIAFgRIAIgOIADgFIAHgIIALgKIAJgGIAVgKIAXgGIAggEIA4AEIAoAIIAAgKIgCgOIgDgKIgFgIIgGgIIgKgJIgDgBIgDgDIgGgDIgDAAIgEgCIgPgEIgZgBIgpAGIgsAOIgUg6IAwgTIBBgJIAjABIAdAGIAeANIAUAQIAMANIAJARIAJAZIAFAlIAADDIhIAAIAAgoIgJALIgQANIgRAKIgVAIIgfAGgAV7lnIgGACIgLAGIgKAGIgGAFIgDAFIgBACIgBACIgCAGIgCAIIAAALIACAHIACAFIABACIACAEIAHAIIAIAFIAKAFIARAEIARABIAEgBIAEAAIAYgFIAOgHIAJgGIAHgGIAHgJIAGgMIACgGIACgLIAAgVIgHgCIgQgGIgdgEIglAAgAJDjSIgYgEIgXgHIgVgLIgTgMIgQgQIgTgZIgKgWIgJggIgDgjIABgbIAFgXIAIgXIAPgbIAJgMIAWgVIAggUIAXgIIAYgFIAjAAIAhAIIAcAMIASAOIAPAQIAJANIAOAbIALAlIAEBAIjqAAIABAGIABADIABAGIADAIIACADIABAFIAGALIANAPIAGAFIAEACIADADIAKAGIALAEIAVAEIAcgBIAMgCIAQgHIAUgMIATgQIAqAmIgGAHIgaAXIgPAJIgiAOIgnAGgAIxndIgHADIgKAGIgJAIIgOASIgIATIgDAIIgDARICiAAIgDgRIgEgRIgFgKIgGgKIgIgIIgFgGIgNgIIgIgDIgQgEIgNgBIgEAAIgEAAgADSjSIgZgGIgWgKIgSgOIgQgOIgIgLIAAAwIhJAAIAAm4IBJAAIAACvIAEgGIAQgRIAYgSIAWgKIAhgHIAQAAIAVACIAUAGIAUAJIASALIALAJIAPAQIAQAaIAHAOIALAqIABAqIgFAjIgHAXIgLAXIgMASIgKAMIgQAOIgSAMIgUAJIgNADIgVAEIgYABgADCnbIgNAEIgIAEIgTALIgMAOIgIALIgGAOIgHAYIAAAkIAHAZIAGANIAIAMIAJAKIAWAPIAMAFIASAEIATAAIAWgGIAQgIIAKgHIAHgGIADgEIADgDIAMgUIAIgeIAAgkIgCgKIgGgTIgMgUIgDgEIgDgDIgHgHIgKgHIgQgIIgNgEIgTgCgAR6jWIgRgEIgLgFIgKgGIgGgGIgDgCIgJgPIgGgSIgDgQIgBi4IgqAAIAAhAIAqAAIAAhXIBIAAIAABXIBUAAIAABAIhUAAIAACgIADANIADAHIAEAFIAGAEIADACIAEAAIADACIAJABIARgBIALgCIAQgFIAFgDIAAA9IgOAGIghAHgAMwjZIAAk9IBIAAIAABIIAIgRIAPgXIAQgQIAKgHIAUgJIASgFIAOgBIAKAAIAABOIgfADIgFABIgPAGIgOAHIgIAGIgLAMIgJANIgIAQIgHAYIgDAdIAACAgAkJjZIgqhkIjIAAIgqBkIhOAAIC7mnIBFAAIC4GngAnfmBICQAAIhIimgAh2jaIAAm3IBJAAIAAG3g");
	this.shape.setTransform(307.475,105.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(284).to({_off:true},1).wait(225));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,615,211.6);


// stage content:
(lib._300x250_aaoo_boy = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// logo
	this.instance = new lib.logo("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(72.45,32,0.192,0.192,0,0,0,308.1,105.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(285));

	// Layer_8
	this.instance_1 = new lib.Symbol5();
	this.instance_1.parent = this;
	this.instance_1.setTransform(84.5,195.2,1,1,0,0,0,64.5,45.3);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(207).to({_off:false},0).to({y:165.2,alpha:1},32,cjs.Ease.quartInOut).wait(46));

	// frame
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#51C4ED").ss(8,1,1).p("A3bzhMAu3AAAMAAAAnDMgu3AAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(285));

	// Layer_7
	this.instance_2 = new lib.Symbol4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(108.95,201.75,1,1,0,0,0,88.5,39.9);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(129).to({_off:false},0).to({y:191.75,alpha:1},30,cjs.Ease.cubicOut).wait(38).to({y:171.75,alpha:0},23,cjs.Ease.quartInOut).wait(65));

	// Layer_6
	this.instance_3 = new lib.Symbol3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150,125,1,1,0,0,0,150,125);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(111).to({_off:false},0).to({alpha:1},26,cjs.Ease.cubicIn).wait(148));

	// Layer_5
	this.instance_4 = new lib.Symbol2();
	this.instance_4.parent = this;
	this.instance_4.setTransform(149.95,180.25,1,1,0,0,0,96.2,26.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(9).to({_off:false},0).to({y:170.25,alpha:1},41,cjs.Ease.quartInOut).wait(51).to({alpha:0},18).wait(166));

	// Layer_1
	this.instance_5 = new lib.Symbol1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(150,121.55,1,1,0,0,0,66.8,40.6);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({y:111.55,alpha:1},41,cjs.Ease.quartInOut).wait(60).to({alpha:0},18).wait(166));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#51C4ED").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_1.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(285));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(146,121,158,163);
// library properties:
lib.properties = {
	id: 'EA7F868821484FEEB1ACA9412835E0FD',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/300x250_aaoo_boy_atlas_.png", id:"300x250_aaoo_boy_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['EA7F868821484FEEB1ACA9412835E0FD'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;