(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"300x600_snow_atlas_", frames: [[0,0,397,318],[0,320,626,120]]}
];


// symbols:



(lib.asiangirl = function() {
	this.spriteSheet = ss["300x600_snow_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.docBC = function() {
	this.spriteSheet = ss["300x600_snow_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.docBC();
	this.instance.parent = this;
	this.instance.setTransform(-142,-30,0.9,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-142,-30,563.4,108);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAOIgEgDIgEgFIgBgGIABgFIAEgFIAEgDIAFgBIAGABIAFADIADAFIABAFIgBAGIgDAFIgFADIgGABg");
	this.shape.setTransform(68.7,280.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_1.setTransform(61.6,274);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgXAeIAWhBIAZAKIgeA+g");
	this.shape_2.setTransform(53.5,267.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgIgHQgGgHgNAAQgIAAgHADQgIAEgGAFIAABHIAQAAIAAAUIg5AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_3.setTransform(42.1,275.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_4.setTransform(28.2,275.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_5.setTransform(18.8,272.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgNAAQgIAAgJAEQgHADgGAGIAABGIAQAAIAAAUIg4AAIAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgIAAgHADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIALgEIAKgBQANAAAJAFQAJAFAFAKIAJgHIALgHIALgEQAGgCAHAAQAJAAAIADQAIADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_6.setTransform(-2.4,275.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_7.setTransform(-21.2,275.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AASA9IAAgUIAGAAIgYgeIgWAeIAGAAIAAAUIgpAAIAAgUIAKAAIAlgqIgigmIgNAAIAAgVIApAAIAAAVIgFAAIAVAcIAXgcIgGAAIAAgVIAoAAIAAAVIgKAAIgiAnIAkApIAJAAIAAAUg");
	this.shape_8.setTransform(-33.9,275.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgUA8QgKgEgIgJQgHgHgFgNQgDgMAAgPQgBgNAEgLQADgMAIgIQAHgJAKgFQAMgFAMAAQAOAAAKAEQAIAFAGAGQAGAHADAJQADAJACAIIAAAJIABAIIhXAAIAAAKIADAIQAEAMAKAGQAJAFALABQAKgBAJgCQAJgCAJgGIAJAOQgLAJgMAEQgNAEgNAAQgLAAgLgEgAAfgOIgCgMQgCgFgEgFQgDgEgGgDQgFgCgIAAQgGAAgHACQgFACgEAFQgEADgCAHQgDAFgBAHIA+AAg");
	this.shape_9.setTransform(-47.5,275.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_10.setTransform(141.8,247);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_11.setTransform(131.5,248.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_12.setTransform(122,245.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_13.setTransform(112.3,248.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_14.setTransform(102.4,247);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgTA8QgLgEgIgJQgHgHgEgMQgFgNAAgPQABgMADgMQADgMAIgIQAHgJALgFQALgFANAAQANAAAJAEQAJAFAHAGQAFAHADAJQADAJABAIIABAJIAAAIIhWAAIABAKIACAIQAEAMAJAGQAKAFAMABQAJgBAJgCQAIgCAKgGIAJAOQgMAJgMAEQgMAEgNAAQgLAAgKgEgAAfgOIgCgMQgCgFgDgFQgEgEgFgDQgGgCgIAAQgHAAgFACQgGACgEAFQgEADgDAHQgCAFgBAHIA+AAg");
	this.shape_15.setTransform(90.7,248.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AA0A+IAAgUIARAAIAAg3QAAgOgHgHQgHgHgNAAQgIAAgJAEQgIADgGAGIAABGIARAAIAAAUIg4AAIAAgUIASAAIAAg3QAAgOgIgHQgGgHgNAAQgJAAgHADQgIAEgGAFIAABHIAQAAIAAAUIg5AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAJgHIAJgFIALgEIAKgBQANAAAJAFQAJAFAGAKIAJgHIAKgHIALgEQAGgCAHAAQAJAAAIADQAIADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_16.setTransform(72.2,248.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_17.setTransform(52.9,248.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_18.setTransform(41.4,247);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Ag/BaIAAgUIARAAIAAiHIgRAAIAAgVIAmAAIAAAKQAIgGAJgDQAIgEAKAAQAMAAAKAFQAKAEAHAIQAHAIAEAMQAEALAAAOQAAAOgEANQgFALgHAIQgIAJgLAFQgLAEgNAAQgIAAgIgBIgNgFIAAAnIATAAIAAAUgAgLhCQgIADgFAGIAABBQADAEAIADQAHADAKAAQAHAAAHgCQAHgDAFgGQAGgGADgIQADgIAAgLQAAgLgDgIQgDgIgFgFQgFgGgHgCQgHgDgIAAQgHAAgIADg");
	this.shape_19.setTransform(29.4,251.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_20.setTransform(15,248.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgIgHQgHgHgMAAQgIAAgHADQgIAEgHAFIAABHIARAAIAAAUIg5AAIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAGAGACAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_21.setTransform(-5.3,248.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_22.setTransform(-20.1,248.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgRIAIAFIAKAFIALACIALABQAIAAAGgCQAHgCAEgEQAFgFACgIQACgIAAgMIAAgCQgGAGgIAEQgIADgKAAQgLAAgLgEQgLgEgHgJQgIgIgFgMQgEgLAAgPQAAgOAEgMQAEgLAIgIQAIgJALgFQALgEAMAAQAJAAAIACQAHADAHAFIAAgHIAWAAIAABzQAAAdgOAPQgOAPgcAAgAgJhCQgHADgFAFQgFAGgDAIQgDAIAAALQAAALACAIQADAIAFAGQAFAFAHAEQAHACAIAAIAKgBIAIgDIAGgEIAFgEIAAhCQgGgFgIgDQgIgCgIAAQgHAAgGADg");
	this.shape_23.setTransform(-39,251.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AALA+IAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgHAAgHADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJABALIAAA6IAQAAIAAAUg");
	this.shape_24.setTransform(-53.7,248.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_25.setTransform(-65.4,245.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AApBbIgwg2IgQAAIAAAiIAKAAIAAAUIg0AAIAAgUIAUAAIAAiNIgVAAIAAgUIArAAIAAAUIAABaIAVAAIAbgdIgHAAIAAgUIAuAAIAAAUIgPAAIglAlIAoArIAPAAIAAAUg");
	this.shape_26.setTransform(-76.6,245.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_27.setTransform(-91.7,248.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_28.setTransform(-106,248.8);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhBBZIAAgUIAQAAIAAiIIgQAAIAAgVIBOAAQALABAKAEQAJAEAHAGQAHAIAEAJQAEAJAAALQAAALgGAKQgGAJgMAGQAGACAEAEQAFAEADAFQAEAFACAFIABALQAAALgEAKQgEAKgHAGQgHAIgJAEQgKAEgLAAgAgaBFIApAAQAFAAAFgDIAJgHQADgFACgFQACgHAAgGQAAgFgCgEQgCgFgDgEIgJgGQgFgCgFAAIgpAAgAgagKIAoAAQAFAAAFgBQAFgDAEgEQADgEACgEQACgFAAgGQAAgFgCgFQgCgHgDgDQgEgFgFgDQgFgCgFAAIgoAAg");
	this.shape_29.setTransform(-120.6,246);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(-477,229.8,971.3,60), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAOIgFgDIgDgFIgBgGIABgFIADgFIAFgDIAFgBIAGABIAFADIADAFIABAFIgBAGIgDAFIgFADIgGABg");
	this.shape.setTransform(112.9,250.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgcBZQgLgFgIgIQgIgJgEgMQgEgMAAgPQAAgOAEgMQAEgKAIgIQAHgIALgFQALgEAOgBQAHAAAIACQAHADAHAEIAAguIgRAAIAAgUIAmAAIAAChIASAAIAAAUIgnAAIAAgKQgGAGgIAEQgIACgJAAQgMAAgKgDgAgSgLQgHADgFAFQgFAFgDAHQgDAJAAAKQAAALADAIQADAKAFAFQAFAGAHADQAHADAIgBQAJABAHgDQAGgDAGgGIAAhDQgGgFgIgCQgHgCgHAAQgIAAgHADg");
	this.shape_1.setTransform(102.9,242.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_2.setTransform(89.6,245.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_3.setTransform(77.3,245.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAMBbIAAgUIAQAAIAAg3QAAgOgHgGQgHgIgNAAQgHAAgHAEQgIADgHAFIAABHIASAAIAAAUIg6AAIAAgUIASAAIAAiNIgQAAIAAgUIAmAAIAABKIABAAIAHgGIAJgFIAKgDIAKgBQAJAAAIACQAIADAFAGQAGAFADAJQADAHAAAMIAAA6IASAAIAAAUg");
	this.shape_4.setTransform(63.2,242.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgVA8QgJgFgFgHIgMAAIAAgUIAYAAQAAAFACADQACAEAEACIAIADIAIABIAJgBIAIgDIAFgFQACgDAAgEQAAgGgEgEQgEgEgJgEIgWgIQgPgEgGgIQgHgIAAgMQAAgHADgHQACgGAGgFQAFgFAIgDQAIgCAKAAQAMAAAJADQAJAEAHAJIALAAIAAAUIgYAAQAAgFgCgDIgGgGIgIgDIgIgBIgIABIgHADQgDACgCADQgBADAAADQAAAGAEAEQADADAJADIAWAJQAPAFAHAHQAHAJAAAMQAAAIgDAHQgDAHgGAEQgGAFgJADQgIACgKAAQgNAAgJgEg");
	this.shape_5.setTransform(44.1,245.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_6.setTransform(34.6,242.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNBYIgNgDIgNgFQgHgDgFgFIALgRIAIAFIAKAFIALACIALABQAIAAAGgCQAHgCAEgEQAFgFACgIQACgIAAgMIAAgCQgGAGgIADQgIAEgKAAQgLAAgLgEQgLgEgHgJQgIgIgFgMQgEgLAAgPQAAgOAEgMQAEgMAIgHQAIgJALgFQALgEAMAAQAJAAAIACQAHACAHAGIAAgHIAWAAIAAB0QAAAdgOAPQgOAOgcAAgAgJhCQgHADgFAFQgFAGgDAIQgDAIAAALQAAAKACAJQADAIAFAFQAFAHAHACQAHADAIAAIAKgBIAIgDIAGgDIAFgFIAAhCQgGgFgIgDQgIgBgIAAQgHAAgGACg");
	this.shape_7.setTransform(18,248.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgIgHQgGgHgNAAQgIAAgHADQgIAEgGAFIAABHIAQAAIAAAUIg5AAIAAgUIARAAIAAhQIgRAAIAAgVIAnAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAIADQAHADAGAFQAFAGADAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape_8.setTransform(3.4,245.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgcBaIAAgUIASAAIAAhQIgSAAIAAgVIAnAAIAABlIASAAIAAAUgAgFg7IgFgEIgDgFIgBgGIABgFIADgFIAFgDIAFgCIAGACIAFADIADAFIABAFIgBAGIgDAFIgFAEIgGABg");
	this.shape_9.setTransform(-8.3,242.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_10.setTransform(-16.7,243.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AALA+IAAgUIASAAIAAg3QAAgOgIgHQgGgHgOAAQgGAAgIADQgIAEgGAFIAABHIARAAIAAAUIg6AAIAAgUIARAAIAAhQIgRAAIAAgVIAoAAIAAAPIAIgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAFAGADAIQAEAJAAALIAAA6IARAAIAAAUg");
	this.shape_11.setTransform(-29.2,245.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgTA8QgLgEgHgJQgIgHgEgMQgFgNAAgPQABgNADgLQAEgMAHgIQAHgJALgFQAKgFANAAQAOAAAJAEQAJAEAHAHQAFAHADAJQADAIABAJIABAJIAAAIIhWAAIABAKIACAIQAEAMAJAGQAKAGAMAAQAJAAAJgDQAIgDALgFIAJAOQgNAJgMAEQgMAEgNAAQgLAAgKgEgAAfgOIgCgMQgCgFgDgFQgEgEgFgDQgGgCgIAAQgHAAgFACQgGACgEAFQgEADgDAHQgCAGgBAGIA+AAg");
	this.shape_12.setTransform(-44.4,245.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgrA9IAAgUIARAAIAAhQIgRAAIAAgUIAnAAIAAARIAEgHIAGgGIAHgEQAEgBAFAAIALAAIALAAIAAAbIgWAAIAAgIIgIACQgEABgEADQgDADgDAFQgCAEgBAHIAAA5IAUAAIAAAUg");
	this.shape_13.setTransform(-56.7,245.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgeA9QgHgDgGgFQgFgFgDgGQgDgHAAgHQAAgIACgGQADgGADgEQAEgEAFgCIALgFIALgDIALAAIAOAAIAKACIAAgKQAAgHgCgFQgCgEgDgDQgDgEgFgBQgFgCgFAAIgKABIgKACIgIADIgGADIgHgPIAJgFIALgEIAMgDIALgBQAKAAAIADQAJACAGAFQAFAGAEAIQADAIAAALIAAA8IANAAIAAAUIgjAAIAAgLQgHAGgIAFQgIAEgKAAQgJAAgIgDgAgQAGQgFACgEACQgEADgCAEQgCAEAAAFQAAAFACAEIAFAGIAHADIAKABIAJgBIAHgCIAHgFIAGgFIAAgbIgYAAQgHAAgFABg");
	this.shape_14.setTransform(-69,245.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag+BZIAAgUIAQAAIAAiJIgQAAIAAgUIBGAAQAMAAAKADQAKADAIAGQAHAGAEAJQAEAJAAAMQAAAKgEAJQgEAIgHAHQgHAGgLADQgKADgMAAIgfAAIAAA/IASAAIAAAUgAgXgMIAfAAQAHAAAGgBQAFgCAEgEQAEgDADgGQACgFAAgHQAAgNgIgHQgIgIgSAAIgcAAg");
	this.shape_15.setTransform(-82.2,242.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(-92.3,226.6,209.9,33), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.asiangirl();
	this.instance.parent = this;
	this.instance.setTransform(-572,238,1.089,1.089);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-572,238,432.3,346.3), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgZBGQgKgGgGgIIgOAAIAAgYIAcAAQAAAGADAFQACAEAFACIAJAEIAKABIAKgBIAJgEIAGgGQACgDAAgFQAAgHgFgFQgEgEgLgFIgagKQgQgFgIgIQgIgJAAgOQAAgJADgIQADgHAHgGQAGgFAJgDQAJgEAMAAQAOAAAKAEQALAEAIALIANAAIAAAXIgcAAQAAgGgCgEQgDgDgEgDIgKgEIgJgBIgKABIgIAEQgDADgCADQgCADAAAEQAAAHAFAEQAEAEAKAEIAaAJQASAGAIAKQAIAKAAAOQAAAJgEAIQgEAIgHAGQgHAFgJADQgKADgMAAQgPAAgLgFg");
	this.shape.setTransform(197.7,251.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBBdQgHgCgEgFQgFgGgDgJQgCgIAAgOIABhNIgXAAIAAgVIAXAAIAAgiIAYgLIAAAtIAhAAIAAAVIghAAIgBBRQAAAIACAGQACAFAEACQAEACAGAAIAKgBIAKgEIAFARIgNAGQgIABgKAAQgJABgGgDg");
	this.shape_1.setTransform(185.8,249.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgcBGQgNgGgJgKQgJgKgGgOQgFgNAAgRQAAgQAFgOQAGgOAJgJQAKgKANgGQANgFAOAAQAQAAANAFQANAGAJAKQAKAJAFAOQAFAOAAAQQAAAQgFAOQgFAOgKAKQgJAKgNAGQgNAFgQAAQgPAAgNgFgAgQgxQgIAEgGAGQgGAHgEAKQgDAKAAAMQAAAMADAKQAEAKAGAHQAGAHAIADQAIAEAIAAQAKAAAIgEQAIgDAGgHQAGgHADgKQAEgKAAgMQAAgMgEgKQgDgKgGgHQgGgGgIgEQgIgDgKAAQgIAAgIADg");
	this.shape_2.setTransform(172.1,251.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgcBGQgNgGgJgKQgJgKgGgOQgFgNAAgRQAAgQAFgOQAGgOAJgJQAKgKANgGQANgFAOAAQAQAAANAFQANAGAJAKQAKAJAFAOQAFAOAAAQQAAAQgFAOQgFAOgKAKQgJAKgNAGQgNAFgQAAQgPAAgNgFgAgQgxQgIAEgGAGQgGAHgEAKQgDAKAAAMQAAAMADAKQAEAKAGAHQAGAHAIADQAIAEAIAAQAKAAAIgEQAIgDAGgHQAGgHADgKQAEgKAAgMQAAgMgEgKQgDgKgGgHQgGgGgIgEQgIgDgKAAQgIAAgIADg");
	this.shape_3.setTransform(155.4,251.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgNBoQgJgDgHgFIAAAJIgZAAIAAi8IgUAAIAAgXIAtAAIAABSQAKgHAKgEQAKgEALAAQAOAAAMAFQALAGAJAJQAIAJAFANQAEANAAAQQAAARgFAOQgFAOgJAKQgJAKgNAFQgNAFgPAAQgJAAgKgDgAgNgMQgJAEgHAHIAABLQAFAEAIAEQAJADAMAAQAIAAAIgDQAJgDAGgHQAGgGAEgKQADgKAAgNQAAgMgDgKQgEgJgGgFQgGgHgIgDQgHgDgKAAQgIAAgKAEg");
	this.shape_4.setTransform(138.4,248);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AA9BIIAAgYIAUAAIAAg/QAAgRgJgIQgIgJgQAAQgJABgJAEQgKAFgHAGIAABRIAUAAIAAAYIhBAAIAAgYIAUAAIAAg/QAAgRgIgIQgIgJgQAAQgJABgJAEQgJAEgIAHIAABRIAUAAIAAAYIhCAAIAAgYIATAAIAAhdIgTAAIAAgYIAtAAIAAARIAKgIIAKgGIANgDIAMgCQAPAAAMAFQAJAGAHAMIALgJIALgIIAOgEQAGgCAHAAQAMAAAJADQAJADAHAGQAGAHADAKQAEAKAAAOIAABCIATAAIAAAYg");
	this.shape_5.setTransform(116.1,251.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgcBFQgJgDgGgHQgGgGgEgKQgDgKAAgOIAAhDIgTAAIAAgXIAuAAIAABXQAAAQAHAJQAIAIAOAAQAHAAAJgDQAKgDAIgFIAAhWIgTAAIAAgXIAtAAIAAB1IAQAAIAAAXIgpAAIAAgMQgKAHgLAEQgLAEgMAAQgLAAgIgDg");
	this.shape_6.setTransform(92,251.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgOBnIgQgEIgQgGQgIgEgFgFIANgVIAJAHIALAFIANADIANACQAJAAAIgDQAIgCAFgFQAFgGACgJQADgKAAgOIAAgCQgHAHgJAEQgKAEgLAAQgNAAgNgFQgMgFgKgJQgIgKgFgOQgGgNAAgSQAAgQAFgOQAFgNAJgKQAJgJANgFQANgGAOAAQAKAAAKADQAHACAJAGIAAgHIAZAAIAACHQAAAhgPASQgQARgiAAgAgLhNQgIADgGAHQgGAGgDAJQgDAKgBAMQAAANADAKQAEAJAGAHQAGAGAIAEQAIADAJAAIALgBIAKgDIAHgFIAGgFIAAhNQgHgGgJgDQgJgCgKAAQgIAAgIADg");
	this.shape_7.setTransform(75,254.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgbAjIAahNIAdAMIgjBJg");
	this.shape_8.setTransform(215.1,228.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgBBdQgHgCgFgFQgEgGgCgJQgDgIAAgOIAAhNIgWAAIAAgUIAXAAIAAgjIAXgLIAAAuIAiAAIAAAUIgiAAIAABRQAAAIACAGQACAEAEACQAFADAFAAIAKgBIAJgEIAGARIgOAGQgHACgKAAQgJgBgGgCg");
	this.shape_9.setTransform(206.9,218.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgWBGQgNgFgJgJQgIgKgFgOQgGgOAAgSQABgPAEgNQAEgOAJgKQAIgKAMgGQANgGAQAAQAPAAALAFQALAFAGAIQAIAIADAKQADALABAKIABALIAAAJIhkAAIAAALIADAKQAFANALAHQAMAHANAAQALAAAKgDQALgDALgHIALASQgOAJgOAFQgPAFgPAAQgOAAgLgFgAAkgQIgCgOQgCgHgEgFQgEgFgHgDQgGgCgKAAQgHAAgHACQgGADgGAFQgEAEgCAHQgEAHgBAIIBIAAg");
	this.shape_10.setTransform(193.2,220.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAwBqIg5g/IgTAAIAAAoIAMAAIAAAXIg8AAIAAgXIAXAAIAAilIgYAAIAAgXIAyAAIAAAXIgBAAIAABpIAZAAIAhgiIgJAAIAAgXIA2AAIAAAXIgSAAIgrAsIAvAyIARAAIAAAXg");
	this.shape_11.setTransform(177.1,217.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgXBFQgMgFgJgKQgJgKgGgOQgEgOAAgQQgBgQAGgOQAFgNAKgKQAJgKAMgFQANgGANAAQANAAAMAFQANAEAIAJIAOAAIAAAYIgZAAQgGgKgIgFQgJgFgMABQgIgBgIAEQgIAEgFAGQgGAIgDAJQgEAKAAALQAAAMAEAKQADAJAGAHQAFAHAIADQAIAEAIgBQANAAAKgFQAKgHAFgMIAWAKQgFAJgGAHQgGAHgIAFQgHAEgJAEQgJACgLAAQgNAAgNgGg");
	this.shape_12.setTransform(160.5,220.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgjBHQgJgDgGgGQgGgFgEgIQgDgHAAgJQAAgJADgHQACgHAFgFQAEgFAGgCIAMgGIAOgDIANgBIAPABIAMABIAAgLQAAgIgCgGQgCgFgEgEQgEgEgFgBQgGgCgGAAIgMABIgLADIgJACIgIAFIgIgSIALgGIANgFIANgDIAOgBQALAAAKACQAKADAHAGQAGAHAEAKQAEAJAAANIAABGIAPAAIAAAXIgpAAIAAgMQgIAHgKAFQgIAEgNAAQgKAAgJgDgAgTAHQgGACgEAEQgFADgCAEQgDAEAAAHQAAAFACAFIAGAGQAEAEAFABIAMABIAKgBIAIgDIAJgFIAGgGIAAggIgcAAQgIAAgGABg");
	this.shape_13.setTransform(144.9,220.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgZB1QAMgCAFgJQAGgKAAgQIAAh9IgUAAIAAgYIAtAAIAACYQAAAMgDAKQgEAJgFAHQgGAHgIAEQgJAEgLAAgAAEhoIgEgDIgEgGIgBgGIABgGIAEgFIAEgEIAGgBIAHABIAEAEIAEAFIABAGIgBAGIgEAGIgEADIgHABg");
	this.shape_14.setTransform(132.7,220.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAgBIIgghwIgfBwIgYAAIgmh3IgNAAIAAgYIAtAAIAAAYIgGAAIAZBZIAhhxIAVAAIAgBxIAahZIgIAAIAAgYIAtAAIAAAYIgNAAIgmB3g");
	this.shape_15.setTransform(111.7,220.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgcBGQgNgGgJgKQgJgKgGgOQgFgNAAgRQAAgQAFgOQAGgOAJgJQAKgKANgGQANgFAOAAQAQAAANAFQANAGAJAKQAKAJAFAOQAFAOAAAQQAAAQgFAOQgFAOgKAKQgJAKgNAGQgNAFgQAAQgPAAgNgFgAgQgxQgIAEgGAGQgGAHgEAKQgDAKAAAMQAAAMADAKQAEAKAGAHQAGAHAIADQAIAEAIAAQAKAAAIgEQAIgDAGgHQAGgHADgKQAEgKAAgMQAAgMgEgKQgDgKgGgHQgGgGgIgEQgIgDgKAAQgIAAgIADg");
	this.shape_16.setTransform(92.3,220.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAOBIIAAgXIAUAAIAAhAQAAgQgJgJQgIgIgPAAQgIAAgJAEQgJAEgIAHIAABSIAUAAIAAAXIhDAAIAAgXIAUAAIAAheIgUAAIAAgXIAuAAIAAAQIAKgHIAKgHIAMgDIAMgCQALAAAJADQAJADAHAHQAGAGAEAKQADAKAAANIAABEIAUAAIAAAXg");
	this.shape_17.setTransform(74.7,220.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgZBGQgKgGgGgIIgOAAIAAgYIAcAAQAAAGADAEQACAEAFADIAJAEIAKABIAKgBIAJgEIAGgGQACgEAAgEQAAgHgFgFQgEgEgLgFIgagKQgQgEgIgKQgIgIAAgOQAAgJADgIQADgHAHgGQAGgFAJgDQAJgEAMAAQAOAAAKAFQALADAIALIANAAIAAAXIgcAAQAAgFgCgEQgDgEgEgDIgKgDIgJgCIgKACIgIADQgDADgCADQgCADAAAEQAAAHAFAFQAEADAKAEIAaAKQASAFAIAKQAIAKAAAOQAAAJgEAIQgEAIgHAGQgHAFgJADQgKADgMAAQgPAAgLgFg");
	this.shape_18.setTransform(58.6,220.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgbAjIAahMIAdALIgjBIg");
	this.shape_19.setTransform(188.9,197.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgZBGQgKgGgGgIIgOAAIAAgXIAcAAQAAAFADAEQACAEAFADIAJAEIAKABIAKgBIAJgEIAGgGQACgEAAgEQAAgHgFgFQgEgEgLgFIgagJQgQgGgIgJQgIgIAAgOQAAgJADgIQADgIAHgFQAGgGAJgDQAJgDAMAAQAOAAAKAFQALADAIALIANAAIAAAYIgcAAQAAgHgCgDQgDgEgEgDIgKgDIgJgCIgKACIgIADQgDADgCADQgCADAAAEQAAAHAFAFQAEAEAKADIAaAKQASAGAIAIQAIALAAAOQAAAJgEAIQgEAIgHAFQgHAGgJADQgKADgMAAQgPAAgLgFg");
	this.shape_20.setTransform(179.1,189.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAOBIIAAgXIAUAAIAAhAQAAgQgJgJQgIgIgPAAQgIgBgJAFQgJAEgIAGIAABTIAUAAIAAAXIhDAAIAAgXIAUAAIAAheIgUAAIAAgXIAuAAIAAAQIAKgHIAKgGIAMgFIAMgBQALAAAJADQAJADAHAHQAGAGAEAKQADAKAAANIAABEIAUAAIAAAXg");
	this.shape_21.setTransform(163,189.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgWBGQgNgFgJgJQgIgKgFgOQgFgOgBgSQAAgPAFgNQAEgOAIgKQAJgKANgGQAMgGAQAAQAPAAALAFQALAFAHAIQAGAIAEAKQAEALAAAKIABALIAAAJIhlAAIABALIADAKQAFANALAHQALAHANAAQALAAALgDQALgDALgHIAKASQgOAJgNAFQgPAFgPAAQgNAAgMgFgAAkgQIgCgOQgCgHgEgFQgEgFgHgDQgGgCgJAAQgIAAgHACQgGADgFAFQgFAEgCAHQgDAHgCAIIBIAAg");
	this.shape_22.setTransform(145.3,189.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgBBdQgHgCgEgFQgFgGgCgJQgDgJAAgNIABhNIgXAAIAAgUIAXAAIAAgiIAXgNIAAAvIAiAAIAAAUIgiAAIAABRQAAAIACAFQACAGAEABQAEACAFAAIALgBIAKgDIAFARIgNAFQgIADgJAAQgKAAgGgDg");
	this.shape_23.setTransform(132.5,187.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgBBdQgHgCgFgFQgEgGgDgJQgCgJAAgNIAAhNIgWAAIAAgUIAXAAIAAgiIAYgNIAAAvIAhAAIAAAUIghAAIgBBRQAAAIACAFQACAGAEABQAFACAFAAIAKgBIAKgDIAFARIgOAFQgHADgKAAQgJAAgGgDg");
	this.shape_24.setTransform(122.1,187.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AggBpIAAgYIAUAAIAAhdIgVAAIAAgYIAuAAIAAB1IAVAAIAAAYgAgGhFIgGgEIgDgGIgCgHIACgHIADgFIAGgEIAGgCIAHACIAFAEIAEAFIACAHIgCAHIgEAGIgFAEIgHABg");
	this.shape_25.setTransform(112.5,186.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AA/BoIAAgYIAWAAIAAieIhIC2IgXAAIhJi2IAACeIAVAAIAAAYIhDAAIAAgYIAUAAIAAicIgUAAIAAgbIBBAAIBBCyIBDiyIA+AAIAAAbIgTAAIAACcIATAAIAAAYg");
	this.shape_26.setTransform(93,186.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(49.8,168,172.1,99.4), null);


(lib.shaker = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AALA+IAAgUIASAAIAAg3QAAgOgHgHQgIgHgNAAQgGAAgIADQgIAEgHAFIAABHIASAAIAAAUIg5AAIAAgUIAQAAIAAhQIgQAAIAAgVIAnAAIAAAPIAIgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAGAGADAIQADAJAAALIAAA6IARAAIAAAUg");
	this.shape.setTransform(168.5,-10.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_1.setTransform(153.2,-10);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag/BaIAAgUIARAAIAAiHIgRAAIAAgVIAmAAIAAAKQAIgGAJgDQAIgEAKAAQAMAAAKAFQAKAEAHAIQAHAIAEAMQAEALAAAOQAAAOgEANQgFALgHAIQgIAJgLAFQgLAEgNAAQgIAAgIgBIgNgFIAAAnIATAAIAAAUgAgLhCQgIADgFAGIAABBQADAEAIADQAHADAKAAQAHAAAHgCQAHgDAFgGQAGgGADgIQADgIAAgLQAAgLgDgIQgDgIgFgFQgFgGgHgCQgHgDgIAAQgHAAgIADg");
	this.shape_2.setTransform(133.4,-7.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgTA8QgLgEgIgJQgHgHgEgNQgFgMAAgPQABgMADgMQAEgMAHgIQAHgJALgFQALgFANAAQANAAAJAEQAJAFAHAGQAFAHADAJQADAJABAIIABAJIAAAIIhWAAIABAKIACAIQAEAMAJAGQAKAFAMABQAJgBAJgCQAIgCAKgGIAJAOQgMAJgMAEQgMAEgNAAQgLAAgKgEgAAfgOIgCgMQgCgFgDgFQgEgEgFgDQgGgCgIAAQgHAAgFACQgGACgEAFQgEADgDAHQgCAFgBAHIA+AAg");
	this.shape_3.setTransform(119.1,-9.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgUA8QgKgEgIgJQgHgHgEgNQgEgMgBgPQAAgMAEgMQAEgMAHgIQAHgJAKgFQAMgFANAAQANAAAJAEQAKAFAFAGQAGAHADAJQADAJABAIIABAJIABAIIhXAAIABAKIACAIQAEAMAKAGQAJAFALABQAKgBAJgCQAIgCAKgGIAJAOQgMAJgLAEQgNAEgNAAQgLAAgLgEgAAfgOIgCgMQgCgFgEgFQgDgEgGgDQgFgCgIAAQgGAAgHACQgFACgEAFQgEADgDAHQgCAFgBAHIA+AAg");
	this.shape_4.setTransform(105.3,-9.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AApBbIgwg2IgQAAIAAAiIAKAAIAAAUIg0AAIAAgUIAUAAIAAiNIgVAAIAAgUIArAAIAAAUIAABaIAVAAIAbgdIgHAAIAAgUIAuAAIAAAUIgPAAIglAlIAoArIAPAAIAAAUg");
	this.shape_5.setTransform(91.5,-13);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_6.setTransform(74,-11.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgMAfIAAg8IAZgBIgFA9g");
	this.shape_7.setTransform(67.4,-19.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAMA+IAAgUIARAAIAAg3QAAgOgHgHQgIgHgMAAQgIAAgHADQgIAEgHAFIAABHIARAAIAAAUIg4AAIAAgUIARAAIAAhQIgRAAIAAgVIAmAAIAAAPIAJgHIAJgFIAKgEIAKgBQAKAAAHADQAJADAFAFQAGAGADAIQACAJAAALIAAA6IARAAIAAAUg");
	this.shape_8.setTransform(57.6,-10.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_9.setTransform(42.3,-10);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAbA+IgbhgIgbBgIgUAAIghhmIgKAAIAAgVIAmAAIAAAVIgGAAIAWBMIAdhhIARAAIAcBhIAWhMIgHAAIAAgVIAmAAIAAAVIgKAAIghBmg");
	this.shape_10.setTransform(25.4,-9.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AglBYIAAgUIAOAAIAOghIgphmIgKAAIAAgUIAuAAIAAAUIgOAAIAcBMIAdhMIgOAAIAAgUIAuAAIAAAUIgNAAIg1CHIAQAAIAAAUg");
	this.shape_11.setTransform(133.2,-30.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgUA8QgKgFgHgHQgIgJgEgMQgFgLAAgQQABgNADgLQADgMAIgJQAHgIALgFQALgFANAAQANAAAJAEQAJAFAHAGQAFAHADAJQADAJABAJIABAJIAAAIIhWAAIABAJIACAIQAEAMAJAGQAKAGAMgBQAJABAJgDQAIgDALgFIAJAPQgNAIgMAEQgMAEgNAAQgLAAgLgEgAAfgNIgCgNQgCgGgDgEQgEgEgFgCQgGgDgIAAQgHAAgFADQgGACgEADQgEAFgDAFQgCAGgBAIIA+AAg");
	this.shape_12.setTransform(119.5,-32.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAMBbIAAgUIAQAAIAAg3QAAgOgHgGQgHgIgNAAQgHAAgHAEQgIADgHAFIAABHIASAAIAAAUIg6AAIAAgUIASAAIAAiNIgQAAIAAgUIAmAAIAABKIABAAIAHgGIAJgFIAKgDIAKgBQAJAAAIACQAIADAFAGQAGAFADAJQADAHAAAMIAAA6IASAAIAAAUg");
	this.shape_13.setTransform(105.2,-36);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_14.setTransform(92.7,-34.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgTA8QgLgFgHgHQgIgJgEgMQgFgLAAgQQABgNADgLQAEgMAHgJQAHgIALgFQAKgFANAAQAOAAAJAEQAJAFAHAGQAFAHADAJQADAJABAJIABAJIAAAIIhWAAIABAJIACAIQAEAMAJAGQAKAGAMgBQAJABAJgDQAIgDALgFIAJAPQgNAIgMAEQgMAEgNAAQgLAAgKgEgAAfgNIgCgNQgCgGgDgEQgEgEgFgCQgGgDgIAAQgHAAgFADQgGACgEADQgEAFgCAFQgDAGgBAIIA+AAg");
	this.shape_15.setTransform(75.8,-32.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgYA7QgIgCgFgGQgFgGgDgIQgDgJAAgLIAAg5IgQAAIAAgVIAnAAIAABLQAAAOAGAHQAHAHAMAAQAGAAAIgCQAIgDAHgFIAAhIIgQAAIAAgVIAnAAIAABlIANAAIAAAUIgjAAIAAgLQgIAGgKADQgKAEgKAAQgJAAgHgDg");
	this.shape_16.setTransform(60.6,-32.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAHBaIAAgUIARAAIAAgtQgGAGgHADQgIADgJAAQgMAAgKgEQgLgEgIgIQgIgJgEgMQgEgLAAgPQAAgOAEgMQAEgLAIgIQAHgJALgEQALgFAOAAQAHAAAHACQAHACAHAFIAAgGIAWAAIAACcIASAAIAAAUgAgShCQgHACgFAGQgFAGgDAHQgDAIAAALQAAALADAIQADAIAFAGQAFAGAHADQAHACAIAAQAJAAAHgDQAHgDAEgFIAAhDQgGgFgHgCQgIgCgGAAQgIAAgHADg");
	this.shape_17.setTransform(46.8,-30.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgYA8QgLgFgIgIQgIgJgEgMQgFgMAAgOQAAgNAFgMQAEgMAJgIQAIgJALgFQALgEAMAAQAOAAALAEQALAFAIAIQAIAJAFAMQAEALAAAOQAAAOgEAMQgFAMgIAIQgIAJgLAFQgLAEgOAAQgMAAgMgEgAgNgpQgHACgFAGQgGAGgDAIQgDAJAAAKQAAAKADAJQADAIAGAGQAFAGAHADQAHAEAGAAQAIAAAHgEQAHgDAFgGQAGgGADgIQACgIAAgLQAAgKgCgJQgDgIgFgGQgGgGgHgCQgHgDgIAAQgGAAgHADg");
	this.shape_18.setTransform(32,-33);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_19.setTransform(20.5,-34.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgUA8QgKgEgIgJQgHgHgFgMQgDgNAAgPQgBgNAEgLQADgMAIgIQAHgJAKgFQAMgFAMAAQAOAAAKAEQAIAEAGAHQAGAHADAJQADAIACAJIAAAJIABAIIhXAAIAAAKIADAIQAEAMAKAGQAJAGALAAQAKAAAJgDQAJgDAJgFIAJAOQgLAJgMAEQgNAEgNAAQgLAAgLgEgAAfgOIgCgMQgCgFgEgFQgDgEgGgDQgFgCgIAAQgGAAgHACQgFACgEAFQgEADgCAHQgDAGgBAGIA+AAg");
	this.shape_20.setTransform(107.3,-55.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAMBbIAAgUIAQAAIAAg3QAAgOgHgGQgHgIgNAAQgHAAgHAEQgIADgHAFIAABHIASAAIAAAUIg6AAIAAgUIASAAIAAiNIgQAAIAAgUIAmAAIAABKIABAAIAHgGIAJgFIAKgDIAKgBQAJAAAIACQAIADAFAGQAGAFADAJQADAHAAAMIAAA6IASAAIAAAUg");
	this.shape_21.setTransform(93,-59);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgBBQQgGgCgEgFQgEgEgCgIQgCgIAAgLIABhCIgUAAIAAgSIAUAAIAAgdIAUgKIAAAnIAdAAIAAASIgdAAIAABFQAAAHABAFQACAEADACQAEACAFAAIAIgBIAJgDIAFAOIgMAFQgGACgJAAQgIAAgFgCg");
	this.shape_22.setTransform(80.5,-57.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AhLBZIAAgUIARAAIAAiJIgRAAIAAgUIBCAAQALAAALADQALADAKAGQAJAGAIAIQAIAIAFAKQAGAKADALQADALAAAMQAAAMgDALQgDAMgGAKQgFAKgIAIQgIAIgJAGQgKAFgLAEQgLADgLAAgAgjBFIAcAAQALAAALgGQAKgFAJgJQAIgKAEgMQAFgNAAgOQAAgOgFgMQgEgNgIgJQgJgJgKgFQgLgGgLAAIgcAAg");
	this.shape_23.setTransform(62.4,-58.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAmBZIhRiSIAAB+IASAAIAAAUIg6AAIAAgUIARAAIAAiIIgRAAIAAgVIAwAAIBQCRIABgFIAAh3IgUAAIAAgVIA6AAIAAAVIgQAAIAACcg");
	this.shape_24.setTransform(44.2,-58.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAgBZIAAgUIAOAAIgOgpIhDAAIgOApIATAAIAAAUIg6AAIAAgUIAPAAIA4idIAhAAIA3CdIASAAIAAAUgAAaAJIgbhPIgbBPIA2AAg");
	this.shape_25.setTransform(25.1,-58.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.shaker, new cjs.Rectangle(14.1,-74.9,164.6,79), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AghA5QgHgDgEgEIgFgGIgEgJIgBgNQAAgGACgKIAKgtIgPAAIAEgTIAmAAIgNA6QgFAVAEAJQAFAKAOAAQAHAAAEgCQAFgCAEgEIAHgJIAOg+IgPAAIAFgTIAlAAIgWBgIARAAIgEATIgnAAIADgMIgIAGIgHAFIgJACIgIABQgHAAgHgCg");
	this.shape.setTransform(111.7,71.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgbA5QgKgEgHgIQgHgGgEgLQgEgJAAgLQAAgIACgJQACgKAFgHQAEgIAGgGQAHgGAHgFQAIgEAIgCQAJgDAIAAQALAAAKAEQAKAEAHAHQAHAHAEAKQAEAJAAALQAAAJgCAJQgCAJgFAHQgEAIgGAHQgHAGgHAFQgIAEgIADQgJACgIAAQgMAAgJgEgAgJglQgIAEgGAGQgGAGgDAJQgEAJAAAKQAAAHACAGQADAHAEAFQAEAEAGACQAFADAHAAQAHAAAIgEQAIgDAGgHQAGgGAEgJQADgJAAgKQAAgHgCgGQgDgHgEgEQgEgEgGgDQgGgCgGAAQgIAAgHADg");
	this.shape_1.setTransform(97.5,71.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhDBUIAEgTIAMAAIAVghIgNhgIgLAAIAFgTIAqAAIgEATIgJAAIAHBGIAshGIgJAAIAEgTIAqAAIgFATIgJAAIhSCBIALAAIgEATg");
	this.shape_2.setTransform(84.4,74.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgwA6IAWhfIgWAAIAFgTIArAAIgDAPIAFgGIAIgGIAIgDIAJgBIAHAAIAGAAIAJABIgHAgIgXAAIADgOQgLAAgHAFQgHAGgFAJIgNA5IATAAIgEATg");
	this.shape_3.setTransform(67.3,71.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AghA5QgIgEgGgGQgGgHgEgIQgEgJAAgKQAAgPAGgOQAGgNAKgKQAJgKANgFQANgFAOAAQAIAAAIACQAHADAFAEIABgGIAXAAIgXBfIASAAIgEATIgoAAIABgIQgHAFgHADQgHACgIAAQgKAAgIgDgAgIglQgIAEgHAGQgGAHgEAKQgEAJAAAMQAAAHACAGQACAFADAEQAEAEAFACQAFACAGAAIAIgBIAIgDIAHgDIAGgEIAOg9QgCgEgHgDQgGgCgKAAQgIAAgIADg");
	this.shape_4.setTransform(53.4,71.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZA6QgJgEgHgHQgHgHgEgJQgEgKAAgNQAAgNAFgNQAFgNAJgJQAJgJANgGQAMgFANAAQALAAAJADQAIAEAGAGQAHAGADAIQADAIAAAJIgBALIgBAJIhYAAIAAACIgBADQAAAHADAGQACAGAEAEQAEAFAGACQAFADAHAAQAIAAAIgEQAIgEAGgHIAQAMIgJAJQgFAFgGACQgHADgHACIgOABQgKAAgKgDgAAjgNQAAgHgCgFQgCgGgDgDQgEgEgFgCQgGgBgGAAQgHAAgEACQgGACgFAEQgFADgEAGIgGALIBBAAIAAAAg");
	this.shape_5.setTransform(39.9,71.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAQA7IARhGQADgNgFgIQgFgGgMAAQgJAAgHADQgIAEgHAHIgTBTIgXAAIAXhfIgWAAIAEgTIAsAAIgDALQAIgGAJgEQAIgEALAAQAJAAAIADQAGADAFAFQAFAGABAHQABAJgCAKIgNA3IARAAIgFATg");
	this.shape_6.setTransform(25.4,71.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgZA6QgJgEgHgHQgHgHgEgJQgEgKAAgNQAAgNAFgNQAFgNAJgJQAJgJANgGQAMgFANAAQALAAAJADQAIAEAGAGQAHAGADAIQADAIAAAJIgBALIgBAJIhYAAIAAACIgBADQAAAHADAGQACAGAEAEQAEAFAGACQAFADAHAAQAIAAAIgEQAIgEAGgHIAQAMIgJAJQgFAFgGACQgHADgHACIgOABQgKAAgKgDgAAjgNQAAgHgCgFQgCgGgDgDQgEgEgFgCQgGgBgGAAQgHAAgEACQgGACgFAEQgFADgEAGIgGALIBBAAIAAAAg");
	this.shape_7.setTransform(6.4,71.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAQA7IARhGQADgNgFgIQgFgGgMAAQgJAAgHADQgIAEgHAHIgTBTIgXAAIAWhfIgVAAIAEgTIArAAIgCALQAIgGAJgEQAIgEALAAQAJAAAIADQAGADAFAFQAEAGACAHQABAJgCAKIgNA3IARAAIgEATg");
	this.shape_8.setTransform(-8.2,71.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgbA5QgKgEgHgIQgHgGgEgLQgEgJAAgLQAAgIACgJQACgKAFgHQAEgIAGgGQAHgGAHgFQAIgEAIgCQAJgDAIAAQALAAAKAEQAKAEAHAHQAHAHAEAKQAEAJAAALQAAAJgCAJQgCAJgFAHQgEAIgGAHQgHAGgHAFQgIAEgIADQgJACgIAAQgMAAgJgEgAgJglQgIAEgGAGQgGAGgDAJQgEAJAAAKQAAAHACAGQADAHAEAFQAEAEAGACQAFADAHAAQAHAAAIgEQAIgDAGgHQAGgGAEgJQADgJAAgKQAAgHgCgGQgDgHgEgEQgEgEgGgDQgGgCgGAAQgIAAgHADg");
	this.shape_9.setTransform(-22.7,71.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgnBUQgIgEgHgGQgGgHgEgJQgDgJAAgLQAAgPAFgNQAGgMAJgKQAJgKANgFQANgFANAAQAJAAAHACQAIADAGAEIAKgtIgTAAIAEgTIAqAAIgkCaIAUAAIgFATIgpAAIABgIQgGAFgGACQgHADgIAAQgKAAgJgEgAgQgJQgIADgGAGQgHAGgDAKQgEAJAAALQAAAIACAGQACAGAEAEQAEAEAFACQAGADAGAAQAHAAAIgEQAGgDAGgGIAOg7QgEgEgGgDQgHgDgJAAQgIAAgIAEg");
	this.shape_10.setTransform(-41.5,68.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAQA7IARhGQADgNgFgIQgFgGgMAAQgJAAgHADQgIAEgHAHIgTBTIgXAAIAWhfIgVAAIAEgTIArAAIgCALQAIgGAJgEQAIgEALAAQAJAAAIADQAGADAFAFQAEAGACAHQABAJgCAKIgNA3IARAAIgEATg");
	this.shape_11.setTransform(-56.8,71.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgbBVIAWhfIgVAAIAFgTIAqAAIgVBfIARAAIgEATgAAIg4IgFgDIgDgFIAAgGIAAgGIADgEIAFgEIAGgBIAFABIAGAEIACAEIABAGIgBAGIgCAFIgGADIgFABg");
	this.shape_12.setTransform(-68,69);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag7ByIAiiUIgYAAIAFgTIAXAAIAFgUQACgLAFgIQAEgHAFgFQAGgFAIgCQAIgCAIAAIAKAAIAJACIAGACIAFACIgLASIgIgEIgLgBQgJAAgHAFQgGAFgDAMIgEATIAfAAIgEATIgfAAIgiCUg");
	this.shape_13.setTransform(-75,71.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(1,1,1).p("A2PjWMAsfAAAIAAGtMgsfAAAg");
	this.shape_14.setTransform(15.4,69.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(-127.9,47.3,286.8,45), null);


(lib.doclogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Tween2("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(277,101.3,0.63,0.63,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.doclogo, new cjs.Rectangle(187.5,82.3,354.7,68), null);


(lib.bywhen = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shaker();
	this.instance.parent = this;
	this.instance.setTransform(86.3,22.4,1.112,1.112,0,0,0,86.3,22.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bywhen, new cjs.Rectangle(6,-85.8,183.1,87.9), null);


// stage content:
(lib._300x600_snow = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 8
	this.instance = new lib.cta();
	this.instance.parent = this;
	this.instance.setTransform(536.1,270.9,0.95,0.95,0,0,0,105.5,22.1);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(311).to({_off:false},0).wait(1).to({regX:15.4,regY:69.8,x:449,y:316.2},0).wait(1).to({x:443.3},0).wait(1).to({x:430.5},0).wait(1).to({x:404.1},0).wait(1).to({x:356.6},0).wait(1).to({x:305.8},0).wait(1).to({x:269.2},0).wait(1).to({x:243.2},0).wait(1).to({x:223.7},0).wait(1).to({x:208.6},0).wait(1).to({x:196.6},0).wait(1).to({x:186.8},0).wait(1).to({x:178.8},0).wait(1).to({x:172.2},0).wait(1).to({x:166.9},0).wait(1).to({x:162.5},0).wait(1).to({x:159},0).wait(1).to({x:156.2},0).wait(1).to({x:154},0).wait(1).to({x:152.4},0).wait(1).to({x:151.4},0).wait(1).to({x:150.7},0).wait(1).to({regX:105.5,regY:22.1,x:236.1,y:270.9},0).wait(27));

	// Layer 6
	this.instance_1 = new lib.doclogo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-339.8,195.2,0.8,0.8,0,0,0,143.1,30.2);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(311).to({_off:false},0).wait(1).to({regX:364.9,regY:116.3,x:-160.8,y:264.1},0).wait(1).to({x:-154.8},0).wait(1).to({x:-141.5},0).wait(1).to({x:-114.1},0).wait(1).to({x:-64.7},0).wait(1).to({x:-11.8},0).wait(1).to({x:26.3},0).wait(1).to({x:53.3},0).wait(1).to({x:73.5},0).wait(1).to({x:89.3},0).wait(1).to({x:101.8},0).wait(1).to({x:112},0).wait(1).to({x:120.3},0).wait(1).to({x:127.1},0).wait(1).to({x:132.7},0).wait(1).to({x:137.2},0).wait(1).to({x:140.9},0).wait(1).to({x:143.8},0).wait(1).to({x:146.1},0).wait(1).to({x:147.7},0).wait(1).to({x:148.8},0).wait(1).to({x:149.4},0).wait(1).to({regX:143.1,regY:30.2,x:-27.8,y:195.2},0).wait(27));

	// Layer 5
	this.instance_2 = new lib.Symbol3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(364,68,1,1,0,0,0,221.8,32.4);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(182).to({_off:false},0).wait(37).to({y:67},0).wait(1).to({regX:12.9,regY:245.1,x:155.1,y:279.4},0).wait(1).to({y:278.2},0).wait(1).to({y:274.9},0).wait(1).to({y:269.4},0).wait(1).to({y:265.7},0).wait(1).to({y:263.6},0).wait(1).to({y:262.3},0).wait(1).to({y:261.5},0).wait(1).to({y:261},0).wait(1).to({y:260.8},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:48},0).wait(75).to({regX:12.9,regY:245.1,x:155.1,y:261.5},0).wait(1).to({y:264.1},0).wait(1).to({y:269.1},0).wait(1).to({y:277.3},0).wait(1).to({y:290},0).wait(1).to({y:309.6},0).wait(1).to({y:340.9},0).wait(1).to({y:393.1},0).wait(1).to({y:466.4},0).wait(1).to({y:523.9},0).wait(1).to({y:559.2},0).wait(1).to({y:581.7},0).wait(1).to({y:596.7},0).wait(1).to({y:606.8},0).wait(1).to({y:613.6},0).wait(1).to({y:617.8},0).wait(1).to({y:620},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:408},0).to({_off:true},1).wait(38));

	// Layer 4
	this.instance_3 = new lib.bywhen();
	this.instance_3.parent = this;
	this.instance_3.setTransform(808.2,72.7,4.84,4.84,6,0,0,86.5,22.7);
	this.instance_3._off = true;

	this.instance_4 = new lib.Symbol5();
	this.instance_4.parent = this;
	this.instance_4.setTransform(364,60.8,1,1,0,0,0,221.8,17.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(93).to({_off:false},0).wait(1).to({regX:96.8,regY:-39.5,scaleX:4.76,scaleY:4.76,rotation:5.7,x:871.5,y:-214.8},0).wait(1).to({scaleX:4.52,scaleY:4.52,rotation:4.9,x:819.9,y:-195.7},0).wait(1).to({scaleX:4.15,scaleY:4.15,rotation:3.7,x:739.3,y:-165},0).wait(1).to({scaleX:3.67,scaleY:3.67,rotation:2,x:637.3,y:-125.2},0).wait(1).to({scaleX:3.12,scaleY:3.12,rotation:0.2,x:523.8,y:-79.5},0).wait(1).to({scaleX:2.56,scaleY:2.56,rotation:-1.7,x:410.1,y:-32.2},0).wait(1).to({scaleX:2.05,scaleY:2.05,rotation:-3.4,x:307.6,y:11.7},0).wait(1).to({scaleX:1.64,scaleY:1.64,rotation:-4.8,x:226.4,y:47.3},0).wait(1).to({scaleX:1.37,scaleY:1.37,rotation:-5.7,x:174,y:70.6},0).wait(1).to({regX:86.3,regY:22.7,scaleX:1.28,scaleY:1.28,rotation:-6,x:151,y:159.3},0).to({_off:true},79).wait(179));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(219).to({_off:false},0).to({alpha:1},16).wait(70).to({regX:9.2,regY:259.4,x:151.4,y:303.2},0).wait(1).to({y:305.8},0).wait(1).to({y:310.7},0).wait(1).to({y:318.7},0).wait(1).to({y:331.1},0).wait(1).to({y:350.3},0).wait(1).to({y:380.9},0).wait(1).to({y:431.9},0).wait(1).to({y:503.5},0).wait(1).to({y:559.8},0).wait(1).to({y:594.3},0).wait(1).to({y:616.3},0).wait(1).to({y:631},0).wait(1).to({y:640.9},0).wait(1).to({y:647.5},0).wait(1).to({y:651.6},0).wait(1).to({y:653.8},0).wait(1).to({regX:221.8,regY:17.7,x:364,y:412.8},0).to({_off:true},1).wait(38));

	// Layer 2
	this.instance_5 = new lib.Symbol1();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-200.6,49.8,1,1,0,0,0,136.3,32.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({regX:135.4,regY:220.3,x:-188.1,y:237.7},0).wait(1).to({x:-171.1},0).wait(1).to({x:-149.1},0).wait(1).to({x:-119.3},0).wait(1).to({x:-79},0).wait(1).to({x:-32.9},0).wait(1).to({x:6},0).wait(1).to({x:34.5},0).wait(1).to({x:55.8},0).wait(1).to({x:72.2},0).wait(1).to({x:85.2},0).wait(1).to({x:95.9},0).wait(1).to({x:104.8},0).wait(1).to({x:112.2},0).wait(1).to({x:118.5},0).wait(1).to({x:123.9},0).wait(1).to({x:128.4},0).wait(1).to({x:132.3},0).wait(1).to({x:135.6},0).wait(1).to({x:138.4},0).wait(1).to({x:140.8},0).wait(1).to({x:142.8},0).wait(1).to({x:144.4},0).wait(1).to({x:145.7},0).wait(1).to({x:146.8},0).wait(1).to({x:147.5},0).wait(1).to({x:148.1},0).wait(1).to({x:148.4},0).wait(1).to({regX:136.3,regY:32.4,x:149.4,y:49.8},0).wait(63).to({regX:135.4,regY:220.3,scaleX:1.01,scaleY:1.01,x:146.3,y:238},0).wait(1).to({scaleX:1.03,scaleY:1.03,x:139,y:239.2},0).wait(1).to({scaleX:1.08,scaleY:1.08,x:125,y:241.5},0).wait(1).to({scaleX:1.16,scaleY:1.16,x:101.7,y:245.3},0).wait(1).to({scaleX:1.29,scaleY:1.29,x:65.3,y:251.2},0).wait(1).to({scaleX:1.48,scaleY:1.48,x:10.5,y:260.1},0).wait(1).to({scaleX:1.74,scaleY:1.74,x:-67.1,y:272.6},0).wait(1).to({scaleX:2.06,scaleY:2.06,x:-159.5,y:287.6},0).wait(1).to({scaleX:2.35,scaleY:2.35,x:-243.9,y:301.3},0).wait(1).to({scaleX:2.58,scaleY:2.58,x:-308.5,y:311.7},0).wait(1).to({scaleX:2.74,scaleY:2.74,x:-355.5,y:319.4},0).wait(1).to({scaleX:2.86,scaleY:2.86,x:-389.5,y:324.9},0).wait(1).to({scaleX:2.94,scaleY:2.94,x:-414,y:328.8},0).wait(1).to({scaleX:3,scaleY:3,x:-431.5,y:331.6},0).wait(1).to({scaleX:3.04,scaleY:3.04,x:-443.5,y:333.6},0).wait(1).to({scaleX:3.07,scaleY:3.07,x:-451.2,y:334.8},0).wait(1).to({scaleX:3.08,scaleY:3.08,x:-455.4,y:335.5},0).wait(1).to({regX:136.2,regY:32.4,scaleX:3.09,scaleY:3.09,x:-454.1,y:-244.2},0).to({_off:true},163).wait(89));

	// Layer 3
	this.instance_6 = new lib.Symbol2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(539.9,459,0.835,0.835,0,0,0,112.2,112.8);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({regX:-355.8,regY:411.1,x:149.2,y:699.2},0).wait(1).to({y:688.2},0).wait(1).to({y:673.9},0).wait(1).to({y:654.5},0).wait(1).to({y:628.2},0).wait(1).to({y:598.2},0).wait(1).to({y:572.9},0).wait(1).to({y:554.2},0).wait(1).to({y:540.4},0).wait(1).to({y:529.7},0).wait(1).to({y:521.2},0).wait(1).to({y:514.3},0).wait(1).to({y:508.5},0).wait(1).to({y:503.6},0).wait(1).to({y:499.5},0).wait(1).to({y:496.1},0).wait(1).to({y:493.1},0).wait(1).to({y:490.5},0).wait(1).to({y:488.4},0).wait(1).to({y:486.5},0).wait(1).to({y:485},0).wait(1).to({y:483.7},0).wait(1).to({y:482.6},0).wait(1).to({y:481.8},0).wait(1).to({y:481.1},0).wait(1).to({y:480.6},0).wait(1).to({y:480.3},0).wait(1).to({y:480.1},0).wait(1).to({regX:112.2,regY:112.8,x:539.9,y:231},0).wait(63).to({regX:-355.8,regY:411.1,scaleX:0.84,scaleY:0.84,x:149.1,y:479.7},0).wait(1).to({scaleX:0.84,scaleY:0.84,x:148.9,y:478.7},0).wait(1).to({scaleX:0.86,scaleY:0.86,x:148.5,y:476.8},0).wait(1).to({scaleX:0.88,scaleY:0.88,x:147.9,y:473.6},0).wait(1).to({scaleX:0.91,scaleY:0.91,x:146.9,y:468.7},0).wait(1).to({scaleX:0.96,scaleY:0.96,x:145.4,y:461.4},0).wait(1).to({scaleX:1.03,scaleY:1.03,x:143.3,y:450.9},0).wait(1).to({scaleX:1.11,scaleY:1.11,x:140.8,y:438.5},0).wait(1).to({scaleX:1.19,scaleY:1.19,x:138.5,y:427.1},0).wait(1).to({scaleX:1.25,scaleY:1.25,x:136.8,y:418.3},0).wait(1).to({scaleX:1.29,scaleY:1.29,x:135.5,y:412},0).wait(1).to({scaleX:1.32,scaleY:1.32,x:134.6,y:407.4},0).wait(1).to({scaleX:1.34,scaleY:1.34,x:133.9,y:404.1},0).wait(1).to({scaleX:1.36,scaleY:1.36,x:133.4,y:401.7},0).wait(1).to({scaleX:1.37,scaleY:1.37,x:133.1,y:400.1},0).wait(1).to({scaleX:1.38,scaleY:1.38,x:132.9,y:399.1},0).wait(1).to({scaleX:1.38,scaleY:1.38,x:132.8,y:398.5},0).wait(1).to({regX:112.5,regY:112.5,scaleX:1.38,scaleY:1.38,x:779.2,y:-13.8},0).wait(1).to({regX:-355.8,regY:411.1,x:132.4,y:398.6},0).wait(1).to({x:132.5},0).wait(1).to({x:132.6},0).wait(1).to({x:132.7},0).wait(1).to({x:132.9},0).wait(1).to({x:133.2},0).wait(1).to({x:133.5},0).wait(1).to({x:133.8},0).wait(1).to({x:134.2},0).wait(1).to({x:134.4},0).wait(1).to({x:134.6},0).wait(1).to({x:134.7},0).wait(1).to({x:134.8},0).wait(1).to({regX:112.5,regY:112.5,x:781.6,y:-13.8},0).wait(1).to({regX:-355.8,regY:411.1,x:134.8,y:398.7},0).wait(2).to({y:398.8},0).wait(1).to({y:399},0).wait(1).to({y:399.1},0).wait(1).to({y:399.4},0).wait(1).to({y:399.7},0).wait(1).to({y:400.1},0).wait(1).to({y:400.6},0).wait(1).to({y:401.1},0).wait(1).to({y:401.6},0).wait(1).to({y:402.1},0).wait(1).to({y:402.5},0).wait(1).to({y:402.8},0).wait(1).to({y:403.1},0).wait(1).to({y:403.2},0).wait(1).to({y:403.4},0).wait(2).to({regX:112.5,regY:112.5,x:781.6,y:-9},0).wait(1).to({regX:-355.8,regY:411.1,x:134.8,y:403.4},0).wait(2).to({y:403.3},0).wait(1).to({x:134.7,y:403.2},0).wait(1).to({y:403.1},0).wait(1).to({x:134.6,y:402.9},0).wait(1).to({x:134.5,y:402.6},0).wait(1).to({x:134.4,y:402.3},0).wait(1).to({x:134.3,y:402},0).wait(1).to({x:134.2,y:401.6},0).wait(1).to({x:134.1,y:401.3},0).wait(1).to({x:133.9,y:400.9},0).wait(1).to({x:133.8,y:400.6},0).wait(1).to({y:400.3},0).wait(1).to({x:133.7,y:400.1},0).wait(1).to({y:400},0).wait(1).to({x:133.6,y:399.9},0).wait(2).to({regX:112.5,regY:112.5,x:780.4,y:-12.6},0).wait(1).to({regX:-355.8,regY:411.1,x:133.6,y:399.8},0).wait(3).to({x:133.7},0).wait(1).to({y:399.7},0).wait(1).to({x:133.8},0).wait(1).to({y:399.6},0).wait(1).to({x:133.9,y:399.5},0).wait(1).to({x:134,y:399.4},0).wait(1).to({x:134.1,y:399.3},0).wait(1).to({x:134.3,y:399.2},0).wait(1).to({x:134.4,y:399.1},0).wait(1).to({x:134.5,y:399},0).wait(1).to({x:134.6,y:398.9},0).wait(1).to({x:134.7,y:398.8},0).wait(1).to({y:398.7},0).wait(1).to({x:134.8},0).wait(3).to({regX:112.5,regY:112.5,x:781.6,y:-13.8},0).to({_off:true},1).wait(179));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#01C6AD").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape.setTransform(1,1,1,1,0,0,0,-149,-299);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(361));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-137.1,300,616.8,852.6);
// library properties:
lib.properties = {
	id: '3B7A4E1EAA3C4C4793A36D8DF72D359B',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/300x600_snow_atlas_.png", id:"300x600_snow_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['3B7A4E1EAA3C4C4793A36D8DF72D359B'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;