(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"300x250_space_atlas_", frames: [[0,252,300,250],[0,756,300,250],[0,504,300,250],[0,0,300,250],[302,0,99,58]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.bb_bg = function() {
	this.spriteSheet = ss["300x250_space_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.bb_black = function() {
	this.spriteSheet = ss["300x250_space_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.bb_panda = function() {
	this.spriteSheet = ss["300x250_space_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.bb_sunflare = function() {
	this.spriteSheet = ss["300x250_space_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.calzooLogo = function() {
	this.spriteSheet = ss["300x250_space_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.calzooLogo();
	this.instance.parent = this;
	this.instance.setTransform(67.9,-16.6,0.6,0.6);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgmAzQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAsAAQAPAAAKAKQAKAKAAAQQAAAOgKAKQgFAGgGACQgHADgHAAIgYAAIAAAcQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAgAgSABIATAAQAHAAAFgDQADgCABgDQABgDAAgEQAAgFgBgCQgBgDgDgDIgFgCIgHgBIgTAAg");
	this.shape.setTransform(24.1,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgIAzQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIARAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAABhQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_1.setTransform(16.6,-0.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAXAzQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgoIgpAAIAAAoQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgSAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIASAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAmIApAAIAAgmQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAABhQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_2.setTransform(8.8,-0.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgSAyQgJgDgIgGQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAIALgNQAAAAAAgBQABAAAAAAQAAAAABAAQAAAAABAAQAFAFAFACQAGACAGAAQAHAAADgDQAEgDAAgFQAAgHgIgDIgHgDIgIgCQgOgFgGgEQgEgEgCgFQgCgGAAgGQAAgGADgGQACgFAFgEQAFgDAHgCQAIgCAIgBQAPABAPAIQABABAAAAQAAAAAAABQABAAAAABQgBAAAAABIgJANQAAABgBAAQAAABAAAAQgBAAAAAAQgBgBAAAAQgKgGgJAAQgHAAgEACQgEACAAAEQAAAFAKAEIAJADIALADQALAFAFAGQAGAIAAALQAAANgLAIQgFAFgHACQgHADgIgBQgKAAgIgCg");
	this.shape_3.setTransform(-0.8,-0.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAQAzQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBgBAAIgQghIgPAAIAAAhQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgSAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAIAAhhQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAIAwAAQANAAAKAKQAEAEADAHQACAFAAAHQAAALgGAIQgGAJgKADIASAiIABACQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAgAgSgCIAXAAQAFgBAEgDQADgCABgDQABgCAAgEQAAgDgBgCQgBgDgDgCQgEgEgFABIgXAAg");
	this.shape_4.setTransform(-9.6,-0.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgkAzQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIBJAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAQQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIg1AAIAAAUIAtAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIAAAOQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgtAAIAAAWIA1AAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAABIAAAPQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAg");
	this.shape_5.setTransform(-19.1,-0.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgjAzQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAiAAQAKAAAJAFQAMAHAAAOQAAAQgNAFIAAABQALACAFAGQAFAHAAALQAAANgLAHQgKAHgOAAgAgPAfIAPAAQAGAAAEgBQAFgDAAgGQAAgMgTAAIgLAAgAgPgJIAFAAQARAAAAgMQAAgFgFgDQgCgCgEABIgLAAg");
	this.shape_6.setTransform(-28.4,-0.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAgAzQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAg7IgUAiIgBACIgOAAIgCgCIgUgiIAAA7QAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgRAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAhhQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIATAAIACACIAbAwIAcgwIACgCIATAAQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAABhQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_7.setTransform(-39.6,-0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgkAzQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIBJAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAQQAAAAAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIg1AAIAAAUIAtAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAOQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgtAAIAAAWIA1AAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIAAAPQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_8.setTransform(-50.1,-0.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAgAzQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAg7IgTAiIgCACIgOAAIgCgCIgVgiIAAA7QAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgRAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAhhQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIASAAIADACIAbAwIAcgwIACgCIATAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAABhQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_9.setTransform(-61.4,-0.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAZAzQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAIgGgSIgiAAIgGASQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAIgTAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAgBIAkhgQAAAAAAgBQABAAAAgBQAAAAAAAAQABAAAAAAIARAAQABAAAAAAQAAAAAAAAQABABAAAAQAAABAAAAIAkBhQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAgAgKALIAVAAIgLghg");
	this.shape_10.setTransform(-76.4,-0.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgIAzQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgtIgmgzIAAgCQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAXAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABIAUAgIAVggQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAIAWAAIACABIAAACIgmAzIAAAtQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_11.setTransform(-89.8,-0.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgRAxQgHgDgFgGIgGgGIgDgHQgDgIAAgJIAAg7QAAAAAAgBQAAAAABAAQAAgBAAAAQABAAABAAIASAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAA5QAAALAGAGQAEAGAJAAQAKAAAFgGQAFgGAAgLIAAg5QAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIASAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAA7QgBAMgCAFQgCAIgGAFQgGAGgHADQgIADgKAAQgLgBgGgCg");
	this.shape_12.setTransform(-99.7,-0.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgjAzQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAiAAQAKAAAJAFQAMAHAAAOQAAAQgNAFIAAABQALACAFAGQAFAHAAALQAAANgLAHQgKAHgOAAgAgPAfIAPAAQAGAAAEgBQAFgDAAgGQAAgMgTAAIgLAAgAgPgJIAFAAQARAAAAgMQAAgFgFgDQgCgCgEABIgLAAg");
	this.shape_13.setTransform(-109.2,-0.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(2,1,1).p("AtGiuIaNAAIAAFdI6NAAg");
	this.shape_14.setTransform(-43.3,-0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128.1,-19.2,255.4,37.4);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.calzooLogo();
	this.instance.parent = this;
	this.instance.setTransform(67.9,-16.6,0.6,0.6);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgmAzQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAsAAQAPAAAKAKQAKAKAAAQQAAAOgKAKQgFAGgGACQgHADgHAAIgYAAIAAAcQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAgAgSABIATAAQAHAAAFgDQADgCABgDQABgDAAgEQAAgFgBgCQgBgDgDgDIgFgCIgHgBIgTAAg");
	this.shape.setTransform(24.1,-0.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgIAzQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIARAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAABhQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_1.setTransform(16.6,-0.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAXAzQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgoIgpAAIAAAoQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgSAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIASAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAmIApAAIAAgmQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIASAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAABhQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_2.setTransform(8.8,-0.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgSAyQgJgDgIgGQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAIALgNQAAAAAAgBQABAAAAAAQAAAAABAAQAAAAABAAQAFAFAFACQAGACAGAAQAHAAADgDQAEgDAAgFQAAgHgIgDIgHgDIgIgCQgOgFgGgEQgEgEgCgFQgCgGAAgGQAAgGADgGQACgFAFgEQAFgDAHgCQAIgCAIgBQAPABAPAIQABABAAAAQAAAAAAABQABAAAAABQgBAAAAABIgJANQAAABgBAAQAAABAAAAQgBAAAAAAQgBgBAAAAQgKgGgJAAQgHAAgEACQgEACAAAEQAAAFAKAEIAJADIALADQALAFAFAGQAGAIAAALQAAANgLAIQgFAFgHACQgHADgIgBQgKAAgIgCg");
	this.shape_3.setTransform(-0.8,-0.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAQAzQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAgBgBAAIgQghIgPAAIAAAhQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAAAAAIgSAAQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAIAAhhQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAIAwAAQANAAAKAKQAEAEADAHQACAFAAAHQAAALgGAIQgGAJgKADIASAiIABACQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAgAgSgCIAXAAQAFgBAEgDQADgCABgDQABgCAAgEQAAgDgBgCQgBgDgDgCQgEgEgFABIgXAAg");
	this.shape_4.setTransform(-9.6,-0.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgkAzQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIBJAAQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAABIAAAQQAAAAAAAAQAAABAAAAQgBAAAAAAQAAABgBAAIg1AAIAAAUIAtAAQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAABIAAAOQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgtAAIAAAWIA1AAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAABIAAAPQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBAAg");
	this.shape_5.setTransform(-19.1,-0.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgjAzQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAiAAQAKAAAJAFQAMAHAAAOQAAAQgNAFIAAABQALACAFAGQAFAHAAALQAAANgLAHQgKAHgOAAgAgPAfIAPAAQAGAAAEgBQAFgDAAgGQAAgMgTAAIgLAAgAgPgJIAFAAQARAAAAgMQAAgFgFgDQgCgCgEABIgLAAg");
	this.shape_6.setTransform(-28.4,-0.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAgAzQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAg7IgUAiIgBACIgOAAIgCgCIgUgiIAAA7QAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAIgRAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAhhQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIATAAIACACIAbAwIAcgwIACgCIATAAQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAABhQAAAAgBABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_7.setTransform(-39.6,-0.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgkAzQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIBJAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAQQAAAAAAAAQAAABAAAAQAAAAgBAAQAAABgBAAIg1AAIAAAUIAtAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIAAAOQAAABAAAAQAAABAAAAQAAAAgBAAQAAAAgBAAIgtAAIAAAWIA1AAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAABIAAAPQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_8.setTransform(-50.1,-0.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAgAzQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAg7IgTAiIgCACIgOAAIgCgCIgVgiIAAA7QAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAIgRAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAhhQAAgBABAAQAAAAAAgBQAAAAABAAQAAAAABAAIASAAIADACIAbAwIAcgwIACgCIATAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAABhQAAAAAAABQAAAAAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_9.setTransform(-61.4,-0.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAZAzQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAIgGgSIgiAAIgGASQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAIgTAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAgBIAkhgQAAAAAAgBQABAAAAgBQAAAAAAAAQABAAAAAAIARAAQABAAAAAAQAAAAAAAAQABABAAAAQAAABAAAAIAkBhQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAgBAAgAgKALIAVAAIgLghg");
	this.shape_10.setTransform(-76.4,-0.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgIAzQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgtIgmgzIAAgCQAAAAAAAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAXAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABIAUAgIAVggQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAIAWAAIACABIAAACIgmAzIAAAtQAAAAAAABQgBAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_11.setTransform(-89.8,-0.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgRAxQgHgDgFgGIgGgGIgDgHQgDgIAAgJIAAg7QAAAAAAgBQAAAAABAAQAAgBAAAAQABAAABAAIASAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAA5QAAALAGAGQAEAGAJAAQAKAAAFgGQAFgGAAgLIAAg5QAAAAAAgBQAAAAABAAQAAgBAAAAQAAAAABAAIASAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAA7QgBAMgCAFQgCAIgGAFQgGAGgHADQgIADgKAAQgLgBgGgCg");
	this.shape_12.setTransform(-99.7,-0.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgjAzQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAhhQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAiAAQAKAAAJAFQAMAHAAAOQAAAQgNAFIAAABQALACAFAGQAFAHAAALQAAANgLAHQgKAHgOAAgAgPAfIAPAAQAGAAAEgBQAFgDAAgGQAAgMgTAAIgLAAgAgPgJIAFAAQARAAAAgMQAAgFgFgDQgCgCgEABIgLAAg");
	this.shape_13.setTransform(-109.2,-0.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(2,1,1).p("AtGiuIaNAAIAAFdI6NAAg");
	this.shape_14.setTransform(-43.3,-0.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-128.1,-19.2,255.4,37.4);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.bb_bg();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(0,0,300,250), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgQAlQgBAAgBAAQAAAAAAAAQgBAAABgBQAAAAAAgBIATgoIAKgSIgWAAIAAAJQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgKAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgVQAAAAAAgBQAAAAAAAAQABAAAAAAQABAAAAAAIAwAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAJIAAADIgbA7QAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape.setTransform(122.3,8.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgGAlQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgiIgbgkIgBgBIABgBIARAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABABAAIAOAYIAPgYQABAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIARAAIABABIAAAAIgcAlIAAAiQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_1.setTransform(112.7,8.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AATAlQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgEgOIgZAAIgEAOQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAIgOAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAABAAIAahHIACgBIAMAAIABABIAaBHQABAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAgAgHAJIAPAAIgIgZg");
	this.shape_2.setTransform(105.8,8.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAXAlQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgrIgPAZIgCABIgJAAIgCgBIgPgZIAAArQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAIgNAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAIAOAAIABABIAUAjIAVgjIABgBIAOAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAABHQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_3.setTransform(97.7,8.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgTAcQgMgLAAgRQAAgHADgHQADgGAGgGQAGgGAGgDQAHgCAHAAQAMAAAMAIQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAgBABIgHAKQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBgBIgHgDIgIgCQgIAAgGAHIgFAIQgCADAAAEQAAAFACAEIAFAIIAHAEQADACAEAAQAGAAAEgCIACgCIADgBQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIAHAKQABABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAQgKAJgOgBQgPABgLgLg");
	this.shape_4.setTransform(86.8,8.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgGAlQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIANAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAABHQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_5.setTransform(81.6,8.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUAlQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAhHQAAAAABgBQAAAAAAAAQAAAAAAAAQABAAAAAAIAOAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAA6IAaAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAALQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_6.setTransform(77.6,8.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgZAlQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIAZAAQAHgBAGAEQAJAFAAALQAAALgKAFQAJABADAEQAEAGAAAIQAAAJgJAGQgHAEgKAAgAgKAXIAKAAQAEAAAEgCQADgBAAgFQAAgJgOABIgHAAgAgKgHIADAAQAMABAAgKQAAgDgEgCIgEgBIgHAAg");
	this.shape_7.setTransform(71.4,8.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgMAkQgGgCgEgEIgDgFIgDgFQgCgFAAgIIAAgrQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIANAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAAqQAAAIADAFQAEADAGABQAHgBAEgDQADgFAAgIIAAgqQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIANAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAArQgBAKgBADQgCAGgEAEQgEAEgGACQgGACgHAAQgIgBgEgBg");
	this.shape_8.setTransform(64,8.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgcAlQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAgAAQALAAAIAHQAHAIAAALQAAAKgHAIQgEADgFACQgEACgGAAIgRAAIAAAVQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAgAgNABIAOAAQAFAAAEgCIACgEIABgFIgBgGIgCgDIgEgDIgFAAIgOAAg");
	this.shape_9.setTransform(56.8,8.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgOAkQgHgDgGgFQgGgGgDgGQgCgIAAgIQAAgIACgGQADgHAGgFQAMgLAPAAQAIAAAHACQAHADAGAGQAMALAAAPQAAARgMALQgMAKgQAAQgHABgHgDgAgPgPQgGAHAAAIQgBAFACAEIAFAIIAHAEQAEACAEAAQAFAAAEgCIAHgEQAGgIABgJQgBgEgBgDQgBgFgEgDQgHgHgJAAQgIAAgHAHg");
	this.shape_10.setTransform(45.7,8.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgFAlQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAg6IgTAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgLQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIA2AAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAALQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgUAAIAAA6QAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_11.setTransform(38.5,8.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AATAlIgCAAIghguIAAAtQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAIgMAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAMAAIACABIAhAtIAAgtQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAIAMAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAABHQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_12.setTransform(28.7,8.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgaAlQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAIA1AAQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAALQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAIgmAAIAAAPIAgAAQABAAAAABQAAAAAAAAQABAAAAAAQAAABAAAAIAAALQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAIggAAIAAAQIAmAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAALQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBAAg");
	this.shape_13.setTransform(21.6,8.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgcAlQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAgAAQALAAAIAHQAHAIAAALQAAAKgHAIQgEADgFACQgEACgGAAIgRAAIAAAVQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAgAgNABIAOAAQAFAAAEgCIACgEIABgFIgBgGIgCgDIgEgDIgFAAIgOAAg");
	this.shape_14.setTransform(14.6,8.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgOAkQgHgDgGgFQgFgGgDgGQgDgIAAgIQAAgIADgGQADgHAFgFQAMgLAPAAQAJAAAGACQAHADAGAGQAMALgBAPQABARgMALQgLAKgRAAQgHABgHgDgAgPgPQgHAHABAIQAAAFABAEIAFAIIAHAEQAEACAEAAQAFAAAEgCIAHgEQAHgIAAgJQAAgEgCgDQgBgFgEgDQgHgHgJAAQgIAAgHAHg");
	this.shape_15.setTransform(6.4,8.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 2
	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgQAlQgBAAgBAAQAAAAAAAAQgBAAABgBQAAAAAAgBIATgoIAKgSIgWAAIAAAJQAAABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgKAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAgVQAAAAAAgBQAAAAAAAAQABAAAAAAQABAAAAAAIAwAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAJIAAADIgbA7QAAAAAAABQgBAAAAAAQAAAAgBAAQAAAAgBAAg");
	this.shape_16.setTransform(122.3,9.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgGAlQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgiIgbgkIgBgCIABAAIARAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABABAAIAOAYIAPgYQABAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIARAAIABAAIAAABIgcAlIAAAiQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAg");
	this.shape_17.setTransform(112.7,9.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AATAlQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAAAIgEgNIgZAAIgEANQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAIgOAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAABAAIAahHIACgBIAMAAIABABIAaBHQABAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAgAgHAIIAPAAIgIgYg");
	this.shape_18.setTransform(105.8,9.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AAXAlQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgrIgPAZIgCABIgJAAIgCgBIgPgZIAAArQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAIgNAAQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAIAOAAIABABIAUAjIAVgjIABgBIAOAAQAAAAABAAQAAAAAAAAQABAAAAAAQAAABAAAAIAABHQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_19.setTransform(97.7,9.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgTAbQgMgLAAgQQAAgHADgHQADgGAGgGQAGgGAGgDQAHgCAHAAQAMgBAMAJQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAgBABIgHAKQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBgBIgHgDIgIgCQgIAAgGAHIgFAHQgCAEAAAEQAAAFACAEIAFAIIAHAEQADACAEAAQAGAAAEgCIACgCIADgBQABAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAAAIAHAKQABABAAAAQAAAAAAAAQAAABgBAAQAAAAAAAAQgKAIgOAAQgPAAgLgLg");
	this.shape_20.setTransform(86.8,9.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgGAlQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIANAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAABHQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_21.setTransform(81.6,9.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgUAlQAAAAgBAAQAAAAAAAAQAAAAAAAAQgBgBAAAAIAAhHQAAAAABgBQAAAAAAAAQAAAAAAAAQABAAAAAAIAOAAQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAA6IAaAAQAAAAABAAQAAAAAAAAQAAABAAAAQAAAAAAABIAAALQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_22.setTransform(77.6,9.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgZAlQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIAZAAQAHAAAGADQAJAFAAALQAAALgKAFQAJABADAFQAEAEAAAJQAAAJgJAGQgHAFgKgBgAgKAXIAKAAQAEAAAEgCQADgBAAgFQAAgIgOAAIgHAAgAgKgHIADAAQAMABAAgKQAAgDgEgCIgEgBIgHAAg");
	this.shape_23.setTransform(71.4,9.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgMAkQgGgDgEgDIgDgFIgDgFQgCgFAAgIIAAgqQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIANAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAApQAAAIADAFQAEADAGAAQAHAAAEgDQADgFAAgIIAAgpQAAgBAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIANAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAAqQgBAKgBADQgCAGgEAEQgEADgGADQgGACgHAAQgIgBgEgBg");
	this.shape_24.setTransform(64,9.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgcAlQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAgAAQALAAAIAHQAHAHAAAMQAAAKgHAIQgEADgFADQgEABgGAAIgRAAIAAAVQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAgAgNABIAOAAQAFAAAEgCIACgEIABgFIgBgGIgCgDIgEgCIgFgBIgOAAg");
	this.shape_25.setTransform(56.8,9.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgOAkQgHgDgGgGQgGgFgDgGQgCgIAAgIQAAgIACgGQADgHAGgGQAMgLAPABQAIgBAHADQAHADAGAFQAMALAAAQQAAARgMALQgMAKgQAAQgHAAgHgCgAgPgPQgGAGAAAJQgBAFACAEIAFAIIAHAEQAEACAEAAQAFAAAEgCIAHgEQAGgIABgJQgBgEgBgEQgBgEgEgDQgHgHgJAAQgIAAgHAHg");
	this.shape_26.setTransform(45.7,9.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AgFAlQgBAAAAAAQAAAAgBAAQAAAAAAAAQAAgBAAAAIAAg6IgTAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAgLQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAABAAIA2AAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAAALQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgUAAIAAA6QAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_27.setTransform(38.5,9.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AATAlIgCAAIghguIAAAtQAAAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAIgMAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAMAAIACAAIAhAuIAAgtQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAIAMAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABAAAAIAABHQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAg");
	this.shape_28.setTransform(28.7,9.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgaAlQgBAAAAAAQAAAAAAAAQgBAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAABAAQAAAAAAAAQAAAAABAAIA1AAQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAALQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAIgmAAIAAAPIAgAAQABAAAAABQAAAAAAAAQABAAAAAAQAAABAAAAIAAALQAAAAAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAIggAAIAAAQIAmAAQABAAAAAAQAAAAAAAAQABABAAAAQAAAAAAABIAAALQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAgBAAg");
	this.shape_29.setTransform(21.6,9.5);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgcAlQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAhHQAAAAAAgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAgAAQALAAAIAHQAHAHAAAMQAAAKgHAIQgEADgFADQgEABgGAAIgRAAIAAAVQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAgAgNABIAOAAQAFAAAEgCIACgEIABgFIgBgGIgCgDIgEgCIgFgBIgOAAg");
	this.shape_30.setTransform(14.6,9.5);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AgOAkQgHgDgGgGQgFgFgDgGQgDgIAAgIQAAgIADgGQADgHAFgGQAMgLAPABQAJgBAGADQAHADAGAFQAMALgBAQQABARgMALQgLAKgRAAQgHAAgHgCgAgPgPQgHAGABAJQAAAFABAEIAFAIIAHAEQAEACAEAAQAFAAAEgCIAHgEQAHgIAAgJQAAgEgCgEQgBgEgEgDQgHgHgJAAQgIAAgHAHg");
	this.shape_31.setTransform(6.4,9.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(0,0,127.9,17.9), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLBDQgFgEAAgHQAAgHAFgFQAFgFAGAAQAHAAAFAFQAEAFAAAHQAAAGgEAFQgFAGgHgBQgGABgFgGgAgFAYQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBgBgBIgHhZQAAAAAAgBQAAAAABgBQAAAAAAAAQABAAAAAAIAcAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIgIBZQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAg");
	this.shape.setTransform(160.1,39.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AghBIQgFAAACgGIAlhLIATgjIgqAAIAAARQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAIgUAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAgpQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIBcAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAAAIAAASQAAAEgCADIgzBvQgBAEgEAAg");
	this.shape_1.setTransform(150,39);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgsBJQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAgKQAAgKADgQIAFgJIAIgJQAHgHAQgIQAPgIAFgFQAEgDACgEQACgEAAgFQAAgIgFgEIgGgEQgEgCgFAAQgHAAgJAEQgHADgJAGQgDABgCgCIgIgRQAAgBAAAAQAAgBAAgBQAAAAAAgBQABAAAAgBQALgHAJgDIANgDQAHgBAHAAQALAAAJADQAJAEAGAHQAFAFADAHQACAHAAAIQAAALgDAHQgEAIgHAGIgLAJIgLAGQgOAIgFAEQgEAEgCAEQgCADAAAHIA7AAQABAAABAAQAAAAABAAQAAABABAAQAAABAAAAIAAAUQAAABAAABQgBAAAAABQgBAAAAAAQgBABgBAAg");
	this.shape_2.setTransform(137.4,38.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgnBIQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAiIQAAAAAAgBQABAAAAgBQAAAAABAAQAAAAABAAIAZAAQABAAABAAQAAAAAAAAQABABAAAAQAAABAAAAIAABwIAzAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAWQAAABAAABQgBAAAAABQAAAAgBAAQAAABgBAAg");
	this.shape_3.setTransform(121.2,39);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLBIQgBAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAgBIAAiIQAAAAABgBQAAAAAAgBQABAAAAAAQABAAABAAIAXAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAAAIAACIQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAg");
	this.shape_4.setTransform(112.1,39);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAXBIQgDAAgCgEIgXguIgWAAIAAAuQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIgaAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAiIQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIBFAAQASgBANAOQAGAHAEAIQADAJABAJQAAAPgJAMQgJAMgOAFIAaAvIABADQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAgbgEIAhAAQAHAAAGgFQAEgDABgEQACgDAAgFQAAgEgCgEQgBgDgEgEQgGgEgHAAIghAAg");
	this.shape_5.setTransform(102.4,39);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag1BIQgBAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAgBIAAiIQAAAAABgBQAAAAAAgBQABAAAAAAQABAAABAAIA+AAQATAAAPAOQAOAOAAAVQAAAVgOAOQgHAIgJAEQgIADgKAAIgiAAIAAAnQAAABgBABQAAAAAAABQgBAAAAAAQgBABAAAAgAgZABIAbAAQAJAAAIgEQADgDABgEQADgEAAgHQAAgFgDgFQgBgEgEgCQgDgEgFgBQgEgBgEAAIgbAAg");
	this.shape_6.setTransform(88.5,39);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAkBIQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIgIgZIgwAAIgJAZQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAIgbAAQgEAAACgEIAxiIQAAAAABgBQAAgBABAAQAAAAABgBQAAAAABAAIAYAAQABAAAAAAQAAABABAAQAAAAABABQAAABAAAAIAyCIQAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAgAgPAQIAfAAIgQgvg");
	this.shape_7.setTransform(74.5,39);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgMBIQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAgBIAAhvIglAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgXQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIBpAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAXQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIglAAIAABvQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAg");
	this.shape_8.setTransform(57,39);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAWBIQgDAAgBgEIgXguIgVAAIAAAuQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAIgZAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAgBIAAiIQAAAAABgBQAAAAAAgBQABAAAAAAQABAAAAAAIBEAAQATgBANAOQAHAHADAIQADAJAAAJQAAAPgIAMQgJAMgNAFIAZAvIABADQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAgagEIAgAAQAHAAAHgFQADgDABgEQACgDABgFQgBgEgCgEQgBgDgDgEQgHgEgHAAIggAAg");
	this.shape_9.setTransform(45.1,39);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAkBIQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIgIgZIgwAAIgJAZQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAIgbAAQgEAAACgEIAxiIQAAAAABgBQAAgBABAAQAAAAABgBQAAAAABAAIAYAAQABAAAAAAQAAABABAAQAAAAABABQAAABAAAAIAyCIQAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAgAgPAQIAfAAIgQgvg");
	this.shape_10.setTransform(31,39);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgLBIQgBAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAgBIAAhvIglAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBgBAAIAAgXQABAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIBoAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAXQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAgBAAIgkAAIAABvQAAABgBABQAAAAAAABQgBAAAAAAQgBABAAAAg");
	this.shape_11.setTransform(19.1,39);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgaBFQgNgEgLgIQAAgBgBAAQAAAAAAgBQAAgBAAAAQAAgBABAAIAOgSQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAABQAHAFAJADQAHADAJAAQAJAAAFgEQAGgEAAgHQAAgIgMgFIgKgEIgLgDQgUgHgIgHQgGgFgDgIQgCgHAAgJQAAgJADgHQAEgHAHgGQAHgFAKgDQALgCALAAQAVAAAWAMQABABAAAAQAAABAAAAQABABgBAAQAAABAAABIgNATQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQgOgJgNAAQgKAAgFADQgGACAAAGQAAAHAOAFIAOAFIANAFQAQAGAJAJQAHALABAPQAAATgQAMQgIAGgJADQgKADgLAAQgOAAgMgEg");
	this.shape_12.setTransform(7.9,39);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgaBFQgNgEgLgIQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIAPgSQAAgBABAAQAAgBABAAQABAAAAAAQABAAAAABQAHAFAJADQAHADAJAAQAJAAAFgEQAGgEAAgHQAAgIgMgFIgKgEIgLgDQgUgHgIgHQgGgFgDgIQgCgHAAgJQAAgJADgHQAEgHAHgGQAHgFAKgDQALgCALAAQAVAAAWAMQABABAAAAQAAABAAAAQABABgBAAQAAABAAABIgNATQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQgOgJgNAAQgKAAgFADQgGACABAGQgBAHAOAFIAOAFIANAFQAQAGAJAJQAHALABAPQAAATgQAMQgIAGgJADQgKADgLAAQgOAAgMgEg");
	this.shape_13.setTransform(179.4,14.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAdBIQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgahVIgaBVQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIghAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAgBgBIgriJQAAAAAAgBQAAgBAAAAQABAAAAgBQABAAABAAIAcAAQABAAAAAAQAAABAAAAQABAAAAABQAAABABAAIAcBlIAdhlQABAAAAgBQAAgBABAAQAAAAAAgBQABAAAAAAIAbAAQAAAAABAAQAAABAAAAQABAAAAABQAAABABAAIAcBlIAdhlQABAAAAgBQAAgBAAAAQABAAAAgBQAAAAABAAIAdAAQABAAAAABQABAAAAAAQAAABAAABQAAAAgBABIgrCIQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAg");
	this.shape_14.setTransform(162.8,14.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgzBHQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAiHQAAgBAAgBQABAAAAgBQAAAAABAAQAAAAABAAIBnAAQAAAAABAAQABAAAAAAQAAABABAAQAAABAAABIAAAVQAAABAAABQgBAAAAAAQAAABgBAAQgBAAAAAAIhLAAIAAAeIBAAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIAAAVQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIhAAAIAAAfIBLAAQAAAAABAAQABAAAAABQAAAAABAAQAAABAAABIAAAVQAAABAAABQgBAAAAABQAAAAgBAAQgBAAAAAAg");
	this.shape_15.setTransform(146.1,14.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgLBHQgBAAgBAAQAAAAgBAAQAAgBAAAAQgBgBAAgBIAAiHQAAgBABgBQAAAAAAgBQABAAAAAAQABAAABAAIAXAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAABIAACHQAAABgBABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_16.setTransform(135.9,14.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgOBIQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAgBgBIgxiJQgBgDAEAAIAcAAQAAAAABAAQAAABABAAQAAAAAAABQABABAAAAIAgBlIAhhlQABAAAAgBQAAgBABAAQAAAAAAgBQABAAAAAAIAcAAIADABIAAADIgyCIQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_17.setTransform(125.9,14.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgzBHQAAAAgBAAQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAiHQAAgBAAgBQABAAAAgBQAAAAABAAQABAAAAAAIBnAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIAAAVQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIhLAAIAAAeIBAAAQAAAAABAAQABAAAAAAQAAABABAAQAAABAAABIAAAVQAAAAAAABQgBAAAAABQAAAAgBAAQgBAAAAAAIhAAAIAAAfIBLAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAABIAAAVQAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_18.setTransform(113.3,14.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAXBHQgDAAgCgDIgXguIgWAAIAAAuQAAABAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgaAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAiHQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIBFAAQASAAANANQAHAHADAJQADAIABAKQAAAOgJAMQgJANgOAEIAaAvIABADQAAAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAgAgbgEIAhAAQAHAAAGgFQAEgCACgEQABgEAAgEQAAgFgBgDQgCgEgEgEQgGgEgHAAIghAAg");
	this.shape_19.setTransform(99.7,14.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag1BHQgBAAgBAAQAAAAgBAAQAAgBAAAAQgBgBAAgBIAAiHQAAgBABgBQAAAAAAgBQABAAAAAAQABAAABAAIA+AAQATAAAPAOQAOAOAAAVQAAAWgOANQgHAIgJADQgIAEgKAAIgiAAIAAAnQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAgAgZACIAaAAQAKAAAIgFQADgDABgEQADgFAAgGQAAgFgDgFQgBgEgEgDQgDgCgFgBQgEgCgFAAIgaAAg");
	this.shape_20.setTransform(85.8,14.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAkBIQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIgIgZIgwAAIgJAZQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAIgbAAQgEAAACgEIAxiIQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAIAYAAQABAAAAAAQAAABABAAQAAAAABABQAAAAAAABIAyCIQAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAgAgPAQIAfAAIgQgvg");
	this.shape_21.setTransform(66.3,14.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("Ag8BHQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAiHQAAgBAAgBQAAAAABgBQAAAAABAAQAAAAABAAIA4AAQAOgBANAGQAMAFAKALQATATAAAeQAAAPgFANQgGANgKAKQgKAKgNAGQgNAEgOAAgAggAsIAVAAQAKAAAGgDQAIgDAHgHQAMgNAAgSQAAgKgEgJQgDgJgJgGQgDgEgGgCIgLgDIgHAAIgMAAIgJAAg");
	this.shape_22.setTransform(52.6,14.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAkBHIgDgBIhBhZIAABXQAAABAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIgYAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAiHQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAYAAIACABIBABYIAAhWQAAgBABgBQAAAAAAgBQABAAAAAAQABAAABAAIAWAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAABIAACHQAAABgBABQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_23.setTransform(36.8,14.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAkBIQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIgIgZIgwAAIgJAZQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAIgbAAQgEAAACgEIAxiIQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAIAYAAQABAAAAAAQAAABABAAQAAAAABABQAAAAAAABIAyCIQAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAgAgPAQIAfAAIgQgvg");
	this.shape_24.setTransform(22.4,14.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("Ag1BHQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAiHQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAABAAIA+AAQATAAAPAOQAOAOAAAVQAAAWgOANQgHAIgJADQgIAEgKAAIgjAAIAAAnQAAABAAABQAAAAAAABQgBAAAAAAQgBAAAAAAgAgaACIAbAAQAKAAAHgFQAEgDACgEQACgFAAgGQAAgFgCgFQgCgEgEgDQgDgCgFgBQgEgCgFAAIgbAAg");
	this.shape_25.setTransform(9.4,14.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Layer 2
	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#000000").s().p("AgLBEQgFgFAAgHQAAgHAFgFQAFgFAGAAQAHAAAFAFQAEAFAAAHQAAAGgEAGQgFAEgHAAQgGAAgFgEgAgFAYQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBgBgBIgHhZQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAIAcAAQABAAABABQAAAAABAAQAAABAAAAQAAABAAAAIgIBZQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAg");
	this.shape_26.setTransform(160.1,40.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#000000").s().p("AghBIQgFAAACgGIAlhLIATgjIgqAAIAAARQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAIgUAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAgpQAAAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAIBcAAQABAAABABQAAAAABAAQAAABAAAAQABABAAAAIAAASQAAAEgCACIgzBxQgBADgEAAg");
	this.shape_27.setTransform(150,40);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#000000").s().p("AgsBJQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgLQAAgKADgPIAFgKIAIgJQAHgHAQgIQAPgIAFgFQAEgDACgEQACgEAAgFQAAgIgFgEIgGgEQgEgBgFAAQgHAAgJADQgHADgJAGQgDACgCgDIgIgRQAAgBAAAAQAAgBAAAAQAAgBAAAAQABgBAAgBQALgGAJgEIANgDQAHgCAHABQALAAAJADQAJAEAGAHQAFAFADAHQACAHAAAIQAAALgDAHQgEAJgHAFIgLAJIgLAGQgOAIgFAEQgEAEgCAEQgCAEAAAFIA7AAQABAAABABQAAAAABAAQAAABABAAQAAABAAAAIAAAVQAAAAAAABQgBAAAAABQgBAAAAAAQgBABgBAAg");
	this.shape_28.setTransform(137.4,39.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#000000").s().p("AgnBIQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAAAIAAiJQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBABAAIAZAAQABAAABABQAAAAAAAAQABABAAAAQAAABAAAAIAABwIAzAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIAAAXQAAAAAAABQgBAAAAABQAAAAgBAAQAAABgBAAg");
	this.shape_29.setTransform(121.2,40);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#000000").s().p("AgLBIQgBAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAAAIAAiJQAAAAABgBQAAAAAAgBQABAAAAAAQABgBABAAIAXAAQABAAABABQAAAAABAAQAAABAAAAQABABAAAAIAACJQAAAAgBABQAAAAAAABQgBAAAAAAQgBABgBAAg");
	this.shape_30.setTransform(112.1,40);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#000000").s().p("AAXBIQgDAAgCgDIgXgvIgWAAIAAAvQAAAAAAABQAAAAAAABQgBAAAAAAQgBABAAAAIgaAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAiJQAAAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAIBFAAQASABANAOQAGAGAEAIQADAJABAJQAAAPgJAMQgJAMgOAFIAaAvIABADQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAgbgEIAhAAQAHAAAGgFQAEgDABgEQACgDAAgFQAAgEgCgEQgBgDgEgDQgGgFgHAAIghAAg");
	this.shape_31.setTransform(102.4,40);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#000000").s().p("Ag1BIQgBAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAAAIAAiJQAAAAABgBQAAAAAAgBQABAAAAAAQABgBABAAIA+AAQATAAAPAPQAOAOAAAWQAAAUgOAPQgHAHgJAEQgIADgKAAIgiAAIAAAoQAAAAgBABQAAAAAAABQgBAAAAAAQgBABAAAAgAgZABIAbAAQAJAAAIgEQADgDABgEQADgEAAgGQAAgGgDgFQgBgEgEgCQgDgEgFgBQgEgBgEAAIgbAAg");
	this.shape_32.setTransform(88.5,40);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#000000").s().p("AAkBIQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIgIgZIgwAAIgJAZQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAIgbAAQgEAAACgEIAxiIQAAAAABgBQAAgBABAAQAAAAABgBQAAAAABAAIAYAAQABAAAAAAQAAABABAAQAAAAABABQAAABAAAAIAyCIQAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAgAgPAQIAfAAIgQgvg");
	this.shape_33.setTransform(74.5,40);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#000000").s().p("AgMBIQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAAAIAAhwIglAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgXQAAAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAIBpAAQAAAAABABQAAAAABAAQAAABAAAAQAAABAAAAIAAAXQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAAAAAIglAAIAABwQAAAAgBABQAAAAAAABQgBAAAAAAQgBABgBAAg");
	this.shape_34.setTransform(57,40);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#000000").s().p("AAWBIQgDAAgBgDIgXgvIgVAAIAAAvQAAAAgBABQAAAAAAABQgBAAAAAAQgBABgBAAIgZAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAAAIAAiJQAAAAABgBQAAAAAAgBQABAAAAAAQABgBAAAAIBEAAQATABANAOQAHAGADAIQADAJAAAJQAAAPgIAMQgJAMgNAFIAZAvIABADQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAgagEIAgAAQAHAAAHgFQADgDABgEQACgDABgFQgBgEgCgEQgBgDgDgDQgHgFgHAAIggAAg");
	this.shape_35.setTransform(45.1,40);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#000000").s().p("AAkBIQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIgIgZIgwAAIgJAZQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAIgbAAQgEAAACgEIAxiIQAAAAABgBQAAgBABAAQAAAAABgBQAAAAABAAIAYAAQABAAAAAAQAAABABAAQAAAAABABQAAABAAAAIAyCIQAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAgAgPAQIAfAAIgQgvg");
	this.shape_36.setTransform(31,40);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#000000").s().p("AgLBIQgBAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAAAIAAhwIglAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBgBAAIAAgXQABAAAAgBQAAAAAAgBQABAAAAAAQABgBAAAAIBoAAQABAAABABQAAAAABAAQAAABAAAAQAAABAAAAIAAAXQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAgBAAIgkAAIAABwQAAAAgBABQAAAAAAABQgBAAAAAAQgBABAAAAg");
	this.shape_37.setTransform(19.1,40);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#000000").s().p("AgaBFQgNgEgLgIQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAgBABAAIAOgSQAAgBABAAQAAgBABAAQAAAAABAAQABAAAAABQAHAFAJADQAHADAJAAQAJAAAFgEQAGgEAAgHQAAgIgMgFIgKgEIgLgDQgUgHgIgHQgGgFgDgIQgCgHAAgJQAAgJADgHQAEgHAHgGQAHgFAKgDQALgCALAAQAVAAAWAMQABABAAAAQAAABAAAAQABABgBAAQAAABAAABIgNATQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQgOgJgNAAQgKAAgFADQgGACAAAGQAAAHAOAFIAOAFIANAFQAQAGAJAJQAHALABAPQAAATgQAMQgIAGgJADQgKADgLAAQgOAAgMgEg");
	this.shape_38.setTransform(7.9,40);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#000000").s().p("AgaBFQgNgEgLgIQAAgBgBAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIAPgSQAAgBABAAQAAgBABAAQABAAAAAAQABAAAAABQAHAFAJADQAHADAJAAQAJAAAFgEQAGgEAAgHQAAgIgMgFIgKgEIgLgDQgUgHgIgHQgGgFgDgIQgCgHAAgJQAAgJADgHQAEgHAHgGQAHgFAKgDQALgCALAAQAVAAAWAMQABABAAAAQAAABAAAAQABABgBAAQAAABAAABIgNATQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQgOgJgNAAQgKAAgFADQgGACABAGQgBAHAOAFIAOAFIANAFQAQAGAJAJQAHALABAPQAAATgQAMQgIAGgJADQgKADgLAAQgOAAgMgEg");
	this.shape_39.setTransform(179.4,15.4);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#000000").s().p("AAdBIQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBIgahVIgaBVQAAABAAAAQAAABgBAAQAAAAAAABQgBAAAAAAIghAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAgBgBIgriJQAAAAAAgBQAAgBAAAAQABAAAAgBQABAAABAAIAcAAQABAAAAAAQAAABAAAAQABAAAAABQAAABABAAIAcBlIAdhlQABAAAAgBQAAgBABAAQAAAAAAgBQABAAAAAAIAbAAQAAAAABAAQAAABAAAAQABAAAAABQAAABABAAIAcBlIAdhlQABAAAAgBQAAgBAAAAQABAAAAgBQAAAAABAAIAdAAQABAAAAABQABAAAAAAQAAABAAABQAAAAgBABIgrCIQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAg");
	this.shape_40.setTransform(162.8,15.4);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#000000").s().p("AgzBIQgBAAAAgBQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAiHQAAgBAAgBQABAAAAgBQAAAAABAAQAAAAABAAIBnAAQAAAAABAAQABAAAAAAQAAABABAAQAAABAAABIAAAVQAAABAAABQgBAAAAAAQAAABgBAAQgBAAAAAAIhLAAIAAAdIBAAAQABABAAAAQABAAAAAAQAAABABAAQAAABAAABIAAAVQAAAAAAABQgBAAAAABQAAAAgBAAQAAAAgBAAIhAAAIAAAfIBLAAQAAAAABAAQABAAAAABQAAAAABAAQAAABAAABIAAAVQAAABAAABQgBAAAAABQAAAAgBAAQgBABAAAAg");
	this.shape_41.setTransform(146.1,15.4);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#000000").s().p("AgLBIQgBAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAgBIAAiHQAAgBABgBQAAAAAAgBQABAAAAAAQABAAABAAIAXAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAABIAACHQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAg");
	this.shape_42.setTransform(135.9,15.4);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#000000").s().p("AgOBIQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAgBgBIgxiJQgBgDAEAAIAcAAQAAAAABAAQAAABABAAQAAAAAAABQABABAAAAIAgBlIAhhlQABAAAAgBQAAgBABAAQAAAAAAgBQABAAAAAAIAcAAIADABIAAADIgyCIQAAABAAAAQgBABAAAAQAAAAgBABQAAAAgBAAg");
	this.shape_43.setTransform(125.9,15.4);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#000000").s().p("AgzBIQAAAAgBgBQgBAAAAAAQAAgBgBAAQAAgBAAgBIAAiHQAAgBAAgBQABAAAAgBQAAAAABAAQABAAAAAAIBnAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIAAAVQAAABAAABQgBAAAAAAQAAABgBAAQAAAAgBAAIhLAAIAAAdIBAAAQAAABABAAQABAAAAAAQAAABABAAQAAABAAABIAAAVQAAAAAAABQgBAAAAABQAAAAgBAAQgBAAAAAAIhAAAIAAAfIBLAAQABAAAAAAQABAAAAABQAAAAABAAQAAABAAABIAAAVQAAABAAABQgBAAAAABQAAAAgBAAQAAABgBAAg");
	this.shape_44.setTransform(113.3,15.4);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#000000").s().p("AAXBIQgDgBgCgDIgXguIgWAAIAAAuQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIgaAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAiHQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIBFAAQASAAANANQAHAHADAJQADAIABAKQAAAPgJALQgJAMgOAFIAaAvIABADQAAAAAAABQAAAAgBAAQAAAAgBAAQAAABgBAAgAgbgEIAhAAQAHAAAGgFQAEgCACgEQABgEAAgEQAAgFgBgEQgCgEgEgDQgGgEgHAAIghAAg");
	this.shape_45.setTransform(99.7,15.4);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#000000").s().p("Ag1BIQgBAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAgBIAAiHQAAgBABgBQAAAAAAgBQABAAAAAAQABAAABAAIA+AAQATAAAPAOQAOAOAAAVQAAAWgOANQgHAIgJADQgIAEgKAAIgiAAIAAAnQAAABgBABQAAAAAAABQgBAAAAAAQgBABAAAAgAgZACIAaAAQAKgBAIgEQADgDABgEQADgEAAgHQAAgFgDgFQgBgEgEgDQgDgDgFAAQgEgCgFAAIgaAAg");
	this.shape_46.setTransform(85.8,15.4);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#000000").s().p("AAkBIQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIgIgZIgwAAIgJAZQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAIgbAAQgEAAACgEIAxiIQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAIAYAAQABAAAAAAQAAABABAAQAAAAABABQAAAAAAABIAyCIQAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAgAgPAQIAfAAIgQgvg");
	this.shape_47.setTransform(66.3,15.4);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#000000").s().p("Ag8BIQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIAAiHQAAgBAAgBQAAAAABgBQAAAAABAAQAAAAABAAIA4AAQAOgBANAGQAMAFAKAKQATAUAAAeQAAAPgFANQgGAMgKALQgKAKgNAFQgNAFgOABgAggAtIAVAAQAKAAAGgEQAIgDAHgHQAMgNAAgSQAAgKgEgJQgDgJgJgGQgDgEgGgCIgLgDIgHAAIgMAAIgJAAg");
	this.shape_48.setTransform(52.6,15.4);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#000000").s().p("AAkBIIgDgCIhBhZIAABXQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIgYAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAiHQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAYAAIACABIBABYIAAhWQAAgBABgBQAAAAAAgBQABAAAAAAQABAAABAAIAWAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAABIAACHQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAg");
	this.shape_49.setTransform(36.8,15.4);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#000000").s().p("AAkBIQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAgBIgIgZIgwAAIgJAZQAAABAAABQgBAAAAABQAAAAgBABQAAAAgBAAIgbAAQgEAAACgEIAxiIQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAIAYAAQABAAAAAAQAAABABAAQAAAAABABQAAAAAAABIAyCIQAAABAAABQAAAAgBABQAAAAAAABQgBAAgBAAgAgPAQIAfAAIgQgvg");
	this.shape_50.setTransform(22.4,15.4);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#000000").s().p("Ag1BIQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAiHQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAABAAIA+AAQATAAAPAOQAOAOAAAVQAAAWgOANQgHAIgJADQgIAEgKAAIgjAAIAAAnQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAgAgaACIAbAAQAKgBAHgEQAEgDACgEQACgEAAgHQAAgFgCgFQgCgEgEgDQgDgDgFAAQgEgCgFAAIgbAAg");
	this.shape_51.setTransform(9.4,15.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,0,187.4,54.2), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLAMQgFgFgBgHQABgHAFgEQAFgGAGAAQAHAAAFAGQAGAEgBAHQABAHgGAFQgFAFgHAAQgGAAgFgFg");
	this.shape.setTransform(207.3,42.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZBCQgMgEgKgHQgBgBAAAAQgBgBAAAAQAAgBABAAQAAgBAAgBIAOgRQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAHAGAHACQAIADAHAAQAKAAAFgEQAFgDAAgIQAAgHgLgFIgKgDIgLgDQgTgIgHgGQgFgFgDgHQgDgGAAgKQAAgIAEgGQADgHAHgGQAHgEAJgDQAKgDALAAQAUAAAVAMQAAAAABABQAAAAAAABQAAAAAAABQAAABAAABIgMASQgBAAAAABQgBAAAAAAQgBAAgBAAQAAAAgBgBQgNgIgMAAQgJAAgGADQgFADAAAEQAAAHANAGIANAEIAOAFQAPAGAHAIQAIAKAAAOQAAASgPAMQgHAGgJADQgKADgKAAQgNAAgMgEg");
	this.shape_1.setTransform(199,37.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgZBCQgMgEgKgHQgBgBAAAAQgBgBAAAAQAAgBABAAQAAgBAAgBIAOgRQAAAAABgBQAAAAAAAAQABAAABAAQAAAAABAAQAHAGAHACQAIADAHAAQAKAAAFgEQAFgDAAgIQAAgHgLgFIgKgDIgLgDQgTgIgHgGQgFgFgDgHQgDgGAAgKQAAgIAEgGQADgHAHgGQAHgEAJgDQAKgDALAAQAUAAAVAMQAAAAABABQAAAAAAABQAAAAAAABQAAABAAABIgMASQgBAAAAABQgBAAAAAAQgBAAgBAAQAAAAgBgBQgNgIgMAAQgJAAgGADQgFADAAAEQAAAHANAGIANAEIAOAFQAPAGAHAIQAIAKAAAOQAAASgPAMQgHAGgJADQgKADgKAAQgNAAgMgEg");
	this.shape_2.setTransform(187.9,37.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgLBEQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAiBQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAXAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAACBQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_3.setTransform(179.3,37.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAqBEQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhOIgbAtIgDAEIgTAAIgDgEIgbgtIAABOQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAIgYAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAiBQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAAAIAaAAIACADIAlBAIAmhAIACgDIAaAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAACBQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_4.setTransform(167.9,37.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgLBEQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhqIgjAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAIAAgVQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIBjAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAVQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgjAAIAABqQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_5.setTransform(149.1,37.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMAdIgDgDQgBgBAAAAQAAgBAAAAQAAgBAAAAQABgBABAAQAGgEADgFQADgFAAgFQgIgBgEgDQgEgFAAgGQAAgIAFgFQAFgEAIAAQAJAAAFAGQADADABAEIABAKQAAAFgCAFQgCAFgEAGQgIALgMAEIgCAAIgBgBg");
	this.shape_6.setTransform(142,33.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAiBEIgCgBIg+hUIAABSQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgWAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAiBQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAWAAIADABIA9BUIAAhSQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAWAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAACBQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_7.setTransform(133,37.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAiBFQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAAAIgIgZIgtAAIgIAZQAAAAgBABQAAAAAAABQgBAAAAAAQgBABAAAAIgaAAQgEAAACgFIAviAQAAgBABgBQAAAAAAgBQABAAAAAAQABAAAAAAIAXAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIAvCBQABABAAABQAAAAgBABQAAAAAAAAQgBABgBAAgAgOAQIAdAAIgPgtg");
	this.shape_8.setTransform(119.3,37.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgkAyQgVgUAAgeQAAgOAGgMQAFgMAKgLQALgJAMgGQAMgFAOAAQAVAAAWAOQABAAAAABQAAAAAAABQABAAgBABQAAAAAAABIgNATQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBgBQgHgFgGgDQgHgCgHAAQgPAAgMANQgGAGgDAHQgDAIAAAHQAAAJADAHQADAIAGAFQAGAHAHACQAGAEAIAAQAKAAAHgEIAFgDIAFgDQABAAABAAQAAgBABABQAAAAABAAQAAAAAAABIANATQAAAAAAABQABAAgBABQAAAAAAABQAAAAgBAAQgSAPgZAAQgdAAgUgUg");
	this.shape_9.setTransform(106.9,37.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgLBEQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAhqIgjAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAIAAgVQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIBjAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAAAVQAAAAAAABQAAAAgBAAQAAABgBAAQAAAAgBAAIgjAAIAABqQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_10.setTransform(90,37.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgZBCQgMgEgKgHQgBgBAAAAQgBgBAAAAQAAgBABAAQAAgBAAgBIAOgRQAAAAABgBQAAAAABAAQAAAAABAAQAAAAABAAQAHAGAHACQAIADAHAAQAKAAAFgEQAFgDAAgIQAAgHgLgFIgKgDIgLgDQgTgIgHgGQgFgFgDgHQgDgGAAgKQAAgIAEgGQADgHAHgGQAHgEAJgDQAKgDALAAQAUAAAVAMQAAAAABABQAAAAAAABQAAAAAAABQAAABAAABIgMASQgBAAAAABQgBAAAAAAQgBAAgBAAQAAAAgBgBQgNgIgMAAQgJAAgGADQgFADAAAEQAAAHANAGIANAEIAOAFQAPAGAHAIQAIAKAAAOQAAASgPAMQgHAGgJADQgKADgKAAQgNAAgMgEg");
	this.shape_11.setTransform(79.3,37.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgWBBQgLgEgHgHIgGgIIgFgJQgEgLAAgNIAAhOQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABLQAAAQAGAHQAHAIAMAAQANAAAHgIQAGgHAAgQIAAhLQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABAAIAYAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABOQgBAQgDAIQgDAKgIAHQgHAHgKAEQgKAEgOAAQgQgBgGgDg");
	this.shape_12.setTransform(66.8,37.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgpA4QgDgCADgDIAOgOQAAAAABgBQAAAAABAAQAAAAABAAQAAABABAAQADAEAEABQAEABAEABQAKgBAGgGQAGgHAAgNIAAhSQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAXAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAABRQAAAOgEAJQgDAKgIAHQgOANgWAAQgVAAgMgNg");
	this.shape_13.setTransform(54.1,37.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgWBBQgLgEgHgHIgGgIIgFgJQgEgLAAgNIAAhOQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABLQAAAQAGAHQAHAIAMAAQANAAAHgIQAGgHAAgQIAAhLQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABAAIAYAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAABOQgBAQgDAIQgDAKgIAHQgHAHgKAEQgKAEgOAAQgQgBgGgDg");
	this.shape_14.setTransform(37.5,37.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgaBBQgNgFgKgKQgLgKgFgMQgGgNAAgPQAAgOAGgNQAFgNALgKQAVgTAcAAQAPAAAMAFQANAEAKAKQAWAVAAAdQAAAegWAUQgUAUgeAAQgOAAgMgFgAgcgcQgMAMAAAQQAAAJADAHQADAHAGAGQAGAHAHACQAIADAHAAQAJAAAHgDQAHgCAGgHQAMgMAAgRQAAgHgDgIQgDgIgGgFQgMgNgRAAQgQAAgMANg");
	this.shape_15.setTransform(22.6,37.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgLBEQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAg9IgyhDIgBgDQAAAAABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAfAAQADAAACADIAbArIAcgrQABgDAEAAIAeAAQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAIgBADIgyBDIAAA9QAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_16.setTransform(8.4,37.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgwBEQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAiBQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIBhAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAVQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAgBAAIhGAAIAAAcIA8AAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAAUQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIg8AAIAAAdIBGAAQABAAABABQAAAAABAAQAAABAAAAQAAABAAABIAAAUQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_17.setTransform(152.2,13.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgkAyQgVgUAAgeQAAgOAGgMQAFgMAKgLQALgJAMgGQAMgFAOAAQAVAAAWAOQABAAAAABQAAAAAAABQABAAgBABQAAAAAAABIgNATQAAABgBAAQAAABgBAAQAAAAgBAAQAAAAgBgBQgHgFgGgDQgHgCgHAAQgPAAgMANQgGAGgDAHQgDAIAAAHQAAAJADAHQADAIAGAFQAGAHAHACQAGAEAIAAQAKAAAHgEIAFgDIAFgDQABAAABAAQAAgBABABQAAAAABAAQAAAAAAABIANATQAAAAAAABQABAAgBABQAAAAAAABQAAAAgBABQgSAOgZAAQgdAAgUgUg");
	this.shape_18.setTransform(139.2,13.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAiBEIgCgBIg+hUIAABSQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAIgWAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAiBQAAgBAAAAQABgBAAAAQAAgBABAAQABAAAAAAIAWAAIADABIA9BUIAAhSQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIAWAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAACBQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_19.setTransform(125.3,13.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgwBEQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAiBQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIBhAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAAAVQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIhGAAIAAAcIA8AAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAAAUQAAABAAAAQgBABAAAAQAAAAgBAAQgBAAAAAAIg8AAIAAAdIBGAAQABAAABABQAAAAAAAAQABABAAAAQAAABAAABIAAAUQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_20.setTransform(112.3,13.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgLBEQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAiBQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABAAIAXAAQABAAAAAAQABAAAAABQABAAAAABQAAAAAAABIAACBQAAABAAAAQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_21.setTransform(102.6,13.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAWBEQgDAAgCgDIgWgsIgUAAIAAAsQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgYAAQAAAAgBAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAiBQAAgBAAAAQABgBAAAAQAAgBABAAQABAAAAAAIBBAAQASAAAMANQAGAHAEAHQADAJAAAIQAAAPgIALQgJAMgMAEIAYAtIABACQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgZgEIAgAAQAGAAAGgEIAFgHQABgDAAgFQAAgEgBgDQgCgEgDgCQgGgFgGAAIggAAg");
	this.shape_22.setTransform(93.3,13.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgwBEQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAiBQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIBhAAQABAAABAAQAAAAAAABQABAAAAABQAAAAAAABIAAAVQAAAAAAABQAAAAgBAAQAAABAAAAQgBAAgBAAIhGAAIAAAcIA8AAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAAAUQAAABAAAAQgBABAAAAQAAAAgBAAQgBAAAAAAIg8AAIAAAdIBGAAQABAAABABQAAAAAAAAQABABAAAAQAAABAAABIAAAUQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_23.setTransform(80.6,13.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgzBEQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAiBQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIA7AAQAUAAANAOQAOANAAAVQAAATgOAOQgHAGgIAEQgIADgKABIggAAIAAAlQAAABAAAAQAAABgBAAQAAABAAAAQgBAAgBAAgAgYABIAaAAQAJAAAHgEQADgDACgEQABgEAAgFQAAgGgBgEIgFgHIgIgEIgIgBIgaAAg");
	this.shape_24.setTransform(67.7,13.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAkBEQgDAAgCgDIgfgqIgdAqQgDADgDAAIgfAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIABgCIAzg/IgyhAIgBgDIACgBIAfAAQADAAACAEIAdApIAdgpQACgEADAAIAhAAQADAAgCAEIgzA/IA0BAIABACQgBABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_25.setTransform(53.8,13.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgwBEQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAiBQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAABAAIBhAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAVQAAAAAAABQAAAAAAAAQgBABAAAAQgBAAgBAAIhGAAIAAAcIA8AAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAAUQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIg8AAIAAAdIBGAAQABAAABABQAAAAABAAQAAABAAAAQAAABAAABIAAAUQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_26.setTransform(41.4,13.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAiBEIgCgBIg+hUIAABSQAAABAAAAQAAABAAAAQgBABAAAAQgBAAgBAAIgWAAQgBAAAAAAQgBAAAAgBQAAAAgBgBQAAAAAAgBIAAiBQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAWAAIADABIA9BUIAAhSQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAWAAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAACBQAAABAAAAQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_27.setTransform(22,13.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAiBFQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAAAIgIgZIgtAAIgIAZQAAAAgBABQAAAAAAABQgBAAAAAAQgBABAAAAIgaAAQgEAAACgFIAviAQAAgBABgBQAAAAAAgBQABAAAAAAQABAAAAAAIAXAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAABIAvCBQABABAAABQAAAAgBABQAAAAAAAAQgBABgBAAgAgOAQIAdAAIgPgtg");
	this.shape_28.setTransform(8.3,13.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(0,0,212.2,50.8), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.bb_sunflare();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,300,250), null);


(lib.panduh = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.bb_panda();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.panduh, new cjs.Rectangle(0,0,300,250), null);


(lib.black = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.bb_black();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.black, new cjs.Rectangle(0,0,300,250), null);


// stage content:
(lib._300x250_space = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 8
	this.instance = new lib.Tween1("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(145.2,227.6);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.instance_1 = new lib.Tween2("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(145.2,217.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance}]},163).to({state:[{t:this.instance_1}]},33).wait(50));
	this.timeline.addTween(cjs.Tween.get(this.instance).wait(163).to({_off:false},0).to({_off:true,y:217.6,alpha:1},33,cjs.Ease.get(1)).wait(50));

	// Layer 7
	this.instance_2 = new lib.Symbol4();
	this.instance_2.parent = this;
	this.instance_2.setTransform(78.9,73.9,1,1,0,0,0,63.9,8.4);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(142).to({_off:false},0).to({alpha:1},20,cjs.Ease.get(-0.99)).wait(84));

	// Layer 6
	this.instance_3 = new lib.Symbol2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(122,35.8,1,1,0,0,0,106,25.4);
	this.instance_3.alpha = 0;

	this.instance_4 = new lib.Symbol3();
	this.instance_4.parent = this;
	this.instance_4.setTransform(108.7,36.1,1,1,0,0,0,93.7,26.6);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({alpha:1},25,cjs.Ease.get(-1)).wait(76).to({alpha:0},23,cjs.Ease.get(1)).to({_off:true},1).wait(121));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(125).to({_off:false},0).to({alpha:1},25,cjs.Ease.get(-1)).wait(96));

	// blok
	this.instance_5 = new lib.black();
	this.instance_5.parent = this;
	this.instance_5.setTransform(181,213,1,1,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(1).to({x:180.9,y:212.8},0).wait(1).to({y:212.6},0).wait(1).to({x:180.8,y:212.4},0).wait(1).to({x:180.7,y:212.2},0).wait(1).to({x:180.6,y:211.9},0).wait(1).to({x:180.5,y:211.6},0).wait(1).to({x:180.4,y:211.3},0).wait(1).to({x:180.3,y:211},0).wait(1).to({x:180.1,y:210.7},0).wait(1).to({x:180,y:210.3},0).wait(1).to({x:179.8,y:209.9},0).wait(1).to({x:179.7,y:209.5},0).wait(1).to({x:179.5,y:209},0).wait(1).to({x:179.4,y:208.6},0).wait(1).to({x:179.2,y:208.1},0).wait(1).to({x:179,y:207.6},0).wait(1).to({x:178.8,y:207.1},0).wait(1).to({x:178.6,y:206.5},0).wait(1).to({x:178.4,y:205.9},0).wait(1).to({x:178.1,y:205.3},0).wait(1).to({x:177.9,y:204.7},0).wait(1).to({x:177.6,y:204},0).wait(1).to({x:177.4,y:203.3},0).wait(1).to({x:177.1,y:202.6},0).wait(1).to({x:176.9,y:201.9},0).wait(1).to({x:176.6,y:201.1,alpha:0.988},0).wait(1).to({x:176.3,y:200.3,alpha:0.976},0).wait(1).to({x:176,y:199.5,alpha:0.964},0).wait(1).to({x:175.7,y:198.7,alpha:0.952},0).wait(1).to({x:175.3,y:197.8,alpha:0.939},0).wait(1).to({x:175,y:196.9,alpha:0.925},0).wait(1).to({x:174.7,y:196.1,alpha:0.912},0).wait(1).to({x:174.3,y:195.2,alpha:0.898},0).wait(1).to({x:174,y:194.2,alpha:0.884},0).wait(1).to({x:173.6,y:193.3,alpha:0.87},0).wait(1).to({x:173.3,y:192.4,alpha:0.855},0).wait(1).to({x:172.9,y:191.4,alpha:0.841},0).wait(1).to({x:172.6,y:190.4,alpha:0.826},0).wait(1).to({x:172.2,y:189.4,alpha:0.811},0).wait(1).to({x:171.8,y:188.5,alpha:0.796},0).wait(1).to({x:171.4,y:187.5,alpha:0.781},0).wait(1).to({x:171.1,y:186.5,alpha:0.766},0).wait(1).to({x:170.7,y:185.5,alpha:0.751},0).wait(1).to({x:170.3,y:184.5,alpha:0.736},0).wait(1).to({x:170,y:183.5,alpha:0.721},0).wait(1).to({x:169.6,y:182.5,alpha:0.706},0).wait(1).to({x:169.2,y:181.5,alpha:0.691},0).wait(1).to({x:168.8,y:180.6,alpha:0.676},0).wait(1).to({x:168.5,y:179.6,alpha:0.661},0).wait(1).to({x:168.1,y:178.6,alpha:0.647},0).wait(1).to({x:167.8,y:177.7,alpha:0.632},0).wait(1).to({x:167.4,y:176.7,alpha:0.618},0).wait(1).to({x:167.1,y:175.8,alpha:0.604},0).wait(1).to({x:166.7,y:174.9,alpha:0.59},0).wait(1).to({x:166.4,y:174,alpha:0.576},0).wait(1).to({x:166,y:173.1,alpha:0.562},0).wait(1).to({x:165.7,y:172.2,alpha:0.549},0).wait(1).to({x:165.4,y:171.3,alpha:0.535},0).wait(1).to({x:165,y:170.5,alpha:0.522},0).wait(1).to({x:164.7,y:169.6,alpha:0.509},0).wait(1).to({x:164.4,y:168.8,alpha:0.497},0).wait(1).to({x:164.1,y:168,alpha:0.484},0).wait(1).to({x:163.8,y:167.2,alpha:0.472},0).wait(1).to({x:163.5,y:166.4,alpha:0.46},0).wait(1).to({x:163.2,y:165.6,alpha:0.448},0).wait(1).to({x:162.9,y:164.8,alpha:0.436},0).wait(1).to({x:162.6,y:164.1,alpha:0.425},0).wait(1).to({x:162.4,y:163.3,alpha:0.414},0).wait(1).to({x:162.1,y:162.6,alpha:0.403},0).wait(1).to({x:161.8,y:161.9,alpha:0.392},0).wait(1).to({x:161.6,y:161.2,alpha:0.381},0).wait(1).to({x:161.3,y:160.5,alpha:0.371},0).wait(1).to({x:161.1,y:159.8,alpha:0.361},0).wait(1).to({x:160.8,y:159.2,alpha:0.351},0).wait(1).to({x:160.6,y:158.5,alpha:0.341},0).wait(1).to({x:160.3,y:157.9,alpha:0.331},0).wait(1).to({x:160.1,y:157.3,alpha:0.322},0).wait(1).to({x:159.9,y:156.7,alpha:0.313},0).wait(1).to({x:159.6,y:156.1,alpha:0.304},0).wait(1).to({x:159.4,y:155.5,alpha:0.295},0).wait(1).to({x:159.2,y:154.9,alpha:0.286},0).wait(1).to({x:159,y:154.4,alpha:0.277},0).wait(1).to({x:158.8,y:153.8,alpha:0.269},0).wait(1).to({x:158.6,y:153.3,alpha:0.261},0).wait(1).to({x:158.4,y:152.8,alpha:0.253},0).wait(1).to({x:158.2,y:152.2,alpha:0.245},0).wait(1).to({x:158,y:151.7,alpha:0.237},0).wait(1).to({x:157.8,y:151.2,alpha:0.23},0).wait(1).to({x:157.6,y:150.8,alpha:0.222},0).wait(1).to({x:157.5,y:150.3,alpha:0.215},0).wait(1).to({x:157.3,y:149.8,alpha:0.208},0).wait(1).to({x:157.1,y:149.4,alpha:0.201},0).wait(1).to({x:156.9,y:148.9,alpha:0.194},0).wait(1).to({x:156.8,y:148.5,alpha:0.188},0).wait(1).to({x:156.6,y:148,alpha:0.181},0).wait(1).to({x:156.5,y:147.6,alpha:0.175},0).wait(1).to({x:156.3,y:147.2,alpha:0.168},0).wait(1).to({x:156.2,y:146.8,alpha:0.162},0).wait(1).to({x:156,y:146.4,alpha:0.156},0).wait(1).to({x:155.9,y:146,alpha:0.15},0).wait(1).to({x:155.7,y:145.7,alpha:0.145},0).wait(1).to({x:155.6,y:145.3,alpha:0.139},0).wait(1).to({x:155.4,y:144.9,alpha:0.134},0).wait(1).to({x:155.3,y:144.6,alpha:0.128},0).wait(1).to({x:155.2,y:144.2,alpha:0.123},0).wait(1).to({x:155.1,y:143.9,alpha:0.118},0).wait(1).to({x:154.9,y:143.6,alpha:0.113},0).wait(1).to({x:154.8,y:143.2,alpha:0.108},0).wait(1).to({x:154.7,y:142.9,alpha:0.103},0).wait(1).to({x:154.6,y:142.6,alpha:0.098},0).wait(1).to({x:154.5,y:142.3,alpha:0.094},0).wait(1).to({x:154.3,y:142,alpha:0.089},0).wait(1).to({x:154.2,y:141.7,alpha:0.085},0).wait(1).to({x:154.1,y:141.4,alpha:0.08},0).wait(1).to({x:154,y:141.1,alpha:0.076},0).wait(1).to({x:153.9,y:140.9,alpha:0.072},0).wait(1).to({x:153.8,y:140.6,alpha:0.068},0).wait(1).to({x:153.7,y:140.4,alpha:0.064},0).wait(1).to({x:153.6,y:140.1,alpha:0.06},0).wait(1).to({x:153.5,y:139.9,alpha:0.056},0).wait(1).to({y:139.6,alpha:0.053},0).wait(1).to({x:153.4,y:139.4,alpha:0.049},0).wait(1).to({x:153.3,y:139.1,alpha:0.046},0).wait(1).to({x:153.2,y:138.9,alpha:0.042},0).wait(1).to({x:153.1,y:138.7,alpha:0.039},0).wait(1).to({x:153,y:138.5,alpha:0.036},0).wait(1).to({x:152.9,y:138.3,alpha:0.032},0).wait(1).to({y:138.1,alpha:0.029},0).wait(1).to({x:152.8,y:137.9,alpha:0.026},0).wait(1).to({x:152.7,y:137.7,alpha:0.023},0).wait(1).to({y:137.5,alpha:0.02},0).wait(1).to({x:152.6,y:137.3,alpha:0.018},0).wait(1).to({x:152.5,y:137.1,alpha:0.015},0).wait(1).to({y:137,alpha:0.012},0).wait(1).to({x:152.4,y:136.8,alpha:0.01},0).wait(1).to({x:152.3,y:136.6,alpha:0.007},0).wait(1).to({y:136.5,alpha:0.005},0).wait(1).to({x:152.2,y:136.3,alpha:0.002},0).wait(1).to({y:136.2,alpha:0},0).to({_off:true},46).wait(61));

	// panda
	this.instance_6 = new lib.panduh();
	this.instance_6.parent = this;
	this.instance_6.setTransform(180,231,1,1,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(1).to({x:179.9,y:230.8},0).wait(1).to({y:230.6},0).wait(1).to({x:179.8,y:230.3},0).wait(1).to({x:179.7,y:230.1},0).wait(1).to({x:179.6,y:229.8},0).wait(1).to({x:179.5,y:229.4},0).wait(1).to({x:179.4,y:229.1},0).wait(1).to({x:179.2,y:228.7},0).wait(1).to({x:179.1,y:228.4},0).wait(1).to({x:179,y:228},0).wait(1).to({x:178.8,y:227.5},0).wait(1).to({x:178.7,y:227.1},0).wait(1).to({x:178.5,y:226.6},0).wait(1).to({x:178.3,y:226},0).wait(1).to({x:178.2,y:225.5},0).wait(1).to({x:178,y:224.9},0).wait(1).to({x:177.8,y:224.3},0).wait(1).to({x:177.6,y:223.7},0).wait(1).to({x:177.3,y:223},0).wait(1).to({x:177.1,y:222.3},0).wait(1).to({x:176.9,y:221.6},0).wait(1).to({x:176.6,y:220.9},0).wait(1).to({x:176.4,y:220.1},0).wait(1).to({x:176.1,y:219.3},0).wait(1).to({x:175.8,y:218.5},0).wait(1).to({x:175.5,y:217.6},0).wait(1).to({x:175.2,y:216.7},0).wait(1).to({x:174.9,y:215.8},0).wait(1).to({x:174.6,y:214.9},0).wait(1).to({x:174.3,y:213.9},0).wait(1).to({x:174,y:213},0).wait(1).to({x:173.7,y:212},0).wait(1).to({x:173.3,y:210.9},0).wait(1).to({x:173,y:209.9},0).wait(1).to({x:172.6,y:208.9},0).wait(1).to({x:172.3,y:207.8},0).wait(1).to({x:171.9,y:206.7},0).wait(1).to({x:171.5,y:205.6},0).wait(1).to({x:171.2,y:204.5},0).wait(1).to({x:170.8,y:203.4},0).wait(1).to({x:170.4,y:202.3},0).wait(1).to({x:170.1,y:201.2},0).wait(1).to({x:169.7,y:200.1},0).wait(1).to({x:169.3,y:199},0).wait(1).to({x:168.9,y:197.8},0).wait(1).to({x:168.6,y:196.7},0).wait(1).to({x:168.2,y:195.6},0).wait(1).to({x:167.8,y:194.5},0).wait(1).to({x:167.5,y:193.4},0).wait(1).to({x:167.1,y:192.4},0).wait(1).to({x:166.8,y:191.3},0).wait(1).to({x:166.4,y:190.2},0).wait(1).to({x:166.1,y:189.2},0).wait(1).to({x:165.7,y:188.1},0).wait(1).to({x:165.4,y:187.1},0).wait(1).to({x:165,y:186.1},0).wait(1).to({x:164.7,y:185.1},0).wait(1).to({x:164.4,y:184.1},0).wait(1).to({x:164,y:183.1},0).wait(1).to({x:163.7,y:182.2},0).wait(1).to({x:163.4,y:181.2},0).wait(1).to({x:163.1,y:180.3},0).wait(1).to({x:162.8,y:179.4},0).wait(1).to({x:162.5,y:178.5},0).wait(1).to({x:162.2,y:177.7},0).wait(1).to({x:161.9,y:176.8},0).wait(1).to({x:161.6,y:175.9},0).wait(1).to({x:161.4,y:175.1},0).wait(1).to({x:161.1,y:174.3},0).wait(1).to({x:160.8,y:173.5},0).wait(1).to({x:160.6,y:172.7},0).wait(1).to({x:160.3,y:171.9},0).wait(1).to({x:160.1,y:171.2},0).wait(1).to({x:159.8,y:170.5},0).wait(1).to({x:159.6,y:169.7},0).wait(1).to({x:159.3,y:169},0).wait(1).to({x:159.1,y:168.3},0).wait(1).to({x:158.9,y:167.6},0).wait(1).to({x:158.7,y:167},0).wait(1).to({x:158.4,y:166.3},0).wait(1).to({x:158.2,y:165.7},0).wait(1).to({x:158,y:165},0).wait(1).to({x:157.8,y:164.4},0).wait(1).to({x:157.6,y:163.8},0).wait(1).to({x:157.4,y:163.2},0).wait(1).to({x:157.2,y:162.6},0).wait(1).to({x:157,y:162.1},0).wait(1).to({x:156.8,y:161.5},0).wait(1).to({x:156.7,y:161},0).wait(1).to({x:156.5,y:160.4},0).wait(1).to({x:156.3,y:159.9},0).wait(1).to({x:156.1,y:159.4},0).wait(1).to({x:156,y:158.9},0).wait(1).to({x:155.8,y:158.4},0).wait(1).to({x:155.6,y:157.9},0).wait(1).to({x:155.5,y:157.4},0).wait(1).to({x:155.3,y:157},0).wait(1).to({x:155.2,y:156.5},0).wait(1).to({x:155,y:156.1},0).wait(1).to({x:154.9,y:155.6},0).wait(1).to({x:154.7,y:155.2},0).wait(1).to({x:154.6,y:154.8},0).wait(1).to({x:154.5,y:154.4},0).wait(1).to({x:154.3,y:154},0).wait(1).to({x:154.2,y:153.6},0).wait(1).to({x:154.1,y:153.2},0).wait(1).to({x:154,y:152.9},0).wait(1).to({x:153.8,y:152.5},0).wait(1).to({x:153.7,y:152.1},0).wait(1).to({x:153.6,y:151.8},0).wait(1).to({x:153.5,y:151.4},0).wait(1).to({x:153.4,y:151.1},0).wait(1).to({x:153.3,y:150.8},0).wait(1).to({x:153.2,y:150.5},0).wait(1).to({x:153,y:150.1},0).wait(1).to({x:152.9,y:149.8},0).wait(1).to({x:152.8,y:149.5},0).wait(1).to({x:152.7,y:149.2},0).wait(1).to({y:149},0).wait(1).to({x:152.6,y:148.7},0).wait(1).to({x:152.5,y:148.4},0).wait(1).to({x:152.4,y:148.1},0).wait(1).to({x:152.3,y:147.9},0).wait(1).to({x:152.2,y:147.6},0).wait(1).to({x:152.1,y:147.4},0).wait(1).to({x:152,y:147.1},0).wait(1).to({y:146.9},0).wait(1).to({x:151.9,y:146.7},0).wait(1).to({x:151.8,y:146.5},0).wait(1).to({x:151.7,y:146.2},0).wait(1).to({y:146},0).wait(1).to({x:151.6,y:145.8},0).wait(1).to({x:151.5,y:145.6},0).wait(1).to({y:145.4},0).wait(1).to({x:151.4,y:145.2},0).wait(1).to({x:151.3,y:145},0).wait(1).to({y:144.9},0).wait(1).to({x:151.2,y:144.7},0).wait(1).to({y:144.5},0).wait(1).to({x:151.1,y:144.4},0).wait(1).to({y:144.2},0).wait(1).to({x:151,y:144},0).wait(1).to({y:143.9},0).wait(1).to({x:150.9,y:143.7},0).wait(1).to({y:143.6},0).wait(1).to({x:150.8,y:143.5},0).wait(1).to({y:143.3},0).wait(1).to({x:150.7,y:143.2},0).wait(1).to({y:143.1},0).wait(1).to({x:150.6,y:142.9},0).wait(1).to({y:142.8},0).wait(1).to({y:142.7},0).wait(1).to({x:150.5,y:142.6},0).wait(1).to({y:142.5},0).wait(1).to({y:142.4},0).wait(1).to({x:150.4,y:142.3},0).wait(1).to({y:142.2},0).wait(1).to({y:142.1},0).wait(1).to({x:150.3,y:142},0).wait(2).to({y:141.9},0).wait(1).to({y:141.8},0).wait(1).to({x:150.2,y:141.7},0).wait(2).to({y:141.6},0).wait(1).to({y:141.5},0).wait(2).to({x:150.1,y:141.4},0).wait(2).to({y:141.3},0).wait(2).to({y:141.2},0).wait(3).to({x:150,y:141.1},0).wait(5).to({y:141},0).wait(66));

	// Layer 4
	this.instance_7 = new lib.Symbol1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(180,224.5,1,1,0,0,0,150,125);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(1).to({x:179.9,y:224.1,alpha:0.008},0).wait(1).to({y:223.7,alpha:0.018},0).wait(1).to({x:179.8,y:223.3,alpha:0.028},0).wait(1).to({x:179.7,y:222.8,alpha:0.039},0).wait(1).to({x:179.6,y:222.3,alpha:0.051},0).wait(1).to({x:179.5,y:221.7,alpha:0.064},0).wait(1).to({x:179.4,y:221.1,alpha:0.078},0).wait(1).to({x:179.2,y:220.4,alpha:0.093},0).wait(1).to({x:179.1,y:219.7,alpha:0.109},0).wait(1).to({x:179,y:219,alpha:0.126},0).wait(1).to({x:178.8,y:218.2,alpha:0.144},0).wait(1).to({x:178.7,y:217.4,alpha:0.163},0).wait(1).to({x:178.5,y:216.5,alpha:0.183},0).wait(1).to({x:178.3,y:215.6,alpha:0.204},0).wait(1).to({x:178.2,y:214.6,alpha:0.227},0).wait(1).to({x:178,y:213.5,alpha:0.25},0).wait(1).to({x:177.8,y:212.4,alpha:0.275},0).wait(1).to({x:177.6,y:211.3,alpha:0.301},0).wait(1).to({x:177.3,y:210.1,alpha:0.328},0).wait(1).to({x:177.1,y:208.9,alpha:0.356},0).wait(1).to({x:176.9,y:207.6,alpha:0.386},0).wait(1).to({x:176.6,y:206.2,alpha:0.416},0).wait(1).to({x:176.4,y:204.8,alpha:0.448},0).wait(1).to({x:176.1,y:203.4,alpha:0.481},0).wait(1).to({x:175.8,y:201.9,alpha:0.515},0).wait(1).to({x:175.5,y:200.4,alpha:0.551},0).wait(1).to({x:175.2,y:198.8,alpha:0.587},0).wait(1).to({x:174.9,y:197.1,alpha:0.624},0).wait(1).to({x:174.6,y:195.4,alpha:0.663},0).wait(1).to({x:174.3,y:193.7,alpha:0.702},0).wait(1).to({x:174,y:191.9,alpha:0.742},0).wait(1).to({x:173.7,y:190.1,alpha:0.784},0).wait(1).to({x:173.3,y:188.3,alpha:0.826},0).wait(1).to({x:173,y:186.4,alpha:0.868},0).wait(1).to({x:172.6,y:184.5,alpha:0.912},0).wait(1).to({x:172.3,y:182.6,alpha:0.956},0).wait(1).to({x:171.9,y:180.7,alpha:1},0).wait(1).to({x:171.6,y:179.3},0).wait(1).to({x:171.4,y:177.8},0).wait(1).to({x:171.1,y:176.4},0).wait(1).to({x:170.9,y:175},0).wait(1).to({x:170.6,y:173.6},0).wait(1).to({x:170.3,y:172.1},0).wait(1).to({x:170.1,y:170.7},0).wait(1).to({x:169.8,y:169.3},0).wait(1).to({x:169.5,y:167.8},0).wait(1).to({x:169.3,y:166.4},0).wait(1).to({x:169,y:165},0).wait(1).to({x:168.7,y:163.6},0).wait(1).to({x:168.5,y:162.1},0).wait(1).to({x:168.2,y:160.7},0).wait(1).to({x:168,y:159.3},0).wait(1).to({x:167.7,y:157.9},0).wait(1).to({x:167.4,y:156.5},0).wait(1).to({x:167.2,y:155.1},0).wait(1).to({x:166.9,y:153.7},0).wait(1).to({x:166.7,y:152.3},0).wait(1).to({x:166.4,y:151},0).wait(1).to({x:166.2,y:149.6},0).wait(1).to({x:165.9,y:148.3},0).wait(1).to({x:165.7,y:147},0).wait(1).to({x:165.4,y:145.6},0).wait(1).to({x:165.2,y:144.3},0).wait(1).to({x:165,y:143},0).wait(1).to({x:164.7,y:141.8},0).wait(1).to({x:164.5,y:140.5},0).wait(1).to({x:164.3,y:139.2},0).wait(1).to({x:164,y:138},0).wait(1).to({x:163.8,y:136.8},0).wait(1).to({x:163.6,y:135.6},0).wait(1).to({x:163.4,y:134.4},0).wait(1).to({x:163.1,y:133.2},0).wait(1).to({x:162.9,y:132},0).wait(1).to({x:162.7,y:130.8},0).wait(1).to({x:162.5,y:129.7},0).wait(1).to({x:162.3,y:128.6},0).wait(1).to({x:162.1,y:127.5},0).wait(1).to({x:161.9,y:126.4},0).wait(1).to({x:161.7,y:125.3},0).wait(1).to({x:161.5,y:124.3},0).wait(1).to({x:161.3,y:123.2},0).wait(1).to({x:161.1,y:122.2},0).wait(1).to({x:160.9,y:121.1},0).wait(1).to({x:160.7,y:120.1},0).wait(1).to({x:160.5,y:119.1},0).wait(1).to({x:160.3,y:118.1},0).wait(1).to({x:160.2,y:117.1},0).wait(1).to({x:160,y:116.2},0).wait(1).to({x:159.8,y:115.2},0).wait(1).to({x:159.6,y:114.3},0).wait(1).to({x:159.5,y:113.4},0).wait(1).to({x:159.3,y:112.5},0).wait(1).to({x:159.1,y:111.6},0).wait(1).to({x:159,y:110.7},0).wait(1).to({x:158.8,y:109.8},0).wait(1).to({x:158.7,y:109},0).wait(1).to({x:158.5,y:108.1},0).wait(1).to({x:158.3,y:107.3},0).wait(1).to({x:158.2,y:106.5},0).wait(1).to({x:158,y:105.6},0).wait(1).to({x:157.9,y:104.8},0).wait(1).to({x:157.8,y:104.1},0).wait(1).to({x:157.6,y:103.3},0).wait(1).to({x:157.5,y:102.5},0).wait(1).to({x:157.3,y:101.8},0).wait(1).to({x:157.2,y:101},0).wait(1).to({x:157.1,y:100.3},0).wait(1).to({x:156.9,y:99.6},0).wait(1).to({x:156.8,y:98.9},0).wait(1).to({x:156.7,y:98.2},0).wait(1).to({x:156.5,y:97.5},0).wait(1).to({x:156.4,y:96.8},0).wait(1).to({x:156.3,y:96.1},0).wait(1).to({x:156.2,y:95.5},0).wait(1).to({x:156,y:94.8},0).wait(1).to({x:155.9,y:94.2},0).wait(1).to({x:155.8,y:93.5},0).wait(1).to({x:155.7,y:92.9},0).wait(1).to({x:155.6,y:92.3},0).wait(1).to({x:155.5,y:91.7},0).wait(1).to({x:155.4,y:91.1},0).wait(1).to({x:155.3,y:90.5},0).wait(1).to({x:155.1,y:89.9},0).wait(1).to({x:155,y:89.4},0).wait(1).to({x:154.9,y:88.8},0).wait(1).to({x:154.8,y:88.2},0).wait(1).to({x:154.7,y:87.7},0).wait(1).to({x:154.6,y:87.2},0).wait(1).to({x:154.5,y:86.6},0).wait(1).to({x:154.4,y:86.1},0).wait(1).to({x:154.3,y:85.6},0).wait(1).to({y:85.1},0).wait(1).to({x:154.2,y:84.6},0).wait(1).to({x:154.1,y:84.1},0).wait(1).to({x:154,y:83.6},0).wait(1).to({x:153.9,y:83.2},0).wait(1).to({x:153.8,y:82.7},0).wait(1).to({x:153.7,y:82.2},0).wait(1).to({x:153.6,y:81.8},0).wait(1).to({y:81.3},0).wait(1).to({x:153.5,y:80.9},0).wait(1).to({x:153.4,y:80.5},0).wait(1).to({x:153.3,y:80},0).wait(1).to({x:153.2,y:79.6},0).wait(1).to({y:79.2},0).wait(1).to({x:153.1,y:78.8},0).wait(1).to({x:153,y:78.4},0).wait(1).to({x:152.9,y:78},0).wait(1).to({y:77.6},0).wait(1).to({x:152.8,y:77.3},0).wait(1).to({x:152.7,y:76.9},0).wait(1).to({y:76.5},0).wait(1).to({x:152.6,y:76.2},0).wait(1).to({x:152.5,y:75.8},0).wait(1).to({y:75.5},0).wait(1).to({x:152.4,y:75.1},0).wait(1).to({x:152.3,y:74.8},0).wait(1).to({y:74.4},0).wait(1).to({x:152.2,y:74.1},0).wait(1).to({y:73.8},0).wait(1).to({x:152.1,y:73.5},0).wait(1).to({y:73.2},0).wait(1).to({x:152,y:72.9},0).wait(1).to({x:151.9,y:72.6},0).wait(1).to({y:72.3},0).wait(1).to({x:151.8,y:72},0).wait(1).to({y:71.7},0).wait(1).to({x:151.7,y:71.4},0).wait(1).to({y:71.2},0).wait(1).to({x:151.6,y:70.9},0).wait(1).to({y:70.6},0).wait(1).to({x:151.5,y:70.4},0).wait(1).to({y:70.1},0).wait(1).to({x:151.4,y:69.9},0).wait(1).to({y:69.6},0).wait(1).to({y:69.4},0).wait(1).to({x:151.3,y:69.2},0).wait(1).to({y:68.9},0).wait(1).to({x:151.2,y:68.7},0).wait(1).to({y:68.5},0).wait(1).to({x:151.1,y:68.3},0).wait(1).to({y:68},0).wait(1).to({y:67.8},0).wait(1).to({x:151,y:67.6},0).wait(1).to({y:67.4},0).wait(1).to({y:67.2},0).wait(1).to({x:150.9,y:67.1},0).wait(1).to({y:66.9},0).wait(1).to({y:66.7},0).wait(1).to({x:150.8,y:66.5},0).wait(1).to({y:66.3},0).wait(1).to({y:66.2},0).wait(1).to({x:150.7,y:66},0).wait(1).to({y:65.8},0).wait(1).to({y:65.7},0).wait(1).to({x:150.6,y:65.5},0).wait(1).to({y:65.4},0).wait(1).to({y:65.2},0).wait(1).to({y:65.1},0).wait(1).to({x:150.5,y:64.9},0).wait(1).to({y:64.8},0).wait(1).to({y:64.7},0).wait(1).to({y:64.6},0).wait(1).to({x:150.4,y:64.4},0).wait(1).to({y:64.3},0).wait(1).to({y:64.2},0).wait(1).to({y:64.1},0).wait(1).to({y:64},0).wait(1).to({x:150.3,y:63.9},0).wait(1).to({y:63.8},0).wait(1).to({y:63.7},0).wait(1).to({y:63.6},0).wait(1).to({y:63.5},0).wait(1).to({x:150.2,y:63.4},0).wait(1).to({y:63.3},0).wait(1).to({y:63.2},0).wait(1).to({y:63.1},0).wait(1).to({y:63},0).wait(2).to({y:62.9},0).wait(1).to({x:150.1,y:62.8},0).wait(2).to({y:62.7},0).wait(1).to({y:62.6},0).wait(2).to({y:62.5},0).wait(2).to({y:62.4},0).wait(2).to({y:62.3},0).wait(1).to({x:150},0).wait(2).to({y:62.2},0).wait(4).to({y:62.1},0).wait(8).to({y:62},0).wait(1));

	// bg
	this.instance_8 = new lib.Symbol5();
	this.instance_8.parent = this;
	this.instance_8.setTransform(150,125,1,1,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({scaleX:1.2,scaleY:1.2},245,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,125,331,356);
// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/300x250_space_atlas_.png", id:"300x250_space_atlas_"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;