(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"300x600_aaoo_girl_atlas_", frames: [[0,0,300,600]]}
];


// symbols:



(lib.bb_boy = function() {
	this.initialize(ss["300x600_aaoo_girl_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#51C4ED").s().p("AgOCEIgUgEIgSgGIgRgJIgPgLIgRgSIgLgPIgJgSIgGgSIgEgUIAAgbIAEgTIAGgTIAJgRIAOgUIAOgMIAPgLIARgJIANgFIAZgEIATgBIAhAFIAYAKIAGAEIAQALIANAMIAQAUIAJARIAIAZIACAUIAAANIgCAUIgIAZIgDAGIgKARIgQAUIgOAMIgWANIgMAFIgTAGIgaACg");
	this.shape.setTransform(13.2,13.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol6, new cjs.Rectangle(0,0,26.4,26.4), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#51C4ED").s().p("AgIAqIAAhDIgVAAIAAgQIA7AAIAAAQIgVAAIAABDg");
	this.shape.setTransform(134.525,459.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#51C4ED").s().p("AgdAfIAKgNQALAJAKAAQAEAAAEgCQADgCAAgEQAAgDgDgCQgEgDgHgEQgNgEgFgEQgHgGABgKIAAgBQAAgKAHgIQAIgGALAAQAQAAAMAKIgKANQgKgHgIgBQgDAAgDACQgDADAAADQAAAEADACQADACAJAEQALAFAGAFQAFAGABAIIAAABQgBAMgHAGQgIAHgMAAQgSAAgNgMg");
	this.shape_1.setTransform(127.8,459.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#51C4ED").s().p("AgIAqIAAhTIARAAIAABTg");
	this.shape_2.setTransform(122.875,459.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#51C4ED").s().p("AAMAqIgPgbIgKAAIAAAbIgSAAIAAhTIAfAAQAOAAAJAIQAHAHAAANIAAAAQAAARgQAHIASAfgAgNAAIAMAAQAGAAAEgDQADgDAAgGQAAgOgNAAIgMAAg");
	this.shape_3.setTransform(117.625,459.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#51C4ED").s().p("AgIAqIAAhDIgVAAIAAgQIA7AAIAAAQIgVAAIAABDg");
	this.shape_4.setTransform(110.325,459.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#51C4ED").s().p("AgaAqIAAhTIA1AAIAAAPIgkAAIAAATIAfAAIAAAOIgfAAIAAATIAkAAIAAAQg");
	this.shape_5.setTransform(103.775,459.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#51C4ED").s().p("AAUAqIAAg1IgUAiIAAAAIgTgiIAAA1IgRAAIAAhTIASAAIASAiIATgiIASAAIAABTg");
	this.shape_6.setTransform(95.675,459.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#51C4ED").s().p("AgbAgQgKgNAAgSIAAgBQAAgSAKgMQAMgNAPAAQAQAAAMANQAKALAAATIAAAAQAAAUgLAMQgLAMgQgBQgQABgLgMgAgNgTQgGAHAAAMIAAAAQAAAMAGAIQAFAIAIgBQAJABAFgIQAGgHAAgNIAAAAQAAgMgGgHQgFgIgJAAQgIAAgFAIg");
	this.shape_7.setTransform(86.85,459.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#51C4ED").s().p("AgIAqIAAhDIgVAAIAAgQIA7AAIAAAQIgVAAIAABDg");
	this.shape_8.setTransform(79.225,459.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#51C4ED").s().p("AgcAqIAAhTIAcAAQANAAAIAHQAIAIAAAOQAAANgJAIQgIAHgNAAIgKAAIAAAagAgLABIAKAAQAFAAAEgDQAEgEAAgFQAAgPgNAAIgKAAg");
	this.shape_9.setTransform(72.675,459.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#51C4ED").s().p("AgbAgQgKgNAAgSIAAgBQAAgSAKgMQAMgNAPAAQARAAAKANQALALAAATIAAAAQAAAUgLAMQgLAMgQgBQgQABgLgMgAgNgTQgGAHAAAMIAAAAQAAAMAGAIQAFAIAIgBQAJABAGgIQAFgHAAgNIAAAAQAAgMgGgHQgGgIgIAAQgIAAgFAIg");
	this.shape_10.setTransform(64.6,459.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#51C4ED").s().p("AARAqIgfgyIAAAyIgRAAIAAhTIAQAAIAeAwIAAgwIARAAIAABTg");
	this.shape_11.setTransform(53.55,459.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#51C4ED").s().p("AAVAqIgHgSIgcAAIgGASIgSAAIAfhTIAPAAIAfBTgAAJAJIgJgbIgJAbIASAAg");
	this.shape_12.setTransform(45.45,459.675);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#51C4ED").s().p("AggAqIAAhTIAbAAQAQAAAMAMQALALAAASIAAAAQAAATgLAMQgMALgQAAgAgPAaIAKAAQAIABAGgIQAHgGAAgNIAAAAQAAgLgHgIQgGgGgIgBIgKAAg");
	this.shape_13.setTransform(34.9,459.7);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#51C4ED").s().p("AASAqIgggyIAAAyIgSAAIAAhTIARAAIAeAwIAAgwIARAAIAABTg");
	this.shape_14.setTransform(26.65,459.7);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#51C4ED").s().p("AgIAqIAAhTIARAAIAABTg");
	this.shape_15.setTransform(20.825,459.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#51C4ED").s().p("AgaAqIAAhTIA1AAIAAAQIgkAAIAAATIAgAAIAAAPIggAAIAAAhg");
	this.shape_16.setTransform(16,459.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgFAQIgGgEIgEgFIgBgHIABgGIAEgFIAGgEIAFgBIAHABIAFAEIAEAFIABAGIgBAHIgEAFIgFAEIgHABg");
	this.shape_17.setTransform(199.075,417.825);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAABZQgIgBgEgGQgEgFgCgIQgDgJAAgNIAAhKIgVAAIAAgUIAVAAIAAghIAXgLIAAAsIAhAAIAAAUIghAAIAABOQAAAHACAFQACAGAEACQAEABAFAAIAKgBIAJgDIAGARIgOAFQgGACgKAAQgJAAgFgDg");
	this.shape_18.setTransform(191.1,410.55);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgYBDQgKgFgGgIIgNAAIAAgXIAbAAQAAAGADAEQACAEAEACQAEADAFABIAKABIAKgBIAIgEQADgCACgEQACgDABgFQgBgGgEgFQgEgEgLgEIgYgKQgRgEgHgJQgIgJAAgNQAAgJADgHQAEgIAGgFQAGgFAJgDQAIgDAMAAQANAAAKAEQALAEAHAKIANAAIAAAWIgbAAQAAgFgDgEQgCgEgEgCIgKgEIgIgBIgKABIgIADQgCADgCADQgCADAAAEQAAAHAEAEQAFAEAJADIAZAKQARAFAIAJQAHAKAAANQABAKgEAHQgDAIgHAFQgHAFgJADQgKADgLAAQgPAAgKgFg");
	this.shape_19.setTransform(179.55,412.575);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgfBlIAAgXIATAAIAAhaIgUAAIAAgXIAsAAIAABxIAVAAIAAAXgAgGhCIgFgFIgEgFIgBgHIABgHIAEgFIAFgEIAGgBIAGABIAGAEIADAFIACAHIgCAHIgDAFIgGAFIgGABg");
	this.shape_20.setTransform(168.875,409.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgwBFIAAgXIATAAIAAhaIgTAAIAAgXIAsAAIAAATIAEgIIAHgGIAIgEQAEgCAFAAIANAAIAMAAIAAAeIgZAAIAAgIIgJABQgEACgEADQgEAEgDAFQgCAFgCAHIAABBIAXAAIAAAXg");
	this.shape_21.setTransform(157.975,412.525);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAABZQgIgBgEgGQgEgFgCgIQgDgJAAgNIABhKIgXAAIAAgUIAXAAIAAghIAWgLIAAAsIAhAAIAAAUIghAAIAABOQAAAHACAFQACAGAEACQAEABAFAAIAKgBIAJgDIAGARIgOAFQgGACgKAAQgJAAgFgDg");
	this.shape_22.setTransform(146.75,410.55);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgWBDQgLgEgJgJQgIgKgFgNQgFgOAAgRQAAgOAEgNQAEgOAIgJQAIgKAMgFQAMgGAPAAQAQAAAKAEQAKAFAHAIQAGAIAEAKQADAKABAKIABAKIAAAJIhhAAIABAKIACAJQAFAOALAHQALAGAMAAQALAAAKgDQAKgDALgGIAKARQgNAJgOAEQgNAFgPAAQgNAAgMgFgAAjgPIgCgOQgCgHgEgFQgEgFgGgCQgGgCgJgBQgIABgGACQgHACgEAFQgFAFgCAGQgDAGgCAJIBGAAg");
	this.shape_23.setTransform(133.625,412.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AA6BFIAAgWIATAAIAAg9QAAgQgHgIQgIgJgPAAQgJABgJAEQgKAEgGAHIAABOIATAAIAAAWIg/AAIAAgWIATAAIAAg9QAAgQgHgIQgJgJgPAAQgIAAgJAEQgIAFgJAGIAABPIAUAAIAAAWIhAAAIAAgWIATAAIAAhbIgTAAIAAgWIArAAIAAAQIABAAIAJgHIAKgGIAMgEIAMgBQAPgBALAGQAKAFAFAMIALgJIALgHIANgEQAGgCAHAAQAMAAAIADQAJACAHAHQAFAGAEAKQADAJAAANIAABBIATAAIAAAWg");
	this.shape_24.setTransform(112.8,412.45);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgbBDQgMgFgJgKQgJgJgFgOQgFgNAAgQQAAgPAFgOQAFgNAJgJQAJgKANgFQAMgFAOAAQAPAAANAFQAMAFAJAJQAJAKAFANQAFANAAAQQAAAQgFANQgFANgJAKQgJAKgMAFQgNAFgPAAQgOAAgNgFgAgPgvQgIADgGAHQgGAGgDAKQgDAKAAALQAAAMADAJQADAKAGAGQAGAHAIAEQAHADAIAAQAJAAAIgDQAIgEAGgGQAGgHADgKQADgJAAgMQAAgLgDgKQgDgKgGgGQgGgHgIgDQgIgDgJAAQgIAAgHADg");
	this.shape_25.setTransform(91.175,412.575);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgBBZQgGgBgFgGQgFgFgCgIQgCgJAAgNIAAhKIgVAAIAAgUIAVAAIAAghIAYgLIAAAsIAgAAIAAAUIggAAIgBBOQAAAHACAFQACAGAEACQAEABAFAAIAKgBIAJgDIAFARIgMAFQgIACgJAAQgJAAgGgDg");
	this.shape_26.setTransform(78.2,410.55);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AhHBlIAAgWIATAAIAAiZIgTAAIAAgXIArAAIAAAMQAJgHAKgEQAJgEALAAQAOAAALAFQALAFAIAJQAIAJAFANQAEANAAAPQAAAQgFAPQgFAMgJAKQgJAJgMAFQgMAGgPAAQgJAAgIgCIgQgGIAAAtIAWAAIAAAWgAgMhKQgJADgHAHIAABJQAFAEAIAEQAIADALAAQAIAAAIgDQAIgDAGgGQAGgHADgJQAEgJAAgNQAAgMgDgJQgEgIgFgGQgGgHgIgDQgIgEgIAAQgJAAgIAFg");
	this.shape_27.setTransform(64.775,415.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgbBDQgMgFgJgKQgJgJgFgOQgFgNAAgQQAAgPAFgOQAFgNAJgJQAJgKANgFQAMgFAOAAQAPAAANAFQAMAFAJAJQAJAKAFANQAFANAAAQQAAAQgFANQgFANgJAKQgJAKgMAFQgNAFgPAAQgOAAgNgFgAgPgvQgIADgGAHQgGAGgDAKQgDAKAAALQAAAMADAJQADAKAGAGQAGAHAIAEQAHADAIAAQAJAAAIgDQAIgEAGgGQAGgHADgKQADgJAAgMQAAgLgDgKQgDgKgGgGQgGgHgIgDQgIgDgJAAQgIAAgHADg");
	this.shape_28.setTransform(48.625,412.575);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AANBFIAAgWIATAAIAAg9QABgQgJgIQgHgJgPAAQgIAAgJAEQgIAFgJAGIAABPIAUAAIAAAWIhAAAIAAgWIATAAIAAhbIgTAAIAAgWIAsAAIAAAQIAAAAIAJgHIAKgGIAMgEIALgBQALAAAJADQAJACAGAHQAGAGAEAKQADAJAAANIAABBIATAAIAAAWg");
	this.shape_29.setTransform(25.75,412.45);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AghBEQgJgDgGgFQgGgGgEgHQgDgHAAgIQAAgJADgHQACgHAFgEQAEgFAGgDIALgFIAOgDIAMgBIAPABIALABIAAgLQAAgHgBgFQgCgGgFgDQgDgEgGgCQgFgBgFAAIgMABIgLACIgJADIgHAEIgIgRIALgGIAMgFIANgDIANgBQALAAAKADQAJADAGAGQAHAGADAJQAEAJAAANIAABDIAPAAIAAAXIgoAAIAAgNQgHAHgKAFQgIAFgMAAQgKAAgIgEgAgSAHIgKAFQgEADgCAEQgDAFAAAFQAAAGACAEQACAEADADQAEACAFACIALABIAKgBIAIgDIAIgFIAGgGIAAgfIgbAAQgHAAgGACg");
	this.shape_30.setTransform(9.1,412.625);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AANBmIAAgWIATAAIAAg+QgBgQgHgHQgJgJgOABQgIgBgJAEQgIAFgHAFIAABQIATAAIAAAWIhBAAIAAgWIAVAAIAAifIgTAAIAAgXIAsAAIAABUIAAAAIAJgHIAKgGIALgDIAKgBQALAAAJADQAJACAGAHQAGAGAEAKQADAIAAANIAABCIAVAAIAAAWg");
	this.shape_31.setTransform(219.75,378.55);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgBBZQgGgBgFgGQgFgFgCgIQgCgJAAgNIAAhKIgVAAIAAgUIAVAAIAAghIAYgLIAAAsIAgAAIAAAUIggAAIgBBOQAAAHACAFQACAGAEACQAEABAFAAIAKgBIAJgDIAFARIgMAFQgIACgJAAQgJAAgGgDg");
	this.shape_32.setTransform(205.65,379.95);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgfBlIAAgXIATAAIAAhaIgUAAIAAgXIAsAAIAABxIAVAAIAAAXgAgGhCIgFgFIgEgFIgBgHIABgHIAEgFIAFgEIAGgBIAGABIAGAEIADAFIACAHIgCAHIgDAFIgGAFIgGABg");
	this.shape_33.setTransform(196.475,378.7);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAfBFIgfhsIgeBsIgXAAIglhzIgMAAIAAgWIAsAAIAAAWIgHAAIAYBWIAhhsIATAAIAgBsIAZhWIgIAAIAAgWIArAAIAAAWIgMAAIglBzg");
	this.shape_34.setTransform(180.925,382.075);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AA7BFIAAgWIATAAIAAg9QAAgQgJgIQgIgJgOABQgJAAgKAEQgIAEgHAHIAABOIATAAIAAAWIg/AAIAAgWIAUAAIAAg9QAAgQgJgIQgHgJgQABQgIgBgJAEQgJAFgHAGIAABPIATAAIAAAWIhAAAIAAgWIATAAIAAhbIgTAAIAAgWIAsAAIAAAQIAAAAIAKgHIAKgGIALgEIAMgBQAPgBAKAGQAKAFAGAMIAKgJIANgHIAMgEQAHgCAGAAQALAAAKADQAIACAGAHQAHAGADAKQADAJAAANIAABBIATAAIAAAWg");
	this.shape_35.setTransform(151,381.85);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgiBEQgIgDgGgFQgGgGgDgHQgEgHAAgIQAAgJADgHQACgHAEgEQAFgFAGgDIAMgFIAMgDIANgBIAPABIAMABIAAgLQAAgHgCgFQgDgGgDgDQgEgEgFgCQgGgBgFAAIgNABIgKACIgJADIgHAEIgIgRIALgGIAMgFIANgDIANgBQALAAAJADQAKADAGAGQAHAGADAJQAEAJAAANIAABDIAPAAIAAAXIgnAAIAAgNQgIAHgJAFQgJAFgMAAQgKAAgJgEgAgSAHIgKAFQgFADgCAEQgCAFAAAFQAAAGACAEQACAEAEADQADACAFACIALABIAKgBIAIgDIAIgFIAHgGIAAgfIgcAAQgHAAgGACg");
	this.shape_36.setTransform(129.85,382.025);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAUBEIAAgWIAIAAIgcgiIgZAiIAHAAIAAAWIguAAIAAgWIALAAIAqgwIgngrIgOAAIAAgWIAtAAIAAAWIgFAAIAYAhIAaghIgHAAIAAgWIAuAAIAAAWIgMAAIgnAtIApAuIAKAAIAAAWg");
	this.shape_37.setTransform(115.575,381.975);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgWBDQgLgEgJgJQgIgKgFgNQgFgOAAgRQAAgOAEgNQAEgOAIgJQAIgKAMgFQAMgGAPAAQAQAAAKAEQAKAFAHAIQAGAIAEAKQADAJABAKIABALIAAAJIhhAAIABAKIACAJQAFAOALAHQALAGAMAAQALAAAKgDQAKgDALgGIAKARQgNAJgOAEQgNAFgPAAQgNAAgMgFgAAjgPIgCgOQgCgHgEgFQgEgFgGgCQgGgCgJgBQgIABgGACQgHACgEAFQgFAFgCAGQgDAGgCAJIBGAAg");
	this.shape_38.setTransform(100.275,382);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgWBDQgLgEgJgJQgIgKgFgNQgFgOAAgRQAAgOAEgNQAEgOAIgJQAIgKAMgFQAMgGAPAAQAQAAAKAEQAKAFAHAIQAGAIAEAKQADAJABAKIABALIAAAJIhhAAIABAKIACAJQAFAOALAHQALAGAMAAQALAAAKgDQAKgDALgGIAKARQgNAJgOAEQgNAFgPAAQgNAAgMgFgAAjgPIgCgOQgCgHgEgFQgEgFgGgCQgGgCgJgBQgIABgGACQgHACgEAFQgFAFgCAGQgDAGgCAJIBGAAg");
	this.shape_39.setTransform(78.925,382);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgqBjIAAgWIARAAIAOgmIguhzIgKAAIAAgWIA0AAIAAAWIgRAAIAgBWIAghWIgQAAIAAgWIA0AAIAAAWIgOAAIg7CZIASAAIAAAWg");
	this.shape_40.setTransform(63.35,385.075);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgWBDQgLgEgJgJQgIgKgFgNQgFgOAAgRQAAgOAEgNQAEgOAIgJQAIgKAMgFQAMgGAPAAQAQAAAKAEQAKAFAHAIQAGAIAEAKQADAJABAKIABALIAAAJIhhAAIABAKIACAJQAFAOALAHQALAGAMAAQALAAAKgDQAKgDALgGIAKARQgNAJgOAEQgNAFgPAAQgNAAgMgFgAAjgPIgCgOQgCgHgEgFQgEgFgGgCQgGgCgJgBQgIABgGACQgHACgEAFQgFAFgCAGQgDAGgCAJIBGAAg");
	this.shape_41.setTransform(47.975,382);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AANBFIAAgWIATAAIAAg9QABgQgJgIQgHgJgPABQgIgBgJAEQgIAFgJAGIAABPIAUAAIAAAWIhAAAIAAgWIATAAIAAhbIgTAAIAAgWIAsAAIAAAQIAAAAIAJgHIAKgGIAMgEIALgBQALAAAJADQAJACAGAHQAGAGAEAKQADAJAAANIAABBIATAAIAAAWg");
	this.shape_42.setTransform(25.75,381.85);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AghBEQgJgDgGgFQgGgGgEgHQgDgHAAgIQAAgJADgHQACgHAFgEQAEgFAGgDIALgFIAOgDIAMgBIAPABIALABIAAgLQAAgHgBgFQgCgGgFgDQgDgEgGgCQgFgBgFAAIgMABIgLACIgJADIgHAEIgIgRIALgGIAMgFIANgDIANgBQALAAAKADQAJADAGAGQAHAGADAJQAEAJAAANIAABDIAPAAIAAAXIgoAAIAAgNQgHAHgKAFQgIAFgMAAQgKAAgIgEgAgSAHIgKAFQgEADgCAEQgDAFAAAFQAAAGACAEQACAEADADQAEACAFACIALABIAKgBIAIgDIAIgFIAGgGIAAgfIgbAAQgHAAgGACg");
	this.shape_43.setTransform(9.1,382.025);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AggBjQgMgEgIgKQgKgJgFgOQgEgNgBgRQABgQAEgNQAFgMAJgKQAJgJAMgEQAMgGAPAAQAJAAAIACQAJACAHAGIAAg1IgTAAIAAgWIArAAIAAC1IAVAAIAAAXIgtAAIAAgLQgHAGgIAEQgJAEgKAAQgOAAgMgFgAgUgNQgIADgFAHQgHAFgCAIQgEAJAAAMQAAANADAJQAEAKAFAGQAGAHAHADQAJADAJAAQAKAAAHgDQAIgDAGgGIAAhLQgHgGgIgDQgJgDgIAAQgIAAgIAEg");
	this.shape_44.setTransform(201.15,348.1);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AggBmIAAgWIAUAAIAAifIgUAAIAAgXIAsAAIAAC2IAUAAIAAAWg");
	this.shape_45.setTransform(188.4,347.95);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgfBlIAAgXIATAAIAAhaIgUAAIAAgXIAsAAIAABxIAVAAIAAAXgAgGhCIgFgFIgEgFIgBgHIABgHIAEgFIAFgEIAGgBIAGABIAGAEIADAFIACAHIgCAHIgDAFIgGAFIgGABg");
	this.shape_46.setTransform(179.775,348.1);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AANBmIAAgWIATAAIAAg+QgBgQgHgHQgJgJgOABQgHgBgKAEQgIAFgIAFIAABQIAUAAIAAAWIhBAAIAAgWIAVAAIAAifIgTAAIAAgXIArAAIAABUIABAAIAIgHIALgGIALgDIAKgBQALAAAJADQAJACAGAHQAGAGAEAKQADAIAAANIAABCIAVAAIAAAWg");
	this.shape_47.setTransform(166.55,347.95);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgWBDQgMgGgJgJQgIgKgFgNQgFgNAAgQQAAgPAFgNQAFgNAJgKQAJgKAMgFQAMgGANAAQANAAALAFQAMAFAIAIIAOAAIAAAYIgYAAQgGgLgIgEQgJgFgLAAQgIAAgHADQgIAEgFAHQgGAGgDAKQgDAJAAALQAAAMADAJQADAJAGAGQAFAHAIAEQAHADAIAAQAMAAAKgGQAJgHAGgLIAUAKQgEAIgGAHQgGAGgHAFQgHAFgJADQgJACgJAAQgOABgMgGg");
	this.shape_48.setTransform(150.175,351.35);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgwBFIAAgXIATAAIAAhaIgTAAIAAgXIAsAAIAAATIAEgIIAHgGIAIgEQAEgCAFAAIANAAIAMAAIAAAeIgZAAIAAgIIgJABQgEACgEADQgEAEgDAFQgCAFgCAHIAABBIAXAAIAAAXg");
	this.shape_49.setTransform(130.425,351.325);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgbBCQgJgDgGgGQgGgGgDgJQgDgLAAgNIAAhAIgSAAIAAgXIAsAAIAABVQAAAPAHAIQAHAIAOAAQAHAAAJgDQAJgDAIgFIAAhSIgTAAIAAgXIAsAAIAABxIAPAAIAAAXIgnAAIAAgNQgKAIgKADQgLAFgMAAQgKAAgIgEg");
	this.shape_50.setTransform(114.575,351.5);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgbBDQgMgFgJgKQgJgJgFgOQgFgNAAgQQAAgPAFgOQAFgNAJgJQAJgKANgFQAMgFAOAAQAPAAANAFQAMAFAJAJQAJAKAFANQAFANAAAQQAAAQgFANQgFANgJAKQgJAKgMAFQgNAFgPAAQgOAAgNgFgAgPgvQgIADgGAHQgGAGgDAKQgDAKAAALQAAAMADAJQADAKAGAGQAGAHAIAEQAHADAIAAQAJAAAIgDQAIgEAGgGQAGgHADgKQADgJAAgMQAAgLgDgKQgDgKgGgGQgGgHgIgDQgIgDgJAAQgIAAgHADg");
	this.shape_51.setTransform(98.325,351.375);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgqBjIAAgWIARAAIAOgmIguhzIgLAAIAAgWIA1AAIAAAWIgRAAIAgBWIAghWIgPAAIAAgWIAzAAIAAAWIgNAAIg9CZIASAAIAAAWg");
	this.shape_52.setTransform(82.1,354.475);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AAvBmIg4g9IgSAAIAAAnIAMAAIAAAWIg7AAIAAgWIAXAAIAAifIgYAAIAAgXIAwAAIAAAXIAABlIAYAAIAgghIgIAAIAAgWIA0AAIAAAWIgSAAIgqAqIAuAxIARAAIAAAWg");
	this.shape_53.setTransform(60.75,347.95);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgbBDQgMgFgJgKQgJgJgFgOQgFgNAAgQQAAgPAFgOQAFgNAJgJQAJgKANgFQAMgFAOAAQAPAAANAFQAMAFAJAJQAJAKAFANQAFANAAAQQAAAQgFANQgFANgJAKQgJAKgMAFQgNAFgPAAQgOAAgNgFgAgPgvQgIADgGAHQgGAGgDAKQgDAKAAALQAAAMADAJQADAKAGAGQAGAHAIAEQAHADAIAAQAJAAAIgDQAIgEAGgGQAGgHADgKQADgJAAgMQAAgLgDgKQgDgKgGgGQgGgHgIgDQgIgDgJAAQgIAAgHADg");
	this.shape_54.setTransform(43.875,351.375);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgbBDQgMgFgJgKQgJgJgFgOQgFgNAAgQQAAgPAFgOQAFgNAJgJQAJgKANgFQAMgFAOAAQAPAAANAFQAMAFAJAJQAJAKAFANQAFANAAAQQAAAQgFANQgFANgJAKQgJAKgMAFQgNAFgPAAQgOAAgNgFgAgPgvQgIADgGAHQgGAGgDAKQgDAKAAALQAAAMADAJQADAKAGAGQAGAHAIAEQAHADAIAAQAJAAAIgDQAIgEAGgGQAGgHADgKQADgJAAgMQAAgLgDgKQgDgKgGgGQgGgHgIgDQgIgDgJAAQgIAAgHADg");
	this.shape_55.setTransform(27.775,351.375);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AhKBkIAAgXIATAAIAAiZIgTAAIAAgXIBZAAQANAAAKAFQALAEAIAIQAHAIAFAKQAEAMABAMQAAANgHAKQgIAKgNAHQAHACAFAFQAFAFAEAEQAEAGACAGQACAGAAAHQgBAMgEALQgEALgIAIQgIAIgKAFQgMAEgMAAgAgdBNIAtAAQAHAAAGgDQAFgDAEgFQAEgFADgHQACgGAAgHQAAgFgCgGQgDgFgEgEQgEgFgFgCQgGgDgHAAIgtAAgAgdgLIAsAAQAHAAAGgCQAFgDAEgEQAEgEACgGQADgGAAgFQAAgHgDgGQgCgGgEgFQgEgFgFgDQgHgDgGAAIgsAAg");
	this.shape_56.setTransform(11.35,348.2);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("ArUCqIAAlTIWpAAIAAFTg");
	this.shape_57.setTransform(74.5,462.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(0,330.3,239.5,149), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bb_boy();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,0,300,600), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFANIgEgDIgEgFIgBgFIABgFIAEgEIAEgEIAFgBIAFABIAFAEIADAEIABAFIgBAFIgDAFIgFADIgFACg");
	this.shape.setTransform(163.1,237.975);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgWBXIAnhAIgKACIgJABQgKAAgLgDQgLgFgHgGQgIgIgEgJQgFgKgBgLQABgOAFgLQAEgMAIgHQAJgIAKgEQALgDALAAQAMAAALADQAKAEAJAIQAIAHAEALQAFALABAMQgBALgEAJIgJATIgrBNgAgOhAQgGAEgGAEQgGAFgDAHQgCAHAAAIQgBAJAEAIQADAGAGAFQAGAEAGADQAHABAGAAQALABAGgDQAGgDAEgDQAFgFAEgGQACgIAAgJQAAgJgCgHQgEgGgFgFQgFgFgHgDQgHgCgIAAQgHAAgHACg");
	this.shape_1.setTransform(153.4,230.65);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSBYIAAgUIARAAIAAh7IgjATIAAgYIAvgbIAJAAIAACbIARAAIAAAUg");
	this.shape_2.setTransform(141.275,230.55);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AALA7IAAgTIARAAIAAg0QgBgOgGgGQgHgHgNAAQgGAAgIADIgNAJIAABDIAQAAIAAATIg2AAIAAgTIAQAAIAAhNIgQAAIAAgTIAlAAIAAAOIAIgHIAJgFIAKgDIAJgBQAJAAAIACQAHADAFAFQAGAFACAJQADAIAAALIAAA3IAQAAIAAATg");
	this.shape_3.setTransform(124.05,233.375);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgpA7IAAgUIAQAAIAAhNIgQAAIAAgTIAmAAIAAAQIADgHIAGgFIAHgEIAIAAIALAAIAKAAIAAAZIgVAAIAAgHIgIABQgEABgDAEQgDACgDAEIgDALIAAA3IATAAIAAAUg");
	this.shape_4.setTransform(110.95,233.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXA5QgHgDgFgFQgFgFgDgJQgCgIAAgLIAAg3IgQAAIAAgTIAlAAIAABHQAAAOAHAHQAFAGAMAAQAGAAAHgCQAIgDAHgEIAAhGIgQAAIAAgTIAmAAIAABgIANAAIAAATIgiAAIAAgLQgIAHgKADQgJADgJAAQgJAAgHgCg");
	this.shape_5.setTransform(97.4,233.575);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgBBMQgFgCgEgEQgEgEgCgIQgCgHAAgLIABg/IgTAAIAAgRIATAAIAAgbIATgKIAAAlIAbAAIAAARIgbAAIAABCQAAAHABAFQACADADACQAEACAEAAIAIgBIAIgDIAFAOIgLAEQgGACgIAAQgIAAgFgCg");
	this.shape_6.setTransform(86.225,231.75);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgjBVIAAgUIAOAAIAMggIgnhhIgJAAIAAgUIAsAAIAAAUIgOAAIAbBJIAchJIgOAAIAAgUIAsAAIAAAUIgMAAIgyCBIAOAAIAAAUg");
	this.shape_7.setTransform(69.925,236.125);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgTA5QgKgDgHgIQgHgIgEgLQgEgMAAgPQAAgMADgLQAEgLAHgJQAGgHALgFQAKgGAMAAQAOAAAIAFQAJAEAGAGQAFAHADAIQADAJABAIIABAJIAAAHIhTAAIABAJIACAIQAEAMAJAFQAKAGAKAAQAJAAAJgDQAIgCAKgGIAIAPQgLAHgMAEQgLAFgNAAQgLAAgKgFgAAegNIgCgMQgCgGgDgEQgEgEgFgCQgFgCgIAAQgGAAgGACQgFACgEAEQgEAEgCAFQgDAGgBAHIA8AAg");
	this.shape_8.setTransform(56.875,233.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AALBXIAAgTIAQAAIAAg1QAAgOgHgFQgHgHgMAAQgHAAgHADQgIADgGAFIAABEIARAAIAAATIg3AAIAAgTIASAAIAAiHIgQAAIAAgTIAkAAIAABHIABAAIAHgGIAJgFIAJgDIAJgBQAKAAAHACQAIADAEAFQAGAFADAJQACAHAAALIAAA4IASAAIAAATg");
	this.shape_9.setTransform(43.15,230.575);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBMQgFgCgEgEQgEgEgCgIQgCgHAAgLIABg/IgTAAIAAgRIATAAIAAgbIATgKIAAAlIAbAAIAAARIgbAAIAABCQAAAHABAFQACADADACQAEACAEAAIAIgBIAIgDIAFAOIgLAEQgGACgIAAQgIAAgFgCg");
	this.shape_10.setTransform(31.125,231.75);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgbBXIAAgTIARAAIAAiHIgRAAIAAgTIAlAAIAACaIARAAIAAATg");
	this.shape_11.setTransform(188.9,201.775);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgbBWIAAgUIARAAIAAhMIgRAAIAAgUIAlAAIAABgIASAAIAAAUgAgFg5IgFgDIgDgFIgBgFIABgGIADgEIAFgEIAFgBIAFABIAFAEIADAEIABAGIgBAFIgDAFIgFADIgFACg");
	this.shape_12.setTransform(181.575,201.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgBBMQgFgCgEgEQgEgEgCgHQgCgIAAgLIABg/IgTAAIAAgRIATAAIAAgbIATgKIAAAlIAbAAIAAARIgbAAIAABCQAAAHABAFQACADADACQAEACAEAAIAIgBIAIgDIAFAOIgLAEQgGACgIAAQgIAAgFgCg");
	this.shape_13.setTransform(173.475,202.95);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAMA7IAAgTIAQAAIAAg0QAAgOgHgGQgHgHgMAAQgHAAgIADIgOAJIAABDIARAAIAAATIg3AAIAAgTIARAAIAAhNIgRAAIAAgTIAmAAIAAAOIAIgHIAIgFIAKgDIAKgBQAJAAAHACQAIADAGAFQAFAFADAJQACAIAAALIAAA3IARAAIAAATg");
	this.shape_14.setTransform(161.55,204.575);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgXA5QgHgDgFgFQgFgFgDgJQgCgIAAgLIAAg3IgQAAIAAgTIAlAAIAABHQAAAOAHAHQAFAGAMAAQAGAAAHgCQAIgDAHgEIAAhGIgQAAIAAgTIAmAAIAABgIANAAIAAATIgiAAIAAgLQgIAHgKADQgJADgJAAQgJAAgHgCg");
	this.shape_15.setTransform(145.65,204.775);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAMA7IAAgTIAQAAIAAg0QAAgOgHgGQgHgHgMAAQgHAAgIADIgNAJIAABDIAQAAIAAATIg3AAIAAgTIARAAIAAhNIgRAAIAAgTIAmAAIAAAOIAIgHIAIgFIAKgDIAKgBQAJAAAHACQAIADAGAFQAFAFADAJQACAIAAALIAAA3IARAAIAAATg");
	this.shape_16.setTransform(126.1,204.575);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgTA5QgKgDgHgIQgHgIgEgLQgEgMAAgPQAAgMADgLQAEgLAHgJQAGgHALgFQAKgGAMAAQAOAAAIAFQAJAEAGAGQAFAHADAIQADAJABAIIABAJIAAAHIhTAAIABAJIACAIQAEAMAJAFQAKAGAKAAQAJAAAJgDQAIgCAKgGIAIAPQgLAHgMAEQgLAFgNAAQgLAAgKgFgAAegNIgCgMQgCgGgDgEQgEgEgFgCQgFgCgIAAQgGAAgGACQgFACgEAEQgEAEgCAGQgDAFgBAHIA8AAg");
	this.shape_17.setTransform(111.575,204.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgpA7IAAgUIAQAAIAAhNIgQAAIAAgTIAlAAIAAAQIAEgGIAGgGIAGgEIAIAAIALAAIALAAIAAAZIgWAAIAAgHIgHABQgEABgDAEQgDACgDAEIgDALIAAA3IATAAIAAAUg");
	this.shape_18.setTransform(99.85,204.65);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgbBUQgKgEgIgHQgHgJgEgLQgEgMgBgOQABgOAEgLQADgKAIgIQAHgIAKgEQALgEANAAQAIAAAGACQAHABAHAFIAAgtIgQAAIAAgSIAkAAIAACZIARAAIAAAUIglAAIAAgKQgGAGgIADQgHAEgIAAQgMAAgKgFgAgRgLQgHADgFAFQgEAEgDAIQgDAIAAAKQAAAKACAJQADAHAFAGQAFAGAHACQAGAEAJAAQAIAAAGgEQAHgCAFgGIAAhAQgGgEgHgDQgIgCgGAAQgIABgGACg");
	this.shape_19.setTransform(87.55,201.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgaBXIAAgTIAQAAIAAiHIgQAAIAAgTIAkAAIAACaIASAAIAAATg");
	this.shape_20.setTransform(76.7,201.775);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgbBWIAAgUIARAAIAAhMIgRAAIAAgUIAlAAIAABgIASAAIAAAUgAgFg5IgFgDIgDgFIgBgFIABgGIADgEIAFgEIAFgBIAFABIAFAEIADAEIABAGIgBAFIgDAFIgFADIgFACg");
	this.shape_21.setTransform(69.375,201.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AALBXIAAgTIAQAAIAAg1QAAgOgHgFQgHgHgNAAQgFAAgIADQgIADgGAFIAABEIARAAIAAATIg3AAIAAgTIASAAIAAiHIgQAAIAAgTIAkAAIAABHIABAAIAHgGIAJgFIAJgDIAJgBQAKAAAHACQAIADAEAFQAGAFADAJQACAHAAALIAAA4IASAAIAAATg");
	this.shape_22.setTransform(58.1,201.775);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgSA5QgLgFgHgIQgIgIgEgLQgEgMAAgNQAAgNAEgLQAEgLAIgIQAIgJAKgEQAKgFALAAQALAAAKAEQAKAEAHAIIAMAAIAAATIgVAAQgFgJgHgDQgHgEgKAAQgHAAgFADQgHADgFAFQgEAGgDAIQgDAIAAAJQAAAKADAHQADAIAEAGQAFAFAHADQAFADAHAAQALAAAHgFQAJgFAFgKIARAIQgDAIgFAFQgFAGgGAEQgHAEgIACQgHADgIAAQgLAAgKgFg");
	this.shape_23.setTransform(44.15,204.675);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgpA7IAAgUIARAAIAAhNIgRAAIAAgTIAmAAIAAAQIADgGIAFgGIAIgEIAIAAIALAAIAKAAIAAAZIgVAAIAAgHIgIABQgEABgEAEQgCACgDAEIgDALIAAA3IATAAIAAAUg");
	this.shape_24.setTransform(27.35,204.65);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgXA5QgKgFgIgHQgHgJgFgLQgEgMAAgNQAAgNAEgMQAFgLAHgIQAIgIALgEQALgFALAAQANAAALAFQALAEAHAIQAIAIAEALQAEAMAAANQAAANgEAMQgEALgIAIQgHAIgLAFQgLAEgNABQgMgBgLgEgAgNgoQgGADgFAFQgFAGgDAIQgDAJAAAJQAAAKADAIQADAIAFAFQAFAHAGACQAHAEAGAAQAIAAAHgEQAGgDAFgFQAFgGADgIQADgIAAgKQAAgJgDgJQgDgIgFgGQgEgFgHgDQgHgCgIgBQgGABgHACg");
	this.shape_25.setTransform(15.075,204.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgpBXIAAgTIASAAIAAhPIgUAAIAAgRIAUAAIAAgSQAAgKACgIQADgHAFgGQAFgFAGgCQAHgCAIAAIALAAIAJACIAGACIAFACIgGAPIgJgDQgHgCgGAAQgJAAgFAGQgFAGAAALIAAATIAaAAIAAARIgaAAIAABPIASAAIAAATg");
	this.shape_26.setTransform(5.3,201.775);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgKA9IgJgBIgHgEIgGgEIgVAAIAAgfIAgAAIAAABQAAADACACIAFAFIAHACIAIAAQAKABAEgDQAFgDAAgEQAAgDgCgDQgDgBgFgCIgVgEQgUgFgLgIQgKgJAAgOQAAgJAEgGQAEgIAHgEQAGgFAKgDQAJgDAKAAIALABIAKADIAIACIAGAEIATAAIAAAgIgdAAQAAgDgBgDIgFgDIgJgDIgKgCIgFAAIgFACIgEADQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIAAADIACACIADACIAFABIAUAFQAMACAHADQAIAEAFADQAFAFACAFQACAGAAAGQAAAKgFAIQgFAHgHAFQgIAFgJADQgKADgJgBg");
	this.shape_27.setTransform(165.275,175.75);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AA9A7IAAhBQAAgKgFgGQgFgGgJAAQgHAAgFADQgGADgFAIIAAACIAAADIAAAlIARAAIAAAfIg1AAIAAhCIgBgIQgBgEgDgDIgGgEIgIgCQgGAAgGADQgGACgFAHIAAAsIATAAIAAAfIhJAAIAAgfIASAAIAAg1IgSAAIAAgfIA2AAIAAAKQAHgGAJgDQAJgDAJAAQAOAAAJAEQAJAFAFAJIAIgHIAKgGIALgEIAMgBQAWAAALALQALAMAAAXIAAAoIARAAIAAAfg");
	this.shape_28.setTransform(147.375,175.775);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgiA6QgIgDgFgFQgHgFgCgHQgDgGAAgIQAAgJADgGQADgIAGgDQAFgFAJgCQAJgDALgBIANACIAMACIAAgEQAAgEgCgDQgCgEgCgCIgHgDIgJgBQgKAAgIACQgJACgHAEIgLgWQALgIANgEQANgEAOAAQAJAAAKACQAJADAHAFQAHAGADAJQAEAJAAAMIAAApIAPAAIAAAfIgwAAIAAgGIgHAEIgGADIgHACIgHAAQgLAAgIgDgAgTALIgEACIgEAEIgBAFQABAGADADQAEADAIABQAHAAAGgEQAGgCAFgDIAAgQIgaAAg");
	this.shape_29.setTransform(127.6,175.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAHA6IAAgfIAHAAIgOgNIgOANIAHAAIAAAfIg2AAIAAgfIALAAIAdgbIgbgaIgNAAIAAgfIA2AAIAAAfIgFAAIANAMIAMgMIgGAAIAAgfIA3AAIAAAfIgNAAIgbAaIAdAbIALAAIAAAfg");
	this.shape_30.setTransform(113.85,175.875);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgWA5QgMgFgIgIQgIgJgEgLQgFgMAAgMQAAgMAFgMQAEgLAIgIQAJgIALgFQALgFANAAQANAAALAEQALAFAHAIQAHAIAEALQAEALAAAMIABAFIAAAFIhVAAIAAAEQACAFADAEQACAEAFACIAIAEIAJABIAKAAIAJgCIAIgCIAIgDIANAXIgMAGIgLAFIgLACIgOABQgOAAgMgFgAAYgOIgDgIIgEgFQgCgDgEgCQgEgBgGAAQgGAAgEABQgEACgDADIgFAGIgDAHIAwAAg");
	this.shape_31.setTransform(100.125,175.775);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgWA5QgMgFgIgIQgIgJgEgLQgFgMAAgMQAAgMAFgMQAEgLAIgIQAJgIALgFQALgFANAAQANAAALAEQALAFAHAIQAHAIAEALQAEALAAAMIABAFIAAAFIhVAAIAAAEQACAFADAEQACAEAFACIAIAEIAJABIAKAAIAJgCIAIgCIAIgDIANAXIgMAGIgLAFIgLACIgOABQgOAAgMgFgAAYgOIgDgIIgEgFQgCgDgEgCQgEgBgGAAQgGAAgEABQgEACgDADIgFAGIgDAHIAwAAg");
	this.shape_32.setTransform(82.225,175.775);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgsBVIAAgfIAUAAIAJgWIglhVIgMAAIAAgfIA6AAIAAAfIgJAAIAPAsIARgsIgKAAIAAgfIA6AAIAAAfIgNAAIgtBrIAUAAIAAAfg");
	this.shape_33.setTransform(68.825,178.525);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgWA5QgMgFgIgIQgIgJgEgLQgFgMAAgMQAAgMAFgMQAEgLAIgIQAJgIALgFQALgFANAAQANAAALAEQALAFAHAIQAHAIAEALQAEALAAAMIABAFIAAAFIhVAAIAAAEQACAFADAEQACAEAFACIAIAEIAJABIAKAAIAJgCIAIgCIAIgDIANAXIgMAGIgLAFIgLACIgOABQgOAAgMgFgAAYgOIgDgIIgEgFQgCgDgEgCQgEgBgGAAQgGAAgEABQgEACgDADIgFAGIgDAHIAwAAg");
	this.shape_34.setTransform(55.025,175.775);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgtBZIAAgfIARAAIAAg4IgRAAIAAgdIARAAIAAgTQAAgKAEgIQAEgIAGgFQAGgFAHgDQAIgDAIAAIALABIAJADIAHADIAEADIgMAYIgHgDIgIgBIgFABIgFADIgDAEIgBAHIAAAQIAVAAIAAAdIgVAAIAAA4IAVAAIAAAfg");
	this.shape_35.setTransform(40.2,172.825);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgYA5QgMgGgIgIQgIgIgFgLQgEgLAAgNQAAgMAEgLQAFgLAIgIQAIgJAMgFQAMgEAMAAQAOAAALAEQAMAFAHAJQAIAIAGALQAEALAAAMQAAANgEALQgFALgIAIQgJAIgLAGQgLAEgOAAQgNAAgLgEgAgKgbQgFACgEAEQgEAEgCAFQgCAGgBAGQABAGACAGQACAFAEAFQAEAEAFACQAFACAFAAQAGAAAFgCQAFgCAEgEIAGgKQACgGAAgGQAAgGgCgGQgDgFgDgEQgEgEgFgCQgFgCgGAAIgBAAQgFAAgEACg");
	this.shape_36.setTransform(27.8,175.85);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgCBPQgFgCgGgEQgEgGgDgHQgCgHgBgKIABgyIgRAAIAAgeIARAAIAAgbIAigRIAAAsIAXAAIAAAeIgXAAIAAAwIAAAHIACAEIADADIAEAAIAIAAIAHgDIAEAWQgGAEgGABQgIADgJAAQgHAAgGgDg");
	this.shape_37.setTransform(178.85,145);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgKA9IgJgBIgHgEIgGgEIgVAAIAAgfIAgAAIAAABQAAADACACIAFAFIAHACIAIAAQAKABAEgDQAFgDAAgEQAAgDgCgDQgDgBgFgCIgVgEQgUgFgLgIQgKgJAAgOQAAgJAEgGQAEgIAHgEQAGgFAKgDQAJgDAKAAIALABIAKADIAIADIAGADIATAAIAAAgIgdAAQAAgDgBgDIgFgDIgJgDIgKgCIgFAAIgFACIgEADQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIAAADIACACIADACIAFABIAUAFQAMACAHADQAIAEAFADQAFAFACAFQACAGAAAGQAAAKgFAIQgFAHgHAFQgIAFgJADQgKADgJgBg");
	this.shape_38.setTransform(168.375,146.95);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgYA5QgMgGgIgIQgIgIgFgLQgEgLAAgNQAAgMAEgLQAGgLAIgIQAIgJALgFQALgEANAAQANAAAMAEQALAFAJAJQAHAIAFALQAFALAAAMQAAANgFALQgEALgIAIQgJAIgKAGQgMAEgOAAQgNAAgLgEgAgKgbQgFACgEAEQgEAEgCAGQgCAFAAAGQAAAGACAGQACAFAEAFQAEAEAFACQAFACAFAAQAGAAAFgCQAFgCAEgEIAGgKQACgGAAgGQAAgGgCgFQgCgGgEgEQgEgEgFgCQgFgCgGAAIgBAAQgFAAgEACg");
	this.shape_39.setTransform(155.45,147.05);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgXA5QgLgFgIgJQgJgIgEgLQgEgMgBgMQAAgNAGgLQAEgLAIgIQAIgIALgFQAMgFAMABQAJgBAJADQAJADAJAFIAVAAIAAAiIgeAAQgFgGgGgDQgGgEgIABQgFgBgGADQgFACgEAEQgEAEgDAGQgBAFAAAGQgBAGADAGQACAFAEAEQAEAEAFACQAGADAFAAQAFAAAEgCQAFgCADgDIAGgGIADgGIAgAIQgDAHgEAHQgEAIgIAGQgIAGgKAEQgKAEgNAAQgMAAgMgFg");
	this.shape_40.setTransform(142.05,147.0464);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgWA5QgMgFgIgIQgIgJgEgLQgFgMAAgMQAAgMAFgMQAEgLAIgIQAJgIALgFQALgFANAAQANAAALAEQALAFAHAIQAHAIAEALQAEALAAAMIABAFIAAAFIhVAAIAAAEQACAFADAEQACAEAFACIAIAEIAJABIAKAAIAJgCIAIgCIAIgDIANAXIgMAGIgLAFIgLACIgOABQgOAAgMgFgAAYgOIgDgIIgEgFQgCgDgEgCQgEgBgGAAQgGAAgEABQgEACgDADIgFAGIgDAHIAwAAg");
	this.shape_41.setTransform(123.825,146.975);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AAUBXIAAhAQAAgKgEgGQgFgFgIAAQgEAAgGACQgGADgGAGIAAArIARAAIAAAfIhFAAIAAgfIASAAIAAhwIgSAAIAAgeIA0AAIAABFQAHgGAIgEQAHgDAJAAQAVAAALAMQALALAAAWIAAApIARAAIAAAfg");
	this.shape_42.setTransform(109.625,144.175);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgBBPQgHgCgEgEQgFgGgDgHQgCgHAAgKIAAgyIgRAAIAAgeIARAAIAAgbIAigRIAAAsIAXAAIAAAeIgYAAIAAAwIABAHIACAEIADADIAFAAIAHAAIAGgDIAFAWQgFAEgIABQgGADgKAAQgHAAgFgDg");
	this.shape_43.setTransform(96.9,145);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgKA9IgJgBIgHgEIgGgEIgVAAIAAgfIAgAAIAAABQAAADACACIAFAFIAHACIAIAAQAKABAEgDQAFgDAAgEQAAgDgCgDQgDgBgFgCIgVgEQgUgFgLgIQgKgJAAgOQAAgJAEgGQAEgIAHgEQAGgFAKgDQAJgDAKAAIALABIAKADIAIADIAGADIATAAIAAAgIgdAAQAAgDgBgDIgFgDIgJgDIgKgCIgFAAIgFACIgEADQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIAAADIACACIADACIAFABIAUAFQAMACAHADQAIAEAFADQAFAFACAFQACAGAAAGQAAAKgFAIQgFAHgHAFQgIAFgJADQgKADgJgBg");
	this.shape_44.setTransform(81.825,146.95);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("Ag0A6IAAgfIARAAIAAg1IgRAAIAAgfIA0AAIAAAIQAEgEAGgCQAGgCAHAAIAQAAIAOAAIAAAqIgfAAIAAgMIgJABIgGACIgFAEQgCADAAADIAAApIAXAAIAAAfg");
	this.shape_45.setTransform(69.525,147.075);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgWA5QgMgFgIgIQgIgJgEgLQgFgMAAgMQAAgMAFgMQAEgLAIgIQAJgIALgFQALgFANAAQANAAALAEQALAFAHAIQAHAIAEALQAEALAAAMIABAFIAAAFIhVAAIAAAEQACAFADAEQACAEAFACIAIAEIAJABIAKAAIAJgCIAIgCIAIgDIANAXIgMAGIgLAFIgLACIgOABQgOAAgMgFgAAYgOIgDgIIgEgFQgCgDgEgCQgEgBgGAAQgGAAgEABQgEACgDADIgFAGIgDAHIAwAAg");
	this.shape_46.setTransform(56.625,146.975);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgRA6IgjhUIgNAAIAAggIA9AAIAAAgIgOAAIASAwIASgwIgNAAIAAggIA9AAIAAAgIgQAAIgiBUg");
	this.shape_47.setTransform(43.05,147.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgZA5QgLgGgIgIQgIgIgEgLQgFgLAAgNQAAgMAFgLQAFgLAHgIQAJgJALgFQAMgEAMAAQAOAAALAEQALAFAIAJQAIAIAGALQAEALAAAMQAAANgEALQgFALgIAIQgJAIgLAGQgLAEgOAAQgNAAgMgEgAgKgbQgFACgEAEQgEAEgCAGQgCAFgBAGQABAGACAGQACAFAEAFQAEAEAFACQAFACAFAAQAGAAAFgCQAFgCAEgEIAGgKQACgGAAgGQAAgGgCgFQgDgGgDgEQgEgEgFgCQgFgCgGAAIgBAAQgFAAgEACg");
	this.shape_48.setTransform(29.05,147.05);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgXA5QgLgFgIgJQgJgIgEgLQgFgMABgMQAAgNAEgLQAFgLAIgIQAJgIALgFQALgFAMABQAKgBAJADQAIADAIAFIAXAAIAAAiIggAAQgEgGgGgDQgGgEgIABQgGgBgFADQgGACgDAEQgEAEgCAGQgCAFgBAGQAAAGADAGQACAFAEAEQAEAEAFACQAFADAGAAQAFAAAFgCQAEgCADgDIAGgGIAEgGIAeAIQgCAHgEAHQgEAIgIAGQgIAGgKAEQgKAEgOAAQgMAAgLgFg");
	this.shape_49.setTransform(15.65,147.0464);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AALBXIAAgTIAQAAIAAg1QAAgOgHgFQgHgHgNAAQgFAAgIADQgIADgGAFIAABEIARAAIAAATIg3AAIAAgTIASAAIAAiHIgQAAIAAgTIAkAAIAABHIABAAIAHgGIAJgFIAJgDIAJgBQAKAAAHACQAIADAEAFQAGAFADAJQACAHAAALIAAA4IASAAIAAATg");
	this.shape_50.setTransform(171.95,115.375);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgBBMQgFgCgEgEQgEgEgCgHQgCgIAAgLIABg/IgTAAIAAgRIATAAIAAgbIATgKIAAAlIAbAAIAAARIgbAAIAABCQAAAHABAFQACADADACQAEACAEAAIAIgBIAIgDIAFAOIgLAEQgGACgIAAQgIAAgFgCg");
	this.shape_51.setTransform(159.925,116.55);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgbBXIAAgTIARAAIAAiHIgRAAIAAgTIAlAAIAACaIARAAIAAATg");
	this.shape_52.setTransform(152,115.375);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AgdA6QgHgCgFgFQgFgFgDgGQgDgGAAgHQAAgHACgGQACgGAEgEQAEgEAFgCIAKgFIALgCIAKgBIANABIAKABIAAgKQAAgGgCgEQgBgFgEgDQgDgDgFgBQgEgCgFAAIgKABIgJACIgIADIgGADIgGgPIAJgFIAKgEIALgCIALgBQAJAAAIACQAJADAFAFQAGAFADAIQADAHAAALIAAA5IANAAIAAAUIgiAAIAAgLQgHAGgIAEQgHAEgKAAQgJAAgHgDgAgPAGQgFABgEADQgEACgCAEQgCAEAAAFQAAAFACADQACAEADACQADACAEABIAKABIAIgBIAHgCIAHgEIAFgFIAAgaIgXAAIgLABg");
	this.shape_53.setTransform(141.725,118.325);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgTA5QgKgDgHgJQgHgHgEgLQgEgMAAgPQAAgMADgLQAEgLAHgJQAGgHALgFQAKgGAMAAQAOAAAIAFQAJAEAGAGQAFAHADAIQADAJABAIIABAJIAAAHIhTAAIABAJIACAIQAEAMAJAFQAKAGAKAAQAJAAAJgDQAIgCAKgGIAIAPQgLAHgMAEQgLAFgNAAQgLAAgKgFgAAegNIgCgMQgCgGgDgEQgEgEgFgCQgFgCgIAAQgGAAgGACQgFACgEAEQgEAEgCAGQgDAFgBAHIA8AAg");
	this.shape_54.setTransform(128.775,118.3);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AAgBVIAAgTIARAAIAAg9IhhAAIAAA9IARAAIAAATIg4AAIAAgTIAQAAIAAiDIgQAAIAAgTIA4AAIAAATIgRAAIAAA0IBhAAIAAg0IgRAAIAAgTIA4AAIAAATIgRAAIAACDIARAAIAAATg");
	this.shape_55.setTransform(112.2,115.575);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgdA6QgHgCgFgFQgFgFgDgGQgDgGAAgHQAAgHACgGQACgGAEgEQAEgEAFgCIAKgFIALgCIAKgBIANABIAKABIAAgKQAAgGgCgEQgBgFgEgDQgDgDgFgBQgEgCgFAAIgKABIgJACIgIADIgGADIgGgPIAJgFIAKgEIALgCIALgBQAJAAAIACQAJADAFAFQAGAFADAIQADAHAAALIAAA5IANAAIAAAUIgiAAIAAgLQgHAGgIAEQgHAEgKAAQgJAAgHgDgAgPAGQgFABgEADQgEACgCAEQgCAEAAAFQAAAFACADQACAEADACQADACAEABIAKABIAIgBIAHgCIAHgEIAFgFIAAgaIgXAAIgLABg");
	this.shape_56.setTransform(90.375,118.325);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AgBBMQgFgCgEgEQgEgEgCgHQgCgIAAgLIABg/IgTAAIAAgRIATAAIAAgbIATgKIAAAlIAbAAIAAARIgbAAIAABCQAAAHABAFQACADADACQAEACAEAAIAIgBIAIgDIAFAOIgLAEQgGACgIAAQgIAAgFgCg");
	this.shape_57.setTransform(80.025,116.55);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgpA7IAAgUIARAAIAAhNIgRAAIAAgTIAlAAIAAAQIAEgGIAFgGIAHgEIAJAAIAKAAIALAAIAAAZIgVAAIAAgHIgIABQgEABgEAEQgDACgCAEIgDALIAAA3IATAAIAAAUg");
	this.shape_58.setTransform(70.3,118.25);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgTA5QgKgDgHgJQgHgHgEgLQgEgMAAgPQAAgMADgLQAEgLAHgJQAGgHALgFQAKgGAMAAQAOAAAIAFQAJAEAGAGQAFAHADAIQADAJABAIIABAJIAAAHIhTAAIABAJIACAIQAEAMAJAFQAKAGAKAAQAJAAAJgDQAIgCAKgGIAIAPQgLAHgMAEQgLAFgNAAQgLAAgKgFgAAegNIgCgMQgCgGgDgEQgEgEgFgCQgFgCgIAAQgGAAgGACQgFACgEAEQgEAEgCAGQgDAFgBAHIA8AAg");
	this.shape_59.setTransform(58.125,118.3);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgLBWQgHgDgFgEIAAAHIgVAAIAAiaIgRAAIAAgTIAmAAIAABEQAHgGAJgEQAIgDAJAAQALAAAKAEQAJAFAIAHQAGAIAEAKQAEALAAANQAAAOgFALQgDAMgIAIQgIAIgKAFQgKAEgNAAQgIAAgIgCgAgLgKQgHADgFAGIAAA+QADADAHADQAHADAJAAQAIAAAHgDQAGgCAFgGQAGgFADgIQACgIAAgLQAAgKgCgIQgDgHgFgFQgFgFgGgDQgHgCgIAAQgHAAgIADg");
	this.shape_60.setTransform(44.65,115.475);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AgaBXIAAgTIAQAAIAAiHIgQAAIAAgTIAkAAIAACaIARAAIAAATg");
	this.shape_61.setTransform(34.15,115.375);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AAfBVIAAgTIAOAAIgOgnIhAAAIgOAnIASAAIAAATIg4AAIAAgTIAQAAIA1iWIAfAAIA1CWIARAAIAAATgAAYAJIgZhLIgaBLIAzAAg");
	this.shape_62.setTransform(21.7,115.575);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-2.1,100,196.79999999999998,147), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,0,0);


(lib.logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol6();
	this.instance.parent = this;
	this.instance.setTransform(551.4,185.65,1,1,0,0,0,13.2,13.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(125).to({_off:false},0).to({alpha:1},14).wait(76).to({_off:true},1).wait(294));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A7iQiIAAmbIBJAAIAAA0IAEgGIAOgSIAYgTIAHgEIAOgGIAQgFIAWgDIAaABIAjAKIAGADIATALIAXATIATAXIAOAeIAIAXIAFAvIgFAuIgIAYIgKAWIgNATIgVAUIgMAJIggAQIgVAFIgVADIgagBIgYgFIgVgKIgMgIIgQgPIgOgQIAACQgA5OK/IgMADIgFACIgMAFIgLAIIgHAGIgJALIgDADIgKARIgGATIgDAQIAAAXIADAQIAGATIAKARIAJALIAOAMIALAIIARAGIAEABIAEABIAOABIAOgBIAEgBIAEgBIARgGIAIgFIAOgMIAMgOIAHgMIAJgYIACgQIAAgXIgCgRIgJgXIgHgNIgPgRIgLgIIgMgGIgRgGIgOgBgEAl6AQfIgegEIgrgQIgCgCIonk8IIqklIACgBIAngMIAkgFIAsAAIAmAHIAZAJIIQEpIhhA4Imkj9IgCgBIgVgMIgngNIgegEIgeABIgSACIhCAYIlnDGIF9DhIABABIAKAFIAmAMIAfABIAIgBIAjgJIAQgHID9iWIj9iTIgBgBIgJgFIgQgFIgSgFIgUgBIgQACIgxAQIgBABIjUB7Ihng1IEtifIA4gUIAOgDIAHgBIAhACIAWAEIAHADIAGACIASAIIGdDsImiDyIgBACIgeALIgNAFIgfAEgAWZPHIgRgDIgjgLIgZgLIgfgUIAhgyIATANIAaAOIAnAKIANABIAWgBIAFgBIAMgEIAHgEIAFgFIADgGIACgIIAAgIIgBgHIgCgDIgBgBIgFgFIgRgLIhjgiIgLgGIgEgEIgNgLIgIgKIgIgRIgCgKIgBgWIABgLIAEgOIACgFIABgFIALgQIADgEIADgEIAQgNIASgJIAFgCIAagHIAuAAIAmAIIAeAMIAbAPIgcAyIgjgRIgSgHIgcgGIgQgBIgOADIgLAEIgFAFIgFAFIgDAHIgBAGIAAAJIABACIAAABIABACIABADIABABIACACIADADIAEADIAUAKIBCAWIAhARIALAIIAKAJIAKAOIAFAMIABAFIACAFIABAPIgBASIgEAQIgEAJIgIAOIgDAEIgLALIgVAOIgPAGIgWAFIgYADgASlPHIgNgDIgQgHIgHgEIgGgGIgIgJIgJgPIgGgTIgCgRIAAizIgqAAIAAg9IAqAAIAAhZIBIAAIAABZIBWAAIAAA9IhWAAIAAChIABAIIAFALIACACIAFAGIADACIADABIAHACIANABIAdgDIAPgFIAAA6IgJAGIgTAHIgaAEgAOPPJIgjgFIgSgEIgZgKIghgRIgPgLIAigyIAfAVIANAGIAnAKIAZABIAKgBIAFgBIAQgGIAIgHIACgDIACgDIABgEIAAgEIAAgKIgBgFIgCgDIgBgBIgEgFIgIgFIgQgIIhTgcIgUgKIgNgMIgIgKIgIgQIgCgEIgCgKIgBgQIABgRIAEgOIAEgKIAHgNIAJgLIAEgEIALgJIASgJIAZgHIARgDIATAAIAfAEIAXAFIAxAXIAGAEIgcAyIgugWIghgIIgPgBIgGABIgJACIgLAEIgCADIgDACIgEAFIgCAEIgCAGIAAAEIAAAFIACAIIAGAJIAIAGIAPAHIBbAiIAPAKIANAMIAIAKIACADIAGANIACAKIABAJIgBAYIgEAQIgEAJIgIAOIgDAEIgKALIgJAGIgEADIgEADIgUAIIgWAFIgYADgAD9PHIgNgDIgQgHIgKgGIgMgNIgDgDIgIgRIgDgJIgDgWIAAizIgnAAIAAg9IAnAAIAAhZIBIAAIAABZIBWAAIAAA9IhWAAIAAClIACAIIACADIACAEIABACIAFAGIADACIAHACIARACIASgBIAdgHIAAA6IgHAEIgPAHIgIACIgbAEgAhOPEIgQgEIgcgNIgHgEIgXgTIgLgMIgNgTIgKgVIgIgYIgFgrIAHgyIAFgPIAWgpIAagcIASgNIAcgMIAQgFIAXgDIASAAIAjAGIAWAIIAOAHIAYATIAOASIAQAaIAKAfIAFAXIADA2IjpAAIACAOIAGARIAIAOIARARIADADIAHAEIAPAHIAMACIAJABIAEABIAVAAIALgCIAQgFIAFgDIAPgIIAagUIAqAmIgMAOIgcAVIgPAIIgaAKIgcAFIgeABgAg9K9IgMACIgHAEIgMAHIgLALIgKANIgJASIgHAbICjAAIgDgSIgIgWIgJgOIgKgLIgIgHIgGgEIgLgFIgQgCIgIgBgAwIPEIgngOIgVgOIgdgbIgFgGIgWgpIgIggIgCgZIACgZIAIghIAWgqIAigiIAVgNIAfgMIAQgFIAagDIATAAIAaADIAQAFIAfAMIAVANIAMALIAWAXIANAVIAJAVIAJAhIABAQIgBAhIgEAQIgOAlIgNAUIgWAYIgTAPIgdAPIggAJIgJACIgkACgAv2LBIgOAFIgRAKIgLAJIgGAHIgLAQIgEAJIgIAdIgBAKIABAUIADAPIACAFIAKAWIADAEIAMAPIAEACIAHAHIAMAIIAJADIATAGIAPABIARgBIATgGIAVgLIAOgNIAMgPIACgFIACgDIAGgOIAEgUIABgUIgCgQIgJgcIgLgQIgGgIIgWgSIgFgCIgEgCIgJgDIgEgCIgKgCIgVgBgAz1PJIgXgDIgIgCIgIgDIgPgIIgHgGIgIgJIgHgLIgEgJIgEgOIgCgRIgBizIgmAAIAAg9IAmAAIAAhZIBJAAIAABZIBWAAIAAA9IhWAAIAAChIAAAEIACAIIADAHIAFAFIAFAFIADABIAIACIANABIAdgDIASgFIAAA6IgPAIIgPAFIgbAEgEgtiAPJIgjgFIgfgLIgIgDIgagSIgGgGIgRgRIgKgMIgPgcIgDgHIgFgQIgEgYIABgqIADgQIAIgYIAPgdIAFgGIAQgSIAZgVIANgIIAfgMIAZgGIAkgCIArAIIAfAMIAbASIAWAXIASAbIANAdIAGAhIABAZIgDAYIgRAtIgNAUIgVAYIgTAPIgdAPIgQAGIgrAHgEgtzALBIgOAFIgIAEIgXASIgGAIIgKAQIgIAYIgBAEIgBAaIABAKIADAPIAFAOIAJARIAJALIALAKIAQALIAJADIATAGIAPABIAagDIAOgFIARgKIAHgHIAEgCIAMgPIAFgJIAHgRIAEgOIACgVIgCgVIgKgcIgQgYIgXgSIgIgEIgJgDIgFgCIgKgCIgUgBgEggoAPIIgigGIgVgGIgdgNIgTgLIgYgTIgWgXIgMgQIgPgbIgOgnIgGggIAAguIAGgfIAGgVIASglIASgaIAVgWIAZgUIAmgVIAggKIAWgEIAkgDIAuAFIAqAMIAdAOIAZATIAXAVIATAZIAPAbIAIATIAKAqIADAhIgDAhIgKAqIgIATIgPAbIgaAhIgYAUIgbARIgeANIg4AMgEggoAJbIgcAIIgGACIgTAKIgLAIIgPAPIgNAQIgLASIgKAbIgDAOIgDAXIAAAPIADAYIADAOIALAbIAPAYIAOAPIAWASIATAJIAVAIIAWADIAPABIAXgCIAVgEIAUgIIAGgEIALgHIAQgOIAOgPIAMgRIAGgNIAJgbIADgVIABgZIgBgIIgFgcIgIgVIgGgNIgQgXIgagYIgGgEIgagNIgVgGIgPgCIgeAAgAKMPDIAAk8IBIAAIAAE8gAGaPDIAAk8IBIAAIAABFIATggIAPgRIAHgFIADgDIAMgGIADgDIAVgIIAOgDIAUgBIAABOIgiADIgUAHIgKAEIgQAOIgLALIgLAUIgEALIgFATIgDAkIAAB6gAlUPDIgBjGIgEgQIAAgDIgEgKIgKgOIgHgGIgCgCIgDgCIgDgBIgDgBIgDgBIgDgBIgDgBIgDgBIgIgBIgEAAIgDgBIgEABIgDAAIgOADIgKADIgDABIgCACIgDACIgDACIgIAHIgIALIgCADIgCAEIgBADIgBADIgCAEIgCAIIgBAJIgBADIAAC+IhIAAIAAi0IgCgaIgEgOIgCgEIgBgDIgCgDIgCgDIgDgFIgKgJIgCgCIgDgCIgDgBIgDgBIgDgBIgDgBIgDgBIgDgBIgIgBIgDAAIgEgBIgEABIgDAAIgHABIgNAEIgJAFIgFAEIgJAKIgGAJIgFAKIgEAQIgCAMIAAC7IhLAAIAAk8IBLAAIAAAvIAEgFIARgVIAKgJIAMgIIANgGIAOgEIAUgDIAVABIAQADIAbALIAPANIAJAKIAIALIADAHIAFgHIAXgVIATgNIAdgLIAQgDIAXgBIAYADIARAFIAOAHIAEADIAJAHIAIAHIAMARIALAbIAGAgIAADZgEgphAPDIAAj/IgqAAIAAg9IAqAAIAAgkIAGghIAEgJIABgEIAIgMIAJgKIATgMIANgFIAPgEIAWgBIAnADIATAGIAAA9IgKgEIgQgDIgUgBIgFAAIgMAEIgEABIgFAFIgFAHIgDAIIgDAPIAAAaIBTAAIAAA7IhTAAIAAD/gEAl4AOiIgTgEIgSgGIgRgJIgQgLIgRgSIgLgPIgJgSIgGgSIgEgUIAAgcIAEgSIAGgTIAJgRIAPgUIANgNIAQgLIARgJIAMgEIAZgFIAUgBIAiAGIAYAKIAFADIAQALIAOANIAPAUIAJARIAIAZIACAUIAAANIgCAVIgIAYIgDAGIgJASIgRATIgOANIgWANIgMAFIgTAFIgbACgEAnSAEzIgHgCIgZgGIgjgCIgSABIgbAGIgRAHIpOEsIAA6EIUAAAIAAaEgAKJJUIAAhFIBOAAIAABFgAP0F1IgRgEIgXgJIgOgIIgUgNIgRgRIgKgMIgQgcIgGgOIgGgXIgDghIABgTIAEgYIALgeIAVghIALgMIAZgUIAdgPIAYgIIAigGIASAAIAjAGIAYAHIAPAHIAVANIAXAVIAUAZIAKAVIAIAXIAFAhIAAARIgFAhIgIAYIgKAVIgKANIgVAYIgiAXIgnAPIgSAEIgbACgAP9BxIgOAEIgMAHIgLAIIgMANIgIANIgEAIIgEAOIgEAZIACAZIABAEIABAGIALAbIAJALIANANIAEAEIAMAHIATAHIAUAEIALAAIAFgBIALgBIAJgDIARgIIAIgEIAOgMIAIgMIADgDIAIgSIAFgYIABgSIgBgPIgDgOIgDgKIgGgMIgFgIIgPgSIgQgKIgEgDIgEgCIgOgEIgVgEIgLAAgADEF0IgVgGIgEgDIgFgCIgNgIIgEgDIgOgOIgJgNIgGgOIgEgPIgBgSIABgSIABgHIAFgQIAFgJIAJgNIAMgLIANgKIAPgHIAFgCIAGgCIALgDIAmgFIBDAGIAdAGIAAgOIgDgPIgBgDIgBgDIgIgPIgFgEIgNgJIgHgEIgWgFIgZgBIgkAEIgRAEIggAMIgTg7IAGgDIAhgNIAdgHIAqgFIAjABIAkAIIAMAGIARAJIASARIAEAEIAKAQIAIASIAEANIADAWIABDRIhFAAIAAgnIgEAFIgaAXIgTAJIgVAHIghAEgAD0DgIgVAFIgLAFIgKAHIgFAFIgCADIgDADIgDAIIAAACIgBADIAAADIgBACIAAAGIABADIAAACIABADIAAADIACAEIABADIAGAIIAHAGIAJAGIAQAFIAMACIAPAAIANgCIALgDIAPgGIAGgEIADgCIADgCIAKgJIACgEIACgCIACgDIAEgJIACgHIABgEIABgDIAAgYIgYgIIgmgFgAj8F3IgYgGIgegMIgagSIgRgRIgKgMIgMgVIgKgVIgGgXIgDghIAAgLIADgYIAJgfIAHgOIARgaIAWgXIAagSIAOgGIAYgIIAhgGIApACIAjAKIAXALIAaATIAMAMIgtAyIgEgFIgWgSIgggOIgTgDIgVABIgJADIgNAEIgQAJIgQAQIgKAQIgGAMIgHAdIAAAVIAFAZIAIASIAHANIAGAHIAEADIADADIALAJIAMAHIAOAEIAUAEIAEAAIAUgCIARgFIAPgIIAPgJIARgQIAtAtIggAdIgnAUIgcAHIggADgAp/F3IgagGIgmgRIgTgNIgSgRIgPgSIgSgkIgGgXIgDgQIAAgkIADgQIAJgfIAPgcIAKgMIARgRIAZgTIAXgLIAYgIIAigGIASAAIAjAGIAYAHIAdAPIANAJIARARIAPASIAPAcIAGAPIAGAgIAAAiIgGAhIgGAQIgLAVIgTAaIgRAQIgUAOIgeAOIghAJIgbACgAp/BxIgOAEIgIAFIgQAKIgNANIgHANIgLAbIAAAEIgBAFIgBAPIABAQIACAJIAGATIAEAJIALAQIAEADIAGAHIAIAHIAQAJIAOAFIAUAEIAKAAIAVgEIAXgJIAMgHIAKgJIALgPIAJgSIADgJIADgTIAAgYIgCgKIAAgEIgFgPIgEgJIgHgLIgJgMIgHgGIgPgKIgJgFIgOgEIgKgDIgUgBgAvUF3IgjgIIgzgYIgWgRIAegvIAvAaIAUAIIAaAEIASABIAGgBIASgEIAHgFIAGgFIAEgGIACgDIACgIIAAgIIgBgDIgBgEIgCgBIAAgCIgCgCIgDgEIgEgCIgJgGIgKgEIhMgZIgdgPIgKgIIgJgKIgIgLIgGgRIgDgPIAAgMIAFgaIAEgKIAIgMIAGgIIAOgNIAJgGIAEgBIAFgEIAZgIIAcgEIAVABIAfAFIAWAGIAeANIATALIgcA2IgdgRIgXgIIgXgFIgVgBIgKABIgEACIgEAAIgEACIgJAGIgEAFIgDAFIgBADIgBAEIAAAHIACAGIABACIABACIABACIABABIAMAJIAQAIIBBAVIAaAMIATANIAJAJIAJAKIAEAIIAEAMIACAJIAAAZIgGAbIgIAOIgJAMIgLAKIgNAJIgUAIIgcAHIgYACgA0BF2IgagHIgzgYIgXgRIAigvIAmAYIAaAKIAaAEIAYAAIAJgCIAJgCIAHgFIADgCIAFgGIACgDIACgDIACgIIAAgHIgBgBIAAgDIgBgCIAAgCIgDgDIgEgGIgEgCIgJgGIgKgEIhDgWIgagLIgEgCIgIgFIgNgLIgJgKIgCgEIgDgEIgGgRIgCgLIgBgQIABgFIAEgVIAEgKIADgDIACgFIAGgIIANgOIANgJIAEgBIAFgEIAEgCIAagHIAXgDIAVABIAfAFIAWAGIAkAQIANAIIgcA2IgFgEIgYgNIgXgIIgXgFIgLgBIgUABIgIACIgEACIgGAEIgFAEIgCADIgDAFIgBADIgBAEIAAAKIABABIABACIABACIABACIABACIABABIAHAGIAFADIAVAKIA8ATIAaAMIATANIAMAMIAIAKIAGARIADAPIAAANIgCAMIgEAQIgEAKIgHANIgHAIIgLAKIgEADIgdAOIgcAHIgYACgAI7F0IgEgBIgFAAIgIgCIgMgEIgHgEIgKgHIgJgJIgHgLIgBgEIgCgFIgGgUIgBi+IgqAAIAAhAIAqAAIAAhWIBIAAIAABWIBWAAIAABAIhWAAIAAChIADAMIADAIIAHAHIAJAEIAMACIAXgBIAQgEIALgGIAAA7IgHAEIgVAIIgaAFgAXcFwIgBjGIgEgSIgCgDIgBgEIgBgCIgCgDIgIgLIgFgEIgCgBIgDgCIgFgEIgDgBIgEgBIgDgBIgDgBIgQgCIgIAAIgOACIgEABIgDABIgEABIgDABIgDACIgGAEIgIAGIgHAHIgCAEIgEAFIgGAPIgDALIgBAJIAAC7IhIAAIAAk9IBIAAIAAAyIAXgbIAFgEIASgMIAVgIIAYgFIAdABIAXAGIAQAHIASAMIAOAQIAGAJIAIAPIAGAYIADAaIAADPgALdFwIAAk9IBIAAIAAE9gAgdFwIAAk9IBKAAIAAE9gA3WFwIgqhkIjIAAIgqBkIhOAAIC6mmIBGAAIC3GmgA6tDJICRAAIhIimgALaADIAAhDIBNAAIAABDgAgfADIAAhDIBMAAIAABDgAVvjRIglgIIgKgEIgNgHIgIgGIgLgKIgGgIIgIgMIgGgPIgDgQIAAgbIACgLIAFgRIAIgOIADgFIAHgIIALgKIAJgGIAVgKIAXgGIAggEIA4AEIAoAIIAAgKIgCgOIgDgKIgFgIIgGgIIgKgJIgDgBIgDgDIgGgDIgDAAIgEgCIgPgEIgZgBIgpAGIgsAOIgUg6IAwgTIBBgJIAjABIAdAGIAeANIAUAQIAMANIAJARIAJAZIAFAlIAADDIhIAAIAAgoIgJALIgQANIgRAKIgVAIIgfAGgAV7lnIgGACIgLAGIgKAGIgGAFIgDAFIgBACIgBACIgCAGIgCAIIAAALIACAHIACAFIABACIACAEIAHAIIAIAFIAKAFIARAEIARABIAEgBIAEAAIAYgFIAOgHIAJgGIAHgGIAHgJIAGgMIACgGIACgLIAAgVIgHgCIgQgGIgdgEIglAAgAJDjSIgYgEIgXgHIgVgLIgTgMIgQgQIgTgZIgKgWIgJggIgDgjIABgbIAFgXIAIgXIAPgbIAJgMIAWgVIAggUIAXgIIAYgFIAjAAIAhAIIAcAMIASAOIAPAQIAJANIAOAbIALAlIAEBAIjqAAIABAGIABADIABAGIADAIIACADIABAFIAGALIANAPIAGAFIAEACIADADIAKAGIALAEIAVAEIAcgBIAMgCIAQgHIAUgMIATgQIAqAmIgGAHIgaAXIgPAJIgiAOIgnAGgAIxndIgHADIgKAGIgJAIIgOASIgIATIgDAIIgDARICiAAIgDgRIgEgRIgFgKIgGgKIgIgIIgFgGIgNgIIgIgDIgQgEIgNgBIgEAAIgEAAgADSjSIgZgGIgWgKIgSgOIgQgOIgIgLIAAAwIhJAAIAAm4IBJAAIAACvIAEgGIAQgRIAYgSIAWgKIAhgHIAQAAIAVACIAUAGIAUAJIASALIALAJIAPAQIAQAaIAHAOIALAqIABAqIgFAjIgHAXIgLAXIgMASIgKAMIgQAOIgSAMIgUAJIgNADIgVAEIgYABgADCnbIgNAEIgIAEIgTALIgMAOIgIALIgGAOIgHAYIAAAkIAHAZIAGANIAIAMIAJAKIAWAPIAMAFIASAEIATAAIAWgGIAQgIIAKgHIAHgGIADgEIADgDIAMgUIAIgeIAAgkIgCgKIgGgTIgMgUIgDgEIgDgDIgHgHIgKgHIgQgIIgNgEIgTgCgAR6jWIgRgEIgLgFIgKgGIgGgGIgDgCIgJgPIgGgSIgDgQIgBi4IgqAAIAAhAIAqAAIAAhXIBIAAIAABXIBUAAIAABAIhUAAIAACgIADANIADAHIAEAFIAGAEIADACIAEAAIADACIAJABIARgBIALgCIAQgFIAFgDIAAA9IgOAGIghAHgAMwjZIAAk9IBIAAIAABIIAIgRIAPgXIAQgQIAKgHIAUgJIASgFIAOgBIAKAAIAABOIgfADIgFABIgPAGIgOAHIgIAGIgLAMIgJANIgIAQIgHAYIgDAdIAACAgAkJjZIgqhkIjIAAIgqBkIhOAAIC7mnIBFAAIC4GngAnfmBICQAAIhIimgAh2jaIAAm3IBJAAIAAG3g");
	this.shape.setTransform(307.475,105.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(215).to({_off:true},1).wait(294));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,615,211.6);


// stage content:
(lib._300x600_aaoo_girl = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// logo
	this.instance = new lib.logo("synched",0,false);
	this.instance.parent = this;
	this.instance.setTransform(226.35,32,0.192,0.192,0,0,0,308.1,105.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(216));

	// Layer_8
	this.instance_1 = new lib.Symbol5();
	this.instance_1.parent = this;
	this.instance_1.setTransform(84.5,195.2,1,1,0,0,0,64.5,45.3);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(138).to({_off:false},0).to({y:165.2,alpha:1},32,cjs.Ease.quartInOut).wait(46));

	// frame
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#51C4ED").ss(8,1,1).p("EgXbgu3MAu3AAAMAAABdvMgu3AAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(216));

	// Layer_6
	this.instance_2 = new lib.Symbol3();
	this.instance_2.parent = this;
	this.instance_2.setTransform(150,125,1,1,0,0,0,150,125);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(111).to({_off:false},0).to({alpha:1},26,cjs.Ease.cubicIn).wait(79));

	// Layer_5
	this.instance_3 = new lib.Symbol2();
	this.instance_3.parent = this;
	this.instance_3.setTransform(149.95,180.25,1,1,0,0,0,96.2,26.7);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(9).to({_off:false},0).to({y:170.25,alpha:1},41,cjs.Ease.quartInOut).wait(51).to({alpha:0},18).wait(97));

	// Layer_1
	this.instance_4 = new lib.Symbol1();
	this.instance_4.parent = this;
	this.instance_4.setTransform(150,121.55,1,1,0,0,0,66.8,40.6);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({y:111.55,alpha:1},41,cjs.Ease.quartInOut).wait(60).to({alpha:0},18).wait(97));

	// bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#51C4ED").s().p("EgXbAu4MAAAhdvMAu3AAAMAAABdvg");
	this.shape_1.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(216));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(146,296,158,333.20000000000005);
// library properties:
lib.properties = {
	id: 'EA7F868821484FEEB1ACA9412835E0FD',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/300x600_aaoo_girl_atlas_.png", id:"300x600_aaoo_girl_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['EA7F868821484FEEB1ACA9412835E0FD'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;