(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"728x90_bcd_park_atlas_", frames: [[0,443,318,67],[0,0,607,441]]}
];


// symbols:



(lib.docBC = function() {
	this.initialize(ss["728x90_bcd_park_atlas_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.whitedad = function() {
	this.initialize(ss["728x90_bcd_park_atlas_"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.docBC();
	this.instance.parent = this;
	this.instance.setTransform(-159,-33);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-159,-33,318,67);


(lib.Tween1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.docBC();
	this.instance.parent = this;
	this.instance.setTransform(-159,-33);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-159,-33,318,67);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAQIgFgFIgEgFIgCgGIACgGIAEgFIAFgEIAGAAIAGAAIAFAEIAEAFIABAGIgBAGIgEAFIgFAFIgGABg");
	this.shape.setTransform(438.6,25.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgFgGQgEgFgCgHQgCgJgBgMIABhIIgVAAIAAgTIAVAAIAAgfIAWgLIAAAqIAfAAIAAATIgfAAIAABLQgBAIACAEQACAGAEABQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHABgJAAQgIAAgGgCg");
	this.shape_1.setTransform(430.95,18.45);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgZAgIAYhHIAbALIggBDg");
	this.shape_2.setTransform(422.175,11.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QAAgPgIgHQgHgJgPAAQgHAAgIAEQgJAFgHAFIAABMIASAAIAAAWIg9AAIAAgWIATAAIAAhXIgTAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQAKAAAJADQAIADAHAGQAFAGAEAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_3.setTransform(409.8,20.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXBBQgJgFgGgIIgNAAIAAgWIAaAAQAAAFADAEQACAEAEACQAEADAEABIAJABIAKgBIAIgEQAEgCACgDQABgEAAgEQAAgGgDgFQgFgEgKgEIgYgJQgPgEgHgJQgIgIAAgNQAAgIADgHQAEgIAFgFQAGgFAJgDQAIgDALAAQANAAAKAEQAJAEAIAKIAMAAIAAAWIgaAAQAAgGgCgDQgDgEgEgDIgJgDIgIgBIgJABIgIADQgCACgCAEQgCADAAADQAAAHAEAEQAEAEAJADIAYAJQARAFAIAJQAHAJAAANQAAAJgEAHQgDAIgHAFQgGAFgJADQgJADgLAAQgOAAgKgFg");
	this.shape_4.setTransform(394.8,20.425);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgFhAIgGgEIgDgFIgCgHIACgGIADgFIAGgEIAFgBIAGABIAGAEIADAFIABAGIgBAHIgDAFIgGAEIgGABg");
	this.shape_5.setTransform(384.55,17.275);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AA4BDIAAgWIATAAIAAg7QAAgPgIgHQgHgJgPAAQgJAAgJAEQgIAFgGAGIAABLIASAAIAAAWIg8AAIAAgWIASAAIAAg7QAAgPgIgHQgIgJgOAAQgIAAgIAEQgJAFgIAFIAABMIATAAIAAAWIg+AAIAAgWIATAAIAAhXIgTAAIAAgVIArAAIAAAPIAAAAIAJgHIAKgGIALgDIAMgCQAOAAAKAFQAKAGAFALIAKgJIALgHIAMgEQAHgCAGAAQALAAAIADQAJADAGAGQAGAGADAJQAEAKgBAMIAAA+IASAAIAAAWg");
	this.shape_6.setTransform(361.6,20.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AghBCQgIgDgFgFQgGgGgDgGQgDgHAAgJQAAgHACgHQADgGAEgGQAEgEAFgDIAMgEIAMgEIAMAAIAOAAIAMACIAAgLQAAgHgDgFQgCgFgDgEQgEgDgEgBQgGgCgGAAIgLABIgKACIgJADIgHADIgHgQIAKgGIAMgEIAMgDIANgBQAKAAAJADQAKACAGAGQAHAGADAJQAEAJgBAMIAABBIAPAAIAAAVIgmAAIAAgLQgIAHgJAEQgIAEgMAAQgJAAgJgDgAgRAHQgGACgEADQgEACgDAFQgCAEAAAGQAAAFACAEQACADAEADQADACAFACIAKABIAKgBIAIgDIAIgFIAGgFIAAgeIgbAAQgGAAgGACg");
	this.shape_7.setTransform(341.25,20.45);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AATBCIAAgWIAHAAIgaghIgYAhIAGAAIAAAWIgsAAIAAgWIALAAIAoguIglgpIgOAAIAAgWIAsAAIAAAWIgFAAIAXAfIAZgfIgHAAIAAgWIAsAAIAAAWIgLAAIglArIAnAsIAKAAIAAAWg");
	this.shape_8.setTransform(327.525,20.425);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIhdAAIABAKIACAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgNAAgLgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgEAFQgEAEgEAGQgCAHgBAIIBDAAg");
	this.shape_9.setTransform(312.75,20.425);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgEgGQgFgFgCgHQgCgJAAgMIAAhIIgVAAIAAgTIAVAAIAAgfIAWgLIAAAqIAfAAIAAATIgfAAIgBBLQAAAIACAEQACAGAEABQAEACAFAAIAJgBIAJgDIAGAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_10.setTransform(295.25,18.45);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgXBBQgJgFgGgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQADADAGABIAJABIAJgBIAIgEQADgCACgDQACgEABgEQgBgGgEgFQgEgEgJgEIgYgJQgQgEgIgJQgHgIAAgNQAAgIAEgHQACgIAHgFQAFgFAIgDQAJgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgDgDQgCgEgEgDIgIgDIgJgBIgJABIgHADQgEACgCAEQgBADAAADQAAAHAEAEQAEAEAKADIAYAJQAQAFAHAJQAIAJAAANQAAAJgDAHQgEAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_11.setTransform(284.05,20.425);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgGhAIgFgEIgDgFIgBgHIABgGIADgFIAFgEIAGgBIAGABIAFAEIAEAFIACAGIgCAHIgEAFIgFAEIgGABg");
	this.shape_12.setTransform(273.8,17.275);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgvBCIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAAASIAFgIIAGgGIAIgEQAEgBAFAAIANAAIAMAAIAAAdIgZAAIAAgJQgEAAgFACQgEACgEADQgEADgCAFQgCAFgCAHIAAA+IAWAAIAAAWg");
	this.shape_13.setTransform(263.35,20.375);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgFgGQgEgFgDgHQgCgJAAgMIABhIIgVAAIAAgTIAVAAIAAgfIAXgLIAAAqIAeAAIAAATIgfAAIAABLQAAAIABAEQACAGAEABQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_14.setTransform(252.55,18.45);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIhdAAIABAKIACAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgNAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgEAFQgEAEgEAGQgCAHgBAIIBDAAg");
	this.shape_15.setTransform(239.85,20.425);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AA4BDIAAgWIASAAIAAg7QAAgPgHgHQgIgJgOAAQgJAAgIAEQgJAFgHAGIAABLIASAAIAAAWIg8AAIAAgWIATAAIAAg7QAAgPgIgHQgIgJgOAAQgIAAgJAEQgIAFgIAFIAABMIATAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIApAAIAAAPIABAAIAJgHIAKgGIALgDIALgCQAOAAALAFQAKAGAFALIAKgJIALgHIAMgEQAGgCAIAAQAKAAAJADQAIADAGAGQAGAGADAJQADAKABAMIAAA+IASAAIAAAWg");
	this.shape_16.setTransform(219.8,20.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_17.setTransform(198.925,20.425);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgEgGQgFgFgCgHQgCgJAAgMIAAhIIgVAAIAAgTIAVAAIAAgfIAWgLIAAAqIAfAAIAAATIgfAAIgBBLQAAAIADAEQABAGAEABQAEACAFAAIAJgBIAJgDIAGAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_18.setTransform(186.45,18.45);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhFBhIAAgWIATAAIAAiSIgTAAIAAgWIAqAAIAAALQAJgHAJgEQAJgDALAAQANAAALAEQAKAFAIAJQAIAJAEAMQAFAMAAAPQAAAQgFANQgFAMgJAJQgIAKgMAFQgMAFgOAAQgJAAgIgCIgPgFIAAAqIAVAAIAAAWgAgMhIQgIAEgHAGIAABGQAFAFAHADQAIAEALAAQAIAAAHgEQAIgDAGgGQAFgGAEgJQADgJAAgMQAAgLgDgJQgDgIgGgGQgFgGgIgDQgHgEgIAAQgJAAgIAEg");
	this.shape_19.setTransform(173.475,23.275);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_20.setTransform(157.875,20.425);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AANBDIAAgWIATAAIAAg7QAAgPgJgHQgHgJgOAAQgIAAgIAEQgIAFgIAFIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQALAAAIADQAJADAFAGQAHAGADAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_21.setTransform(135.9,20.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AghBCQgIgDgGgFQgFgGgEgGQgDgHAAgJQABgHACgHQADgGADgGQAEgEAGgDIALgEIANgEIAMAAIAPAAIAKACIABgLQAAgHgCgFQgCgFgEgEQgDgDgGgBQgFgCgGAAIgKABIgLACIgIADIgHADIgIgQIAKgGIAMgEIANgDIAMgBQALAAAJADQAIACAHAGQAGAGAEAJQADAJABAMIgBBBIAOAAIAAAVIgmAAIAAgLQgHAHgJAEQgIAEgMAAQgJAAgJgDgAgRAHQgGACgEADQgEACgCAFQgDAEAAAGQAAAFACAEQACADADADQAEACAFACIALABIAJgBIAIgDIAHgFIAGgFIAAgeIgaAAQgGAAgGACg");
	this.shape_22.setTransform(119.9,20.45);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgOBfIgOgDIgPgGQgGgDgGgFIAMgTIAJAGIAKAFIAMADIAMABQAJAAAHgCQAHgCAFgFQAFgFACgJQACgJAAgNIAAgCQgGAHgJADQgJAEgLAAQgMAAgMgEQgLgFgJgJQgIgJgEgNQgGgMAAgRQAAgPAGgMQAEgNAIgJQAJgJALgEQAMgFANAAQALAAAHACQAJACAHAFIAAgGIAYAAIAAB9QAAAfgPAQQgPAQgfAAgAgKhHQgHADgGAGQgFAGgEAIQgDAJAAALQAAAMADAJQAEAJAEAGQAGAGAIADQAIAEAIAAIAKgCIAJgCIAHgFIAFgFIAAhHQgGgGgJgCQgJgDgJAAQgGAAgIAEg");
	this.shape_23.setTransform(99.4,23.175);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QAAgPgIgHQgHgJgPAAQgHAAgIAEQgJAFgHAFIAABMIASAAIAAAWIg9AAIAAgWIATAAIAAhXIgTAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQAKAAAJADQAIADAHAGQAFAGAEAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_24.setTransform(83.55,20.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgFhAIgGgEIgDgFIgCgHIACgGIADgFIAGgEIAFgBIAGABIAGAEIADAFIABAGIgBAHIgDAFIgGAEIgGABg");
	this.shape_25.setTransform(70.9,17.275);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAtBjIg1g7IgRAAIAAAlIAKAAIAAAWIg4AAIAAgWIAWAAIAAiZIgXAAIAAgWIAvAAIAAAWIAABhIAWAAIAfgfIgIAAIAAgWIAyAAIAAAWIgRAAIgoAoIAsAvIAQAAIAAAWg");
	this.shape_26.setTransform(58.725,17.125);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_27.setTransform(42.425,20.425);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_28.setTransform(26.875,20.425);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhHBgIAAgWIASAAIAAiTIgSAAIAAgWIBWAAQAMAAAJAEQALAFAHAHQAIAIAFAKQAEAKAAAMQAAAMgHALQgHAKgNAGIAMAGQAFAFADAFQAEAFACAGQACAGAAAGQAAAMgEAKQgFALgIAIQgHAHgKAFQgLAEgLAAgAgcBKIAsAAQAGAAAFgDQAGgDADgFQAEgEADgHQACgGAAgGQAAgGgCgFQgCgFgFgEQgDgEgGgDQgFgCgGAAIgsAAgAgcgKIArAAQAGAAAFgDQAGgCADgEQAFgEACgGQACgFAAgGQAAgGgCgGQgCgGgFgFQgDgEgGgDQgFgDgGAAIgrAAg");
	this.shape_29.setTransform(11.05,17.375);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(0,0,443.6,35.4), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAQIgGgFIgDgFIgBgGIABgGIADgFIAGgEIAFAAIAGAAIAGAEIADAFIABAGIgBAGIgDAFIgGAFIgGABg");
	this.shape.setTransform(330.2,25.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgfBgQgLgFgJgJQgIgJgFgNQgFgNAAgRQAAgPAFgMQAFgMAIgJQAIgJAMgEQAMgFAOAAQAJAAAIACQAIACAHAFIAAgyIgSAAIAAgWIAqAAIAACuIATAAIAAAWIgrAAIAAgLQgGAHgJAEQgIADgKAAQgNAAgMgEgAgTgMQgIADgFAGQgGAFgDAIQgDAJAAALQAAAMADAJQADAKAFAGQAGAGAIADQAHAEAJAAQAKAAAHgDQAHgEAGgGIAAhIQgGgGgJgCQgIgDgIAAQgIAAgHAEg");
	this.shape_1.setTransform(319.425,17.275);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AguBCIAAgWIASAAIAAhWIgSAAIAAgWIApAAIAAASIAFgIIAHgGIAHgEQAEgBAFAAIAMAAIAMAAIAAAdIgYAAIAAgJQgEAAgEACQgFACgDADQgFADgCAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape_2.setTransform(305.15,20.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AghBCQgIgDgGgFQgFgGgEgGQgDgHAAgJQABgHACgHQADgGADgGQAEgEAGgDIALgEIANgEIAMAAIAPAAIAKACIABgLQAAgHgCgFQgCgFgEgEQgDgDgGgBQgFgCgGAAIgKABIgLACIgIADIgHADIgIgQIAKgGIAMgEIANgDIAMgBQALAAAJADQAIACAHAGQAHAGADAJQADAJABAMIgBBBIAOAAIAAAVIgmAAIAAgLQgHAHgJAEQgIAEgMAAQgJAAgJgDgAgRAHQgGACgEADQgEACgCAFQgDAEAAAGQAAAFACAEQACADADADQAEACAFACIALABIAJgBIAIgDIAHgFIAGgFIAAgeIgaAAQgGAAgGACg");
	this.shape_3.setTransform(291.8,20.45);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AANBjIAAgWIASAAIAAg8QAAgPgIgHQgIgIgOAAQgIAAgHAEQgJAEgHAFIAABNIATAAIAAAWIg/AAIAAgWIAUAAIAAiZIgSAAIAAgWIAqAAIAABRIABAAIAIgHIAKgFIAKgEIAKgBQALAAAIADQAJADAGAGQAFAGAEAJQADAIAAANIAAA/IAUAAIAAAWg");
	this.shape_4.setTransform(276.55,17.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXBBQgKgFgFgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQAEADAFABIAJABIAJgBIAIgEQAEgCABgDQADgEAAgEQgBgGgEgFQgEgEgJgEIgYgJQgQgEgIgJQgHgIAAgNQAAgIAEgHQACgIAHgFQAFgFAIgDQAJgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgDgDQgCgEgEgDIgIgDIgJgBIgJABIgHADQgDACgDAEQgBADAAADQAAAHAEAEQAEAEAJADIAZAJQAQAFAHAJQAIAJAAANQAAAJgDAHQgEAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_5.setTransform(255.8,20.425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIAqAAIAABsIAUAAIAAAWgAgGhAIgFgEIgEgFIgBgHIABgGIAEgFIAFgEIAGgBIAHABIAEAEIAEAFIACAGIgCAHIgEAFIgEAEIgHABg");
	this.shape_6.setTransform(245.55,17.275);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNBfIgQgDIgNgGQgHgDgHgFIAOgTIAIAGIALAFIALADIAMABQAIAAAIgCQAHgCAFgFQAEgFACgJQADgJAAgNIAAgCQgGAHgJADQgJAEgKAAQgNAAgLgEQgMgFgIgJQgJgJgFgNQgEgMAAgRQAAgPAEgMQAFgNAIgJQAJgJAMgEQALgFAOAAQAKAAAIACQAHACAIAFIAAgGIAXAAIAAB9QAAAfgOAQQgPAQgfAAgAgKhHQgHADgGAGQgFAGgDAIQgEAJAAALQAAAMADAJQADAJAGAGQAFAGAIADQAHAEAIAAIALgCIAJgCIAHgFIAFgFIAAhHQgGgGgJgCQgIgDgJAAQgIAAgHAEg");
	this.shape_7.setTransform(227.6,23.175);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AANBDIAAgWIATAAIAAg7QgBgPgHgHQgIgJgPAAQgGAAgJAEQgJAFgHAFIAABMIATAAIAAAWIg+AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIABAAIAJgHIAKgGIAKgDIALgCQAKAAAJADQAJADAFAGQAGAGAEAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_8.setTransform(211.75,20.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIASAAIAAhWIgTAAIAAgWIArAAIAABsIATAAIAAAWgAgGhAIgFgEIgDgFIgBgHIABgGIADgFIAFgEIAGgBIAGABIAGAEIADAFIACAGIgCAHIgDAFIgGAEIgGABg");
	this.shape_9.setTransform(199.1,17.275);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgBBWQgGgBgFgGQgEgFgDgHQgCgJAAgMIABhIIgVAAIAAgTIAVAAIAAgfIAXgLIAAAqIAeAAIAAATIgfAAIAABLQAAAIABAEQACAGAEABQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_10.setTransform(190,18.45);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QABgPgJgHQgHgJgOAAQgIAAgIAEQgJAFgHAFIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQALAAAIADQAJADAFAGQAHAGADAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_11.setTransform(176.5,20.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAHAIADAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_12.setTransform(160,20.425);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgvBCIAAgWIATAAIAAhWIgTAAIAAgWIAqAAIAAASIAFgIIAGgGIAIgEQAEgBAFAAIANAAIAMAAIAAAdIgZAAIAAgJQgEAAgFACQgEACgEADQgEADgCAFQgCAFgCAHIAAA+IAWAAIAAAWg");
	this.shape_13.setTransform(146.8,20.375);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AggBCQgJgDgGgFQgFgGgDgGQgDgHAAgJQAAgHACgHQADgGAEgGQAEgEAFgDIAMgEIAMgEIAMAAIAOAAIAMACIAAgLQAAgHgDgFQgBgFgEgEQgEgDgEgBQgGgCgFAAIgMABIgKACIgJADIgHADIgHgQIAKgGIAMgEIAMgDIANgBQAKAAAJADQAKACAGAGQAHAGADAJQAEAJgBAMIAABBIAPAAIAAAVIgmAAIAAgLQgIAHgJAEQgIAEgLAAQgLAAgHgDgAgRAHQgGACgEADQgEACgDAFQgCAEAAAGQAAAFACAEQACADAEADQADACAFACIAKABIAKgBIAIgDIAIgFIAGgFIAAgeIgbAAQgGAAgGACg");
	this.shape_14.setTransform(133.45,20.45);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhEBgIAAgWIATAAIAAiTIgTAAIAAgWIBNAAQANAAALADQALAEAIAGQAIAHAEAJQAFAKAAANQAAAKgFAKQgEAJgIAHQgIAHgLADQgLAEgNAAIghAAIAABDIATAAIAAAWgAgYgNIAhAAQAHAAAHgCQAGgCAEgDQAEgEADgGQACgGAAgHQAAgOgIgIQgJgIgTAAIgeAAg");
	this.shape_15.setTransform(119.175,17.375);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(108.4,0,226.79999999999998,35.4), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.whitedad();
	this.instance.parent = this;
	this.instance.setTransform(-53,2,0.5186,0.5186);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(-53,2,314.8,228.7), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgvBCIAAgWIATAAIAAhWIgTAAIAAgWIArAAIAAASIAEgIIAGgGIAIgEQAEgBAFAAIAMAAIANAAIAAAdIgZAAIAAgJQgEAAgEACQgFACgEADQgDADgDAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape.setTransform(279.25,49.775);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_1.setTransform(265.375,49.825);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgvBjIAAgWIAUAAIAAhaIgVAAIAAgTIAVAAIAAgUQAAgMADgIQAEgJAFgFQAFgGAJgDQAHgDAJAAIAMABIAJACIAIACIAGACIgHARIgLgDQgGgCgIAAQgKAAgHAHQgEAGAAANIAAAVIAdAAIAAATIgdAAIAABaIATAAIAAAWg");
	this.shape_2.setTransform(254.3,46.525);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AA4BDIAAgWIATAAIAAg7QgBgPgHgHQgIgIgOAAQgJAAgIADQgJAEgHAGIAABMIASAAIAAAWIg8AAIAAgWIATAAIAAg7QAAgPgIgHQgHgIgPAAQgIAAgJADQgIAEgIAGIAABMIATAAIAAAWIg9AAIAAgWIASAAIAAhWIgSAAIAAgWIApAAIAAAPIABAAIAJgHIAKgFIALgFIAMgBQANAAALAGQAJAEAGAMIAKgIIALgIIAMgEQAGgCAIAAQAKAAAJADQAIADAGAGQAGAGADAJQAEAJAAANIAAA+IASAAIAAAWg");
	this.shape_3.setTransform(229.6,49.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgoBgIAAgWIAQAAIAOgkIgshvIgLAAIAAgWIAyAAIAAAWIgQAAIAfBTIAghTIgQAAIAAgWIAyAAIAAAWIgOAAIg5CTIARAAIAAAWg");
	this.shape_4.setTransform(208.675,52.825);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QABgPgJgHQgHgIgOAAQgIAAgIADQgIAEgIAGIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhWIgSAAIAAgWIAqAAIAAAPIAAAAIAKgHIAJgFIALgFIALgBQALAAAIADQAJADAFAGQAHAGADAJQADAJAAANIAAA+IASAAIAAAWg");
	this.shape_5.setTransform(193.05,49.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgaBBQgMgFgIgKQgJgJgFgNQgFgNAAgPQAAgPAFgMQAFgNAJgJQAJgKAMgFQAMgFANAAQAPAAAMAFQAMAFAJAJQAIAJAFANQAFANAAAPQAAAPgFANQgFANgIAJQgJAJgMAGQgMAFgPAAQgOAAgMgFgAgPgtQgHADgGAGQgFAHgEAJQgDAJAAALQAAALADAJQAEAKAFAGQAGAGAHAEQAIADAHAAQAJAAAIgDQAHgDAGgHQAFgGADgJQAEgKAAgLQAAgLgEgJQgDgJgFgHQgGgGgHgDQgIgDgJAAQgHAAgIADg");
	this.shape_6.setTransform(176.525,49.825);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QABgPgJgHQgHgIgOAAQgIAAgIADQgIAEgIAGIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhWIgSAAIAAgWIAqAAIAAAPIABAAIAIgHIAKgFIALgFIALgBQALAAAIADQAJADAFAGQAHAGADAJQADAJAAANIAAA+IASAAIAAAWg");
	this.shape_7.setTransform(160.2,49.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgoBgIAAgWIAQAAIAOgkIgshvIgLAAIAAgWIAyAAIAAAWIgQAAIAfBTIAghTIgQAAIAAgWIAyAAIAAAWIgOAAIg5CTIARAAIAAAWg");
	this.shape_8.setTransform(143.625,52.825);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgXBBQgKgFgFgIIgNAAIAAgWIAaAAQAAAFADAEQACAEAEACQADADAFABIAJABIAKgBIAIgEQADgCACgDQACgEAAgEQAAgGgDgFQgFgEgKgEIgYgJQgPgEgHgJQgIgIAAgNQAAgIADgHQAEgIAFgFQAGgFAIgDQAJgDALAAQANAAAKAEQAJAEAIAKIAMAAIAAAWIgaAAQAAgGgCgDQgDgEgEgDIgJgDIgIgBIgJABIgIADQgDACgBAEQgCADAAADQAAAHAEAEQAEAEAKADIAXAJQARAFAIAJQAHAJAAANQAAAJgEAHQgDAIgHAFQgGAFgJADQgJADgLAAQgOAAgKgFg");
	this.shape_9.setTransform(130.3,49.825);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AggBCQgIgDgHgFQgFgFgEgIQgCgHAAgHQgBgJADgGQACgHAFgEQAEgFAFgDIALgFIANgDIAMAAIAPAAIALACIAAgLQAAgHgCgFQgDgFgDgDQgEgEgFgCQgFgBgFAAIgMABIgKACIgJADIgGADIgIgQIAKgFIAMgFIANgDIAMgBQALAAAIADQAKADAGAFQAGAGAEAJQADAJAAAMIAABAIAPAAIAAAXIgmAAIAAgNQgIAHgJAFQgIAEgLAAQgLAAgHgDgAgRAHQgGABgEAEQgEADgCADQgDAFAAAGQAAAFACAEQACAEADACQAEACAFACIAKACIAKgCIAIgDIAHgEIAHgGIAAgeIgbAAQgGABgGABg");
	this.shape_10.setTransform(111.05,49.85);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgBBXQgGgDgEgFQgFgEgDgIQgBgJAAgNIAAhHIgVAAIAAgTIAVAAIAAgfIAWgMIAAArIAfAAIAAATIgfAAIgBBLQAAAIADAEQABAFAEADQAEABAFAAIAJAAIAJgEIAGAQIgNAFQgHABgJABQgJAAgFgCg");
	this.shape_11.setTransform(93.75,47.85);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgXBBQgKgFgFgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQAEADAFABIAJABIAJgBIAIgEQAEgCABgDQADgEAAgEQAAgGgFgFQgEgEgJgEIgYgJQgQgEgIgJQgHgIAAgNQAAgIAEgHQACgIAHgFQAFgFAIgDQAJgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgDgDQgCgEgEgDIgIgDIgJgBIgJABIgHADQgDACgDAEQgBADAAADQAAAHAEAEQAEAEAKADIAYAJQAQAFAHAJQAIAJAAANQAAAJgDAHQgEAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_12.setTransform(82.55,49.825);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgaBAQgIgDgGgGQgGgGgDgJQgDgKAAgNIAAg9IgSAAIAAgWIArAAIAABRQAAAPAHAIQAHAHANABQAHgBAIgDQAJgCAHgFIAAhPIgRAAIAAgWIAqAAIAABsIAPAAIAAAXIgnAAIAAgNQgJAHgKAEQgLAEgKAAQgKAAgIgDg");
	this.shape_13.setTransform(67.025,49.95);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgYBsQAMgBAFgJQAGgJAAgPIAAh0IgUAAIAAgWIAqAAIAACNQAAALgCAJQgDAJgGAHQgFAGgIAEQgHADgLAAgAADhhIgDgDIgEgEIgBgGIABgHIAEgEIADgDIAHgCIAFACIAFADIADAEIACAHIgCAGIgDAEIgFADIgFACg");
	this.shape_14.setTransform(54.75,49.75);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgXBBQgJgFgGgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQAEADAFABIAIABIAKgBIAIgEQAEgCACgDQACgEAAgEQAAgGgFgFQgDgEgKgEIgZgJQgPgEgHgJQgIgIAAgNQAAgIADgHQAEgIAFgFQAGgFAJgDQAIgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgCgDQgDgEgEgDIgIgDIgJgBIgJABIgIADQgCACgDAEQgBADAAADQAAAHAEAEQAEAEAJADIAYAJQARAFAIAJQAHAJAAANQAAAJgEAHQgDAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_15.setTransform(39.55,49.825);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgeBhIAAgWIATAAIAAhWIgTAAIAAgWIApAAIAABsIAVAAIAAAWgAgGhAIgFgEIgEgFIgBgHIABgGIAEgFIAFgEIAGgBIAHABIAEAEIAEAFIACAGIgCAHIgEAFIgEAEIgHABg");
	this.shape_16.setTransform(29.3,46.675);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AADAdIAYhAIAYAJIgfA/gAgyAdIAYhAIAYAJIgfA/g");
	this.shape_17.setTransform(266.925,10.9);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAtBjIg1g7IgRAAIAAAlIAKAAIAAAWIg4AAIAAgWIAWAAIAAiZIgXAAIAAgWIAvAAIAAAWIAABhIAWAAIAfgfIgIAAIAAgWIAyAAIAAAWIgRAAIgoAoIAsAvIAQAAIAAAWg");
	this.shape_18.setTransform(252.775,17.125);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AguBCIAAgWIASAAIAAhWIgSAAIAAgWIAqAAIAAASIAEgIIAHgGIAHgEQAEgBAFAAIAMAAIAMAAIAAAdIgYAAIAAgJQgEAAgEACQgFACgDADQgEADgDAFQgCAFgBAHIAAA+IAVAAIAAAWg");
	this.shape_19.setTransform(238.2,20.375);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AghBCQgHgDgGgFQgGgGgDgGQgEgHAAgJQABgHACgHQACgGAEgGQAFgEAFgDIAMgEIAMgEIAMAAIAOAAIALACIABgLQAAgHgCgFQgDgFgDgEQgDgDgGgBQgFgCgGAAIgKABIgLACIgIADIgIADIgHgQIAKgGIAMgEIAMgDIANgBQALAAAJADQAIACAHAGQAGAGAEAJQADAJABAMIgBBBIAOAAIAAAVIgmAAIAAgLQgHAHgJAEQgIAEgMAAQgKAAgIgDgAgRAHQgGACgEADQgEACgDAFQgCAEAAAGQAAAFACAEQACADAEADQADACAFACIALABIAJgBIAIgDIAIgFIAFgFIAAgeIgaAAQgGAAgGACg");
	this.shape_20.setTransform(224.85,20.45);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhFBhIAAgWIATAAIAAiSIgTAAIAAgWIAqAAIAAALQAJgHAJgEQAJgDALAAQANAAALAEQAKAFAIAJQAIAJAEAMQAFAMAAAPQAAAQgFANQgFAMgJAJQgIAKgMAFQgMAFgOAAQgJAAgIgCIgPgFIAAAqIAVAAIAAAWgAgMhIQgIAEgHAGIAABGQAFAFAHADQAIAEALAAQAIAAAHgEQAIgDAGgGQAFgGAEgJQADgJAAgMQAAgLgDgJQgDgIgGgGQgFgGgIgDQgHgEgIAAQgJAAgIAEg");
	this.shape_21.setTransform(209.875,23.275);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgBBWQgHgBgEgGQgEgFgDgHQgCgJAAgMIABhIIgVAAIAAgTIAVAAIAAgfIAXgLIAAAqIAeAAIAAATIgfAAIAABLQAAAIACAEQABAGAEABQAEACAFAAIAKgBIAJgDIAFAQIgNAFQgHABgJAAQgJAAgFgCg");
	this.shape_22.setTransform(191.7,18.45);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AANBDIAAgWIASAAIAAg7QABgPgJgHQgHgJgOAAQgIAAgIAEQgIAFgIAFIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIABAAIAIgHIAKgGIALgDIALgCQALAAAIADQAJADAFAGQAHAGADAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_23.setTransform(178.2,20.3);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgUBBQgMgEgIgJQgJgJgEgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAHgJAMgGQAMgFAOAAQAPAAAKAEQAKAFAGAHQAGAIAEAJQADAKABAKIABAJIAAAJIheAAIABAKIADAJQAEANALAGQAKAHAMAAQAKAAAKgDQAKgDAKgGIAKAQQgNAJgNAEQgNAEgOAAQgMAAgLgEgAAigOIgCgOQgCgGgEgFQgEgEgGgDQgGgCgJAAQgHAAgGACQgGACgEAFQgFAEgCAGQgDAHgBAIIBDAAg");
	this.shape_24.setTransform(161.7,20.425);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AA4BDIAAgWIATAAIAAg7QAAgPgIgHQgHgJgPAAQgJAAgJAEQgIAFgGAGIAABLIASAAIAAAWIg9AAIAAgWIATAAIAAg7QAAgPgIgHQgIgJgOAAQgIAAgIAEQgJAFgIAFIAABMIATAAIAAAWIg+AAIAAgWIATAAIAAhXIgTAAIAAgVIAqAAIAAAPIABAAIAJgHIAKgGIALgDIAMgCQAOAAAKAFQAJAGAGALIAKgJIALgHIAMgEQAHgCAGAAQALAAAIADQAJADAGAGQAGAGADAJQADAKAAAMIAAA+IASAAIAAAWg");
	this.shape_25.setTransform(141.65,20.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgVBBQgLgEgJgJQgHgJgFgNQgFgNAAgRQAAgOAEgMQAEgNAIgJQAIgJALgGQAMgFAOAAQAPAAAKAEQAKAFAHAHQAFAIAEAJQADAKABAKIABAJIAAAJIhdAAIABAKIABAJQAGANAKAGQAKAHAMAAQAKAAAKgDQAKgDALgGIAJAQQgNAJgNAEQgNAEgOAAQgMAAgMgEgAAigOIgDgOQgBgGgEgFQgEgEgGgDQgGgCgIAAQgIAAgGACQgGACgFAFQgDAEgEAGQgCAHgBAIIBDAAg");
	this.shape_26.setTransform(120.8,20.425);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgXBBQgKgFgFgIIgNAAIAAgWIAaAAQAAAFACAEQADAEAEACQAEADAFABIAIABIAKgBIAIgEQADgCADgDQACgEAAgEQAAgGgFgFQgDgEgKgEIgZgJQgPgEgIgJQgHgIAAgNQAAgIADgHQAEgIAFgFQAGgFAJgDQAIgDALAAQANAAAJAEQAKAEAIAKIAMAAIAAAWIgaAAQAAgGgDgDQgCgEgEgDIgIgDIgJgBIgJABIgHADQgEACgCAEQgBADAAADQAAAHAEAEQAEAEAJADIAZAJQAQAFAIAJQAHAJAAANQAAAJgEAHQgDAIgGAFQgHAFgJADQgJADgLAAQgPAAgJgFg");
	this.shape_27.setTransform(107.4,20.425);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgaBAQgIgDgGgGQgGgGgDgKQgDgIAAgNIAAg+IgSAAIAAgWIArAAIAABRQAAAPAHAHQAHAJANAAQAHAAAIgDQAJgDAHgFIAAhPIgRAAIAAgWIAqAAIAABtIAPAAIAAAWIgnAAIAAgMQgJAGgKAEQgLAEgKAAQgKAAgIgDg");
	this.shape_28.setTransform(91.875,20.55);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AA4BDIAAgWIASAAIAAg7QAAgPgHgHQgHgJgPAAQgIAAgKAEQgIAFgHAGIAABLIASAAIAAAWIg7AAIAAgWIASAAIAAg7QAAgPgIgHQgHgJgPAAQgIAAgJAEQgIAFgHAFIAABMIASAAIAAAWIg9AAIAAgWIASAAIAAhXIgSAAIAAgVIAqAAIAAAPIAAAAIAJgHIAKgGIALgDIALgCQAPAAAKAFQAKAGAFALIAKgJIALgHIAMgEQAGgCAIAAQAKAAAIADQAJADAGAGQAGAGADAJQADAKABAMIAAA+IARAAIAAAWg");
	this.shape_29.setTransform(71.05,20.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAiBgIAAgWIAQAAIgPgrIhJAAIgPArIATAAIAAAWIg+AAIAAgWIARAAIA8ipIAkAAIA8CpIAUAAIAAAWgAAbAKIgchVIgeBVIA6AAg");
	this.shape_30.setTransform(48.3,17.375);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AADAbIAfg+IARAHIgYBBgAgyAbIAfg+IARAHIgYBBg");
	this.shape_31.setTransform(31.775,10.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(23,0,264.6,64.8), null);


(lib.shaker = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFANIgFgDIgCgFIgBgFIABgFIADgFIAFgDIAEgBIAGABIAEAEIAEAFIABAEIgBAGIgFAEIgEADIgFACg");
	this.shape.setTransform(185.1,44.725);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AALBYIABgUIAQABIACg1QAAgOgHgFQgGgIgNAAQgGAAgIACQgHAEgHAFIgDBCIARACIAAATIg4gCIABgUIARABIAGiHIgQgBIAAgTIAlABIgCBHIABABIAHgGIAJgEIAIgDIAKgBQAKAAAHADQAIAEAEAFQAFAFADAIQADAIgBALIgCA4IASAAIgBATg");
	this.shape_1.setTransform(175.05,36.95);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAAA+QgOgBgIgFQgJgEgEgIIgMAAIABgTIAXAAQAAAFACAEQACAEADACIAIADIAIABIAIAAIAHgDIAGgFQACgDAAgEQAAgFgEgEQgDgEgJgEIgVgJQgNgEgGgIQgHgIABgLQAAgHADgGQADgHAFgEQAFgEAIgCQAIgDAIAAQANABAIADQAIAEAHAJIALAAIgBAUIgXgBQAAgFgCgDQgCgEgDgCIgIgDIgIgBIgIAAIgGADIgEAEQgCADAAADQAAAGADAEQADAEAJADIAUAIQAPAFAGAIQAHAJgBALQAAAIgDAHQgEAGgGAEQgFAFgIACQgHACgIAAIgCAAg");
	this.shape_2.setTransform(161.875,39.4256);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgOA9QgJAAgGgEQgIgCgFgFQgFgFgCgGQgCgHgBgHQABgHACgGQACgFAEgFQAEgDAFgCIAKgFIALgCIALAAIAMABIAKACIABgKQAAgGgCgFIgEgHQgDgDgFgCQgEgCgFAAIgKABIgJABIgIADIgGADIgHgPIAKgFIAKgEIAMgCIAKAAQAJAAAJADQAIADAFAFQAGAFACAIQADAIAAALIgDA5IAOAAIgBAUIgigBIAAgLQgHAGgIAEQgFADgJAAIgDAAgAgOAGIgJADQgEADgCADQgCAEgBAFQAAAFACADQACAEACACQADADAFABIAKABIAIgBIAHgCIAHgEIAFgEIABgaIgXgBIgDAAIgIABg");
	this.shape_3.setTransform(149.8,39.0031);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgrA5IAAgTIARAAIADhMIgQgBIAAgTIAlABIAAAQIADgGIAGgFIAIgEIAIgBIAKABIALAAIgBAaIgVgBIAAgIIgHACQgEABgEADQgDACgDAFIgDAKIgCA3IATABIgBATg");
	this.shape_4.setTransform(138.4,38.525);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgVA4QgLgFgHgIQgHgJgEgLQgDgMAAgMQABgOAEgLQAFgLAIgIQAIgIAKgEQALgEAKAAQALAAAKAFQAKAEAHAIIAMAAIgBATIgVAAQgEgJgHgEQgIgEgJAAQgHgBgGADQgGADgGAFQgEAGgEAIQgCAIgBAJQAAAJACAIQADAIAEAGQAFAFAGAEQAGADAHAAQAKAAAIgEQAJgGAFgJIARAJQgEAHgFAFQgFAGgHAEQgGAEgHACQgIACgIAAQgLgBgKgFg");
	this.shape_5.setTransform(126.9719,38.2222);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgrA5IABgTIAQAAIADhMIgRgBIABgTIAmABIgBAQIAEgGIAGgFIAGgEIAIgBIAMABIAKAAIgBAaIgWgBIABgIIgIACQgEABgDADQgDACgDAFIgEAKIgCA3IATABIAAATg");
	this.shape_6.setTransform(110.1,37.575);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgOA9QgIAAgIgEQgGgCgGgFQgEgFgDgGQgDgHABgHQAAgHACgGQACgFAFgFQADgDAFgCIALgFIAKgCIALAAIANABIAKACIAAgKQAAgGgBgFIgFgHQgDgDgFgCQgEgCgFAAIgKABIgJABIgIADIgGADIgGgPIAJgFIAKgEIALgCIALAAQAJAAAJADQAIADAFAFQAFAFAEAIQACAIgBALIgBA5IAMAAIAAAUIgigBIABgLQgHAGgJAEQgGADgIAAIgDAAgAgOAGIgJADQgEADgCADQgCAEgBAFQABAFABADQABAEAEACQADADAEABIAKABIAHgBIAHgCIAIgEIAFgEIABgaIgXgBIgDAAIgIABg");
	this.shape_7.setTransform(98.2,37.2031);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgEBVIgNgBIgNgEIgMgFQgGgEgFgEIAMgRIAHAGIAJAFIAKADIALABQAIAAAGgCQAGgBAEgEQAFgFACgHQADgIAAgMIAAgBQgGAFgIADQgHADgJAAQgMAAgKgFQgKgEgHgIQgIgJgDgKQgEgMABgPQAAgNAFgLQAEgLAIgHQAHgIALgEQAKgEAMABQAJAAAHACQAHACAHAFIAAgGIAUABIgEBvQgBAbgNAOQgNANgYAAIgDAAgAgIhAQgHADgFAFQgFAFgDAHQgDAIgBAKQAAALACAIQADAHAEAGQAFAGAHADQAGADAHAAIAKgBIAHgCIAHgEIAFgEIACg+QgGgGgHgCQgIgDgHAAIgDAAQgFAAgFACg");
	this.shape_8.setTransform(85.2719,39.1506);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAbA7IAAgLQgIAHgKACQgJADgJAAQgJAAgHgDQgHgDgEgGQgFgEgDgJQgDgIABgMIACg2IgQgBIAAgUIAmACIgDBHQAAAOAHAIQAFAGAMAAQAFAAAIgCIAPgGIAChFIgPgBIABgUIAlABIgEBgIANABIAAATg");
	this.shape_9.setTransform(70.6,36.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAAA+QgOgBgIgFQgJgEgEgIIgMAAIABgTIAXAAQAAAFACAEQACAEADACIAIADIAIABIAIAAIAHgDIAGgFQACgDAAgEQAAgFgEgEQgDgEgJgEIgVgJQgNgEgGgIQgHgIABgLQAAgHADgGQADgHAFgEQAFgEAIgCQAIgDAIAAQANABAIADQAIAEAHAJIALAAIgBAUIgXgBQAAgFgCgDQgCgEgDgCIgIgDIgIgBIgIAAIgGADIgEAEQgCADAAADQAAAGADAEQADAEAJADIAUAIQAPAFAGAIQAHAJgBALQAAAIgDAHQgEAGgGAEQgFAFgIACQgHACgIAAIgCAAg");
	this.shape_10.setTransform(58.075,35.7756);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgOA9QgIAAgIgEQgGgCgGgFQgEgFgDgGQgCgHAAgHQAAgHACgGQACgFAFgFQADgDAFgCIALgFIAKgCIALAAIANABIAKACIAAgKQAAgGgBgFIgFgHQgEgDgEgCQgFgCgEAAIgKABIgJABIgIADIgHADIgFgPIAJgFIALgEIAKgCIALAAQAKAAAHADQAJADAFAFQAFAFAEAIQACAIgBALIgBA5IAMAAIAAAUIgigBIABgLQgIAGgHAEQgHADgIAAIgDAAgAgOAGIgJADQgEADgCADQgCAEAAAFQgBAFACADQABAEAEACQADADAEABIAJABIAIgBIAHgCIAIgEIAFgEIABgaIgXgBIgDAAIgIABg");
	this.shape_11.setTransform(40.95,35.2031);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgcBTQgLgEgGgIQgIgJgEgLQgDgMAAgPQABgNAEgLQAFgKAHgHQAIgIAKgEQALgEANABQAHAAAHACQAHACAGAFIACgtIgQAAIABgTIAkABIgFCaIARAAIgBAUIgmgBIABgKQgGAFgIAEQgHACgIAAQgMAAgKgFgAgPgMQgGADgGAFQgFAEgDAHQgDAIAAAKQgBALADAIQACAIAFAGQAEAGAHADQAHADAIAAQAIAAAGgCQAHgDAFgFIAChAQgFgFgHgCQgHgDgHAAIgCAAQgGAAgGACg");
	this.shape_12.setTransform(22.9219,31.775);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AALA6IABgTIAQAAIACg0QAAgMgGgIQgHgHgMgBQgHAAgHAEIgPAHIgCBDIAQABIAAAUIg3gCIABgTIAQAAIADhNIgQAAIAAgUIAmABIgBAPIAJgHIAIgEIAJgDIALgBQAJABAHACQAIADAFAFQAFAGADAJQACAIAAALIgCA2IAQABIgBAUg");
	this.shape_13.setTransform(7.975,34.05);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgOA9QgJAAgGgEQgIgCgFgFQgFgFgCgGQgDgHAAgHQABgHACgGQACgFAEgFQAEgDAFgCIALgFIALgCIAKAAIAMABIALACIAAgKQABgGgDgFIgEgHQgEgDgEgCQgFgCgEAAIgKABIgJABIgIADIgHADIgFgPIAJgFIALgEIAKgCIALAAQAKAAAHADQAJADAGAFQAEAFAEAIQACAIAAALIgCA5IAMAAIAAAUIgigBIAAgLQgHAGgHAEQgHADgIAAIgDAAgAgOAGIgJADQgEADgCADQgCAEAAAFQAAAFABADQABAEADACQAEADAEABIAJABIAIgBIAHgCIAIgEIAFgEIABgaIgXgBIgDAAIgIABg");
	this.shape_14.setTransform(-6.05,33.5531);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAAA+QgOgBgIgFQgJgEgEgIIgMAAIABgTIAXAAQAAAFACAEQACAEADACIAIADIAIABIAIAAIAHgDIAGgFQACgDAAgEQAAgFgEgEQgDgEgJgEIgVgJQgNgEgGgIQgHgIABgLQAAgHADgGQADgHAFgEQAFgEAIgCQAIgDAIAAQANABAIADQAIAEAHAJIALAAIgBAUIgXgBQAAgFgCgDQgCgEgDgCIgIgDIgIgBIgIAAIgGADIgEAEQgCADAAADQAAAGADAEQADAEAJADIAUAIQAPAFAGAIQAHAJgBALQAAAIgDAHQgEAGgGAEQgFAFgIACQgHACgIAAIgCAAg");
	this.shape_15.setTransform(172.275,13.9756);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAxA8IABgUIAQABIACg0QABgNgHgHQgGgHgNgBQgHAAgIADQgJADgFAGIgDBCIAQABIAAATIg1gCIAAgTIAQAAIACg0QABgNgHgHQgGgHgNgBQgHAAgIADIgOAIIgDBDIARABIgBAUIg2gCIAAgUIARABIADhNIgRAAIABgUIAlABIAAAOIAIgGIAJgEIAKgDIAKgBQANAAAJAFQAIAFAEAKIAJgHIALgFIAKgFIAMgBQAJABAIACQAHAEAGAFQAEAGADAIQACAIAAALIgCA3IAQAAIAAAUg");
	this.shape_16.setTransform(155.125,13.375);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAbA7IABgLQgJAGgJADQgJADgKAAQgJAAgHgDQgHgDgFgGQgFgEgCgJQgCgIAAgMIACg2IgQgBIABgTIAlABIgCBHQgBAOAGAHQAGAHALAAQAHAAAHgCIAPgGIADhGIgQAAIAAgUIAlABIgDBgIANABIgBATg");
	this.shape_17.setTransform(135.55,12.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgrA5IABgTIAQAAIADhMIgQgBIAAgTIAlABIAAAQIAEgGIAFgFIAIgEIAIgBIAKABIALAAIgBAaIgVgBIAAgIIgHACQgFABgEADQgDACgCAFIgEAKIgBA3IATABIgBATg");
	this.shape_18.setTransform(123.2,12.225);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgDBMQgFgCgEgFQgDgEgCgHQgBgIAAgLIACg/IgSgBIAAgRIATABIABgbIAUgKIgCAmIAbABIAAARIgcgBIgCBCIABALQACAEADADQAEABAEAAIAIAAIAIgDIAFAOIgMAEQgGACgIAAQgHgBgGgCg");
	this.shape_19.setTransform(113.6,10.225);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AALA7IABgUIAQABIACg0QAAgOgGgGQgHgIgMAAQgHAAgHADIgPAIIgCBCIAQACIAAATIg3gCIABgUIAQABIADhMIgQgBIAAgTIAmABIgBANIAJgFIAIgFIAJgDIALgBQAJAAAHADQAIAEAFAFQAFAFADAIQACAJAAALIgCA3IAQAAIgBATg");
	this.shape_20.setTransform(101.525,11.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgOA9QgJAAgGgEQgIgCgFgFQgEgFgDgGQgDgHAAgHQABgHACgGQACgFAEgFQAEgDAFgCIAKgFIAMgCIAKAAIAMABIAKACIABgKQAAgGgCgFIgEgHQgDgDgFgCQgEgCgFAAIgKABIgJABIgIADIgHADIgGgPIAKgFIALgEIALgCIAKAAQAKAAAHADQAJADAGAFQAEAFAEAIQACAIAAALIgCA5IAMAAIAAAUIgigBIAAgLQgGAGgIAEQgHADgIAAIgDAAgAgOAGIgJADQgEADgCADQgCAEAAAFQAAAFABADQABAEADACQADADAFABIAJABIAIgBIAIgCIAHgEIAFgEIABgaIgXgBIgDAAIgIABg");
	this.shape_21.setTransform(87.45,11.0531);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgCBMQgGgCgEgFQgDgEgCgHQgBgIgBgLIADg/IgTgBIABgRIATABIABgbIAUgKIgBAmIAbABIgBARIgbgBIgDBCIABALQABAEAEADQAEABAEAAIAIAAIAIgDIAEAOIgLAEQgGACgIAAQgIgBgEgCg");
	this.shape_22.setTransform(77.2,8.975);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgUA5QgKgFgHgIQgHgIgEgLQgDgMAAgOQABgNAEgLQADgLAHgIQAIgIAKgEQAKgFANABQANAAAJAEQAJAFAFAHQAFAGADAJQACAIABAJIAAAJIAAAHIhSgDIAAAJIACAIQAEAMAJAGQAIAGALAAQAJAAAJgCQAIgCAKgFIAIAPQgMAHgLADQgMAEgMAAQgLgBgKgEgAAfgMIgCgMIgEgKQgEgEgFgCQgFgDgIAAQgGAAgGACQgFACgEAEQgEADgDAFQgDAGgBAHIA8ACg");
	this.shape_23.setTransform(61.0969,10.1475);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgUA5QgKgFgHgIQgHgIgEgLQgDgMAAgOQABgNAEgLQADgLAHgIQAIgIAKgEQAKgFANABQANAAAJAEQAJAFAFAHQAFAGADAJQACAIABAJIAAAJIAAAHIhSgDIAAAJIACAIQAEAMAJAGQAIAGALAAQAJAAAJgCQAIgCAKgFIAIAPQgMAHgLADQgMAEgMAAQgLgBgKgEgAAfgMIgCgMIgEgKQgEgEgFgCQgFgDgIAAQgGAAgGACQgFACgEAEQgEADgDAFQgDAGgBAHIA8ACg");
	this.shape_24.setTransform(47.9469,9.6975);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgrA5IAAgTIARAAIADhMIgQgBIAAgTIAlABIAAAQIADgGIAGgFIAIgEIAIgBIAKABIALAAIgBAaIgVgBIAAgIIgHACQgEABgFADQgCACgDAFIgDAKIgCA3IATABIgBATg");
	this.shape_25.setTransform(36.25,9.175);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AALBYIABgUIAPABIADg1QAAgOgHgFQgGgIgNAAQgGAAgIACQgHAEgHAFIgDBCIARACIAAATIg4gCIABgUIARABIAGiHIgQgBIABgTIAkABIgCBHIABABIAHgGIAJgEIAIgDIAKgBQAKAAAHADQAIAEAEAFQAFAFAEAIQACAIgBALIgCA4IASAAIgBATg");
	this.shape_26.setTransform(23.3,5.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgiBVIABgTIAPAAIAFiDIgngBIgBAaIgXgBIACgtICXAGIgCAsIgXgBIABgaIgtgBIgFCDIASAAIgBAUg");
	this.shape_27.setTransform(8.075,5.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.shaker, new cjs.Rectangle(-14.5,-10.7,206,64.7), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeA0QgGgCgFgEIgFgGIgDgIIgBgLQAAgHACgIIAJgqIgOAAIAFgRIAjAAIgNA1QgEATADAIQAFAJANAAQAGAAADgCQAFgCAEgDIAGgHIAOg6IgOAAIAEgRIAiAAIgUBXIAQAAIgEASIgkAAIADgLIgHAGIgHAEIgIACIgHABQgHAAgGgCg");
	this.shape.setTransform(191.6,25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZA0QgJgEgHgGQgGgHgEgIQgDgKAAgKQAAgHACgIQACgJAEgGQAEgIAGgGQAGgFAGgFQAIgDAHgCQAIgDAIAAQAKAAAJAEQAJAEAGAGQAHAHAEAJQADAIABAKQgBAIgBAJQgDAHgEAHQgEAHgFAHQgGAGgHAEQgHADgIADQgIACgIAAQgKAAgJgEgAgIghQgIACgFAHQgGAFgDAIQgDAJAAAIQAAAHACAGQACAGAEAEQAEAEAFADQAFACAHAAQAGAAAIgEQAGgCAGgHQAGgGADgHQADgIAAgJQAAgIgCgGQgCgFgEgFQgEgDgFgCQgGgDgGAAQgHAAgGAEg");
	this.shape_1.setTransform(178.5,24.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag+BNIAFgSIAKAAIATgdIgMhZIgKAAIAFgRIAmAAIgDARIgJAAIAGBBIAphBIgJAAIAFgRIAnAAIgFARIgJAAIhKB2IAKAAIgEASg");
	this.shape_2.setTransform(166.45,27.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgsA2IAVhYIgVAAIAEgRIAoAAIgDAOIAFgGIAHgFIAHgDIAIgBIAHAAIAGAAIAIABIgHAcIgVAAIAEgMQgLAAgGAFQgHAFgEAJIgNA0IASAAIgDASg");
	this.shape_3.setTransform(150.75,24.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgfA0QgHgDgFgHQgHgFgCgIQgDgIAAgJQAAgOAEgMQAFgNAKgIQAIgKAMgFQAMgEANgBQAIAAAGADQAHACAFAEIABgFIAUAAIgUBXIARAAIgFASIglAAIACgHQgHAEgGACQgHACgHABQgJgBgIgDgAgHghQgIADgGAGQgGAGgEAIQgDAJAAALQAAAHABAEQACAFAEAEQACAEAGACQAEABAGABIAIgBIAGgDIAGgDIAHgEIAMg4QgCgDgGgCQgGgDgIAAQgIAAgHAEg");
	this.shape_4.setTransform(138,24.85);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgXA1QgIgDgHgGQgGgHgEgJQgDgJAAgLQAAgNAEgLQAFgMAJgIQAIgJALgFQALgFANAAQAJAAAJADQAHAEAGAFQAFAGADAHQADAIAAAIIgBAKIgBAIIhRAAIAAACIAAACQAAAHACAFQACAGAEAEQAEAEAFACQAGACAFAAQAIAAAHgDQAIgDAEgHIAQALQgEAFgFAEIgKAGIgMAEIgNABQgKAAgJgDgAAggMQAAgGgCgFQgBgFgEgDQgDgDgFgCQgEgCgHAAQgFAAgFACQgFACgFAEIgIAIQgDAFgCAFIA7AAIAAAAg");
	this.shape_5.setTransform(125.65,24.875);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAPA2IAPhAQADgNgFgGQgEgGgMAAQgIAAgGADQgHAEgGAGIgSBMIgVAAIAVhYIgVAAIAFgRIAoAAIgDAKQAHgGAIgDQAJgDAJAAQAJAAAGACQAHACAEAGQAEAFABAIQACAHgCAJIgMAyIAPAAIgEASg");
	this.shape_6.setTransform(112.225,24.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgWA1QgJgDgHgGQgGgHgDgJQgEgJAAgLQAAgNAEgLQAFgMAJgIQAHgJAMgFQALgFAMAAQALAAAHADQAJAEAFAFQAGAGADAHQACAIAAAIIgBAKIgBAIIhQAAIAAACIAAACQAAAHABAFQACAGAFAEQADAEAFACQAGACAGAAQAHAAAHgDQAIgDAEgHIAQALQgEAFgEAEIgLAGIgNAEIgMABQgKAAgIgDgAAggMQABgGgCgFQgCgFgEgDQgDgDgFgCQgFgCgGAAQgFAAgFACQgFACgFAEIgHAIQgEAFgCAFIA7AAIAAAAg");
	this.shape_7.setTransform(94.85,24.875);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAPA2IAPhAQADgNgFgGQgEgGgMAAQgIAAgGADQgHAEgGAGIgSBMIgVAAIAVhYIgVAAIAFgRIAoAAIgDAKQAHgGAIgDQAJgDAJAAQAJAAAGACQAHACAEAGQAEAFABAIQACAHgCAJIgMAyIAPAAIgEASg");
	this.shape_8.setTransform(81.425,24.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgZA0QgJgEgGgGQgHgHgEgIQgDgKgBgKQABgHACgIQACgJAEgGQAEgIAGgGQAGgFAGgFQAIgDAHgCQAIgDAIAAQAKAAAJAEQAJAEAHAGQAGAHAEAJQAEAIgBAKQAAAIgCAJQgCAHgEAHQgEAHgGAHQgFAGgHAEQgHADgIADQgIACgIAAQgKAAgJgEgAgJghQgGACgGAHQgFAFgDAIQgEAJAAAIQAAAHADAGQACAGADAEQAEAEAFADQAGACAGAAQAHAAAGgEQAIgCAFgHQAGgGADgHQADgIAAgJQAAgIgCgGQgCgFgEgFQgEgDgFgCQgFgDgHAAQgGAAgIAEg");
	this.shape_9.setTransform(68.1,24.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgjBNQgIgDgGgGQgGgGgDgJQgEgIAAgKQAAgOAFgMQAFgLAJgJQAJgJALgFQAMgFAMAAQAIAAAHADQAHACAGAEIAJgpIgSAAIAEgSIAnAAIghCNIASAAIgEASIgnAAIACgHQgGAEgFACQgHADgHAAQgJAAgIgEgAgOgIQgIADgGAFQgFAGgEAIQgDAJAAAKQAAAHACAGQACAFADAEQAEAEAFACQAFACAGAAQAGAAAHgDQAGgDAGgFIAMg2QgDgFgGgCQgGgDgJAAQgHAAgHAEg");
	this.shape_10.setTransform(50.875,22.325);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAPA2IAPhAQADgNgFgGQgEgGgMAAQgIAAgGADQgHAEgGAGIgSBMIgVAAIAVhYIgVAAIAFgRIAoAAIgDAKQAHgGAIgDQAJgDAJAAQAJAAAGACQAHACAEAGQAEAFABAIQACAHgCAJIgMAyIAPAAIgEASg");
	this.shape_11.setTransform(36.825,24.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgZBPIAVhYIgTAAIADgRIAnAAIgUBXIAQAAIgDASgAAHgzIgEgDIgDgFIAAgFIAAgFIADgEIAEgEIAGgBIAFABIAEAEIADAEIABAFIgBAFIgDAFIgEADIgFAAg");
	this.shape_12.setTransform(26.55,22.35);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag2BpIAfiIIgWAAIAEgRIAWAAIAFgTQACgLAEgGQAEgIAFgDQAFgFAHgCQAHgCAIAAIAJABIAIABIAGACIAEACIgKAQIgHgDQgFgBgGAAQgIgBgGAFQgFAEgDAMIgEASIAdAAIgEARIgcAAIgfCIg");
	this.shape_13.setTransform(20.025,24.55);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("#FFFFFF").ss(1,1,1).p("AwejbMAg9AAAIAAG3Mgg9AAAg");
	this.shape_14.setTransform(105.5,23);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(-1,0,213,46), null);


(lib.bywhen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shaker();
	this.instance.parent = this;
	this.instance.setTransform(86.3,22.5,1,1,0,0,0,86.3,22.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bywhen, new cjs.Rectangle(-14.5,-10.7,206,64.7), null);


// stage content:
(lib._728x90_bcd_park = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 8
	this.instance = new lib.cta();
	this.instance.parent = this;
	this.instance.setTransform(838.5,45.5,1,1,0,0,0,105.5,22);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(310).to({_off:false},0).wait(1).to({regY:23,x:836.9,y:46.5},0).wait(1).to({x:830.9},0).wait(1).to({x:817.5},0).wait(1).to({x:790.05},0).wait(1).to({x:740.5},0).wait(1).to({x:687.45},0).wait(1).to({x:649.25},0).wait(1).to({x:622.1},0).wait(1).to({x:601.85},0).wait(1).to({x:586.05},0).wait(1).to({x:573.5},0).wait(1).to({x:563.3},0).wait(1).to({x:554.95},0).wait(1).to({x:548.1},0).wait(1).to({x:542.5},0).wait(1).to({x:537.95},0).wait(1).to({x:534.25},0).wait(1).to({x:531.3},0).wait(1).to({x:529.1},0).wait(1).to({x:527.45},0).wait(1).to({x:526.3},0).wait(1).to({x:525.7},0).wait(1).to({regY:22,x:525.5,y:45.5},0).wait(25));

	// Layer 6
	this.instance_1 = new lib.Tween1("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(-169,34.5);
	this.instance_1._off = true;

	this.instance_2 = new lib.Tween2("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(241,34.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_1}]},310).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).wait(25));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(310).to({_off:false},0).wait(1).to({regY:0.5,x:-166.9,y:35},0).wait(1).to({x:-159.05},0).wait(1).to({x:-141.5},0).wait(1).to({x:-105.55},0).wait(1).to({x:-40.65},0).wait(1).to({x:28.8},0).wait(1).to({x:78.85},0).wait(1).to({x:114.4},0).wait(1).to({x:140.95},0).wait(1).to({x:161.6},0).wait(1).to({x:178.1},0).wait(1).to({x:191.45},0).wait(1).to({x:202.35},0).wait(1).to({x:211.35},0).wait(1).to({x:218.65},0).wait(1).to({x:224.65},0).wait(1).to({x:229.5},0).wait(1).to({x:233.3},0).wait(1).to({x:236.25},0).wait(1).to({x:238.4},0).wait(1).to({x:239.85},0).wait(1).to({x:240.7},0).to({_off:true},1).wait(25));

	// Layer 5
	this.instance_3 = new lib.Symbol3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(364,62,1,1,0,0,0,221.8,32.4);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(178).to({_off:false},0).wait(38).to({regX:222.1,regY:20,x:364.3,y:49.35},0).wait(1).to({y:48.5},0).wait(1).to({y:46.05},0).wait(1).to({y:42},0).wait(1).to({y:39.25},0).wait(1).to({y:37.7},0).wait(1).to({y:36.75},0).wait(1).to({y:36.15},0).wait(1).to({y:35.8},0).wait(1).to({y:35.65},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:48},0).wait(75).to({regX:222.1,regY:20,x:364.3,y:35.75},0).wait(1).to({y:36.3},0).wait(1).to({y:37.4},0).wait(1).to({y:39.15},0).wait(1).to({y:41.95},0).wait(1).to({y:46.2},0).wait(1).to({y:52.95},0).wait(1).to({y:64.25},0).wait(1).to({y:80.15},0).wait(1).to({y:92.6},0).wait(1).to({y:100.25},0).wait(1).to({y:105.1},0).wait(1).to({y:108.4},0).wait(1).to({y:110.55},0).wait(1).to({y:112.05},0).wait(1).to({y:112.95},0).wait(1).to({y:113.45},0).wait(1).to({regX:221.8,regY:32.4,x:364,y:126},0).to({_off:true},2).wait(38));

	// Layer 4
	this.instance_4 = new lib.bywhen();
	this.instance_4.parent = this;
	this.instance_4.setTransform(1116.5,43.65,4.7999,4.7999,5.998,0,0,86.5,22.7);
	this.instance_4._off = true;

	this.instance_5 = new lib.Symbol5();
	this.instance_5.parent = this;
	this.instance_5.setTransform(364,60.75,1,1,0,0,0,221.8,17.7);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(89).to({_off:false},0).wait(1).to({regX:87.6,regY:22.2,scaleX:4.5595,scaleY:4.5595,rotation:5.1965,x:1084.55,y:41.8},0).wait(1).to({scaleX:4.1349,scaleY:4.1349,rotation:3.7814,x:1018.4,y:41.9},0).wait(1).to({scaleX:3.6581,scaleY:3.6581,rotation:2.1925,x:944.15,y:41.95},0).wait(1).to({scaleX:3.1709,scaleY:3.1709,rotation:0.5689,x:868.3,y:42.05},0).wait(1).to({scaleX:2.6963,scaleY:2.6963,rotation:-1.0126,x:794.4,y:42.2},0).wait(1).to({scaleX:2.2519,scaleY:2.2519,rotation:-2.4936,x:725.25,y:42.3},0).wait(1).to({scaleX:1.855,scaleY:1.855,rotation:-3.8165,x:663.5,y:42.5},0).wait(1).to({scaleX:1.5258,scaleY:1.5258,rotation:-4.9133,x:612.25,y:42.6},0).wait(1).to({scaleX:1.2927,scaleY:1.2927,rotation:-5.6903,x:576,y:42.7},0).wait(1).to({regX:86.3,regY:22.6,scaleX:1.2,scaleY:1.2,rotation:-5.9991,x:560.3,y:43.6},0).to({_off:true},79).wait(180));
	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(215).to({_off:false},0).to({alpha:1},16).wait(70).to({regX:222.1,regY:20.1,x:364.3,y:63.3},0).wait(1).to({y:63.8},0).wait(1).to({y:64.75},0).wait(1).to({y:66.35},0).wait(1).to({y:68.85},0).wait(1).to({y:72.65},0).wait(1).to({y:78.7},0).wait(1).to({y:88.85},0).wait(1).to({y:103.1},0).wait(1).to({y:114.3},0).wait(1).to({y:121.15},0).wait(1).to({y:125.55},0).wait(1).to({y:128.45},0).wait(1).to({y:130.45},0).wait(1).to({y:131.75},0).wait(1).to({y:132.55},0).wait(1).to({y:133},0).wait(1).to({regX:221.8,regY:17.7,x:364,y:130.75},0).to({_off:true},1).wait(39));

	// Layer 3
	this.instance_6 = new lib.Symbol2();
	this.instance_6.parent = this;
	this.instance_6.setTransform(784,49,0.6,0.6,0,0,0,112.1,112.9);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(4).to({_off:false},0).wait(1).to({regX:104.4,regY:116.4,x:768.6,y:50.7},0).wait(1).to({x:755,y:50.15},0).wait(1).to({x:737.3,y:49.5},0).wait(1).to({x:713.4,y:48.55},0).wait(1).to({x:681.05,y:47.3},0).wait(1).to({x:644.05,y:45.85},0).wait(1).to({x:612.8,y:44.6},0).wait(1).to({x:589.9,y:43.7},0).wait(1).to({x:572.85,y:43.05},0).wait(1).to({x:559.65,y:42.5},0).wait(1).to({x:549.15,y:42.1},0).wait(1).to({x:540.6,y:41.8},0).wait(1).to({x:533.5,y:41.5},0).wait(1).to({x:527.5,y:41.25},0).wait(1).to({x:522.45,y:41.05},0).wait(1).to({x:518.15,y:40.9},0).wait(1).to({x:514.5,y:40.75},0).wait(1).to({x:511.35,y:40.65},0).wait(1).to({x:508.7,y:40.55},0).wait(1).to({x:506.4,y:40.45},0).wait(1).to({x:504.5,y:40.35},0).wait(1).to({x:502.9,y:40.3},0).wait(1).to({x:501.6,y:40.25},0).wait(1).to({x:500.55,y:40.2},0).wait(1).to({x:499.7},0).wait(1).to({x:499.1,y:40.15},0).wait(1).to({x:498.7},0).wait(1).to({x:498.45},0).wait(1).to({regX:112.1,regY:112.9,x:503,y:38},0).wait(55).to({regX:104.4,regY:116.4,scaleX:0.6013,scaleY:0.6013,x:497.8,y:40.2},0).wait(1).to({scaleX:0.6059,scaleY:0.6059,x:495.8,y:40.4},0).wait(1).to({scaleX:0.6147,scaleY:0.6147,x:492,y:40.75},0).wait(1).to({scaleX:0.6294,scaleY:0.6294,x:485.7,y:41.35},0).wait(1).to({scaleX:0.6522,scaleY:0.6522,x:475.9,y:42.35},0).wait(1).to({scaleX:0.6866,scaleY:0.6866,x:461,y:43.8},0).wait(1).to({scaleX:0.7353,scaleY:0.7353,x:440.05,y:45.95},0).wait(1).to({scaleX:0.7932,scaleY:0.7932,x:415.05,y:48.45},0).wait(1).to({scaleX:0.8461,scaleY:0.8461,x:392.25,y:50.7},0).wait(1).to({scaleX:0.8867,scaleY:0.8867,x:374.75,y:52.4},0).wait(1).to({scaleX:0.9162,scaleY:0.9162,x:362.05,y:53.7},0).wait(1).to({scaleX:0.9375,scaleY:0.9375,x:352.85,y:54.6},0).wait(1).to({scaleX:0.9529,scaleY:0.9529,x:346.25,y:55.25},0).wait(1).to({scaleX:0.9639,scaleY:0.9639,x:341.5,y:55.75},0).wait(1).to({scaleX:0.9714,scaleY:0.9714,x:338.25,y:56.05},0).wait(1).to({scaleX:0.9762,scaleY:0.9762,x:336.15,y:56.3},0).wait(1).to({scaleX:0.9789,scaleY:0.9789,x:335.05,y:56.4},0).wait(1).to({regX:112.4,regY:112.8,scaleX:0.9797,scaleY:0.9797,x:342.3,y:53},0).wait(1).to({regX:104.4,regY:116.4,x:334.4,y:56.55},0).wait(1).to({x:334.35,y:56.5},0).wait(1).to({x:334.25,y:56.45},0).wait(1).to({x:334.05,y:56.35},0).wait(1).to({x:333.8,y:56.15},0).wait(1).to({x:333.45,y:55.95},0).wait(1).to({x:333.05,y:55.65},0).wait(1).to({x:332.65,y:55.4},0).wait(1).to({x:332.25,y:55.1},0).wait(1).to({x:331.9,y:54.9},0).wait(1).to({x:331.7,y:54.75},0).wait(1).to({x:331.55,y:54.65},0).wait(1).to({x:331.45,y:54.6},0).wait(1).to({regX:112.4,regY:112.8,x:339.3,y:51},0).wait(1).to({regX:104.4,regY:116.4,x:331.45,y:54.55},0).wait(1).to({x:331.5},0).wait(1).to({x:331.6},0).wait(1).to({x:331.75},0).wait(1).to({x:331.95},0).wait(1).to({x:332.2},0).wait(1).to({x:332.55},0).wait(1).to({x:332.95},0).wait(1).to({x:333.45},0).wait(1).to({x:333.95},0).wait(1).to({x:334.5},0).wait(1).to({x:334.95},0).wait(1).to({x:335.4},0).wait(1).to({x:335.75},0).wait(1).to({x:336},0).wait(1).to({x:336.2},0).wait(1).to({x:336.35},0).wait(1).to({x:336.4},0).wait(1).to({regX:112.4,regY:112.8,x:344.3,y:51},0).wait(1).to({regX:104.4,regY:116.4,x:336.45,y:54.55},0).wait(18).to({regX:112.4,regY:112.8,x:344.3,y:51},0).wait(1).to({regX:104.4,regY:116.4,x:336.45,y:54.6},0).wait(3).to({x:336.5,y:54.65},0).wait(2).to({x:336.55,y:54.7},0).wait(1).to({x:336.6,y:54.75},0).wait(1).to({x:336.7,y:54.85},0).wait(1).to({x:336.8,y:54.95},0).wait(1).to({x:336.9,y:55.05},0).wait(1).to({x:337,y:55.15},0).wait(1).to({x:337.1,y:55.25},0).wait(1).to({x:337.15,y:55.3},0).wait(1).to({x:337.25,y:55.4},0).wait(1).to({x:337.3,y:55.45},0).wait(1).to({x:337.35,y:55.5},0).wait(1).to({x:337.4,y:55.55},0).wait(3).to({regX:112.4,regY:112.8,x:345.3,y:52},0).to({_off:true},1).wait(180));

	// Layer 2
	this.instance_7 = new lib.Symbol1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(-140.65,45.75,1,1,0,0,0,136.3,32.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(1).to({regX:155.1,regY:34.8,x:-107.6,y:48.15},0).wait(1).to({x:-89.7},0).wait(1).to({x:-66.4},0).wait(1).to({x:-34.95},0).wait(1).to({x:7.65},0).wait(1).to({x:56.4},0).wait(1).to({x:97.5},0).wait(1).to({x:127.7},0).wait(1).to({x:150.15},0).wait(1).to({x:167.45},0).wait(1).to({x:181.25},0).wait(1).to({x:192.55},0).wait(1).to({x:201.9},0).wait(1).to({x:209.75},0).wait(1).to({x:216.4},0).wait(1).to({x:222.1},0).wait(1).to({x:226.9},0).wait(1).to({x:231.05},0).wait(1).to({x:234.55},0).wait(1).to({x:237.55},0).wait(1).to({x:240.05},0).wait(1).to({x:242.15},0).wait(1).to({x:243.9},0).wait(1).to({x:245.25},0).wait(1).to({x:246.35},0).wait(1).to({x:247.15},0).wait(1).to({x:247.7},0).wait(1).to({x:248},0).wait(1).to({regX:136.3,regY:32.4,x:229.35,y:45.75},0).wait(59).to({regX:155.1,regY:34.8,scaleX:1.0058,scaleY:1.0058,x:245.8,y:48.15},0).wait(1).to({scaleX:1.0266,scaleY:1.0266,x:237.5,y:48.2},0).wait(1).to({scaleX:1.0714,scaleY:1.0714,x:219.5,y:48.3},0).wait(1).to({scaleX:1.1609,scaleY:1.1609,x:183.6,y:48.5},0).wait(1).to({scaleX:1.3589,scaleY:1.3589,x:104.25,y:48.95},0).wait(1).to({scaleX:1.7681,scaleY:1.7681,x:-59.85,y:50},0).wait(1).to({scaleX:2.0517,scaleY:2.0517,x:-173.6,y:50.6},0).wait(1).to({scaleX:2.2074,scaleY:2.2074,x:-236.05,y:50.95},0).wait(1).to({scaleX:2.3084,scaleY:2.3084,x:-276.5,y:51.25},0).wait(1).to({scaleX:2.3794,scaleY:2.3794,x:-305,y:51.4},0).wait(1).to({scaleX:2.4314,scaleY:2.4314,x:-325.9,y:51.5},0).wait(1).to({scaleX:2.4701,scaleY:2.4701,x:-341.4,y:51.6},0).wait(1).to({scaleX:2.4988,scaleY:2.4988,x:-352.95,y:51.65},0).wait(1).to({scaleX:2.5198,scaleY:2.5198,x:-361.35,y:51.7},0).wait(1).to({scaleX:2.5346,scaleY:2.5346,x:-367.3,y:51.75},0).wait(1).to({scaleX:2.5443,scaleY:2.5443,x:-371.2,y:51.8},0).wait(1).to({scaleX:2.5497,scaleY:2.5497,x:-373.3},0).wait(1).to({regX:136.2,regY:32.4,scaleX:2.5514,scaleY:2.5514,x:-422.1,y:45.75},0).to({_off:true},113).wait(140));

	// bg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#F0B0AD").s().p("Eg43AHCIAAuDMBxvAAAIAAODg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(358));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-346.9,-121.4,1981.1999999999998,366.9);
// library properties:
lib.properties = {
	id: '2672068B7FDB4113A44DB72DDA239F2C',
	width: 728,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/728x90_bcd_park_atlas_.png", id:"728x90_bcd_park_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['2672068B7FDB4113A44DB72DDA239F2C'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;