(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"728x90_zebra_atlas_", frames: [[0,273,300,250],[254,726,226,185],[0,0,300,271],[254,525,227,199],[0,525,252,260]]}
];


// symbols:



(lib.bb_bg = function() {
	this.spriteSheet = ss["728x90_zebra_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.bb_pandas = function() {
	this.spriteSheet = ss["728x90_zebra_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.bb_pingu = function() {
	this.spriteSheet = ss["728x90_zebra_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.bb_redpa = function() {
	this.spriteSheet = ss["728x90_zebra_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.zebras = function() {
	this.spriteSheet = ss["728x90_zebra_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgHAsQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAgBIAAgnIgggsIgBgBIACgBIAUAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABIARAcIASgcQABgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAUAAIACABIgBABIggAsIAAAnQAAABAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape.setTransform(672.2,-161.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAWAsQAAAAAAAAQgBAAAAAAQAAAAAAgBQgBAAAAgBIgFgQIgdAAIgFAQQAAABgBAAQAAABAAAAQAAAAgBAAQAAAAAAAAIgRAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAABgBIAehTIACgDIAPAAIACADIAfBTQAAABAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAgAgJAKIATAAIgKgdg");
	this.shape_1.setTransform(664.8,-161.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AglAsQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhTQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAjAAQASAAAMANQAMAMAAASQAAATgNAMQgNANgSAAgAgTAbIANAAQAKAAAIgIQAIgIAAgLQAAgMgKgJQgEgEgIgBIgEAAIgIAAIgFAAg");
	this.shape_2.setTransform(656.4,-161.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AggAhQgOgNAAgUQAAgSAOgNQAOgNASgBQATABANANQAOANABASQgBAUgOANQgMAMgUAAQgSAAgOgMgAgRgSQgIAIAAAKQgBAMAIAHQAIAIAKAAQALAAAIgIQAIgHAAgMQAAgKgIgIQgIgIgLAAQgKAAgHAIg");
	this.shape_3.setTransform(646.3,-161.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgGAsQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAhEIgXAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgNQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIA/AAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAANQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAgBAAIgWAAIAABEQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_4.setTransform(638.2,-161.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeAjQgBAAAAAAQAAgBAAAAQAAAAAAgBQAAAAABAAIAJgLQAAgBAAAAQAAAAABAAQAAAAAAAAQABAAAAAAQAJAHAKAAQAMAAAAgKQABgEgIgDIgFgDIgIgCQgMgEgFgEQgHgHAAgLQAAgFADgFQACgEAEgEQAEgDAHgCQAGgBAHAAQANAAANAHQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAIgIAMQAAABgBAAQAAAAAAAAQAAAAgBAAQAAAAAAAAQgJgGgJAAQgLAAAAAHQgBAFAJADIAIADIAJADQATAGAAASQAAAMgJAIQgKAHgOAAQgQAAgOgKg");
	this.shape_5.setTransform(628.3,-161.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgGAsQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhEIgWAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgNQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIA/AAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAANQAAABAAAAQAAAAAAAAQAAABgBAAQAAAAgBAAIgXAAIAABEQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_6.setTransform(621.4,-161.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgfAsQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhTQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIA/AAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAAANQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIguAAIAAASIAnAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAMQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgnAAIAAATIAuAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIAAANQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_7.setTransform(614.2,-161.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AANAsQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAgBAAIgUghIgFAHIAAAZQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAgBAAIgPAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAhTQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAPAAQABAAAAAAQABAAAAAAQAAABAAAAQAAAAAAABIAAAgIAXggQABgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAVAAIABABIAAABIgfAlIAhAuIAAABIgBABg");
	this.shape_8.setTransform(606.3,-161.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgXAgQgNgNAAgTQAAgSANgOQAOgNASABQANgBAOAKQABAAAAAAQAAAAAAABQAAAAAAAAQAAABAAAAIgIAMQgBABAAAAQAAAAAAAAQgBAAAAAAQAAAAgBAAQgJgGgIAAQgKgBgIAJQgHAIAAAKQAAALAHAIQAIAIAKAAQAGAAAFgCIADgDIADgCQABAAAAAAQAAAAABAAQAAAAAAABQAAAAABAAIAIANQAAAAAAAAQAAAAAAABQAAAAAAAAQAAABgBAAQgLAKgQAAQgTgBgNgNg");
	this.shape_9.setTransform(598,-161.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgHAsQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAhTQAAgBAAAAQAAAAABgBQAAAAAAAAQABAAAAAAIAPAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAABTQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_10.setTransform(591.8,-161.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgGAsQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAhEIgYAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAgBIAAgNQAAgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIBAAAQABAAAAAAQABAAAAAAQAAABAAAAQABAAAAABIAAANQAAABgBAAQAAAAAAAAQAAABgBAAQAAAAgBAAIgWAAIAABEQAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_11.setTransform(586.6,-161.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgHAsQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAgnIgggsIgBgBIACgBIAUAAQAAAAABAAQAAAAABAAQAAABAAAAQABAAAAABIARAcIASgcQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAUAAIACABIgBABIggAsIAAAnQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAg");
	this.shape_12.setTransform(576.1,-161.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgOAqQgHgCgFgFQgEgFgDgGQgCgHAAgIIAAgzQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAABAAIAPAAQABAAAAAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAxQAAAUAQAAQARAAAAgUIAAgxQAAAAAAgBQAAAAABAAQAAAAAAgBQAAAAABAAIAPAAQABAAAAAAQAAABABAAQAAAAAAAAQAAABAAAAIAAAzQAAAIgCAHQgDAGgEAFQgFAFgHACQgGADgJAAQgIAAgGgDg");
	this.shape_13.setTransform(567.5,-161.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgeAsQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAhTQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAdAAQAJAAAHAEQALAGAAAMQAAAOgLAFIAAAAQASAEAAASQAAAMgKAHQgIAFgNAAgAgNAbIANAAQAFAAADgBQAFgDAAgFQAAgKgRAAIgJAAgAgNgIIAFAAQAOAAAAgKQAAgFgEgCQgCgBgDAAIgKAAg");
	this.shape_14.setTransform(559.3,-161.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f().s("#FFFFFF").ss(2,1,1).p("AqniIIVPAAIAAERI1PAAg");
	this.shape_15.setTransform(616,-161.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol8, new cjs.Rectangle(547,-175.9,138,29.4), null);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMAOQgHgGABgIQgBgHAHgGQAFgFAHAAQAIAAAGAFQAFAGAAAHQAAAIgFAGQgGAFgIAAQgHAAgFgFg");
	this.shape.setTransform(216.5,63.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAh0IgnAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgXQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAXQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgnAAIAAB0QAAABAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_1.setTransform(209.5,58);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAgBIAAiOQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAAAIAACOQAAABgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_2.setTransform(200.6,58);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_3.setTransform(191.1,58);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAAAIAACOQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_4.setTransform(181.7,58);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgOBLQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAgBIg0iPQgBgDAEAAIAdAAQABAAAAAAQAAAAABABQAAAAABABQAAAAABABIAhBqIAjhqQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAeAAQAAAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAQAAAAAAABIg1COQAAABgBABQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_5.setTransform(171.3,58);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("Ag2A4QgYgXAAghQAAghAYgWQAXgVAfAAQAgAAAXAVQAYAWAAAhQAAAhgYAXQgWAVghAAQgfAAgXgVgAgfgfQgNAOAAARQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgNQgNgOgTAAQgSAAgNAOg");
	this.shape_6.setTransform(149.7,58);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgMBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAgBIAAh0IgnAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgXQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAXQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgnAAIAAB0QAAABAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_7.setTransform(136,58);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_8.setTransform(119.1,58);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAlBLIgCgBIhEheIAABbQAAABAAABQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIAAiOQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABABAAIBDBcIAAhbQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAACOQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_9.setTransform(104.9,58);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag2A4QgYgXAAghQAAghAYgWQAXgVAfAAQAgAAAXAVQAYAWAAAhQAAAhgYAXQgWAVghAAQgfAAgXgVgAgfgfQgNAOAAARQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgNQgNgOgTAAQgSAAgNAOg");
	this.shape_10.setTransform(88,58);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_11.setTransform(73.2,58);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_12.setTransform(59.9,57.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAgBIAAiOQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQAAABAAAAIAAAXQAAABAAABQAAAAAAABQgBAAAAAAQgBAAAAAAIhPAAIAAAfIBCAAQABAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhCAAIAAAgIBPAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAWQAAABAAABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_13.setTransform(46.1,58);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAYBLQgDAAgCgEIgYgwIgWAAIAAAwQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAPQANAOAAAVQAAAPgJAMQgJANgOAFIAbAxIABAEQAAAAAAAAQgBAAAAABQAAAAgBAAQgBAAAAAAgAgbgEIAiAAQAHAAAHgFQAHgHAAgIQAAgKgHgGQgHgFgHAAIgiAAg");
	this.shape_14.setTransform(31.8,58);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#BEA149").s().p("AgxA3QgVgXAAggQAAgeAWgXQAXgXAfAAQAXAAAYAQQABAAAAABQABAAAAAAQAAABAAABQgBAAAAABIgOAVQgBADgDgCQgPgLgPAAQgRAAgNAOQgNAOAAARQAAATANAOQANANARAAQAUAAAMgKIAAgMIgbAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgYQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIA5AAQABAAABAAQAAABABAAQAAAAAAABQABABAAAAIAABKQAAABgBABQAAAAAAABQgBAAAAABQgBAAgBAAIgaAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAgBIAAgBQgPAHgRAAQghAAgWgWg");
	this.shape_15.setTransform(197.8,35.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEhdIAABaQAAABAAABQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIAAiOQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAABAAQAAAAAAAAQABABAAAAQAAABABAAIBDBcIAAhbQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAACOQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_16.setTransform(181.6,35.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAgBIAAiOQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAAAIAACOQAAABgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_17.setTransform(170.2,35.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#BEA149").s().p("Ag4BLQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBBAAQAVAAAPAPQAPAPAAAXQAAAWgPAPQgPAPgVAAIgjAAIAAAoQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAgAgaABIAcAAQALAAAHgEQAHgGAAgMQAAgNgIgFQgGgGgLAAIgcAAg");
	this.shape_18.setTransform(160.1,35.7);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#BEA149").s().p("Ag4BLQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBBAAQAVAAAPAPQAPAPAAAXQAAAWgPAPQgPAPgVAAIgjAAIAAAoQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAgAgaABIAcAAQALAAAHgEQAHgGAAgMQAAgNgIgFQgGgGgLAAIgcAAg");
	this.shape_19.setTransform(145.6,35.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#BEA149").s().p("Ag2A3QgYgWAAghQAAggAYgXQAXgVAfAAQAgAAAXAVQAYAXAAAgQAAAigYAVQgWAWghAAQgfAAgXgWgAgfgfQgNANAAASQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgNQgNgOgTAAQgSAAgNAOg");
	this.shape_20.setTransform(129.2,35.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAh0IgnAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgXQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAXQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgnAAIAAB0QAAABAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_21.setTransform(115.5,35.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_22.setTransform(104.2,35.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#BEA149").s().p("AAeBLQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAgBAAgBIgchYIgbBYQAAABAAABQgBAAAAABQAAAAgBAAQAAAAAAAAIgjAAQgBAAAAAAQAAAAgBAAQAAgBAAAAQgBgBAAgBIgtiPQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIAeAAQAAAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAeBqIAfhqQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAcAAQAAAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAfBqIAehqQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAIAeAAQABAAAAAAQABAAAAABQAAAAAAABQAAABAAABIguCOQAAABAAABQgBAAAAABQAAAAgBAAQAAAAgBAAg");
	this.shape_23.setTransform(81,35.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#BEA149").s().p("Ag2A3QgYgWAAghQAAggAYgXQAXgVAfAAQAgAAAXAVQAYAXAAAgQAAAigYAVQgWAWghAAQgfAAgXgWgAgfgfQgNANAAASQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgNQgNgOgTAAQgSAAgNAOg");
	this.shape_24.setTransform(61,35.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#BEA149").s().p("AAiBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAgBIAAg5Ig8AAIAAA5QAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAaAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAAA5IA8AAIAAg5QAAAAAAgBQAAgBABAAQAAgBAAAAQABAAABAAIAaAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAAAIAACOQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_25.setTransform(44.2,35.7);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_26.setTransform(30.1,35.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_27.setTransform(140.5,15);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_28.setTransform(128.6,15);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBrAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAAAWQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAIhNAAIAAAeIBBAAQABAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhBAAIAAAgIBNAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAXQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_29.setTransform(116.4,15);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#BEA149").s().p("AgoBLQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAB0IA1AAQAAAAABAAQABAAAAABQAAAAABABQAAAAAAABIAAAXQAAAAAAABQgBABAAAAQAAABgBAAQgBAAAAAAg");
	this.shape_30.setTransform(104.1,15);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_31.setTransform(92.3,15);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEheIAABcQAAAAAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAAAAAQABAAAAABQABAAAAAAQAAABABAAIBDBcIAAhaQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAACOQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_32.setTransform(78.5,15);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#BEA149").s().p("AgZBIQgMgFgHgIQgIgHgFgMQgDgLAAgPIAAhVQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAABSQAAAiAcAAQAdAAAAgiIAAhSQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAaAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAABVQAAAPgFALQgEAMgHAHQgJAIgLAFQgMAEgOAAQgOAAgLgEg");
	this.shape_33.setTransform(62.8,15.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#BEA149").s().p("Ag2A4QgYgXAAghQAAggAYgXQAXgVAfAAQAgAAAXAVQAYAXAAAgQAAAigYAWQgWAVghAAQgfAAgXgVgAgfggQgNAPAAARQAAATANANQANAOASAAQATAAANgOQANgNAAgTQAAgSgNgOQgNgNgTAAQgSAAgNANg");
	this.shape_34.setTransform(46.4,15);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#BEA149").s().p("AgoA4QgWgWAAgiQAAgeAXgXQAWgXAfAAQAYAAAXAQQABAAABABQAAAAAAABQAAAAAAABQAAAAgBABIgNAVQgCADgDgCQgPgLgPABQgRAAgNANQgNAOAAARQAAATANANQANAOARAAQALAAAIgEIAGgDIAFgDQABgBABAAQAAAAABAAQAAAAABABQAAAAABABIANAUQABAAAAABQAAABAAAAQAAABAAAAQgBABgBAAQgTAQgcAAQgfAAgXgVg");
	this.shape_35.setTransform(31.2,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol7, new cjs.Rectangle(22,0,199.7,72.8), null);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AoyRKQidhkh3iYQizjmhMklQiMoaF2lpQEHj/F1AfIEOAYIgVJuICgD5IGQgeIIiSQQl1BYmEAVQguACgtAAQnGAAmEj2g");
	mask.setTransform(63,134.4);

	// Layer_1
	this.instance = new lib.zebras();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol6, new cjs.Rectangle(0,54,176.3,206), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bb_redpa();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(0,0,227,199), null);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BEA149").s().p("AgwA3QgXgXAAggQAAgeAYgXQAWgXAfAAQAXAAAYAQQABAAAAABQABAAAAAAQAAABAAABQAAAAgBABIgNAVQgCADgEgCQgOgLgPAAQgRAAgNAOQgNAOAAARQAAATANAOQANANARAAQAUAAANgKIAAgMIgcAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgYQAAAAAAgBQAAgBABAAQAAAAABgBQAAAAABAAIA5AAQABAAABAAQAAABABAAQAAAAAAABQAAABAAAAIAABKQAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAIgaAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAgBQgQAHgRAAQghAAgVgWg");
	this.shape.setTransform(171.7,-159);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEheIAABbQAAABAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIAAiOQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAAAAAQABAAAAAAQABABAAAAQAAABABAAIBDBcIAAhbQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAACOQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(155.6,-159);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAAAIAACOQAAABAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_2.setTransform(144.1,-159);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEheIAABbQAAABAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAgBIAAiOQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAAAAAQABAAAAAAQABABAAAAQAAABABAAIBDBcIAAhbQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAACOQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_3.setTransform(132.6,-159);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#BEA149").s().p("AAYBLQgDAAgCgEIgYgvIgWAAIAAAvQAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAPQANAOAAAUQAAARgJALQgJANgOAFIAbAxIABADQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgbgEIAiAAQAHAAAHgFQAHgHAAgJQAAgJgHgGQgHgFgHAAIgiAAg");
	this.shape_4.setTransform(117.6,-159);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BEA149").s().p("AgZBHQgMgDgHgJQgIgIgEgKQgFgMAAgPIAAhWQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAABUQAAAhAcAAQAdAAAAghIAAhUQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAbAAQAAAAABAAQAAAAABABQAAAAAAABQABABAAAAIAABWQgBAPgEAMQgEAKgIAIQgHAJgMADQgLAFgPAAQgOAAgLgFg");
	this.shape_5.setTransform(102.2,-158.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAh0IgnAAQgBAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgXQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAAAXQAAABAAABQAAAAgBABQAAAAgBAAQAAAAgBAAIgnAAIAAB0QAAABAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_6.setTransform(88.9,-159);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#BEA149").s().p("Ag/BLQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAiPQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIA6AAQAgAAAUAWQAUAVAAAfQAAAggWAVQgWAWgeAAgAghAuIAWAAQASAAANgNQAOgOAAgTQAAgWgQgOQgIgIgOgBIgHgBIgOAAIgIAAg");
	this.shape_7.setTransform(70.6,-159);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#BEA149").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_8.setTransform(55.3,-159.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAgBIAAiOQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQABABAAAAIAAAXQAAABgBABQAAAAAAABQgBAAAAAAQgBAAAAAAIhOAAIAAAfIBBAAQABAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhBAAIAAAgIBOAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAWQAAABgBABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_9.setTransform(41.5,-159);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#BEA149").s().p("AAiBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAg5Ig8AAIAAA5QAAABAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAgBIAAiOQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAaAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAAA5IA8AAIAAg5QAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAABAAQAAAAAAABQABAAAAABQAAABAAAAIAACOQAAABAAABQAAABgBAAQAAABAAAAQgBAAgBAAg");
	this.shape_10.setTransform(26,-159);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol4, new cjs.Rectangle(16,-174,166.5,29.8), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bb_pandas();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,0,226,185), null);


(lib.Symbol2copy4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAAWQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIhPAAIAAAeIBDAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIhDAAIAAAgIBPAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAXQAAAAAAABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape.setTransform(152,15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BEA149").s().p("AgoBLQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAaAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAB0IA1AAQABAAAAAAQABAAAAABQAAAAABABQAAAAAAABIAAAXQAAAAAAABQgBABAAAAQAAABgBAAQAAAAgBAAg");
	this.shape_1.setTransform(139.7,15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BEA149").s().p("AgzBLQgBAAgBAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQABAAABAAIAxAAQAQAAAMAHQASALAAAVQAAAWgTAIIAAABQAfAIAAAeQAAAVgRALQgOAJgVAAgAgWAuIAWAAQAJAAAFgDQAJgDgBgJQAAgRgdgBIgPAAgAgWgOIAIAAQAYAAAAgSQAAgIgGgDQgEgBgGAAIgQAAg");
	this.shape_2.setTransform(127.4,15);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAACOQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_3.setTransform(116.8,15);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBABAAQAAgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_4.setTransform(107.8,15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_5.setTransform(96.5,15);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAACOQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_6.setTransform(87.1,15);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#BEA149").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBABAAAAQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_7.setTransform(77.6,15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBrAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAAAWQAAABgBABQAAAAAAABQgBAAAAAAQgBABgBAAIhOAAIAAAeIBDAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAAAAAIhDAAIAAAgIBOAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAXQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_8.setTransform(65.4,15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#BEA149").s().p("AAYBLQgDAAgCgDIgYgxIgWAAIAAAxQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAPQANAOAAAVQAAAQgJALQgJANgOAFIAbAxIABAEQAAAAAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAgAgbgEIAiAAQAHAAAHgFQAHgHAAgIQAAgKgHgGQgHgFgHAAIgiAAg");
	this.shape_9.setTransform(51.1,15);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#BEA149").s().p("AAYBLQgDAAgCgDIgYgxIgWAAIAAAxQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAPQANAOAAAVQAAAQgJALQgJANgOAFIAbAxIABAEQAAAAAAAAQgBAAAAABQAAAAgBAAQgBAAAAAAgAgbgEIAiAAQAHAAAHgFQAHgHAAgIQAAgKgHgGQgHgFgHAAIgiAAg");
	this.shape_10.setTransform(36.5,15);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_11.setTransform(25.4,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2copy4, new cjs.Rectangle(20,0,140.3,29.8), null);


(lib.Symbol2copy2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BEA149").s().p("AgoA4QgWgWAAgiQAAgeAXgXQAWgXAfAAQAYAAAXAQQABAAABABQAAAAAAABQAAAAAAABQAAAAgBABIgNAVQgCADgDgCQgPgLgPABQgRAAgNANQgNAOAAARQAAATANANQANAOARAAQALAAAIgEIAGgDIAFgDQABgBABAAQAAAAABAAQAAAAABABQAAAAABABIANAUQABAAAAABQAAABAAAAQAAABAAAAQgBABgBAAQgTAQgcAAQgfAAgXgVg");
	this.shape.setTransform(122.9,15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQABABAAABIAACOQAAAAgBABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(112.5,15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_2.setTransform(103.5,15);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BEA149").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_3.setTransform(91.7,14.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#BEA149").s().p("AAvBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAhWIgeAyQgBABAAABQgBAAAAABQAAAAgBAAQAAAAAAAAIgUAAIgEgDIgdgyIAABWQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgZAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAbAAQABAAAAAAQAAAAABABQAAAAABABQAAABABABIAoBGIAphGIAEgEIAbAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_4.setTransform(75.6,15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BEA149").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_5.setTransform(59.5,14.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BEA149").s().p("AAYBLQgDAAgCgDIgYgxIgWAAIAAAxQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAPQANAOAAAVQAAAQgJALQgJANgOAFIAbAxIABAEQAAAAAAAAQgBAAAAABQAAAAgBAAQgBAAAAAAgAgbgEIAiAAQAHAAAHgFQAHgHAAgIQAAgKgHgGQgHgFgHAAIgiAAg");
	this.shape_6.setTransform(45.8,15);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#BEA149").s().p("Ag/BLQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIA6AAQAgAAAUAWQAUAVAAAfQAAAggWAWQgWAVgeAAgAghAvIAWAAQASAAANgOQAOgOAAgTQAAgWgQgOQgIgIgOgBIgHgBIgOAAIgIAAg");
	this.shape_7.setTransform(30.4,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2copy2, new cjs.Rectangle(20,0,111.9,29.8), null);


(lib.Symbol2copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape.setTransform(117.1,9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAlBLIgCgBIhEhdIAABbQAAAAAAABQgBABAAAAQAAABgBAAQAAAAgBAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiPQAAAAAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABABIBDBcIAAhbQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAAAIAACPQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(102.9,9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ag2A3QgYgWAAghQAAghAYgVQAXgWAfAAQAgAAAXAWQAYAVAAAhQAAAhgYAWQgWAWghAAQgfAAgXgWgAgfggQgNAOAAASQAAATANAOQANANASAAQATAAANgNQANgOAAgTQAAgSgNgOQgNgNgTAAQgSAAgNANg");
	this.shape_2.setTransform(86,9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ag0A8QgBgBAAAAQgBgBAAAAQAAgBABgBQAAAAAAgBIAPgTQABAAAAgBQABAAAAAAQABAAABAAQAAAAABABQAPALARAAQAWAAAAgQQAAgIgNgFIgKgEIgMgDQgVgIgIgHQgMgMAAgTQAAgJAEgHQAEgIAHgFQAIgGAKgDQALgDAMAAQAWAAAXANQADACgCADIgNAUQgBAAAAABQgBAAAAABQgBAAgBAAQAAAAgBgBQgOgJgOAAQgVAAgBALQAAAIAPAGIAOAFIAPAFQAhALAAAfQAAAUgQANQgQANgYAAQgdAAgXgRg");
	this.shape_3.setTransform(71.2,9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_4.setTransform(57.9,8.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiPQAAAAABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQABABAAAAIAAAXQAAABgBABQAAAAAAABQgBAAAAAAQgBABAAAAIhOAAIAAAeIBBAAQABAAABAAQABAAAAABQABAAAAABQAAABAAABIAAAVQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhBAAIAAAgIBOAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAXQAAAAgBABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_5.setTransform(44.1,9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAYBLQgDAAgCgDIgYgwIgWAAIAAAwQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiPQAAAAAAgBQAAgBABAAQAAgBABAAQAAAAABAAIBIAAQATAAAOAOQANAPAAAUQAAAQgJAMQgJANgOAFIAbAyIABACQAAABAAAAQgBAAAAABQAAAAgBAAQgBAAAAAAgAgbgEIAiAAQAHAAAHgFQAHgGAAgKQAAgJgHgGQgHgFgHAAIgiAAg");
	this.shape_6.setTransform(29.8,9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2copy, new cjs.Rectangle(20,-6,105.4,29.8), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#BEA149").s().p("AgwA3QgXgXAAggQAAgeAYgXQAWgXAfAAQAXAAAYAQQABAAAAABQABAAAAAAQAAABAAABQAAAAgBABIgNAVQgCADgEgCQgOgLgPAAQgRAAgNAOQgNAOAAARQAAATANAOQANANARAAQAUAAANgKIAAgMIgcAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgYQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIA5AAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABIAABKQAAABAAABQAAAAAAABQgBAAAAABQgBAAgBAAIgaAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAgBQgQAHgRAAQghAAgVgWg");
	this.shape.setTransform(166.8,15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#BEA149").s().p("AAlBLIgCgBIhEheIAABcQAAAAAAABQgBABAAAAQAAABgBAAQgBAAAAAAIgYAAQgBAAgBAAQAAAAgBgBQAAAAgBgBQAAgBAAAAIAAiOQAAgBAAgBQABgBAAAAQABgBAAAAQABAAABAAIAYAAQAAAAAAAAQABAAAAABQABAAAAAAQAAABABAAIBDBcIAAhaQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAYAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAACOQAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_1.setTransform(150.6,15);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIAZAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_2.setTransform(139.2,15);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#BEA149").s().p("AAiBLQgBAAgBAAQAAAAAAgBQgBAAAAgBQAAgBAAAAIAAg6Ig8AAIAAA6QAAAAAAABQgBABAAAAQgBABAAAAQgBAAgBAAIgaAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAgBAAAAIAAiOQAAgBAAgBQAAgBABAAQAAgBABAAQAAAAABAAIAaAAQABAAABAAQAAAAABABQAAAAABABQAAABAAABIAAA4IA8AAIAAg4QAAgBAAgBQAAgBABAAQAAgBAAAAQABAAABAAIAaAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAABIAACOQAAAAAAABQAAABAAAAQgBABAAAAQgBAAgBAAg");
	this.shape_3.setTransform(127.8,15);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#BEA149").s().p("AgoA4QgWgWAAgiQAAgeAXgXQAWgXAfAAQAYAAAXAQQABAAABABQAAAAAAABQAAAAAAABQAAAAgBABIgNAVQgCADgDgCQgPgLgPABQgRAAgNANQgNAOAAARQAAATANANQANAOARAAQALAAAIgEIAGgDIAFgDQABgBABAAQAAAAABAAQAAAAABABQAAAAABABIANAUQABAAAAABQAAABAAAAQAAABAAAAQgBABgBAAQgTAQgcAAQgfAAgXgVg");
	this.shape_4.setTransform(113,15);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAgBAAAAIAAh0IgnAAQgBAAgBgBQAAAAgBAAQAAgBAAAAQAAgBAAgBIAAgWQAAgBAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBtAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAAWQAAABAAABQAAAAgBABQAAAAgBAAQAAABgBAAIgnAAIAAB0QAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_5.setTransform(101.1,15);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#BEA149").s().p("AAmBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIgIgbIgyAAIgJAbQAAABgBAAQAAABAAAAQgBABAAAAQgBAAAAAAIgdAAQgEAAACgEIA0iOQAAgBAAAAQABgBAAAAQABgBAAAAQABAAAAAAIAaAAQAAAAABAAQAAAAAAABQABAAAAABQABAAAAABIA0COQAAABAAABQAAABAAAAQAAABgBAAQgBAAAAAAgAgPARIAgAAIgRgxg");
	this.shape_6.setTransform(89.3,14.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#BEA149").s().p("AgoA4QgWgWAAgiQAAgeAXgXQAWgXAfAAQAYAAAXAQQABAAABABQAAAAAAABQAAAAAAABQAAAAgBABIgNAVQgCADgDgCQgPgLgPABQgRAAgNANQgNAOAAARQAAATANANQANAOARAAQALAAAIgEIAGgDIAFgDQABgBABAAQAAAAABAAQAAAAABABQAAAAABABIANAUQABAAAAABQAAABAAAAQAAABAAAAQgBABgBAAQgTAQgcAAQgfAAgXgVg");
	this.shape_7.setTransform(75.3,15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQABABAAABIAAAWQAAABgBABQAAAAAAABQgBAAAAAAQgBABAAAAIhOAAIAAAeIBBAAQABAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhBAAIAAAgIBOAAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAXQAAAAgBABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_8.setTransform(56.3,15);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#BEA149").s().p("AgMBLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAhDIg3hKIAAgDQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAAAAAIAhAAQAEAAADAEIAdAvIAfgvQACgEADAAIAiAAQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIgBADIg3BKIAABDQAAAAAAABQAAABgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_9.setTransform(42.6,15);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#BEA149").s().p("Ag1BLQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBgBAAAAIAAiOQAAgBABgBQAAgBAAAAQABgBAAAAQABAAABAAIBsAAQAAAAABAAQAAAAABABQAAAAAAABQAAABAAABIAAAWQAAABAAABQAAAAAAABQgBAAAAAAQgBABAAAAIhPAAIAAAeIBCAAQABAAABAAQABAAAAABQABAAAAABQAAABAAAAIAAAWQAAABAAAAQAAABgBAAQAAABgBAAQgBAAgBAAIhCAAIAAAgIBPAAQAAAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAXQAAAAAAABQAAABAAAAQgBABAAAAQgBAAAAAAg");
	this.shape_10.setTransform(29.5,15);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(20,0,157.6,29.8), null);


(lib.Symbol1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AB/SgQAAgDjjmmQjimigCgIIAAAAIAAAAQgHgDjOiAQAEADh4AlQh4AmADADQAEADhugsQhmgogEAAQADgKgXq1QgYrCADACQW1FUAHAFQAEACEiE3IElE6QAEADgsLMQgsLMADADQABABgYAAQhzAAqqgWgAB/SgIAAAAIAAAAIAAAAg");
	mask.setTransform(171.1,111);

	// Layer_1
	this.instance = new lib.zebras();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1copy, new cjs.Rectangle(68.3,0,183.8,231.6), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AmKPHQgHgGpj7IQgDgDHfhdQHNhaAOgFQgDAIABDAIADDMIC/DLQABgFB0guQB3gwgDgCQgDgDCCBFQB7BAAEABQABAHCwGiQC1GsgEgDQAvFUgGgGQgDgDq9A7QqaA4gjAAIgCAAgAJqlJIAAAAIAAAAIAAAAg");
	mask.setTransform(73.4,179.4);

	// Layer_1
	this.instance = new lib.zebras();
	this.instance.parent = this;

	var maskedShapeInstanceList = [this.instance];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,82.7,174.8,177.3), null);


(lib.pingus = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bb_pingu();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.pingus, new cjs.Rectangle(0,0,300,271), null);


// stage content:
(lib._728x90_zebra = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer_12
	this.instance = new lib.Symbol6();
	this.instance.parent = this;
	this.instance.setTransform(564,-2.9,0.829,0.829,0,0,0,126.2,102.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(295).to({_off:false},0).wait(1).to({regX:88.1,regY:130,x:531.9,y:20.1,alpha:0.033},0).wait(1).to({x:531.3,alpha:0.07},0).wait(1).to({x:530.6,alpha:0.114},0).wait(1).to({x:529.8,alpha:0.164},0).wait(1).to({x:528.9,alpha:0.221},0).wait(1).to({x:527.8,alpha:0.286},0).wait(1).to({x:526.7,alpha:0.357},0).wait(1).to({x:525.5,alpha:0.43},0).wait(1).to({x:524.4,alpha:0.502},0).wait(1).to({x:523.3,alpha:0.569},0).wait(1).to({x:522.3,alpha:0.63},0).wait(1).to({x:521.5,alpha:0.682},0).wait(1).to({x:520.7,alpha:0.728},0).wait(1).to({x:520.1,alpha:0.768},0).wait(1).to({x:519.6,alpha:0.803},0).wait(1).to({x:519.1,alpha:0.833},0).wait(1).to({x:518.7,alpha:0.859},0).wait(1).to({x:518.3,alpha:0.881},0).wait(1).to({x:518,alpha:0.901},0).wait(1).to({x:517.7,alpha:0.918},0).wait(1).to({x:517.5,alpha:0.932},0).wait(1).to({x:517.3,alpha:0.945},0).wait(1).to({x:517.1,alpha:0.956},0).wait(1).to({x:516.9,alpha:0.966},0).wait(1).to({x:516.8,alpha:0.974},0).wait(1).to({x:516.7,alpha:0.98},0).wait(1).to({x:516.6,alpha:0.986},0).wait(1).to({alpha:0.991},0).wait(1).to({x:516.5,alpha:0.994},0).wait(1).to({alpha:0.997},0).wait(1).to({x:516.4,alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:126.2,regY:102.2,x:548,y:-2.9},0).wait(24));

	// Layer_9
	this.instance_1 = new lib.pingus();
	this.instance_1.parent = this;
	this.instance_1.setTransform(420,70,0.299,0.299,0,0,0,150.6,136.4);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(295).to({_off:false},0).wait(1).to({regX:150,regY:135.5,x:419.6,y:69.8,alpha:0.033},0).wait(1).to({x:419.4,alpha:0.07},0).wait(1).to({x:419.2,alpha:0.114},0).wait(1).to({x:419,alpha:0.164},0).wait(1).to({x:418.7,alpha:0.221},0).wait(1).to({x:418.4,alpha:0.286},0).wait(1).to({x:418,alpha:0.357},0).wait(1).to({x:417.7,alpha:0.43},0).wait(1).to({x:417.3,alpha:0.502},0).wait(1).to({x:417,alpha:0.569},0).wait(1).to({x:416.7,alpha:0.63},0).wait(1).to({x:416.4,alpha:0.682},0).wait(1).to({x:416.2,alpha:0.728},0).wait(1).to({x:416,alpha:0.768},0).wait(1).to({x:415.8,alpha:0.803},0).wait(1).to({x:415.6,alpha:0.833},0).wait(1).to({x:415.5,alpha:0.859},0).wait(1).to({x:415.4,alpha:0.881},0).wait(1).to({x:415.3,alpha:0.901},0).wait(1).to({x:415.2,alpha:0.918},0).wait(1).to({x:415.1,alpha:0.932},0).wait(1).to({alpha:0.945},0).wait(1).to({x:415,alpha:0.956},0).wait(1).to({alpha:0.966},0).wait(1).to({x:414.9,alpha:0.974},0).wait(1).to({alpha:0.98},0).wait(1).to({alpha:0.986},0).wait(1).to({x:414.8,alpha:0.991},0).wait(1).to({alpha:0.994},0).wait(1).to({alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:150.6,regY:136.4,x:415,y:70},0).wait(24));

	// Layer_8
	this.instance_2 = new lib.Symbol5();
	this.instance_2.parent = this;
	this.instance_2.setTransform(319.7,83.2,0.18,0.18,0,0,180,113,100.5);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(295).to({_off:false},0).wait(1).to({regX:113.5,regY:99.5,y:83,alpha:0.033},0).wait(1).to({x:319.9,alpha:0.07},0).wait(1).to({x:320.1,alpha:0.114},0).wait(1).to({x:320.4,alpha:0.164},0).wait(1).to({x:320.7,alpha:0.221},0).wait(1).to({x:321,alpha:0.286},0).wait(1).to({x:321.3,alpha:0.357},0).wait(1).to({x:321.7,alpha:0.43},0).wait(1).to({x:322.1,alpha:0.502},0).wait(1).to({x:322.4,alpha:0.569},0).wait(1).to({x:322.7,alpha:0.63},0).wait(1).to({x:323,alpha:0.682},0).wait(1).to({x:323.2,alpha:0.728},0).wait(1).to({x:323.4,alpha:0.768},0).wait(1).to({x:323.6,alpha:0.803},0).wait(1).to({x:323.7,alpha:0.833},0).wait(1).to({x:323.8,alpha:0.859},0).wait(1).to({x:324,alpha:0.881},0).wait(1).to({x:324.1,alpha:0.901},0).wait(1).to({alpha:0.918},0).wait(1).to({x:324.2,alpha:0.932},0).wait(1).to({x:324.3,alpha:0.945},0).wait(1).to({alpha:0.956},0).wait(1).to({x:324.4,alpha:0.966},0).wait(1).to({alpha:0.974},0).wait(1).to({x:324.5,alpha:0.98},0).wait(1).to({alpha:0.986},0).wait(1).to({alpha:0.991},0).wait(1).to({alpha:0.994},0).wait(1).to({alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:113,regY:100.5,x:324.7,y:83.2},0).wait(24));

	// Layer_4
	this.instance_3 = new lib.Symbol2copy();
	this.instance_3.parent = this;
	this.instance_3.setTransform(92.9,35.9,1,1,0,0,0,77.9,14.8);
	this.instance_3.alpha = 0;

	this.instance_4 = new lib.Symbol3();
	this.instance_4.parent = this;
	this.instance_4.setTransform(304,47.6,0.57,0.57,0,0,180,112.9,92.7);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:55.9,alpha:1},29,cjs.Ease.quartOut).to({_off:true},253).wait(70));
	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(295).to({_off:false},0).wait(1).to({regX:113,regY:92.5,x:304.3,y:47.5,alpha:0.033},0).wait(1).to({x:304.7,alpha:0.07},0).wait(1).to({x:305.1,alpha:0.114},0).wait(1).to({x:305.6,alpha:0.164},0).wait(1).to({x:306.2,alpha:0.221},0).wait(1).to({x:306.8,alpha:0.286},0).wait(1).to({x:307.5,alpha:0.357},0).wait(1).to({x:308.2,alpha:0.43},0).wait(1).to({x:309,alpha:0.502},0).wait(1).to({x:309.6,alpha:0.569},0).wait(1).to({x:310.2,alpha:0.63},0).wait(1).to({x:310.8,alpha:0.682},0).wait(1).to({x:311.2,alpha:0.728},0).wait(1).to({x:311.6,alpha:0.768},0).wait(1).to({x:312,alpha:0.803},0).wait(1).to({x:312.3,alpha:0.833},0).wait(1).to({x:312.5,alpha:0.859},0).wait(1).to({x:312.8,alpha:0.881},0).wait(1).to({x:313,alpha:0.901},0).wait(1).to({x:313.1,alpha:0.918},0).wait(1).to({x:313.3,alpha:0.932},0).wait(1).to({x:313.4,alpha:0.945},0).wait(1).to({x:313.5,alpha:0.956},0).wait(1).to({x:313.6,alpha:0.966},0).wait(1).to({x:313.7,alpha:0.974},0).wait(1).to({x:313.8,alpha:0.98},0).wait(1).to({alpha:0.986},0).wait(1).to({x:313.9,alpha:0.991},0).wait(1).to({alpha:0.994},0).wait(1).to({alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({alpha:1},0).wait(1).to({regX:112.9,regY:92.7,x:314,y:47.6},0).wait(24));

	// type2
	this.instance_5 = new lib.Symbol2copy2();
	this.instance_5.parent = this;
	this.instance_5.setTransform(92.9,7.9,1,1,0,0,0,77.9,14.8);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.instance_6 = new lib.Symbol4();
	this.instance_6.parent = this;
	this.instance_6.setTransform(102.2,202.6,1,1,0,0,0,83.2,25.9);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.instance_7 = new lib.Symbol8();
	this.instance_7.parent = this;
	this.instance_7.setTransform(86,221.3,1,1,0,0,0,68,13.7);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(75).to({_off:false},0).to({y:27.9,alpha:1},29,cjs.Ease.quartOut).wait(29).to({y:37.9,alpha:0},10).to({_off:true},1).wait(208));
	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(209).to({_off:false},0).wait(1).to({regX:99.3,regY:-159,x:118.3,y:18.3,alpha:0.053},0).wait(1).to({y:19.1,alpha:0.118},0).wait(1).to({y:20,alpha:0.196},0).wait(1).to({y:21.1,alpha:0.289},0).wait(1).to({y:22.3,alpha:0.391},0).wait(1).to({y:23.6,alpha:0.495},0).wait(1).to({y:24.7,alpha:0.591},0).wait(1).to({y:25.7,alpha:0.674},0).wait(1).to({y:26.6,alpha:0.743},0).wait(1).to({y:27.2,alpha:0.799},0).wait(1).to({y:27.8,alpha:0.845},0).wait(1).to({y:28.2,alpha:0.882},0).wait(1).to({y:28.6,alpha:0.912},0).wait(1).to({y:28.9,alpha:0.937},0).wait(1).to({y:29.1,alpha:0.956},0).wait(1).to({y:29.3,alpha:0.971},0).wait(1).to({y:29.4,alpha:0.982},0).wait(1).to({y:29.5,alpha:0.99},0).wait(1).to({y:29.6,alpha:0.996},0).wait(1).to({alpha:0.999},0).wait(1).to({regX:83.2,regY:25.9,x:102.2,y:214.6,alpha:1},0).wait(42).to({alpha:0},10).to({_off:true},1).wait(69));
	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(334).to({_off:false},0).to({alpha:1},17).wait(1));

	// type
	this.instance_8 = new lib.Symbol2();
	this.instance_8.parent = this;
	this.instance_8.setTransform(92.9,7.9,1,1,0,0,0,77.9,14.8);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.instance_9 = new lib.Symbol2copy4();
	this.instance_9.parent = this;
	this.instance_9.setTransform(92.9,7.9,1,1,0,0,0,77.9,14.8);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.instance_10 = new lib.Symbol7();
	this.instance_10.parent = this;
	this.instance_10.setTransform(113.7,39.1,1,1,0,0,0,99.9,36.4);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(4).to({_off:false},0).to({y:27.9,alpha:1},29,cjs.Ease.quartOut).wait(32).to({y:37.9,alpha:0},10).to({_off:true},1).wait(276));
	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(143).to({_off:false},0).to({y:27.9,alpha:1},29,cjs.Ease.quartOut).wait(27).to({y:37.9,alpha:0},10).to({_off:true},2).wait(141));
	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(310).to({_off:false},0).wait(1).to({regX:121.5,regY:36.5,x:135.3,y:39.6,alpha:0.046},0).wait(1).to({y:40.1,alpha:0.1},0).wait(1).to({y:40.8,alpha:0.163},0).wait(1).to({y:41.5,alpha:0.237},0).wait(1).to({y:42.3,alpha:0.32},0).wait(1).to({y:43.2,alpha:0.407},0).wait(1).to({y:44.1,alpha:0.495},0).wait(1).to({y:44.9,alpha:0.578},0).wait(1).to({y:45.7,alpha:0.651},0).wait(1).to({y:46.3,alpha:0.715},0).wait(1).to({y:46.8,alpha:0.769},0).wait(1).to({y:47.3,alpha:0.815},0).wait(1).to({y:47.7,alpha:0.853},0).wait(1).to({y:48,alpha:0.885},0).wait(1).to({y:48.3,alpha:0.911},0).wait(1).to({y:48.5,alpha:0.933},0).wait(1).to({y:48.7,alpha:0.951},0).wait(1).to({y:48.8,alpha:0.966},0).wait(1).to({y:48.9,alpha:0.977},0).wait(1).to({y:49,alpha:0.986},0).wait(1).to({y:49.1,alpha:0.992},0).wait(1).to({alpha:0.997},0).wait(1).to({alpha:0.999},0).wait(1).to({regX:99.9,regY:36.4,x:113.7,alpha:1},0).wait(18));

	// Layer_7
	this.instance_11 = new lib.Symbol3();
	this.instance_11.parent = this;
	this.instance_11.setTransform(435.7,17.8,1,1,0,0,0,113,92.5);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(141).to({_off:false},0).to({x:431.7,y:21.8,alpha:1},19).to({x:428.7,y:25.8},40).to({x:425.7,y:29.8,alpha:0},16).to({_off:true},1).wait(135));

	// Layer_6
	this.instance_12 = new lib.pingus();
	this.instance_12.parent = this;
	this.instance_12.setTransform(357.3,75.4,0.7,0.7,0,0,0,150.2,135.6);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.instance_13 = new lib.Symbol5();
	this.instance_13.parent = this;
	this.instance_13.setTransform(450.4,67.5,1,1,0,0,0,113.5,99.5);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(71).to({_off:false},0).to({x:362.3,y:82.4,alpha:1},19).to({x:368.3,y:94.4},36).to({x:371.3,y:101.4,alpha:0},17).to({_off:true},2).wait(207));
	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(214).to({_off:false},0).to({x:445.4,alpha:1},22).to({x:438.4},40).to({x:431.4,alpha:0},19).to({_off:true},34).wait(23));

	// animals copy
	this.instance_14 = new lib.Symbol1copy();
	this.instance_14.parent = this;
	this.instance_14.setTransform(621.1,49.4,0.987,0.987,0,0,0,126,102.1);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).to({x:611.1,alpha:1},21).to({x:606.1},32).to({x:601.1,alpha:0},21).to({_off:true},1).wait(277));

	// animals
	this.instance_15 = new lib.Symbol1();
	this.instance_15.parent = this;
	this.instance_15.setTransform(568.1,3.2,0.987,0.987,0,0,0,126,102.1);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({x:556.1,y:5.2,alpha:1},21).to({x:551.1},32).to({x:546.1,alpha:0},21).to({_off:true},1).wait(277));

	// bg
	this.instance_16 = new lib.bb_bg();
	this.instance_16.parent = this;
	this.instance_16.setTransform(0,-1,2.44,0.648);

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(352));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(364,-52.6,767.1,302.8);
// library properties:
lib.properties = {
	id: '0267BCEF7A554799BD8E2A3CB4CDA28B',
	width: 728,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/728x90_zebra_atlas_.png", id:"728x90_zebra_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0267BCEF7A554799BD8E2A3CB4CDA28B'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;